= Configuración de Alertmanager
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/guías-de-usuario-avanzadas/monitoring-v2-guías-de-configuración/configuración-avanzada/alertmanager.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

Por lo general, no es necesario editar directamente el recurso personalizado de Alertmanager. Para la mayoría de los casos de uso, solo necesitaréis editar los Receptores y Rutas para configurar las notificaciones.

Cuando se actualizan los Receptores y Rutas, la aplicación de monitoreo actualizará automáticamente el recurso personalizado de Alertmanager para que sea coherente con esos cambios.

[NOTE]
====

Esta sección asume familiaridad con el funcionamiento conjunto de los componentes de monitoreo. Para más información sobre Alertmanager, consulta {xref-how-monitoring-works}#_3_how_alertmanager_works[esta sección.]
====


[#_about_the_alertmanager_custom_resource]
== Acerca del Recurso Personalizado de Alertmanager

Por defecto, Rancher Monitoring despliega un único Alertmanager en un clúster que utiliza un secreto de configuración de Alertmanager por defecto.

Puede que queráis editar el recurso personalizado de Alertmanager si deseáis aprovechar opciones avanzadas que no están expuestas en los formularios de la interfaz de usuario de Rancher, como la capacidad de crear una estructura de árbol de enrutamiento que tenga más de dos niveles de profundidad.

También es posible crear más de un Alertmanager en un clúster, lo que puede ser útil si queréis implementar monitoreo con alcance de espacio de nombres. En este caso, debéis gestionar los recursos personalizados de Alertmanager utilizando el mismo secreto de configuración de Alertmanager subyacente.

[#_deeply_nested_routes]
=== Rutas Profundamente Anidadas

Mientras que la interfaz de usuario de Rancher solo admite un árbol de enrutamiento que tiene dos niveles de profundidad, podéis configurar estructuras de enrutamiento más profundamente anidadas editando el YAML de Alertmanager.

[#_multiple_alertmanager_replicas]
=== Multiple Alertmanager Replicas

Como parte de las opciones de despliegue del Helm Chart, puedes optar por aumentar el número de réplicas del Alertmanager desplegado en tu clúster. Las réplicas pueden ser gestionadas utilizando el mismo secreto de configuración de Alertmanager subyacente.

Este Secreto debe ser actualizado o modificado cada vez que queráis:

* Añadir nuevos notificadores o receptores
* Cambiar las alertas que deben ser enviadas a notificadores o receptores específicos
* Cambiar el grupo de alertas que se envían

Por defecto, podéis elegir proporcionar un secreto de configuración de Alertmanager existente (es decir, cualquier Secreto en el espacio de nombres `cattle-monitoring-system`) o permitir que Rancher Monitoring despliegue un secreto de configuración de Alertmanager por defecto en vuestro clúster.

Por defecto, el secreto de configuración de Alertmanager creado por Rancher nunca será modificado o eliminado en una actualización de versión o desinstalación del chart `rancher-monitoring`. Esta restricción impide que los usuarios pierdan o sobrescriban su configuración de alertas al ejecutar operaciones en el chart.

Para más información sobre qué campos se pueden especificar en el secreto de configuración de Alertmanager, por favor, consulta la https://prometheus.io/docs/alerting/latest/alertmanager/[documentación de Prometheus Alertmanager.]

La especificación completa del archivo de configuración de Alertmanager y lo que requiere se puede encontrar https://prometheus.io/docs/alerting/latest/configuration/#configuration-file[aquí.]
