= Configurando PrometheusRules
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/guías-avanzadas-de-usuario/monitoring-v2-guías-de-configuración/configuración-avanzada/prometheusrules.adoc 
:product-path: observabilidad/monitoring-and-dashboards/configuración/advanced/prometheusrules.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-promql-expressions: xref:observability/monitoring-and-dashboards/promql-expressions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-promql-expressions: xref:integrations-in-rancher/monitoring-and-alerting/promql-expressions.adoc
endif::[]

Una PrometheusRule define un grupo de reglas de alerta y/o grabación de Prometheus.

[NOTE]
====

Esta sección asume familiaridad con el funcionamiento conjunto de los componentes de monitoreo. Para más información, consulte {xref-how-monitoring-works}[esta sección.]
====


[#_creating_prometheusrules_in_the_rancher_ui]
== Creando PrometheusRules en la interfaz de usuario de Rancher

[NOTE]
.Requisito previo:
====

La aplicación de monitorización necesita estar instalada.
====


Para crear grupos de reglas en la interfaz de usuario de Rancher,

. Ve al clúster donde deseas crear grupos de reglas. Haz clic en menu:Monitorización[Avanzado] y haz clic en *Reglas de Prometheus*.
. Haga clic en *Crear*.
. Introduce un *Nombre del Grupo*.
. Configura las reglas. En la interfaz de usuario de Rancher, esperamos que un grupo de reglas contenga ya sea reglas de alerta o reglas de grabación, pero no ambas. Para obtener ayuda para completar los formularios, consulta las opciones de configuración a continuación.
. Haga clic en *Crear*.

*Resultado:* Las alertas se pueden configurar para enviar notificaciones a los receptores.

[#_about_the_prometheusrule_custom_resource]
== Acerca del recurso personalizado PrometheusRule

Cuando defines una regla (que se declara dentro de un RuleGroup en un recurso PrometheusRule), la https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#rule[especificación de la regla en sí] contiene etiquetas que son utilizadas por Alertmanager para determinar qué ruta debe recibir esta alerta. Por ejemplo, una alerta con la etiqueta `team: front-end` se enviará a todas las rutas que coincidan con esa etiqueta.

Los archivos de reglas de Prometheus se mantienen en recursos personalizados de PrometheusRule. Un PrometheusRule permite definir uno o más RuleGroups. Cada RuleGroup consiste en un conjunto de objetos Rule que pueden representar reglas de alerta o reglas de grabación con los siguientes campos:

* El nombre de la nueva alerta o registro.
* Una expresión PromQL para la nueva alerta o registro.
* Etiquetas que deben adjuntarse a la alerta o al registro para identificarlos (por ejemplo, nombre del clúster o severidad).
* Anotaciones que codifican cualquier pieza adicional de información importante que necesita mostrarse en la notificación de una alerta (por ejemplo, resumen, descripción, mensaje, URL del runbook, etc.). Este campo no es obligatorio para las reglas de grabación.

Para más información sobre qué campos se pueden especificar, consulta la https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#prometheusrulespec[especificación de Prometheus Operator.]

Utiliza el campo de selector de etiquetas `ruleSelector` en el objeto Prometheus para definir los archivos de reglas que deseas que se monten en Prometheus.

Para ejemplos, consulta la documentación de Prometheus sobre https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/[reglas de grabación] y https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[reglas de alerta.]

[#_configuration]
== Configuración

[#_rule_group]
=== Grupo de reglas

|===
| Campo | Descripción

| Nombre de grupo
| El nombre del grupo. Debe ser único dentro de un archivo de reglas.

| Intervalo de anulación del grupo
| Duración en segundos para la frecuencia con la que se evalúan las reglas en el grupo.
|===

[#_alerting_rules]
=== Reglas de alerta

https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[Las reglas de alerta] te permiten definir condiciones de alerta basadas en expresiones de PromQL (Lenguaje de Consulta de Prometheus) y enviar notificaciones sobre alertas activadas a un servicio externo.

|===
| Campo | Descripción

| Nombre de la alerta
| El nombre de la alerta. Debe ser un valor de etiqueta válido.

| Esperar para activar durante
| Duración en segundos. Las alertas se consideran activadas una vez que han estado en ese estado durante este tiempo. Las alertas que aún no se han activado durante el tiempo suficiente se consideran pendientes.

| Expresión PromQL
| La expresión PromQL a evaluar. Prometheus evaluará el valor actual de esta expresión PromQL en cada ciclo de evaluación y todas las series temporales resultantes se convertirán en alertas pendientes/activadas. Para más información, consulta la https://prometheus.io/docs/prometheus/latest/querying/basics/[documentación de Prometheus] o nuestros {xref-promql-expressions}[ejemplos de expresiones PromQL.]

| Etiquetas
| Etiquetas para añadir o sobrescribir para cada alerta.

| Gravedad
| Cuando está habilitado, se adjuntan etiquetas a la alerta o registro que la identifican por el nivel de severidad.

| Valor de la etiqueta de severidad
| Crítico, advertencia o ninguno

| Anotaciones
| Las anotaciones son un conjunto de etiquetas informativas que se pueden utilizar para almacenar información adicional más extensa, como descripciones de alertas o enlaces a runbooks. Un https://en.wikipedia.org/wiki/Runbook[runbook] es un conjunto de documentación sobre cómo manejar alertas. Los valores de anotación pueden definirse mediante https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating[plantillas.]
|===

[#_recording_rules]
=== Reglas de grabación

Las https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules[reglas de grabación] te permiten precomputar expresiones de PromQL (Lenguaje de Consulta de Prometheus) que se necesitan con frecuencia o que son computacionalmente costosas y guardar su resultado como un nuevo conjunto de series temporales.

|===
| Campo | Descripción

| Nombre de la serie temporal
| El nombre de la serie temporal a la que se debe enviar la salida. Debe ser un nombre de métrica válido.

| Expresión PromQL
| La expresión PromQL a evaluar. Prometheus evaluará el valor actual de esta expresión de PromQL en cada ciclo de evaluación y el resultado se registrará como un nuevo conjunto de series temporales con el nombre de métrica dado por 'record'.  Para más información sobre expresiones, consulta la https://prometheus.io/docs/prometheus/latest/querying/basics/[documentación de Prometheus] o nuestros {xref-promql-expressions}[ejemplos de expresiones PromQL.]

| Etiquetas
| Etiquetas para añadir o sobrescribir antes de almacenar el resultado.
|===
