= 功能开关
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-27
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/installation-references/feature-flags.adoc 
:product-path: installation-and-upgrade/references/feature-flags.adoc
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-cluster-project-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/cluster-and-project-roles.adoc
:xref-harvester-overview: xref:integrations/harvester/overview.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-fleet: xref:integrations/fleet/fleet.adoc
:xref-unsupported-storage-drivers: xref:rancher-admin/experimental-features/unsupported-storage-drivers.adoc
:xref-role-template-aggregation: xref:rancher-admin/experimental-features/role-template-aggregation.adoc
:xref-istio-traffic-management: xref:rancher-admin/experimental-features/istio-traffic-management-features.adoc
:xref-ui-server-side-pagination: xref:rancher-admin/global-configuration/ui-server-side-pagination.adoc
:xref-continuous-delivery: xref:rancher-admin/experimental-features/continuous-delivery.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-cluster-project-roles: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles.adoc
:xref-harvester-overview: xref:integrations-in-rancher/harvester/overview.adoc
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
:xref-fleet: xref:integrations-in-rancher/fleet/index.adoc
:xref-unsupported-storage-drivers: xref:how-to-guides/advanced-user-guides/enable-experimental-features/unsupported-storage-drivers.adoc
:xref-role-template-aggregation: xref:how-to-guides/advanced-user-guides/enable-experimental-features/role-template-aggregation.adoc
:xref-istio-traffic-management: xref:how-to-guides/advanced-user-guides/enable-experimental-features/istio-traffic-management-features.adoc
:xref-ui-server-side-pagination: xref:how-to-guides/advanced-user-guides/ui-server-side-pagination.adoc
:xref-continuous-delivery: xref:how-to-guides/advanced-user-guides/enable-experimental-features/continuous-delivery.adoc
endif::[]

通过功能开关，您可以尝试可选或实验性功能，并启用正在逐步淘汰的遗留功能。

要了解有关功能值及如何启用它们的更多信息，请参见 {xref-experimental-features}[启用实验性功能]。

[NOTE]
====
某些功能开关需要重启 Rancher 容器。需要重启的功能开关在 Rancher UI 中被标记。
====


以下是 Rancher 中可用的功能开关列表。如果您从以前的 Rancher 版本升级，您可能会在 Rancher UI 中看到额外的功能开关，例如 `proxy` 或 `dashboard`（均为 xref:[已停用]）：

* `aggregated-roletemplates`：对 RoleTemplates、ProjectRoleTemplateBindings 和 ClusterRoleTemplateBindings 使用集群角色聚合架构。有关更多信息，请参见 {xref-role-template-aggregation}[RoleTemplate 聚合]。
* `clean-stale-secrets`：从 `cattle-impersonation-system` 名称空间中移除过期的密钥。这会慢慢清理不再被模拟系统使用的旧密钥。
* `continuous-delivery`：允许单独禁用 Fleet GitOps。有关更多信息，请参见 {xref-continuous-delivery}[持续交付。]。
* `fleet`：v2.6 及更高版本中的 Rancher 供应框架需要 Fleet。当您升级时，该功能开关将自动启用，即使您在早期版本的 Rancher 中禁用了它。有关更多信息，请参见 {xref-fleet}[与 Fleet 的持续交付]。
* `harvester`：管理对虚拟化管理页面的访问，用户可以直接导航到 Harvester 集群并访问 Harvester UI。有关更多信息，请参见 {xref-harvester-overview}[{harvester-product-name} 集成概述]。
* `imperative-api-extension`：启用 Rancher 的 https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/[扩展 API 服务器] 以向 Kubernetes 注册新 API。此开关默认情况下启用。有关更多信息，请参见 xref:api/extension-apiserver.adoc[扩展 API 服务器] 页面。
* `istio-virtual-service-ui`：启用一个 {xref-istio-traffic-management}[可视化界面] 来创建、读取、更新和删除 Istio 虚拟服务和目标规则，这些都是 Istio 流量管理功能。
* `legacy`：启用 2.5.x 及更早版本的一组功能，这些功能正在逐渐被新的实现所取代。这些功能混合了已弃用的功能以及最终将可用于新版本的功能。在新的 Rancher 安装中，该功能开关默认禁用。如果您是从之前的 Rancher 版本升级，则该功能开关启用。
* `managed-system-upgrade-controller`：启用在下游导入的 RKE2/K3s 集群中安装 system-upgrade-controller APP，以及在本地群集中（如果它是 RKE2/K3s 集群）。

[IMPORTANT]
====
该 `managed-system-upgrade-controller` 功能开关仅供 **内部使用**，并没有关联的功能 CR。使用此选项时要特别小心。

要控制 Rancher 是否应管理导入的 RKE2/K3s 集群的 Kubernetes 版本，建议使用 Rancher v2.11.0 或更高版本中提供的 {xref-register-clusters}#_configuring_version_management_for_rke2_and_k3s_clusters[导入集群版本管理] 功能。
====

[WARNING]
====
如果在 Rancher v2.10.x 中 `managed-system-upgrade-controller` 功能开关被 **禁用**，并且任何导入的 RKE2/K3s 集群在 **Rancher 之外** 升级，请按照以下步骤操作，以防止意外安装 system-upgrade-controller APP，并确保 {xref-register-clusters}#_configuring_version_management_for_rke2_and_k3s_clusters[导入集群版本管理] 功能正常工作：

. 将 Rancher 升级到 v2.11.0 或更高版本，确保在 v2.10.x 安装期间如果设置了 **保留** `managed-system-upgrade-controller=false` 功能开关，则在 Helm 值中保留该开关。
. 在 Rancher 完全运行后，禁用 `imported-cluster-version-management` 设置。您可以通过 Rancher UI 点击 **☰ > 全局设置 > 设置 > 导入集群版本管理** 来执行此操作，或者通过 kubectl 编辑相应的 `Setting.management.cattle.io/v3` 自定义资源。
. 执行第二次 Helm 升级，这次省略 `managed-system-upgrade-controller=false` 功能开关。

现在，导入集群版本管理默认情况下是禁用的，Rancher 不再自动在导入的集群上安装 system-upgrade-controller APP。

您可以按集群启用此功能。有关更多信息，请参阅 {xref-register-clusters}#_configuring_version_management_for_rke2_and_k3s_clusters[文档]。
====

* `multi-cluster-management`：允许对 Kubernetes 集群进行多集群的配置和管理。该功能开关只能在安装时设置。该功能开关之后无法启用或禁用。
* `rke2`：启用 RKE2 集群的配置。该功能开关默认启用。
* `token-hashing`：启用词元哈希。一旦启用，现有词元将被哈希，所有新词元将自动使用 SHA256 算法进行哈希。一旦词元被哈希，无法撤销。该功能开关在启用后无法禁用。有关更多信息，请参见 xref:api/api-tokens.adoc#_token_hashing[API 词元]。
* `uiextension`：启用 UI 扩展。该功能开关默认启用。启用或禁用该功能开关会强制重启 Rancher pod。第一次将该功能开关设置为 `Active` 时，会创建一个 CRD，并启用该功能所需的控制器和端点。如果将该功能开关设置为 `Disabled`，则会禁用前面提到的控制器和端点。将 `uiextension` 设置为 `Disabled` 对 CRD -- 没有影响，如果 CRD 尚不存在，则不会创建 CRD，也不会删除已存在的 CRD。* `unsupported-storage-drivers`:启用默认未启用的存储提供者和配置器的类型。有关更多信息，请参见 {xref-unsupported-storage-drivers}[允许不受支持的存储驱动程序]。
* `ui-sql-cache`：为 UI 表格和服务器端分页启用基于 SQLite 的缓存。有关更多信息，请参见 {xref-ui-server-side-pagination}[UI 服务器端分页]。

下表显示了 Rancher 中某些功能开关的可用性和默认值。标记为 "GA" 的功能开关是一般可用的：

|===
| 功能开关名称 | 默认值 | 状态 | 可用版本 | 附加信息

| `aggregated-roletemplates`
| `Disabled`
| 实验性
| v2.11.0
| 该功能开关的值在安装时被锁定，且无法更改。

| `clean-stale-secrets`
| `Active`
| GA
| v2.11.0
|

| `continuous-delivery`
| `Active`
| GA
| v2.6.0
|

| `external-rules`
| v2.7.14: `Disabled`, v2.8.5: `Active`
| 已去除
| v2.7.14, v2.8.5
| 该功能开关影响 {xref-cluster-project-roles}#_external_roletemplate_behavior[external `RoleTemplate` behavior].在 Rancher v2.9.0 及更高版本中已去除，因为该行为默认启用。

| `fleet`
| `Active`
| 该功能开关无法再禁用。
| v2.6.0
|

| `fleet`
| `Active`
| GA
| v2.5.0
|

| `harvester`
| `Active`
| 实验性
| v2.6.1
|

| `imperative-api-extension`
| `Active`
| GA
| v2.11.0
|

| `legacy`
| 新安装为 `false`，升级为 `true`
| GA
| v2.6.0
|

| `managed-system-upgrade-controller`
| `true`
| GA
| v2.10.0
|

| `rke2`
| `true`
| 实验性
| v2.6.0
|

| `token-hashing`
| 新安装为 `Disabled`，升级为 `Active`
| GA
| v2.6.0
|

| `uiextension`
| `Active`
| GA
| v2.9.0
|

| `ui-sql-cache`
| `Active`
| GA
| v2.9.0
|
|===
