= Monitoring and Dashboards
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/index.adoc 
:product-path: observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:description: Prometheus lets you view metrics from your different Rancher and Kubernetes objects. Learn about the scope of monitoring and how to enable cluster monitoring
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
:xref-configure-alertmanager: xref:observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:observability/monitoring-and-dashboards/configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:observability/monitoring-and-dashboards/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheusrules.adoc
:xref-prometheus: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
:xref-enable-monitoring: xref:observability/monitoring-and-dashboards/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/create-persistent-grafana-dashboard.adoc
:xref-servicemonitors-and-podmonitors: xref:observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:observability/monitoring-and-dashboards/configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:observability/monitoring-and-dashboards/configuration/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:observability/monitoring-and-dashboards/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:observability/monitoring-and-dashboards/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:observability/monitoring-and-dashboards/windows-support.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
:xref-configure-alertmanager: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:reference-guides/monitoring-v2-configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheusrules.adoc
:xref-prometheus: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc
:xref-enable-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard.adoc
:xref-servicemonitors-and-podmonitors: xref:reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:reference-guides/monitoring-v2-configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:integrations-in-rancher/monitoring-and-alerting/windows-support.adoc
endif::[]

[#_monitoring_dashboards]
== Monitoring Dashboards

The Monitoring Dashboards chart provides standalone dashboard functionality for `rancher-monitoring`:

* *No Bundled Runtime*: Operates without depending on Rancher's shipped `kube-prometheus-stack` images or components.
* *Prerequisite*: Requires an existing Prometheus infrastructure to already be in place. While several configurations are possible, installing `kube-prometheus-stack` is the simplest method. 

=== Monitoring Dashboards Installation

This section guides you through installing the `monitoring-dashboards` chart and integrating it with your Prometheus stack.

Before installing the `monitoring-dashboards` chart, you must first set up the underlying monitoring infrastructure using the https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack[`kube-prometheus-stack`] chart:

. Add the https://github.com/prometheus-community/helm-charts[prometheus-community] Helm repository to access the `kube-prometheus-stack` chart. You can do this through the Rancher UI or using the Helm CLI with the following command.
+
[,shell]
----
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
----

. Create the `kube-prometheus-stack` `values.yaml` file. Configure the file with the following required settings to ensure `kube-prometheus-stack` integrates properly and supports embedded dashboards in `monitoring-dashboards`.
+
[,yaml]
----
grafana:
  # NOTE: Do NOT set root_url or serve_from_sub_path here
  grafana.ini:
    security:
      allow_embedding: true
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: true
      org_role: Viewer
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/rancher-default-home.json
    users:
      auto_assign_org_role: Viewer

# Prometheus configuration to pick up all ServiceMonitors
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

# No metric exporter by default
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
----
+
[IMPORTANT]
====
By default, the monitoring-dashboards chart does not enable metric scraping for `kubeEtcd`, `kubeControllerManager`, `kubeScheduler`, or `kubeProxy`. To export metrics from these components, you must configure https://github.com/prometheus-community/PushProx[PushProx].
====

. Install the `kube-prometheus-stack` chart in the `cattle-monitoring-system` namespace via the Rancher UI or Helm CLI, applying the `values.yaml` file from the previous step:
+
[,shell]
----
helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
  --namespace cattle-monitoring-system \
  --create-namespace \
  --debug \
  --wait \
  -f values.yaml
----

. With the monitoring infrastructure installed, you can now deploy the `rancher-monitoring-dashboards` chart from the Apps tab in the Rancher UI.

=== Customization and Overrides

==== Monitoring Proxy Image Customization

A single NGINX pod (`monitoringProxy`) acts as a proxy for Grafana, Prometheus, and Alertmanager, ensuring the Kubernetes API server’s service proxy (used by the Rancher UI) can reach them reliably. You can customize the NGINX image using the following configuration:

[,yaml]
----
monitoringProxy:
  image:
    repository: <new/image>
    tag: <version>
----

==== Service Name Overrides

The default `values.yaml` assumes standard service naming conventions (for example, kube-prometheus-stack-<application>), as shown below:

[,yaml]
----
grafanaProxy:
  upstreamService: kube-prometheus-stack-grafana

prometheusProxy:
  upstreamService: kube-prometheus-stack-prometheus

alertmanagerProxy:
  upstreamService: kube-prometheus-stack-alertmanager
----

This creates mirror services alongside the new chart, which the reverse proxy uses to enable Rancher UI functionality. If you modified the service names during installation, update the `upstreamService` configuration accordingly:

[,yaml]
----
grafanaProxy:
  upstreamService: <upstream_service_name>

prometheusProxy:
  upstreamService: <upstream_service_name>

alertmanagerProxy:
  upstreamService: <upstream_service_name>
----

[NOTE]
====
Make sure to disable `k3sServer` if you are not using `k3s`:

[,yaml]
----
k3sServer:
  enabled: false
----
====

==== Project Monitoring Container Image Customization

To use custom container images for Prometheus, Alertmanager, or Grafana with `prometheus-federator`, apply the following overrides in your `helmProjectOperator` configuration:

[,yaml]
----
helmProjectOperator:
  valuesOverride:
    prometheus:
      prometheusSpec:
        image:
          repository: <custom_repo>
          tag: <custom_tag>
    alertmanager:
      alertmanagerSpec:
        image:
          repository: <custom_repo>
          tag: <custom_tag>
    grafana:
      image:
        repository: <custom_repo>
        tag: <custom_tag>
----

=== Migrating from `rancher-monitoring` to `rancher-monitoring-dashboards`

// Update formatting 

To migrate to `rancher-monitoring-dashboards`, uninstall the `rancher-monitoring` chart, deploy your own `kube-prometheus-stack` (see the installation guide above), and then install `rancher-monitoring-dashboards`. If you need to preserve or migrate existing data, refer to the official Grafana and Prometheus documentation:

* https://grafana.com/docs/grafana/latest/administration/back-up-grafana/[Grafana | Back up Grafana]
* https://prometheus.io/docs/prometheus/latest/querying/api/#snapshot[Prometheus | TSDB Admin APIs - Snapshot]
* https://prometheus.io/docs/prometheus/latest/storage/[Prometheus | Storage]

[#_rancher_monitoring]
== Rancher Monitoring

The `rancher-monitoring` application can quickly deploy leading open-source monitoring and alerting solutions onto your cluster.

Introduced in Rancher v2.5, the application is powered by https://prometheus.io/[Prometheus], https://grafana.com/grafana/[Grafana],  https://prometheus.io/docs/alerting/latest/alertmanager/[Alertmanager], the https://github.com/prometheus-operator/prometheus-operator[Prometheus Operator], and the https://github.com/DirectXMan12/k8s-prometheus-adapter[Prometheus adapter.]

For information on V1 monitoring and alerting, available in Rancher v2.2 up to v2.4, please see the Rancher v2.0--v2.4 docs on xref:[cluster monitoring], xref:[alerting], xref:[notifiers] and other xref:[tools].

Using the `rancher-monitoring` application, you can quickly deploy leading open-source monitoring and alerting solutions onto your cluster.

[#_features]
=== Features

Prometheus lets you view metrics from your Rancher and Kubernetes objects. Using timestamps, Prometheus lets you query and view these metrics in easy-to-read graphs and visuals, either through the Rancher UI or Grafana, which is an analytics viewing platform deployed along with Prometheus.

By viewing data that Prometheus scrapes from your cluster control plane, nodes, and deployments, you can stay on top of everything happening in your cluster. You can then use these analytics to better run your organization: stop system emergencies before they start, develop maintenance strategies, or restore crashed servers.

The monitoring application:

* Monitors the state and processes of your cluster nodes, Kubernetes components, and software deployments.
* Defines alerts based on metrics collected via Prometheus.
* Creates custom Grafana dashboards.
* Configures alert-based notifications via email, Slack, PagerDuty, etc. using Prometheus Alertmanager.
* Defines precomputed, frequently needed or computationally expensive expressions as new time series based on metrics collected via Prometheus.
* Exposes collected metrics from Prometheus to the Kubernetes Custom Metrics API via Prometheus Adapter for use in HPA.

See {xref-how-monitoring-works}[How Monitoring Works] for an explanation of how the monitoring components work together.

[#_default_components_and_deployments]
== Default Components and Deployments

[#_built_in_dashboards]
=== Built-in Dashboards

By default, the monitoring application deploys Grafana dashboards (curated by the https://github.com/prometheus-operator/kube-prometheus[kube-prometheus] project) onto a cluster.

It also deploys an Alertmanager UI and a Prometheus UI. For more information about these tools, see {xref-monitoring-builtin-dashboards}[Built-in Dashboards.]

[#_default_metrics_exporters]
=== Default Metrics Exporters

By default, Rancher Monitoring deploys exporters (such as https://github.com/prometheus/node_exporter[node-exporter] and https://github.com/kubernetes/kube-state-metrics[kube-state-metrics]).

These default exporters automatically scrape metrics for CPU and memory from all components of your Kubernetes cluster, including your workloads.

[#_default_alerts]
=== Default Alerts

The monitoring application deploys some alerts by default. To see the default alerts, go to the xref:./built-in-dashboards.adoc#_alertmanager_ui[Alertmanager UI] and click *Expand all groups.*

[#_components_exposed_in_the_rancher_ui]
=== Components Exposed in the Rancher UI

For a list of monitoring components exposed in the Rancher UI, along with common use cases for editing them, see xref:./how-monitoring-works.adoc#_components_exposed_in_the_rancher_ui[this section.]

[#_role_based_access_control]
== Role-based Access Control

For more information on configuring access to monitoring, see {xref-rancher-monitoring-rbac}[this page.]

[NOTE]
====

Rancher and Project read permissions don't necessarily apply to monitoring resources. See xref:./rbac-for-monitoring.adoc#_additional_monitoring_clusterroles[monitoring-ui-view] for more details.
====


[#_guides]
== Guides

* {xref-enable-monitoring}[Enable monitoring]
* {xref-monitoring-uninstall}[Uninstall monitoring]
* {xref-rancher-workload-monitoring}[Monitoring workloads]
* {xref-customize-grafana-dashboard}[Customizing Grafana dashboards]
* {xref-create-persistent-grafana-dashboard}[Persistent Grafana dashboards]
* {xref-monitoring-debug-high-memory}[Debugging high memory usage]

[#_configuration]
== Configuration

[#_configuring_monitoring_resources_in_rancher]
=== Configuring Monitoring Resources in Rancher

The configuration reference assumes familiarity with how monitoring components work together. For more information, see {xref-how-monitoring-works}[How Monitoring Works.]

* {xref-servicemonitors-and-podmonitors}[ServiceMonitor and PodMonitor]
* {xref-receivers}[Receiver]
* {xref-monitoring-routes}[Route]
* {xref-prometheusrules}[PrometheusRule]
* {xref-prometheus}[Prometheus]
* {xref-configure-alertmanager}[Alertmanager]

[#_configuring_helm_chart_options]
=== Configuring Helm Chart Options

For more information on `rancher-monitoring` chart options, including options to set resource limits and requests, see {xref-monitoring-helm-chart-options}[Helm Chart Options].

[#_windows_cluster_support]
== Windows Cluster Support

To be able to fully deploy Monitoring V2 for Windows, all of your Windows hosts must have a minimum https://github.com/rancher/wins[wins] version of v0.1.0.

For more details on how to upgrade wins on existing Windows hosts, see {xref-monitoring-windows}[Windows cluster support for Monitoring V2.].

[#_known_issues]
== Known Issues

There is a https://github.com/rancher/rancher/issues/28787#issuecomment-693611821[known issue] that K3s clusters require more than the allotted default memory. If you enable monitoring on a K3s cluster, set `prometheus.prometheusSpec.resources.memory.limit` to 2500 Mi and `prometheus.prometheusSpec.resources.memory.request` to 1750 Mi.

See {xref-monitoring-debug-high-memory}[Debugging High Memory Usage] for advice and recommendations.
