= Vorlagen anwenden
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/vorlagen-anwenden.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/apply-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-access-share-rke1-templates: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/zugriff-oder-teilen-von-vorlagen.adoc
:xref-manage-rke1-templates: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/rke1-vorlagen-verwalten.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

Sie können einen Cluster aus einer RKE-Vorlage erstellen, die Sie erstellt haben, oder aus einer Vorlage, die {xref-access-share-rke1-templates}[mit Ihnen geteilt wurde.]

RKE-Vorlagen können auf neue Cluster angewendet werden.

Sie können <<_converting_an_existing_cluster_to_use_an_rke_template,die Konfiguration eines bestehenden Clusters als RKE-Vorlage speichern.>> Dann können die Einstellungen des Clusters nur geändert werden, wenn die Vorlage aktualisiert wird.

Sie können einen Cluster nicht ändern, um eine andere RKE-Vorlage zu verwenden. Sie können den Cluster nur auf eine neue Revision derselben Vorlage aktualisieren.

[#_creating_a_cluster_from_an_rke_template]
== Einen Cluster aus einer RKE-Vorlage erstellen

Um einen Cluster {xref-launch-k8s-with-rancher}[der von einem Infrastruktur-Anbieter gehostet wird] mithilfe einer RKE-Vorlage hinzuzufügen, verwenden Sie diese Schritte:

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Auf der Seite *Cluster* klicken Sie auf *Erstellen* und wählen Sie den Infrastruktur-Anbieter aus.
. Geben Sie den Clusternamen und die Details der Knotenvorlage wie gewohnt an.
. Um eine RKE-Vorlage zu verwenden, aktivieren Sie unter *Clusteroptionen* das Kästchen für *Eine vorhandene RKE-Vorlage und Revision verwenden*.
. Wählen Sie eine RKE-Vorlage und Revision aus dem Dropdown-Menü aus.
. Optional: Sie können alle Einstellungen bearbeiten, die der Eigentümer der RKE-Vorlage als *Benutzerüberschreibung zulassen* markiert hat, als die Vorlage erstellt wurde. Wenn es Einstellungen gibt, die Sie ändern möchten, aber nicht die Möglichkeit dazu haben, müssen Sie den Vorlageninhaber kontaktieren, um eine neue Revision der Vorlage zu erhalten. Dann müssen Sie den Cluster bearbeiten, um ihn auf die neue Revision zu aktualisieren.
. Klicken Sie *Erstellen*, um den Cluster zu starten.

[#_updating_a_cluster_created_with_an_rke_template]
== Aktualisierung eines Clusters, das mit einer RKE-Vorlage erstellt wurde

Wenn der Vorlageninhaber eine Vorlage erstellt, hat jede Einstellung einen Schalter in der Rancher-Benutzeroberfläche, der anzeigt, ob Benutzer die Einstellung überschreiben können.

* Wenn die Einstellung eine Benutzerüberschreibung zulässt, können Sie diese Einstellungen im Cluster aktualisieren, indem Sie xref:[den Cluster bearbeiten.]
* Wenn der Schalter deaktiviert ist, können Sie diese Einstellungen nicht ändern, es sei denn, der Clusterbesitzer erstellt eine Vorlagenrevision, die es Ihnen ermöglicht, sie zu überschreiben. Wenn es Einstellungen gibt, die Sie ändern möchten, aber nicht die Möglichkeit dazu haben, müssen Sie den Vorlageninhaber kontaktieren, um eine neue Revision der Vorlage zu erhalten.

Wenn ein Cluster aus einer RKE-Vorlage erstellt wurde, können Sie den Cluster bearbeiten, um ihn auf eine neue Revision der Vorlage zu aktualisieren.

Die Einstellungen eines bestehenden Clusters können <<_converting_an_existing_cluster_to_use_an_rke_template,als RKE-Vorlage gespeichert werden.>> In dieser Situation können Sie auch den Cluster bearbeiten, um ihn auf eine neue Revision der Vorlage zu aktualisieren.

[NOTE]
====

Sie können den Cluster nicht ändern, um eine andere RKE-Vorlage zu verwenden. Sie können den Cluster nur auf eine neue Revision derselben Vorlage aktualisieren.
====


[#_converting_an_existing_cluster_to_use_an_rke_template]
== Konvertierung eines bestehenden Clusters zur Verwendung einer RKE-Vorlage

Dieser Abschnitt beschreibt, wie man eine RKE-Vorlage aus einem bestehenden Cluster erstellt.

RKE-Vorlagen können nicht auf bestehende Cluster angewendet werden, es sei denn, Sie speichern die Einstellungen eines bestehenden Clusters als RKE-Vorlage. Dies exportiert die Einstellungen des Clusters als neue RKE-Vorlage und bindet den Cluster auch an diese Vorlage. Das Ergebnis ist, dass der Cluster nur geändert werden kann, wenn die {xref-manage-rke1-templates}#_aktualisierung_einer_vorlage[Vorlage aktualisiert wird,] und der Cluster ein Upgrade auf {xref-manage-rke1-templates}#_upgrade_eines_clusters_zur_verwendung_einer_neuen_vorlagenrevision[eine neuere Version der Vorlage erhält.]

Um einen bestehenden Cluster zur Verwendung einer RKE-Vorlage zu konvertieren,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Cluster* zu dem Cluster, das zur Verwendung einer RKE-Vorlage konvertiert werden soll. Klicken Sie *⋮  > Als RKE-Vorlage speichern*.
. Geben Sie einen Namen für die Vorlage in das erscheinende Formular ein und klicken Sie *Erstellen*.

*Ergebnisse:*

* Eine neue RKE-Vorlage wird erstellt.
* Der Cluster wird umgestellt, um die neue Vorlage zu verwenden.
* Neue Cluster können <<_creating_a_cluster_from_an_rke_template,aus der neuen Vorlage erstellt werden.>>
