= Beispiel-Szenarios
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzer-guides/authentifizierung-berechtigungen-und-globale-konfiguration/about-rke1-templates/beispiel-use-cases.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/example-use-cases.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/benutzer/authn-und-authz/verwaltung-der-rollenbasierten-zugriffskontrolle-rbac/global-berechtigungen.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-global-konfiguration/verwaltung-der-rollenbasierten-zugriffskontrolle-rbac/global-berechtigungen.adoc 
:xref-access-share-rke1-templates: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/zugriff-oder-teilen-von-vorlagen.adoc
:xref-manage-rke1-templates: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/rke1-vorlagen-verwalten.adoc
endif::[]

Diese Beispielszenarien beschreiben, wie eine Organisation Vorlagen verwenden könnte, um die Clustererstellung zu standardisieren.

* *Durchsetzung von Vorlagen:* Administratoren möchten möglicherweise <<_enforcing_a_template_setting_for_everyone,eine oder mehrere Vorlageneinstellungen für alle Benutzer erzwingen>>, wenn sie möchten, dass alle neuen von Rancher bereitgestellten Cluster diese Einstellungen haben.
* *Teilen verschiedener Vorlagen mit verschiedenen Benutzern:* Administratoren könnten <<_templates_for_basic_and_advanced_users,verschiedene Vorlagen für grundlegende und fortgeschrittene Benutzer>> bereitstellen, damit grundlegende Benutzer eingeschränktere Optionen haben und fortgeschrittene Benutzer mehr Ermessensspielraum bei der Erstellung von Clustern haben.
* *Aktualisierung von Vorlageneinstellungen:* Wenn die Sicherheits- und DevOps-Teams einer Organisation beschließen, bewährte Praktiken in die erforderlichen Einstellungen für neue Cluster einzubetten, könnten sich diese bewährten Praktiken im Laufe der Zeit ändern. Wenn sich die besten Praktiken ändern, <<_updating_templates_and_clusters_created_with_them,kann eine Vorlage auf eine neue Revision aktualisiert werden>> und Cluster, die aus der Vorlage erstellt wurden, können auf die neue Version der Vorlage upgraden.
* *Teilen des Eigentums an einer Vorlage:* Wenn ein Vorlageninhaber die Vorlage nicht mehr pflegen möchte oder die Eigentümerschaft der Vorlage delegieren möchte, beschreibt dieses Szenario, wie <<_allowing_other_users_to_control_and_share_a_template,die Vorlageneigentümerschaft geteilt werden kann.>>

[#_enforcing_a_template_setting_for_everyone]
== Vorlageneinstellung für alle erzwingen

Angenommen, es gibt eine Organisation, in der die Administratoren entscheiden, dass alle neuen Cluster mit Kubernetes Version 1.14 erstellt werden sollen.

. Zuerst erstellt ein Administrator eine Vorlage, die die Kubernetes-Version auf 1.14 festlegt und alle anderen Einstellungen als *Benutzerüberschreibung zulassen* markiert.
. Der Administrator macht die Vorlage öffentlich.
. Der Administrator aktiviert die Vorlagendurchsetzung.

*Ergebnisse:*

* Alle Rancher-Benutzer in der Organisation haben Zugriff auf die Vorlage.
* Alle neuen Cluster, die von {xref-global-permissions}[Standardbenutzern] mit dieser Vorlage erstellt werden, verwenden Kubernetes 1.14 und sie können keine andere Kubernetes-Version verwenden. Standardbenutzer haben standardmäßig keine Berechtigung, Vorlagen zu erstellen, sodass diese Vorlage die einzige Vorlage ist, die sie verwenden können, es sei denn, es werden weitere Vorlagen mit ihnen geteilt.
* Alle Standardbenutzer müssen eine Cluster-Vorlage verwenden, um einen neuen Cluster zu erstellen. Sie können keinen Cluster erstellen, ohne eine Vorlage zu verwenden.

Auf diese Weise setzen die Administratoren die Kubernetes-Version in der gesamten Organisation durch, während sie den Endbenutzern dennoch erlauben, alles andere zu konfigurieren.

[#_templates_for_basic_and_advanced_users]
== Vorlagen für grundlegende und fortgeschrittene Benutzer

Angenommen, eine Organisation hat sowohl grundlegende als auch fortgeschrittene Benutzer. Administratoren möchten, dass die grundlegenden Benutzer verpflichtet sind, eine Vorlage zu verwenden, während die fortgeschrittenen Benutzer und Administratoren ihre Cluster nach Belieben erstellen.

. Zuerst aktiviert ein Administrator xref:./enforce-templates.adoc#_requiring_new_clusters_to_use_an_rke_template[die Durchsetzung von RKE-Vorlagen.] Das bedeutet, dass jeder {xref-global-permissions}[Standardbenutzer] in Rancher eine RKE-Vorlage verwenden muss, wenn er einen Cluster erstellt.
. Der Administrator erstellt dann zwei Vorlagen:

* Eine Vorlage für grundlegende Benutzer, bei der fast jede Option angegeben ist, außer Zugriffsschlüsseln.
* Eine Vorlage für fortgeschrittene Benutzer, bei der die meisten oder alle Optionen *Benutzerüberschreibung zulassen* aktiviert sind.

. Der Administrator teilt die erweiterte Vorlage nur mit den fortgeschrittenen Benutzern.
. Der Administrator macht die Vorlage für grundlegende Benutzer öffentlich, sodass die restriktivere Vorlage für jeden, der einen von Rancher bereitgestellten Cluster erstellt, eine Option ist.

*Ergebnis:* Alle Rancher-Benutzer, mit Ausnahme der Administratoren, sind verpflichtet, eine Vorlage zu verwenden, wenn sie einen Cluster erstellen. Jeder hat Zugang zur restriktiven Vorlage, aber nur fortgeschrittene Benutzer haben die Berechtigung, die weniger restriktive Vorlage zu verwenden. Die grundlegenden Benutzer sind stärker eingeschränkt, während fortgeschrittene Benutzer mehr Freiheit bei der Konfiguration ihrer Kubernetes-Cluster haben.

[#_updating_templates_and_clusters_created_with_them]
== Aktualisierung von Vorlagen und den damit erstellten Clustern

Nehmen wir an, eine Organisation hat eine Vorlage, die erfordert, dass Cluster Kubernetes v1.14 verwenden. Mit der Zeit ändern die Administratoren jedoch ihre Meinung. Sie entscheiden, dass die Benutzer in der Lage sein sollen, ihre Cluster auf neuere Versionen von Kubernetes zu aktualisieren.

In dieser Organisation wurden viele Cluster mit einer Vorlage erstellt, die Kubernetes v1.14 erfordert. Da die Vorlage nicht zulässt, dass diese Einstellung überschrieben wird, können die Benutzer, die den Cluster erstellt haben, diese Einstellung nicht direkt bearbeiten.

Der Vorlageninhaber hat mehrere Optionen, um den Clustererstellern zu ermöglichen, Kubernetes auf ihren Clustern zu aktualisieren:

* *Geben Sie Kubernetes v1.15 in der Vorlage an:* Der Vorlageninhaber kann eine neue Vorlagenrevision erstellen, die Kubernetes v1.15 angibt. Dann kann der Besitzer jedes Clusters, das diese Vorlage verwendet, seinen Cluster auf eine neue Revision der Vorlage aktualisieren. Dieses Upgrade der Vorlage ermöglicht es dem Cluster-Ersteller, Kubernetes auf v1.15 in ihrem Cluster zu aktualisieren.
* *Erlauben Sie jede Kubernetes-Version in der Vorlage:* Beim Erstellen einer Template-Revision kann der Template-Besitzer auch die Kubernetes-Version als *Benutzerüberschreibung zulassen* markieren, indem er den Schalter in der Nähe dieser Einstellung in der Rancher-Benutzeroberfläche verwendet. Dies ermöglicht es Clustern, die auf diese Template-Revision aktualisieren, jede Version von Kubernetes zu verwenden.
* *Erlauben Sie die neueste minor Kubernetes-Version in der Vorlage:* Der Vorlageninhaber kann auch eine Vorlagenrevision erstellen, in der die Kubernetes-Version als *Neueste v1.14 (Erlaubt Patch-Version-Upgrades)* definiert ist. Das bedeutet, dass Cluster, die diese Revision verwenden, Patch-Upgrades erhalten können, aber Major-Upgrades nicht erlaubt sind.

[#_allowing_other_users_to_control_and_share_a_template]
== Anderen Benutzern erlauben, eine Vorlage zu steuern und zu teilen

Nehmen wir an, Alice ist eine Rancher-Administratorin. Sie besitzt eine RKE-Vorlage, die die vereinbarten Best Practices ihrer Organisation für die Erstellung eines Clusters widerspiegelt.

Bob ist ein fortgeschrittener Benutzer, der informierte Entscheidungen über die Cluster-Konfiguration treffen kann. Alice vertraut Bob, dass er neue Revisionen ihres Templates erstellt, während die Best Practices im Laufe der Zeit aktualisiert werden. Daher beschließt sie, Bob zum Besitzer der Vorlage zu machen.

Um die Eigentümerschaft der Vorlage mit Bob zu teilen, xref:./access-or-share-templates.adoc#_sharing_ownership_of_templates[fügt Alice Bob als Besitzer ihrer Vorlage hinzu.]

Das Ergebnis ist, dass Bob als Vorlageninhaber für die Versionskontrolle dieser Vorlage verantwortlich ist. Bob kann nun Folgendes tun:

* {xref-manage-rke1-templates}#_updating_a_template[Die Vorlage überarbeiten], wenn sich die Best Practices ändern
* {xref-manage-rke1-templates}#_disabling_a_template_revision[Veraltete Revisionen deaktivieren] der Vorlage, sodass keine neuen Cluster damit erstellt werden können
* {xref-manage-rke1-templates}#_deleting_a_template[Die gesamte Vorlage löschen], wenn die Organisation in eine andere Richtung gehen möchte
* {xref-manage-rke1-templates}#_setting_a_template_revision_as_default[Eine bestimmte Revision als Standard festlegen], wenn Benutzer mit ihr einen Cluster erstellen. Endbenutzer der Vorlage werden weiterhin wählen können, mit welcher Revision sie den Cluster erstellen möchten.
* {xref-access-share-rke1-templates}[Teilen Sie die Vorlage] mit bestimmten Benutzern, machen Sie die Vorlage für alle Rancher-Benutzer verfügbar oder teilen Sie das Eigentum an der Vorlage mit einem anderen Benutzer.
