= RKE-Vorlagen und Infrastruktur
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/authentifizierungsberechtigungen-und-global-konfiguration/über-rke1-vorlagen/infrastruktur.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/infrastructure.adoc
ifeval::["{build-type}" != "community"]
:xref-security-overview: xref:security/security-overview.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-security-overview: xref:reference-guides/rancher-security/index.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

In Rancher werden RKE-Vorlagen verwendet, um Kubernetes bereitzustellen und Rancher-Einstellungen zu definieren, während Knotenvorlagen zur Bereitstellung von Knoten verwendet werden.

Daher hat der Endbenutzer, selbst wenn die Durchsetzung von RKE-Vorlagen aktiviert ist, Flexibilität bei der Auswahl der zugrunde liegenden Hardware beim Erstellen eines Rancher-Clusters. Die Endbenutzer einer RKE-Vorlage können weiterhin einen Infrastruktur-Anbieter und die Knoten auswählen, die sie verwenden möchten.

Wenn Sie die Hardware in Ihren Clustern standardisieren möchten, verwenden Sie RKE-Vorlagen in Verbindung mit Knotenvorlagen oder mit einem Serverbereitstellungstool wie Terraform.

[#_node_templates]
== Knotenvorlagen

Knotenvorlagen sind für die Konfiguration und Bereitstellung von Knoten in Rancher verantwortlich. Von Ihrem Benutzerprofil aus können Sie Knotenvorlagen einrichten, um zu definieren, welche Vorlagen in jedem Ihrer Knotengruppen verwendet werden. Mit aktivierten Knotengruppen können Sie sicherstellen, dass Sie die erforderliche Anzahl von Knoten in jeder Knotengruppe haben und dass alle Knoten in der Gruppe identisch sind.

[#_terraform]
== Terraform

Terraform ist ein Serverbereitstellungstool. Es verwendet Infrastruktur als Code, mit dem Sie fast jeden Aspekt Ihrer Infrastruktur mit Terraform-Konfigurationsdateien erstellen können. Es kann den Prozess der Serverbereitstellung automatisieren, sodass er selbstdokumentierend und leicht in der Versionskontrolle nachverfolgbar ist.

Dieser Abschnitt konzentriert sich darauf, wie man Terraform mit dem https://www.terraform.io/docs/providers/rancher2/[Rancher 2 Terraform-Anbieter] verwendet, was eine empfohlene Option ist, um die Hardware für Ihre Kubernetes-Cluster zu standardisieren. Wenn Sie den Rancher Terraform-Anbieter verwenden, um Hardware bereitzustellen, und dann eine RKE-Vorlage verwenden, um einen Kubernetes-Cluster auf dieser Hardware bereitzustellen, können Sie schnell einen umfassenden, produktionsbereiten Cluster erstellen.

Terraform ermöglicht es Ihnen:

* Fast jede Art von Infrastructure-as-Code zu definieren, einschließlich Server, Datenbanken, Lastenausgleich, Überwachung, Firewall-Einstellungen und SSL-Zertifikate
* Infrastruktur über viele Plattformen hinweg zu kodifizieren, einschließlich Rancher und großer Cloud-Anbieter
* Infrastruktur als Code in die Versionskontrolle einpflegen
* Konfiguration und Setup der Infrastruktur einfach zu wiederholen
* Integrieren Sie Infrastrukturänderungen in die standardmäßigen Entwicklungspraktiken.
* Verhindern Sie Konfigurationsabweichungen, bei denen einige Server anders konfiguriert sind als andere.

[#_how_does_terraform_work]
== Wie funktioniert Terraform?

Terraform wird in Dateien mit der Erweiterung `.tf` geschrieben. Es ist in der HashiCorp-Konfigurationssprache geschrieben, einer deklarativen Sprache, mit der Sie die Infrastruktur, den von Ihnen verwendeten Cloud-Anbieter und Ihre Anmeldeinformationen für den Anbieter definieren können. Dann tätigt Terraform API-Aufrufe an den Anbieter, um diese Infrastruktur effizient zu erstellen.

Um einen von Rancher bereitgestellten Cluster mit Terraform zu erstellen, gehen Sie zu Ihrer Terraform-Konfigurationsdatei und definieren Sie den Anbieter als Rancher 2. Sie können Ihren Rancher 2-Anbieter mit einem Rancher-API-Schlüssel einrichten. Hinweis: Der API-Schlüssel hat die gleichen Berechtigungen und Zugriffsrechte wie der Benutzer, mit dem er verknüpft ist.

Dann ruft Terraform die Rancher-API auf, um Ihre Infrastruktur bereitzustellen, und Rancher ruft den Infrastruktur-Anbieter auf. Als Beispiel, wenn Sie Rancher verwenden möchten, um Infrastruktur auf AWS bereitzustellen, würden Sie sowohl Ihren Rancher-API-Schlüssel als auch Ihre AWS-Anmeldeinformationen in der Terraform-Konfigurationsdatei oder in Umgebungsvariablen angeben, damit sie zur Bereitstellung der Infrastruktur verwendet werden können.

Wenn Sie Änderungen an Ihrer Infrastruktur vornehmen müssen, können Sie anstelle von manuellen Aktualisierungen der Server Änderungen in den Terraform-Konfigurationsdateien vornehmen. Dann können diese Dateien in die Versionskontrolle eingegeben, validiert und nach Bedarf überprüft werden. Dann, wenn Sie `terraform apply` ausführen, würden die Änderungen bereitgestellt.

[#_tips_for_working_with_terraform]
== Tipps zur Arbeit mit Terraform

* Es gibt Beispiele, wie man die meisten Aspekte eines Clusters in der https://www.terraform.io/docs/providers/rancher2/[Dokumentation für den Rancher 2-Anbieter] bereitstellt.
* In den Terraform-Einstellungen können Sie Docker Machine installieren, indem Sie den Docker Machine-Knotentreiber verwenden.
* Sie können auch die Authentifizierung im Terraform-Anbieter ändern.
* Sie können zurückverfolgen, wie man eine Einstellung in Terraform definiert, indem Sie die Einstellung in Rancher ändern und dann zurückgehen und Ihre Terraform-Zustandsdatei überprüfen, um zu sehen, wie sie mit dem aktuellen Zustand Ihrer Infrastruktur übereinstimmt.

[#_tip_for_creating_cis_benchmark_compliant_clusters]
== Tipp zur Erstellung von CIS-Benchmark-konformen Clustern.

Dieser Abschnitt beschreibt eine Möglichkeit, wie Sie sicherheits- und compliancebezogene Konfigurationsdateien in Ihren Clustern standardisieren können.

Wenn Sie einen {xref-security-overview}[CIS-Benchmark-konformen Cluster] erstellen, haben Sie eine Verschlüsselungs-Konfigurationsdatei und eine Audit-Log-Konfigurationsdatei.

Ihr Infrastruktur-Bereitstellungssystem kann diese Dateien auf die Festplatte schreiben. Dann würden Sie in Ihrer RKE-Vorlage angeben, wo sich diese Dateien befinden, und Ihre Verschlüsselungs-Konfigurationsdatei sowie die Audit-Log-Konfigurationsdatei als zusätzliche Mounts zum `kube-api-server` hinzufügen.

Dann würden Sie sicherstellen, dass das `kube-api-server`-Flag in Ihrer RKE-Vorlage Ihre CIS-konformen Konfigurationsdateien verwendet.

Auf diese Weise können Sie Flags erstellen, die den CIS-Benchmark erfüllen.

[#_resources]
== Ressourcen

* https://www.terraform.io/docs/[Terraform-Dokumentation]
* https://www.terraform.io/docs/providers/rancher2/[Rancher 2 Terraform-Provider-Dokumentation]
* https://youtu.be/YNCq-prI8-8[Der RanchCast - Episode 1: Rancher 2 Terraform-Provider]: In dieser Demo führt Jason van Brackel, Direktor der Community, durch die Verwendung des Rancher 2 Terraform-Providers zur Bereitstellung von Knoten und zur Erstellung eines benutzerdefinierten Clusters.
