= Erstellen und Überarbeiten von RKE-Vorlagen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/rke1-vorlagen-verwalten.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-rke1-creator-permissions: xref:rancher-admin/global-configuration/rke1-templates/creator-permissions.adoc
:xref-rke1-template-apply: xref:rancher-admin/global-configuration/rke1-templates/apply-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-rke1-creator-permissions: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/erstellungsberechtigungen.adoc
:xref-rke1-template-apply: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/vorlagen-anwenden.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

In diesem Abschnitt wird beschrieben, wie man RKE-Vorlagen und -Revisionen verwaltet. Sie können Vorlagen aus der *Cluster Management*-Ansicht unter menu:RKE1-Konfiguration[RKE-Vorlagen] erstellen, teilen, aktualisieren und löschen.

Vorlagenaktualisierungen werden über ein Revisionssystem verwaltet. Wenn Vorlageninhaber eine Vorlage ändern oder aktualisieren möchten, erstellen sie eine neue Revision der Vorlage. Einzelne Revisionen können nicht bearbeitet werden. Wenn Sie jedoch verhindern möchten, dass eine Revision verwendet wird, um einen neuen Cluster zu erstellen, können Sie sie deaktivieren.

Vorlagenrevisionen können auf zwei Arten verwendet werden: um einen neuen Cluster zu erstellen oder um einen Cluster zu aktualisieren, der mit einer früheren Version der Vorlage erstellt wurde. Der Vorlageneigentümer kann eine Standardrevision wählen, aber wenn Endbenutzer einen Cluster erstellen, können sie jede Vorlage und jede Vorlagenrevision wählen, die ihnen zur Verfügung steht. Nachdem der Cluster aus einer bestimmten Revision erstellt wurde, kann er nicht zu einer anderen Vorlage wechseln, aber der Cluster kann auf eine neuere verfügbare Revision derselben Vorlage aktualisiert werden.

Der Vorlageneigentümer hat die volle Kontrolle über Vorlagenrevisionen und kann neue Revisionen erstellen, um die Vorlage zu aktualisieren, Revisionen löschen oder deaktivieren, die nicht zur Erstellung von Clustern verwendet werden sollen, und wählen, welche Vorlagenrevision die Standardrevision ist.

[#_prerequisites]
== Voraussetzungen

Sie können RKE-Vorlagen erstellen, wenn Sie die Berechtigung *RKE-Vorlagen erstellen* haben, die {xref-rke1-creator-permissions}[von einem Administrator vergeben werden kann.]

Sie können eine Vorlage überarbeiten, teilen und löschen, wenn Sie der Eigentümer der Vorlage sind. Für Details, wie Sie Eigentümer einer Vorlage werden können, siehe xref:./access-or-share-templates.adoc#_sharing_ownership_of_templates[die Dokumentation zum Teilen des Vorlageneigentums.]

[#_creating_a_template]
== Erstellen von Vorlagen

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie auf menu:RKE1-Konfiguration[Knoten-Vorlagen].
. Klicken Sie auf *Vorlage hinzufügen*.
. Legen Sie einen Namen für die Vorlage fest. Ein automatisch generierter Name wird bereits für die erste Version der Vorlage bereitgestellt, die zusammen mit dieser Vorlage erstellt wird.
. Optional: Teilen Sie die Vorlage mit anderen Benutzern oder Gruppen, indem Sie xref:./access-or-share-templates.adoc#_sharing_templates_with_specific_users_or_groups[sie als Mitglieder hinzufügen.] Sie können die Vorlage auch öffentlich machen, um sie mit allen im Rancher-Setup zu teilen.
. Füllen Sie dann das auf dem Bildschirm angezeigte Formular aus, um die Cluster-Konfigurationsparameter als Teil der Revision der Vorlage zu speichern. Die Revision kann als Standard für diese Vorlage markiert werden.

*Ergebnis:* Eine RKE-Vorlage mit einer Revision ist konfiguriert. Sie können diese RKE-Vorlagenrevision später verwenden, wenn Sie {xref-launch-k8s-with-rancher}[einen von Rancher gestarteten Cluster bereitstellen]. Nachdem ein Cluster von einer RKE-Vorlage verwaltet wird, kann es nicht getrennt werden, und die Option, *Eine vorhandene RKE-Vorlage und Revision verwenden* abzuwählen, ist nicht verfügbar.

[#_updating_a_template]
== Aktualisieren einer Vorlage

Wenn Sie eine RKE-Vorlage aktualisieren, erstellen Sie eine Revision der vorhandenen Vorlage. Cluster, die mit einer älteren Version der Vorlage erstellt wurden, können aktualisiert werden, um der neuen Revision zu entsprechen.

Sie können einzelne Revisionen nicht bearbeiten. Da Sie einzelne Revisionen einer Vorlage nicht bearbeiten können, können Sie, um zu verhindern, dass eine Revision verwendet wird, <<_disabling_a_template_revision,sie deaktivieren.>>

Wenn neue Vorlagenrevisionen erstellt werden, sind Cluster, die eine ältere Revision der Vorlage verwenden, nicht betroffen.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie im linken Navigationsmenü auf menu:RKE1-Konfiguration[RKE-Vorlagen].
. Gehen Sie zu der Vorlage, die Sie bearbeiten möchten, und klicken Sie auf *⋮ > Bearbeiten*.
. Bearbeiten Sie die erforderlichen Informationen und klicken Sie auf *Speichern*.
. Optional: Sie können die Standardrevision dieser Vorlage ändern und auch ändern, mit wem sie geteilt wird.

*Ergebnis:* Die Vorlage wurde aktualisiert. Um sie auf einem Cluster anzuwenden, das eine ältere Version der Vorlage verwendet, beziehen Sie sich auf den Abschnitt über <<_upgrading_a_cluster_to_use_a_new_template_revision,das Upgrade eines Clusters zur Verwendung einer neuen Revision einer Vorlage.>>

[#_deleting_a_template]
== Löschen einer Vorlage

Wenn Sie eine RKE-Vorlage für keines Ihrer Cluster mehr verwenden, können Sie sie löschen.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie auf menu:RKE1-Konfiguration[RKE-Vorlagen].
. Gehen Sie zu der RKE-Vorlage, die Sie löschen möchten, und klicken Sie auf *⋮ > Löschen*.
. Bestätigen Sie den Löschvorgang.

*Ergebnis:* Die Vorlage wird gelöscht.

[#_creating_a_revision_based_on_the_default_revision]
== Erstellen einer Revision basierend auf der Standardrevision

Sie können die Standardvorlagenrevision klonen und deren Einstellungen schnell aktualisieren, anstatt eine neue Revision von Grund auf zu erstellen. Das Klonen von Vorlagen erspart Ihnen die Mühe, die Zugangsschlüssel und andere für die Clustererstellung benötigte Parameter erneut einzugeben.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie im linken Navigationsmenü auf menu:RKE1-Konfiguration[RKE-Vorlagen].
. Gehen Sie zu der RKE-Vorlage, die Sie klonen möchten, und klicken Sie auf *⋮ > Neue Revision von Standard*.
. Vervollständigen Sie den Rest des Formulars, um eine neue Revision zu erstellen.

*Ergebnis:* Die RKE-Vorlagenrevision wird geklont und konfiguriert.

[#_creating_a_revision_based_on_a_cloned_revision]
== Erstellen einer Revision basierend auf einer geklonten Revision

Beim Erstellen neuer RKE-Vorlagenrevisionen aus Ihren Benutzereinstellungen können Sie eine vorhandene Revision klonen und deren Einstellungen schnell aktualisieren, anstatt eine neue von Grund auf zu erstellen. Das Klonen von Vorlagenrevisionen erspart Ihnen die Mühe, die Clusterparameter erneut einzugeben.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie unter *RKE1-Konfiguration* auf *RKE-Vorlagen*.
. Gehen Sie zu der Vorlagenrevision, die Sie klonen möchten. Wählen Sie dann *⋮ > Revision klonen* aus.
. Vervollständigen Sie den Rest des Formulars.

*Ergebnis:* Die RKE-Vorlagenrevision wird geklont und konfiguriert. Sie können die RKE-Vorlagenrevision später verwenden, wenn Sie ein Cluster bereitstellen. Jedes vorhandene Cluster, das diese RKE-Vorlage verwendet, kann auf diese neue Revision aktualisiert werden.

[#_disabling_a_template_revision]
== Deaktivieren einer Vorlagenrevision

Wenn Sie eine RKE-Vorlagenrevision nicht mehr für die Erstellung neuer Cluster verwenden möchten, können Sie sie deaktivieren. Eine deaktivierte RKE-Vorlagenrevision kann wieder aktiviert werden.

Sie können die RKE-Vorlagenrevision deaktivieren, wenn sie von keinem Cluster verwendet wird.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie im linken Navigationsmenü auf menu:RKE1-Konfiguration[RKE-Vorlagen].
. Gehen Sie zu der RKE-Vorlagenrevision, die Sie deaktivieren möchten. Wählen Sie dann *⋮ > Deaktivieren* aus.

*Ergebnis:* Die RKE-Vorlagenrevision kann nicht verwendet werden, um einen neuen Cluster zu erstellen.

[#_re_enabling_a_disabled_template_revision]
== Eine deaktivierte Vorlagenrevision wieder aktivieren

Wenn Sie entscheiden, dass eine deaktivierte RKE-Vorlagenrevision verwendet werden soll, um neue Cluster zu erstellen, können Sie sie wieder aktivieren.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie unter *RKE1-Konfiguration* auf *RKE-Vorlagen*.
. Gehen Sie zu der RKE-Vorlagenrevision, die Sie wieder aktivieren möchten. Wählen Sie dann *⋮ > Aktivieren* aus.

*Ergebnis:* Die RKE-Vorlagenrevision kann verwendet werden, um einen neuen Cluster zu erstellen.

[#_setting_a_template_revision_as_default]
== Eine Vorlagenrevision als Standard festlegen

Wenn Endbenutzer einen Cluster mit einer RKE-Vorlage erstellen, können sie wählen, mit welcher Revision der Cluster erstellt werden soll. Sie können konfigurieren, welche Revision standardmäßig verwendet wird.

Um eine RKE-Template-Revision als Standard festzulegen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie im linken Navigationsmenü auf menu:RKE1-Konfiguration[RKE-Vorlagen].
. Gehen Sie zu der RKE-Template-Revision, die als Standard festgelegt werden soll, und klicken Sie auf *⋮ > Als Standard festlegen*.

*Ergebnis:* Die RKE-Template-Revision wird als Standardoption verwendet, wenn Cluster mit der Vorlage erstellt werden.

[#_deleting_a_template_revision]
== Eine Vorlagenrevision löschen

Sie können alle Revisionen einer Vorlage löschen, außer der Standardrevision.

Um eine Template-Revision endgültig zu löschen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie im linken Navigationsmenü auf menu:RKE1-Konfiguration[RKE-Vorlagen].
. Gehen Sie zu der RKE-Template-Revision, die gelöscht werden soll, und klicken Sie auf *⋮ > Löschen*.

*Ergebnis:* Die RKE-Vorlagenrevision wird gelöscht.

[#_upgrading_a_cluster_to_use_a_new_template_revision]
== Einen Cluster auf eine neue Vorlagenrevision aktualisieren

[NOTE]
====

Dieser Abschnitt geht davon aus, dass Sie bereits einen Cluster haben, der {xref-rke1-template-apply}[eine RKE-Vorlage angewendet hat.]

Dieser Abschnitt geht auch davon aus, dass Sie <<_updating_a_template,die Vorlage, die der Cluster verwendet, aktualisiert haben>>, sodass eine neue Vorlagenrevision verfügbar ist.
====


Um einen Cluster auf eine neue Template-Revision zu aktualisieren,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, das Sie aktualisieren möchten, und klicken Sie auf *⋮ > Konfiguration bearbeiten*.
. Im Abschnitt *Cluster-Optionen* klicken Sie auf das Dropdown-Menü für die Template-Revision und wählen dann die neue Template-Revision aus.
. Klicken Sie auf *Speichern*.

*Ergebnis:* Der Cluster wird aktualisiert, um die in der neuen Template-Revision definierten Einstellungen zu verwenden.

[#_exporting_a_running_cluster_to_a_new_rke_template_and_revision]
== Einen laufenden Cluster in eine neue RKE-Vorlage und Vorlagenrevision exportieren

Sie können die Einstellungen eines bestehenden Clusters als RKE-Vorlage speichern.

Dies exportiert die Einstellungen des Clusters als neue RKE-Vorlage und bindet den Cluster auch an diese Vorlage. Das Ergebnis ist, dass der Cluster nur geändert werden kann, wenn die <<_updating_a_template,Vorlage aktualisiert wird,>> und der Cluster auf <<_upgrading_a_cluster_to_use_a_new_template_revision,eine neuere Version der RKE-Vorlage aktualisiert wird.>>

Um einen bestehenden Cluster zur Verwendung einer RKE-Vorlage zu konvertieren,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, der zur Verwendung einer RKE-Vorlage konvertiert werden soll, und *⋮ > Als RKE-Vorlage speichern*.
. Geben Sie einen Namen für die RKE-Vorlage in das erscheinende Formular ein und klicken Sie auf *Erstellen*.

*Ergebnisse:*

* Eine neue RKE-Vorlage wird erstellt.
* Der Cluster wird umgestellt, um die neue Vorlage zu verwenden.
* Neue Cluster können xref:./apply-templates.adoc#_creating_a_cluster_from_an_rke_template[aus der neuen Vorlage und Revision erstellt werden.]
