= Überschreiben von Vorlageneinstellungen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/vorlageneinstellungen-überschreiben.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/override-template-settings.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rke1-templates: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-rke1-vorlagen/rke1-vorlagen-verwalten.adoc
endif::[]

Wenn ein Benutzer eine RKE-Vorlage erstellt, hat jede Einstellung in der Vorlage einen Schalter in der Rancher-Benutzeroberfläche, der anzeigt, ob Benutzer die Einstellung überschreiben können. Dieser Schalter kennzeichnet diese Einstellungen als *Benutzerüberschreibung erlauben*.

Nachdem ein Cluster mit einer Vorlage erstellt wurde, können Endbenutzer keine der in der Vorlage definierten Einstellungen aktualisieren, es sei denn, der Vorlageninhaber hat sie als *Benutzerüberschreibung erlauben* markiert. Wenn die Vorlage jedoch {xref-manage-rke1-templates}[auf eine neue Revision aktualisiert] wird, die die Einstellungen ändert oder es Endbenutzern erlaubt, sie zu ändern, kann der Cluster auf eine neue Revision der Vorlage geupgradet werden, und die Änderungen in der neuen Revision werden auf den Cluster angewendet.

Wenn ein Parameter in der RKE-Vorlage als *Benutzerüberschreibung erlauben* festgelegt ist, bedeutet dies, dass Endbenutzer diese Felder während der Clustererstellung ausfüllen müssen und diese Einstellungen danach jederzeit bearbeiten können.

Das Modell *Benutzerüberschreibung erlauben* der RKE-Vorlage ist nützlich für Situationen wie:

* Administratoren wissen, dass einige Einstellungen die Flexibilität benötigen, im Laufe der Zeit häufig aktualisiert zu werden.
* Endbenutzer müssen beispielsweise ihre eigenen Zugriffsschlüssel oder geheimen Schlüssel eingeben, wie Cloud-Anmeldeinformationen oder Anmeldeinformationen für Sicherungssnapshots.
