= EC2マシン構成リファレンス
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-10
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/amazon-ec2.adoc 
:product-path: cluster-deployment/infra-providers/aws/machine-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
endif::[]

EC2ノードに関する詳細は、 https://aws.amazon.com/ec2[EC2管理コンソール]の公式ドキュメントを参照してください。

[#_basic_options]
== 基本的なオプション

[#_region]
=== 地域

クラスターを構築する地理的な https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html[リージョン]。

[#_zone]
=== ゾーン

クラスターを構築するための https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-availability-zones[ゾーン]、リージョン内の孤立した場所。

[#_instance_type]
=== インスタンスタイプ

クラスターをプロビジョニングするために使用されるハードウェア特性を決定する https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html[インスタンスタイプ]。

[#_root_disk_size]
=== ルートディスクサイズ

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html[ルートデバイス]のサイズ（GB単位）を設定してください。

[#_vpc_subnet]
=== VPC/Subnet

リソースを追加するための https://docs.aws.amazon.com/vpc/latest/userguide/configure-your-vpc.html[VPC]または特定の https://docs.aws.amazon.com/vpc/latest/userguide/configure-subnets.html[サブネット]、VPC内のIP範囲。

[#_iam_instance_profile_name]
=== IAMインスタンスプロファイル名

EC2インスタンスにIAMロールを渡すために使用される https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html[インスタンスプロファイル]の名前。

[#_advanced_options]
== 詳細オプション

[#_ami_id]
=== AMI ID

クラスター内のノードに使用される https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html[Amazonマシンイメージ]。

[#_ssh_username_for_ami]
=== AMIのSSHユーザー名

起動したインスタンスに接続するためのユーザー名。選択したAMIのデフォルトユーザー名については、 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connection-prereqs.html[こちら]を参照してください。リストにないAMIについては、AMIプロバイダーに確認してください。

[#_security_group]
=== セキュリティグループ

デフォルトのセキュリティグループを選択するか、セキュリティグループを構成してください。

{xref-port-reqs}#_rancher_aws_ec2_security_group[ノードドライバーを使用する際のAmazon EC2セキュリティグループ]を参照して、`rancher-nodes`セキュリティグループで作成されるルールを確認してください。

[#_ebs_root_volume_type]
=== EBSルートボリュームタイプ

ルートデバイスに使用する https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html[EBSボリュームタイプ]。

[#_encrypt_ebs_volume]
=== EBSボリュームを暗号化する

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html[Amazon EBS暗号化]を有効にします。

[#_request_spot_instance]
=== スポットインスタンスをリクエストする

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html[スポットインスタンスをリクエストする]オプションを有効にし、支払う意志のある最大インスタンス価格を指定します。

[#_use_only_private_address]
=== プライベートアドレスのみを使用する

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html[プライベートアドレス]のみを使用するオプションを有効にします。

[#_ebs_optimized_instance]
=== EBS最適化インスタンス

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html[EBS最適化インスタンス]を使用します。

[#_allow_access_to_ec2_metadata]
=== EC2メタデータへのアクセスを許可する

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html[EC2メタデータ]へのアクセスを有効にします。

[#_use_tokens_for_metadata]
=== メタデータ用のトークンを使用する

メタデータにアクセスするためのトークンベースの方法である https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html[インスタンスメタデータサービスバージョン2 (IMDSv2)]を使用します。

[#_add_tag]
=== タグを追加する

リソースを分類するために https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html[タグ]を使用してメタデータを追加します。

[#_ipv6_address_count]
=== IPv6アドレス数

インスタンスのネットワークインタフェースに割り当てるIPv6アドレスの数を指定します。

[#_ipv6_address_only]
=== IPv6アドレスのみ

インスタンスがIPv6のみを使用する必要がある場合は、このオプションを有効にします。IPv6専用のVPCまたはサブネットでは、これが必要です。有効にすると、インスタンスはIPv6を唯一のアドレスとして持ち、IPv6アドレス数はゼロより大きくなければなりません。

[#_http_protocol_ipv6]
=== HTTP Protocol IPv6

インスタンスメタデータサービスの IPv6 エンドポイントを有効または無効にします。

[#_enable_primary_ipv6]
=== プライマリ IPv6 を有効にする

このオプションを有効にすると、最初に割り当てられた IPv6 アドレスをプライマリアドレスとして指定します。これにより、インスタンスの一貫した変更のない IPv6 アドレスが保証されます。IPv6 アドレスが割り当てられるかどうかは制御しません。
