= Kubernetesのアップグレードとロールバック
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes.adoc 
:product-path: cluster-admin/backups-and-restore/backups-and-restore.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-ds-backup: xref:cluster-admin/backups-and-restore/backups.adoc
:xref-nodes-machinepools: xref:cluster-admin/manage-clusters/nodes-and-machine-pools.adoc
:xref-ds-restore: xref:cluster-admin/backups-and-restore/restore.adoc
:xref-backup-disaster-recovery: xref:rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
:xref-ds-backup: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher-launched-kubernetes-clusters.adoc
:xref-nodes-machinepools: xref:how-to-guides/new-user-guides/manage-clusters/nodes-and-machine-pools.adoc
:xref-ds-restore: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher-launched-kubernetes-clusters-from-backup.adoc
:xref-backup-disaster-recovery: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/index.adoc
endif::[]

Rancherの最新バージョンにアップグレードした後、ダウンストリームのKubernetesクラスターは、サポートされている最新のKubernetesバージョンを使用するようにアップグレードできます。

Rancherは、RKEクラスターをプロビジョニングおよび編集する際に、RKE（Rancher Kubernetes Engine）をライブラリとして呼び出します。RKEクラスターのアップグレード戦略を構成する方法についての詳細は、 https://rancher.com/docs/rke/latest/en/[RKEドキュメント]を参照してください。

[#_tested_kubernetes_versions]
== テストされたKubernetesバージョン

新しいRancherのバージョンがリリースされる前に、互換性を確認するために、最新のマイナーバージョンのKubernetesでテストされます。各RancherバージョンでテストされたKubernetesバージョンの詳細については、 https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.6.0/[サポート保守条件を参照してください。]

[#_how_upgrades_work]
== アップグレードの仕組み

RKE v1.1.0は、クラスターのアップグレード方法を変更しました。

この https://rancher.com/docs/rke/latest/en/upgrades/how-upgrades-work[RKEドキュメント,]のセクションでは、RKE Kubernetesクラスターを編集またはアップグレードすると何が起こるかを学びます。

[#_recommended_best_practice_for_upgrades]
== アップグレードの推奨ベストプラクティス

クラスターのKubernetesバージョンをアップグレードする際は、次のことを推奨します。

. スナップショットを作成してください。
. Kubernetesアップグレードを開始してください。
. アップグレードが失敗した場合は、クラスタをアップグレード前のKubernetesバージョンに戻すこれは、*etcdとKubernetesバージョンを復元する*オプションを選択することで実現されます。これにより、etcdスナップショットを復元する前に、クラスターがアップグレード前のKubernetesバージョンに戻ります。

復元操作は、正常またはアクティブな状態ではないクラスタで機能します。

[#_upgrading_the_kubernetes_version]
== Kubernetesバージョンのアップグレード

[NOTE]
.前提条件:
====

* 以下のオプションは、{xref-launch-k8s-with-rancher}[Rancherが起動したKubernetesクラスター]および{xref-register-clusters}#_additional_features_for_registered_rke2_and_k3s_clusters[登録されたK3s Kubernetesクラスター]に利用可能です。
* 以下のオプションは、登録したインポートされたRKE2クラスターにも適用されます。外部クラウドプラットフォームからクラスターをインポートしても、登録しない場合はRancherからKubernetesのバージョンをアップグレードすることはできません。
* Kubernetesをアップグレードする前に、{xref-backup-disaster-recovery}[クラスターをバックアップしてください。]
====


. 左上隅で、*☰ > クラスター管理*をクリックします。
. *クラスター*ページで、アップグレードしたいクラスターに移動し、*⋮ > 設定を編集*をクリックします。
. *Kubernetesバージョン*のドロップダウンから、クラスターで使用したいKubernetesのバージョンを選択します。
. ［*保存*］をクリックします。

*結果:*Kubernetesがクラスターのアップグレードを開始します。

[#_rolling_back]
== ロールバック

クラスターは、以前のKubernetesバージョンが使用されていたバックアップに復元できます。詳細については、以下のセクションを参照してください：

* {xref-ds-backup}#_how_snapshots_work[Backing up a cluster]
* {xref-ds-restore}#_restoring_a_cluster_from_a_snapshot[Restoring a cluster from backup]

[#_configuring_the_upgrade_strategy]
== アップグレード戦略の設定

RKE v1.1.0以降、アップグレードプロセスに対するより詳細な制御を提供するために、追加のアップグレードオプションが利用可能になりました。これらのオプションは、特定の https://rancher.com/docs/rke/latest/en/upgrades/maintaining-availability[条件と要件]が満たされている場合、クラスターのアップグレード中にアプリケーションの可用性を維持するために使用できます。

アップグレード戦略は、Rancher UIで設定するか、`cluster.yml`を編集することで構成できます。より高度なオプションは、`cluster.yml`を編集することで利用可能です。

[#_configuring_the_maximum_unavailable_worker_nodes_in_the_rancher_ui]
=== Rancher UIでの最大利用不可ワーカーノードの設定

Rancher UIから、最大利用不可ワーカーノードの数を設定できます。クラスタのアップグレード中に、ワーカーノードがこのサイズのバッチでアップグレードされます。

デフォルトでは、使用できないワーカーの最大数は、すべてのワーカーノードの10パーセントとして定義されています。この数は、パーセンテージとして、または整数として設定できます。パーセンテージとして定義されている場合、バッチサイズは、1つ以上のノードを含む最も近いノードに切り捨てられます。

デフォルトのワーカーノードの数または割合を変更するには、

. 左上隅で、*☰ > クラスター管理*をクリックします。
. *クラスター*ページで、アップグレードしたいクラスターに移動し、*⋮ > 設定を編集*をクリックします。
. *アップグレード戦略*タブで、*ワーカーの同時実行数*を固定数または割合として入力します。この数値を取得するには、クラスター内のノードの数から最大の利用不可ノードを引くことができます。
. ［*保存*］をクリックします。

*結果:*クラスターは新しいアップグレード戦略を使用するように更新されます。

[#_enabling_draining_nodes_during_upgrades_from_the_rancher_ui]
=== Rancher UIからのアップグレード中にノードの排出を有効にする

デフォルトでは、RKEはアップグレードする前に各ノードを https://kubernetes.io/docs/concepts/architecture/nodes/#manual-node-administration[コーデン]します。アップグレード中は https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/[排出]がデフォルトで無効になっています。クラスター構成で排出が有効になっている場合、RKEはアップグレードの前にノードをコーデンし、排出します。

クラスターのアップグレード中に各ノードの排出を有効にするには、

. 左上隅で、*☰ > クラスター管理*をクリックします。
. *クラスター*ページで、ノードの排出を有効にしたいクラスターに移動し、*⋮ > 設定を編集*をクリックします。
. *⋮ > 編集*をクリックします。
. *アップグレード戦略*タブで、*ノードを排出*フィールドに移動し、*はい*をクリックします。ノードの排出は、コントロールプレーンとワーカーノードで別々に構成されます。
. ポッドが削除される方法のオプションを構成します。各オプションの詳細については、{xref-nodes-machinepools}#_aggressive_and_safe_draining_options[このセクション]を参照してください。
. オプションで、猶予期間を構成します。猶予期間は、各ポッドにクリーンアップのために与えられるタイムアウトで、ポッドが正常に終了するための猶予を与えます。ポッドは、未処理のリクエストを完了したり、トランザクションをロールバックしたり、外部ストレージに状態を保存したりする必要があるかもしれません。この値が負の場合、ポッドで指定されたデフォルト値が使用されます。
. オプションで、タイムアウトを構成します。これは、排出があきらめる前に待機する時間のことです。
. ［*保存*］をクリックします。

*結果:*クラスターは新しいアップグレード戦略を使用するように更新されます。

[NOTE]
====
* Rancher UIがetcdとコントロールプレーンの状態を排出中として表示しない https://github.com/rancher/rancher/issues/25478[既知の問題]がありますが、実際には排出されています。
* アップグレード中は、ユーザーが目に見えるYAMLの変更がない場合でも、ノードが排出されることがあります。これは、非動的な設定ファイルが更新されたり、新しい`system-agent-installer`イメージが導入されたりする場合に発生する可能性があります。そのような場合、Rancherは新しいアップグレードプランを生成し、新しいプランハッシュが生成されます。`Upgrade Strategy`が`Drain nodes`に設定されている場合、このプランの変更はノードの排出を引き起こす可能性があります。
====


[#_maintaining_availability_for_applications_during_upgrades]
=== アップグレード中のアプリケーションの可用性を維持する

https://rancher.com/docs/rke/latest/en/upgrades/maintaining-availability/[このRKEドキュメントのセクション,]では、クラスターのアップグレード時にアプリケーションのダウンタイムを防ぐための要件について学びます。

[#_configuring_the_upgrade_strategy_in_the_cluster_yml]
=== cluster.ymlでのアップグレード戦略の設定

より高度なアップグレード戦略の設定オプションは、`cluster.yml`を編集することで利用可能です。

詳細については、RKEドキュメントの https://rancher.com/docs/rke/latest/en/upgrades/configuring-strategy[アップグレード戦略の設定]を参照してください。このセクションには、アップグレード戦略を設定するための例`cluster.yml`も含まれています。

[#_troubleshooting]
== トラブルシューティング

アップグレード後にノードが起動しない場合、`rke up`コマンドはエラーになります。

使用できないノードの数が設定されている最大数を超えると、アップグレードは続行されません。

アップグレードが停止した場合、アップグレードを続行する前に、使用できないノードを修正するか、クラスターから削除する必要があります。

失敗したノードは多くの異なる状態にある可能性があります：

* 電源オフ
* 使用不可
* ユーザーがアップグレード中にノードをドレインするため、ノード上にkubeletが存在しません。
* アップグレード自体が失敗しました。

アップグレード中に最大の使用できないノード数に達した場合、Rancherユーザークラスターは更新状態に留まり、他のコントロールプレーンノードのアップグレードを進めることができません。ノードのいずれかが利用可能になる場合に備えて、使用できないノードのセットを引き続き評価します。ノードを修正できない場合、アップグレードを続行するためにノードを削除する必要があります。
