= 审计日志中的用户ID跟踪
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-27
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc 
:product-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc
ifeval::["{build-type}" != "community"]
:xref-enable-api-audit-log: xref:observability/logging/enable-api-audit-log.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-enable-api-audit-log: xref:how-to-guides/advanced-user-guides/enable-api-audit-log.adoc
endif::[]

以下审计日志用于Rancher，以跟踪本地和下游集群上发生的事件：

* https://rancher.com/docs/rke/latest/en/config-options/audit-log/[Kubernetes审计日志]
* {xref-enable-api-audit-log}[Rancher API审计日志]

Rancher v2.6中的审计日志已增强，以在Rancher和下游Kubernetes审计日志中包含外部身份提供者名称（外部身份提供者中用户的通用名称）。

在v2.6之前，Rancher管理员无法从Rancher审计日志追踪事件到Kubernetes审计日志，而不知道外部身份提供者用户名与Rancher中使用的用户ID（`u-xXXX`）的映射。
要了解此映射，集群管理员需要访问Rancher API、用户界面和本地管理集群。

现在有了这个功能，下游集群管理员应该能够查看Kubernetes审计日志，并知道哪个特定的外部身份提供者（IDP）用户执行了某个操作，而无需查看Rancher中的任何内容。
如果审计日志被转移出集群，日志系统的用户应该能够在外部身份提供者系统中识别用户。
Rancher管理员现在应该能够查看Rancher审计日志，并通过使用外部身份提供者用户名跟踪到Kubernetes审计日志。

[#_feature_description]
== 功能描述

* 当在下游集群上启用Kubernetes审计日志时，在每个记录的事件中，外部身份提供者的用户名现在在"元数据"级别记录每个请求。
* 当您为Rancher安装启用Rancher API审计日志时，外部身份提供者的用户名现在也在`auditLog.level=0`中记录每个请求，包括登录请求。
