= Empfohlene Cluster-Architektur
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/kubernetes-cluster-in-rancher-setup/checkliste-für-produktionsbereite-cluster/empfohlene-cluster-architektur.adoc 
:product-path: cluster-deployment/production-checklist/recommended-cluster-architecture.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-production-checklist-node-roles: xref:cluster-deployment/production-checklist/roles-for-nodes-in-kubernetes.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-production-checklist-node-roles: xref:how-to-guides/neue-benutzeranleitungen/kubernetes-cluster-in-rancher-setup/checkliste-für-produktionsbereite-cluster/rollen-für-knoten-in-kubernetes.adoc
endif::[]

Es gibt drei Rollen, die Knoten zugewiesen werden können: `etcd`, `controlplane` und `worker`.

[#_separating_worker_nodes_from_nodes_with_other_roles]
== Trennung von Worker-Knoten und Knoten mit anderen Rollen

Bei der Gestaltung Ihrer Cluster haben Sie zwei Optionen:

* Verwenden Sie dedizierte Knoten für jede Rolle. Dies gewährleistet die Verfügbarkeit von Ressourcen für die Komponenten, die für die angegebene Rolle benötigt werden. Es isoliert auch den Netzwerkverkehr zwischen den einzelnen Rollen gemäß den {xref-node-reqs}#_networking_requirements[Portanforderungen].
* Weisen Sie die Rollen `etcd` und `controlplane` denselben Knoten zu. Diese Knoten müssen die Hardwareanforderungen für beide Rollen erfüllen.

In beiden Fällen sollte die Rolle `worker` weder verwendet noch auf Knoten mit der Rolle `etcd` oder `controlplane` hinzugefügt werden.

Daher sollte jeder Knoten eine der folgenden Rollenkonfigurationen haben:

* `etcd`
* `controlplane`
* Sowohl `etcd` als auch `controlplane`
* `worker`

[#_recommended_number_of_nodes_with_each_role]
== Empfohlene Anzahl von Knoten mit jeder Rolle

Der Cluster sollte haben:

* Mindestens drei Knoten mit der Rolle `etcd`, um den Verlust eines Knotens zu überstehen. Erhöhen Sie diese Anzahl für eine höhere Fehlertoleranz der Knoten und verteilen Sie sie über (Verfügbarkeits-)Zonen, um eine noch bessere Fehlertoleranz zu gewährleisten.
* Mindestens zwei Knoten mit der Rolle `controlplane` für hohe Verfügbarkeit der Master-Komponenten.
* Mindestens zwei Knoten mit der Rolle `worker` für die Neuzuweisung von Workloads bei einem Knotenausfall.

Für weitere Informationen darüber, wofür jede Rolle verwendet wird, siehe die {xref-production-checklist-node-roles}[Sektion über Rollen für Knoten in Kubernetes.]

[#_number_of_controlplane_nodes]
=== Anzahl der Controlplane-Knoten

Das Hinzufügen von mehr als einem Knoten mit der `controlplane`-Rolle macht jede Masterkomponente hochverfügbar.

[#_number_of_etcd_nodes]
=== Anzahl der etcd-Knoten

Die Anzahl der Knoten, die Sie gleichzeitig verlieren können, während die Clusterverfügbarkeit aufrechterhalten wird, wird durch die Anzahl der Knoten bestimmt, die die `etcd`-Rolle zugewiesen haben. Für ein Cluster mit n Mitgliedern beträgt das Minimum (n/2)+1. Daher empfehlen wir, einen `etcd`-Knoten in 3 verschiedenen Verfügbarkeitszonen innerhalb einer Region zu erstellen, um den Verlust einer Verfügbarkeitszone zu überstehen. Wenn Sie nur zwei Zonen verwenden, können Sie nur den Verlust der Zone überstehen, in der Sie nicht die Mehrheit der Knoten verlieren.

|===
| Knoten mit der `etcd`-Rolle | Mehrheit | Fehlertoleranz

| 1
| 1
| 0

| 2
| 2
| 0

| 3
| 2
| *1*

| 4
| 3
| 1

| 5
| 3
| *2*

| 6
| 4
| 2

| 7
| 4
| *3*

| 8
| 5
| 3

| 9
| 5
| *4*
|===

Referenzen:

* https://etcd.io/docs/v3.5/faq/#what-is-failure-tolerance[Offizielle etcd-Dokumentation zur optimalen etcd-Clustergröße]
* https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/[Offizielle Kubernetes-Dokumentation zum Betrieb von etcd-Clustern für Kubernetes]

[#_number_of_worker_nodes]
=== Anzahl der Worker-Knoten

Das Hinzufügen von mehr als einem Knoten mit der `worker`-Rolle stellt sicher, dass Ihre Workloads neu zugewiesen werden können, wenn ein Knoten ausfällt.

[#_why_production_requirements_are_different_for_the_rancher_cluster_and_the_clusters_running_your_applications]
=== Warum die Produktionsanforderungen für den Rancher-Cluster und die Cluster, die Ihre Anwendungen ausführen, unterschiedlich sind

Sie haben vielleicht bemerkt, dass unsere {xref-install-rancher}[Kubernetes Install]-Anweisungen nicht unserer Definition eines produktionsbereiten Clusters entsprechen, da es keine dedizierten Knoten für die `worker`-Rolle gibt. Für Ihre Rancher-Installation ist dieser Cluster mit drei Knoten jedoch gültig, weil:

* Er erlaubt einen Ausfall eines `etcd`-Knotens.
* Er erhält mehrere Instanzen der Masterkomponenten, indem er mehrere `controlplane`-Knoten hat.
* Es sollten keine anderen Workloads als Rancher selbst in diesem Cluster erstellt werden.

[#_references]
== Hinweise

* https://kubernetes.io/docs/concepts/overview/components/#master-components[Kubernetes: Masterkomponenten]
