= Configuración de la ubicación de almacenamiento de copias de seguridad
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/backup-restore-configuration/configuración-almacenamiento.adoc 
:product-path: rancher-admin/back-up-restore-and-disaster-recovery/configuration/storage.adoc
ifeval::["{build-type}" != "community"]
:xref-existing-storage-setup: xref:cluster-admin/manage-clusters/persistent-storage/set-up-existing-storage.adoc
:xref-dynamically-provision-new-storage: xref:cluster-admin/manage-clusters/persistent-storage/dynamically-provision-new-storage.adoc
:xref-rancher-backup-config: xref:rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-existing-storage-setup: xref:instrucciones/nuevas-guías-de-usuario/gestionar-clusters/crear-almacenamiento-persistente-de-kubernetes/gestionar-almacenamiento-persistente/configuración-almacenamiento-existente.adoc
:xref-dynamically-provision-new-storage: xref:instrucciones/nuevas-guías-de-usuario/gestionar-clusters/crear-almacenamiento-persistente-de-kubernetes/gestionar-almacenamiento-persistente/provisionar-nuevo-almacenamiento-dinámicamente.adoc
:xref-rancher-backup-config: xref:referencia-guías/backup-restore-configuration/respaldo-configuración.adoc
endif::[]

Configura una ubicación de almacenamiento donde se guardarán todas las copias de seguridad por defecto. Tendrás la opción de anular esto con cada copia de seguridad, pero estarás limitado a utilizar un almacén de objetos compatible con S3.

Solo se puede configurar una ubicación de almacenamiento a nivel de operador.

[#_storage_location_configuration]
== Configuración de la ubicación de almacenamiento

[#_no_default_storage_location]
=== Sin ubicación de almacenamiento predeterminada

Puedes elegir no tener ninguna ubicación de almacenamiento configurada a nivel de operador. Si seleccionas esta opción, deberás configurar un almacén de objetos compatible con S3 como la ubicación de almacenamiento para cada copia de seguridad individual.

[#_s3_compatible_object_store]
=== Almacén de objetos compatible con S3

|===
| Parámetro | Descripción

| Secreto de credenciales
| Elige las credenciales para S3 de tus secretos en Rancher. {xref-rancher-backup-config}#_ejemplo_secreto_de_credenciales[Ejemplo].

| Nombre del bucket
| Introduce el nombre del https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html[bucket de S3] donde se almacenarán las copias de seguridad. Por defecto: `rancherbackups`.

| Región
| La https://aws.amazon.com/about-aws/global-infrastructure/regions_az/[región de AWS] donde se encuentra el bucket de S3.

| Carpeta
| La https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html[carpeta en el bucket de S3] donde se almacenarán las copias de seguridad. Si este campo se deja vacío, el comportamiento predeterminado es almacenar los archivos de copia de seguridad en la carpeta raíz del bucket de S3.

| Puesto final
| El https://docs.aws.amazon.com/general/latest/gr/s3.html[endpoint de S3]. Por ejemplo, `s3.us-west-2.amazonaws.com`.

| Endpoint CA
| El certificado CA utilizado para el endpoint de S3. Por defecto: certificado CA codificado en base64

| insecureTLSSkipVerify
| Establecer en verdadero si no estás utilizando TLS.
|===

[#_existing_storageclass]
=== Clase de almacenamiento existente

Instalar el gráfico `rancher-backup` seleccionando la opción de Clase de Almacenamiento creará una Solicitud de Volumen Persistente (PVC), y Kubernetes, a su vez, aprovisionará dinámicamente un Volumen Persistente (PV) donde se guardarán todas las copias de seguridad por defecto.

Para información sobre cómo crear clases de almacenamiento, consulta {xref-dynamically-provision-new-storage}[esta sección.]

[NOTE]
.Importante:
====

Se recomienda encarecidamente utilizar una Clase de Almacenamiento con una política de recuperación de "Retener". De lo contrario, si la PVC creada por el gráfico `rancher-backup` se elimina (ya sea durante la actualización de la versión de la app o accidentalmente), el PV también se eliminará, lo que significa que todas las copias de seguridad guardadas en él se eliminarán.
Si no hay tal Clase de Almacenamiento disponible, después de que se aprovisione el PV, asegúrate de editar su política de recuperación y establecerla en "Retener" antes de almacenar copias de seguridad en él.
====


[#_existing_persistent_volume]
=== Volumen persistente existente

Selecciona un Volumen Persistente (PV) existente que se utilizará para almacenar tus copias de seguridad. Para información sobre cómo crear Volúmenes Persistentes en Rancher, consulta {xref-existing-storage-setup}#_2_add_a_persistentvolume_that_refers_to_the_persistent_storage[esta sección.]

[NOTE]
.Importante:
====

Se recomienda encarecidamente utilizar un Volumen Persistente con una política de recuperación de "Retener". De lo contrario, si la PVC creada por el gráfico `rancher-backup` se elimina (ya sea durante la actualización de la versión de la app o accidentalmente), el PV también se eliminará, lo que significa que todas las copias de seguridad guardadas en él se eliminarán.
====


[#_example_yaml_file_rancher_backup_helm_chart]
== Ejemplo de Archivo YAML: Helm Chart de copia de seguridad de Rancher

El archivo `values.yaml` documentado que se puede utilizar para configurar el `backup-restore-operator` cuando se utiliza la CLI de Helm se puede encontrar en el https://github.com/rancher/backup-restore-operator/blob/master/charts/rancher-backup/values.yaml[repositorio backup-restore-operator.]

Para más información sobre los archivos `values.yaml` y la configuración de charts de Helm durante la instalación, consulta la https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing[documentación de Helm.]
