= Configuration de l'emplacement de stockage de la sauvegarde
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/backup-restore-configuration/storage-configuration.adoc 
:product-path: rancher-admin/back-up-restore-and-disaster-recovery/configuration/storage.adoc
ifeval::["{build-type}" != "community"]
:xref-existing-storage-setup: xref:cluster-admin/manage-clusters/persistent-storage/set-up-existing-storage.adoc
:xref-dynamically-provision-new-storage: xref:cluster-admin/manage-clusters/persistent-storage/dynamically-provision-new-storage.adoc
:xref-rancher-backup-config: xref:rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-existing-storage-setup: xref:how-to-guides/nouveaux-guides-utilisateurs/gerer-des-clusters/créer-un-stockage-persistent-kubernetes/gerer-le-stockage-persistent/configurer-le-stockage-existant.adoc
:xref-dynamically-provision-new-storage: xref:how-to-guides/nouveaux-guides-utilisateurs/gerer-des-clusters/créer-un-stockage-persistent-kubernetes/gerer-le-stockage-persistent/provisionner-un-nouveau-stockage-de-manière-dynamique.adoc
:xref-rancher-backup-config: xref:reference-guides/backup-restore-configuration/backup-configuration.adoc
endif::[]

Configurez un emplacement de stockage où toutes les sauvegardes sont enregistrées par défaut. Vous aurez la possibilité de remplacer cela pour chaque sauvegarde, mais vous serez limité à l'utilisation d'un stockage d'objets compatible S3.

Un seul emplacement de stockage peut être configuré au niveau de l'opérateur.

[#_storage_location_configuration]
== Configuration de l'emplacement de stockage

[#_no_default_storage_location]
=== Aucun emplacement de stockage par défaut

Vous pouvez choisir de ne pas avoir d'emplacement de stockage configuré au niveau de l'opérateur. Si vous sélectionnez cette option, vous devez configurer un stockage d'objets compatible S3 comme emplacement de stockage pour chaque sauvegarde individuelle.

[#_s3_compatible_object_store]
=== Stockage d'objets compatible S3

|===
| Paramètre | Description

| Secret d'identifiants
| Choisissez les identifiants pour S3 parmi vos secrets dans Rancher. {xref-rancher-backup-config}#_example_credentialsecret[Exemple].

| Nom du bucket
| Entrez le nom du https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html[bucket S3] où les sauvegardes seront stockées. Par défaut{nbsp}: `rancherbackups`.

| Région
| La https://aws.amazon.com/about-aws/global-infrastructure/regions_az/[région AWS] où se trouve le bucket S3.

| Dossier
| Le https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html[dossier dans le bucket S3] où les sauvegardes seront stockées. Si ce champ est laissé vide, le comportement par défaut est de stocker les fichiers de sauvegarde dans le dossier [Root] du bucket S3.

| Noeud d'extrémité
| Le https://docs.aws.amazon.com/general/latest/gr/s3.html[point de terminaison S3]. Par exemple, `s3.us-west-2.amazonaws.com`.

| Point de terminaison CA
| Le certificat CA utilisé pour le point de terminaison S3. Par défaut{nbsp}: certificat CA encodé en base64

| insecureTLSSkipVerify
| Définir sur vrai si vous n'utilisez pas TLS.
|===

[#_existing_storageclass]
=== StorageClass existant

L'installation du chart `rancher-backup` en sélectionnant l'option StorageClass créera une Persistent Volume Claim (PVC), et Kubernetes provisionnera dynamiquement une Persistent Volume (PV) où toutes les sauvegardes seront enregistrées par défaut.

Pour des informations sur la création de classes de stockage, reportez-vous à {xref-dynamically-provision-new-storage}[cette section.]

[NOTE]
.Important :
====

Il est fortement recommandé d'utiliser une StorageClass avec une politique de récupération de "Retain". Sinon, si la PVC créée par le chart `rancher-backup` est supprimée (soit lors de la mise à niveau de l'appli, soit par accident), la PV sera également supprimée, ce qui signifie que toutes les sauvegardes enregistrées seront supprimées.
Si aucune StorageClass de ce type n'est disponible, après que la PV soit provisionnée, assurez-vous de modifier sa politique de récupération et de la définir sur "Retain" avant d'y stocker des sauvegardes.
====


[#_existing_persistent_volume]
=== Volume Persistant Existant

Sélectionnez un Volume Persistant (PV) existant qui sera utilisé pour stocker vos sauvegardes. Pour des informations sur la création de PersistentVolumes dans Rancher, reportez-vous à {xref-existing-storage-setup}#_2_add_a_persistentvolume_that_refers_to_the_persistent_storage[cette section.]

[NOTE]
.Important :
====

Il est fortement recommandé d'utiliser un Volume Persistant avec une politique de récupération de "Retain". Sinon, si la PVC créée par le chart `rancher-backup` est supprimée (soit lors de la mise à niveau de l'appli, soit par accident), la PV sera également supprimée, ce qui signifie que toutes les sauvegardes enregistrées seront supprimées.
====


[#_example_yaml_file_rancher_backup_helm_chart]
== Exemple de fichier YAML{nbsp}: Chart Helm de sauvegarde de Rancher

Le fichier `values.yaml` documenté qui peut être utilisé pour configurer le `backup-restore-operator` lors de l'utilisation de l'interface en ligne de commande Helm se trouve dans le https://github.com/rancher/backup-restore-operator/blob/master/charts/rancher-backup/values.yaml[dépôt backup-restore-operator.]

Pour plus d'informations sur les fichiers `values.yaml` et la configuration des charts Helm lors de l'installation, reportez-vous à la https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing[documentation Helm.]
