= {neuvector-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/neuvector/index.adoc 
:product-path: integrations/neuvector/neuvector.adoc

NeuVector es la única plataforma de seguridad de contenedores 100% de código abierto y Zero Trust. Escanea continuamente durante todo el ciclo de vida del contenedor. Elimina obstáculos de seguridad. Incorpora políticas de seguridad desde el principio para maximizar la agilidad de los desarrolladores. NeuVector proporciona análisis y gestión de vulnerabilidades y cumplimiento desde la creación hasta la producción. La protección en tiempo de ejecución única de NeuVector protege las conexiones de red dentro del clúster y el ingreso/egreso con un firewall de contenedores de capa 7. Además, NeuVector monitorea la actividad de procesos y archivos en contenedores y en hosts para terminar la actividad no autorizada.

[#__neuvector_product_name_with_rancher]
== {neuvector-product-name} con Rancher

Todas las características de NeuVector están disponibles a través de Rancher con despliegue integrado e inicio de sesión único en la consola de NeuVector. Los administradores de clústeres de Rancher pueden desplegar y gestionar la ampliación de NeuVector en sus clústeres y configurar fácilmente NeuVector a través de valores de Helm, configMaps, definiciones de recursos personalizadas (CRDs) y la consola de NeuVector.

Con NeuVector y Rancher:

* Desplegar, gestionar y proteger múltiples clústeres.
* Gestionar e informar vulnerabilidades y resultados de cumplimiento para cargas de trabajo y nodos de Rancher.

[#__neuvector_product_name_prime_with_rancher_prime]
== {neuvector-product-name} Prime con {rancher-prime}

La extensión de la interfaz de usuario de NeuVector para Rancher Manager está disponible y es compatible para clientes de Rancher Prime y NeuVector Prime. Esta extensión proporciona:

* Ampliación automatizada de NeuVector, incluyendo el panel de control de la extensión de NeuVector de Rancher Prime.
* Acceso a información de seguridad importante de cada clúster, como eventos de seguridad críticos, resultados de escaneo de vulnerabilidades y exposiciones de ingreso/egreso.
* Resultados de escaneo de vulnerabilidades (CVE) y cumplimiento integrados directamente en los recursos de Rancher, como nodos y contenedores/pods.
* Acciones integradas como activaciones manuales de escaneos en recursos de Rancher.
