= {rancher-product-name} 服务器和组件
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: reference-guides/rancher-manager-architecture/rancher-server-and-components.adoc 
:product-path: about-rancher/architecture/rancher-server-and-components.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-hosted-k8s-clusters: xref:如何指南/新用户指南/在Rancher中设置Kubernetes集群/从托管的Kubernetes提供商处设置集群/index.adoc
:xref-migrate-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster.adoc
endif::[]

大多数 Rancher 2.x 软件运行在 Rancher 服务器上。Rancher 服务器包含用于管理整个 Rancher 部署的所有软件组件。

下图展示了 Rancher 2.x 的高层架构。该图描绘了一个 Rancher 服务器安装，它管理两个下游 Kubernetes 集群：一个由 RKE2 创建，另一个由 Amazon EKS（弹性 Kubernetes 服务）创建。

为了获得最佳性能和安全性，我们建议为 Rancher 管理服务器使用专用的 Kubernetes 集群。不建议在此集群上运行用户工作负载。部署 Rancher 后，您可以 {xref-cluster-deployment}[创建或导入集群] 来运行您的工作负载。

该图显示了用户如何通过 Rancher 的身份验证代理操作 {xref-launch-k8s-with-rancher}[Rancher 启动的 Kubernetes] 集群和 {xref-hosted-k8s-clusters}[托管的 Kubernetes] 集群：

.通过 Rancher 的身份验证代理管理 Kubernetes 集群
image::rancher-architecture-rancher-api-server.svg[架构]

您可以在单个节点上安装 Rancher，或在高可用性 Kubernetes 集群上安装。

建议在生产环境中使用高可用性 Kubernetes 安装。

仅建议在开发和测试环境中使用 Rancher 的 Docker 安装。将 Rancher 迁移到高可用性集群的能力取决于 Rancher 版本。

要查看已部署的资源，请运行以下命令：

[,bash]
----
kubectl get all -n <namespace>
----

如果您拥有管理员权限，您还可以在 Rancher UI 中查看这些资源：

. 点击 *☰* 并选择一个集群。
. 从侧边导航菜单中选择 *更多资源* 以按类型查看已部署的资源。
. 从侧边导航菜单中选择 *集群* > *项目/名称空间*，然后选择一个名称空间，以按名称空间查看已部署的资源。
Rancher 备份操作员可用于将 Rancher 从单个 Docker 容器安装迁移到高可用性 Kubernetes 集群的安装。有关详细信息，请参阅关于 {xref-migrate-cluster}[将 Rancher 迁移到新集群] 的文档。

无论安装方法如何，Rancher 服务器应始终运行在与其管理的下游用户集群分开的节点上。如果 Rancher 安装在高可用性 Kubernetes 集群上，则应在与其管理的集群分开的集群上运行。
