= Configuração do Alertmanager
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

Geralmente, não é necessário editar diretamente o recurso personalizado do Alertmanager. Para a maioria dos casos de uso, você só precisará editar os Receivers e Routes para configurar as notificações.

Quando os Receivers e Routes são atualizados, o aplicativo de monitoramento atualizará automaticamente o recurso personalizado do Alertmanager para ser consistente com essas mudanças.

[NOTE]
====

Esta seção assume familiaridade com o funcionamento conjunto dos componentes de monitoramento. Para mais informações sobre o Alertmanager, consulte {xref-how-monitoring-works}#_3_how_alertmanager_works[esta seção.]
====


[#_about_the_alertmanager_custom_resource]
== Sobre o Recurso Personalizado do Alertmanager

Por padrão, o Rancher Monitoring implanta um único Alertmanager em um cluster que utiliza um Secret de Configuração do Alertmanager padrão.

Você pode querer editar o recurso personalizado do Alertmanager se desejar aproveitar opções avançadas que não estão expostas nos formulários da interface do Rancher, como a capacidade de criar uma estrutura de árvore de roteamento que tenha mais de dois níveis de profundidade.

Também é possível criar mais de um Alertmanager em um cluster, o que pode ser útil se você quiser implementar monitoramento com escopo de namespace. Nesse caso, você deve gerenciar os recursos personalizados do Alertmanager usando o mesmo Secret de Configuração do Alertmanager subjacente.

[#_deeply_nested_routes]
=== Rotas Profundamente Aninhadas

Enquanto a interface do Rancher suporta apenas uma árvore de roteamento de dois níveis, você pode configurar estruturas de roteamento mais profundamente aninhadas editando o YAML do Alertmanager.

[#_multiple_alertmanager_replicas]
=== Múltiplas Réplicas do Alertmanager

Como parte das opções de implantação do gráfico, você pode optar por aumentar o número de réplicas do Alertmanager implantadas em seu cluster. As réplicas podem ser gerenciadas usando o mesmo Secret de Configuração do Alertmanager subjacente.

Este Secret deve ser atualizado ou modificado sempre que você quiser:

* Adicionar novos notifiers ou receivers
* Alterar os alertas que devem ser enviados a notifiers ou receivers específicos
* Alterar o grupo de alertas que são enviados

Por padrão, você pode escolher fornecer um Secret de Configuração do Alertmanager existente (ou seja, qualquer Secret no namespace `cattle-monitoring-system`) ou permitir que o Rancher Monitoring implante um Secret de Configuração do Alertmanager padrão em seu cluster.

Por padrão, o Secret de Configuração do Alertmanager criado pelo Rancher nunca será modificado ou excluído durante o fazer upgrade ou desinstalação do `rancher-monitoring`gráfico. Essa restrição impede que os usuários percam ou sobrescrevam sua configuração de alertas ao executar operações no gráfico.

Para mais informações sobre quais campos podem ser especificados no Secret de Configuração do Alertmanager, consulte a documentação do https://prometheus.io/docs/alerting/latest/alertmanager/[Prometheus Alertmanager.]

A especificação completa para o arquivo de configuração do Alertmanager e o que ele requer pode ser encontrada https://prometheus.io/docs/alerting/latest/configuration/#configuration-file[aqui.]
