= Configuração do Prometheus
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

Geralmente, não é necessário editar diretamente o recurso personalizado do Prometheus, pois o aplicativo de monitoramento o atualiza automaticamente com base nas alterações nos ServiceMonitors e PodMonitors.

[NOTE]
====

Esta seção assume familiaridade com o funcionamento conjunto dos componentes de monitoramento. Para mais informações, consulte {xref-how-monitoring-works}[esta seção.]
====


[#_about_the_prometheus_custom_resource]
== Sobre o Recurso Personalizado do Prometheus

O CR do Prometheus define uma implantação desejada do Prometheus. O Operador do Prometheus observa o CR do Prometheus. Quando o CR muda, o Operador do Prometheus cria `prometheus-rancher-monitoring-prometheus`, uma implantação do Prometheus baseada na configuração do CR.

O CR do Prometheus especifica detalhes como regras e quais Alertmanagers estão conectados ao Prometheus. O Rancher cria esse CR para você.

O Monitoramento V2 suporta apenas um Prometheus por cluster. No entanto, você pode querer editar o CR do Prometheus se desejar limitar o monitoramento a certos namespaces.
