= {rancher-product-name} Inicio rápido de Equinix Metal
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/equinix-metal.adoc 
:product-path: installation-and-upgrade/quick-start/deploy-rancher/equinix-metal.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-qs-deploy-workloads: xref:installation-and-upgrade/quick-start/deploy-workloads/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-qs-deploy-workloads: xref:getting-started/quick-start-guides/deploy-workloads/index.adoc
endif::[]

[#_this_tutorial_walks_you_through_the_following]
== Este tutorial te guía a través de lo siguiente:

* Provisionamiento de un Servidor Equinix Metal
* Instalación de Rancher 2.x
* Creación de tu primer clúster
* Despliegue de una aplicación, Nginx

[CAUTION]
====

La intención de estas guías es lanzar rápidamente un entorno aislado que puedas utilizar para evaluar Rancher. La instalación de Docker no se recomienda para entornos de producción. Para instrucciones de configuración completas, consulta {xref-install-upgrade}[Instalación].
====


[#_quick_start_outline]
== Esquema de inicio rápido

Esta Guía de inicio rápido está dividida en diferentes tareas para facilitar su consumo.

[#_prerequisites]
== Requisitos previos

* Una https://deploy.equinix.com/developers/docs/metal/identity-access-management/users/[cuenta de Equinix Metal]
* Un https://deploy.equinix.com/developers/docs/metal/projects/creating-a-project/[proyecto de Equinix Metal]

[#_1_provision_a_equinix_metal_host]
=== 1. Provisionar un Host de Equinix Metal

Comienza a desplegar un Host de Equinix Metal. Los Servidores de Equinix Metal pueden ser provisionados desde la consola de Equinix Metal, API o CLI. Puedes encontrar instrucciones para cada tipo de despliegue en la https://deploy.equinix.com/developers/docs/metal/deploy/on-demand/[documentación de despliegue de Equinix Metal]. Puedes encontrar información adicional sobre los tipos de servidores de Equinix Metal en la https://deploy.equinix.com/developers/docs/metal/hardware/standard-servers/[Documentación de Equinix Metal].

[NOTE]
.Notas:
====

* Al provisionar un nuevo Servidor de Equinix Metal a través de la CLI o API, necesitarás proporcionar la siguiente información: project-id, plan, metro y sistema operativo.
* Al utilizar una máquina virtual alojada en la nube, necesitas permitir la comunicación TCP entrante a los puertos 80 y 443. Por favor, consulta la documentación de tu proveedor de nube para obtener información sobre la configuración de puertos.
* Para una lista completa de requisitos de puertos, consulta {xref-node-reqs}[Instalación de Docker].
* Provisiona el host de acuerdo a nuestros {xref-install-reqs}[Requisitos].
====


[#_2_install_rancher]
=== 2. Instalar Rancher

Para instalar Rancher en tu host de Equinix Metal, conéctate a él y luego utiliza una shell para instalar.

. Inicia sesión en tu host de Equinix Metal utilizando tu shell preferida, como PuTTy o una conexión de Terminal remota.
. Desde tu shell, introduce el siguiente comando:
+
----
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher
----

*Resultado:* Rancher está instalado.

[#_3_log_in]
=== 3. Iniciar sesión

Inicia sesión en Rancher para comenzar a utilizar la aplicación. Después de iniciar sesión, realizarás algunas configuraciones únicas.

. Abre un navegador web e introduce la dirección IP de tu host: `\https://<server_ip>`.
+
Sustituye `<SERVER_IP>` por la dirección IP de tu host.

. Cuando se te pida, crea una contraseña para la cuenta predeterminada `admin`.
. Establece la *URL del Servidor Rancher*. La URL puede ser una dirección IP o un nombre de host. Sin embargo, cada nodo añadido a tu clúster debe poder conectarse a esta URL. +
 +
Si utilizas un nombre de host en la URL, este nombre debe ser resoluble por DNS en los nodos que deseas añadir a tu clúster.

{blank}

[#_4_create_the_cluster]
=== 4. Crea el Clúster

¡Bienvenido a Rancher! Ahora puedes crear tu primer clúster de Kubernetes.

En esta tarea, puedes utilizar la versátil opción *Personalizada*. Esta opción te permite añadir _a cualquier_ host Linux (VM en la nube, VM en local o equipo sin sistema operativo) para usarlo en un clúster.

. Haz clic en *☰ > Gestión de Clústeres*.
. Desde la página *Clústeres*, haz clic en *Crear*.
. Elige *Personalizada*.
. Introduce un *Nombre del Clúster*.
. Haga clic en *Siguiente*.
. Desde *Rol del Nodo*, selecciona _todos_ los roles: *etcd*, *Control* y *Trabajador*.
 ** *Opcional*: Rancher detecta automáticamente las direcciones IP utilizadas para la comunicación de Rancher y la comunicación del clúster. Puedes anular estas utilizando `Public Address` y `Internal Address` en la sección *Dirección del Nodo*.
. Copia el comando de registro en tu portapapeles.
. Inicia sesión en tu host de Linux utilizando tu shell preferido, como PuTTy o una conexión de Terminal remota. Ejecuta el comando copiado en tu portapapeles.
. Cuando termines de ejecutar el comando en tu host de Linux, haz clic en *Hecho*.

*Resultado:*

Tu clúster se ha creado y se le ha asignado un estado de *Provisionando*. Rancher está configurando tu clúster.

Puedes acceder a tu clúster después de que su estado se actualice a *Activo*.

Los clústeres *Activos* están asignados a dos Proyectos:

* `Default`, que contiene el espacio de nombres `default`
* `System`, que contiene los espacios de nombres `cattle-system`, `traefik`, `kube-public` y `kube-system`

[#_finished]
==== Terminado

Enhorabuena. Has creado tu primer clúster.

[#_whats_next]
==== ¿Qué sigue?

Utiliza Rancher para crear un despliegue. Para más información, consulta {xref-qs-deploy-workloads}[Creando Despliegues].
