= Inicio rápido de Helm CLI
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 16-04-2026
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/helm-cli.adoc 
:product-path: installation-and-upgrade/quick-start/deploy-rancher/helm-cli.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-setup-ec2-nodes: xref:installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-bootstrap-password: xref:installation-and-upgrade/resources/bootstrap-password.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-setup-ec2-nodes: xref:how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-bootstrap-password: xref:getting-started/installation-and-upgrade/resources/bootstrap-password.adoc 
endif::[]

Estas instrucciones capturan una forma rápida de configurar una instalación de prueba de concepto de Rancher.

Estas instrucciones asumen que tienes una máquina virtual Linux con la que te comunicarás desde tu estación de trabajo local. Rancher se instalará en la máquina Linux. Necesitarás recuperar la dirección IP de esa máquina para poder acceder a Rancher desde tu estación de trabajo local. Rancher está diseñado para gestionar clústeres de Kubernetes de forma remota, por lo que cualquier clúster de Kubernetes que Rancher gestione en el futuro también necesitará poder alcanzar esta dirección IP.

No recomendamos instalar Rancher localmente porque crea un problema de red. Instalar Rancher en host local no permite que Rancher se comunique con clústeres de Kubernetes en sentido descendente, por lo que en host local no podrías probar la provisión de clústeres o la funcionalidad de gestión de clústeres de Rancher.

Tu máquina Linux puede estar en cualquier lugar. Podría ser una instancia de Amazon EC2, un droplet de Digital Ocean o una máquina virtual de Azure, por nombrar algunos ejemplos. Otros documentos de Rancher a menudo utilizan 'nodo' como un término genérico para todos estos. Una forma posible de desplegar una máquina Linux es configurando una instancia de Amazon EC2 como se muestra en {xref-setup-ec2-nodes}[este tutorial].

Los requisitos completos de instalación están {xref-install-reqs}[aquí].

[#_install_k3s_product_name_on_linux]
== Instalar {k3s-product-name} en Linux

Rancher debe instalarse en una versión de Kubernetes compatible. Para averiguar qué versiones de Kubernetes son compatibles con tu versión de Rancher, consulta la https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/[matriz de soporte de Rancher].

Para especificar la versión de K3s (Kubernetes), utiliza la variable de entorno INSTALL_K3S_VERSION (por ejemplo, `INSTALL_K3S_VERSION="v1.24.10+k3s1"`) al ejecutar el script de instalación de K3s.

Instala un clúster K3s ejecutando este comando en la máquina Linux:

----
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<VERSION> sh -s - server --cluster-init
----

Usar `--cluster-init` permite que K3s utilice etcd embebido como la base de datos y tiene la capacidad de convertirse en una configuración de alta disponibilidad. Consulta https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/[Alta Disponibilidad con DB Embebido].

Guarda la IP de la máquina Linux.

[#_save_the_kubeconfig_to_your_workstation]
== Guarda el kubeconfig en tu estación de trabajo

El archivo kubeconfig es importante para acceder al clúster de Kubernetes. Copia el archivo en `/etc/rancher/k3s/k3s.yaml` desde la máquina Linux y guárdalo en tu estación de trabajo local en el directorio `~/.kube/config`. Una forma de hacerlo es utilizando la herramienta `scp` y ejecutar este comando en tu máquina local:

[tabs]
======
Mac y Linux::
+
--
----
scp root@<IP_OF_LINUX_MACHINE>:/etc/rancher/k3s/k3s.yaml ~/.kube/config
----

En algunos casos, puede que necesites asegurarte de que tu shell tenga la variable de entorno `KUBECONFIG=~/.kube/config` definida; por ejemplo, se puede exportar en tu perfil o archivos rc.
--

Windows::
+
--
Por defecto, "scp" no es un comando reconocido, así que necesitamos instalar un módulo primero.

En Windows Powershell:

----
Find-Module Posh-SSH
Install-Module Posh-SSH

## Get the remote kubeconfig file
scp root@<IP_OF_LINUX_MACHINE>:/etc/rancher/k3s/k3s.yaml $env:USERPROFILE\.kube\config
----
--
====== 

[#_edit_the_rancher_server_url_in_the_kubeconfig]
== Edita la URL del servidor Rancher en el kubeconfig

En el archivo kubeconfig, necesitarás cambiar el valor del campo `server` a `<IP_OF_LINUX_NODE>:6443`. El servidor de la API de Kubernetes se alcanzará en el puerto 6443, mientras que el servidor de Rancher se alcanzará en los puertos 80 y 443. Esta edición es necesaria para que cuando ejecutes comandos de Helm o kubectl desde tu estación de trabajo local, puedas comunicarte con el clúster de Kubernetes en el que se instalará Rancher.

[tabs]
======
Mac y Linux::
+
--
Una forma de abrir el archivo kubeconfig para editar es usar Vim:

----
vi ~/.kube/config
----

Presiona `i` para poner Vim en modo de inserción. Para guardar tu trabajo, presiona `Esc`. Luego presiona `:wq` y presiona `Enter`.
--

Windows::
+
--
En Windows Powershell, puedes usar `notepad.exe` para editar el archivo kubeconfig:

----
notepad.exe $env:USERPROFILE\.kube\config
----

Una vez editado, presiona `ctrl+s` o ve a `File > Save` para guardar tu trabajo.
--
====== 

[#_install_rancher_with_helm]
== Instala Rancher con Helm

Luego, desde tu estación de trabajo local, ejecuta los siguientes comandos. Necesitarás tener https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl] y https://helm.sh/docs/intro/install/[helm] instalados.

[NOTE]
====

Para ver opciones sobre cómo personalizar la instalación de cert-manager (incluyendo casos donde tu clúster utiliza PodSecurityPolicies), consulta la https://artifacthub.io/packages/helm/cert-manager/cert-manager#configuration[documentación de cert-manager].
====


----
helm repo add rancher-prime <helm-chart-repo-url>
----

include::shared:ROOT:partial$en/helm-chart-repo-url.adoc[]

----
kubectl create namespace cattle-system

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/<VERSION>/cert-manager.crds.yaml

helm repo add jetstack https://charts.jetstack.io

helm repo update

helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace

# Windows Powershell
helm install cert-manager jetstack/cert-manager `
  --namespace cert-manager `
  --create-namespace
----

El comando final para instalar Rancher se encuentra a continuación. El comando requiere un nombre de dominio que redirija el tráfico a la máquina Linux. Por simplicidad en este tutorial, puedes usar un nombre de dominio falso para crear tu prueba de concepto. Un ejemplo de un nombre de dominio falso sería `<IP_OF_LINUX_NODE>.sslip.io`.

Para instalar una versión específica de Rancher, utiliza la bandera `--version` (por ejemplo, `--version 2.6.6`). De lo contrario, se instalará la última versión de Rancher por defecto.

Consulta {xref-bootstrap-password}#_password_requirements[Configuración de la Contraseña de Inicio] para los requisitos de la contraseña.

----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=<IP_OF_LINUX_NODE>.sslip.io \
  --set replicas=1 \
  --set bootstrapPassword=<PASSWORD_FOR_RANCHER_ADMIN>

# Windows Powershell

helm install rancher rancher-prime/rancher `
  --namespace cattle-system `
  --set hostname=<IP_OF_LINUX_NODE>.sslip.io `
  --set replicas=1 `
  --set bootstrapPassword=<PASSWORD_FOR_RANCHER_ADMIN>
----

Ahora, si navegas a `<IP_OF_LINUX_NODE>.sslip.io` en un navegador web, deberías ver la interfaz de usuario de Rancher.

Para simplificar estas instrucciones, utilizamos un nombre de dominio falso y certificados autofirmados para realizar esta instalación. Por lo tanto, probablemente necesitarás añadir una excepción de seguridad a tu navegador web para ver la interfaz de usuario de Rancher. Ten en cuenta que para instalaciones en producción, necesitarías una configuración de alta disponibilidad con un balanceador de carga, un nombre de dominio real y certificados reales.

Estas instrucciones también omitieron los requisitos completos de instalación y otras opciones de instalación. Si tienes algún problema con estos pasos, consulta la {xref-install-rancher}[documentación completa de instalación de Helm CLI.]

Para lanzar nuevos clústeres de Kubernetes con tu nuevo servidor Rancher, puede que necesites realizar la configuración de credenciales en la nube en Rancher. Para más información, consulta {xref-launch-k8s-with-rancher}[Lanzamiento de clústeres de Kubernetes con Rancher.]
