= ロールベースのアクセス制御
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: integrations-in-rancher/compliance-scans/rbac-for-compliance-scans.adoc 
:product-path: security/compliance-scans/rbac-for-compliance-scans.adoc

このセクションでは、rancher-complianceアプリを使用するために必要な権限について説明します。

rancher-complianceは、デフォルトではクラスター管理者専用の機能です。

ただし、`rancher-compliance` チャートはこれらの2つのデフォルト `ClusterRoles` をインストールします：

* compliance-admin
* compliance-view

Rancherでは、デフォルトでクラスターの所有者とグローバル管理者のみが`compliance-admin`アクセスを持っています。

[#_cluster_admin_access]
== クラスター管理者アクセス

Rancher Compliance Scansは、デフォルトではクラスター管理者専用の機能です。
これは、Rancherのグローバル管理者とクラスター所有者のみが次のことを行えることを意味します：

* rancher-complianceアプリをインストール/アンインストールする
* Compliance CRDのナビゲーションリンクを表示する - ClusterScanBenchmarks、ClusterScanProfiles、ClusterScans
* デフォルトのClusterScanBenchmarksおよびClusterScanProfilesを一覧表示する
* 新しいClusterScanProfilesを作成/編集/削除する
* クラスターでComplianceスキャンを実行するための新しいClusterScanを作成/編集/削除する
* ClusterScanが完了した後に作成されたClusterScanReportを表示およびダウンロードする

[#_summary_of_default_permissions_for_kubernetes_default_roles]
== Kubernetesのデフォルトロールに対するデフォルト権限の概要

rancher-complianceは3つの`ClusterRoles`を作成し、次のデフォルトのK8s `ClusterRoles`にCompliance Benchmark CRDアクセスを追加します：

|===
| チャートによって作成されたClusterRole | デフォルトのK8s ClusterRole | ロールに付与された権限

| `compliance-admin`
| `admin`
| clusterscanbenchmarks、clusterscanprofiles、clusterscans、clusterscanreports CRのCRUD機能

| `compliance-view`
| `表示 `
| (R) clusterscanbenchmarks、clusterscanprofiles、clusterscans、clusterscanreports CRをリストする機能
|===

デフォルトでは、クラスターオーナーの役割のみが `rancher-compliance` 機能を管理および使用する権限を持ちます。

他の Rancher の役割（クラスター メンバー、プロジェクト オーナー、プロジェクト メンバー）には、rancher-compliance リソースを管理および使用するためのデフォルトの権限はありません。

ただし、クラスターオーナーが他のユーザーにアクセスを委任したい場合は、これらのユーザーと上記のコンプライアンス クラスター ロールとの間に ClusterRoleBindings を手動で作成することで可能です。
`rancher-compliance` クラスター ロールに対して自動的なロール集約はサポートされていません。
