= Guia para a Aposentadoria do Ingress NGINX
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-25
:page-revdate: {revdate}
:community-path: how-to-guides/novos-guias-de-usuário/kubernetes-resources-setup/load-balancer-and-ingress-controller/guide-to-ingress-nginx-retirement.adoc 
:product-path: cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/guia-para-aposentadoria-do-Ingress.adoc
:description: Guia para a Aposentadoria do Ingress NGINX
ifeval::["{build-type}" != "community"]
:url-storage-longhorn-ingress-traefik: https://documentation.suse.com/cloudnative/storage/1.11/en/longhorn-system/system-access/longhorn-ingress-traefik.html
:url-continuous-delivery-webhook: https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/how-tos-for-users/webhook.html
:xref-rancher-on-amazon-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc#_5_install_an_ingress
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc#_5_install_an_ingress
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc#_7_install_an_ingress
endif::[]
ifeval::["{build-type}" == "community"]
:url-storage-longhorn-ingress-traefik: https://longhorn.io/docs/1.11.1/deploy/accessing-the-ui/longhorn-ingress-traefik/#additional-steps-for-aws-eks-kubernetes-clusters
:url-continuous-delivery-webhook: https://fleet.rancher.io/0.15/how-tos-for-users/webhook#_1_configure_the_webhook_service
:xref-rancher-on-amazon-eks: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-amazon-eks.adoc#_5_instalar_um_ingress
:xref-rancher-on-aks: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-aks.adoc#_5_instalar_um_ingress
:xref-rancher-on-gke: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-gke.adoc#_7_instalar_um_ingress
endif::[]

O SIG de Rede do Kubernetes e o Comitê de Resposta a Segurança anunciaram a https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/[aposentadoria do projeto Ingress NGINX]. A manutenção upstream de melhor esforço, e todos os lançamentos upstream associados, correções de bugs ou atualizações de segurança, terminaram em março de 2026.

Para apoiar os usuários durante essa transição, 

ifeval::["{build-type}" != "community"]
A SUSE fornece prazos de suporte estendidos e caminhos de migração claros para o Traefik. 
endif::[]
ifeval::["{build-type}" == "community"]
Rancher fornece caminhos de migração claros para o Traefik.
endif::[]

Este guia centraliza as informações sobre como proceder com base no seu cenário de implantação específico.

[#_support_and_timelines]
== Suporte e Prazos

ifeval::["{build-type}" != "community"]
Para organizações que não podem migrar imediatamente, {rancher-product-name} LTS fornece suporte estendido para a versão 1.35 do RKE2. 

[IMPORTANT]
.Suporte estendido para o Ingress NGINX
====
{rancher-product-name} LTS fornece patches para Vulnerabilidades e Exposições Comuns (CVEs) críticas e importantes para o componente Ingress NGINX até dezembro de 2027. Nenhum novo recurso será adicionado durante este período.
====
endif::[]

ifeval::["{build-type}" == "community"]
Os ciclos de vida do Rancher e do RKE2 estão alinhados com o cronograma de aposentadoria upstream.

[IMPORTANT]
====
Após março de 2026, as imagens do Ingress NGINX upstream não receberão mais atualizações. Qualquer imagem construída com patches após essa data é restrita a clientes comerciais. Os usuários devem migrar para o Traefik ou outro controlador de Ingress suportado antes deste prazo para garantir segurança e compatibilidade contínuas.
====
endif::[]

[#_migration_paths_by_environment]
== Caminhos de Migração por Ambiente

ifeval::["{build-type}" != "community"]
Para organizações prontas para a mudança, a SUSE oferece um caminho suportado para o Traefik. 
endif::[]
ifeval::["{build-type}" == "community"]
Os ciclos de vida do Rancher e do RKE2 estão alinhados com o cronograma de aposentadoria upstream.
endif::[]

O Traefik inclui uma camada de compatibilidade que pode interpretar muitas anotações existentes do Ingress NGINX. Identifique seu ambiente de cluster abaixo para encontrar a abordagem de migração correta.

[#_standalone_rke2_clusters]
=== Clusters RKE2 independentes

Para clusters RKE2 independentes ou importados que estão atualmente usando o Ingress NGINX, siga o https://support.scc.suse.com/s/kb/Migrating-from-Ingress-NGINX-to-Traefik-in-a-standalone-RKE2-cluster?language=en_US[guia de migração oficial para clusters RKE2 independentes]. 

O processo de migração envolve uma estratégia de quatro fases:

. *Configuração de controlador de Ingress duplo:* Ative o Traefik ao lado do Ingress NGINX usando portas temporárias e não conflitantes.
. *Migração e validação paralelas:* Duplique os recursos de Ingress e teste o processamento das anotações existentes pelo Traefik.
. *Troca final:* Remova o Ingress NGINX e configure o Traefik para usar as portas padrão.
. *Limpeza:* Exclua os objetos de Ingress legados.

[#_rancher_server_on_rke2_local_clusters]
=== Servidor Rancher no RKE2 (clusters locais)

Ao migrar um cluster local do Rancher, o recurso de Ingress do Rancher requer um tratamento específico para evitar bloqueios. Siga o https://support.scc.suse.com/s/kb/How-to-migrate-the-Rancher-Ingress-to-Traefik-in-an-RKE2-cluster?language=en_US[guia específico para migrar o Ingress do Rancher para o Traefik em um cluster RKE2]. Este guia se baseia nas fases de migração autônomas, mas inclui etapas adaptadas ao servidor de gerenciamento Rancher.

[#_downstream_rke2_clusters_provisioned_by_rancher]
=== Clusters RKE2 a jusante (Provisionados pelo Rancher)

Para clusters RKE2 provisionados e gerenciados pelo {rancher-product-name}, as opções de migração estão integradas diretamente na interface do usuário.

[NOTE]
====
ifeval::["{build-type}" != "community"]
Esta opção de migração é possível apenas no Rancher v2.13.5+ e v2.14.
endif::[]
ifeval::["{build-type}" == "community"]
Esta opção de migração é possível apenas no Rancher v2.14.0+.
endif::[]
====

A interface de configuração do cluster fornece uma opção de migração em modo dual. Isso permite que você teste e migre o tráfego do Ingress NGINX para o Traefik diretamente da tela de gerenciamento do cluster.

[#_rancher_on_managed_kubernetes_amazon_eks_azure_aks_google_gke]
=== Rancher em Kubernetes Gerenciado (Amazon EKS, Azure AKS, Google GKE)

Se você executar {rancher-product-name} em um serviço de Kubernetes gerenciado, como {xref-rancher-on-amazon-eks}[Amazon Elastic Kubernetes Service (EKS)], {xref-rancher-on-aks}[Azure Kubernetes Service (AKS)] ou {xref-rancher-on-gke}[Google Kubernetes Engine (GKE)], a recomendação é migrar para o Traefik. 

ifeval::["{build-type}" != "community"]
Os clientes do {rancher-product-name} podem aproveitar a Coleção de Aplicativos para implantar e gerenciar o proxy Traefik.
endif::[]
ifeval::["{build-type}" == "community"]
Os usuários devem implantar e migrar para a distribuição do proxy Traefik upstream.
endif::[]

ifeval::["{build-type}" != "community"]
[#_impact_on_other_suse_products]
== Impacto em Outros Produtos SUSE
endif::[]
ifeval::["{build-type}" == "community"]
[#_impact_on_projects]
== Impacto em Projetos
endif::[]

A aposentadoria do Ingress NGINX impacta outros 

ifeval::["{build-type}" != "community"]
produtos SUSE
endif::[]
ifeval::["{build-type}" == "community"]
projetos
endif::[]

das seguintes maneiras:

* {longhorn-product-name}: Não há impacto no backend do Longhorn. No entanto, os administradores devem reconfigurar seu Ingress para fazer upgrade da Longhorn UI. Para mais informações, consulte {url-storage-longhorn-ingress-traefik}[Criar um Ingress com Autenticação Básica Traefik].
* {fleet-product-name}: A configuração de um serviço de webhook é afetada. Consulte a {url-continuous-delivery-webhook}[documentação do Fleet] para mais informações.
* Referências do Ingress NGINX na documentação de outros projetos foram removidas.
