= Configuração de Balanceadores de Carga e Controladores de Ingress dentro de {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-23
:page-revdate: {revdate}
:community-path: procedimentos/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/index.adoc 
:product-path: cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/balanceador-de-carga-e-controlador-de-ingress.adoc
:description: Aprenda como você pode configurar balanceadores de carga e controladores de ingress para redirecionar solicitações de serviço dentro do Rancher e conheça as limitações dos balanceadores de carga
ifeval::["{build-type}" != "community"]
:xref-l4-l7-lb: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/camada-4-e-camada-7-balanceamento-de-carga.adoc
:xref-add-ingresses: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/add-ingresses.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-l4-l7-lb: xref:procedimentos/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/layer-4-and-layer-7-load-balancing.adoc
:xref-add-ingresses: xref:procedimentos/novos-guias/configuração-de-recursos-do-kubernetes/balanceador-de-carga-e-controlador-de-ingress/add-ingresses.adoc
endif::[]

Dentro do Rancher, você pode configurar balanceadores de carga e controladores de ingress para redirecionar solicitações de serviço.

[#_load_balancers]
== Balanceadores de Carga

Após lançar um aplicativo, o app está disponível apenas dentro do cluster. Ele não pode ser acessado de fora do cluster.

Se você quiser que seus aplicativos sejam acessíveis externamente, deve adicionar um balanceador de carga ou ingress ao seu cluster. Balanceadores de carga criam um gateway para conexões externas acessarem seu cluster, desde que o usuário conheça o endereço IP do balanceador de carga e o número da porta do aplicativo.

O Rancher suporta dois tipos de balanceadores de carga:

* xref:./layer-4-and-layer-7-load-balancing.adoc#_layer_4_load_balancer[Balanceadores de carga de Camada 4]
* xref:./layer-4-and-layer-7-load-balancing.adoc#_layer_7_load_balancer[Balanceadores de carga de Camada 7]

Para mais informações, veja {xref-l4-l7-lb}[balanceadores de carga].

[#_load_balancer_limitations]
=== Limitações dos Balanceadores de Carga

Os Balanceadores de Carga têm algumas limitações que você deve estar ciente:

* Os Balanceadores de Carga podem lidar com apenas um endereço IP por serviço, o que significa que se você executar vários serviços em seu cluster, deve ter um balanceador de carga para cada serviço. Executar múltiplos balanceadores de carga pode ser caro.
* Se você quiser usar um balanceador de carga com um cluster Kubernetes hospedado (ou seja, clusters hospedados no GKE, EKS ou AKS), o balanceador de carga deve estar em execução dentro da infraestrutura desse provedor de nuvem. Por favor, revise as tabelas de compatibilidade sobre o suporte a balanceadores de carga com base em como você provisionou seus clusters:
* xref:./layer-4-and-layer-7-load-balancing.adoc#_support_for_layer_4_load_balancing[Suporte para Balanceamento de Carga de Camada 4]
* xref:./layer-4-and-layer-7-load-balancing.adoc#_support_for_layer_7_load_balancing[Suporte para Balanceamento de Carga de Camada 7]

[#_ingress]
== Ingress

Conforme mencionado nas limitações acima, as desvantagens de usar um balanceador de carga são:

* Os Balanceadores de Carga podem lidar apenas com um endereço IP por serviço.
* Se você executar vários serviços em seu cluster, deve ter um balanceador de carga para cada serviço.
* Pode ser caro ter um balanceador de carga para cada serviço.

Em contraste, quando um ingress é usado como ponto de entrada em um cluster, o ingress pode direcionar o tráfego para vários serviços com maior flexibilidade. Ele pode mapear várias solicitações HTTP para serviços sem endereços IP individuais para cada serviço.

Portanto, é útil ter um ingress se você quiser que vários serviços sejam expostos com o mesmo endereço IP, o mesmo protocolo de camada 7 ou as mesmas portas de nó privilegiadas: 80 e 443.

O ingress funciona em conjunto com um ou mais controladores de ingress para direcionar dinamicamente as solicitações de serviço. Quando o ingress recebe uma solicitação, o(s) controlador(es) de ingress em seu cluster direcionam a solicitação para o serviço correto com base nos subdomínios de serviço ou nas regras de caminho que você configurou.

Seu ingress, que cria uma porta de entrada para seu cluster semelhante a um balanceador de carga, pode residir dentro do seu cluster ou externamente.

O ingress pode fornecer outras funcionalidades também, como terminação SSL, hospedagem virtual baseada em nome e mais.

* Para mais informações sobre como configurar ingress no Rancher, veja {xref-add-ingresses}[Ingress].
* Para informações completas sobre ingress e controladores de ingress, veja a https://kubernetes.io/docs/concepts/services-networking/ingress/[Documentação do Ingress do Kubernetes]
* Ao usar ingresses em um projeto, você pode programar o nome do host do ingress para um DNS externo configurando uma entrada de DNS Global.
