= Meilleures pratiques pour les clusters déconnectés
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-22
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-managed-clusters/disconnected-clusters.adoc 
:product-path: cluster-admin/best-practices/disconnected-clusters.adoc

Rancher prend en charge la gestion des clusters qui peuvent ne pas toujours être en ligne en raison de perturbations réseau, de la disponibilité du plan de contrôle ou parce que tous les nœuds du cluster sont hors service. Pour le moment, il n'y a aucun problème connu avec les clusters déconnectés dans la dernière version publiée de Rancher.

Lorsqu'un cluster géré est déconnecté de Rancher, les opérations de gestion ne seront pas disponibles, et l'interface utilisateur de Rancher ne permettra pas de naviguer vers le cluster. Cependant, une fois la connexion rétablie, la fonctionnalité est entièrement restaurée.

[#_best_practices_for_managing_disconnected_clusters]
== Meilleures pratiques pour la gestion des clusters déconnectés

* *Disponibilité des clusters pendant les mises à jour de Rancher*: Il est recommandé d'avoir tous, ou au moins la plupart, des clusters gérés en ligne pendant une mise à jour de Rancher. La raison en est que la mise à jour de Rancher met automatiquement à jour le logiciel de l'agent Rancher fonctionnant sur les clusters gérés. Maintenir les versions de l'agent et de Rancher alignées garantit une fonctionnalité cohérente. Tous les clusters qui sont déconnectés pendant la mise à jour auront leurs agents mis à jour dès qu'ils se reconnecteront.

* *Nettoyage des clusters déconnectés*: Supprimer régulièrement les clusters qui ne se reconnecteront plus à Rancher (par exemple, les clusters qui ont été désactivés ou détruits). Garder de tels clusters dans le système de gestion de Rancher consomme des ressources inutiles, ce qui pourrait affecter les performances de Rancher au fil du temps.

* *Considérations sur la rotation des certificats*: Lors de la conception de processus impliquant l'arrêt régulier des clusters, qu'ils soient connectés à Rancher ou non, tenez compte des politiques de rotation des certificats. Par exemple, les clusters RKE2/K3s peuvent renouveler les certificats au démarrage s'ils ont dépassé leur durée de vie.
