= グローバルデフォルトプライベートレジストリの設定
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/global-default-private-registry.adoc 
:product-path: rancher-admin/global-configuration/global-default-private-registry.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/index.adoc
endif::[]

[NOTE]
====
このページでは、Rancherがすでにインストールされた後に、Rancher UIからグローバルデフォルトプライベートレジストリを設定する方法について説明します。

Rancherのインストール中にプライベートレジストリを設定する方法については、{xref-air-gap}[エアギャップ(された)インストールガイド]を参照してください。
====


プライベートレジストリは、クラスター内のコンテナイメージのためのプライベートで一貫性のある中央集権的な真実のソースです。プライベートコンテナイメージレジストリを使用して、組織内でカスタムベースイメージを共有できます。

Rancherでプライベートレジストリを設定する主な方法は2つあります：

* グローバルビューの*設定*タブを通じてグローバルデフォルトレジストリを設定します。
* クラスター設定の高度なオプションでプライベートレジストリを設定します。

グローバルデフォルトレジストリは、認証情報を必要としないレジストリのために、エアギャップ構成で使用されることを意図しています。クラスターレベルのプライベートレジストリは、プライベートレジストリが認証情報を必要とする構成で使用されることを意図しています。

[#_set_a_private_registry_with_no_credentials_as_the_default_registry]
== 認証情報なしのプライベートレジストリをデフォルトレジストリとして設定する

. Rancherにログインし、デフォルトの管理者パスワードを設定します。
. *☰ > グローバル設定*を選択します。
. `system-default-registry`に移動し、*⋮ > 設定を編集*を選択します。
. レジストリのホスト名とポートを入力します（例：`registry.yourdomain.com:port`）。テキストの先頭に`http://`や`https://`を付けないでください。

*結果:*Rancherは、プライベートレジストリからシステムイメージを取得します。

[#_namespaced_private_registry_with_rke2_product_name_downstream_clusters]
=== {rke2-product-name}ダウンストリームクラスターを持つネームスペースのプライベートレジストリ

ほとんどのプライベートレジストリは、デフォルトでRKE2ダウンストリームクラスターと動作するはずです。

ただし、次のような形式のURLを持つネームスペースのプライベートレジストリを設定しようとする場合は、追加の手順が必要です：`website/subdomain:portnumber`。

. *☰ > クラスター管理*を選択します。
. リストからRKE2クラスターを見つけて、*⋮ > 設定を編集*をクリックします。
. *クラスター設定*メニューから、*レジストリ*を選択します。
. *レジストリ*ペインで、*高度なcontainerdミラーリングおよびレジストリアクセス認証オプションを設定する*オプションを選択します。
. *ミラー*の下のテキストフィールドに、*レジストリホスト名*と*ミラーエンドポイント*を入力します。
. ［*保存*］をクリックします。
. 各ダウンストリームRKE2クラスターについて必要に応じて繰り返します。

[#_configure_a_private_registry_with_credentials_when_creating_a_cluster]
== クラスター作成時に資格情報を使用してプライベートレジストリを設定する

すべてのRancherプロビジョニングクラスターに対して認証付きプライベートレジストリを設定するためのグローバルな方法はありません。したがって、Rancherプロビジョニングクラスターが資格情報を必要とするプライベートレジストリからイメージをプルする場合は、新しいクラスターを作成するたびに高度なクラスターオプションを通じてレジストリの資格情報を渡す必要があります。

プライベートレジストリはクラスター作成後に設定できないため、初期クラスターセットアップ中にこれらの手順を実行する必要があります。

. *☰ > クラスター管理*を選択します。
. *クラスター*ページで、*作成*をクリックします。
. クラスタータイプを選択します。
. *クラスター設定*で、*レジストリ*タブに移動します。
. *Rancherシステムコンテナイメージ用のクラスター範囲のコンテナレジストリを有効にする*の隣のボックスにチェックを入れます。
. レジストリホスト名を入力します。
. *認証*の下で、*HTTP基本認証シークレットを作成する*を選択し、資格情報フィールドに入力します。
. ［*作成*］をクリックします。

*結果:*新しいクラスターはプライベートレジストリからイメージをプルします。

[#_working_with_private_registry_credentials]
=== プライベートレジストリ資格情報の取り扱い

プライベートレジストリを扱う際は、これらのレジストリ用に作成されたシークレットが適切にバックアップされていることを確認することが重要です。Rancher GUIを通じてプライベートレジストリ資格情報シークレットを追加し、*HTTP基本認証シークレットを作成する*を選択すると、そのシークレットはRancherバックアップを使用したバックアップ操作に含まれます。

ただし、Rancher GUIの外で、kubectlやTerraformを使用して資格情報のシークレットを作成する場合は、Rancher Backupsによって作成されたバックアップにシークレットを含めるべきであることを示すために、`fleet.cattle.io/managed=true`ラベルを追加する必要があります。

たとえば、"my-private-registry"という名前のカスタムプライベートレジストリがあり、それに対して"my-reg-creds"というシークレットを作成する場合は、このシークレットに`fleet.cattle.io/managed=true`ラベルを適用してください。これにより、バックアッププロセスがシークレットをキャプチャし、必要に応じて簡単に復元できるようになります。

このガイダンスに従うことで、すべてのプライベートレジストリの資格情報がバックアップされ、復元や移行の際に簡単にアクセスできることを確保できます。
