= Configurando un Registro Privado Global por Defecto
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guías-prácticas/guías-para-nuevos-usuarios/autenticación-permisos-y-configuración-global/registro-privado-global-por-defecto.adoc 
:product-path: rancher-admin/global-configuration/global-default-private-registry.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap: xref:comenzando/instalación-y-actualización/otros-métodos-de-instalación/instalación-helm-cli-entorno-aislado/index.adoc
endif::[]

[NOTE]
====
Esta página describe cómo configurar un registro privado global por defecto desde la interfaz de usuario de Rancher, después de que Rancher ya esté instalado.

Para instrucciones sobre cómo configurar un registro privado durante la instalación de Rancher, consulta la {xref-air-gap}[guía de instalación en entorno aislado].
====


Un registro privado es una fuente de verdad privada, consistente y centralizada para las imágenes de contenedores en tus clústeres. Puedes utilizar un registro de imágenes de contenedores privado para compartir imágenes base personalizadas dentro de tu organización.

Hay dos formas principales de configurar un registro privado en Rancher:

* Configura un registro global por defecto a través de la pestaña *Configuración* en la vista global.
* Configura un registro privado en las opciones avanzadas bajo la configuración a nivel de clúster.

El registro global por defecto está destinado a ser utilizado en entornos aislados, para registros que no requieren credenciales. El registro privado a nivel de clúster está destinado a ser utilizado en configuraciones donde el registro privado requiere credenciales.

[#_set_a_private_registry_with_no_credentials_as_the_default_registry]
== Establecer un Registro Privado Sin Credenciales como el Registro por Defecto

. Inicia sesión en Rancher y configura la contraseña del administrador por defecto.
. Selecciona *☰ > Configuración Global*.
. Ve a `system-default-registry` y elige *⋮ > Editar Configuración*.
. Introduce el nombre de host y el puerto de tu registro (por ejemplo, `registry.yourdomain.com:port`). No precedas el texto con `http://` o `https://`.

*Resultado:* Rancher obtiene imágenes del sistema de tu registro privado.

[#_namespaced_private_registry_with_rke2_product_name_downstream_clusters]
=== Registro privado con espacio de nombres con {rke2-product-name} clústeres en sentido descendente.

La mayoría de los registros privados deberían funcionar, por defecto, con clústeres en sentido descendente de RKE2.

Sin embargo, necesitarás realizar algunos pasos adicionales si intentas configurar un registro privado con espacio de nombres cuya URL está formateada así: `website/subdomain:portnumber`.

. Selecciona *☰ > Gestión de Clústeres*.
. Encuentra el clúster RKE2 en la lista y haz clic en *⋮ >Editar Configuración*.
. Desde el menú *Configuración del clúster*, selecciona *Registros*.
. En el panel *Registros*, selecciona la opción *Configurar opciones avanzadas de espejado de containerd y autenticación de registro*.
. En los campos de texto bajo *Espejos*, introduce el *Nombre del Host del Registro* y los *puntos finales del espejo*.
. Haz clic en *Guardar*.
. Repite según sea necesario para cada clúster RKE2 en sentido descendente.

[#_configure_a_private_registry_with_credentials_when_creating_a_cluster]
== Configura un Registro Privado con Credenciales al Crear un Clúster

No hay una forma global de configurar un registro privado con autorización para cada clúster provisionado por Rancher. Por lo tanto, si deseas que un clúster provisionado por Rancher obtenga imágenes de un registro privado que requiere credenciales, tendrás que pasar las credenciales del registro a través de las opciones avanzadas del clúster cada vez que crees un nuevo clúster.

Dado que el registro privado no se puede configurar después de que se crea el clúster, necesitarás realizar estos pasos durante la configuración inicial del clúster.

. Selecciona *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, haz clic en *Crear*.
. Elige un tipo de clúster.
. En la *Configuración del Clúster* ve a la pestaña *Registros*.
. Marca la casilla junto a *Habilitar registro de contenedores con alcance de clúster para imágenes de contenedores del sistema Rancher*.
. Introduce el nombre del host del registro.
. Bajo *Autenticación* selecciona *Crear un Secreto de Autenticación HTTP Básica* y completa los campos de credenciales.
. Haga clic en *Crear*.

*Resultado:* El nuevo clúster obtiene imágenes del registro privado.

[#_working_with_private_registry_credentials]
=== Trabajando con Credenciales de Registro Privado

Al trabajar con registros privados, es importante asegurarse de que cualquier secreto creado para estos registros esté debidamente respaldado. Cuando añades un secreto de credencial de registro privado a través de la GUI de Rancher y seleccionas *Crear un Secreto de Autenticación HTTP Básica*, el secreto se incluye en las operaciones de copia de seguridad utilizando Rancher Backups.

Sin embargo, si creas un secreto de credencial fuera de la interfaz gráfica de Rancher, como utilizando kubectl o Terraform, debes añadir la etiqueta `fleet.cattle.io/managed=true` para indicar que el secreto debe ser incluido en las copias de seguridad creadas por Rancher Backups.

Por ejemplo, si tienes un registro privado personalizado llamado "mi-registro-privado" y creas un secreto llamado "my-reg-creds" para él, aplica la etiqueta `fleet.cattle.io/managed=true` a este secreto. Esto asegura que tu proceso de copia de seguridad capture el secreto, proporcionando una fácil restauración si es necesario.

Siguiendo esta guía, puedes asegurarte de que todas tus credenciales de registro privado estén respaldadas y sean fácilmente accesibles en caso de una restauración o migración.
