= Zu beitragen {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-14
:page-revdate: {revdate}
:community-path: contribute-to-rancher.adoc 
:product-path: contribute-to-rancher.adoc

Erfahren Sie mehr über die Repositories, die für Rancher und die Rancher-Dokumentation verwendet werden, wie man Rancher-Repositories erstellt und welche Informationen Sie angeben sollten, wenn Sie ein Problem melden.

Für detailliertere Informationen darüber, wie Sie zur Entwicklung von Rancher-Projekten beitragen können, beziehen Sie sich auf das https://github.com/rancher/rancher/wiki[Rancher Developer Wiki]. Das Wiki enthält Ressourcen zu vielen Themen, einschließlich der folgenden:

* Wie man die Rancher-Entwicklungsumgebung einrichtet und Tests durchführt
* Der typische Ablauf eines Problems im Entwicklungslebenszyklus
* Kodierungsrichtlinien und bewährte Entwicklungspraktiken
* Debuggen und Fehlersuche
* Entwicklung der Rancher API

Im Rancher Users Slack ist der Kanal für Entwickler *#developer*.

[#_rancher_docs]
== Rancher Dokumentation

Wenn Sie Vorschläge für die Dokumentation auf dieser Website haben, https://github.com/rancher/rancher-docs/issues/new/choose[öffnen] Sie ein Problem im Haupt- https://github.com/rancher/rancher-docs[Rancher docs]-Repository. Dieses Repository enthält Dokumentation für Rancher v2.0 und später.

Siehe das https://github.com/rancher/rancher-docs#readme[Rancher docs README] für weitere Details zum Beitragen und Erstellen des Rancher v2.x docs Repository.

Für Dokumentationen, die Rancher v1.6 und früher beschreiben, siehe das https://github.com/rancher/rancher.github.io[Rancher 1.x docs]-Repository, das Quelldateien für https://rancher.com/docs/rancher/v1.6/en/. enthält.

[#_rancher_repositories]
== Rancher Repositories

Alle Repositories befinden sich innerhalb unserer Haupt-GitHub-Organisation. Es gibt viele Repositories, die für Rancher verwendet werden, aber wir werden Beschreibungen einiger der wichtigsten bereitstellen, die in Rancher verwendet werden.

|===
| Repository | URL | Beschreibung

| Rancher
| https://github.com/rancher/rancher
| Dieses Repository ist der Hauptquellcode für Rancher 2.x.

| Arten
| https://github.com/rancher/types
| Dieses Repository ist das Repository, das alle API-Typen für Rancher 2.x enthält.

| API-Framework
| https://github.com/rancher/norman
| Dieses Repository ist ein API-Framework zum Erstellen von Rancher-Stil-APIs, die von Kubernetes Custom Resources unterstützt werden.

| User Interface
| https://github.com/rancher/dashboard/
| Dieses Repository ist die Quelle der Dashboard-Benutzeroberfläche.

| (Rancher) Docker Machine
| https://github.com/rancher/machine
| Dieses Repository ist die Quelle der Docker Machine-Binärdatei, die bei der Verwendung von Node-Treibern verwendet wird. Dies ist ein Fork des `docker/machine` Repositories.

| machine-package
| https://github.com/rancher/machine-package
| Dieses Repository wird verwendet, um die Rancher Docker Machine-Binärdatei zu erstellen.

| kontainer-engine
| https://github.com/rancher/kontainer-engine
| Dieses Repository ist die Quelle von kontainer-engine, dem Tool zur Bereitstellung von gehosteten Kubernetes-Clustern.

| CLI
| https://github.com/rancher/cli
| Dieses Repository ist der Quellcode für die Rancher CLI, die in Rancher 2.x verwendet wird.

| (Rancher) Helm-Repository
| https://github.com/rancher/helm
| Dieses Repository ist die Quelle der verpackten Helm-Binärdatei. Dies ist ein Fork des `helm/helm` Repositories.

| loglevel Repository
| https://github.com/rancher/loglevel
| Dieses Repository ist die Quelle der loglevel-Binärdatei, die verwendet wird, um die Protokollebene dynamisch zu ändern.
|===

Um alle Bibliotheken/Projekte zu sehen, die in Rancher verwendet werden, siehe die https://github.com/rancher/rancher/blob/master/go.mod[`go.mod` Datei] im `rancher/rancher` Repository.

.Rancher-Komponenten, die zur Bereitstellung/Verwaltung von Kubernetes-Clustern verwendet werden
image::ranchercomponentsdiagram-2.6.svg[Rancher-Diagramm]

[#_building_rancher_repositories]
=== Rancher-Repositories erstellen

Jedes Repository sollte ein Makefile haben und kann mit dem `make` Befehl erstellt werden. Die `make` Ziele basieren auf den Skripten im `/scripts` Verzeichnis des Repositories, und jedes Ziel wird https://github.com/rancher/dapper[Dapper] verwenden, um das Ziel in einer isolierten Umgebung auszuführen. Das `Dockerfile.dapper` wird für diesen Prozess verwendet und enthält alle notwendigen Build-Tools.

Das Standardziel ist `ci` und wird `./scripts/validate`, `./scripts/build`, `./scripts/test` und `./scripts/package` ausführen. Die resultierenden Binärdateien des Builds befinden sich in `./build/bin` und werden normalerweise auch in einem Docker-Image verpackt.

[#_rancher_bugs_issues_or_questions]
=== Rancher-Fehler, -Probleme oder -Fragen

Wenn Sie Fehler finden oder Probleme haben, suchen Sie bitte nach dem https://github.com/rancher/rancher/issues[gemeldeten Problem], da jemand möglicherweise dasselbe Problem erlebt hat oder wir aktiv an einer Lösung arbeiten.

Wenn Sie nichts finden können, das mit Ihrem Problem zusammenhängt, kontaktieren Sie uns, indem Sie https://github.com/rancher/rancher/issues/new[ein Problem melden]. Obwohl wir viele Repositories im Zusammenhang mit Rancher haben, möchten wir, dass die Fehler im Rancher-Repository gemeldet werden, damit wir sie nicht übersehen! Wenn Sie eine Frage stellen oder andere Benutzer zu einem Anwendungsfall fragen möchten, empfehlen wir, einen Beitrag in den https://forums.rancher.com[Rancher Foren] zu erstellen.

[#_checklist_for_filing_issues]
==== Checkliste für die Meldung von Problemen

Bitte folgen Sie dieser Checkliste, wenn Sie ein Problem melden, da sie uns hilft, das Problem zu untersuchen und zu beheben. Mehr Informationen bedeuten mehr Daten, die wir verwenden können, um zu bestimmen, was das Problem verursacht oder was möglicherweise mit dem Problem zusammenhängt.

[NOTE]
====

Für große Datenmengen verwenden Sie bitte https://gist.github.com/[GitHub Gist] oder ähnliches und verlinken Sie die erstellte Ressource im gemeldeten Problem.
====


[NOTE]
.Wichtig:
====

Bitte entfernen Sie alle sensiblen Daten, da diese öffentlich einsehbar sind.
====


* *Ressourcen:* Geben Sie so viele Details wie möglich zu den verwendeten Ressourcen an. Da die Ursache des Problems viele Dinge sein kann, hilft es, so viele Details wie möglich anzugeben, um die Grundursache zu bestimmen. Siehe einige Beispiele unten:
 ** *Hosts:* Welche Spezifikationen hat der Host, wie CPU/Speicher/Festplatte, auf welcher Cloud passiert es, welches Amazon Machine Image verwenden Sie, welchen DigitalOcean-Droplet verwenden Sie, welches Image stellen Sie bereit, das wir neu erstellen oder verwenden können, wenn wir versuchen, es zu reproduzieren.
 ** *Betriebssystem:* Welches Betriebssystem verwenden Sie? Spezifische Informationen helfen hier, wie die Ausgabe von `cat /etc/os-release` für die genaue OS-Version und `uname -r` für den genauen verwendeten Kernel.
 ** *Docker:* Welche Docker-Version verwenden Sie, wie haben Sie es installiert? Die meisten Details zu Docker finden Sie, indem Sie die Ausgaben von `docker version` und `docker info` bereitstellen.
 ** *Umgebung:* Befinden Sie sich in einer Proxy-Umgebung, verwenden Sie anerkannte CA-/selbstsignierte Zertifikate, verwenden Sie einen externen Lastenausgleich?
 ** *Rancher:* Welche Version von Rancher verwenden Sie? Dies kann unten links in der Benutzeroberfläche gefunden oder aus dem Image-Tag abgerufen werden, das Sie auf dem Host ausführen.
 ** *Cluster:* Welche Art von Cluster haben Sie erstellt, wie haben Sie diesen erstellt, was haben Sie angegeben, als Sie ihn erstellt haben?
* *Schritte zur Reproduktion des Problems:* Geben Sie so viele Details wie möglich dazu an, wie Sie in die gemeldete Situation gelangt sind. Dies hilft der Person, die Situation, in der Sie sich befinden, zu reproduzieren.
 ** Geben Sie manuelle Schritte oder Automatisierungsskripte an, die verwendet wurden, um von einem neu erstellten Setup zu der von Ihnen gemeldeten Situation zu gelangen.
* *Protokolle:* Geben Sie Daten/Protokolle von den verwendeten Ressourcen an.
 ** Rancher
  *** Docker-Installation

+
----
  docker logs \
  --timestamps \
  $(docker ps | grep -E "rancher/rancher:|rancher/rancher " | awk '{ print $1 }')
----
  *** Kubernetes-Installation mit `kubectl`

+

[NOTE]
====
Stellen Sie sicher, dass Sie die richtige kubeconfig konfiguriert haben (zum Beispiel `export KUBECONFIG=$PWD/kube_config_cluster.yml`, wenn Rancher auf einem Kubernetes-Cluster installiert ist) oder verwenden Sie das integrierte kubectl über die Benutzeroberfläche.
====

+
----
  kubectl -n cattle-system \
  logs \
  -l app=rancher \
  --timestamps=true
----

 ** Systemprotokollierung (diese könnten je nach Betriebssystem nicht alle vorhanden sein)
  *** `/var/log/messages`
  *** `/var/log/syslog`
  *** `/var/log/kern.log`
 ** Docker-Daemon-Protokollierung (diese könnten je nach Betriebssystem nicht alle vorhanden sein)
  *** `/var/log/docker.log`
* *Metriken:* Wenn Sie Leistungsprobleme haben, stellen Sie bitte so viele Daten (Dateien oder Screenshots) von Metriken zur Verfügung, die helfen können, herauszufinden, was los ist. Wenn Sie ein Problem mit einer Maschine haben, ist es hilfreich, die Ausgaben von `top`, `free -m`, `df` bereitzustellen, die Prozesse/Speicher/Festplattennutzung anzeigen.
