= Lançando Kubernetes em Novos Nós em um Provedor de Infraestrutura
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: guias-procedimentos/guias-para-novos-usuários/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-de-infraestrutura/index.adoc 
:product-path: cluster-deployment/infra-providers/infra-providers.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:url-rke2-introduction: https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
:xref-manage-node-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
:xref-cluster-templates: xref:cluster-admin/manage-clusters/cluster-templates.adoc
:xref-recommended-architecture: xref:cluster-deployment/production-checklist/recommended-cluster-architecture.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rke2-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-rke2.adoc
:url-rke2-introduction: https://docs.rke2.io/
:xref-infra-providers: xref:guias-procedimentos/guias-para-novos-usuários/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-de-infraestrutura/index.adoc
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
:xref-manage-node-drivers: xref:guias-procedimentos/guias-para-novos-usuários/autenticação-permissões-e-configuração-global/sobre-drivers-de-provisionamento/gerenciar-drivers-de-nós.adoc
:xref-cluster-templates: xref:how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc
:xref-recommended-architecture: xref:guias-procedimentos/guias-para-novos-usuários/clusters-kubernetes-no-rancher/configuração/lista-de-verificação-para-clusters-prontos-para-produção/arquitetura-recomendada-do-cluster.adoc
endif::[]

Quando você {xref-rke2-config}criar um cluster RKE2 usando uma configuração de máquina no Rancher, cada pool de nós resultante será exibido em uma nova aba **Pools de Máquinas**. Você pode ver os pools de máquinas fazendo o seguinte:

. Clique em *☰ > Gerenciamento de Cluster*.
. Clique no nome do cluster RKE2.

[#__rke2_product_name_clusters]
== {rke2-product-name} Clusters

O Rancher v2.6 introduz provisionamento para {url-rke2-introduction}[clusters RKE2] diretamente da interface do usuário do Rancher. RKE2, também conhecido como RKE Government, é uma distribuição Kubernetes totalmente compatível que se concentra na segurança e conformidade nos EUA. Governo Federal dos EUA.

[NOTE]
====

Para modelos de cluster RKE2, consulte {xref-cluster-templates}#_rke2_cluster_template[esta página] para informações adicionais.
====


[#_node_roles]
=== Funções de Nó

A CLI do RKE2 expõe duas funções, `server` e `agent`, que representam as funções de nó do Kubernetes `etcd` + `controlplane` e `worker`, respectivamente. Com a integração do RKE2 no Rancher v2.6, os pools de nós RKE2 podem representar atribuições de função mais detalhadas, de modo que as funções `etcd` e `controlplane` podem ser representadas.

A mesma funcionalidade de usar `etcd`, `controlplane` e `worker` nós é possível no RKE2 CLI utilizando flags e marcação de nós para controlar onde as cargas de trabalho e o mestre do Kubernetes são agendados. A razão pela qual essas funções não foram implementadas como funções de primeira-classe no RKE2 CLI é que o RKE2 é concebido como um conjunto de blocos de construção brutos que são melhor aproveitados por meio de um sistema de orquestração como o Rancher.

Em nossa {xref-recommended-architecture}[arquitetura de cluster recomendada], descrevemos quantos nós de cada função os clusters devem ter:

* Pelo menos três nós com a função etcd para sobreviver à perda de um nó.
* Pelo menos dois nós com a função controlplane para alta disponibilidade do componente mestre.
* Pelo menos dois nós com a função worker para reprogramação de cargas de trabalho em caso de falha de um nó.
