= CPU 和内存分配
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/cpu-and-memory-allocations.adoc 
:product-path: observability/istio/cpu-and-memory-allocations.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-config: xref:observability/istio/configuration/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] 自 Rancher v2.12.0 起已被弃用；请转向 https://apps.rancher.io[SUSE 应用程序集合] 版本的 Istio，以获得增强的安全性（包含在 SUSE Rancher Prime 订阅中）。
详细信息可以在 https://forums.suse.com/t/deprecation-of-rancher-istio/45043[此公告] 中找到。
====

本节描述了集群中 Istio 组件的最低推荐计算资源。

每个组件的 CPU 和内存分配是 <<_configuring_resource_allocations,可配置的。>>

在启用 Istio 之前，我们建议您确认您的 Rancher 工作节点具有足够的 CPU 和内存以运行 Istio 的所有组件。

[TIP]
====

在较大的部署中，强烈建议通过为每个 Istio 组件添加节点选择器，将基础设施放置在集群中的专用节点上。
====


下表显示了每个内核 Istio 组件在 CPU 和内存方面的最低推荐资源请求和限制摘要。

在 Kubernetes 中，资源请求表示工作负载不会在节点上部署，除非该节点至少具有指定数量的可用内存和 CPU。如果工作负载超过 CPU 或内存的限制，它可能会被终止或驱逐出节点。有关管理容器资源限制的更多信息，请参阅 https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/[Kubernetes 文档。]

|===
| 工作负载 | CPU - 请求 | 内存 - 请求 | CPU - 限制 | 内存 - 限制

| 入口网关
| 100m
| 128mi
| 2000m
| 1024mi

| 出口网关
| 100m
| 128mi
| 2000m
| 1024mi

| istiod
| 500m
| 2048mi
| 无限制
| 无限制

| proxy
| 10m
| 10mi
| 2000m
| 1024mi

| *总数:*
| *710m*
| *2314Mi*
| *6000m*
| *3072Mi*
|===

[#_configuring_resource_allocations]
== 配置资源分配

您可以单独配置每种类型的 Istio 组件的资源分配。本节包括每个组件的默认资源分配。

为了更容易将工作负载调度到节点，集群管理员可以减少组件的 CPU 和内存资源请求。然而，默认的 CPU 和内存分配是我们建议的最低值。

您可以在 https://istio.io/[官方 Istio 文档] 中找到有关 Istio 配置的更多信息。

要配置分配给 Istio 组件的资源，

. 单击 *☰ > 集群管理*。
. 转到您创建的集群并单击*Explore*.
. 在左侧导航栏中，点击*Apps*。
. 单击*已安装的应用程序*。
. 转到 `istio-system` 名称空间。在其中一个 Istio 工作负载中，例如 `rancher-istio`，单击 *⋮ > 编辑/升级*。
. 单击 *升级* 通过更改 values.yaml 编辑基础组件或添加 {xref-istio-config}#_overlay_file[覆盖文件]。有关编辑覆盖文件的更多信息，请参见 <<_editing_the_overlay_file,本节。>>
. 更改 CPU 或内存分配、每个组件将被调度到的节点或节点容忍度。
. 单击 *升级* 以推出更改。

*结果：*Istio 组件的资源分配已更新。

[#_editing_the_overlay_file]
=== 编辑覆盖文件

覆盖文件可以包含 https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec[Istio Operator 规格] 中的任意值。与 Istio 应用程序一起提供的覆盖文件仅是覆盖文件可能配置的一个示例。

只要文件包含 `kind: IstioOperator` 且 YAML 选项有效，该文件就可以用作覆盖。

在与 Istio 应用程序一起提供的示例覆盖文件中，以下部分允许您更改 Kubernetes 资源：

----
#      k8s:
#        resources:
#          requests:
#            cpu: 200m
----
