= 禁用Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/disable-istio.adoc 
:product-path: observability/istio/disable-istio.adoc

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] 自 Rancher v2.12.0 起已被弃用；请转向 https://apps.rancher.io[SUSE 应用程序集合] 版本的 Istio，以获得增强的安全性（包含在 SUSE Rancher Prime 订阅中）。
详细信息可以在 https://forums.suse.com/t/deprecation-of-rancher-istio/45043[此公告] 中找到。
====

本节描述如何在集群中卸载Istio或禁用名称空间或工作负载。

[#_uninstall_istio_in_a_cluster]
== 在集群中卸载Istio

要卸载Istio，

. 单击 *☰ > 集群管理*。
. 转到您创建的集群并单击*Explore*.
. 在左侧导航栏中，单击menu:APP[已安装的APP]。
. 在`istio-system`名称空间中，转到`rancher-istio`并单击*⋮ > 删除*。
. 在`rancher-istio`被删除后，您可以选择`istio-system`名称空间中所有剩余的APP并单击*删除*。

*结果：*集群中的`rancher-istio` APP被移除。Istio边车无法在集群中的任何工作负载上部署。

[NOTE]
====

您无法再禁用和重新启用您的Istio安装。如果您希望保存设置以供将来安装，请查看并保存单个YAML以供将来参考/重用。
====


*卸载故障排除:*如果您没有按照卸载步骤操作，您可能会在卸载过程中遇到警告：

`Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: unable to recognize "": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"`

这可能意味着几件事。您要么同时选择了`istio-system`名称空间中的所有APP并删除它们，要么在删除`rancher-istio`图表之前删除了`rancher-istio`图表依赖项。由于卸载未正确完成，您将在`istio-system`名称空间中留下资源，需要手动清理。避免手动清理的另一个选项是再次安装`rancher-istio`，然后按正确的顺序卸载它。

[#_disable_istio_in_a_namespace]
== 在名称空间中禁用Istio

. 单击 *☰ > 集群管理*。
. 转到您创建的集群并单击*探索*。
. 单击menu:集群[项目/名称空间]。
. 转到您希望启用Istio的名称空间并单击*⋮  > 启用Istio自动注入*。或者，单击名称空间，然后在名称空间详细信息页面上单击*⋮  > 启用Istio自动注入*。

*结果：*当工作负载在此名称空间中部署时，它们将没有Istio边车。

[#_remove_the_istio_sidecar_from_a_workload]
== 从工作负载中去除Istio边车

在名称空间中禁用Istio，然后重新部署其中的工作负载。它们将被部署而不带Istio边车。
