= Servidor de API de Extensão
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-20
:page-revdate: {revdate}
:community-path: api/extension-apiserver.adoc 
:product-path: api/extension-apiserver.adoc

O Rancher estende o Kubernetes com APIs adicionais registrando um servidor de API de extensão usando a https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/[Camada de Agregação de API do Kubernetes].

[#_aggregation_layer_is_required]
== Camada de Agregação de API é Necessária

A camada de agregação de API deve ser configurada no cluster local do Kubernetes para que o `v1.ext.cattle.io` `APIService` funcione corretamente. Se o `APIService` não receber uma solicitação de registro após o início do servidor Rancher, o pod falha com uma entrada de log indicando o erro. Se seus pods estão consistentemente falhando em detectar o registro, apesar de ter um cluster configurado corretamente, você pode aumentar o tempo limite configurando o `.Values.aggregationRegistrationTimeout` no Helm.

Nesta versão do Rancher, as versões do Kubernetes suportadas pelo RKE2/K3s têm a camada de agregação configurada e habilitada por padrão. No entanto, se você suspeitar que a configuração do seu cluster está incorreta, consulte a https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/[documentação da Camada de Agregação do Kubernetes] para informações sobre como configurar a camada de agregação.

[NOTE]
====
Se a distribuição subjacente do Kubernetes não suportar a camada de agregação, você deve migrar para uma distribuição do Kubernetes que suporte antes de atualizar.
====
