= Conditions préalables
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/adapter-requirements.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/adapter-requirements.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-on-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-on-eks: xref:démarrer/installation-et-mise-à-niveau/installer-mise-à-niveau-sur-un-cluster-kubernetes/rancher-sur-amazon-eks.adoc
endif::[]

[#_1_setting_up_license_manager_and_purchasing_support]
== 1. Configuration du gestionnaire de licences et achat de support

Tout d'abord, complétez le https://docs.aws.amazon.com/license-manager/latest/userguide/getting-started.html[première étape] de la configuration unique du gestionnaire de licences.
Ensuite, allez sur le Marketplace AWS. Localisez le "Pack de démarrage de conteneur de facturation de support premium Rancher". Achetez au moins un droit.

Si vous avez installé Rancher en utilisant l'offre "Configuration de Rancher" sur le Marketplace AWS, passez à <<_4_create_an_oidc_provider,Étape 4>>.

NOTE: Chaque droit donne accès à un support pour un certain nombre de nœuds. Vous pouvez acheter plus de licences si nécessaire par la suite.

[#_2_create_an_eks_cluster]
== 2. Créer un cluster EKS

Suivez la {xref-rancher-on-eks}[documentation de Rancher] pour créer un cluster EKS. Lorsque vous arrivez à l'{xref-rancher-on-eks}#_8_installer_le_chart_helm_de_rancher[étape finale pour installer Rancher], *interrompez et revenez à cette page*. Ce cluster devra répondre aux exigences suivantes{nbsp}:

* EKS version 1.22.
* Chaque nœud du cluster a accès au registre contenant Rancher et ses images associées.
* Chaque nœud du cluster a accès au dépôt ECR stockant l'adaptateur CSP.
* Chaque nœud du cluster a accès au service de gestion des licences.
* Chaque nœud du cluster a accès aux points de terminaison globaux pour le service STS.

[#_3_install_rancher]
== 3. Installer Rancher

En plus des options spécifiées pour installer Rancher dans la {xref-rancher-on-eks}#_8_install_the_rancher_helm_chart[documentation de Rancher], vous devrez également activer des métriques supplémentaires.
Cela peut être fait via le CLI Helm avec les options suivantes{nbsp}:

[,bash]
----
--set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
----

Vous pouvez également utiliser un fichier values.yaml comme ci-dessous{nbsp}:

[,yaml]
----
extraEnv:
  - name: "CATTLE_PROMETHEUS_METRICS"
    value: "true"
----

Vous devrez également installer Rancher version 2.6.7 ou supérieure.

[#_4_create_an_oidc_provider]
== 4. Créer un fournisseur OIDC

Suivez la https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html[documentation AWS] pour créer un fournisseur OIDC pour le cluster spécifié dans la section précédente.

[#_5_create_an_iam_role]
== 5. Créer un rôle IAM

Un rôle IAM est requis pour que l'adaptateur CSP puisse réaliser le check-in et le check-out des droits.

Tout d'abord, configurez la stratégie de confiance comme ci-dessous : Remplacez `MY_AWS_ACC` par votre numéro de compte AWS, `MY_AWS_REGION` par votre région AWS, et `MY_OIDC_PROVIDER` par l'identifiant de votre fournisseur OIDC{nbsp}:

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::${MY_AWS_ACC}:oidc-provider/oidc.eks.${MY_AWS_REGION}.amazonaws.com/id/${MY_OIDC_PROVIDER}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.${MY_AWS_REGION}.amazonaws.com/id/${MY_OIDC_PROVIDER}:sub": "system:serviceaccount:cattle-csp-adapter-system:rancher-csp-adapter",
                    "oidc.eks.${MY_AWS_REGION}.amazonaws.com/id/${MY_OIDC_PROVIDER}:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
----

Ensuite, utilisez une stratégie pour le rôle qui a les permissions suivantes :

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "RancherCSPAdapterPermissions",
            "Effect": "Allow",
            "Action": [
                "license-manager:ListReceivedLicenses",
                "license-manager:CheckoutLicense",
                "license-manager:ExtendLicenseConsumption",
                "license-manager:CheckInLicense",
                "license-manager:GetLicense",
                "license-manager:GetLicenseUsage"
            ],
            "Resource": "*"
        }
    ]
}
----

Enregistrez le nom du rôle. Vous en aurez besoin plus tard lors de l'installation de l'adaptateur CSP.
