= Aplicando Modelos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/sobre-modelos-rke1/aplicar-modelos.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/apply-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-access-share-rke1-templates: xref:procedimentos-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/sobre-modelos-rke1/acessar-ou-compartilhar-modelos.adoc
:xref-manage-rke1-templates: xref:procedimentos-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/sobre-modelos-rke1/gerenciar-modelos-rke1.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

Você pode criar um cluster a partir de um modelo RKE que você criou ou de um modelo que foi {xref-access-share-rke1-templates}[compartilhado com você.]

Modelos RKE podem ser aplicados a novos clusters.

Você pode <<_converting_an_existing_cluster_to_use_an_rke_template,salvar a configuração de um cluster existente como um modelo RKE.>> Então, as configurações do cluster só podem ser alteradas se o modelo for atualizado.

Você não pode mudar um cluster para usar um modelo RKE diferente. Você só pode atualizar o cluster para uma nova revisão do mesmo modelo.

[#_creating_a_cluster_from_an_rke_template]
== Criando um cluster a partir de um Modelo RKE

Para adicionar um cluster {xref-launch-k8s-with-rancher}[hospedado por um provedor de infraestrutura] usando um modelo RKE, siga estas etapas:

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique em *Criar* e escolha o provedor de infraestrutura.
. Forneça o nome do cluster e os detalhes do modelo de nó como de costume.
. Para usar um modelo RKE, na seção *Opções do Cluster*, marque a caixa para *Usar um modelo e revisão RKE existente*.
. Escolha um modelo RKE e uma revisão no menu suspenso.
. Opcional: Você pode editar qualquer configuração que o proprietário do modelo RKE marcou como *Permitir Sobrescrita do Usuário* quando o modelo foi criado. Se houver configurações que você deseja alterar, mas não tem a opção de fazê-lo, você precisará entrar em contato com o proprietário do modelo para obter uma nova revisão do modelo. Então, você precisará editar o cluster para atualizá-lo para a nova revisão.
. Clique em *Criar* para iniciar o cluster.

[#_updating_a_cluster_created_with_an_rke_template]
== Atualizando um cluster criado com um Modelo RKE

Quando o proprietário do modelo cria um modelo, cada configuração tem um interruptor na interface do Rancher que indica se os usuários podem sobrescrever a configuração.

* Se a configuração permitir uma sobrescrita do usuário, você pode atualizar essas configurações no cluster xref:[editando o cluster.]
* Se o interruptor estiver desligado, você não pode alterar essas configurações, a menos que o proprietário do cluster crie uma revisão do modelo que permita que você as sobrescreva. Se houver configurações que você deseja alterar, mas não tem a opção de fazê-lo, você precisará entrar em contato com o proprietário do modelo para obter uma nova revisão do modelo.

Se um cluster foi criado a partir de um modelo RKE, você pode editar o cluster para atualizar o cluster para uma nova revisão do modelo.

As configurações de um cluster existente podem ser <<_converting_an_existing_cluster_to_use_an_rke_template,salvas como um modelo RKE.>> Nessa situação, você também pode editar o cluster para atualizar o cluster para uma nova revisão do modelo.

[NOTE]
====

Você não pode mudar o cluster para usar um modelo RKE diferente. Você só pode atualizar o cluster para uma nova revisão do mesmo modelo.
====


[#_converting_an_existing_cluster_to_use_an_rke_template]
== Convertendo um Cluster Existente para Usar um Modelo RKE

Esta seção descreve como criar um modelo RKE a partir de um cluster existente.

Modelos RKE não podem ser aplicados a clusters existentes, exceto se você salvar as configurações de um cluster existente como um modelo RKE. Isso exporta as configurações do cluster como um novo modelo RKE e também vincula o cluster a esse modelo. O resultado é que o cluster só pode ser alterado se o {xref-manage-rke1-templates}#_atualizando_um_modelo[o modelo for atualizado,] e o cluster for atualizado para {xref-manage-rke1-templates}#_atualizando_um_cluster_para_usar_uma_nova_revisão_do_modelo[usar uma versão mais recente do modelo.]

Para converter um cluster existente para usar um modelo RKE,

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster que será convertido para usar um modelo RKE. Clique em *⋮  > Salvar como Modelo RKE*.
. Digite um nome para o modelo no formulário que aparece e clique em *Criar*.

*Resultados:*

* Um novo modelo RKE é criado.
* O cluster é convertido para usar o novo modelo.
* Novos clusters podem ser <<_creating_a_cluster_from_an_rke_template,criados a partir do novo modelo.>>
