= Sobrescrevendo Configurações do Modelo
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/sobre-modelos-rke1/sobrescrever-configurações-do-modelo.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/override-template-settings.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rke1-templates: xref:procedimentos-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/sobre-modelos-rke1/gerenciar-modelos-rke1.adoc
endif::[]

Quando um usuário cria um modelo RKE, cada configuração no modelo tem um interruptor na interface do Rancher que indica se os usuários podem sobrescrever a configuração. Esse interruptor marca essas configurações como *Permitir Sobrescrita pelo Usuário*.

Após um cluster ser criado com um modelo, os usuários finais não podem atualizar nenhuma das configurações definidas no modelo, a menos que o proprietário do modelo as tenha marcado como *Permitir Sobrescrita pelo Usuário*. No entanto, se o modelo for {xref-manage-rke1-templates}[atualizado para uma nova revisão] que altera as configurações ou permite que os usuários finais as mudem, o cluster pode fazer upgrade para uma nova revisão do modelo e as mudanças na nova revisão serão aplicadas ao cluster.

Quando qualquer parâmetro é definido como *Permitir Sobrescrita pelo Usuário* no modelo RKE, isso significa que os usuários finais precisam preencher esses campos durante a criação do cluster e podem editar essas configurações a qualquer momento depois.

O modelo *Permitir Sobrescrita pelo Usuário* do modelo RKE é útil para situações como:

* Os administradores sabem que algumas configurações precisarão da flexibilidade de serem frequentemente atualizadas ao longo do tempo
* Os usuários finais precisarão inserir suas próprias chaves de acesso ou chaves secretas, por exemplo, credenciais de nuvem ou credenciais para instantâneos de backup.
