= ConfigMaps
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc 
:product-path: cluster-admin/kubernetes-resources/configmaps.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
endif::[]

Mientras que la mayoría de los tipos de secretos de Kubernetes almacenan información sensible, https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/[ConfigMaps] almacenan información de configuración general, como un grupo de archivos de configuración. Debido a que los ConfigMaps no almacenan información sensible, pueden actualizarse automáticamente y, por lo tanto, no requieren que sus contenedores se reinicien tras la actualización (a diferencia de la mayoría de los tipos de secretos, que requieren actualizaciones manuales y un reinicio del contenedor para que surta efecto).

Los ConfigMaps aceptan pares clave-valor en formatos de cadena comunes, como archivos de configuración o blobs JSON. Después de subir un ConfigMap, cualquier carga de trabajo puede hacer referencia a él como una variable de entorno o un montaje de volumen.

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster que tiene la carga de trabajo que debería hacer referencia a un ConfigMap y haz clic en *Explorar*.
. En la barra de navegación izquierda, haz clic en menu:Más Recursos[Kernel> ConfigMaps].
. Haga clic en *Crear*.
. Introduce un *Nombre* para el ConfigMap.
+

[NOTE]
====
Kubernetes clasifica los ConfigMaps como https://kubernetes.io/docs/concepts/configuration/secret/[secretos], y no puede haber dos secretos en un proyecto o espacio de nombres que tengan nombres duplicados. Por lo tanto, para evitar conflictos, tus ConfigMaps deben tener un nombre único entre los otros certificados, registros y secretos dentro de tu espacio de trabajo.
====


. Selecciona el *Espacio de Nombres* al que deseas añadir el ConfigMap.
. En la pestaña *Datos*, añade un par clave-valor a tu ConfigMap. Añade tantos valores como necesites.  Puedes añadir múltiples pares clave-valor al ConfigMap copiando y pegando. Alternativamente, utiliza *Leer desde Archivo* para añadir los datos. Nota: Si necesitas almacenar datos sensibles, {xref-secrets}[usa un secreto], no un ConfigMap.
. Haga clic en *Crear*.

*Resultado:* Tu ConfigMap se ha añadido al espacio de nombres. Puedes verlo en la interfaz de usuario de Rancher desde la vista de menu:Recursos[ConfigMaps].

[#_whats_next]
== ¿Qué sigue?

Ahora que has añadido un ConfigMap a un espacio de nombres, puedes añadirlo a una carga de trabajo que despliegues desde el espacio de nombres de origen. Puedes usar el ConfigMap para especificar información que tu aplicación consuma, como:

* Variables de entorno de la aplicación.
* Especificando parámetros para un volumen montado en la carga de trabajo.

Para más información sobre cómo añadir ConfigMaps a una carga de trabajo, consulta {xref-deploy-workloads}[Desplegando Cargas de Trabajo].
