= Configuración de Recursos de Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/index.adoc 
:product-path: cluster-admin/kubernetes-resources/kubernetes-resources-setup.adoc
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-configmaps: xref:cluster-admin/kubernetes-resources/configmaps.adoc
:xref-workloads-and-pods: xref:cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:xref-http-encrypt: xref:security/encrypting-http.adoc
:xref-l4-l7-lb: xref:cluster-admin/recursos-kubernetes/balanceador-de-carga-y-controlador-de-ingress/balanceo-de-carga-capa-4-y-capa-7.adoc
:xref-k8s-docker-registries: xref:cluster-admin/kubernetes-resources/kubernetes-and-docker-registries.adoc
:xref-add-ingresses: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/add-ingresses.adoc
:xref-create-services: xref:cluster-admin/kubernetes-resources/create-services.adoc
:xref-upgrade-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/roll-back-workloads.adoc
:xref-add-sidecar: xref:cluster-admin/kubernetes-resources/workloads-and-pods/add-a-sidecar.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-configmaps: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc
:xref-workloads-and-pods: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc
:xref-http-encrypt: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc
:xref-l4-l7-lb: xref:guías-prácticas/nuevos-usuarios/configuración-recursos-kubernetes/balanceador-de-carga-y-controlador-de-ingress/balanceo-de-carga-capa-4-y-capa-7.adoc
:xref-k8s-docker-registries: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries.adoc
:xref-add-ingresses: xref:guías-prácticas/nuevos-usuarios/recursos-kubernetes-configuración/balanceador-de-carga-y-controlador-de-ingress/añadir-ingress.adoc
:xref-create-services: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/create-services.adoc
:xref-upgrade-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/roll-back-workloads.adoc
:xref-add-sidecar: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/add-a-sidecar.adoc
endif::[]

Puedes ver y manipular todos los recursos personalizados y los CRD en un clúster de Kubernetes desde la interfaz de usuario de Rancher.

[#_workloads]
== Cargas de trabajo

Despliega aplicaciones en los nodos de tu clúster utilizando {xref-workloads-and-pods}[workloads], que son objetos que contienen pods que ejecutan tus aplicaciones, junto con metadatos que establecen reglas para el comportamiento de la ampliación. Los workloads pueden ser desplegados dentro del ámbito de todo el clúster o dentro de un espacio de nombres.

Al desplegar un workload, puedes desplegar desde cualquier imagen. Hay una variedad de {xref-workloads-and-pods}#_workload_types[_workload_types[tipos de workloads] para elegir, que determinan cómo debe ejecutarse tu aplicación.

Tras la ampliación de un workload, puedes seguir trabajando con él. Puede:

* {xref-upgrade-workloads}[Actualizar versión] el workload a una versión más nueva de la aplicación que está ejecutando.
* {xref-roll-back-workloads}[Revertir] un workload a una versión anterior, si ocurre un problema durante la actualización de versión.
* {xref-add-sidecar}[Añadir un sidecar], que es un workload que apoya a un workload principal.

[#_load_balancing_and_ingress]
== Balance de la carga e Ingress

[#_load_balancers]
=== Balanceadores de Carga

Después de lanzar una aplicación, solo está disponible dentro del clúster. No se puede alcanzar externamente.

Si deseas que tus aplicaciones sean accesibles externamente, debes añadir un balance de la carga a tu clúster. Los balanceadores de carga crean una puerta de enlace para que las conexiones externas accedan a tu clúster, siempre que el usuario conozca la dirección IP del balanceador de carga y el número de puerto de la aplicación.

Rancher soporta dos tipos de balanceadores de carga:

* {xref-l4-l7-lb}#_layer_4_load_balancer[Layer-4 Load Balancers]
* {xref-l4-l7-lb}#_layer_7_load_balancer[Layer-7 Load Balancers]

Para más información, consulta {xref-l4-l7-lb}[balanceadores de carga].

[#_ingress]
==== Ingress

Los Balanceadores de Carga solo pueden manejar una dirección IP por servicio, lo que significa que si ejecutas múltiples servicios en tu clúster, debes tener un balanceador de carga para cada servicio. Ejecutar múltiples balanceadores de carga puede ser costoso. Puedes sortear este problema utilizando un ingress.

El ingress es un conjunto de reglas que actúan como un balance de la carga. El ingress funciona en conjunto con uno o más controladores de ingress para dirigir dinámicamente las solicitudes de servicio. Cuando el ingress recibe una solicitud, los controladores de ingress en tu clúster programan el balance de la carga para dirigir la solicitud al servicio correcto según los subdominios de servicio o las reglas de vía que hayas configurado.

Para más información, consulte {xref-add-ingresses}[Ingress].

Al usar ingress en un proyecto, puedes programar el nombre de host del ingress a un DNS externo configurando una entrada de DNS Global.

[#_service_discovery]
== Descubrimiento de servicios

Después de exponer tu clúster a solicitudes externas utilizando un balance de la carga y/o ingress, solo está disponible por dirección IP. Para crear un nombre de host resoluble, debes crear un registro de servicio, que es un registro que mapea una dirección IP, un nombre de host externo, un alias DNS, workload(s) o pods etiquetados a un nombre de host específico.

Para más información, consulte {xref-create-services}[Descubrimiento de Servicios].

[#_applications]
== Aplicaciones

Además de lanzar componentes individuales de una aplicación, puedes utilizar el catálogo de Rancher para comenzar a lanzar aplicaciones, que son gráficos de Helm.

[#_kubernetes_resources]
== Kubernetes Resources

Dentro del contexto de un proyecto o espacio de nombres de Rancher, _los recursos_ son archivos y datos que apoyan la operación de tus pods. Dentro de Rancher, los certificados, registros y secretos se consideran recursos. Sin embargo, Kubernetes clasifica los recursos como diferentes tipos de https://kubernetes.io/docs/concepts/configuration/secret/[secretos]. Por lo tanto, dentro de un solo proyecto o espacio de nombres, los recursos individuales deben tener nombres únicos para evitar conflictos. Aunque los recursos se utilizan principalmente para llevar información sensible, también tienen otros usos.

Los recursos incluyen:

* {xref-http-encrypt}[Certificados]: Archivos utilizados para cifrar/desencriptar datos que entran o salen del clúster.
* {xref-configmaps}[ConfigMaps]: Archivos que almacenan información de configuración general, como un grupo de archivos de configuración.
* {xref-secrets}[Secretos]: Archivos que almacenan datos sensibles, como contraseñas, tokens o claves.
* {xref-k8s-docker-registries}[Registros]: Archivos que llevan credenciales utilizadas para autenticar con registros privados.
