= Registro de Kubernetes y Registro de Imágenes de Contenedor
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries.adoc 
:product-path: cluster-admin/kubernetes-resources/kubernetes-and-docker-registries.adoc
:description: Aprende sobre el registro de imágenes de contenedor y el registro de Kubernetes, sus casos de uso y cómo utilizar un registro privado con la interfaz de usuario de Rancher
:experimental:

Los registros son secretos de Kubernetes que contienen credenciales utilizadas para autenticar con https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[registros de contenedores privados].

La palabra "registro" puede significar dos cosas, dependiendo de si se utiliza para referirse a un registro de contenedor o a un registro de Kubernetes:

* Un *Registro de imágenes de contenedor* (anteriormente "registro de Docker") contiene imágenes de contenedor que puedes extraer y desplegar. El registro es una aplicación del lado del servidor sin estado y escalable que almacena y te permite distribuir imágenes de contenedor.
* El *registro de Kubernetes* es un secreto de extracción de imágenes que tu despliegue utiliza para autenticar con un registro de imágenes.

Los despliegues utilizan el secreto del registro de Kubernetes para autenticar con un registro de imágenes privado y luego extraer una imagen de contenedor alojada en él.

Actualmente, los despliegues extraen las credenciales del registro privado automáticamente solo si la carga de trabajo se crea en la interfaz de usuario de Rancher y no cuando se crea a través de kubectl.

[#_creating_a_registry_in_namespaces]
== Crear un Registro en Espacios de Nombres

[NOTE]
.Requisito previo:
====

Debes tener un registro privado disponible ya desplegado.

Si necesitas crear un registro privado, consulta las páginas de documentación para tu entorno de ejecución respectivo:

* https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration[Containerd].
 ** https://github.com/containerd/nerdctl/blob/main/docs/registry.md[Comandos de Nerdctl y servicios de registro gestionados].
* https://docs.docker.com/registry/deploying/[Docker].
====


. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster donde deseas añadir un registro y haz clic en *Explorar*.
. En la navegación izquierda, haz clic en menu:Almacenamiento[Secretos] o en menu:Más Recursos[Kernel> Secretos].
. Haga clic en *Crear*.
. Haz clic en *Registro*.
. Introduce un *Nombre* para el registro.
+

[NOTE]
====
Kubernetes clasifica secretos, certificados y registros todos como https://kubernetes.io/docs/concepts/configuration/secret/[secretos], y no puede haber dos secretos en un proyecto o espacio de nombres con nombres duplicados. Por lo tanto, para evitar conflictos, tu registro debe tener un nombre único entre todos los secretos dentro de tu espacio de trabajo.
====


. Selecciona un espacio de nombres para el registro.
. Selecciona el sitio web que aloja tu registro privado. Luego, introduce las credenciales que autentiquen con el registro. Por ejemplo, si utilizas Docker Hub, proporciona tu nombre de usuario y contraseña de Docker Hub.
. Haz clic en *Guardar*.

*Resultado:*

* Tu secreto se añade al espacio de nombres que elegiste.
* Puedes ver el secreto en la interfaz de usuario de Rancher haciendo clic en menu:Almacenamiento[Secretos] o menu:Más Recursos[Kernel> Secretos].
* Cualquier carga de trabajo que crees en la interfaz de usuario de Rancher tendrá las credenciales para acceder al registro si la carga de trabajo está dentro del alcance del registro.

[#_creating_a_registry_in_projects]
== Creando un Registro en Proyectos

[NOTE]
.Requisitos previos:
====

Debes tener un registro privado disponible ya desplegado.

Si necesitas crear un registro privado, consulta las páginas de documentación para tu entorno de ejecución respectivo:

* https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration[Containerd].
 ** https://github.com/containerd/nerdctl/blob/main/docs/registry.md[Comandos de Nerdctl y servicios de registro gestionados].
* https://docs.docker.com/registry/deploying/[Docker].
====


Antes de la v2.6, se requería que los secretos estuvieran en un alcance de proyecto. Los proyectos ya no son obligatorios, y puedes utilizar el alcance de espacio de nombres en su lugar. Como resultado, la interfaz de usuario de Rancher se actualizó para reflejar esta nueva funcionalidad. Sin embargo, aún puedes crear un registro con alcance de proyecto si lo deseas. Utiliza los siguientes pasos para hacerlo:

. En la esquina superior izquierda, haz clic en *☰ > Configuración Global* en el menú desplegable.
. Haz clic en *Banderas de Características*.
. Ve a la bandera de características `legacy` y haz clic en *Activar*.
. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster donde deseas añadir un registro y haz clic en *Explorar*.
. En la navegación izquierda, haz clic en menu:Almacenamiento[Secretos] o en menu:Más Recursos[Kernel> Secretos].
. Haga clic en *Crear*.
. Haz clic en *Registro*.
. En la barra de navegación superior, filtra para ver solo un proyecto.
. Introduce un *Nombre* para el registro.
+

[NOTE]
====
Kubernetes clasifica secretos, certificados y registros todos como https://kubernetes.io/docs/concepts/configuration/secret/[secretos], y no puede haber dos secretos en un proyecto o espacio de nombres con nombres duplicados. Por lo tanto, para evitar conflictos, tu registro debe tener un nombre único entre todos los secretos dentro de tu espacio de trabajo.
====


. Selecciona un espacio de nombres para el registro.
. Selecciona el sitio web que aloja tu registro privado. Luego, introduce las credenciales que autentiquen con el registro. Por ejemplo, si utilizas Docker Hub, proporciona tu nombre de usuario y contraseña de Docker Hub.
. Haz clic en *Guardar*.

*Resultado:*

* Tu secreto se añade al proyecto individual que elegiste.
* Puedes ver el secreto en la interfaz de usuario de Rancher haciendo clic en menu:Almacenamiento[Secretos] o menu:Más Recursos[Kernel> Secretos].
* Cualquier carga de trabajo que crees en la interfaz de usuario de Rancher tendrá las credenciales para acceder al registro si la carga de trabajo está dentro del alcance del registro.

[NOTE]
====

Los registros con alcance de proyecto en el clúster local solo son visibles cuando se selecciona un único proyecto.
====


[#_using_a_private_registry]
== Usando un Registro Privado

Puedes desplegar una carga de trabajo con una imagen de un registro privado a través de la interfaz de usuario de Rancher, o con `kubectl`.

[#_using_the_private_registry_with_the_rancher_ui]
=== Usando el Registro Privado con la interfaz de usuario de Rancher

Para desplegar una carga de trabajo con una imagen de tu registro privado,

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster donde deseas desplegar una carga de trabajo y haz clic en *Explorar*.
. Haz clic en *Carga de trabajo*.
. Haga clic en *Crear*.
. Selecciona el tipo de carga de trabajo que deseas crear.
. Introduce un nombre único para la carga de trabajo y elige un espacio de nombres.
. En el campo *Imagen del Contenedor*, introduce la URL de la vía a la imagen en tu registro privado. Por ejemplo, si tu registro privado está en Quay.io, podrías usar `quay.io/<Quay profile name>/<Image name>`.
. Haga clic en *Crear*.

*Resultado:* Tu despliegue debería iniciarse, autenticarse usando las credenciales del registro privado que añadiste en la interfaz de usuario de Rancher, y extraer la imagen del contenedor que especificaste.

[#_using_the_private_registry_with_kubectl]
=== Usando el Registro Privado con kubectl

Cuando creas la carga de trabajo usando `kubectl`, necesitas configurar el pod para que su YAML tenga la vía a la imagen en el registro privado. También tienes que crear y referenciar el secreto del registro porque el pod solo obtiene acceso automáticamente a las credenciales del registro privado si se crea en la interfaz de usuario de Rancher.

El secreto tiene que ser creado en el mismo espacio de nombres donde se despliega la carga de trabajo.

A continuación se muestra un ejemplo `pod.yml` para una carga de trabajo que utiliza una imagen de un registro privado. En este ejemplo, el pod utiliza una imagen de Quay.io, y el .yml especifica la vía a la imagen. El pod se autentica con el registro usando credenciales almacenadas en un secreto de Kubernetes llamado `testquay`, que se especifica en `spec.imagePullSecrets` en el campo `name`:

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: quay.io/<Quay profile name>/<image name>
  imagePullSecrets:
  - name: testquay
----

En este ejemplo, el secreto llamado `testquay` está en el espacio de nombres predeterminado.

Puedes usar `kubectl` para crear el secreto con las credenciales del registro privado. Este comando crea el secreto llamado `testquay`:

----
kubectl create secret docker-registry testquay \
    --docker-server=quay.io \
    --docker-username=<Profile name> \
    --docker-password=<password>
----

Para ver cómo se almacena el secreto en Kubernetes, puedes usar este comando:

----
kubectl get secret testquay --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
----

El resultado se ve así:

----
{"auths":{"quay.io":{"username":"<Profile name>","password":"<password>","auth":"c291bXlhbGo6dGVzdGFiYzEyMw=="}}}
----

Después de que se despliegue la carga de trabajo, puedes comprobar si la imagen se ha extraído correctamente:

----
kubectl get events
----

El resultado debería verse así:

----
14s         Normal    Scheduled          Pod    Successfully assigned default/private-reg2 to minikube
11s         Normal    Pulling            Pod    pulling image "quay.io/<Profile name>/<image name>"
10s         Normal    Pulled             Pod    Successfully pulled image "quay.io/<Profile name>/<image name>"
----

Para más información, consulta la documentación de Kubernetes sobre https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret[creando un pod que utiliza tu secreto.]
