= Configurando o OpenLDAP
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/novos-usuarios/guias-de-autenticacao/permissoes-e-configuracao-global/configurar-openldap/index.adoc 
:product-path: rancher-admin/users/authn-and-authz/openldap/openldap.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-openldap-reference: xref:rancher-admin/users/authn-and-authz/openldap/reference.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:procedimentos/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/configuração-de-autenticação/index.adoc
:xref-openldap-reference: xref:procedimentos/novos-usuarios/guias-de-autenticacao/permissoes-e-configuracao-global/configurar-openldap/referencia-de-configuracao-openldap.adoc
endif::[]

Se sua organização usa LDAP para autenticação de usuários, você pode configurar o Rancher para se comunicar com um servidor OpenLDAP para autenticar usuários. Isso permite que os administradores do Rancher controlem o acesso a clusters e projetos com base em usuários e grupos gerenciados externamente no repositório central de usuários da organização, enquanto permite que os usuários finais se autentiquem com suas credenciais LDAP ao fazer login na interface do Rancher.

[#_prerequisites]
== Pré-requisitos

O Rancher deve ser configurado com uma conta de vinculação LDAP (também conhecida como conta de serviço) para buscar e recuperar entradas LDAP relacionadas a usuários e grupos que devem ter acesso. Recomenda-se não usar uma conta de administrador ou conta pessoal para esse propósito e, em vez disso, criar uma conta dedicada no OpenLDAP com acesso somente leitura a usuários e grupos sob a base de pesquisa configurada (veja abaixo).

____
*Usando TLS?*

Se o certificado usado pelo servidor OpenLDAP for autoassinado ou não for de uma autoridade certificadora reconhecida, certifique-se de ter em mãos o certificado CA (concatenado com quaisquer certificados intermediários) no formato PEM. Você terá que colar este certificado durante a configuração para que o Rancher consiga validar a cadeia de certificados.
____

[#_configure_openldap_in_rancher]
== Configure o OpenLDAP no Rancher

Configure as configurações para o servidor OpenLDAP, grupos e usuários. Para ajuda ao preencher cada campo, consulte a {xref-openldap-reference}[referência de configuração.]

____
Antes de prosseguir com a configuração, familiarize-se com os conceitos de {xref-authn-authz}#_external_authentication_configuration_and_principal_users[Configuração de Autenticação Externa e Usuários Principais].
____

. No canto superior esquerdo, clique em *☰ > Usuários e Autenticação*.
. No menu de navegação à esquerda, clique em *Provedor de Autenticação*.
. Clique em *OpenLDAP*. Preencha o formulário *Configurar um servidor OpenLDAP*.
. Clique em *Habilitar*.

[#_test_authentication]
=== Testar Autenticação

Uma vez que você tenha completado a configuração, prossiga testando a conexão com o servidor OpenLDAP. A autenticação com OpenLDAP será habilitada implicitamente se o teste for bem-sucedido.

[NOTE]
====

O usuário OpenLDAP referente às credenciais inseridas nesta etapa será mapeado para a conta principal local e receberá privilégios de administrador no Rancher. Portanto, você deve tomar uma decisão consciente sobre qual conta LDAP usar para realizar esta etapa.
====


. Insira o *nome de usuário* e a *senha* para a conta OpenLDAP que deve ser mapeada para a conta principal local.
. Clique em *Autenticar com OpenLDAP* para testar a conexão OpenLDAP e finalizar a configuração.

*Resultado:*

* A autenticação OpenLDAP está configurada.
* O usuário LDAP referente às credenciais inseridas é mapeado para a conta principal local (administrativa).

[NOTE]
====

Você ainda poderá fazer login usando a conta e senha `admin` configuradas localmente em caso de interrupção dos serviços LDAP.
====


[#_annex_troubleshooting]
== Anexo: Solução de problemas

Se você estiver enfrentando problemas ao testar a conexão com o servidor OpenLDAP, primeiro verifique novamente as credenciais inseridas para a conta de serviço, bem como a configuração da base de pesquisa. Você também pode inspecionar os logs do Rancher para ajudar a identificar a causa do problema. Os logs de depuração podem conter informações mais detalhadas sobre o erro. Por favor, consulte xref:faq/technical-items.adoc#_how_can_i_enable_debug_logging[Como posso habilitar o registro de depuração] nesta documentação.
