= Habilita Istio en el clúster.
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-cluster.adoc 
:product-path: observability/istio/guides/enable-istio-in-cluster.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-cpu-memory-allocations: xref:observability/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:observability/istio/configuration/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:observability/istio/configuration/project-network-isolation.adoc
:xref-istio-config: xref:observabilidad/istio/configuración/configuración.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-cpu-memory-allocations: xref:integrations-in-rancher/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:integrations-in-rancher/istio/configuration-options/project-network-isolation.adoc
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ha quedado obsoleto desde Rancher v2.12.0; recurran a la https://apps.rancher.io[SUSE Application Collection] de Istio para una mayor seguridad (incluida en las suscripciones de SUSE Rancher Prime).
Se puede encontrar información detallada en https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anuncio].
====

[NOTE]
.Requisitos previos:
====

* Solo un usuario con el `cluster-admin` https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles[rol predeterminado de Kubernetes] asignado puede configurar e instalar Istio en un clúster de Kubernetes.
* Para instalar Istio en un clúster RKE2, se requieren pasos adicionales. Para más detalles, consulta {xref-istio-on-rke2}[esta sección.]
* Para instalar Istio en un clúster donde el aislamiento de red del proyecto está habilitado, se requieren pasos adicionales. Para más detalles, consulta {xref-istio-project-network-isolation}[esta sección.]
====


. Haz clic en *☰ > Gestión de Clústeres*.
. Ve al lugar donde deseas habilitar Istio y haz clic en *Explorar*.
. Haz clic en *Apps*.
. Haz clic en *Charts*.
. Haz clic en *Istio*.
. Si no has instalado ya tu propia aplicación de monitoreo, se te pedirá que instales la aplicación rancher-monitoring. Opcional: Configura tus opciones de Selector o Scrape en la instalación de la aplicación rancher-monitoring.
. Opcional: Configura el acceso de miembros y {xref-istio-cpu-memory-allocations}[límites de recursos] para los componentes de Istio. Asegúrate de tener suficientes recursos en tus nodos de trabajo para habilitar Istio.
. Opcional: Realiza cambios de configuración adicionales en values.yaml si es necesario.
. Opcional: Agrega más recursos o configuración a través del {xref-istio-config}#_overlay_file[archivo de superposición].
. Haz clic en *Instalar*.

*Resultado:* Istio está instalado a nivel de clúster.

[#_additional_config_options]
== Opciones de configuración adicionales

Para más información sobre la configuración de Istio, consulta la {xref-istio-config}[referencia de configuración.]
