= Habilitar Istio en un espacio de nombres
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-namespace.adoc 
:product-path: observability/istio/guides/enable-istio-in-namespace.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-sidecar: xref:observability/istio/guides/use-istio-sidecar.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-sidecar: xref:how-to-guides/advanced-user-guides/istio-setup-guide/use-istio-sidecar.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ha quedado obsoleto desde Rancher v2.12.0; dirígete a la https://apps.rancher.io[colección de aplicaciones SUSE] de Istio para una mayor seguridad (incluida en las suscripciones de SUSE Rancher Prime).
Se puede encontrar información detallada en https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anuncio].
====

Necesitarás habilitar manualmente Istio en cada espacio de nombres que desees que sea rastreado o controlado por Istio. Cuando Istio está habilitado en un espacio de nombres, el proxy sidecar de Envoy se inyectará automáticamente en todas las nuevas cargas de trabajo que se desplieguen en el espacio de nombres.

Esta configuración de espacio de nombres solo afectará a las nuevas cargas de trabajo en el espacio de nombres. Cualquier carga de trabajo preexistente necesitará volver a desplegarse para aprovechar la inyección automática del sidecar.

[NOTE]
.Requisito previo:
====

Para habilitar Istio en un espacio de nombres, el clúster debe tener Istio instalado.
====


. Haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster que creaste y haz clic en *Explorar*.
. Haz clic en menu:Clúster[Proyectos/Espacios de nombres].
. Ve al espacio de nombres donde deseas habilitar Istio y haz clic en *⋮  > Habilitar inyección automática de Istio*. Alternativamente, haz clic en el espacio de nombres, y luego en la página de detalles del espacio de nombres, haz clic en *⋮  > Habilitar inyección automática de Istio*.

*Resultado:* El espacio de nombres ahora tiene la etiqueta `istio-injection=enabled`. Todas las nuevas cargas de trabajo desplegadas en este espacio de nombres tendrán el sidecar de Istio inyectado por defecto.

[#_verifying_that_automatic_istio_sidecar_injection_is_enabled]
== Verificando que la inyección automática del sidecar de Istio está habilitada

Para verificar que Istio está habilitado, despliega una carga de trabajo hello-world en el espacio de nombres. Ve a la carga de trabajo y haz clic en el nombre del pod. En la sección *Contenedores*, deberías ver el contenedor `istio-proxy`.

[#_excluding_workloads_from_being_injected_with_the_istio_sidecar]
== Excluyendo cargas de trabajo de ser inyectadas con el sidecar de Istio

Si necesitas excluir una carga de trabajo de ser inyectada con el sidecar de Istio, utiliza la siguiente anotación en la carga de trabajo:

----
sidecar.istio.io/inject: “false”
----

Para añadir la anotación a una carga de trabajo,

. Haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster que creaste y haz clic en *Explorar*.
. Haz clic en *Carga de trabajo*.
. Ve a la carga de trabajo que no debería tener el sidecar y edítala como yaml.
. Añade la siguiente clave, valor `sidecar.istio.io/inject: false` como anotación en la carga de trabajo
. Haz clic en *Guardar*.

*Resultado:* El sidecar de Istio no será inyectado en la carga de trabajo.

[NOTE]
====

Si tienes problemas con un Job que has desplegado que no se completa, necesitarás añadir esta anotación a tu pod siguiendo los pasos proporcionados. Dado que los sidecars de Istio se ejecutan indefinidamente, un Job no puede considerarse completo incluso después de que su tarea se haya completado.
====

[#__xref_istio_sidecar_next_add_deployments_with_the_istio_sidecar]
== {xref-istio-sidecar}[Siguiente: [Añadir Despliegues con el Sidecar de Istio]
