= Generar y ver tráfico desde Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/generate-and-view-traffic.adoc 
:product-path: observability/istio/guides/generate-and-view-traffic.adoc
ifeval::["{build-type}" != "community"]
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ha quedado obsoleto desde Rancher v2.12.0; recurran a la https://apps.rancher.io[SUSE Application Collection] de Istio para una mayor seguridad (incluida en las suscripciones de SUSE Rancher Prime).
Se puede encontrar información detallada en https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anuncio].
====

[#_the_kiali_traffic_graph]
== El gráfico de tráfico de Kiali

La página de resumen de Istio proporciona un enlace al panel de Kiali. Desde el panel de Kiali, puedes ver gráficos para cada espacio de nombres. El gráfico de Kiali proporciona una forma poderosa de visualizar la topología de tu malla de servicios de Istio. Te muestra qué servicios se comunican entre sí.

[#_prerequisites]
== Requisitos previos

Para habilitar que el tráfico aparezca en el gráfico, asegúrate de tener Prometheus instalado en el clúster. `Rancher-istio` instala Kiali y lo configura por defecto para trabajar con el gráfico `rancher-monitoring`. Puedes usar `rancher-monitoring` o instalar tu propia solución de monitoreo.

Además, para instalaciones de Istio versión `103.1.0+up1.19.6` y posteriores, Kiali utiliza un valor de token para su estrategia de autenticación. Si intentas generar o recuperar el token (por ejemplo, para iniciar sesión), ten en cuenta que el nombre de la cuenta de servicio de Kiali en Rancher es `kiali`. Para más información, consulta la https://kiali.io/docs/faq/authentication/[FAQ de autenticación de token de Kiali].

Opcional: Puedes configurar en qué espacios de nombres ocurre la recopilación de datos estableciendo las opciones del gráfico de Helm descritas en {xref-selectors-and-scrape-configurations}[Selectores y Configuraciones de Recopilación].

[#_traffic_visualization]
== Visualización del tráfico

Para ver el gráfico de tráfico, sigue los pasos a continuación:

. En el clúster donde está instalado Istio, haz clic en *Istio* en la barra de navegación izquierda.
. Haz clic en el enlace *Kiali*.
. Haz clic en *Gráfico* en la navegación lateral.
. Cambia el espacio de nombres en el menú desplegable *Espacio de nombres* para ver el tráfico de cada espacio de nombres.

Si actualizas la URL de la aplicación BookInfo varias veces, deberías poder ver flechas verdes en el gráfico de Kiali que muestran el tráfico hacia `v1` y `v3` del servicio `reviews`. El panel de control en el lado derecho del gráfico te permite configurar detalles, incluyendo cuántos minutos del tráfico más reciente deben mostrarse en el gráfico.

Para herramientas y visualizaciones adicionales, puedes ir a Grafana y a los paneles de Prometheus desde la página *Monitoreo* *Resumen*.
