= Benachrichtigungen für regelmäßigen Scan nach einem Zeitplan konfigurieren
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: anleitungen/erweiterte-benutzeranleitungen/compliance-scan-anleitungen/benachrichtigungen-für-regelmäßigen-scan-nach-einem-zeitplan-konfigurieren.adoc 
:product-path: security/compliance-scans/configure-alerts-for-periodic-scan-on-a-schedule.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
:xref-compliance-enable-alerting: xref:security/compliance-scans/enable-alerting-for-rancher-compliance.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
:xref-compliance-enable-alerting: xref:anleitungen/erweiterte-benutzeranleitungen/compliance-scan-anleitungen/benachrichtigungen-für-Rancher-Compliance-aktivieren.adoc
endif::[]

Es ist möglich, einen ClusterScan nach einem Zeitplan auszuführen.

Ein geplanter Scan kann auch angeben, ob Sie Benachrichtigungen erhalten sollen, wenn der Scan abgeschlossen ist.

Benachrichtigungen werden nur für einen Scan unterstützt, der nach einem Zeitplan ausgeführt wird.

Die Compliance-Anwendung unterstützt zwei Arten von Benachrichtigungen:

* Benachrichtigung bei Scan-Abschluss: Diese Benachrichtigung wird gesendet, wenn der Scan abgeschlossen ist. Die Benachrichtigung enthält Details, einschließlich des Namens des ClusterScans und des Namens des ClusterScanProfils.
* Benachrichtigung bei Scanfehler: Diese Benachrichtigung wird gesendet, wenn es während des Scanlaufs zu Testfehlern kommt oder wenn der Scan sich in einem `Fail` Zustand befindet.

[NOTE]
.Voraussetzung
====

Bevor Sie Benachrichtigungen für `rancher-compliance` aktivieren, stellen Sie sicher, dass Sie die `rancher-monitoring` Anwendung installiert und die Empfänger und Routen konfiguriert haben. Für weitere Informationen siehe {xref-receivers}[diesen Abschnitt.]

Beim Konfigurieren der Routen für `rancher-compliance` Benachrichtigungen können Sie die Übereinstimmung mit dem Schlüssel-Wert-Paar `job: rancher-compliance-scan` angeben. Ein Beispiel für eine Routen-Konfiguration ist {xref-receivers}#_beispiel_routen_config_für_compliance_scan_benachrichtigungen[hier.]
====


Um Benachrichtigungen für einen Scan zu konfigurieren, der nach einem Zeitplan ausgeführt wird,

. Bitte aktivieren Sie die Benachrichtigungen in der `rancher-compliance` Anwendung. Für weitere Informationen siehe {xref-compliance-enable-alerting}[diese Seite].
. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Cluster* zu dem Cluster, in dem Sie einen Compliance-Scan durchführen möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie auf *Compliance > Scan*.
. Klicken Sie auf *Erstellen*.
. Wählen Sie ein Cluster-Scan-Profil aus. Das Profil bestimmt, welche CIS-Benchmark-Version verwendet wird und welche Tests durchgeführt werden. Wenn Sie das Standardprofil wählen, wählt der Compliance-Operator ein Profil aus, das für den Typ des Kubernetes-Clusters, auf dem es installiert ist, anwendbar ist.
. Wählen Sie die Option *Scan nach einem Zeitplan ausführen*.
. Geben Sie einen gültigen https://en.wikipedia.org/wiki/Cron#CRON_expression[cron-Zeitplan-Ausdruck] im Feld *Zeitplan* ein.
. Aktivieren Sie die Kontrollkästchen neben den Benachrichtigungstypen unter *Benachrichtigungen*.
. Optional: Wählen Sie eine *Aufbewahrungsanzahl*, die die Anzahl der Berichte angibt, die für diesen wiederkehrenden Scan aufbewahrt werden. Standardmäßig beträgt diese Anzahl 3. Wenn dieses Aufbewahrungslimit erreicht ist, werden ältere Berichte gelöscht.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Der Scan wird ausgeführt und neu geplant, um gemäß dem angegebenen Cron-Zeitplan zu laufen. Benachrichtigungen werden gesendet, wenn der Scan abgeschlossen ist, sofern Routen und Empfänger unter der `rancher-monitoring` Anwendung konfiguriert sind.

Ein Bericht mit den Scan-Ergebnissen wird jedes Mal generiert, wenn der Scan ausgeführt wird. Um die neuesten Ergebnisse zu sehen, klicken Sie auf den Namen des Scans, der angezeigt wird.
