= Benachrichtigungen für {rancher-product-name} Compliance aktivieren
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: anleitung-guides/advanced-user-guides/compliance-scan-guides/benachrichtigungen-für-rancher-compliance-aktivieren.adoc 
:product-path: security/compliance-scans/enable-alerting-for-rancher-compliance.adoc
ifeval::["{build-type}" != "community"]
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
endif::[]

Benachrichtigungen können so konfiguriert werden, dass sie für einen Scan, der nach einem Zeitplan ausgeführt wird, versendet werden.

[NOTE]
.Voraussetzung:
====

Bevor Sie Benachrichtigungen für `rancher-compliance` aktivieren, stellen Sie sicher, dass Sie die `rancher-monitoring` Anwendung installiert und die Empfänger und Routen konfiguriert haben. Für weitere Informationen siehe {xref-receivers}[diesen Abschnitt.]

Beim Konfigurieren der Routen für `rancher-compliance` Benachrichtigungen können Sie die Übereinstimmung mit dem Schlüssel-Wert-Paar `job: rancher-compliance-scan` angeben. Ein Beispiel für eine Routen-Konfiguration ist {xref-receivers}#_beispiel_routen_config_für_compliance_scan_benachrichtigungen[hier.]
====


Beim Installieren oder Aktualisieren des `rancher-compliance` Helm-Chart setzen Sie das folgende Flag auf `true` in der `values.yaml`:

[,yaml]
----
alerts:
  enabled: true
----
