= Einen Scan regelmäßig nach einem Zeitplan ausführen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/compliance-scan-guides/run-a-scan-periodically-on-a-schedule.adoc 
:product-path: security/compliance-scans/run-a-scan-periodically-on-a-schedule.adoc
:experimental:

Um einen ClusterScan nach einem Zeitplan auszuführen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Cluster* zu dem Cluster, in dem Sie einen Compliance-Scan durchführen möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie auf *Compliance > Scan*.
. Wählen Sie ein Cluster-Scan-Profil aus. Das Profil bestimmt, welche CIS-Benchmark-Version verwendet wird und welche Tests durchgeführt werden. Wenn Sie das Standardprofil wählen, wählt der Compliance-Operator ein Profil aus, das für den Typ des Kubernetes-Clusters, auf dem es installiert ist, anwendbar ist.
. Wählen Sie die Option *Scan nach einem Zeitplan ausführen*.
. Geben Sie einen gültigen https://en.wikipedia.org/wiki/Cron#CRON_expression[cron-Zeitplan-Ausdruck] im Feld *Zeitplan* ein.
. Wählen Sie eine *Retention*-Anzahl, die angibt, wie viele Berichte für diesen wiederkehrenden Scan aufbewahrt werden. Standardmäßig beträgt diese Anzahl 3. Wenn dieses Aufbewahrungslimit erreicht ist, werden ältere Berichte gelöscht.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Der Scan wird ausgeführt und neu geplant, um gemäß dem angegebenen Cron-Zeitplan zu laufen. Der *Next Scan*-Wert gibt an, wann dieser Scan das nächste Mal ausgeführt wird.

Ein Bericht mit den Scan-Ergebnissen wird jedes Mal generiert, wenn der Scan ausgeführt wird. Um die neuesten Ergebnisse zu sehen, klicken Sie auf den Namen des Scans, der angezeigt wird.

Sie können auch die vorherigen Berichte einsehen, indem Sie einen Bericht aus dem *Reports*-Dropdown auf der Detailseite des Scans auswählen.
