= Einen Scan ausführen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/compliance-scan-guides/run-a-scan.adoc 
:product-path: security/compliance-scans/run-a-scan.adoc
:experimental:

Wenn eine ClusterScan-Custom-Ressource erstellt wird, startet sie einen neuen Compliance-Scan im Cluster für das gewählte ClusterScan-Profil.

[NOTE]
====
Derzeit gibt es eine Einschränkung, dass nur ein Compliance-Scan gleichzeitig für einen Cluster ausgeführt werden kann. Wenn Sie mehrere ClusterScan-Custom-Ressourcen erstellen, werden diese nacheinander vom Operator ausgeführt, und bis ein Scan abgeschlossen ist, befinden sich die restlichen ClusterScan-Custom-Ressourcen im Status "Ausstehend".
====


Um einen Scan durchzuführen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Cluster* zu dem Cluster, in dem Sie einen Compliance-Scan durchführen möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie auf *Compliance > Scan*.
. Klicken Sie auf *Erstellen*.
. Wählen Sie ein ClusterScan-Profil aus. Das Profil bestimmt, welche CIS-Benchmark-Version verwendet wird und welche Tests durchgeführt werden. Wenn Sie das Standardprofil wählen, wählt der Compliance-Operator ein Profil aus, das für den Typ des Kubernetes-Clusters, auf dem er installiert ist, anwendbar ist.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Ein Bericht wird mit den Scan-Ergebnissen erstellt. Um die Ergebnisse zu sehen, klicken Sie auf den Namen des angezeigten Scans.
