= Berichte ansehen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/compliance-scan-guides/view-reports.adoc 
:product-path: security/compliance-scans/view-reports.adoc
:experimental:

Um die generierten Compliance-Scan-Berichte anzuzeigen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite **Cluster** zu dem Cluster, in dem Sie einen Compliance-Scan durchführen möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie auf *Compliance > Scan*.
. Die Seite *Scans* zeigt die generierten Berichte an. Um einen detaillierten Bericht zu sehen, gehen Sie zu einem Compliance-Scan-Bericht und klicken Sie auf den Namen.

Man kann den Bericht aus der Liste der Scans oder von der Detailseite des Scans herunterladen.

Um die ausführliche Version der Ergebnisse des Compliance-Scans zu erhalten, führen Sie den folgenden Befehl auf dem gescannten Cluster aus. Beachten Sie, dass der Scan abgeschlossen sein muss, bevor dies durchgeführt werden kann.

[,shell]
----
export REPORT="scan-report-name"
kubectl get clusterscanreports.compliance.cattle.io $REPORT -o json |jq ".spec.reportJSON | fromjson" | jq -r ".actual_value_map_data" | base64 -d | gunzip | jq .
----
