= Zugriff auf Cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/access-clusters/index.adoc 
:product-path: cluster-admin/manage-clusters/access-clusters/access-clusters.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
:xref-user-api-keys: rancher-admin/users/settings/api-keys.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-manage-rbac: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc
:xref-add-users-to-clusters: xref:cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
:xref-user-api-keys: xref:reference-guides/user-settings/api-keys.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
:xref-manage-rbac: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/index.adoc
:xref-add-users-to-clusters: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/add-users-to-clusters.adoc
endif::[]

In diesem Abschnitt geht es darum, welche Werkzeuge verwendet werden können, um auf von Rancher verwaltete Cluster zuzugreifen.

Für Informationen, wie Sie Benutzern die Berechtigung zum Zugriff auf einen Cluster erteilen, siehe den Abschnitt über {xref-add-users-to-clusters}[Benutzer zu Clustern hinzufügen.]

Für weitere Informationen zur rollenbasierten Zugriffskontrolle siehe {xref-manage-rbac}[diesen Abschnitt.]

Für Informationen, wie Sie ein Authentifizierungssystem einrichten, siehe {xref-authn-authz}[diesen Abschnitt.]

[#_clusters_in_rancher_ui]
== Cluster in der Rancher-Benutzeroberfläche

Es gibt mehrere Wege, um Cluster über die Rancher-Benutzeroberfläche anzuzeigen und zu verwalten.

[#_clusters_page]
=== Cluster-Seite

Sie können die *Cluster* Seite über das *☰* Menü aufrufen:

. Klicken Sie auf *☰*.
. Wählen Sie *Clusterverwaltung*.

Sie können auch auf die *Cluster*-Seite zugreifen, indem Sie auf die *Verwalten*-Schaltfläche über der Cluster-Tabelle auf der Rancher UI *Startseite* klicken.

Auf der *Cluster*-Seite wählen Sie *⁝* am Ende jeder Zeile, um ein Untermenü mit den folgenden Optionen anzuzeigen:

* {xref-access-cluster-kubectl}[Kubectl-Shell]
* KubeConfig herunterladen
* KubeConfig in die Zwischenablage kopieren
* Konfiguration bearbeiten
* YAML anzeigen
* YAML herunterladen

[#_cluster_dashboard]
=== Cluster-Dashboard

Auf der *Cluster*-Seite wählen Sie die *Erkunden*-Schaltfläche am Ende jeder Zeile, um das *Cluster-Dashboard* dieses Clusters anzuzeigen. Sie können das Dashboard auch anzeigen, indem Sie auf den Namen eines Clusters in der Tabelle klicken und anschließend die *Erkunden*-Schaltfläche auf der *Cluster*-Seite klicken.

Das *Cluster-Dashboard* ist auch von der Rancher UI *Startseite* aus zugänglich, indem Sie auf den Namen eines Clusters klicken.

Sie können auch auf das *Cluster-Dashboard* über das *☰* in der oberen Navigationsleiste zugreifen:

. Klicken Sie auf *☰*.
. Wählen Sie den Namen eines Clusters aus der Menüoption *Cluster erkunden* aus.

Das *Cluster-Dashboard* listet Informationen über einen bestimmten Cluster auf, wie z.B. die Anzahl der Knoten, den Speicherverbrauch, Ereignisse und Ressourcen.

[#_kubectl]
== kubectl

Sie können das Kubernetes-Kommandozeilenwerkzeug https://kubernetes.io/docs/reference/kubectl/overview/[kubectl] verwenden, um Ihre Cluster zu verwalten. Sie haben zwei Optionen zur Verwendung von kubectl:

* *Rancher kubectl-Shell:* Interagieren Sie mit Ihren Clustern, indem Sie eine kubectl-Shell starten, die in der Rancher UI verfügbar ist. Diese Option erfordert keine Konfigurationsmaßnahmen Ihrerseits. Für weitere Informationen siehe {xref-access-cluster-kubectl}[Zugriff auf Cluster mit kubectl Shell].
* *Remote-Terminalverbindung:* Sie können auch mit Ihren Clustern interagieren, indem Sie https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl] auf Ihrem lokalen Desktop installieren und dann die kubeconfig-Datei des Clusters in Ihr lokales `~/.kube/config` Verzeichnis kopieren. Für weitere Informationen siehe {xref-access-cluster-kubectl}[Zugriff auf Cluster mit kubectl und einer kubeconfig-Datei].

[#_rancher_cli]
== Rancher CLI

Sie können Ihre Cluster steuern, indem Sie die eigene Befehlszeilenschnittstelle von Rancher, {xref-rancher-cli}[Rancher CLI], herunterladen. Dieses CLI-Tool kann direkt mit verschiedenen Clustern und Projekten interagieren oder ihnen `kubectl` Befehle übergeben.

[#_rancher_api]
== Rancher API

Schließlich können Sie über die Rancher API mit Ihren Clustern interagieren. Bevor Sie die API verwenden, müssen Sie einen {xref-user-api-keys}[API-Schlüssel] erhalten. Um die verschiedenen Ressourcenfelder und Aktionen für ein API-Objekt anzuzeigen, öffnen Sie die API-Benutzeroberfläche, die Sie erreichen können, indem Sie auf *In API anzeigen* für ein beliebiges Rancher UI-Objekt klicken.
