= 概述
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-04
:page-revdate: {revdate}
:community-path: integrations-in-rancher/fleet/overview.adoc 
:product-path: integrations/fleet/overview.adoc
ifeval::["{build-type}" != "community"]
:xref-backup-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/back-up.adoc
:xref-fleet-architecture: xref:integrations/fleet/architecture.adoc
:xref-fleet-windows: xref:integrations/fleet/windows-support.adoc
:xref-fleet-proxy: xref:integrations/fleet/use-fleet-behind-a-proxy.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-backup-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher.adoc
:xref-fleet-architecture: xref:integrations-in-rancher/fleet/architecture.adoc
:xref-fleet-windows: xref:integrations-in-rancher/fleet/windows-support.adoc
:xref-fleet-proxy: xref:integrations-in-rancher/fleet/use-fleet-behind-a-proxy.adoc
endif::[]

使用 Fleet 的持续交付是大规模的 GitOps。Fleet 旨在管理多达一百万个集群。它也足够轻量，可以很好地用于一个 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-operators/installation.html#_default_install[单个集群]，但当你达到 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-operators/installation.html#_configuration_for_multi_cluster[大规模] 时，它的表现尤为出色。我们所说的大规模是指有很多集群、很多部署或在单个组织中有很多团队。

Fleet 是一个独立于 Rancher 的项目，可以在任何 Kubernetes 集群上通过 Helm 安装。

[#_architecture]
== 体系结构

有关 Fleet 工作原理的信息，请参见 {xref-fleet-architecture}[架构] 页面。

[#_accessing_fleet_product_name_in_the_rancher_ui]
== 在 Rancher UI 中访问 {fleet-product-name}

Fleet 在 Rancher 中预装，并由 Rancher UI 中的 *持续交付* 选项管理。有关持续交付和其他 Fleet 故障排除提示的更多信息，请参见 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/troubleshooting.html[这里]。

用户可以利用持续交付将他们的应用程序部署到 git 储存库中的 Kubernetes 集群，而无需任何手动操作，只需遵循 *gitops* 实践。

按照以下步骤在 Rancher UI 中访问持续交付：

. 点击 *☰ > 持续交付*。
. 在菜单顶部选择您的命名空间，注意以下事项：
 ** 默认情况下，选择 *fleet-default*，其中包括通过 Rancher 注册的所有下游集群。
 ** 您可以切换到 *fleet-local*，该选项仅包含 *本地* 集群，或者您可以创建自己的工作区，以便分配和移动集群。
 ** 然后，您可以通过点击左侧导航栏上的 *集群* 来管理集群。
. 点击左侧导航栏上的 *Gitrepos* 将 gitrepo 部署到当前工作区中的集群。
. 选择您的 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-users/gitrepo-add.html[git 储存库] 和 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-users/gitrepo-targets.html[目标集群/集群组]。您还可以通过点击左侧导航栏中的 *集群组* 在 UI 中创建集群组。
. 一旦 gitrepo 部署完成，您可以通过 Rancher UI 监控应用程序。

[#_windows_support]
== Windows 支持

有关支持 Windows 节点集群的详细信息，请参阅 {xref-fleet-windows}[Windows 支持] 页面。

[#_github_repository]
== GitHub 储存库

Fleet Helm 图表可在 https://github.com/rancher/fleet/releases[此处] 获取。

[#_using_fleet_product_name_behind_a_proxy]
== 在代理后使用 {fleet-product-name}

有关在代理后使用 Fleet 的详细信息，请参阅 {xref-fleet-proxy}[在代理后使用 Fleet] 页面。

[#_helm_chart_dependencies]
== Helm 图表依赖项

为了使具有依赖项的 Helm 图表成功部署，您必须运行手动命令（如下所列），因为满足依赖项列表由用户负责。如果您不这样做并继续克隆您的储存库并运行 `helm install`，您的安装将失败，因为依赖项将缺失。

git 储存库中的 Helm 图表必须在 `charts/` 子目录中包含其依赖项。为此，请手动运行 `helm dependencies update $chart` 或在本地运行 `helm dependencies build $chart`，然后将完整的 `charts/` 目录提交到您的 git 储存库。确保您根据环境更新命令及其适用参数。

[#_fleet_resource_configuration]
== Fleet 资源配置

Fleet 允许您为管理集群控制器和下游集群代理配置 CPU 和内存资源请求及限制。通过 Rancher 运行 Fleet 时，请使用 `rancher-config` ConfigMap 应用这些更改，而不是直接通过 Helm。

有关详细的配置选项，请参阅 link:https://fleet.rancher.io/how-tos-for-operators/resource-limits[Fleet 中的资源限制]。

[#_troubleshooting]
== 查错

* *已知问题*：Fleet gitrepos 的 clientSecretName 和 helmSecretName 秘密未包含在 {xref-backup-cluster}#_1_install_the_rancher_backup_operator[备份-恢复-操作员] 创建的备份或恢复中。一旦有了永久解决方案，我们将更新社区。
* *临时解决方法*：默认情况下，用户定义的秘密不会在 Fleet 中备份。如果执行灾难恢复恢复或将 Rancher 迁移到新集群，则需要重新创建秘密。要修改 resourceSet 以包含您想要备份的额外资源，请参阅文档 https://github.com/rancher/backup-restore-operator#user-flow[此处]。
* *调试日志记录*:要启用 Fleet 组件的调试日志记录，请在现有的 *rancher-config* ConfigMap 中的 *cattle-system* 命名空间中创建一个新的 *fleet* 条目，值为 `{"debug": 1, "debugLevel": 1}`。保存 ConfigMap 后，Fleet 应用程序会重新启动。

[#_documentation]
== 文档

请参阅 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/index.html[{fleet-product-name} 文档] 以了解更多信息。
