= Verwalten von Cloud-Anmeldeinformationen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: reference-guides/user-settings/manage-cloud-credentials.adoc 
:product-path: rancher-admin/users/settings/manage-cloud-credentials.adoc
ifeval::["{build-type}" != "community"]
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-manage-node-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-infra-providers: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/index.adoc
:xref-manage-node-drivers: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.adoc
endif::[]

Die Erstellung oder Zuordnung von Cloud-Anmeldeinformationen ist Teil des Clustererstellungsprozesses. Die folgenden Informationen bieten Anleitungen zum Verwalten von Anmeldeinformationen in Rancher.

Cloud-Anmeldeinformationen sind an das Benutzerprofil ihres Erstellers gebunden. Sie *können nicht* zwischen Nicht-Admin-Benutzern geteilt werden. Administratoren können jedoch die Cloud-Anmeldeinformationen anderer Benutzer anzeigen und verwalten.

[#_creating_a_cloud_credential]
== Erstellen einer Cloud-Anmeldeinformation

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Klicken Sie auf *Cloud-Anmeldeinformationen*.
. Klicken Sie auf *Erstellen*.
. Klicken Sie auf einen Typ von Cloud-Anmeldeinformationen. Die Werte dieses Dropdowns basieren auf den `active` {xref-manage-node-drivers}[Knoten-Treibern] in Rancher.
. Geben Sie einen Namen für die Cloud-Anmeldeinformation ein.
. Basierend auf dem ausgewählten Typ der Cloud-Anmeldeinformation geben Sie die erforderlichen Werte zur Authentifizierung beim Infrastruktur-Anbieter ein.
. Klicken Sie auf *Erstellen*.

**Ergebnis:** Die Cloud-Anmeldeinformation wurde erstellt.

[#_updating_a_cloud_credential]
== Aktualisieren einer Cloud-Anmeldeinformation

Wenn Zugangsdaten geändert oder kompromittiert werden, ermöglicht das Aktualisieren einer Cloud-Anmeldeinformation, diese Zugangsdaten zu rotieren, während dasselbe Knotentemplate beibehalten wird.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Klicken Sie auf *Cloud-Anmeldeinformationen*.
. Wählen Sie die Cloud-Anmeldeinformation aus, die Sie bearbeiten möchten, und klicken Sie auf *⋮ > Konfiguration bearbeiten*.
. Aktualisieren Sie die Zugangsdaten und klicken Sie auf *Speichern*.

**Ergebnis:** Die Cloud-Anmeldeinformation wurde mit den neuen Zugangsdaten aktualisiert.

[#_deleting_a_cloud_credential]
== Löschen einer Cloud-Anmeldeinformation

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Klicken Sie auf *Cloud-Anmeldeinformationen*.
. Sie können entweder eine Cloud-Anmeldeinformation einzeln löschen oder mehrere gleichzeitig löschen.
 ** Um eine einzelne zu löschen, wählen Sie die Cloud-Anmeldeinformation aus, die Sie bearbeiten möchten, und klicken Sie auf *⋮ > Löschen*.
 ** Um Cloud-Anmeldeinformationen in großen Mengen zu löschen, wählen Sie eine oder mehrere Cloud-Anmeldeinformationen aus der Liste aus. Klicken Sie auf *Löschen*.
. Bestätigen Sie, dass Sie diese Cloud-Anmeldeinformationen löschen möchten.
