= Fehlerbehebung bei Controlplane-Knoten
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/kubernetes-components/troubleshooting-controlplane-nodes.adoc 
:product-path: troubleshooting/kubernetes-components/troubleshooting-controlplane-nodes.adoc

Dieser Abschnitt gilt für Knoten mit der Rolle `controlplane`.

[#_check_if_the_controlplane_containers_are_running]
== Überprüfen Sie, ob die Controlplane-Container ausgeführt werden.

Es gibt drei spezifische Container, die auf Knoten mit der Rolle `controlplane` gestartet werden:

* `kube-apiserver`
* `kube-controller-manager`
* `kube-scheduler`

Die Container sollten den Status *Up* haben. Die Dauer, die nach *Up* angezeigt wird, ist die Zeit, die der Container bereits läuft.

----
docker ps -a -f=name='kube-apiserver|kube-controller-manager|kube-scheduler'
----

Beispielausgabe:

----
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
26c7159abbcc        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-apiserver
f3d287ca4549        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-scheduler
bdf3898b8063        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-controller-manager
----

[#_controlplane_container_logging]
== Protokollierung der Controlplane-Container

[NOTE]
====

Wenn Sie mehrere Knoten mit der Rolle `controlplane` hinzugefügt haben, verwenden sowohl `kube-controller-manager` als auch `kube-scheduler` einen Führerwahl-Prozess, um den Führer zu bestimmen. Nur der aktuelle Führer wird die durchgeführten Aktionen protokollieren. Siehe xref:troubleshooting/other-troubleshooting-tips/kubernetes-resources.adoc#_kubernetes_leader_election[Kubernetes-Führerwahl], wie Sie den aktuellen Führer abrufen können.
====


Die Protokollierung der Container kann Informationen darüber enthalten, was das Problem sein könnte.

----
docker logs kube-apiserver
docker logs kube-controller-manager
docker logs kube-scheduler
----

[#__rke2_product_name_server_logging]
== {rke2-product-name} Server-Protokollierung

Wenn Rancher ein RKE2-Cluster bereitstellt, das nicht mit Rancher kommunizieren kann, können Sie diesen Befehl auf einem Serverknoten im Downstream-Cluster ausführen, um die RKE2-Serverprotokolle zu erhalten:

----
journalctl -u rke2-server -f
----
