= Stockage NFS
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/nfs-storage.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/examples/nfs-storage.adoc
ifeval::["{build-type}" != "community"]
:xref-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/manage-persistent-storage.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-persistent-storage: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/index.adoc
endif::[]

Avant de pouvoir utiliser le plug-in de volume de stockage NFS avec les déploiements Rancher, vous devez provisionner un serveur NFS.

[NOTE]
====

* Si vous avez déjà un partage NFS, vous n'avez pas besoin de provisionner un nouveau serveur NFS pour utiliser le plug-in de volume NFS dans Rancher. Au lieu de cela, ignorez le reste de cette procédure et complétez {xref-persistent-storage}[ajouter du stockage].
* Cette procédure démontre comment configurer un serveur NFS en utilisant Ubuntu, bien que vous devriez pouvoir utiliser ces instructions pour d'autres distributions Linux (par exemple, Debian, RHEL, Arch Linux, etc.). Pour des instructions officielles sur la façon de créer un serveur NFS en utilisant une autre distribution Linux, consultez la documentation de la distribution.
====


[NOTE]
.Recommandé :
====

Pour simplifier le processus de gestion des règles de la passerelle de périmètre de sécurité, utilisez NFSv4.
====


. En utilisant une connexion Terminal distante, connectez-vous au serveur Ubuntu que vous comptez utiliser pour le stockage NFS.
. Saisissez la commande suivante :
+
----
 sudo apt-get install nfs-kernel-server
----

. Entrez la commande ci-dessous, qui définit le répertoire utilisé pour le stockage, ainsi que les droits d'accès des utilisateurs. Modifiez la commande si vous souhaitez conserver le stockage dans un répertoire différent.
+
----
 mkdir -p /nfs && chown nobody:nogroup /nfs
----

 ** Le paramètre `-p /nfs` crée un répertoire nommé `nfs` à la racine.
 ** Le paramètre `chown nobody:nogroup /nfs` permet un accès total au répertoire de stockage.

. Créez une table d'exports NFS. Cette table définit les chemins de répertoire sur votre serveur NFS qui sont exposés aux nœuds qui utiliseront le serveur pour le stockage.
 .. Ouvrez `/etc/exports` avec votre éditeur de texte de choix.
 .. Ajoutez le chemin du dossier `/nfs` que vous avez créé à l'étape 3, ainsi que les adresses IP de vos nœuds de cluster. Ajoutez une entrée pour chaque adresse IP de votre cluster. Suivez chaque adresse et ses paramètres associés d'un espace unique qui sert de délimiteur.
+
----
 /nfs <IP_ADDRESS1>(rw,sync,no_subtree_check) <IP_ADDRESS2>(rw,sync,no_subtree_check) <IP_ADDRESS3>(rw,sync,no_subtree_check)
----
+

[TIP]
====
Vous pouvez remplacer les adresses IP par un sous-réseau. Exemples :`10.212.50.12&#47;24`
====


 .. Mettez à jour la table NFS en entrant la commande suivante{nbsp}:
+
----
 exportfs -ra
----
. Ouvrez les ports utilisés par NFS.
 .. Pour savoir quels ports NFS utilise, entrez la commande suivante{nbsp}:
+
----
 rpcinfo -p | grep nfs
----

 .. https://help.ubuntu.com/lts/serverguide/firewall.html.en[Ouvrez les ports] que la commande précédente affiche. Par exemple, la commande suivante ouvre le port 2049{nbsp}:
+
----
 sudo ufw allow 2049
----

*Résultat :* Votre serveur NFS est configuré pour être utilisé comme stockage avec vos nœuds Rancher.

[#_whats_next]
== Et maintenant\...

Dans Rancher, ajoutez le serveur NFS en tant que volume de stockage et/ou classe de stockage. Après avoir ajouté le serveur, vous pouvez l'utiliser pour le stockage de vos déploiements.
