= Création de stockage persistant sur Amazon EBS
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/persistent-storage-in-amazon-ebs.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/examples/persistent-storage-in-amazon-ebs.adoc
ifeval::["{build-type}" != "community"]
:xref-existing-storage-setup: xref:cluster-admin/manage-clusters/persistent-storage/set-up-existing-storage.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-existing-storage-setup: xref:how-to-guides/nouveaux-guides-utilisateurs/gerer-des-clusters/créer-un-stockage-persistent-kubernetes/gerer-le-stockage-persistent/configurer-le-stockage-existant.adoc
endif::[]

Cette section décrit comment configurer le stockage en bloc élastique d'Amazon dans EC2.

. Depuis la console EC2, allez dans la section *STOCKAGE EN BLOC ÉLASTIQUE* dans le panneau de gauche et cliquez sur *Volumes*.
. Cliquez sur *Créer un volume*.
. Facultatives : Configurez la taille du volume ou d'autres options. Le volume doit être créé dans la même zone de disponibilité que l'instance à laquelle il sera attaché.
. Cliquez sur *Créer un volume*.
. Cliquez sur *Fermer*.

*Résultat :* Le stockage persistant a été créé.

Pour des détails sur la façon de configurer le stockage nouvellement créé dans Rancher, référez-vous à la section sur {xref-existing-storage-setup}[la configuration du stockage existant.]
