= Plantillas de clúster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 4/11/2025
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc 
:product-path: cluster-admin/manage-clusters/cluster-templates.adoc
:experimental:

Las plantillas de clúster abarcan tanto la configuración de Kubernetes como la configuración del grupo de nodos, permitiendo que una sola plantilla contenga toda la información que Rancher necesita para aprovisionar nuevos nodos en un proveedor de nube e instalar Kubernetes en esos nodos.

[#_overview]
== Descripción general

Las plantillas de clúster se proporcionan como gráficos de Helm. Para utilizarlas, deberás clonar y bifurcar las plantillas, modificarlas según tu caso de uso y luego instalar los gráficos de Helm en el clúster de gestión de Rancher. Cuando el gráfico de Helm se instala en el clúster de gestión de Rancher, se crea un nuevo recurso de clúster, que Rancher utiliza para aprovisionar el nuevo clúster.

Después de que el clúster se aprovisione utilizando la plantilla, ningún cambio en la plantilla afectará al clúster. Después de que el clúster se cree a partir de la plantilla de clúster, su configuración e infraestructura pueden cambiar, ya que no se imponen restricciones por las plantillas de clúster.

[#_kubernetes_distribution]
=== Distribución de Kubernetes

Las plantillas de clúster pueden utilizar cualquier distribución de Kubernetes. Por ahora, proporcionamos un ejemplo con un clúster de Kubernetes RKE2. Podemos proporcionar más ejemplos en el futuro utilizando otras distribuciones de Kubernetes.

[#_versioning]
=== Control de versiones

Rancher no gestiona el control de versiones para las plantillas de clúster. El control de versiones se gestiona en el repositorio que contiene el gráfico de Helm de la plantilla.

[#__rke2_product_name_cluster_template]
== {rke2-product-name} Plantilla de Clúster

Consulta el repositorio de ejemplo para una https://github.com/rancher/cluster-template-examples[plantilla de clúster RKE2].

[#_adding_a_cluster_template_to_rancher]
== Añadiendo una Plantilla de Clúster a Rancher

En esta sección, aprenderás cómo añadir la plantilla de clúster a la `local` lista de repositorios de gráficos del clúster. El resultado es que Rancher incluirá la plantilla de clúster como una opción cuando los usuarios instalen nuevos clústeres de Kubernetes.

[NOTE]
.Requisitos previos:
====

* Necesitarás permiso para instalar gráficos de Helm en el `local` clúster de Rancher.
* Para hacer que el gráfico sea visible en el formulario de creación de clúster, tanto el gráfico como el archivo index.yaml deben tener la anotación, `catalog.cattle.io/type: cluster-template`.
====


. Ve a un repositorio de ejemplo de plantilla de clúster. Los ejemplos de Rancher están en https://github.com/rancher/cluster-template-examples[este repositorio de GitHub.]
. Haz un fork del repositorio.
. Opcional: Edita las opciones del clúster editando el archivo `values.yaml`. Para obtener ayuda editando el archivo, consulta el README del gráfico Helm de la plantilla de clúster.
. Añade el repositorio de gráficos a Rancher. Haz clic en *☰ > Gestión de Clústeres*.
. Ve al `local` clúster y haz clic en *Explorar.*
. En la barra de navegación izquierda, haz clic en menu:Apps[Repositorios de Gráficos.]
. Haz clic en *Crear.*
. Introduce un nombre para el repositorio de la plantilla de clúster.
. Haz clic en *Repositorio Git que contiene definiciones de gráficos Helm.*
. En el campo *URL del Repositorio Git*, introduce la URL del repositorio. Por ejemplo, `https://github.com/rancher/cluster-template-examples.git`.
. En el campo *Rama Git*, introduce la rama que se utilizará como fuente para la plantilla. El repositorio de ejemplo de Rancher utiliza `main`.
. Haz clic en *Crear.*

*Resultado:* La plantilla de clúster disponible desde *Apps* en el `local` clúster de Rancher. Ahora se puede utilizar para desplegar clústeres.

[#_creating_a_cluster_from_a_cluster_template]
== Creando un Clúster a partir de una Plantilla de Clúster

[NOTE]
.Requisitos previos:
====

* Necesitarás permiso para aprovisionar nuevos clústeres de Kubernetes.
* Necesitarás credenciales de nube para aprovisionar infraestructura utilizando la plantilla.
* Para mostrar en el formulario para crear nuevos clústeres, el gráfico de Helm de la plantilla de clúster debe tener la anotación `catalog.cattle.io/type: cluster-template`.
====


. Haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, haz clic en *Crear.*
. Haz clic en el nombre de tu plantilla de clúster.
. Termina de instalar el gráfico de Helm.

*Resultado:* Después de que Rancher aprovisione el nuevo clúster, se gestiona de la misma manera que cualquier otro clúster de Kubernetes lanzado por Rancher. Puedes configurar cualquier opción a través de la interfaz si la plantilla de clúster tiene opciones para que el usuario elija.

[#_updating_a_cluster_created_from_a_cluster_template]
== Actualizando un Clúster Creado a Partir de una Plantilla de Clúster

Puedes actualizar cualquier clúster utilizando una plantilla desde la página menu:Apps[Installed Apps], siempre que haya una nueva versión de una plantilla que esté siendo utilizada por esos clústeres.

[#_deploying_clusters_from_a_template_with_fleet_product_name]
== Desplegando Clústeres desde una Plantilla con {fleet-product-name}

[NOTE]
.Requisitos previos:
====

* Necesitarás permiso para aprovisionar nuevos clústeres de Kubernetes.
* Necesitarás credenciales de nube para aprovisionar infraestructura utilizando la plantilla.
* Para mostrar en el formulario para crear nuevos clústeres, el gráfico de Helm de la plantilla de clúster debe tener la anotación `catalog.cattle.io/type:cluster-template`.
* Para utilizar una plantilla como parte de la entrega continua/GitOps, la plantilla de clúster necesita ser desplegada en el espacio de nombres `fleet-local` del `local` clúster.
* Todos los valores deben establecerse en el `values.yaml` de la plantilla.
* Los repositorios de Fleet deben seguir estas https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/explanations/gitrepo-content.html[directrices]. Para las plantillas de clúster RKE2, eso significa que se debe añadir un archivo `fleet.yaml` al repositorio.
====


. Haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, haz clic en *Crear.*
. Haz clic en *Crear Clúster desde Plantilla.*

*Resultado:* Después de que Rancher aprovisione el nuevo clúster, se gestiona por Fleet.

[#_uninstalling_cluster_templates]
== Desinstalando Plantillas de Clúster

. Haz clic en *☰ > Gestión de Clústeres*.
. Ve al `local` clúster y haz clic en menu:Apps[Repositorios de Gráficos.]
. Ve al repositorio de gráficos para tu plantilla de clúster y haz clic en *⋮ > Eliminar.*
. Confirme la supresión.

*Resultado:* La plantilla de clúster se desinstala. Esta acción no afecta a los clústeres creados con la plantilla de clúster.

Un administrador con acceso al `local` clúster también puede eliminar un clúster desplegado a través de plantillas de clúster en la página menu:Apps[Installed Apps].

[#_configuration_options]
== Opciones de configuración

Las plantillas de clúster son lo suficientemente flexibles como para que se puedan utilizar para configurar todas las siguientes opciones:

* Configuración de nodo
* Grupos de nodos
* Credenciales de nube preespecificadas
* Habilitar/configurar un punto de acceso autorizado al clúster para obtener acceso a kubectl al clúster sin usar Rancher como proxy
* Instalar la monitorización de Rancher V2
* Kubernetes version
* Asignar miembros del clúster
* Configuración de infraestructura como AWS VPC/subredes o centro de datos de vSphere
* Opciones del proveedor de nube
* Opciones de seguridad de pods
* Proveedores de red
* Controladores de Ingress
* Configuración de seguridad de red
* Plugins de red
* URL y credenciales del registro privado
* Complementos
* Opciones de Kubernetes, incluidas configuraciones para componentes de Kubernetes como kube-api, kube-controller, kubelet y servicios

Para obtener detalles sobre cómo configurar la plantilla, consulte el README del gráfico Helm de la plantilla del clúster.
