= Administración del clúster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 18-12-2025
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/index.adoc 
:product-path: cluster-admin/manage-clusters/manage-clusters.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/usuarios/authn-y-authz/gestionar-control-de-acceso-basado-en-funciones-rbac/roles-de-cluster-y-proyecto.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:guías-como-hacer/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/gestionar-control-de-acceso-basado-en-funciones-rbac/roles-de-cluster-y-proyecto.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
endif::[]

Después de aprovisionar un clúster en Rancher, puedes comenzar a utilizar potentes características de Kubernetes para desplegar y escalar tus aplicaciones en contenedores en entornos de desarrollo, pruebas o producción.

[NOTE]
====

Esta sección asume un conocimiento básico de Docker y Kubernetes. Para una breve explicación de cómo los componentes de Kubernetes trabajan juntos, consulta la página de {xref-k8s-concepts}[conceptos].
====


[#_managing_clusters_in_rancher]
== Gestión de Clústeres en Rancher

Después de que los clústeres hayan sido {xref-cluster-deployment}[aprovisionados en Rancher], {xref-cluster-project-roles}#_cluster_roles[los propietarios de clústeres] necesitarán gestionar estos clústeres. Existen muchas opciones diferentes sobre cómo gestionar tu clúster.

ifeval::["{build-type}" != "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table.adoc[]
endif::[]
ifeval::["{build-type}" == "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table-srfa.adoc[]
endif::[]

[#_configuring_tools]
== Configuración de Herramientas

Rancher contiene una variedad de herramientas que no están incluidas en Kubernetes para ayudar en tus operaciones de DevOps. Rancher puede integrarse con servicios externos para ayudar a que tus clústeres funcionen de manera más eficiente. Las herramientas se dividen en las siguientes categorías:

* Alertas
* Notificadores
* Registro
* Monitorización
* Malla de Servicios Istio

Las herramientas se pueden instalar a través de *Apps.*
