= Descripción general
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 4/11/2025
:page-revdate: {revdate}
:community-path: integrations-in-rancher/fleet/overview.adoc 
:product-path: integrations/fleet/overview.adoc
ifeval::["{build-type}" != "community"]
:xref-backup-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/back-up.adoc
:xref-fleet-architecture: xref:integrations/fleet/architecture.adoc
:xref-fleet-windows: xref:integrations/fleet/windows-support.adoc
:xref-fleet-proxy: xref:integrations/fleet/use-fleet-behind-a-proxy.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-backup-cluster: xref:guías-de-cómo/nuevas-guías-de-usuario/copia-de-seguridad-recuperación-y-recuperación-de-desastres/copia-de-seguridad-rancher.adoc
:xref-fleet-architecture: xref:integrations-in-rancher/fleet/architecture.adoc
:xref-fleet-windows: xref:integrations-in-rancher/fleet/windows-support.adoc
:xref-fleet-proxy: xref:integrations-in-rancher/fleet/use-fleet-behind-a-proxy.adoc
endif::[]

La entrega continua con Fleet es GitOps a gran escala. Fleet está diseñado para gestionar hasta un millón de clústeres. También es lo suficientemente ligero como para funcionar muy bien con un https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-operators/installation.html#_default_install[clúster único], pero realmente brilla cuando se alcanza una https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-operators/installation.html#_configuration_for_multi_cluster[gran escala]. Por gran escala nos referimos a muchos clústeres, muchas ampliaciones o muchos equipos en una sola organización.

Fleet es un proyecto separado de Rancher y se puede instalar en cualquier clúster de Kubernetes con Helm.

[#_architecture]
== Arquitectura

Para información sobre cómo funciona Fleet, consulta la página de {xref-fleet-architecture}[Arquitectura].

[#_accessing_fleet_product_name_in_the_rancher_ui]
== Accediendo a {fleet-product-name} en la interfaz de usuario de Rancher

Fleet viene preinstalado en Rancher y se gestiona a través de la opción *Entrega Continua* en la interfaz de usuario de Rancher. Para información adicional sobre la entrega continua y otros consejos de solución de problemas de Fleet, consulta https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/troubleshooting.html[aquí].

Los usuarios pueden aprovechar la entrega continua para desplegar sus aplicaciones en los clústeres de Kubernetes en el repositorio git sin ninguna operación manual siguiendo la práctica de *gitops*.

Sigue los pasos a continuación para acceder a la entrega continua en la interfaz de usuario de Rancher:

. Haz clic en *☰ > Entrega Continua*.
. Selecciona tu espacio de nombres en la parte superior del menú, teniendo en cuenta lo siguiente:
 ** Por defecto, se selecciona *fleet-default*, que incluye todos los clústeres en sentido descendente que están registrados a través de Rancher.
 ** Puedes cambiar a *fleet-local*, que solo contiene el clúster *local*, o puedes crear tu propio espacio de trabajo al que puedes asignar y mover clústeres.
 ** Puedes gestionar clústeres haciendo clic en *Clusters* en la barra de navegación izquierda.
. Haz clic en *Gitrepos* en la barra de navegación izquierda para desplegar el gitrepo en tus clústeres en el espacio de trabajo actual.
. Selecciona tu https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-users/gitrepo-add.html[repositorio git] y https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-users/gitrepo-targets.html[clústeres de destino/grupo de clústeres]. También puedes crear el grupo de clústeres en la interfaz de usuario haciendo clic en *Grupos de Clústeres* desde la barra de navegación izquierda.
. Una vez que el gitrepo esté desplegado, puedes monitorizar la aplicación a través de la interfaz de usuario de Rancher.

[#_windows_support]
== Soporte para Windows

Para detalles sobre el soporte para clústeres con nodos de Windows, consulta la página {xref-fleet-windows}[Soporte para Windows].

[#_github_repository]
== Repositorio de GitHub

Los gráficos de Helm de Fleet están disponibles https://github.com/rancher/fleet/releases[aquí].

[#_using_fleet_product_name_behind_a_proxy]
== Usando {fleet-product-name} Detrás de un proxy

Para detalles sobre el uso de Fleet detrás de un proxy, consulta la página {xref-fleet-proxy}[Uso de Fleet Detrás de un Proxy].

[#_helm_chart_dependencies]
== Dependencias del gráfico de Helm

Para que los gráficos de Helm con dependencias se desplieguen correctamente, debes ejecutar un comando manual (como se indica a continuación), ya que depende del usuario cumplir con la lista de dependencias. Si no haces esto y procedes a clonar tu repositorio y ejecutar `helm install`, tu instalación fallará porque faltarán las dependencias.

El gráfico de Helm en el repositorio git debe incluir sus dependencias en el subdirectorio `charts/`. Para hacer esto, ejecuta manualmente `helm dependencies update $chart` o ejecuta `helm dependencies build $chart` localmente, luego confirma el directorio completo `charts/` en tu repositorio git. Asegúrate de actualizar tus comandos con los parámetros aplicables a tu entorno.

[#_fleet_resource_configuration]
== Configuración de recursos de Fleet

Fleet te permite configurar solicitudes y límites de recursos de CPU y memoria tanto para los controladores del clúster de gestión como para los agentes del clúster descendente. Al ejecutar Fleet a través de Rancher, aplica estos cambios utilizando el `rancher-config` ConfigMap en lugar de hacerlo directamente a través de Helm.

Para opciones de configuración detalladas, consulta link:https://fleet.rancher.io/how-tos-for-operators/resource-limits[Límites de recursos en Fleet].

[#_troubleshooting]
== Solución de problemas

* *Problema Conocido*: los secretos clientSecretName y helmSecretName para los gitrepos de Fleet no están incluidos en la copia de seguridad ni en la restauración creada por el {xref-backup-cluster}#_1_instalar_el_operador_de_copia_de_seguridad_de_rancher[operador-de-copia-de-seguridad]. Actualizaremos a la comunidad una vez que se implemente una solución permanente.
* *Solución temporal*: Por defecto, los secretos definidos por el usuario no se incluyen en la copia de seguridad en Fleet. Es necesario recrear los secretos si se realiza una restauración de recuperación ante desastres o migración de Rancher a un clúster nuevo. Para modificar resourceSet e incluir recursos adicionales que deseas incluir en la copia de seguridad, consulta la documentación https://github.com/rancher/backup-restore-operator#user-flow[aquí].
* *Registro de depuración*: Para habilitar el registro de depuración de los componentes de Fleet, crea una nueva entrada *fleet* en el ConfigMap existente *rancher-config* en el espacio de nombres *cattle-system* con el valor `{"debug": 1, "debugLevel": 1}`. La aplicación Fleet se reinicia después de que guardas el ConfigMap.

[#_documentation]
== Documentación

Consulta la https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/index.html[{fleet-product-name} documentación] para aprender más.
