= Soporte para Windows
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/fleet/windows-support.adoc 
:product-path: integrations/fleet/windows-support.adoc

Antes de Rancher v2.5.6, el `agent` no tenía manifiestos nativos de Windows en clústeres en sentido descendente con nodos de Windows. Esto resultaría en un pod fallido `agent` para el clúster.

Si actualizáis de una versión anterior de Rancher a v2.5.6+, podéis desplegar un `agent` funcional con el siguiente flujo de trabajo _en el clúster en sentido descendente_:

. Cordonad todos los nodos de Windows.
. Aplicad la tolerancia a continuación a la `agent` carga de trabajo.
. Descordonad todos los nodos de Windows.
. Suprimid todos los `agent` pods. Se deberían crear nuevos pods con la nueva tolerancia.
. Una vez que los `agent` pods estén en funcionamiento, y la actualización automática esté habilitada para Fleet, deberían actualizarse a una `agent` versión compatible con Windows.

[,yaml]
----
tolerations:
- effect: NoSchedule
  key: cattle.io/os
  operator: Equal
  value: linux
----
