= Installieren/Upgrade von {rancher-product-name} auf einem Kubernetes-Cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-16
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc 
:product-path: installation-and-upgrade/install-rancher.adoc
:description: Erfahren Sie, wie Sie Rancher in Entwicklungs- und Produktionsumgebungen installieren. Lesen Sie über die Installation auf einem einzelnen Knoten und die Installation mit hoher Verfügbarkeit
ifeval::["{build-type}" != "community"]
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-tls-secrets: xref:installation-and-upgrade/resources/tls-secrets.adoc
:xref-tls-settings: xref:installation-and-upgrade/references/tls-settings.adoc
:xref-upgrade-certmanager: xref:installation-and-upgrade/resources/upgrade-cert-manager.adoc
:xref-install-upgrade-troubleshooting: xref:installation-and-upgrade/troubleshooting/troubleshooting.adoc
:xref-rancher-on-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
:xref-air-gap-rancher-ha: xref:installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc
:xref-helm-reqs: xref:installation-and-upgrade/requirements/helm-version-requirements.adoc
:xref-ha-k3s: xref:installation-and-upgrade/infrastructure-setup/ha-k3s-kubernetes-cluster.adoc
:xref-ha-rke2: xref:installation-and-upgrade/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc
:xref-k3s-for-rancher: xref:installation-and-upgrade/install-kubernetes/k3s-for-rancher.adoc
:xref-rke2-for-rancher: xref:installation-and-upgrade/install-kubernetes/rke2-for-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-on-aks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-aks.adoc
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-tls-secrets: xref:getting-started/installation-and-upgrade/resources/add-tls-secrets.adoc
:xref-tls-settings: xref:getting-started/installation-and-upgrade/installation-references/tls-settings.adoc
:xref-upgrade-certmanager: xref:getting-started/installation-and-upgrade/resources/upgrade-cert-manager.adoc
:xref-install-upgrade-troubleshooting: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/troubleshooting.adoc
:xref-rancher-on-eks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks.adoc
:xref-air-gap-rancher-ha: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha.adoc
:xref-helm-reqs: xref:getting-started/installation-and-upgrade/resources/helm-version-requirements.adoc
:xref-ha-k3s: xref:how-to-guides/new-user-guides/infrastructure-setup/ha-k3s-kubernetes-cluster.adoc
:xref-ha-rke2: xref:how-to-guides/new-user-guides/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc
:xref-rancher-on-gke: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke.adoc
:xref-k3s-for-rancher: xref:how-to-guides/new-user-guides/kubernetes-cluster-setup/k3s-for-rancher.adoc
:xref-rke2-for-rancher: xref:how-to-guides/new-user-guides/kubernetes-cluster-setup/rke2-for-rancher.adoc
endif::[]

In diesem Abschnitt lernen Sie, wie Sie Rancher auf einem Kubernetes-Cluster mit der Helm-CLI bereitstellen.

[#_prerequisites]
== Voraussetzungen

* <<_kubernetes_cluster,Kubernetes Cluster>>
* <<_ingress_controller,Ingress-Controller>>
* <<_cli_tools,Kommandozeilenschnittstelle-Tools>>

[#_kubernetes_cluster]
=== Kubernetes Cluster

Richten Sie den lokalen Kubernetes-Cluster des Rancher-Servers ein.

Rancher kann auf jedem Kubernetes-Cluster installiert werden. Dieser Cluster kann Upstream Kubernetes verwenden, oder er kann eine der Kubernetes-Distributionen von Rancher nutzen, oder es kann ein verwalteter Kubernetes-Cluster von einem Anbieter wie Amazon EKS sein.

Für Hilfe bei der Einrichtung eines Kubernetes-Clusters stellen wir diese Tutorials zur Verfügung:

* *K3s:* Für die Anleitung zur Installation eines K3s Kubernetes-Clusters verweisen Sie auf {xref-k3s-for-rancher}[diese Seite.] Für Hilfe bei der Einrichtung der Infrastruktur für einen hochverfügbaren K3s-Cluster verweisen Sie auf {xref-ha-k3s}[diese Seite.]
* *RKE2:* Für die Anleitung zur Installation eines RKE2 Kubernetes-Clusters verweisen Sie auf {xref-rke2-for-rancher}[diese Seite.] Für Hilfe bei der Einrichtung der Infrastruktur für einen hochverfügbaren RKE2-Cluster verweisen Sie auf {xref-ha-rke2}[diese Seite.]
* *Amazon EKS:* Für Details zur Installation von Rancher auf Amazon EKS, einschließlich der Installation eines Ingress-Controllers, damit der Rancher-Server zugänglich ist, siehe {xref-rancher-on-eks}[diese Seite.]
* *AKS:* Für Details zur Installation von Rancher mit Azure Kubernetes Service, einschließlich der Installation eines Ingress-Controllers, damit der Rancher-Server zugänglich ist, siehe {xref-rancher-on-aks}[diese Seite.]
* *GKE:* Für Details zur Installation von Rancher mit Google Kubernetes Engine, einschließlich der Installation eines Ingress-Controllers, damit der Rancher-Server zugänglich ist, siehe {xref-rancher-on-gke}[diese Seite.] GKE hat zwei Betriebsmodi beim Erstellen eines Kubernetes-Clusters, Autopilot und Standardmodus. Die Clusterkonfiguration für den Autopilotmodus hat Einschränkungen beim Bearbeiten des kube-system-Namensraums. Rancher muss jedoch während der Installation Ressourcen im kube-system-Namensraum erstellen. Daher können Sie Rancher nicht auf einem GKE-Cluster installieren, der im Autopilot-Modus erstellt wurde.

[#_ingress_controller]
=== Ingress-Controller

Die Rancher-Benutzeroberfläche und die API werden über einen Ingress bereitgestellt. Das bedeutet, dass der Kubernetes-Cluster, in dem Sie Rancher installieren, einen Ingress-Controller enthalten muss.

Für RKE2- und K3s-Installationen müssen Sie den Ingress-Controller nicht manuell installieren, da einer standardmäßig installiert wird.

Für Distributionen, die standardmäßig keinen Ingress-Controller enthalten, wie einen gehosteten Kubernetes-Cluster wie EKS, GKE oder AKS, müssen Sie zuerst einen Ingress-Controller bereitstellen. Beachten Sie, dass das Rancher-Helm-Chart standardmäßig kein `ingressClassName` für den Ingress festlegt. Aus diesem Grund müssen Sie den Ingress-Controller so konfigurieren, dass er auch Ingresses ohne ein `ingressClassName` überwacht.

Beispiele sind in den oben genannten *Amazon EKS*, *AKS* und *GKE*-Tutorials enthalten.

[#_cli_tools]
=== Kommandozeilenschnittstelle-Tools

Die folgenden Kommandozeilenwerkzeuge sind erforderlich, um den Kubernetes-Cluster einzurichten. Bitte stellen Sie sicher, dass diese Tools installiert sind und in Ihrem `$PATH` verfügbar sind.

* https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl[kubectl] - Kubernetes-Kommandozeilenwerkzeug.
* https://docs.helm.sh/using_helm/#installing-helm[helm] - Paketverwaltung für Kubernetes. Verweisen Sie auf die {xref-helm-reqs}[Helm-Versionanforderungen], um eine passende Helm-Version auszuwählen, mit der Rancher installiert wird. Verweisen Sie auf die https://helm.sh/docs/intro/install/[vom Helm-Projekt bereitgestellten Anweisungen] für Ihre spezifische Plattform.

[#_install_the_rancher_helm_chart]
== Installieren Sie das Rancher Helm Chart.

Rancher wird mit dem https://helm.sh/[Helm] Paketmanager für Kubernetes installiert. Helm-Charts bieten eine Vorlagensyntax für Kubernetes-YAML-Manifestdokumente. Mit Helm können wir konfigurierbare Deployments erstellen, anstatt nur statische Dateien zu verwenden.

Für Systeme ohne direkten Internetzugang siehe {xref-air-gap-rancher-ha}[Air Gap: Kubernetes install].

Um eine Rancher-Version auszuwählen, die installiert werden soll, verweisen Sie auf xref:[Wählen einer Rancher-Version.]

Um eine Version von Helm auszuwählen, mit der Rancher installiert werden soll, verweisen Sie auf die {xref-helm-reqs}[Helm-Versionanforderungen]

[NOTE]
====

Die Installationsanweisungen setzen voraus, dass Sie Helm 3 verwenden.
====


Um Rancher einzurichten,

. <<_1_add_the_helm_chart_repository,Fügen Sie das Helm-Chart-Repository hinzu>>
. <<_2_create_a_namespace_for_rancher,Erstellen Sie einen Namespace für Rancher>>
. <<_3_choose_your_ssl_configuration,Wählen Sie Ihre SSL-Konfiguration>>
. <<_4_install_cert_manager,Installieren Sie cert-manager>> (es sei denn, Sie bringen Ihre eigenen Zertifikate mit oder TLS wird an einem Lastenausgleich beendet)
. <<_5_install_rancher_with_helm_and_your_chosen_certificate_option,Installieren Sie Rancher mit Helm und Ihrer gewählten Zertifikatsoption>>
. <<_6_verify_that_the_rancher_server_is_successfully_deployed,Überprüfen Sie, ob der Rancher-Server erfolgreich bereitgestellt wurde>>
. <<_7_save_your_options,Speichern Sie Ihre Optionen>>

[#_1_add_the_helm_chart_repository]
=== 1. Fügen Sie das Helm-Chart-Repository hinzu

ifeval::["{build-type}" == "product"]
Verwenden Sie den `helm repo add` Befehl, um das Helm-Chart-Repository hinzuzufügen, das Charts zum Installieren von Rancher Prime enthält.

[,shell]
----
helm repo add rancher-prime <helm-chart-repo-url>
----

include::shared:ROOT:partial$en/helm-chart-repo-url.adoc[]
endif::[]

ifeval::["{build-type}" == "community"]
Verwenden Sie den `helm repo add` Befehl, um das Helm-Chart-Repository hinzuzufügen, das Charts zum Installieren von Rancher enthält. Für weitere Informationen zu den Repository-Optionen und welches am besten für Ihren Anwendungsfall geeignet ist, siehe xref:getting-started/installation-and-upgrade/resources/choose-a-rancher-version.adoc[Wählen einer Rancher-Version].

* Neueste: Empfohlen, um die neuesten Funktionen auszuprobieren
+
----
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
----

* Stabil: Empfohlen für Produktionsumgebungen
+
----
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
----

* Alpha: Experimentelle Vorschau auf kommende Versionen.
+
----
helm repo add rancher-alpha https://releases.rancher.com/server-charts/alpha
----
+
[NOTE]
====
Upgrades werden nicht unterstützt zu, von oder zwischen Alphas.
====
endif::[]

[#_2_create_a_namespace_for_rancher]
=== 2. Erstellen Sie einen Namespace für Rancher

Wir müssen einen Kubernetes-Namespace definieren, in dem die vom Chart erstellten Ressourcen installiert werden sollen. Dies sollte immer `cattle-system` sein:

----
kubectl create namespace cattle-system
----

[#_3_choose_your_ssl_configuration]
=== 3. Wählen Sie Ihre SSL-Konfiguration

Der Rancher-Management-Server ist standardmäßig sicher konzipiert und erfordert eine SSL/TLS-Konfiguration.

[NOTE]
====

Wenn Sie SSL/TLS extern beenden möchten, siehe {xref-helm-chart-options}#_external_tls_termination[TLS-Terminierung auf einem externen Lastenausgleich]. Wie auf dieser Seite dargelegt, hat diese Option zusätzliche Anforderungen für die TLS-Überprüfung.
====


Es gibt drei empfohlene Optionen für die Quelle des Zertifikats, das für die TLS-Beendigung am Rancher-Server verwendet wird:

* *Vom Rancher generiertes TLS-Zertifikat:* In diesem Fall müssen Sie `cert-manager` in den Cluster installieren. Rancher nutzt `cert-manager`, um seine Zertifikate auszustellen und zu verwalten. Rancher wird ein eigenes CA-Zertifikat generieren und ein Zertifikat mit dieser CA signieren. `cert-manager` ist dann verantwortlich für die Verwaltung dieses Zertifikats. Es sind keine zusätzlichen Maßnahmen erforderlich, wenn `agent-tls-mode` auf strikt gesetzt ist. Weitere Informationen zu dieser Einstellung finden Sie in {xref-tls-settings}#_agent_tls_enforcement[Agent TLS Enforcement].
* *Let's Encrypt:* Die Let's Encrypt-Option verwendet ebenfalls `cert-manager`. In diesem Fall wird der cert-manager mit einem speziellen Issuer für Let's Encrypt kombiniert, der alle erforderlichen Aktionen (einschließlich Anfrage und Validierung) zur Erlangung eines von Let's Encrypt ausgestellten Zertifikats durchführt. Diese Konfiguration verwendet die HTTP-Validierung (`HTTP-01`), sodass der Lastenausgleich einen öffentlichen DNS-Eintrag haben und aus dem Internet zugänglich sein muss. Beim Setzen von `agent-tls-mode` auf `strict` müssen Sie auch `--privateCA=true` angeben und das Let's Encrypt CA wie in {xref-tls-secrets}[Hinzufügen von TLS-Geheimnissen] hochladen. Weitere Informationen zu dieser Einstellung finden Sie in {xref-tls-settings}#_agent_tls_enforcement[Agent TLS Enforcement].
* *Bringen Sie Ihr eigenes Zertifikat mit:* Diese Option ermöglicht es Ihnen, Ihr eigenes öffentliches oder privat signiertes CA-Zertifikat mitzubringen. Rancher wird dieses Zertifikat verwenden, um Websocket- und HTTPS-Verkehr abzusichern. In diesem Fall müssen Sie dieses Zertifikat (und den zugehörigen Schlüssel) als PEM-codierte Dateien mit den Namen `tls.crt` und `tls.key` hochladen. Wenn Sie eine private CA verwenden, müssen Sie auch dieses Zertifikat hochladen. Dies liegt daran, dass diese private CA möglicherweise von Ihren Knoten nicht vertraut wird. Rancher wird dieses CA-Zertifikat nehmen und eine Prüfsumme daraus generieren, die die verschiedenen Rancher-Komponenten verwenden werden, um ihre Verbindung zu Rancher zu validieren. Wenn `agent-tls-mode` auf `strict` gesetzt ist, muss die CA hochgeladen werden, damit Downstream-Cluster erfolgreich eine Verbindung herstellen können. Weitere Informationen zu dieser Einstellung finden Sie in {xref-tls-settings}#_agent_tls_enforcement[Agent TLS Enforcement].

|===
| Konfiguration | Helm-Chart-Option | Benötigt cert-manager

| Von Rancher generierte Zertifikate (Standard)
| `ingress.tls.source=rancher`
| <<_4_install_cert_manager,Ja>>

| Let's Encrypt
| `ingress.tls.source=letsEncrypt`
| <<_4_install_cert_manager,Ja>>

| Zertifikate aus Dateien
| `ingress.tls.source=secret`
| Nein
|===

[#_4_install_cert_manager]
=== 4. Installieren Sie cert-manager

____
Sie sollten diesen Schritt überspringen, wenn Sie Ihre eigenen Zertifikatdateien mitbringen (Option `ingress.tls.source=secret`), oder wenn Sie {xref-helm-chart-options}#_external_tls_termination[TLS-Terminierung auf einem externen Lastenausgleich] verwenden.
____

Dieser Schritt ist nur erforderlich, um Zertifikate zu verwenden, die von der von Rancher generierten CA (`ingress.tls.source=rancher`) ausgestellt wurden, oder um Zertifikate von Let's Encrypt (`ingress.tls.source=letsEncrypt`) anzufordern.

.Zum Aufklappen klicken
[%collapsible]
======

[NOTE]
.Wichtig:
====

Jüngste Änderungen am cert-manager erfordern ein Upgrade. Wenn Sie Rancher aktualisieren und eine Version von cert-manager verwenden, die älter als v0.11.0 ist, lesen Sie bitte unsere {xref-upgrade-certmanager}[Upgrade-Dokumentation].
====


Diese Anweisungen sind aus der https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm[offiziellen cert-manager-Dokumentation] übernommen.

[NOTE]
====

Um Optionen zur Anpassung der cert-manager-Installation zu sehen (einschließlich für Fälle, in denen Ihr Cluster PodSecurityPolicies verwendet), siehe die https://artifacthub.io/packages/helm/cert-manager/cert-manager#configuration[cert-manager-Dokumentation].
====


----
# If you have installed the CRDs manually, instead of setting `installCRDs` or `crds.enabled` to `true` in your Helm install command, you should upgrade your CRD resources before upgrading the Helm chart:
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/<VERSION>/cert-manager.crds.yaml

# Add the Jetstack Helm repository
helm repo add jetstack https://charts.jetstack.io

# Update your local Helm chart repository cache
helm repo update

# Install the cert-manager Helm chart
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --set crds.enabled=true
----

Sobald Sie cert-manager installiert haben, können Sie überprüfen, ob es korrekt bereitgestellt wurde, indem Sie den cert-manager-Namespace auf laufende Pods überprüfen:

----
kubectl get pods --namespace cert-manager

NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-5c6866597-zw7kh               1/1     Running   0          2m
cert-manager-cainjector-577f6d9fd7-tr77l   1/1     Running   0          2m
cert-manager-webhook-787858fcdb-nlzsq      1/1     Running   0          2m
----

======

[#_5_install_rancher_with_helm_and_your_chosen_certificate_option]
=== 5. Installieren Sie Rancher mit Helm und Ihrer gewählten Zertifikatsoption.

Der genaue Befehl zur Installation von Rancher hängt von der Zertifikatkonfiguration ab.

Unabhängig von der Zertifikatkonfiguration sollte der Name der Rancher-Installation im `cattle-system` Namespace immer `rancher` sein.

[TIP]
.Testen und Entwicklung:
====

Dieser letzte Befehl zur Installation von Rancher erfordert einen Domainnamen, der den Verkehr an Rancher weiterleitet. Wenn Sie die Helm-CLI verwenden, um ein Proof-of-Concept einzurichten, können Sie einen falschen Domainnamen verwenden, wenn Sie die `hostname` Option übergeben. Ein Beispiel für einen falschen Domainnamen wäre `<IP_OF_LINUX_NODE>.sslip.io`, der Rancher auf einer IP exponiert, auf der es läuft. Produktionsinstallationen erfordern einen echten Domainnamen.
====


[tabs]
======
Von Rancher generierte Zertifikate::
+
--
Standardmäßig generiert Rancher eine CA und verwendet `cert-manager`, um das Zertifikat für den Zugriff auf die Rancher-Serveroberfläche auszustellen.

Da `rancher` die Standardoption für `ingress.tls.source` ist, geben wir `ingress.tls.source` beim Ausführen des `helm install` Befehls nicht an.

* Setzen Sie `hostname` auf den DNS-Namen, den Sie Ihrem Load-Balancer zugeordnet haben.
* Setzen Sie `bootstrapPassword` auf etwas Einzigartiges für den `admin`-Benutzer.
* Um eine bestimmte Rancher-Version zu installieren, verwenden Sie das `--version` Flag, Beispiel: `--version 2.7.0`

ifeval::["{build-type}" == "product"]
----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin
----
endif::[]

ifeval::["{build-type}" == "community"]
----
helm install rancher rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin
----

Wenn Sie eine Alpha-Version installieren, erfordert Helm, dass Sie die --devel-Option zum Installationsbefehl hinzufügen:

----
helm install rancher rancher-alpha/rancher --devel
----
endif::[]

Warten Sie, bis Rancher ausgerollt ist:

----
kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----
--

Let's Encrypt::
+
--
Diese Option verwendet `cert-manager`, um automatisch https://letsencrypt.org/[Let's Encrypt] Zertifikate anzufordern und zu erneuern. Dies ist ein kostenloser Dienst, der Ihnen ein gültiges Zertifikat bereitstellt, da Let's Encrypt eine vertrauenswürdige CA ist.

[NOTE]
====

Sie müssen Port 80 geöffnet haben, da die HTTP-01-Herausforderung nur auf Port 80 durchgeführt werden kann.
====


Im folgenden Befehl,

* wird `hostname` auf den öffentlichen DNS-Eintrag gesetzt,
* Setzen Sie `bootstrapPassword` auf etwas Einzigartiges für den `admin`-Benutzer.
* `ingress.tls.source` ist auf `letsEncrypt` gesetzt
* `letsEncrypt.email` ist auf die für die Kommunikation über Ihr Zertifikat verwendete E-Mail-Adresse gesetzt (zum Beispiel, Ablaufbenachrichtigungen)
* Setzen Sie `letsEncrypt.ingress.class` auf das, was Ihr Ingress-Controller ist, z.B. `traefik`, `nginx`, `haproxy` usw.

[CAUTION]
====

Wenn `agent-tls-mode` auf `strict` gesetzt ist (der Standardwert für neue Installationen von Rancher ab v2.9.0), müssen Sie den `privateCA=true`-Wert des Charts angeben (z. B. über `--set privateCA=true`) und die Let's Encrypt-Zertifizierungsstelle hochladen, wie in {xref-tls-secrets}[Hinzufügen von TLS-Secrets] beschrieben. Informationen zur Identifizierung der Let's Encrypt Root CA finden Sie in der Let's Encrypt https://letsencrypt.org/certificates/[Dokumentation]. Wenn Sie die CA nicht hochladen, kann Rancher möglicherweise keine Verbindung zu neuen oder bestehenden Downstream-Clustern herstellen.
====

ifeval::["{build-type}" == "product"]
----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=me@example.org \
  --set letsEncrypt.ingress.class=nginx
----
endif::[]

ifeval::["{build-type}" == "community"]
----
helm install rancher rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=me@example.org \
  --set letsEncrypt.ingress.class=nginx
----

Wenn Sie eine Alpha-Version installieren, erfordert Helm, dass Sie die --devel-Option zum Installationsbefehl hinzufügen:

----
helm install rancher rancher-alpha/rancher --devel
----
endif::[]

Warten Sie, bis Rancher ausgerollt ist:

----
kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----
--

Zertifikate aus Dateien::
+
--
In dieser Option werden Kubernetes-Secrets aus Ihren eigenen Zertifikaten erstellt, die Rancher verwenden kann.

Wenn Sie diesen Befehl ausführen, muss die `hostname`-Option mit `Common Name` oder einem `Subject Alternative Names`-Eintrag im Serverzertifikat übereinstimmen, sonst kann der Ingress-Controller nicht korrekt konfiguriert werden.

Obwohl ein Eintrag in der `Subject Alternative Names` technisch erforderlich ist, maximiert ein passendes `Common Name` die Kompatibilität mit älteren Browsern und Anwendungen.

[NOTE]
====

Wenn Sie überprüfen möchten, ob Ihre Zertifikate korrekt sind, siehe xref:../../../faq/technical-items.adoc#_how_do_i_check_common_name_and_subject_alternative_names_in_my_server_certificate[Wie überprüfe ich den Common Name und die Subject Alternative Names in meinem Serverzertifikat?]
====


* Setzen Sie den `hostname`.
* Setzen Sie `bootstrapPassword` auf etwas Einzigartiges für den `admin`-Benutzer.
* Setzen Sie `ingress.tls.source` auf `secret`.

ifeval::["{build-type}" == "product"]
----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret
----
endif::[]

ifeval::["{build-type}" == "community"]
----
helm install rancher rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret
----

Wenn Sie eine Alpha-Version installieren, erfordert Helm, dass Sie die --devel-Option zum Installationsbefehl hinzufügen:

----
helm install rancher rancher-alpha/rancher --devel
----
endif::[]

Wenn Sie ein von einer privaten CA signiertes Zertifikat verwenden, fügen Sie `--set privateCA=true` dem Befehl hinzu:

ifeval::["{build-type}" == "product"]
----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --set privateCA=true
----
endif::[]

ifeval::["{build-type}" == "community"]
----
helm install rancher rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --set privateCA=true
----
endif::[]

Jetzt, da Rancher bereitgestellt ist, siehe {xref-tls-secrets}[Hinzufügen von TLS-Secrets], um die Zertifikatdateien zu veröffentlichen, damit Rancher und der Ingress-Controller sie verwenden können.
--
======

Die Rancher-Chart-Konfiguration bietet viele Optionen zur Anpassung der Installation an Ihre spezifische Umgebung. Hier sind einige gängige erweiterte Szenarien.

* {xref-helm-chart-options}#_http_proxy[HTTP Proxy]
* {xref-helm-chart-options}#_private_registry_and_air_gap_installs[Private Container Image Registry]
* {xref-helm-chart-options}#_external_tls_termination[TLS Termination on an External Load Balancer]

Siehe die {xref-helm-chart-options}[Chart-Optionen] für die vollständige Liste der Optionen.

[#_6_verify_that_the_rancher_server_is_successfully_deployed]
=== 6. Überprüfen Sie, ob der Rancher-Server erfolgreich bereitgestellt wurde

Überprüfen Sie nach dem Hinzufügen der Secrets, ob Rancher erfolgreich ausgerollt wurde:

----
kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----

Wenn Sie den folgenden Fehler sehen: `error: deployment "rancher" exceeded its progress deadline`, können Sie den Status der Bereitstellung überprüfen, indem Sie den folgenden Befehl ausführen:

----
kubectl -n cattle-system get deploy rancher
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
rancher   3         3         3            3           3m
----

Es sollte die gleiche Anzahl für `DESIRED` und `AVAILABLE` anzeigen.

[#_7_save_your_options]
=== 7. Speichern Sie Ihre Optionen

Stellen Sie sicher, dass Sie die von Ihnen verwendeten `--set`-Optionen speichern. Sie müssen die gleichen Optionen verwenden, wenn Sie Rancher auf neue Versionen mit Helm upgraden.

[#_finishing_up]
=== Abschluss

Das ist alles. Sie sollten einen funktionierenden Rancher-Server haben.

Gehen Sie in einem Webbrowser zu dem DNS-Namen, der den Datenverkehr an Ihren Load-Balancer weiterleitet. Dann sollten Sie von der bunten Anmeldeseite begrüßt werden.

Funktioniert nicht? Werfen Sie einen Blick auf die {xref-install-upgrade-troubleshooting}[Fehlerbehebungs-Seite]
