= SELinux RPM
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-01-20
:page-revdate: {revdate}
:community-path: reference-guides/rancher-security/selinux-rpm/index.adoc 
:product-path: security/selinux-rpm/selinux-rpm.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-selinux: xref:security/selinux-rpm/about-rancher-selinux.adoc
:xref-rke2-selinux: xref:security/selinux-rpm/about-rke2-selinux.adoc
:xref-k3s-selinux: xref:security/selinux-rpm/about-k3s-selinux.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-selinux: xref:reference-guides/rancher-security/selinux-rpm/about-rancher-selinux.adoc
:xref-rke2-selinux: xref:reference-guides/rancher-security/selinux-rpm/about-rke2-selinux.adoc
:xref-k3s-selinux: xref:reference-guides/rancher-security/selinux-rpm/about-k3s-selinux.adoc
endif::[]

https://en.wikipedia.org/wiki/Security-Enhanced_Linux[Security-Enhanced Linux (SELinux)] ist eine Sicherheitsverbesserung für Linux.

Entwickelt von Red Hat, ist es eine Implementierung von verpflichtenden Zugriffskontrollen (MAC) unter Linux. Verpflichtende Zugriffskontrollen ermöglichen es einem Administrator eines Systems, zu definieren, wie Anwendungen und Benutzer auf verschiedene Ressourcen wie Dateien, Geräte, Netzwerke und die Interprozesskommunikation zugreifen können. SELinux verbessert auch die Sicherheit, indem es ein Betriebssystem standardmäßig restriktiv macht.

Nachdem es historisch von Regierungsbehörden verwendet wurde, ist SELinux jetzt ein Industriestandard und standardmäßig auf SUSE-Distributionen wie SUSE Linux Enterprise 16, openSUSE-Distributionen wie openSUSE Tumbleweed und RHEL-basierten Betriebssystemen wie Rocky Linux aktiviert. Um zu überprüfen, ob SELinux auf Ihrem System aktiviert und durchgesetzt ist, verwenden Sie `getenforce`:

----
# getenforce
Enforcing
----

Wir bieten drei RPMs (RPM Package Manager) an, die es Rancher-Produkten ermöglichen, ordnungsgemäß auf SELinux-durchsetzenden Hosts zu funktionieren:

* {xref-rancher-selinux}[`rancher-selinux`]
* {xref-rke2-selinux}[`rke2-selinux`]
* {xref-k3s-selinux}[`k3s-selinux`]
