= NFS存储
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/nfs-storage.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/examples/nfs-storage.adoc
ifeval::["{build-type}" != "community"]
:xref-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/manage-persistent-storage.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-persistent-storage: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/index.adoc
endif::[]

在您可以将NFS存储卷插件与Rancher部署一起使用之前，您需要部署一个NFS服务器。

[NOTE]
====

* 如果您已经有一个NFS共享，则无需为在Rancher中使用NFS存储卷插件而部署新的NFS服务器。相反，跳过此过程的其余部分并完成{xref-persistent-storage}[添加存储]。
* 本步骤演示如何使用Ubuntu设置NFS服务器，尽管您应该能够将这些说明用于其他Linux发行版（例如Debian、RHEL、Arch Linux等）。有关如何使用其他Linux发行版创建NFS服务器的官方指南，请查阅该发行版的文档。
====


[NOTE]
.推荐：
====

为了简化管理防火墙规则的过程，请使用NFSv4。
====


. 使用远程终端连接，登录到您打算用于NFS存储的Ubuntu服务器。
. 输入下面的命令：
+
----
 sudo apt-get install nfs-kernel-server
----

. 输入以下命令，该命令设置用于存储的目录以及用户访问权限。如果您希望将存储保留在不同的目录中，请修改该命令。
+
----
 mkdir -p /nfs && chown nobody:nogroup /nfs
----

 ** `-p /nfs`参数在root下创建一个名为`nfs`的目录。
 ** `chown nobody:nogroup /nfs`参数允许对存储目录的所有访问。

. 创建NFS导出表。该表设置您NFS服务器上暴露给将使用该服务器进行存储的节点的目录路径。
 .. 使用您选择的文本编辑器打开`/etc/exports`。
 .. 添加您在第3步中创建的`/nfs`文件夹的路径，以及您集群节点的IP地址。为集群中的每个IP地址添加一个条目。在每个地址及其附带参数后跟一个空格作为分隔符。
+
----
 /nfs <IP_ADDRESS1>(rw,sync,no_subtree_check) <IP_ADDRESS2>(rw,sync,no_subtree_check) <IP_ADDRESS3>(rw,sync,no_subtree_check)
----
+

[TIP]
====
您可以用子网替换IP地址。例如：`10.212.50.12&#47;24`
====


 .. 通过输入以下命令更新NFS表：
+
----
 exportfs -ra
----
. 打开NFS使用的端口。
 .. 要找出NFS使用的端口，请输入以下命令：
+
----
 rpcinfo -p | grep nfs
----

 .. https://help.ubuntu.com/lts/serverguide/firewall.html.en[打开前一个命令输出的端口]。例如，以下命令打开端口2049：
+
----
 sudo ufw allow 2049
----

*结果：*您的NFS服务器已配置，可与Rancher节点一起用于存储。

[#_whats_next]
== 下一步怎么办？

在Rancher中，将NFS服务器添加为存储卷和/或存储类。添加服务器后，您可以在部署中将其用作存储。
