= Nutanix-Knoten-Vorlagenkonfiguration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: referenz-anleitungen/cluster-konfiguration/Downstream-cluster-konfiguration/knoten-vorlagen-konfiguration/nutanix.adoc 
:product-path: cluster-deployment/infra-providers/nutanix/node-template-configuration.adoc

[#_account_access]
== Kontozugriff

[cols="<,^,<,<"]
|===
| Parameter | required | Beschreibung | Standard

| Management-Endpunkt
| ✓
| Hostname/IP-Adresse von Prism Central
|

| Benutzername
| ✓
| Benutzername des Prism Central-Benutzers
|

| Passwort
| ✓
| Passwort des Prism Central-Benutzers
|

| Unsichere Kommunikation zulassen
|
| Auf true setzen, um unsichere SSL-Kommunikation zu Prism Central zuzulassen
| Falsch
|===

[#_scheduling]
== Planung

Wählen Sie aus, zu welchem Nutanix-Cluster die virtuelle Maschine geplant werden soll.

[cols="<,^,<"]
|===
| Parameter | required | Beschreibung

| Cluster
| ✓
| Name des Nutanix-Clusters, in dem die VM bereitgestellt werden soll (Groß- und Kleinschreibung beachten)
|===

[#_instance_options]
== Instanzoptionen

Im Abschnitt *Instanzoptionen* konfigurieren Sie die Anzahl der vCPUs, den Arbeitsspeicher und die Festplattengröße für die von dieser Vorlage erstellten VMs.

[cols="<,^,<,<"]
|===
| Parameter | required | Beschreibung | Standard

| CPUs
|
| Anzahl der vCPUs, die der VM zugewiesen sind (Kerne)
| 2

| Arbeitsspeicher
|
| Menge an RAM, die der VM zugewiesen ist (MB)
| 2 GB

| Vorlagenbild
| ✓
| Name der Festplattenbildvorlage, die als primäre Festplatte der VM geklont werden soll (muss cloud-init unterstützen)
|

| VM-Festplattengröße
|
| Neue Größe der primären Festplatte der VM (in GiB)
|

| Zusätzliche Festplattengröße
|
| Größe einer zusätzlichen Festplatte, die der VM hinzugefügt werden soll (in GiB)
|

| Speichercontainer
|
| Speichercontainer _UUID_, in dem eine zusätzliche Festplatte bereitgestellt werden soll
|

| Cloud Config YAML
|
| Cloud-init, um der VM zur Verfügung gestellt zu werden (wird mit dem Rancher-Root-Benutzer gepatcht)
|

| Netzwerk
| ✓
| Name(n) des/der Netzwerke, die an die VM angeschlossen werden sollen
|

| VM-Kategorien
|
| Name(n) der Kategorien, die auf die VM angewendet werden sollen
|
|===

Die VM kann jedes moderne Linux-Betriebssystem verwenden, das mit Unterstützung für https://cloudinit.readthedocs.io/en/latest/[cloud-init] konfiguriert ist, unter Verwendung der https://cloudinit.readthedocs.io/en/latest/reference/datasources/configdrive.html[Config Drive v2-Datenquelle].

[#_networks]
== Netzwerke

Die Knotenvorlage ermöglicht es, eine VM mit mehreren Netzwerken bereitzustellen. Im Feld *Netzwerk* können Sie auf *Hinzufügen* klicken, um alle in AOS verfügbaren Netzwerke hinzuzufügen.

[#_vm_categories]
== VM-Kategorien

Eine Kategorie ist eine Gruppierung von Entitäten in ein Schlüssel-Wert-Paar. Typischerweise werden VMs basierend auf bestimmten Kriterien einer Kategorie zugewiesen. Richtlinien können dann an die Entitäten gebunden werden, die einem bestimmten Kategorienwert zugewiesen (gruppiert) sind.

[#_cloud_init]
== cloud-init

https://cloudinit.readthedocs.io/en/latest/[Cloud-init] ermöglicht es Ihnen, Ihre Knoten zu initialisieren, indem Sie beim ersten Bootvorgang Konfiguration anwenden. Dies kann Dinge wie das Erstellen von Benutzern oder das Autorisieren von SSH-Schlüsseln umfassen.

Um die Initialisierung von cloud-init zu nutzen, fügen Sie eine Cloud-Konfiguration mit gültiger YAML-Syntax in das Feld *Cloud Config YAML* ein. Verweisen Sie auf die https://cloudinit.readthedocs.io/en/latest/topics/examples.html[cloud-init-Dokumentation] für eine kommentierte Sammlung von Beispielen unterstützter Cloud-Konfigurationsanweisungen.

Beachten Sie, dass eine auf cloud-init basierende Netzwerkkonfiguration nicht empfohlen wird und nur über Benutzerdaten `runcmd` unterstützt wird, nicht jedoch über NoCloud oder andere Netzwerkkonfigurationsdatenquellen.

Nutanix IP-Adressmanagement (IPAM) oder ein anderer DHCP-Dienst wird empfohlen.

[#_engine_options]
== Engine-Optionen

Im Abschnitt *Engine-Optionen* der Knotenvorlage können Sie den Container-Daemon konfigurieren. Sie möchten möglicherweise die Container-Version oder einen Container-Image-Registry-Mirror angeben.

[NOTE]
====
Wenn Sie Red Hat Enterprise Linux (RHEL) oder CentOS-Knoten bereitstellen, lassen Sie das Feld *Docker Install URL* auf dem Standardwert oder wählen Sie *keine* aus. Dies umgeht eine Überprüfung der Docker-Installation, da Docker bereits auf diesen Knotentypen installiert ist.

Wenn Sie *Docker Install URL* auf einen anderen Wert als den Standard oder *keine* setzen, könnte eine Fehlermeldung wie die folgende angezeigt werden: `Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`
====

