= Erstellen eines Nutanix AOS-Clusters
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/starten-von-kubernetes-mit-rancher/neue-knoten-in-einem-infrastrukturprovider/nutanix/index.adoc 
:product-path: cluster-deployment/infra-providers/nutanix/nutanix.adoc
:description: Verwenden Sie Rancher, um einen Nutanix AOS (AHV)-Cluster zu erstellen. Er kann aus Gruppen von VMs mit unterschiedlichen Eigenschaften bestehen, die eine feingranulare Kontrolle über die Größe der Knoten ermöglichen.
ifeval::["{build-type}" != "community"]
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:xref-nutanix-aos-provisioning: xref:cluster-deployment/infra-providers/nutanix/provision-kubernetes-clusters-in-aos.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-landing-page: https://docs.k3s.io/
:url-rke2-landing-page: https://docs.rke2.io/
:xref-nutanix-aos-provisioning: xref:how-to-guides/neue-benutzeranleitungen/starten-von-kubernetes-mit-rancher/neue-knoten-in-einem-infrastrukturprovider/nutanix/provision-kubernetes-clusters-in-aos.adoc
endif::[]

https://www.nutanix.com/products/acropolis[Nutanix Acropolis-Betriebssystem] (Nutanix AOS) ist ein Betriebssystem für die Nutanix hyperkonvergente Infrastrukturplattform. AOS wird mit einem integrierten Hypervisor namens https://www.nutanix.com/products/ahv[Acropolis Hypervisor] oder AHV geliefert. Durch die Verwendung von Rancher mit Nutanix AOS (AHV) können Sie Cloud-Operationen lokal durchführen.

Rancher kann Knoten in AOS (AHV) bereitstellen und Kubernetes auf ihnen installieren. Beim Erstellen eines Kubernetes-Clusters in AOS stellt Rancher zunächst die angegebene Anzahl von virtuellen Maschinen bereit, indem es mit der Prism Central API kommuniziert. Dann installiert es Kubernetes auf den VMs.

Ein Nutanix-Cluster kann aus mehreren Gruppen von VMs mit unterschiedlichen Eigenschaften bestehen, wie z.B. der Menge an Arbeitsspeicher oder der Anzahl der vCPUs. Diese Gruppierung ermöglicht eine feingranulare Kontrolle über die Größe der Knoten für jede Kubernetes-Rolle.

[#_creating_a_nutanix_cluster]
== Erstellen eines Nutanix-Clusters

Verweisen Sie auf das {xref-nutanix-aos-provisioning}[Bereitstellen von Kubernetes-Clustern in Nutanix AOS], um zu erfahren, wie Sie Rancher verwenden, um ein {url-rke2-landing-page}[RKE2]/{url-k3s-landing-page}[K3s]-Kubernetes-Cluster in Nutanix AOS zu installieren.
