= Etapas Adicionais para Instalar o Istio em clusters {rke2-product-name} e {k3s-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc 
:product-path: observability/istio/configuration/install-istio-on-rke2-cluster.adoc

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] foi descontinuado desde o Rancher v2.12.0; recorra à https://apps.rancher.io[SUSE Application Collection] versão do Istio para segurança aprimorada (incluída nas assinaturas do SUSE Rancher Prime).
Informações detalhadas podem ser encontradas em https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anúncio].
====

Ao instalar ou atualizar o gráfico Helm do Istio através de *Apps,*

. Se você estiver instalando o gráfico, clique em *Personalizar opções do Helm antes da instalação* e clique em *Próximo*.
. Você verá opções para configurar o gráfico Helm do Istio. Na aba *Componentes*, marque a caixa ao lado de *Enabled CNI*.
. Adicione um arquivo de sobreposição personalizado especificando `cniBinDir` e `cniConfDir`. Para mais informações sobre essas opções, consulte a https://istio.io/latest/docs/setup/additional-setup/cni/#helm-chart-parameters[documentação do Istio.] Um exemplo está abaixo:

[tabs]
======
RKE2::
+
--
[,yaml]
----
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
      k8s:
        overlays:
        - apiVersion: "apps/v1"
          kind: "DaemonSet"
          name: "istio-cni-node"
          patches:
          - path: spec.template.spec.containers.[name:install-cni].securityContext.privileged
            value: true
  values:
    cni:
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
----
--

K3s::
+
--
[,yaml]
----
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
      k8s:
        overlays:
        - apiVersion: "apps/v1"
          kind: "DaemonSet"
          name: "istio-cni-node"
          patches:
          - path: spec.template.spec.containers.[name:install-cni].securityContext.privileged
            value: true
  values:
    cni:
      cniBinDir: /var/lib/rancher/k3s/data/current/bin
      cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
----
--
======

*Resultado:* Agora você deve ser capaz de utilizar o Istio conforme desejado, incluindo injeção de sidecar e monitoramento via Kiali.
