= Provisioning Storage Examples
:page-languages: [en, zh]
:revdate: 2024-12-13
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/index.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/examples/examples.adoc

Rancher supports persistent storage with a variety of volume plugins. However, before you use any of these plugins to bind persistent storage to your workloads, you have to configure the storage itself, whether its a cloud-based solution from a service-provider or an on-prem solution that you manage yourself.

For your convenience, Rancher offers documentation on how to configure some of the popular storage methods:

* xref:cluster-admin/manage-clusters/persistent-storage/examples/nfs-storage.adoc[NFS]
* xref:cluster-admin/manage-clusters/persistent-storage/examples/vsphere-storage.adoc[vSphere]
* xref:cluster-admin/manage-clusters/persistent-storage/examples/persistent-storage-in-amazon-ebs.adoc[EBS]
