= Einrichten von Prometheus Federator für eine Arbeitslast
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: anleitung-guides/advanced-user-guides/monitoring-alerting-guides/prometheus-federator-guides/arbeitslasten-einrichten.adoc 
:product-path: observability/monitoring-and-dashboards/prometheus-federator/set-up-workloads.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-workload-monitoring: xref:observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-workload-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc
endif::[]

[#_display_cpu_and_memory_metrics_for_a_workload]
== CPU- und Arbeitsspeicher-Metriken für eine Arbeitslast anzeigen

Die Anzeige von CPU- und Speichermetriken mit Prometheus Federator erfolgt auf die gleiche Weise wie bei rancher-monitoring. For instructions, refer {xref-rancher-workload-monitoring}#_display_cpu_and_memory_metrics_for_a_workload[here].

[#_setting_up_metrics_beyond_cpu_and_memory]
== Einrichten von Metriken über CPU und Arbeitsspeicher hinaus

Das Einrichten von Metriken über CPU und Speicher hinaus mit Prometheus Federator erfolgt auf die gleiche Weise wie bei rancher-monitoring. Für Anweisungen siehe {xref-rancher-workload-monitoring}#_einrichten_von_metriken_über_cpu_und_speicher_hinaus[hier].
