= Solução de Problemas de Nós do Controlplane
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/kubernetes-components/troubleshooting-controlplane-nodes.adoc 
:product-path: troubleshooting/kubernetes-components/troubleshooting-controlplane-nodes.adoc

Esta seção se aplica aos nós com a função `controlplane`.

[#_check_if_the_controlplane_containers_are_running]
== Verifique se os contêineres do Controlplane estão em execução.

Existem três contêineres específicos lançados em nós com a função `controlplane`:

* `kube-apiserver`
* `kube-controller-manager`
* `kube-scheduler`

Os contêineres devem ter o status *Up*. A duração mostrada após *Up* é o tempo que o contêiner está em execução.

----
docker ps -a -f=name='kube-apiserver|kube-controller-manager|kube-scheduler'
----

Saída de exemplo:

----
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
26c7159abbcc        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-apiserver
f3d287ca4549        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-scheduler
bdf3898b8063        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-controller-manager
----

[#_controlplane_container_logging]
== Registro de Contêiner do Controlplane

[NOTE]
====

Se você adicionou vários nós com a função `controlplane`, tanto `kube-controller-manager` quanto `kube-scheduler` usam um processo de eleição de líder para determinar o líder. Apenas o líder atual registrará as ações realizadas. Veja xref:troubleshooting/other-troubleshooting-tips/kubernetes-resources.adoc#_kubernetes_leader_election[Kubernetes leader election] como recuperar o líder atual.
====


O registro dos contêineres pode conter informações sobre qual poderia ser o problema.

----
docker logs kube-apiserver
docker logs kube-controller-manager
docker logs kube-scheduler
----

[#__rke2_product_name_server_logging]
== {rke2-product-name} Registro do Servidor

Se o Rancher provisionar um cluster RKE2 que não consegue se comunicar com o Rancher, você pode executar este comando em um nó de servidor no cluster downstream para obter os logs do servidor RKE2.

----
journalctl -u rke2-server -f
----
