= Kubernetesの概念
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-27
:page-revdate: {revdate}
:community-path: reference-guides/kubernetes-concepts.adoc 
:product-path: about-rancher/concepts.adoc
ifeval::["{build-type}" != "community"]
:xref-workloads-and-pods: xref:cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-workloads-and-pods: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc
endif::[]


このページでは、Rancherの動作を理解するために重要なKubernetesに関連する概念を説明します。以下の説明は、Kubernetesコンポーネントの簡略化された概要を提供します。詳細については、 https://kubernetes.io/docs/concepts/overview/components/[Kubernetesコンポーネントに関する公式ドキュメント]を参照してください。

[#_about_docker]
== Dockerについて

Dockerは、コンテナのパッケージングとランタイムの標準です。開発者はDockerfileからコンテナイメージを構築し、Dockerレジストリからコンテナイメージを配布できます。 https://hub.docker.com[Docker Hub]は人気のある公共レジストリです。多くの組織もプライベートDockerレジストリを設定します。Dockerは主に個々のノード上でコンテナを管理するために使用されます。

[#_about_kubernetes]
== Kubernetesについて

Kubernetesは、コンテナクラスター管理の標準です。YAMLファイルは、アプリケーションを構成するコンテナやその他のリソースを指定します。Kubernetesは、スケジューリング、スケーリング、サービス発見、ヘルスチェック、シークレット管理、設定管理などの機能を実行します。

[#_what_is_a_kubernetes_cluster]
== Kubernetesクラスターとは何ですか？

クラスターは、単一のシステムとして協力して動作するコンピュータのグループです。

_Kubernetesクラスター_は、 https://kubernetes.io/[Kubernetesコンテナオーケストレーションシステム]を使用してコンテナをデプロイ、維持、スケールするクラスターであり、組織がアプリケーションの運用を自動化できるようにします。

[#_roles_for_nodes_in_kubernetes_clusters]
== Kubernetesクラスターにおけるノードの役割

Kubernetesクラスターの各コンピューティングリソースは、_ノード_と呼ばれます。ノードは、ベアメタルサーバ、または仮想マシンのいずれかが可能です。Kubernetesはノードを3種類に分類します：_etcd_ノード、_コントロールプレーン_ノード、および_ワーカー_ノードです。

Kubernetesクラスターは、少なくとも1つのetcd、コントロールプレーン、およびワーカーノードで構成されています。

[#_etcd_nodes]
=== etcdノード

Rancherは、単一ノードおよび高可用性インストールの両方でetcdをデータストアとして使用します。Kubernetesでは、etcdはクラスタの状態を保存するノードの役割も果たします。

Kubernetesクラスタの状態は https://kubernetes.io/docs/concepts/overview/components/#etcd[etcd.]に保持されます。etcdノードはetcdデータベースを実行します。

etcdデータベースコンポーネントは、クラスタの調整や状態管理など、すべてのクラスタデータのKubernetesストレージとして使用される分散型キー-バリューストアです。常にフェールオーバー用のバックアップが利用できるように、複数のノードでetcdを実行することをお勧めします。

etcdを1つのノードで実行することもできますが、etcdはクラスタの状態を更新するために、過半数のノード、すなわちクォーラムが必要です。クラスタは常にクォーラムを形成するのに十分な健全なetcdノードを含むべきです。n個のメンバーを持つクラスタの場合、クォーラムは(n/2)+1です。奇数サイズのクラスタにノードを追加すると、常にクォーラムに必要なノードの数が増加します。

小規模なクラスタには通常3つのetcdノードで十分であり、大規模なクラスタには5つのetcdノードが推奨されます。

[#_controlplane_nodes]
=== コントロールプレーンノード

コントロールプレーンノードはKubernetes APIサーバー、スケジューラー、およびコントローラーマネージャーを実行します。これらのノードは、クラスタが設定を維持できるようにルーチンタスクを処理します。すべてのクラスタデータはetcdノードに格納されるため、コントロールプレーンノードはステートレスです。コントロールプレーンは単一ノードで実行できますが、冗長性のために3つ以上のノードを推奨します。さらに、単一ノードがコントロールプレーンとetcdの役割を共有することもできます。

[#_worker_nodes]
=== ワーカーノード

各 https://kubernetes.io/docs/concepts/architecture/nodes/[ワーカーノード]は次のように実行されます：

* *Kubelets:*ノードの状態を監視し、コンテナが正常であることを確認するエージェントです。
* *ワークロード:*アプリを保持するコンテナとポッド、ならびに他のタイプのデプロイメントです。

ワーカーノードは、必要に応じてストレージおよびネットワーキングドライバー、そしてイングレスコントローラーも実行します。{xref-workloads-and-pods}[ワークロード]を実行するために必要なだけのワーカーノードを作成します。

[#_about_helm]
== Helmについて

Rancherの高可用性インストールには、KubernetesクラスターにRancherをインストールするためにHelmが使用されます。

HelmはKubernetesのためのパッケージ管理ツールです。Helmチャートは、Kubernetes YAMLマニフェストドキュメントのテンプレート構文を提供します。Helmを使用すると、静的ファイルを使用する代わりに、設定可能なデプロイメントを作成できます。独自のデプロイメントカタログを作成する方法についての詳細は、 https://helm.sh.のドキュメントを参照してください。

サービスアカウントとクラスター役割バインディングに関する詳細は、 https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Kubernetesのドキュメントを参照してください。]
