= {elemental-product-name}
:revdate: 2024-12-13
:page-revdate: {revdate}

Elemental enables cloud-native host management. Elemental allows you to onboard any machine in any location, whether its in a datacenter or on the edge, and integrate them seamlessly into Kubernetes while managing your workflows (e.g., OS updates).

== {elemental-product-name} with Rancher

Elemental in Rancher:

* Is Kubernetes native, which allows you to manage the OS via Elemental in Kubernetes clusters.
* Is nondisruptive from a Kubernetes operational perspective.
* Is declarative and GitOps friendly.
* Allows OCI Image-based flows, which are trusted, deterministic, and predictable.
* Works at scale. It enables fleet-sized OS management.

=== When should I use {elemental-product-name}?

* Elemental enables cloud-native OS management from Rancher manager. It works with any OS (e.g., SLE Micro vanilla).
* Elemental allows cloud-native management for machines in datacenters and on the edge.
* Elemental is flexible and allows platform teams to perform all kind of workflows across their fleet of machines.

== {elemental-product-name} with {rancher-prime}

* Deeply integrated already as GUI Extension in Rancher.
* Extends the Rancher story to the OS. Working perfectly with SLE Micro for Rancher today.
