= Utilitaire kubectl
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cli-with-rancher/kubectl-utility.adoc 
:product-path: rancher-admin/cli/kubectl.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
endif::[]

[#_kubectl]
== kubectl

Interagissez avec Rancher en utilisant kubectl.

[#_kubectl_utility]
=== Utilitaire kubectl

Installez l'utilitaire `kubectl`. Voir https://kubernetes.io/docs/tasks/tools/install-kubectl/[installer kubectl].

Configurez kubectl en visitant votre cluster dans l'interface Web de Rancher, en cliquant sur `Kubeconfig`, en copiant le contenu et en le mettant dans votre fichier `~/.kube/config`.

Exécutez `kubectl cluster-info` ou `kubectl get pods` avec succès.

[#_authentication_with_kubectl_and_kubeconfig_tokens_with_ttl]
=== Authentification avec kubectl et tokens kubeconfig avec TTL

_Configuration requise_

Si les administrateurs ont xref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[désactivé la génération de token kubeconfig], le fichier kubeconfig nécessite que le {xref-rancher-cli}[Rancher CLI] soit présent dans votre PATH lorsque vous exécutez `kubectl`. Sinon, vous verrez une erreur comme{nbsp}:
`Unable to connect to the server: getting credentials: exec: exec: "rancher": executable file not found in $PATH`.

Cette fonctionnalité permet à kubectl de s'authentifier auprès du serveur Rancher et d'obtenir un nouveau token kubeconfig si nécessaire. Les fournisseurs d'authentification suivants sont actuellement pris en charge{nbsp}:

. Local
. Active Directory (LDAP uniquement)
. FreeIPA
. OpenLDAP
. Fournisseurs SAML{nbsp}: Ping, Okta, ADFS, Keycloak, Shibboleth
. Azure AD

Lorsque vous exécutez kubectl pour la première fois, par exemple, `kubectl get pods`, vous êtes invité à choisir un fournisseur d'authentification et à vous connecter au serveur Rancher. Le token kubeconfig est mis en cache dans le chemin où vous exécutez kubectl sous `./.cache/token`. Ce token est valide jusqu'à xref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[son expiration], ou xref:api/api-tokens.adoc#_deleting_tokens[sa suppression du serveur Rancher]. À l'expiration, vous devez vous reconnecter au serveur Rancher pour exécuter la commande `kubectl get pods`.
