= レイヤー4およびレイヤー7の負荷分散
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-23
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/layer-4-and-layer-7-load-balancing.adoc 
:product-path: cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/layer-4-and-layer-7-load-balancing.adoc
:description: Kubernetesは2つの方法で負荷分散をサポートしています：レイヤー4負荷分散とレイヤー7負荷分散です。異なるデプロイメントにおける各方法のサポートについて学びましょう

Kubernetesは2つの方法で負荷分散をサポートしています：レイヤー4負荷分散とレイヤー7負荷分散です。

[#_layer_4_load_balancer]
== レイヤー4負荷分散装置

Layer-4ロードバランサ(または外部ロードバランサ)はトラフィックをNodeportに転送します。レイヤー4負荷分散装置は、HTTPおよびTCPトラフィックの両方を転送することを可能にします。

[NOTE]
====
https://metallb.universe.tf/[MetalLB]のような非クラウド負荷分散装置でクラスターをデプロイすることも可能ですが、これはクラウドプロバイダーがサポートするレイヤー4負荷分散装置よりも高度な使用ケースであり、Rancherでは設定できません。
====


[#_support_for_layer_4_load_balancing]
=== レイヤー4負荷分散のサポート

レイヤー4負荷分散装置のサポートは、基盤となるクラウドプロバイダーによって異なります。

|===
| クラスタの展開 | レイヤー4負荷分散装置サポート

| Amazon EKS
| AWSクラウドプロバイダーによってサポートされています

ifeval::["{build-type}" != "srfa"]
| Google GKE
| GCEクラウドプロバイダーによってサポートされています

| Azure AKS
| Azureクラウドプロバイダーによってサポートされています
endif::[]

| サードパーティのMetalLB
| サードパーティのIngress*
|===

[#_layer_7_load_balancer]
== レイヤー7負荷分散装置

レイヤー7負荷分散装置（またはイングレスコントローラー）は、ホスト名およびパスベースの負荷分散とSSL終端をサポートしています。レイヤー7の負荷分散装置は、HTTPおよびHTTPSトラフィックのみを転送し、ポート80および443のみにリスンします。AmazonやGoogleなどのクラウドプロバイダーは、レイヤー7の負荷分散装置をサポートしています。

[#_support_for_layer_7_load_balancing]
=== レイヤー7負荷分散のサポート

レイヤー7の負荷分散装置のサポートは、基盤となるクラウドプロバイダーによって異なります。

|===
| クラスタの展開 | レイヤー7負荷分散装置サポート

| Amazon EKS
| AWSクラウドプロバイダーによってサポートされています

ifeval::["{build-type}" != "srfa"]
| Google GKE
| GKEクラウドプロバイダーによってサポートされています。

| Azure AKS
| サポート対象外
endif::[]
|===

[#_host_names_in_layer_7_load_balancer]
=== レイヤー7負荷分散装置のホスト名

一部のクラウド管理型レイヤー7負荷分散装置（AWSのALBイングレスコントローラーなど）は、イングレスルールのためのDNSアドレスを公開します。レイヤー7の負荷分散装置によって生成されたDNSアドレスに、あなたのドメイン名をCNAME経由でマッピングする必要があります。

Google負荷分散装置などの他のレイヤー7負荷分散装置は、1つ以上のIPアドレスを直接公開します。Google負荷分散装置は、単一のルーティング可能なIPアドレスを提供します。次のいずれかを実行できます：

. 自分のDNSを設定して、レイヤー7負荷分散装置によって公開されたIPアドレスにドメイン名をAレコード経由でマッピングします。
. Rancherに、イングレスルールのためのxip.ioホスト名を生成するように依頼します。Rancherは、あなたの公開されたIPの1つ、例えば`a.b.c.d`を取り、ホスト名`<ingressname>.<namespace>.a.b.c.d.xip.io`を生成します。

xip.ioを使用する利点は、イングレスルールを作成した直後に動作するエントリポイントURLを取得できることです。一方、自分のドメイン名を設定するには、DNSサーバーを構成し、DNSの伝播を待つ必要があります。

[#_related_links]
== 関連リンク

* https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/[外部負荷分散装置を作成する]
