= Einrichten eines VMware vSphere Cloud Providers außerhalb des Baums
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:experimental:

Kubernetes entfernt sich von der Pflege von Cloud-Anbietern im Baum. VMware vSphere hat einen Cloud Provider außerhalb des Baums, der durch die Installation des vSphere Cloud Providers und der Cloud-Speicher-Plugins verwendet werden kann.

Diese Seite behandelt, wie man die Cloud Provider Interface (CPI) und Cloud Storage Interface (CSI) Plugins nach der Einrichtung eines Clusters installiert.

[#_prerequisites]
== Voraussetzungen

Die unterstützten vSphere-Versionen sind:

* 6.7u3
* 7.0u1 oder höher.

Die Kubernetes-Version muss 1.19 oder höher sein.

Die Verwendung des vSphere Cloud Providers außerhalb des Baums erfordert Linux-Knoten und wird nicht auf Windows unterstützt.

[#_installation]
== Installation

Das Cloud Provider Interface (CPI) sollte zuerst installiert werden, bevor das Cloud Storage Interface (CSI) installiert wird.

[#_1_create_a_vmware_vsphere_cluster]
=== 1. Erstellen Sie einen VMware vSphere Cluster

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zur Seite *Cluster* und klicken Sie auf *Erstellen*.
. Klicken Sie auf *VMware vSphere* oder *Benutzerdefiniert*.
. Gehen Sie zum Tab *Grundlagen* im Abschnitt *Cluster-Konfiguration* und setzen Sie den *Cloud Provider* auf *vSphere*.
. Im Tab *Add-on-Konfiguration* befinden sich die Optionen für den vSphere Cloud Provider (CPI) und den Storage-Provider (CSI).
. Vervollständigen Sie die Erstellung Ihres Clusters.

[#_2_install_the_cpi_plugin]
=== 2. Installieren Sie das CPI-Plugin

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem das vSphere CPI-Plugin installiert werden soll, und klicken Sie auf *Erforschen*.
. Klicken Sie auf menu:Apps[Diagramme].
. Klicken Sie auf *vSphere CPI*.
. Füllen Sie die erforderlichen vCenter-Details aus.
. vSphere CPI initialisiert alle Knoten mit ProviderID, die vom vSphere CSI-Treiber benötigt wird. Überprüfen Sie, ob alle Knoten mit der ProviderID initialisiert sind, bevor Sie den CSI-Treiber mit dem folgenden Befehl installieren:
+
----
 kubectl describe nodes | grep "ProviderID"
----

[#_3_installing_the_csi_plugin]
=== 3. Installation des CSI-Plugins

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem das vSphere CSI-Plugin installiert werden soll, und klicken Sie auf *Erforschen*.
. Klicken Sie auf menu:Apps[Diagramme].
. Klicken Sie auf *vSphere CSI*.
. Klicken Sie auf *Installieren*.
. Füllen Sie die erforderlichen vCenter-Details aus. Setzen Sie im Tab *Funktionen* *CSI-Migration aktivieren* auf *false*.
. Füllen Sie im Tab *Speicher* die Details für die StorageClass aus. Dieses Chart erstellt eine StorageClass mit `csi.vsphere.vmware.com` als Provisioner.
. Klicken Sie auf *Installieren*.

[#_using_the_csi_driver_for_provisioning_volumes]
== Verwendung des CSI-Treibers zur Bereitstellung von Volumes

Das CSI-Chart erstellt standardmäßig eine StorageClass.

Wenn diese Option beim Starten des Charts nicht ausgewählt wurde, erstellen Sie eine StorageClass mit `csi.vsphere.vmware.com` als Provisioner.

Alle Volumes, die mit dieser StorageClass bereitgestellt werden, werden vom CSI-Treiber bereitgestellt.
