= Einrichten eines In-tree VMware vSphere Cloud Providers
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/kubernetes-clusters-in-rancher-setup/konfigurieren-von-cloud-anbietern/konfigurieren-von-in-tree-vsphere.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc

Um den In-tree VMware vSphere Cloud Provider einzurichten, befolgen Sie diese Schritte beim Erstellen des vSphere-Clusters in Rancher:

. Setzen Sie die *Cloud Provider*-Option auf `Custom` oder `Custom (In-Tree)`.
. Klicken Sie auf *Als YAML bearbeiten*
. Fügen Sie die folgende Struktur in das vorab ausgefüllte Cluster-YAML ein. Diese Struktur muss unter `rancher_kubernetes_engine_config` platziert werden. Beachten Sie, dass `name` auf `vsphere` _gesetzt werden muss_.
+
[,yaml]
----
 rancher_kubernetes_engine_config:
   cloud_provider:
       name: vsphere
       vsphereCloudProvider:
           [Insert provider configuration]
----

Rancher verwendet RKE (die Rancher Kubernetes Engine), um Kubernetes-Cluster bereitzustellen. Verweisen Sie auf die https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/config-reference/[vSphere-Konfigurationsreferenz in der RKE-Dokumentation] für Details zu den Eigenschaften der `vsphereCloudProvider`-Direktive.
