= Einrichten von Cloud-Anbietern
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/index.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
ifeval::["{build-type}" != "community"]
:xref-azure-cloud-provider: xref:cluster-deployment/set-up-cloud-providers/azure.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-cloud-provider-amazon: xref:cluster-deployment/set-up-cloud-providers/amazon.adoc
:xref-cloud-provider-google-compute-engine: xref:cluster-deployment/set-up-cloud-providers/google-compute-engine.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-azure-cloud-provider: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/cloud-anbieter-setup/azure.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/cloud-anbieter-setup/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/cloud-anbieter-setup/configure-in-tree-vsphere.adoc
:xref-cloud-provider-amazon: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/cloud-anbieter-setup/amazon.adoc
:xref-cloud-provider-google-compute-engine: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/cloud-anbieter-setup/google-compute-engine.adoc
endif::[]

Ein _Cloud-Anbieter_ ist ein Modul in Kubernetes, das eine Schnittstelle zur Verwaltung von Knoten, Lastenausgleich und Netzwerk-Routen bereitstellt.

Wenn ein Cloud-Anbieter in Rancher eingerichtet ist, kann der Rancher-Server automatisch neue Knoten, Lastenausgleich oder persistente Speichergeräte bereitstellen, wenn Kubernetes-Definitionen gestartet werden, sofern der verwendete Cloud-Anbieter eine solche Automatisierung unterstützt.

Ihr Cluster wird nicht korrekt bereitgestellt, wenn Sie einen Cloud-Anbieter-Cluster von Knoten konfigurieren, die die Voraussetzungen nicht erfüllen.

Standardmäßig ist die Option *Cloud-Anbieter* auf `None` eingestellt.

Die folgenden Cloud-Anbieter können aktiviert werden:

* Amazon
* Azure
* GCE (Google Compute Engine)
* vSphere

[#_setting_up_the_amazon_cloud_provider]
== Einrichten des Amazon Cloud-Anbieters

Für Details zur Aktivierung des Amazon-Cloud-Anbieters siehe {xref-cloud-provider-amazon}[diese Seite.]

[#_setting_up_the_azure_cloud_provider]
== Einrichten des Azure-Cloud-Anbieters

Für Details zur Aktivierung des Azure-Cloud-Anbieters siehe {xref-azure-cloud-provider}[diese Seite.]

[#_setting_up_the_gce_cloud_provider]
== Einrichten des GCE-Cloud-Anbieters

Für Details zur Aktivierung des Google Compute Engine-Cloud-Anbieters siehe {xref-cloud-provider-google-compute-engine}[diese Seite.]

[#_setting_up_the_vmware_vsphere_cloud_provider]
== Einrichten des VMware vSphere-Cloud-Anbieters

Für Details zur Aktivierung des vSphere-Cloud-Anbieters siehe {xref-cloud-provider-vsphere}[in-tree vSphere-Konfiguration] und {xref-cloud-provider-vsphere-out-of-tree}[out-of-tree vSphere-Konfiguration].

[#_setting_up_a_custom_cloud_provider]
== Einrichten eines benutzerdefinierten Cloud-Anbieters

Der `Custom` Cloud-Anbieter ist verfügbar, wenn Sie einen beliebigen Kubernetes-Cloud-Anbieter konfigurieren möchten.

Für die Option des benutzerdefinierten Cloud-Anbieters können Sie sich auf die https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/[RKE-Dokumentation] beziehen, wie Sie die YAML-Datei für Ihren spezifischen Cloud-Anbieter bearbeiten. Es gibt spezifische Cloud-Anbieter, die eine detailliertere Konfiguration haben.

* https://rke.docs.rancher.com/config-options/cloud-providers/vsphere[vSphere]
* https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/openstack/[OpenStack]
