= Gerenciando Credenciais de Nuvem
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: reference-guides/user-settings/manage-cloud-credentials.adoc 
:product-path: rancher-admin/users/settings/manage-cloud-credentials.adoc
ifeval::["{build-type}" != "community"]
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-manage-node-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-infra-providers: xref:guias-de-procedimentos/guias-para-novos-usuarios/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-infra-provider/index.adoc
:xref-manage-node-drivers: xref:procedimentos/novos-usuários/guias-de-autenticação-permissões-e-configuração-global/sobre-provisionamento-de-drivers/gerenciar-drivers-de-nó.adoc
endif::[]

A criação ou associação de credenciais de nuvem faz parte do processo de criação do cluster; as informações abaixo fornecem orientações sobre como gerenciar credenciais no Rancher.

As credenciais de nuvem estão vinculadas ao arquivo de controle do seu criador. Elas *não podem* ser compartilhadas entre usuários não administradores. No entanto, os administradores podem visualizar e gerenciar as credenciais de nuvem de outros usuários.

[#_creating_a_cloud_credential]
== Criando uma Credencial de Nuvem

. Clique em *☰ > Gerenciamento de Cluster*.
. Clique em *Credenciais de Nuvem*.
. Clique em *Criar*.
. Clique em um tipo de credencial de nuvem. Os valores deste dropdown são baseados nos `active` {xref-manage-node-drivers}[drivers de nó] no Rancher.
. Digite um nome para a credencial de nuvem.
. Com base no tipo de credencial de nuvem selecionado, insira os valores necessários para autenticar com o provedor de infraestrutura.
. Clique em *Criar*.

**Resultado:** A credencial de nuvem é criada.

[#_updating_a_cloud_credential]
== Atualizando uma Credencial de Nuvem

Quando as credenciais de acesso são alteradas ou comprometidas, atualizar uma credencial de nuvem permite que você rotacione essas credenciais enquanto mantém o mesmo modelo de nó.

. Clique em *☰ > Gerenciamento de Cluster*.
. Clique em *Credenciais de Nuvem*.
. Escolha a credencial de nuvem que deseja editar e clique em *⋮ > Editar Configuração*.
. Atualize as informações da credencial e clique em *Salvar*.

**Resultado:** A credencial de nuvem é atualizada com as novas credenciais de acesso.

[#_deleting_a_cloud_credential]
== Excluindo uma Credencial de Nuvem

. Clique em *☰ > Gerenciamento de Cluster*.
. Clique em *Credenciais de Nuvem*.
. Você pode excluir uma credencial de nuvem individualmente ou excluir em massa.
 ** Para excluir individualmente uma, escolha a credencial de nuvem que deseja editar e clique em *⋮ > Excluir*.
 ** Para excluir credenciais de nuvem em massa, selecione uma ou mais credenciais de nuvem da lista. Clique em *Excluir*.
. Confirme que deseja excluir essas credenciais de nuvem.
