= Configuring an Ingress
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-20
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/ingress-configuration.adoc 
:product-path: cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/ingress-configuration.adoc
:description: Configuring an Ingress
ifeval::["{build-type}" != "community"]
:xref-rke1-config: xref:cluster-deployment/configuration/rke1.adoc
:xref-http-encrypt: xref:security/encrypting-http.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rke1-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/rke1-cluster-configuration.adoc
:xref-http-encrypt: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc
endif::[]

[#_specify_a_hostname_to_use]
== Specify a hostname to use

If you use this option, Ingress routes requests for a hostname to the service or workload that you specify.

. Specify a path of type `Prefix` and specify a path such as `/`.
. Add a *Target Service*.
. *Optional:* If you want to specify a workload or service when a request is sent to a particular hostname path, add a *Path* for the target. For example, if you want requests for `www.mysite.com/contact-us` to be sent to a different service than `www.mysite.com`, enter `/contact-us` in the *Path* field. Typically, the first rule that you create does not include a path.
. Enter the *Port* number that each target operates on.

[#_certificates]
== Certificates

[NOTE]
====

You must have an SSL certificate that Ingress can use to encrypt and decrypt communications. For more information, see {xref-http-encrypt}[Adding SSL Certificates].
====


. To create an Ingress controller, click the *Certificates* tab.
. Click *Add Certificate*.
. Select a *Certificate - Secret Name* from the drop-down list.
. Enter the host using encrypted communication.
. To add more hosts that use the same certificate, click *Add Hosts*.

[#_labels_and_annotations]
== Labels and Annotations

Please refer to the Traefik documentation for the full list of Ingress NGINX annotations that are https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/ingress-nginx/#annotations-support[supported] and https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/ingress-nginx/#unsupported-annotations[unsupported] by Traefik's kubernetesIngressNginx provider.
