= Layer 4 and Layer 7 Load Balancing
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-23
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/layer-4-and-layer-7-load-balancing.adoc 
:product-path: cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/layer-4-and-layer-7-load-balancing.adoc
:description: Kubernetes supports load balancing in two ways: Layer-4 Load Balancing and Layer-7 Load Balancing. Learn about the support for each way in different deployments

Kubernetes supports load balancing in two ways: Layer-4 Load Balancing and Layer-7 Load Balancing.

[#_layer_4_load_balancer]
== Layer-4 Load Balancer

Layer-4 load balancer (or the external load balancer) forwards traffic to Nodeports. Layer-4 load balancer allows you to forward both HTTP and TCP traffic.

[NOTE]
====
It is possible to deploy a cluster with a non-cloud load balancer, such as https://metallb.universe.tf/[MetalLB.] However, that use case is more advanced than the Layer-4 load balancer supported by a cloud provider, and it is not configurable in Rancher.
====


[#_support_for_layer_4_load_balancing]
=== Support for Layer-4 Load Balancing

Support for layer-4 load balancer varies based on the underlying cloud provider.

|===
| Cluster Deployment | Layer-4 Load Balancer Support

| Amazon EKS
| Supported by AWS cloud provider

ifeval::["{build-type}" != "srfa"]
| Google GKE
| Supported by GCE cloud provider

| Azure AKS
| Supported by Azure cloud provider
endif::[]

| Third-party MetalLB
| third-party Ingress*
|===

[#_layer_7_load_balancer]
== Layer-7 Load Balancer

Layer-7 load balancer (or the ingress controller) supports host and path-based load balancing and SSL termination. Layer-7 load balancer only forwards HTTP and HTTPS traffic and therefore they listen on ports 80 and 443 only. Cloud providers such as Amazon and Google support layer-7 load balancer.

[#_support_for_layer_7_load_balancing]
=== Support for Layer-7 Load Balancing

Support for layer-7 load balancer varies based on the underlying cloud provider.

|===
| Cluster Deployment | Layer-7 Load Balancer Support

| Amazon EKS
| Supported by AWS cloud provider

ifeval::["{build-type}" != "srfa"]
| Google GKE
| Supported by GKE cloud provider

| Azure AKS
| Not Supported
endif::[]
|===

[#_host_names_in_layer_7_load_balancer]
=== Host Names in Layer-7 Load Balancer

Some cloud-managed layer-7 load balancers (such as the ALB ingress controller on AWS) expose DNS addresses for ingress rules. You need to map (via CNAME) your domain name to the DNS address generated by the layer-7 load balancer.

Other layer-7 load balancers, such as the Google Load Balancer, directly expose one or more IP addresses. Google Load Balancer provides a single routable IP address. You can do either of the following:

. Configure your own DNS to map (via A records) your domain name to the IP addresses exposes by the Layer-7 load balancer.
. Ask Rancher to generate an xip.io host name for your ingress rule. Rancher will take one of your exposed IPs, say `a.b.c.d`, and generate a host name `<ingressname>.<namespace>.a.b.c.d.xip.io`.

The benefit of using xip.io is that you obtain a working entrypoint URL immediately after you create the ingress rule. Setting up your own domain name, on the other hand, requires you to configure DNS servers and wait for DNS to propagate.

[#_related_links]
== Related Links

* https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/[Create an External Load Balancer]
