= Guide sur la mise hors service d'Ingress NGINX
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-25
:page-revdate: {revdate}
:community-path: guides-de-procédure/nouveaux-guides-utilisateurs/configuration-des-ressources-kubernetes/équilibreur-de-charge-et-contrôleur-ingress/guide-de-la-mise-hors-service-d-ingress-nginx.adoc 
:product-path: administrateur-de-cluster/ressources-kubernetes/équilibreur-de-charge-et-contrôleur-ingress/guide-de-la-mise-hors-service.adoc
:description: Guide sur la mise hors service d'Ingress NGINX
ifeval::["{build-type}" != "community"]
:url-storage-longhorn-ingress-traefik: https://documentation.suse.com/cloudnative/storage/1.11/en/longhorn-system/system-access/longhorn-ingress-traefik.html
:url-continuous-delivery-webhook: https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/how-tos-for-users/webhook.html
:xref-rancher-on-amazon-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc#_5_install_an_ingress
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc#_5_install_an_ingress
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc#_7_install_an_ingress
endif::[]
ifeval::["{build-type}" == "community"]
:url-storage-longhorn-ingress-traefik: https://longhorn.io/docs/1.11.1/deploy/accessing-the-ui/longhorn-ingress-traefik/#additional-steps-for-aws-eks-kubernetes-clusters
:url-continuous-delivery-webhook: https://fleet.rancher.io/0.15/how-tos-for-users/webhook#_1_configure_the_webhook_service
:xref-rancher-on-amazon-eks: xref:démarrer/installation-et-mise-à-niveau/installer-mise-à-niveau-sur-un-cluster-kubernetes/rancher-sur-amazon-eks.adoc#_5_installer_un_ingress
:xref-rancher-on-aks: xref:démarrer/installation-et-mise-à-niveau/installer-mise-à-niveau-sur-un-cluster-kubernetes/rancher-sur-aks.adoc#_5_installer_un_ingress
:xref-rancher-on-gke: xref:démarrer/installation-et-mise-à-niveau/installer-mise-à-niveau-sur-un-cluster-kubernetes/rancher-sur-gke.adoc#_7_installer_un_ingress
endif::[]

Le SIG Réseau Kubernetes et le Comité de Réponse à la Sécurité ont annoncé la https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/[mise hors service du projet Ingress NGINX]. La maintenance en amont à meilleur effort, ainsi que toutes les versions en amont associées, les correctifs ou mises à jour de sécurité, ont pris fin en mars 2026.

Pour soutenir les utilisateurs pendant cette transition, 

ifeval::["{build-type}" != "community"]
SUSE fournit des délais de support prolongés et des chemins de migration clairs vers Traefik. 
endif::[]
ifeval::["{build-type}" == "community"]
Rancher fournit des chemins de migration clairs vers Traefik.
endif::[]

Ce guide centralise les informations sur la manière de procéder en fonction de votre scénario de déploiement spécifique.

[#_support_and_timelines]
== Support et délais

ifeval::["{build-type}" != "community"]
Pour les organisations qui ne peuvent pas migrer immédiatement, {rancher-product-name} LTS fournit un support prolongé pour la version 1.35 de RKE2. 

[IMPORTANT]
.Support prolongé pour Ingress NGINX
====
{rancher-product-name} LTS fournit des correctifs pour les vulnérabilités et expositions communes (CVE) critiques et importantes pour le composant Ingress NGINX jusqu'en décembre 2027. Aucune nouvelle fonctionnalité ne sera ajoutée pendant cette période.
====
endif::[]

ifeval::["{build-type}" == "community"]
Les cycles de vie de Rancher et RKE2 s'alignent sur le calendrier de mise hors service en amont.

[IMPORTANT]
====
Après mars 2026, les images Ingress NGINX en amont ne recevront plus de mises à jour. Toutes les images construites avec des correctifs après cette date sont réservées aux clients commerciaux. Les utilisateurs doivent migrer vers Traefik ou un autre contrôleur Ingress pris en charge avant cette date limite pour garantir la sécurité et la compatibilité continues.
====
endif::[]

[#_migration_paths_by_environment]
== Chemins de migration par environnement

ifeval::["{build-type}" != "community"]
Pour les organisations prêtes à migrer, SUSE propose un chemin pris en charge vers Traefik. 
endif::[]
ifeval::["{build-type}" == "community"]
Les cycles de vie de Rancher et RKE2 s'alignent sur le calendrier de mise hors service en amont.
endif::[]

Traefik comprend une couche de compatibilité qui peut interpréter de nombreuses annotations Ingress NGINX existantes. Identifiez votre environnement de cluster ci-dessous pour trouver l'approche de migration correcte.

[#_standalone_rke2_clusters]
=== Clusters RKE2 autonomes

Pour les clusters RKE2 autonomes ou importés utilisant actuellement Ingress NGINX, suivez le https://support.scc.suse.com/s/kb/Migrating-from-Ingress-NGINX-to-Traefik-in-a-standalone-RKE2-cluster?language=en_US[guide de migration officiel pour les clusters RKE2 autonomes]. 

Le processus de migration implique une stratégie en quatre phases{nbsp}:

. *Configuration du contrôleur d'ingress en double :* Activez Traefik aux côtés d'Ingress NGINX en utilisant des ports temporaires sans conflit.
. *Migration et validation parallèles :* Dupliquez les ressources Ingress et testez la gestion des annotations existantes par Traefik.
. *Changement final :* Supprimez Ingress NGINX et configurez Traefik pour utiliser les ports standards.
. *Nettoyage:* Supprimez les objets Ingress hérités.

[#_rancher_server_on_rke2_local_clusters]
=== Serveur Rancher sur RKE2 (Grappes locales)

Lors de la migration d'une grappe locale Rancher, la ressource Ingress de Rancher nécessite un traitement spécifique pour éviter les verrouillages. Suivez le https://support.scc.suse.com/s/kb/How-to-migrate-the-Rancher-Ingress-to-Traefik-in-an-RKE2-cluster?language=en_US[guide spécifique pour migrer l'Ingress de Rancher vers Traefik dans un cluster RKE2]. Ce guide s'appuie sur les phases de migration autonomes mais inclut des étapes adaptées au serveur de gestion Rancher.

[#_downstream_rke2_clusters_provisioned_by_rancher]
=== Clusters RKE2 en aval (Provisionnés par Rancher)

Pour les clusters RKE2 provisionnés et gérés par {rancher-product-name}, les options de migration sont intégrées directement dans l'interface utilisateur.

[NOTE]
====
ifeval::["{build-type}" != "community"]
Cette option de migration n'est possible que dans Rancher v2.13.5+ et v2.14.
endif::[]
ifeval::["{build-type}" == "community"]
Cette option de migration n'est possible que dans Rancher v2.14.0+.
endif::[]
====

L'interface de configuration du cluster propose une option de migration en mode double. Cela vous permet de tester et de migrer en toute sécurité le trafic d'Ingress NGINX vers Traefik directement depuis l'écran de gestion du cluster.

[#_rancher_on_managed_kubernetes_amazon_eks_azure_aks_google_gke]
=== Rancher sur Kubernetes géré (Amazon EKS, Azure AKS, Google GKE)

Si vous exécutez {rancher-product-name} sur un service Kubernetes géré tel que {xref-rancher-on-amazon-eks}[Amazon Elastic Kubernetes Service (EKS)], {xref-rancher-on-aks}[Azure Kubernetes Service (AKS)], ou {xref-rancher-on-gke}[Google Kubernetes Engine (GKE)], la recommandation est de migrer vers Traefik. 

ifeval::["{build-type}" != "community"]
Les clients de {rancher-product-name} peuvent tirer parti de la Collection d'applications pour déployer et gérer le proxy Traefik.
endif::[]
ifeval::["{build-type}" == "community"]
Les utilisateurs doivent déployer et migrer vers la distribution du proxy Traefik en amont.
endif::[]

ifeval::["{build-type}" != "community"]
[#_impact_on_other_suse_products]
== Impact sur d'autres produits SUSE
endif::[]
ifeval::["{build-type}" == "community"]
[#_impact_on_projects]
== Impact sur les projets
endif::[]

La mise hors service d'Ingress NGINX impacte d'autres 

ifeval::["{build-type}" != "community"]
produits SUSE
endif::[]
ifeval::["{build-type}" == "community"]
projets
endif::[]

de la manière suivante{nbsp}:

* {longhorn-product-name} : Il n'y a pas d'impact sur le backend Longhorn. Cependant, les administrateurs doivent reconfigurer leur Ingress pour mettre à niveau l'interface utilisateur de Longhorn. Pour plus d'informations, consultez {url-storage-longhorn-ingress-traefik}[Créer un Ingress avec authentification de base Traefik].
* {fleet-product-name} : La configuration d'un service webhook est affectée. Reportez-vous à la {url-continuous-delivery-webhook}[documentation Fleet] pour plus d'informations.
* Les références à Ingress NGINX dans la documentation d'autres projets ont été supprimées.
