= Équilibrage de la charge de couche 4 et de couche 7
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-23
:page-revdate: {revdate}
:community-path: procédure-guides/nouveaux-guides-utilisateurs/configuration-des-ressources-kubernetes/équilibreur-de-charge-et-contrôleur-d-ingress/équilibrage-de-charge-de-couche-4-et-de-couche-7.adoc 
:product-path: administrateur-de-cluster/ressources-kubernetes/équilibreur-de-charge-et-contrôleur-d-ingress/équilibrage-de-charge-de-couche-4-et-de-couche-7.adoc
:description: Kubernetes prend en charge l'équilibrage de charge de deux manières{nbsp}: Équilibrage de la charge de couche 4 et équilibrage de la charge de couche 7. Découvrez le support pour chaque méthode dans différents déploiements

Kubernetes prend en charge l'équilibrage de charge de deux manières{nbsp}: Équilibrage de la charge de couche 4 et équilibrage de la charge de couche 7.

[#_layer_4_load_balancer]
== Équilibreur de charge de couche 4

L'équilibreur de charge de couche 4 (ou l'équilibreur de charge externe) redirige le trafic vers les Nodeports. L'équilibreur de charge de couche 4 vous permet de rediriger à la fois le trafic HTTP et TCP.

[NOTE]
====
Il est possible de déployer un cluster avec un équilibreur de charge non cloud, tel que https://metallb.universe.tf/[MetalLB.] Cependant, ce cas d'utilisation est plus avancé que l'équilibreur de charge de couche 4 pris en charge par un fournisseur de cloud, et il n'est pas configurable dans Rancher.
====


[#_support_for_layer_4_load_balancing]
=== Support pour l'équilibrage de la charge de couche 4

Le support pour l'équilibreur de charge de couche 4 varie en fonction du fournisseur de cloud sous-jacent.

|===
| Déploiement de la grappe | Support de l'équilibreur de charge de couche 4

| Amazon EKS
| Prise en charge par le fournisseur de cloud AWS

ifeval::["{build-type}" != "srfa"]
| Google GKE
| Prise en charge par le fournisseur de cloud GCE

| Azure AKS
| Prise en charge par le fournisseur de cloud Azure
endif::[]

| MetalLB tiers
| Ingress tiers*
|===

[#_layer_7_load_balancer]
== Équilibreur de charge de couche 7

L'équilibreur de charge de couche 7 (ou le contrôleur d'entrée) prend en charge l'équilibrage de charge basé sur l'hôte et le chemin ainsi que la terminaison SSL. L'équilibreur de charge de couche 7 ne transfère que le trafic HTTP et HTTPS et écoute donc uniquement sur les ports 80 et 443. Les fournisseurs de cloud tels qu'Amazon et Google prennent en charge l'équilibreur de charge de couche 7.

[#_support_for_layer_7_load_balancing]
=== Support pour l'équilibrage de la charge de couche 7

Le support pour l'équilibreur de charge de couche 7 varie en fonction du fournisseur de cloud sous-jacent.

|===
| Déploiement de la grappe | Support de l'équilibreur de charge de couche 7

| Amazon EKS
| Prise en charge par le fournisseur de cloud AWS

ifeval::["{build-type}" != "srfa"]
| Google GKE
| Prise en charge par le fournisseur de cloud GKE

| Azure AKS
| Non pris en charge
endif::[]
|===

[#_host_names_in_layer_7_load_balancer]
=== Noms d'hôtes dans l'équilibreur de charge de couche 7

Certains équilibreurs de charge de couche 7 gérés par le cloud (comme le contrôleur d'entrée ALB sur AWS) exposent des adresses DNS pour les règles d'entrée. Vous devez mapper (via CNAME) votre nom de domaine à l'adresse DNS générée par l'équilibreur de charge de couche 7.

D'autres équilibreurs de charge de couche 7, tels que le Google Load Balancer, exposent directement une ou plusieurs adresses IP. Le Google Load Balancer fournit une seule adresse IP routable. Vous pouvez procéder de l'une des manières suivantes :

. Configurez votre propre DNS pour mapper (via des enregistrements A) votre nom de domaine aux adresses IP exposées par l'équilibreur de charge de couche 7.
. Demandez à Rancher de générer un nom d'hôte xip.io pour votre règle d'entrée. Rancher prendra l'une de vos IP exposées, disons `a.b.c.d`, et générera un nom d'hôte `<ingressname>.<namespace>.a.b.c.d.xip.io`.

L'avantage d'utiliser xip.io est que vous obtenez immédiatement une URL d'entrée fonctionnelle après avoir créé la règle d'entrée. Configurer votre propre nom de domaine, en revanche, nécessite de configurer des serveurs DNS et d'attendre la propagation DNS.

[#_related_links]
== Liens connexes

* https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/[Créer un équilibreur de charge externe]
