= Clés API
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-06
:page-revdate: {revdate}
:community-path: reference-guides/user-settings/api-keys.adoc 
:product-path: rancher-admin/users/settings/api-keys.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
endif::[]

include::shared:ROOT:partial$en/v3-api-tokens-deprecation-warning.adoc[]

[#_api_keys_and_user_authentication]
== Clés API et authentification des utilisateurs

Si vous souhaitez accéder à vos clusters Rancher, projets ou autres objets à l'aide d'applications externes, vous pouvez le faire en utilisant l'API Rancher. Cependant, avant que votre application puisse accéder à l'API, vous devez fournir à l'appli une clé utilisée pour s'authentifier auprès de Rancher. Vous pouvez obtenir une clé en utilisant l'interface utilisateur de Rancher.

Une clé API est également requise pour utiliser Rancher CLI.

Les clés API sont composées de quatre composants{nbsp}:

* *Point de terminaison :* Ceci est l'adresse IP et le chemin que d'autres applications utilisent pour envoyer des requêtes à l'API Rancher.
* *Clé d'accès :* Le nom d'utilisateur du token.
* *Clé secrète :* Le mot de passe du token. Pour les applications qui vous demandent deux chaînes différentes pour l'authentification API, vous entrez généralement les deux clés ensemble.
* *Jeton d'accès :* Le nom d'utilisateur et le mot de passe du token concaténés ensemble. Utilisez cette chaîne pour les applications qui vous demandent une chaîne d'authentification.

[NOTE]
====

Les utilisateurs peuvent choisir d'activer xref:api/api-tokens.adoc[hachage de token].
====


[#_creating_an_api_key]
== Création d'une clé API

. Sélectionnez menu:Avatar de l'utilisateur[Compte et clés API] dans le coin supérieur droit.
. Cliquez sur *Créer une clé API*.
. *Facultatives :* Entrez une description pour la clé API et sélectionnez une période d'expiration ou un champ d'application. Nous recommandons de définir une date d'expiration.
+
La clé API ne sera plus valide après l'expiration. Des périodes d'expiration plus courtes sont plus sécurisées.
+
La période d'expiration est limitée par `v3/settings/auth-token-max-ttl-minutes`. Si elle dépasse le max-ttl, la clé API est créée avec max-ttl comme période d'expiration.
+
Un champ d'application limite la clé API afin qu'elle ne fonctionne que contre l'API Kubernetes du cluster spécifié. Si le cluster est configuré avec un point de terminaison de cluster autorisé, vous pouvez utiliser un token limité directement contre l'API du cluster sans passer par le proxy du serveur Rancher. Voir {xref-arch-com-ds-cluster}#_4_authorized_cluster_endpoint[Points de terminaison de cluster autorisés] pour plus d'informations.

. Cliquez sur *Create*.
+
*Résultat de l'étape :* Votre clé API est créée. Votre API *Point de terminaison*, *Clé d'accès*, *Clé secrète* et *Jeton d'accès* sont affichés.
+
Utilisez le *Jeton d'accès* pour vous authentifier avec Rancher CLI.

. Copiez les informations affichées dans un endroit sécurisé. Ces informations ne sont affichées qu'une seule fois, donc si vous perdez votre clé, vous devrez en créer une nouvelle.

[#_whats_next]
== Et maintenant\...

* Entrez les informations de votre clé API dans l'application qui envoie des requêtes à l'API Rancher.
* En savoir plus sur les points de terminaison et les paramètres de Rancher en sélectionnant *Voir dans l'API* pour un objet dans l'interface utilisateur de Rancher.
* Les clés API sont utilisées pour les appels API et {xref-rancher-cli}[Rancher CLI].

[#_deleting_api_keys]
== Suppression des clés API

Si vous devez révoquer une clé API, supprimez-la. Vous devez supprimer les clés API{nbsp}:

* Celles-ci ont peut-être été compromises.
* Celles-ci ont expiré.

Pour supprimer une clé API, sélectionnez la clé obsolète et cliquez sur *Supprimer*.
