= Controladores de clúster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: xref:guías-de-instrucciones/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-controladores-de-provisión/gestionar-controladores-de-clúster.adoc 
:product-path: rancher-admin/global-configuration/provisioning-drivers/manage-cluster-drivers.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions.adoc 
:xref-hosted-k8s-clusters: xref:guías-de-instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configurar-clusters-a-partir-de-proveedores-kubernetes-alojados/index.adoc
endif::[]

Los controladores de clúster se utilizan para crear clústeres en un {xref-hosted-k8s-clusters}[proveedor de Kubernetes alojado], como Google GKE. La disponibilidad de qué controlador de clúster mostrar al crear clústeres está definida por el estado del controlador de clúster. Solo se mostrarán `active` controladores de clúster como opción para crear clústeres. Por defecto, Rancher se empaqueta con varios controladores de clúster de proveedores de nube existentes, pero también puedes añadir controladores de clúster personalizados a Rancher.

Si hay controladores de clúster específicos que no deseas mostrar a tus usuarios, puedes desactivar esos controladores de clúster dentro de Rancher y no aparecerán como opción para la creación de clústeres.

[#_managing_cluster_drivers]
== Gestión de controladores de clúster

[NOTE]
.Requisitos previos:
====

Para crear, editar o eliminar controladores de clúster, necesitas _uno_ de los siguientes permisos:

* {xref-global-permissions}[Permisos Globales de Administrador]
* {xref-global-permissions}#_custom_global_permissions[Permisos Globales Personalizados] con el rol {xref-global-permissions}[Gestionar Controladores de Clúster] asignado.
====


[#_activating_deactivating_cluster_drivers]
== Activar/Desactivar Controladores de Clúster

Por defecto, Rancher solo activa controladores para los proveedores de nube más populares, Google GKE, Amazon EKS y Azure AKS. Si deseas mostrar u ocultar algún controlador de nodo, puedes cambiar su estado.

. En la esquina superior izquierda, haz clic en *☰ > Gestión del Clúster*.
. En el menú de navegación de la izquierda, haz clic en *Controladores*.
. En la pestaña *Controladores de Clúster*, selecciona el controlador que deseas activar o desactivar y haz clic en *⋮ > Activar* o *⋮ > Desactivar*.

[#_adding_custom_cluster_drivers]
== Añadiendo controladores de clúster personalizados

Si deseas utilizar un controlador de clúster que Rancher no soporta de forma predeterminada, puedes añadir el controlador del proveedor para empezar a utilizarlo para crear clústeres de kubernetes _alojados_.

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En el menú de navegación de la izquierda, haz clic en *Controladores*.
. En la pestaña *Controladores de Clúster*, haz clic en *Añadir Controlador de Clúster*.
. Completa el formulario *Añadir Controlador de Clúster*. Luego haz clic en *Crear*.

[#_developing_your_own_cluster_driver]
== Desarrollando tu propio controlador de clúster

Para desarrollar un controlador de clúster para añadirlo a Rancher, consulta nuestro https://github.com/rancher-plugins/kontainer-engine-driver-example[ejemplo].
