= Acerca de los controladores de aprovisionamiento
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: xref:instrucciones/nuevos-usuarios/autenticación-permisos-y-configuración-global/acerca-de-controladores-de-aprovisionamiento/index.adoc 
:product-path: rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc
ifeval::["{build-type}" != "community"]
:xref-harvester-overview: xref:integrations/harvester/overview.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-infra-aws: xref:cluster-deployment/infra-providers/aws/aws.adoc
:xref-deploy-gke: xref:cluster-deployment/hosted-kubernetes/gke/gke.adoc
:xref-deploy-eks: xref:cluster-deployment/hosted-kubernetes/eks/eks.adoc
:xref-deploy-aks: xref:cluster-deployment/hosted-kubernetes/aks/aks.adoc
:xref-infra-gce: xref:cluster-deployment/infra-providers/gce/gce.adoc
:xref-infra-azure: xref:cluster-deployment/infra-providers/azure/azure.adoc
:xref-infra-digitalocean: xref:cluster-deployment/infra-providers/digitalocean/digitalocean.adoc
:xref-infra-vsphere: xref:cluster-deployment/infra-providers/vsphere/vsphere.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-harvester-overview: xref:integrations-in-rancher/harvester/overview.adoc
:xref-infra-providers: xref:guías-de-instrucciones/nuevas-guías-de-usuario/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/index.adoc
:xref-hosted-k8s-clusters: xref:guías-de-instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configurar-clusters-a-partir-de-proveedores-kubernetes-alojados/index.adoc
:xref-infra-aws: xref:instrucciones/nuevas-guías-de-usuario/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/crear-un-cluster-amazon-ec2.adoc
:xref-deploy-gke: xref:instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configuración-de-clusters-de-proveedores-de-kubernetes-alojados/gke.adoc
:xref-deploy-eks: xref:instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configuración-de-clusters-de-proveedores-de-kubernetes-alojados/eks.adoc
:xref-deploy-aks: xref:instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configuración-de-clusters-de-proveedores-de-kubernetes-alojados/aks.adoc
:xref-infra-gce: xref:instrucciones/nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/crear-un-clúster-de-google-compute-engine.adoc
:xref-infra-azure: xref:instrucciones/nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/crear-un-clúster-de-azure.adoc
:xref-infra-digitalocean: xref:instrucciones/nuevos-usuarios/guías-de-nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/crear-un-cluster-digitalocean.adoc
:xref-infra-vsphere: xref:instrucciones/nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/vsphere/index.adoc
endif::[]

Los controladores en Rancher te permiten gestionar qué proveedores pueden utilizarse para desplegar {xref-hosted-k8s-clusters}[clústeres de Kubernetes alojados] o {xref-infra-providers}[nodos en un proveedor de infraestructura] para permitir que Rancher despliegue y gestione Kubernetes.

[#_rancher_drivers]
== Controladores de Rancher

Con los controladores de Rancher, puedes habilitar o deshabilitar los controladores integrados que vienen en el paquete de Rancher. Alternativamente, puedes añadir tu propio controlador si Rancher aún no lo ha implementado.

Hay dos tipos de controladores dentro de Rancher:

* <<_cluster_drivers,Controladores de clúster>>
* <<_node_drivers,Controladores de nodo>>

[#_cluster_drivers]
== Controladores de clúster

Los controladores de clúster se utilizan para aprovisionar {xref-hosted-k8s-clusters}[clústeres de Kubernetes alojados], como GKE, EKS, AKS, etc. La disponibilidad de qué controlador de clúster mostrar al crear un clúster se define en función del estado del controlador de clúster. Solo se mostrarán `active` controladores de clúster como opción para la creación de clústeres de Kubernetes alojados. Por defecto, Rancher viene con varios controladores de clúster existentes en el paquete, pero también puedes crear controladores de clúster personalizados para añadir a Rancher.

Por defecto, Rancher ha activado varios proveedores de nube de Kubernetes alojados, incluyendo:

* {xref-deploy-eks}[Amazon EKS]
* {xref-deploy-gke}[Google GKE]
* {xref-deploy-aks}[Azure AKS]

[#_node_drivers]
== Controladores de nodo

Los controladores de nodo se utilizan para aprovisionar hosts, que Rancher utiliza para lanzar y gestionar clústeres de Kubernetes. Un controlador de nodo es lo mismo que un https://github.com/docker/docs/blob/vnext-engine/machine/drivers/index.md[controlador de Docker Machine]. La disponibilidad de qué controlador de nodo mostrar al crear plantillas de nodo se define en función del estado del controlador de nodo. Solo se mostrarán `active` controladores de nodo como opción para crear plantillas de nodo. Por defecto, Rancher viene empaquetado con muchos controladores de Docker Machine existentes, pero también puedes crear controladores de nodo personalizados para añadir a Rancher.

Si hay controladores de nodo específicos que no deseas mostrar a tus usuarios, necesitarías desactivar estos controladores de nodo.

Rancher soporta varios proveedores de nube importantes, pero por defecto, estos controladores de nodo están activos y disponibles para su ampliación:

* {xref-infra-aws}[Amazon EC2]
* {xref-infra-azure}[Azure]
* {xref-infra-digitalocean}[Digital Ocean]
* {xref-infra-vsphere}[vSphere]

Hay varios otros controladores de nodo que están desactivados por defecto, pero que vienen en el paquete de Rancher:

* {xref-harvester-overview}#_harvester_node_driver/[{harvester-product-name}], disponible a partir de Rancher v2.6.1
* {xref-infra-gce}[Google GCE], disponible a partir de Rancher v2.12.0
