= Configuración de la plantilla de nodo de DigitalOcean
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guías-de-referencia/configuración-de-cluster/configuración-de-cluster-sentido-descendente/configuración-de-plantilla-de-nodo/digitalocean.adoc 
:product-path: cluster-deployment/infra-providers/digitalocean/node-template-configuration.adoc

La información de acceso a la cuenta se almacena como una credencial en la nube. Las credenciales en la nube se almacenan como secretos de Kubernetes. Múltiples plantillas de nodo pueden utilizar la misma credencial en la nube. Puedes utilizar una credencial en la nube existente o crear una nueva.

[#_droplet_options]
== Opciones de Droplet

Las *Opciones de Droplet* proporcionan la región geográfica y las especificaciones de tu clúster.

[#_docker_daemon]
== Docker daemon

Si utilizas Docker, las opciones de configuración del https://docs.docker.com/engine/docker-overview/#the-docker-daemon[Docker daemon] incluyen:

* *Etiquetas:* Para información sobre etiquetas, consulta la https://docs.docker.com/config/labels-custom-metadata/[documentación de etiquetas de objetos de Docker.]
* *URL de instalación de Docker Engine:* Determina qué versión de Docker se instalará en la instancia.
* *Espejos de registro:* Espejo de registro de Docker que será utilizado por el Docker daemon
* *Otras opciones avanzadas:* Consulta la https://docs.docker.com/engine/reference/commandline/dockerd/[referencia de opciones del Docker daemon].
