= 安全
:page-languages: [en, zh]
:revdate: 2026-01-20
:page-revdate: {revdate}

[pass]
<table width="100%">
  <tr style="vertical-align: top;text-align: center;border-bottom-style: none;border-top-style: solid;border-top-width: 2px;border-top-color: #c0c2c4;">
    <td width="30%">
      <h4>Security policy</h4><br/>
      <p style={{padding: '8px'}}>Rancher Labs 会负责任地披露问题，并致力于在合理的时间内解决所有问题。</p>
    </td>
    <td width="30%">
      <h4>Reporting process</h4><br/>
      <p style={{padding: '8px'}}>请将安全问题发送至 <a href="mailto:security-rancher@suse.com">security-rancher@suse.com</a>。</p>
    </td>
    <td width="30%">
      <h4>Announcements</h4><br/>
      <p style={{padding:'8px'}}>订阅 <a href="https://forums.rancher.com/c/announcements">Rancher 公告论坛</a> 以获取版本更新。</p>
    </td>
  </tr>
</table>

安全是 Rancher 全部功能的基础。Rancher 集成了全部主流认证工具和服务，并提供了企业级的 xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc[RBAC 功能]，让你的 Kubernetes 集群更加安全。

本文介绍了安全相关的文档以及资源，让你的 Rancher 安装和下游 Kubernetes 集群更加安全。

== {neuvector-product-name} 与 Rancher 的集成

NeuVector 是一个开源的、以容器为中心的安全应用程序，现已集成到 Rancher 中。NeuVector 提供生产安全、DevOps 漏洞保护和容器防火墙等功能。请参阅 xref:integrations/neuvector/neuvector.adoc[Rancher 文档] 和 https://documentation.suse.com/cloudnative/security/{neuvector-docs-version}/en/overview.html[{neuvector-product-name} 文档]了解更多信息。

== 在 Kubernetes 集群上运行 Compliance 安全扫描

Rancher leverages https://github.com/aquasecurity/kube-bench[kube-bench] to run a security scan to check whether Kubernetes is deployed according to security best practices.

When Rancher runs a Compliance scan on a cluster, it generates a report showing the results of each test, including a summary with the number of passed, skipped and failed tests. The report also includes remediation steps for any failed tests.

有关详细信息，请参阅xref:security/compliance-scans/how-to.adoc[安全扫描]。

== SELinux RPM

We provide three RPMs (RPM Package Manager) that enable Rancher products to function properly on SELinux-enforcing hosts: `rancher-selinux`, `rke2-selinux` and `k3s-selinux`.  For details, see xref:security/selinux-rpm/selinux-rpm.adoc[this page].

== Rancher 加固指南

Rancher 加固指南基于 https://www.cisecurity.org/benchmark/kubernetes/[CIS Kubernetes Benchmark]。

加固指南为加固 Rancher 的生产安装提供了说明性指导。有关安全管控的完整列表，请参阅 Rancher 的 <<_cis_benchmark_和自我评估,CIS Kubernetes Benchmark 自我评估>>指南。

____
加固指南描述了如何保护集群中的节点，建议在安装 Kubernetes 之前参考加固指南中的步骤。
____

每个加固指南版本都针对特定的 CIS Kubernetes Benchmark、Kubernetes 和 Rancher 版本。

== CIS Benchmark 和自我评估

Benchmark 自我评估是 Rancher 安全加固指南的辅助。加固指南展示了如何加固集群，而 Benchmark 指南旨在帮助你评估加固集群的安全级别。

This guide walks through the various controls and provide updated example commands to audit compliance in Rancher created clusters. The original benchmark documents can be downloaded from the https://www.cisecurity.org/benchmark/kubernetes/[CIS website].

Rancher 自我评估指南的每个版本都对应于强化指南、Rancher、Kubernetes 和 CIS Benchmark 的特定版本。

== 第三方渗透测试报告

Rancher 会定期聘请第三方对 Rancher 软件栈进行安全审计和渗透测试。被测环境遵循 Rancher 在测试时提供的强化指南。以前的渗透测试报告如下。

结果：

* https://releases.rancher.com/documents/security/pen-tests/2019/RAN-01-cure53-report.final.pdf[Cure53 渗透测试 - 2019 年 7 月]
* https://releases.rancher.com/documents/security/pen-tests/2019/UntamedTheory-Rancher_SecurityAssessment-20190712_v5.pdf[Untamed Theory 渗透测试 - 2019 年 3 月]

请注意，新报告不再共享或公开发布。

== Rancher 安全公告和 CVE

Rancher 致力于向社区通报我们产品中的安全问题。有关我们已解决的问题的 CVE（常见漏洞和暴露）列表，请参阅xref:security/cves.adoc[此页]。

== Kubernetes 安全最佳实践

For recommendations on securing your Kubernetes cluster, refer to the https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/[Kubernetes Cluster Security Best Practices] guide.

== Rancher 安全最佳实践

有关保护 Rancher Manager 部署的建议，请参阅 xref:security/rancher-security-best-practices.adoc[Rancher 安全最佳实践]指南。

== Rancher Kubernetes Distributions (K3s/RKE2) Self-Assessment and Hardening Guides

Rancher uses the following Kubernetes distributions:

* https://documentation.suse.com/en-us/cloudnative/rke2/[*RKE2*] is a fully conformant Kubernetes distribution that focuses on security and compliance within the U.S. Federal Government sector.
* https://documentation.suse.com/en-us/cloudnative/k3s/[*K3s*] is a fully conformant, lightweight Kubernetes distribution. It is easy to install, with half the memory requirement of upstream Kubernetes, all in a binary of less than 100 MB.

To harden a Kubernetes cluster that's running a distribution other than those listed, refer to your Kubernetes provider's docs.

=== Hardening Guides and Benchmark Versions

Each self-assessment guide is accompanied by a hardening guide. These guides were tested alongside the listed Rancher releases. Each self-assessment guide was tested on a specific Kubernetes version and CIS benchmark version. If a CIS benchmark has not been validated for your Kubernetes version, you can use the existing guides until a guide for your version is added.

=== RKE2 Guides

|===
| Type | Kubernetes Version | CIS Benchmark Version | Self Assessment Guide | Hardening Guide

| Standalone RKE2
| Kubernetes v1.27
| CIS v1.9
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment19.html[Link]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Link]

| Standalone RKE2
| Kubernetes v1.28
| CIS v1.10
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment110.html[Link]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Link]

| Standalone RKE2
| Kubernetes v1.29 and above
| CIS v1.11
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment111.html[Link]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Link]
|===

=== K3s Guides

|===
| Type | Kubernetes Version | CIS Benchmark Version | Self Assessment Guide | Hardening Guide

| Standalone K3s
| Kubernetes v1.27
| CIS v1.9
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.9.html[Link]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Link]

| Standalone K3s
| Kubernetes v1.28
| CIS v1.10
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.10.html[Link]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Link]

| Standalone K3s
| Kubernetes v1.29 and above
| CIS v1.11
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.11.html[Link]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Link]
|===
