site:
  title: SUSE® Rancher Multi Cluster Manager
  url: /
  start_page: latest@rancher-mcm:en:about-rancher/what-is-rancher.adoc
  robots: disallow
content:
  sources: 
  - url: .
    branches: HEAD
    start_paths: [shared, versions/latest]
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher
asciidoc:
  attributes:
    build-type: 'mcm'
    rancher-prime: Cloud Native
    rancher-product-name: "SUSE Rancher Multi Cluster Manager"
    rancher-product-name-tm: "SUSE® Rancher Multi Cluster Manager"
    rancher-short-name: "Rancher"
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en]
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml
    enabled: true
  - require: ./extensions/unpublish-unlisted-pages-extension.js
