= Namespaces
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-namespaces.adoc 
:product-path: cluster-admin/namespaces.adoc
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/manage-persistent-storage.adoc
:xref-configmaps: xref:cluster-admin/kubernetes-resources/configmaps.adoc
:xref-workloads-and-pods: xref:cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:xref-project-resource-quotas: xref:cluster-admin/project-admin/project-resource-quotas/project-resource-quotas.adoc
:xref-http-encrypt: xref:security/encrypting-http.adoc
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
:xref-k8s-docker-registries: xref:cluster-admin/kubernetes-resources/kubernetes-and-docker-registries.adoc
:xref-create-services: xref:cluster-admin/kubernetes-resources/create-services.adoc
:xref-lb-and-ingress-controller: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/load-balancer-and-ingress-controller.adoc
:xref-namespace-default-limit: xref:cluster-admin/project-admin/project-resource-quotas/override-default-limit-in-namespaces.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-persistent-storage: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/index.adoc
:xref-configmaps: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc
:xref-workloads-and-pods: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc
:xref-project-resource-quotas: xref:how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/index.adoc
:xref-http-encrypt: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
:xref-k8s-docker-registries: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries.adoc
:xref-create-services: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/create-services.adoc
:xref-lb-and-ingress-controller: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/index.adoc
:xref-namespace-default-limit: xref:how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/override-default-limit-in-namespaces.adoc
endif::[]

Innerhalb von Rancher können Sie Projekte weiter in verschiedene https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/[Namespaces] unterteilen, die virtuelle Cluster innerhalb eines Projekts sind, das von einem physischen Cluster unterstützt wird. Sollten Sie eine weitere Organisationsebene über Projekte und den `default` Namespace hinaus benötigen, können Sie mehrere Namespaces verwenden, um Anwendungen und Ressourcen zu isolieren.

Obwohl Sie Ressourcen auf Projektebene zuweisen, sodass jeder Namespace im Projekt diese nutzen kann, können Sie diese Vererbung überschreiben, indem Sie Ressourcen explizit einem Namespace zuweisen.

Ressourcen, die Sie direkt an Namespaces zuweisen können, umfassen:

* {xref-workloads-and-pods}[Workloads]
* {xref-lb-and-ingress-controller}[Lastenausgleicher/Ingress]
* {xref-create-services}[Service Discovery Records]
* {xref-persistent-storage}[Persistente Volume Claims]
* {xref-http-encrypt}[Zertifikate]
* {xref-configmaps}[ConfigMaps]
* {xref-k8s-docker-registries}[Registries]
* {xref-secrets}[Secrets]

Um Berechtigungen in einem Standard-Kubernetes-Cluster zu verwalten, konfigurieren Cluster-Administratoren rollenbasierte Zugriffskontrolle für jeden Namespace. Mit Rancher werden die Benutzerberechtigungen stattdessen auf Projektebene zugewiesen, und die Berechtigungen werden automatisch von jedem Namespace geerbt, der zu dem jeweiligen Projekt gehört.

[NOTE]
====

Wenn Sie einen Namespace mit `kubectl` erstellen, kann er unbrauchbar sein, da `kubectl` nicht erfordert, dass Ihr neuer Namespace innerhalb eines Projekts, auf das Sie Zugriff haben, eingegrenzt ist. Wenn Ihre Berechtigungen auf Projektebene beschränkt sind, ist es besser, <<_creating_namespaces,einen Namespace über Rancher zu erstellen>>, um sicherzustellen, dass Sie die Berechtigung haben, auf den Namespace zuzugreifen.
====


[#_creating_namespaces]
== Namespaces erstellen

Erstellen Sie einen neuen Namespace, um Apps und Ressourcen in einem Projekt zu isolieren.

[TIP]
====

Wenn Sie mit Projektressourcen arbeiten, die Sie einem Namespace zuweisen können (d.h. {xref-deploy-workloads}[Workloads], {xref-http-encrypt}[Zertifikate], {xref-configmaps}[ConfigMaps] usw.), können Sie einen Namespace im Handumdrehen erstellen.
====


. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Clusters* zu dem Cluster, in dem Sie einen Namespace erstellen möchten, und klicken Sie auf *Erforschen*.
. Klicken Sie auf menu:Cluster[Projekte/Namespaces].
. Gehen Sie zu dem Projekt, in dem Sie einen Namespace hinzufügen möchten, und klicken Sie auf *Namespace erstellen*. Alternativ gehen Sie zu *Nicht in einem Projekt*, um einen Namespace zu erstellen, der nicht mit einem Projekt verbunden ist.
. *Optional:* Wenn Ihr Projekt {xref-project-resource-quotas}[Ressourcenkontingente] hat, die in Kraft sind, können Sie die standardmäßigen Ressourcen *Limits* überschreiben (die eine Obergrenze für die Ressourcen festlegt, die der Namespace verbrauchen kann).
. Geben Sie einen *Namen* ein und klicken Sie dann auf *Erstellen*.

*Ergebnis:* Ihr Namespace wird dem Projekt hinzugefügt. Sie können beginnen, Clusterressourcen dem Namespace zuzuweisen.

[#_moving_namespaces_to_another_project]
== Namespaces in ein anderes Projekt verschieben

Cluster-Administratoren und Mitglieder müssen gelegentlich einen Namespace in ein anderes Projekt verschieben, beispielsweise wenn Sie möchten, dass ein anderes Team die Anwendung zu nutzen beginnt.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Clusters* zu dem Cluster, in dem Sie einen Namespace verschieben möchten, und klicken Sie auf *Erforschen*.
. Klicken Sie auf menu:Cluster[Projekte/Namespaces].
. Gehen Sie zu dem Namespace, den Sie verschieben möchten, und klicken Sie auf *⋮ > Verschieben*.
. Wählen Sie die Namespace(s) aus, die Sie in ein anderes Projekt verschieben möchten. Klicken Sie dann auf *Verschieben*. Sie können mehrere Namespaces auf einmal verschieben.
+
[NOTE]
.Hinweise:
====
* Verschieben Sie die Namespaces nicht im `System` Projekt. Das Verschieben dieser Namespaces kann sich nachteilig auf das Cluster-Netzwerk auswirken.
* Sie können einen Namespace nicht in ein Projekt verschieben, das bereits ein {xref-project-resource-quotas}[Ressourcenkontingent] konfiguriert hat.
* Wenn Sie einen Namespace von einem Projekt mit einer festgelegten Quote in ein Projekt ohne festgelegtes Ressourcenkontingent verschieben, wird das Ressourcenkontingent vom Namespace entfernt.
====

. Wählen Sie ein neues Projekt für den neuen Namespace aus und klicken Sie dann auf *Verschieben*. Alternativ können Sie den Namespace aus allen Projekten entfernen, indem Sie *Keine* auswählen.

*Ergebnis:* Ihr Namespace wird in ein anderes Projekt verschoben (oder von allen Projekten getrennt). Wenn Ressourcen eines Projekts an den Namespace angehängt sind, gibt der Namespace diese frei und hängt dann Ressourcen aus dem neuen Projekt an.

[#_editing_namespace_resource_quotas]
== Bearbeiten der Ressourcenquoten für Namespaces

Sie können immer das Standardlimit des Namespaces überschreiben, um einem bestimmten Namespace den Zugriff auf mehr (oder weniger) Projektressourcen zu ermöglichen.

Weitere Informationen finden Sie in der Anleitung zum {xref-namespace-default-limit}[Bearbeiten von Namespace-Ressourcenquoten].
