= Cluster Autoscaler
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}

Dans cette section, vous apprendrez comment installer et utiliser le https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/[cluster-autoscaler Kubernetes] sur des clusters personnalisés Rancher en utilisant les groupes de mise à l'échelle automatique AWS EC2.

Le Cluster Autoscaler est un outil qui ajuste automatiquement la taille du cluster Kubernetes lorsque l'une des conditions suivantes est remplie{nbsp}:

* Il y a des pods qui n'ont pas pu s'exécuter dans le cluster en raison de ressources insuffisantes.
* Il y a des nœuds dans le cluster qui ont été sous-utilisés pendant une période prolongée et leurs pods peuvent être placés sur d'autres nœuds existants.

Pour empêcher votre pod d'être évincé, définissez une propriété `priorityClassName: system-cluster-critical` dans la spécification de votre pod.

Cluster Autoscaler est conçu pour fonctionner sur les nœuds maîtres Kubernetes. Il peut fonctionner dans l'espace de noms `kube-system`. Cluster Autoscaler ne réduit pas la taille des nœuds sur lesquels s'exécutent des pods `kube-system` non mis en miroir.

Il est possible d'exécuter un déploiement personnalisé de Cluster Autoscaler sur des nœuds de travail, mais une attention particulière doit être portée pour s'assurer que Cluster Autoscaler reste opérationnel.

[#_cloud_providers]
== Fournisseurs de cloud

Cluster Autoscaler fournit un support pour différents fournisseurs de cloud. Pour plus d'informations, rendez-vous sur https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#deployment[les fournisseurs de cloud pris en charge par Cluster Autoscaler.]

[#_setting_up_cluster_autoscaler_on_amazon_cloud_provider]
=== Configuration de Cluster Autoscaler sur le fournisseur de cloud Amazon

Pour des détails sur l'exécution de Cluster Autoscaler sur le fournisseur de cloud Amazon, consultez xref:cluster-admin/manage-clusters/install-cluster-autoscaler/use-aws-ec2-auto-scaling-groups.adoc[cette page.]
