= Options de configuration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/configuration-options/index.adoc 
:product-path: observability/istio/configuration/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
:xref-istio-on-rke2: xref:observability/istio/configuration/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:observability/istio/configuration/project-network-isolation.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
:xref-istio-on-rke2: xref:integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:integrations-in-rancher/istio/configuration-options/project-network-isolation.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] a cessé la prise en charge depuis Rancher v2.12.0{nbsp}; tournez-vous vers l'https://apps.rancher.io[SUSE Application Collection] d'Istio pour une sécurité renforcée (incluse dans les abonnements SUSE Rancher Prime).
Des informations détaillées peuvent être trouvées dans https://forums.suse.com/t/deprecation-of-rancher-istio/45043[cette annonce].
====

[#_egress_support]
== Support Egress

Par défaut, la passerelle Egress est désactivée, mais peut être activée lors de l'installation ou de la mise à niveau via le <<_overlay_file,fichier overlay>>.

[#_enabling_automatic_sidecar_injection]
== Activation de l'injection automatique de sidecar

L'injection automatique de sidecar est désactivée par défaut. Pour activer cela, définissez le `sidecarInjectorWebhook.enableNamespacesByDefault=true` dans le values.yaml lors de l'installation ou de la mise à niveau. Cela active automatiquement l'injection de sidecar Istio dans tous les nouveaux espaces de noms qui sont déployés.

[#_overlay_file]
== Fichier overlay

Un fichier overlay est conçu pour prendre en charge une configuration étendue de votre installation Istio. Il vous permet d'apporter des modifications à toutes les valeurs disponibles dans le https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/[IstioOperator API]. Cela garantira que vous pouvez personnaliser l'installation par défaut pour s'adapter à n'importe quel scénario.

Le fichier overlay ajoutera une configuration par-dessus l'installation par défaut fournie par l'installation du chart Istio. Cela signifie que vous n'avez pas besoin de redéfinir les composants qui sont déjà définis pour l'installation.

Pour plus d'informations sur les fichiers overlay, reportez-vous à la https://istio.io/latest/docs/setup/install/istioctl/#configure-component-settings[Istio documentation]

[#_selectors_and_scrape_configs]
== Sélecteurs et configurations de scraping

L'appli de surveillance définit `prometheus.prometheusSpec.ignoreNamespaceSelectors=false`, ce qui permet la surveillance de tous les espaces de noms par défaut. Cela garantit que vous pouvez voir le trafic, les métriques et les graphiques pour les ressources déployées dans un espace de noms avec l'étiquette `istio-injection=enabled`.

Si vous souhaitez limiter Prometheus à des espaces de noms spécifiques, définissez `prometheus.prometheusSpec.ignoreNamespaceSelectors=true`. Une fois que vous avez fait cela, vous devez effectuer une configuration supplémentaire pour continuer à surveiller vos ressources.

Pour plus de détails, reportez-vous à {xref-selectors-and-scrape-configurations}[cette section.]

[#_additional_steps_for_installing_istio_on_an_rke2_product_name_cluster]
== Étapes supplémentaires pour installer Istio sur un cluster {rke2-product-name}.

Reportez-vous à {xref-istio-on-rke2}[cette section.]

[#_additional_steps_for_project_network_isolation]
== Étapes supplémentaires pour l'isolement du réseau de projet

Reportez-vous à {xref-istio-project-network-isolation}[cette section.]
