= DigitalOcean Maschinenkonfiguration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-10
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/digitalocean.adoc 
:product-path: cluster-deployment/infra-providers/digitalocean/machine-configuration.adoc

Für weitere Informationen über DigitalOcean, Droplets, siehe die https://docs.digitalocean.com/products/compute/[offizielle Dokumentation].

[#_region]
== Region

Konfigurieren Sie die https://docs.digitalocean.com/glossary/region/[Region], in der Droplets erstellt werden.

[#_size]
== Größe

Konfigurieren Sie die https://docs.digitalocean.com/products/droplets/resources/choose-plan/[Größe] der Droplets.

[#_os_image]
== Betriebssystem-Image

Konfigurieren Sie das Betriebssystem https://docs.digitalocean.com/products/images/[Image], von dem die Droplets erstellt werden.

[#_monitoring]
== Überwachung

Aktivieren Sie den DigitalOcean-Agenten für zusätzliche https://docs.digitalocean.com/products/monitoring/[Überwachung].

[#_ipv6]
== IPv6

Aktivieren Sie IPv6 für Droplets.

Für weitere Informationen, siehe die https://docs.digitalocean.com/products/networking/ipv6[DigitalOcean IPv6-Dokumentation].

[#_private_networking]
== Privates Netzwerk

Aktivieren Sie privates Netzwerk für Droplets.

[#_droplet_tags]
== Droplet-Tags

Wenden Sie ein Tag (Label) auf ein Droplet an. Tags dürfen nur Buchstaben, Zahlen, Doppelpunkte, Bindestriche und Unterstriche enthalten. Beispiel: `my_server`. 
