= DigitalOcean Node-Vorlagenkonfiguration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/digitalocean.adoc 
:product-path: cluster-deployment/infra-providers/digitalocean/node-template-configuration.adoc

Die Kontozugangsinformationen werden als Cloud-Anmeldeinformationen gespeichert. Cloud-Anmeldeinformationen werden als Kubernetes-Geheimnisse gespeichert. Mehrere Node-Vorlagen können dieselben Cloud-Anmeldeinformationen verwenden. Sie können vorhandene Cloud-Anmeldeinformationen verwenden oder neue erstellen.

[#_droplet_options]
== Droplet-Optionen

Die *Droplet-Optionen* legen die geografische Region und die Spezifikationen Ihres Clusters fest.

[#_docker_daemon]
== Docker-Daemon

Wenn Sie Docker verwenden, umfassen die https://docs.docker.com/engine/docker-overview/#the-docker-daemon[Docker-Daemon] Konfigurationsoptionen:

* *Labels:* Für Informationen zu Labels siehe die https://docs.docker.com/config/labels-custom-metadata/[Dokumentation zu Docker-Objekt-Labels.]
* *Docker Engine Installations-URL:* Bestimmt, welche Docker-Version auf der Instanz installiert wird.
* *Registry-Spiegel:* Docker-Registry-Spiegel, der vom Docker-Daemon verwendet werden soll
* *Weitere erweiterte Optionen:* Siehe die https://docs.docker.com/engine/reference/commandline/dockerd/[Referenz zu Docker-Daemon-Optionen].
