= Configurar o GitHub
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/guias-para-novos-usuários/autenticação-permissões-e-configuração-global/configuração-de-autenticação/configurar-github.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-github.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:procedimentos/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/configuração-de-autenticação/index.adoc
endif::[]

Em ambientes que utilizam o GitHub, você pode configurar o Rancher para permitir o login usando credenciais do GitHub.

[NOTE]
.Pré-requisitos:
====

Leia {xref-authn-authz}#_configuração_de_autenticação_externa_e_usuários_principais[Configuração de Autenticação Externa e Usuários Principais].
====


. Faça login no Rancher usando um usuário local atribuído ao papel `administrator` (ou seja, o _principal local_).
. No canto superior esquerdo, clique em *☰ > Usuários e Autenticação*.
. No menu de navegação à esquerda, clique em *Provedor de Autenticação*.
. Clique em *GitHub*.
. Siga as instruções exibidas para configurar um Aplicativo do GitHub. O Rancher redireciona você para o GitHub para completar o registro.
+

[NOTE]
.O que é uma URL de Retorno de Autorização?
====
A URL de Retorno de Autorização é a URL onde os usuários vão para começar a usar seu aplicativo (ou seja, a tela de boas-vindas).

Quando você usa autenticação externa, a autenticação não ocorre realmente em seu aplicativo. Em vez disso, a autenticação ocorre externamente (neste caso, no GitHub). Após a conclusão bem-sucedida dessa autenticação externa, a URL de Retorno de Autorização é o local onde o usuário reentra em seu aplicativo.
====


. Do GitHub, copie o *ID do Cliente* e o *Segredo do Cliente*. Cole-os no Rancher.
+

[NOTE]
.Onde encontro o ID do Cliente e o Segredo do Cliente?
====
No GitHub, selecione Configurações > Configurações de Desenvolvedor > Aplicativos OAuth. O ID do Cliente e o Segredo do Cliente são exibidos de forma proeminente.
====


. Clique em *Autenticar com o GitHub*.
. Use as opções de *Acesso ao Site* para configurar o escopo da autorização do usuário.
 ** *Permitir qualquer usuário válido*
+
_Qualquer_ usuário do GitHub pode acessar o Rancher. Geralmente, desencorajamos o uso dessa configuração!

 ** *Permitir membros de Clusters, Projetos, além de Usuários e Organizações Autorizados*
+
Qualquer usuário ou grupo do GitHub adicionado como *Membro do Cluster* ou *Membro do Projeto* pode fazer login no Rancher. Além disso, qualquer usuário ou grupo do GitHub que você adicionar à lista de *Usuários e Organizações Autorizados* pode fazer login no Rancher.

 ** *Restringir o acesso apenas a Usuários e Organizações Autorizados*
+
Apenas usuários ou grupos do GitHub adicionados aos Usuários e Organizações Autorizados podem fazer login no Rancher.
 +
. Clique em *Habilitar*.

*Resultado:*

* A autenticação do GitHub está configurada.
* Você está conectado ao Rancher com sua conta do GitHub (ou seja, o _principal externo_).
