= Usuários e grupos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-09-18
:page-revdate: {revdate}
:community-path: xref:procedimentos/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/configuração-de-autenticação/gerenciar-usuários-e-grupos.adoc 
:product-path: rancher-admin/users/authn-and-authz/manage-users-and-groups.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rbac: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc
:xref-local-users: xref:rancher-admin/users/authn-and-authz/create-local-users.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rbac: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/index.adoc
:xref-local-users: xref:procedimentos/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/configuração-de-autenticação/criar-usuários-locais.adoc
endif::[]

O Rancher depende de usuários e grupos para determinar quem tem permissão para fazer login no Rancher e quais recursos podem acessar. Quando você configura um provedor de autenticação externo, os usuários desse provedor poderão fazer login no seu servidor Rancher. Quando um usuário faz login, o provedor de autenticação fornecerá ao seu servidor Rancher uma lista de grupos aos quais o usuário pertence.

O acesso a clusters, projetos e provedores e entradas de DNS globais pode ser controlado adicionando usuários individuais ou grupos a esses recursos. Quando você adiciona um grupo a um recurso, todos os usuários que são membros desse grupo no provedor de autenticação poderão acessar o recurso com as permissões que você especificou para o grupo. Para mais informações sobre funções e permissões, consulte {xref-manage-rbac}[Controle de acesso com base em função].

[#_managing_members]
== Gerenciando Membros

Ao adicionar um usuário ou grupo a um recurso, você pode pesquisar usuários ou grupos começando a digitar o nome deles. O servidor Rancher consultará o provedor de autenticação para encontrar usuários e grupos que correspondam ao que você digitou. A pesquisa é limitada ao provedor de autenticação com o qual você está atualmente logado. Por exemplo, se você ativou a autenticação do GitHub, mas está logado usando uma conta de usuário {xref-local-users}[local], não poderá pesquisar usuários ou grupos do GitHub.

Todos os usuários, sejam eles locais ou de um provedor de autenticação, podem ser visualizados e gerenciados. No canto superior esquerdo, clique em *☰ > Usuários e Autenticação*. Na barra de navegação à esquerda, clique em *Usuários*.

[NOTE]
.Advertências do Provedor SAML
====
* Usuários e grupos não são validados quando você atribui permissões a eles no Rancher.
* Ao adicionar usuários, os IDs exatos dos usuários (ou seja, `UID Field`) devem ser inseridos corretamente. Enquanto você digita o ID do usuário, não haverá busca por outros IDs de usuários que possam corresponder.
* Ao adicionar grupos, você deve selecionar o grupo no menu suspenso ao lado da caixa de texto. O Rancher assume que qualquer entrada da caixa de texto é um usuário.
* O menu suspenso de grupos mostra apenas os grupos dos quais você é membro. No entanto, se você tiver permissões de Administrador ou permissões de Administrador restritas, poderá ingressar em um grupo do qual não é membro.
====

[#_user_information]
== Informações do Usuário

O Rancher mantém informações sobre cada usuário que faz login através de um provedor de autenticação. Essas informações incluem se o usuário tem permissão para acessar seu servidor Rancher e a lista de grupos aos quais o usuário pertence. O Rancher mantém essas informações do usuário para que o CLI, API e kubectl possam refletir com precisão o acesso que o usuário tem com base na associação ao grupo no provedor de autenticação.

Sempre que um usuário faz login na interface usando um provedor de autenticação, o Rancher atualiza automaticamente as informações desse usuário.

[#_automatically_refreshing_user_information]
=== Atualizando Automaticamente as Informações do Usuário

O Rancher irá periodicamente atualizar as informações do usuário mesmo antes que um usuário faça login pela interface. Você pode controlar com que frequência o Rancher realiza essa atualização.

Duas configurações controlam esse comportamento:

* *`auth-user-info-max-age-seconds`*
+
Essa configuração controla quão antigas as informações de um usuário podem ser antes que o Rancher as atualize. Se um usuário fizer uma chamada de API (diretamente ou usando o Rancher CLI ou kubectl) e o tempo desde a última atualização do usuário for maior do que essa configuração, então o Rancher irá acionar uma atualização. Essa configuração tem como padrão `3600` segundos, ou seja, 1 hora.

* *`auth-user-info-resync-cron`*
+
Essa configuração controla um cron recorrente para re-sincronizar as informações do provedor de autenticação para todos os usuários. Independentemente de um usuário ter feito login ou usado a API recentemente, isso fará com que o usuário seja atualizado no intervalo especificado. Essa configuração tem como padrão `0 0 * * *`, ou seja, uma vez por dia à meia-noite. Veja a https://en.wikipedia.org/wiki/Cron[documentação do cron] para mais informações sobre valores válidos para essa configuração.

Para alterar essas configurações,

. No canto superior esquerdo, clique em *☰ > Configurações Globais*.
. Vá para a configuração que você deseja ajustar e clique em *⋮ > Editar Configuração*.

[NOTE]
====

Como o SAML não suporta busca de usuários, provedores de autenticação baseados em SAML não suportam a atualização periódica das informações do usuário. As informações do usuário só serão atualizadas quando o usuário fizer login na interface do Rancher.
====


[#_manually_refreshing_user_information]
=== Atualizando Manualmente as Informações do Usuário

Se você não tem certeza de quando foi a última vez que o Rancher realizou uma atualização automática das informações do usuário, você pode realizar uma atualização manual de todos os usuários.

. No canto superior esquerdo, clique em *☰ > Usuários e Autenticação*.
. Na página *Usuários*, clique em *Atualizar Membros do Grupo*.

*Resultados:* O Rancher atualiza as informações do usuário para todos os usuários. Solicitar essa atualização irá atualizar quais usuários podem acessar o Rancher, bem como todos os grupos aos quais cada usuário pertence.

[NOTE]
====

Como o SAML não suporta a busca de usuários, os provedores de autenticação baseados em SAML não oferecem a capacidade de atualizar manualmente as informações do usuário. As informações do usuário só serão atualizadas quando o usuário fizer login na interface do Rancher.
====


[#_minimum_password_length]
== Tamanho Mínimo da Senha

Por padrão, as senhas dos usuários devem ter pelo menos 12 caracteres de comprimento. No entanto, você pode personalizar o requisito de comprimento da senha:

. No canto superior esquerdo, clique em *☰ > Configurações Globais*.
. Vá para *`password-min-length`* e clique em *⋮ > Editar Configuração*.
. Insira um valor inteiro entre 2 e 256 e clique em *Salvar*.

[#_session_length]
== Duração da Sessão

O comprimento padrão (TTL) de cada sessão de usuário é ajustável. O comprimento padrão da sessão é de 16 horas.

. No canto superior esquerdo, clique em *☰ > Configurações Globais*.
. Vá para *`auth-user-session-ttl-minutes`* e clique em *⋮ > Editar Configuração*.
. Insira a quantidade de tempo, em minutos, que a sessão deverá durar e clique em *Salvar*.

*Resultado:* Os usuários são automaticamente desconectados do Rancher após o número definido de minutos.
