= VMware vSphereにおけるKubernetesクラスターのプロビジョニング
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/provision-kubernetes-clusters-in-vsphere.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/provision-kubernetes-clusters-in-vsphere.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-vsphere-node-template-config: xref:cluster-deployment/infra-providers/vsphere/node-template-configuration.adoc
:xref-vsphere-create-credentials: xref:cluster-deployment/infra-providers/vsphere/create-credentials.adoc
:xref-persistent-storage-examples: xref:cluster-admin/manage-clusters/persistent-storage/examples/examples.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/rancher管理クラスターのノード要件.adoc
:xref-rke2-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/index.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-k3s-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc
:xref-vsphere-node-template-config: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/vsphere.adoc
:xref-vsphere-create-credentials: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/create-credentials.adoc
:xref-persistent-storage-examples: xref:how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/index.adoc
endif::[]

このセクションでは、Rancherを使用してVMware vSphereに{url-rke2-landing-page}[RKE2]または{url-k3s-landing-page}[K3s] Kubernetesクラスターをデプロイする方法を学びます。

まず、RancherにvSphereクラウド認証情報を設定します。

次に、RancherでvSphereクラスターを作成し、新しいクラスターを構成する際に、マシンプールを定義します。各マシンプールには、etcd、controlplane、または worker の Kubernetes ロールがあります。Rancher は新しいノードに Kubernetes をインストールし、マシンプールによって定義された Kubernetes ロールで各ノードを設定します。

* <<_preparation_in_vmware_vsphere,vSphereの準備>>
* <<_creating_a_vmware_vsphere_cluster,vSphereクラスターの作成>>

[#_preparation_in_vmware_vsphere]
== VMware vSphereの準備

このセクションでは、RancherがVMおよびクラスターをプロビジョニングできるようにするためのvSphereの設定要件について説明します。

[#_create_credentials_in_vmware_vsphere]
=== VMware vSphereでの認証情報の作成

クラスターを作成する前に、十分な権限を持つvSphereユーザーが必要です。

必要な権限を持つユーザーをvSphereで作成する方法については、この{xref-vsphere-create-credentials}[ハウツーガイド]を参照してください。これらの手順により、Rancherに提供する必要があるユーザー名とパスワードが生成され、RancherがvSphereでリソースをプロビジョニングできるようになります。

[#_network_permissions]
=== ネットワークの権限

Rancherサーバーを実行しているホストが、以下のネットワーク接続を確立できることを確認する必要があります：

* vCenterサーバーのvSphere APIへの接続（通常はポート443/TCP）。
* クラスターのために仮想マシンをインスタンス化するために使用されるすべてのESXiホストのホストAPI（ポート443/TCP）への接続（_ISO作成方法を使用する場合のみ必要_）。
* 作成されたVMのポート22/TCPおよび2376/TCPへの接続

ノードのインフラストラクチャプロバイダーを作成するために適用されるポート要件の詳細なリストについては、{xref-node-reqs}#_networking_requirements[ノードネットワーキング要件]を参照してください。

[#_valid_esxi_license_for_vmware_vsphere_api_access]
=== VMware vSphere APIアクセスのための有効なESXiライセンス

無料のESXiライセンスはAPIアクセスをサポートしていません。vSphereサーバーには、有効なまたは評価用のESXiライセンスが必要です。

[#_vm_vm_affinity_rules_for_clusters_with_drs]
=== DRSを使用したクラスターのVM-VMアフィニティルール

DRSが有効なクラスターがある場合、 https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-7297C302-378F-4AF2-9BD6-6EDB1E0A850A.html[VM-VMアフィニティルール]の設定をお勧めします。これらのルールにより、etcdおよびコントロールプレーンの役割が割り当てられたVMは、異なるノードプールに割り当てられた場合、別々のESXiホストで動作することができます。この手法により、単一の物理マシンの障害がそれらのプレーンの可用性に影響を与えないことが保証されます。

[#_creating_a_vmware_vsphere_cluster]
== VMware vSphereクラスターを作成する

[#_1_create_your_cloud_credentials]
=== 1.クラウド資格情報を作成する

. *☰ > クラスター管理* をクリックします。
. *クラウド資格情報* をクリックします。
. ［*作成*］をクリックします。
. *VMware vSphere*をクリックしてください。
. vSphereの認証情報を入力してください。ヘルプが必要な場合は、*アカウントアクセス*を{xref-vsphere-node-template-config}[ノードテンプレート設定リファレンス]で参照してください。
. ［*作成*］をクリックします。

**結果:**クラスター内のノードをプロビジョニングするために使用されるクラウド認証情報を作成しました。

[#_2_create_your_cluster]
=== 2.クラスターを作成する

Rancherを使用してvSphereにKubernetesクラスターを作成します。

. 左上隅で、*☰ > クラスター管理*をクリックします。
. *クラスター*ページで、*作成*をクリックします。
. *VMware vSphere*をクリックしてください。
. *クラスター名*を入力し、vSphereクラウドの認証情報を使用してください。
. 各Kubernetesロールごとにマシンプールを作成してください。役割の割り当てと数に関する推奨事項については、{xref-infra-providers}#_node_roles[ベストプラクティス]を参照してください。
.. 各マシンプールごとに、マシンの構成を定義してください。
. インストールするKubernetesのバージョン、使用するネットワークプロバイダー、およびプロジェクトネットワークの分離を有効にするかどうかを選択するには、*クラスター構成*を使用してください。 クラスターの構成に関するヘルプについては、{xref-rke2-config}[RKE2]および{xref-k3s-config}[K3s]クラスター構成リファレンスを参照してください。
. クラスターのユーザー認可を構成するには、*メンバー役割*を使用してください。*メンバーを追加*をクリックして、クラスターにアクセスできるユーザーを追加してください。各ユーザーの権限を設定するには、*役割*のドロップダウンを使用してください。
. 後で永続ストレージやその他のインフラストラクチャを動的にプロビジョニングしたい場合は、クラスターYAMLファイルを修正してvSphereクラウドプロバイダーを有効にする必要があります。詳細については、{xref-cloud-provider-vsphere}[インツリーvSphereクラウドプロバイダーのドキュメント]および{xref-cloud-provider-vsphere-out-of-tree}[アウトオブツリーvSphereクラウドプロバイダーのドキュメント]を参照してください。
. オプションを確認して、正しいことを確認してください。続いて*作成*をクリックします。

*結果:*

クラスターが作成され、状態が*プロビジョニング*に割り当てられました。Rancherがクラスターを立ち上げています。

状態が*アクティブ*に更新された後、クラスターにアクセスできます。

*アクティブ*なクラスターには、2つのプロジェクトが割り当てられています：

* `Default`、`default`名前空間を含む
* `System`、`cattle-system`、`traefik`、`kube-public`、および`kube-system`名前空間を含む

[#_optional_next_steps]
== オプションの次のステップ

クラスターを作成した後、Rancher UIを通じてアクセスできます。ベストプラクティスとして、クラスターにアクセスするためのこれらの代替方法を設定することをお勧めします：

* *kubectl CLIを使用してクラスターにアクセスする:*{xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[これらの手順]に従って、ワークステーションでkubectlを使用してクラスターにアクセスしてください。この場合、Rancherサーバーの認証プロキシを通じて認証され、その後Rancherがダウンストリームクラスターに接続します。この方法を使用すると、Rancher UIなしでクラスターを管理できます。
* *認可されたクラスターエンドポイントを使用して、kubectl CLIでクラスターにアクセスします:*{xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[これらの手順]に従って、Rancherを介さずにkubectlでクラスターに直接アクセスします。Rancherに接続できない場合でもクラスターにアクセスできるように、この代替方法を設定することをお勧めします。
* *ストレージのプロビジョニング:*Rancherを使用してvSphereでストレージをプロビジョニングする方法の例については、{xref-persistent-storage-examples}[このセクション]を参照してください。vSphereでストレージを動的にプロビジョニングするには、vSphereプロバイダーを有効にする必要があります。詳細については、{xref-cloud-provider-vsphere}[インツリーvSphereクラウドプロバイダーのドキュメント]および{xref-cloud-provider-vsphere-out-of-tree}[アウトオブツリーvSphereクラウドプロバイダーのドキュメント]を参照してください。
