= VMware vSphere 仮想マシンのグレースフルシャットダウン
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/shutdown-vm.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/shutdown-vm.adoc
:experimental:

Rancher v2.8.3以降では、VMware vSphereノードドライバークラスターの仮想マシン（VM）のグレースフルシャットダウンを構成できます。グレースフルシャットダウンは、VMが強制的に削除される前に遅延を導入し、実行中のプロセスやオープン接続を終了する時間を確保します。

RKE2/K3sでは、クラスターを作成する際にグレースフルシャットダウンを設定するか、後でクラスター設定を編集して追加できます。

[NOTE]
====
Rancherはインポートされたクラスターのプラットフォームを検出できないため、インポートしたVMware vSphereクラスターでグレースフルシャットダウンを有効にすることはできません。
====


[#_enable_graceful_shutdown_during_vmware_vsphere_cluster_creation]
== VMware vSphere クラスター作成時にグレースフルシャットダウンを有効にする

RKE2/K3sでは、VMのためにグレースフルシャットダウンを設定した新しいVMware vSphereクラスターを構成できます：

. *☰ > クラスター管理*をクリックします。
. *Create*をクリックし、*VMware vSphere*を選択して新しいクラスターをプロビジョニングします。
. menu:マシンプール[スケジューリング]の下で、*グレースフルシャットダウンタイムアウト*フィールドに0より大きい整数値を入力します。入力した値は、Rancherがクラスター上のVMを削除する前に待機する秒数です。値が`0`に設定されている場合、グレースフルシャットダウンは無効になります。

[#_enable_graceful_shutdown_in_existing_rke2_product_name_k3s_product_name_clusters]
== 既存の{rke2-product-name}/{k3s-product-name}クラスターでグレースフルシャットダウンを有効にする

RKE2/K3sでは、既存のVMware vSphereクラスターの設定を編集してグレースフルシャットダウンを有効にすることができ、これによりVMを削除する前に遅延が追加されます。

. *☰ > クラスター管理*をクリックします。
. *クラスター*ページで、編集対象の、VMware vSphere上でホストされているクラスターを見つけます。クラスターに関連する行の最後にある*⋮*をクリックします。*Edit Config*を選択します。
. menu:マシンプール[スケジューリング]の下で、*グレースフルシャットダウンタイムアウト*フィールドに0より大きい整数値を入力します。入力した値は、Rancherがクラスター上のVMを削除する前に待機する秒数です。値が`0`に設定されている場合、グレースフルシャットダウンは無効になります。
