= Configuration du stockage existant
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: xref:guides-pratiques/guides-nouveaux-utilisateurs/gerer-des-clusters/creer-un-stockage-persistant-kubernetes/gerer-le-stockage-persistant/configurer-le-stockage-existant.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/set-up-existing-storage.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/roles-de-cluster-et-de-projet.adoc
:xref-longhorn: xref:integrations/longhorn/longhorn.adoc
:xref-vsphere-storage-example: xref:cluster-admin/manage-clusters/persistent-storage/examples/vsphere-storage.adoc
:xref-amazon-ebs-storage: xref:cluster-admin/manage-clusters/persistent-storage/examples/persistent-storage-in-amazon-ebs.adoc
:xref-nfs-storage: xref:cluster-admin/manage-clusters/persistent-storage/examples/nfs-storage.adoc
:xref-about-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/about-persistent-storage.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/roles-de-cluster-et-de-projet.adoc
:xref-longhorn: xref:integrations-in-rancher/longhorn/index.adoc
:xref-vsphere-storage-example: xref:how-to-guides/nouveaux-guides-utilisateurs/gerer-des-clusters/exemples-de-provisionnement-de-stockage/vsphere-storage.adoc
:xref-amazon-ebs-storage: xref:how-to-guides/nouveaux-guides-utilisateurs/gerer-des-clusters/exemples-de-provisionnement-de-stockage/persistent-storage-in-amazon-ebs.adoc
:xref-nfs-storage: xref:how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/nfs-storage.adoc
:xref-about-persistent-storage: xref:how-to-guides/nouveaux-guides-utilisateurs/gerer-des-clusters/créer-un-stockage-persistent-kubernetes/gerer-le-stockage-persistent/à-propos-du-stockage-persistent.adoc
endif::[]

Cette section décrit comment configurer un stockage persistant existant pour les charges de travail dans Rancher.

[NOTE]
====

Cette section suppose que vous comprenez les concepts Kubernetes de volumes persistants et de revendications de volumes persistants. Pour plus d'informations, reportez-vous à la section sur {xref-about-persistent-storage}[comment fonctionne le stockage.]
====


Pour configurer le stockage, suivez ces étapes{nbsp}:

. <<_1_set_up_persistent_storage,Configurer le stockage persistant.>>
. <<_2_add_a_persistentvolume_that_refers_to_the_persistent_storage,Ajouter un PersistentVolume qui fait référence au stockage persistant.>>
. <<_3_use_the_storage_class_for_pods_deployed_with_a_statefulset,Utiliser la classe de stockage pour les Pods déployés avec un StatefulSet.>>

[#_prerequisites]
== Conditions préalables

* Pour créer un volume persistant en tant que ressource Kubernetes, vous devez avoir le `Manage Volumes` {xref-cluster-project-roles}#_project_role_reference[rôle.]
* Si vous provisionnez du stockage pour un cluster hébergé dans le cloud, le stockage et les hôtes du cluster doivent avoir le même fournisseur de cloud.

[#_1_set_up_persistent_storage]
== 1. Configurer le stockage persistant

Créer un volume persistant dans Rancher ne créera pas de volume de stockage. Cela crée uniquement une ressource Kubernetes qui correspond à un volume existant. Par conséquent, avant de pouvoir créer un volume persistant en tant que ressource Kubernetes, vous devez avoir un stockage provisionné.

ifeval::["{build-type}" != "srfa"]
Les étapes pour configurer un dispositif de stockage persistant varieront en fonction de votre infrastructure. Nous fournissons des exemples de configuration de stockage utilisant {xref-vsphere-storage-example}[vSphere,] {xref-nfs-storage}[NFS,] ou {xref-amazon-ebs-storage}[EBS] d'Amazon.
endif::[]
ifeval::["{build-type}" == "srfa"]
Les étapes pour configurer un dispositif de stockage persistant varieront en fonction de votre infrastructure. Nous fournissons des exemples de configuration de stockage utilisant {xref-nfs-storage}[NFS] ou {xref-amazon-ebs-storage}[EBS] d'Amazon.
endif::[]

Si vous avez un pool de stockage de blocs et que vous ne souhaitez pas utiliser un fournisseur de cloud, Longhorn pourrait vous aider à fournir un stockage persistant à votre cluster Kubernetes. Pour plus d'informations, consultez {xref-longhorn}[Stockage natif Cloud avec Longhorn].

[#_2_add_a_persistentvolume_that_refers_to_the_persistent_storage]
== 2. Ajouter un PersistentVolume qui fait référence au stockage persistant

Ces étapes décrivent comment configurer un PersistentVolume au niveau du cluster dans Kubernetes.

. Cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster où vous souhaitez ajouter un volume persistant et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur menu:Stockage[Volumes persistants].
. Cliquez sur *Create*.
. Entrez un *Nom* pour le volume persistant.
. Sélectionnez le *Plugin de volume* pour le type de disque ou le service que vous utilisez. Lors de l'ajout de stockage à un cluster hébergé par un fournisseur de cloud, utilisez le plug-in du fournisseur de cloud pour le stockage cloud. Par exemple, si vous avez un cluster Amazon EC2 et que vous souhaitez utiliser un stockage cloud pour celui-ci, vous devez utiliser le plug-in de volume `Amazon EBS Disk`.
. Entrez la *Capacité* de votre volume en gigaoctets.
. Complétez le formulaire de *Configuration du plug-in*. Chaque type de plug-in nécessite des informations spécifiques au fournisseur du type de disque. Pour obtenir de l'aide concernant le formulaire de chaque plug-in et les informations requises, consultez la documentation du fournisseur du plug-in.
. Facultatives : Dans le formulaire *Personnaliser*, configurez les https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[modes d'accès.] Cette option définit combien de nœuds peuvent accéder au volume, ainsi que les autorisations de lecture/écriture des nœuds. La https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[Documentation Kubernetes] comprend un tableau qui répertorie les modes d'accès pris en charge par les plugins disponibles.
. Facultatives : Dans le formulaire *Personnaliser*, configurez les https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options[options de montage.] Chaque plugin de volume vous permet de spécifier des options de commande supplémentaires lors du processus de montage. Consultez la documentation du fournisseur de chaque plugin pour les options de montage disponibles.
. Cliquez sur *Create*.

*Résultat :* Votre nouveau volume persistant est créé.

[#_3_use_the_storage_class_for_pods_deployed_with_a_statefulset]
== 3. Utilisez la classe de stockage pour les pods déployés avec un StatefulSet.

Les StatefulSets gèrent le déploiement et la mise à l'échelle des pods tout en maintenant une identité persistante pour chaque pod. Dans ce StatefulSet, nous allons configurer un VolumeClaimTemplate. Chaque pod géré par le StatefulSet sera déployé avec un PersistentVolumeClaim basé sur ce VolumeClaimTemplate. Le PersistentVolumeClaim fera référence au PersistentVolume que nous avons créé. Par conséquent, lorsque chaque pod géré par le StatefulSet est déployé, il sera lié à un PersistentVolume tel que défini dans son PersistentVolumeClaim.

Vous pouvez configurer le stockage pour le StatefulSet pendant ou après la création de la charge de travail.

Les étapes suivantes décrivent comment attribuer un stockage existant à un nouveau StatefulSet{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster où vous souhaitez configurer le stockage pour le StatefulSet et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur menu:Charge de travail[StatefulSets].
. Cliquez sur *Create*.
. Choisissez l'espace de noms où la charge de travail sera déployée.
. Entrez un nom pour le StatefulSet.
. Dans l'onglet *Modèles de demande de volume*, cliquez sur *Ajouter un modèle de demande*.
. Cliquez sur *Utiliser un volume persistant existant*.
. Dans le champ des volumes persistants, sélectionnez le volume persistant que vous avez créé.
. Dans le champ *Point de montage*, entrez le chemin que la charge de travail utilisera pour accéder au volume.
. Cliquez sur *Lancer*.

*Résultat :* Lorsque la charge de travail est déployée, elle fera une demande pour la quantité spécifiée d'espace disque au maître Kubernetes. Si un PV avec les ressources spécifiées est disponible lorsque la charge de travail est déployée, le maître Kubernetes liera le PV au PVC.

Les étapes suivantes décrivent comment attribuer un stockage persistant à une charge de travail existante{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster où vous souhaitez configurer le stockage pour le StatefulSet et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur menu:Charge de travail[StatefulSets].
. Allez à la charge de travail à laquelle vous souhaitez ajouter le stockage persistant. Cliquez sur *⋮ > Modifier*.
. Dans l'onglet *Modèles de demande de volume*, cliquez sur *Ajouter un modèle de demande*.
. Cliquez sur *Utiliser un volume persistant existant*.
. Dans le champ des volumes persistants, sélectionnez le volume persistant que vous avez créé.
. Dans le champ *Point de montage*, entrez le chemin que la charge de travail utilisera pour accéder au volume.
. Cliquez sur *Lancer*.

*Résultat :* La charge de travail fera une demande pour la quantité spécifiée d'espace disque au maître Kubernetes. Si un PV avec les ressources spécifiées est disponible lorsque la charge de travail est déployée, le maître Kubernetes liera le PV au PVC.
