= Release v2.12.5
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-16
:page-revdate: {revdate}

[IMPORTANT]
====
If you are using Active Directory Federation Service (AD FS), upgrading to Rancher v2.10.1 or later may cause issues with authentication, requiring manual intervention. These issues are due to the AD FS Relying Party Trust not being able to pick up a signature verification certificate from the metadata. They can be corrected by either of two methods:

* Updating the Relying Party Trust information from federation metadata (Relying Party Trust -> Update from Federation Metadata...)
* Directly adding the certificate (Relying Party Trust -> Properties -> Signature tab -> Add -> Select the certificate).

For more information see https://github.com/rancher/rancher/issues/48655[#48655].
====

[IMPORTANT]
====
ifeval::["{build-type}" == "community"]
https://ranchermanager.docs.rancher.com/v2.12/integrations-in-rancher/istio[Rancher-Istio] has been deprecated in Rancher v2.12.0; turn to the https://apps.rancher.io[SUSE Application Collection] build of Istio for enhanced security (included in SUSE Rancher Prime subscriptions). Detailed information can be found in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[this announcement].
endif::[]
ifeval::["{build-type}" == "product"]
https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/observability/istio/istio.html[Rancher-Istio] has been deprecated in Rancher v2.12.0; turn to the https://apps.rancher.io[SUSE Application Collection] build of Istio for enhanced security (included in SUSE Rancher Prime subscriptions). Detailed information can be found in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[this announcement].
endif::[]
====

For more information on new features in the general minor release see the https://github.com/rancher/rancher/releases/tag/v2.12.0[v2.12.0 release notes].

== Changes Since v2.12.4

See the full list of https://github.com/rancher/rancher/compare/v2.12.4...v2.12.5[changes].

== Install/Upgrade Notes

ifeval::["{build-type}" == "community"]
If you're installing Rancher for the first time, your environment must fulfill the https://ranchermanager.docs.rancher.com/v2.12/getting-started/installation-and-upgrade/installation-requirements[installation requirements].
endif::[]
ifeval::["{build-type}" == "product"]
If you're installing Rancher for the first time, your environment must fulfill the https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/installation-and-upgrade/requirements/requirements.html[installation requirements].
endif::[]

[IMPORTANT]
====
Rancher now requires the cluster it runs on to have the https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/[Kubernetes API Aggregation Layer] enabled. This is because Rancher extends Kubernetes with additional APIs by registering its own extension API server. Please note that all versions of Kubernetes supported in this Rancher versions K8s distributions (RKE2/K3s) will have the aggregation layer configured and enabled by default. 
ifeval::["{build-type}" == "community"]
Refer to the https://ranchermanager.docs.rancher.com/v2.12/api/extension-apiserver#aggregation-layer-is-required[Extension API Server documentation] and https://github.com/rancher/rancher/issues/50400[#50400] for more information.
endif::[]
ifeval::["{build-type}" == "product"]
Refer to the https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/api/extension-apiserver.html#_aggregation_layer_is_required[Extension API Server documentation] and https://github.com/rancher/rancher/issues/50400[#50400] for more information.
endif::[]
====

[IMPORTANT]
====
Rancher Kubernetes Engine (RKE/RKE1) has reached end of life as of *July 31, 2025*. Rancher versions 2.12.0 and later no longer support provisioning or managing downstream RKE1 clusters. We recommend replatforming RKE1 clusters to RKE2 to ensure continued support and security updates. Learn more about the transition https://www.suse.com/support/kb/doc/?id=000021518[here].
Rancher now has a pre-upgrade validation check for RKE1 resources which fails and lists the RKE1 resources if present. Refer to https://github.com/rancher/rancher/issues/50286[#50286] for more information.
====

[IMPORTANT]
====
It is crucial that you review the available disk space on your nodes and plan accordingly before upgrading to Rancher v2.12.0 and later to avoid potential disk pressure and pod eviction issues.
ifeval::["{build-type}" == "community"]
For additional information refer to the https://ranchermanager.docs.rancher.com/v2.12/how-to-guides/advanced-user-guides/ui-server-side-pagination#disk-space[UI Server Side Pagination - Disk Space documentation].
endif::[]
ifeval::["{build-type}" == "product"]
For additional information refer to the https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/rancher-admin/global-configuration/ui-server-side-pagination.html#_disk_space[UI Server Side Pagination - Disk Space documentation].
endif::[]
====

[IMPORTANT]
====
ifeval::["{build-type}" == "community"]
Rancher now has an enablement option called https://ranchermanager.docs.rancher.com/v2.12/how-to-guides/advanced-user-guides/enable-api-audit-log#viewing-api-audit-logs:~:text=Description-,AUDIT_LOG_ENABLED,-false%20%2D%20Disables%20the[`AUDIT_LOG_ENABLED`] for API Audit Logs for a Rancher installation. In Rancher versions 2.11.x and earlier, only the `AUDIT_LEVEL` could be set and the default log level (`0`) would disable the audit log. In Rancher versions 2.12.x and later, the default log level (`0`) now only contains the log request and response metadata, and can be set when configuring `AUDIT_LOG_ENABLED`. If installing or upgrading via Helm you can enable the API Audit Logs and specify the log level by applying the following setting to your Helm command: `--set auditLog.enabled=true --set auditLog.level=0`. See the https://ranchermanager.docs.rancher.com/v2.12/how-to-guides/advanced-user-guides/enable-api-audit-log[Enabling the API Audit Log to Record System Events] documentation and https://github.com/rancher/rancher/issues/48941[#48941].
endif::[]
ifeval::["{build-type}" == "product"]
Rancher now has an enablement option called https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/observability/logging/enable-api-audit-log.html#_api_audit_log_options[`AUDIT_LOG_ENABLED`] for API Audit Logs for a Rancher installation. In Rancher versions 2.11.x and earlier, only the `AUDIT_LEVEL` could be set and the default log level (`0`) would disable the audit log. In Rancher versions 2.12.x and later, the default log level (`0`) now only contains the log request and response metadata, and can be set when configuring `AUDIT_LOG_ENABLED`. If installing or upgrading via Helm you can enable the API Audit Logs and specify the log level by applying the following setting to your Helm command: `--set auditLog.enabled=true --set auditLog.level=0`. See the https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/observability/logging/enable-api-audit-log.html[Enabling the API Audit Log to Record System Events] documentation and https://github.com/rancher/rancher/issues/48941[#48941].
endif::[]
====

=== Changes in Image Artifacts

Image artifact digests are renamed in Rancher v2.12.0, v2.11.4 and v2.10.8. Up until this change, separate image digests files for each operating system and architecture have been maintained for compatibility reasons. With this change, only one file for each operating system is to be provided:
* The `rancher-images-digests-linux-amd64.txt` and `rancher-images-digests-linux-arm64.txt` files are to be renamed to `rancher-images-digests-linux.txt`.
* The `rancher-images-digests-windows-ltsc2019.txt` and `rancher-images-digests-windows-ltsc2022.txt` files are to be renamed to `rancher-images-digests-windows.txt`.

== Upgrade Requirements

ifeval::["{build-type}" == "community"]
* *Creating backups:* https://ranchermanager.docs.rancher.com/v2.12/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher[Create a backup] before you upgrade Rancher. To roll back Rancher after an upgrade, you must first back up and restore Rancher to the previous Rancher version. Because Rancher will be restored to the same state as when the backup was created, any changes post-upgrade will not be included after the restore.
endif::[]
ifeval::["{build-type}" == "product"]
* *Creating backups:* https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/rancher-admin/back-up-restore-and-disaster-recovery/back-up.html[Create a backup] before you upgrade Rancher. To roll back Rancher after an upgrade, you must first back up and restore Rancher to the previous Rancher version. Because Rancher will be restored to the same state as when the backup was created, any changes post-upgrade will not be included after the restore.
endif::[]
* *Helm version requirements:*
** To manage Rancher 2.12.x and later, you must upgrade your Helm client to version 3.18 or newer.
** This change is required to reflect the addition of Kubernetes 1.33 support with this release.
** Currently, the official https://helm.sh/docs/topics/version_skew/[Helm Version Support Policy] dictates that only Helm 3.18 supports the proper Kubernetes version range for Rancher 2.12.
* *CNI requirements:*
** For Kubernetes v1.19 and later, disable firewalld as it's incompatible with various CNI plugins. See https://github.com/rancher/rancher/issues/28840[#28840].
** When upgrading or installing a Linux distribution that uses nf_tables as the backend packet filter, such as SLES 15, RHEL 8, Ubuntu 20.10, Debian 10, or later, upgrade to RKE v1.19.2 or later to get Flannel v0.13.0. Flannel v0.13.0 supports nf_tables. See Flannel https://github.com/flannel-io/flannel/issues/1317[#1317].
* *Requirements for air-gapped environments:*
ifeval::["{build-type}" == "community"]
** When using a proxy in front of an air-gapped Rancher instance, you must pass additional parameters to `NO_PROXY`. See the https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-rancher[documentation] and issue https://github.com/rancher/docs/issues/2725#issuecomment-702454584[#2725].
** When installing Rancher with Docker in an air-gapped environment, you must supply a custom `registries.yaml` file to the `docker run` command, as shown in the https://docs.k3s.io/installation/private-registry[K3s documentation]. If the registry has certificates, then you'll also need to supply those. See https://github.com/rancher/rancher/issues/28969#issuecomment-694474229[#28969].
endif::[]
ifeval::["{build-type}" == "product"]
** When using a proxy in front of an air-gapped Rancher instance, you must pass additional parameters to `NO_PROXY`. See the https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/installation-and-upgrade/other-installation-methods/http-proxy/install-rancher.html[documentation] and issue https://github.com/rancher/docs/issues/2725#issuecomment-702454584[#2725].
** When installing Rancher with Docker in an air-gapped environment, you must supply a custom `registries.yaml` file to the `docker run` command, as shown in the https://documentation.suse.com/cloudnative/k3s/latest/en/installation/private-registry.html[K3s documentation]. If the registry has certificates, then you'll also need to supply those. See https://github.com/rancher/rancher/issues/28969#issuecomment-694474229[#28969].
endif::[]

== Versions

== Images

* rancher/rancher:v2.12.5

== Tools

* CLI - https://github.com/rancher/cli/releases/tag/v2.12.5[v2.12.5]

=== Kubernetes Versions for RKE2/K3s

* v1.33.6 (Default)
* v1.32.10
* v1.31.14

=== Rancher Helm Chart Versions

In Rancher v2.6.0 and later, in the **Apps & Marketplace** UI, many Rancher Helm charts are named with a major version that starts with *100*. This avoids simultaneous upstream changes and Rancher changes from causing conflicting version increments. This also complies with semantic versioning (SemVer), which is a requirement for Helm. You can see the upstream version number of a chart in the build metadata, for example: `100.0.0+up2.1.0`. See [#32294](https://github.com/rancher/rancher/issues/32294).

== Previous Rancher Behavior Changes

=== Previous Rancher Behavior Changes - Rancher General

* **Rancher v2.12.0:**
** Kubernetes v1.30 is no longer supported. Before upgrading to Rancher v2.12.0, ensure all clusters are running Kubernetes v1.31 or later. See https://github.com/rancher/rancher/issues/49679[#49679].
** The feature flag `ui-sql-cache` (Server-Side Pagination) is now enabled by default in Rancher. Please refer to the https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/rancher-admin/global-configuration/ui-server-side-pagination.html[UI Server-Side Pagination] document for more information.

  Beginning with Rancher v2.12.0, UI Server-Side Pagination is enabled by default to provide significant performance improvements across the Rancher UI. This feature relies on a caching mechanism that introduces a new requirement for ephemeral disk space on your cluster nodes.

  This cache, an internal SQLite database, is stored within the container's filesystem. This affects the nodes running the Rancher server pods (rancher in the cattle-system namespace on the local cluster) and the nodes running the Rancher agent pods (cattle-cluster-agent in the cattle-system namespace on all downstream clusters).
  The amount of disk space required is dynamic and depends on the quantity and size of Kubernetes resources visualized in the UI. As a guideline, the cache may consume approximately twice the size of the raw Kubernetes objects it stores. For instance, internal tests showed that caching 5000 ConfigMaps, totaling 50 MB, consumed 81 MB of disk space. For a conservative, high-level estimate, you can plan for the available disk space on each relevant node to be at least twice the size of your etcd snapshot. For most production environments, ensuring a few extra gigabytes of storage are available on the relevant nodes is a safe starting point.

  It is crucial that you review the available disk space on your nodes and plan accordingly before upgrading to this version to avoid potential disk pressure and pod eviction issues.

  This update has introduced limitations which are outlined in the https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/rancher-admin/global-configuration/ui-server-side-pagination.html#_known_limitations_of_ui_server_side_pagination[UI Server Side Pagination documentation]. See https://github.com/rancher/rancher/issues/48691[#48691] and https://github.com/rancher/dashboard/issues/12975[#12975] for more information.

=== Previous Rancher Behavior Changes - Logging

* **Rancher v2.12.0:**
** Rancher now has an enablement option called https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/observability/logging/enable-api-audit-log.html#_api_audit_log_options[`AUDIT_LOG_ENABLED`] for API Audit Logs for a Rancher installation. In Rancher versions 2.11.x and earlier, only the `AUDIT_LEVEL` could be set and the default log level (`0`) would disable the audit log. In Rancher versions 2.12.x and later, the default log level (`0`) now only contains the log request and response metadata, and can be set when configuring `AUDIT_LOG_ENABLED`. If installing or upgrading via Helm you can enable the API Audit Logs and specify the log level by applying the following setting to your Helm command: `--set auditLog.enabled=true --set auditLog.level=0`. See the https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/observability/logging/enable-api-audit-log.html[Enabling the API Audit Log to Record System Events] documentation and https://github.com/rancher/rancher/issues/48941[#48941].

=== Previous Rancher Behavior Changes - Cluster Provisioning

* **Rancher v2.12.0:**
** Rancher's `system-upgrade-controller` app is now managed by the `systemchart` handler in downstream provisioned RKE2/K3s clusters. For additional information refer to this https://github.com/rancher/rancher/issues/47737#issuecomment-3025216088[comment] and see https://github.com/rancher/rancher/issues/47737[#47737].
** Rancher v2.12.0 introduces changes in Custom Resource Definition (CRD) validations for `dynamicschemas.management.cattle.io` and dynamically generated CRDs:
  **DynamicSchema**
  `dynamicschemas.management.cattle.io`
  This CRD had a generic schema that allowed any field to be set. It has been updated to only allow the expected fields.
  This is not a user-facing CRD and is used internally by rancher.
  **InfrastructureMachine CRDs**
  These are the CAPI InfrastructureMachine CRDs defined for the Rancher Cluster API (CAPI) infrastructure provider. They are dynamically generated and are named `<name>machines.rke-machine.cattle.io`, where `<name>` is derived from the node driver used to provision machines with a given infrastructure provider. Each active node driver has an associated InfrastructureMachine CRD.
  InfrastructureMachine objects are generated automatically by Rancher from other configuration objects.
  The following validations were changed in this CRD schema:
  * `spec.common.cloudCredentialSecretName`
  ** Value must be 317 characters long or less (`<namespace>:<secretname>`). 
  * `spec.common.labels`
  ** Label values are no longer allowed to take a `null` value.
  * `spec.common.taints`, in each taint object:
  ** Fields `effect` and `key` are now required.
  ** Field `timeAdded` is now required to be in the `date-time` format.
  ** All fields are no longer allowed to take a `null` value.
  * `status.addresses`, in each address object:
  ** Fields `address` and `type` are now required and are no longer allowed to take a `null` value.
  ** Field `type` must take one of the following values: `Hostname`, `ExternalIP`, `InternalIP`, `ExternalDNS` or `InternalDNS`.
  ** Field `address` must be between 1 and 256 characters long.
  * `status.conditions`, in each condition object:
  ** Fields `status` and `type` are now required.
  ** No fields are allowed to take a `null` value anymore.
  * `status`
  ** No fields are allowed to take a `null` value anymore.
  **InfrastructureMachineTemplate CRDs**
  These are the CAPI InfrastructureMachineTemplate CRDs defined for the Rancher CAPI infrastructure provider. They are dynamically generated and are named `<name>machinetemplates.rke-machine.cattle.io`, where `<name>` is derived from the node driver used to provision machines with a given infrastructure provider. Each active node driver has an associated InfrastructureMachineTemplate CRD.
  InfrastructureMachineTemplate objects are generated automatically by Rancher from other configuration objects.
  * `spec.template.spec.common.cloudCredentialSecretName`
  ** Value must be 317 characters long or less (`<namespace>:<secretname>`).
  * `spec.template.spec.common.labels`
  ** Label values are no longer allowed to take a `null` value.
  * `spec.template.spec.common.taints`, in each taint object:
  ** Fields `effect` and `key` are now required.
  ** Field `timeAdded` is now required to be in the `date-time` format.
  ** No fields are allowed to take a `null` value anymore.
    
  See https://github.com/rancher/rancher/issues/49402[#49402] for more information.

=== Previous Rancher Behavior Changes - Continuous Delivery (Fleet)

* **Rancher v2.12.0:**
** A migration patching service account is removed, meaning the image `rancher/kubectl` is no longer needed. See https://github.com/rancher/fleet/pull/3601[fleet#3601].

== Long-standing Known Issues
<!-- Apply same headers as "Major Bug Fixes" but with "Long-standing Known Issues" suffix instead -->

=== Long-standing Known Issues - Rancher General

* **Rancher v2.12.2:**
** The https://scc.suse.com/home[SUSE Customer Center (SCC)] system view has a known issue being investigated regarding duplicate Rancher Manager registrations. See https://github.com/rancher/scc-operator/issues/38[rancher/scc-operator #38].

=== Long-standing Known Issues - Cluster Provisioning

* Not all cluster tools can be installed on a hardened cluster.<!--no issue number available -->
* **Rancher v2.8.1:**
** When you  attempt to register a new etcd/controlplane node in a CAPR-managed cluster after a failed etcd snapshot restoration, the node can become stuck in a perpetual paused state, displaying the error message `[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again`. As a workaround, you can unpause the cluster by running `kubectl edit clusters.cluster clustername -n fleet-default` and set `spec.unpaused` to `false`.  See https://github.com/rancher/rancher/issues/43735[#43735].
* **Rancher v2.7.2:**
** If you upgrade or update any hosted cluster, and go to **Cluster Management > Clusters** while the cluster is still provisioning, the **Registration** tab is visible. Registering a cluster that is already registered with Rancher can cause data corruption. See https://github.com/rancher/dashboard/issues/8524[#8524].

=== Long-standing Known Issues - RKE2 Provisioning <!-- hostbusters -->

* **Rancher v2.7.7:**
** Due to the backoff logic in various components, downstream provisioned K3s and RKE2 clusters may take longer to re-achieve `Active` status after a migration. If you see that a downstream cluster is still updating or in an error state immediately after a migration, please let it attempt to resolve itself. This might take up to an hour to complete. See https://github.com/rancher/rancher/issues/34518[#34518] and https://github.com/rancher/rancher/issues/42834[#42834].
* **Rancher v2.7.6:**
** Provisioning RKE2/K3s clusters with added (not built-in) custom node drivers causes provisioning to fail. As a workaround, https://github.com/rancher/rancher/issues/37074#issuecomment-1664722305[fix] the added node drivers after activating. See https://github.com/rancher/rancher/issues/37074[#37074].

=== Long-standing Known Issues - K3s Provisioning <!-- hostbusters -->

* **Rancher v2.7.6:**
** Provisioning RKE2/K3s clusters with added (not built-in) custom node drivers causes provisioning to fail. As a workaround, https://github.com/rancher/rancher/issues/37074#issuecomment-1664722305[fix] the added node drivers after activating. See https://github.com/rancher/rancher/issues/37074[#37074].
* **Rancher v2.7.2:**
** Clusters remain in an `Updating` state even when they contain nodes in an `Error` state. See https://github.com/rancher/rancher/issues/39164[#39164].

=== Long-standing Known Issues - Rancher App (Global UI)

* **Rancher v2.12.1:**
** When a standard user with the Cluster Owner role attempts to edit an Azure or AKS cluster, the Machine Pools section shows an error `Cannot read properties of undefined...`. As a workaround, standard users must manually add their cloud credentials to create, edit, and manage Azure or AKS clusters. See https://github.com/rancher/dashboard/issues/15241[#15241].
* **Rancher v2.10.0:**
** After deleting a Namespace or Project in the Rancher UI, the Namespace or Project remains visible. As a workaround, refresh the page. See https://github.com/rancher/dashboard/issues/12220[#12220].
* **Rancher v2.9.2:**
** Although system mode node pools must have at least one node, the Rancher UI allows a minimum node count of zero. Inputting a zero minimum node count through the UI can cause cluster creation to fail due to an invalid parameter error. To prevent this error from occurring, enter a minimum node count at least equal to the node count. See https://github.com/rancher/dashboard/issues/11922[#11922].
* **Rancher v2.7.7:**
** When creating a cluster in the Rancher UI it does not allow the use of an underscore `_` in the `Cluster Name` field. See https://github.com/rancher/dashboard/issues/9416[#9416].

=== Long-standing Known Issues - Hosted Rancher <!-- hostbusters -->

* **Rancher v2.7.5:**
** The **Cluster** page shows the **Registration** tab when updating or upgrading a hosted cluster. See https://github.com/rancher/dashboard/issues/8524[#8524].

=== Long-standing Known Issues - EKS

* **Rancher v2.7.0:**
** EKS clusters on Kubernetes v1.21 or below on Rancher v2.7 cannot be upgraded. See https://github.com/rancher/rancher/issues/39392[#39392].

=== Long-standing Known Issues - Authentication <!-- night's watch -->

* **Rancher v2.9.0:**
** There are some known issues with the OpenID Connect provider support:
*** When the generic OIDC auth provider is enabled, and you attempt to add auth provider users to a cluster or project, users are not populated in the dropdown search bar. This is expected behavior as the OIDC auth provider alone is not searchable. See https://github.com/rancher/rancher/issues/46104[#46104].
*** When the generic OIDC auth provider is enabled, auth provider users that are added to a cluster/project by their username are not able to access resources upon logging in. A user will only have access to resources upon login if the user is added by their userID.  See https://github.com/rancher/rancher/issues/46105[#46105].
*** When the generic OIDC auth provider is enabled and an auth provider user in a nested group is logged into Rancher, the user will see the following error when they attempt to create a Project: `http://projectroletemplatebindings.management.cattle.io/[projectroletemplatebindings.management.cattle.io] is forbidden: User "u-gcxatwsnku" cannot create resource "projectroletemplatebindings" in API group "http://management.cattle.io/[management.cattle.io]" in the namespace "p-9t5pg"`. However, the project is still created. See https://github.com/rancher/rancher/issues/46106[#46106].

=== Long-standing Known Issues - Rancher Webhook <!-- neo -->

* **Rancher v2.7.2:**
** A webhook is installed in all downstream clusters. There are several issues that users may encounter with this functionality:
*** If you rollback from a version of Rancher v2.7.2 or later, to a Rancher version earlier than v2.7.2, the webhooks will remain in downstream clusters. Since the webhook is designed to be 1:1 compatible with specific versions of Rancher, this can cause unexpected behaviors to occur downstream. The Rancher team has developed a https://github.com/rancher/webhook/wiki/Remove-Webhook-from-downstream-clusters[script] which should be used after rollback is complete (meaning after a Rancher version earlier than v2.7.2 is running). This removes the webhook from affected downstream clusters. See https://github.com/rancher/rancher/issues/40816[#40816].

=== Long-standing Known Issues - Virtualization Management (Harvester)

* **Rancher v2.7.2:**
** If you're using Rancher v2.7.2 with Harvester v1.1.1 clusters, you won't be able to select the Harvester cloud provider when deploying or updating guest clusters. The https://github.com/harvester/release-notes/blob/main/v1.1.2.md#important-information-about-rancher-support[Harvester release notes] contain instructions on how to resolve this. See https://github.com/harvester/harvester/issues/3750[#3750].

=== Long-standing Known Issues - Backup/Restore <!-- night's watch -->

* When migrating to a cluster with the Rancher Backup feature, the server-url cannot be changed to a different location. It must continue to use the same URL.<!-- no issue number -->
* **Rancher v2.7.7:**
** Due to the backoff logic in various components, downstream provisioned K3s and RKE2 clusters may take longer to re-achieve `Active` status after a migration. If you see that a downstream cluster is still updating or in an error state immediately after a migration, please let it attempt to resolve itself. This might take up to an hour to complete. See https://github.com/rancher/rancher/issues/34518[#34518] and https://github.com/rancher/rancher/issues/42834[#42834].