= FAQ Geral
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-18
:page-revdate: {revdate}
:community-path: faq/general-faq.adoc 
:product-path: faq/general-faq.adoc
ifeval::["{build-type}" != "community"]
:xref-istio: xref:observability/istio/istio.adoc
:xref-manage-clusters: xref:cluster-admin/manage-clusters/manage-clusters.adoc
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-use-windows-clusters: xref:cluster-deployment/custom-clusters/windows/use-windows-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio: xref:integrations-in-rancher/istio/index.adoc
:xref-manage-clusters: xref:how-to-guides/new-user-guides/manage-clusters/index.adoc
:xref-rancher-on-aks: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-aks.adoc
:xref-use-windows-clusters: xref:guias-de-procedimentos/guias-para-novos-usuários/kubernetes-clusters-no-rancher-setup/use-windows-clusters/index.adoc
endif::[]

Este FAQ é um trabalho em andamento projetado para responder às perguntas mais frequentemente feitas sobre o Rancher v2.x.

Consulte o xref:faq/technical-items.adoc[FAQ Técnico] para perguntas técnicas frequentes.

ifeval::["{build-type}" != "srfa"]
[#_is_it_possible_to_manage_azure_kubernetes_services_with_rancher_v2_x]
== É possível gerenciar os Serviços de Kubernetes do Azure com o Rancher v2.x?

Sim. Consulte nosso guia de {xref-manage-clusters}[Administração de Cluster] para saber quais recursos do Rancher estão disponíveis no AKS, bem como nossa {xref-rancher-on-aks}[documentação sobre AKS].

[#_does_rancher_support_windows]
== O Rancher suporta Windows?

Sim. O Rancher suporta contêineres do Windows Server 1809. Para detalhes sobre como configurar um cluster com nós de trabalho do Windows, consulte a seção sobre {xref-use-windows-clusters}[configurando clusters personalizados para Windows.]
endif::[]

[#_does_rancher_support_istio]
== O Rancher suporta Istio?

Sim. O Rancher suporta {xref-istio}[Istio].

[#_will_rancher_v2_x_support_hashicorps_vault_for_storing_secrets]
== O Rancher v2.x suportará o Vault da Hashicorp para armazenar segredos?

O gerenciamento de segredos está em nosso roadmap, mas ainda não o atribuímos a uma versão específica.

[#_does_rancher_v2_x_support_rkt_containers_as_well]
== O Rancher v2.x também suporta contêineres RKT?

Neste momento, suportamos apenas Docker.

[#_does_rancher_v2_x_support_calico_contiv_contrail_flannel_weave_net_etc_for_embedded_and_registered_kubernetes]
== O Rancher v2.x suporta Calico, Contiv, Contrail, Flannel, Weave net, etc., para Kubernetes embutido e registrado?

Pronto para uso, o Rancher fornece os seguintes provedores de rede CNI para clusters Kubernetes: Canal, Flannel, Calico e Weave.  Sempre consulte a https://rancher.com/support-maintenance-terms/[Matriz de Suporte do Rancher] para detalhes sobre o que é oficialmente suportado.

[#_are_you_planning_on_supporting_traefik_for_existing_setups]
== Você está planejando oferecer suporte ao Traefik para configurações existentes?

Atualmente, não planejamos fornecer suporte embutido ao Traefik, mas ainda estamos explorando abordagens de balanceamento de carga.

[#_can_i_import_openshift_kubernetes_clusters_into_v2_x]
== Posso importar clusters Kubernetes do OpenShift para a versão v2.x?

Nosso objetivo é executar qualquer cluster Kubernetes. Portanto, o Rancher v2.x deve funcionar com o OpenShift, mas ainda não o testamos.

[#_is_longhorn_product_name_integrated_with_rancher]
== O {longhorn-product-name} está integrado ao Rancher?

Sim. O Longhorn está integrado ao Rancher v2.5 e versões posteriores.
