= {rancher-product-name}のインストール
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/index.adoc 
:product-path: installation-and-upgrade/installation-and-upgrade.adoc
:description: Rancherを開発環境と本番環境にインストールする方法を学びます。単一ノードおよび高可用性インストールについて読む
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
:xref-rancher-architecture: xref:about-rancher/architecture/architecture.adoc
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-qs-aws-marketplace: xref:installation-and-upgrade/quick-start/deploy-rancher/aws-marketplace.adoc
:xref-http-proxy: xref:installation-and-upgrade/other-installation-methods/http-proxy/http-proxy.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-air-gap: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/index.adoc
:xref-migrate-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster.adoc
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-qs-aws-marketplace: xref:getting-started/quick-start-guides/deploy-rancher-manager/aws-marketplace.adoc
:xref-http-proxy: xref:getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/index.adoc
endif::[]

このセクションでは、Rancherのインストールに関するアーキテクチャオプションの概要を提供し、それぞれのオプションの利点を説明します。

[#_terminology]
== 用語集

このセクションでは、

* *Rancherサーバー*はKubernetesクラスターを管理およびプロビジョニングします。Rancherサーバーのユーザーインターフェースを通じて、ダウンストリームのKubernetesクラスターと対話できます。Rancher管理サーバーは、Amazon EKSクラスターなどのホスティングされたクラスターを含む、任意のKubernetesクラスターにインストールできます。
* *RKE (Rancher Kubernetes Engine)*は、Kubernetesクラスターを作成および管理する認定KubernetesディストリビューションおよびCLI/ライブラリです。
* *K3s (軽量Kubernetes)*も完全準拠のKubernetesディストリビューションです。それはRKEよりも新しく、使いやすく、バイナリサイズが100MB未満で、より軽量です。
* *RKE2*は、米国におけるセキュリティとコンプライアンスに焦点を当てた完全準拠のKubernetesディストリビューションです。の紹介。

[#_overview_of_installation_options]
== インストールオプションの概要

Rancherは、これらの主要なアーキテクチャにインストールできます：

[#_high_availability_kubernetes_install_with_the_helm_cli]
=== Helm CLIを使用した高可用性Kubernetesインストール

専用のKubernetesクラスター上の複数のノードにRancherをインストールするために、KubernetesパッケージマネージャーであるHelmの使用をお勧めします。RKEクラスターの場合、高可用性クラスターを達成するには3つのノードが必要です。K3sクラスターの場合、2つのノードのみが必要です。

[#_rancher_on_eks_install_with_the_aws_marketplace]
=== AWSマーケットプレイスを使用したEKS上のRancherインストール

Rancherは、Amazon Elastic Kubernetes Service (EKS)に{xref-qs-aws-marketplace}[AWSマーケットプレイスを通じて]インストールできます。デプロイされたEKSクラスターは運用準備完了であり、AWSのベストプラクティスに従っています。

[#_single_node_kubernetes_install]
=== 単一ノードKubernetesインストール

Rancherは単一ノードのKubernetesクラスターにインストールできます。この場合、Rancherサーバーは高可用性を持たず、これは本番環境でRancherを運用するために重要です。

ただし、このオプションは、短期間に単一ノードを使用してリソースを節約しつつ、高可用性への移行パスを確保したい場合に役立ちます。将来的には、クラスターにノードを追加して高可用性のRancherサーバーを構築できます。

[#_docker_install]
=== Dockerのインストール

テストやデモ目的で、Rancherは単一ノードにDockerでインストールできます。ローカルクラスタは単一のDockerコンテナ内にインストールされ、Rancherはローカルクラスタにインストールされます。

Rancherバックアップオペレーターは、単一のDockerコンテナインストールから高可用性KubernetesクラスターへのRancherの移行に使用できます。詳細については、{xref-migrate-cluster}[新しいクラスターへのRancherの移行]に関するドキュメントを参照してください。

[#_other_options]
=== その他のオプション

エアギャップ環境やHTTPプロキシの背後でRancherをインストールするための別の手順もあります：

|===
| インターネットアクセスのレベル | Kubernetesインストール - 強く推奨されます | Dockerインストール

| インターネットへの直接アクセスがある場合
| {xref-install-rancher}[マニュアル]
| xref:[マニュアル]

| HTTPプロキシの背後で
| {xref-http-proxy}[マニュアル]
| これらのxref:[マニュアル]、およびこのxref:[設定]

| エアギャップ環境で
| {xref-air-gap}[マニュアル]
| {xref-air-gap}[マニュアル]
|===

RancherはKubernetesクラスターにインストールすることをお勧めします。なぜなら、マルチノードクラスターではRancher管理サーバーが高可用性になるからです。この高可用性の構成は、Rancherが管理するダウンストリームのKubernetesクラスターへの一貫したアクセスを維持するのに役立ちます。

そのため、本番環境に適したアーキテクチャを構築するには、高可用性のKubernetesクラスターを設定し、その上にRancherをインストールすることをお勧めします。Rancherがインストールされた後、Rancherを使用してKubernetesクラスターをデプロイおよび管理できます。

テストまたはデモ目的の場合、単一のDockerコンテナにRancherをインストールできます。このDockerインストールでは、Rancherを使用してKubernetesクラスターをすぐにセットアップできます。Dockerインストールでは、Rancherサーバーの機能を探索できますが、開発およびテスト目的でのみ使用することを意図しています。

私たちの{xref-install-rancher}[Kubernetes上にRancherをインストールするための手順]では、最初にK3sまたはRKEを使用してKubernetesクラスターを作成および管理し、その後そのクラスターにRancherをインストールする方法を説明しています。

Kubernetesクラスター内のノードが稼働し、{xref-install-reqs}[ノード要件]を満たすと、Helmを使用してKubernetesにRancherをデプロイします。HelmはRancherのHelmチャートを使用して、Kubernetesクラスター内の各ノードにRancherのレプリカをインストールします。クラスター内の各Rancherのレプリカにトラフィックを誘導するために、ロードバランサーの使用をお勧めします。

Rancherアーキテクチャについての詳細な議論については、{xref-rancher-architecture}[アーキテクチャの概要]、{xref-arch-rec}[生産グレードのアーキテクチャに関する推奨事項]、または私たちの{xref-tips-for-running-rancher}[ベストプラクティスガイド]を参照してください。

[#_prerequisites]
== 前提条件

Rancherをインストールする前に、ノードがすべての{xref-install-reqs}[インストール要件]を満たしていることを確認してください。

[#_architecture_tip]
== アーキテクチャのヒント

最高のパフォーマンスとより高いセキュリティのために、Rancher管理サーバー専用の別のKubernetesクラスターを推奨します。このクラスターでユーザーのワークロードを実行することは推奨されません。Rancherをデプロイした後、ワークロードを実行するために{xref-cluster-deployment}[クラスターを作成またはインポート]できます。

さらなるアーキテクチャの推奨事項については、{xref-arch-rec}[このページ]を参照してください。

[#_more_options_for_installations_on_a_kubernetes_cluster]
=== Kubernetesクラスターへのインストールのためのその他のオプション

他の構成でKubernetesクラスターにRancherをインストールするための詳細については、{xref-helm-chart-options}[Helmチャートオプション]を参照してください。

* {xref-helm-chart-options}#_api_audit_log[すべてのトランザクションを記録するAPI監査]を使用して
* {xref-helm-chart-options}#_external_tls_termination[ロードバランサーでのTLS終端]を使用して
* With a {xref-helm-chart-options}#_customizing_your_ingress[custom Ingress]

Rancherのインストール手順では、クラスターにRancherをインストールする前にK3sまたはRKEを使用してKubernetesクラスターをセットアップすることをお勧めします。K3sとRKEの両方には、特定の環境に合わせてKubernetesクラスターをカスタマイズするための多くの構成オプションがあります。それぞれの機能の全リストについては、各ドキュメントを参照してください。

* https://rancher.com/docs/rke/latest/en/config-options/[RKEの構成オプション]
* https://rancher.com/docs/k3s/latest/en/installation/install-options/[K3sの構成オプション]

