= 在现有自定义节点上启动Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/index.adoc 
:product-path: cluster-deployment/custom-clusters/custom-clusters.adoc
:description: 要创建一个自定义节点的集群，您需要访问集群中的服务器，并根据Rancher的要求进行配置
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-use-windows-clusters: xref:cluster-deployment/custom-clusters/windows/use-windows-clusters.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-clean-cluster-nodes: xref:cluster-admin/manage-clusters/clean-cluster-nodes.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
:xref-production-checklist: xref:cluster-deployment/production-checklist/production-checklist.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-rke2-config: xref:参考指南/集群配置/Rancher 服务器配置/rke2-cluster-configuration.adoc
:xref-use-windows-clusters: xref:如何指南/新用户指南/在Rancher中设置Kubernetes集群/使用Windows集群/index.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-clean-cluster-nodes: xref:how-to-guides/new-user-guides/manage-clusters/clean-cluster-nodes.adoc
:xref-k3s-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
:xref-production-checklist: xref:如何指南/新用户指南/在Rancher中设置Kubernetes集群/可用于生产用途集群检查清单/index.adoc
endif::[]

当您创建自定义集群时，Rancher可以使用RKE2/K3s在本地裸机服务器、本地虚拟机或任何由基础设施提供商托管的节点上创建Kubernetes集群。

要使用此选项，您需要访问将成为Kubernetes集群一部分的服务器。根据{xref-node-reqs}[要求]配置每台服务器。然后，在每台服务器上运行Rancher UI中提供的命令，将其转换为Kubernetes节点。

本节描述如何设置自定义集群。

[#_creating_a_cluster_with_custom_nodes]
== 使用自定义节点创建集群

[NOTE]
.想要将Windows主机用作Kubernetes工作节点吗？
====

在开始之前，请查看{xref-use-windows-clusters}[为Windows配置自定义集群]。
====


[#_1_provision_a_linux_host]
=== 1.配置Linux主机

通过配置Linux主机开始创建自定义集群。您的主机可以是：

* 云托管的虚拟机（VM）
* 本地虚拟机
* 裸机服务器

如果您想重用之前自定义集群中的节点，请在再次使用之前{xref-clean-cluster-nodes}[清理节点]。如果您重用未清理的节点，集群配置可能会失败。

根据 {xref-node-reqs}[安装要求] 和 {xref-production-checklist}[可用于生产用途集群检查清单] 配置主机。

[NOTE]
.仅 IPv6 集群
====
对于仅 IPv6 集群，请确保您的操作系统正确配置 `/etc/hosts` 文件。

----
::1       localhost
----
====

[#_2_create_the_custom_cluster]
=== 2.创建自定义集群

. 单击 *☰ > 集群管理*。
. 在*集群*页面，点击*创建*。
. 单击 *自定义*。
. 输入*集群名称*。
. 使用 *集群配置* 部分来设置集群。有关更多信息，请参见 {xref-rke2-config}[RKE2 集群配置参考] 和 {xref-k3s-config}[K3s 集群配置参考]。
+
[NOTE]
.Windows 节点
====
要了解更多关于将 Windows 节点用作 Kubernetes 工作节点的信息，请参见 {xref-use-windows-clusters}[在 Windows 集群上启动 Kubernetes]。
====
+
. 单击*创建*。
+
*结果：*用户界面重定向到 *注册* 页面，您可以在此生成节点的注册命令。
+
. 在 *节点角色* 中，选择您希望集群节点承担的角色。您必须为每个角色（etcd、工作节点和控制平面）配置至少一个节点。自定义集群需要完成所有三个角色的配置。有关角色的更多信息，请参见 {xref-k8s-concepts}#_roles_for_nodes_in_kubernetes_clusters[Kubernetes 集群中节点的角色].
+
[NOTE]
.裸机服务器
====
如果您计划为每个角色专用裸机服务器，则必须为每个角色配置一台裸机服务器（即，配置多台裸机服务器）。
====
+
. *可选：*单击 *显示高级* 以配置其他设置，例如指定 IP 地址、覆盖节点主机名或向节点添加 https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[标签] 或 https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[污点]。
+
[NOTE]
====
* *节点公共 IP* 和 *节点私有 IP* 字段可以接受单个地址或以逗号分隔的地址列表（例如：`10.0.0.5,2001:db8::1`）。
====
+
[NOTE]
.仅 IPv6 或双栈集群
====
* 在仅 IPv6 和双栈集群中，您应将节点的 *IPv6 地址* 指定为 *节点私有 IP*。
====
+
. 将屏幕上显示的命令复制到剪贴板。
. 使用您喜欢的外壳（如 PuTTy 或远程终端连接）登录到您的 Linux 主机。运行复制到剪贴板的命令。

[NOTE]
====
如果您想将特定主机分配给特定节点角色，请重复步骤 7-10。根据需要重复这些步骤。
====

*结果：*

集群已创建，并在 Rancher 初始化和配置集群组件时过渡到 *更新中* 状态。

在集群状态更新为*活动*后，您可以访问您的集群。

*活动*集群被分配两个项目：

* `Default`，包含`default`名称空间
* `System`，包含 `cattle-system`、`traefik`、`kube-public` 和 `kube-system` 名称空间

[#_3_amazon_only_tag_resources]
=== 3.仅限Amazon：标记资源

如果您已将集群配置为使用Amazon作为*云提供商*，请使用集群ID标记您的AWS资源。

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html[亚马逊文档：标记您的Amazon EC2资源]

[NOTE]
====

您可以在Kubernetes中使用Amazon EC2实例，而无需配置云提供商。只有在您想使用特定的Kubernetes云提供商功能时，才需要配置云提供商。有关更多信息，请参见 https://github.com/kubernetes/website/blob/release-1.18/content/en/docs/concepts/cluster-administration/cloud-providers.md[Kubernetes云提供商]。
====


以下资源需要标记为`ClusterID`：

* *节点*：在Rancher中添加的所有主机。
* *子网*：用于您的集群的子网。
* *安全组*：用于您的集群的安全组。

[NOTE]
====

请勿标记多个安全组。标记多个组在创建弹性负载均衡器时会生成错误。
====


应该使用的标签是：

----
Key=kubernetes.io/cluster/<CLUSTERID>, Value=owned
----

`<CLUSTERID>` 可以是您选择的任何字符串。然而，您标记的每个资源必须使用相同的字符串。将标签值设置为 `owned` 会通知集群，所有标记为 `<CLUSTERID>` 的资源均由该集群拥有和管理。

如果您在集群之间共享资源，可以将标签更改为：

----
Key=kubernetes.io/cluster/CLUSTERID, Value=shared
----

[#_optional_next_steps]
== 可选的后续步骤

创建集群后，您可以通过Rancher UI访问它。作为最佳实践，我们建议设置这些访问集群的替代方式：

* *使用kubectl CLI访问您的集群：*按照{xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[这些步骤]在您的工作站上使用kubectl访问集群。在这种情况下，您将通过Rancher服务器的身份验证代理进行身份验证，然后Rancher将连接您到下游集群。此方法允许您在没有Rancher UI的情况下管理集群。
* *使用授权的集群端点，通过kubectl CLI访问您的集群：*按照{xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[这些步骤]直接使用kubectl访问您的集群，而无需通过Rancher进行身份验证。我们建议设置这种替代方法来访问您的集群，以便在无法连接到Rancher的情况下，您仍然可以访问集群。
