= 备份、恢复和灾难恢复
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-13
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/index.adoc 
:product-path: rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.adoc
:experimental:
:keywords: ["rancher 备份 恢复", "rancher 备份和恢复", "备份 恢复 rancher", "rancher 备份和恢复 rancher"]
ifeval::["{build-type}" != "community"]
:xref-fleet-overview: xref:integrations/fleet/overview.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
:xref-backup-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/back-up.adoc
:xref-rancher-restore: xref:rancher-admin/back-up-restore-and-disaster-recovery/restore.adoc
:xref-rancher-backup-storage-config: xref:rancher-admin/back-up-restore-and-disaster-recovery/configuration/storage.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-fleet-overview: xref:integrations-in-rancher/fleet/overview.adoc
:xref-migrate-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster.adoc
:xref-backup-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher.adoc
:xref-rancher-restore: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher.adoc
:xref-rancher-backup-storage-config: xref:reference-guides/backup-restore-configuration/storage-configuration.adoc
endif::[]

在本节中，您将学习如何创建 Rancher 的备份，如何从备份中恢复 Rancher，以及如何将 Rancher 迁移到新的 Kubernetes 集群。

`rancher-backup` 操作符用于在任何 Kubernetes 集群上备份和恢复 Rancher。此应用程序是一个 Helm 图表，可以通过 Rancher *应用* 页面部署，或使用 Helm CLI 部署。`rancher-backup` Helm 图表是 https://github.com/rancher/charts/tree/release-v2.6/charts/rancher-backup[在这里。]

备份-恢复操作符需要在本地群集中安装，并且仅备份 Rancher APP。备份和恢复操作仅在本地 Kubernetes 集群中执行。

[#_backup_and_restore_for_rancher_installed_with_docker]
== 使用 Docker 安装的 Rancher 的备份和恢复

对于使用 Docker 安装的 Rancher，请参考 xref:[此页面] 进行备份，参考 xref:[此页面] 进行恢复。

[#_how_backups_and_restores_work]
== 备份和恢复的工作原理

`rancher-backup` 操作符引入了三个自定义资源：备份、恢复和资源集。以下集群范围的自定义资源定义已添加到集群中：

* `backups.resources.cattle.io`
* `resourcesets.resources.cattle.io`
* `restores.resources.cattle.io`

资源集定义了需要备份的 Kubernetes 资源。资源集无法在 Rancher UI 中配置，因为备份 Rancher 所需的值是预定义的。此资源集不应被修改。

当创建备份自定义资源时，`rancher-backup` 操作符调用 `kube-apiserver` 以获取备份自定义资源所引用的资源集中的资源。

操作员随后创建备份文件，格式为 .tar.gz，并将其存储在备份资源中配置的位置。

当创建恢复自定义资源时，操作员访问恢复指定的备份 .tar.gz 文件，并从该文件中恢复应用程序。

备份和恢复自定义资源可以在 Rancher UI 中创建，或使用 `kubectl apply`。

[NOTE]
====

有关在 Rancher v2.6.3 中将现有备份文件恢复到 v1.22 集群的帮助，请参阅 {xref-migrate-cluster}#_2_restore_from_backup_using_a_restore_custom_resource[这里]。
====


[#_installing_the_rancher_backup_operator]
== 安装 rancher-backup 操作符

可以通过 Rancher UI 或使用 Helm CLI 安装 `rancher-backup` 操作符。在这两种情况下，`rancher-backup` Helm 图表会安装在运行 Rancher 服务器的 Kubernetes 集群上。这是仅限集群管理员的功能，仅适用于本地群集。 (_如果您在 Rancher UI 中看不到 `rancher-backup`，您可能选择了错误的集群。_)

[NOTE]
====

在使用 backup-restore-operator 执行恢复后，Fleet 中存在一个已知问题：用于 clientSecretName 和 helmSecretName 的机密未包含在 Fleet gitrepos 中。有关解决方法，请参阅 {xref-fleet-overview}#_troubleshooting[{fleet-product-name} 故障排除]。
====


[#_installing_rancher_backup_with_the_rancher_ui]
=== 通过 Rancher UI 安装 rancher-backup

. 在左上角，点击 *☰ > 集群管理*。
. 在 *集群* 页面上，转到 `local` 集群并单击 *探索*。
. 在左侧导航栏中，menu:APP[图表]。
. 单击 *Rancher 备份*。
. 单击 *安装*。
. 可选：配置默认存储位置。如需帮助，请参阅 {xref-rancher-backup-storage-config}[配置部分。]
. 单击 *安装*。

*结果：*已安装 `rancher-backup` 操作符。

从 *集群仪表板*，您可以在 `rancher-backup` 操作符下看到 *部署*。

要在 Rancher 中配置备份 APP，请转到左侧导航菜单并点击 *Rancher Backups*。

[#_rbac]
=== RBAC

只有 Rancher 管理员和本地群集的群集所有者可以：

* 安装 Chart
* 查看备份和恢复 CRD 的导航链接
* 通过分别创建 Backup CR 和 Restore CR 执行备份或恢复
* 列出到目前为止执行的备份/恢复

[#_backing_up_rancher]
== 备份 Rancher

通过创建 Backup 自定义资源来执行备份。有关教程，请参阅 {xref-backup-cluster}[此页面。]

[#_restoring_rancher]
== 恢复 Rancher

通过创建 Restore 自定义资源来执行恢复。有关教程，请参阅 {xref-rancher-restore}[此页面。]

[#_migrating_rancher_to_a_new_cluster]
== 将 Rancher 迁移到新集群

迁移是通过遵循 {xref-migrate-cluster}[这些步骤。]来执行的。

[#_default_storage_location_configuration]
== 默认存储位置配置

为您的备份配置默认存储位置。有多种配置选项，例如指定 S3 兼容的对象存储作为单个备份的位置，或在安装 `backup-restore-operator` Helm chart 时选择现有的 `StorageClass`。您还可以选择在每次备份时覆盖配置的存储位置，但仅限于使用 S3 兼容或 Minio 对象存储。

有关配置这些选项的信息，请参阅 {xref-rancher-backup-storage-config}[此页面。]

[#_example_yaml_file_rancher_backup_helm_chart]
=== 示例 YAML 文件：Rancher 备份 Helm Chart

示例 {xref-rancher-backup-storage-config}#_example_yaml_file_rancher_backup_helm_chart[values.yaml 文件] 可用于在使用 Helm CLI 安装时配置 `backup-restore-operator`。
