= 恢复{rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-04
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher.adoc 
:product-path: rancher-admin/back-up-restore-and-disaster-recovery/restore.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:url-continuous-delivery-gitreo-add: https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-users/gitrepo-add.html#_backing_up_and_restoring
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
:xref-rancher-restore-config: xref:rancher-admin/back-up-restore-and-disaster-recovery/configuration/restore.adoc
:xref-back-restore-example-configs: xref:rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc
:xref-rancher-rollback: xref:installation-and-upgrade/rollbacks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-continuous-delivery-gitreo-add: https://fleet.rancher.io/{fleet-docs-version}/how-tos-for-users/gitrepo-add
:xref-migrate-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/迁移-Rancher到新集群.adoc
:xref-rancher-restore-config: xref:reference-guides/backup-restore-configuration/restore-configuration.adoc
:xref-back-restore-example-configs: xref:reference-guides/backup-restore-configuration/examples.adoc
:xref-rancher-rollback: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rollbacks.adoc
endif::[]

本页面概述了如何使用 Rancher 执行恢复。

在以下情况下，请遵循本页面的说明：

* 运行中的 Rancher 实例与备份时的版本相同。
* 上游（本地）集群与备份创建时的集群相同。

[NOTE]
.重要说明
====

在同一设置中恢复 Rancher 时，操作员将在恢复开始时缩减 Rancher 部署，并在恢复完成后重新扩展部署。在恢复期间，Rancher 将不可用。
====


[NOTE]
.Fleet 用户的警告
====
在恢复运行 Fleet 工作负载的 Rancher 设置时，您必须考虑如何处理 Kubernetes API 服务器的可用性和暂停的 GitRepos。有关更多详细信息，请参见{url-continuous-delivery-gitreo-add}[{fleet-product-name} 文档]。
====

[TIP]
====

* 按照这些步骤{xref-migrate-cluster}[迁移 Rancher]。
* 如果您在升级后需要将 Rancher 恢复到先前版本，请参见{xref-rancher-rollback}[回滚文档]。
====


[#_create_the_restore_custom_resource]
== 创建恢复自定义资源

恢复是通过创建恢复自定义资源来执行的。

. 在左上角，单击*☰ > 集群管理*。
. 在*集群*页面上，转到`local`集群并点击*浏览*。`local`集群运行 Rancher 服务器。
. 在左侧导航栏中，点击menu:Rancher 备份[恢复]。
. 单击*创建*。
. 使用表单或 YAML 创建恢复。 有关使用表单创建恢复资源的信息，请参阅{xref-rancher-restore-config}[配置参考]和{xref-back-restore-example-configs}[示例]。
. 要使用 YAML 编辑器，我们可以点击menu:创建[从 YAML 创建]。输入恢复 YAML。
+
[,yaml]
----
 apiVersion: resources.cattle.io/v1
 kind: Restore
 metadata:
   name: restore-migration
 spec:
   backupFilename: backup-b0450532-cee1-4aa1-a881-f5f48a007b1c-2020-09-15T07-27-09Z.tar.gz
   encryptionConfigSecretName: encryptionconfig
   storageLocation:
     s3:
       credentialSecretName: s3-creds
       credentialSecretNamespace: default
       bucketName: rancher-backups
       folder: rancher
       region: us-west-2
       endpoint: s3.us-west-2.amazonaws.com
----
+
有关配置恢复的帮助，请参阅 {xref-rancher-restore-config}[配置参考] 和 {xref-back-restore-example-configs}[示例]

. 单击*创建*。

*结果：*rancher-operator 在恢复期间缩减 rancher 部署，并在恢复完成后重新扩展部署。资源按以下顺序恢复：

. 自定义资源定义 (CRDs)
. 集群范围资源
. 命名空间资源

[#_logs]
== 日志

要检查恢复进度，可以查看操作员的日志。运行此命令以跟踪日志：

----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

[#_cleanup]
== 清理

如果您使用 kubectl 创建了恢复资源，请删除该资源以防止与未来的恢复发生命名冲突。

[#_known_issues]
== 已知问题

在某些情况下，恢复备份后，Rancher 日志将显示类似以下的错误：

----
2021/10/05 21:30:45 [ERROR] error syncing 'c-89d82/m-4067aa68dd78': handler rke-worker-upgrader: clusters.management.cattle.io "c-89d82" not found, requeuing
----

这发生是因为刚刚恢复的资源包含终结器，但相关资源已被删除，导致处理程序无法找到它。

要消除错误，我们需要找到并删除导致错误的资源。有关更多信息，请参见 https://github.com/rancher/rancher/issues/35050#issuecomment-937968556[这里]
