= ポッドセキュリティスタンダード (PSS) とポッドセキュリティアドミッション (PSA)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards.adoc 
:product-path: security/psa-pss.adoc
ifeval::["{build-type}" != "community"]
:xref-psact: xref:security/psact.adoc
:xref-sample-psact: xref:security/sample-psact.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-psact: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates.adoc
:xref-sample-psact: xref:reference-guides/rancher-security/psa-restricted-exemptions.adoc
endif::[]

https://kubernetes.io/docs/concepts/security/pod-security-standards/[ポッドセキュリティスタンダード (PSS)] と https://kubernetes.io/docs/concepts/security/pod-security-admission/[ポッドセキュリティアドミッション (PSA)] は、幅広いワークロードに対するセキュリティ制限を定義します。
これらはKubernetes v1.23で利用可能になり、デフォルトで有効になり、Kubernetes v1.25以降では https://kubernetes.io/docs/concepts/security/pod-security-policy/[ポッドセキュリティポリシー (PSP)] に置き換わります。

PSSはワークロードのためのセキュリティレベルを定義します。PSAはポッドセキュリティコンテキストおよび関連フィールドの要件を説明します。PSAはPSSレベルを参照してセキュリティ制限を定義します。

[#_pod_security_admission_configuration_templates]
== ポッドセキュリティアドミッション設定テンプレート

RancherはPSA設定テンプレートを提供します。これらはクラスターに適用できる事前定義されたセキュリティ設定です。Rancherの管理者（または適切な権限を持つ者）は、{xref-psact}[PSAテンプレートを作成、管理、編集]できます。

[#_rancher_on_psa_restricted_clusters]
=== PSA制限付きクラスター上のRancher

Rancherのシステムネームスペースも、PSAテンプレートによって説明される制限的なセキュリティポリシーの影響を受けます。テンプレートを割り当てた後、Rancherのシステムネームスペースを除外する必要があります。そうしないと、クラスターは正しく動作しません。詳細については、{xref-psact}#_exempting_required_rancher_namespaces[ポッドセキュリティアドミッション (PSA) 設定テンプレート]を参照してください。

Rancherを実行するために必要なすべての除外が含まれている完全なファイルについては、この {xref-sample-psact}[サンプルアドミッション設定]を参照してください。
