= Criando um Cluster GKE
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: procedimentos/novos-guias-para-usuários/cluster-kubernetes-no-rancher/configurar-clusters-a-partir-de-provedores-kubernetes-hospedados/gke.adoc 
:product-path: cluster-deployment/hosted-kubernetes/gke/gke.adoc
ifeval::["{build-type}" != "community"]
:xref-sync-hosted-clusters: xref:cluster-deployment/hosted-kubernetes/sync-clusters.adoc
:xref-gke-private-clusters: xref:cluster-deployment/hosted-kubernetes/gke/private-clusters.adoc
:xref-gke-config: xref:cluster-deployment/hosted-kubernetes/gke/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-sync-hosted-clusters: xref:reference-guides/cluster-configuration/rancher-server-configuration/sync-clusters.adoc
:xref-gke-private-clusters: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-gke/clusters-privados-gke.adoc
:xref-gke-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-gke/index.adoc
endif::[]

[#_prerequisites]
== Pré-requisitos

Algumas configurações no Google Kubernetes Engine são necessárias.

[#_service_account_token]
=== Token de Conta de Serviço

Crie uma conta de serviço usando https://console.cloud.google.com/projectselector/iam-admin/serviceaccounts[Google Kubernetes Engine]. O GKE usa esta conta para operar seu cluster. Criar esta conta também gera uma chave privada usada para autenticação.

A conta de serviço requer os seguintes papéis:

* *Visualizador de Computação:* `roles/compute.viewer`
* *Visualizador de Projeto:* `roles/viewer`
* *Administrador do Kubernetes Engine:* `roles/container.admin`
* *Usuário da Conta de Serviço:* `roles/iam.serviceAccountUser`

https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[Documentação do Google: Criando e Habilitando Contas de Serviço]

Para obter ajuda para obter uma chave privada para sua conta de serviço, consulte a documentação do Google Cloud https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys[aqui.] Você precisará salvar a chave no formato JSON.

[#_google_project_id]
=== ID do Projeto do Google

Seu cluster precisará fazer parte de um Projeto do Google.

Para criar um novo projeto, consulte a documentação do Google Cloud https://cloud.google.com/resource-manager/docs/creating-managing-projects#creating_a_project[aqui.]

Para obter o ID do projeto de um projeto existente, consulte a documentação do Google Cloud https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects[aqui.]

[#_provisioning_a_gke_cluster]
== Provisionando um Cluster GKE

[CAUTION]
====

Implantar no GKE incorrerá em cobranças.
====


[#_1_create_a_cloud_credential]
=== 1. Crie uma Credencial de Nuvem

. Clique em *☰ > Gerenciamento de Cluster*.
. No menu de navegação à esquerda, clique em *Credenciais de Nuvem*.
. Clique em *Criar*.
. Digite um nome para suas credenciais do Google Cloud.
. Na caixa de texto *Conta de Serviço*, cole sua chave privada JSON da conta de serviço ou faça o upload do arquivo JSON.
. Clique em *Criar*.

*Resultado:* Você criou credenciais que o Rancher usará para provisionar o novo cluster GKE.

[#_2_create_the_gke_cluster]
=== 2. Crie o Cluster GKE

Use o Rancher para configurar seu cluster Kubernetes. Para criar com sucesso um cluster GKE com o Rancher, seu GKE deve estar no modo Padrão. O GKE tem dois modos de operação ao criar um cluster Kubernetes, Modo Autopilot e Modo Padrão. A configuração do cluster para o modo Autopilot tem restrições na edição do namespace kube-system. No entanto, o Rancher precisa criar recursos no namespace kube-system durante a instalação. Como resultado, você não poderá criar um cluster GKE no modo Autopilot. Para mais informações sobre a diferença entre o modo Autopilot do GKE e o modo Padrão, visite https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison[Compare GKE Autopilot e Padrão.]

. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique em *Criar*.
. Click *Google GKE*.
. Digite um *Nome do Cluster*.
. Opcional: Use *Funções de Membro* para configurar a autorização de usuários para o cluster. Clique em *Adicionar Membro* para adicionar usuários que podem acessar o cluster. Use o menu suspenso *Função* para definir permissões para cada usuário.
. Opcional: Adicione https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[rótulos] ou https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/[anotações] ao cluster.
. Digite seu ID do projeto Google e suas credenciais do Google Cloud.
. Preencha o restante do formulário. Para ajuda, consulte a {xref-gke-config}[referência de configuração do cluster GKE.]
. Clique em *Criar*.

*Resultado:* Você implantou com sucesso um cluster GKE.

Seu cluster foi criado e atribuído ao estado de *Provisionamento*. O Rancher está configurando seu cluster.

Você pode acessar seu cluster após seu estado ser atualizado para *Ativo*.

Clusters *Ativos* são atribuídos a dois projetos:

* `Default`, contendo o namespace `default`
* `System`, contendo os namespaces `cattle-system`, `traefik`, `kube-public` e `kube-system`

[#_private_clusters]
== Clusters Privados

Clusters GKE privados são suportados. Nota: Essa configuração avançada pode exigir mais etapas durante o processo de provisionamento do cluster. Para detalhes, veja {xref-gke-private-clusters}[esta seção.]

[#_configuration_reference]
== Referência de configuração

Para detalhes sobre como configurar clusters GKE no Rancher, veja {xref-gke-config}[esta página.]

[#_updating_kubernetes_version]
== Atualizando a Versão do Kubernetes

É possível fazer upgrade da versão do Kubernetes de um cluster para qualquer versão disponível na região ou zona do cluster GKE. Fazer upgrade da versão do Kubernetes do master não atualiza automaticamente os nós de trabalho. É possível fazer upgrade dos nós de forma independente.

[NOTE]
====

O GKE removeu a autenticação básica na versão 1.19+. Para fazer upgrade de um cluster para 1.19+, a autenticação básica deve ser desativada no Google Cloud. Caso contrário, um erro aparecerá no Rancher quando um upgrade para 1.19+ for tentado. Você pode seguir a https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#disabling_authentication_with_a_static_password[documentação do Google]. Após isso, é possível fazer upgrade da versão do Kubernetes para 1.19+ via Rancher.
====


[#_syncing]
== Sincronizando

O provisionador GKE pode sincronizar o estado de um cluster GKE entre o Rancher e o provedor. Para uma explicação técnica detalhada de como isso funciona, veja {xref-sync-hosted-clusters}[Sincronizando.]

Para informações sobre como configurar o intervalo de atualização, veja {xref-gke-config}#_configurando_o_intervalo_de_atualização[esta seção.]

[#_programmatically_creating_gke_clusters]
== Criando Clusters GKE Programaticamente

A maneira mais comum de implantar clusters GKE programaticamente através do Rancher é usando o provedor Terraform Rancher2. A documentação para criar clusters com Terraform está https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster[aqui.]
