= Helm-Versionanforderungen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-21
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/helm-version-requirements.adoc 
:product-path: installation-and-upgrade/requirements/helm-version-requirements.adoc

Dieser Abschnitt enthält die Anforderungen für Helm, das Tool, das verwendet wird, um Rancher in einem hochverfügbaren Kubernetes-Cluster zu installieren.

[#_identifying_the_proper_helm_v3_version]
== Die richtige Helm v3-Version identifizieren

Wählen Sie eine beliebige Helm v3-Version aus, die offiziell mit dem Kubernetes-Versionsbereich kompatibel ist, den Sie aus unserer https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancher Support Matrix] verwenden.

Um diese Regel anzuwenden, müssen Sie möglicherweise auf zwei externe Ressourcen verweisen:

* *Kompatibilität der Helm-Version:* Verweisen Sie auf die https://helm.sh/docs/topics/version_skew/[Helm-Version-Support-Richtlinie] und wählen Sie die Version aus, die der Regel für Ihre Zielversion von Rancher entspricht.
* *Ranchers Kubernetes-Supportbereich:* Verwenden Sie die https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancher Support Matrix], um die Kubernetes-Versionen zu identifizieren, die von Ihrer Zielversion von Rancher unterstützt werden.

[#_example]
=== Beispiel

* *Szenario:* Sie zielen auf Rancher v2.11.4 ab, das die Kubernetes-Versionen 1.30 bis 1.32 unterstützt.
* *Anwendung:* Unsere Regel erfordert eine Helm-Version, die diesen Bereich unterstützt. Sie können dies überprüfen, indem Sie die Kompatibilität der Helm-Version mit der höchsten Version im Bereich, Kubernetes v1.32, feststellen.
* *Ergebnis:* Sie stellen fest, dass sowohl Helm v3.17 als auch Helm v3.18 den Kubernetes-Versionsbereich von v1.30 bis v1.32 unterstützen.
* Obwohl beide funktionieren, empfehlen wir Helm v3.18, da es die neueste Helm-Nebenversion ist, die mit dem unterstützten Kubernetes-Versionsbereich überlappt.

[#_additional_notes]
== Weitere Hinweise

* Helm v3.2.x oder höher ist erforderlich, um Rancher v2.5 zu installieren oder zu aktualisieren.
* Wenn Sie Tools verwenden, die Helm-Befehle für Sie ausführen (wie Terraform), müssen Sie sicherstellen, dass sie so konfiguriert sind, dass sie die richtige Helm-Version verwenden.
