= Installationsanforderungen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:product-path: installation-and-upgrade/requirements/requirements.adoc
:description: Lernen Sie die Anforderungen an die Knoten für jeden Knoten, der den Rancher-Server ausführt, wenn Sie Rancher für den Betrieb in einem Kubernetes-Setup konfigurieren.
ifeval::["{build-type}" != "community"]
:url-k3s-advanced-docker-runtime: https://documentation.suse.com/cloudnative/k3s/latest/en/advanced.html#_using_docker_as_the_container_runtime
:url-rke2-requirements: https://documentation.suse.com/cloudnative/rke2/latest/en/install/requirements.html
:url-k3s-datastore: https://documentation.suse.com/cloudnative/k3s/latest/en/datastore/datastore.html
:url-k3s-requirements: https://documentation.suse.com/cloudnative/k3s/latest/en/installation/requirements.html
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
:xref-psact: xref:security/psact.adoc
:xref-rancher-on-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
:xref-tuning-rancher-at-scale: xref:installation-and-upgrade/best-practices/tuning-rancher-at-scale.adoc
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-rancher-on-arm64: xref:rancher-admin/experimental-features/rancher-on-arm64.adoc
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc
:xref-dual-stack: xref:cluster-deployment/dual-stack.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-advanced-docker-runtime: https://docs.k3s.io/advanced#using-docker-as-the-container-runtime
:url-rke2-requirements: https://docs.rke2.io/install/requirements
:url-k3s-datastore: https://docs.k3s.io/datastore
:url-k3s-requirements: https://docs.k3s.io/installation/requirements
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-rancher-on-aks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-aks.adoc
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
:xref-psact: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates.adoc
:xref-rancher-on-eks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks.adoc
:xref-tuning-rancher-at-scale: xref:reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.adoc
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-rancher-on-arm64: xref:how-to-guides/advanced-user-guides/enable-experimental-features/rancher-on-arm64.adoc
:xref-rancher-on-gke: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke.adoc
:xref-dual-stack: xref:reference-guides/dual-stack.adoc
endif::[]

Diese Seite beschreibt die Software-, Hardware- und Netzwerkanforderungen für die Knoten, auf denen der Rancher-Server installiert wird. Der Rancher-Server kann auf einem einzelnen Knoten oder einem Kubernetes-Cluster mit hoher Verfügbarkeit installiert werden.

[NOTE]
.Wichtig:
====

Wenn Sie Rancher auf einem Kubernetes-Cluster installieren, sind die Anforderungen anders als die {xref-node-reqs}[Knotenanforderungen für Downstream-Benutzercluster], die Ihre Apps und Dienste ausführen werden.
====


Die Rancher-Benutzeroberfläche funktioniert am besten in Firefox oder Chromium-basierten Browsern (Chrome, Edge, Opera, Brave usw.).

Siehe unsere Seite über {xref-tips-for-running-rancher}[Best Practices] für eine Liste von Empfehlungen zum Betrieb eines Rancher-Servers in der Produktion.

[#_kubernetes_compatibility_with_rancher]
== Kubernetes-Kompatibilität mit Rancher

Rancher muss auf einer unterstützten Kubernetes-Version installiert werden. Konsultieren Sie die https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancher-Supportmatrix], um sicherzustellen, dass Ihre beabsichtigte Version von Kubernetes unterstützt wird.

Unabhängig von Version und Distribution muss der Kubernetes-Cluster die Aggregation-API-Schicht ordnungsgemäß konfiguriert haben, um die xref:api/extension-apiserver.adoc[Erweiterung-API] zu unterstützen, die von Rancher verwendet wird.

[#_install_rancher_on_a_hardened_kubernetes_cluster]
=== Installieren Sie Rancher auf einem gehärteten Kubernetes-Cluster

Wenn Sie Rancher auf einem gehärteten Kubernetes-Cluster installieren, überprüfen Sie den Abschnitt {xref-psact}#_exempting_required_rancher_namespaces[Ausnahme erforderlicher Rancher-Namespaces] auf detaillierte Anforderungen.

[#_install_rancher_on_an_ipv6_only_or_dual_stack_kubernetes_cluster]
=== Installieren Sie Rancher auf einem IPv6- oder Dual-Stack-Kubernetes-Cluster.

Sie können Rancher auf einem IPv6- oder Dual-Stack-Kubernetes-Cluster bereitstellen.

Für Details zur IPv6- und Dual-Stack-Unterstützung von Rancher siehe die {xref-dual-stack}[IPv4/IPv6-Dual-Stack]-Seite.

[#_operating_systems_and_container_runtime_requirements]
== Betriebssysteme und Anforderungen an die Container-Laufzeit

Alle unterstützten Betriebssysteme sind 64-Bit x86. Rancher sollte mit jeder modernen Linux-Distribution funktionieren.

Die https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancher-Supportmatrix] listet auf, welche Betriebssystem- und Docker-Versionen für jede Rancher-Version getestet wurden.

Docker ist erforderlich für Knoten, die RKE-Cluster ausführen werden. Es ist nicht erforderlich für RKE2- oder K3s-Cluster.

Das `ntp` (Network Time Protocol)-Paket sollte installiert sein. Dies verhindert Fehler bei der Zertifikatsvalidierung, die auftreten können, wenn die Zeit zwischen Client und Server nicht synchronisiert ist.

Einige Linux-Distributionen haben möglicherweise standardmäßig Firewall-Regeln, die die Kommunikation innerhalb des Kubernetes-Clusters blockieren. Seit Kubernetes v1.19 muss firewalld deaktiviert sein, da es mit den Kubernetes-Netzwerk-Plugins in Konflikt steht.

Wenn Sie sich dabei nicht wohlfühlen, können Sie die Vorschläge im https://github.com/rancher/rancher/issues/28840[entsprechenden Problem] überprüfen. Einige Benutzer hatten Erfolg https://github.com/rancher/rancher/issues/28840#issuecomment-787404822[eine separate firewalld-Zone mit einer Richtlinie von ACCEPT für den Pod CIDR zu erstellen].

Wenn Sie planen, Rancher auf ARM64 auszuführen, siehe {xref-rancher-on-arm64}[Ausführen auf ARM64 (experimentell)].

[#__rke2_product_name_specific_requirements]
=== {rke2-product-name} Spezifische Anforderungen

RKE2 bündelt seine eigene Container-Laufzeit, containerd.

Für Details, welche Betriebssystemversionen mit RKE2 getestet wurden, siehe die https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancher-Supportmatrix].

[#__k3s_product_name_specific_requirements]
=== {k3s-product-name} Spezifische Anforderungen

Für die Container-Laufzeit bündelt K3s standardmäßig sein eigenes containerd. Alternativ können Sie K3s so konfigurieren, dass es eine bereits installierte Docker-Laufzeit verwendet. Für weitere Informationen zur Verwendung von K3s mit Docker siehe die {url-k3s-advanced-docker-runtime}[K3s-Dokumentation.]

Rancher muss auf einer unterstützten Kubernetes-Version installiert werden. Um herauszufinden, welche Versionen von Kubernetes für Ihre Rancher-Version unterstützt werden, beziehen Sie sich auf die https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancher-Supportmatrix]. Um die K3s-Version anzugeben, verwenden Sie die Umgebungsvariable INSTALL_K3S_VERSION, wenn Sie das K3s-Installationsskript ausführen.

Wenn Sie Rancher in einem K3s-Cluster mit *Raspbian Buster* installieren, folgen Sie https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster[diesen Schritten], um zu Legacy-iptables zu wechseln.

Wenn Sie Rancher in einem K3s-Cluster mit Alpine Linux installieren, folgen Sie https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup[diesen Schritten] für zusätzliche Einstellungen.

[#_hardware_requirements]
== Hardwareanforderungen

Die folgenden Abschnitte beschreiben die CPU-, Speicher- und I/O-Anforderungen für Knoten, auf denen Rancher installiert ist. Die Anforderungen variieren je nach Größe der Infrastruktur.

[#_practical_considerations]
=== Praktische Überlegungen

Der Hardwarebedarf von Rancher hängt von einer Reihe von Faktoren ab, einschließlich:

* Größe der verwalteten Infrastruktur (z. B. Anzahl der Knoten, Anzahl der Cluster).
* Komplexität der gewünschten Zugriffskontrollregeln (z. B. `RoleBinding` Objektanzahl).
* Anzahl der Workloads (z. B. Kubernetes-Deployments, Fleet-Deployments).
* Nutzungsmuster (z. B. Teilmenge der aktiv verwendeten Funktionalität, Häufigkeit der Nutzung, Anzahl der gleichzeitigen Benutzer).

Da es eine hohe Anzahl von Einflussfaktoren gibt, die sich im Laufe der Zeit ändern können, sollten die hier aufgeführten Anforderungen als angemessene Ausgangspunkte verstanden werden, die für die meisten Anwendungsfälle gut funktionieren. Dennoch kann Ihr Anwendungsfall andere Anforderungen haben. Für Anfragen zu einem bestimmten Szenario wenden Sie sich bitte https://rancher.com/contact/[an Rancher] für weitere Hinweise.

Insbesondere unterliegen die Anforderungen auf dieser Seite typischen Nutzungsvoraussetzungen, die Folgendes umfassen:

* Unter 60.000 insgesamt Kubernetes-Ressourcen pro Typ.
* Bis zu 120 Pods pro Knoten.
* Bis zu 200 CRDs im upstream (lokalen) Cluster.
* Bis zu 100 CRDs in downstream Clustern.
* Bis zu 50 Fleet-Implementierungen.

Höhere Zahlen sind möglich, aber die Anforderungen könnten höher sein. Wenn Sie mehr als 20.000 Ressourcen desselben Typs haben, kann die Ladezeit der gesamten Liste über die Rancher UI mehrere Sekunden in Anspruch nehmen.

[NOTE]
.Evolution:
====

Der Code von Rancher entwickelt sich weiter, Anwendungsfälle ändern sich, und das Wissen über Rancher wächst jeden Tag.

Die Empfehlungen für Hardwareanforderungen können sich im Laufe der Zeit ändern, da die Richtlinien an Genauigkeit gewinnen und konkreter werden.

Wenn Sie feststellen, dass Ihre Rancher-Bereitstellung nicht mehr den aufgeführten Empfehlungen entspricht, https://rancher.com/contact/[kontaktieren Sie Rancher] für eine Neubewertung.
====


[#__rke2_product_name_kubernetes]
=== {rke2-product-name} Kubernetes

Die folgende Tabelle listet die minimalen CPU- und Speicheranforderungen für jeden Knoten im {xref-install-rancher}[Upstream-Cluster] auf.

Bitte beachten Sie, dass für die Produktion eine hochverfügbare Konfiguration mit mindestens drei Knoten erforderlich ist.

|===
| Größe der verwalteten Infrastruktur | Maximale Anzahl von Clustern | Maximale Anzahl von Knoten | vCPUs | RAM

| Small
| 150
| 1500
| 4
| 16 GB

| Mittel
| 300
| 3000
| 8
| 32 GB

| Groß (*)
| 500
| 5.000
| 16
| 64 GB

| Größer (†)
| (†)
| (†)
| (†)
| (†)
|===

(*): Große Implementierungen erfordern, dass Sie {xref-tuning-rancher-at-scale}[beste Praktiken befolgen] für eine angemessene Leistung.

(†): Größere Implementierungsgrößen sind im Allgemeinen mit ad-hoc Hardwareempfehlungen und Anpassungen möglich. Sie können https://rancher.com/contact/[Rancher kontaktieren] für eine individuelle Bewertung.

Bitte beziehen Sie sich auf die RKE2-Dokumentation für detailliertere Informationen zu {url-rke2-requirements}[RKE2 allgemeinen Anforderungen].

[#__k3s_product_name_kubernetes]
=== {k3s-product-name} Kubernetes

Die folgende Tabelle listet die minimalen CPU- und Speicheranforderungen für jeden Knoten im {xref-install-rancher}[upstream-Cluster] auf.

Bitte beachten Sie, dass für die Produktion eine hochverfügbare Konfiguration mit mindestens drei Knoten erforderlich ist.

|===
| Größe der verwalteten Infrastruktur | Maximale Anzahl von Clustern | Maximale Anzahl von Knoten | vCPUs | RAM | Externer Datenbank-Host (*)

| Small
| 150
| 1500
| 4
| 16 GB
| 2 vCPUs, 8 GB + 1000 IOPS

| Mittel
| 300
| 3000
| 8
| 32 GB
| 4 vCPUs, 16 GB + 2000 IOPS

| Groß (†)
| 500
| 5.000
| 16
| 64 GB
| 8 vCPUs, 32 GB + 4000 IOPS
|===

(*): Der externe Datenbank-Host bezieht sich auf das Hosting des K3s-Cluster-Datenspeichers auf einem {url-k3s-datastore}[dedizierten externen Host]. Diese Einstellung ist optional. Die genauen Anforderungen hängen vom externen Datenspeicher ab.

(†): Große Implementierungen erfordern, dass Sie {xref-tuning-rancher-at-scale}[beste Praktiken befolgen] für eine angemessene Leistung.

Bitte beziehen Sie sich auf die K3s-Dokumentation für detailliertere Informationen zu {url-k3s-requirements}[allgemeinen Anforderungen].

[#_hosted_kubernetes]
=== Gehostetes Kubernetes

Die folgende Tabelle listet die minimalen CPU- und Speicheranforderungen für jeden Knoten im {xref-install-rancher}[Upstream-Cluster] auf.

Bitte beachten Sie, dass für die Produktion eine hochverfügbare Konfiguration mit mindestens drei Knoten erforderlich ist.

Diese Anforderungen gelten für gehostete Kubernetes-Cluster wie Amazon Elastic Kubernetes Service (EKS), Azure Kubernetes Service (AKS) oder Google Kubernetes Engine (GKE). Sie gelten nicht für Rancher SaaS-Lösungen wie https://www.rancher.com/products/rancher[Rancher Prime Hosted].

|===
| Größe der verwalteten Infrastruktur | Maximale Anzahl von Clustern | Maximale Anzahl von Knoten | vCPUs | RAM

| Small
| 150
| 1500
| 4
| 16 GB

| Mittel
| 300
| 3000
| 8
| 32 GB

| Groß (*)
| 500
| 5.000
| 16
| 64 GB
|===

(*): Große Implementierungen erfordern, dass Sie {xref-tuning-rancher-at-scale}[beste Praktiken befolgen] für eine angemessene Leistung.

ifeval::["{build-type}" == "community"]

[#_docker]
=== Docker

Die folgende Tabelle listet die minimalen CPU- und Speicheranforderungen für eine xref:[einzelne Docker-Knoteninstallation von Rancher] auf.

Bitte beachten Sie, dass eine Docker-Installation nur für Entwicklungs- oder Testzwecke geeignet ist und nicht für den Einsatz in Produktionsumgebungen gedacht ist.

|===
| Größe der verwalteten Infrastruktur | Maximale Anzahl von Clustern | Maximale Anzahl von Knoten | vCPUs | RAM

| Small
| 5
| 50
| 1
| 4 GB

| Mittel
| 15
| 200
| 2
| 8 GB
|===

endif::[]

[#_ingress]
== Ingress

Jeder Knoten im Kubernetes-Cluster, auf dem Rancher installiert ist, sollte einen Ingress ausführen.

Der Ingress sollte als DaemonSet bereitgestellt werden, um sicherzustellen, dass Ihr Lastenausgleich den Datenverkehr erfolgreich an alle Knoten weiterleiten kann.

Für RKE2- und K3s-Installationen müssen Sie den Ingress nicht manuell installieren, da er standardmäßig installiert wird.

Für gehostete Kubernetes-Cluster (EKS, GKE, AKS) müssen Sie den Ingress einrichten.

* *Amazon EKS:* Für Details zur Installation von Rancher auf Amazon EKS, einschließlich der Installation eines Ingress, damit der Rancher-Server zugänglich ist, siehe {xref-rancher-on-eks}[diese Seite.]
* *AKS:* Für Details zur Installation von Rancher mit Azure Kubernetes Service, einschließlich der Installation eines Ingress, damit der Rancher-Server zugänglich ist, siehe {xref-rancher-on-aks}[diese Seite.]
* *GKE:* Für Details zur Installation von Rancher mit Google Kubernetes Engine, einschließlich der Installation eines Ingress, damit der Rancher-Server zugänglich ist, siehe {xref-rancher-on-gke}[diese Seite.]

[#_disks]
== Festplatten

Die Leistung von Rancher hängt von der Leistung von etcd im Cluster ab. Um optimale Geschwindigkeit zu gewährleisten, empfehlen wir, immer SSD-Festplatten für Ihren Rancher-Management-Kubernetes-Cluster zu verwenden. Bei Cloud-Anbietern sollten Sie auch die minimale Größe verwenden, die die maximale IOPS ermöglicht. In größeren Clustern sollten Sie in Betracht ziehen, dedizierte Speichergeräte für etcd-Daten und wal-Verzeichnisse zu verwenden.

[#_networking_requirements]
== Netzwerkanforderungen

Dieser Abschnitt beschreibt die Netzwerkanforderungen für die Knoten, auf denen der Rancher-Server installiert ist.

[CAUTION]
====

Wenn ein Server, der Rancher enthält, den `X-Frame-Options=DENY` Header hat, können einige Seiten in der neuen Rancher-Benutzeroberfläche nach dem Upgrade von der alten Benutzeroberfläche nicht gerendert werden. Das liegt daran, dass einige alte Seiten als iFrames in der neuen Benutzeroberfläche eingebettet sind.
====


[#_node_ip_addresses]
=== Knoten-IP-Adressen

Jeder verwendete Knoten sollte eine statische IP konfiguriert haben, unabhängig davon, ob Sie Rancher auf einem einzelnen Knoten oder auf einem HA-Cluster installieren. Im Falle von DHCP sollte jeder Knoten eine DHCP-Reservierung haben, um sicherzustellen, dass der Knoten die gleiche IP zugewiesen bekommt.

[#_port_requirements]
=== Portanforderungen

Um ordnungsgemäß zu funktionieren, benötigt Rancher eine Reihe von offenen Ports auf den Rancher-Knoten und auf den Downstream-Kubernetes-Cluster-Knoten. {xref-port-reqs}[Portanforderungen] listet alle notwendigen Ports für Rancher und Downstream-Cluster für die verschiedenen Clustertypen auf.

[#_load_balancer_requirements]
=== Lastenausgleichsanforderungen

Wenn Sie einen Lastenausgleich verwenden, sollte dieser HTTP/2-kompatibel sein.

Um Hilfe von SUSE Support zu erhalten, müssen Rancher Prime-Kunden, die Lastenausgleich verwenden (oder andere Mittel wie Firewalls), einen verwenden, der HTTP/2-kompatibel ist.

Wenn HTTP/2 nicht verfügbar ist, fällt Rancher auf HTTP/1.1 zurück. Da HTTP/2 jedoch eine verbesserte Leistung von Webanwendungen bietet, kann die Verwendung von HTTP/1.1 Leistungsprobleme verursachen.
