= Installation von {rancher-product-name} auf Amazon EKS
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-09
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-qs-aws-marketplace: xref:installation-and-upgrade/quick-start/deploy-rancher/aws-marketplace.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-qs-aws-marketplace: xref:getting-started/quick-start-guides/deploy-rancher-manager/aws-marketplace.adoc
endif::[]

Diese Seite behandelt die Installation von Rancher auf einem Amazon EKS-Cluster.  Sie können auch {xref-qs-aws-marketplace}[Rancher über den AWS Marketplace installieren].

Wenn Sie bereits einen EKS Kubernetes-Cluster haben, überspringen Sie den Schritt zur <<_5_install_an_ingress,Installation eines Ingress.>> Installieren Sie dann das Rancher Helm-Chart, indem Sie die Anweisungen auf {xref-install-rancher}#_install_the_rancher_helm_chart[diese Seite] befolgen.

[#_creating_an_eks_cluster_for_the_rancher_server]
== Erstellen eines EKS-Clusters für den Rancher-Server

In diesem Abschnitt installieren Sie einen EKS-Cluster mit einem Ingress, indem Sie Kommandozeilenwerkzeuge verwenden. Dieser Leitfaden kann nützlich sein, wenn Sie weniger Ressourcen verwenden möchten, während Sie Rancher auf EKS ausprobieren.

[NOTE]
.Voraussetzungen:
====

* Sie sollten bereits ein AWS-Konto haben.
* Es wird empfohlen, einen IAM-Benutzer anstelle des Root-AWS-Kontos zu verwenden. Sie benötigen den Zugriffsschlüssel und den geheimen Schlüssel des IAM-Benutzers, um die AWS-Befehlszeilenschnittstelle zu konfigurieren.
* Der IAM-Benutzer benötigt die minimalen IAM-Richtlinien, die in der offiziellen https://eksctl.io/usage/minimum-iam-policies/[eksctl-Dokumentation.] beschrieben sind.
====


[#_1_prepare_your_workstation]
=== 1. Bereiten Sie Ihre Arbeitsstation vor

Installieren Sie die folgenden Befehlszeilenwerkzeuge auf Ihrer Arbeitsstation:

* *The AWS CLI v2:* Für Hilfe beziehen Sie sich auf diese https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html[Installationsschritte.]
* *eksctl:* Für Hilfe beziehen Sie sich auf diese https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html[Installationsschritte.]
* *kubectl:* Für Hilfe beziehen Sie sich auf diese https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html[Installationsschritte.]
* *helm:* Für Hilfe beziehen Sie sich auf diese https://helm.sh/docs/intro/install/[Installationsschritte.]

[#_2_configure_the_aws_cli]
=== 2. Konfigurieren Sie die AWS CLI

Um die AWS CLI zu konfigurieren, führen Sie den folgenden Befehl aus:

----
aws configure
----

Geben Sie dann die folgenden Werte ein:

|===
| Wert | Beschreibung

| AWS Zugriffsschlüssel-ID
| Die Zugriffsschlüsselberechtigung für den IAM-Benutzer mit EKS-Berechtigungen.

| AWS geheimer Zugriffsschlüssel
| Der geheime Schlüssel für den IAM-Benutzer mit EKS-Berechtigungen.

| Standardregionname
| Eine https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html#Concepts.RegionsAndAvailabilityZones.Regions[AWS-Region], in der sich die Clusterknoten befinden.

| Standardausgabeformat
| Öffnen Sie die Datei `json`.
|===

[#_3_create_the_eks_cluster]
=== 3. Erstellen Sie den EKS-Cluster

Um einen EKS-Cluster zu erstellen, führen Sie den folgenden Befehl aus. Verwenden Sie die AWS-Region, die für Ihren Anwendungsfall zutrifft. Wenn Sie eine Kubernetes-Version auswählen, konsultieren Sie zuerst die https://rancher.com/support-matrix/[Supportmatrix], um die höchste Kubernetes-Version zu finden, die für Ihre Rancher-Version validiert wurde.

----
eksctl create cluster \
  --name rancher-server \
  --version <VERSION> \
  --region us-west-2 \
  --nodegroup-name ranchernodes \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
----

Der Cluster benötigt einige Zeit, um mit CloudFormation bereitgestellt zu werden.

[#_4_test_the_cluster]
=== 4. Testen Sie den Cluster

Um den Cluster zu testen, führen Sie aus:

----
eksctl get cluster
----

Das Ergebnis sollte folgendermaßen aussehen:

----
eksctl get cluster
2021-03-18 15:09:35 [ℹ]  eksctl version 0.40.0
2021-03-18 15:09:35 [ℹ]  using region us-west-2
NAME        REGION        EKSCTL CREATED
rancher-server-cluster        us-west-2    True
----

[#_5_install_an_ingress]
=== 5. Installieren Sie ein Ingress

Der Cluster benötigt ein Ingress, damit Rancher von außerhalb des Clusters zugänglich ist. Die Installation eines Ingress erfordert die Zuweisung einer öffentlichen IP-Adresse. Stellen Sie sicher, dass Sie über genügend Kontingent verfügen, andernfalls wird die Zuweisung der IP-Adresse fehlschlagen. Die Grenzen für öffentliche IP-Adressen gelten auf regionaler Ebene pro Abonnement. Sie können einen verwalteten Ingress-Controller von AWS (ALB) oder einen Drittanbieter-Ingress-Controller wie Traefik verwenden.

[WARNING]
====
Es wird nicht empfohlen, einen Drittanbieter-Ingress-Controller wie Traefik zu installieren, wenn bereits ein verwalteter Ingress-Controller verwendet wird.
====

[WARNING]
====
**Ingress-NGINX EOL:** Der Community-`ingress-nginx`-Controller erreicht im März 2026 das Ende seiner Lebensdauer (EOL). Diese Seite verwendet Traefik, das der empfohlene Migrationspfad für Rancher-Umgebungen ist.
====

Traefik enthält einen nativen Ingress-NGINX-Anbieter. Dies ermöglicht es Ihnen, von NGINX zu migrieren, ohne Ihre vorhandenen Ingress-Objekte umzuschreiben, da Traefik automatisch `nginx.ingress.kubernetes.io`-Annotationen interpretiert. Wenn Sie ein Cluster aktualisieren, das bereits `ingress-nginx` verwendet, folgen Sie diesem https://doc.traefik.io/traefik/migrate/nginx-to-traefik/[Leitfaden] für weitere Informationen.

Um Traefik zu installieren, empfehlen wir dringend, die Traefik-Anwendung in der https://apps.rancher.io/applications/traefik-proxy[Rancher Prime Application Collection] zu verwenden. Überprüfen Sie deren https://docs.apps.rancher.io/howto-guides/integrate-with-rancher-manager[Dokumentation zur Integration mit Rancher Manager].


[#_6_get_load_balancer_ip]
=== 6. IP des Load Balancers abrufen.

Um die Adresse des Load Balancers zu erhalten, führen Sie Folgendes aus:

----
kubectl get service traefik --namespace=traefik
----

Das Ergebnis sollte wie folgt aussehen:

----
NAME                       TYPE           CLUSTER-IP     EXTERNAL-IP                                                              PORT(S)
 AGE
traefik  LoadBalancer   10.0.116.18    40.31.180.83   80:31229/TCP,443:31050/TCP 27m
----

Speichern Sie die `EXTERNAL-IP`.

[#_7_set_up_dns]
=== 7. DNS einrichten.

Der externe Verkehr zum Rancher-Server muss an den von Ihnen erstellten Load Balancer gerichtet werden.

Richten Sie ein DNS ein, das auf die externe IP zeigt, die Sie gespeichert haben. Dieses DNS wird als URL des Rancher-Servers verwendet.

Es gibt viele gültige Möglichkeiten, das DNS einzurichten. Für Hilfe, siehe die AWS-Dokumentation zu https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html[dem Routing des Datenverkehrs zu einem ELB Load Balancer.]

[#_8_install_the_rancher_helm_chart]
=== 8. Installieren Sie das Rancher Helm Chart.

Installieren Sie als Nächstes das Rancher Helm-Chart, indem Sie die Anweisungen auf {xref-install-rancher}#_install_the_rancher_helm_chart[diese Seite.] befolgen. Die Helm-Anweisungen sind für die Installation von Rancher auf jeder Kubernetes-Distribution gleich.

Verwenden Sie den DNS-Namen aus dem vorherigen Schritt als die Rancher-Server-URL, wenn Sie Rancher installieren. Es kann als Helm-Option übergeben werden. Wenn der DNS-Name beispielsweise `rancher.my.org` ist, könnten Sie den Helm-Installationsbefehl mit der Option `--set hostname=rancher.my.org` ausführen.

Beim Installieren von Rancher auf dieser Konfiguration müssen Sie auch den untenstehenden Wert in den Rancher Helm-Installationsbefehl übergeben, um den Namen des Ingress-Controllers festzulegen, der mit der Ingress-Ressource von Rancher verwendet werden soll:

----
--set ingress.ingressClassName=traefik
----

Siehe {xref-install-rancher}#_5_install_rancher_with_helm_and_your_chosen_certificate_option[hier für den Helm-Installationsbefehl] für Ihre gewählte Zertifikatsoption.
