= クラスターオートスケーラー
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}

このセクションでは、AWS EC2 Auto Scaling Groupsを使用してRancherカスタムクラスターに https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/[Kubernetesクラスターオートスケーラー]をインストールして使用する方法を学びます。

クラスターオートスケーラーは、次のいずれかの場合にKubernetesクラスターのサイズを自動的に調整するツールです。

* リソース不足のためにクラスター内で実行に失敗したポッドがあります。
* クラスター内に長期間過小利用されているノードがあり、そのポッドは他の既存のノードに配置できます。

ポッドが追い出されないようにするには、ポッド仕様に`priorityClassName: system-cluster-critical`プロパティを設定してください。

クラスターオートスケーラーはKubernetesマスターノードで実行されるように設計されています。`kube-system`ネームスペースで実行できます。クラスターオートスケーラーは、非ミラーの`kube-system`ポッドが稼働しているノードをスケールダウンしません。

クラスターオートスケーラーのカスタマイズされたデプロイメントをワーカーノードで実行することは可能ですが、クラスターオートスケーラーが稼働し続けることを確実にするために特別な注意が必要です。

[#_cloud_providers]
== クラウドプロバイダ

クラスターオートスケーラーは、異なるクラウドプロバイダーをサポートしています。詳細については、 https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#deployment[クラスターオートスケーラーがサポートするクラウドプロバイダー]をご覧ください。

[#_setting_up_cluster_autoscaler_on_amazon_cloud_provider]
=== Amazon Cloud Providerでのクラスターオートスケーラーの設定

Amazonクラウドプロバイダーでクラスターオートスケーラーを実行する詳細については、xref:cluster-admin/manage-clusters/install-cluster-autoscaler/use-aws-ec2-auto-scaling-groups.adoc[このページ]を参照してください。
