= NFS Storage
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/nfs-storage.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/examples/nfs-storage.adoc
ifeval::["{build-type}" != "community"]
:xref-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/manage-persistent-storage.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-persistent-storage: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/index.adoc
endif::[]

RancherデプロイメントでNFSストレージボリュームプラグインを使用する前に、NFSサーバーを用意する必要があります。

[NOTE]
====

* すでにNFS共有がある場合は、Rancher内でNFSボリュームプラグインを使用するために新しいNFSサーバーを用意する必要はありません。代わりに、この手順の残りをスキップし、{xref-persistent-storage}[ストレージの追加]を完了してください。
* この手順では、Ubuntuを使用してNFSサーバーを設定する方法を示しますが、他のLinux配布パッケージ（例：Debian、RHEL、Arch Linuxなど）でもこれらの指示を使用できるはずです。他のLinux配布パッケージを使用してNFSサーバーを作成する方法についての公式な指示については、その配布パッケージのドキュメントを参照してください。
====


[NOTE]
.推奨:
====

ファイアウォールルールの管理を簡素化するために、NFSv4を使用してください。
====


. リモートターミナル接続を使用して、NFSストレージに使用するUbuntuサーバーにログインします。
. 次のコマンドを入力します。
+
----
 sudo apt-get install nfs-kernel-server
----

. 以下のコマンドを入力し、ストレージに使用するディレクトリとアクセス権を設定します。ストレージを別のディレクトリに保持したい場合は、コマンドを修正してください。
+
----
 mkdir -p /nfs && chown nobody:nogroup /nfs
----

 ** `-p /nfs`パラメータは、ルートに`nfs`という名前のディレクトリを作成します。
 ** `chown nobody:nogroup /nfs`パラメータは、ストレージディレクトリへのすべてのアクセスを許可します。

. NFSエクスポートテーブルを作成します。このテーブルは、NFSサーバー上のディレクトリパスを、サーバーをストレージとして使用するノードに公開するために設定します。
 .. お好みのテキストエディタを使用して`/etc/exports`を開きます。
 .. ステップ3で作成した`/nfs`フォルダのパスと、クラスターのノードのIPアドレスを追加します。クラスター内の各IPアドレスのエントリを追加します。各アドレスとその付随するパラメータの後に、区切りとして単一のスペースを付けます。
+
----
 /nfs <IP_ADDRESS1>(rw,sync,no_subtree_check) <IP_ADDRESS2>(rw,sync,no_subtree_check) <IP_ADDRESS3>(rw,sync,no_subtree_check)
----
+

[TIP]
====
IPアドレスをサブネットに置き換えることができます。次に例を示します。`10.212.50.12&#47;24`
====


 .. 次のコマンドを入力してNFSテーブルを更新します:
+
----
 exportfs -ra
----
. NFSで使用されるポートを開きます。
 .. NFSが使用しているポートを確認するには、以下のコマンドを入力してください:
+
----
 rpcinfo -p | grep nfs
----

 .. 前のコマンドが出力する https://help.ubuntu.com/lts/serverguide/firewall.html.en[ポートを開く]を開放してください。たとえば、以下のコマンドはポート2049を開きます:
+
----
 sudo ufw allow 2049
----

*結果:*あなたのNFSサーバーは、Rancherノードでストレージとして使用するように設定されています。

[#_whats_next]
== 次は何ですか？

Rancher内で、NFSサーバーをストレージボリュームおよび/またはストレージクラスとして追加します。サーバーを追加した後、デプロイメント用のストレージとして使用できます。
