= Configuración de clusters de proveedores de Kubernetes alojados
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configuración-de-clusters-de-proveedores-de-kubernetes-alojados/index.adoc 
:product-path: cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
ifeval::["{build-type}" != "community"]
:xref-deploy-gke: xref:cluster-deployment/hosted-kubernetes/gke/gke.adoc
:xref-deploy-eks: xref:cluster-deployment/hosted-kubernetes/eks/eks.adoc
:xref-deploy-aks: xref:cluster-deployment/hosted-kubernetes/aks/aks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-deploy-gke: xref:instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configuración-de-clusters-de-proveedores-de-kubernetes-alojados/gke.adoc
:xref-deploy-eks: xref:instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configuración-de-clusters-de-proveedores-de-kubernetes-alojados/eks.adoc
:xref-deploy-aks: xref:instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configuración-de-clusters-de-proveedores-de-kubernetes-alojados/aks.adoc
endif::[]

ifeval::["{build-type}" != "srfa"]
En este escenario, Rancher no aprovisiona Kubernetes porque está instalado por proveedores como Google Kubernetes Engine (GKE), Amazon Elastic Container Service for Kubernetes o Azure Kubernetes Service.

Si utiliza un proveedor de Kubernetes como Google GKE, Rancher se integra con sus APIs en la nube, permitiéndole crear y gestionar el control de acceso basado en funciones para el cluster alojado desde la interfaz de usuario de Rancher.

En este caso de uso, Rancher envía una solicitud a un proveedor alojado utilizando la API del proveedor. El proveedor luego aprovisiona y aloja el cluster para usted. Cuando el cluster termina de construirse, puede gestionarlo desde la interfaz de usuario de Rancher junto con los clusters que ha aprovisionado que están alojados localmente o en un proveedor de infraestructura.

Rancher admite los siguientes proveedores de Kubernetes:

* https://cloud.google.com/kubernetes-engine/[Google GKE (Google Kubernetes Engine)]
* https://aws.amazon.com/eks/[Amazon EKS (Amazon Elastic Container Service for Kubernetes)]
* https://azure.microsoft.com/en-us/services/kubernetes-service/[Microsoft AKS (Azure Kubernetes Service)]

endif::[]
ifeval::["{build-type}" == "srfa"]
En este escenario, Rancher no aprovisiona Kubernetes porque está instalado por Amazon Elastic Container Service for Kubernetes.

Si utiliza un proveedor de Kubernetes, Rancher se integra con sus APIs en la nube, permitiéndole crear y gestionar el control de acceso basado en funciones para el cluster alojado desde la interfaz de usuario de Rancher.

En este caso de uso, Rancher envía una solicitud a un proveedor alojado utilizando la API del proveedor. El proveedor luego aprovisiona y aloja el cluster para usted. Cuando el cluster termina de construirse, puede gestionarlo desde la interfaz de usuario de Rancher junto con los clusters que ha aprovisionado que están alojados localmente o en un proveedor de infraestructura.

Rancher admite el proveedor Amazon EKS:

* https://aws.amazon.com/eks/[Amazon EKS (Amazon Elastic Container Service for Kubernetes)]
endif::[]

[#_hosted_kubernetes_provider_authentication]
== Autenticación del proveedor de Kubernetes alojado

ifeval::["{build-type}" != "srfa"]
Al utilizar Rancher para crear un clúster alojado por un proveedor, se te solicita información de autenticación. Esta información es necesaria para acceder a la API del proveedor. Para obtener más información sobre cómo obtener esta información, consulta los siguientes procedimientos:

* {xref-deploy-gke}[Creando un Clúster GKE]
* {xref-deploy-eks}[Creando un Clúster EKS]
* {xref-deploy-aks}[Creando un Clúster AKS]
endif::[]
ifeval::["{build-type}" == "srfa"]
Al utilizar Rancher para crear un clúster alojado por un proveedor, se te solicita información de autenticación. Esta información es necesaria para acceder a la API del proveedor. Para obtener más información sobre cómo obtener esta información, consulta el siguiente procedimiento:

* {xref-deploy-eks}[Creando un Clúster EKS]
endif::[]
