= Rotação de Certificados de Webhook Expirados
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/expired-webhook-certificate-rotation.adoc 
:product-path: security/rancher-webhook/expired-webhook-certificate-rotation.adoc

Para versões do Rancher que têm `rancher-webhook` instalado, certas versões criaram certificados que expirarão após um ano. Será necessário que você rotacione seu certificado de webhook caso o certificado não tenha sido renovado.

No Rancher v2.6.3 e superior, as implantações do rancher-webhook renovarão automaticamente seu certificado TLS quando estiver a 30 dias ou menos da data de expiração. Se você estiver usando v2.6.2 ou anterior, existem dois métodos para contornar esse problema:

[#_1_users_with_cluster_access_run_the_following_commands]
== 1. Usuários com acesso ao cluster, execute os seguintes comandos:

----
kubectl delete secret -n cattle-system cattle-webhook-tls
kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io --ignore-not-found=true rancher.cattle.io
kubectl delete pod -n cattle-system -l app=rancher-webhook
----

[#_2_users_with_no_cluster_access_via_kubectl]
== 2. Usuários sem acesso ao cluster via `kubectl`:

. Delete o segredo `cattle-webhook-tls` no namespace `cattle-system` no cluster local.
. Exclua o `rancher.cattle.io` mutating webhook
. Delete o `rancher-webhook` pod no namespace `cattle-system` no cluster local.

[NOTE]
====

O problema de expiração do certificado de webhook não é específico de `cattle-webhook-tls` conforme listado nos exemplos. Você preencherá seu segredo de certificado expirado de acordo.
====

