= AKSクラスター構成リファレンス
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/aks-cluster-configuration.adoc 
:product-path: cluster-deployment/hosted-kubernetes/aks/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rbac: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc
:xref-ds-aks-deploy: xref:cluster-deployment/hosted-kubernetes/aks/aks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rbac: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/index.adoc
:xref-ds-aks-deploy: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.adoc
endif::[]

[#_role_based_access_control]
== ロール（役割）ベースのアクセス制御

Rancher UIでAKSクラスターをプロビジョニングする際、RBACを無効にすることはできません。AKSのクラスターでロールベースのアクセス制御が無効になっている場合、そのクラスターはRancherに登録またはインポートできません。実際には、AKSクラスターを登録するためにローカルアカウントを有効にする必要があります。

Rancherは、AKSクラスターのメンバー役割を他のクラスターと同様に構成できます。詳細については、{xref-manage-rbac}[ロールベースのアクセス制御]に関するセクションを参照してください。

[#_cloud_credentials]
== クラウド資格情報

[NOTE]
====

このセクションの構成情報は、Rancher用のサービスプリンシパルをすでに設定していることを前提としています。サービスプリンシパルの設定方法についての手順は、{xref-ds-aks-deploy}#_prerequisites_in_microsoft_azure[このセクション]を参照してください。
====


[#_subscription_id]
=== サブスクリプションID

サブスクリプションIDを取得するには、左側のナビゲーションバーで*すべてのサービス*をクリックします。次に、*サブスクリプション*をクリックします。Kubernetesクラスターに関連付けたいサブスクリプションの名前に移動し、*サブスクリプションID*をコピーします。

[#_client_id]
=== クライアントID

クライアントIDを取得するには、Azureポータルに移動し、次に*Azure Active Directory*をクリックし、次に*アプリ登録*をクリックし、サービスプリンシパルの名前をクリックします。クライアントIDは、アプリ登録の詳細ページに*アプリケーション（クライアント）ID*として表示されます。

[#_client_secret]
=== クライアントシークレット

クライアントシークレット値は作成後に取得できないため、クライアントシークレット値をまだ持っていない場合は、新しいクライアントシークレットを作成する必要があります。

新しいクライアントシークレットを取得するには、Azureポータルに移動し、次に*Azure Active Directory*をクリックし、次に*アプリ登録*をクリックし、サービスプリンシパルの名前をクリックします。

次に、*証明書とシークレット*をクリックし、*新しいクライアントシークレット*をクリックします。*[追加]* をクリックします。次に、新しいクライアントシークレットの*値*をコピーします。

[#_environment]
=== 使用環境

Microsoftは、地域の法律に準拠するために複数の https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest[クラウド]を提供しており、利用可能です：

* AzurePublicCloud
* AzureGermanCloud
* AzureChinaCloud
* AzureUSGovernmentCloud

[#_account_access]
== アカウントアクセス

このセクションでは、既存のAzureクラウド資格情報を選択するか、新しいものを作成する必要があります。

Azureクラウド資格情報の設定に関するヘルプについては、<<_cloud_credentials,このセクションをご覧ください。>>

[#_cluster_location]
== クラスターの場所

クラスターとノードの場所を設定します。AKSの可用性ゾーンに関する詳細は、 https://docs.microsoft.com/en-us/azure/aks/availability-zones[AKSドキュメントをご覧ください。]

高可用性の場所には、複数の可用性ゾーンが含まれます。

[#_cluster_options]
== クラスタオプション

[#_kubernetes_version]
=== Kubernetesバージョン

利用可能なKubernetesのバージョンは、Azure APIから動的に取得されます。

[#_cluster_resource_group]
=== クラスタリソースグループ

リソースグループは、Azureソリューションに関連するリソースを保持するコンテナです。リソースグループには、ソリューションのすべてのリソースを含めるか、またはグループとして管理するリソースのみを含めることができます。組織にとって最も理にかなった方法に基づいて、リソースをリソースグループに割り当てる方法を決定します。一般的に、同じライフサイクルを共有するリソースを同じリソースグループに追加することで、グループとして簡単にデプロイ、更新、削除できます。

既存のリソースグループを使用するか、リソースグループ名を入力すると、新しいリソースグループが作成されます。

既存のAKSクラスターを含むリソースグループを使用すると、新しいリソースグループが作成されます。Azure AKSは、リソースグループごとに1つのAKSクラスターのみを許可します。

リソースグループの管理に関する情報は、 https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal[Azureドキュメントをご覧ください。]

[#_linux_admin_username]
=== Linux管理ユーザー名

LinuxノードへのSSH接続を作成するために使用されるユーザー名です。

AKSノードのデフォルトユーザー名は`azureuser`です。

[#_ssh_public_key]
=== SSH公開鍵

LinuxノードへのSSH接続を作成するために使用される鍵です。

[#_tags]
=== タグ

クラスタータグは、組織が複数のAzureサービスにわたってリソースを整理する方法としてタグを使用する場合に便利です。これらのタグは、クラスター内のリソースには適用されません。

[#_networking_options]
== ネットワーキングオプション

[#_loadbalancer_sku]
=== LoadBalancer SKU

Azureのロードバランサーは、標準SKUと基本SKUの両方をサポートしています。

標準と基本のロードバランサーの比較については、公式の https://docs.microsoft.com/en-us/azure/load-balancer/skus#skus[Azureドキュメント]を参照してください。Microsoftは標準ロードバランサーを推奨しています。

1つ以上の可用性ゾーンを選択した場合、またはノードプールが1つ以上ある場合、標準ロードバランサーが必要です。

[#_network_policy]
=== ネットワークポリシー

AKSクラスター内のすべてのポッドは、デフォルトで制限なくトラフィックを送受信できます。セキュリティを向上させるために、トラフィックの流れを制御するルールを定義できます。Kubernetesのネットワークポリシー機能を使用すると、クラスター内のポッド間のインバウンドおよびアウトバウンドトラフィックに対するルールを定義できます。

Azureは、ネットワークポリシーを実装する2つの方法を提供しています。AKSクラスターを作成する際に、ネットワークポリシーオプションを選択します。クラスターが作成された後は、ポリシーオプションを変更することはできません。

* Azure独自の実装であるAzureネットワークポリシー。Azureネットワークポリシーは、Azure CNIを必要とします。
* Calicoネットワークポリシーは、 https://www.tigera.io/[Tigera]によって設立されたオープンソースのネットワークおよびネットワークセキュリティソリューションです。

ネットワークポリシーを持たないことを選択することもできます。

AzureとCalicoネットワークポリシーの違いやその機能についての詳細は、 https://docs.microsoft.com/en-us/azure/aks/use-network-policies#differences-between-azure-and-calico-policies-and-their-capabilities[AKS のドキュメント]を参照してください。

[#_dns_prefix]
=== DNSプレフィックス

クラスターのKubernetes APIサーバーのFQDN用に一意のDNSプレフィックスを入力してください。

[#_network_plugin]
=== ネットワークプラグイン

ネットワークプラグインは2つあります：kubenetとAzure CNI。

https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/#kubenet[kubenet] Kubernetes プラグインは、AKSクラスター作成のデフォルト設定です。kubenetが使用されると、クラスター内の各ノードはルーティング可能なIPアドレスを受け取ります。ポッドは、AKSクラスターの外部にある他のリソースと通信するためにNATを使用します。このアプローチにより、ポッドが使用するためにネットワークスペースで予約する必要のあるIPアドレスの数が減少します。

Azure CNI（高度な）ネットワーキングプラグインを使用すると、ポッドは完全な仮想ネットワーク接続を得て、接続されたネットワークからプライベートIPアドレスで直接アクセスできます。このプラグインは、より多くのIPアドレススペースを必要とします。

kubenetとAzure CNIの違いについての詳細は、 https://docs.microsoft.com/en-us/azure/aks/concepts-network#compare-network-models[AKSドキュメント]を参照してください。

[#_http_application_routing]
=== HTTPアプリケーションルーティング

有効にすると、HTTPアプリケーションルーティング アドオンは、AKSクラスターにデプロイされたアプリケーションへのアクセスを容易にします。2つのコンポーネントをデプロイします： https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes Ingress コントローラー]と https://github.com/kubernetes-incubator/external-dns[External-DNS コントローラー]。

詳細については、 https://docs.microsoft.com/en-us/azure/aks/http-application-routing[AKSドキュメント]を参照してください。

[#_set_authorized_ip_ranges]
=== 承認されたIP範囲を設定する

https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges#overview-of-api-server-authorized-ip-ranges[承認されたIPアドレス範囲を使用して、Kubernetes APIサーバーへのアクセスを保護できます。]

Kubernetes APIサーバーは、Kubernetes APIを公開します。このコンポーネントは、kubectlなどの管理ツールとのインタラクションを提供します。AKSは、専用のAPIサーバーを持つシングルテナントクラスター制御プレーンを提供します。デフォルトでは、APIサーバーにはパブリックIPアドレスが割り当てられ、KubernetesベースまたはAzureベースのRBACを使用してアクセスを制御する必要があります。

それ以外は公開アクセス可能なAKS制御プレーンとAPIサーバーへのアクセスを保護するために、承認されたIP範囲を有効にして使用できます。これらの承認されたIP範囲は、定義されたIPアドレス範囲のみがAPIサーバーと通信することを許可します。

ただし、認可されたIPアドレス範囲を使用しても、ユーザーと要求されたアクションを認可するためにKubernetes RBACまたはAzure RBACを使用する必要があります。

[#_container_monitoring]
=== コンテナ監視

コンテナ監視は、KubernetesのMetrics APIを通じて、コントローラー、ノード、およびコンテナからメモリとプロセッサのメトリックを収集することにより、パフォーマンスの可視性を提供します。コンテナログも収集されます。監視を有効にすると、メトリックとログはLinux用のLog Analyticsエージェントのコンテナ化バージョンを通じて自動的に収集されます。メトリックはメトリックストアに書き込まれ、ログデータはあなたの https://docs.microsoft.com/en-us/azure/azure-monitor/logs/log-query-overview[Log Analytics]ワークスペースに関連付けられたログストアに書き込まれます。

[#_log_analytics_workspace_resource_group]
=== Log Analyticsワークスペースリソースグループ

Log Analyticsワークスペースを含む https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview#resource-groups[リソースグループ]。Azure Monitor Logsを使用するには、少なくとも1つのワークスペースを作成する必要があります。

[#_log_analytics_workspace_name]
=== Log Analyticsワークスペース名

Azure Monitor Logsによって収集されたデータは、1つ以上の https://docs.microsoft.com/en-us/azure/azure-monitor/logs/design-logs-deployment[Log Analyticsワークスペース]に保存されます。ワークスペースはデータの地理的位置、どのユーザーがデータにアクセスできるかを定義するアクセス権、および価格帯やデータ保持などの設定を定義します。

Azure Monitor Logsを使用するには、少なくとも1つのワークスペースを作成する必要があります。単一のワークスペースは、すべての監視データに対して十分である場合もあれば、要件に応じて複数のワークスペースを作成することを選択する場合もあります。例えば、プロダクションデータ用のワークスペースとテスト用の別のワークスペースを持つことができます。

Azure Monitor Logsに関する詳細は、 https://docs.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs[Azureのドキュメント]を参照してください。

[#_support_private_kubernetes_service]
=== プライベートKubernetesサービスをサポート

通常、AKSワーカーノードは、クラスターがプライベートであるかどうかにかかわらず、パブリックIPを取得しません。プライベートクラスターでは、コントロールプレーンにパブリックエンドポイントはありません。

Rancherは、プライベートAKSクラスターに2つの方法のいずれかで接続できます。

RancherがAKSノードと同じ https://docs.microsoft.com/en-us/azure/virtual-network/nat-overview[NAT]上で実行されていることを確認する最初の方法です。

2番目の方法は、クラスターをRancherに登録するためのコマンドを実行することです。クラスターがプロビジョニングされると、クラスターのKubernetes APIに接続できる場所で表示されたコマンドを実行できます。このコマンドは、プライベートAPIエンドポイントが有効なAKSクラスターをプロビジョニングする際にポップアップで表示されます。

[NOTE]
====

既存のAKSクラスターを登録する際には、クラスターが`Cluster To register`のドロップダウンリストに表示されるまでに時間がかかる場合があることにご注意ください。この結果はリージョンによって決まります。
====


AKSプライベートクラスターへの接続に関する詳細は、 https://docs.microsoft.com/en-us/azure/aks/private-clusters#options-for-connecting-to-the-private-cluster[AKS ドキュメントをご覧ください。]

[#_node_pools]
== ノードプール

[#_mode]
=== モード

Azureインターフェースでは、プライマリノードプールが`system`（通常はコントロールプレーン用）または`user`（Rancherで最も一般的に必要とされるもの）に依存するかどうかを指定できます。

プライマリノードプールでは、モード、OS、数、サイズを指定できます。

システムノードプールは常に稼働中のノードを必要とするため、1ノード未満にスケールダウンすることはできません。少なくとも1つのシステムノードプールが必要です。

その後のノードプールでは、Rancher UIによってデフォルトが「ユーザー」に設定されます。ユーザーノードプールは、ノード数をゼロまでスケールできます。ユーザーノードプールは、Kubernetesコントロールプレーンの一部を実行しません。

AKSは、Kubernetesコントロールプレーンコンポーネントを実行するノードを公開しません。

[#_availability_zones]
=== アベイラビリティゾーン

https://docs.microsoft.com/en-us/azure/availability-zones/az-overview[アベイラビリティゾーン]は、地域内の一意の物理的な場所です。各ゾーンは、独立した電源、冷却、ネットワーキングを備えた1つ以上のデータセンターで構成されています。

すべての地域がアベイラビリティゾーンをサポートしているわけではありません。アベイラビリティゾーンを持つAzure地域のリストについては、 https://docs.microsoft.com/en-us/azure/availability-zones/az-region#azure-regions-with-availability-zones[Azureのドキュメントをご覧ください。]

[#_vm_size]
=== VMサイズ

ノードプール内の各VMのサイズを選択してください。各VMサイズの詳細については、 https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/[このページをご覧ください。]

[#_os_disk_type]
=== OSディスクの種類

ノードプール内のノードは、管理ディスクまたは一時ディスクのいずれかを使用できます。

https://docs.microsoft.com/en-us/azure/virtual-machines/ephemeral-os-disks[一時的なOSディスク]は、ローカルの仮想マシンストレージに作成され、リモートのAzureストレージには保存されません。一時的なOSディスクは、アプリケーションが個々のVMの障害に耐性があるステートレスなワークロードに適しており、VMの展開時間や個々のVMインスタンスの再イメージにより影響を受けやすくなります。一時的なOSディスクを使用すると、OSディスクへの読み取り/書き込みのレイテンシが低く、VMの再イメージが速くなります。

https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview[Azure管理ディスク]は、Azureによって管理され、Azure仮想マシンで使用されるブロックレベルのストレージボリュームです。管理ディスクは、99.999%の可用性を目指して設計されています。管理ディスクは、データの3つのレプリカを提供することでこれを実現し、高い耐久性を確保します。

[#_os_disk_size]
=== OSディスクのサイズ

各ノードのディスクのサイズ（GB単位）。

[#_node_count]
=== ノード数

ノードプール内のノードの数。最大ノード数は、 https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits[Azureサブスクリプション]によって制限される場合があります。

[#_max_pods_per_node]
=== ノードあたりの最大ポッド数

ノードあたりの最大ポッド数はデフォルトで110で、最大250です。

[#_enable_auto_scaling]
=== 自動スケーリングを有効にする

自動スケーリングが有効になっている場合、最小および最大のノード数を入力する必要があります。

自動スケーリングが有効になっている場合、ノードプールを手動でスケールすることはできません。スケールはAKSオートスケーラーによって制御されます。
