= 1.インフラストラクチャのセットアップ
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/set-up-infrastructure.adoc 
:product-path: installation-and-upgrade/other-installation-methods/http-proxy/set-up-infrastructure.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-setup-ec2-nodes: xref:installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:installation-and-upgrade/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:installation-and-upgrade/infrastructure-setup/amazon-elb-load-balancer.adoc
:xref-http-proxy-install-k8s: xref:installation-and-upgrade/other-installation-methods/http-proxy/install-kubernetes.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-setup-ec2-nodes: xref:how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:how-to-guides/new-user-guides/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:how-to-guides/new-user-guides/infrastructure-setup/amazon-elb-load-balancer.adoc
:xref-http-proxy-install-k8s: xref:getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-kubernetes.adoc
endif::[]

このセクションでは、HTTPプロキシを介してインターネットアクセスを持つRancher管理サーバーの基盤となるインフラストラクチャをプロビジョニングします。

高可用性のRKE2/K3sクラスターにRancher管理サーバーをインストールするには、以下のインフラストラクチャを設定することをお勧めします：

* *三つのLinuxノード*、通常は仮想マシンで、AmazonのEC2、Google Compute Engine、またはvSphereなどのインフラストラクチャプロバイダーに配置します。
* *ロードバランサー*は、フロントエンドトラフィックを三つのノードに振り分けるために使用します。
* *DNSレコード*は、URLをロードバランサーにマッピングします。これがRancherサーバーのURLとなり、ダウンストリームのKubernetesクラスターはこれにアクセスする必要があります。

これらのノードは同じリージョン/データセンター内に配置する必要があります。これらのサーバーは別々のアベイラビリティゾーンに配置することができます。

[#_why_three_nodes]
== なぜ三つのノードなのか？

RKE2/K3sクラスターでは、Rancherサーバーのデータはetcdに保存されます。このetcdデータベースは三つのノードすべてで実行されます。

etcdデータベースは、常にetcdクラスターの過半数でリーダーを選出できるように、奇数のノード数を必要とします。etcdデータベースがリーダーを選出できない場合、 https://www.quora.com/What-is-split-brain-in-distributed-systems[スプリットブレイン]が発生し、クラスターをバックアップから復元する必要があります。三つのetcdノードのうち一つが故障した場合、残りの二つのノードはetcdノードの総数の過半数を持っているため、リーダーを選出できます。

[#_1_set_up_linux_nodes]
== 1.Linuxノードのセットアップ

これらのホストはHTTPプロキシを介してインターネットに接続します。

ノードが{xref-install-reqs}[OS、コンテナランタイム、ハードウェア、ネットワーキング]の一般的なインストール要件を満たしていることを確認してください。

Linuxノードを設定する一例については、Amazon EC2のインスタンスとしてノードを設定するためのこの{xref-setup-ec2-nodes}[チュートリアル]を参照してください。

[#_2_set_up_the_load_balancer]
== 2.ロードバランサーの設定

Rancherのレプリカにトラフィックを誘導するために、両方のノードにロードバランサーを設定する必要があります。これにより、単一のノードの障害がRancher管理サーバーへの通信を妨げることを防ぎます。

Kubernetesが後のステップで設定されると、RKE2/K3sツールがNGINX Ingressコントローラーをデプロイします。このコントローラーは、ワーカーノードのポート80および443でリスンし、特定のホスト名宛てのトラフィックに応答します。

Rancherがインストールされると（これも後のステップで）、RancherシステムはIngressリソースを作成します。そのIngressは、NGINX IngressコントローラーにRancherのホスト名宛てのトラフィックをリスンするよう指示します。NGINX Ingressコントローラーは、Rancherのホスト名宛てのトラフィックを受信すると、そのトラフィックをクラスター内の実行中のRancherポッドに転送します。

実装において、レイヤー4またはレイヤー7のロードバランサーを使用するかどうかを検討してください：

* *レイヤー4のロードバランサー*は、ノードにTCPトラフィックを転送するという点で、2つの選択肢の中でよりシンプルです。ロードバランサーをレイヤー4バランサーとして構成し、TCP/80およびTCP/443のポートにトラフィックをRancher管理クラスターのノードに転送することをお勧めします。クラスター内のIngressコントローラーは、HTTPトラフィックをHTTPSにリダイレクトし、ポートTCP/443でSSL/TLSを終了します。Ingressコントローラーは、Rancherデプロイメント内のIngressポッドにTCP/80のポートへのトラフィックを転送します。
* *レイヤー7のロードバランサー*は少し複雑ですが、必要な機能を提供することができます。例えば、レイヤー7のロードバランサーは、RancherがTLS終了を行うのではなく、ロードバランサーでTLS終了を処理することができます。これは、インフラストラクチャ内でTLS終了を集中管理したい場合に有益です。レイヤー7のロードバランシングは、レイヤー4のロードバランサーが関与できないクッキーなどのHTTP属性に基づいて、ロードバランサーが意思決定を行う能力も提供します。レイヤー7のロードバランサーでSSL/TLSトラフィックを終了することを決定した場合、後のステップでRancherをインストールする際に`--set tls=external`オプションを使用する必要があります。詳細については、{xref-helm-chart-options}#_external_tls_termination[Rancher Helmチャートオプション]を参照してください。

NGINXロードバランサーの設定方法を示す例については、{xref-nginx-load-balancer}[このページ]を参照してください。

Amazon ELBネットワークロードバランサーのセットアップに関するハウツーガイドについては、{xref-amazon-elb}[このページ]を参照してください。

[NOTE]
.重要:
====

インストール後、Rancher以外のアプリケーションのロードバランシングにこのロードバランサー（すなわち、`local`クラスターのIngress）を使用しないでください。このIngressを他のアプリケーションと共有すると、他のアプリのIngress設定のリロード後にRancherに対してウェブソケットエラーが発生する可能性があります。`local`クラスターをRancher専用にし、他のアプリケーションには使用しないことをお勧めします。
====


[#_3_set_up_the_dns_record]
== 3.DNSレコードを設定する

ロードバランサーを設定したら、このロードバランサーにトラフィックを送信するためのDNSレコードを作成する必要があります。

環境によっては、LB IPを指すAレコードであるか、ロードバランサーのホスト名を指すCNAMEである場合があります。いずれの場合でも、このレコードがRancherが応答することを意図しているホスト名であることを確認してください。

Rancherをインストールする際の後のステップでこのホスト名を指定する必要があり、後で変更することはできません。あなたの決定が最終的なものであることを確認してください。

Amazon ELBロードバランサーにドメイントラフィックをルーティングするためのDNSレコードの設定に関するハウツーガイドについては、 https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer[公式AWSドキュメントを参照してください。]

[#__xref_http_proxy_install_k8s_next_set_up_a_kubernetes_cluster]
== {xref-http-proxy-install-k8s}[次へ：Kubernetesクラスターのセットアップ]
