= Configurar FreeIPA
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/guías-de-nuevos-usuarios/autenticación-permisos-y-configuración-global/configuración-de-autenticación/configurar-freeipa.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-freeipa.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configuración-de-autenticación/index.adoc
endif::[]

Si tu organización utiliza FreeIPA para la autenticación de usuarios, puedes configurar Rancher para permitir que tus usuarios inicien sesión utilizando sus credenciales de FreeIPA.

[NOTE]
.Requisitos previos:
====

* Debes tener un https://www.freeipa.org/[Servidor FreeIPA] configurado.
* Crea una cuenta de servicio en FreeIPA con `read-only` acceso. Rancher utiliza esta cuenta para verificar la pertenencia a grupos cuando un usuario realiza una solicitud utilizando una clave API.
* Lee {xref-authn-authz}#_external_authentication_configuration_and_principal_users[Configuración de Autenticación Externa y Usuarios Principales].
====


. Inicia sesión en Rancher utilizando un usuario local asignado al rol `administrator` (es decir, el _principal local_).
. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En el menú de navegación de la izquierda, haz clic en *Proveedor de Autenticación*.
. Haz clic en *FreeIPA*.
. Completa el formulario *Configurar un servidor FreeIPA*.
+
Es posible que necesites iniciar sesión en tu controlador de dominio para encontrar la información solicitada en el formulario.
+

[NOTE]
.¿Usando TLS?
====
Si el certificado es autofirmado o no proviene de una autoridad de certificación reconocida, asegúrate de proporcionar la cadena completa. Esa cadena es necesaria para verificar el certificado del servidor.
====

+

[NOTE]
.Base de Búsqueda de Usuarios vs. Base de Búsqueda de Grupos
====
La base de búsqueda permite a Rancher buscar usuarios y grupos que están en tu FreeIPA.  Estos campos son solo para bases de búsqueda y no para filtros de búsqueda.

 ** Si tus usuarios y grupos están en la misma base de búsqueda, completa solo la Base de Búsqueda de Usuarios.
 ** Si tus grupos están en una base de búsqueda diferente, puedes completar opcionalmente la Base de Búsqueda de Grupos. Este campo está dedicado a la búsqueda de grupos, pero no es obligatorio.
====


. Si tu FreeIPA se desvía del esquema estándar de AD, completa el formulario *Personalizar esquema* para que coincida. Si no es así, omita este paso.
+

[NOTE]
.Atributo de búsqueda
====
El campo Atributo de búsqueda tiene tres valores predeterminados específicos: `uid|sn|givenName`. Después de que FreeIPA esté configurado, cuando un usuario introduce texto para añadir usuarios o grupos, Rancher consulta automáticamente el servidor FreeIPA e intenta coincidir los campos por id de usuario, apellido o nombre de pila. Rancher busca específicamente usuarios/grupos que comiencen con el texto introducido en el campo de búsqueda.

El valor de campo predeterminado es `uid|sn|givenName`, pero puedes configurar este campo a un subconjunto de estos campos. La barra vertical (`|`) entre los campos separa estos campos.

 ** `uid`: ID de usuario
 ** `sn`: Apellido
 ** `givenName`: Nombre

Con este atributo de búsqueda, Rancher crea filtros de búsqueda para usuarios y grupos, pero _no puedes_ añadir tus propios filtros de búsqueda en este campo.
====


. Introduce tu nombre de usuario y contraseña de FreeIPA en *Autenticar con FreeIPA* para confirmar que Rancher está configurado para usar la autenticación de FreeIPA.
. Haz clic en *Habilitar*.

*Resultado:*

* La autenticación de FreeIPA está configurada.
* Has iniciado sesión en Rancher con tu cuenta de FreeIPA (es decir, el _principal externo_).
