= Configurar Okta (SAML)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-okta-saml.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-okta-saml.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
:xref-openldap-reference: xref:rancher-admin/users/authn-and-authz/openldap/reference.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions.adoc 
:xref-openldap-reference: xref:instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configurar-openldap/referencia-de-configuración-openldap.adoc
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
endif::[]

Si tu organización utiliza Okta Identity Provider (IdP) para la autenticación de usuarios, puedes configurar Rancher para permitir que tus usuarios inicien sesión utilizando sus credenciales de IdP.

[NOTE]
====

La integración de Okta solo admite inicios de sesión iniciados por el Proveedor de Servicios.
====


[#_prerequisites]
== Requisitos previos

En Okta, crea una aplicación SAML con la configuración que se indica a continuación. Consulta la https://developer.okta.com/standards/SAML/setting_up_a_saml_application_in_okta[documentación de Okta] para obtener ayuda.

|===
| Valor | Valor

| `Single Sign on URL`
| `https://yourRancherHostURL/v1-saml/okta/saml/acs`

| `Audience URI (SP Entity ID)`
| `https://yourRancherHostURL/v1-saml/okta/saml/metadata`
|===

[#_configuring_okta_in_rancher]
== Configurando Okta en Rancher

Puedes integrar Okta con Rancher, de modo que los usuarios autenticados puedan acceder a los recursos de Rancher a través de los permisos de sus grupos. Okta devuelve una afirmación SAML que autentica a un usuario, incluyendo a qué grupos pertenece un usuario.

. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En el menú de navegación de la izquierda, haz clic en *Proveedor de Autenticación*.
. Haz clic en *Okta*.
. Completa el formulario *Configurar cuenta de Okta*. Los ejemplos a continuación describen cómo puedes mapear los atributos de Okta desde las declaraciones de atributos a los campos dentro de Rancher.
+
|===
| Campo | Descripción

| Campo Nombre para Mostrar
| El nombre del atributo de una declaración de atributo que contiene el nombre para mostrar de los usuarios.

| Campo Nombre de Usuario
| El nombre del atributo de una declaración de atributo que contiene el nombre de usuario/nombre de pila.

| Campo UID
| El nombre del atributo de una declaración de atributo que es único para cada usuario.

| Campo Grupos
| El nombre del atributo en una declaración de atributo de grupo que expone tus grupos.

| Host de la API de Rancher
| La URL de tu servidor Rancher.

| Clave Privada / Certificado
| Un par clave/certificado utilizado para la encriptación de afirmaciones.

| Metadata XML
| El archivo `Identity Provider metadata` que encuentras en la sección `Sign On` de la aplicación.
|===
+

[TIP]
====
Puede generar un par de clave/certificado utilizando un comando openssl. Por ejemplo:

----
 openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout myservice.key -out myservice.crt
----
====


. Después de completar el formulario *Configurar cuenta de Okta*, haz clic en *Habilitar*.
+
Rancher te redirige a la página de inicio de sesión del IdP. Introduce las credenciales que autentican con Okta IdP para validar tu configuración de Okta en Rancher.
+

[NOTE]
====
Si parece que no sucede nada, es probable que tu navegador haya bloqueado el pop-up. Asegúrate de desactivar el bloqueador de pop-ups para tu dominio de Rancher y de añadirlo a la lista blanca en cualquier otra extensión que puedas utilizar.
====


*Resultado:* Rancher está configurado para trabajar con Okta. Tus usuarios ahora pueden iniciar sesión en Rancher utilizando sus credenciales de Okta.

[NOTE]
.Advertencias del Proveedor SAML
====
Si configuras Okta sin OpenLDAP, no podrás buscar ni consultar directamente a usuarios o grupos. Esto conlleva varias advertencias:

* Los usuarios y grupos no son validados cuando les asignas permisos en Rancher.
* Al añadir usuarios, los IDs de usuario exactos (es decir, `UID Field`) deben ser introducidos correctamente. A medida que escribes el ID de usuario, no habrá búsqueda de otros IDs de usuario que puedan coincidir.
* Al añadir grupos, debes seleccionar el grupo del menú desplegable que está al lado del cuadro de texto. Rancher asume que cualquier entrada del cuadro de texto es un usuario.
* El menú desplegable de grupos muestra solo los grupos de los que eres miembro. Sin embargo, si tienes permisos de Administrador o permisos de Administrador restringidos, puedes unirte a un grupo del que no eres miembro.
====

[#_okta_with_openldap_search]
== Okta con búsqueda en OpenLDAP

Puedes añadir un backend de OpenLDAP para ayudar con la búsqueda de usuarios y grupos. Rancher mostrará usuarios y grupos adicionales del servicio OpenLDAP. Esto permite asignar permisos a grupos de los que el usuario conectado no sea ya miembro.

[#_openldap_prerequisites]
=== Requisitos Previos de OpenLDAP

Si utilizas Okta como tu IdP, puedes https://help.okta.com/en-us/Content/Topics/Directory/LDAP-interface-main.htm[configurar una interfaz LDAP] para que la utilice Rancher. También puedes configurar un servidor OpenLDAP externo.

Debes configurar Rancher con una cuenta de enlace LDAP (también conocida como cuenta de servicio) para que puedas buscar y recuperar entradas LDAP de usuarios y grupos que deberían tener acceso. No utilices una cuenta de administrador o una cuenta personal como cuenta de enlace LDAP. https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-add-users.htm[Crea] una cuenta dedicada en OpenLDAP, con acceso de solo lectura a los usuarios y grupos bajo la base de búsqueda configurada.

[CAUTION]
.Consideraciones relativas a la seguridad
====

La cuenta de servicio de OpenLDAP se utiliza para todas las búsquedas. Los usuarios de Rancher verán usuarios y grupos que la cuenta de servicio de OpenLDAP puede ver, independientemente de sus permisos SAML individuales.
====


____
*¿Usando TLS?*

Si el certificado utilizado por el servidor OpenLDAP es autofirmado o proviene de una autoridad de certificación no reconocida, Rancher necesita el certificado CA (concatenado con cualquier certificado intermedio) en formato PEM. Proporciona este certificado durante la configuración para que Rancher pueda validar la cadena de certificados.
____

[#_configure_openldap_in_rancher]
=== Configura OpenLDAP en Rancher

{xref-openldap-reference}[Configura los ajustes] para el servidor OpenLDAP, grupos y usuarios. Ten en cuenta que la membresía de grupos anidados no está disponible.

____
Antes de proceder con la configuración, familiarízate con {xref-authn-authz}#_external_authentication_configuration_and_principal_users[la configuración de autenticación externa y los usuarios principales].
____

. Inicia sesión en Rancher utilizando un usuario local asignado al rol {xref-global-permissions}[administrador] (es decir, el _principal local_).
. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En el menú de navegación de la izquierda, haz clic en *Proveedor de Autenticación*.
. Haz clic en *Okta* o, si SAML ya está configurado, en *Editar Config*.
. Bajo *Búsqueda de Usuarios y Grupos*, marca *Configurar un servidor OpenLDAP*

Si experimentas problemas al probar la conexión con el servidor OpenLDAP, asegúrate de haber introducido las credenciales de la cuenta de servicio y de haber configurado correctamente la base de búsqueda. Inspeccionar los registros de Rancher puede ayudar a identificar la causa raíz. Los registros de depuración pueden contener información más detallada sobre el error. Por favor, consulta xref:faq/technical-items.adoc#_how_can_i_enable_debug_logging[Cómo puedo habilitar el registro de depuración] para más información.

[#_configuring_saml_single_logout_slo]
== Configuración de Cierre de Sesión Único SAML (SLO)

include::shared:ROOT:partial$en/configure-slo.adoc[]

[#_saml_and_openldap_group_permissions]
== Permisos de grupo SAML y OpenLDAP

include::shared:ROOT:partial$en/saml-openldap-group-permissions.adoc[]
