= Configurar PingIdentity (SAML)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: instrucciones/guías-de-nuevos-usuarios/autenticación-permisos-y-configuración-global/configuración-de-autenticación/configurar-pingidentity.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-pingidentity.adoc

Si tu organización utiliza Ping Identity Provider (IdP) para la autenticación de usuarios, puedes configurar Rancher para permitir que tus usuarios inicien sesión utilizando sus credenciales de IdP.

____
*Requisitos previos:*

* Debes tener un https://www.pingidentity.com/[Servidor IdP de Ping] configurado.
* A continuación se presentan las URL del Proveedor de Servicios de Rancher necesarias para la configuración:
Metadata URL: `\https://<rancher-server>/v1-saml/ping/saml/metadata`
URL del Servicio de Consumo de Afirmaciones (ACS): `\https://<rancher-server>/v1-saml/ping/saml/acs`
Ten en cuenta que estas URLs no devolverán datos válidos hasta que la configuración de autenticación se guarde en Rancher.
* Exporta un archivo `metadata.xml` desde tu servidor IdP. Para más información, consulta la https://documentation.pingidentity.com/pingfederate/pf83/index.shtml#concept_exportingMetadata.html[documentación de PingIdentity].
____

. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En el menú de navegación de la izquierda, haz clic en *Proveedor de Autenticación*.
. Haz clic en *Ping Identity*.
. Completa el formulario *Configurar una cuenta de Ping*. Ping IdP te permite especificar qué almacén de datos deseas utilizar. Puedes añadir una base de datos o utilizar un servidor LDAP existente. Por ejemplo, si seleccionas tu servidor de Active Directory (AD), los ejemplos a continuación describen cómo puedes mapear atributos de AD a campos dentro de Rancher.
 .. *Campo Nombre para Mostrar*: Introduce el atributo de AD que contiene el nombre para mostrar de los usuarios (ejemplo: `displayName`).
 .. *Campo Nombre de Usuario*: Introduce el atributo de AD que contiene el nombre de usuario/nombre de pila (ejemplo: `givenName`).
 .. *Campo UID*: Introduce un atributo de AD que sea único para cada usuario (ejemplo: `sAMAccountName`, `distinguishedName`).
 .. *Campo Grupos*: Haz entradas para gestionar la membresía de grupos (ejemplo: `memberOf`).
 .. *Campo de ID de Entidad* (opcional): El identificador único, dependiente del protocolo, publicado de tu socio. Este ID define tu organización como la entidad que opera el servidor para transacciones SAML 2.0. Este ID puede haber sido obtenido fuera de banda o a través de un archivo de metadatos SAML.
 .. *Host de la API de Rancher*: Introduce la URL de tu servidor Rancher.
 .. *Clave Privada* y *Certificado*: Este es un par de clave-certificado para crear un shell seguro entre Rancher y tu IdP.
+
Puedes generar uno utilizando un comando openssl. Por ejemplo:
+
----
 openssl req -x509 -newkey rsa:2048 -keyout myservice.key -out myservice.cert -days 365 -nodes -subj "/CN=myservice.example.com"
----

 .. *IDP-metadata*: El archivo `metadata.xml` que https://documentation.pingidentity.com/pingfederate/pf83/index.shtml#concept_exportingMetadata.html[exportaste desde tu servidor IdP].
. Después de completar el formulario *Configurar una cuenta de Ping*, haz clic en *Habilitar*.
+
Rancher te redirige a la página de inicio de sesión del IdP. Introduce las credenciales que autentican con Ping IdP para validar tu configuración de PingIdentity en Rancher.
+

[NOTE]
====
Es posible que tengas que desactivar tu bloqueador de ventanas emergentes para ver la página de inicio de sesión del IdP.
====


*Resultado:* Rancher está configurado para trabajar con PingIdentity. Tus usuarios ahora pueden iniciar sesión en Rancher utilizando sus credenciales de PingIdentity.

[NOTE]
.Advertencias del Proveedor SAML
====
* Los usuarios y grupos no son validados cuando les asignas permisos en Rancher.
* Al añadir usuarios, los IDs de usuario exactos (es decir, `UID Field`) deben ser introducidos correctamente. A medida que escribes el ID de usuario, no habrá búsqueda de otros IDs de usuario que puedan coincidir.
* Al añadir grupos, debes seleccionar el grupo del menú desplegable que está al lado del cuadro de texto. Rancher asume que cualquier entrada del cuadro de texto es un usuario.
* El menú desplegable de grupos muestra solo los grupos de los que eres miembro. Si tienes permisos de administrador o permisos de administrador restringidos, puedes unirte a un grupo del que no eres miembro.
====

[#_configuring_saml_single_logout_slo]
== Configuración de Cierre de Sesión Único SAML (SLO)

include::shared:ROOT:partial$en/configure-slo.adoc[]

[#_saml_and_openldap_group_permissions]
== Permisos de grupo SAML y OpenLDAP

include::shared:ROOT:partial$en/saml-openldap-group-permissions.adoc[]
