= Configurar GitHub
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configuración-de-autenticación/configurar-github.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-github.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configuración-de-autenticación/index.adoc
endif::[]

En entornos que utilizan GitHub, puedes configurar Rancher para permitir el inicio de sesión utilizando credenciales de GitHub.

[NOTE]
.Requisitos previos:
====

Lee {xref-authn-authz}#_configuración_de_autenticación_externa_y_usuarios_principales[Configuración de Autenticación Externa y Usuarios Principales].
====


. Inicia sesión en Rancher utilizando un usuario local asignado al rol `administrator` (es decir, el _principal local_).
. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En el menú de navegación de la izquierda, haz clic en *Proveedor de Autenticación*.
. Haz clic en *GitHub*.
. Sigue las instrucciones mostradas para configurar una aplicación de GitHub. Rancher te redirige a GitHub para completar el registro.
+

[NOTE]
.¿Qué es una URL de Callback de Autorización?
====
La URL de Callback de Autorización es la URL a la que los usuarios van para comenzar a utilizar tu aplicación (es decir, la pantalla de inicio).

Cuando utilizas autenticación externa, la autenticación no se lleva a cabo realmente en tu aplicación. En su lugar, la autenticación se lleva a cabo externamente (en este caso, GitHub). Después de que esta autenticación externa se complete con éxito, la URL de Callback de Autorización es la ubicación donde el usuario vuelve a entrar en tu aplicación.
====


. Desde GitHub, copia el *ID de Cliente* y el *Secreto de Cliente*. Pégalos en Rancher.
+

[NOTE]
.¿Dónde encuentro el ID de Cliente y el Secreto de Cliente?
====
Desde GitHub, selecciona Configuración > Configuración de Desarrollador > Aplicaciones OAuth. El ID de Cliente y el Secreto de Cliente se muestran de manera prominente.
====


. Haz clic en *Autenticar con GitHub*.
. Utiliza las opciones de *Acceso al Sitio* para configurar el alcance de la autorización del usuario.
 ** *Permitir cualquier Usuario válido*
+
_Cualquier_ usuario de GitHub puede acceder a Rancher. ¡Generalmente desaconsejamos el uso de esta configuración!

 ** *Permitir a los miembros de Clusters, Proyectos, además de Usuarios y Organizaciones Autorizados*
+
Cualquier usuario o grupo de GitHub añadido como *Miembro del Cluster* o *Miembro del Proyecto* puede iniciar sesión en Rancher. Además, cualquier usuario o grupo de GitHub que añadas a la lista de *Usuarios y Organizaciones Autorizados* puede iniciar sesión en Rancher.

 ** *Restringir el acceso solo a Usuarios y Organizaciones Autorizados*
+
Solo los usuarios o grupos de GitHub añadidos a los Usuarios y Organizaciones Autorizados pueden iniciar sesión en Rancher.
 +
. Haz clic en *Habilitar*.

*Resultado:*

* La autenticación de GitHub está configurada.
* Has iniciado sesión en Rancher con tu cuenta de GitHub (es decir, el _principal externo_).
