= Autenticación local
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/nuevos-usuarios/autenticación-permisos-y-configuración-global/configuración-de-autenticación/crear-usuarios-locales.adoc 
:product-path: rancher-admin/users/authn-and-authz/create-local-users.adoc

La autenticación local es la predeterminada hasta que configures un proveedor de autenticación externo. Rancher almacena la información de las cuentas de usuario, como nombres de usuario y contraseñas, de forma local. Por defecto, el usuario `admin` que inicia sesión en Rancher por primera vez es un usuario local.

[#_adding_local_users]
== Añadir usuarios locales

Independientemente de si utilizas autenticación externa, deberías crear algunos usuarios de autenticación local para que puedas seguir utilizando Rancher si tu servicio de autenticación externo encuentra problemas.

. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En el menú de navegación de la izquierda, haz clic en *Usuarios*.
. Haga clic en *Crear*.
. Completa el formulario de *Añadir Usuario*.
. Haga clic en *Crear*.
