= 切断されたクラスターのベストプラクティス
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-22
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-managed-clusters/disconnected-clusters.adoc 
:product-path: cluster-admin/best-practices/disconnected-clusters.adoc

Rancherは、ネットワークの中断、コントロールプレーンの可用性、またはすべてのクラスターノードがダウンしているために、常にオンラインでない可能性のあるクラスターの管理をサポートしています。現在、最新のRancherバージョンにおいて切断されたクラスターに関する既知の問題はありません。

管理されたクラスターがRancherから切断されている間、管理操作は利用できず、RancherのUIはクラスターへのナビゲーションを許可しません。しかし、接続が再確立されると、機能は完全に復元されます。

[#_best_practices_for_managing_disconnected_clusters]
== 切断されたクラスターの管理に関するベストプラクティス

* *Rancherのアップグレード中のクラスターの可用性*:Rancherのアップグレード中は、すべての管理されたクラスター、または少なくともほとんどのクラスターがオンラインであることを推奨します。その理由は、Rancherをアップグレードすると、管理されたクラスターで実行されているRancherエージェントソフトウェアが自動的にアップグレードされるためです。エージェントとRancherのバージョンを一致させることで、一貫した機能が確保されます。アップグレード中に切断されたクラスターは、再接続されるとすぐにエージェントが更新されます。

* *切断されたクラスターの削除*:Rancherに再接続しないクラスター（例：廃止または破壊されたクラスター）を定期的に削除してください。そのようなクラスターをRancher管理システムに保持することは、不必要なリソースを消費し、時間の経過とともにRancherのパフォーマンスに影響を与える可能性があります。

* *証明書のローテーションに関する考慮事項*:Rancherに接続されているかどうかにかかわらず、クラスターを定期的にシャットダウンするプロセスを設計する際は、証明書のローテーションポリシーを考慮してください。例えば、RKE2/K3sクラスターは、寿命を超えた場合に起動時に証明書をローテーションすることがあります。
