= Gestionar HPAs con la {rancher-product-name} UI
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc 
:product-path: cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-hpas-with-kubectl: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-hpas-with-kubectl: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
endif::[]

La interfaz de usuario de Rancher admite la creación, gestión y eliminación de HPAs. Puedes configurar el uso de CPU o memoria como la métrica que el HPA utiliza para escalar.

Si deseas crear HPAs que escalen basándose en otras métricas que no sean CPU y memoria, consulta {xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[Configuración del HPA para escalar utilizando métricas personalizadas con Prometheus].

[#_creating_an_hpa]
== Creando un HPA

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster en el que deseas crear un HPA y haz clic en *Explorar*.
. En la barra de navegación izquierda, haz clic en menu:Descubrimiento de Servicios[HorizontalPodAutoscalers].
. Haga clic en *Crear*.
. Selecciona un *Espacio de nombres* para el HPA.
. Introduce un *Nombre* para el HPA.
. Selecciona una *Referencia de Objetivo* como objetivo de escala para el HPA.
. Especifica las *réplicas mínimas* y las *réplicas máximas* para el HPA.
. Configura las métricas para el HPA. Puedes elegir el uso de memoria o CPU como la métrica que hará que el HPA escale el servicio hacia arriba o hacia abajo. En el campo *Cantidad*, introduce el porcentaje del uso de memoria o CPU de la carga de trabajo que hará que el HPA escale el servicio. Para configurar otras métricas de HPA, incluidas las métricas disponibles de Prometheus, necesitas {xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[gestionar HPAs utilizando kubectl].
. Haz clic en *Crear* para crear el HPA.

[NOTE]
.Resultado:
====

El HPA se despliega en el espacio de nombres elegido. Puedes ver el estado del HPA desde la vista Recursos > HPA del proyecto.
====


[#_get_hpa_metrics_and_status]
== Obtener métricas y estado del HPA

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster que tiene el HPA y haz clic en *Explorar*.
. En la barra de navegación izquierda, haz clic en menu:Descubrimiento de Servicios[HorizontalPodAutoscalers]. La página de *HorizontalPodAutoscalers* muestra el número de réplicas actuales.

Para métricas más detalladas y el estado de un HPA específico, haz clic en el nombre del HPA. Esto lleva a la página de detalles del HPA.

[#_deleting_an_hpa]
== Eliminando un HPA

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster que tiene el HPA que deseas eliminar y haz clic en *Explorar*.
. En la barra de navegación izquierda, haz clic en menu:Descubrimiento de Servicios[HorizontalPodAutoscalers].
. Haz clic en menu:Recursos[HPA].
. Encuentra el HPA que te gustaría eliminar y haz clic en *⋮ > Eliminar*.
. Haz clic en *Eliminar* para confirmar.

[NOTE]
.Resultado:
====

El HPA se elimina del clúster actual.
====

