= Configuration d'OpenLDAP
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/configurer-openldap/index.adoc 
:product-path: rancher-admin/users/authn-and-authz/openldap/openldap.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-openldap-reference: xref:rancher-admin/users/authn-and-authz/openldap/reference.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/configuration-d'authentification/index.adoc
:xref-openldap-reference: xref:how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/configurer-openldap/openldap-config-reference.adoc
endif::[]

Si votre organisation utilise LDAP pour l'authentification des utilisateurs, vous pouvez configurer Rancher pour communiquer avec un serveur OpenLDAP afin d'authentifier les utilisateurs. Cela permet aux administrateurs de Rancher de contrôler l'accès aux clusters et aux projets en fonction des utilisateurs et des groupes gérés de manière externe dans le dépôt central des utilisateurs de l'organisation, tout en permettant aux utilisateurs finaux de s'authentifier avec leurs identifiants LDAP lors de la connexion à l'interface utilisateur de Rancher.

[#_prerequisites]
== Conditions préalables

Rancher doit être configuré avec un compte de liaison LDAP (également appelé compte de service) pour rechercher et récupérer les entrées LDAP concernant les utilisateurs et les groupes qui devraient avoir accès. Il est recommandé de ne pas utiliser un compte administrateur ou un compte personnel à cette fin et de créer plutôt un compte dédié dans OpenLDAP avec un accès en lecture seule aux utilisateurs et groupes sous la base de recherche configurée (voir ci-dessous).

____
*Utiliser TLS?*

Si le certificat utilisé par le serveur OpenLDAP est auto-signé ou n'est pas d'une autorité de certification reconnue, assurez-vous d'avoir à portée de main le certificat CA (concaténé avec tous les certificats intermédiaires) au format PEM. Vous devrez coller ce certificat lors de la configuration afin que Rancher puisse valider la chaîne de certificats.
____

[#_configure_openldap_in_rancher]
== Configurer OpenLDAP dans Rancher

Configurer les paramètres pour le serveur OpenLDAP, les groupes et les utilisateurs. Pour obtenir de l'aide pour remplir chaque champ, référez-vous à la {xref-openldap-reference}[référence de configuration.]

____
Avant de procéder à la configuration, veuillez vous familiariser avec les concepts de {xref-authn-authz}#_configuration_d'authentification_externe_et_utilisateurs_principaux[Configuration d'authentification externe et utilisateurs principaux].
____

. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs & Authentification*.
. Dans le menu de navigation à gauche, cliquez sur *Fournisseur d'authentification*.
. Cliquez sur *OpenLDAP*. Remplissez le formulaire *Configurer un serveur OpenLDAP*.
. Cliquez sur *Activer*.

[#_test_authentication]
=== Test de l'authentification

Une fois la configuration terminée, procédez à tester la connexion au serveur OpenLDAP. L'authentification avec OpenLDAP sera activée implicitement si le test est réussi.

[NOTE]
====

L'utilisateur OpenLDAP correspondant aux identifiants saisis à cette étape sera associé au compte principal local et se verra attribuer des privilèges d'administrateur dans Rancher. Vous devez donc prendre une décision consciente sur le compte LDAP que vous utilisez pour effectuer cette étape.
====


. Entrez le *nom d'utilisateur* et le *mot de passe* pour le compte OpenLDAP qui doit être associé au compte principal local.
. Cliquez sur *Authentifier avec OpenLDAP* pour tester la connexion OpenLDAP et finaliser la configuration.

*Résultat :*

* L'authentification OpenLDAP est configurée.
* L'utilisateur LDAP correspondant aux identifiants saisis est associé au compte principal (administratif) local.

[NOTE]
====

Vous pourrez toujours vous connecter en utilisant le compte et le mot de passe `admin` configurés localement en cas de perturbation des services LDAP.
====


[#_annex_troubleshooting]
== Annexe{nbsp}: Dépannage

Si vous rencontrez des problèmes lors du test de la connexion au serveur OpenLDAP, vérifiez d'abord les identifiants saisis pour le compte de service ainsi que la configuration de la base de recherche. Vous pouvez également consulter les journaux de Rancher pour aider à identifier la cause du problème. Les journaux de débogage peuvent contenir des informations plus détaillées sur l'erreur. Veuillez vous référer à xref:faq/technical-items.adoc#_how_can_i_enable_debug_logging[Comment puis-je activer la journalisation de débogage] dans cette documentation.
