= Starten von Kubernetes auf neuen Knoten bei einem Infrastrukturprovider
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/starten-von-kubernetes-mit-rancher/neue-knoten-in-einem-infrastrukturprovider/index.adoc 
:product-path: cluster-deployment/infra-providers/infra-providers.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-rke2-config: xref:cluster-bereitstellung/Konfiguration/rke2.adoc
:url-rke2-introduction: https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html
:xref-infra-providers: xref:cluster-bereitstellung/infrastrukturprovider/infrastrukturprovider.adoc
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
:xref-manage-node-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
:xref-cluster-templates: xref:cluster-admin/manage-clusters/cluster-templates.adoc
:xref-recommended-architecture: xref:cluster-deployment/production-checklist/recommended-cluster-architecture.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rke2-config: xref:referenzanleitungen/cluster-konfiguration/rancher-server-konfiguration/rke2-cluster-konfiguration.adoc
:url-rke2-introduction: https://docs.rke2.io/
:xref-infra-providers: xref:how-to-guides/neue-benutzeranleitungen/starten-von-kubernetes-mit-rancher/neue-knoten-in-einem/infrastrukturprovider/index.adoc
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
:xref-manage-node-drivers: xref:how-to-guides/neue-benutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/über-bereitstellungstreiber/manage-node-drivers.adoc
:xref-cluster-templates: xref:how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc
:xref-recommended-architecture: xref:how-to-guides/neue-benutzeranleitungen/kubernetes-cluster-in-rancher-einrichten/checkliste-für-produktionsbereite-cluster/empfohlene-cluster-architektur.adoc
endif::[]

Wenn Sie {xref-rke2-config}#_cluster_config_file_reference[einen RKE2-Cluster erstellen] mithilfe einer Maschinenkonfiguration in Rancher erstellen, wird jeder resultierende Knotenpool in einer neuen **Maschinenpools**-Registerkarte angezeigt. Sie können die Maschinenpools wie folgt anzeigen:

. Klicken Sie auf *☰ > Cluster-Management*.
. Klicken Sie auf den Namen des RKE2-Clusters.

[#__rke2_product_name_clusters]
== {rke2-product-name} Cluster

Rancher v2.6 führt die Bereitstellung von {url-rke2-introduction}[RKE2] Cluster direkt über die Rancher-GUI ein. RKE2, auch bekannt als RKE Government, ist eine vollständig konforme Kubernetes-Distribution, deren Schwerpunkt auf Sicherheit und Compliance innerhalb der USA liegt. US-Bundesbehörden liegt.

[NOTE]
====

Für RKE2-Cluster-Vorlagen finden Sie weitere Informationen auf {xref-cluster-templates}#_rke2_cluster_template[dieser Seite].
====


[#_node_roles]
=== Knotenrollen

Die RKE2-CLI bietet zwei Rollen, `server` und `agent`, die die Kubernetes-Knotenrollen `etcd` + `controlplane` und `worker` repräsentieren. Mit der RKE2-Integration in Rancher v2.6 können RKE2-Knotenpools feinere Rollenzuweisungen darstellen, sodass die Rollen `etcd` und `controlplane` repräsentiert werden können.

Die gleiche Funktionalität zur Verwendung von `etcd`, `controlplane` und `worker` Knoten ist in der RKE2-CLI möglich, indem Flags und Knoten-Tainting verwendet werden, um zu steuern, wo Workloads und der Kubernetes-Master geplant wurden. Der Grund, warum diese Rollen nicht als erstklassige Rollen in der RKE2-CLI implementiert wurden, ist, dass RKE2 als eine Reihe von Rohbausteinen konzipiert ist, die am besten durch ein Orchestrierungssystem wie Rancher genutzt werden.

In unserer {xref-recommended-architecture}[empfohlenen Clusterarchitektur] skizzieren wir, wie viele Knoten jeder Rolle Cluster haben sollten:

* Mindestens drei Knoten mit der Rolle etcd, um den Verlust eines Knotens zu überstehen.
* Mindestens zwei Knoten mit der Rolle controlplane für hohe Verfügbarkeit der Master-Komponenten.
* Mindestens zwei Knoten mit der Rolle worker für die Neuzuweisung von Workloads bei einem Knotenausfall.
