= Rastreamento de ID de Usuário em Logs de Auditoria
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-27
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc 
:product-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc
ifeval::["{build-type}" != "community"]
:xref-enable-api-audit-log: xref:observability/logging/enable-api-audit-log.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-enable-api-audit-log: xref:how-to-guides/advanced-user-guides/enable-api-audit-log.adoc
endif::[]

Os seguintes logs de auditoria são utilizados no Rancher para rastrear eventos que ocorrem nos clusters locais e downstream:

* https://rancher.com/docs/rke/latest/en/config-options/audit-log/[Logs de Auditoria do Kubernetes]
* {xref-enable-api-audit-log}[Logs de Auditoria da API do Rancher]

Os logs de auditoria no Rancher v2.6 foram aprimorados para incluir o nome do Provedor de Identidade externo (nome comum do usuário no provedor de autenticação externo) tanto nos logs de auditoria do Rancher quanto nos logs de auditoria do Kubernetes downstream.

Antes da versão v2.6, um Administrador do Rancher não conseguia rastrear um evento nos logs de auditoria do Rancher e nos logs de auditoria do Kubernetes sem conhecer o mapeamento do nome de usuário do Provedor de Identidade externo para o userId (`u-xXXX`) utilizado no Rancher.
Para conhecer esse mapeamento, os administradores do cluster precisavam ter acesso à API do Rancher, à interface do usuário e ao cluster de gerenciamento local.

Agora, com esse recurso, um administrador de cluster downstream deve ser capaz de olhar os logs de auditoria do Kubernetes e saber qual usuário específico do Provedor de Identidade externo (IDP) realizou uma ação sem precisar visualizar nada no Rancher.
Se os logs de auditoria forem enviados para fora do cluster, um usuário do sistema de logs deve ser capaz de identificar o usuário no sistema do Provedor de Identidade externo.
Um Administrador do Rancher deve agora ser capaz de visualizar os logs de auditoria do Rancher e seguir para o log de auditoria do Kubernetes usando o nome de usuário do Provedor de Identidade externo.

[#_feature_description]
== Descrição do recurso

* Quando os logs de auditoria do Kubernetes são ativados no cluster downstream, em cada evento registrado, o nome de usuário do Provedor de Identidade externo agora é registrado para cada solicitação, no nível de "metadados".
* Quando você ativa os logs de auditoria da API do Rancher para uma instalação do Rancher, o nome de usuário do Provedor de Identidade externo também é registrado agora no `auditLog.level=0` para cada solicitação que atinge o servidor da API do Rancher, incluindo solicitações de login.
