= {rke2-product-name} Referência de Configuração do Cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-30
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.adoc 
:product-path: cluster-deployment/configuration/rke2.adoc
ifeval::["{build-type}" != "community"]
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
:xref-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/manage-persistent-storage.adoc
:xref-ds-backup-restore: xref:cluster-admin/backups-and-restore/backups-and-restore.adoc
:xref-psact: xref:security/psact.adoc
:xref-azure-machine-configuration: xref:cluster-deployment/infra-providers/azure/machine-configuration.adoc
:xref-compliance-scans-howto: xref:security/compliance-scans/how-to.adoc
:xref-digitalocean-machine-configuration: xref:cluster-deployment/infra-providers/digitalocean/machine-configuration.adoc
:xref-aws-machine-configuration: xref:cluster-deployment/infra-providers/aws/machine-configuration.adoc
:xref-about-rancher-agents: xref:cluster-deployment/about-rancher-agents.adoc
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-gce-machine-configuration: xref:cluster-deployment/infra-providers/gce/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-set-up-cloud-providers: xref:guias-de-procedimentos/guias-para-novos-usuários/clusters-kubernetes-no-rancher/configurar-provedores-de-nuvem/index.adoc
:xref-persistent-storage: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/index.adoc
:xref-ds-backup-restore: xref:getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes.adoc
:xref-psact: xref:guias-de-como/novos-usuários/guias-de-autenticação-permissões-e-configuração-global/modelos-de-configuração-psa.adoc
:xref-azure-machine-configuration: xref:guias-de-referência/configuração-do-cluster/downstream/configuração-da-máquina/azure.adoc
:xref-compliance-scans-howto: xref:how-to-guides/advanced-user-guides/compliance-scan-guides/index.adoc
:xref-digitalocean-machine-configuration: xref:guias-de-referência/configuração-do-cluster/configuração-do-cluster-downstream/configuração-da-máquina/digitalocean.adoc
:xref-aws-machine-configuration: xref:guias-de-referência/configuração-do-cluster/configuração-do-cluster-downstream/configuração-da-máquina/amazon-ec2.adoc
:xref-about-rancher-agents: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/about-rancher-agents.adoc
:xref-node-reqs: xref:como-fazer/guias-para-novos-usuários/cluster-kubernetes-na-configuração-do-rancher/requisitos-dos-nós-para-clusters-gerenciados-pelo-rancher.adoc
:xref-gce-machine-configuration: xref:guias-de-referência/configuração-do-cluster/downstream/configuração-da-máquina/google-gce.adoc
endif::[]

Esta seção abrange as opções de configuração disponíveis no Rancher para um cluster RKE2 Kubernetes novo ou existente.

[#_overview]
== Visão Geral

Você pode configurar as opções do Kubernetes de uma das duas maneiras a seguir:

* <<_configuration_options_in_the_rancher_ui,Interface do Rancher>>: Use a interface do Rancher para selecionar opções que são comumente personalizadas ao configurar um cluster Kubernetes.
* <<_cluster_config_file_reference,Arquivo de Configuração do Cluster>>: Em vez de usar a interface do Rancher para escolher opções do Kubernetes para o cluster, usuários avançados podem criar um arquivo de configuração RKE2. Usar um arquivo de configuração permite que você defina muitas https://documentation.suse.com/cloudnative/rke2/latest/en/install/configuration.html[opções] adicionais disponíveis para uma instalação RKE2.

[#_editing_clusters_in_the_rancher_ui]
== Editando clusters na Interface do Rancher

A interface do Rancher fornece duas maneiras de editar um cluster:

. Com um formulário.
. Com YAML.

[#_editing_clusters_with_a_form]
=== Editando clusters com um Formulário

O formulário abrange as opções mais frequentemente necessárias para clusters.

Para editar seu cluster,

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que você deseja configurar e clique em *⋮ > Editar Configuração*.

[#_editing_clusters_in_yaml]
=== Editando Clusters em YAML

Para uma referência completa das opções configuráveis para clusters RKE2 em YAML, consulte a https://documentation.suse.com/cloudnative/rke2/latest/en/install/configuration.html[documentação do RKE2].

Para editar seu cluster em YAML:

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que você deseja configurar e clique em *⋮ > Editar como YAML*.
. Edite as opções do RKE sob a diretiva `rkeConfig`.

[#_configuration_options_in_the_rancher_ui]
== Opções de Configuração na Interface do Rancher

[#_machine_pool_configuration]
=== Configuração do Pool de Máquinas

ifeval::["{build-type}" != "srfa"]
Esta subseção abrange configurações genéricas de pool de máquinas. Para configurações específicas de provedores de infraestrutura, consulte o seguinte:

* {xref-azure-machine-configuration}[Azure]
* {xref-digitalocean-machine-configuration}[DigitalOcean]
* {xref-aws-machine-configuration}[Amazon EC2]
* {xref-gce-machine-configuration}[Google GCE]
endif::[]
ifeval::["{build-type}" == "srfa"]
Esta subseção abrange configurações genéricas de pool de máquinas. Para configurações específicas de provedores de infraestrutura EC2, consulte o seguinte:

* {xref-aws-machine-configuration}[EC2]
endif::[]

[discrete]
[#_pool_name]
===== Nome do pool

O nome do pool de máquinas.

[discrete]
[#_machine_count]
===== Contagem de Máquinas

O número de máquinas no pool.

[discrete]
[#_roles]
===== Funções

Opção para atribuir funções de etcd, plano de controle e trabalhador aos nós.

[#_advanced]
==== Avançado

[#_auto_replace]
===== Substituição Automática

A quantidade de tempo que os nós podem ficar inacessíveis antes de serem automaticamente excluídos e substituídos.

[#_drain_before_delete]
===== Drenar Antes de Excluir

Habilita a drenagem dos nós, expulsando todos os pods antes que o nó seja excluído.

[#_kubernetes_node_labels]
===== Rótulos de Nó do Kubernetes

Adicione https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[rótulos] aos nós para ajudar na organização e seleção de objetos.

Para detalhes sobre os requisitos de sintaxe de rótulos, consulte a https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set[documentação do Kubernetes.]

[#_taints]
===== Taints

Adicione https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[taints] aos nós, para evitar que pods sejam agendados ou executados nos nós, a menos que os pods tenham tolerâncias correspondentes.

[#_cluster_configuration]
=== Configuração do Cluster

[#_basics]
==== Noções básicas

[#_kubernetes_version]
===== Kubernetes Version

A versão do Kubernetes instalada em seus nós de cluster.

Para detalhes sobre como atualizar ou reverter o Kubernetes, consulte {xref-ds-backup-restore}[Atualizando o Kubernetes].

[#_container_network_provider]
===== Provedor de Rede de Contêiner

O https://kubernetes.io/docs/concepts/cluster-administration/networking/[Provedor de Rede] que o cluster utiliza.

[CAUTION]
====

Após lançar o cluster, você não pode mudar seu provedor de rede. Portanto, escolha cuidadosamente qual provedor de rede deseja usar, pois o Kubernetes não permite a troca entre provedores de rede. Uma vez que um cluster é criado com um provedor de rede, mudar de provedores de rede exigiria que você desmontasse todo o cluster e todas as suas aplicações.
====


Por padrão, o Rancher é compatível com os seguintes provedores de rede:

* https://github.com/projectcalico/canal[Canal]
* https://cilium.io/[Cilium]*
* https://docs.projectcalico.org/v3.11/introduction/[Calico]
* https://github.com/flannel-io/flannel[Flannel]
* https://github.com/k8snetworkplumbingwg/multus-cni[Multus]

* Ao usar <<_project_network_isolation,isolamento de rede do projeto>> no xref:faq/container-network-interface-providers.adoc#_cilium[Cilium CNI], é possível habilitar o roteamento de entrada entre nós. Clique na xref:faq/container-network-interface-providers.adoc#_ingress_routing_across_nodes_in_cilium[documentação do provedor de CNI] para saber mais.

Para mais detalhes sobre os diferentes provedores de rede e como configurá-los, consulte nossa https://documentation.suse.com/cloudnative/rke2/latest/en/networking/basic_network_options.html[documentação do RKE2].

[CAUTION]
====
Ao usar `cilium` ou `multus,cilium` como seu provedor de interface de rede de contêiner, certifique-se de que a opção *Habilitar Suporte a IPv6* também esteja habilitada.
====

[#_cloud_provider]
===== Provedor de Nuvem

Você pode configurar um {xref-set-up-cloud-providers}[provedor de nuvem Kubernetes]. Se você quiser usar {xref-persistent-storage}[volumes e armazenamento] provisionados dinamicamente no Kubernetes, normalmente deve selecionar o provedor de nuvem específico para usá-lo. Por exemplo, se você quiser usar o Amazon EBS, precisará selecionar o `aws` provedor de nuvem.

[NOTE]
====

Se o provedor de nuvem que você deseja usar não estiver listado como uma opção, precisará usar a <<_cluster_config_file_reference,opção de arquivo de configuração>> para configurar o provedor de nuvem. Por favor, consulte https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/[esta documentação] sobre como configurar o provedor de nuvem.
====

[#_pod_security_admission_configuration_template]
===== Modelo de Configuração de Admissão de Segurança de Pod

O {xref-psact}[modelo de configuração de admissão de segurança de pod] padrão para o cluster.

[#_worker_compliance_profile]
===== Perfil de Conformidade do Trabalhador

Selecione um {xref-compliance-scans-howto}[padrão de conformidade] para validar a configuração do sistema.

[#_project_network_isolation]
===== Isolamento de Rede do Projeto

Se seu provedor de rede permitir isolamento de rede do projeto, você pode escolher habilitar ou desabilitar a comunicação entre projetos.

O isolamento de rede do projeto está disponível se você estiver usando qualquer plugin de rede RKE2 que suporte a aplicação de políticas de rede do Kubernetes, como o Canal.

[#_coredns]
===== CoreDNS

Por padrão, https://coredns.io/[CoreDNS] é instalado como o provedor de DNS padrão. Se o CoreDNS não estiver instalado, um provedor de DNS alternativo deve ser instalado por você mesmo. Consulte a https://documentation.suse.com/cloudnative/rke2/latest/en/networking/networking_services.html#_coredns[documentação do RKE2] para configurações adicionais do CoreDNS.

[#_ingress]
===== Ingress

[tabs]
======
Ingress-NGINX::
+
--
[WARNING]
====
*Ingress-NGINX EOL:* O controlador da comunidade `ingress-nginx` atingiu o fim do serviço (EOL) em março de 2026 e está descontinuado no RKE2 v1.36. As versões do RKE2 provisionadas pelo SUSE Rancher Prime continuarão a receber `ingress-nginx` suporte e correções de CVE (8+) durante todo o ciclo de vida do RKE2 v1.32, v1.33, v1.34, v1.35 e v1.36. Traefik é o caminho de migração recomendado para ambientes SUSE Rancher RKE2, é aconselhável migrar o mais rápido possível. Consulte https://support.scc.suse.com/s/kb/Migrating-from-Ingress-NGINX-to-Traefik-in-a-Rancher-provisioned-RKE2-Cluster?language=en_US[Migrando do Ingress NGINX para Traefik em um Cluster RKE2 provisionado pelo Rancher] para mais detalhes.
====

Esta é a opção de ingress legado para habilitar o Ingress-NGINX dentro do cluster. Consulte a https://documentation.suse.com/cloudnative/rke2/latest/en/networking/networking_services.html#_ingress_controller[documentação do RKE2] para opções de configuração adicionais.
--

Traefik::
+
--
Se você deseja expor suas aplicações em uma configuração de alta disponibilidade, e está hospedando seus nós com um provedor de nuvem que não possui um recurso nativo de balanceamento de carga, habilite esta opção para usar o Traefik Ingress dentro do cluster. Consulte a https://documentation.suse.com/cloudnative/rke2/latest/en/networking/networking_services.html#_ingress_controller[documentação do RKE2] para opções de configuração adicionais.
--
======

[#_metrics_server]
===== Servidor de Métricas

Opção para habilitar ou desabilitar o https://rancher.com/docs/rke/latest/en/config-options/add-ons/metrics-server/[Servidor de Métricas].

Cada provedor de nuvem capaz de lançar um cluster usando RKE2 pode coletar métricas e monitorar seus nós do cluster. Habilite esta opção para visualizar suas métricas de nó no portal do seu provedor de nuvem.

[#_add_on_config]
==== Configuração de Complemento

Manifests adicionais do Kubernetes, gerenciados como um https://kubernetes.io/docs/concepts/cluster-administration/addons/[complemento], a serem aplicados ao cluster na inicialização. Consulte a https://documentation.suse.com/cloudnative/rke2/latest/en/helm.html#_automatically_deploying_manifests_and_helm_charts[documentação do RKE2] para detalhes.

[#_agent_environment_vars]
==== Variáveis de Ambiente do Agente

Opção para definir variáveis de ambiente para {xref-about-rancher-agents}[agentes do Rancher]. As variáveis de ambiente podem ser definidas usando pares de chave e valor. Consulte a https://documentation.suse.com/cloudnative/rke2/latest/en/reference/linux_agent_config.html[documentação do RKE2] para mais detalhes.

[#_etcd]
==== etcd

[#_automatic_snapshots]
===== Instantâneos Automáticos

Opção para habilitar ou desabilitar instantâneos recorrentes do etcd. Se habilitado, os usuários têm a opção de configurar a frequência dos instantâneos. Para detalhes, consulte a https://documentation.suse.com/cloudnative/rke2/latest/en/backup_restore.html#_creating_snapshots[documentação do RKE2]. Observe que com o RKE2, os instantâneos são armazenados em cada nó etcd. Isso varia do RKE1, que armazena apenas um instantâneo por cluster.

[#_metrics]
===== Métricas

Opção para escolher se deve expor métricas do etcd ao público ou apenas dentro do cluster.

[#_networking]
==== Projeto de Rede

[#_cluster_cidr]
===== Cluster CIDR

CIDRs de rede IPv4 e/ou IPv6 a serem usados para IPs de pod (padrão: `10.42.0.0/16`).

Valores de exemplo:

* Somente IPv4: `10.42.0.0/16`
* Apenas IPv6: `2001:cafe:42::/56`
* Pilha dupla: `10.42.0.0/16,2001:cafe:42::/56`

Para requisitos e limitações adicionais relacionados à rede dual-stack ou apenas IPv6, consulte os seguintes recursos:

* https://documentation.suse.com/cloudnative/rke2/latest/en/networking/basic_network_options.html#_dual_stack_configuration[documentação do RKE2: Configuração de pilha dupla]
* https://documentation.suse.com/cloudnative/rke2/latest/en/networking/basic_network_options.html#_ipv6_setup[documentação do RKE2: Configuração somente IPv6]

[CAUTION]
====
* Você deve configurar o Service CIDR quando criar o cluster pela primeira vez. Você não pode habilitar o Service CIDR em um cluster existente após ele ser iniciado.
* Ao usar `cilium` ou `multus,cilium` como seu provedor de interface de rede de contêiner, certifique-se de que a opção **Habilitar Suporte a IPv6** também esteja habilitada.
====

[#_service_cidr]
===== Service CIDR

CIDRs de rede IPv4/IPv6 a serem usados para IPs de serviço (padrão: `10.43.0.0/16`).

Valores de exemplo:

* Somente IPv4: `10.43.0.0/16`
* Apenas IPv6: `2001:cafe:43::/112`
* Pilha dupla: `10.43.0.0/16,2001:cafe:43::/112`

Para requisitos e limitações adicionais relacionados à rede dual-stack ou apenas IPv6, consulte os seguintes recursos:

* https://documentation.suse.com/cloudnative/rke2/latest/en/networking/basic_network_options.html#_dual_stack_configuration[documentação do RKE2: Configuração de pilha dupla]
* https://documentation.suse.com/cloudnative/rke2/latest/en/networking/basic_network_options.html#_ipv6_setup[documentação do RKE2: Configuração somente IPv6]

[CAUTION]
====
* Você deve configurar o Service CIDR quando criar o cluster pela primeira vez. Você não pode habilitar o Service CIDR em um cluster existente após ele ser iniciado.
* Ao usar `cilium` ou `multus,cilium` como seu provedor de interface de rede de contêiner, certifique-se de que a opção **Habilitar Suporte a IPv6** também esteja habilitada.
====

[#_cluster_dns]
===== Cluster DNS

IP de cluster IPv4 para o serviço coredns. Deve estar na sua faixa de service-cidr (padrão: `10.43.0.10`).

[#_cluster_domain]
===== Domínio do Cluster

Selecione o domínio para o cluster. O padrão é `cluster.local`.

[#_nodeport_service_port_range]
===== Faixa de Portas do Serviço NodePort

Opção para alterar a faixa de portas que podem ser usadas para https://kubernetes.io/docs/concepts/services-networking/service/#nodeport[serviços NodePort]. O padrão é `30000-32767`.

[#_truncate_hostnames]
===== Truncar Nomes de Host

Opção para truncar nomes de host para 15 caracteres ou menos. Você só pode definir este campo durante a criação inicial do cluster. Você não pode habilitar ou desabilitar o limite de 15 caracteres após a criação do cluster.

Esta configuração afeta apenas clusters provisionados por máquinas. Como clusters personalizados definem nomes de host durante seu próprio processo de criação de nós, que ocorre fora do Rancher, este campo não restringe o comprimento do nome de host do cluster personalizado.

Truncar nomes de host em um cluster melhora a compatibilidade com sistemas baseados em Windows. Embora o Kubernetes permita nomes de host com até 63 caracteres, sistemas que usam NetBIOS restringem os nomes de host a 15 caracteres ou menos.

[#_tls_alternate_names]
===== Nomes Alternativos TLS

Adicione nomes de host ou endereços IPv4/IPv6 como Nomes Alternativos do Sujeito no certificado TLS do servidor.

[#_stack_preference]
===== Preferência de Pilha

Escolha a pilha de rede para o cluster. Esta opção afeta:

* O endereço usado para sondagens de saúde e prontidão de componentes como Calico, etcd, kube-apiserver, kube-scheduler, kube-controller-manager e kubelet.
* A URL do servidor no `authentication-token-webhook-config-file` para o Ponto de Extremidade do Cluster Autorizado.
* A configuração `advertise-client-urls` para etcd durante a restauração do instantâneo.

As opções são `ipv4`, `ipv6`, `dual`:

* Quando definido como `ipv4`, o cluster usa `127.0.0.1`
* Quando definido como `ipv6`, o cluster usa `[::1]`
* Quando definido como `dual`, o cluster usa `localhost`

A preferência de pilha deve corresponder à configuração de rede do cluster:

* Defina como `ipv4` para clusters apenas IPv4
* Defina como `ipv6` para clusters apenas IPv6
* Defina como `dual` para clusters de pilha dupla

[CAUTION]
====
Garantir que a configuração do endereço de loopback esteja correta é fundamental para o provisionamento bem-sucedido do cluster.
Para mais informações, consulte a página {xref-node-reqs}[Requisitos do Nó].
====

[#_authorized_cluster_endpoint]
===== Ponto de Extremidade do Cluster Autorizado

O Ponto de Extremidade do Cluster Autorizado pode ser usado para acessar diretamente o servidor API do Kubernetes, sem exigir comunicação através do Rancher.

Isso é habilitado por padrão em clusters Kubernetes lançados pelo Rancher, usando o IP do nó com o papel `controlplane` e os certificados autoassinados padrão do Kubernetes.

Para mais detalhes sobre como um endpoint de cluster autorizado funciona e por que é utilizado, consulte a seção de {xref-arch-com-ds-cluster}#_4_authorized_cluster_endpoint[arquitetura.]

Recomendamos o uso de um balanceador de carga com o endpoint de cluster autorizado. Para detalhes, consulte a seção de {xref-arch-rec}#_architecture_for_an_authorized_cluster_endpoint_ace[arquitetura recomendada.]

[#_registries]
==== Registros

Selecione o repositório de imagens para puxar imagens do Rancher. Para mais detalhes e opções de configuração, consulte a https://documentation.suse.com/cloudnative/rke2/latest/en/install/containerd_registry_configuration.html[documentação do RKE2].

[#_upgrade_strategy]
==== Estratégia de fazer upgrade

[#_control_plane_concurrency]
===== Concorrência do Plano de Controle

Selecione quantos nós podem fazer upgrade ao mesmo tempo. Pode ser um número fixo ou uma porcentagem.

[#_worker_concurrency]
===== Concorrência de Trabalhadores

Selecione quantos nós podem fazer upgrade ao mesmo tempo. Pode ser um número fixo ou uma porcentagem.

[#_drain_nodes_control_plane]
===== Drenar Nós (Plano de Controle)

Opção para remover todos os pods do nó antes de fazer upgrade.

[#_drain_nodes_worker_nodes]
===== Drenar Nós (Nós de Trabalho)

Opção para remover todos os pods do nó antes de fazer upgrade.

[#_advanced_1]
==== Avançado

Opção para definir opções do kubelet para diferentes nós. Para opções disponíveis, consulte a https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/[documentação do Kubernetes].

[#_cluster_config_file_reference]
== Referência do Arquivo de Configuração do Cluster

Editar clusters em YAML permite que você defina as https://documentation.suse.com/cloudnative/rke2/latest/en/install/configuration.html[opções disponíveis] em uma instalação do RKE2, incluindo aquelas já listadas em <<_configuration_options_in_the_rancher_ui,Opções de Configuração na UI do Rancher>>, além de definir parâmetros específicos do Rancher.+++++++++<summary>+++*Exemplo de Trecho de Arquivo de Configuração de Cluster*+++</summary>+++ ```yaml apiVersion: provisioning.cattle.io/v1 kind: Especificação do cluster: cloudCredentialSecretName: cattle-global-data:cc-s879v kubernetesVersion: v1.25.12+rke2r1 localClusterAuthEndpoint: {} rkeConfig: additionalManifest: "" chartValues: rke2-calico: {} etcd: snapshotRetention: 5 snapshotScheduleCron: 0 */5 * * * machineGlobalConfig: cni: calico disable-kube-proxy: false etcd-expose-metrics: false arquivo de controle: null kube-apiserver-arg: - audit-policy-file=/etc/rancher/rke2/user-audit-policy.yaml - audit-log-path=/etc/rancher/rke2/user-audit.logs machinePools: - controlPlaneRole: true etcdRole: true machineConfigRef: kind: Amazonec2Config name: nc-test-pool1-pwl5h name: pool1 quantity: 1 unhealthyNodeTimeout: 0s workerRole: true machineSelectorConfig: - config: protect-kernel-defaults: false machineSelectorFiles: - fileSources: - configMap: name: '' secret: name: audit-policy items: - key: audit-policy path: /etc/rancher/rke2/user-audit-policy.yaml machineLabelSelector: matchLabels: rke.cattle.io/control-plane-role: 'true' registries: {} upgradeStrategy: controlPlaneConcurrency: "1" controlPlaneDrainOptions: deleteEmptyDirData: true enabled: true gracePeriod: -1 ignoreDaemonSets: true timeout: 120 workerConcurrency: "1" workerDrainOptions: deleteEmptyDirData: true enabled: true gracePeriod: -1 ignoreDaemonSets: true timeout: 120 ```++++++

[#_additionalmanifest]
=== additionalManifest

Especifique manifestos adicionais a serem entregues aos nós do plano de controle.

O valor é uma String e será colocado no caminho `/var/lib/rancher/rke2/server/manifests/rancher/addons.yaml` nos nós de destino.

Exemplo:

[,yaml]
----
additionalManifest: |-
  apiVersion: v1
  kind: Namespace
  metadata:
    name: name-xxxx
----

[NOTE]
====

Se você quiser personalizar gráficos do sistema, deve usar o campo `chartValues` conforme descrito abaixo.

Alternativas, como usar um HelmChartConfig para personalizar os gráficos do sistema via `additionalManifest`, podem causar comportamentos inesperados, devido a ter múltiplos HelmChartConfigs para o mesmo gráfico.
====


[#_chartvalues]
=== chartValues

Especifique os valores para os gráficos do sistema instalados pelo RKE2.

Para mais informações sobre como o RKE2 gerencia componentes empacotados, consulte https://documentation.suse.com/cloudnative/rke2/latest/en/helm.html[documentação do RKE2].

Exemplo:

[,yaml]
----
chartValues:
    chart-name:
        key: value
----

[#_machineglobalconfig]
=== machineGlobalConfig

Especifique as configurações do RKE2. Qualquer alteração de configuração feita aqui se aplicará a todos os nós. As opções de configuração disponíveis na https://documentation.suse.com/cloudnative/rke2/latest/en/reference/server_config.html[versão autônoma do RKE2] podem ser aplicadas aqui.

Exemplo:

[,yaml]
----
machineGlobalConfig:
    etcd-arg:
        - key1=value1
        - key2=value2
----

Existem algumas opções de configuração que não podem ser alteradas ao provisionar via Rancher:

* data-dir (pasta para manter o estado), que por padrão é `/var/lib/rancher/rke2`.

Para facilitar a colocação de arquivos nos nós com antecedência, o Rancher espera que os seguintes valores sejam incluídos na configuração, enquanto o RKE2 espera que os valores sejam inseridos como caminhos de arquivo:

* arquivo-de-política-de-auditoria
* cloud-provider-config
* registro-privado

O Rancher entrega os arquivos para o caminho `/var/lib/rancher/rke2/etc/config-files/<option>` nos nós de destino e define as opções adequadas no servidor RKE2.

Exemplo:

[,yaml]
----
apiVersion: provisioning.cattle.io/v1
kind: Cluster
spec:
  rkeConfig:
    machineGlobalConfig:
      audit-policy-file:
        apiVersion: audit.k8s.io/v1
        kind: Policy
        rules:
        - level: RequestResponse
          resources:
          - group: ""
            resources:
            - pods
----

[#_machineselectorconfig]
=== machineSelectorConfig

`machineSelectorConfig` é o mesmo que <<_machineglobalconfig,`machineGlobalConfig`>>, exceto que um <<_kubernetes_node_labels,seletor de rótulo>> pode ser especificado com a configuração. A configuração será aplicada apenas aos nós que correspondem ao seletor de rótulo fornecido.

Várias entradas de `config` são permitidas, cada uma especificando seu próprio `machineLabelSelector`. Um usuário pode especificar `matchExpressions`, `matchLabels`, ambos ou nenhum. Omitir a seção `machineLabelSelector` deste campo tem o mesmo efeito que colocar a configuração na seção `machineGlobalConfig`.

Exemplo:

[,yaml]
----
machineSelectorConfig
  - config:
      config-key: config-value
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
----

[#_machineselectorfiles]
=== machineSelectorFiles

[NOTE]
====

Este recurso está disponível no Rancher v2.7.2 e versões posteriores.
====


Entregar arquivos aos nós, para que os arquivos possam estar disponíveis antes de iniciar os processos do servidor ou do agente RKE2.
O conteúdo do arquivo é recuperado de um segredo ou de um configmap. Os nós de destino são filtrados pelo `machineLabelSelector`.

Exemplo:

[,yaml]
----
machineSelectorFiles:
  - fileSources:
      - secret:
          items:
            - key: example-key
              path: path-to-put-the-file-on-nodes
              permissions: 644 (optional)
              hash: base64-encoded-hash-of-the-content (optional)
          name: example-secret-name
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
  - fileSources:
      - configMap:
          items:
            - key: example-key
              path: path-to-put-the-file-on-nodes
              permissions: 644 (optional)
              hash: base64-encoded-hash-of-the-content (optional)
          name: example-configmap-name
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
----

O segredo ou configmap deve atender aos seguintes requisitos:

. Deve estar no namespace `fleet-default` onde o objeto Cluster existe.
. Deve ter a anotação `rke.cattle.io/object-authorized-for-clusters: cluster-name1,cluster-name2`, que permite que os clusters de destino o utilizem.

[TIP]
====

O Rancher Dashboard fornece um formulário fácil de usar para criar o segredo ou configmap.
====


Exemplo:

[,yaml]
----
apiVersion: v1
data:
  audit-policy: >-
    IyBMb2cgYWxsIHJlcXVlc3RzIGF0IHRoZSBNZXRhZGF0YSBsZXZlbC4KYXBpVmVyc2lvbjogYXVkaXQuazhzLmlvL3YxCmtpbmQ6IFBvbGljeQpydWxlczoKLSBsZXZlbDogTWV0YWRhdGE=
kind: Secret
metadata:
  annotations:
    rke.cattle.io/object-authorized-for-clusters: cluster1
  name: name1
  namespace: fleet-default
----
