= Création d'un cluster Google Compute Engine
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: guides-procédures/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/créer-un-cluster-google-compute-engine.adoc 
:product-path: cluster-deployment/infra-providers/gce/gce.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-infra-gce-machine-config: xref:cluster-deployment/infra-providers/gce/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:guides-de-référence/configuration-de-cluster/configuration-du-serveur-rancher/configuration-du-cluster-rke2.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:guides-de-référence/configuration-de-cluster/configuration-du-serveur-rancher/configuration-du-cluster-k3s.adoc
:xref-infra-gce-machine-config: xref:guides-de-référence/configuration-cluster/configuration-cluster-en-aval/configuration-machine/google-gce.adoc
endif::[]

Dans cette section, vous apprendrez à utiliser Rancher pour provisionner un {url-rke2-landing-page}[RKE2] ou {url-k3s-landing-page}[K3s] cluster Kubernetes sur Google Cloud Platform (GCP) en utilisant Google Compute Engine (GCE) via Rancher.

Tout d'abord, vous activerez le pilote de nœud GCE dans l'interface utilisateur de Rancher. Ensuite, vous suivrez les étapes pour créer un compte de service GCP avec les autorisations nécessaires et générer un fichier de clé JSON. Ce fichier de clé sera utilisé pour créer un identifiant cloud dans Rancher. 

Ensuite, vous créerez un cluster GCE dans Rancher, et lors de la configuration du cluster, vous définirez des pools de machines pour celui-ci. Chaque pool de machines aura un rôle Kubernetes d'etcd, de controlplane ou de worker. Rancher installera RKE2 sur les nouveaux nœuds, et il configurera chaque nœud avec le rôle Kubernetes défini par le pool de machines.

. <<_enable_the_gce_node_driver>>
. <<_create_a_cloud_credential>>
. <<_create_a_cluster_using_the_cloud_credential>>
. <<_gce_best_practices>>

[#_prerequisites]
== Conditions préalables

.  Un compte et un projet Google Cloud Platform valides.
.  Un fichier de clé JSON de compte de service GCP. Le compte de service associé à cette clé doit avoir les rôles IAM suivants{nbsp}:
.. **Administrateur Compute**
.. **Utilisateur de compte de service**
.. **Visionneuse**
. Un réseau VPC pour provisionner des VM. 

Consultez la https://cloud.google.com/iam/docs/service-account-overview[documentation GCP] sur la création et la gestion des clés de compte de service pour plus de détails.

[#_enable_the_gce_node_driver]
== Activer le pilote de nœud GCE

Le pilote de nœud GCE n'est pas activé par défaut dans Rancher. Vous devez l'activer avant de pouvoir provisionner des clusters GCE ou travailler avec des CRD spécifiques à GCE.

. Cliquez sur **☰ > Gestion des clusters**.
. Sur le côté gauche, cliquez sur **Drivers**.
. Ouvrez l'onglet **Node Drivers**.
. Trouvez le pilote **Google GCE** et sélectionnez **⋮ > Activer**.

[#_create_a_cloud_credential]
== Créez un identifiant cloud

. Cliquez sur **☰ > Gestion des clusters**.
. Cliquez sur **Identifiants cloud**.
. Cliquez sur **Créer**.
. Click **Google**.
. Entrez votre fichier de clé JSON de compte de service GCP.
. Cliquez sur **Créer**.

**Résultat :** Vous avez créé les identifiants cloud qui seront utilisés pour provisionner des nœuds dans votre cluster. Vous pouvez réutiliser ces identifiants dans d'autres clusters. En fonction des autorisations accordées au compte de service, cet identifiant peut également être utilisé pour des clusters GKE.

[#_create_a_cluster_using_the_cloud_credential]
== Créez un cluster en utilisant l'identifiant cloud

. Cliquez sur **☰ > Gestion des clusters**.
. Sur la page **Clusters**, cliquez sur **Créer**.
. Click **Google GCE**.
. Sélectionnez un **Identifiant Cloud** et fournissez le projet GCP pour créer la VM.
. Entrez un **Nom de cluster**.
. Créez un pool de machines pour chaque rôle Kubernetes. Référez-vous aux [meilleures pratiques](use-new-nodes-in-an-infra-provider.md#node-roles) pour des recommandations sur les attributions de rôles et les quantités.
.. Pour chaque pool de machines, définissez la configuration de la machine. Référez-vous à la {xref-infra-gce-machine-config}[référence de configuration des machines Google GCE] pour des informations sur les options de configuration.
. Utilisez la **Configuration du Cluster** pour choisir la version de Kubernetes qui sera installée, quel fournisseur de réseau sera utilisé et si vous souhaitez activer l'isolement réseau des projets. Pour obtenir de l'aide sur la configuration du cluster, référez-vous aux {xref-rke2-config}[références de configuration du RKE2] et {xref-k3s-config}[K3s].
. Utilisez les **Rôles de membre** pour configurer l'autorisation des utilisateurs pour le cluster. Cliquez sur **Ajouter un membre** pour ajouter des utilisateurs pouvant accéder au cluster. Utilisez le menu déroulant **Rôle** pour définir les permissions pour chaque utilisateur.
. Cliquez sur **Créer**.

**Résultat :**

Votre cluster est créé et a un état de **Provisionnement**. Rancher est en train de mettre en place votre cluster.

Vous pouvez accéder à votre cluster après que son état soit mis à jour à **Actif**.

Les clusters **Actifs** sont assignés à deux projets{nbsp}:

* `Default`, contenant l'espace de noms `default`
* `System`, contenant les espaces de noms `cattle-system`, `traefik`, `kube-public` et `kube-system`

[#_gce_best_practices]
== Meilleures pratiques GCE

[#_external_firewall_rules_open_ports_and_ace]
=== Règles de passerelle de périmètre de sécurité externes, ports ouverts et ACE

Si le cluster en cours de provisionnement utilisera la {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[fonctionnalité de point de terminaison de cluster autorisé (ACE)], les nœuds de contrôle doivent exposer le port `6443`. Ce port n'est pas exposé dans la configuration par défaut du pool de machines pour éviter qu'il ne soit exposé sur tous les nœuds du cluster, et pour réduire le nombre de règles de passerelle de périmètre de sécurité créées par Rancher.

Pour que l'ACE fonctionne comme prévu, vous devez spécifier ce port dans l'interface utilisateur de Rancher lors de la configuration du pool de machines de contrôle en activant la case à cocher `Expose external ports`, sous la section `Show Advanced` de l'interface de configuration du pool de machines. Alternativement, vous pouvez créer manuellement une règle de passerelle de périmètre de sécurité personnalisée dans GCP et fournir le tag réseau associé dans la configuration du pool de machines de contrôle.

[#_internal_firewall_rules]
=== Règles de passerelle de périmètre de sécurité internes

Rancher créera automatiquement une règle de passerelle de périmètre de sécurité et un tag réseau pour faciliter la communication entre les nœuds du cluster en interne au sein du réseau VPC spécifié. Cette règle contiendra le nombre minimum de ports requis pour créer un cluster RKE2/K3s.

Si vous devez étendre le nombre de ports exposés en interne entre les nœuds du cluster, une nouvelle règle de passerelle de périmètre de sécurité doit être créée manuellement, et le tag réseau associé doit être attribué aux pools de machines concernés. Si vous le souhaitez, la création automatique de la règle de passerelle de périmètre de sécurité interne peut être désactivée pour chaque pool de machines donné lors de la création ou de la mise à jour du cluster.

[#_cross_network_deployments]
=== Déploiements inter-réseaux

Bien qu'il soit possible de déployer différents pools de machines dans différents réseaux VPC, la règle de passerelle de périmètre de sécurité interne créée par Rancher ne prend pas en charge cette configuration par défaut. Pour créer des pools de machines dans différents réseaux, des règles de passerelle de périmètre de sécurité supplémentaires doivent être créées manuellement pour faciliter la communication entre les nœuds dans différents réseaux.

[#_optional_next_steps]
== Étapes suivantes optionnelles

Après avoir créé votre cluster, vous pouvez y accéder via l'interface utilisateur de Rancher. En tant que meilleure pratique, nous recommandons de mettre en place ces méthodes alternatives pour accéder à votre cluster{nbsp}:

* **Accédez à votre cluster avec la CLI kubectl :** Suivez {xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[ces étapes] pour accéder aux clusters avec kubectl sur votre station de travail. Dans ce cas, vous serez authentifié via le proxy d'authentification du serveur Rancher, puis Rancher vous connectera au cluster en aval. Cette méthode vous permet de gérer le cluster sans l'interface utilisateur de Rancher.
* **Accédez à votre cluster avec la CLI kubectl, en utilisant le point de terminaison de cluster autorisé :** Suivez {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[ces étapes] pour accéder directement à votre cluster avec kubectl, sans vous authentifier via Rancher. Nous recommandons de mettre en place cette méthode alternative pour accéder à votre cluster afin que, dans le cas où vous ne pouvez pas vous connecter à Rancher, vous puissiez toujours accéder au cluster.
