= 3.安装 {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-21
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-rancher.adoc 
:product-path: installation-and-upgrade/other-installation-methods/http-proxy/install-rancher.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-tls-secrets: xref:installation-and-upgrade/resources/tls-secrets.adoc
:xref-install-upgrade-troubleshooting: xref:installation-and-upgrade/troubleshooting/troubleshooting.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-tls-secrets: xref:getting-started/installation-and-upgrade/resources/add-tls-secrets.adoc
:xref-install-upgrade-troubleshooting: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/troubleshooting.adoc
endif::[]


现在您已经有一个运行中的 RKE2/K3s 集群，您可以在其中安装 Rancher。出于安全原因，所有到 Rancher 的流量必须使用 TLS 加密。在本教程中，您将通过 https://cert-manager.io/[cert-manager] 自动颁发自签名证书。在实际使用案例中，您可能会使用 Let's Encrypt 或提供自己的证书。

[#_install_the_helm_cli]
== 安装 Helm CLI

在您有 kubeconfig 以访问 Kubernetes 集群的主机上安装 https://helm.sh/docs/intro/install/[Helm] CLI：

----
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod +x get_helm.sh
sudo ./get_helm.sh
----

[#_install_cert_manager]
== 安装 cert-manager

添加 cert-manager Helm 储存库：

----
helm repo add jetstack https://charts.jetstack.io
----

为 cert-manager 创建一个名称空间：

----
kubectl create namespace cert-manager
----

安装 cert-manager 的 CustomResourceDefinitions：

----
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/<VERSION>/cert-manager.crds.yaml
----

并使用 Helm 安装它。请注意，cert-manager 还需要您的代理配置，以便在需要与 Let's Encrypt 或其他外部证书颁发机构通信时使用：

[NOTE]
====

要查看如何自定义 cert-manager 安装的选项（包括在集群使用 PodSecurityPolicies 的情况下），请参阅 https://artifacthub.io/packages/helm/cert-manager/cert-manager#configuration[cert-manager 文档]。
====


----
helm upgrade --install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --set http_proxy=http://${proxy_host} \
  --set https_proxy=http://${proxy_host} \
  --set no_proxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local
----

现在您应该等待 cert-manager 启动完成：

----
kubectl rollout status deployment -n cert-manager cert-manager
kubectl rollout status deployment -n cert-manager cert-manager-webhook
----

[#_install_rancher_product_name]
== 安装 {rancher-product-name}

接下来，您可以安装 {rancher-product-name} 本身。首先，添加 Helm 储存库：

[sh,subs="attributes+"]
----
helm repo add {rancher-helm-repo} <helm-chart-repo-url>
----

ifeval::["{build-type}" == "product"]
include::shared:ROOT:partial$en/helm-chart-repo-url.adoc[]
endif::[]

创建一个名称空间：

----
kubectl create namespace cattle-system
----

并使用 Helm 安装 Rancher。Rancher 还需要代理配置，以便能够与外部应用程序目录通信或检索 Kubernetes 版本更新元数据：

[sh,subs="attributes+"]
----
helm 升级 --安装 rancher {rancher-helm-repo}/rancher \
   --名称空间 cattle-system \
   --设置主机名=rancher.example.com \
   --设置代理=http://${proxy_host} \
   --设置 noProxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local
----

等待部署完成后：

----
kubectl rollout status deployment -n cattle-system rancher
----

您现在可以导航到 `https://rancher.example.com` 并开始使用 Rancher。

[#_additional_resources]
== 其他资源

这些资源在安装 Rancher 时可能会有所帮助：

* {xref-helm-chart-options}[Rancher Helm 图表选项]
* {xref-tls-secrets}[添加 TLS 秘密]
* {xref-install-upgrade-troubleshooting}[故障排除 Rancher Kubernetes 安装]
