= {neuvector-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/neuvector/index.adoc 
:product-path: integrations/neuvector/neuvector.adoc

O NeuVector é a única plataforma de segurança de contêiner 100% de código aberto e Zero Trust. Escaneie continuamente durante todo o ciclo de vida do contêiner. Remova obstáculos de segurança. Incorpore políticas de segurança desde o início para maximizar a agilidade dos desenvolvedores. O NeuVector fornece escaneamento e gerenciamento de vulnerabilidades e conformidade desde a construção até a produção. A proteção em tempo de execução única do NeuVector protege conexões de rede dentro do cluster e a entrada/saída para o cluster com um gateway de segurança de contêineres de camada 7. Além disso, o NeuVector monitora a atividade de processos e arquivos em contêineres e em hosts para parar atividades não autorizadas.

[#__neuvector_product_name_with_rancher]
== {neuvector-product-name} com o Rancher

Todos os recursos do NeuVector estão disponíveis através do Rancher com implantação integrada e autenticação única no console do NeuVector. Os administradores do cluster Rancher podem implantar e gerenciar a implantação do NeuVector em seus clusters e configurar facilmente o NeuVector através de valores Helm, configMaps, definições de recursos personalizados (CRDs) e o console do NeuVector.

Com o NeuVector e o Rancher:

* Implante, gerencie e proteja múltiplos clusters.
* Gerencie e relate vulnerabilidades e resultados de conformidade para cargas de trabalho e nós do Rancher.

[#__neuvector_product_name_prime_with_rancher_prime]
== {neuvector-product-name} Prime com {rancher-prime}

A Extensão da UI do NeuVector para o Gerenciador Rancher está disponível e suportada para clientes do Rancher Prime e NeuVector Prime. Esta extensão fornece:

* Implantação automatizada do NeuVector, incluindo o painel da Extensão NeuVector do Rancher Prime.
* Acesso a informações de segurança importantes de cada cluster, como eventos de segurança críticos, resultados de escaneamento de vulnerabilidades e exposições de entrada/saída.
* Resultados de escaneamento de vulnerabilidades (CVE) e conformidade integrados diretamente nos recursos do Rancher, como nós e contêineres/pods.
* Ações integradas, como acionamentos manuais de escaneamentos em recursos do Rancher.
