== Icons & Symbols

☰:: The navigation menu toggle, a button in the far top left corner of the Rancher UI. Clicking the ☰ opens a sidebar that provides access to the main sections of the Rancher interface.

⋮:: The submenu toggle, a button found at the far right of many table rows throughout the Rancher UI. Clicking the ⋮ opens a submenu containing a contextual list of tasks related to the item in that row.

== A

Apps::
+
*Versions:* Rancher v2.6.5 and later When describing navigation within Rancher, the section of the Rancher UI where you manage Helm charts and Helm chart repositories. In earlier versions of Rancher, this section was called _Apps & Marketplace_, or _Catalogs_.
+
*Synonyms:* _Apps & Marketplace, Catalogs_

Apps & Marketplace::
+
*Versions:* Rancher v2.5.0--2.6.5 The section of the Rancher UI where you manage Helm charts and Helm chart repositories. In earlier versions of Rancher, this section was called _Catalogs_. In later versions, it is called _Apps_.
+
*Synonyms:* _Apps, Catalogs_

== C

Catalogs::
+
*Versions:* 1. Rancher v2.4 and earlier 2. Rancher v2.7 and later The section of the Rancher UI where you manage Helm charts and Helm chart repositories. In later versions of Rancher, this section is called _Apps & Marketplace_, or _Apps_.
+
*Synonyms:* _Apps, Apps & Marketplace_
+
*Related terms:* _Extension catalogs_

Community:: A build of Rancher that's available to the entire Rancher community.
+
*Related terms:* _Prime, Rancher Prime_

== D

Downstream cluster:: An alternative name for a _managed cluster_, a Kubernetes cluster that is managed by a Rancher server.
+
*Synonyms:* _Managed cluster_
+
*Related terms:* _Hosted cluster, Imported cluster, Rancher server, Registered cluster, Upstream cluster_

== E

Extension::
+
*Versions:* Rancher v2.7.0 and later Helm charts that can extend and enhance the Rancher UI, and tailor Rancher to your specific environment. Some Extensions require manual installation on a cluster, while others are built into Rancher. Built-in Extensions include Fleet and Harvester. Manually installed Extensions include Kubewarden and Elemental.
+
*Related terms:* _Apps & Marketplace, Catalogs, Integrations_

Extension catalogs::
+
*Versions:* Rancher v2.7.0 and later Container image repositories that can be imported to add UI extensions to your Rancher instance.

== H

Hosted cluster:: A managed cluster that is hosted in the cloud, by a Kubernetes provider. Rancher supports a variety of hosted Kubernetes providers, including Amazon Elastic Kubernetes Service (EKS), Azure Kubernetes Service (AKS), and Google Kubernetes Engine (GKE). Rancher integrates with the hosted Kubernetes provider's cloud APIs, so that you can manage the cluster from the Rancher UI.
+
*Related terms:* _Downstream cluster, Imported cluster, Managed cluster, Registered cluster_

== I

Imported cluster::
+
*Versions:* Rancher v2.0--2.4 An existing cluster that was provisioned by a third party, then set up to be managed by Rancher. _Registered clusters_ in later versions of Rancher are roughly synonymous with imported clusters. The main difference is that there are more management features exposed in the Rancher UI for registered clusters than for imported clusters.
+
*Related terms:* _Downstream cluster, Hosted cluster, Managed cluster, Reistered cluster_

== K

K3s:: A lightweight Kubernetes distribution chiefly designed for workloads that run unattended under tight resource constraints.
+
*Related terms:* _RKE, RKE2_

== L

Local cluster:: An alternative name for a _Rancher server_, the Kubernetes cluster that hosts Rancher and manages other clusters. Here, _local_ refers to the location of the Rancher installation, not to the user's local workstation. Local clusters can be hosted on-premises, in air-gapped environments, or in the cloud.
+
*Synonyms:* _Rancher server, Upstream cluster_
+
*Related terms:* _Downstream cluster, Hosted cluster, Imported cluster, Managed cluster, Registered cluster_

== M

Managed cluster:: A Kubernetes cluster that is managed by a Rancher server. Managed clusters can run on a variety of infrastructure and can be located anywhere, including in the cloud, on-premises, or in air-gapped environments.
+
*Synonyms:* _Downstream cluster_
+
*Related terms:* _Hosted cluster, Imported cluster, Rancher server, Registered cluster_

== R

Rancher:: A Kubernetes management tool to deploy and run clusters anywhere and on any provider. Rancher includes all the software and downstream cluster components used to manage the entire Rancher deployment.

Rancher Kubernetes Engine (RKE):: A CNCF-certified Kubernetes distribution that runs entirely within Docker containers. There are two main versions of RKE available. The 1.x software line is sometimes called _RKE1_, or simply _RKE_. The next-generation line is called _RKE2_.
+
*Synonyms:* _RKE1_
+
*Related terms:* _K3s, RKE2_

Rancher Prime:: Rancher Prime is a new edition of the commercial, enterprise offering built on the the same source code. Installation assets are hosted on a trusted registry owned and managed by Rancher with additional value coming in from security assurances, extended lifecycles, access to focused architectures and Kubernetes advisories.

Rancher server:: The Kubernetes cluster that hosts Rancher and manages the other clusters in the Rancher deployment.
+
*Synonyms:* _Local cluster, Upstream cluster_
+
*Related terms:* _Downstream cluster, Hosted cluster, Imported cluster, Managed cluster, Registered cluster_

Registered cluster::
+
*Versions:* Rancher v2.5 and later An existing cluster that was provisioned by a third party, then set up to be managed by Rancher. Older versions of Rancher use _Imported cluster_ to refer to a similar concept. The main difference is that there are more management features exposed in the Rancher UI for registered clusters than for imported clusters.
+
*Related terms:* _Downstream cluster, Hosted cluster, Imported cluster, Managed cluster_

RKE1:: An alternative name for the v1.x software line of _Rancher Kubernetes Engine (RKE)_. Sometimes called _RKE_ for short. RKE1 is a certified Kubernetes distribution and CLI/library which creates and manages a Kubernetes cluster.
+
*Synonyms:* _Rancher Kubernetes Engine_
+
*Related terms:* _K3s, RKE2_

RKE2::
+
*Versions:* Rancher v2.6.0 and later (to provision clusters), Rancher 2.5.0 and later (to register clusters) A fully conformant version of the Rancher Kubernetes Engine (RKE) that is designed for security and compliance with US federal government standards.
+
*Related terms:* _K3s, RKE_

Roles:: Roles determine what actions a Rancher user can make within a cluster or project.

== U

Upstream cluster:: An alternative name for the _Rancher server_, the Kubernetes cluster that hosts Rancher and manages the other clusters in the Rancher deployment.
+
*Synonyms:* _Local cluster, Rancher server_
+
*Related terms:* _Downstream cluster, Hosted cluster, Imported cluster, Managed cluster, Registered cluster_

== W

Workload:: Objects that set deployment rules for pods. Based on these rules, Kubernetes performs the deployment and updates the workload with the current state of the application. Workloads let you define the rules for application scheduling, scaling, and upgrade.
