= Configuração do Modelo de Nó EC2
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: guias-de-referência/configuração-do-cluster/configuração-do-cluster-downstream/configuração-do-modelo-de-nó/amazon-ec2.adoc 
:product-path: cluster-deployment/infra-providers/aws/node-template-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
:xref-infra-aws: xref:cluster-deployment/infra-providers/aws/aws.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-set-up-cloud-providers: xref:guias-de-procedimentos/guias-para-novos-usuários/clusters-kubernetes-no-rancher/configurar-provedores-de-nuvem/index.adoc
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
:xref-infra-aws: xref:guias-de-procedimentos/guias-para-novos-usuários/lançar-kubernetes-com-rancher/usar-novos-nós-em-um-provedor-infra/criar-um-cluster-amazon-ec2.adoc
endif::[]

Para mais detalhes sobre EC2 e nós, consulte a documentação oficial para o https://aws.amazon.com/ec2[Console de Gerenciamento do EC2].

[#_region]
== Região

No campo *Região*, selecione a mesma região que você usou ao criar suas credenciais de nuvem.

[#_cloud_credentials]
== Credenciais de Nuvem

As informações de acesso da sua conta AWS, armazenadas em uma {xref-cloud-credentials}[credencial de nuvem.]

Veja https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey[Documentação da Amazon: Criando Chaves de Acesso] como criar uma Chave de Acesso e Chave Secreta.

Veja https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html#access_policies_create-start[Documentação da Amazon: Criando Políticas IAM (Console)] como criar uma política IAM.

Veja https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_change-permissions.html#users_change_permissions-add-console[Documentação da Amazon: Adicionando Permissões a um Usuário (Console)] como anexar uma política IAM.

Veja nossas três políticas JSON de exemplo.

* {xref-infra-aws}#_exemplo_politica_iam[Exemplo de Política IAM].
* {xref-infra-aws}#_exemplo_politica_iam_com_passrole[Exemplo de Política IAM com PassRole] (necessário se você quiser usar {xref-set-up-cloud-providers}[Provedor de Nuvem Kubernetes] ou quiser passar um Perfil IAM para uma instância).
* {xref-infra-aws}#_exemplo_politica_iam_para_permitir_volumes_ebs_encriptados[Exemplo de Política IAM para permitir volumes EBS encriptados] para um usuário.

[#_authenticate_configure_nodes]
== Autenticar e Configurar Nós

Escolha uma zona de disponibilidade e configurações de rede para seu cluster.

[#_security_group]
== Grupo de Segurança

Escolha o grupo de segurança padrão ou configure um grupo de segurança.

Por favor, consulte {xref-port-reqs}#_rancher_aws_ec2_security_group[grupo de segurança do Amazon EC2 ao usar o Driver de Nó] para ver quais regras são criadas no `rancher-nodes` Grupo de Segurança.

Se você fornecer seu próprio grupo de segurança para uma instância EC2, observe que o Rancher não o modificará. Assim, você será responsável por garantir que seu grupo de segurança esteja configurado para permitir os {xref-port-reqs}#_ports_for_rancher_server_nodes_on_rke2[portas necessárias para o Rancher provisionar a instância]. Para mais informações sobre como controlar o tráfego de entrada e saída para instâncias EC2 com grupos de segurança, consulte https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#WorkingWithSecurityGroups[aqui].

[#_instance_options]
== Opções de Instância

Configure as instâncias que serão criadas. Certifique-se de configurar o *Usuário SSH* correto para a AMI configurada. É possível que uma região selecionada não suporte o tipo de instância padrão. Nesse cenário, você deve selecionar um tipo de instância que realmente exista, caso contrário, ocorrerá um erro informando que a configuração solicitada não é suportada.

Se você precisar passar um *Nome do Arquivo de Controle de Instância IAM* (não ARN), por exemplo, quando quiser usar um {xref-set-up-cloud-providers}[Provedor de Nuvem Kubernetes], você precisará de uma permissão adicional em sua política. Veja {xref-infra-aws}#_exemplo_politica_iam_com_passrole[Exemplo de política IAM com PassRole] para um exemplo de política.

[#_engine_options]
== Opções de Motor

Na seção *Opções de Motor* do modelo de nó, você pode configurar o daemon de contêiner. Você pode querer especificar a versão do contêiner ou um espelho de registro de imagem de contêiner.
