= Cluster- und Projektrollen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-02-11
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/authentifizierungsberechtigungen-und-global-konfiguration/rollenbasierte-zugriffskontrolle-rbac/cluster-und-projektrollen.adoc 
:product-path: rancher-admin/benutzer/authn-und-authz/rollenbasierte-zugriffskontrolle-rbac/cluster-und-projektrollen.adoc
ifeval::["{build-type}" != "community"]
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-psa-pss: xref:security/psa-pss.adoc
:xref-locked-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-psa-pss: xref:how-to-guides/neue-benutzeranleitungen/authentifizierungsberechtigungen-und-global-konfiguration/pod-sicherheitsstandards.adoc
:xref-custom-roles: xref:how-to-guides/neue-benutzeranleitungen/authentifizierungsberechtigungen-und-global-konfiguration/rollenbasierte-zugriffskontrolle-rbac/benutzerdefinierte-rollen.adoc
:xref-locked-roles: xref:how-to-guides/neue-benutzeranleitungen/authentifizierungsberechtigungen-und-global-konfiguration/rollenbasierte-zugriffskontrolle-rbac/gesperrte-rollen.adoc
endif::[]

Cluster- und Projektrollen definieren die Benutzerautorisierung innerhalb eines Clusters oder Projekts.

Um diese Rollen zu verwalten,

. Klicken Sie auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie in der linken Navigationsleiste auf *Rollenvorlagen* und gehen Sie zur *Cluster* oder zur *Projekt/Namensräume* Registerkarte.

[#_membership_and_role_assignment]
== Mitgliedschaft und Rollenvergabe

Die Projekte und Cluster, auf die nicht-administrative Benutzer zugreifen können, werden durch die _Mitgliedschaft_ bestimmt. Die Mitgliedschaft ist eine Liste von Benutzern, die basierend auf den Rollen, die ihnen in diesem Cluster oder Projekt zugewiesen wurden, Zugriff auf ein bestimmtes Cluster oder Projekt haben. Jedes Cluster und Projekt enthält eine Registerkarte, die ein Benutzer mit den entsprechenden Berechtigungen nutzen kann, um die Mitgliedschaft zu verwalten.

Wenn Sie ein Cluster oder Projekt erstellen, weist Rancher Ihnen automatisch die Rolle des `Owner` dafür zu. Benutzer, die die Rolle `Owner` zugewiesen bekommen haben, können anderen Benutzern Rollen im Cluster oder Projekt zuweisen.

[NOTE]
====

Nicht-administrative Benutzer können standardmäßig nicht auf vorhandene Projekte/Cluster zugreifen. Ein Benutzer mit den entsprechenden Berechtigungen (typischerweise der Eigentümer) muss die Projekt- und Cluster-Mitgliedschaft ausdrücklich zuweisen.
====


[#_cluster_roles]
== Cluster-Rollen

_Cluster-Rollen_ sind Rollen, die Sie Benutzern zuweisen können, um ihnen Zugriff auf ein Cluster zu gewähren. Es gibt zwei primäre Cluster-Rollen: `Owner` und `Member`.

* *Cluster-Eigentümer:*
+
Diese Benutzer haben die volle Kontrolle über das Cluster und alle darin enthaltenen Ressourcen.

* *Cluster-Mitglied:*
+
Diese Benutzer können die meisten Ressourcen auf Cluster-Ebene einsehen und neue Projekte erstellen.
+
[WARNING]
====
Wenn ein Cluster-Mitglied ein Projekt erstellt, wird dem Benutzer automatisch <<Project Roles,Projekt-Eigentümerrechte>> zugewiesen. Dies gewährt ihnen umfassende Kontrolle über das Projekt und die damit verbundenen Ressourcen, einschließlich der Berechtigungen, Arbeitslasten bereitzustellen. Ohne durchgesetzte {xref-psa-pss}[Pod-Sicherheitsstandards (PSS) und Pod-Sicherheitszulassung (PSA)] kann ein Cluster-Mitglied privilegierte Container im Cluster ausführen.
====

[#_custom_cluster_roles]
=== Benutzerdefinierte Cluster-Rollen

Rancher ermöglicht es Ihnen, _benutzerdefinierte Cluster-Rollen_ einem Standardbenutzer anstelle der typischen `Owner` oder `Member` Rollen zuzuweisen. Diese Rollen können entweder eine integrierte benutzerdefinierte Cluster-Rolle oder eine von einem Rancher-Administrator definierte Rolle sein. Sie sind praktisch, um engen oder spezialisierten Zugriff für einen Standardbenutzer innerhalb eines Clusters zu definieren. Siehe die Tabelle unten für eine Liste der integrierten benutzerdefinierten Cluster-Rollen.

[#_cluster_role_reference]
=== Cluster-Rollen-Referenz

Die folgende Tabelle listet jede integrierte benutzerdefinierte Cluster-Rolle auf, die verfügbar ist, und ob dieses Zugriffslevel in den Standardberechtigungen auf Cluster-Ebene, `Cluster Owner` und `Cluster Member`, enthalten ist.

|===
| Integrierte Cluster-Rolle | Besitzer | Mitglied +++<a id="clus-roles">++++++</a>+++

| Projekte erstellen
| ✓
| ✓

| Cluster-Sicherungen verwalten
| ✓
|

| Cluster-Kataloge verwalten
| ✓
|

| Cluster-Mitglieder verwalten
| ✓
|

| Knoten verwalten <<_manage_nodes_permissions,(siehe Tabelle unten)>>
| ✓
|

| Speicher verwalten
| ✓
|

| Alle Projekte anzeigen
| ✓
|

| Cluster-Kataloge anzeigen
| ✓
| ✓

| Cluster-Mitglieder anzeigen
| ✓
| ✓

| Knoten anzeigen
| ✓
| ✓
|===

[#_manage_nodes_permissions]
=== Berechtigungen für Knoten verwalten

Die folgende Tabelle listet die für die Rolle `Manage Nodes` in RKE und RKE2 verfügbaren Berechtigungen auf.

|===
| Berechtigungen für Knoten verwalten | RKE | RKE2

| SSH-Zugriff
| ✓
| ✓

| Knoten löschen
| ✓
| ✓

| Cluster hoch- und herunterskalieren
| ✓
| *
|===

*In RKE2 müssen Sie die Berechtigung haben, einen Cluster zu bearbeiten, um Cluster hoch- und herunterskalieren zu können.*

Für Details, wie jede Cluster-Rolle auf Kubernetes-Ressourcen zugreifen kann, können Sie diese in der Rancher UI nachschlagen:

. Klicken Sie in der oberen linken Ecke auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie in der linken Navigationsleiste auf *Rollenvorlagen*.
. Klicken Sie auf die Registerkarte *Cluster*.
. Klicken Sie auf den Namen einer einzelnen Rolle. Die Tabelle zeigt alle Operationen und Ressourcen, die von der Rolle erlaubt sind.

[NOTE]
====

Beim Anzeigen der mit den Standardrollen, die von Rancher erstellt wurden, verbundenen Ressourcen, wird, wenn mehrere Kubernetes-API-Ressourcen in einem einzelnen Listeneintrag vorhanden sind, `(Custom)` an die Ressource angehängt. Dies sind keine benutzerdefinierten Ressourcen, sondern lediglich ein Hinweis darauf, dass es mehrere Kubernetes-API-Ressourcen als eine Ressource gibt.
====


[#_giving_a_custom_cluster_role_to_a_cluster_member]
== Einem Cluster-Mitglied eine benutzerdefinierte Cluster-Rolle zuweisen

Nachdem ein Administrator {xref-custom-roles}[eine benutzerdefinierte Cluster-Rolle eingerichtet hat,] können Clusterbesitzer und -administratoren diese Rollen dann Cluster-Mitgliedern zuweisen.

Um einem neuen Cluster-Mitglied eine benutzerdefinierte Rolle zuzuweisen, können Sie die Rancher-Benutzeroberfläche verwenden. Um die Berechtigungen eines bestehenden Mitglieds zu ändern, müssen Sie die Rancher-API-Ansicht verwenden.

Um die Rolle einem neuen Cluster-Mitglied zuzuweisen,

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie einem Mitglied eine Rolle zuweisen möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie auf menu:Cluster[Cluster-Mitglieder].
. Klicken Sie auf *Hinzufügen*.
. Wählen Sie im Abschnitt *Clusterberechtigungen* die benutzerdefinierte Cluster-Rolle aus, die dem Mitglied zugewiesen werden soll.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Das Mitglied hat die zugewiesene Rolle.

Um einem bestehenden Cluster-Mitglied eine beliebige benutzerdefinierte Rolle zuzuweisen,

. Klicken Sie auf *☰ > Benutzer & Authentifizierung*.
. Gehen Sie zu dem Mitglied, dem Sie die Rolle geben möchten. Klicken Sie auf *⋮ > Konfiguration bearbeiten*.
. Wenn Sie benutzerdefinierte Rollen hinzugefügt haben, werden diese im Abschnitt *Benutzerdefiniert* angezeigt. Wählen Sie die Rolle aus, die Sie dem Mitglied zuweisen möchten.
. Klicken Sie auf *Speichern*.

*Ergebnis:* Das Mitglied hat die zugewiesene Rolle.

[#_project_roles]
== Projektrollen

_Projektrollen_ sind Rollen, die verwendet werden können, um Benutzern Zugriff auf ein Projekt zu gewähren. Es gibt drei Hauptprojektrollen: `Owner`, `Member` und `Read Only`.

* *Projekt-Eigentümer:*
+
Diese Benutzer haben die volle Kontrolle über das Projekt und alle Ressourcen darin.

* *Projektmitglied:*
+
Diese Benutzer können projektbezogene Ressourcen wie Namespaces und Workloads verwalten, aber keine anderen Projektmitglieder verwalten.

[NOTE]
====

Standardmäßig erbt die Rancher-Rolle `project-member` von der Rolle `Kubernetes-edit`, und die Rolle `project-owner` erbt von der Rolle `Kubernetes-admin`. Daher ermöglichen sowohl die Rollen `project-member` als auch `project-owner` die Verwaltung von Namespaces, einschließlich der Möglichkeit, Namespaces zu erstellen und zu löschen.
====


* *Nur Lesen:*
+
Diese Benutzer können alles im Projekt einsehen, aber nichts erstellen, aktualisieren oder löschen.

[WARNING]
====

Benutzer, die die Rolle `Owner` oder `Member` für ein Projekt zugewiesen bekommen, erben automatisch die Rolle `namespace creation`. Diese Rolle ist jedoch eine https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole[Kubernetes ClusterRole], was bedeutet, dass ihr Geltungsbereich alle Projekte im Cluster umfasst. Daher können Benutzer, die ausdrücklich die Rolle `owner` oder `member` für ein Projekt zugewiesen bekommen, Namespaces in anderen Projekten erstellen, denen sie zugewiesen sind, selbst wenn ihnen nur die Rolle `Read Only` zugewiesen ist.
====


[#_custom_project_roles]
=== Benutzerdefinierte Projektrollen

Rancher ermöglicht es Ihnen, _benutzerdefinierte Projektrollen_ einem Standardbenutzer anstelle der typischen Rollen `Owner`, `Member` oder `Read Only` zuzuweisen. Diese Rollen können entweder eine integrierte benutzerdefinierte Projektrolle oder eine von einem Rancher-Administrator definierte Rolle sein. Sie sind praktisch, um engen oder spezialisierten Zugriff für einen Standardbenutzer innerhalb eines Projekts zu definieren. Siehe die Tabelle unten für eine Liste der integrierten benutzerdefinierten Projektrollen.

[#_project_role_reference]
=== Referenz der Projektrollen

Die folgende Tabelle listet jede integrierte benutzerdefinierte Projektrolle auf, die in Rancher verfügbar ist, und ob sie auch von der Rolle `Owner`, `Member` oder `Read Only` gewährt wird.

|===
| Integrierte Projektrolle | Besitzer | Mitglied+++<a id="proj-roles">++++++</a>+++ | Nur Lesen

| Projektmitglieder verwalten
| ✓
|
|

| Namespaces erstellen
| ✓
| ✓
|

| Config Maps verwalten
| ✓
| ✓
|

| Ingress verwalten
| ✓
| ✓
|

| Projektkataloge verwalten
| ✓
|
|

| Geheimnisse verwalten
| ✓
| ✓
|

| Servicekonten verwalten
| ✓
| ✓
|

| Manage Services (Services verwalten)
| ✓
| ✓
|

| Verwalten von Volumes
| ✓
| ✓
|

| Workloads verwalten
| ✓
| ✓
|

| Geheimnisse anzeigen
| ✓
| ✓
|

| ConfigMaps anzeigen
| ✓
| ✓
| ✓

| Ingress anzeigen
| ✓
| ✓
| ✓

| Projektmitglieder anzeigen
| ✓
| ✓
| ✓

| Projektkataloge anzeigen
| ✓
| ✓
| ✓

| Servicekonten anzeigen
| ✓
| ✓
| ✓

| Dienste anzeigen
| ✓
| ✓
| ✓

| Volumes anzeigen
| ✓
| ✓
| ✓

| Workloads anzeigen
| ✓
| ✓
| ✓
|===

[NOTE]
.Hinweise:
====

* Jede oben aufgeführte Projektrolle, einschließlich `Owner`, `Member` und `Read Only`, besteht aus mehreren Regeln, die den Zugriff auf verschiedene Ressourcen gewähren. Sie können die Rollen und deren Regeln auf der Seite Global > Sicherheit > Rollen anzeigen.
* Beim Anzeigen der mit den Standardrollen, die von Rancher erstellt wurden, verbundenen Ressourcen, wird, wenn mehrere Kubernetes-API-Ressourcen in einem einzelnen Listeneintrag vorhanden sind, `(Custom)` an die Ressource angehängt. Dies sind keine benutzerdefinierten Ressourcen, sondern lediglich ein Hinweis darauf, dass es mehrere Kubernetes-API-Ressourcen als eine Ressource gibt.
* Die Rolle `Manage Project Members` erlaubt es dem Projekteigentümer, beliebige Mitglieder des Projekts zu verwalten *und* ihnen unabhängig von ihrem Zugriff auf die Projektressourcen jede projektbezogene Rolle zuzuweisen. Seien Sie vorsichtig, wenn Sie diese Rolle einzeln zuweisen.
====


[#_defining_custom_roles]
== Benutzerdefinierte Rollen definieren

Wie bereits erwähnt, können benutzerdefinierte Rollen für die Verwendung auf Cluster- oder Projektebene definiert werden. Das Kontextfeld definiert, ob die Rolle auf der Seite der Cluster-Mitglieder, der Projekt-Mitglieder oder auf beiden angezeigt wird.

Bei der Definition einer benutzerdefinierten Rolle können Sie den Zugriff auf bestimmte Ressourcen gewähren oder Rollen angeben, von denen die benutzerdefinierte Rolle erben soll. Eine benutzerdefinierte Rolle kann aus einer Kombination spezifischer Berechtigungen und geerbter Rollen bestehen. Alle Berechtigungen sind additiv. Das bedeutet, dass die Definition einer engeren Berechtigung für eine bestimmte Ressource *nicht* eine breitere Berechtigung, die in einer Rolle definiert ist, von der die benutzerdefinierte Rolle erbt, überschreibt.

[#_default_cluster_and_project_roles]
== Standard-Cluster- und Projektrollen

Standardmäßig wird einem Standardbenutzer, der einen neuen Cluster oder ein neues Projekt erstellt, automatisch eine Eigentümerrolle zugewiesen: entweder <<_cluster_roles,Cluster-Eigentümer>> oder <<_project_roles,Projekt-Eigentümer>>. In einigen Organisationen können diese Rollen jedoch zu weitreichenden administrativen Zugriff gewähren. In diesem Anwendungsfall können Sie die Standardrolle in etwas restriktiveres ändern, wie z. B. eine Reihe individueller Rollen oder eine benutzerdefinierte Rolle.

Es gibt zwei Methoden, um die Standard-Cluster-/Projektrollen zu ändern:

* *Benutzerdefinierte Rollen zuweisen*: Erstellen Sie eine {xref-custom-roles}[benutzerdefinierte Rolle] für entweder Ihren <<_custom_cluster_roles,Cluster>> oder <<_custom_project_roles,Projekt>> und setzen Sie dann die benutzerdefinierte Rolle als Standard.
* *Individuelle Rollen zuweisen*: Konfigurieren Sie mehrere <<_cluster_role_reference,Cluster>>/<<_project_role_reference,Projekt>> Rollen als Standard für die Zuweisung an den erstellenden Benutzer.
+
Zum Beispiel können Sie anstelle der Zuweisung einer Rolle, die andere Rollen erbt (wie `cluster owner`), eine Mischung aus individuellen Rollen (wie `manage nodes` und `manage storage`) wählen.

[NOTE]
====

* Obwohl Sie eine Standardrolle {xref-locked-roles}[sperren] können, weist das System die Rolle weiterhin Benutzern zu, die einen Cluster/ein Projekt erstellen.
* Nur Benutzer, die Cluster/Projekte erstellen, erben ihre Rollen. Benutzer, die später zur Cluster-/Projektmitgliedschaft hinzugefügt werden, müssen ausdrücklich ihren Rollen zugewiesen werden.
====


[#_configuring_default_roles_for_cluster_and_project_creators]
== Konfiguration der Standardrollen für Cluster- und Projektersteller

Sie können die Cluster- oder Projektrolle(n) ändern, die automatisch dem erstellenden Benutzer zugewiesen werden.

. Klicken Sie in der oberen linken Ecke auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie in der linken Navigationsleiste auf *Rollen-Vorlagen*.
. Klicken Sie auf die Registerkarte *Cluster* oder *Projekt/Namensräume*.
. Finden Sie die benutzerdefinierte oder individuelle Rolle, die Sie als Standard verwenden möchten. Bearbeiten Sie dann die Rolle, indem Sie *⋮ > Konfiguration bearbeiten* auswählen.
. Aktivieren Sie im Abschnitt *Cluster Creator Default* oder *Project Creator Default* die Rolle als Standard.
. Klicken Sie auf *Speichern*.

*Ergebnis:* Die Standardrollen werden basierend auf Ihren Änderungen konfiguriert. Rollen, die Cluster-/Projekt-Erstellern zugewiesen sind, zeigen ein Häkchen in der Spalte *Cluster/Projekt Creator Default* an.

Wenn Sie eine Standardrolle entfernen möchten, bearbeiten Sie die Berechtigung und wählen Sie *Nein* aus der Option für Standardrollen aus.

[#_cluster_membership_revocation_behavior]
== Verhalten bei der Widerrufung der Cluster-Mitgliedschaft

Wenn Sie die Cluster-Mitgliedschaft für einen Standardbenutzer widerrufen, der ausdrücklich Mitglied sowohl des Clusters _als auch_ eines Projekts innerhalb des Clusters ist, verliert dieser Standardbenutzer <<_cluster_roles,seine Cluster-Rollen>>, behält jedoch <<_project_roles,seine Projekt-Rollen>> bei. Mit anderen Worten, obwohl Sie die Berechtigungen des Benutzers zum Zugriff auf den Cluster und seine Knoten widerrufen haben, kann der Standardbenutzer weiterhin:

* Auf die Projekte zugreifen, in denen er Mitglied ist.
* Alle <<_project_role_reference,individuellen Projektrollen>> ausüben, die ihm zugewiesen sind.

Wenn Sie den Zugriff eines Benutzers innerhalb eines Clusters vollständig widerrufen möchten, widerrufen Sie sowohl seine Cluster- als auch seine Projektmitgliedschaften.

[#_external_roletemplate_behavior]
== Externes `RoleTemplate` Verhalten

In Rancher v2.9.0 und später können externe `RoleTemplate` Objekte nur erstellt werden, wenn das zugrunde liegende `ClusterRole` im lokalen Cluster existiert oder das `ExternalRules` in Ihrer Konfiguration festgelegt ist.

Zur Erläuterung: Das zugrunde liegende `ClusterRole` enthält Clusterregeln und -privilegien und verwendet dasselbe `metadata.name`, das in den `RoleTemplate` in Ihrem jeweiligen Cluster verwendet wird, auf das sich das `ClusterRoleTemplateBinding/ProjectRoleTemplateBinding` bezieht. Darüber hinaus beachten Sie, dass `escalate` Berechtigungen auf `RoleTemplates` erforderlich sind, um externe `RoleTemplates` mit `ExternalRules` zu erstellen.
