= Benutzerdefinierte Rollen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: anleitungen/neue-benutzeranleitungen/authentifizierungsberechtigungen-und-globale-konfiguration/rollenbasierte-zugriffskontrolle-rbac/benutzerdefinierte-rollen.adoc 
:product-path: rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-rollenbasierte-zugriffskontrolle-rbac/globale-berechtigungen.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-users-and-groups: xref:rancher-admin/users/authn-and-authz/manage-users-and-groups.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:anleitungen/neue-nutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/manage-rollenbasierte-zugriffskontrolle-rbac/globale-berechtigungen.adoc 
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
:xref-users-and-groups: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/manage-users-and-groups.adoc
endif::[]

Innerhalb von Rancher bestimmen _Rollen_, welche Aktionen ein Benutzer innerhalb eines Clusters oder Projekts durchführen kann.

Beachten Sie, dass _Rollen_ sich von _Berechtigungen_ unterscheiden, die bestimmen, auf welche Cluster und Projekte Sie zugreifen können.

[WARNING]
====

Es ist möglich, dass eine benutzerdefinierte Rolle eine Privilegieneskalation ermöglicht. Für Details siehe <<_privilege_escalation,diesen Abschnitt.>>
====


[#_prerequisites]
== Voraussetzungen

Um die Aufgaben auf dieser Seite abzuschließen, ist eine der folgenden Berechtigungen erforderlich:

* {xref-global-permissions}[Administrator Global Permissions].
* {xref-global-permissions}#_benutzerdefinierte_globale_berechtigungen[Benutzerdefinierte Globale Berechtigungen] mit der Rolle {xref-global-permissions}[Rollen verwalten] zugewiesen.

[#_creating_a_custom_role]
== Benutzerdefinierte Rolle erstellen

Während Rancher mit einer Reihe von Standardbenutzerrollen ausgeliefert wird, können Sie auch benutzerdefinierte Standardrollen erstellen, um Benutzern sehr spezifische Berechtigungen innerhalb von Rancher zu gewähren.

Die Schritte zum Hinzufügen benutzerdefinierter Rollen unterscheiden sich je nach Version von Rancher.

. Klicken Sie in der oberen linken Ecke auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie in der linken Navigationsleiste auf *Rollenvorlagen*.
. Wählen Sie eine Registerkarte aus, um den Umfang der Rolle zu bestimmen, die Sie hinzufügen. Die Registerkarten sind:

* *Global:* Die Rolle ist gültig, um Mitgliedern die Verwaltung von globalen Ressourcen zu ermöglichen.
* *Cluster:* Die Rolle ist gültig für die Zuweisung beim Hinzufügen/Verwalten von Mitgliedern zu Clustern.
* *Projekt/Namespaces:* Die Rolle ist gültig für die Zuweisung beim Hinzufügen/Verwalten von Mitgliedern zu Projekten oder Namespaces.

. Klicken Sie auf *Globale Rolle erstellen,* *Clusterrolle erstellen* oder *Projekt/Namespace Rolle erstellen,* je nach Umfang.
. Geben Sie einen *Namen* für die Rolle ein.
. Optional: Wählen Sie die Option *Cluster/Projekt-Ersteller Standard*, um diese Rolle einem Benutzer zuzuweisen, wenn er ein neues Cluster oder Projekt erstellt. Mit dieser Funktion können Sie die Standardrollen für Cluster-/Projekt-Ersteller aufklappen oder einschränken.
+
____
Standardmäßig sind die Rollen "Cluster Creator Default" und "Project Creator Default" `Cluster Owner` bzw. `Project Owner`.
____

. Verwenden Sie die *Ressourcen gewähren*-Optionen, um einzelnen https://kubernetes.io/docs/reference/[Kubernetes-API-Endpunkten] die Rolle zuzuweisen.
+
____
Beim Anzeigen der Ressourcen, die den von Rancher erstellten Standardrollen zugeordnet sind, wird, falls in einem Zeilenartikel mehrere Kubernetes-API-Ressourcen vorkommen, an die jeweilige Ressource `(Custom)` angehängt. Dies sind keine benutzerdefinierten Ressourcen, sondern lediglich ein Hinweis darauf, dass es mehrere Kubernetes-API-Ressourcen als eine Ressource gibt.
____
+
____
Das Textfeld "Ressource" bietet eine Methode, um nach vordefinierten Kubernetes-API-Ressourcen zu suchen oder einen benutzerdefinierten Ressourcennamen für die Gewährung einzugeben. Die vordefinierte oder `(Custom)` Ressource muss aus dem Dropdown-Menü ausgewählt werden, nachdem ein Ressourcenname in dieses Feld eingegeben wurde.
____
+
Sie können auch die einzelnen cURL-Methoden (`Create`, `Delete`, `Get` usw.) auswählen, die für jeden zugewiesenen Endpunkt verwendet werden können.

. Verwenden Sie die *Von übernehmen*-Optionen, um den benutzerdefinierten Rollen einzelne Rancher-Rollen zuzuweisen. Hinweis: Wenn eine benutzerdefinierte Rolle von einer übergeordneten Rolle erbt, kann die übergeordnete Rolle nicht gelöscht werden, bis die untergeordnete Rolle gelöscht ist.
. Klicken Sie auf *Erstellen*.

[#_creating_a_custom_role_that_inherits_from_another_role]
== Erstellen einer benutzerdefinierten Rolle, die von einer anderen Rolle erbt.

Wenn Sie eine Gruppe von Personen haben, die das gleiche Zugriffslevel in Rancher benötigen, kann es Zeit sparen, eine benutzerdefinierte Rolle zu erstellen, in der alle Regeln einer anderen Rolle, wie der Administratorrolle, in eine neue Rolle kopiert werden. Dies ermöglicht es Ihnen, nur die Variationen zwischen der bestehenden Rolle und der neuen Rolle zu konfigurieren.

Die benutzerdefinierte Rolle kann dann einem Benutzer oder einer Gruppe zugewiesen werden, sodass sie beim ersten Anmelden in Rancher wirksam wird.

Um eine benutzerdefinierte Rolle basierend auf einer bestehenden Rolle zu erstellen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie in der linken Navigationsleiste auf *Rollen-Vorlagen*.
. Klicken Sie auf die Registerkarte *Cluster* oder *Projekt/Namensräume*. Klicken Sie auf *Clusterrolle erstellen* oder *Projekt/Namespace-Rolle erstellen*, je nach Umfang. Hinweis: Nur Clusterrollen und Projekt/Namespace-Rollen können von einer anderen Rolle erben.
. Geben Sie einen Namen für die Rolle ein.
. Wählen Sie im Tab *Von erben* die Rolle(n) aus, von denen die benutzerdefinierte Rolle Berechtigungen erben soll.
. Wählen Sie im Tab *Ressourcen gewähren* die Kubernetes-Ressourcenoperationen aus, die für Benutzer mit der benutzerdefinierten Rolle aktiviert werden.
+
____
Das Textfeld "Ressource" bietet eine Methode, um nach vordefinierten Kubernetes-API-Ressourcen zu suchen oder einen benutzerdefinierten Ressourcennamen für die Gewährung einzugeben. Die vordefinierte oder `(Custom)` Ressource muss aus dem Dropdown-Menü ausgewählt werden, nachdem ein Ressourcenname in dieses Feld eingegeben wurde.
____

. Optional: Weisen Sie die Rolle als Standard zu.
. Klicken Sie auf *Erstellen*.

[#_deleting_a_custom_role]
== Löschen einer benutzerdefinierten Rolle

Beim Löschen einer benutzerdefinierten Rolle werden alle globalen Rollenzuweisungen mit dieser benutzerdefinierten Rolle gelöscht.

Wenn einem Benutzer nur eine benutzerdefinierte Rolle zugewiesen ist und die Rolle gelöscht wird, verliert der Benutzer den Zugriff auf Rancher. Damit der Benutzer wieder Zugriff erhält, muss ein Administrator den Benutzer bearbeiten und neue globale Berechtigungen anwenden.

Benutzerdefinierte Rollen können gelöscht werden, integrierte Rollen können jedoch nicht gelöscht werden.

Um eine benutzerdefinierte Rolle zu löschen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie in der linken Navigationsleiste auf *Rollenvorlagen*.
. Gehen Sie zu der benutzerdefinierten globalen Rolle, die gelöscht werden soll, und klicken Sie auf *⋮ (...) > Löschen*.
. Klicken Sie auf *Löschen*.

[#_assigning_a_custom_role_to_a_group]
== Zuweisen einer benutzerdefinierten Rolle zu einer Gruppe

Wenn Sie eine Gruppe von Personen haben, die das gleiche Zugriffslevel in Rancher benötigen, kann es Zeit sparen, eine benutzerdefinierte Rolle zu erstellen. Wenn die Rolle einer Gruppe zugewiesen ist, haben die Benutzer in der Gruppe beim ersten Anmelden bei Rancher das entsprechende Zugriffslevel.

Wenn sich ein Benutzer in der Gruppe anmeldet, erhält er standardmäßig die integrierte Rolle "Standardbenutzer". Sie erhalten auch die Berechtigungen, die ihren Gruppen zugewiesen sind.

Wenn ein Benutzer aus der Gruppe des externen Authentifizierungsanbieters entfernt wird, verliert er die Berechtigungen der benutzerdefinierten Rolle, die der Gruppe zugewiesen war. Sie behalten weiterhin ihre individuelle Rolle als Standardbenutzer.

[NOTE]
.Voraussetzungen:
====

Sie können einer Gruppe nur eine globale Rolle zuweisen, wenn:

* Sie einen {xref-authn-authz}#_external_vs_local_authentication[externen Authentifizierungsanbieter] eingerichtet haben
* Der externe Authentifizierungsanbieter unterstützt {xref-users-and-groups}[Benutzergruppen]
* Sie haben bereits mindestens eine Benutzergruppe mit dem Authentifizierungsanbieter eingerichtet
====


Um einer Gruppe eine benutzerdefinierte Rolle zuzuweisen, befolgen Sie diese Schritte:

. Klicken Sie in der oberen linken Ecke auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie in der linken Navigationsleiste auf *Gruppen*.
. Gehen Sie zu der bestehenden Gruppe, der die benutzerdefinierte Rolle zugewiesen wird, und klicken Sie auf *⋮ > Konfiguration bearbeiten*.
. Wenn Sie Rollen erstellt haben, werden diese im Abschnitt *Benutzerdefiniert* angezeigt. Wählen Sie eine beliebige benutzerdefinierte Rolle aus, die der Gruppe zugewiesen werden soll.
. Optional: Wählen Sie in den Abschnitten *Globale Berechtigungen* oder *Integriert* alle zusätzlichen Berechtigungen aus, die die Gruppe haben soll.
. Klicken Sie auf *Speichern.*.

*Ergebnis:* Die benutzerdefinierte Rolle tritt in Kraft, wenn sich die Benutzer in der Gruppe bei Rancher anmelden.

[#_privilege_escalation]
== Privilegieneskalation

Die `Configure Catalogs` benutzerdefinierte Berechtigung ist mächtig und sollte mit Vorsicht verwendet werden. Wenn ein Administrator die `Configure Catalogs` Berechtigung einem Standardbenutzer zuweist, könnte dies zu einer Privilegieneskalation führen, bei der der Benutzer sich selbst Administratorzugriff auf von Rancher bereitgestellte Cluster gewähren könnte. Jeder mit dieser Berechtigung sollte als gleichwertig zu einem Administrator betrachtet werden.
