= Beispiele für Monitoring-Konfigurationen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/examples.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/examples.adoc

[#_servicemonitor]
== ServiceMonitor

Siehe das offizielle GitHub-Repo des prometheus-operators für ein Beispiel https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml[ServiceMonitor] YAML.

[#_podmonitor]
== PodMonitor

Siehe die https://prometheus-operator.dev/docs/developer/getting-started/#using-podmonitors[Dokumentation des Prometheus Operators] für ein Beispiel PodMonitor und eine Beispiel-Prometheus-Ressource, die auf einen PodMonitor verweist.

[#_prometheusrule]
== PrometheusRule

Eine PrometheusRule enthält die Alarmierungs- und Aufzeichnungsregeln, die Sie normalerweise in einer https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/[Prometheus-Regeldatei] platzieren würden.

Für einen differenzierteren Ansatz kann das `ruleSelector` Feld in einer Prometheus-Ressource auswählen, welche PrometheusRules in Prometheus geladen werden sollen, basierend auf den an den PrometheusRules-Ressourcen angehängten Labels.

Siehe die https://prometheus-operator.dev/docs/developer/alerting/[Dokumentation des Prometheus Operators] für ein Beispiel PrometheusRule.

[#_alertmanager_config]
== Alertmanager-Konfiguration

Siehe die Rancher-Dokumentationsseite zu Receivern für ein Beispiel xref:./receivers.adoc#_example_alertmanager_configs[Alertmanager-Konfiguration].
