= Routen-Konfiguration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/routes.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/routes.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
endif::[]

Die Routen-Konfiguration ist der Abschnitt der benutzerdefinierten Ressource des Alertmanagers, der steuert, wie die von Prometheus ausgelösten Alarme gruppiert und gefiltert werden, bevor sie den Empfänger erreichen.

Wenn eine Route geändert wird, regeneriert der Prometheus-Operator die benutzerdefinierte Ressource des Alertmanagers, um die Änderungen widerzuspiegeln.

Für weitere Informationen zur Konfiguration von Routen siehe die https://www.prometheus.io/docs/alerting/latest/configuration/#route[offizielle Dokumentation des Alertmanagers.]

[NOTE]
====

Dieser Abschnitt setzt voraus, dass Sie mit der Funktionsweise der Überwachungskomponenten vertraut sind. Für weitere Informationen siehe {xref-how-monitoring-works}[diesen Abschnitt.]
====


[#_route_restrictions]
== Routenbeschränkungen

Der Alertmanager leitet Alarme für Prometheus basierend auf seinen Empfängern und einem Routing-Baum weiter, der Alarme anhand von Labels an bestimmte Empfänger filtert.

Alarmierungstreiber leiten Alarme für den Alertmanager an nicht-native Empfänger weiter, wie Microsoft Teams und SMS.

In der Rancher-Benutzeroberfläche zur Konfiguration von Routen und Empfängern können Sie Routing-Bäume mit einer Wurzel und dann einer Tiefe von einer weiteren Ebene konfigurieren, für einen Baum mit einer Tiefe von zwei. Wenn Sie jedoch eine `continue` Route verwenden, wenn Sie den Alertmanager direkt konfigurieren, können Sie den Baum tiefer machen.

Jeder Empfänger ist für einen oder mehrere Benachrichtigungsanbieter. Wenn Sie also wissen, dass jeder Alarm für Slack auch an PagerDuty gesendet werden soll, können Sie beide im selben Empfänger konfigurieren.

[#_route_configuration]
== Routen-Konfiguration

[#_note_on_labels_and_annotations]
=== Hinweis zu Labels und Annotationen

Labels sollten verwendet werden, um identifizierende Informationen zu kennzeichnen, die die Weiterleitung von Benachrichtigungen beeinflussen können. Identifizierende Informationen über den Alarm könnten aus einem Container-Namen oder dem Namen des Teams bestehen, das benachrichtigt werden soll.

Annotationen sollten für Informationen verwendet werden, die nicht beeinflussen, wer den Alarm erhält, wie eine Runbook-URL oder eine Fehlermeldung.

[#_receiver]
=== Empfänger

Die Route muss auf einen {xref-receivers}[Empfänger] verweisen, der bereits konfiguriert wurde.

[#_grouping]
=== Gruppierung

|===
| Feld | Standard | Beschreibung

| Gruppieren nach
| N/a
| Liste der Labels, nach denen gruppiert werden soll. Labels müssen eindeutig sein. Das spezielle Label "..." (aggregiere nach allen möglichen Labels), falls angegeben, muss das einzige Element in der Liste sein. Akzeptiert eine Liste von Zeichenfolgen. Siehe die https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#route[Upstream-Dokumentation] für Details.

| Gruppierungswartezeit
| 30s
| Wie lange gewartet werden soll, um Alarme derselben Gruppe zu puffern, bevor sie zunächst gesendet werden.

| Gruppierungsintervall
| 5m
| Wie lange gewartet werden soll, bevor ein Alarm gesendet wird, der zu einer Gruppe von Alarmen hinzugefügt wurde, für die bereits eine erste Benachrichtigung gesendet wurde.

| Wiederholungsintervall
| 4h
| Wie lange gewartet werden soll, bevor ein gegebener Alarm, der bereits gesendet wurde, erneut gesendet wird.
|===

[#_matching]
=== Übereinstimmung

Das *Übereinstimmung* Feld bezieht sich auf eine Menge von Gleichheitsabgleichern, die verwendet werden, um zu identifizieren, welche Alarme an eine gegebene Route gesendet werden sollen, basierend auf den Labels, die für diesen Alarm definiert sind. Wenn Sie Schlüssel-Wert-Paare in der Rancher-Benutzeroberfläche hinzufügen, entsprechen sie dem YAML in diesem Format:

[,yaml]
----
match:
  [ <labelname>: <labelvalue>, ... ]
----

Das Feld *Match Regex* bezieht sich auf eine Menge von Regex-Abgleichern, die verwendet werden, um zu identifizieren, welche Alarme an eine gegebene Route gesendet werden sollen, basierend auf den Labels, die für diesen Alarm definiert sind. Wenn Sie Schlüssel-Wert-Paare in der Rancher-Benutzeroberfläche hinzufügen, entsprechen sie dem YAML in diesem Format:

[,yaml]
----
match_re:
  [ <labelname>: <regex>, ... ]
----
