= Instalar/Fazer upgrade {rancher-product-name} em um Cluster Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-16
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc 
:product-path: installation-and-upgrade/install-rancher.adoc
:description: Aprenda como instalar o Rancher em ambientes de desenvolvimento e produção. Leia sobre a instalação em um único nó e a instalação de alta disponibilidade
ifeval::["{build-type}" != "community"]
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-tls-secrets: xref:installation-and-upgrade/resources/tls-secrets.adoc
:xref-tls-settings: xref:installation-and-upgrade/references/tls-settings.adoc
:xref-upgrade-certmanager: xref:installation-and-upgrade/resources/upgrade-cert-manager.adoc
:xref-install-upgrade-troubleshooting: xref:installation-and-upgrade/troubleshooting/troubleshooting.adoc
:xref-rancher-on-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
:xref-air-gap-rancher-ha: xref:installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc
:xref-helm-reqs: xref:installation-and-upgrade/requirements/helm-version-requirements.adoc
:xref-ha-k3s: xref:installation-and-upgrade/infrastructure-setup/ha-k3s-kubernetes-cluster.adoc
:xref-ha-rke2: xref:installation-and-upgrade/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc
:xref-k3s-for-rancher: xref:installation-and-upgrade/install-kubernetes/k3s-for-rancher.adoc
:xref-rke2-for-rancher: xref:installation-and-upgrade/install-kubernetes/rke2-for-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-on-aks: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-aks.adoc
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-tls-secrets: xref:getting-started/installation-and-upgrade/resources/add-tls-secrets.adoc
:xref-tls-settings: xref:getting-started/installation-and-upgrade/installation-references/tls-settings.adoc
:xref-upgrade-certmanager: xref:getting-started/installation-and-upgrade/resources/upgrade-cert-manager.adoc
:xref-install-upgrade-troubleshooting: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/troubleshooting.adoc
:xref-rancher-on-eks: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-amazon-eks.adoc
:xref-air-gap-rancher-ha: xref:começando/instalação-e-atualização/outros-métodos-de-instalação/air-gapped-helm-cli-install/instalar-rancher-ha.adoc
:xref-helm-reqs: xref:getting-started/installation-and-upgrade/resources/helm-version-requirements.adoc
:xref-ha-k3s: xref:how-to-guides/new-user-guides/infrastructure-setup/ha-k3s-kubernetes-cluster.adoc
:xref-ha-rke2: xref:how-to-guides/new-user-guides/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc
:xref-rancher-on-gke: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-gke.adoc
:xref-k3s-for-rancher: xref:how-to-guides/new-user-guides/kubernetes-cluster-setup/k3s-for-rancher.adoc
:xref-rke2-for-rancher: xref:how-to-guides/new-user-guides/kubernetes-cluster-setup/rke2-for-rancher.adoc
endif::[]

Nesta seção, você aprenderá como implantar o Rancher em um cluster Kubernetes usando a CLI do Helm.

[#_prerequisites]
== Pré-requisitos

* <<_kubernetes_cluster,Kubernetes Cluster>>
* <<_ingress_controller,Controlador de Ingress>>
* <<_cli_tools,Ferramentas CLI>>

[#_kubernetes_cluster]
=== Kubernetes Cluster

Configure o cluster Kubernetes local do servidor Rancher.

O Rancher pode ser instalado em qualquer cluster Kubernetes. Este cluster pode usar Kubernetes upstream, ou pode usar uma das distribuições Kubernetes do Rancher, ou pode ser um cluster Kubernetes gerenciado de um provedor como o Amazon EKS.

Para ajuda na configuração de um cluster Kubernetes, fornecemos estes tutoriais:

* *K3s:* Para o tutorial de instalação de um cluster Kubernetes K3s, consulte {xref-k3s-for-rancher}[esta página.] Para ajuda na configuração da infraestrutura para um cluster K3s de alta disponibilidade, consulte {xref-ha-k3s}[esta página.]
* *RKE2:* Para o tutorial de instalação de um cluster Kubernetes RKE2, consulte {xref-rke2-for-rancher}[esta página.] Para ajuda na configuração da infraestrutura para um cluster RKE2 de alta disponibilidade, consulte {xref-ha-rke2}[esta página.]
* *Amazon EKS:* Para detalhes sobre como instalar o Rancher no Amazon EKS, incluindo como instalar um controlador de Ingress para que o servidor Rancher possa ser acessado, consulte {xref-rancher-on-eks}[esta página.]
* *AKS:* Para detalhes sobre como instalar o Rancher com o Azure Kubernetes Service, incluindo como instalar um controlador de Ingress para que o servidor Rancher possa ser acessado, consulte {xref-rancher-on-aks}[esta página.]
* *GKE:* Para detalhes sobre como instalar o Rancher com o Google Kubernetes Engine, incluindo como instalar um controlador de Ingress para que o servidor Rancher possa ser acessado, consulte {xref-rancher-on-gke}[esta página.] O GKE possui dois modos de operação ao criar um cluster Kubernetes, modo Autopilot e modo Padrão. A configuração do cluster para o modo Autopilot tem restrições na edição do namespace kube-system. No entanto, o Rancher precisa criar recursos no namespace kube-system durante a instalação. Como resultado, você não poderá instalar o Rancher em um cluster GKE criado no modo Autopilot.

[#_ingress_controller]
=== Controlador de Ingress

A interface do usuário e a API do Rancher são expostas através de um Ingress. Isso significa que o cluster Kubernetes em que você instala o Rancher deve conter um controlador de Ingress.

Para instalações RKE2 e K3s, você não precisa instalar o controlador de Ingress manualmente, pois um é instalado por padrão.

Para distribuições que não incluem um Controlador de Ingress por padrão, como um cluster Kubernetes hospedado, como EKS, GKE ou AKS, você deve implantar um controlador de Ingress primeiro. Observe que o Helm chart do Rancher não define um `ingressClassName` no ingress por padrão. Por causa disso, você deve configurar o controlador de Ingress para também monitorar Ingress sem um `ingressClassName`.

Exemplos estão incluídos nos tutoriais *Amazon EKS*, *AKS* e *GKE* acima.

[#_cli_tools]
=== Ferramentas CLI

As seguintes ferramentas de linha de comando são necessárias para configurar o cluster Kubernetes. Por favor, certifique-se de que essas ferramentas estão instaladas e disponíveis em seu `$PATH`.

* https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl[kubectl] - ferramenta de linha de comando do Kubernetes.
* https://docs.helm.sh/using_helm/#installing-helm[helm] - gerenciamento de pacotes para Kubernetes. Consulte os {xref-helm-reqs}[requisitos de versão do Helm] para escolher uma versão do Helm para instalar o Rancher. Consulte as https://helm.sh/docs/intro/install/[instruções fornecidas pelo projeto Helm] para sua plataforma específica.

[#_install_the_rancher_helm_chart]
== Instale o Helm Chart do Rancher

O Rancher é instalado usando o gerenciador de pacotes https://helm.sh/[Helm] para Kubernetes. Os charts do Helm fornecem uma sintaxe de template para documentos de manifesto YAML do Kubernetes. Com o Helm, podemos criar implantações configuráveis em vez de apenas usar arquivos estáticos.

Para sistemas sem acesso direto à internet, veja {xref-air-gap-rancher-ha}[Air Gap: Kubernetes install].

Para escolher uma versão do Rancher para instalar, consulte xref:[Escolhendo uma Versão do Rancher.]

Para escolher uma versão do Helm para instalar o Rancher, consulte os {xref-helm-reqs}[requisitos de versão do Helm]

[NOTE]
====

As instruções de instalação assumem que você está usando o Helm 3.
====


Para configurar o Rancher,

. <<_1_add_the_helm_chart_repository,Adicione o repositório do Helm Chart>>
. <<_2_create_a_namespace_for_rancher,Crie um namespace para o Rancher>>
. <<_3_choose_your_ssl_configuration,Escolha sua configuração SSL>>
. <<_4_install_cert_manager,Instale o cert-manager>> (a menos que você esteja trazendo seus próprios certificados ou que o TLS será encerrado em um balanceador de carga)
. <<_5_install_rancher_with_helm_and_your_chosen_certificate_option,Instale o Rancher com o Helm e a opção de certificado escolhida>>
. <<_6_verify_that_the_rancher_server_is_successfully_deployed,Verifique se o servidor Rancher foi implantado com sucesso>>
. <<_7_save_your_options,Salve suas opções>>

[#_1_add_the_helm_chart_repository]
=== 1. Adicione o Repositório do Helm Chart

ifeval::["{build-type}" == "product"]
Use o comando `helm repo add` para adicionar o repositório do Helm Chart que contém charts para instalar o Rancher Prime.

[,shell]
----
helm repo add rancher-prime <helm-chart-repo-url>
----

include::shared:ROOT:partial$en/helm-chart-repo-url.adoc[]
endif::[]

ifeval::["{build-type}" == "community"]
Use o comando `helm repo add` para adicionar o repositório do Helm Chart que contém charts para instalar o Rancher. Para mais informações sobre as opções de repositório e qual é a melhor para o seu caso de uso, veja xref:getting-started/installation-and-upgrade/resources/choose-a-rancher-version.adoc[Escolhendo uma Versão do Rancher].

* Mais Recente: Recomendado para experimentar os novos recursos
+
----
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
----

* Estável: Recomendado para ambientes de produção
+
----
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
----

* Alpha: Prévia experimental de lançamentos futuros.
+
----
helm repo add rancher-alpha https://releases.rancher.com/server-charts/alpha
----
+
[NOTE]
====
Atualizações não são suportadas para, de ou entre Alphas.
====
endif::[]

[#_2_create_a_namespace_for_rancher]
=== 2. Crie um namespace para Rancher

Precisamos definir um namespace do Kubernetes onde os recursos criados pelo Chart devem ser instalados. Isso deve sempre ser `cattle-system`:

----
kubectl create namespace cattle-system
----

[#_3_choose_your_ssl_configuration]
=== 3. Escolha sua configuração SSL

O servidor de gerenciamento do Rancher é projetado para ser seguro por padrão e requer configuração SSL/TLS.

[NOTE]
====

Se você deseja terminar SSL/TLS externamente, veja {xref-helm-chart-options}#_external_tls_termination[Terminação TLS em um Balanceador de Carga Externo]. Como descrito nessa página, essa opção possui requisitos adicionais para verificação TLS.
====


Existem três opções recomendadas para a origem do certificado usado para a terminação TLS no servidor Rancher:

* *Certificado TLS gerado pelo Rancher:* Nesse caso, você precisará instalar `cert-manager` no cluster. O Rancher utiliza `cert-manager` para emitir e manter seus certificados. O Rancher gerará um certificado CA próprio e assinará um certificado usando essa CA. `cert-manager` é então responsável por gerenciar esse certificado. Nenhuma ação extra é necessária quando `agent-tls-mode` está definido como estrito. Mais informações podem ser encontradas sobre essa configuração em {xref-tls-settings}#_agent_tls_enforcement[Aplicação de TLS do Agente].
* *Let's Encrypt:* A opção Let's Encrypt também utiliza `cert-manager`. No entanto, neste caso, o cert-manager é combinado com um Issuer especial para o Let's Encrypt que realiza todas as ações (incluindo solicitação e validação) necessárias para obter um certificado emitido pelo Let's Encrypt. Esta configuração utiliza validação HTTP (`HTTP-01`), portanto, o balanceador de carga deve ter um registro DNS público e ser acessível pela internet. Ao definir `agent-tls-mode` como `strict`, você também deve especificar `--privateCA=true` e fazer o upload do CA do Let's Encrypt conforme descrito em {xref-tls-secrets}[Adicionando Segredos TLS]. Mais informações podem ser encontradas sobre esta configuração em {xref-tls-settings}#_agent_tls_enforcement[Aplicação de TLS do Agente].
* *Traga seu Próprio Certificado:* Esta opção permite que você traga seu próprio certificado assinado por uma CA pública ou privada. O Rancher usará esse certificado para proteger o tráfego websocket e HTTPS. Neste caso, você deve fazer o upload deste certificado (e da chave associada) como arquivos codificados em PEM com os nomes `tls.crt` e `tls.key`. Se você estiver usando uma CA privada, também deve fazer o upload desse certificado. Isso se deve ao fato de que essa CA privada pode não ser confiável pelos seus nós. O Rancher pegará esse certificado CA e gerará um checksum a partir dele, que os vários componentes do Rancher usarão para validar sua conexão com o Rancher. Se `agent-tls-mode` estiver definido como `strict`, o CA deve ser enviado, para que os clusters downstream possam se conectar com sucesso. Mais informações podem ser encontradas sobre essa configuração em {xref-tls-settings}#_agent_tls_enforcement[Aplicação de TLS do Agente].

|===
| Configuração | Opção do Helm Chart | Requer cert-manager

| Certificados Gerados pelo Rancher (Padrão)
| `ingress.tls.source=rancher`
| <<_4_install_cert_manager,sim>>

| Let's Encrypt
| `ingress.tls.source=letsEncrypt`
| <<_4_install_cert_manager,sim>>

| Certificados de Arquivos
| `ingress.tls.source=secret`
| não
|===

[#_4_install_cert_manager]
=== 4. Instalar cert-manager

____
Você deve pular esta etapa se estiver trazendo seus próprios arquivos de certificado (opção `ingress.tls.source=secret`), ou se usar {xref-helm-chart-options}#_external_tls_termination[terminação TLS em um balanceador de carga externo].
____

Esta etapa é necessária apenas para usar certificados emitidos pela CA gerada pelo Rancher (`ingress.tls.source=rancher`) ou para solicitar certificados emitidos pelo Let's Encrypt (`ingress.tls.source=letsEncrypt`).

.Clique para expandir
[%collapsible]
======

[NOTE]
.Importante:
====

Mudanças recentes no cert-manager exigem fazer upgrade. Se você estiver atualizando o Rancher e usando uma versão do cert-manager anterior à v0.11.0, consulte nossa {xref-upgrade-certmanager}[documentação de upgrade].
====


Estas instruções são adaptadas da https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm[documentação oficial do cert-manager].

[NOTE]
====

Para ver opções sobre como personalizar a instalação do cert-manager (incluindo para casos em que seu cluster usa PodSecurityPolicies), consulte a https://artifacthub.io/packages/helm/cert-manager/cert-manager#configuration[documentação do cert-manager].
====


----
# If you have installed the CRDs manually, instead of setting `installCRDs` or `crds.enabled` to `true` in your Helm install command, you should upgrade your CRD resources before upgrading the Helm chart:
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/<VERSION>/cert-manager.crds.yaml

# Add the Jetstack Helm repository
helm repo add jetstack https://charts.jetstack.io

# Update your local Helm chart repository cache
helm repo update

# Install the cert-manager Helm chart
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --set crds.enabled=true
----

Uma vez que você tenha instalado o cert-manager, pode verificar se ele está implantado corretamente verificando o namespace do cert-manager em busca de pods em execução:

----
kubectl get pods --namespace cert-manager

NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-5c6866597-zw7kh               1/1     Running   0          2m
cert-manager-cainjector-577f6d9fd7-tr77l   1/1     Running   0          2m
cert-manager-webhook-787858fcdb-nlzsq      1/1     Running   0          2m
----

======

[#_5_install_rancher_with_helm_and_your_chosen_certificate_option]
=== 5. Instale o Rancher com Helm e a opção de certificado escolhida.

O comando exato para instalar o Rancher difere dependendo da configuração do certificado.

No entanto, independentemente da configuração do certificado, o nome da instalação do Rancher no namespace `cattle-system` deve sempre ser `rancher`.

[TIP]
.Teste e Desenvolvimento:
====

Este comando final para instalar o Rancher requer um nome de domínio que redirecione o tráfego para o Rancher. Se você estiver usando a CLI do Helm para configurar um protótipo, pode usar um nome de domínio falso ao passar a opção `hostname`. Um exemplo de um nome de domínio falso seria `<IP_OF_LINUX_NODE>.sslip.io`, que exporia o Rancher em um IP onde está em execução. Instalações em produção exigiriam um nome de domínio real.
====


[tabs]
======
Certificados gerados pelo Rancher::
+
--
O padrão é que o Rancher gere um CA e use `cert-manager` para emitir o certificado para acesso à interface do servidor Rancher.

Como `rancher` é a opção padrão para `ingress.tls.source`, não estamos especificando `ingress.tls.source` ao executar o comando `helm install`.

* Defina o `hostname` para o nome DNS que você apontou para o seu balanceador de carga.
* Defina o `bootstrapPassword` para algo único para o usuário `admin`.
* Para instalar uma versão específica do Rancher, use a flag `--version`, exemplo: `--version 2.7.0`

ifeval::["{build-type}" == "product"]
----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin
----
endif::[]

ifeval::["{build-type}" == "community"]
----
helm install rancher rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin
----

Se você estiver instalando uma versão alpha, o Helm requer adicionar a opção --devel ao comando de instalação:

----
helm install rancher rancher-alpha/rancher --devel
----
endif::[]

Aguarde o Rancher ser implantado:

----
kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----
--

Let's Encrypt::
+
--
Esta opção usa `cert-manager` para solicitar e renovar automaticamente certificados https://letsencrypt.org/[Let's Encrypt]. Este é um serviço gratuito que fornece um certificado válido, pois o Let's Encrypt é uma CA confiável.

[NOTE]
====

Você precisa ter a porta 80 aberta, pois o desafio HTTP-01 só pode ser realizado na porta 80.
====


No seguinte comando,

* `hostname` está definido como o registro DNS público,
* Defina o `bootstrapPassword` para algo único para o usuário `admin`.
* `ingress.tls.source` está definido como `letsEncrypt`
* `letsEncrypt.email` está definido como o endereço de e-mail usado para comunicação sobre seu certificado (por exemplo, avisos de expiração)
* Defina `letsEncrypt.ingress.class` como o que seu controlador de entrada é, por exemplo, `traefik`, `nginx`, `haproxy`, etc.

[CAUTION]
====

Quando `agent-tls-mode` está definido como `strict` (o valor padrão para novas instalações do Rancher a partir da v2.9.0), você deve fornecer o valor do gráfico `privateCA=true` (por exemplo, através de `--set privateCA=true`) e fazer o upload da Autoridade Certificadora Let's Encrypt conforme descrito em {xref-tls-secrets}[Adicionando Segredos TLS]. Informações sobre como identificar a Root CA do Let's Encrypt podem ser encontradas na https://letsencrypt.org/certificates/[documentação] do Let's Encrypt. Se você não fizer o upload da CA, o Rancher pode falhar ao se conectar a clusters downstream novos ou existentes.
====

ifeval::["{build-type}" == "product"]
----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=me@example.org \
  --set letsEncrypt.ingress.class=nginx
----
endif::[]

ifeval::["{build-type}" == "community"]
----
helm install rancher rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=me@example.org \
  --set letsEncrypt.ingress.class=nginx
----

Se você estiver instalando uma versão alpha, o Helm requer adicionar a opção --devel ao comando:

----
helm install rancher rancher-alpha/rancher --devel
----
endif::[]

Aguarde o Rancher ser implantado:

----
kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----
--

Certificados de Arquivos::
+
--
Nesta opção, segredos do Kubernetes são criados a partir de seus próprios certificados para uso do Rancher.

Quando você executar este comando, a opção `hostname` deve corresponder ao `Common Name` ou a uma entrada `Subject Alternative Names` no certificado do servidor, ou o controlador de entrada falhará ao configurar corretamente.

Embora uma entrada no `Subject Alternative Names` seja tecnicamente necessária, ter um `Common Name` correspondente maximiza a compatibilidade com navegadores e aplicativos mais antigos.

[NOTE]
====

Se você quiser verificar se seus certificados estão corretos, veja xref:../../../faq/technical-items.adoc#_how_do_i_check_common_name_and_subject_alternative_names_in_my_server_certificate[Como faço para verificar o Nome Comum e os Nomes Alternativos do Sujeito no meu certificado de servidor?]
====


* Defina o `hostname`.
* Defina o `bootstrapPassword` para algo único para o usuário `admin`.
* Defina `ingress.tls.source` como `secret`.

ifeval::["{build-type}" == "product"]
----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret
----
endif::[]

ifeval::["{build-type}" == "community"]
----
helm install rancher rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret
----

Se você estiver instalando uma versão alpha, o Helm requer adicionar a opção --devel ao comando:

----
helm install rancher rancher-alpha/rancher --devel
----
endif::[]

Se você estiver usando um certificado assinado por uma CA Privada, adicione `--set privateCA=true` ao comando:

ifeval::["{build-type}" == "product"]
----
helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --set privateCA=true
----
endif::[]

ifeval::["{build-type}" == "community"]
----
helm install rancher rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --set privateCA=true
----
endif::[]

Agora que o Rancher está implantado, veja {xref-tls-secrets}[Adicionando Segredos TLS] para publicar os arquivos de certificados para que o Rancher e o Ingress controller possam usá-los.
--
======

A configuração do gráfico do Rancher tem muitas opções para personalizar a instalação de acordo com o seu ambiente específico. Aqui estão alguns cenários avançados comuns.

* {xref-helm-chart-options}#_http_proxy[HTTP Proxy]
* {xref-helm-chart-options}#_private_registry_and_air_gap_installs[Private Container Image Registry]
* {xref-helm-chart-options}#_external_tls_termination[Terminação TLS em um Balanceador de Carga Externo]

Veja as {xref-helm-chart-options}[Opções do Gráfico] para a lista completa de opções.

[#_6_verify_that_the_rancher_server_is_successfully_deployed]
=== 6. Verifique se o servidor Rancher foi implantado com sucesso

Após adicionar os segredos, verifique se o Rancher foi implantado com sucesso:

----
kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----

Se você ver o seguinte erro: `error: deployment "rancher" exceeded its progress deadline`, pode verificar o status da implantação executando o seguinte comando:

----
kubectl -n cattle-system get deploy rancher
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
rancher   3         3         3            3           3m
----

Deve mostrar a mesma contagem para `DESIRED` e `AVAILABLE`.

[#_7_save_your_options]
=== 7. Salve suas opções

Certifique-se de salvar as opções `--set` que você usou. Você precisará usar as mesmas opções ao fazer upgrade do Rancher para novas versões com o Helm.

[#_finishing_up]
=== Finalizando

É isso. Você deve ter um servidor Rancher funcional.

Em um navegador da web, vá para o nome DNS que encaminha o tráfego para o seu balanceador de carga. Então você deve ser recebido pela colorida página de login.

Não funciona? Dê uma olhada na página {xref-install-upgrade-troubleshooting}[Solução de Problemas]
