= Instalando {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/index.adoc 
:product-path: installation-and-upgrade/installation-and-upgrade.adoc
:description: Aprenda como instalar o Rancher em ambientes de desenvolvimento e produção. Leia sobre a instalação em um único nó e a instalação de alta disponibilidade
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
:xref-rancher-architecture: xref:sobre-rancher/arquitetura/arquitetura.adoc
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-qs-aws-marketplace: xref:installation-and-upgrade/quick-start/deploy-rancher/aws-marketplace.adoc
:xref-http-proxy: xref:installation-and-upgrade/other-installation-methods/http-proxy/http-proxy.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-air-gap: xref:começando/instalação-e-atualização/outros-métodos-de-instalação/air-gapped-helm-cli-install/index.adoc
:xref-migrate-cluster: xref:procedimentos/novos-usuários/backup-restore-and-disaster-recovery/migrar-rancher-para-novo-cluster.adoc
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-qs-aws-marketplace: xref:getting-started/quick-start-guides/deploy-rancher-manager/aws-marketplace.adoc
:xref-http-proxy: xref:getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/index.adoc
endif::[]

Esta seção fornece uma visão geral das opções de arquitetura para a instalação do Rancher, descrevendo as vantagens de cada opção.

[#_terminology]
== Terminologia

Nesta seção,

* *O servidor Rancher* gerencia e provisiona clusters Kubernetes. Você pode interagir com clusters Kubernetes downstream através da interface do usuário do servidor Rancher. O servidor de gerenciamento do Rancher pode ser instalado em qualquer cluster Kubernetes, incluindo clusters hospedados, como os clusters Amazon EKS.
* *RKE (Rancher Kubernetes Engine)* é uma distribuição Kubernetes certificada e CLI/biblioteca que cria e gerencia um cluster Kubernetes.
* *K3s (Kubernetes Leve)* também é uma distribuição Kubernetes totalmente compatível. É mais recente que o RKE, mais fácil de usar e mais leve, com um tamanho de binário inferior a 100 MB.
* *RKE2* é uma distribuição Kubernetes totalmente compatível que se concentra na segurança e conformidade nos EUA. Governo Federal dos EUA.

[#_overview_of_installation_options]
== Visão geral das opções de instalação

O Rancher pode ser instalado nessas principais arquiteturas:

[#_high_availability_kubernetes_install_with_the_helm_cli]
=== Instalação de Kubernetes de alta disponibilidade com o Helm CLI

Recomendamos o uso do Helm, um gerenciador de pacotes do Kubernetes, para instalar o Rancher em múltiplos nós em um cluster Kubernetes dedicado. Para clusters RKE, são necessários três nós para alcançar um cluster de alta disponibilidade. Para clusters K3s, são necessários apenas dois nós.

[#_rancher_on_eks_install_with_the_aws_marketplace]
=== Instalação do Rancher no EKS com o AWS Marketplace

O Rancher pode ser instalado no Amazon Elastic Kubernetes Service (EKS) {xref-qs-aws-marketplace}[através do AWS Marketplace]. O cluster EKS implantado está pronto para produção e segue as melhores práticas da AWS.

[#_single_node_kubernetes_install]
=== Instalação do Kubernetes em um único nó

O Rancher pode ser instalado em um cluster Kubernetes de um único nó. Nesse caso, o servidor Rancher não possui alta disponibilidade, o que é importante para executar o Rancher em produção.

No entanto, essa opção é útil se você quiser economizar recursos usando um único nó a curto prazo, enquanto preserva um caminho de migração para alta disponibilidade. No futuro, você pode adicionar nós ao cluster para obter um servidor Rancher com alta disponibilidade.

[#_docker_install]
=== Instalação do Docker

Para fins de teste e demonstração, o Rancher pode ser instalado com Docker em um único nó. Um cluster local do Kubernetes é instalado no único contêiner Docker, e o Rancher é instalado no cluster local.

O operador de backup do Rancher pode ser usado para migrar o Rancher da instalação de contêiner Docker único para uma instalação em um cluster Kubernetes de alta disponibilidade. Para mais detalhes, consulte a documentação sobre {xref-migrate-cluster}[migrando o Rancher para um novo cluster.]

[#_other_options]
=== Outras Opções

Existem também instruções separadas para instalar o Rancher em um ambiente air gap ou atrás de um proxy HTTP:

|===
| Nível de Acesso à Internet | Instalação do Kubernetes - Fortemente Recomendado | Instalação do Docker

| Com acesso direto à Internet
| {xref-install-rancher}[Documentos]
| xref:[Documentos]

| Atrás de um proxy HTTP
| {xref-http-proxy}[Documentos]
| Esses xref:[documentos,] mais esta xref:[configuração]

| Em um ambiente air gap
| {xref-air-gap}[Documentos]
| {xref-air-gap}[Documentos]
|===

Recomendamos instalar o Rancher em um cluster Kubernetes, pois em um cluster de múltiplos nós, o servidor de gerenciamento do Rancher se torna altamente disponível. Essa configuração de alta disponibilidade ajuda a manter o acesso consistente aos clusters Kubernetes downstream que o Rancher irá gerenciar.

Por essa razão, recomendamos que, para uma arquitetura de nível de produção, você configure um cluster Kubernetes de alta disponibilidade e, em seguida, instale o Rancher nele. Após a instalação do Rancher, você pode usar o Rancher para implantar e gerenciar clusters Kubernetes.

Para fins de teste ou demonstração, você pode instalar o Rancher em um único contêiner Docker. Na instalação Docker, você pode usar o Rancher para configurar clusters Kubernetes prontos para uso. A instalação Docker permite que você explore a funcionalidade do servidor Rancher, mas é destinada apenas para fins de desenvolvimento e teste.

Nossas {xref-install-rancher}[instruções para instalar o Rancher no Kubernetes] descrevem como usar primeiro o K3s ou RKE para criar e gerenciar um cluster Kubernetes, e depois instalar o Rancher nesse cluster.

Quando os nós em seu cluster Kubernetes estiverem em execução e atenderem aos {xref-install-reqs}[requisitos de nó,] você usará o Helm para implantar o Rancher no Kubernetes. O Helm utiliza o chart do Rancher para instalar uma réplica do Rancher em cada nó no cluster Kubernetes. Recomendamos o uso de um balanceador de carga para direcionar o tráfego para cada réplica do Rancher no cluster.

Para uma discussão mais longa sobre a arquitetura do Rancher, consulte o {xref-rancher-architecture}[visão geral da arquitetura,] {xref-arch-rec}[recomendações para arquitetura de nível de produção,] ou nosso {xref-tips-for-running-rancher}[guia de melhores práticas.]

[#_prerequisites]
== Pré-requisitos

Antes de instalar o Rancher, certifique-se de que seus nós atendem a todos os {xref-install-reqs}[requisitos de instalação.]

[#_architecture_tip]
== Dica de Arquitetura

Para o melhor desempenho e maior segurança, recomendamos um cluster Kubernetes separado e dedicado para o servidor de gerenciamento do Rancher. Executar cargas de trabalho de usuários neste cluster não é aconselhável. Após implantar o Rancher, você pode {xref-cluster-deployment}[criar ou importar clusters] para executar suas cargas de trabalho.

Para mais recomendações de arquitetura, consulte {xref-arch-rec}[esta página.]

[#_more_options_for_installations_on_a_kubernetes_cluster]
=== Mais opções para instalações em um cluster Kubernetes

Consulte as {xref-helm-chart-options}[opções do chart do Helm] para detalhes sobre a instalação do Rancher em um cluster Kubernetes com outras configurações, incluindo:

* Com {xref-helm-chart-options}#_api_audit_log[auditoria de API para registrar todas as transações]
* Com {xref-helm-chart-options}#_external_tls_termination[terminação TLS em um balanceador de carga]
* Com um {xref-helm-chart-options}#_customizing_your_ingress[Ingress personalizado]

Nas instruções de instalação do Rancher, recomendamos usar o K3s ou RKE para configurar um cluster Kubernetes antes de instalar o Rancher no cluster. Tanto o K3s quanto o RKE possuem muitas opções de configuração para personalizar o cluster Kubernetes de acordo com o seu ambiente específico. Para a lista completa de suas capacidades, consulte a documentação deles:

* https://rancher.com/docs/rke/latest/en/config-options/[opções de configuração do RKE]
* https://rancher.com/docs/k3s/latest/en/installation/install-options/[opções de configuração do K3s]

