= Deprecated Features in {rancher-product-name}

== What is Rancher's deprecation policy?

We have published our official deprecation policy in the support https://rancher.com/support-maintenance-terms[terms of service].

== Where can I find out which features have been deprecated in Rancher?

Rancher will publish deprecated features as part of the https://github.com/rancher/rancher/releases[release notes] for Rancher found on GitHub. Please consult the following patch releases for deprecated features:

|===
| Patch Version | Release Date

| https://github.com/rancher/rancher/releases/tag/v2.10.5[2.10.5]
| Apr 23, 2025

| https://github.com/rancher/rancher/releases/tag/v2.10.4[2.10.4]
| Mar 31, 2025

| https://github.com/rancher/rancher/releases/tag/v2.10.3[2.10.3]
| Feb 27, 2025

| https://github.com/rancher/rancher/releases/tag/v2.10.2[2.10.2]
| Jan 29, 2025

| https://github.com/rancher/rancher/releases/tag/v2.10.1[2.10.1]
| Dec 19, 2024

| https://github.com/rancher/rancher/releases/tag/v2.10.0[2.10.0]
| Nov 18, 2024
|===

== What can I expect when a feature is marked for deprecation?

In the release where functionality is marked as "Deprecated", it will still be available and supported allowing upgrades to follow the usual procedure. Once upgraded, users/admins should start planning to move away from the deprecated functionality before upgrading to the release it marked as removed. The recommendation for new deployments is to not use the deprecated feature.
