= Desabilitando o Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/disable-istio.adoc 
:product-path: observability/istio/disable-istio.adoc

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] foi descontinuado desde o Rancher v2.12.0; recorra à https://apps.rancher.io[SUSE Application Collection] versão do Istio para segurança aprimorada (incluída nas assinaturas do SUSE Rancher Prime).
Informações detalhadas podem ser encontradas em https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anúncio].
====

Esta seção descreve como desinstalar o Istio em um cluster ou desabilitar um namespace ou carga de trabalho.

[#_uninstall_istio_in_a_cluster]
== Desinstalar o Istio em um Cluster

Para desinstalar o Istio,

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que você criou e clique em *Explorar*.
. Na barra de navegação à esquerda, clique em menu:Apps[Apps Instalados].
. No namespace `istio-system`, vá para `rancher-istio` e clique em *⋮ > Excluir*.
. Após `rancher-istio` ser excluído, você pode selecionar todos os apps restantes no namespace `istio-system` e clicar em *Excluir*.

*Resultado:* O app `rancher-istio` no cluster é removido. O sidecar do Istio não pode ser implantado em nenhuma carga de trabalho no cluster.

[NOTE]
====

Você não pode mais desabilitar e reabilitar sua instalação do Istio. Se você deseja salvar suas configurações para uma instalação futura, visualize e salve os YAMLs individuais para consultar / reutilizar em futuras instalações.
====


*Solução de Problemas na Desinstalação:* Se você não seguiu os passos de desinstalação, pode encontrar um aviso durante a desinstalação:

`Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: unable to recognize "": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"`

Isso pode significar algumas coisas. Você selecionou todos os apps no namespace `istio-system` e os excluiu ao mesmo tempo, ou você excluiu as dependências do chart `rancher-istio` antes de excluir o chart `rancher-istio`. Como a desinstalação não foi concluída corretamente, você terá recursos restantes no namespace `istio-system` que precisará limpar manualmente. Outra opção para evitar a limpeza manual é instalar `rancher-istio` novamente e, em seguida, desinstalá-lo na ordem correta.

[#_disable_istio_in_a_namespace]
== Desabilitar o Istio em um Namespace

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que você criou e clique em *Explorar*.
. Clique em menu:Cluster[Projetos/Namespaces].
. Vá para o namespace onde você deseja habilitar o Istio e clique em *⋮  > Habilitar Injeção Automática do Istio*. Alternativamente, clique no namespace e, em seguida, na página de detalhes do namespace, clique em *⋮  > Habilitar Injeção Automática do Istio*.

*Resultado:* Quando cargas de trabalho são implantadas neste namespace, elas não terão o sidecar do Istio.

[#_remove_the_istio_sidecar_from_a_workload]
== Remover o Sidecar do Istio de uma Carga de Trabalho

Desative o Istio no namespace e, em seguida, reimplante as cargas de trabalho nele. Elas serão implantadas sem o sidecar do Istio.
