= {rancher-product-name} Deployment Quick Start Guides
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/index.adoc 
:product-path: installation-and-upgrade/quick-start/quick-start.adoc
ifeval::["{build-type}" != "community"]
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-qs-deploy-workloads: xref:installation-and-upgrade/quick-start/deploy-workloads/deploy-workloads.adoc
:xref-qs-deploy-rancher: xref:installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-qs-deploy-workloads: xref:getting-started/quick-start-guides/deploy-workloads/index.adoc
:xref-qs-deploy-rancher: xref:getting-started/quick-start-guides/deploy-rancher-manager/index.adoc
endif::[]

[CAUTION]
====

The intent of these guides is to quickly launch a sandbox that you can use to evaluate Rancher. These guides are not intended for production environments. For comprehensive setup instructions, see {xref-install-upgrade}[Installation].
====


Use this section of the docs to jump start your deployment and testing of Rancher 2.x. It contains instructions for a simple Rancher setup and some common use cases. We plan on adding more content to this section in the future.

We have Quick Start Guides for:

* {xref-qs-deploy-rancher}[Deploying Rancher Server]: Get started running Rancher using the method most convenient for you.
* {xref-qs-deploy-workloads}[Deploying Workloads]: Deploy a simple https://kubernetes.io/docs/concepts/workloads/[workload] and expose it, letting you access it from outside the cluster.
