= Livraison continue
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/enable-experimental-features/continuous-delivery.adoc 
:product-path: rancher-admin/experimental-features/continuous-delivery.adoc
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-fleet: xref:integrations/fleet/fleet.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-fleet: xref:integrations-in-rancher/fleet/index.adoc
endif::[]

{xref-fleet}[La Livraison Continue avec Fleet] est préinstallée dans Rancher et ne peut pas être complètement désactivée. Cependant, la fonctionnalité Fleet pour la livraison continue GitOps peut être désactivée à l'aide du drapeau de fonctionnalité `continuous-delivery`.

Pour activer ou désactiver cette fonctionnalité, reportez-vous aux instructions sur {xref-experimental-features}[la page principale concernant l'activation des fonctionnalités expérimentales.]

|===
| Clé de Variable d'Environnement | Valeur par défaut | Description

| `continuous-delivery`
| `true`
| Ce drapeau désactive la fonctionnalité de livraison continue GitOps de Fleet.
|===

Si Fleet a été désactivé dans Rancher v2.5.x, il sera activé si Rancher est mis à niveau vers v2.6.x. Seule la partie livraison continue de Fleet peut être désactivée. Lorsque `continuous-delivery` est désactivé, le déploiement `gitjob` n'est plus déployé dans la grappe locale du serveur Rancher, et `continuous-delivery` n'est pas affiché dans l'interface utilisateur de Rancher.
