= Activation des Fonctionnalités Expérimentales
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-22
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc 
:product-path: rancher-admin/experimental-features/experimental-features.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap-rancher-ha: xref:installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc
:xref-unsupported-storage-drivers: xref:rancher-admin/experimental-features/unsupported-storage-drivers.adoc
:xref-feature-flags: xref:installation-and-upgrade/references/feature-flags.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap-rancher-ha: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha.adoc
:xref-unsupported-storage-drivers: xref:how-to-guides/advanced-user-guides/enable-experimental-features/unsupported-storage-drivers.adoc
:xref-feature-flags: xref:getting-started/installation-and-upgrade/installation-references/feature-flags.adoc
endif::[]

Rancher inclut certaines fonctionnalités qui sont expérimentales et désactivées par défaut. Vous pourriez vouloir activer ces fonctionnalités, par exemple, si vous décidez que les avantages d'utiliser un {xref-unsupported-storage-drivers}[type de stockage non pris en charge] l'emportent sur le risque d'utiliser une fonctionnalité non testée. Les drapeaux de fonctionnalités ont été introduits pour vous permettre d'essayer ces fonctionnalités qui ne sont pas activées par défaut.

Les fonctionnalités peuvent être activées de trois manières{nbsp}:

* <<_enabling_features_when_starting_rancher,Activer les fonctionnalités lors du démarrage de Rancher.>> Lors de l'installation de Rancher avec une CLI, vous pouvez utiliser un drapeau de fonctionnalité pour activer une fonctionnalité par défaut.
* <<_enabling_features_with_the_rancher_ui,Activer les fonctionnalités depuis l'interface utilisateur de Rancher>> en allant sur la page *Paramètres*.
* <<_enabling_features_with_the_rancher_api,Activer les fonctionnalités avec l'API Rancher>> après l'installation de Rancher.

Chaque fonctionnalité a deux valeurs{nbsp}:

* Une valeur par défaut, qui peut être configurée avec un drapeau ou une variable d'environnement depuis la ligne de commande
* Une valeur définie, qui peut être configurée avec l'API ou l'interface utilisateur de Rancher

Si aucune valeur n'a été définie, Rancher utilise la valeur par défaut.

Parce que l'API définit la valeur réelle et que la ligne de commande définit la valeur par défaut, cela signifie que si vous activez ou désactivez une fonctionnalité avec l'API ou l'interface utilisateur, cela remplacera toute valeur définie avec la ligne de commande.

Par exemple, si vous installez Rancher, puis définissez un drapeau de fonctionnalité sur vrai avec l'API Rancher, puis mettez à niveau Rancher avec une commande qui définit le drapeau de fonctionnalité sur faux, la valeur par défaut sera toujours fausse, mais la fonctionnalité sera toujours activée car elle a été définie avec l'API Rancher. Si vous supprimez ensuite la valeur définie (vraie) avec l'API Rancher, en la définissant sur NULL, la valeur par défaut (fausse) prendra effet. Voir la {xref-feature-flags}[page des drapeaux de fonctionnalités] pour plus d'informations.

[#_enabling_features_when_starting_rancher]
== Activer des fonctionnalités lors du démarrage de Rancher

Lorsque vous installez Rancher, activez la fonctionnalité souhaitée avec un drapeau de fonctionnalité. La commande est différente selon que vous installez Rancher sur un nœud unique ou si vous effectuez une installation de Rancher sur Kubernetes.

[#_enabling_features_for_kubernetes_installs]
=== Activer des fonctionnalités pour les installations Kubernetes

[NOTE]
====

Les valeurs définies à partir de l'API Rancher remplaceront la valeur transmise par la ligne de commande.
====


Lors de l'installation de Rancher avec un chart Helm, utilisez l'option `--set`. Dans l'exemple ci-dessous, deux fonctionnalités sont activées en passant les noms des drapeaux de fonctionnalité dans une liste séparée par des virgules{nbsp}:

[,shell,subs="attributes+"]
----
helm install rancher {rancher-helm-repo}/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set 'extraEnv[0].name=CATTLE_FEATURES'
  --set 'extraEnv[0].value=<FEATURE-FLAG-NAME-1>=true,<FEATURE-FLAG-NAME-2>=true'
----

[#_enabling_features_for_air_gap_installs]
=== Activer des fonctionnalités pour les installations en isolation physique

Pour effectuer une {xref-air-gap-rancher-ha}[installation de Rancher en isolation physique], ajoutez un dépôt de chart Helm et téléchargez un chart Helm, puis installez Rancher avec Helm.

Lorsque vous installez le chart Helm, vous devez passer les noms des drapeaux de fonctionnalité dans une liste séparée par des virgules, comme dans l'exemple suivant{nbsp}:

----
helm install rancher ./rancher-<VERSION>.tgz \
  --namespace cattle-system 
  --set hostname=<RANCHER.YOURDOMAIN.COM> \
  --set image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
  --set ingress.tls.source=secret \
  --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ # Set a default private registry to be used in Rancher
  --set useBundledSystemChart=true # Use the packaged Rancher system charts
  --set 'extraEnv[0].name=CATTLE_FEATURES'
  --set 'extraEnv[0].value=<FEATURE-FLAG-NAME-1>=true,<FEATURE-FLAG-NAME-2>=true'
----

[#_enabling_features_for_docker_installs]
=== Activer des fonctionnalités pour les installations Docker

Lors de l'installation de Rancher avec Docker, utilisez l'option `--features`. Dans l'exemple ci-dessous, deux fonctionnalités sont activées en passant les noms des drapeaux de fonctionnalité dans une liste séparée par des virgules{nbsp}:

----
docker run -d -p 80:80 -p 443:443 \
  --restart=unless-stopped \
  rancher/rancher:rancher-latest \
  --features=<FEATURE-FLAG-NAME-1>=true,<FEATURE-FLAG-NAME-2>=true
----

[#_enabling_features_with_the_rancher_ui]
== Activer des fonctionnalités avec l'interface utilisateur de Rancher

. Dans le coin supérieur gauche, cliquez sur *☰ > Paramètres globaux*.
. Cliquez sur *Drapeaux de fonctionnalités*.
. Pour activer une fonctionnalité, allez à la fonctionnalité désactivée que vous souhaitez activer et cliquez sur *⋮ > Activer*.

*Résultat :* La fonctionnalité est activée.

[#_disabling_features_with_the_rancher_ui]
=== Désactiver des fonctionnalités avec l'interface utilisateur de Rancher

. Dans le coin supérieur gauche, cliquez sur *☰ > Paramètres globaux*.
. Cliquez sur *Drapeaux de fonctionnalités*. Vous verrez une liste de fonctionnalités expérimentales.
. Pour désactiver une fonctionnalité, allez à la fonctionnalité activée que vous souhaitez désactiver et cliquez sur *⋮ > Désactiver*.

*Résultat :* La fonctionnalité est désactivée.

[#_enabling_features_with_the_rancher_api]
== Activer des fonctionnalités avec l'API Rancher

. Accédez à l'`<RANCHER-SERVER-URL>/v3/features`.
. Dans la section `data`, vous verrez un tableau contenant toutes les fonctionnalités qui peuvent être activées avec des drapeaux de fonctionnalité. Le nom de la fonctionnalité se trouve dans le champ `id`. Cliquez sur le nom de la fonctionnalité que vous souhaitez activer.
. Dans le coin supérieur gauche de l'écran, sous *Opérations,*, cliquez sur *Modifier*.
. Dans le menu déroulant *Valeur*, cliquez sur *Vrai*.
. Cliquez sur *Afficher la demande*.
. Cliquez sur *Envoyer la demande*.
. Cliquez sur *Fermer*.

*Résultat :* La fonctionnalité est activée.

[#_disabling_features_with_the_rancher_api]
=== Désactiver des fonctionnalités avec l'API Rancher

. Accédez à l'`<RANCHER-SERVER-URL>/v3/features`.
. Dans la section `data`, vous verrez un tableau contenant toutes les fonctionnalités qui peuvent être activées avec des drapeaux de fonctionnalité. Le nom de la fonctionnalité se trouve dans le champ `id`. Cliquez sur le nom de la fonctionnalité que vous souhaitez activer.
. Dans le coin supérieur gauche de l'écran, sous *Opérations,*, cliquez sur *Modifier*.
. Dans le menu déroulant *Valeur*, cliquez sur *Faux*.
. Cliquez sur *Afficher la demande*.
. Cliquez sur *Envoyer la demande*.
. Cliquez sur *Fermer*.

*Résultat :* La fonctionnalité est désactivée.
