= Options du chart Helm rancher-logging
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-15
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/logging-helm-chart-options.adoc 
:product-path: observability/logging/logging-helm-chart-options.adoc
ifeval::["{build-type}" != "community"]
:xref-selinux-rpm: xref:security/selinux-rpm/selinux-rpm.adoc
:xref-logging-taints-and-tolerations: xref:observability/logging/taints-and-tolerations.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selinux-rpm: xref:reference-guides/rancher-security/selinux-rpm/index.adoc
:xref-logging-taints-and-tolerations: xref:integrations-in-rancher/logging/taints-and-tolerations.adoc
endif::[]

[#_enable_disable_windows_node_logging]
== Activer/Désactiver la journalisation des nœuds Windows

Vous pouvez activer ou désactiver la journalisation des nœuds Windows en définissant `global.cattle.windows.enabled` sur `true` ou `false` dans le `values.yaml`.

Par défaut, la journalisation des nœuds Windows sera activée si l'interface utilisateur du tableau de bord du cluster est utilisée pour installer l'application de journalisation sur un cluster Windows.

Dans ce scénario, définir `global.cattle.windows.enabled` sur `false` désactivera la journalisation des nœuds Windows sur le cluster.
Lorsque désactivée, les journaux seront toujours collectés à partir des nœuds Linux au sein du cluster Windows.

[NOTE]
====

Actuellement, un https://github.com/rancher/rancher/issues/32325[problème] existe où les agents de nœuds Windows ne sont pas supprimés lors de l'exécution d'un `helm upgrade` après avoir désactivé la journalisation Windows dans un cluster Windows. Dans ce scénario, les utilisateurs peuvent avoir besoin de supprimer manuellement les agents de nœuds Windows s'ils sont déjà installés.
====


[#_working_with_a_custom_docker_root_directory]
== Travailler avec un répertoire racine Docker personnalisé

Si vous utilisez un répertoire racine Docker personnalisé, vous pouvez définir `global.dockerRootDirectory` dans `values.yaml`.

Cela garantira que les CRs de journalisation créés utiliseront votre chemin spécifié plutôt que l'emplacement par défaut de Docker `data-root`.

Notez que cela n'affecte que les nœuds Linux.

S'il y a des nœuds Windows dans le cluster, le changement ne sera pas applicable à ces nœuds.

[#_adding_nodeselector_settings_and_tolerations_for_custom_taints]
== Ajouter des paramètres NodeSelector et des tolérances pour des taints personnalisés

Vous pouvez ajouter vos propres paramètres `nodeSelector` et ajouter `tolerations` pour des taints supplémentaires en modifiant les valeurs du chart Helm de journalisation. Pour plus de détails, voir {xref-logging-taints-and-tolerations}[cette page.]

[#_enabling_the_logging_application_to_work_with_selinux]
== Activer l'application de journalisation pour fonctionner avec SELinux

[NOTE]
.Configuration requise :
====

La journalisation v2 a été testée avec SELinux sur RHEL/CentOS 7 et 8.
====


https://en.wikipedia.org/wiki/Security-Enhanced_Linux[Linux à sécurité renforcée (SELinux)] est une amélioration de la sécurité pour Linux. Après avoir été historiquement utilisé par des agences gouvernementales, SELinux est désormais une norme industrielle et est activé par défaut sur CentOS 7 et 8.

Pour utiliser la journalisation v2 avec SELinux, nous recommandons d'installer le `rancher-selinux` RPM selon ces {xref-selinux-rpm}[instructions].

Ensuite, lors de l'installation de l'application de journalisation, configurez le chart pour qu'il prenne en compte SELinux en changeant `global.seLinux.enabled` en `true` dans le `values.yaml`.

[#_additional_logging_sources]
== Sources de journalisation supplémentaires

Par défaut, Rancher collecte des journaux pour https://kubernetes.io/docs/concepts/overview/components/#control-plane-components[les composants du plan de contrôle] et https://kubernetes.io/docs/concepts/overview/components/#node-components[les composants des nœuds] pour tous les types de clusters.

Dans certains cas, Rancher peut être en mesure de collecter des journaux supplémentaires.

Le tableau suivant résume les sources où des journaux supplémentaires peuvent être collectés pour chaque type de nœud{nbsp}:

|===
| Source de journalisation | Nœuds Linux (y compris dans le cluster Windows) | Nœuds Windows

| RKE2
| ✓
|

| K3s
| ✓
|

ifeval::["{build-type}" != "srfa"]
| AKS
| ✓
|

| EKS
| ✓
|

| GKE
| ✓
|
endif::[]
ifeval::["{build-type}" == "srfa"]
| EKS
| ✓
|
endif::[]
|===

Pour activer les fournisseurs Kubernetes hébergés en tant que sources de journalisation supplémentaires, activez l'option *Activer la journalisation améliorée des fournisseurs cloud* lors de l'installation ou de la mise à niveau du chart Helm de journalisation.

Lorsqu'elle est activée, Rancher collecte tous les journaux supplémentaires des nœuds et du plan de contrôle que le fournisseur a rendus disponibles, ce qui peut varier entre les fournisseurs.

Si vous utilisez déjà la solution de journalisation propre à un fournisseur cloud, comme AWS CloudWatch ou la suite d'opérations Google Cloud (anciennement Stackdriver), il n'est pas nécessaire d'activer cette option car la solution native aura un accès illimité à tous les journaux.

[#_systemd_configuration]
== Configuration de Systemd

Dans la journalisation Rancher, `SystemdLogPath` doit être configuré pour les distributions Kubernetes K3s et RKE2.

Les distributions Kubernetes K3s et RKE2 enregistrent dans journald, qui est le sous-système de systemd utilisé pour la journalisation. Pour collecter ces journaux, le `systemdLogPath` doit être défini. Bien que le répertoire `run/log/journal` soit utilisé par défaut, certaines distributions Linux n'utilisent pas ce chemin par défaut. Par exemple, Ubuntu utilise par défaut `var/log/journal`. Pour déterminer votre configuration `systemdLogPath`, consultez les étapes ci-dessous.

*Étapes pour la configuration de Systemd\&nbsp;:*

* Exécutez `cat /etc/systemd/journald.conf | grep -E ^\#?Storage | cut -d"=" -f2` sur l'un de vos nœuds.
* Si `persistent` est retourné, votre `systemdLogPath` devrait être `/var/log/journal`.
* Si `volatile` est retourné, votre `systemdLogPath` devrait être `/run/log/journal`.
* Si `auto` est retourné, vérifiez si `/var/log/journal` existe.
 ** Si `/var/log/journal` existe, utilisez `/var/log/journal`.
 ** Si `/var/log/journal` n'existe pas, utilisez `/run/log/journal`.

[NOTE]
====

Si une valeur non décrite ci-dessus est retournée, Rancher Logging ne pourra pas collecter les journaux du plan de contrôle. Pour résoudre ce problème, vous devrez effectuer les actions suivantes sur chaque nœud du plan de contrôle{nbsp}:

* Définissez `Storage=volatile` dans journald.conf.
* Redémarrez votre machine.
* Définissez `systemdLogPath` sur `/run/log/journal`.
====

