= {rancher-product-name} Intégration avec les services de journalisation
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/index.adoc 
:product-path: observability/logging/logging.adoc
:description: Rancher s'intègre aux services de journalisation populaires. Découvrez les exigences et les avantages de l'intégration avec les services de journalisation, et activez la journalisation sur votre cluster.
ifeval::["{build-type}" != "community"]
:xref-logging-taints-and-tolerations: xref:observability/logging/taints-and-tolerations.adoc
:xref-logging-helm-chart-options: xref:observability/logging/logging-helm-chart-options.adoc
:xref-logging-architecture: xref:observability/logging/logging-architecture.adoc
:xref-logging-rbac: xref:observability/logging/rbac-for-logging.adoc
:xref-logging-flows-clusterflows: xref:observability/logging/custom-resource-configuration/flows-and-clusterflows.adoc
:xref-logging-outputs-clusteroutputs: xref:observability/logging/custom-resource-configuration/outputs-and-clusteroutputs.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-logging-taints-and-tolerations: xref:integrations-in-rancher/logging/taints-and-tolerations.adoc
:xref-logging-helm-chart-options: xref:integrations-in-rancher/logging/logging-helm-chart-options.adoc
:xref-logging-architecture: xref:integrations-in-rancher/logging/logging-architecture.adoc
:xref-logging-rbac: xref:integrations-in-rancher/logging/rbac-for-logging.adoc
:xref-logging-flows-clusterflows: xref:integrations-in-rancher/logging/custom-resource-configuration/flows-and-clusterflows.adoc
:xref-logging-outputs-clusteroutputs: xref:integrations-in-rancher/logging/custom-resource-configuration/outputs-and-clusteroutputs.adoc
endif::[]

Le https://kube-logging.github.io/docs/[Opérateur de journalisation] alimente désormais la solution de journalisation de Rancher à la place de l'ancienne solution interne.

[#_enabling_logging]
== Activation de la journalisation

Vous pouvez activer la journalisation pour un cluster géré par Rancher en allant sur la page des applis et en installant l'appli de journalisation.

. Allez au cluster où vous souhaitez installer la journalisation et cliquez sur *Applis*.
. Cliquez sur l'appli *Journalisation*.
. Faites défiler jusqu'en bas du README du chart Helm et cliquez sur *Installer*.

*Résultat :* L'application de journalisation est déployée dans l'espace de noms `cattle-logging-system`.

[#_uninstall_logging]
== Désinstaller la journalisation

. Allez au cluster où vous souhaitez installer la journalisation et cliquez sur *Applis*.
. Cliquez sur *Applis installées*.
. Allez dans l'espace de noms `cattle-logging-system` et cochez les cases pour `rancher-logging` et `rancher-logging-crd`.
. Cliquez sur *Supprimer*.
. Confirmez *Supprimer*.

*Résultat* `rancher-logging` est désinstallé.

[#_architecture]
== Architecture

Pour plus d'informations sur le fonctionnement de l'appli de journalisation, consultez {xref-logging-architecture}[cette section.]

[#_role_based_access_control]
== Contrôle d'accès en fonction du rôle

Rancher logging a deux rôles, `logging-admin` et `logging-view`. Pour plus d'informations sur la façon et le moment d'utiliser ces rôles, consultez {xref-logging-rbac}[cette page.]

[#_configuring_logging_custom_resources]
== Configuration des ressources personnalisées de journalisation

Pour gérer `Flows,` `ClusterFlows`, `Outputs` et `ClusterOutputs`,

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, allez au cluster où vous souhaitez configurer les ressources personnalisées de journalisation et cliquez sur *Explorer*.
. Dans la barre de navigation de gauche, cliquez sur *Journalisation*.

[#_flows_and_clusterflows]
=== Flux et ClusterFlows

Pour obtenir de l'aide sur la configuration de `Flows` et `ClusterFlows`, consultez {xref-logging-flows-clusterflows}[cette page.]

[#_outputs_and_clusteroutputs]
=== Sorties et ClusterOutputs

Pour obtenir de l'aide sur la configuration de `Outputs` et `ClusterOutputs`, consultez {xref-logging-outputs-clusteroutputs}[cette page.]

[#_using_a_custom_hosttailer_image]
== Utilisation d'une image Custom HostTailer

Pour utiliser une image personnalisée pour la ressource `HostTailer`, vous devez spécifier l'image dans la section `containerOverrides` de chaque `fileTailer` de la ressource `HostTailer`.

[,yaml]
----
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: cluster-system-log
spec:
  workloadMetaOverrides:
    annotations: {}
    labels: {}
  fileTailers:
    - disabled: false
      name: kubelet-log
      path: /var/lib/rancher/rke2/agent/logs/*.log
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
    - disabled: false
      name: containerd-log
      path: /var/lib/rancher/rke2/agent/containerd/*.log
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
    - name: kube-audit
      path: /var/log/kube-audit/audit-log.json
      disabled: false
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
----

[#_configuring_the_logging_helm_chart]
== Configuration du Helm Chart de journalisation

Pour une liste des options pouvant être configurées lors de l'installation ou de la mise à niveau de l'application de journalisation, voir {xref-logging-helm-chart-options}[cette page.]

[#_windows_support]
=== Support Windows

Vous pouvez xref:./logging-helm-chart-options.adoc#_enabledisable_windows_node_logging[activer la journalisation] depuis les nœuds Windows.

[#_working_with_a_custom_docker_root_directory]
=== Travailler avec un répertoire racine Docker personnalisé

Pour des détails sur l'utilisation d'un répertoire racine Docker personnalisé, voir xref:./logging-helm-chart-options.adoc#_working_with_a_custom_docker_root_directory[cette section.]

[#_working_with_taints_and_tolerations]
=== Travailler avec des taints et des tolérances

Pour des informations sur l'utilisation des taints et des tolérances avec l'application de journalisation, voir {xref-logging-taints-and-tolerations}[cette page.]

[#_logging_v2_with_selinux]
=== Journalisation V2 avec SELinux

Pour des informations sur l'activation de l'application de journalisation sur les nœuds où SELinux est activé, voir xref:./logging-helm-chart-options.adoc#_enabling_the_logging_application_to_work_with_selinux[cette section.]

[#_additional_logging_sources]
=== Sources de journalisation supplémentaires

Par défaut, Rancher collecte les journaux pour les composants du plan de contrôle et les composants des nœuds pour tous les types de clusters. Dans certains cas, des journaux supplémentaires peuvent être collectés. Pour des détails, voir xref:./logging-helm-chart-options.adoc#_additional_logging_sources[cette section.]

[#_troubleshooting]
== Dépannage

[#_the_logging_buffer_overloads_pods]
=== Le tampon de journalisation surcharge les pods

Selon votre configuration, la taille de tampon par défaut peut être trop grande et provoquer des échecs de pods. Une façon de réduire la charge est de diminuer l'intervalle de vidage du journaliseur. Cela empêche les journaux de trop remplir le tampon. Vous pouvez également ajouter plus de threads de vidage pour gérer les moments où de nombreux journaux tentent de remplir le tampon en même temps.

Pour une description plus complète de la façon de configurer le tampon de journalisation pour répondre aux besoins de votre organisation, voir la documentation officielle de l'opérateur de journalisation sur https://kube-logging.github.io/docs/configuration/plugins/outputs/buffer/[tampons] et sur https://kube-logging.github.io/docs/logging-infrastructure/fluentd/[configuration de Fluentd].

[#_the_cattle_logging_namespace_being_recreated]
=== Le `cattle-logging` espace de noms est en cours de recréation

Si votre cluster a précédemment déployé la journalisation depuis la vue globale dans l'interface utilisateur héritée de Rancher, vous pouvez rencontrer un problème où son `cattle-logging` espace de noms est continuellement recréé.

La solution consiste à supprimer toutes les ressources personnalisées `clusterloggings.management.cattle.io` et `projectloggings.management.cattle.io` de l'espace de noms spécifique au cluster dans le cluster de gestion.
L'existence de ces ressources personnalisées entraîne la création de l'espace de noms `cattle-logging` dans le cluster en aval s'il n'existe pas.

L'espace de noms du cluster correspond à l'ID du cluster, nous devons donc trouver l'ID du cluster pour chaque cluster.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, allez au cluster dont vous souhaitez obtenir l'ID et cliquez sur *Explorer*.
. Copiez la portion `<cluster-id>` d'une des URL ci-dessous. La portion `<cluster-id>` est le nom de l'espace de noms du cluster.

[,bash]
----
# Cluster Management UI
https://<your-url>/c/<cluster-id>/

# Cluster Dashboard
https://<your-url>/dashboard/c/<cluster-id>/
----

Maintenant que nous avons l'espace de noms `<cluster-id>`, nous pouvons supprimer les CR qui provoquent la recréation continue de `cattle-logging`.
_Avertissement\&nbsp;:_ assurez-vous que la journalisation, la version installée depuis la vue globale dans l'interface utilisateur héritée de Rancher, n'est pas actuellement utilisée.

[,bash]
----
kubectl delete crd clusterloggings.management.cattle.io -n <cluster-id>
kubectl delete crd projectloggings.management.cattle.io -n <cluster-id>
----
