= Contrôle d'accès en fonction du rôle pour la journalisation
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/rbac-for-logging.adoc 
:product-path: observabilité/journalisation/rbac-pour-journalisation.adoc

La journalisation Rancher a deux rôles, `logging-admin` et `logging-view`.

* `logging-admin` donne aux utilisateurs un accès complet aux `Flows` et `Outputs` dans l’espace de noms.
* `logging-view` permet aux utilisateurs de _voir_ les `Flows` et `Outputs` dans l’espace de noms, ainsi que `ClusterFlows` et `ClusterOutputs`.

[NOTE]
.Pourquoi choisir un rôle plutôt qu'un autre{nbsp}?
====

L'accès d'édition aux ressources `ClusterFlow` et `ClusterOutput` est puissant. Tout utilisateur disposant de cet accès peut modifier tous les journaux dans le cluster.
====


Dans Rancher, le rôle d'administrateur de cluster est le seul rôle ayant un accès complet à toutes les ressources `rancher-logging`. Les membres du cluster ne peuvent ni modifier ni lire les ressources de journalisation. Les propriétaires de projet et les membres ont les privilèges suivants{nbsp}:

|===
| Propriétaires de projet | Membres de projet

| capables de créer des `Flows` et `Outputs` dans les espaces de noms de leurs projets
| uniquement capables de voir les `Flows` et `Outputs` dans les espaces de noms des projets

| peuvent collecter des journaux de tout ce qui se trouve dans les espaces de noms de leurs projets
| ne peuvent pas collecter de journaux dans les espaces de noms de leurs projets
|===

Les propriétaires de projet et les membres de projet nécessitent au moins _un_ espace de noms dans leur projet pour utiliser la journalisation. S'ils n'en ont pas, ils ne verront peut-être pas le bouton de journalisation dans le menu déroulant de navigation en haut.
