= Creando un clúster de Google Compute Engine
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: guías-prácticas/nuevos-usuarios/guías-de-nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/crear-un-clúster-de-google-compute-engine.adoc 
:product-path: cluster-deployment/infra-providers/gce/gce.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-infra-gce-machine-config: xref:cluster-deployment/infra-providers/gce/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:guías-de-referencia/configuración-de-cluster/configuración-del-servidor-rancher/configuración-del-cluster-rke2.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:guías-de-referencia/configuración-de-cluster/configuración-del-servidor-rancher/configuración-del-cluster-k3s.adoc
:xref-infra-gce-machine-config: xref:guías-de-referencia/configuración-del-clúster/configuración-del-clúster-descendente/configuración-de-máquina/google-gce.adoc
endif::[]

En esta sección, aprenderás a utilizar Rancher para aprovisionar un clúster de Kubernetes {url-rke2-landing-page}[RKE2] o {url-k3s-landing-page}[K3s] en Google Cloud Platform (GCP) utilizando Google Compute Engine (GCE) a través de Rancher.

Primero, habilitarás el controlador de nodos GCE en la interfaz de usuario de Rancher. Luego, seguirás los pasos para crear una cuenta de servicio de GCP con los permisos necesarios y generar un archivo de clave JSON. Este archivo de clave se utilizará para crear una credencial de nube en Rancher. 

Luego, crearás un clúster GCE en Rancher, y al configurar el clúster, definirás grupos de máquinas para él. Cada grupo de máquinas tendrá un rol de Kubernetes de etcd, controlplane o worker. Rancher instalará RKE2 en los nuevos nodos y configurará cada nodo con el rol de Kubernetes definido por el grupo de máquinas.

. <<_enable_the_gce_node_driver>>
. <<_create_a_cloud_credential>>
. <<_create_a_cluster_using_the_cloud_credential>>
. <<_gce_best_practices>>

[#_prerequisites]
== Requisitos previos

.  Una cuenta y proyecto válidos de Google Cloud Platform.
.  Un archivo de clave JSON de cuenta de servicio de GCP. La cuenta de servicio asociada con esta clave debe tener los siguientes roles IAM:
.. **Administrador de Cómputo**
.. **Usuario de Cuenta de Servicio**
.. **Visor**
. Una red VPC para aprovisionar máquinas virtuales. 

Consulta la https://cloud.google.com/iam/docs/service-account-overview[documentación de GCP] sobre la creación y gestión de claves de cuentas de servicio para más detalles.

[#_enable_the_gce_node_driver]
== Habilitar el controlador de nodos GCE

El controlador de nodos GCE no está habilitado por defecto en Rancher. Debes habilitarlo antes de poder aprovisionar clústeres GCE o trabajar con CRD específicos de GCE.

. Haz clic en **☰ > Gestión de Clústeres**.
. En el lado izquierdo, haz clic en **Controladores**.
. Abre la pestaña **Controladores de Nodo**.
. Encuentra el controlador **Google GCE** y selecciona **⋮ > Activar**.

[#_create_a_cloud_credential]
== Crea una credencial de nube

. Haz clic en **☰ > Gestión de Clústeres**.
. Haz clic en **Credenciales de Nube**.
. Haz clic en **Crear**.
. Haz clic en **Google**.
. Introduce tu archivo de clave JSON de la cuenta de servicio de GCP.
. Haz clic en **Crear**.

**Resultado:** Has creado las credenciales de nube que se utilizarán para aprovisionar nodos en tu clúster. Puedes reutilizar estas credenciales en otros clústeres. Dependiendo de los permisos otorgados a la cuenta de servicio, esta credencial también puede ser utilizada para clústeres de GKE.

[#_create_a_cluster_using_the_cloud_credential]
== Crea un clúster utilizando la credencial de nube

. Haz clic en **☰ > Gestión de Clústeres**.
. En la página **Clústeres**, haz clic en **Crear**.
. Haz clic en **Google GCE**.
. Selecciona una **Credencial de Nube** y proporciona el proyecto de GCP para crear la VM en él.
. Introduce un **Nombre del Clúster**.
. Crea un grupo de máquinas para cada rol de Kubernetes. Consulta las [mejores prácticas](use-new-nodes-in-an-infra-provider.md#node-roles) para recomendaciones sobre asignaciones de roles y cantidades.
.. Para cada grupo de máquinas, define la configuración de la máquina. Consulta la {xref-infra-gce-machine-config}[referencia de configuración de máquinas Google GCE] para información sobre las opciones de configuración.
. Utiliza la **Configuración del Clúster** para elegir la versión de Kubernetes que se instalará, qué proveedor de red se utilizará y si deseas habilitar el aislamiento de red del proyecto. Para ayuda configurando el clúster, consulta las {xref-rke2-config}[referencias de configuración de clúster RKE2] y {xref-k3s-config}[K3s].
. Utiliza **Roles de Miembros** para configurar la autorización de usuarios para el clúster. Haz clic en **Añadir Miembro** para añadir usuarios que puedan acceder al clúster. Utiliza el menú desplegable **Rol** para establecer permisos para cada usuario.
. Haz clic en **Crear**.

**Resultado:**

Tu clúster se ha creado y se le ha asignado un estado de **Aprovisionamiento**. Rancher está configurando tu clúster.

Puedes acceder a tu clúster después de que su estado se actualice a **Activo**.

Los clústeres **Activos** están asignados a dos proyectos:

* `Default`, que contiene el espacio de nombres `default`
* `System`, que contiene los espacios de nombres `cattle-system`, `traefik`, `kube-public` y `kube-system`

[#_gce_best_practices]
== Prácticas recomendadas de GCE

[#_external_firewall_rules_open_ports_and_ace]
=== Reglas de Firewall Externas, Puertos Abiertos y ACE

Si el clúster que se está aprovisionando utilizará la {xref-access-cluster-kubectl}#_autenticación_directa_con_un_clúster_en_sentido_descendente[función de Punto de Acceso de Clúster Autorizado (ACE)], los nodos del plano de control deben exponer el puerto `6443`. Este puerto no está expuesto en la configuración predeterminada del grupo de máquinas para evitar que se exponga en todos los nodos del clúster y para reducir el número de reglas de firewall creadas por Rancher.

Para que ACE funcione como se espera, debes especificar este puerto en la interfaz de usuario de Rancher al configurar el grupo de máquinas del plano de control habilitando la casilla `Expose external ports`, en la sección `Show Advanced` de la interfaz de configuración del grupo de máquinas. Alternativamente, puedes crear manualmente una regla de firewall personalizada en GCP y proporcionar la etiqueta de red relacionada en la configuración del grupo de máquinas del plano de control.

[#_internal_firewall_rules]
=== Reglas de Firewall Internas

Rancher creará automáticamente una regla de firewall y una etiqueta de red para facilitar la comunicación entre los nodos del clúster internamente dentro de la red VPC especificada. Esta regla contendrá el número mínimo de puertos requeridos para crear un clúster RKE2/K3s.

Si necesitas ampliar el número de puertos expuestos internamente entre los nodos del clúster, se debe crear manualmente una nueva regla de firewall, y la etiqueta de red asociada debe asignarse a los grupos de máquinas relevantes. Si lo deseas, la creación automática de la regla de firewall interna se puede desactivar para cada grupo de máquinas dado al crear o actualizar el clúster.

[#_cross_network_deployments]
=== Despliegues entre redes

Si bien es posible desplegar diferentes grupos de máquinas en diferentes redes VPC, la regla de firewall interna creada por Rancher no admite esta configuración de forma predeterminada. Para crear grupos de máquinas en diferentes redes, se deben crear manualmente reglas de firewall adicionales para facilitar la comunicación entre nodos en diferentes redes.

[#_optional_next_steps]
== Pasos siguientes opcionales

Después de crear tu clúster, puedes acceder a él a través de la interfaz de usuario de Rancher. Como mejor práctica, recomendamos configurar estas formas alternativas de acceder a tu clúster:

* **Accede a tu clúster con la CLI de kubectl:** Sigue {xref-access-cluster-kubectl}#_accediendo_a_clústeres_con_kubectl_desde_tu_estación_de_trabajo[estos pasos] para acceder a clústeres con kubectl en tu estación de trabajo. En este caso, serás autenticado a través del proxy de autenticación del servidor de Rancher, luego Rancher te conectará al clúster en sentido descendente. Este método te permite gestionar el clúster sin la interfaz de usuario de Rancher.
* **Accede a tu clúster con la CLI de kubectl, utilizando el punto final autorizado del clúster:** Sigue {xref-access-cluster-kubectl}#_autenticando_directamente_con_un_clúster_descendente[estos pasos] para acceder a tu clúster con kubectl directamente, sin autenticarte a través de Rancher. Recomendamos configurar este método alternativo para acceder a tu clúster, de modo que, en caso de que no puedas conectarte a Rancher, aún puedas acceder al clúster.
