= {rancher-product-name} Démarrage rapide d'Equinix Metal
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/equinix-metal.adoc 
:product-path: installation-and-upgrade/quick-start/deploy-rancher/equinix-metal.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-qs-deploy-workloads: xref:installation-and-upgrade/quick-start/deploy-workloads/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-qs-deploy-workloads: xref:getting-started/quick-start-guides/deploy-workloads/index.adoc
endif::[]

[#_this_tutorial_walks_you_through_the_following]
== Ce tutoriel vous guide à travers les étapes suivantes{nbsp}:

* Provisionnement d'un serveur Equinix Metal
* Installation de Rancher 2.x
* Création de votre premier cluster
* Déploiement d'une application, Nginx

[CAUTION]
====

L'objectif de ces guides est de lancer rapidement une sandbox que vous pouvez utiliser pour évaluer Rancher. L'installation de Docker n'est pas recommandée pour les environnements de production. Pour des instructions de configuration complètes, voir {xref-install-upgrade}[Installation].
====


[#_quick_start_outline]
== Aperçu du démarrage rapide

Ce guide de démarrage rapide est divisé en différentes tâches pour une consommation plus facile.

[#_prerequisites]
== Conditions préalables

* Un https://deploy.equinix.com/developers/docs/metal/identity-access-management/users/[compte Equinix Metal]
* Un https://deploy.equinix.com/developers/docs/metal/projects/creating-a-project/[projet Equinix Metal]

[#_1_provision_a_equinix_metal_host]
=== 1. Provisionner un hôte Equinix Metal

Commencez à déployer un hôte Equinix Metal. Les serveurs Equinix Metal peuvent être provisionnés depuis la console Equinix Metal, l'API ou la CLI. Vous pouvez trouver des instructions pour chaque type de déploiement dans la https://deploy.equinix.com/developers/docs/metal/deploy/on-demand/[documentation de déploiement Equinix Metal]. Vous pouvez trouver des informations supplémentaires sur les types de serveurs Equinix Metal dans la https://deploy.equinix.com/developers/docs/metal/hardware/standard-servers/[Documentation Equinix Metal].

[NOTE]
.Remarques :
====

* Lors de la provision d'un nouveau serveur Equinix Metal via la CLI ou l'API, vous devrez fournir les informations suivantes{nbsp}: identifiant de projet, plan, métropole et système d'exploitation.
* Lorsque vous utilisez une machine virtuelle hébergée dans le cloud, vous devez autoriser la communication TCP entrante sur les ports 80 et 443. Veuillez consulter la documentation de votre hébergeur cloud pour des informations concernant la configuration des ports.
* Pour une liste complète des exigences en matière de ports, référez-vous à {xref-node-reqs}[Installation de Docker].
* Provisionnez l'hôte selon nos {xref-install-reqs}[Exigences].
====


[#_2_install_rancher]
=== 2. Installer Rancher

Pour installer Rancher sur votre hôte Equinix Metal, connectez-vous à celui-ci et utilisez un shell pour l'installation.

. Connectez-vous à votre hôte Equinix Metal en utilisant votre shell préféré, tel que PuTTy ou une connexion shell à distance.
. Depuis votre shell, entrez la commande suivante{nbsp}:
+
----
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher
----

*Résultat :* Rancher est installé.

[#_3_log_in]
=== 3. Connexion

Connectez-vous à Rancher pour commencer à utiliser l'application. Après vous être connecté, vous effectuerez quelques configurations initiales.

. Ouvrez un navigateur web et entrez l'adresse IP de votre hôte{nbsp}: `\https://<server_ip>`.
+
Remplacez `<SERVER_IP>` par l'adresse IP de votre hôte.

. Lorsque vous y êtes invité, créez un mot de passe pour le compte par défaut `admin`.
. Définissez l'*URL du serveur Rancher*. L'URL peut être soit une adresse IP, soit un nom d'hôte. Cependant, chaque nœud ajouté à votre cluster doit être capable de se connecter à cette URL. +
 +
Si vous utilisez un nom d'hôte dans l'URL, ce nom d'hôte doit être résolvable par DNS sur les nœuds que vous souhaitez ajouter à votre cluster.

{blank}

[#_4_create_the_cluster]
=== 4. Créer le cluster

Bienvenue dans Rancher{nbsp}! Vous pouvez maintenant créer votre premier cluster Kubernetes.

Dans cette tâche, vous pouvez utiliser l'option polyvalente *Personnalisé*. Cette option vous permet d'ajouter _tout_ hôte Linux (VM cloud, VM sur site ou matériel sans système d'exploitation) à utiliser dans un cluster.

. Cliquez sur *☰ > Gestion des clusters*.
. Depuis la page *Clusters*, cliquez sur *Créer*.
. Choisissez *Personnalisé*.
. Entrez un *Nom de cluster*.
. Cliquez sur *Next*.
. Dans *Rôle de nœud*, sélectionnez _tous_ les rôles{nbsp}: *etcd*, *Contrôle* et *Travailleur*.
 ** *Facultatif* : Rancher détecte automatiquement les adresses IP utilisées pour la communication Rancher et la communication de cluster. Vous pouvez les remplacer en utilisant `Public Address` et `Internal Address` dans la section *Adresse du nœud*.
. Copiez la commande d'enregistrement dans votre presse-papiers.
. Connectez-vous à votre hôte Linux en utilisant votre shell préféré, tel que PuTTy ou une connexion Terminal à distance. Exécutez la commande copiée dans votre presse-papiers.
. Lorsque vous avez terminé d'exécuter la commande sur votre hôte Linux, cliquez sur *Terminé*.

*Résultat :*

Votre cluster est créé et a un état de *Provisionnement*. Rancher est en train de déployer votre cluster.

Vous pouvez accéder à votre cluster après que son état soit mis à jour en *Actif*.

Les clusters *Actifs* sont assignés à deux projets{nbsp}:

* `Default`, contenant l'espace de noms `default`
* `System`, contenant les espaces de noms `cattle-system`, `traefik`, `kube-public` et `kube-system`

[#_finished]
==== Terminé

Félicitations ! Vous avez créé votre premier cluster.

[#_whats_next]
==== Et maintenant\...

Utilisez Rancher pour créer un déploiement. Pour plus d'informations, reportez-vous à {xref-qs-deploy-workloads}[Création de déploiements].
