= Opciones de configuración
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/configuration-options/index.adoc 
:product-path: observability/istio/configuration/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
:xref-istio-on-rke2: xref:observability/istio/configuration/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:observability/istio/configuration/project-network-isolation.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
:xref-istio-on-rke2: xref:integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:integrations-in-rancher/istio/configuration-options/project-network-isolation.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ha quedado obsoleto desde Rancher v2.12.0; recurran a la https://apps.rancher.io[SUSE Application Collection] de Istio para una mayor seguridad (incluida en las suscripciones de SUSE Rancher Prime).
Se puede encontrar información detallada en https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anuncio].
====

[#_egress_support]
== Soporte de Egress

Por defecto, el gateway de Egress está deshabilitado, pero se puede habilitar en la instalación o al actualizar versión a través del values.yaml o mediante el <<_overlay_file,archivo de superposición>>.

[#_enabling_automatic_sidecar_injection]
== Habilitando la Inyección Automática de Sidecar

La inyección automática de sidecar está deshabilitada por defecto. Para habilitar esto, establece el `sidecarInjectorWebhook.enableNamespacesByDefault=true` en el values.yaml en la instalación o al actualizar versión. Esto habilita automáticamente la inyección de sidecar de Istio en todos los nuevos espacios de nombres que se despliegan.

[#_overlay_file]
== Archivo de Superposición

Un Archivo de Superposición está diseñado para soportar una configuración extensa de tu instalación de Istio. Te permite realizar cambios en cualquier valor disponible en el https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/[API de IstioOperator]. Esto asegurará que puedas personalizar la instalación por defecto para adaptarse a cualquier escenario.

El Archivo de Superposición añadirá configuración sobre la instalación por defecto que se proporciona desde la instalación del chart de Istio. Esto significa que no necesitas redefinir los componentes que ya están definidos para la instalación.

Para más información sobre los Archivos de Superposición, consulta la https://istio.io/latest/docs/setup/install/istioctl/#configure-component-settings[documentación de Istio.]

[#_selectors_and_scrape_configs]
== Selectores y Configuraciones de Scrape

La aplicación de Monitoreo establece `prometheus.prometheusSpec.ignoreNamespaceSelectors=false`, lo que permite el monitoreo en todos los espacios de nombres por defecto. Esto asegura que puedas ver el tráfico, métricas y gráficos de los recursos desplegados en un espacio de nombres con la etiqueta `istio-injection=enabled`.

Si deseas limitar Prometheus a espacios de nombres específicos, establece `prometheus.prometheusSpec.ignoreNamespaceSelectors=true`. Una vez que hagas esto, deberás realizar una configuración adicional para continuar monitoreando tus recursos.

Para más detalles, consulta {xref-selectors-and-scrape-configurations}[esta sección.]

[#_additional_steps_for_installing_istio_on_an_rke2_product_name_cluster]
== Pasos adicionales para instalar Istio en un clúster {rke2-product-name}

Consulta {xref-istio-on-rke2}[esta sección.]

[#_additional_steps_for_project_network_isolation]
== Pasos adicionales para el aislamiento de red del proyecto

Consulta {xref-istio-project-network-isolation}[esta sección.]
