= Mejores prácticas para {rancher-product-name} clústeres de VMware vSphere gestionados
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-managed-clusters/rancher-managed-clusters-in-vsphere.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/best-practices.adoc

Esta guía describe una arquitectura de referencia para aprovisionar los clústeres Rancher de sentido descendente en un entorno vSphere, además de las mejores prácticas estándar de vSphere documentadas por VMware.

* <<_1_vm_considerations,1. Consideraciones sobre las VM>>
* <<_2_network_considerations,2. Consideraciones de red>>
* <<_3_storage_considerations,3. Consideraciones de almacenamiento>>
* <<_4_backups_and_disaster_recovery,4. Copias de seguridad y recuperación ante desastres>>

.Descripción general de la solución
image::solution_overview.drawio.svg[Descripción general de la solución]

[#_1_vm_considerations]
== 1. Consideraciones sobre las VM

[#_leverage_vm_templates_to_construct_the_environment]
=== Aprovechar las plantillas de VM para construir el entorno

Para facilitar la consistencia entre las máquinas virtuales desplegadas en el entorno, considera el uso de "imágenes doradas" en forma de plantillas de VM. Packer se puede utilizar para lograr esto, añadiendo mayores opciones de personalización.

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_downstream_cluster_nodes_across_esxi_hosts]
=== Aprovechar las reglas de anti-afinidad de DRS (donde sea posible) para separar los nodos del clúster de sentido descendente entre hosts ESXi

Hacer esto asegurará que las VM de los nodos se distribuyan entre múltiples hosts ESXi, previniendo un único punto de fallo a nivel de host.

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_downstream_cluster_nodes_across_datastores]
=== Aprovechar las reglas de anti-afinidad de DRS (donde sea posible) para separar los nodos del clúster de sentido descendente entre datastores

Hacer esto asegurará que las VM de los nodos se distribuyan entre múltiples datastores, previniendo un único punto de fallo a nivel de datastore.

[#_configure_vms_as_appropriate_for_kubernetes]
=== Configurar las VM según sea apropiado para Kubernetes

Es importante seguir las mejores prácticas de K8s y etcd al desplegar sus nodos, incluyendo deshabilitar swap, verificar que se dispone de conectividad de red completa entre todas las máquinas en el clúster, y utilizar nombres de host, direcciones MAC y product_uuids únicos para cada nodo.

[#_2_network_considerations]
== 2. Consideraciones de red

[#_leverage_low_latency_high_bandwidth_connectivity_between_etcd_nodes]
=== Aprovechar la conectividad de baja latencia y alto ancho de banda entre los nodos de ETCD

Desplegar miembros de etcd dentro de un único centro de datos donde sea posible para evitar sobrecargas de latencia y reducir la probabilidad de particionamiento de red. Para la mayoría de las configuraciones, las conexiones de 1Gb serán suficientes. Para grandes clústeres, las conexiones de 10Gb pueden reducir el tiempo necesario para restaurar desde una copia de seguridad.

[#_consistent_ip_addressing_for_vms]
=== Direccionamiento IP consistente para las máquinas virtuales

Cada nodo utilizado debe tener una IP estática configurada. En el caso de DHCP, cada nodo debe tener una reserva DHCP para asegurarse de que el nodo obtenga la misma IP asignada.

[#_3_storage_considerations]
== 3. Consideraciones de almacenamiento

[#_leverage_ssd_drives_for_etcd_nodes]
=== Aprovechar los discos SSD para los nodos ETCD.

ETCD es muy sensible a la latencia de escritura. Por lo tanto, aprovechar los discos SSD siempre que sea posible.

[#_4_backups_and_disaster_recovery]
== 4. Copias de seguridad y recuperación ante desastres

[#_perform_regular_downstream_cluster_backups]
=== Realizar copias de seguridad regulares del clúster de sentido descendente.

Kubernetes utiliza etcd para almacenar todos sus datos: desde la configuración, el estado y los metadatos. Respaldar esto es crucial en caso de recuperación ante desastres.

[#_back_up_downstream_node_vms]
=== Realizar copias de seguridad de las máquinas virtuales de los nodos de sentido descendente.

Incorporar las máquinas virtuales de los nodos de sentido descendente de Rancher dentro de una política estándar de copias de seguridad de máquinas virtuales.
