= Configuración de la Plantilla de Nodo de VMware vSphere
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guías-de-referencia/configuración-del-clúster/configuración-del-clúster-descendente/configuración-de-plantilla-de-nodo/vsphere.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/node-template-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
endif::[]

[#_account_access]
== Acceso a la cuenta

[cols="<,^,<"]
|===
| Parámetro | required | Descripción

| Credenciales de nube
| *
| La información de acceso de tu cuenta de vSphere, almacenada en una {xref-cloud-credentials}[credencial de nube.]
|===

Tu credencial de nube tiene estos campos:

|===
| Campo de Credencial | Descripción

| vCenter or ESXi Server
| Introduce el nombre de host/IP del vCenter o del ESXi. ESXi es la plataforma de virtualización donde creas y ejecutas máquinas virtuales y dispositivos virtuales. El Servidor vCenter es el servicio a través del cual gestionas múltiples hosts conectados en una red y agrupas los recursos de los hosts.

| Puerto
| Configura el puerto del servidor vCenter o ESXi.

| Nombre de usuario y contraseña
| Introduce tu nombre de usuario y contraseña de inicio de sesión de vSphere.
|===

[#_scheduling]
== Programación

Elige qué hipervisor se programará para la máquina virtual.

Los campos en la sección *Programación* deberían autocompletar con el centro de datos y otras opciones de programación que están disponibles para ti en vSphere.

|===
| Campo | required | Explicación

| Centro de datos
| *
| Elige el nombre/vía del centro de datos donde se programará la VM.

| Grupo de Recursos
|
| Nombre del grupo de recursos para programar las VMs. Los grupos de recursos se pueden utilizar para particionar los recursos de CPU y memoria disponibles de un host independiente o clúster, y también pueden estar anidados. Deja en blanco para ESXi independiente. Si no se especifica, se utiliza el grupo de recursos predeterminado.

| almacén de datos
| *
| Si tienes un clúster de almacén de datos, puedes alternar el campo *Almacén de Datos*. Esto te permite seleccionar un clúster de almacén de datos donde se programará tu VM. Si el campo no está activado, puedes seleccionar un disco individual.

| Carpeta
|
| Nombre de una carpeta en el centro de datos para crear las VMs. Debe existir ya. Las carpetas de VM en este menú desplegable corresponden directamente a tus carpetas de VM en vSphere. El nombre de la carpeta debe ir precedido de `vm/` en tu archivo de configuración de vSphere.

| Host
|
| La IP del sistema host para programar VMs. Deja este campo en blanco para un ESXi independiente o para un clúster con DRS (Distributed Resource Scheduler). Si se especifica, se utilizará el grupo del sistema host y se ignorará el parámetro *Grupo de Recursos*.

| Tiempo de espera para el apagado ordenado
|
| La cantidad de tiempo, en segundos, que Rancher espera antes de eliminar máquinas virtuales en un clúster. Si se establece en `0`, el apagado ordenado está deshabilitado. Solo acepta valores enteros.
|===

[#_instance_options]
== Opciones de instancia

En la sección *Opciones de Instancia*, configura el número de vCPUs, memoria y tamaño del disco para las VMs creadas por esta plantilla.

[cols="<,^,<"]
|===
| Parámetro | required | Descripción

| CPU
| *
| Número de vCPUs a asignar a las VMs.

| Memoria
| *
| Cantidad de memoria a asignar a las VMs.

| Disco
| *
| Tamaño del disco (en MB) a adjuntar a las VMs.

| Método de creación
| *
| El método para configurar un sistema operativo en el nodo. El sistema operativo se puede instalar desde un ISO o desde una plantilla de VM. Dependiendo del método de creación, también tendrás que especificar una plantilla de VM, biblioteca de contenido, VM existente o ISO. Para más información sobre los métodos de creación, consulta <<_about_vm_creation_methods,Acerca de los métodos de creación de VM.>>

| Cloud Init
|
| URL de un archivo `cloud-config.yml` o URL para aprovisionar VMs. Este archivo permite una mayor personalización del sistema operativo, como la configuración de red, servidores DNS o daemon del sistema. El sistema operativo debe soportar `cloud-init`.

| Redes
|
| Nombre(s) de la red a la que se conectará la VM.

| Parámetros de configuración utilizados para guestinfo
|
| Parámetros de configuración adicionales para las VMs. Estos corresponden a la https://kb.vmware.com/s/article/1016098[Configuración avanzada] en la consola de vSphere. Los casos de uso incluyen proporcionar parámetros de https://rancher.com/docs/os/v1.x/en/installation/cloud/vmware-esxi/#vmware-guestinfo[guestinfo] de RancherOS o habilitar los UUID de disco para las VMs (`disk.EnableUUID=TRUE`).
|===

[#_about_vm_creation_methods]
=== Acerca de los métodos de creación de VM

En el campo *Método de creación*, configura el método utilizado para aprovisionar VMs en vSphere. Las opciones disponibles incluyen crear VMs que arranquen desde un ISO de RancherOS o crear VMs clonando desde una máquina virtual existente o https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-F7BF0E6B-7C4F-4E46-8BBF-76229AEA7220.html[plantilla de VM].

La VM o plantilla existente puede utilizar cualquier sistema operativo Linux moderno que esté configurado con soporte para https://cloudinit.readthedocs.io/en/latest/[cloud-init] utilizando el https://canonical-cloud-init.readthedocs-hosted.com/en/latest/reference/datasources/nocloud.html[datasource NoCloud].

Elige la forma en que se creará la VM:

* *Desplegar desde plantilla: Centro de Datos:* Elige una plantilla de VM que exista en el centro de datos que seleccionaste.
* *Desplegar desde plantilla: Biblioteca de Contenido:* Primero, selecciona la https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-254B2CE8-20A8-43F0-90E8-3F6776C2C896.html[Biblioteca de Contenido] que contiene tu plantilla, luego selecciona la plantilla de la lista poblada *Plantillas de biblioteca*.
* *Clonar una máquina virtual existente:* En el campo *Máquina virtual*, elige una VM existente de la que se clonará la nueva VM.
* *Instalar desde la ISO de boot2docker:* Asegúrate de que el campo *URL de la ISO del SO* contenga la URL de una versión de ISO de VMware para RancherOS (`rancheros-vmware.iso`). Ten en cuenta que esta URL debe ser accesible desde los nodos que ejecutan tu instalación del servidor Rancher.

[#_networks]
== Redes

La plantilla de nodo ahora permite aprovisionar una VM con múltiples redes. En el campo *Redes*, ahora puedes hacer clic en *Añadir red* para añadir cualquier red disponible en vSphere.

[#_node_tags_and_custom_attributes]
== Etiquetas de nodo y atributos personalizados

Las etiquetas te permiten adjuntar metadatos a objetos en el inventario de vSphere para facilitar la clasificación y búsqueda de estos objetos.

Para las etiquetas, todas tus etiquetas de vSphere aparecerán como opciones para seleccionar en tu plantilla de nodo.

En los atributos personalizados, Rancher te permitirá seleccionar todos los atributos personalizados que ya has configurado en vSphere. Los atributos personalizados son claves y puedes introducir valores para cada uno.

[NOTE]
====

Los atributos personalizados son una característica heredada que eventualmente se eliminará de vSphere.
====


[#_cloud_init]
== cloud-init

https://cloudinit.readthedocs.io/en/latest/[Cloud-init] te permite inicializar tus nodos aplicando configuración en el primer arranque. Esto puede implicar cosas como crear usuarios, autorizar claves SSH o configurar la red.

Para hacer uso de la inicialización de cloud-init, crea un archivo de configuración para cloud-init utilizando una sintaxis YAML válida y pega el contenido del archivo en el campo *Cloud Init*. Consulta la https://cloudinit.readthedocs.io/en/latest/topics/examples.html[documentación de cloud-init.] para un conjunto comentado de ejemplos de directivas de configuración de nube soportadas.

Ten en cuenta que cloud-init no es compatible cuando se utiliza el método de creación de ISO.

[#_engine_options]
== Opciones del motor

En la sección *Opciones del motor* de la plantilla del nodo, puedes configurar el daemon de contenedor. Puede que desees especificar la versión del contenedor o un espejo del registro de imágenes del contenedor.

[NOTE]
====
Si estás aprovisionando nodos de Red Hat Enterprise Linux (RHEL) o CentOS, deja el campo *URL de instalación de Docker* con el valor predeterminado, o selecciona *ninguno*. Esto eludirá una comprobación de la instalación de Docker, ya que Docker ya está instalado en estos tipos de nodos.

Si estableces *URL de instalación de Docker* a un valor diferente del predeterminado o *ninguno*, podrías ver un mensaje de error como el siguiente: `Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`
====

