= {rancher-product-name} Server und Komponenten
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: reference-guides/rancher-manager-architecture/rancher-server-and-components.adoc 
:product-path: about-rancher/architecture/rancher-server-and-components.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-hosted-k8s-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/index.adoc
:xref-migrate-cluster: xref:how-to-guides/neue-anleitungen/sicherung-wiederherstellung-und-notfallwiederherstellung/migration-rancher-zu-neuem-cluster.adoc
endif::[]

Die Mehrheit der Rancher 2.x-Software läuft auf dem Rancher-Server. Der Rancher-Server umfasst alle Softwarekomponenten, die zur Verwaltung der gesamten Rancher-Implementierung verwendet werden.

Das folgende Diagramm veranschaulicht die Architektur von Rancher 2.x auf hoher Ebene. Die Abbildung zeigt eine Rancher-Server-Installation, die zwei Downstream-Kubernetes-Cluster verwaltet: einen, der von RKE2 erstellt wurde, und einen anderen, der von Amazon EKS (Elastic Kubernetes Service) erstellt wurde.

Für die beste Leistung und Sicherheit empfehlen wir einen dedizierten Kubernetes-Cluster für den Rancher-Management-Server. Es wird nicht empfohlen, Benutzerlasten in diesem Cluster auszuführen. Nach der Bereitstellung von Rancher können Sie {xref-cluster-deployment}[Cluster erstellen oder importieren], um Ihre Workloads auszuführen.

Das Diagramm zeigt, wie Benutzer sowohl {xref-launch-k8s-with-rancher}[von Rancher gestartete Kubernetes]-Cluster als auch {xref-hosted-k8s-clusters}[gehostete Kubernetes]-Cluster über den Authentifizierungsproxy von Rancher manipulieren können:

.Verwaltung von Kubernetes-Clustern über den Authentifizierungsproxy von Rancher
image::rancher-architecture-rancher-api-server.svg[Architektur]

Sie können Rancher auf einem einzelnen Knoten oder auf einem hochverfügbaren Kubernetes-Cluster installieren.

Eine hochverfügbare Kubernetes-Installation wird für die Produktion empfohlen.

Eine Docker-Installation von Rancher wird nur für Entwicklungs- und Testzwecke empfohlen. Die Möglichkeit, Rancher auf einen hochverfügbaren Cluster zu migrieren, hängt von der Rancher-Version ab.

Um bereitgestellte Ressourcen anzuzeigen, führen Sie den folgenden Befehl aus:

[,bash]
----
kubectl get all -n <namespace>
----

Wenn Sie über Administratorrechte verfügen, können Sie diese Ressourcen auch in der Rancher-Benutzeroberfläche aufgelistet sehen:

. Klicken Sie *☰* und wählen Sie einen Cluster aus.
. Wählen Sie *Weitere Ressourcen* aus dem seitlichen Navigationsmenü, um bereitgestellte Ressourcen nach Typ anzuzeigen.
. Wählen Sie *Cluster* > *Projekte/Namespaces* aus dem seitlichen Navigationsmenü, und wählen Sie dann einen Namespace aus, um bereitgestellte Ressourcen nach Namespace anzuzeigen.
Der Rancher-Sicherungs-Operator kann verwendet werden, um Rancher von der Einzel-Docker-Container-Installation auf eine Installation in einem Kubernetes-Cluster mit hoher Verfügbarkeit zu migrieren. Für Details siehe die Dokumentation zu {xref-migrate-cluster}[der Migration von Rancher zu einem neuen Cluster].

Der Rancher-Server sollte unabhängig von der Installationsmethode immer auf Knoten laufen, die von den Downstream-Benutzer-Clustern, die er verwaltet, getrennt sind. Wenn Rancher auf einem hochverfügbaren Kubernetes-Cluster installiert ist, sollte es auf einem separaten Cluster von den Clustern laufen, die es verwaltet.
