= Architekturempfehlungen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-22
:page-revdate: {revdate}
:community-path: reference-guides/rancher-manager-architecture/architecture-recommendations.adoc 
:product-path: about-rancher/architecture/recommendations.adoc
ifeval::["{build-type}" != "community"]
:xref-user-api-keys: rancher-admin/users/settings/api-keys.adoc
:xref-arch-com-ds-cluster: xref:about-rancher/architektur/kommunikation-mit-downstream-clustern.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-user-api-keys: xref:reference-guides/user-settings/api-keys.adoc
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architektur/kommunikation-mit-downstream-nutzer-clustern.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
endif::[]

Wenn Sie Rancher auf einem einzelnen Knoten installieren, besteht die Hauptarchitekturempfehlung für Ihre Installation darin, dass der Knoten, auf dem Rancher läuft, <<_separation_of_rancher_and_user_clusters,von den Downstream-Clustern getrennt sein sollte.>>

[#_separation_of_rancher_and_user_clusters]
== Trennung von Rancher und Benutzerclustern

Ein Benutzercluster ist ein Downstream-Kubernetes-Cluster, der Ihre Apps und Dienste ausführt.

Wenn Sie eine Docker-Installation von Rancher haben, sollte der Knoten, auf dem der Rancher-Server läuft, von Ihren Downstream-Clustern getrennt sein.

Wenn Rancher dazu gedacht ist, Downstream-Kubernetes-Cluster zu verwalten, sollte der Kubernetes-Cluster, auf dem der Rancher-Server läuft, ebenfalls von den Downstream-Benutzerclustern getrennt sein.

image::rancher-architecture-separation-of-rancher-server.svg[Trennung des Rancher-Servers von Benutzerclustern]

[#_why_ha_is_better_for_rancher_in_production]
== Warum HA besser für Rancher in der Produktion ist

Wir empfehlen, den Rancher-Server auf einem Kubernetes-Cluster mit hoher Verfügbarkeit zu installieren, hauptsächlich weil es die Daten des Rancher-Servers schützt. Bei einer Installation mit hoher Verfügbarkeit dient ein Lastenausgleich als einziger Kontaktpunkt für Clients, verteilt den Netzwerkverkehr auf mehrere Server im Cluster und hilft, zu verhindern, dass ein einzelner Server zu einem Fehlerpunkt wird.

Wir empfehlen nicht, Rancher in einem einzelnen Docker-Container zu installieren, da, wenn der Knoten ausfällt, keine Kopie der Cluster-Daten auf anderen Knoten vorhanden ist und Sie die Daten auf Ihrem Rancher-Server verlieren könnten.

[#__k3s_product_name_kubernetes_cluster_installations]
=== {k3s-product-name} Kubernetes-Cluster-Installationen

Eine Option für den zugrunde liegenden Kubernetes-Cluster ist die Verwendung von K3s Kubernetes. K3s ist die von Rancher zertifizierte Kubernetes-Distribution der CNCF. Es ist einfach zu installieren und benötigt nur die Hälfte des Speichers von Kubernetes, alles in einer Binärdatei von weniger als 100 MB. Ein weiterer Vorteil von K3s ist, dass es einen externen Datenspeicher ermöglicht, die Cluster-Daten zu halten, wodurch die K3s-Serverknoten als flüchtig behandelt werden können.

.Architektur eines K3s Kubernetes-Clusters, das den Rancher-Management-Server ausführt
image::k3s-server-storage.svg[Architektur eines K3s Kubernetes-Clusters, das den Rancher-Management-Server ausführt]

[#_recommended_load_balancer_configuration_for_kubernetes_installations]
== Empfohlene Lastenausgleichskonfiguration für Kubernetes-Installationen

Wir empfehlen die folgenden Konfigurationen für den Load Balancer und die Ingress-Controller:

* Der DNS für Rancher sollte auf einen Layer-4-Load-Balancer (TCP) verweisen.
* Der Lastenausgleicher sollte die Ports TCP/80 und TCP/443 an alle 3 Knoten im Kubernetes-Cluster weiterleiten.
* Der Ingress-Controller wird HTTP auf HTTPS umleiten und SSL/TLS an Port TCP/443 terminieren.
* Der Ingress-Controller wird den Datenverkehr an Port TCP/80 im Pod der Rancher-Bereitstellung weiterleiten.

.Rancher, installiert auf einem Kubernetes-Cluster mit Layer-4-Load-Balancer, der die SSL-Terminierung an Ingress-Controllern darstellt.
image::ha/rancher2ha.svg[Rancher HA]

[#_environment_for_kubernetes_installations]
== Umgebung für Kubernetes-Installationen

Es wird dringend empfohlen, Rancher auf einem Kubernetes-Cluster auf gehosteter Infrastruktur wie Amazons EC2 oder Google Compute Engine zu installieren.

Für die beste Leistung und höhere Sicherheit empfehlen wir einen dedizierten Kubernetes-Cluster für den Rancher-Management-Server. Es wird nicht empfohlen, Benutzerlasten in diesem Cluster auszuführen. Nach der Bereitstellung von Rancher können Sie {xref-cluster-deployment}[Cluster erstellen oder importieren], um Ihre Workloads auszuführen.

[#_recommended_node_roles_for_kubernetes_installations]
== Empfohlene Knotenrollen für Kubernetes-Installationen

Die folgenden Empfehlungen gelten, wenn Rancher auf einem K3s-Kubernetes-Cluster installiert ist.

[#__k3s_product_name_cluster_roles]
=== {k3s-product-name} Cluster-Rollen

In K3s-Clustern gibt es zwei Arten von Knoten: Serverknoten und Agentenknoten. Sowohl Server als auch Agenten können Arbeitslasten zugewiesen bekommen. Serverknoten führen den Kubernetes-Master aus.

Für den Cluster, der den Rancher-Management-Server ausführt, empfehlen wir die Verwendung von zwei Serverknoten. Agentenknoten sind nicht erforderlich.

[#_architecture_for_an_authorized_cluster_endpoint_ace]
== Architektur für einen autorisierten Cluster-Endpunkt (ACE)

Wenn Sie einen {xref-arch-com-ds-cluster}#_4_authorized_cluster_endpoint[autorisierten Cluster-Endpunkt (ACE)] verwenden, empfehlen wir, einen FQDN zu erstellen, der auf einen Load Balancer zeigt, der den Datenverkehr über unsere Knoten mit der `controlplane` Rolle verteilt.

Wenn Sie private, von einer CA signierte Zertifikate auf dem Lastenausgleicher verwenden, müssen Sie das CA-Zertifikat bereitstellen, das in die generierte kubeconfig-Datei aufgenommen wird, um die Zertifikatkette zu validieren. Siehe die Dokumentation zu {xref-access-cluster-kubectl}[kubeconfig-Dateien] und {xref-user-api-keys}#_creating_an_api_key[API-Schlüsseln] für weitere Informationen.

ACE-Unterstützung ist für registrierte RKE2- und K3s-Cluster verfügbar. Um die manuellen Schritte anzuzeigen, die auf dem Downstream-Cluster zur Aktivierung des ACE durchzuführen sind, klicken Sie {xref-register-clusters}#_authorized_cluster_endpoint_support_for_rke2_and_k3s_clusters[hier].
