= À propos des certificats racine CA personnalisés
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/custom-ca-root-certificates.adoc 
:product-path: installation-and-upgrade/resources/custom-ca-root-certificates.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
endif::[]

Si vous utilisez Rancher dans un environnement de production interne où vous n'exposez pas les applications publiquement, utilisez un certificat d'une autorité de certification (CA) privée.

Les services auxquels Rancher doit accéder sont parfois configurés avec un certificat d'une racine CA personnalisée/interne, également connu sous le nom de certificat auto-signé. Si le certificat présenté par le service ne peut pas être validé par Rancher, l'erreur suivante s'affiche: `x509: certificate signed by unknown authority`.

Pour valider le certificat, les certificats racine CA doivent être ajoutés à Rancher. Comme Rancher est écrit en Go, nous pouvons utiliser la variable d'environnement `SSL_CERT_DIR` pour pointer vers le répertoire où se trouvent les certificats racine CA dans le conteneur. Le répertoire des certificats racine CA peut être monté en utilisant l'option de volume Docker (`-v host-source-directory:container-destination-directory`) lors du démarrage du conteneur Rancher.

Exemples de services auxquels Rancher peut accéder:

* Catalogues
* Fournisseurs d'authentification
* Accès à l'API d'hébergement/cloud lors de l'utilisation de pilotes Node

[#_installing_with_the_custom_ca_certificate]
== Installation avec le certificat CA personnalisé

Pour des détails sur le démarrage d'un conteneur Rancher avec vos certificats CA privés montés, consultez la documentation d'installation:

* {xref-helm-chart-options}#_additional_trusted_cas[Kubernetes install options for Additional Trusted CAs]
