= Configuración de un proveedor de nube VMware vSphere in-tree
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/guías-para-nuevos-usuarios/clusters-de-kubernetes-en-rancher/configurar-proveedores-de-nube/configurar-vsphere-in-tree.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc

Para configurar el proveedor de nube VMware vSphere in-tree, sigue estos pasos mientras creas el clúster de vSphere en Rancher:

. Establece la opción *Proveedor de Nube* a `Custom` o `Custom (In-Tree)`.
. Haz clic en *Editar como YAML*
. Inserta la siguiente estructura en el YAML del clúster pre-poblado. Esta estructura debe colocarse bajo `rancher_kubernetes_engine_config`. Ten en cuenta que el `name` _debe_ establecerse en `vsphere`.
+
[,yaml]
----
 rancher_kubernetes_engine_config:
   cloud_provider:
       name: vsphere
       vsphereCloudProvider:
           [Insert provider configuration]
----

Rancher utiliza RKE (el Motor de Kubernetes de Rancher) para aprovisionar clústeres de Kubernetes. Consulta la https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/config-reference/[referencia de configuración de vSphere en la documentación de RKE] para obtener detalles sobre las propiedades de la directiva `vsphereCloudProvider`.
