= Alertmanager配置
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

通常不需要直接编辑 Alertmanager 自定义资源。对于大多数用例，您只需编辑接收器和路由以配置通知。

当接收器和路由被更新时，监控应用程序将自动更新 Alertmanager 自定义资源，以与这些更改保持一致。

[NOTE]
====

本节假设您对监控组件如何协同工作有一定了解。有关 Alertmanager 的更多信息，请参见 {xref-how-monitoring-works}#_3_how_alertmanager_works[本节。]
====


[#_about_the_alertmanager_custom_resource]
== 关于 Alertmanager 自定义资源

默认情况下，Rancher Monitoring 会在使用默认 Alertmanager 配置密钥的集群上部署一个 Alertmanager。

如果您希望利用 Rancher UI 表单中未公开的高级选项，例如创建深度超过两级的路由树结构，您可能需要编辑 Alertmanager 自定义资源。

在一个集群中也可以创建多个 Alertmanager，这在您想要实现名称空间范围的监控时可能会很有用。在这种情况下，您应该使用相同的基础 Alertmanager 配置密钥来管理 Alertmanager 自定义资源。

[#_deeply_nested_routes]
=== 深层嵌套路由

虽然 Rancher UI 仅支持深度为两级的路由树，但您可以通过编辑 Alertmanager YAML 配置更深层次的嵌套路由结构。

[#_multiple_alertmanager_replicas]
=== 多个 Alertmanager 副本

作为图表部署选项的一部分，您可以选择增加部署到集群上的 Alertmanager 副本数量。所有副本都可以使用相同的基础 Alertmanager 配置密钥进行管理。

每当您想要时，应该更新或修改此配置密钥：

* 添加新的通知者或接收器
* 更改应发送到特定通知者或接收器的警报
* 更改发送的警报组

默认情况下，您可以选择提供现有的 Alertmanager 配置密钥（即 `cattle-monitoring-system` 名称空间中的任何密钥），或允许 Rancher Monitoring 在您的集群上部署默认的 Alertmanager 配置密钥。

默认情况下，Rancher 创建的 Alertmanager 配置密钥在升级或卸载 `rancher-monitoring` 图表时将不会被修改或删除。此限制防止用户在对图表执行操作时丢失或覆盖其警报配置。

有关可以在 Alertmanager 配置密钥中指定的字段的更多信息，请查看 https://prometheus.io/docs/alerting/latest/alertmanager/[Prometheus Alertmanager 文档。]

Alertmanager 配置文件的完整规范及其所需内容可以在 https://prometheus.io/docs/alerting/latest/configuration/#configuration-file[这里找到。]
