= Exemples de configuration de monitoring
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/examples.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/examples.adoc

[#_servicemonitor]
== ServiceMonitor

Consultez le dépôt GitHub officiel de prometheus-operator pour un exemple de YAML https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml[ServiceMonitor].

[#_podmonitor]
== PodMonitor

Consultez la https://prometheus-operator.dev/docs/developer/getting-started/#using-podmonitors[documentation de Prometheus Operator] pour un exemple de PodMonitor et un exemple de ressource Prometheus qui fait référence à un PodMonitor.

[#_prometheusrule]
== Règle Prometheus

Une PrometheusRule contient les règles d'alerte et d'enregistrement que vous placeriez généralement dans un https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/[fichier de règles Prometheus].

Pour une approche plus fine, le champ `ruleSelector` sur une ressource Prometheus peut sélectionner quelles PrometheusRules doivent être chargées sur Prometheus, en fonction des étiquettes attachées aux ressources PrometheusRules.

Consultez la https://prometheus-operator.dev/docs/developer/alerting/[documentation de Prometheus Operator] pour un exemple de PrometheusRule.

[#_alertmanager_config]
== Configuration d'Alertmanager

Consultez la page de documentation de Rancher sur les Récepteurs pour un exemple de xref:./receivers.adoc#_example_alertmanager_configs[configuration d'Alertmanager].
