= Configuration du récepteur
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/receivers.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/receivers.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-compliance-enable-alerting: xref:security/compliance-scans/enable-alerting-for-rancher-compliance.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-compliance-enable-alerting: xref:procédures/guides-utilisateur-avancés/guides-de-scan-de-conformité/activer-les-alertes-pour-rancher-conformité.adoc
endif::[]

Le Secret https://prometheus.io/docs/alerting/latest/configuration/#configuration-file[Config d'Alertmanager] contient la configuration d'une instance d'Alertmanager qui envoie des notifications en fonction des alertes qu'elle reçoit de Prometheus.

[NOTE]
====

Cette section suppose que vous êtes familier avec la manière dont les composants de surveillance fonctionnent ensemble. Pour plus d'informations sur Alertmanager, consultez {xref-how-monitoring-works}#_3_how_alertmanager_works[cette section.]
====


[#_creating_receivers_in_the_rancher_ui]
== Création de récepteurs dans l'interface utilisateur de Rancher

[NOTE]
.Conditions préalables :
====

* L'application de surveillance doit être installée.
* Si vous avez configuré la surveillance avec un Secret d'Alertmanager existant, il doit avoir un format pris en charge par l'interface utilisateur de Rancher. Sinon, vous ne pourrez apporter des modifications qu'en modifiant directement le Secret d'Alertmanager. Remarque : Nous continuons à améliorer les types de configurations d'Alertmanager que nous pouvons prendre en charge en utilisant l'interface utilisateur des Routes et des Récepteurs, donc veuillez https://github.com/rancher/rancher/issues/new[signaler un problème] si vous avez une demande d'amélioration de fonctionnalité.
====

. Allez dans le cluster où vous souhaitez créer des récepteurs. Cliquez sur *Surveillance \-> Alertes \-> Configurations d'AlertManager*.
. Cliquez sur *Create*.
. Entrez un *Nom* pour la nouvelle configuration d'Alertmanager.
. Cliquez sur *Create*.
. Après avoir créé la configuration d'AlertManager, cliquez dessus pour ajouter un récepteur.
. Cliquez sur *Ajouter un récepteur*.
. Entrez un *Nom* pour le récepteur.
. Configurez un ou plusieurs fournisseurs pour le récepteur. Pour obtenir de l'aide pour remplir les formulaires, reportez-vous aux options de configuration ci-dessous.
. Cliquez sur *Create*.

*Résultat :* Les alertes peuvent être configurées pour envoyer des notifications aux récepteurs.

[#_receiver_configuration]
== Configuration du récepteur

Les intégrations de notification sont configurées avec le `receiver`, qui est expliqué dans la https://prometheus.io/docs/alerting/latest/configuration/#receiver[documentation de Prometheus.]

[#_native_vs_non_native_receivers]
=== Natif vs. Récepteurs non natifs

Par défaut, AlertManager fournit une intégration native avec certains récepteurs, qui sont listés dans https://prometheus.io/docs/alerting/latest/configuration/#receiver[cette section.] Tous les récepteurs pris en charge nativement sont configurables via l'interface utilisateur de Rancher.

Pour les mécanismes de notification, tels que Telegram, qui ne sont pas pris en charge nativement par AlertManager, l'intégration est réalisée à l'aide du https://prometheus.io/docs/alerting/latest/configuration/#webhook_config[récepteur webhook.] Une liste de pilotes tiers fournissant de telles intégrations peut être trouvée https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver[ici.] L'accès à ces pilotes et à leurs intégrations associées est fourni via l'appli Alerting Drivers. Une fois activé, la configuration des récepteurs non natifs peut également être effectuée via l'interface utilisateur de Rancher.

Actuellement, l'application Rancher Alerting Drivers donne accès aux intégrations suivantes{nbsp}:

* Microsoft Teams, basé sur le pilote https://github.com/idealista/prom2teams[prom2teams].
* Telegram, basé sur le pilote https://github.com/messagebird/sachet[Sachet].

Les types suivants de récepteurs peuvent être configurés dans l'interface utilisateur de Rancher{nbsp}:

* <<_slack,Slack>>
* <<_email,Message électronique>>
* <<_pagerduty,PagerDuty>>
* <<_opsgenie,Opsgenie>>
* <<_webhook,Webhook>>
* <<_custom,Personnalisé>>
* <<_teams,Équipes>>
* <<_sms,SMS>>
* <<_telegram,Telegram>>

L'option de récepteur personnalisé peut être utilisée pour configurer tout récepteur en YAML qui ne peut pas être configuré en remplissant les autres formulaires dans l'interface utilisateur de Rancher.

[#_slack]
== Slack

|===
| Champ | Type | Description

| URL
| Chaîne
| Entrez l'URL de votre webhook Slack. Pour des instructions sur la création d'un webhook Slack, consultez la https://get.slack.help/hc/en-us/articles/115005265063-Incoming-WebHooks-for-Slack[documentation Slack.]

| Canal par défaut
| Chaîne
| Entrez le nom du canal dans lequel vous souhaitez envoyer des notifications d'alerte au format suivant{nbsp}: `#<channelname>`.

| URL du proxy
| Chaîne
| Proxy pour les notifications de webhook.

| Activer l'envoi d'alertes résolues
| Booléen
| Indique s'il faut envoyer une notification de suivi si une alerte a été résolue (par exemple, [Résolu] Utilisation élevée de l'UC).
|===

[#_email]
== Message électronique

|===
| Champ | Type | Description

| Adresse du destinataire par défaut
| Chaîne
| L'adresse e-mail qui recevra les notifications.

| Activer l'envoi d'alertes résolues
| Booléen
| Indique s'il faut envoyer une notification de suivi si une alerte a été résolue (par exemple, [Résolu] Utilisation élevée de l'UC).
|===

Options SMTP{nbsp}:

|===
| Champ | Type | Description

| Expéditeur
| Chaîne
| Entrez une adresse e-mail disponible sur votre serveur de messagerie SMTP à partir de laquelle vous souhaitez envoyer la notification.

| Hôte
| Chaîne
| Entrez l'adresse IP ou le nom d'hôte de votre serveur SMTP. Exemple{nbsp}: `smtp.email.com`.

| Utiliser TLS
| Booléen
| Utilisez TLS pour le chiffrement.

| Nom d'utilisateur
| Chaîne
| Entrez un nom d'utilisateur pour vous authentifier auprès du serveur SMTP.

| Mot de passe
| Chaîne
| Entrez un mot de passe pour vous authentifier auprès du serveur SMTP.
|===

[#_pagerduty]
== PagerDuty

|===
| Champ | Type | Description

| Type d'intégration
| Chaîne
| `Events API v2` ou `Prometheus`.

| Clé d'intégration par défaut
| Chaîne
| Pour des instructions sur l'obtention d'une clé d'intégration, consultez la https://www.pagerduty.com/docs/guides/prometheus-integration-guide/[documentation de PagerDuty.]

| URL du proxy
| Chaîne
| Proxy pour les notifications de PagerDuty.

| Activer l'envoi d'alertes résolues
| Booléen
| Indique s'il faut envoyer une notification de suivi si une alerte a été résolue (par exemple, [Résolu] Utilisation élevée de l'UC).
|===

[#_opsgenie]
== Opsgenie

|===
| Champ | Description

| Clé API
| Pour des instructions sur l'obtention d'une clé API, référez-vous à la https://docs.opsgenie.com/docs/api-key-management[documentation d'Opsgenie.]

| URL du proxy
| Proxy pour les notifications d'Opsgenie.

| Activer l'envoi d'alertes résolues
| Indique s'il faut envoyer une notification de suivi si une alerte a été résolue (par exemple, [Résolu] Utilisation élevée de l'UC).
|===

Répondants Opsgenie{nbsp}:

|===
| Champ | Type | Description

| Type
| Chaîne
| Calendrier, Équipe, Utilisateur ou Escalade. Pour plus d'informations sur les répondants d'alerte, référez-vous à la https://docs.opsgenie.com/docs/alert-recipients-and-teams[documentation d'Opsgenie.]

| Envoyer à
| Chaîne
| Id, Nom ou Nom d'utilisateur du destinataire Opsgenie.
|===

[#_webhook]
== Webhook

|===
| Champ | Description

| URL
| URL du webhook pour l'appli de votre choix.

| URL du proxy
| Proxy pour la notification de webhook.

| Activer l'envoi d'alertes résolues
| Indique s'il faut envoyer une notification de suivi si une alerte a été résolue (par exemple, [Résolu] Utilisation élevée du CPU).
|===

[#_custom]
== Personnalisé

Le YAML fourni ici sera directement ajouté à votre récepteur dans le Secret de configuration d'Alertmanager.

[#_teams]
== Équipes

[#_enabling_the_teams_receiver_for_rancher_managed_clusters]
=== Activation du récepteur Teams pour les clusters gérés par Rancher

Le récepteur Teams n'est pas un récepteur natif et doit être activé avant de pouvoir être utilisé. Vous pouvez activer le récepteur Teams pour un cluster géré par Rancher en allant sur la page Apps et en installant l'appli rancher-alerting-drivers avec l'option Teams sélectionnée.

. Dans l'interface Rancher, allez au cluster où vous souhaitez installer rancher-alerting-drivers et cliquez sur *Apps*.
. Cliquez sur l'application *Alerting Drivers*.
. Cliquez sur l'onglet *Helm Deploy Options*.
. Sélectionnez l'option *Teams* et cliquez sur *Installer*.
. Prenez note de l'espace de noms utilisé, car il sera requis dans une étape ultérieure.

[#_configuring_the_teams_receiver]
=== Configuration du récepteur Teams

. Pour configurer le récepteur Teams, mettez à jour son ConfigMap. L'exemple suivant est une configuration minimale du récepteur Teams{nbsp}:
+
[,yaml]
----
 [Microsoft Teams]
 connector: https://your-teams-webhook-url
----

. Après avoir mis à jour la configuration, suivez les instructions dans <<_creating_receivers_in_the_rancher_ui,Création de récepteurs dans l'interface utilisateur de Rancher>> pour ajouter le récepteur. Utilisez l'exemple ci-dessous pour former votre URL. Assurez-vous de remplacer `<namespace>` par l'espace de noms de l'appli `rancher-alerting-drivers`{nbsp}:
+
[,yaml]
----
 url: http://rancher-alerting-drivers-prom2teams.<namespace>.svc:8089/v2/connector
----

// https://github.com/idealista/prom2teams

[#_sms]
== SMS

[#_enabling_the_sms_receiver_for_rancher_managed_clusters]
=== Activation du récepteur SMS pour les clusters gérés par Rancher

Le récepteur SMS n'est pas un récepteur natif et doit être activé avant de pouvoir être utilisé. Vous pouvez activer le récepteur SMS pour un cluster géré par Rancher en allant sur la page Apps et en installant l'appli rancher-alerting-drivers avec l'option SMS sélectionnée.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, allez au cluster où vous souhaitez installer `rancher-alerting-drivers` et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur
. Cliquez sur l'application *Alerting Drivers*.
. Cliquez sur l'onglet *Helm Deploy Options*
. Sélectionnez l'option *SMS* et cliquez sur *Installer*.
. Prenez note de l'espace de noms utilisé, car il sera requis dans une étape ultérieure.

[#_configuring_the_sms_receiver]
=== Configuration du récepteur SMS

Le récepteur SMS peut être configuré en mettant à jour son ConfigMap. Par exemple, la configuration minimale du récepteur SMS est la suivante.

[,yaml]
----
providers:
  telegram:
    token: 'your-token-from-telegram'

receivers:
- name: 'telegram-receiver-1'
  provider: 'telegram'
  to:
    - '123456789'
----

Lorsque la configuration est terminée, ajoutez le récepteur en suivant les étapes de <<_creating_receivers_in_the_rancher_ui,cette section>>.

Utilisez l'exemple ci-dessous comme nom et URL, où{nbsp}:

* le nom attribué au récepteur, par exemple `telegram-receiver-1`, doit correspondre au nom dans le champ `receivers.name` du ConfigMap, par exemple `telegram-receiver-1`
* `ns-1` dans l'URL est remplacé par l'espace de noms où l'appli `rancher-alerting-drivers` est installée

[,yaml]
----
name: telegram-receiver-1
url http://rancher-alerting-drivers-sachet.ns-1.svc:9876/alert
----

// https://github.com/messagebird/sachet

[#_telegram]
== Telegram

[#_enabling_the_telegram_receiver_for_rancher_managed_clusters]
=== Activation du récepteur Telegram pour les clusters gérés par Rancher

Le récepteur Telegram n'est pas un récepteur natif. Vous devez l'activer avant de pouvoir l'utiliser. Vous pouvez activer le récepteur Telegram pour un cluster géré par Rancher en allant sur la page *Apps* et en installant l'application `rancher-alerting-drivers` avec l'option *Telegram* sélectionnée{nbsp}:

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, allez au cluster où vous souhaitez installer `rancher-alerting-drivers` et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur *Apps*.
. Cliquez sur l'application *Alerting Drivers*.
. Cliquez sur *Installer*.
. Dans la page qui s'ouvre ensuite, assurez-vous que la case *Activer SMS* est cochée. Les notifications Telegram nécessitent d'activer le SMS.
. Prenez note de l'espace de noms utilisé, car il sera requis dans une étape ultérieure.

[#_test_the_configuration_by_configuring_a_prometheusrule]
=== Testez la configuration en configurant une PrometheusRule

Pour tester votre configuration Telegram, créez une *PrometheusRule* qui génère continuellement des alertes.

[CAUTION]
.REMARQUE
====
Cette règle est uniquement destinée à tester si les alertes Telegram fonctionnent comme prévu. Ne la laissez pas active après la fin des tests.
====


. Dans le menu à gauche, cliquez sur *Surveillance*.
. Cliquez sur *Avancé*.
. Cliquez sur menu:Règles Prometheus[Créer].
. Sélectionnez un espace de noms pour placer la règle et nommez la règle de manière appropriée.
. Définissez le nom du groupe sur `test`. Utilisez cette valeur plus tard lorsque vous créerez un *Route* dans le *AlertManagerConfig*.
. Sous *Règles d'alerte*, cliquez sur *Ajouter*.
. Définissez un *Nom d'alerte* approprié.
. Pour déclencher l'alerte immédiatement et en continu, entrez l'expression PromQL suivante{nbsp}: `vector(1)`.
. Sous *Étiquettes*, cliquez sur *Ajouter une étiquette*. Entrez la clé `test` et la valeur `alert`. Cette paire clé-valeur sera également utilisée plus tard.

[#_configure_an_alertmanagerconfig]
==== Configurez un AlertManagerConfig

Configurez un *AlertManagerConfig* pour contenir la configuration de *Récepteur* et de *Route* pour la *Règle Prometheus* créée ci-dessus{nbsp}:

. Cliquez sur menu:Surveillance[Alertes], et ouvrez *AlertManagerConfigs*.
. Cliquez sur *Create*

[#_create_a_receiver_in_alertmanagerconfig]
==== Créez un Récepteur dans AlertManagerConfig

. Choisissez un espace de noms dans la liste déroulante et définissez un nom approprié.
. Cliquez sur *Create*.
. Ouvrez le *AlertManagerConfig* nouvellement créé et cliquez sur *⋮ > Modifier la configuration*.
. Cliquez sur *Ajouter un récepteur*.
. Sélectionnez *Webhook* dans la liste sur la page *Créer un récepteur dans AlertmanagerConfig*.
. Nommez le webhook, et cliquez sur *Ajouter un webhook*.
. Dans le menu déroulant *Sélectionner le type de webhook*, sélectionnez *SMS*. Cela remplira automatiquement le champ *Target* en tant que `http://rancher-alerting-drivers-sachet.cattle-monitoring-system.svc:9876/alert`. Si vous avez installé les *Alerting Drivers* dans un espace de noms autre que `cattle-monitoring-system`, l'URL cible le reflétera.
. Cliquez sur *Create*.

[#_create_a_route_in_alertmanagerconfig]
==== Créez une Route dans AlertManagerConfig

. Cliquez sur *⋮ > Modifier la configuration*.
. Cliquez sur *Route*.
. Dans le menu déroulant, sélectionnez le *Récepteur* que vous venez de créer.
. Dans le champ *Étiquettes pour regrouper les alertes*, tapez `test`.
. Sous *Attente et intervalles*, définissez *Délai d'attente du groupe* sur `1s` et *Intervalle du groupe* sur `10s`. Cela déclenche des alertes fréquentes. Modifiez les valeurs selon les besoins.
. Sous *Matchers*, cliquez sur *Ajouter un matcher*. Entrez `test` dans le champ *Nom* et `alert` dans le champ *Valeur*. Dans le menu déroulant *Type de correspondance*, sélectionnez `MatchEqual`.
. Cliquez sur *Enregistrer*.

[#_configuring_the_telegram_receiver]
=== Configuration du récepteur Telegram

Vous pouvez configurer le récepteur Telegram en mettant à jour le `rancher-alerting-drivers-sachet` ConfigMap dans l'espace de noms `cattle-monitoring-system`. Par exemple, ce qui suit est une configuration minimale du récepteur Telegram{nbsp}:

[,yaml]
----
providers:
  telegram:
    token: <your-token-from-telegram>

receivers:
- name: 'cattle-monitoring-system/test-amc/prom2tel'
  provider: 'telegram'
  to:
    - '123456789'
----

Pour obtenir un token Telegram, configurez un bot Telegram. Référez-vous au https://core.telegram.org/bots/tutorial[guide officiel de Telegram] pour plus de détails.
Après avoir terminé la configuration du récepteur, <<_creating_receivers_in_the_rancher_ui,ajoutez-le>>.

Nommez le récepteur `<namespace>/<alertmanagerconfig-name>/<receiver-name>`. Entrez `123456789` comme un espace réservé pour l'ID utilisateur Telegram à qui envoyer les notifications. Pour trouver votre ID Telegram, vérifiez https://telegram.me/userinfobot[le bot d'informations utilisateur Telegram].

Vous devriez maintenant recevoir des notifications Telegram pour l'ID utilisateur. Si vous ne recevez pas de notifications, veuillez vérifier s'il y a des erreurs signalées dans le Pod pour le Déploiement `rancher-alerting-drivers-sachet` sous l'espace de noms `cattle-monitoring-system`.

[#_configuring_multiple_receivers]
== Configuration de plusieurs récepteurs

En modifiant les formulaires dans l'interface utilisateur de Rancher, vous pouvez configurer une ressource Récepteur avec toutes les informations nécessaires à l'Alertmanager pour envoyer des alertes à votre système de notification.

Il est également possible d'envoyer des alertes à plusieurs systèmes de notification. Une façon de procéder est de configurer le Récepteur en utilisant un YAML personnalisé, auquel cas vous pouvez ajouter la configuration pour plusieurs systèmes de notification, tant que vous êtes sûr que les deux systèmes doivent recevoir les mêmes messages.

Vous pouvez également configurer plusieurs récepteurs en utilisant l'option `continue` pour une route, de sorte que les alertes envoyées à un récepteur continuent d'être évaluées au niveau suivant de l'arbre de routage, qui pourrait contenir un autre récepteur.

[#_example_alertmanager_configs]
== Exemples de configurations Alertmanager

[#_slack_1]
=== Slack

Pour configurer des notifications via Slack, le YAML de configuration Alertmanager suivant peut être placé dans la clé `alertmanager.yaml` du Secret de configuration Alertmanager, où le `api_url` doit être mis à jour pour utiliser votre URL de Webhook de Slack{nbsp}:

[,yaml]
----
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  slack_configs:
  - send_resolved: true
    text: '{{ template "slack.rancher.text" . }}'
    api_url: <user-provided slack webhook url here>
templates:
- /etc/alertmanager/config/*.tmpl
----

[#_pagerduty_1]
=== PagerDuty

Pour configurer des notifications via PagerDuty, utilisez l'exemple ci-dessous tiré de la https://www.pagerduty.com/docs/guides/prometheus-integration-guide/[documentation de PagerDuty] comme guide. Cet exemple configure une route qui capture les alertes pour un service de base de données et les envoie à un récepteur lié à un service qui notifiera directement les DBA dans PagerDuty, tandis que toutes les autres alertes seront dirigées vers un récepteur par défaut avec une clé d'intégration PagerDuty différente.

Le YAML de configuration Alertmanager suivant peut être placé dans la clé `alertmanager.yaml` du Secret de configuration Alertmanager. Le `service_key` doit être mis à jour pour utiliser votre clé d'intégration PagerDuty et peut être trouvé selon la section "Intégration avec le Routage d'Événements Global" de la documentation de PagerDuty. Pour la liste complète des options de configuration, référez-vous à la https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config[documentation de Prometheus].

[,yaml]
----
route:
 group_by: [cluster]
 receiver: 'pagerduty-notifications'
 group_interval: 5m
 routes:
  - match:
      service: database
    receiver: 'database-notifcations'

receivers:
- name: 'pagerduty-notifications'
  pagerduty_configs:
  - service_key: 'primary-integration-key'

- name: 'database-notifcations'
  pagerduty_configs:
  - service_key: 'database-integration-key'
----

[#_example_route_config_for_compliance_scan_alerts]
== Exemple de configuration de route pour les alertes de scan de conformité

Lors de la configuration des itinéraires pour les alertes `rancher-compliance`, vous pouvez spécifier la correspondance en utilisant la paire clé-valeur `job: rancher-compliance-scan`.

Par exemple, la configuration de route suivante pourrait être utilisée avec un récepteur Slack nommé `test-compliance`{nbsp}:

[,yaml]
----
spec:
  receiver: test-compliance
  group_by:
#    - string
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  match:
    job: rancher-compliance-scan
#    key: string
  match_re:
    {}
#    key: string
----

Pour plus d'informations sur l'activation des alertes pour `rancher-compliance`, voir {xref-compliance-enable-alerting}[cette section.]

[#_trusted_ca_for_notifiers]
== CA de confiance pour les Notificateurs

Si vous devez ajouter un CA de confiance à votre notificateur, suivez les étapes dans xref:./helm-chart-options.adoc#_trusted_ca_for_notifiers[cette section.]
