= Configuration de la route
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/routes.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/routes.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
endif::[]

La configuration de la route est la section de la ressource personnalisée Alertmanager qui contrôle comment les alertes déclenchées par Prometheus sont regroupées et filtrées avant d'atteindre le récepteur.

Lorsqu'une route est modifiée, l'Opérateur Prometheus régénère la ressource personnalisée Alertmanager pour refléter les changements.

Pour plus d'informations sur la configuration des routes, consultez la https://www.prometheus.io/docs/alerting/latest/configuration/#route[documentation officielle d'Alertmanager.]

[NOTE]
====

Cette section suppose que vous êtes familier avec la manière dont les composants de surveillance fonctionnent ensemble. Pour plus d'informations, consultez {xref-how-monitoring-works}[cette section.]
====


[#_route_restrictions]
== Restrictions de la route

Alertmanager fait office de proxy pour les alertes de Prometheus en fonction de ses récepteurs et d'un arbre de routage qui filtre les alertes vers certains récepteurs en fonction des étiquettes.

Les pilotes d'alerte font office de proxy pour les alertes d'Alertmanager vers des récepteurs non natifs, tels que Microsoft Teams et SMS.

Dans l'interface utilisateur de Rancher pour configurer les routes et les récepteurs, vous pouvez configurer des arbres de routage avec une racine et ensuite une profondeur d'un niveau supplémentaire, pour un arbre d'une profondeur de deux. Mais si vous utilisez une `continue` route lors de la configuration d'Alertmanager directement, vous pouvez rendre l'arbre plus profond.

Chaque récepteur est destiné à un ou plusieurs fournisseurs de notifications. Donc, si vous savez que chaque alerte pour Slack doit également aller à PagerDuty, vous pouvez configurer les deux dans le même récepteur.

[#_route_configuration]
== Configuration de la route

[#_note_on_labels_and_annotations]
=== Remarque sur les étiquettes et les annotations

Les étiquettes doivent être utilisées pour des informations permettant d'identifier et pouvant influencer le routage des notifications. Les informations d'identification concernant l'alerte pourraient consister en un nom de conteneur, ou le nom de l'équipe qui doit être notifiée.

Les annotations doivent être utilisées pour des informations qui n'affectent pas qui reçoit l'alerte, comme une URL de runbook ou un message d'erreur.

[#_receiver]
=== Récepteur

La route doit faire référence à un {xref-receivers}[récepteur] qui a déjà été configuré.

[#_grouping]
=== Catégorie

|===
| Champ | Par défaut | Description

| Regrouper par
| N/a
| Liste des étiquettes selon lesquelles regrouper. Les étiquettes doivent être uniques. L'étiquette spéciale "..." (agréger par toutes les étiquettes possibles), si fournie, doit être le seul élément de la liste. Accepte une liste de chaînes. Voir la https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#route[documentation en amont] pour plus de détails.

| Groupe d'attente
| 30s
| Durée pendant laquelle attendre pour mettre en mémoire tampon les alertes appartenant au même groupe avant leur envoi initial.

| Intervalle de groupe
| 5m
| Durée d'attente avant d'envoyer une alerte qui a été ajoutée à un groupe d'alertes pour lequel une notification initiale a déjà été envoyée.

| Intervalle de répétition
| 4h
| Durée d'attente avant de renvoyer une alerte donnée qui a déjà été envoyée.
|===

[#_matching]
=== Concordance

Le champ *Match* fait référence à un ensemble de correspondances d'égalité utilisées pour identifier quelles alertes envoyer à une Route donnée en fonction des étiquettes définies sur cette alerte. Lorsque vous ajoutez des paires clé-valeur à l'interface utilisateur de Rancher, elles correspondent au YAML dans ce format{nbsp}:

[,yaml]
----
match:
  [ <labelname>: <labelvalue>, ... ]
----

Le champ *Match Regex* fait référence à un ensemble de correspondances regex utilisées pour identifier quelles alertes envoyer à une Route donnée en fonction des étiquettes définies sur cette alerte. Lorsque vous ajoutez des paires clé-valeur dans l'interface utilisateur de Rancher, elles correspondent au YAML dans ce format{nbsp}:

[,yaml]
----
match_re:
  [ <labelname>: <regex>, ... ]
----
