= Configuration de ServiceMonitor et PodMonitor
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

Les ServiceMonitors et PodMonitors sont tous deux des pseudo-CRD qui mappent la configuration de collecte de la ressource personnalisée Prometheus.

Ces objets de configuration spécifient de manière déclarative les points de terminaison à partir desquels Prometheus collectera des métriques.

Les ServiceMonitors sont plus couramment utilisés que les PodMonitors, et nous les recommandons pour la plupart des cas d'utilisation.

[NOTE]
====

Cette section suppose une familiarité avec le fonctionnement conjoint des composants de surveillance. Pour plus d'informations sur Alertmanager, voir {xref-how-monitoring-works}[cette section.]
====


[#_servicemonitors]
== ServiceMonitors

Ce pseudo-CRD correspond à une section de la configuration de la ressource personnalisée Prometheus. Il spécifie de manière déclarative comment les groupes de services Kubernetes doivent être surveillés.

Lorsqu'un ServiceMonitor est créé, l'Opérateur Prometheus met à jour la configuration de collecte de Prometheus pour inclure la configuration du ServiceMonitor. Ensuite, Prometheus commence à collecter des métriques à partir du point de terminaison défini dans le ServiceMonitor.

Tous les Services de votre cluster qui correspondent aux étiquettes situées dans le champ `selector` du ServiceMonitor seront surveillés en fonction du `endpoints` spécifié sur le ServiceMonitor. Pour plus d'informations sur les champs qui peuvent être spécifiés, veuillez consulter le https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#servicemonitor[spec] fourni par l'Opérateur Prometheus.

Pour plus d'informations sur le fonctionnement des ServiceMonitors, référez-vous à la https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/running-exporters.md[documentation de l'Opérateur Prometheus.]

[#_podmonitors]
== PodMonitors

Ce pseudo-CRD correspond à une section de la configuration de la ressource personnalisée Prometheus. Il spécifie de manière déclarative comment les groupes de pods doivent être surveillés.

Lorsqu'un PodMonitor est créé, l'Opérateur Prometheus met à jour la configuration de collecte de Prometheus pour inclure la configuration du PodMonitor. Ensuite, Prometheus commence à collecter des métriques à partir du point de terminaison défini dans le PodMonitor.

Tous les Pods de votre cluster qui correspondent aux étiquettes situées dans le champ `selector` du PodMonitor seront surveillés en fonction du `podMetricsEndpoints` spécifié sur le PodMonitor. Pour plus d'informations sur les champs qui peuvent être spécifiés, veuillez consulter le https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#podmonitor[spec] fourni par l'Opérateur Prometheus.
