= ConfigMaps
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc 
:product-path: cluster-admin/kubernetes-resources/configmaps.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
endif::[]

Bien que la plupart des types de secrets Kubernetes stockent des informations sensibles, https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/[les ConfigMaps] stockent des informations de configuration générales, telles qu'un groupe de fichiers de configuration. Comme les ConfigMaps ne stockent pas d'informations sensibles, ils peuvent être mis à jour automatiquement et ne nécessitent donc pas que leurs conteneurs soient redémarrés après une mise à jour (contrairement à la plupart des types de secrets, qui nécessitent des mises à jour manuelles et un redémarrage du conteneur pour prendre effet).

Les ConfigMaps acceptent des paires clé-valeur dans des formats de chaîne courants, comme des fichiers de configuration ou des blobs JSON. Après avoir téléversé un ConfigMap, n'importe quelle charge de travail peut y faire référence en tant que variable d'environnement ou montage de volume.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster qui a la charge de travail qui doit faire référence à un ConfigMap et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur menu:Plus de ressources[Noyau> ConfigMaps].
. Cliquez sur *Create*.
. Entrez un *Nom* pour le ConfigMap.
+

[NOTE]
====
Kubernetes classe les ConfigMaps comme https://kubernetes.io/docs/concepts/configuration/secret/[secrets], et deux secrets dans un projet ou un espace de noms ne peuvent pas porter le même nom. Par conséquent, pour éviter les conflits, vos ConfigMaps doivent avoir un nom unique parmi les autres certificats, registres et secrets dans votre espace de travail.
====


. Sélectionnez l'*Espace de noms* auquel vous souhaitez ajouter le ConfigMap.
. Dans l'onglet *Données*, ajoutez une paire clé-valeur à votre ConfigMap. Ajoutez autant de valeurs que nécessaire.  Vous pouvez ajouter plusieurs paires clé-valeur au ConfigMap en copiant et collant. Alternativement, utilisez *Lire à partir du fichier* pour ajouter les données. Remarque : Si vous devez stocker des données sensibles, {xref-secrets}[utilisez un secret], pas un ConfigMap.
. Cliquez sur *Create*.

*Résultat :* Votre ConfigMap est ajouté à l'espace de noms. Vous pouvez le voir dans l'interface utilisateur de Rancher depuis la vue menu:Ressources[ConfigMaps].

[#_whats_next]
== Et maintenant\...

Maintenant que vous avez un ConfigMap ajouté à un espace de noms, vous pouvez l'ajouter à une charge de travail que vous déployez depuis l'espace de noms d'origine. Vous pouvez utiliser le ConfigMap pour spécifier des informations que votre application doit consommer, telles que{nbsp}:

* Variables d'environnement de l'application.
* Spécification des paramètres pour un volume monté sur la charge de travail.

Pour plus d'informations sur l'ajout de ConfigMaps à une charge de travail, voir {xref-deploy-workloads}[Déploiement de charges de travail].
