= Configuration des ressources Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/index.adoc 
:product-path: cluster-admin/kubernetes-resources/kubernetes-resources-setup.adoc
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-configmaps: xref:cluster-admin/kubernetes-resources/configmaps.adoc
:xref-workloads-and-pods: xref:cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:xref-http-encrypt: xref:security/encrypting-http.adoc
:xref-l4-l7-lb: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/layer-4-and-layer-7-load-balancing.adoc
:xref-k8s-docker-registries: xref:cluster-admin/kubernetes-resources/kubernetes-and-docker-registries.adoc
:xref-add-ingresses: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/add-ingresses.adoc
:xref-create-services: xref:cluster-admin/kubernetes-resources/create-services.adoc
:xref-upgrade-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/roll-back-workloads.adoc
:xref-add-sidecar: xref:cluster-admin/kubernetes-resources/workloads-and-pods/add-a-sidecar.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-configmaps: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc
:xref-workloads-and-pods: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc
:xref-http-encrypt: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc
:xref-l4-l7-lb: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/layer-4-and-layer-7-load-balancing.adoc
:xref-k8s-docker-registries: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries.adoc
:xref-add-ingresses: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/add-ingresses.adoc
:xref-create-services: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/create-services.adoc
:xref-upgrade-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/roll-back-workloads.adoc
:xref-add-sidecar: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/add-a-sidecar.adoc
endif::[]

Vous pouvez visualiser et manipuler toutes les ressources personnalisées et les CRD dans un cluster Kubernetes depuis l'interface utilisateur de Rancher.

[#_workloads]
== Workloads

Déployez des applications sur vos nœuds de cluster en utilisant {xref-workloads-and-pods}[workloads], qui sont des objets contenant des pods exécutant vos applications, ainsi que des métadonnées définissant des règles pour le comportement du déploiement. Les workloads peuvent être déployés dans le cadre de l'ensemble des clusters ou dans un espace de noms.

Lors du déploiement d'un workload, vous pouvez déployer à partir de n'importe quelle image. Il existe une variété de {xref-workloads-and-pods}#_workload_types[_workload_types[types de workload] parmi lesquels choisir, qui déterminent comment votre application doit s'exécuter.

Après le déploiement d'un workload, vous pouvez continuer à travailler avec celui-ci. Vous pouvez :

* {xref-upgrade-workloads}[Mettre à niveau] le workload vers une version plus récente de l'application qu'il exécute.
* {xref-roll-back-workloads}[Rétablir] un workload à une version précédente, si un problème survient lors de la mise à niveau.
* {xref-add-sidecar}[Ajouter un sidecar], qui est un workload qui soutient un workload principal.

[#_load_balancing_and_ingress]
== Équilibrage de la charge et Ingress

[#_load_balancers]
=== Équilibreurs de charge

Après avoir lancé une application, elle n'est disponible que dans le cluster. Elle ne peut pas être atteinte de l'extérieur.

Si vous souhaitez que vos applications soient accessibles de l'extérieur, vous devez ajouter un équilibreur de charge à votre cluster. Les équilibreurs de charge créent une passerelle pour que les connexions externes accèdent à votre cluster, à condition que l'utilisateur connaisse l'adresse IP de l'équilibreur de charge et le numéro de port de l'application.

Rancher prend en charge deux types d'équilibreurs de charge{nbsp}:

* {xref-l4-l7-lb}#_layer_4_load_balancer[Layer-4 Load Balancers]
* {xref-l4-l7-lb}#_layer_7_load_balancer[Layer-7 Load Balancers]

Pour plus d'informations, consultez {xref-l4-l7-lb}[les équilibreurs de charge].

[#_ingress]
==== Ingress

Les équilibreurs de charge ne peuvent gérer qu'une seule adresse IP par service, ce qui signifie que si vous exécutez plusieurs services dans votre cluster, vous devez avoir un équilibreur de charge pour chaque service. Exécuter plusieurs équilibreurs de charge peut être coûteux. Vous pouvez contourner ce problème en utilisant un ingress.

L'ingress est un ensemble de règles qui agit comme un équilibreur de charge. L'ingress fonctionne en conjonction avec un ou plusieurs contrôleurs d'ingress pour acheminer dynamiquement les demandes de service. Lorsque l'ingress reçoit une demande, le(s) contrôleur(s) d'ingress dans votre cluster programment l'équilibreur de charge pour diriger la demande vers le service correct en fonction des sous-domaines de service ou des règles de chemin que vous avez configurées.

Pour plus d'informations, consultez {xref-add-ingresses}[Ingress].

Lors de l'utilisation d'ingress dans un projet, vous pouvez programmer le nom d'hôte de l'ingress à un DNS externe en configurant une entrée DNS globale.

[#_service_discovery]
== Découverte de service

Après avoir exposé votre cluster à des requêtes externes à l'aide d'un équilibreur de charge et/ou d'un ingress, il n'est disponible que par adresse IP. Pour créer un nom d'hôte résolvable, vous devez créer un enregistrement de service, qui est un enregistrement qui associe une adresse IP, un nom d'hôte externe, un alias d'enregistrement DNS, des workloads ou des pods étiquetés à un nom d'hôte spécifique.

Pour plus d'informations, consultez {xref-create-services}[Découverte de service].

[#_applications]
== Applications

En plus de lancer des composants individuels d'une application, vous pouvez utiliser le catalogue Rancher pour commencer à lancer des applications, qui sont des charts Helm.

[#_kubernetes_resources]
== Ressources Kubernetes

Dans le contexte d'un projet ou d'un espace de noms Rancher, _ressources_ sont des fichiers et des données qui soutiennent le fonctionnement de vos pods. Dans Rancher, les certificats, les registres et les secrets sont tous considérés comme des ressources. Cependant, Kubernetes classe les ressources en différents types de https://kubernetes.io/docs/concepts/configuration/secret/[secrets]. Par conséquent, dans un projet ou un espace de noms unique, les ressources individuelles doivent avoir des noms uniques pour éviter les conflits. Bien que les ressources soient principalement utilisées pour transporter des informations sensibles, elles ont également d'autres utilisations.

Les ressources incluent{nbsp}:

* {xref-http-encrypt}[Certificats]{nbsp}: Fichiers utilisés pour chiffrer/déchiffrer les données entrant ou sortant du cluster.
* {xref-configmaps}[ConfigMaps]{nbsp}: Fichiers qui stockent des informations de configuration générales, telles qu'un groupe de fichiers de configuration.
* {xref-secrets}[Secrets]: Fichiers qui stockent des données sensibles comme des mots de passe, des token ou des clés.
* {xref-k8s-docker-registries}[Registres]{nbsp}: Fichiers qui contiennent des identifiants utilisés pour s'authentifier auprès de registres privés.
