= Registre Kubernetes et registre d'images de conteneur
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries.adoc 
:product-path: cluster-admin/kubernetes-resources/kubernetes-and-docker-registries.adoc
:description: Découvrez le registre d'images de conteneur et le registre Kubernetes, leurs cas d'utilisation et comment utiliser un registre privé avec l'interface utilisateur de Rancher
:experimental:

Les registres sont des secrets Kubernetes contenant des identifiants utilisés pour s'authentifier auprès des https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[registres de conteneurs privés].

Le mot "registre" peut signifier deux choses, selon qu'il est utilisé pour désigner un registre de conteneurs ou un registre Kubernetes{nbsp}:

* Un *registre d'images de conteneur* (anciennement "registre Docker") contient des images de conteneur que vous pouvez récupérer et déployer. Le registre est une application côté serveur sans état et évolutive qui stocke et vous permet de distribuer des images de conteneurs.
* Le *registre Kubernetes* est un secret d'extraction d'images que votre déploiement utilise pour s'authentifier auprès d'un registre d'images.

Les déploiements utilisent le secret de registre Kubernetes pour s'authentifier auprès d'un registre d'images privé et ensuite récupérer une image de conteneur hébergée dessus.

Actuellement, les déploiements récupèrent automatiquement les identifiants du registre privé uniquement si la charge de travail est créée dans l'interface utilisateur de Rancher et non lorsqu'elle est créée via kubectl.

[#_creating_a_registry_in_namespaces]
== Créer un registre dans des espaces de noms

[NOTE]
.Condition préalable :
====

Vous devez avoir un registre privé disponible déjà déployé.

Si vous devez créer un registre privé, consultez les pages de documentation pour votre composant d'exécution respectif{nbsp}:

* https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration[Containerd].
 ** https://github.com/containerd/nerdctl/blob/main/docs/registry.md[Commandes Nerdctl et services de registre gérés].
* https://docs.docker.com/registry/deploying/[Docker].
====


. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster où vous souhaitez ajouter un registre et cliquez sur *Explorer*.
. Dans la navigation à gauche, cliquez soit sur menu:Stockage[Secrets] soit sur menu:Autres ressources[Noyau> Secrets].
. Cliquez sur *Create*.
. Cliquez sur *Registre*.
. Entrez un *Nom* pour le registre.
+

[NOTE]
====
Kubernetes classe les secrets, certificats et registres tous comme https://kubernetes.io/docs/concepts/configuration/secret/[secrets], et aucun secret dans un projet ou un espace de noms ne peut avoir un nom dupliqué. Par conséquent, pour éviter les conflits, votre registre doit avoir un nom unique parmi tous les secrets de votre espace de travail.
====


. Sélectionnez un espace de noms pour le registre.
. Sélectionnez le site web qui héberge votre registre privé. Ensuite, entrez les identifiants qui s'authentifient auprès du registre. Par exemple, si vous utilisez Docker Hub, fournissez votre nom d'utilisateur et votre mot de passe Docker Hub.
. Cliquez sur *Enregistrer*.

*Résultat :*

* Votre secret est ajouté à l'espace de noms que vous avez choisi.
* Vous pouvez voir le secret dans l'interface utilisateur de Rancher en cliquant soit sur menu:Stockage[Secrets] soit sur menu:Plus de ressources[Noyau> Secrets].
* Toute charge de travail que vous créez dans l'interface utilisateur de Rancher aura les identifiants pour accéder au registre si la charge de travail est dans le champ d'application du registre.

[#_creating_a_registry_in_projects]
== Créer un registre dans les projets

[NOTE]
.Conditions préalables :
====

Vous devez avoir un registre privé disponible déjà déployé.

Si vous devez créer un registre privé, consultez les pages de documentation pour votre composant d'exécution respectif{nbsp}:

* https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration[Containerd].
 ** https://github.com/containerd/nerdctl/blob/main/docs/registry.md[Commandes Nerdctl et services de registre gérés].
* https://docs.docker.com/registry/deploying/[Docker].
====


Avant la version 2.6, les secrets devaient être dans un champ d'application de projet. Les projets ne sont plus requis, et vous pouvez utiliser l'espace de noms à la place. En conséquence, l'interface utilisateur de Rancher a été mise à jour pour refléter cette nouvelle fonctionnalité. Cependant, vous pouvez toujours créer un registre à portée de projet si vous le souhaitez. Utilisez les étapes suivantes pour ce faire{nbsp}:

. Dans le coin supérieur gauche, cliquez sur *☰ > Paramètres globaux* dans le menu déroulant.
. Cliquez sur *Drapeaux de fonctionnalités*.
. Allez à l'option de fonctionnalité `legacy` et cliquez sur *Activer*.
. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster où vous souhaitez ajouter un registre et cliquez sur *Explorer*.
. Dans la navigation à gauche, cliquez soit sur menu:Stockage[Secrets] soit sur menu:Autres ressources[Noyau> Secrets].
. Cliquez sur *Create*.
. Cliquez sur *Registre*.
. Dans la barre de navigation supérieure, filtrez pour voir un seul projet.
. Entrez un *Nom* pour le registre.
+

[NOTE]
====
Kubernetes classe les secrets, certificats et registres tous comme https://kubernetes.io/docs/concepts/configuration/secret/[secrets], et aucun secret dans un projet ou un espace de noms ne peut avoir un nom dupliqué. Par conséquent, pour éviter les conflits, votre registre doit avoir un nom unique parmi tous les secrets de votre espace de travail.
====


. Sélectionnez un espace de noms pour le registre.
. Sélectionnez le site web qui héberge votre registre privé. Ensuite, entrez les identifiants qui s'authentifient auprès du registre. Par exemple, si vous utilisez Docker Hub, fournissez votre nom d'utilisateur et votre mot de passe Docker Hub.
. Cliquez sur *Enregistrer*.

*Résultat :*

* Votre secret est ajouté au projet individuel que vous avez choisi.
* Vous pouvez voir le secret dans l'interface utilisateur de Rancher en cliquant soit sur menu:Stockage[Secrets] soit sur menu:Plus de ressources[Noyau> Secrets].
* Toute charge de travail que vous créez dans l'interface utilisateur de Rancher aura les identifiants pour accéder au registre si la charge de travail est dans le champ d'application du registre.

[NOTE]
====

Les registres à portée de projet sur le cluster local ne sont visibles que lorsqu'un seul projet est sélectionné.
====


[#_using_a_private_registry]
== Utiliser un registre privé

Vous pouvez déployer une charge de travail avec une image provenant d'un registre privé via l'interface utilisateur de Rancher, ou avec `kubectl`.

[#_using_the_private_registry_with_the_rancher_ui]
=== Utilisation du registre privé avec l'interface utilisateur Rancher

Pour déployer une charge de travail avec une image de votre registre privé,

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster où vous souhaitez déployer une charge de travail et cliquez sur *Explorer*.
. Cliquez sur *Charge de travail*.
. Cliquez sur *Create*.
. Sélectionnez le type de charge de travail que vous souhaitez créer.
. Entrez un nom unique pour la charge de travail et choisissez un espace de noms.
. Dans le champ *Image du conteneur*, entrez l'URL du chemin vers l'image dans votre registre privé. Par exemple, si votre registre privé est sur Quay.io, vous pourriez utiliser `quay.io/<Quay profile name>/<Image name>`.
. Cliquez sur *Create*.

*Résultat :* Votre déploiement devrait se lancer, s'authentifier en utilisant les identifiants du registre privé que vous avez ajoutés dans l'interface utilisateur Rancher, et récupérer l'image du conteneur que vous avez spécifiée.

[#_using_the_private_registry_with_kubectl]
=== Utilisation du registre privé avec kubectl

Lorsque vous créez la charge de travail en utilisant `kubectl`, vous devez configurer le pod afin que son YAML contienne le chemin vers l'image dans le registre privé. Vous devez également créer et référencer le secret du registre car le pod n'a accès automatiquement aux identifiants du registre privé que s'il est créé dans l'interface utilisateur Rancher.

Le secret doit être créé dans le même espace de noms où la charge de travail est déployée.

Voici un exemple `pod.yml` pour une charge de travail qui utilise une image d'un registre privé. Dans cet exemple, le pod utilise une image de Quay.io, et le .yml spécifie le chemin vers l'image. Le pod s'authentifie auprès du registre en utilisant des identifiants stockés dans un secret Kubernetes appelé `testquay`, qui est spécifié dans `spec.imagePullSecrets` dans le champ `name`{nbsp}:

[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: quay.io/<Quay profile name>/<image name>
  imagePullSecrets:
  - name: testquay
----

Dans cet exemple, le secret nommé `testquay` se trouve dans l'espace de noms par défaut.

Vous pouvez utiliser `kubectl` pour créer le secret avec les identifiants du registre privé. Cette commande crée le secret nommé `testquay`{nbsp}:

----
kubectl create secret docker-registry testquay \
    --docker-server=quay.io \
    --docker-username=<Profile name> \
    --docker-password=<password>
----

Pour voir comment le secret est stocké dans Kubernetes, vous pouvez utiliser cette commande{nbsp}:

----
kubectl get secret testquay --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
----

Le résultat ressemble à ceci{nbsp}:

----
{"auths":{"quay.io":{"username":"<Profile name>","password":"<password>","auth":"c291bXlhbGo6dGVzdGFiYzEyMw=="}}}
----

Après le déploiement de la charge de travail, vous pouvez vérifier si l'image a été récupérée avec succès{nbsp}:

----
kubectl get events
----

Le résultat doit se présenter comme suit :

----
14s         Normal    Scheduled          Pod    Successfully assigned default/private-reg2 to minikube
11s         Normal    Pulling            Pod    pulling image "quay.io/<Profile name>/<image name>"
10s         Normal    Pulled             Pod    Successfully pulled image "quay.io/<Profile name>/<image name>"
----

Pour plus d'informations, consultez la documentation Kubernetes sur https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret[la création d'un pod qui utilise votre secret.]
