= Shibboleth (SAML) konfigurieren
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/configure-shibboleth-saml/index.adoc 
:product-path: rancher-admin/users/authn-and-authz/shibboleth-saml/shibboleth-saml.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-openldap-reference: xref:rancher-admin/users/authn-and-authz/openldap/reference.adoc
:xref-shibboleth-saml-group-permissions: xref:rancher-admin/users/authn-and-authz/shibboleth-saml/group-permissions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
:xref-openldap-reference: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/configure-openldap/openldap-config-reference.adoc
:xref-shibboleth-saml-group-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/configure-shibboleth-saml/about-group-permissions.adoc
endif::[]

Wenn Ihre Organisation Shibboleth Identity Provider (IdP) für die Benutzerauthentifizierung verwendet, können Sie Rancher so konfigurieren, dass Ihre Benutzer sich mit ihren Shibboleth-Anmeldeinformationen bei Rancher anmelden können.

In dieser Konfiguration werden Rancher-Benutzer, wenn sie sich anmelden, zum Shibboleth IdP weitergeleitet, um ihre Anmeldeinformationen einzugeben. Nach der Authentifizierung werden sie zurück zur Rancher-Benutzeroberfläche weitergeleitet.

Wenn Sie auch OpenLDAP als Backend für Shibboleth konfigurieren, wird eine SAML-Assertion an Rancher zurückgegeben, die Benutzerattribute einschließlich Gruppen enthält. Der authentifizierte Benutzer kann dann auf Ressourcen in Rancher zugreifen, für die seine Gruppen Berechtigungen haben.

____
Die Anweisungen in diesem Abschnitt setzen voraus, dass Sie verstehen, wie Rancher, Shibboleth und OpenLDAP zusammenarbeiten. Für eine detailliertere Erklärung, wie es funktioniert, siehe {xref-shibboleth-saml-group-permissions}[diese Seite.]
____

[#_setting_up_shibboleth_in_rancher]
== Einrichten von Shibboleth in Rancher

[#_shibboleth_prerequisites]
=== Shibboleth-Voraussetzungen

____
* Sie müssen einen Shibboleth IdP-Server konfiguriert haben.
* Nachfolgend sind die Rancher Service Provider-URLs aufgeführt, die für die Konfiguration benötigt werden:
Metadaten-URL: `\https://<rancher-server>/v1-saml/shibboleth/saml/metadata`
Assertion Consumer Service (ACS) URL: `\https://<rancher-server>/v1-saml/shibboleth/saml/acs`
* Exportieren Sie eine `metadata.xml` Datei von Ihrem IdP-Server. Für weitere Informationen siehe die https://wiki.shibboleth.net/confluence/display/SP3/Home[Shibboleth-Dokumentation.]
____

[#_configure_shibboleth_in_rancher]
=== Shibboleth in Rancher konfigurieren

Wenn Ihre Organisation Shibboleth zur Benutzerauthentifizierung verwendet, können Sie Rancher so konfigurieren, dass Ihre Benutzer sich mit ihren IdP-Anmeldeinformationen anmelden können.

. Klicken Sie oben links auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie im linken Navigationsmenü auf *Auth-Anbieter*.
. Klicken Sie auf *Shibboleth*.
. Füllen Sie das Formular *Shibboleth-Konto konfigurieren* aus. Shibboleth IdP ermöglicht es Ihnen, den gewünschten Datenspeicher anzugeben. Sie können entweder eine Datenbank hinzufügen oder einen vorhandenen LDAP-Server verwenden. Wenn Sie beispielsweise Ihren Active Directory (AD)-Server auswählen, beschreiben die folgenden Beispiele, wie Sie AD-Attribute auf Felder innerhalb von Rancher abbilden können.
 .. *Feld für Anzeigenamen*: Geben Sie das AD-Attribut ein, das den Anzeigenamen der Benutzer enthält (Beispiel: `displayName`).
 .. *Feld für Benutzernamen*: Geben Sie das AD-Attribut ein, das den Benutzernamen/Vornamen enthält (Beispiel: `givenName`).
 .. *UID-Feld*: Geben Sie ein AD-Attribut ein, das für jeden Benutzer eindeutig ist (Beispiel: `sAMAccountName`, `distinguishedName`).
 .. *Gruppenfeld*: Erstellen Sie Einträge zur Verwaltung von Gruppenmitgliedschaften (Beispiel: `memberOf`).
 .. *Rancher API-Host*: Geben Sie die URL für Ihren Rancher-Server ein.
 .. *Privater Schlüssel* und *Zertifikat*: Dies ist ein Schlüssel-Zertifikat-Paar, um eine sichere Shell zwischen Rancher und Ihrem IdP zu erstellen.
+
Sie können eines mit einem openssl-Befehl generieren. Beispiel:
+
----
 openssl req -x509 -newkey rsa:2048 -keyout myservice.key -out myservice.cert -days 365 -nodes -subj "/CN=myservice.example.com"
----

 .. *IDP-Metadaten*: Die `metadata.xml` Datei, die Sie von Ihrem IdP-Server exportiert haben.
. Nachdem Sie das Formular *Shibboleth-Konto konfigurieren* ausgefüllt haben, klicken Sie auf *Aktivieren*.
+
Rancher leitet Sie zur IdP-Anmeldeseite weiter. Geben Sie Anmeldeinformationen ein, die mit Shibboleth IdP authentifiziert werden, um Ihre Rancher Shibboleth-Konfiguration zu validieren.
+

[NOTE]
====
Möglicherweise müssen Sie Ihren Popup-Blocker deaktivieren, um die IdP-Anmeldeseite zu sehen.
====


*Ergebnis:* Rancher ist so konfiguriert, dass es mit Shibboleth funktioniert. Ihre Benutzer können sich jetzt mit ihren Shibboleth-Anmeldedaten bei Rancher anmelden.

[NOTE]
.SAML-Anbieter-Hinweise
====
Wenn Sie Shibboleth ohne OpenLDAP konfigurieren, gelten die folgenden Hinweise, da das SAML-Protokoll keine Suche oder Abfrage nach Benutzern oder Gruppen unterstützt.

* Es gibt keine Validierung von Benutzern oder Gruppen, wenn Berechtigungen in Rancher zugewiesen werden.
* Beim Hinzufügen von Benutzern müssen die genauen Benutzer-IDs (d.h. UID-Feld) korrekt eingegeben werden. Während Sie die Benutzer-ID eingeben, wird nicht nach anderen Benutzer-IDs gesucht, die übereinstimmen könnten.
* Beim Hinzufügen von Gruppen müssen Sie die Gruppe aus dem Dropdown-Menü auswählen, die sich neben dem Textfeld befindet. Rancher geht davon aus, dass jede Eingabe im Textfeld ein Benutzer ist.
* Das Gruppen-Dropdown zeigt nur die Gruppen an, in denen Sie Mitglied sind. Wenn Sie jedoch Administratorrechte oder eingeschränkte Administratorrechte haben, können Sie einer Gruppe beitreten, in der Sie kein Mitglied sind.

Um die Suche nach Gruppen bei der Zuweisung von Berechtigungen in Rancher zu aktivieren, müssen Sie ein Backend für den SAML-Anbieter konfigurieren, das Gruppen unterstützt, wie OpenLDAP.
====

[#_configuring_saml_single_logout_slo]
=== Konfigurieren von SAML Single Logout (SLO)

include::shared:ROOT:partial$en/configure-slo.adoc[]

[#_setting_up_openldap_in_rancher]
== Einrichten von OpenLDAP in Rancher

Wenn Sie auch OpenLDAP als Backend für Shibboleth konfigurieren, wird eine SAML-Assertion an Rancher zurückgegeben, die Benutzerattribute einschließlich Gruppen enthält. Dann können authentifizierte Benutzer auf Ressourcen in Rancher zugreifen, für die ihre Gruppen Berechtigungen haben.

[#_openldap_prerequisites]
=== OpenLDAP-Voraussetzungen

Rancher muss mit einem LDAP-Bind-Konto (auch bekannt als Dienstkonto) konfiguriert werden, um LDAP-Einträge zu suchen und abzurufen, die Benutzern und Gruppen zugeordnet sind, die Zugriff haben sollten. Es wird empfohlen, kein Administratorkonto oder persönliches Konto für diesen Zweck zu verwenden und stattdessen ein dediziertes Konto in OpenLDAP mit schreibgeschütztem Zugriff auf Benutzer und Gruppen unter der konfigurierten Suchbasis zu erstellen (siehe unten).

____
*Verwendung von TLS?*

Wenn das vom OpenLDAP-Server verwendete Zertifikat selbstsigniert ist oder nicht von einer anerkannten Zertifizierungsstelle stammt, stellen Sie sicher, dass Sie das CA-Zertifikat (verknüpft mit allen Zwischenzertifikaten) im PEM-Format zur Hand haben. Sie müssen dieses Zertifikat während der Konfiguration einfügen, damit Rancher in der Lage ist, die Zertifikatkette zu validieren.
____

[#_configure_openldap_in_rancher]
=== Konfigurieren Sie OpenLDAP in Rancher

Konfigurieren Sie die Einstellungen für den OpenLDAP-Server, Gruppen und Benutzer. Für Hilfe beim Ausfüllen jedes Feldes, beziehen Sie sich auf die {xref-openldap-reference}[Konfigurationsreferenz.] Beachten Sie, dass die Mitgliedschaft in verschachtelten Gruppen für Shibboleth nicht verfügbar ist.

____
Bevor Sie mit der Konfiguration fortfahren, machen Sie sich bitte mit den Konzepten der {xref-authn-authz}#_external_authentication_configuration_and_principal_users[Externe Authentifizierungskonfiguration und Hauptbenutzer] vertraut.
____

. Melden Sie sich mit dem anfänglichen lokalen `admin` Konto in der Rancher-Benutzeroberfläche an.
. Klicken Sie oben links auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie im linken Navigationsmenü auf *Auth-Anbieter*.
. Klicken Sie auf *Shibboleth* oder, falls SAML bereits konfiguriert ist, auf *Konfiguration bearbeiten*.
. Unter *Benutzer- und Gruppensuche* aktivieren Sie *OpenLDAP-Server konfigurieren*.

[#_troubleshooting]
== Fehlerbehebung

Wenn Sie beim Testen der Verbindung zum OpenLDAP-Server auf Probleme stoßen, überprüfen Sie zuerst die eingegebenen Anmeldeinformationen für das Dienstkonto sowie die Konfiguration der Suchbasis. Sie können auch die Rancher-Protokolle überprüfen, um die Ursache des Problems zu ermitteln. Debug-Protokolle können detailliertere Informationen über den Fehler enthalten. Bitte beziehen Sie sich auf xref:faq/technical-items.adoc#_how_can_i_enable_debug_logging[Wie kann ich das Debug-Logging aktivieren] in dieser Dokumentation.
