= Crea una versión de cumplimiento personalizada para ejecutar un escaneo de clúster.
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: instrucciones/guías-de-usuario-avanzadas/guías-de-escaneo-de-cumplimiento/crear-una-versión-de-cumplimiento-personalizada-para-ejecutar.adoc 
:product-path: security/compliance-scans/create-a-custom-compliance-version-to-run.adoc
ifeval::["{build-type}" != "community"]
:xref-compliance-scan-custom-benchmark: xref:security/compliance-scans/custom-benchmark.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-compliance-scan-custom-benchmark: xref:integrations-in-rancher/compliance-scans/custom-benchmark.adoc
endif::[]

Podría haber algunas configuraciones de clúster de Kubernetes que requieran configuraciones personalizadas de las pruebas de cumplimiento. Por ejemplo, la vía a los archivos de configuración de Kubernetes o certificados podría ser diferente de la ubicación estándar donde el cumplimiento en sentido ascendente los busca.

Ahora es posible crear una versión de cumplimiento personalizada para ejecutar un escaneo de clúster utilizando la `rancher-compliance` aplicación.

Para más detalles, consulta {xref-compliance-scan-custom-benchmark}[esta página.]
