= Habilitar alertas para {rancher-product-name} Compliance
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: instrucciones/advanced-user-guides/compliance-scan-guides/habilitar-alertas-para-rancher-compliance.adoc 
:product-path: security/compliance-scans/enable-alerting-for-rancher-compliance.adoc
ifeval::["{build-type}" != "community"]
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
endif::[]

Se pueden configurar alertas para que se envíen para un escaneo que se ejecute según un horario.

[NOTE]
.Requisito previo:
====

Antes de habilitar alertas para `rancher-compliance`, aseguraos de instalar la aplicación `rancher-monitoring` y configurar los Receptores y Rutas. Para más información, consultad {xref-receivers}[esta sección.]

Al configurar las rutas para las alertas de `rancher-compliance`, podéis especificar la coincidencia utilizando el par clave-valor `job: rancher-compliance-scan`. Un ejemplo de configuración de ruta es {xref-receivers}#_ejemplo_configuración_ruta_alertas_escaneo_cumplimiento[aquí.]
====


Mientras se instala o se actualiza el chart de Helm `rancher-compliance`, establece la siguiente bandera a `true` en el `values.yaml`:

[,yaml]
----
alerts:
  enabled: true
----
