= Lancement de Kubernetes sur de nouveaux nœuds dans un fournisseur d'infrastructure
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: procédures/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-d'infrastructure/index.adoc 
:product-path: cluster-deployment/infra-providers/infra-providers.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:url-rke2-introduction: https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html
:xref-infra-providers: xref:déploiement/fournisseurs-d'infrastructure/fournisseurs-d'infrastructure.adoc
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
:xref-manage-node-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
:xref-cluster-templates: xref:cluster-admin/manage-clusters/cluster-templates.adoc
:xref-recommended-architecture: xref:cluster-deployment/production-checklist/recommended-cluster-architecture.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rke2-config: xref:guides-de-référence/configuration-de-cluster/configuration-du-serveur-rancher/configuration-du-cluster-rke2.adoc
:url-rke2-introduction: https://docs.rke2.io/
:xref-infra-providers: xref:procédures/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-d'infrastructure/index.adoc
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
:xref-manage-node-drivers: xref:procédures/nouveaux-guides-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-pilotes-de-provisionnement/gérer-pilotes-de-nœuds.adoc
:xref-cluster-templates: xref:how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc
:xref-recommended-architecture: xref:procédures/nouveaux-guides-utilisateurs/kubernetes-clusters-dans-la-configuration-rancher/liste-de-vérification-pour-clusters-prêts-pour-la-production/architecture-recommandée-du-cluster.adoc
endif::[]

Lorsque vous {xref-rke2-config}#_cluster_config_file_reference[créez un cluster RKE2] en utilisant une configuration de machine dans Rancher, chaque pool de nœuds résultant est affiché dans un nouvel onglet **Pools de machines**. Vous pouvez voir les pools de machines en procédant comme suit{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Cliquez sur le nom du cluster RKE2.

[#__rke2_product_name_clusters]
== {rke2-product-name} Clusters

Rancher v2.6 introduit le provisionnement pour les clusters {url-rke2-introduction}[RKE2] directement depuis l'interface utilisateur de Rancher. RKE2, également connu sous le nom de RKE Government, est une distribution Kubernetes entièrement conforme axée sur la sécurité et la conformité aux États-Unis. secteur du gouvernement fédéral américain.

[NOTE]
====

Pour les modèles de cluster RKE2, veuillez vous référer à {xref-cluster-templates}#_modèle_de_cluster_rke2[cette page] pour des informations supplémentaires.
====


[#_node_roles]
=== Rôles de nœud

La CLI RKE2 expose deux rôles, `server` et `agent`, qui représentent les rôles de nœud Kubernetes `etcd` + `controlplane` et `worker` respectivement. Avec l'intégration de RKE2 dans Rancher v2.6, les pools de nœuds RKE2 peuvent représenter des attributions de rôles plus détaillées de sorte que les rôles `etcd` et `controlplane` peuvent être représentés.

La même fonctionnalité d'utilisation des nœuds `etcd`, `controlplane` et `worker` est possible dans la CLI RKE2 en utilisant des options et le marquage des nœuds pour contrôler où les charges de travail et le nœud maître Kubernetes étaient programmés. La raison pour laquelle ces rôles n'ont pas été implémentés en tant que rôles de première classe dans le RKE2 CLI est que RKE2 est conceptualisé comme un ensemble de blocs de construction bruts qui sont mieux exploités par un système d'orchestration tel que Rancher.

Dans notre {xref-recommended-architecture}[architecture de cluster recommandée], nous décrivons combien de nœuds de chaque rôle les clusters devraient avoir{nbsp}:

* Au moins trois nœuds avec le rôle etcd pour survivre à la perte d'un nœud.
* Au moins deux nœuds avec le rôle controlplane pour une haute disponibilité du composant maître.
* Au moins deux nœuds avec le rôle worker pour la replanification des charges de travail en cas d'échec d'un nœud.
