= Configuration d'Alertmanager
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procédure/guides-utilisateur-avancés/guides-de-configuration-v2/configuration-avancée/alertmanager.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

Il n'est généralement pas nécessaire de modifier directement la ressource personnalisée d'Alertmanager. Pour la plupart des cas d'utilisation, vous n'aurez besoin de modifier que les Récepteurs et les Routes pour configurer les notifications.

Lorsque les Récepteurs et les Routes sont mis à jour, l'application de surveillance mettra automatiquement à jour la ressource personnalisée d'Alertmanager pour être cohérente avec ces changements.

[NOTE]
====

Cette section suppose que vous êtes familier avec la manière dont les composants de surveillance fonctionnent ensemble. Pour plus d'informations sur Alertmanager, consultez {xref-how-monitoring-works}#_3_how_alertmanager_works[cette section.]
====


[#_about_the_alertmanager_custom_resource]
== À propos de la ressource personnalisée d'Alertmanager

Par défaut, Rancher Monitoring déploie un seul Alertmanager sur un cluster qui utilise un Secret de configuration d'Alertmanager par défaut.

Vous souhaiterez peut-être modifier la ressource personnalisée d'Alertmanager si vous souhaitez profiter d'options avancées qui ne sont pas exposées dans les formulaires de l'interface utilisateur de Rancher, telles que la possibilité de créer une structure d'arbre de routage qui est plus profonde que deux niveaux.

Il est également possible de créer plus d'un Alertmanager dans un cluster, ce qui peut être utile si vous souhaitez mettre en œuvre une surveillance au niveau de l'espace de noms. Dans ce cas, vous devez gérer les ressources personnalisées d'Alertmanager en utilisant le même Secret de configuration d'Alertmanager sous-jacent.

[#_deeply_nested_routes]
=== Routes profondément imbriquées

Bien que l'interface utilisateur de Rancher ne prenne en charge qu'un arbre de routage de deux niveaux, vous pouvez configurer des structures de routage plus profondément imbriquées en modifiant le YAML d'Alertmanager.

[#_multiple_alertmanager_replicas]
=== Répliques multiples d'Alertmanager

Dans le cadre des options de déploiement du chart, vous pouvez choisir d'augmenter le nombre de réplicas d'Alertmanager déployés sur votre cluster. Les réplicas peuvent tous être gérés en utilisant le même Secret de configuration d'Alertmanager sous-jacent.

Ce Secret doit être mis à jour ou modifié chaque fois que vous souhaitez{nbsp}:

* Ajouter de nouveaux notificateurs ou récepteurs
* Modifier les alertes qui doivent être envoyées à des notificateurs ou récepteurs spécifiques
* Modifier le groupe d'alertes qui est envoyé.

Par défaut, vous pouvez soit choisir de fournir un Secret de configuration d'Alertmanager existant (c'est-à-dire tout Secret dans l'espace de noms `cattle-monitoring-system`) ou permettre à Rancher Monitoring de déployer un Secret de configuration d'Alertmanager par défaut sur votre cluster.

Par défaut, le Secret de configuration d'Alertmanager créé par Rancher ne sera jamais modifié ou supprimé lors d'une mise à niveau ou d'une désinstallation du chart `rancher-monitoring`. Cette restriction empêche les utilisateurs de perdre ou d'écraser leur configuration d'alerte lors de l'exécution d'opérations sur le chart.

Pour plus d'informations sur les champs pouvant être spécifiés dans le Secret de configuration d'Alertmanager, veuillez consulter la https://prometheus.io/docs/alerting/latest/alertmanager/[documentation d'Alertmanager de Prometheus.]

La spécification complète du fichier de configuration d'Alertmanager et ce qu'elle nécessite se trouve https://prometheus.io/docs/alerting/latest/configuration/#configuration-file[ici.]
