= Configuration des PrometheusRules
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procédure-guides/guides-utilisateur-avancés/guides-de-configuration-v2/configuration-avancée/prometheusrules.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/prometheusrules.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-promql-expressions: xref:observability/monitoring-and-dashboards/promql-expressions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-promql-expressions: xref:integrations-in-rancher/monitoring-and-alerting/promql-expressions.adoc
endif::[]

Une PrometheusRule définit un groupe de règles d'alerte et/ou d'enregistrement Prometheus.

[NOTE]
====

Cette section suppose que vous êtes familier avec la manière dont les composants de surveillance fonctionnent ensemble. Pour plus d'informations, consultez {xref-how-monitoring-works}[cette section.]
====


[#_creating_prometheusrules_in_the_rancher_ui]
== Création de PrometheusRules dans l'interface utilisateur Rancher

[NOTE]
.Condition préalable :
====

L'application de surveillance doit être installée.
====


Pour créer des groupes de règles dans l'interface utilisateur Rancher,

. Allez dans le cluster où vous souhaitez créer des groupes de règles. Cliquez sur menu:Surveillance[Avancé] et cliquez sur *Règles Prometheus*.
. Cliquez sur *Create*.
. Entrez un *Nom de groupe*.
. Configurez les règles. Dans l'interface utilisateur de Rancher, nous nous attendons à ce qu'un groupe de règles contienne soit des règles d'alerte, soit des règles d'enregistrement, mais pas les deux. Pour obtenir de l'aide pour remplir les formulaires, reportez-vous aux options de configuration ci-dessous.
. Cliquez sur *Create*.

*Résultat :* Les alertes peuvent être configurées pour envoyer des notifications aux destinataires.

[#_about_the_prometheusrule_custom_resource]
== À propos de la ressource personnalisée PrometheusRule

Lorsque vous définissez une Rule (déclarée au sein d'un RuleGroup dans une ressource PrometheusRule), la https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#rule[spec de la Rule elle-même] contient des labels utilisés par Alertmanager pour déterminer quelle Route doit recevoir cette alerte. Par exemple, une alerte avec le label `team: front-end` sera envoyée à toutes les Routes qui correspondent à ce label.

Les fichiers de règles Prometheus sont conservés dans des ressources personnalisées PrometheusRule. Une PrometheusRule vous permet de définir un ou plusieurs RuleGroups. Chaque RuleGroup se compose d'un ensemble d'objets Rule qui peuvent chacun représenter soit une règle d'alerte, soit une règle d'enregistrement avec les champs suivants{nbsp}:

* Le nom de la nouvelle alerte ou du nouvel enregistrement
* Une expression PromQL pour la nouvelle alerte ou le nouvel enregistrement
* Étiquettes qui doivent être attachées à l'alerte ou à l'enregistrement pour l'identifier (par exemple, nom du cluster ou gravité)
* Annotations qui encodent des informations supplémentaires importantes à afficher sur la notification d'une alerte (par exemple, résumé, description, message, URL du runbook, etc.). Ce champ n'est pas requis pour les règles d'enregistrement.

Pour plus d'informations sur les champs qui peuvent être spécifiés, veuillez consulter le https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#prometheusrulespec[spec du Prometheus Operator]

Utilisez le champ de sélection d'étiquettes `ruleSelector` dans l'objet Prometheus pour définir les fichiers de règles que vous souhaitez monter dans Prometheus.

Pour des exemples, référez-vous à la documentation de Prometheus sur https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/[les règles d'enregistrement] et https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[les règles d'alerte.]

[#_configuration]
== Configuration

[#_rule_group]
=== Groupe de règles

|===
| Champ | Description

| Nom du groupe
| Le nom du groupe. Doit être unique dans un fichier de règles.

| Intervalle de remplacement du groupe
| Durée (en secondes) définissant la fréquence d'évaluation des règles du groupe
|===

[#_alerting_rules]
=== Règles d'alerte

https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[Les règles d'alerte] vous permettent de définir des conditions d'alerte basées sur des expressions PromQL (Langage de requête Prometheus) et d'envoyer des notifications concernant les alertes déclenchées à un service externe.

|===
| Champ | Description

| Nom de l'alerte
| Le nom de l'alerte. Doit être une valeur d'étiquette valide.

| Délai avant déclenchement
| Durée en secondes. Les alertes sont considérées comme déclenchées dès qu'elles se maintiennent pendant ce laps de temps Les alertes qui n'ont pas encore été déclenchées depuis suffisamment longtemps sont considérées comme en attente.

| Expression PromQL
| L'expression PromQL à évaluer. Prometheus évaluera la valeur actuelle de cette expression PromQL à chaque cycle d'évaluation et toutes les séries temporelles résultantes deviendront des alertes en attente ou déclenchées. Pour plus d'informations, consultez la https://prometheus.io/docs/prometheus/latest/querying/basics/[documentation de Prometheus] ou nos {xref-promql-expressions}[exemples d'expressions PromQL.]

| Libellés
| Étiquettes à ajouter ou à écraser pour chaque alerte.

| Gravité
| Lorsqu'elles sont activées, les étiquettes sont attachées à l'alerte ou à l'enregistrement qui l'identifient par le niveau de gravité.

| Valeur de l'étiquette de gravité
| Critique, avertissement ou aucune

| Annotations
| Les annotations sont un ensemble d'étiquettes informatives qui peuvent être utilisées pour stocker des informations supplémentaires plus longues, telles que des descriptions d'alerte ou des liens vers des runbooks. Un https://en.wikipedia.org/wiki/Runbook[runbook] est un ensemble de documentation sur la manière de gérer les alertes. Les valeurs d'annotation peuvent https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating[utiliser des modèles.]
|===

[#_recording_rules]
=== Règles d'enregistrement

https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules[Les règles d'enregistrement] vous permettent de précalculer des expressions PromQL (Langage de requête Prometheus) fréquemment nécessaires ou coûteuses en calcul et de sauvegarder leur résultat sous forme d'un nouvel ensemble de séries temporelles.

|===
| Champ | Description

| Nom de la série temporelle
| Le nom de la série temporelle à produire. Doit être un nom de métrique valide.

| Expression PromQL
| L'expression PromQL à évaluer. Prometheus évaluera la valeur actuelle de cette expression PromQL à chaque cycle d'évaluation et le résultat sera enregistré sous forme d'un nouvel ensemble de séries temporelles avec le nom de métrique donné par 'record'.  Pour plus d'informations sur les expressions, consultez la https://prometheus.io/docs/prometheus/latest/querying/basics/[documentation de Prometheus] ou nos {xref-promql-expressions}[exemples d'expressions PromQL.]

| Libellés
| Étiquettes à ajouter ou à écraser avant de stocker le résultat.
|===
