= {kubewarden-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/kubewarden/index.adoc 
:product-path: integrations/kubewarden.adoc

Kubewardenは、クラスターリソースを保護し、管理するためのポリシーエンジンです。ポリシーを通じてリソースリクエストの検証と変更を行うことができ、コンテキストに応じたポリシーやイメージ署名の検証を含みます。ポリシーを監視モードまたは強制モードで実行でき、クラスターの状態の概要を提供します。

Kubewardenは、ポリシーをコードとして有効化し、簡素化することで、ユニバーサルポリシーエンジンを目指しています。KubewardenのポリシーはWebAssemblyにコンパイルされており、サイズは小さく（400KB〜2MB）、サンドボックスされており、安全で、ポータブルです。それは、組織内の各ペルソナに対応することでユニバーサルであることを目指しています：

* ポリシーユーザー：Kubernetesカスタムリソースを使用してポリシーを管理および宣言し、Rego（OPAおよびGatekeeper）で書かれた既存のポリシーを再利用します。CI/CDでクラスターの外でポリシーをテストします。
* ポリシー開発者：好みのWasmコンパイル言語（Rego、Go、Rust、C#、Swift、TypeScriptなど）でポリシーを書きます。すでに知っているツール、ライブラリ、ワークフローのエコシステムを再利用します。
* ポリシー配布者：ポリシーはOCIアーティファクトであり、OCIリポジトリを通じて提供し、ソフトウェア部品表やアーティファクト署名などの業界標準をインフラストラクチャで使用します。
* クラスターオペレーター：Kubewardenはモジュラーです（OCIレジストリ、PolicyServers、監査スキャナー、コントローラー）。ニーズに合わせてデプロイメントを構成し、異なるテナントを分離します。監査スキャナーとポリシーレポートを使用して、クラスター全体の過去、現在、可能な違反の概要を取得します。
* Kubewardenインテグレーター：新しいKubewardenモジュールやカスタムポリシーを書くためのプラットフォームとして使用します。

[#__kubewarden_product_name_with_rancher]
== {kubewarden-product-name} と Rancher

KubewardenのアップストリームHelmチャートは完全にRancherアプリとして統合されており、インストールオプションのUIを提供します。チャートには、Rancherスタックを尊重するデフォルト設定（例：Rancherシステムネームスペースにポリシーを適用しない）や、デフォルトのPolicyServerおよびポリシーが含まれています。ユーザーはすべてのKubewarden機能にアクセスでき、Kubernetes API（例：kubectlを使用）と対話することでPolicyServersおよびポリシーを手動でデプロイすることができます。

Kubewardenは、削除されたKubernetes Podセキュリティポリシーの完全な置き換えを提供します。Kubewardenは、最近のKubernetesのバージョンで導入された新しいPodセキュリティアドミッション機能と統合し、そのセキュリティ機能を強化します。

[#__kubewarden_product_name_with_rancher_prime]
== {kubewarden-product-name} と {rancher-prime}

Kubewardenのために利用可能なRancher UI拡張機能は、それをRancher UIに統合します。UI拡張機能は、Kubewardenスタックのインストールと設定を自動化し、SUSEによって管理されるポリシーへのアクセスを設定します。UI拡張機能は、すぐに使用できるポリシーの厳選されたカタログへのアクセスを提供します。UI拡張機能を使用すると、これらのポリシーを閲覧、インストール、設定できます。

UI拡張機能は、Kubewardenスタックのコンポーネントとその動作の概要を提供します。これには、Kubewardenのメトリクスとトレースイベントへのアクセスが含まれます。オペレーターは、ポリシーがクラスターに与える影響を理解し、問題をトラブルシュートできます。

さらに、UI拡張機能はポリシーレポーターUIを提供し、Kubernetesクラスターのコンプライアンス状況の視覚的な概要を示します。このUIを使用すると、オペレーターはすべての非準拠のKubernetesリソースを迅速に特定し、違反の理由を理解し、それに応じて行動できます。
これらすべては、Rancher Primeのサポート提供とともに提供されます。
