= Personalización de los paneles de Grafana
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc 
:product-path: observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-rancher-monitoring-rbac: xref:observabilidad/monitoring-and-dashboards/rbac-para-monitoreo.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
endif::[]

En esta sección, aprenderás a personalizar el tablero de Grafana para mostrar métricas que se aplican a un contenedor determinado.

[#_prerequisites]
== Requisitos previos

Antes de que puedas personalizar un tablero de Grafana, la aplicación `rancher-monitoring` debe estar instalada.

Para ver los enlaces a las interfaces de usuario de monitorización externas, incluidos los paneles de Grafana, necesitarás al menos un {xref-rancher-monitoring-rbac}#_usuarios_con_permisos_basados_en_rancher[rol de miembro del proyecto.]

[#_signing_in_to_grafana]
== Iniciar sesión en Grafana

. En la interfaz de Rancher, ve al clúster que tiene el tablero que deseas personalizar.
. En el menú de navegación de la izquierda, haz clic en *Monitorización.*
. Haz clic en *Grafana.* El tablero de Grafana debería abrirse en una nueva pestaña.
. Ve al icono de inicio de sesión en la esquina inferior izquierda y haz clic en *Iniciar sesión.*
. Inicie sesión en Grafana. El nombre de usuario y la contraseña predeterminados del administrador para la instancia de Grafana son `admin/prom-operator`. (Independientemente de quién tenga la contraseña, se requiere permiso de administrador del clúster en Rancher para acceder a la instancia de Grafana.) También se pueden proporcionar credenciales alternativas al desplegar o actualizar el gráfico.

[#_getting_the_promql_query_powering_a_grafana_panel]
== Obteniendo la consulta PromQL que alimenta un panel de Grafana

Para cualquier panel, puedes hacer clic en el título y luego en *Explorar* para obtener las consultas PromQL que alimentan el gráfico.

Para este ejemplo, nos gustaría obtener el uso de CPU para el contenedor Alertmanager, así que hacemos clic en menu:Utilización de CPU[Inspeccionar.]

La pestaña *Datos* muestra los datos subyacentes como una serie temporal, con el tiempo en la primera columna y el resultado de la consulta PromQL en la segunda columna. Copia la consulta PromQL.

----
(1 - (avg(irate({__name__=~"node_cpu_seconds_total|windows_cpu_time_total",mode="idle"}[5m])))) * 100
----

Luego puedes modificar la consulta en el panel de Grafana o crear un nuevo panel de Grafana utilizando la consulta.

Temas relacionados:

* https://grafana.com/docs/grafana/latest/panels-visualizations/configure-panel-options/#edit-a-panel[Documentación de Grafana sobre la edición de un panel]
* https://grafana.com/docs/grafana/latest/panels-visualizations/panel-editor-overview[Documentación de Grafana sobre cómo añadir un panel a un tablero]
