= FAQ générale
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-18
:page-revdate: {revdate}
:community-path: faq/general-faq.adoc 
:product-path: faq/general-faq.adoc
ifeval::["{build-type}" != "community"]
:xref-istio: xref:observability/istio/istio.adoc
:xref-manage-clusters: xref:cluster-admin/manage-clusters/manage-clusters.adoc
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-use-windows-clusters: xref:cluster-deployment/custom-clusters/windows/use-windows-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio: xref:integrations-in-rancher/istio/index.adoc
:xref-manage-clusters: xref:how-to-guides/new-user-guides/manage-clusters/index.adoc
:xref-rancher-on-aks: xref:démarrer/installation-et-mise-à-niveau/installer-mise-à-niveau-sur-un-cluster-kubernetes/rancher-sur-aks.adoc
:xref-use-windows-clusters: xref:how-to-guides/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-configuration/utiliser-des-clusters-windows/index.adoc
endif::[]

Cette FAQ est un travail en cours conçu pour répondre aux questions les plus fréquemment posées sur Rancher v2.x.

Consultez la xref:faq/technical-items.adoc[FAQ technique] pour les questions techniques fréquemment posées.

ifeval::["{build-type}" != "srfa"]
[#_is_it_possible_to_manage_azure_kubernetes_services_with_rancher_v2_x]
== Est-il possible de gérer les services Kubernetes Azure avec Rancher v2.x{nbsp}?

Oui. Consultez notre guide {xref-manage-clusters}[Administration des clusters] pour connaître les fonctionnalités de Rancher disponibles sur AKS, ainsi que notre {xref-rancher-on-aks}[documentation sur AKS].

[#_does_rancher_support_windows]
== Rancher prend-il en charge Windows{nbsp}?

Oui. Rancher prend en charge les conteneurs Windows Server 1809. Pour des détails sur la façon de configurer un cluster avec des nœuds de travail Windows, reportez-vous à la section sur {xref-use-windows-clusters}[la configuration de clusters personnalisés pour Windows.]
endif::[]

[#_does_rancher_support_istio]
== Rancher prend-il en charge Istio{nbsp}?

Oui. Rancher prend en charge {xref-istio}[Istio].

[#_will_rancher_v2_x_support_hashicorps_vault_for_storing_secrets]
== Rancher v2.x prendra-t-il en charge Vault de Hashicorp pour le stockage des secrets{nbsp}?

La gestion des secrets est sur notre feuille de route, mais nous ne l'avons pas encore assignée à une version spécifique.

[#_does_rancher_v2_x_support_rkt_containers_as_well]
== Rancher v2.x prend-il également en charge les conteneurs RKT{nbsp}?

Pour l'instant, nous ne prenons en charge que Docker.

[#_does_rancher_v2_x_support_calico_contiv_contrail_flannel_weave_net_etc_for_embedded_and_registered_kubernetes]
== Rancher v2.x prend-il en charge Calico, Contiv, Contrail, Flannel, Weave net, etc., pour Kubernetes intégrés et enregistrés{nbsp}?

Prêt à l'emploi, Rancher fournit les fournisseurs de réseau CNI suivants pour les clusters Kubernetes{nbsp}: Canal, Flannel, Calico et Weave.  Référez-vous toujours à la https://rancher.com/support-maintenance-terms/[Matrice de support Rancher] pour des détails sur ce qui est officiellement pris en charge.

[#_are_you_planning_on_supporting_traefik_for_existing_setups]
== Prévoyez-vous de prendre en charge Traefik pour les configurations existantes{nbsp}?

Nous ne prévoyons pas actuellement de fournir un support intégré pour Traefik, mais nous explorons encore des approches d'équilibrage de la charge.

[#_can_i_import_openshift_kubernetes_clusters_into_v2_x]
== Puis-je importer des clusters Kubernetes OpenShift dans la version 2.x{nbsp}?

Notre objectif est de faire fonctionner tous les clusters Kubernetes. Par conséquent, Rancher v2.x devrait fonctionner avec OpenShift, mais nous ne l'avons pas encore testé.

[#_is_longhorn_product_name_integrated_with_rancher]
== Est-ce que {longhorn-product-name} est intégré à Rancher{nbsp}?

Oui. Longhorn est intégré à Rancher v2.5 et versions ultérieures.
