= {rancher-product-name} n'est plus nécessaire
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: faq/rancher-is-no-longer-needed.adoc 
:product-path: faq/rancher-is-no-longer-needed.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
endif::[]

Cette page est destinée à répondre aux questions sur ce qui se passe si vous ne souhaitez plus Rancher, si vous ne voulez plus qu'un cluster soit géré par Rancher, ou si le serveur Rancher est supprimé.

[#_if_the_rancher_server_is_deleted_what_happens_to_the_workloads_in_my_downstream_clusters]
== Que se passe-t-il si le serveur Rancher est supprimé, pour les charges de travail dans mes clusters en aval{nbsp}?

Si Rancher est un jour supprimé ou irrécupérable, toutes les charges de travail dans les clusters Kubernetes en aval gérés par Rancher continueront de fonctionner normalement.

[#_if_the_rancher_server_is_deleted_how_do_i_access_my_downstream_clusters]
== Si le serveur Rancher est supprimé, comment puis-je accéder à mes clusters en aval{nbsp}?

La capacité d'accéder à un cluster en aval sans Rancher dépend du type de cluster et de la manière dont le cluster a été créé. Pour résumer{nbsp}:

* *Clusters enregistrés/importés :* Le cluster ne sera pas affecté et vous pouvez accéder au cluster en utilisant les mêmes méthodes que celles que vous utilisiez avant que le cluster ne soit enregistré dans Rancher.
ifeval::["{build-type}" != "srfa"] 
* *Clusters Kubernetes hébergés :* Si vous avez créé le cluster dans un fournisseur Kubernetes hébergé dans le cloud tel qu'EKS, GKE ou AKS, vous pouvez continuer à gérer le cluster en utilisant les identifiants cloud de votre fournisseur.
endif::[]
ifeval::["{build-type}" == "srfa"]
* *Clusters Kubernetes hébergés :* Si vous avez créé le cluster dans un fournisseur Kubernetes hébergé dans le cloud tel qu'EKS, vous pouvez continuer à gérer le cluster en utilisant les identifiants cloud de votre fournisseur.
endif::[]
* *Clusters provisionnés par Rancher :* Pour accéder à un {xref-launch-k8s-with-rancher}[cluster RKE2/K3s,] le cluster doit avoir le {xref-arch-com-ds-cluster}#_4_point_de_terminaison_de_cluster_autorisé[point de terminaison de cluster autorisé] activé, et vous devez avoir déjà téléchargé le fichier kubeconfig du cluster depuis l'interface utilisateur de Rancher. (Le point de terminaison de cluster autorisé est activé par défaut pour les clusters RKE.) Avec ce point de terminaison, vous pouvez accéder à votre cluster avec kubectl directement au lieu de communiquer via le {xref-arch-com-ds-cluster}#_1_proxy_d'authentification[proxy d'authentification] du serveur Rancher. Pour des instructions sur la façon de configurer kubectl pour utiliser le point de terminaison de cluster autorisé, référez-vous à la section sur l'accès direct aux clusters avec {xref-access-cluster-kubectl}#_authentification_directe_avec_un_cluster_en_aval[kubectl et le fichier kubeconfig.] Ces clusters utiliseront un instantané de l'authentification tel qu'il a été configuré lorsque Rancher a été supprimé.

[#_what_if_i_dont_want_rancher_anymore]
== Que faire si je ne veux plus de Rancher{nbsp}?

[NOTE]
====

Les xref:[Outils système] précédemment recommandés ont cessé la prise en charge depuis juin 2022.
====


Si vous {xref-install-rancher}[avez installé Rancher sur un cluster Kubernetes,] supprimez Rancher en utilisant l'outil https://github.com/rancher/rancher-cleanup[Nettoyage de Rancher].

La désinstallation de Rancher en mode haute disponibilité (HA) supprimera également tous les `helm-operation-*` pods et les applications suivantes{nbsp}:

* Fleet
* fleet-agent
* opérateur-rancher
* rancher-webhook

Les ressources personnalisées (CRD) et les espaces de noms personnalisés devront toujours être supprimés manuellement.

Si vous avez installé Rancher avec Docker, vous pouvez désinstaller Rancher en supprimant le seul conteneur Docker dans lequel il s'exécute.

Les clusters importés ne seront pas affectés par la suppression de Rancher. Pour d'autres types de clusters, référez-vous à la section sur <<_if_the_rancher_server_is_deleted_how_do_i_access_my_downstream_clusters,l'accès aux clusters en aval lorsque Rancher est supprimé.>>

[#_what_if_i_dont_want_my_registered_cluster_managed_by_rancher]
== Que faire si je ne veux pas que mon cluster enregistré soit géré par Rancher{nbsp}?

Si un cluster enregistré est supprimé de l'interface utilisateur de Rancher, le cluster est détaché de Rancher, le laissant intact et accessible par les mêmes méthodes qui étaient utilisées pour y accéder avant son enregistrement dans Rancher.

Pour détacher le cluster,

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez au cluster enregistré qui doit être détaché de Rancher et cliquez sur *⋮ > Supprimer*.
. Cliquez sur *Supprimer*.

*Résultat :* Le cluster enregistré est détaché de Rancher et fonctionne normalement en dehors de Rancher.

[#_what_if_i_dont_want_my_hosted_kubernetes_cluster_managed_by_rancher]
== Que faire si je ne veux pas que mon cluster Kubernetes hébergé soit géré par Rancher{nbsp}?

À l'heure actuelle, il n'y a pas de fonctionnalité pour détacher ces clusters de Rancher. Dans ce contexte, "détacher" est défini comme la capacité de supprimer les composants de Rancher du cluster et de gérer l'accès au cluster indépendamment de Rancher.

La capacité de gérer ces clusters sans Rancher est suivie dans ce https://github.com/rancher/rancher/issues/25234[ticket.]

Pour des informations sur la façon d'accéder aux clusters si le serveur Rancher est supprimé, référez-vous à <<_if_the_rancher_server_is_deleted_how_do_i_access_my_downstream_clusters,cette section.>>
