= FAQ sur la sécurité
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: faq/security.adoc 
:product-path: faq/security.adoc
ifeval::["{build-type}" != "community"]
:xref-security-overview: xref:security/security-overview.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-security-overview: xref:reference-guides/rancher-security/index.adoc
endif::[]

[#_is_there_a_hardening_guide]
== Y a-t-il un guide de renforcement de la sécurité{nbsp}?

Le guide de renforcement de la sécurité se trouve dans la section principale {xref-security-overview}[Sécurité].

[#_have_hardened_rancher_kubernetes_clusters_been_evaluated_by_the_cis_kubernetes_benchmark_where_can_i_find_the_results]
== Les clusters Kubernetes Rancher renforcés au niveau de la sécurité ont-ils été évalués par le CIS Kubernetes Benchmark{nbsp}? Où puis-je trouver les résultats{nbsp}?

Nous avons exécuté le benchmark CIS Kubernetes sur un cluster Kubernetes Rancher renforcé au niveau de la sécurité.  Les résultats de cette évaluation peuvent être trouvés dans la section principale {xref-security-overview}[Sécurité].

[#_how_does_rancher_verify_communication_with_downstream_clusters_and_what_are_some_associated_security_concerns]
== Comment Rancher vérifie-t-il la communication avec les clusters en aval, et quelles sont les préoccupations de sécurité associées{nbsp}?

La communication entre le serveur Rancher et les clusters en aval se fait par le biais d'agents. Rancher utilise soit un bundle d'autorité de certification (CA) enregistré, soit le magasin de confiance local pour vérifier la communication entre les agents Rancher et le serveur Rancher. L'utilisation d'un bundle d'autorité de certification (CA) pour la vérification est plus stricte, car seuls les certificats basés sur ce bundle sont de confiance. Si la vérification TLS pour un bundle d'autorité de certification (CA) explicite échoue, Rancher peut revenir à l'utilisation du magasin de confiance local pour vérifier les communications futures. Toute CA dans le magasin de confiance local peut alors être utilisée pour générer un certificat valide.

Comme décrit dans https://www.suse.com/c/rancher-security-update/[Rancher Security Update CVE-2024-22030], dans un ensemble restreint de circonstances, des acteurs malveillants peuvent prendre le contrôle des nœuds Rancher en exploitant le comportement des CA Rancher. Pour que l'attaque réussisse, l'acteur malveillant doit générer un certificat valide à partir d'une CA valide dans le serveur Rancher ciblé, ou à partir d'une CA enregistrée valide. L'attaquant doit également soit détourner, soit usurper l'URL du serveur Rancher comme étape préliminaire. Rancher évalue actuellement le comportement des CA Rancher pour atténuer cette menace et toute voie d'attaque similaire.
