= 監査ログにおけるユーザーIDの追跡
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-27
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc 
:product-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc
ifeval::["{build-type}" != "community"]
:xref-enable-api-audit-log: xref:observability/logging/enable-api-audit-log.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-enable-api-audit-log: xref:how-to-guides/advanced-user-guides/enable-api-audit-log.adoc
endif::[]

以下の監査ログは、ローカルおよびダウンストリームクラスターで発生するイベントを追跡するためにRancherで使用されます：

* https://rancher.com/docs/rke/latest/en/config-options/audit-log/[Kubernetes監査ログ]
* {xref-enable-api-audit-log}[Rancher API監査ログ]

Rancher v2.6の監査ログは、RancherおよびダウンストリームKubernetes監査ログの両方に外部アイデンティティプロバイダー名（外部認証プロバイダーにおけるユーザーの共通名）を含むように強化されました。

v2.6以前は、Rancher管理者は、外部アイデンティティプロバイダーのユーザー名とRancherで使用されるユーザーID（`u-xXXX`）のマッピングを知らずに、Rancher監査ログからKubernetes監査ログにイベントを追跡することができませんでした。
このマッピングを知るためには、クラスター管理者はRancher API、UI、およびローカル管理クラスターへのアクセスが必要でした。

この機能により、ダウンストリームクラスター管理者はKubernetes監査ログを確認し、Rancherを表示することなく、どの特定の外部アイデンティティプロバイダー（IDP）ユーザーがアクションを実行したかを知ることができるようになります。
監査ログがクラスターから送信される場合、ログシステムのユーザーは外部アイデンティティプロバイダーシステム内のユーザーを特定できるはずです。
Rancher管理者は、外部アイデンティティプロバイダーのユーザー名を使用してRancher監査ログを表示し、Kubernetes監査ログに追跡できるようになりました。

[#_feature_description]
== 機能の説明

* ダウンストリームクラスターでKubernetes監査ログが有効になっている場合、記録される各イベントにおいて、外部アイデンティティプロバイダーのユーザー名が各リクエストの「メタデータ」レベルで記録されます。
* RancherインストールのためにRancher API監査ログを有効にすると、外部アイデンティティプロバイダーのユーザー名も、Rancher APIサーバーにヒットする各リクエスト、ログインリクエストを含めて`auditLog.level=0`で記録されるようになります。
