= Node Template Configuration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-02-26
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/node-template-configuration
:product-path:

[WARNING]
====
Rancher Kubernetes Engine (RKE/RKE1) will reach end of life on July 31, 2025. Rancher 2.12.0 and later will no longer support provisioning or managing downstream RKE1 clusters. We recommend replatforming RKE1 clusters to RKE2 to ensure continued support and security updates. Learn more about the transition https://www.suse.com/support/kb/doc/?id=000021518[here].
====

To learn about node template config, refer to xref:reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/amazon-ec2.adoc[EC2 Node Template Configuration], xref:reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/digitalocean.adoc[DigitalOcean Node Template Configuration], xref:reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/azure.adoc[Azure Node Template Configuration], xref:reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/vsphere.adoc[vSphere Node Template Configuration], and xref:reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/nutanix.adoc[Nutanix Node Template Configuration].
