= PingIdentity (SAML) konfigurieren
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: how-to-guides/neue-nutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/authentifizierung-config/configure-pingidentity.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-pingidentity.adoc

Wenn Ihre Organisation den Ping Identity Provider (IdP) zur Benutzerauthentifizierung verwendet, können Sie Rancher so konfigurieren, dass Ihre Benutzer sich mit ihren IdP-Anmeldeinformationen anmelden können.

____
*Voraussetzungen:*

* Sie müssen einen https://www.pingidentity.com/[Ping IdP-Server] konfiguriert haben.
* Nachfolgend sind die Rancher Service Provider-URLs aufgeführt, die für die Konfiguration benötigt werden:
Metadaten-URL: `\https://<rancher-server>/v1-saml/ping/saml/metadata`
Assertion Consumer Service (ACS) URL: `\https://<rancher-server>/v1-saml/ping/saml/acs`
Bitte beachten Sie, dass diese URLs keine gültigen Daten zurückgeben, bis die Authentifizierungskonfiguration in Rancher gespeichert ist.
* Exportieren Sie eine `metadata.xml` Datei von Ihrem IdP-Server. Für weitere Informationen siehe die https://documentation.pingidentity.com/pingfederate/pf83/index.shtml#concept_exportingMetadata.html[PingIdentity-Dokumentation].
____

. Klicken Sie oben links auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie im linken Navigationsmenü auf *Auth-Anbieter*.
. Klicken Sie auf *Ping Identity*.
. Füllen Sie das Formular *Ping-Konto konfigurieren* aus. Ping IdP ermöglicht es Ihnen, den gewünschten Datenspeicher anzugeben. Sie können entweder eine Datenbank hinzufügen oder einen vorhandenen LDAP-Server verwenden. Wenn Sie beispielsweise Ihren Active Directory (AD)-Server auswählen, beschreiben die folgenden Beispiele, wie Sie AD-Attribute auf Felder innerhalb von Rancher abbilden können.
 .. *Feld für Anzeigenamen*: Geben Sie das AD-Attribut ein, das den Anzeigenamen der Benutzer enthält (Beispiel: `displayName`).
 .. *Feld für Benutzernamen*: Geben Sie das AD-Attribut ein, das den Benutzernamen/Vornamen enthält (Beispiel: `givenName`).
 .. *UID-Feld*: Geben Sie ein AD-Attribut ein, das für jeden Benutzer eindeutig ist (Beispiel: `sAMAccountName`, `distinguishedName`).
 .. *Gruppenfeld*: Erstellen Sie Einträge zur Verwaltung von Gruppenmitgliedschaften (Beispiel: `memberOf`).
 .. *Entity-ID-Feld* (optional): Der veröffentlichte, protokollabhängige, eindeutige Identifikator Ihres Partners. Diese ID definiert Ihre Organisation als die Entität, die den Server für SAML 2.0-Transaktionen betreibt. Diese ID kann über einen separaten Kommunikationskanal oder mittels einer SAML-Metadatendatei erhalten worden sein.
 .. *Rancher API-Host*: Geben Sie die URL für Ihren Rancher-Server ein.
 .. *Privater Schlüssel* und *Zertifikat*: Dies ist ein Schlüssel-Zertifikat-Paar, um eine sichere Shell zwischen Rancher und Ihrem IdP zu erstellen.
+
Sie können eines mit einem openssl-Befehl generieren. Beispiel:
+
----
 openssl req -x509 -newkey rsa:2048 -keyout myservice.key -out myservice.cert -days 365 -nodes -subj "/CN=myservice.example.com"
----

 .. *IDP-Metadaten*: Die `metadata.xml` Datei, die Sie https://documentation.pingidentity.com/pingfederate/pf83/index.shtml#concept_exportingMetadata.html[von Ihrem IdP-Server exportiert haben].
. Nachdem Sie das Formular *Ping-Konto konfigurieren* ausgefüllt haben, klicken Sie auf *Aktivieren*.
+
Rancher leitet Sie zur IdP-Anmeldeseite weiter. Geben Sie Anmeldeinformationen ein, die mit dem Ping IdP authentifiziert werden, um Ihre Rancher PingIdentity-Konfiguration zu validieren.
+

[NOTE]
====
Möglicherweise müssen Sie Ihren Popup-Blocker deaktivieren, um die IdP-Anmeldeseite zu sehen.
====


*Ergebnis:* Rancher ist so konfiguriert, dass es mit PingIdentity funktioniert. Ihre Benutzer können sich jetzt mit ihren PingIdentity-Anmeldedaten bei Rancher anmelden.

[NOTE]
.SAML-Anbieter-Hinweise
====
* Benutzer und Gruppen werden nicht validiert, wenn Sie ihnen Berechtigungen in Rancher zuweisen.
* Beim Hinzufügen von Benutzern müssen die genauen Benutzer-IDs (d.h. `UID Field`) korrekt eingegeben werden. Während Sie die Benutzer-ID eingeben, wird nicht nach anderen Benutzer-IDs gesucht, die möglicherweise übereinstimmen.
* Beim Hinzufügen von Gruppen müssen Sie die Gruppe aus dem Dropdown-Menü auswählen, das neben dem Textfeld steht. Rancher geht davon aus, dass jede Eingabe im Textfeld ein Benutzer ist.
* Das Gruppen-Dropdown zeigt nur die Gruppen an, in denen Sie Mitglied sind. Wenn Sie Administratorrechte oder eingeschränkte Administratorrechte haben, können Sie einer Gruppe beitreten, in der Sie kein Mitglied sind.
====

[#_configuring_saml_single_logout_slo]
== Konfigurieren von SAML Single Logout (SLO)

include::shared:ROOT:partial$en/configure-slo.adoc[]

[#_saml_and_openldap_group_permissions]
== SAML- und OpenLDAP-Gruppenberechtigungen

include::shared:ROOT:partial$en/saml-openldap-group-permissions.adoc[]
