= GitHub konfigurieren
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-github.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-github.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
endif::[]

In Umgebungen, die GitHub verwenden, können Sie Rancher so konfigurieren, dass die Anmeldung mit GitHub-Anmeldeinformationen ermöglicht wird.

[NOTE]
.Voraussetzungen:
====

Lesen Sie {xref-authn-authz}#_external_authentication_configuration_and_principal_users[Externe Authentifizierungskonfiguration und Hauptnutzer].
====


. Melden Sie sich bei Rancher mit einem lokalen Benutzer an, dem die Rolle `administrator` zugewiesen wurde (d.h. dem _lokalen Hauptnutzer_).
. Klicken Sie in der oberen linken Ecke auf *☰ > Benutzer & Authentifizierung*.
. Klicken Sie im linken Navigationsmenü auf *Auth Provider*.
. Klicken Sie auf *GitHub*.
. Befolgen Sie die angezeigten Anweisungen, um eine GitHub-Anwendung einzurichten. Rancher leitet Sie zu GitHub weiter, um die Registrierung abzuschließen.
+

[NOTE]
.Was ist eine Autorisierungs-Callback-URL?
====
Die Autorisierungs-Callback-URL ist die URL, zu der Benutzer gehen, um Ihre Anwendung zu nutzen (d.h. der Begrüßungsbildschirm).

Wenn Sie externe Authentifizierung verwenden, findet die Authentifizierung nicht tatsächlich in Ihrer Anwendung statt. Stattdessen erfolgt die Authentifizierung extern (in diesem Fall bei GitHub). Nachdem diese externe Authentifizierung erfolgreich abgeschlossen ist, ist die Autorisierungs-Callback-URL der Ort, an dem der Benutzer wieder in Ihre Anwendung eintritt.
====


. Kopieren Sie von GitHub die *Client-ID* und das *Client-Geheimnis*. Fügen Sie sie in Rancher ein.
+

[NOTE]
.Wo finde ich die Client-ID und das Client-Geheimnis?
====
Wählen Sie in GitHub Einstellungen > Entwicklereinstellungen > OAuth-Apps. Die Client-ID und das Client-Geheimnis werden deutlich angezeigt.
====


. Klicken Sie auf *Mit GitHub authentifizieren*.
. Verwenden Sie die Optionen für den *Site-Zugriff*, um den Umfang der Benutzerautorisierung zu konfigurieren.
 ** *Erlauben Sie allen gültigen Benutzern*
+
_Jeder_ GitHub-Benutzer kann auf Rancher zugreifen. Wir raten generell von der Verwendung dieser Einstellung ab!

 ** *Erlauben Sie Mitgliedern von Clustern, Projekten sowie autorisierten Benutzern und Organisationen*
+
Jeder GitHub-Benutzer oder jede Gruppe, die als *Cluster-Mitglied* oder *Projekt-Mitglied* hinzugefügt wird, kann sich bei Rancher anmelden. Darüber hinaus kann sich jeder GitHub-Benutzer oder jede Gruppe, die Sie zur *Liste der autorisierten Benutzer und Organisationen* hinzufügen, bei Rancher anmelden.

 ** *Zugriff nur auf autorisierte Benutzer und Organisationen beschränken*
+
Nur GitHub-Benutzer oder Gruppen, die zu den autorisierten Benutzern und Organisationen hinzugefügt wurden, können sich bei Rancher anmelden.
 +
. Klicken Sie auf *Aktivieren*.

*Ergebnis:*

* Die GitHub-Authentifizierung ist konfiguriert.
* Sie sind mit Ihrem GitHub-Konto (d.h. dem _externen Hauptnutzer_) bei Rancher angemeldet.
