= JSON Web Token (JWT) Authentifizierung
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-nutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/jwt-authentifizierung.adoc 
:product-path: rancher-admin/users/authn-and-authz/jwt-authentication.adoc

Viele Drittanbieter-Integrationen für Kubernetes, wie GitLab und HashiCorp Vault, beinhalten, dass einem externen Prozess Zugriff auf die Kubernetes-API gewährt wird, wobei ein nativer Kubernetes-Service-Account-Token zur Authentifizierung verwendet wird.

In Rancher v2.9.0 und später können Service-Accounts in Downstream-Clustern sich nun über ein JSON-Web-Token (JWT) mithilfe des Rancher-Authentifizierungsproxies authentifizieren. In Rancher-Versionen vor v2.9.0 wurden nur von Rancher ausgegebene Token unterstützt.

Um diese Funktion zu aktivieren, befolgen Sie diese Schritte:

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Klicken Sie auf *Erweitert*, um das Dropdown-Menü zu öffnen.
. Wählen Sie *JWT-Authentifizierung* aus.
. Aktivieren Sie das Kontrollkästchen für den Cluster, für den Sie die JWT-Authentifizierung aktivieren möchten, und klicken Sie auf *Aktivieren*. Alternativ können Sie auf *⋮* > *Aktivieren* klicken.
