= Ativar o Istio no Cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-cluster.adoc 
:product-path: observability/istio/guides/enable-istio-in-cluster.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-cpu-memory-allocations: xref:observability/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:observability/istio/configuration/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:observability/istio/configuration/project-network-isolation.adoc
:xref-istio-config: xref:observability/istio/configuration/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-cpu-memory-allocations: xref:integrations-in-rancher/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:integrations-in-rancher/istio/configuration-options/project-network-isolation.adoc
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] foi descontinuado desde o Rancher v2.12.0; recorra à https://apps.rancher.io[SUSE Application Collection] versão do Istio para segurança aprimorada (incluída nas assinaturas do SUSE Rancher Prime).
Informações detalhadas podem ser encontradas em https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anúncio].
====

[NOTE]
.Pré-requisitos:
====

* Apenas um usuário com o `cluster-admin` https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles[papel padrão do Kubernetes] atribuído pode configurar e instalar o Istio em um cluster Kubernetes.
* Para instalar o Istio em um cluster RKE2, etapas adicionais são necessárias. Para detalhes, veja {xref-istio-on-rke2}[esta seção.]
* Para instalar o Istio em um cluster onde o isolamento de rede do projeto está ativado, etapas adicionais são necessárias. Para detalhes, veja {xref-istio-project-network-isolation}[esta seção.]
====


. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para onde você deseja ativar o Istio e clique em *Explorar*.
. Clique em *Apps*.
. Clique em *Charts*.
. Clique em *Istio*.
. Se você ainda não instalou seu próprio aplicativo de monitoramento, será solicitado que instale o aplicativo rancher-monitoring. Opcional: Defina suas opções de Selector ou Scrape na instalação do aplicativo rancher-monitoring.
. Opcional: Configure o acesso dos membros e {xref-istio-cpu-memory-allocations}[limites de recursos] para os componentes do Istio. Certifique-se de que você tem recursos suficientes em seus nós de trabalho para ativar o Istio.
. Opcional: Faça alterações de configuração adicionais no values.yaml, se necessário.
. Opcional: Adicione mais recursos ou configuração via o {xref-istio-config}#_overlay_file[arquivo de sobreposição].
. Clique em *Instalar*.

*Resultado:* O Istio está instalado no nível do cluster.

[#_additional_config_options]
== Opções de configuração adicionais

Para mais informações sobre como configurar o Istio, consulte a {xref-istio-config}[referência de configuração.]
