= Habilitar o Istio em um Namespace
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-namespace.adoc 
:product-path: observability/istio/guides/enable-istio-in-namespace.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-sidecar: xref:observability/istio/guides/use-istio-sidecar.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-sidecar: xref:how-to-guides/advanced-user-guides/istio-setup-guide/use-istio-sidecar.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] foi descontinuado desde o Rancher v2.12.0; recorra à https://apps.rancher.io[SUSE Application Collection] versão do Istio para segurança aprimorada (incluída nas assinaturas do SUSE Rancher Prime).
Informações detalhadas podem ser encontradas em https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anúncio].
====

Você precisará habilitar manualmente o Istio em cada namespace que deseja que seja monitorado ou controlado pelo Istio. Quando o Istio é habilitado em um namespace, o proxy sidecar Envoy será automaticamente injetado em todas as novas cargas de trabalho que forem implantadas no namespace.

Essa configuração de namespace afetará apenas novas cargas de trabalho no namespace. Quaisquer cargas de trabalho pré-existentes precisarão ser reimplantadas para aproveitar a injeção automática do sidecar.

[NOTE]
.Pré-requisitos:
====

Para habilitar o Istio em um namespace, o cluster deve ter o Istio instalado.
====


. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que você criou e clique em *Explorar*.
. Clique em menu:Cluster[Projetos/Namespaces].
. Vá para o namespace onde você deseja habilitar o Istio e clique em *⋮  > Habilitar Injeção Automática do Istio*. Alternativamente, clique no namespace e, em seguida, na página de detalhes do namespace, clique em *⋮  > Habilitar Injeção Automática do Istio*.

*Resultado:* O namespace agora possui o rótulo `istio-injection=enabled`. Todas as novas cargas de trabalho implantadas neste namespace terão o sidecar do Istio injetado por padrão.

[#_verifying_that_automatic_istio_sidecar_injection_is_enabled]
== Verificando se a Injeção Automática do Sidecar do Istio está Habilitada

Para verificar se o Istio está habilitado, implante uma carga de trabalho hello-world no namespace. Vá para a carga de trabalho e clique no nome do pod. Na seção *Contêineres*, você deve ver o contêiner `istio-proxy`.

[#_excluding_workloads_from_being_injected_with_the_istio_sidecar]
== Excluindo Cargas de Trabalho da Injeção com o Sidecar do Istio

Se você precisar excluir uma carga de trabalho da injeção com o sidecar do Istio, use a seguinte anotação na carga de trabalho:

----
sidecar.istio.io/inject: “false”
----

Para adicionar a anotação a uma carga de trabalho,

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que você criou e clique em *Explorar*.
. Clique em *Carga de Trabalho*.
. Vá para a carga de trabalho que não deve ter o sidecar e edite como yaml
. Adicione a seguinte chave, valor `sidecar.istio.io/inject: false` como uma anotação na carga de trabalho
. Clique em *Salvar*.

*Resultado:* O sidecar do Istio não será injetado na carga de trabalho.

[NOTE]
====

Se você estiver tendo problemas com um Job que você implantou e que não está completando, você precisará adicionar esta anotação ao seu pod usando os passos fornecidos. Como os Sidecars do Istio funcionam indefinidamente, um Job não pode ser considerado completo mesmo após a conclusão de sua tarefa.
====

[#__xref_istio_sidecar_next_add_deployments_with_the_istio_sidecar]
== {xref-istio-sidecar}[Próximo: Adicione Implantações com o Sidecar do Istio]
