= Gerar e visualizar tráfego do Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/generate-and-view-traffic.adoc 
:product-path: observability/istio/guides/generate-and-view-traffic.adoc
ifeval::["{build-type}" != "community"]
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] foi descontinuado desde o Rancher v2.12.0; recorra à https://apps.rancher.io[SUSE Application Collection] versão do Istio para segurança aprimorada (incluída nas assinaturas do SUSE Rancher Prime).
Informações detalhadas podem ser encontradas em https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anúncio].
====

[#_the_kiali_traffic_graph]
== O gráfico de tráfego do Kiali

A página de visão geral do Istio fornece um link para o painel do Kiali. A partir do painel do Kiali, você pode visualizar gráficos para cada namespace. O gráfico do Kiali oferece uma maneira poderosa de visualizar a topologia da sua malha de serviços Istio. Ele mostra quais serviços se comunicam entre si.

[#_prerequisites]
== Pré-requisitos

Para habilitar o tráfego a ser exibido no gráfico, certifique-se de que você tenha o Prometheus instalado no cluster. `Rancher-istio` instala o Kiali e o configura por padrão para trabalhar com o gráfico `rancher-monitoring`. Você pode usar `rancher-monitoring` ou instalar sua própria solução de monitoramento.

Além disso, para instalações do Istio versão `103.1.0+up1.19.6` e posteriores, o Kiali usa um valor de token para sua estratégia de autenticação. Se você estiver tentando gerar ou recuperar o token (por exemplo, para login), observe que o nome da conta de serviço do Kiali no Rancher é `kiali`. Para mais informações, consulte o https://kiali.io/docs/faq/authentication/[FAQ de autenticação de token do Kiali].

Opcional: Você pode configurar em quais namespaces ocorre a coleta de dados, definindo as opções do Helm chart descritas em {xref-selectors-and-scrape-configurations}[Seletores e Configurações de Coleta].

[#_traffic_visualization]
== Visualização de Tráfego

Para ver o gráfico de tráfego, siga os passos abaixo:

. No cluster onde o Istio está instalado, clique em *Istio* na barra de navegação à esquerda.
. Clique no link *Kiali*.
. Clique em *Gráfico* na navegação lateral.
. Altere o namespace no menu suspenso *Namespace* para visualizar o tráfego de cada namespace.

Se você atualizar a URL do aplicativo BookInfo várias vezes, deverá conseguir ver setas verdes no gráfico do Kiali mostrando o tráfego para `v1` e `v3` do serviço `reviews`. O painel de controle no lado direito do gráfico permite que você configure detalhes, incluindo quantos minutos do tráfego mais recente devem ser exibidos no gráfico.

Para ferramentas e visualizações adicionais, você pode acessar o Grafana e os painéis do Prometheus a partir da página *Monitoramento* *Visão Geral*.
