= Was ist {rancher-product-name}?
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-02-05
:page-revdate: {revdate}
:community-path: rancher-manager.adoc 
:product-path: about-rancher/what-is-rancher.adoc
:description: Rancher bietet einen erheblichen Mehrwert gegenüber Kubernetes: die Verwaltung von Hunderte von Clustern über eine einzige Schnittstelle, die Zentralisierung von RBAC sowie die Ermöglichung von Überwachung und Alarmierung. Weitere Informationen
:sidebar_label: Was ist Rancher?
:slug: /

Rancher ist ein Kubernetes-Management-Tool zum Bereitstellen und Ausführen von Clustern überall und bei jedem Anbieter.

Rancher kann Kubernetes von einem gehosteten Anbieter bereitstellen, Rechenknoten bereitstellen und anschließend Kubernetes darauf installieren oder vorhandene Kubernetes-Cluster importieren, die an beliebigen Standorten ausgeführt werden.

Rancher bietet einen erheblichen Mehrwert gegenüber Kubernetes, indem es zunächst die Authentifizierung und die rollenbasierte Zugriffskontrolle (RBAC) für alle Cluster zentralisiert und globalen Administratoren die Möglichkeit gibt, den Cluster-Zugriff von einem Standort aus zu steuern.

Es ermöglicht dann eine detaillierte Überwachung und Alarmierung für Cluster und deren Ressourcen, übermittelt Protokolle an externe Anbieter und lässt sich über den Anwendungskatalog direkt in Helm integrieren. Wenn Sie ein externes CI/CD-System haben, können Sie es in Rancher integrieren, aber wenn nicht, enthält Rancher sogar Fleet, um Ihnen zu helfen, Workloads automatisch bereitzustellen und zu upgraden.

Rancher ist eine _umfassende_ Container-Management-Plattform für Kubernetes, die Ihnen die Werkzeuge zur Verfügung stellt, um Kubernetes überall erfolgreich zu betreiben.
