= Configurando la contraseña de iniciar
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/bootstrap-password.adoc 
:product-path: installation-and-upgrade/resources/bootstrap-password.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-users-and-groups: xref:rancher-admin/users/authn-and-authz/manage-users-and-groups.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-users-and-groups: xref:instrucciones/nuevas-guías-de-usuario/permisos-de-autenticación-y-configuración-global/configuración-de-autenticación/gestionar-usuarios-y-grupos.adoc
endif::[]

Cuando instalas Rancher, puedes establecer una contraseña de iniciar para la primera cuenta de administrador.

Si decides no establecer una contraseña de iniciar, Rancher genera aleatoriamente una contraseña de iniciar para la primera cuenta de administrador.

Para detalles sobre cómo establecer la contraseña de inicio, consulta a continuación.

[#_password_requirements]
== Requisitos de la contraseña

La contraseña de inicio puede tener cualquier longitud.

Cuando restablezcas la contraseña de la primera cuenta de administrador después del primer inicio de sesión, la nueva contraseña debe tener al menos 12 caracteres de longitud.

Puedes {xref-users-and-groups}#_minimum_password_length[personalizar la longitud mínima de la contraseña] para las cuentas de usuario, dentro de las limitaciones.

La longitud mínima de la contraseña puede ser cualquier valor entero positivo entre 2 y 256. No se permiten valores decimales ni ceros a la izquierda.

[#_specifying_the_bootstrap_password]
== Especificando la contraseña de iniciar

Durante {xref-install-rancher}[la instalación de Rancher], establece `bootstrapPassword` junto con cualquier otra bandera para el gráfico Helm de Rancher. Por ejemplo:

[,bash]
----
helm install rancher rancher-<chart-repo>/rancher \
  --set bootstrapPassword=<password>
----

## Recuperando la contraseña de iniciar

La contraseña de iniciar se almacena en los registros del contenedor de Docker. Una vez que Rancher esté instalado, la GUI muestra instrucciones sobre cómo recuperar la contraseña según tu método de instalación. 

[,bash]
----
kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{ .data.bootstrapPassword|base64decode}}{{ "\n" }}'
----
