= Acerca de los certificados CA raíz personalizados
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/custom-ca-root-certificates.adoc 
:product-path: installation-and-upgrade/resources/custom-ca-root-certificates.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
endif::[]

Si utilizáis Rancher en un entorno de producción interno donde no exponéis apps públicamente, utilizad un certificado de una autoridad certificadora (CA) privada.

Los servicios a los que Rancher necesita acceder a veces están configurados con un certificado de una CA raíz personalizada o interna, también conocido como certificado autofirmado. Si el certificado presentado por el servicio no puede ser validado por Rancher, se muestra el siguiente error: `x509: certificate signed by unknown authority`.

Para validar el certificado, es necesario añadir los certificados CA raíz a Rancher. Como Rancher está escrito en Go, podemos utilizar la variable de entorno `SSL_CERT_DIR` para señalar el directorio donde se encuentran los certificados CA raíz en el contenedor. El directorio de certificados CA raíz se puede montar utilizando la opción de volumen de Docker (`-v host-source-directory:container-destination-directory`) al iniciar el contenedor de Rancher.

Ejemplos de servicios a los que Rancher puede acceder:

* Catálogos
* Proveedores de autenticación
* Accediendo a la API de hosting/nube al utilizar controladores de nodo

[#_installing_with_the_custom_ca_certificate]
== Instalando con el certificado CA personalizado

Para obtener detalles sobre cómo iniciar un contenedor de Rancher con vuestros certificados CA privados montados, consultad la documentación de instalación:

* {xref-helm-chart-options}#_additional_trusted_cas[Opciones de instalación de Kubernetes para CA adicionales de confianza]
