= インストール要件
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:product-path: installation-and-upgrade/requirements/requirements.adoc
:description: RancherをKubernetesセットアップで実行するように構成する際の各ノードの要件について学びます。
ifeval::["{build-type}" != "community"]
:url-k3s-advanced-docker-runtime: https://documentation.suse.com/cloudnative/k3s/latest/en/advanced.html#_using_docker_as_the_container_runtime
:url-rke2-requirements: https://documentation.suse.com/cloudnative/rke2/latest/en/install/requirements.html
:url-k3s-datastore: https://documentation.suse.com/cloudnative/k3s/latest/en/datastore/datastore.html
:url-k3s-requirements: https://documentation.suse.com/cloudnative/k3s/latest/en/installation/requirements.html
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
:xref-psact: xref:security/psact.adoc
:xref-rancher-on-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
:xref-tuning-rancher-at-scale: xref:installation-and-upgrade/best-practices/tuning-rancher-at-scale.adoc
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-rancher-on-arm64: xref:rancher-admin/experimental-features/rancher-on-arm64.adoc
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc
:xref-dual-stack: xref:cluster-deployment/dual-stack.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-advanced-docker-runtime: https://docs.k3s.io/advanced#using-docker-as-the-container-runtime
:url-rke2-requirements: https://docs.rke2.io/install/requirements
:url-k3s-datastore: https://docs.k3s.io/datastore
:url-k3s-requirements: https://docs.k3s.io/installation/requirements
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/rancher管理クラスターのノード要件.adoc
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-rancher-on-aks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-aks.adoc
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
:xref-psact: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates.adoc
:xref-rancher-on-eks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks.adoc
:xref-tuning-rancher-at-scale: xref:reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.adoc
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-rancher-on-arm64: xref:how-to-guides/advanced-user-guides/enable-experimental-features/rancher-on-arm64.adoc
:xref-rancher-on-gke: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke.adoc
:xref-dual-stack: xref:reference-guides/dual-stack.adoc
endif::[]

このページでは、Rancherサーバーがインストールされるノードのソフトウェア、ハードウェア、およびネットワーキング要件について説明します。Rancherサーバーは、単一ノードまたは高可用性のKubernetesクラスターにインストールできます。

[NOTE]
.重要:
====

KubernetesクラスターにRancherをインストールする場合、要件は{xref-node-reqs}[ダウンストリームユーザークラスターのノード要件]とは異なります。これらのクラスターは、アプリやサービスを実行します。
====


Rancher UIは、FirefoxまたはChromiumベースのブラウザ（Chrome、Edge、Opera、Braveなど）で最適に動作します。

本番環境でRancherサーバーを実行するための推奨事項のリストについては、{xref-tips-for-running-rancher}[ベストプラクティス]のページをご覧ください。

[#_kubernetes_compatibility_with_rancher]
== RancherとのKubernetesの互換性

Rancherは、サポートされているKubernetesバージョンにインストールする必要があります。意図したKubernetesのバージョンがサポートされていることを確認するには、 https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancherサポートマトリックス]を参照してください。

バージョンや配布に関係なく、Kubernetesクラスターは、Rancherが使用するxref:api/extension-apiserver.adoc[拡張API]をサポートするために、集約APIレイヤーが適切に構成されている必要があります。

[#_install_rancher_on_a_hardened_kubernetes_cluster]
=== ハードニングされたKubernetesクラスターにRancherをインストールする

ハードニングされたKubernetesクラスターにRancherをインストールする場合は、詳細な要件について{xref-psact}#_exempting_required_rancher_namespaces[必要なRancher名前空間の除外]セクションを確認してください。

[#_install_rancher_on_an_ipv6_only_or_dual_stack_kubernetes_cluster]
=== IPv6専用またはデュアルスタックKubernetesクラスターにRancherをインストールする

IPv6専用またはデュアルスタックKubernetesクラスターにRancherをデプロイできます。

RancherのIPv6専用およびデュアルスタックサポートの詳細については、{xref-dual-stack}[IPv4/IPv6デュアルスタック]ページをご覧ください。

[#_operating_systems_and_container_runtime_requirements]
== オペレーティングシステムとコンテナランタイムの要件

すべてのサポートされているオペレーティングシステムは64ビットx86です。Rancherは、最新のLinux配布パッケージで動作するはずです。

https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancherサポートマトリックス]には、各RancherバージョンでテストされたOSおよびDockerバージョンが一覧表示されています。

RKEクラスターを実行するノードにはDockerが必要です。RKE2またはK3sクラスターには必要ありません。

`ntp`（ネットワークタイムプロトコル）パッケージをインストールする必要があります。これにより、クライアントとサーバー間で時間が同期されていない場合に発生する可能性のある証明書検証エラーを防ぎます。

一部のLinuxディストリビューションには、Kubernetesクラスター内の通信をブロックするデフォルトのファイアウォールルールがある場合があります。Kubernetes v1.19以降、firewalldはKubernetesのネットワークプラグインと競合するため、無効にする必要があります。

もしそれを行うことに不安がある場合は、 https://github.com/rancher/rancher/issues/28840[該当する問題]の提案を確認することをお勧めします。 https://github.com/rancher/rancher/issues/28840#issuecomment-787404822[Pod CIDRに対してACCEPTポリシーを持つ別のfirewalldゾーンを作成することに成功したユーザーもいます。]

RancherをARM64で実行する予定がある場合は、{xref-rancher-on-arm64}[ARM64での実行（実験的）]を参照してください。

[#__rke2_product_name_specific_requirements]
=== {rke2-product-name}特定の要件

RKE2は独自のコンテナランタイムであるcontainerdをバンドルしています。

RKE2でテストされたOSバージョンの詳細については、 https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancherサポートマトリックス]を参照してください。

[#__k3s_product_name_specific_requirements]
=== {k3s-product-name}特定の要件

K3sはデフォルトで独自のcontainerdをバンドルしています。また、K3sを既にインストールされているDockerランタイムを使用するように構成することもできます。DockerとK3sを使用する際の詳細については、{url-k3s-advanced-docker-runtime}[K3sドキュメント]を参照してください。

Rancherは、サポートされているKubernetesバージョンにインストールする必要があります。ご利用のRancherバージョンに対してサポートされているKubernetesのバージョンを確認するには、 https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancherサポートマトリックス]を参照してください。K3sバージョンを指定するには、K3sインストールスクリプトを実行する際にINSTALL_K3S_VERSION環境変数を使用します。

*Raspbian Buster*を使用したK3sクラスターにRancherをインストールする場合は、レガシーiptablesに切り替えるために https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster[これらの手順]に従ってください。

Alpine Linuxを使用したK3sクラスターにRancherをインストールする場合は、追加のセットアップのために https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup[これらの手順]に従ってください。

[#_hardware_requirements]
== ハードウェア要件

以下のセクションでは、RancherがインストールされているノードのCPU、メモリ、およびI/O要件について説明します。要件は、インフラストラクチャの規模に基づいて異なります。

[#_practical_considerations]
=== 実用的な考慮事項

Rancherのハードウェアフットプリントは、以下を含むいくつかの要因に依存します：

* 管理されるインフラストラクチャのサイズ（例：ノード数、クラスター数）。
* 必要なアクセス制御ルールの複雑さ（例：`RoleBinding`オブジェクト数）。
* ワークロードの数（例：Kubernetesデプロイメント、Fleetデプロイメント）。
* 使用パターン（例：積極的に使用される機能のサブセット、使用頻度、同時ユーザー数）。

影響を与える要因が多く、時間とともに変化する可能性があるため、ここに示されている要件は、ほとんどのユースケースに適した合理的な出発点として理解されるべきです。それにもかかわらず、あなたのユースケースには異なる要件があるかもしれません。特定のシナリオに関するお問い合わせは、さらなるガイダンスを得るために https://rancher.com/contact/[Rancherに連絡してください]。

特に、このページの要件は、以下を含む典型的な使用の仮定に基づいています：

* タイプごとに60,000未満のKubernetesリソース。
* ノードごとに最大120ポッド。
* アップストリーム（ローカルクラスタ）に最大200のCRD。
* ダウンストリームクラスタに最大100のCRD。
* 最大50のFleetデプロイメント。

より高い数も可能ですが、要件が高くなる可能性があります。同じタイプのリソースが20,000を超える場合、Rancher UIを通じて全リストの読み込み時間が数秒かかることがあります。

[NOTE]
.Evolution:
====

Rancherのコードベースは進化し、ユースケースは変化し、蓄積されたRancherの経験は日々増加しています。

ハードウェア要件の推奨は、ガイドラインが精度を向上させ、より具体的になるにつれて、時間とともに変更される可能性があります。

Rancherのデプロイメントがリストされた推奨事項に従わなくなった場合は、 https://rancher.com/contact/[Rancherに連絡する]ことをお勧めします。
====


[#__rke2_product_name_kubernetes]
=== {rke2-product-name} Kubernetes

以下の表は、{xref-install-rancher}[アップストリームクラスター]内の各ノードに対する最小CPUおよびメモリ要件を示しています。

本番環境には、少なくとも3ノードの高可用性セットアップが必要であることに注意してください。

|===
| 管理されたインフラストラクチャのサイズ | 最大クラスター数 | 最大ノード数 | vCPUs | RAM

| 小規模
| 150
| 1500
| 4
| 16GB

| 中
| 300
| 3000
| 8
| 32GB

| 大規模 (*)
| 500
| 5000
| 16
| 64GB

| 大きい (†)
| (†)
| (†)
| (†)
| (†)
|===

(*):大規模なデプロイメントでは、適切なパフォーマンスのために{xref-tuning-rancher-at-scale}[ベストプラクティスに従う]必要があります。

(†):大規模なデプロイメントサイズは、一般的にアドホックなハードウェア推奨と調整によって可能です。カスタム評価のために https://rancher.com/contact/[Rancherに連絡する]ことができます。

{url-rke2-requirements}[RKE2の一般要件]に関する詳細情報は、RKE2のドキュメントを参照してください。

[#__k3s_product_name_kubernetes]
=== {k3s-product-name} Kubernetes

以下の表は、{xref-install-rancher}[アップストリームクラスター]内の各ノードに対する最小CPUおよびメモリ要件を示しています。

本番環境には、少なくとも3ノードの高可用性セットアップが必要であることに注意してください。

|===
| 管理されたインフラストラクチャのサイズ | 最大クラスター数 | 最大ノード数 | vCPUs | RAM | 外部データベースホスト (*)

| 小規模
| 150
| 1500
| 4
| 16GB
| 2 vCPU、8 GB + 1000 IOPS

| 中
| 300
| 3000
| 8
| 32GB
| 4 vCPU、16 GB + 2000 IOPS

| 大規模 (†)
| 500
| 5000
| 16
| 64GB
| 8 vCPU、32 GB + 4000 IOPS
|===

(*):外部データベースホストは、K3sクラスターのデータストアを{url-k3s-datastore}[専用の外部ホスト]にホスティングすることを指します。これは必要な場合のみ指定してください。正確な要件は外部データストアによって異なります。

(†):大規模なデプロイメントでは、適切なパフォーマンスのために{xref-tuning-rancher-at-scale}[ベストプラクティスに従う]必要があります。

{url-k3s-requirements}[一般的な要件]に関する詳細情報については、K3sのドキュメントを参照してください。

[#_hosted_kubernetes]
=== ホステッドKubernetes

以下の表は、{xref-install-rancher}[アップストリームクラスター]内の各ノードに対する最小CPUおよびメモリ要件を示しています。

本番環境には、少なくとも3ノードの高可用性セットアップが必要であることに注意してください。

これらの要件は、Amazon Elastic Kubernetes Service (EKS)、Azure Kubernetes Service (AKS)、またはGoogle Kubernetes Engine (GKE)などのホステッドKubernetesクラスターに適用されます。これらは、 https://www.rancher.com/products/rancher[Rancher Prime Hosted]のようなRancher SaaSソリューションには適用されません。

|===
| 管理されたインフラストラクチャのサイズ | 最大クラスター数 | 最大ノード数 | vCPUs | RAM

| 小規模
| 150
| 1500
| 4
| 16GB

| 中
| 300
| 3000
| 8
| 32GB

| 大規模 (*)
| 500
| 5000
| 16
| 64GB
|===

(*):大規模なデプロイメントでは、適切なパフォーマンスのために{xref-tuning-rancher-at-scale}[ベストプラクティスに従う]必要があります。

ifeval::["{build-type}" == "community"]

[#_docker]
=== Docker

以下の表は、xref:[Rancherの単一Dockerノードインストール]の最小CPUおよびメモリ要件を示しています。

Dockerのインストールは、開発またはテスト目的にのみ適しており、本番環境での使用を目的としていません。

|===
| 管理されたインフラストラクチャのサイズ | 最大クラスター数 | 最大ノード数 | vCPUs | RAM

| 小規模
| 5
| 50
| 1
| 4GB

| 中
| 15
| 200
| 2
| 8GB
|===

endif::[]

[#_ingress]
== Ingress

RancherがインストールされているKubernetesクラスターの各ノードは、Ingressを実行する必要があります。

IngressはDaemonSetとしてデプロイする必要があり、これによりロードバランサーがすべてのノードにトラフィックを正常にルーティングできるようになります。

RKE2およびK3sのインストールでは、Ingressはデフォルトでインストールされるため、手動でインストールする必要はありません。

ホステッドKubernetesクラスター（EKS、GKE、AKS）では、Ingressをセットアップする必要があります。

* *Amazon EKS:*Amazon EKSにRancherをインストールする方法の詳細、RancherサーバーにアクセスできるようにするためのIngressのインストール方法については、{xref-rancher-on-eks}[このページ]を参照してください。
* *AKS:*Azure Kubernetes ServiceでRancherをインストールする方法の詳細、RancherサーバーにアクセスできるようにするためのIngressのインストール方法については、{xref-rancher-on-aks}[このページ]を参照してください。
* *GKE:*Google Kubernetes EngineでRancherをインストールする方法の詳細、RancherサーバーにアクセスできるようにするためのIngressのインストール方法については、{xref-rancher-on-gke}[このページ]を参照してください。

[#_disks]
== ディスク

Rancherのパフォーマンスは、クラスター内のetcdのパフォーマンスに依存します。最適な速度を確保するために、Rancher管理Kubernetesクラスターのストレージには常にSSDディスクを使用することをお勧めします。クラウドプロバイダーでは、最大IOPSを許可する最小サイズを使用することをお勧めします。大規模なクラスターでは、etcdデータおよびwalディレクトリ用に専用のストレージデバイスを使用することを検討してください。

[#_networking_requirements]
== ネットワーキング要件

このセクションでは、Rancherサーバーがインストールされているノードのネットワーキング要件について説明します。

[CAUTION]
====

Rancherを含むサーバーに`X-Frame-Options=DENY`ヘッダーがある場合、レガシーUIから新しいRancher UIにアップグレードした後、一部のページがレンダリングできなくなります。これは、一部のレガシーページが新しいUIにiFrameとして埋め込まれているためです。
====


[#_node_ip_addresses]
=== ノードのIPアドレス

使用する各ノードには、Rancherを単一ノードまたはHAクラスターにインストールするかどうかにかかわらず、静的IPが設定されている必要があります。DHCPの場合、各ノードにはDHCP予約が必要で、ノードが同じIPを割り当てられることを確認します。

[#_port_requirements]
=== ポートの要件

Rancherが適切に動作するためには、RancherノードおよびダウンストリームのKubernetesクラスターのノードでいくつかのポートが開いている必要があります。{xref-port-reqs}[ポート要件]では、さまざまなクラスタータイプのRancherおよびダウンストリームクラスターに必要なすべてのポートをリストしています。

[#_load_balancer_requirements]
=== ロードバランサー要件

ロードバランサーを使用する場合、HTTP/2に対応している必要があります。

SUSEサポートからの支援を受けるために、ロードバランサー（またはファイアウォールなどの他のミドルボックス）を使用するRancher Primeの顧客は、HTTP/2に対応したものを使用する必要があります。

HTTP/2が利用できない場合、RancherはHTTP/1.1にフォールバックします。ただし、HTTP/2はウェブアプリケーションのパフォーマンスを向上させるため、HTTP/1.1を使用するとパフォーマンスの問題が発生する可能性があります。
