= Activer Istio dans le cluster.
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-cluster.adoc 
:product-path: observability/istio/guides/enable-istio-in-cluster.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-cpu-memory-allocations: xref:observability/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:observability/istio/configuration/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:observability/istio/configuration/project-network-isolation.adoc
:xref-istio-config: xref:observability/istio/configuration/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-cpu-memory-allocations: xref:integrations-in-rancher/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:integrations-in-rancher/istio/configuration-options/project-network-isolation.adoc
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] a cessé la prise en charge depuis Rancher v2.12.0{nbsp}; tournez-vous vers l'https://apps.rancher.io[SUSE Application Collection] d'Istio pour une sécurité renforcée (incluse dans les abonnements SUSE Rancher Prime).
Des informations détaillées peuvent être trouvées dans https://forums.suse.com/t/deprecation-of-rancher-istio/45043[cette annonce].
====

[NOTE]
.Conditions préalables :
====

* Seul un utilisateur avec le `cluster-admin` https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles[rôle par défaut Kubernetes] attribué peut configurer et installer Istio dans un cluster Kubernetes.
* Pour installer Istio sur un cluster RKE2, des étapes supplémentaires sont nécessaires. Pour plus de détails, voir {xref-istio-on-rke2}[cette section.]
* Pour installer Istio dans un cluster où l'isolation du réseau de projet est activée, des étapes supplémentaires sont nécessaires. Pour plus de détails, voir {xref-istio-project-network-isolation}[cette section.]
====


. Cliquez sur *☰ > Gestion des clusters*.
. Allez à l'endroit où vous souhaitez activer Istio et cliquez sur *Explorer*.
. Cliquez sur *Applications*.
. Cliquez sur *Graphiques*.
. Cliquez sur *Istio*.
. Si vous n'avez pas encore installé votre propre appli de surveillance, vous serez invité à installer l'appli rancher-monitoring. Facultatives : Définissez vos options de configuration pour Selector ou Scrape lors de l'installation de l'appli rancher-monitoring.
. Facultatives : Configurez l'accès des membres et {xref-istio-cpu-memory-allocations}[limites de ressources] pour les composants Istio. Assurez-vous d'avoir suffisamment de ressources sur vos nœuds de travail pour activer Istio.
. Facultatives : Apportez des modifications de configuration supplémentaires à values.yaml si nécessaire.
. Facultatives : Ajoutez d'autres ressources ou configurations via le {xref-istio-config}#_overlay_file[fichier de superposition].
. Cliquez sur *Installer*.

*Résultat :* Istio est installé au niveau du cluster.

[#_additional_config_options]
== Options de configuration supplémentaires

Pour plus d'informations sur la configuration d'Istio, reportez-vous à la {xref-istio-config}[référence de configuration.]
