= Générer et afficher le trafic depuis Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/generate-and-view-traffic.adoc 
:product-path: observability/istio/guides/generate-and-view-traffic.adoc
ifeval::["{build-type}" != "community"]
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] a cessé la prise en charge depuis Rancher v2.12.0{nbsp}; tournez-vous vers l'https://apps.rancher.io[SUSE Application Collection] d'Istio pour une sécurité renforcée (incluse dans les abonnements SUSE Rancher Prime).
Des informations détaillées peuvent être trouvées dans https://forums.suse.com/t/deprecation-of-rancher-istio/45043[cette annonce].
====

[#_the_kiali_traffic_graph]
== Le graphique de trafic Kiali

La page d'aperçu d'Istio fournit un lien vers le tableau de bord Kiali. Depuis le tableau de bord Kiali, vous pouvez voir des graphiques pour chaque espace de noms. Le graphique Kiali offre un moyen puissant de visualiser la topologie de votre maillage de services Istio. Il vous montre quels services communiquent entre eux.

[#_prerequisites]
== Conditions préalables

Pour que le trafic apparaisse dans le graphique, assurez-vous que vous avez installé Prometheus dans le cluster. `Rancher-istio` installe Kiali et le configure par défaut pour fonctionner avec le `rancher-monitoring` graphique. Vous pouvez utiliser `rancher-monitoring` ou installer votre propre solution de surveillance.

De plus, pour les installations d'Istio version `103.1.0+up1.19.6` et ultérieures, Kiali utilise une valeur de token pour sa stratégie d'authentification. Si vous essayez de générer ou de récupérer le token (par exemple pour vous connecter), notez que le nom du compte de service Kiali dans Rancher est `kiali`. Pour plus d'informations, consultez le https://kiali.io/docs/faq/authentication/[FAQ sur l'authentification par token Kiali].

Facultatives : Vous pouvez configurer les espaces de noms dans lesquels la collecte des données a lieu en définissant les options de configuration Helm décrites dans {xref-selectors-and-scrape-configurations}[Sélecteurs et configurations de collecte].

[#_traffic_visualization]
== Visualisation du trafic

Pour voir le graphique de trafic, suivez les étapes ci-dessous{nbsp}:

. Dans le cluster où Istio est installé, cliquez sur *Istio* dans la barre de navigation à gauche.
. Cliquez sur le lien *Kiali*.
. Cliquez sur *Graphique* dans la navigation latérale.
. Changez l'espace de noms dans le menu déroulant *Espace de noms* pour voir le trafic pour chaque espace de noms.

Si vous actualisez l'URL de l'application BookInfo plusieurs fois, vous devriez pouvoir voir des flèches vertes sur le graphique Kiali montrant le trafic vers `v1` et `v3` du service `reviews`. Le panneau de contrôle sur le côté droit du graphique vous permet de configurer des détails, y compris combien de minutes du trafic le plus récent doivent être affichées sur le graphique.

Pour des outils et visualisations supplémentaires, vous pouvez aller aux tableaux de bord Grafana et Prometheus depuis la page *Monitoring* *Overview*.
