= Guides de configuration d'Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/index.adoc 
:product-path: observability/istio/guides/guides.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-istio-traffic-management-setup: xref:observability/istio/guides/set-up-traffic-management.adoc
:xref-istio-gateway-setup: xref:observability/istio/guides/set-up-istio-gateway.adoc
:xref-istio-cpu-memory-allocations: xref:observability/istio/cpu-and-memory-allocations.adoc
:xref-istio-sidecar: xref:observability/istio/guides/use-istio-sidecar.adoc
:xref-istio-generate-and-view-traffic: xref:observability/istio/guides/generate-and-view-traffic.adoc
:xref-enable-istio-in-namespace: xref:observability/istio/guides/enable-istio-in-namespace.adoc
:xref-enable-istio-in-cluster: xref:observability/istio/guides/enable-istio-in-cluster.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-istio-traffic-management-setup: xref:how-to-guides/advanced-user-guides/istio-setup-guide/set-up-traffic-management.adoc
:xref-istio-gateway-setup: xref:how-to-guides/advanced-user-guides/istio-setup-guide/set-up-istio-gateway.adoc
:xref-istio-cpu-memory-allocations: xref:integrations-in-rancher/istio/cpu-and-memory-allocations.adoc
:xref-istio-sidecar: xref:how-to-guides/advanced-user-guides/istio-setup-guide/use-istio-sidecar.adoc
:xref-istio-generate-and-view-traffic: xref:how-to-guides/advanced-user-guides/istio-setup-guide/generate-and-view-traffic.adoc
:xref-enable-istio-in-namespace: xref:how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-namespace.adoc
:xref-enable-istio-in-cluster: xref:how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-cluster.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] a cessé la prise en charge depuis Rancher v2.12.0{nbsp}; tournez-vous vers la https://apps.rancher.io[SUSE Application Collection] d'Istio pour une sécurité renforcée (incluse dans les abonnements SUSE Rancher Prime).
Des informations détaillées peuvent être trouvées dans https://forums.suse.com/t/deprecation-of-rancher-istio/45043[cette annonce].
====

Cette section décrit comment activer Istio et commencer à l'utiliser dans vos projets.

Si vous utilisez Istio pour la gestion du trafic, vous devrez autoriser le trafic externe vers le cluster. Dans ce cas, vous devrez suivre toutes les étapes ci-dessous.

[#_prerequisites]
== Conditions préalables

Ce guide suppose que vous avez déjà {xref-install-upgrade}[installé Rancher,] et que vous avez déjà {xref-cluster-deployment}[provisionné un cluster Kubernetes séparé] sur lequel vous installerez Istio.

Les nœuds de votre cluster doivent répondre aux {xref-istio-cpu-memory-allocations}exigences en matière d'UC et de mémoire.

Les charges de travail et les services que vous souhaitez contrôler par Istio doivent répondre à https://istio.io/docs/setup/additional-setup/requirements/[les exigences d'Istio.]

[#_install]
== Installez

[TIP]
.Astuce de configuration rapide{nbsp}:
====

Si vous n'avez pas besoin que le trafic externe atteigne Istio, et que vous souhaitez simplement configurer Istio pour surveiller et tracer le trafic au sein du cluster, sautez les étapes pour {xref-istio-gateway-setup}[configurer la passerelle Istio] et {xref-istio-traffic-management-setup}[configurer les composants d'Istio pour la gestion du trafic.]
====


. {xref-enable-istio-in-cluster}[Activer Istio dans le cluster.]
. {xref-enable-istio-in-namespace}[Activer Istio dans tous les espaces de noms où vous souhaitez l'utiliser.]
. {xref-istio-sidecar}[Ajouter des déploiements et des services qui ont le sidecar Istio injecté.]
. {xref-istio-gateway-setup}[Configurer la passerelle Istio.]
. {xref-istio-traffic-management-setup}[Configurer les composants d'Istio pour la gestion du trafic.]
. {xref-istio-generate-and-view-traffic}[Générer du trafic et voir Istio en action.]
