= 设置指南

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] will be deprecated in Rancher v2.12.0; turn to the https://apps.rancher.io[SUSE Application Collection] build of Istio for enhanced security (included in SUSE Rancher Prime subscriptions).
Detailed information can be found in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[this announcement]
====

本文介绍如何启用 Istio 并在你的项目中使用它。

如果你使用 Istio 进行流量管理，则需要允许外部流量进入集群。在这种情况下，你将需要执行以下所有步骤。

== 先决条件

本指南假设你已经xref:installation-and-upgrade/installation-and-upgrade.adoc[安装 Rancher]，且已经xref:cluster-deployment/cluster-deployment.adoc[配置了一个单独的 Kubernetes 集群]并要在该集群上安装 Istio。

集群中的节点必须满足 xref:observability/istio/cpu-and-memory-allocations.adoc[CPU 和内存要求]。

Istio 控制的工作负载和服务必须满足 https://istio.io/docs/setup/additional-setup/requirements/[Istio 要求]。

== 安装

[TIP]
.快速设置提示:
====

如果你不需要外部流量到达 Istio，而只想设置 Istio 以监控和跟踪集群内的流量，请跳过xref:observability/istio/guides/set-up-istio-gateway.adoc[设置 Istio Gateway]和xref:observability/istio/guides/set-up-traffic-management.adoc[设置 Istio 的流量管理组件]步骤。
====


. xref:observability/istio/guides/enable-istio-in-cluster.adoc[在集群中启用 Istio。]
. xref:observability/istio/guides/enable-istio-in-namespace.adoc[在命名空间中启用 Istio。]
. xref:observability/istio/guides/use-istio-sidecar.adoc[使用 Istio Sidecar 添加部署和服务。]
. xref:observability/istio/guides/set-up-istio-gateway.adoc[设置 Istio Gateway。]
. xref:observability/istio/guides/set-up-traffic-management.adoc[设置 Istio 的流量管理组件。]
. xref:observability/istio/guides/generate-and-view-traffic.adoc[生成和查看流量。]
