= kubectl Utility
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cli-with-rancher/kubectl-utility.adoc 
:product-path: rancher-admin/cli/kubectl.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
endif::[]

[#_kubectl]
== kubectl

Interagieren Sie mit Rancher über kubectl.

[#_kubectl_utility]
=== kubectl Utility

Installieren Sie das Dienstprogramm `kubectl`. Siehe https://kubernetes.io/docs/tasks/tools/install-kubectl/[install kubectl].

Konfigurieren Sie kubectl, indem Sie Ihren Cluster in der Rancher-Weboberfläche besuchen, auf `Kubeconfig` klicken, den Inhalt kopieren und in die Datei `~/.kube/config` einfügen.

Führen Sie `kubectl cluster-info` oder `kubectl get pods` erfolgreich aus.

[#_authentication_with_kubectl_and_kubeconfig_tokens_with_ttl]
=== Authentifizierung mit kubectl und kubeconfig-Token mit TTL

_Anforderungen_

Wenn Administratoren xref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[die kubeconfig-Token-Generierung deaktiviert haben], erfordert die kubeconfig-Datei, dass die {xref-rancher-cli}[Rancher-Kommandozeilenschnittstelle] in Ihrem PATH vorhanden ist, wenn Sie `kubectl` ausführen. Andernfalls sehen Sie einen Fehler wie:
`Unable to connect to the server: getting credentials: exec: exec: "rancher": executable file not found in $PATH`.

Dieses Feature ermöglicht es kubectl, sich beim Rancher-Server zu authentifizieren und bei Bedarf ein neues kubeconfig-Token zu erhalten. Die folgenden Auth-Anbieter werden derzeit unterstützt:

. Lokal
. Active Directory (nur LDAP)
. FreeIPA
. OpenLDAP
. SAML-Anbieter: Ping, Okta, ADFS, Keycloak, Shibboleth
. Azure AD

Wenn Sie kubectl zum ersten Mal ausführen, zum Beispiel `kubectl get pods`, werden Sie aufgefordert, einen Auth-Anbieter auszuwählen und sich beim Rancher-Server anzumelden. Das kubeconfig-Token wird im Pfad, in dem Sie kubectl ausführen, unter `./.cache/token` zwischengespeichert. Dieses Token ist gültig, bis xref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[es abläuft] oder xref:api/api-tokens.adoc#_deleting_tokens[vom Rancher-Server gelöscht wird]. Nach Ablauf müssen Sie sich erneut beim Rancher-Server anmelden, um den `kubectl get pods` Befehl auszuführen.
