= {rancher-product-name} CLI
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: reference-guides/cli-with-rancher/rancher-cli.adoc 
:product-path: rancher-admin/cli/rancher-cli.adoc
:description: Interagieren Sie mit Rancher über die Kommandozeilenschnittstelle (CLI) von Ihrem Arbeitsplatz.
ifeval::["{build-type}" != "community"]
:xref-user-api-keys: rancher-admin/users/settings/api-keys.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-projects-and-namespaces: xref:cluster-admin/manage-clusters/projects-and-namespaces.adoc
:xref-workloads-and-pods: xref:cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:xref-helm-charts-in-rancher: xref:cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc
:xref-nodes-machinepools: xref:cluster-admin/manage-clusters/nodes-and-machine-pools.adoc
:xref-namespaces: xref:cluster-admin/namespaces.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-user-api-keys: xref:reference-guides/user-settings/api-keys.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-projects-and-namespaces: xref:how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces.adoc
:xref-workloads-and-pods: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc
:xref-helm-charts-in-rancher: xref:how-to-guides/new-user-guides/helm-charts-in-rancher/index.adoc
:xref-nodes-machinepools: xref:how-to-guides/new-user-guides/manage-clusters/nodes-and-machine-pools.adoc
:xref-namespaces: xref:how-to-guides/new-user-guides/manage-namespaces.adoc
endif::[]

Die Rancher CLI (Kommandozeilenschnittstelle) ist ein einheitliches Tool, mit dem Sie mit Rancher interagieren können. Mit diesem Tool können Sie Rancher über die Befehlszeile anstelle der GUI bedienen.

[#_download_rancher_cli]
== Laden Sie die Rancher CLI herunter

Die Binärdatei kann direkt über die Benutzeroberfläche heruntergeladen werden.

. Klicken Sie oben links auf *☰*.
. Klicken Sie unten im Navigationsseitenleistenmenü auf *Über*.
. Unter dem Abschnitt *CLI-Downloads* finden Sie Links zum Herunterladen der Binärdateien für Windows, Mac und Linux. Sie können auch die https://github.com/rancher/cli/releases[Release-Seite für unsere CLI] überprüfen, um die Binärdatei direkt herunterzuladen.

[#_requirements]
== Anforderungen

Nachdem Sie die Rancher CLI heruntergeladen haben, müssen Sie einige Konfigurationen vornehmen. Die Rancher CLI benötigt:

* Ihre Rancher Server-URL, die verwendet wird, um eine Verbindung zum Rancher Server herzustellen.
* Ein API-Bearer-Token, das zur Authentifizierung bei Rancher verwendet wird. Für weitere Informationen zum Erhalten eines Bearer-Tokens siehe {xref-user-api-keys}[Erstellen eines API-Schlüssels].

[#_cli_authentication]
== CLI-Authentifizierung

Bevor Sie die Rancher CLI zur Steuerung Ihres Rancher Servers verwenden können, müssen Sie sich mit einem API-Bearer-Token authentifizieren. Melden Sie sich mit dem folgenden Befehl an (ersetzen Sie `<BEARER_TOKEN>` und `<SERVER_URL>` durch Ihre Informationen):

[,bash]
----
$ ./rancher login https://<SERVER_URL> --token <BEARER_TOKEN>
----

Wenn der Rancher Server ein selbstsigniertes Zertifikat verwendet, fordert die Rancher CLI Sie auf, mit der Verbindung fortzufahren.

[#_project_selection]
== Projektauswahl

Bevor Sie Befehle ausführen können, müssen Sie ein Rancher-Projekt auswählen, gegen das Sie diese Befehle ausführen können. Um ein {xref-projects-and-namespaces}[Projekt] auszuwählen, an dem Sie arbeiten möchten, verwenden Sie den Befehl `./rancher context switch`. Wenn Sie diesen Befehl eingeben, wird eine Liste der verfügbaren Projekte angezeigt. Geben Sie eine Nummer ein, um Ihr Projekt auszuwählen.

*Beispiel: `./rancher context switch` Ausgabe*

----
User:rancher-cli-directory user$ ./rancher context switch
NUMBER    CLUSTER NAME   PROJECT ID              PROJECT NAME
1         cluster-2      c-7q96s:p-h4tmb         project-2
2         cluster-2      c-7q96s:project-j6z6d   Default
3         cluster-1      c-lchzv:p-xbpdt         project-1
4         cluster-1      c-lchzv:project-s2mch   Default
Select a Project:
----

Nachdem Sie eine Nummer eingegeben haben, zeigt die Konsole eine Nachricht an, dass Sie das Projekt gewechselt haben.

----
INFO[0005] Setting new context to project project-1
INFO[0005] Saving config to /Users/markbishop/.ranchcli2.json
----

Stellen Sie sicher, dass Sie `rancher kubectl get pods` erfolgreich ausführen können.

[#_commands]
== Befehle

Die folgenden Befehle stehen zur Verwendung in Rancher CLI zur Verfügung.

|===
| Kommando | Ergebnis

| `clusters, [cluster]`
| Führt Operationen an Ihren {xref-cluster-deployment}[Cluster] durch.

| `context`
| Wechselt zwischen Rancher {xref-projects-and-namespaces}[Projekten]. Für ein Beispiel siehe <<_project_selection,Projektauswahl>>.

| `inspect [OPTIONS] [RESOURCEID RESOURCENAME]`
| Zeigt Details zu https://kubernetes.io/docs/reference/kubectl/cheatsheet/#resource-types[Kubernetes-Ressourcen] oder Rancher-Ressourcen (d.h.: {xref-projects-and-namespaces}[Projekte] und {xref-workloads-and-pods}[Workloads]) an. Geben Sie Ressourcen nach Name oder ID an.

| `kubectl`
| Führt https://kubernetes.io/docs/reference/kubectl/overview/#operations[kubectl-Befehle] aus.

| `login, [l]`
| Meldet sich bei einem Rancher-Server an. Für ein Beispiel siehe <<_cli_authentication,CLI-Authentifizierung>>.

| `machines, [machine]`
| Führt Operationen an Maschinen durch.

| `namespaces, [namespace]`
| Führt Operationen an {xref-namespaces}[Namespaces] durch.

| `nodes, [node]`
| Führt Operationen an {xref-nodes-machinepools}[Knoten] durch.

| `projects, [project]`
| Führt Operationen an {xref-projects-and-namespaces}[Projekten] durch.

| `ps`
| Zeigt {xref-workloads-and-pods}[Workloads] in einem Projekt an.

| `server`
| Führt Operationen für den Server aus.

| `settings, [setting]`
| Zeigt die aktuellen Einstellungen für Ihren Rancher-Server an.

| `ssh`
| Stellt eine Verbindung zu einem Ihrer Cluster-Knoten über das SSH-Protokoll her.

| `up`
| Wendet die Compose-Konfiguration an.

| `wait`
| Wartet auf Ressourcen: Cluster, App, Projekt, MultiClusterApp.

| `token`
| Authentifiziert und generiert ein neues kubeconfig-Token.

| `help, [h]`
| Zeigt eine Liste von Befehlen oder Hilfe für einen Befehl an.
|===

[#_rancher_cli_help]
== Rancher CLI Hilfe

Nachdem Sie sich über die CLI beim Rancher-Server angemeldet haben, geben Sie `./rancher --help` für eine Liste von Befehlen ein.

Alle Befehle akzeptieren das `--help` Flag, das die Verwendung jedes Befehls dokumentiert.

[#_limitations]
== Nutzungsbeschränkungen

Die Rancher CLI *kann nicht* verwendet werden, um {xref-helm-charts-in-rancher}[Dashboard-Apps oder Rancher-Funktionsdiagramme] zu installieren.
