= Configuración de Plantilla de Nodo Nutanix
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guías-de-referencia/configuración-del-clúster/configuración-del-clúster-sentido-descendente/configuración-de-plantilla-de-nodo/nutanix.adoc 
:product-path: cluster-deployment/infra-providers/nutanix/node-template-configuration.adoc

[#_account_access]
== Acceso a la cuenta

[cols="<,^,<,<"]
|===
| Parámetro | required | Descripción | Default

| Punto de Gestión
| ✓
| Nombre de host/dirección IP de Prism Central
|

| Nombre de usuario
| ✓
| Nombre de usuario de Prism Central
|

| Contraseña
| ✓
| Contraseña de Prism Central
|

| Permitir comunicación insegura
|
| Establecer en verdadero para permitir la comunicación SSL insegura con Prism Central
| False
|===

[#_scheduling]
== Programación

Elige a qué clúster Nutanix se programará la máquina virtual.

[cols="<,^,<"]
|===
| Parámetro | required | Descripción

| Clúster
| ✓
| Nombre del clúster Nutanix donde se debe desplegar la VM (sensible a mayúsculas)
|===

[#_instance_options]
== Opciones de instancia

En la sección *Opciones de Instancia*, configura el número de vCPUs, memoria y tamaño del disco para las VMs creadas por esta plantilla.

[cols="<,^,<,<"]
|===
| Parámetro | required | Descripción | Default

| CPU
|
| Número de vCPUs asignadas a la VM (núcleos)
| 2

| Memoria
|
| Cantidad de RAM asignada a la VM (MB)
| 2 GB

| Imagen de Plantilla
| ✓
| Nombre de la plantilla de imagen de disco a clonar como el disco principal de la VM (debe soportar cloud-init)
|

| Tamaño del Disco de la VM
|
| Nuevo tamaño del disco principal de la VM (en GiB)
|

| Tamaño del Disco Adicional
|
| Tamaño de un disco adicional para añadir a la VM (en GiB)
|

| Contenedor de Almacenamiento
|
| Contenedor de almacenamiento _UUID_ en el que provisionar un disco adicional
|

| YAML de configuración cloud
|
| Cloud-init para proporcionar a la VM (se parcheará con el usuario raíz de Rancher)
|

| Red
| ✓
| Nombre(s) de la(s) red(es) a conectar a la VM
|

| Categorías de la VM
|
| Nombre(s) de cualquier categoría que se aplique a la VM
|
|===

La VM puede utilizar cualquier sistema operativo Linux moderno que esté configurado con soporte para https://cloudinit.readthedocs.io/en/latest/[cloud-init] utilizando el https://cloudinit.readthedocs.io/en/latest/reference/datasources/configdrive.html[datasource Config Drive v2].

[#_networks]
== Redes

La plantilla de nodo permite aprovisionar una VM con múltiples redes. En el campo *Red*, puedes hacer clic en *Añadir* para agregar cualquier red disponible para ti en AOS.

[#_vm_categories]
== Categorías de la VM

Una categoría es un agrupamiento de entidades en un par clave-valor. Típicamente, las VMs se asignan a una categoría basada en algún criterio. Las políticas pueden estar vinculadas a aquellas entidades que están asignadas (agrupadas por) un valor de categoría específico.

[#_cloud_init]
== cloud-init

https://cloudinit.readthedocs.io/en/latest/[Cloud-init] te permite inicializar tus nodos aplicando configuración en el primer arranque. Esto puede implicar cosas como crear usuarios o autorizar claves SSH.

Para hacer uso de la inicialización de cloud-init, pega una configuración cloud utilizando una sintaxis YAML válida en el campo *YAML de configuración cloud*. Consulta la https://cloudinit.readthedocs.io/en/latest/topics/examples.html[documentación de cloud-init] para un conjunto comentado de ejemplos de directivas de configuración cloud soportadas.

Ten en cuenta que la configuración de red basada en cloud-init no se recomienda y solo se admite a través de datos de usuario `runcmd` en lugar de NoCloud u otras fuentes de configuración de red.

Se recomienda la gestión de direcciones IP de Nutanix (IPAM) o otro servicio DHCP.

[#_engine_options]
== Opciones del motor

En la sección *Opciones del motor* de la plantilla del nodo, puedes configurar el daemon de contenedor. Puede que desees especificar la versión del contenedor o un espejo del registro de imágenes del contenedor.

[NOTE]
====
Si estás aprovisionando nodos de Red Hat Enterprise Linux (RHEL) o CentOS, deja el campo *URL de instalación de Docker* con el valor predeterminado, o selecciona *ninguno*. Esto eludirá una comprobación de la instalación de Docker, ya que Docker ya está instalado en estos tipos de nodos.

Si estableces *URL de instalación de Docker* a un valor diferente del predeterminado o *ninguno*, podrías ver un mensaje de error como el siguiente: `Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`
====

