= Creando un clúster Nutanix AOS
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: instrucciones/guías-para-nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nodos-nuevos-en-un-proveedor-de-infraestructura/nutanix/index.adoc 
:product-path: cluster-deployment/infra-providers/nutanix/nutanix.adoc
:description: Utiliza Rancher para crear un clúster Nutanix AOS (AHV). Puede consistir en grupos de máquinas virtuales con propiedades distintas que permiten un control detallado sobre el tamaño de los nodos.
ifeval::["{build-type}" != "community"]
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:xref-nutanix-aos-provisioning: xref:cluster-deployment/infra-providers/nutanix/provision-kubernetes-clusters-in-aos.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-landing-page: https://docs.k3s.io/
:url-rke2-landing-page: https://docs.rke2.io/
:xref-nutanix-aos-provisioning: xref:instrucciones/guías-para-nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/nutanix/provisionar-clusters-de-kubernetes-en-aos.adoc
endif::[]

https://www.nutanix.com/products/acropolis[Nutanix Acropolis Operating System] (Nutanix AOS) es un sistema operativo para la plataforma de infraestructura hiperconvergente de Nutanix. AOS viene con un hipervisor integrado llamado https://www.nutanix.com/products/ahv[Acropolis Hypervisor], o AHV. Al utilizar Rancher con Nutanix AOS (AHV), puedes llevar las operaciones en la nube in situ.

Rancher puede aprovisionar nodos en AOS (AHV) e instalar Kubernetes en ellos. Al crear un clúster de Kubernetes en AOS, Rancher primero aprovisiona el número especificado de máquinas virtuales comunicándose con la API de Prism Central. Luego instala Kubernetes sobre las máquinas virtuales.

Un clúster Nutanix puede consistir en múltiples grupos de máquinas virtuales con propiedades distintas, como la cantidad de memoria o el número de vCPUs. Este agrupamiento permite un control detallado sobre el tamaño de los nodos para cada rol de Kubernetes.

[#_creating_a_nutanix_cluster]
== Creando un clúster Nutanix

Consulta el {xref-nutanix-aos-provisioning}[Provisionamiento de clústeres de Kubernetes en Nutanix AOS] para aprender a utilizar Rancher para instalar un {url-rke2-landing-page}[RKE2]/{url-k3s-landing-page}[K3s] clúster de Kubernetes en Nutanix AOS.
