= Lista de verificación para clústeres listos para producción
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: xref:guías-como-hacer/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/lista-de-verificación-para-clusters-listos-para-producción/index.adoc 
:product-path: cluster-deployment/production-checklist/production-checklist.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
:xref-production-checklist-node-roles: xref:cluster-deployment/production-checklist/roles-for-nodes-in-kubernetes.adoc
:xref-best-practices: xref:installation-and-upgrade/best-practices/best-practices.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-set-up-cloud-providers: xref:instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configurar-proveedores-de-nube/index.adoc
:xref-production-checklist-node-roles: xref:how-to-guides/guías-para-nuevos-usuarios/configuración-de-clústeres-de-Kubernetes-en-Rancher/lista-de-verificación-para-clústeres-listos-para-producción/roles-para-nodos-en-Kubernetes.adoc
:xref-best-practices: xref:reference-guides/best-practices/rancher-server/index.adoc
endif::[]

En esta sección, recomendamos las mejores prácticas para crear los clústeres de Kubernetes listos para producción que ejecutarán tus apps y servicios.

Para una lista de requisitos para tu clúster, incluidos los requisitos para el sistema operativo/Docker, hardware y red, consulta la sección sobre {xref-node-reqs}[requisitos de nodo.]

Esta es una lista corta de mejores prácticas que recomendamos encarecidamente para todos los clústeres de producción.

Para una lista completa de todas las mejores prácticas que recomendamos, consulta la {xref-best-practices}[sección de mejores prácticas.]

[#_node_requirements]
== Requisitos del Nodo

* Asegúrate de que tus nodos cumplan con todos los {xref-node-reqs}[requisitos de nodo,] incluidos los requisitos de puerto.

[#_back_up_etcd]
== Haz una copia de seguridad de etcd

* Habilita las instantáneas de etcd. Verifica que se estén creando instantáneas y realiza un escenario de recuperación ante desastres para verificar que las instantáneas sean válidas. etcd es el lugar donde se almacena el estado de tu clúster, y perder datos de etcd significa perder tu clúster. Asegúrate de configurar instantáneas recurrentes de etcd para tu(s) clúster(es), y asegúrate de que las instantáneas se almacenen externamente (fuera del nodo) también.

[#_cluster_architecture]
== Arquitectura del clúster

* Los nodos deben tener una de las siguientes configuraciones de rol:
 ** `etcd`
 ** `controlplane`
 ** `etcd` y `controlplane`
 ** `worker` (el rol `worker` no debe ser utilizado ni añadido a nodos con el rol `etcd` o `controlplane`)
* Ten al menos tres nodos con el rol `etcd` para sobrevivir a la pérdida de un nodo. Aumenta este número para una mayor tolerancia a fallos de nodo y distribúyelos en zonas de disponibilidad para proporcionar una tolerancia a fallos aún mejor.
* Asigna dos o más nodos el rol `controlplane` para alta disponibilidad de componentes maestros.
* Asigna dos o más nodos el rol `worker` para la reprogramación de cargas de trabajo en caso de fallo de un nodo.

Para más información sobre el uso de cada rol, consulta la {xref-production-checklist-node-roles}[sección sobre roles para nodos en Kubernetes.]

Para más información sobre el número de nodos para cada rol de Kubernetes, consulta la sección sobre {xref-arch-rec}[arquitectura recomendada.]

[#_logging_and_monitoring]
== Registro y supervisión

* Configura alertas/notificadores para los componentes de Kubernetes (Servicio del Sistema).
* Configura el registro para el análisis del clúster y los post-mortems.

[#_reliability]
== Fiabilidad

* Realiza pruebas de carga en tu clúster para verificar que su hardware puede soportar tus cargas de trabajo.

[#_networking]
== Conectividad

* Minimiza la latencia de la red. Rancher recomienda minimizar la latencia entre los nodos de etcd. La configuración predeterminada para `heartbeat-interval` es `500`, y la configuración predeterminada para `election-timeout` es `5000`. Estas https://etcd.io/docs/v3.5/tuning/[configuraciones para la optimización de etcd] permiten que etcd funcione en la mayoría de las redes (excepto en redes con latencia realmente alta).
* Los nodos del clúster deben estar ubicados dentro de una única región. La mayoría de los proveedores de la nube ofrecen múltiples zonas de disponibilidad dentro de una región, que se pueden utilizar para crear una alta disponibilidad para tu clúster. Usar múltiples zonas de disponibilidad está bien para nodos con cualquier rol. Si estás utilizando recursos de {xref-set-up-cloud-providers}[Proveedor de Nube de Kubernetes], consulta la documentación para cualquier restricción (es decir, restricciones de almacenamiento por zona).
