= Créer une version de conformité personnalisée pour exécuter un scan de cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/compliance-scan-guides/créer-une-version-de-conformité-personnalisée-à-exécuter.adoc 
:product-path: security/compliance-scans/create-a-custom-compliance-version-to-run.adoc
ifeval::["{build-type}" != "community"]
:xref-compliance-scan-custom-benchmark: xref:security/compliance-scans/custom-benchmark.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-compliance-scan-custom-benchmark: xref:integrations-in-rancher/compliance-scans/custom-benchmark.adoc
endif::[]

Il pourrait y avoir certaines configurations de clusters Kubernetes qui nécessitent des configurations personnalisées des tests de conformité. Par exemple, le chemin vers les fichiers de configuration Kubernetes ou les certificats pourrait être différent de l'emplacement standard où la conformité en amont les recherche.

Il est désormais possible de créer une version de conformité personnalisée pour exécuter un scan de cluster en utilisant l'application `rancher-compliance`.

Pour plus de détails, consultez {xref-compliance-scan-custom-benchmark}[cette page].
