= Afficher les rapports
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/compliance-scan-guides/view-reports.adoc 
:product-path: security/compliance-scans/view-reports.adoc
:experimental:

Pour afficher les rapports d'analyse de conformité générés,

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sur la page **Clusters**, allez au cluster où vous souhaitez exécuter une analyse de conformité et cliquez sur *Explorer*.
. Cliquez sur *Conformité > Analyse*.
. La page *Scans* affichera les rapports générés. Pour voir un rapport détaillé, allez à un rapport d'analyse et cliquez sur le nom.

On peut télécharger le rapport depuis la liste des analyses ou depuis la page de détails de l'analyse.

Pour obtenir la version détaillée des résultats de l'analyse de conformité, exécutez la commande suivante sur le cluster qui a été analysé. Notez que l’analyse doit être terminée avant que cela puisse être fait.

[,shell]
----
export REPORT="scan-report-name"
kubectl get clusterscanreports.compliance.cattle.io $REPORT -o json |jq ".spec.reportJSON | fromjson" | jq -r ".actual_value_map_data" | base64 -d | gunzip | jq .
----
