= Adicionando Usuários a Projetos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/add-users-to-projects.adoc 
:product-path: cluster-admin/project-admin/add-users-to-projects.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/usuarios/authn-e-authz/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-projects-and-namespaces: xref:cluster-admin/manage-clusters/projects-and-namespaces.adoc
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-locked-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:como-fazer-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-projects-and-namespaces: xref:how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces.adoc
:xref-custom-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-personalizadas.adoc
:xref-locked-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-bloqueadas.adoc
endif::[]

Se você deseja conceder a um usuário acesso e permissões a projetos e recursos _específicos_ dentro de um cluster, adicione-o como membro do projeto.

Você pode adicionar membros a um projeto enquanto ele é criado, ou adicioná-los a um projeto existente.

[TIP]
====

Deseja fornecer a um usuário acesso a _todos_ os projetos dentro de um cluster? Veja {xref-cluster-project-roles}[Adicionando Membros ao Cluster] em vez disso.
====


[#_adding_members_to_a_new_project]
== Adicionando Membros a um Novo Projeto

Você pode adicionar membros a um projeto enquanto o cria (recomendado, se possível). Para detalhes sobre como criar um novo projeto, consulte a {xref-projects-and-namespaces}[seção de administração do cluster.]

[#_adding_members_to_an_existing_project]
== Adicionando Membros a um Projeto Existente

Após a criação do projeto, você pode adicionar usuários como membros do projeto para que possam acessar seus recursos.

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster onde você deseja adicionar membros a um projeto e clique em *Explorar*.
. Clique em menu:Cluster[Projetos/Namespaces].
. Vá para o projeto onde você deseja adicionar membros. Ao lado do botão *Criar Namespace* acima do nome do projeto, clique em *☰*. Selecione *Editar Configuração*.
. Na aba *Membros*, clique em *Adicionar*.
. Pesquise o usuário ou grupo que você deseja adicionar ao projeto.
+
[NOTE]
.Notes
====
* Pelo menos 2 caracteres devem ser digitados na caixa de pesquisa para que os resultados apareçam.
* Os usuários podem ser pesquisados com base em seu nome de usuário ou nome exibido.
* A pesquisa é baseada em prefixo (por exemplo, um usuário chamado `Stan Dard` aparecerá ao pesquisar por `Sta`, mas não ao pesquisar por `Dar`) e é sensível a maiúsculas e minúsculas.
====
+
Se a autenticação externa estiver configurada:

 ** O Rancher retorna usuários da sua fonte de autenticação externa à medida que você digita.
 ** Um menu suspenso permite que você adicione grupos em vez de usuários individuais. O menu suspenso lista apenas grupos dos quais você, o usuário logado, faz parte.

+

[NOTE]
====
Se você estiver logado como um usuário local, usuários externos não aparecem nos seus resultados de pesquisa.
====


. Atribua ao usuário ou grupo funções *Projeto*.
+
{xref-cluster-project-roles}[O que são Funções de Projeto?]
+

[NOTE]
.Notas:
====

 ** Usuários atribuídos à função `Owner` ou `Member` para um projeto herdam automaticamente a função `namespace creation`. No entanto, essa função é um https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole[ClusterRole do Kubernetes], o que significa que seu escopo se estende a todos os projetos no cluster. Portanto, usuários explicitamente atribuídos à função `Owner` ou `Member` para um projeto podem criar ou excluir namespaces em outros projetos aos quais estão atribuídos, mesmo com apenas a função `Read Only` atribuída.
 ** Por padrão, a função Rancher de `project-member` herda da função `Kubernetes-edit`, e a função `project-owner` herda da função `Kubernetes-admin`. Assim, tanto as funções `project-member` quanto `project-owner` permitirão o gerenciamento de namespaces, incluindo a capacidade de criar e excluir namespaces.
 ** Para funções `Custom`, você pode modificar a lista de funções individuais disponíveis para atribuição.
  *** Para adicionar funções à lista, {xref-custom-roles}[Adicionar uma Função Personalizada].
  *** Para remover funções da lista, {xref-locked-roles}[Bloquear/Desbloquear Funções].

+
====


*Resultado:* Os usuários escolhidos são adicionados ao projeto.

* Para revogar a participação no projeto, selecione o usuário e clique em *Excluir*. Esta ação exclui a associação, não o usuário.
* Para modificar as funções de um usuário no projeto, exclua-o do projeto e, em seguida, adicione-o novamente com as funções modificadas.
