= Administração de Projetos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/manage-projects/index.adoc 
:product-path: cluster-admin/project-admin/project-admin.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/usuarios/authn-e-authz/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/permissões-globais.adoc
:xref-project-resource-quotas: xref:cluster-admin/project-admin/project-resource-quotas/project-resource-quotas.adoc
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-namespaces: xref:cluster-admin/namespaces.adoc
:xref-add-users-to-projects: xref:cluster-admin/project-admin/add-users-to-projects.adoc
:xref-rancher-project-tools: xref:observabilidade/ferramentas-de-projeto-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:como-fazer-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-global-permissions: xref:procedimentos/novos-usuários/guias-de-autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/permissões-globais.adoc 
:xref-project-resource-quotas: xref:how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/index.adoc
:xref-custom-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-personalizadas.adoc
:xref-namespaces: xref:how-to-guides/new-user-guides/manage-namespaces.adoc
:xref-add-users-to-projects: xref:how-to-guides/new-user-guides/add-users-to-projects.adoc
:xref-rancher-project-tools: xref:reference-guides/rancher-project-tools.adoc
endif::[]

_Projetos_ são objetos introduzidos no Rancher que ajudam a organizar namespaces em seu cluster Kubernetes. Você pode usar projetos para criar clusters multi-inquilinos, o que permite que um grupo de usuários compartilhe os mesmos recursos subjacentes sem interagir com os aplicativos uns dos outros.

Em termos de hierarquia:

* Clusters contêm projetos
* Projetos contêm namespaces

Dentro do Rancher, os projetos permitem que você gerencie múltiplos namespaces como uma única entidade. No Kubernetes nativo, que não inclui projetos, recursos como direitos de acesso baseados em função ou recursos de cluster são atribuídos a namespaces individuais. Em clusters onde múltiplos namespaces requerem o mesmo conjunto de direitos de acesso, atribuir esses direitos a cada namespace individual pode se tornar tedioso. Mesmo que todos os namespaces exijam os mesmos direitos, não há como aplicar esses direitos a todos os seus namespaces em uma única ação. Você teria que atribuir repetidamente esses direitos a cada namespace!

Os projetos do Rancher resolvem esse problema permitindo que você aplique recursos e direitos de acesso no nível do projeto. Cada namespace no projeto herda então esses recursos e políticas, assim você só precisa atribuí-los ao projeto uma vez, em vez de atribuí-los a cada namespace individual.

Você pode usar projetos para realizar ações como:

* {xref-add-users-to-projects}[][Atribuir acesso de usuários a um grupo de namespaces]
* Atribuir usuários {xref-cluster-project-roles}#_project_roles[papéis específicos em um projeto]. Um papel pode ser proprietário, membro, somente leitura ou {xref-custom-roles}[personalizada].
* {xref-project-resource-quotas}[Definir cotas de recursos]
* {xref-namespaces}[Gerenciar namespaces]
* {xref-rancher-project-tools}[Configurar ferramentas]

[#_authorization]
== Autorização

Usuários não administrativos estão autorizados a acessar o projeto somente após que um {xref-global-permissions}[administrador], {xref-cluster-project-roles}#_cluster_roles[proprietário ou membro do cluster] ou {xref-cluster-project-roles}#_project_roles[proprietário do projeto] os adicione à aba *Membros* do projeto.

Quem cria o projeto automaticamente se torna um {xref-cluster-project-roles}#_project_roles[proprietário do projeto].

[#_switching_between_projects]
== Alternando entre Projetos

Para alternar entre projetos, use o menu suspenso disponível na barra de navegação. Alternativamente, você pode alternar entre projetos diretamente na barra de navegação.

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster onde você deseja alternar projetos e clique em *Explorar*.
. Na barra de navegação superior, selecione o projeto que você deseja abrir.
