= {stackstate-product-name}
:revdate: 2025-07-23
:page-revdate: {revdate}

SUSE Observability is a complete observability solution that provides deep insights into the health of your clusters and nodes, and the workloads running on them. Designed to give you clear visibility into your entire Kubernetes environment, SUSE Observability's full-stack approach allows you to seamlessly explore everything from services to infrastructure within a single platform, eliminating the need for multiple observability tools.

SUSE Observability securely collects and correlates data, offering actionable insights into both existing and potential issues in your cluster. This helps you address current problems swiftly and take preventative measures against future challenges.

The intuitive dashboards highlight problem areas and offer remediation steps, guiding you from issue identification to root cause analysis, and ultimately to resolution, in the quickest possible time.

For more information and to set up SUSE Observability in your SUSE Rancher-managed Kubernetes cluster, please refer to the https://documentation.suse.com/en-us/cloudnative/suse-observability/[documentation].
