= {rancher-product-name} Guias de Início Rápido de Implantação
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/index.adoc 
:product-path: installation-and-upgrade/quick-start/quick-start.adoc
ifeval::["{build-type}" != "community"]
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-qs-deploy-workloads: xref:installation-and-upgrade/quick-start/deploy-workloads/deploy-workloads.adoc
:xref-qs-deploy-rancher: xref:installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-qs-deploy-workloads: xref:getting-started/quick-start-guides/deploy-workloads/index.adoc
:xref-qs-deploy-rancher: xref:getting-started/quick-start-guides/deploy-rancher-manager/index.adoc
endif::[]

[CAUTION]
====

A intenção destes guias é lançar rapidamente uma área de segurança que você pode usar para avaliar o Rancher. Esses guias não são destinados a ambientes de produção. Para instruções abrangentes de configuração, consulte {xref-install-upgrade}[Instalação].
====


Use esta seção da documentação para iniciar sua implantação e testes do Rancher 2.x. Ela contém instruções para uma configuração simples do Rancher e alguns casos de uso comuns. Planejamos adicionar mais conteúdo a esta seção no futuro.

Temos Guias de Início Rápido para:

* {xref-qs-deploy-rancher}[Implantando o Servidor Rancher]: Comece a executar o Rancher usando o método mais conveniente para você.
* {xref-qs-deploy-workloads}[Implantando Cargas de Trabalho]: Implante uma https://kubernetes.io/docs/concepts/workloads/[carga de trabalho] simples e exponha-a, permitindo que você a acesse de fora do cluster.
