= {rancher-product-name}セットアップでのKubernetesクラスター
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc 
:product-path: cluster-deployment/cluster-deployment.adoc
:description: Kubernetesクラスターのプロビジョニング
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-custom-clusters: xref:cluster-deployment/custom-clusters/custom-clusters.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
:xref-rancher-architecture: xref:about-rancher/architecture/architecture.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-infra-providers: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/index.adoc
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
:xref-custom-clusters: xref:reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/index.adoc
:xref-hosted-k8s-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/index.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
endif::[]

Rancherは、より複雑な代替手段ではなく、Rancher UIを通じてクラスターを作成できるようにすることで、クラスターの作成を簡素化します。Rancherは、クラスターを起動するための複数のオプションを提供します。ユースケースに最適なオプションを選択してください。

このセクションでは、DockerとKubernetesの基本的な知識があることを前提としています。Kubernetesコンポーネントがどのように連携して動作するかについての簡単な説明は、{xref-k8s-concepts}[concepts]ページを参照してください。

Rancherサーバーがクラスターをプロビジョニングする方法と、それに使用するツールの概念的な概要については、{xref-rancher-architecture}[アーキテクチャ]ページを参照してください。

[#_cluster_management_capabilities_by_cluster_type]
== クラスタータイプ別のクラスター管理機能

以下の表は、各クラスタータイプで利用可能なオプションと設定を要約しています：

ifeval::["{build-type}" != "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table.adoc[]
endif::[]
ifeval::["{build-type}" == "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table-srfa.adoc[]
endif::[]

[#_setting_up_clusters_in_a_hosted_kubernetes_provider]
== ホステッドKubernetesプロバイダーでのクラスターのセットアップ

ifeval::["{build-type}" != "srfa"]
このシナリオでは、RancherはKubernetesをプロビジョニングしません。なぜなら、Google Kubernetes Engine (GKE)、Amazon Elastic Container Service for Kubernetes、またはAzure Kubernetes Serviceなどのプロバイダーによってインストールされるからです。
endif::[]
ifeval::["{build-type}" == "srfa"]
このシナリオでは、RancherはKubernetesをプロビジョニングしません。なぜなら、Amazon Elastic Container Service for Kubernetesによってインストールされるからです。
endif::[]

ifeval::["{build-type}" != "srfa"]
Google GKEなどのKubernetesプロバイダーを使用する場合、RancherはそのクラウドAPIと統合され、Rancher UIからホステッドクラスターのロールベースのアクセス制御を作成および管理できます。
endif::[]
ifeval::["{build-type}" == "srfa"]
Kubernetesプロバイダーを使用する場合、RancherはそのクラウドAPIと統合され、Rancher UIからホステッドクラスターのロールベースのアクセス制御を作成および管理できます。
endif::[]

詳細については、{xref-hosted-k8s-clusters}[ホステッドKubernetesクラスター]に関するセクションを参照してください。

[#_launching_kubernetes_with_rancher]
== Rancherを使用してKubernetesを起動する

Rancherは、独自のノードでKubernetesをプロビジョニングする際に、 https://docs.rke2.io/[RKE2]または https://docs.k3s.io/[K3s]をライブラリとして使用します。RKE2は、Rancher独自の軽量Kubernetesインストーラーです。

RKE2クラスターでは、RancherがKubernetesのデプロイメントを管理します。これらのクラスターは、任意のベアメタルサーバー、クラウドプロバイダー、またはビジュアル化プラットフォームにデプロイできます。

RKE2クラスターに追加したいノードがすでにある場合は、そのノード上でRancher RKE2エージェントコンテナを実行することで、クラスターに追加できます。

詳細については、{xref-launch-k8s-with-rancher}[Rancherを使用してKubernetesを起動する]を参照してください。

[#_launching_kubernetes_and_provisioning_nodes_in_an_infrastructure_provider]
=== インフラプロバイダーでのKubernetesの起動とノードのプロビジョニング

ifeval::["{build-type}" != "srfa"]
Rancherは、Amazon EC2、DigitalOcean、Azure、またはvSphereなどのインフラプロバイダーでノードを動的にプロビジョニングし、その上にKubernetesをインストールできます。
endif::[]
ifeval::["{build-type}" == "srfa"]
Rancherは、Amazon EC2などのインフラプロバイダーでノードを動的にプロビジョニングし、その上にKubernetesをインストールします。
endif::[]

インフラプロバイダーがホストするノードを使用する利点の一つは、ノードがクラスターとの接続を失った場合、Rancherが自動的にそれを置き換え、期待されるクラスター設定を維持できることです。

詳細については、{xref-infra-providers}[インフラプロバイダーにおける新しいノードでのKubernetesの起動]を参照してください。

[#_launching_kubernetes_on_existing_custom_nodes]
=== 既存のカスタムノードでKubernetesを起動する

このタイプのクラスターを設定する際、Rancherは既存の{xref-custom-clusters}[カスタムノード]にKubernetesをインストールし、カスタムクラスターを作成します。

任意のノードをRancherに持ち込み、それを使用してクラスターを作成できます。

これらのノードには、オンプレミスのベアメタルサーバー、クラウドホストの仮想マシン、またはオンプレミスの仮想マシンが含まれます。

[#_registering_existing_clusters]
== 既存のクラスターの登録

クラスター登録機能は、クラスターをインポートする機能に置き換わります。

EKSクラスターの登録は、現在追加の利点を提供します。ほとんどの場合、登録されたEKSクラスターとRancherで作成されたEKSクラスターは、削除を除いてRancher UIで同じように扱われます。

Rancherで作成されたEKSクラスターを削除すると、そのクラスターは破棄されます。Rancherに登録されたEKSクラスターを削除すると、それはRancherサーバーから切断されますが、依然として存在し、Rancherに登録される前と同じようにアクセスできます。

詳細については、{xref-register-clusters}[既存のクラスターの登録]を参照してください。

[#_programmatically_creating_clusters]
== プログラムによるクラスターの作成

Rancherを通じてKubernetesクラスターをプログラムでデプロイする最も一般的な方法は、Rancher2 Terraformプロバイダーを使用することです。 https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster[Terraformを使用したクラスターの作成]に関するドキュメントを参照してください。

ifeval::["{build-type}" != "srfa"]
EKS、GKE、およびAKSクラスターは、Terraformを使用して作成またはインポートできます。
endif::[]
ifeval::["{build-type}" == "srfa"]
EKSクラスターは、Terraformを使用して作成またはインポートできます。
endif::[]
