= 登録済みクラスター
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/registered-clusters.adoc 
:product-path: cluster-deployment/register-existing-clusters-troubleshooting.adoc

このページに記載されているコマンドや手順は、登録中のクラスターまたはRancherに登録済みのクラスターを確認するために使用できます。

正しい kubeconfig を設定したことを確認してください（例えば、`export KUBECONFIG=$PWD/kubeconfig_from_imported_cluster.yml`）。

[#_rancher_agents]
== Rancher エージェント

クラスターへの通信（cattle-cluster-agent 経由のKubernetes API）およびノードへの通信は、Rancherエージェントを通じて行われます。

cattle-cluster-agentが設定された`server-url`に接続できない場合、クラスターは*Pending*状態のままとなり、`Waiting for full cluster configuration`が表示されます。

[#_cattle_node_agent]
=== cattle-node-agent

[NOTE]
====

cattle-node-agentsは、RancherでRKEを使用して作成されたクラスターにのみ存在します。
====


各ノードにcattle-node-agentポッドが存在し、ステータスが*Running*であり、再起動の回数が多くないことを確認してください：

----
kubectl -n cattle-system get pods -l app=cattle-agent -o wide
----

出力の例：

----
NAME                      READY     STATUS    RESTARTS   AGE       IP                NODE
cattle-node-agent-4gc2p   1/1       Running   0          2h        x.x.x.x           worker-1
cattle-node-agent-8cxkk   1/1       Running   0          2h        x.x.x.x           etcd-1
cattle-node-agent-kzrlg   1/1       Running   0          2h        x.x.x.x           etcd-0
cattle-node-agent-nclz9   1/1       Running   0          2h        x.x.x.x           controlplane-0
cattle-node-agent-pwxp7   1/1       Running   0          2h        x.x.x.x           worker-0
cattle-node-agent-t5484   1/1       Running   0          2h        x.x.x.x           controlplane-1
cattle-node-agent-t8mtz   1/1       Running   0          2h        x.x.x.x           etcd-2
----

特定のcattle-node-agentポッドまたはすべてのcattle-node-agentポッドのログを確認してください：

----
kubectl -n cattle-system logs -l app=cattle-agent
----

[#_cattle_cluster_agent]
=== cattle-cluster-agent

cattle-cluster-agentポッドがクラスターに存在し、ステータスが*Running*であり、再起動の回数が多くないことを確認してください：

----
kubectl -n cattle-system get pods -l app=cattle-cluster-agent -o wide
----

出力の例：

----
NAME                                    READY     STATUS    RESTARTS   AGE       IP           NODE
cattle-cluster-agent-54d7c6c54d-ht9h4   1/1       Running   0          2h        x.x.x.x      worker-1
----

cattle-cluster-agentポッドのログを確認してください：

----
kubectl -n cattle-system logs -l app=cattle-cluster-agent
----
