= {rancher-product-name} Estratégia de Implantação
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-server/rancher-deployment-strategy.adoc 
:product-path: installation-and-upgrade/best-practices/deployment-strategy.adoc

Existem duas estratégias de implantação recomendadas para uma instância do Rancher que gerencia clusters Kubernetes downstream. Cada uma tem suas próprias vantagens e desvantagens. Leia mais sobre qual delas se encaixaria melhor no seu caso de uso.

[#_hub_spoke_strategy]
== Estratégia Hub & Spoke

'''

Neste cenário de implantação, há uma única instância do Rancher gerenciando clusters Kubernetes ao redor do mundo. A instância do Rancher seria executada em um cluster Kubernetes de alta disponibilidade, e haveria impacto devido às latências.

[#_pros]
=== Vantagens

* Interface única de plano de controle para visualizar todas as regiões e ambientes.
* O Kubernetes não requer o Rancher para operar e pode tolerar a perda de conectividade com a instância do Rancher.

[#_cons]
=== Desvantagens

* Sujeito às latências da rede.
* Se o Rancher ficar fora do ar, o provisionamento global de novos serviços ficará indisponível até que seja restaurado. No entanto, cada cluster Kubernetes pode continuar a ser gerenciado individualmente.

[#_regional_strategy]
== Estratégia Regional

'''

No modelo de implantação regional, uma instância do Rancher é implantada próxima aos clusters Kubernetes downstream.

[#_pros_1]
=== Vantagens

* A funcionalidade do Rancher nas regiões permanece operacional se uma instância do Rancher em outra região ficar fora do ar.
* A latência da rede entre o Rancher e os clusters downstream é significativamente reduzida, melhorando o desempenho da funcionalidade no Rancher.
* É possível fazer upgrade do Rancher de forma independente por região.

[#_cons_1]
=== Desvantagens

* Sobrecarga de gerenciar várias instalações do Rancher.
* A visibilidade em clusters Kubernetes em diferentes regiões requer múltiplas interfaces/painéis de controle.
* Implantar aplicativos em múltiplos clusters no Rancher requer repetir o processo para cada servidor do Rancher.
