= Sobre Instalações de Alta Disponibilidade
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-cluster-setup/high-availability-installs.adoc 
:product-path: installation-and-upgrade/best-practices/high-availability-installs.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-architecture: xref:sobre-rancher/arquitetura/arquitetura.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
endif::[]

Recomendamos o uso do Helm, um gerenciador de pacotes do Kubernetes, para instalar o Rancher em um cluster Kubernetes dedicado. Isso é chamado de instalação Kubernetes de alta disponibilidade porque a maior disponibilidade é alcançada executando o Rancher em múltiplos nós.

Em uma instalação padrão, o Kubernetes é primeiro instalado em três nós que estão hospedados em um provedor de infraestrutura, como o EC2 da Amazon ou o Google Compute Engine.

Em seguida, o Helm é usado para instalar o Rancher sobre o cluster Kubernetes. O Helm utiliza o chart do Rancher para instalar uma réplica do Rancher em cada um dos três nós no cluster Kubernetes. Recomendamos o uso de um balanceador de carga para direcionar o tráfego para cada réplica do Rancher no cluster, a fim de aumentar a disponibilidade do Rancher.

Os dados do servidor Rancher são armazenados no etcd. Este banco de dados etcd também é executado em todos os três nós e requer um número ímpar de nós para que sempre possa eleger um líder com a maioria do cluster etcd. Se o banco de dados etcd não conseguir eleger um líder, o etcd pode falhar, exigindo que o cluster seja restaurado a partir do backup.

Para informações sobre como o Rancher funciona, independentemente do método de instalação, consulte a {xref-rancher-architecture}[seção de arquitetura.]

[#_recommended_architecture]
== Arquitetura Recomendada

* O DNS para o Rancher deve resolver para um balanceador de carga de camada 4
* O Balanceador de Carga deve encaminhar a porta TCP/80 e TCP/443 para todos os 3 nós no cluster Kubernetes.
* O controlador de Ingress redirecionará HTTP para HTTPS e encerrará SSL/TLS na porta TCP/443.
* O controlador de Ingress encaminhará o tráfego para a porta TCP/80 no pod na implantação do Rancher.

.Instalação do Kubernetes Rancher com balanceador de carga de camada 4, representando a terminação de SSL nos controladores de Ingress.
image::ha/rancher2ha.svg[Instalação Kubernetes de Alta Disponibilidade do Rancher]
