= Outros Recursos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/index.adoc 
:product-path: installation-and-upgrade/best-practices/resources.adoc
ifeval::["{build-type}" != "community"]
:xref-security-overview: xref:security/security-overview.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-security-overview: xref:reference-guides/rancher-security/index.adoc
endif::[]

O objetivo desta seção é consolidar as melhores práticas para implementações do Rancher. Isso também inclui recomendações para tecnologias relacionadas, como Kubernetes, Docker, contêineres e mais. O objetivo é melhorar o resultado de uma implementação do Rancher usando a experiência operacional do Rancher e de seus clientes.

Se você tiver alguma dúvida sobre como isso pode se aplicar ao seu caso de uso, entre em contato com seu gerente de sucesso do cliente ou suporte.

Use a barra de navegação à esquerda para encontrar as melhores práticas atuais para gerenciar e implantar o Rancher Server.

Para mais orientações sobre melhores práticas, você pode consultar estes recursos:

* {xref-security-overview}[Segurança]
* https://www.suse.com/c/rancherblog/[Blog do Rancher]
* https://forums.rancher.com/[Fórum do Rancher]
* https://slack.rancher.io/[Slack dos Usuários do Rancher]
* https://www.youtube.com/channel/UCh5Xtp82q8wjijP8npkVTBA/featured[Canal do YouTube do Rancher Labs - Encontros Online, Demonstrações, Treinamento, and Webinars]
