= Drivers de cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/novos-usuários/guias-de-autenticação-permissões-e-configuração-global/sobre-provisionamento-de-drivers/gerenciar-drivers-de-cluster.adoc 
:product-path: rancher-admin/global-configuration/provisioning-drivers/manage-cluster-drivers.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/permissões-globais.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:procedimentos/novos-usuários/guias-de-autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/permissões-globais.adoc 
:xref-hosted-k8s-clusters: xref:guias-de-procedimentos/guias-para-novos-usuários/clusters-kubernetes-no-rancher/configuração-clusters-a-partir-de-provedores-de-kubernetes-hospedados/index.adoc
endif::[]

Drivers de cluster são usados para criar clusters em um {xref-hosted-k8s-clusters}[provedor Kubernetes hospedado], como o Google GKE. A disponibilidade de qual driver de cluster exibir ao criar clusters é definida pelo status do driver de cluster. Apenas `active` drivers de cluster serão exibidos como uma opção para a criação de clusters. Por padrão, o Rancher é fornecido com vários drivers de cluster de provedores de nuvem existentes, mas você também pode adicionar drivers de cluster personalizados ao Rancher.

Se houver drivers de cluster específicos que você não deseja mostrar aos seus usuários, você pode desativar esses drivers de cluster dentro do Rancher e eles não aparecerão como uma opção para a criação de clusters.

[#_managing_cluster_drivers]
== Gerenciando drivers de cluster

[NOTE]
.Pré-requisitos:
====

Para criar, editar ou excluir drivers de cluster, você precisa de _uma_ das seguintes permissões:

* {xref-global-permissions}[Permissões Globais de Administrador]
* {xref-global-permissions}#_permissões_globais_personalizadas[Permissões Globais Personalizadas] com a função {xref-global-permissions}[Gerenciar Drivers de Cluster] atribuída.
====


[#_activating_deactivating_cluster_drivers]
== Ativando/Desativando drivers de cluster

Por padrão, o Rancher ativa apenas drivers para os provedores de nuvem mais populares, Google GKE, Amazon EKS e Azure AKS. Se você quiser mostrar ou ocultar qualquer driver de nó, pode alterar seu status.

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. No menu de navegação à esquerda, clique em *Drivers*.
. Na aba *Drivers de Cluster*, selecione o driver que você deseja ativar ou desativar e clique em *⋮ > Ativar* ou *⋮ > Desativar*.

[#_adding_custom_cluster_drivers]
== Adicionando drivers de cluster personalizados

Se você quiser usar um driver de cluster que o Rancher não suporta de forma nativa, pode adicionar o driver do provedor para começar a usá-los na criação de clusters Kubernetes _hospedados_.

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. No menu de navegação à esquerda, clique em *Drivers*.
. Na aba *Drivers de Cluster*, clique em *Adicionar Driver de Cluster*.
. Preencha o formulário *Adicionar Driver de Cluster*. Então clique em *Criar*.

[#_developing_your_own_cluster_driver]
== Desenvolvendo seu próprio driver de cluster

Para desenvolver um driver de cluster para adicionar ao Rancher, consulte nosso https://github.com/rancher-plugins/kontainer-engine-driver-example[exemplo].
