= kubectl 工具
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cli-with-rancher/kubectl-utility.adoc 
:product-path: rancher-admin/cli/kubectl.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
endif::[]

[#_kubectl]
== kubectl

使用 kubectl 与 Rancher 交互。

[#_kubectl_utility]
=== kubectl 工具

安装 `kubectl` 工具。请参见 https://kubernetes.io/docs/tasks/tools/install-kubectl/[安装 kubectl]。

通过访问 Rancher Web UI 中的集群，点击 `Kubeconfig`，复制内容，并将其放入您的 `~/.kube/config` 文件中来配置 kubectl。

成功运行 `kubectl cluster-info` 或 `kubectl get pods`。

[#_authentication_with_kubectl_and_kubeconfig_tokens_with_ttl]
=== 使用 kubectl 和带有 TTL 的 kubeconfig 词元进行身份验证

_要求_

如果管理员已关闭 xref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[kubeconfig 词元生成]，则在运行 `kubectl` 时，kubeconfig 文件要求 {xref-rancher-cli}[Rancher CLI] 存在于您的路径中。否则，您将看到类似的错误：
`Unable to connect to the server: getting credentials: exec: exec: "rancher": executable file not found in $PATH`。

此功能使 kubectl 能够与 Rancher 服务器进行身份验证，并在需要时获取新的 kubeconfig 词元。当前支持以下身份验证提供程序：

. 本地
. Active Directory（仅限 LDAP）
. FreeIPA
. OpenLDAP
. SAML 提供程序：Ping、Okta、ADFS、Keycloak、Shibboleth
. Azure AD

当您第一次运行 kubectl 时，例如 `kubectl get pods`，系统会提示您选择一个身份验证提供程序并使用 Rancher 服务器登录。kubeconfig 词元会被缓存到您在 `./.cache/token` 下运行 kubectl 所在的路径中。此词元有效，直至 xref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[过期] 或 xref:api/api-tokens.adoc#_deleting_tokens[从 Rancher 服务器删除]。在过期后，您必须再次使用 Rancher 服务器登录以运行 `kubectl get pods` 命令。
