= {k3s-product-name}Référence de configuration de cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-10
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc 
:product-path: cluster-deployment/configuration/k3s.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-ds-backup-restore: xref:cluster-admin/backups-and-restore/backups-and-restore.adoc
:xref-psact: xref:security/psact.adoc
:xref-azure-machine-configuration: xref:cluster-deployment/infra-providers/azure/machine-configuration.adoc
:xref-digitalocean-machine-configuration: xref:cluster-deployment/infra-providers/digitalocean/machine-configuration.adoc
:xref-aws-machine-configuration: xref:cluster-deployment/infra-providers/aws/machine-configuration.adoc
:xref-gce-machine-configuration: xref:cluster-deployment/infra-providers/gce/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-ds-backup-restore: xref:getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes.adoc
:xref-psact: xref:how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/psa-modèles-de-configuration.adoc
:xref-azure-machine-configuration: xref:guides-de-référence/configuration-cluster/configuration-cluster-en-aval/configuration-machine/azure.adoc
:xref-digitalocean-machine-configuration: xref:guides-de-référence/configuration-cluster/configuration-cluster-en-aval/configuration-machine/digitalocean.adoc
:xref-aws-machine-configuration: xref:guides-de-référence/configuration-cluster/configuration-cluster-en-aval/configuration-machine/amazon-ec2.adoc
:xref-gce-machine-configuration: xref:guides-de-référence/configuration-cluster/configuration-cluster-en-aval/configuration-machine/google-gce.adoc
endif::[]

Cette section couvre les options de configuration disponibles dans Rancher pour un cluster Kubernetes K3s nouveau ou existant.

[#_overview]
== Présentation

Vous pouvez configurer les options Kubernetes de deux manières :

* <<_configuration_options_in_the_rancher_ui,Interface utilisateur Rancher>> : Utilisez l'interface utilisateur Rancher pour sélectionner les options qui sont couramment personnalisées lors de la configuration d'un cluster Kubernetes.
* <<_cluster_config_file_reference,Fichier de configuration de cluster>> : Au lieu d'utiliser l'interface utilisateur Rancher pour choisir les options Kubernetes pour le cluster, les utilisateurs avancés peuvent créer un fichier de configuration K3s. L'utilisation d'un fichier de configuration vous permet de définir n'importe laquelle des https://rancher.com/docs/k3s/latest/en/installation/install-options/[options] disponibles lors d'une installation K3s.

[#_editing_clusters_in_the_rancher_ui]
== Modification des clusters dans l'interface utilisateur Rancher

L'interface utilisateur Rancher propose deux façons de modifier un cluster :

. Avec un formulaire.
. Avec YAML.

[#_editing_clusters_with_a_form]
=== Modification des clusters avec un formulaire

Le formulaire couvre les options les plus fréquemment nécessaires pour les clusters.

Pour modifier votre cluster,

. Cliquez sur *☰ > Gestion des clusters*.
. Allez au cluster que vous souhaitez configurer et cliquez sur *⋮ > Modifier la configuration*.

[#_editing_clusters_in_yaml]
=== Modification des clusters en YAML

Pour une référence complète des options configurables pour les clusters K3s en YAML, consultez la https://documentation.suse.com/cloudnative/k3s/latest/en/installation/configuration.html[documentation K3s].

Pour modifier votre cluster avec YAML :

. Cliquez sur *☰ > Gestion des clusters*.
. Allez au cluster que vous souhaitez configurer et cliquez sur *⋮ > Modifier en YAML*.
. Modifiez les options RKE sous la directive `rkeConfig`.

[#_configuration_options_in_the_rancher_ui]
== Options de configuration dans l'interface utilisateur de Rancher

[#_machine_pool_configuration]
=== Configuration de la réserve de machines

Cette sous-section couvre les configurations génériques de réserves de machines. Pour des configurations spécifiques aux fournisseurs d'infrastructure, référez-vous aux éléments suivants{nbsp}:

* {xref-azure-machine-configuration}[Azure]
* {xref-digitalocean-machine-configuration}[DigitalOcean]
* {xref-aws-machine-configuration}[Amazon EC2]
* {xref-gce-machine-configuration}[Google GCE]

[discrete]
[#_pool_name]
===== Nom de la réserve

Le nom de la réserve de machines.

[discrete]
[#_machine_count]
===== Nombre de machines

Le nombre de machines dans la réserve.

[discrete]
[#_roles]
===== Rôles

Option pour attribuer des rôles etcd, de plan de contrôle et de travail aux nœuds.

[#_advanced]
==== Avancé

[#_auto_replace]
===== Remplacement automatique

La durée pendant laquelle les nœuds peuvent être inaccessibles avant d'être automatiquement supprimés et remplacés.

[#_drain_before_delete]
===== Vidage avant suppression

Permet de vider les nœuds en évacuant tous les pods avant que le nœud ne soit supprimé.

[#_kubernetes_node_labels]
===== Étiquettes des nœuds Kubernetes

Ajoutez https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[étiquettes] aux nœuds pour aider à l'organisation et à la sélection des objets.

Pour plus de détails sur les exigences de syntaxe des étiquettes, consultez la https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set[documentation Kubernetes.]

[#_taints]
===== Taints

Ajoutez https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[taints] aux nœuds pour empêcher les pods d'être planifiés ou exécutés sur les nœuds, à moins que les pods n'aient des tolérances correspondantes.

[#_cluster_configuration]
=== Configuration de la grappe

[#_basics]
==== Basiques

[#_kubernetes_version]
===== Kubernetes Version

La version de Kubernetes installée sur vos nœuds de cluster.

Pour des détails sur la mise à niveau ou le retour en arrière de Kubernetes, reportez-vous à {xref-ds-backup-restore}[Mise à niveau de Kubernetes].

[#_pod_security_admission_configuration_template]
===== Modèle de configuration d'admission de sécurité des pods

Le {xref-psact}[modèle de configuration d'admission de sécurité des pods] par défaut pour le cluster.

[#_encrypt_secrets]
===== Chiffrer les secrets

Option pour activer ou désactiver le chiffrement des secrets. Lorsqu'il est activé, les secrets sont chiffrés à l'aide d'une clé AES-CBC. S'il est désactivé, les secrets précédemment chiffrés ne sont pas lisibles tant que le chiffrement n'est pas réactivé. Pour plus de détails, reportez-vous à la https://documentation.suse.com/cloudnative/k3s/latest/en/security/secrets-encryption.html[documentation K3s].

[#_project_network_isolation]
===== Isolation du réseau de projet

Si votre fournisseur de réseau permet l'isolation du réseau de projet, vous pouvez choisir d'activer ou de désactiver la communication inter-projets.

[#_selinux]
===== SELinux

Option pour activer ou désactiver le support de https://documentation.suse.com/cloudnative/k3s/latest/en/advanced.html#_selinux_support[SELinux].

[#_coredns]
===== CoreDNS

Par défaut, https://coredns.io/[CoreDNS] est installé en tant que fournisseur DNS par défaut. Si CoreDNS n'est pas installé, un autre fournisseur DNS doit être installé par vos soins. Référez-vous à la https://documentation.suse.com/cloudnative/k3s/latest/en/networking/networking-services.html#_coredns[documentation K3s] pour plus de détails.

[#_klipper_service_lb]
===== Service LB Klipper

Option pour activer ou désactiver le répartiteur de charge du service https://github.com/rancher/klipper-lb[Klipper]. Référez-vous à la https://documentation.suse.com/cloudnative/k3s/latest/en/networking/networking-services.html#_service_load_balancer[documentation K3s] pour plus de détails.

[#_traefik_ingress]
===== Traefik Ingress

Option pour activer ou désactiver le proxy inverse HTTP et le répartiteur de charge https://traefik.io/[Traefik]. Pour plus de détails et d'options de configuration, consultez la https://documentation.suse.com/cloudnative/k3s/latest/en/networking/networking-services.html#_traefik_ingress_controller[documentation K3s].

[#_local_storage]
===== Stockage local

Option pour activer ou désactiver le https://documentation.suse.com/cloudnative/k3s/latest/en/storage.html[stockage local] sur le(s) nœud(s).

[#_metrics_server]
===== Metrics Server

Option pour activer ou désactiver le https://github.com/kubernetes-incubator/metrics-server[serveur de métriques]. Si activé, assurez-vous que le port 10250 est ouvert pour le trafic TCP entrant.

[#_add_on_config]
==== Configuration du produit complémentaire

Manifests Kubernetes supplémentaires, gérés en tant que https://kubernetes.io/docs/concepts/cluster-administration/addons/[produit complémentaire], à appliquer au cluster au démarrage. Référez-vous à la https://documentation.suse.com/cloudnative/k3s/latest/en/installation/packaged-components.html#_auto_deploying_manifests_addons[documentation K3s] pour plus de détails.

[#_agent_environment_vars]
==== Variables d'environnement de l'agent

Option pour définir des variables d'environnement pour les https://documentation.suse.com/cloudnative/k3s/latest/en/architecture.html[agents K3s]. Les variables d'environnement peuvent être définies à l'aide de paires clé-valeur. Référez-vous à la https://documentation.suse.com/cloudnative/k3s/latest/en/installation/configuration.html#_configuration_file[documentation K3] pour plus de détails.

[#_etcd]
==== etcd

[#_automatic_snapshots]
===== Instantanés automatiques

Option pour activer ou désactiver les instantanés etcd récurrents. Si activé, les utilisateurs ont la possibilité de configurer la fréquence des instantanés. Pour plus de détails, consultez la https://documentation.suse.com/cloudnative/k3s/latest/en/cli/etcd-snapshot.html#_creating_snapshots[documentation K3s].

[#_metrics]
===== Métriques

Option permettant de choisir si les métriques etcd doivent être exposées au public ou uniquement au sein du cluster.

[#_networking]
==== Réseautique

[#_cluster_cidr]
===== CIDR de cluster

CIDR de réseau IPv4/IPv6 à utiliser pour les IP des pods (par défaut{nbsp}: `10.42.0.0/16`).

Exemples de valeurs{nbsp}:

* IPv4 uniquement{nbsp}: `10.42.0.0/16`
* IPv6 uniquement{nbsp}: `2001:cafe:42::/56`
* Double pile{nbsp}: `10.42.0.0/16,2001:cafe:42::/56`

Pour des exigences et des limitations supplémentaires liées à la double pile ou à la mise en réseau IPv6 à pile unique, consultez les ressources suivantes{nbsp}:

* https://documentation.suse.com/cloudnative/k3s/latest/en/networking/basic-network-options.html#_dual_stack_ipv4_ipv6_networking[documentation K3s{nbsp}: Mise en réseau à double pile (IPv4 + IPv6)]
* https://documentation.suse.com/cloudnative/k3s/latest/en/networking/basic-network-options.html#_single_stack_ipv6_networking[documentation K3s{nbsp}: Mise en réseau IPv6 à pile unique]

[CAUTION]
====
Vous devez configurer le CIDR de service lors de la création initiale du cluster. Vous ne pouvez pas activer le CIDR de service sur un cluster existant après son démarrage.
====

[#_service_cidr]
===== CIDR de service

CIDR de réseau IPv4/IPv6 à utiliser pour les IP des services (par défaut{nbsp}: `10.43.0.0/16`).

Exemples de valeurs{nbsp}:

* IPv4 uniquement{nbsp}: `10.43.0.0/16` 
* IPv6 uniquement{nbsp}: `2001:cafe:43::/112` 
* Double pile{nbsp}: `10.43.0.0/16,2001:cafe:43::/112`

Pour des exigences et des limitations supplémentaires liées à la double pile ou à la mise en réseau IPv6 à pile unique, consultez les ressources suivantes{nbsp}:

* https://documentation.suse.com/cloudnative/k3s/latest/en/networking/basic-network-options.html#_dual_stack_ipv4_ipv6_networking[documentation K3s{nbsp}: Mise en réseau à double pile (IPv4 + IPv6)]
* https://documentation.suse.com/cloudnative/k3s/latest/en/networking/basic-network-options.html#_single_stack_ipv6_networking[documentation K3s{nbsp}: Mise en réseau IPv6 à pile unique]

[CAUTION]
====
Vous devez configurer le CIDR de service lors de la création initiale du cluster. Vous ne pouvez pas activer le CIDR de service sur un cluster existant après son démarrage.
====

[#_cluster_dns]
===== DNS de cluster

IP Cluster IPv4 pour le service coredns. Doit être dans votre plage de service-cidr (par défaut{nbsp}: `10.43.0.10`).

[#_cluster_domain]
===== Domaine de cluster

Sélectionnez le domaine pour le cluster. La valeur par défaut est `cluster.local`.

[#_nodeport_service_port_range]
===== Plage de ports de service NodePort

Option pour changer la plage de ports pouvant être utilisés pour https://kubernetes.io/docs/concepts/services-networking/service/#nodeport[NodePort services]. La valeur par défaut est `30000-32767`.

[#_truncate_hostnames]
===== Tronquer les noms d'hôtes

Option pour tronquer les noms d'hôtes à 15 caractères ou moins. Vous ne pouvez définir ce champ que lors de la création initiale du cluster. Vous ne pouvez pas activer ou désactiver la limite de 15 caractères après la création du cluster.

Ce paramètre n'affecte que les clusters provisionnés par machine. Étant donné que les clusters personnalisés définissent les noms d'hôtes lors de leur propre processus de création de nœuds, qui se déroule en dehors de Rancher, ce champ ne limite pas la longueur des noms d'hôtes des clusters personnalisés.

Tronquer les noms d'hôtes dans un cluster améliore la compatibilité avec les systèmes basés sur Windows. Bien que Kubernetes autorise des noms d'hôtes jusqu'à 63 caractères, les systèmes utilisant NetBIOS limitent les noms d'hôtes à 15 caractères ou moins.

[#_tls_alternate_names]
===== Noms alternatifs TLS

Ajouter des noms d'hôtes ou des adresses IPv4/IPv6 en tant que noms alternatifs de sujet sur le certificat TLS du serveur.

[#_stack_preference]
===== Préférence de pile

Choisissez la pile réseau pour le cluster. Cette option affecte{nbsp}:

* L'adresse utilisée pour les sondes de santé et de disponibilité des composants tels que Calico, etcd, kube-apiserver, kube-scheduler, kube-controller-manager et kubelet.
* L'URL du serveur dans le `authentication-token-webhook-config-file` pour le point de terminaison de cluster autorisé.
* Le paramètre `advertise-client-urls` pour etcd lors de la restauration de l'instantané.

Les options sont `ipv4`, `ipv6`, `dual`{nbsp}:

* Lorsqu'il est défini sur `ipv4`, le cluster utilise `127.0.0.1`
* Lorsqu'il est défini sur `ipv6`, le cluster utilise `[::1]`
* Lorsqu'il est défini sur `dual`, le cluster utilise `localhost`

La préférence de pile doit correspondre à la configuration réseau du cluster{nbsp}:

* Définir sur `ipv4` pour des clusters uniquement IPv4
* Définir sur `ipv6` pour des clusters uniquement IPv6
* Définir sur `dual` pour des clusters à double pile

[CAUTION]
====
S'assurer que la configuration de l'adresse de boucle est correcte est essentiel pour un approvisionnement réussi du cluster.
Pour plus d'informations, consultez la page {xref-node-reqs}[Exigences des nœuds].
====

[#_authorized_cluster_endpoint]
===== Point de terminaison de cluster autorisé

Le point de terminaison de cluster autorisé peut être utilisé pour accéder directement au serveur API Kubernetes, sans nécessiter de communication via Rancher.

Pour plus de détails sur le fonctionnement d'un point de terminaison de cluster autorisé et pourquoi il est utilisé, consultez la section {xref-arch-com-ds-cluster}#_4_authorized_cluster_endpoint[architecture.]

Nous recommandons d'utiliser un équilibreur de charge avec le point de terminaison de cluster autorisé. Pour plus de détails, consultez la section {xref-arch-rec}#_architecture_for_an_authorized_cluster_endpoint_ace[architecture recommandée.]

[#_registries]
==== Registres

Sélectionnez le dépôt d'images à partir duquel tirer les images de Rancher. Pour plus de détails et d'options de configuration, consultez la https://documentation.suse.com/cloudnative/k3s/latest/en/installation/private-registry.html[documentation K3s].

[#_upgrade_strategy]
==== Stratégie de mise à niveau

[#_control_plane_concurrency]
===== Concurrence du plan de contrôle

Sélectionnez combien de nœuds peuvent être mis à niveau en même temps. Peut être un nombre fixe ou un pourcentage.

[#_worker_concurrency]
===== Concurrence des travailleurs

Sélectionnez combien de nœuds peuvent être mis à niveau en même temps. Peut être un nombre fixe ou un pourcentage.

[#_drain_nodes_control_plane]
===== Vider les nœuds (plan de contrôle)

Option pour supprimer tous les pods du nœud avant la mise à niveau.

[#_drain_nodes_worker_nodes]
===== Vider les nœuds (nœuds de travail)

Option pour supprimer tous les pods du nœud avant la mise à niveau.

[#_advanced_1]
==== Avancé

Option pour définir des options kubelet pour différents nœuds. Pour les options disponibles, consultez la https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/[documentation Kubernetes].

[#_cluster_config_file_reference]
== Référence du fichier de configuration du cluster

Modifier les clusters en YAML vous permet de définir des configurations déjà listées dans <<_configuration_options_in_the_rancher_ui,Options de configuration dans l'interface Rancher>>, ainsi que de définir des paramètres spécifiques à Rancher.

.Cliquez pour développer *Exemple d'extrait de fichier de configuration de cluster*
[%collapsible]
======
apiVersion: provisioning.cattle.io/v1
kind: Cluster
spec:
  cloudCredentialSecretName: cattle-global-data:cc-fllv6
  clusterAgentDeploymentCustomization: {}
  fleetAgentDeploymentCustomization: {}
  kubernetesVersion: v1.26.7+k3s1
  localClusterAuthEndpoint: {}
  rkeConfig:
    additionalManifest: ""
    chartValues: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      disable-apiserver: false
      disable-cloud-controller: false
      disable-controller-manager: false
      disable-etcd: false
      disable-kube-proxy: false
      disable-network-policy: false
      disable-scheduler: false
      etcd-expose-metrics: false
      kube-apiserver-arg:
        - audit-policy-file=/etc/rancher/k3s/user-audit-policy.yaml
        - audit-log-path=/etc/rancher/k3s/user-audit.logs
      profile: null
      secrets-encryption: false
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      machineConfigRef:
        kind: Amazonec2Config
        name: nc-test-pool1-pwl5h
      name: pool1
      quantity: 1
      unhealthyNodeTimeout: 0s
      workerRole: true
    machineSelectorConfig:
      - config:
          docker: false
          protect-kernel-defaults: false
          selinux: false
    machineSelectorFiles:
      - fileSources:
          - configMap:
              name: ''
            secret:
              name: audit-policy
              items:
                - key: audit-policy
                  path: /etc/rancher/k3s/user-audit-policy.yaml
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
======

[#_additionalmanifest]
=== additionalManifest

Spécifiez des manifestes supplémentaires à livrer aux nœuds du plan de contrôle.

La valeur est une chaîne de caractères et sera placée au chemin `/var/lib/rancher/k3s/server/manifests/rancher/addons.yaml` sur les nœuds cibles.

Exemple :

[,yaml]
----
additionalManifest: |-
  apiVersion: v1
  kind: Namespace
  metadata:
    name: name-xxxx
----

[NOTE]
====

Si vous souhaitez personnaliser les graphiques du système, vous devez utiliser le champ `chartValues` comme décrit ci-dessous.

Des alternatives, telles que l'utilisation d'un HelmChartConfig pour personnaliser les graphiques du système via `additionalManifest`, peuvent entraîner un comportement inattendu, en raison de la présence de plusieurs HelmChartConfigs pour le même graphique.
====


[#_chartvalues]
=== chartValues

Spécifiez les valeurs pour les graphiques du système installés par K3s.

Pour plus d'informations sur la façon dont K3s gère les paquets, veuillez vous référer à https://documentation.suse.com/cloudnative/k3s/latest/en/installation/packaged-components.html[la documentation K3s].

Exemple :

[,yaml]
----
chartValues:
    chart-name:
        key: value
----

[#_machineglobalconfig]
=== machineGlobalConfig

Spécifiez les configurations de K3s. Tout changement de configuration effectué ici s'appliquera à chaque nœud. Les options de configuration disponibles dans la https://documentation.suse.com/cloudnative/k3s/latest/en/cli/server.html[version autonome de k3s] peuvent être appliquées ici.

Exemple :

[,yaml]
----
machineGlobalConfig:
    etcd-arg:
        - key1=value1
        - key2=value2
----

Pour faciliter la mise en place des fichiers sur les nœuds à l'avance, Rancher s'attend à ce que les valeurs suivantes soient incluses dans la configuration, tandis que K3s s'attend à ce que les valeurs soient saisies sous forme de chemins de fichiers :

* registre-privé
* flannel-conf

Rancher livre les fichiers au chemin `/var/lib/rancher/k3s/etc/config-files/<option>` dans les nœuds cibles et définit les options appropriées dans le serveur K3s.

Exemple :

[,yaml]
----
apiVersion: provisioning.cattle.io/v1
kind: Cluster
spec:
  rkeConfig:
    machineGlobalConfig:
      private-registry: |
        mirrors:
          docker.io:
            endpoint:
              - "http://mycustomreg.com:5000"
        configs:
          "mycustomreg:5000":
            auth:
              username: xxxxxx # this is the registry username
              password: xxxxxx # this is the registry password
----

[#_machineselectorconfig]
=== machineSelectorConfig

`machineSelectorConfig` est identique à <<_machineglobalconfig,`machineGlobalConfig`>> sauf qu'un sélecteur <<_kubernetes_node_labels,label>> peut être spécifié avec la configuration. La configuration ne sera appliquée qu'aux nœuds qui correspondent au sélecteur d'étiquettes fourni.

Plusieurs entrées `config` sont autorisées, chacune spécifiant son propre `machineLabelSelector`. Un utilisateur peut spécifier `matchExpressions`, `matchLabels`, les deux ou aucun. Omettre la section `machineLabelSelector` de ce champ a le même effet que de mettre la configuration dans la section `machineGlobalConfig`.

Exemple :

[,yaml]
----
machineSelectorConfig
  - config:
      config-key: config-value
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
----

[#_machineselectorfiles]
=== machineSelectorFiles

[NOTE]
====

Cette fonctionnalité est disponible dans Rancher v2.7.2 et versions ultérieures.
====


Livrer des fichiers aux nœuds, afin que les fichiers puissent être en place avant de lancer les processus du serveur ou de l'agent K3s.
Le contenu du fichier est récupéré soit d'un secret, soit d'un configmap. Les nœuds cibles sont filtrés par le `machineLabelSelector`.

Exemple :

[,yaml]
----
machineSelectorFiles:
  - fileSources:
      - secret:
          items:
            - key: example-key
              path: path-to-put-the-file-on-nodes
              permissions: 644 (optional)
              hash: base64-encoded-hash-of-the-content (optional)
          name: example-secret-name
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
  - fileSources:
      - configMap:
          items:
            - key: example-key
              path: path-to-put-the-file-on-nodes
              permissions: 644 (optional)
              hash: base64-encoded-hash-of-the-content (optional)
          name: example-configmap-name
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
----

Le secret ou le configmap doit répondre aux exigences suivantes{nbsp}:

. Il doit se trouver dans l'espace de noms `fleet-default` où l'objet Cluster existe.
. Il doit avoir l'annotation `rke.cattle.io/object-authorized-for-clusters: cluster-name1,cluster-name2`, qui permet aux clusters cibles de l'utiliser.

[TIP]
====

Le tableau de bord Rancher fournit un formulaire facile à utiliser pour créer le secret ou le configmap.
====


Exemple :

[,yaml]
----
apiVersion: v1
data:
  audit-policy: >-
    IyBMb2cgYWxsIHJlcXVlc3RzIGF0IHRoZSBNZXRhZGF0YSBsZXZlbC4KYXBpVmVyc2lvbjogYXVkaXQuazhzLmlvL3YxCmtpbmQ6IFBvbGljeQpydWxlczoKLSBsZXZlbDogTWV0YWRhdGE=
kind: Secret
metadata:
  annotations:
    rke.cattle.io/object-authorized-for-clusters: cluster1
  name: name1
  namespace: fleet-default
----
