= {turtles-product-name}
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-09-03
:page-revdate: {revdate}
:community-path: integrations-in-rancher/cluster-api/index.adoc 
:product-path: integrations/cluster-api/cluster-api.adoc
ifeval::["{build-type}" != "community"]
:url-cluster-api-index: https://documentation.suse.com/cloudnative/cluster-api/{turtles-docs-version}/en/index.html
:url-cluster-api-capiprovider: https://documentation.suse.com/cloudnative/cluster-api/{turtles-docs-version}/en/reference/capiprovider.html
:xref-turtles-overview: xref:integrations/cluster-api/overview.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-cluster-api-index: https://turtles.docs.rancher.com/turtles/{turtles-docs-version}/en/index.html
:url-cluster-api-capiprovider: https://turtles.docs.rancher.com/turtles/{turtles-docs-version}/en/reference/capiprovider.html
:xref-turtles-overview: xref:integrations-in-rancher/cluster-api/overview.adoc
endif::[]

{url-cluster-api-index}[{turtles-product-name}] é um https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#operators-in-kubernetes[Operador Kubernetes] que gerencia o ciclo de vida de clusters Kubernetes provisionados, fornecendo integração entre sua API de Cluster (CAPI) e o Rancher. Com o Rancher Turtles, você pode:

* Importar clusters CAPI para o Rancher, instalando o Agente de Cluster do Rancher em clusters provisionados pelo CAPI.
* Gerenciar o https://cluster-api-operator.sigs.k8s.io/[Operador CAPI] usando o recurso {url-cluster-api-capiprovider}[CAPIProvider].

A seção {xref-turtles-overview}[Visão Geral] descreve opções de instalação, arquitetura do Rancher Turtles e uma breve demonstração. Para mais detalhes, veja a {url-cluster-api-index}[{turtles-product-name} documentação].
