= Añadiendo Usuarios a Proyectos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/add-users-to-projects.adoc 
:product-path: cluster-admin/project-admin/add-users-to-projects.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/usuarios/authn-y-authz/gestionar-control-de-acceso-basado-en-funciones-rbac/roles-de-cluster-y-proyecto.adoc
:xref-projects-and-namespaces: xref:cluster-admin/manage-clusters/projects-and-namespaces.adoc
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-locked-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:guías-como-hacer/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/gestionar-control-de-acceso-basado-en-funciones-rbac/roles-de-cluster-y-proyecto.adoc
:xref-projects-and-namespaces: xref:how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces.adoc
:xref-custom-roles: xref:como-guías/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/gestionar-control-de-acceso-basado-en-funciones-rbac/roles-personalizados.adoc
:xref-locked-roles: xref:como-guías/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/gestionar-control-de-acceso-basado-en-funciones-rbac/roles-bloqueados.adoc
endif::[]

Si deseas proporcionar a un usuario acceso y permisos a proyectos y recursos _específicos_ dentro de un clúster, asigna al usuario una membresía de proyecto.

Puedes añadir miembros a un proyecto mientras se crea, o añadirlos a un proyecto existente.

[TIP]
====

¿Quieres proporcionar a un usuario acceso a _todos_ los proyectos dentro de un clúster? Consulta {xref-cluster-project-roles}[Añadiendo miembros al clúster] en su lugar.
====


[#_adding_members_to_a_new_project]
== Añadiendo miembros a un nuevo proyecto

Puedes añadir miembros a un proyecto mientras lo creas (recomendado si es posible). Para obtener detalles sobre cómo crear un nuevo proyecto, consulta la {xref-projects-and-namespaces}[sección de administración del clúster.]

[#_adding_members_to_an_existing_project]
== Añadiendo miembros a un proyecto existente

Tras la creación del proyecto, puedes añadir usuarios como miembros del proyecto para que puedan acceder a sus recursos.

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, ve al clúster donde deseas añadir miembros a un proyecto y haz clic en *Explorar*.
. Haz clic en menu:Clúster[Proyectos/Espacios de nombres].
. Ve al proyecto donde deseas añadir miembros. Junto al botón *Crear espacio de nombres* encima del nombre del proyecto, haz clic en *☰*. Seleccione *Editar Configuración*.
. En la pestaña *Miembros*, haz clic en *Añadir*.
. Busca al usuario o grupo que deseas añadir al proyecto.
+
[NOTE]
.Notas
====
* Se deben escribir al menos 2 caracteres en el cuadro de búsqueda para que aparezcan resultados.
* Los usuarios se pueden buscar según su nombre de usuario o nombre para mostrar.
* La búsqueda se basa en prefijos (por ejemplo, un usuario llamado `Stan Dard` aparecerá al buscar `Sta`, pero no al buscar `Dar`) y es sensible a mayúsculas y minúsculas.
====
+
Si la autenticación externa está configurada:

 ** Rancher devuelve usuarios de tu fuente de autenticación externa a medida que escribes.
 ** Un menú desplegable te permite añadir grupos en lugar de usuarios individuales. El menú desplegable solo lista los grupos en los que tú, el usuario conectado, estás incluido.

+

[NOTE]
====
Si has iniciado sesión como un usuario local, los usuarios externos no se mostrarán en tus resultados de búsqueda.
====


. Asigna al usuario o grupo roles de *Proyecto*.
+
{xref-cluster-project-roles}[¿Cuáles son los roles de proyecto?]
+

[NOTE]
.Notas:
====

 ** Los usuarios asignados al rol `Owner` o `Member` para un proyecto heredan automáticamente el rol `namespace creation`. Sin embargo, este rol es un https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole[ClusterRole de Kubernetes], lo que significa que su alcance se extiende a todos los proyectos en el clúster. Por lo tanto, los usuarios asignados explícitamente al rol `Owner` o `Member` para un proyecto pueden crear o eliminar espacios de nombres en otros proyectos a los que están asignados, incluso con solo el rol `Read Only` asignado.
 ** Por defecto, el rol de Rancher de `project-member` hereda del rol `Kubernetes-edit`, y el rol `project-owner` hereda del rol `Kubernetes-admin`. Como tal, tanto los roles `project-member` como `project-owner` permitirán la gestión de espacios de nombres, incluyendo la capacidad de crear y eliminar espacios de nombres.
 ** Para roles de `Custom`, puedes modificar la lista de roles individuales disponibles para asignar.
  *** Para agregar roles a la lista, {xref-custom-roles}[Agregar un rol personalizado].
  *** Para quitar roles de la lista, {xref-locked-roles}[Bloquear/Desbloquear Roles].

+
====


*Resultado:* Los usuarios elegidos se añaden al proyecto.

* Para revocar la membresía del proyecto, selecciona al usuario y haz clic en *Eliminar*. Esta acción elimina la membresía, no al usuario.
* Para modificar los roles de un usuario en el proyecto, elimínalo del proyecto y luego vuélvelo a añadir con los roles modificados.
