= Google Compute Engine クラスターの作成
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-google-compute-engine-cluster.adoc 
:product-path: cluster-deployment/infra-providers/gce/gce.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-infra-gce-machine-config: xref:cluster-deployment/infra-providers/gce/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc
:xref-infra-gce-machine-config: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/google-gce.adoc
endif::[]

このセクションでは、Rancher を使用して Google Cloud Platform (GCP) 上で Google Compute Engine (GCE) を通じて {url-rke2-landing-page}[RKE2] または {url-k3s-landing-page}[K3s] Kubernetes クラスターをプロビジョニングする方法を学びます。

まず、Rancher UI で GCE ノードドライバーを有効にします。次に、必要な権限を持つ GCP サービスアカウントを作成し、JSON キーファイルを生成する手順に従います。このキーファイルは、Rancher でクラウドクレデンシャルを作成するために使用されます。

次に、Rancher で GCE クラスターを作成し、クラスターを構成する際に、マシンプールを定義します。各マシンプールには、etcd、controlplane、または worker の Kubernetes ロールがあります。Rancher は新しいノードに RKE2 をインストールし、マシンプールによって定義された Kubernetes ロールで各ノードを設定します。

. <<_enable_the_gce_node_driver>>
. <<_create_a_cloud_credential>>
. <<_create_a_cluster_using_the_cloud_credential>>
. <<_gce_best_practices>>

[#_prerequisites]
== 前提条件

.  有効な Google Cloud Platform アカウントとプロジェクト。
.  GCP サービスアカウントの JSON キーファイル。このキーに関連付けられたサービスアカウントは、次の IAM ロールを持っている必要があります：
.. **Compute Admin**
.. **Service Account User**
.. **ビューア**
. VM をプロビジョニングするための VPC ネットワーク。

サービスアカウントキーの作成と管理に関する詳細は、 https://cloud.google.com/iam/docs/service-account-overview[GCP ドキュメント]を参照してください。

[#_enable_the_gce_node_driver]
== GCE ノードドライバーを有効にする

GCE ノードドライバーは、Rancher ではデフォルトで有効になっていません。GCE クラスターをプロビジョニングしたり、GCE 特有の CRD を操作したりする前に、有効にする必要があります。

. **☰ > クラスター管理**をクリックします。
. 左側にある**ドライバー**をクリックします。
. **ノードドライバー**タブを開きます。
. **Google GCE**ドライバーを見つけて、**⋮ > 有効化**を選択します。

[#_create_a_cloud_credential]
== クラウド資格情報を作成します。

. **☰ > クラスター管理**をクリックします。
. **クラウド資格情報**をクリックします。
. ［**作成**］をクリックします。
. **Google**をクリックします。
. GCP サービスアカウントの JSON キーファイルを入力してください。
. ［**作成**］をクリックします。

**結果:**クラスター内のノードをプロビジョニングするために使用されるクラウド資格情報を作成しました。これらの資格情報は他のクラスターでも再利用できます。サービスアカウントに付与された権限に応じて、この資格情報は GKE クラスターでも使用される場合があります。

[#_create_a_cluster_using_the_cloud_credential]
== クラウド資格情報を使用してクラスターを作成します。

. **☰ > クラスター管理**をクリックします。
. **クラスター**ページで、**作成**をクリックします。
. **Google GCE**をクリックします。
. **クラウド資格情報**を選択し、VM を作成する GCP プロジェクトを指定してください。
. **クラスター名**を入力してください。
. 各Kubernetesロールごとにマシンプールを作成してください。役割の割り当てと数に関する推奨事項については、[ベストプラクティス](use-new-nodes-in-an-infra-provider.md#node-roles)を参照してください。
.. 各マシンプールごとに、マシンの構成を定義してください。構成オプションに関する情報については、{xref-infra-gce-machine-config}[Google GCEマシン設定リファレンス]を参照してください。
. インストールするKubernetesのバージョン、使用するネットワークプロバイダー、およびプロジェクトネットワークの分離を有効にするかどうかを選択するには、**クラスター構成**を使用してください。クラスターの構成に関するヘルプについては、{xref-rke2-config}[RKE2]および{xref-k3s-config}[K3s]クラスター構成リファレンスを参照してください。
. クラスターのユーザー認可を構成するには、**メンバー役割**を使用してください。**メンバーを追加**をクリックして、クラスターにアクセスできるユーザーを追加してください。各ユーザーの権限を設定するには、**役割**のドロップダウンを使用してください。
. ［**作成**］をクリックします。

**結果:**

クラスターが作成され、状態が**プロビジョニング**に割り当てられました。Rancherがクラスターを立ち上げています。

状態が**アクティブ**に更新された後、クラスターにアクセスできます。

**アクティブ**なクラスターには、2つのプロジェクトが割り当てられています：

* `Default`、`default`名前空間を含む
* `System`、`cattle-system`、`traefik`、`kube-public`、および`kube-system`名前空間を含む

[#_gce_best_practices]
== GCEベストプラクティス

[#_external_firewall_rules_open_ports_and_ace]
=== 外部ファイアウォールルール、オープンポート、およびACE

プロビジョニングされるクラスターが{xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[Authorized Cluster Endpoint (ACE)機能]を利用する場合、コントロールプレーンノードはポート`6443`を公開する必要があります。このポートは、すべてのクラスター ノードに公開されるのを防ぎ、Rancher によって作成されるファイアウォールルールの数を減らすために、デフォルトのマシンプール構成では公開されていません。

ACEが期待通りに機能するためには、マシンプール構成UIの`Show Advanced`セクションの下にある`Expose external ports`チェックボックスを有効にして、Rancher UIでコントロールプレーンマシンプールを構成する際にこのポートを指定する必要があります。または、GCPでカスタムファイアウォールルールを手動で作成し、関連するネットワークタグをコントロールプレーンマシンプール構成に提供することもできます。

[#_internal_firewall_rules]
=== 内部ファイアウォールルール

Rancherは、指定されたVPCネットワーク内でクラスター ノード間の通信を容易にするために、ファイアウォールルールとネットワークタグを自動的に作成します。このルールには、RKE2/K3sクラスターを作成するために必要な最小限のポートが含まれます。

クラスター ノード間で内部に公開されるポートの数を拡張する必要がある場合は、新しいファイアウォールルールを手動で作成し、関連するマシンプールに関連付けられたネットワークタグを割り当てる必要があります。必要に応じて、クラスターを作成または更新する際に、各マシンプールに対して内部ファイアウォールルールの自動作成を無効にすることができます。

[#_cross_network_deployments]
=== クロスネットワークデプロイ

異なるマシンプールを異なるVPCネットワークにデプロイすることは可能ですが、Rancherによって作成された内部ファイアウォールルールは、デフォルトではこの構成をサポートしていません。異なるネットワークにマシンプールを作成するには、異なるネットワーク内のノード間の通信を容易にするために、追加のファイアウォールルールを手動で作成する必要があります。

[#_optional_next_steps]
== オプションの次のステップ

クラスターを作成した後、Rancher UIを通じてアクセスできます。ベストプラクティスとして、クラスターにアクセスするためのこれらの代替方法を設定することをお勧めします：

* **kubectl CLIを使用してクラスターにアクセスする:**{xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[これらの手順]に従って、ワークステーションでkubectlを使用してクラスターにアクセスしてください。この場合、Rancherサーバーの認証プロキシを通じて認証され、その後Rancherがダウンストリームクラスターに接続します。この方法を使用すると、Rancher UIなしでクラスターを管理できます。
* **認可されたクラスターエンドポイントを使用して、kubectl CLIでクラスターにアクセスします:**{xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[これらの手順]に従って、Rancherを介さずにkubectlでクラスターに直接アクセスします。Rancherに接続できない場合でもクラスターにアクセスできるように、この代替方法を設定することをお勧めします。
