= {rancher-prime}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/prime.adoc 
:product-path: sobre-rancher/prime.adoc

O SUSE Rancher apresenta o Rancher Prime --, uma evolução do Rancher -- a partir da versão v2.7. O Rancher Prime é a nova oferta empresarial disponível comercialmente do Rancher, construída sobre o mesmo código aberto. O projeto Rancher continuará sendo 100% código aberto. O Rancher Prime agrega valor adicional com garantias de segurança superiores, ciclos de vida estendidos, acesso a arquiteturas focadas e recomendações do Kubernetes. O Rancher Prime também oferecerá opções para receber suporte de produção para projetos inovadores do Rancher. Com o Rancher Prime, os ativos de instalação são hospedados em um registro confiável de propriedade e gerenciado pelo Rancher.

Para começar com o Rancher Prime, https://www.rancher.com/quick-start[vá para esta página] e preencha o formulário.
