= O que é o comando {rancher-product-name}?
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-02-05
:page-revdate: {revdate}
:community-path: rancher-manager.adoc 
:product-path: about-rancher/what-is-rancher.adoc
:description: O Rancher agrega um valor significativo ao Kubernetes: gerenciando centenas de clusters a partir de uma única interface, centralizando o RBAC, permitindo monitoramento e alertas. Leia mais.
:sidebar_label: O que é o Rancher?
:slug: /

O Rancher é uma ferramenta de gerenciamento do Kubernetes para implantar e executar clusters em qualquer lugar e em qualquer provedor.

O Rancher pode provisionar o Kubernetes de um provedor hospedado, provisionar nós de computação e, em seguida, instalar o Kubernetes neles, ou importar clusters Kubernetes existentes executados em qualquer lugar.

O Rancher agrega um valor significativo ao Kubernetes, primeiro centralizando a autenticação e o controle de acesso com base em função (RBAC) para todos os clusters, permitindo que administradores globais controlem o acesso aos clusters de um único local.

Em seguida, ele permite monitoramento e alertas detalhados para os clusters e seus recursos, envia registros a fornecedores externos e se integra diretamente ao Helm por meio do Catálogo de Aplicativos. Se você tiver um sistema CI/CD externo, pode conectá-lo ao Rancher, mas se não tiver, o Rancher inclui até mesmo o Fleet para ajudá-lo a implantar e fazer upgrade automaticamente as cargas de trabalho.

O Rancher é uma plataforma _completa_ de gerenciamento de contêiner para Kubernetes, oferecendo as ferramentas para executar o Kubernetes com sucesso em qualquer lugar.
