= ブートストラップパスワードの設定
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/bootstrap-password.adoc 
:product-path: installation-and-upgrade/resources/bootstrap-password.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-users-and-groups: xref:rancher-admin/users/authn-and-authz/manage-users-and-groups.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-users-and-groups: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/manage-users-and-groups.adoc
endif::[]

Rancherをインストールすると、最初の管理者アカウントのためにブートストラップパスワードを設定できます。

ブートストラップパスワードを設定しないことを選択した場合、Rancherは最初の管理者アカウントのためにランダムにブートストラップパスワードを生成します。

ブートストラップパスワードの設定方法の詳細は、以下を参照してください。

[#_password_requirements]
== Password Requirements

ブートストラップパスワードは任意の長さにできます。

最初の管理者アカウントのパスワードを初回ログイン後にリセットする場合、新しいパスワードは少なくとも12文字以上でなければなりません。

ユーザーアカウントの最小パスワード長を{xref-users-and-groups}#_minimum_password_length[カスタマイズする]ことができますが、制限があります。

最小パスワード長は2から256の間の任意の正の整数値にできます。小数値と先頭のゼロは許可されていません。

[#_specifying_the_bootstrap_password]
== ブートストラップパスワードの指定

{xref-install-rancher}[Rancherのインストール]中に、Rancher Helmチャートの他のフラグと一緒に`bootstrapPassword`を設定します。次に例を示します。

[,bash]
----
helm install rancher rancher-<chart-repo>/rancher \
  --set bootstrapPassword=<password>
----

## ブートストラップパスワードの取得

ブートストラップパスワードはDockerコンテナのログに保存されます。Rancherがインストールされた後、UIはインストール方法に基づいてパスワードを取得する方法の指示を表示します。

[,bash]
----
kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{ .data.bootstrapPassword|base64decode}}{{ "\n" }}'
----
