= カスタム CA ルート証明書について
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/custom-ca-root-certificates.adoc 
:product-path: installation-and-upgrade/resources/custom-ca-root-certificates.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
endif::[]

アプリを外部に公開していない内部の本番環境で Rancher を使用している場合は、プライベート証明書機関 (CA) からの証明書を使用してください。

Rancher がアクセスする必要があるサービスは、カスタムまたは内部 CA ルート証明書、いわゆる自己署名証明書で構成されていることがあります。サービスから提示された証明書が Rancher によって検証できない場合、次のエラーが表示されます: `x509: certificate signed by unknown authority`。

証明書を検証するには、CA ルート証明書を Rancher に追加する必要があります。Rancher は Go で書かれているため、環境変数 `SSL_CERT_DIR` を使用して、コンテナ内の CA ルート証明書が格納されているディレクトリを指すことができます。CA ルート証明書のディレクトリは、Rancher コンテナを起動する際に Docker ボリュームオプション (`-v host-source-directory:container-destination-directory`) を使用してマウントできます。

Rancher がアクセスできるサービスの例:

* カタログ
* 認証プロバイダー
* ノードドライバーを使用してホスティング/クラウド API にアクセスする

[#_installing_with_the_custom_ca_certificate]
== カスタム CA 証明書を使用してインストールする

プライベート CA 証明書をマウントして Rancher コンテナを起動する方法の詳細については、インストールドキュメントを参照してください:

* {xref-helm-chart-options}#_additional_trusted_cas[Kubernetes install options for Additional Trusted CAs]
