= Orientações de Migração do RKE1 para {rke2-product-name} Windows
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/guias-para-novos-usuários/kubernetes-clusters-no-rancher-configuração/use-windows-clusters/orientações-migração-carga-de-trabalho.adoc 
:product-path: cluster-deployment/custom-clusters/windows/workload-migration-guidance.adoc

CAUTION: O conteúdo deste documento não está coberto pelo SLA do Suporte Rancher. Por favor, prossiga com cautela.

Este documento aborda como os usuários finais podem migrar suas cargas de trabalho do Windows do RKE1 para o RKE2.

[#_rke1_windows_scheduling]
== RKE1 Windows Scheduling

O agendamento de cargas de trabalho do Windows no RKE1 é baseado em taints e tolerâncias.

Cada nó Linux em um cluster Windows RKE1, independentemente do papel atribuído a ele, terá uma taint padrão que impede que cargas de trabalho sejam agendadas nele, a menos que a carga de trabalho tenha uma tolerância configurada. Este é um recurso de design importante para clusters Windows RKE1, que foram projetados para executar apenas cargas de trabalho do Windows.

* Taint padrão do nó Linux RKE1 `NoSchedule`:

[,yml]
----
apiVersion: v1
kind: Node
spec:
  ...
  taints:
  - effect: NoSchedule
    key: cattle.io/os
    value: linux
----

{blank}

* Tolerância do Linux RKE1 `NoSchedule` para cargas de trabalho

A seguinte tolerância permitiria que uma carga de trabalho de um usuário final fosse agendada em qualquer nó Linux de um cluster Windows RKE1. Essas tolerâncias são usadas para vários serviços e cargas de trabalho essenciais do Rancher.

[,yml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
----

{blank}

* Alinhando-se às melhores práticas, quaisquer cargas de trabalho de usuários finais executadas em nós Linux seriam agendadas apenas nos que têm o papel de trabalhador:

[,yml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
            weight: 100
      ...
----

[#__rke2_product_name_windows_scheduling]
== {rke2-product-name} Agendamento do Windows

Com base no feedback e nas solicitações de suporte a cargas de trabalho híbridas, o RKE2 Windows foi projetado para suportar tanto cargas de trabalho Linux quanto Windows por padrão. O agendamento do RKE2 depende de seletores de nós por padrão. Esta é uma mudança significativa em relação ao RKE1, pois taints e tolerâncias não foram incorporados ao RKE2. Seletores de nós foram uma parte crítica dos clusters Windows RKE1, o que facilita a migração de suas cargas de trabalho.

[#_example_migrations]
== Exemplos de Migrações

[#_rke1_to_rke2_product_name_windows_workload]
=== RKE1 para {rke2-product-name} Carga de Trabalho do Windows

* Implantação do Windows RKE1 antes da migração:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: NotIn
                values:
                - linux
----

{blank}

* Implantação do Windows RKE2 migrada usando `NodeAffinity`:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      ...
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - windows
----

[#_rke1_windows_cluster_linux_only_deployment]
=== Implantação do Cluster Windows RKE1 somente para Linux

[IMPORTANT]
====
Ao utilizar seletores de nó e afinidade de nó, observe o seguinte:

* Se tanto `nodeSelector` quanto `nodeAffinity` forem especificados, ambos devem ser atendidos para que o `Pod` seja agendado em um nó.
* Se você especificar múltiplos `matchExpressions` associados a um único `nodeSelectorTerms`, então o `Pod` pode ser agendado em um nó apenas se todos os `matchExpressions` forem atendidos.
====

{blank}

* Implantação do cluster Windows RKE1 somente para Linux antes da migração, visando nós de trabalho Linux RKE1:

[,yml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
----

{blank}

* Implantação do cluster híbrido RKE2 somente para Linux migrada, visando nós de trabalhador Linux RKE2 usando seletores de nó:

[,yml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      nodeSelector:
        kubernetes.io/os: "linux"
        node-role.kubernetes.io/worker: "true"
----

{blank}

* Implantação do cluster híbrido RKE2 somente para Linux migrada, visando nós de trabalhador Linux RKE2 usando afinidade de nó:

[,yaml]
----
 apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
----

[#_rke1_windows_supported_windows_server_versions]
== Versões do Windows Server suportadas pelo Windows RKE1

[#_long_term_servicing_channel_ltsc]
=== Canal de Manutenção de Longo Prazo (LTSC)

* O Windows Server 2019 LTSC &#9989; atingirá o EOL principal em 9 de janeiro de 2024 e o EOL estendido em 9 de janeiro de 2029

[#_semi_annual_channel_sac]
=== Canal Semestral (SAC)

* O Windows Server 20H2 SAC &#10060; atingiu o EOL em 9 de agosto de 2022
* O Windows Server 2004 SAC &#10060; atingiu o EOL em 14 de dezembro de 2021
* O Windows Server 1909 SAC &#10060; atingiu o EOL em 11 de maio de 2021
* O Windows Server 1903 SAC &#10060; atingiu o EOL em 8 de dezembro de 2020
* O Windows Server 1809 SAC &#10060; atingiu o EOL em 10 de novembro de 2020

[#__rke2_product_name_windows_supported_windows_server_versions]
== {rke2-product-name} Versões do Windows Server Suportadas pelo Windows

[#_long_term_servicing_channel_in_rke2_product_name]
=== Canal de Manutenção de Longo Prazo em {rke2-product-name}

* O Windows Server 2019 LTSC &#9989; atingirá o EOL principal em 9 de janeiro de 2024 e o EOL estendido em 9 de janeiro de 2029
* O Windows Server 2022 LTSC &#9989; atingirá o EOL principal em 13 de outubro de 2026 e o EOL estendido em 13 de outubro de 2031

NOTE: SAC não é suportado no RKE2.

Para mais informações, consulte as seguintes referências:

* https://docs.microsoft.com/en-us/lifecycle/products/windows-server[Ciclo de Vida do Windows Server SAC]
* https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2022[Windows Server 2022 LTSC Lifecycle]
* https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2019[Windows Server 2019 LTSC Lifecycle]

[#_kubernetes_version_support]
== Suporte a Versões do Kubernetes

NOTE: Todas as versões listadas abaixo são suportadas por SLA de acordo com https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-7/[Matriz de Suporte do Rancher v2.6.7]. Qualquer versão não listada deve ser considerada como EOL e não suportada sob SLA pela SUSE.

[#_rancher_2_5_vs_rancher_2_6_support_matrix_for_windows_clusters]
=== Rancher 2.5 vs. Matriz de Suporte do Rancher 2.6 para Clusters Windows

*RKE1 vs. Versões do Kubernetes suportadas por clusters Windows RKE2:*

[cols=",^,^"]
|===
| Kubernetes Versions | RKE1 | RKE2

| 1.18
| &check;
|

| 1.19
| &check;
|

| 1.20
| &check;
|

| 1.21
| &check;
|

| 1.22
| &check;
| &check;

| 1.23
|
| &check;

| 1.24
|
| &check;

| 1.25+
|
| &check;
|===

[#_rancher_2_5_vs_rancher_2_6_supported_kubernetes_versions_for_provisioning_rke1_and_rke2_windows_clusters]
=== Rancher 2.5 vs. Versões do Kubernetes suportadas pelo Rancher 2.6 para Provisionamento de Clusters RKE1 e {rke2-product-name} Windows

[cols="^,^,^,^"]
|===
| Versões do Rancher | Kubernetes Versions | RKE1 | RKE2

| 2.5 - Aprovisionamento RKE1
| 1.18 1.19 1.20
| &check;
|

| 2.6 - Aprovisionamento RKE1
| 1.18 1.19 1.20 1.21 1.22
| &check;
|

| 2.6 - Aprovisionamento RKE2
| 1.22 1.23 1.24 1.25+
|
| &check;
|===

[#_guiding_migrations_of_workloads_to_rke2_product_name_windows]
== Orientando Migrações de Cargas de Trabalho para {rke2-product-name} Windows

Referenciando as tabelas em <<_rancher_2_5_vs_rancher_2_6_support_matrix_for_windows_clusters,Rancher 2.5 vs. Matriz de Suporte do Rancher 2.6 para Clusters Windows>> e <<_rancher_2_5_vs_rancher_2_6_supported_kubernetes_versions_for_provisioning_rke1_and_rke2_windows_clusters,Rancher 2.5 vs. Versões do Kubernetes Suportadas pelo Rancher 2.6 para Aprovisionamento de Clusters Windows RKE1 e RKE2>>, você encontrará a sobreposição nas versões do Kubernetes entre RKE1 e RKE2 que ocorre em 1.22. Esta será a versão base necessária para migrar cargas de trabalho do Windows RKE1 ao seguir a abordagem recomendada pelo Rancher.

[#_in_place_upgrade_of_rancher_2_5]
=== Atualização In-Place do Rancher 2.5

. Atualize a versão do Rancher para v2.6.5+.
. Atualize o(s) cluster(s) downstream do Windows RKE1 para RKE1 v1.22 usando a versão de patch mais recente disponível.
. Provisione um novo cluster downstream do Windows RKE2 usando RKE2 v1.22 com a versão de patch correspondente à qual o cluster Windows RKE1 se encontra.
. Inicie a migração das cargas de trabalho do Windows dos clusters RKE1 para RKE2.
. Realize testes de validação para garantir que não houve perda ou alteração de funcionalidade ao migrar seu aplicativo de RKE1 para RKE2.
. Após a realização bem-sucedida dos testes de validação, você pode optar por atualizar seu cluster RKE2 1.22.x para uma nova versão menor, como 1.23 ou 1.24.

[#_migrating_windows_workloads_to_a_new_rancher_environment]
=== Migrando Cargas de Trabalho do Windows para um Novo Ambiente Rancher

IMPORTANT: Para realizar qualquer uma das opções a seguir, é necessário o Rancher v2.6.5 ou superior.

*Ao usar versões de patch do Kubernetes correspondentes para RKE1 e RKE2:*

. Provisione um novo cluster downstream do Windows RKE2 usando RKE2 v1.22 com a versão de patch correspondente à qual o cluster Windows RKE1 se encontra.
. Inicie a migração das cargas de trabalho do Windows dos clusters RKE1 para RKE2.
. Realize testes de validação para garantir que não houve perda ou alteração de funcionalidade ao migrar seu aplicativo de RKE1 para RKE2.
. Após a realização bem-sucedida dos testes de validação, você pode optar por atualizar seu cluster RKE2 1.22.x para uma nova versão menor, como 1.23 ou 1.24.

*Ao usar uma versão de patch mais recente do Kubernetes para RKE2:*

. Provisione um novo cluster downstream do Windows RKE2 usando RKE2 v1.23 ou v1.24.
. Inicie a migração das cargas de trabalho do Windows dos clusters RKE1 para RKE2.
. Realize testes de validação para garantir que não houve perda ou alteração de funcionalidade ao migrar seu aplicativo de RKE1 para RKE2.
