= ConfigMaps
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc 
:product-path: cluster-admin/kubernetes-resources/configmaps.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
endif::[]

虽然大多数类型的Kubernetes秘密存储敏感信息，但 https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/[ConfigMaps]存储一般配置信息，例如一组配置文件。由于ConfigMaps不存储敏感信息，因此可以自动更新，因此在更新后不需要重新启动其容器（与大多数秘密类型不同，后者需要手动更新并重新启动容器以生效）。

ConfigMaps接受常见字符串格式的键值对，如配置文件或JSON数据块。上传 ConfigMap 后，任何工作负载都可以将其作为环境变量或卷挂载进行引用。

. 在左上角，单击*☰ > 集群管理*。
. 转到具有应引用ConfigMap的工作负载的集群，然后单击*Explore*。
. 在左侧导航栏中，单击menu:More Resources[内核> ConfigMaps]。
. 单击*创建*。
. 为 ConfigMap 输入一个*Name*。
+

[NOTE]
====
Kubernetes将ConfigMaps分类为 https://kubernetes.io/docs/concepts/configuration/secret/[secrets]，在一个项目或名称空间中没有两个秘密可以具有重复的名称。因此，为了防止冲突，您的 ConfigMaps 在工作区内必须具有唯一名称，不能与其他证书、注册表和秘密重复。
====


. 选择您要将ConfigMap添加到的*Namespace*。
. 在*Data*选项卡上，向您的ConfigMap添加一个键值对。根据需要添加尽可能多的值。 您可以通过复制和粘贴向ConfigMap添加多个键值对。或者，使用*Read from File*来添加数据。注意：如果您需要存储敏感数据，请{xref-secrets}[使用秘密]，而不是ConfigMap。
. 单击*创建*。

*结果：*您的ConfigMap已添加到名称空间。您可以在Rancher UI的menu:Resources[ConfigMaps]视图中查看它。

[#_whats_next]
== 下一步怎么办？

现在您已将ConfigMap添加到名称空间，您可以将其添加到您从源名称空间部署的工作负载中。您可以使用ConfigMap指定应用程序要使用的信息，例如：

* 应用程序环境变量。
* 为挂载到工作负载的卷指定参数。

有关将ConfigMaps添加到工作负载的更多信息，请参见 {xref-deploy-workloads}[部署工作负载]。
