= Configuração da Máquina GCE
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: guias-de-referência/configuração-do-cluster/downstream/configuração-da-máquina/google-gce.adoc 
:product-path: cluster-deployment/infra-providers/gce/machine-configuration.adoc

Para mais informações sobre o Google Cloud Platform (GCP) e o Google Compute Engine (GCE), consulte a documentação oficial https://cloud.google.com/docs[do GCP].

[#_basic_options]
== opções básicas

[#_zone]
=== Zona

A Região e Zona do GCP onde a VM será implantada. Por exemplo, `us-east1-b`.

[#_machine_image_project]
=== Projeto da Imagem da Máquina

O projeto da imagem ao qual as famílias de imagens desejadas pertencem.

[#_machine_image_family]
=== Família da Imagem da Máquina

A família de imagens à qual o sistema operacional da máquina desejada pertence.

[#_machine_image]
=== Imagem da Máquina

O sistema operacional que será instalado na VM.

[#_disk_type]
=== Tipo de Disco

O tipo do disco anexado à VM. Os tipos disponíveis podem diferir entre regiões.

[#_disk_size]
=== Tamanho do Disco

O tamanho do disco anexado à VM, em Gigabytes.

[#_machine_type]
=== Tipo de Máquina

O tipo de VM que será implantada. Os tipos de máquina determinam o número de recursos (vCPU, RAM, etc.) alocados para cada nó.

[#_network]
=== Rede

A rede VPC onde a VM será criada. Esse valor não pode ser alterado uma vez que o pool de máquinas tenha sido provisionado.

[#_subnet]
=== Sub-rede

A sub-rede VPC onde a VM será criada. Esse valor não pode ser alterado uma vez que o pool de máquinas tenha sido provisionado.

[#_username]
=== Nome de usuário

Um nome de usuário personalizado definido como o usuário padrão da VM GCE. 

[#_external_address]
=== Endereço Externo

O endereço IP externo desejado para a VM GCE.

[#_scopes]
=== Escopos

Uma lista de escopos OAuth2 que permitem que a VM acesse outras APIs do GCP.

[#_allow_internal_communication]
=== Permitir Comunicação Interna

Por padrão, uma regra de gateway de segurança VPC é criada automaticamente para expor um conjunto fixo de portas dentro da VPC para facilitar a comunicação entre os nós do cluster. Esse comportamento pode ser desativado por pool de máquinas, ao clicar na opção `Show Advanced` e desmarcar a caixa `Allow Internal Communication`. 

[#_expose_external_ports]
=== Expor portas externas

Uma lista de portas a serem abertas _externamente_ para a internet em geral. As portas abertas são definidas no nível do pool de máquinas. Ativar esta opção resultará na criação automática de uma regra de gateway de segurança VPC. Essa regra será automaticamente excluída quando o cluster ou o pool de máquinas for excluído.

[#_network_tags]
=== Tags de Rede

Tags é uma lista de _tags de rede_, que podem ser usadas para associar regras de gateway de segurança preexistentes a todas as VMs dentro de um pool de máquinas.

[#_labels]
=== Rótulos

Uma lista de rótulos personalizados separados por vírgula a serem anexados a todas as VMs dentro de um determinado pool de máquinas. Ao contrário das Tags, os Rótulos não influenciam o comportamento de rede e servem apenas para organizar recursos em nuvem.

[#_advanced_options]
== Opções Avançadas

Ao criar clusters via a interface do Rancher, algumas opções são configuradas automaticamente para você. No entanto, ao criar objetos de configuração de máquinas manualmente, você deve garantir que configure corretamente os campos abaixo.

[#_external_firewall_rule_prefix]
=== prefixo-da-regra-de-gateway-de-segurança-externo

Um prefixo que será usado ao criar a regra de gateway de segurança para expor portas publicamente. Idealmente, isso deve ser uma concatenação do nome do pool de máquinas e do nome do cluster. Este campo deve ser preenchido se o pool de máquinas estiver configurado para expor portas publicamente; caso contrário, pode ser omitido.

[#_internal_firewall_rule_prefix]
=== prefixo-da-regra-de-gateway-de-segurança-interno

Um prefixo que será utilizado ao criar a regra de gateway de segurança interno que permite a comunicação entre os nós dentro do cluster. Se este campo for omitido, nenhuma regra de gateway de segurança interno será criada.

