= Iniciando o Kubernetes em Nós Personalizados Existentes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/index.adoc 
:product-path: cluster-deployment/custom-clusters/custom-clusters.adoc
:description: Para criar um cluster com nós personalizados, você precisará acessar os servidores em seu cluster e provisioná-los de acordo com os requisitos do Rancher
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-use-windows-clusters: xref:cluster-deployment/custom-clusters/windows/use-windows-clusters.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-clean-cluster-nodes: xref:cluster-admin/manage-clusters/clean-cluster-nodes.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-k8s-concepts: xref:sobre-rancher/conceitos.adoc
:xref-production-checklist: xref:cluster-deployment/production-checklist/production-checklist.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:como-fazer/guias-para-novos-usuários/cluster-kubernetes-na-configuração-do-rancher/requisitos-dos-nós-para-clusters-gerenciados-pelo-rancher.adoc
:xref-rke2-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-rke2.adoc
:xref-use-windows-clusters: xref:guias-de-procedimentos/guias-para-novos-usuários/kubernetes-clusters-no-rancher-setup/use-windows-clusters/index.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-clean-cluster-nodes: xref:how-to-guides/new-user-guides/manage-clusters/clean-cluster-nodes.adoc
:xref-k3s-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-k3s.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
:xref-production-checklist: xref:guias-de-procedimentos/guias-para-novos-usuários/kubernetes-clusters-no-rancher-setup/checklist-para-clusters-prontos-para-produção/index.adoc
endif::[]

Quando você cria um cluster personalizado, o Rancher pode usar RKE2/K3s para criar um cluster Kubernetes em servidores bare-metal locais, máquinas virtuais locais ou em qualquer nó hospedado por um provedor de infraestrutura.

Para usar esta opção, você precisa ter acesso aos servidores que farão parte do seu cluster Kubernetes. Provisione cada servidor de acordo com os {xref-node-reqs}[requisitos]. Em seguida, execute o comando fornecido na interface do Rancher em cada servidor para convertê-lo em um nó Kubernetes.

Esta seção descreve como configurar um cluster personalizado.

[#_creating_a_cluster_with_custom_nodes]
== Criando um Cluster com Nós Personalizados

[NOTE]
.Deseja usar hosts Windows como worker do Kubernetes?
====

Veja {xref-use-windows-clusters}[Configurando Clusters Personalizados para Windows] antes de começar.
====


[#_1_provision_a_linux_host]
=== 1. Provisione um Host Linux

Inicie a criação de um cluster personalizado provisionando um host Linux. Seu host pode ser:

* Uma máquina virtual (VM) hospedada na nuvem
* Uma VM local
* Um servidor bare-metal

Se você quiser reutilizar um nó de um cluster personalizado anterior, {xref-clean-cluster-nodes}[limpe o nó] antes de usá-lo em um cluster novamente. Se você reutilizar um nó que não foi limpo, a provisão do cluster pode falhar.

Provisione o host de acordo com os {xref-node-reqs}[requisitos de instalação] e a {xref-production-checklist}[lista de verificação para clusters prontos para produção].

[NOTE]
.Cluster somente IPv6
====
Para um cluster somente IPv6, certifique-se de que seu sistema operacional configure corretamente o arquivo `/etc/hosts`.

----
::1       localhost
----
====

[#_2_create_the_custom_cluster]
=== 2. Crie o Cluster Personalizado

. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique em *Criar*.
. Clique em *Personalizado*.
. Digite um *Nome do Cluster*.
. Use a seção *Configuração do Cluster* para configurar o cluster. Para mais informações, consulte {xref-rke2-config}[Referência de Configuração do Cluster RKE2] e {xref-k3s-config}[Referência de Configuração do Cluster K3s].
+
[NOTE]
.Nós Windows
====
Para saber mais sobre como usar nós Windows como worker do Kubernetes, consulte {xref-use-windows-clusters}[Iniciando o Kubernetes em Clusters Windows].
====
+
. Clique em *Criar*.
+
*Resultado:* A interface redireciona para a página *Registro*, onde você pode gerar o comando de registro para seus nós.
+
. Em *Função do Nó*, selecione as funções que você deseja que um nó do cluster preencha. Você deve provisionar pelo menos um nó para cada função: etcd, worker e plano de controle. Um cluster personalizado requer as três funções para concluir a provisão. Para mais informações sobre funções, consulte {xref-k8s-concepts}#_funções_para_nós_em_clusters_kubernetes[Funções para Nós em Clusters Kubernetes].
+
[NOTE]
.Servidor bare metal
====
Se você planeja dedicar servidores bare metal a cada função, deve provisionar um servidor bare metal para cada função (ou seja, provisionar vários servidores bare metal).
====
+
. *Opcional:* Clique em *Mostrar Avançado* para configurar configurações adicionais, como especificar o(s) endereço(s) IP, substituir o nome do host do nó ou adicionar https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[rótulos] ou https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[taints] ao nó.
+
[NOTE]
====
* Os campos *IP Público do Nó* e *IP Privado do Nó* podem aceitar um único endereço ou uma lista de endereços separados por vírgulas (por exemplo: `10.0.0.5,2001:db8::1`).
====
+
[NOTE]
.Cluster Somente IPv6 ou Dual-stack
====
* Em clusters somente IPv6 e dual-stack, você deve especificar o *endereço IPv6* do nó como o *IP Privado do Nó*.
====
+
. Copie o comando exibido na tela para a sua área de transferência.
. Faça login no seu host Linux usando seu shell preferido, como PuTTy ou uma conexão de Terminal remoto. Execute o comando copiado para sua área de transferência.

[NOTE]
====
Repita os passos 7-10 se você quiser dedicar hosts específicos a funções específicas de nó. Repita os passos quantas vezes forem necessárias.
====

*Resultado:*

O cluster é criado e transita para o estado *Atualizando* enquanto o Rancher inicializa e provisiona os componentes do cluster.

Você pode acessar seu cluster após seu estado ser atualizado para *Ativo*.

Clusters *Ativos* são atribuídos a dois projetos:

* `Default`, contendo o namespace `default`
* `System`, contendo os namespaces `cattle-system`, `traefik`, `kube-public` e `kube-system`

[#_3_amazon_only_tag_resources]
=== 3. Apenas Amazon: Marcar Recursos

Se você configurou seu cluster para usar a Amazon como *Provedor de Nuvem*, marque seus recursos da AWS com um ID de cluster.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html[Documentação da Amazon: Marcação de Seus Recursos Amazon EC2]

[NOTE]
====

Você pode usar instâncias Amazon EC2 sem configurar um provedor de nuvem no Kubernetes. Você só precisa configurar o provedor de nuvem se quiser usar funcionalidades específicas do provedor de nuvem do Kubernetes. Para mais informações, veja https://github.com/kubernetes/website/blob/release-1.18/content/en/docs/concepts/cluster-administration/cloud-providers.md[Provedores de Nuvem do Kubernetes]
====


Os seguintes recursos precisam ser marcados com um `ClusterID`:

* *Nós*: Todos os hosts adicionados no Rancher.
* *Sub-rede*: A sub-rede usada para o seu cluster
* *Grupo de Segurança*: O grupo de segurança utilizado para o seu cluster.

[NOTE]
====

Não marque múltiplos grupos de segurança. Marcar múltiplos grupos gera um erro ao criar o Elastic Load Balancer.
====


A tag que deve ser utilizada é:

----
Key=kubernetes.io/cluster/<CLUSTERID>, Value=owned
----

`<CLUSTERID>` pode ser qualquer string que você escolher. No entanto, a mesma string deve ser utilizada em todos os recursos que você marcar. Definir o valor da tag como `owned` informa ao cluster que todos os recursos marcados com `<CLUSTERID>` são de propriedade e gerenciados por este cluster.

Se você compartilhar recursos entre clusters, pode alterar a tag para:

----
Key=kubernetes.io/cluster/CLUSTERID, Value=shared
----

[#_optional_next_steps]
== Próximas etapas opcionais

Após criar seu cluster, você pode acessá-lo através da interface do Rancher. Como uma melhor prática, recomendamos configurar essas maneiras alternativas de acessar seu cluster:

* *Acesse seu cluster com a CLI kubectl:* Siga {xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[estas etapas] para acessar clusters com kubectl em sua estação de trabalho. Neste caso, você será autenticado através do proxy de autenticação do servidor Rancher, e então o Rancher o conectará ao cluster downstream. Este método permite que você gerencie o cluster sem a interface do Rancher.
* *Acesse seu cluster com a CLI kubectl, usando o endpoint autorizado do cluster:* Siga {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[estas etapas] para acessar seu cluster com kubectl diretamente, sem autenticar através do Rancher. Recomendamos configurar este método alternativo para acessar seu cluster, para que, caso você não consiga se conectar ao Rancher, ainda possa acessar o cluster.
