= Configurer FreeIPA
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-freeipa.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-freeipa.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
endif::[]

Si votre organisation utilise FreeIPA pour l'authentification des utilisateurs, vous pouvez configurer Rancher pour permettre à vos utilisateurs de se connecter en utilisant leurs identifiants FreeIPA.

[NOTE]
.Conditions préalables :
====

* Vous devez avoir un https://www.freeipa.org/[Serveur FreeIPA] configuré.
* Créez un compte de service dans FreeIPA avec `read-only` un accès. Rancher utilise ce compte pour vérifier l'appartenance à un groupe lorsqu'un utilisateur fait une demande en utilisant une clé API.
* Lisez {xref-authn-authz}#_external_authentication_configuration_and_principal_users[Configuration de l'authentification externe et utilisateurs principaux].
====


. Connectez-vous à Rancher en utilisant un utilisateur local assigné au rôle `administrator` (c'est-à-dire, le _principal local_).
. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et authentification*.
. Dans le menu de navigation à gauche, cliquez sur *Fournisseur d'authentification*.
. Click *FreeIPA*.
. Complétez le formulaire *Configurer un serveur FreeIPA*.
+
Vous devrez peut-être vous connecter à votre contrôleur de domaine pour trouver les informations demandées dans le formulaire.
+

[NOTE]
.Utilisez-vous TLS{nbsp}?
====
Si le certificat est auto-signé ou n'est pas d'une autorité de certification reconnue, assurez-vous de fournir la chaîne complète. Cette chaîne est nécessaire pour vérifier le certificat du serveur.
====

+

[NOTE]
.Base de recherche utilisateur vs. Base de recherche de groupe
====
La base de recherche permet à Rancher de rechercher des utilisateurs et des groupes qui se trouvent dans votre FreeIPA.  Ces champs sont uniquement destinés aux bases de recherche et non aux filtres de recherche.

 ** Si vos utilisateurs et groupes se trouvent dans la même base de recherche, complétez uniquement la Base de recherche utilisateur.
 ** Si vos groupes se trouvent dans une base de recherche différente, vous pouvez compléter facultativement la Base de recherche de groupe. Ce champ est dédié à la recherche de groupes, mais n'est pas obligatoire.
====


. Si votre FreeIPA s'écarte du schéma AD standard, complétez le formulaire *Personnaliser le schéma* pour l'adapter. Sinon, passez cette étape.
+

[NOTE]
.Attribut de recherche
====
Le champ Attribut de recherche est par défaut configuré avec trois valeurs spécifiques{nbsp}: `uid|sn|givenName`. Après la configuration de FreeIPA, lorsqu'un utilisateur saisit du texte pour ajouter des utilisateurs ou des groupes, Rancher interroge automatiquement le serveur FreeIPA et tente de faire correspondre les champs par identifiant utilisateur, nom de famille ou prénom. Rancher recherche spécifiquement des utilisateurs/groupes qui commencent par le texte saisi dans le champ de recherche.

La valeur par défaut du champ est `uid|sn|givenName`, mais vous pouvez configurer ce champ sur un sous-ensemble de ces champs. Le pipe (`|`) entre les champs sépare ces champs.

 ** `uid` : ID utilisateur
 ** `sn` : Nom de famille
 ** `givenName` : Prénom

Avec cet attribut de recherche, Rancher crée des filtres de recherche pour les utilisateurs et les groupes, mais vous _ne pouvez pas_ ajouter vos propres filtres de recherche dans ce champ.
====


. Entrez votre nom d'utilisateur et votre mot de passe FreeIPA dans *Authentifier avec FreeIPA* pour confirmer que Rancher est configuré pour utiliser l'authentification FreeIPA.
. Cliquez sur *Activer*.

*Résultat :*

* L'authentification FreeIPA est configurée.
* Vous êtes connecté à Rancher avec votre compte FreeIPA (c'est-à-dire, le _principal externe_).
