= Configurer Okta (SAML)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: procédures/guides-nouveaux-utilisateurs/permissions-d'authentification-et-configuration-globale/configuration-authentification/configurer-okta-saml.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-okta-saml.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc
:xref-openldap-reference: xref:rancher-admin/users/authn-and-authz/openldap/reference.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc 
:xref-openldap-reference: xref:how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/configurer-openldap/openldap-config-reference.adoc
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
endif::[]

Si votre organisation utilise Okta Identity Provider (IdP) pour l'authentification des utilisateurs, vous pouvez configurer Rancher pour permettre à vos utilisateurs de se connecter en utilisant leurs identifiants IdP.

[NOTE]
====

L'intégration d'Okta ne prend en charge que les connexions initiées par le fournisseur de services.
====


[#_prerequisites]
== Conditions préalables

Dans Okta, créez une application SAML avec les paramètres ci-dessous. Consultez la https://developer.okta.com/standards/SAML/setting_up_a_saml_application_in_okta[documentation d'Okta] pour obtenir de l'aide.

|===
| Paramètre | Valeur

| `Single Sign on URL`
| `https://yourRancherHostURL/v1-saml/okta/saml/acs`

| `Audience URI (SP Entity ID)`
| `https://yourRancherHostURL/v1-saml/okta/saml/metadata`
|===

[#_configuring_okta_in_rancher]
== Configurer Okta dans Rancher

Vous pouvez intégrer Okta avec Rancher, afin que les utilisateurs authentifiés puissent accéder aux ressources de Rancher via leurs permissions de groupe. Okta renvoie une assertion SAML qui authentifie un utilisateur, y compris les groupes auxquels appartient un utilisateur.

. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et authentification*.
. Dans le menu de navigation à gauche, cliquez sur *Fournisseur d'authentification*.
. Click *Okta*.
. Complétez le formulaire *Configurer le compte Okta*. Les exemples ci-dessous décrivent comment vous pouvez mapper les attributs d'Okta à partir des déclarations d'attributs aux champs dans Rancher.
+
|===
| Champ | Description

| Champ Nom d'affichage
| Le nom de l'attribut d'une déclaration d'attribut qui contient le nom d'affichage des utilisateurs.

| Champ Nom d'utilisateur
| Le nom de l'attribut d'une déclaration d'attribut qui contient le nom d'utilisateur/prénom.

| Champ UID
| Le nom de l'attribut d'une déclaration d'attribut qui est unique à chaque utilisateur.

| Champ Groupes
| Le nom de l'attribut dans une déclaration d'attribut de groupe qui expose vos groupes.

| Hôte de l'API Rancher
| L'URL de votre serveur Rancher.

| Clé privée / Certificat
| Une paire clé/certificat utilisée pour le chiffrement des assertions.

| Metadata XML
| Le fichier `Identity Provider metadata` que vous trouvez dans la section `Sign On` de l'application.
|===
+

[TIP]
====
Vous pouvez générer une paire clé/certificat en utilisant une commande openssl. Par exemple :

----
 openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout myservice.key -out myservice.crt
----
====


. Après avoir complété le formulaire *Configurer le compte Okta*, cliquez sur *Activer*.
+
Rancher vous redirige vers la page de connexion de l'IdP. Entrez les identifiants permettant de vous authentifier auprès de l'IdP Okta afin de valider la configuration Okta dans Rancher.
+

[NOTE]
====
Si rien ne semble se passer, c'est probablement parce que votre navigateur a bloqué le pop-up. Assurez-vous de désactiver le bloqueur de pop-up pour votre domaine Rancher et de l'ajouter à la liste blanche dans toutes les autres extensions que vous pourriez utiliser.
====


*Résultat :* Rancher est configuré pour fonctionner avec Okta. Vos utilisateurs peuvent désormais se connecter à Rancher en utilisant leurs identifiants Okta.

[NOTE]
.Avertissements concernant le fournisseur SAML
====
Si vous configurez Okta sans OpenLDAP, vous ne pourrez pas rechercher ou consulter directement les utilisateurs ou les groupes. Cela entraîne plusieurs mises en garde{nbsp}:

* Les utilisateurs et les groupes ne sont pas validés lorsque vous leur attribuez des autorisations dans Rancher.
* Lors de l'ajout d'utilisateurs, les identifiants d'utilisateur exacts (c'est-à-dire `UID Field`) doivent être saisis correctement. Lorsque vous tapez l'identifiant de l'utilisateur, il n'y aura pas de recherche d'autres identifiants d'utilisateur pouvant correspondre.
* Lors de l'ajout de groupes, vous devez sélectionner le groupe dans le menu déroulant à côté de la zone de texte. Rancher suppose que toute saisie dans la zone de texte est un utilisateur.
* Le menu déroulant des groupes affiche uniquement les groupes dont vous êtes membre. Cependant, si vous avez des permissions d'administrateur ou des permissions d'administrateur restreintes, vous pouvez rejoindre un groupe dont vous n'êtes pas membre.
====

[#_okta_with_openldap_search]
== Okta avec recherche OpenLDAP

Vous pouvez ajouter un backend OpenLDAP pour aider à la recherche d'utilisateurs et de groupes. Rancher affichera des utilisateurs et des groupes supplémentaires provenant du service OpenLDAP. Cela permet d'attribuer des permissions à des groupes dont l'utilisateur connecté n'est pas déjà membre.

[#_openldap_prerequisites]
=== Prérequis pour OpenLDAP

Si vous utilisez Okta comme votre IdP, vous pouvez https://help.okta.com/en-us/Content/Topics/Directory/LDAP-interface-main.htm[configurer une interface LDAP] pour que Rancher l'utilise. Vous pouvez également configurer un serveur OpenLDAP externe.

Vous devez configurer Rancher avec un compte de liaison LDAP (également appelé compte de service) afin de pouvoir rechercher et récupérer les entrées LDAP pour les utilisateurs et les groupes qui devraient avoir accès. N'utilisez pas un compte administrateur ou un compte personnel comme compte de liaison LDAP. https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-add-users.htm[Créer] un compte dédié dans OpenLDAP, avec un accès en lecture seule aux utilisateurs et groupes sous la base de recherche configurée.

[CAUTION]
.Considérations relatives à la sécurité
====

Le compte de service OpenLDAP est utilisé pour toutes les recherches. Les utilisateurs de Rancher verront les utilisateurs et groupes que le compte de service OpenLDAP peut consulter, indépendamment de leurs autorisations SAML individuelles.
====


____
*Utilisez-vous TLS ?*

Si le certificat utilisé par le serveur OpenLDAP est auto-signé ou provient d'une autorité de certification non reconnue, Rancher a besoin du certificat CA (concaténé avec tous les certificats intermédiaires) au format PEM. Fournissez ce certificat lors de la configuration afin que Rancher puisse valider la chaîne de certificats.
____

[#_configure_openldap_in_rancher]
=== Configurer OpenLDAP dans Rancher

{xref-openldap-reference}[Configurer les paramètres] pour le serveur OpenLDAP, les groupes et les utilisateurs. Notez que l'appartenance à des groupes imbriqués n'est pas disponible.

____
Avant de procéder à la configuration, veuillez vous familiariser avec {xref-authn-authz}#_configuration_d'authentification_externe_et_utilisateurs_principaux[la configuration d'authentification externe et les utilisateurs principaux].
____

. Connectez-vous à Rancher en utilisant un utilisateur local assigné au rôle {xref-global-permissions}[administrateur] (c'est-à-dire, le _principal local_).
. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et authentification*.
. Dans le menu de navigation à gauche, cliquez sur *Fournisseur d'authentification*.
. Cliquez sur *Okta* ou, si SAML est déjà configuré, *Modifier la configuration*.
. Sous *User and Group Search*, cochez *Configurer un serveur OpenLDAP*.

Si vous rencontrez des problèmes lors du test de la connexion au serveur OpenLDAP, assurez-vous d'avoir saisi les identifiants du compte de service et configuré correctement la base de recherche. L'inspection des journaux de Rancher peut aider à identifier la cause profonde. Les journaux de débogage peuvent contenir des informations plus détaillées sur l'erreur. Veuillez vous référer à xref:faq/technical-items.adoc#_how_can_i_enable_debug_logging[Comment puis-je activer la journalisation de débogage] pour plus d'informations.

[#_configuring_saml_single_logout_slo]
== Configuration de la déconnexion unique SAML (SLO)

include::shared:ROOT:partial$en/configure-slo.adoc[]

[#_saml_and_openldap_group_permissions]
== Permissions de groupe SAML et OpenLDAP

include::shared:ROOT:partial$en/saml-openldap-group-permissions.adoc[]
