= Configurer PingIdentity (SAML)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-pingidentity.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-pingidentity.adoc

Si votre organisation utilise Ping Identity Provider (IdP) pour l'authentification des utilisateurs, vous pouvez configurer Rancher pour permettre à vos utilisateurs de se connecter en utilisant leurs identifiants IdP.

____
*Conditions préalables :*

* Vous devez avoir un https://www.pingidentity.com/[Serveur Ping IdP] configuré.
* Voici les URL du fournisseur de services Rancher nécessaires à la configuration{nbsp}:
URL des métadonnées{nbsp}: `\https://<rancher-server>/v1-saml/ping/saml/metadata` URL du service consommateur d'assertion (ACS){nbsp}: `\https://<rancher-server>/v1-saml/ping/saml/acs` Notez que ces URL ne renverront pas de données valides tant que la configuration d'authentification n'est pas enregistrée dans Rancher.
* Exportez un fichier `metadata.xml` depuis votre serveur IdP. Pour plus d'informations, consultez la https://documentation.pingidentity.com/pingfederate/pf83/index.shtml#concept_exportingMetadata.html[documentation de PingIdentity].
____

. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et authentification*.
. Dans le menu de navigation à gauche, cliquez sur *Fournisseur d'authentification*.
. Cliquez sur *Ping Identity*.
. Complétez le formulaire *Configurer un compte Ping*. Ping IdP vous permet de spécifier quel magasin de données vous souhaitez utiliser. Vous pouvez soit ajouter une base de données, soit utiliser un serveur LDAP existant. Par exemple, si vous sélectionnez votre serveur Active Directory (AD), les exemples ci-dessous décrivent comment vous pouvez mapper les attributs AD aux champs dans Rancher.
 .. *Champ Nom d'affichage*{nbsp}: Entrez l'attribut AD qui contient le nom d'affichage des utilisateurs (exemple{nbsp}: `displayName`).
 .. *Champ Nom d'utilisateur*{nbsp}: Entrez l'attribut AD qui contient le nom d'utilisateur/prénom (exemple{nbsp}: `givenName`).
 .. *Champ UID*{nbsp}: Entrez un attribut AD qui est unique pour chaque utilisateur (exemple{nbsp}: `sAMAccountName`, `distinguishedName`).
 .. *Champ Groupes*{nbsp}: Faites des entrées pour gérer les adhésions aux groupes (exemple{nbsp}: `memberOf`).
 .. *Champ d'ID d'entité* (optionnel){nbsp}: L'identifiant unique publié et dépendant du protocole de votre partenaire. Cet ID définit votre organisation comme l'entité opérant le serveur pour les transactions SAML 2.0. Cet ID peut avoir été obtenu hors bande ou via un fichier de métadonnées SAML.
 .. *Rancher API Host*{nbsp}: Entrez l'URL de votre serveur Rancher.
 .. *Clé privée* et *Certificat*{nbsp}: Ceci est une paire clé-certificat pour créer un shell sécurisé entre Rancher et votre IdP.
+
Vous pouvez en générer une en utilisant une commande openssl. Par exemple :
+
----
 openssl req -x509 -newkey rsa:2048 -keyout myservice.key -out myservice.cert -days 365 -nodes -subj "/CN=myservice.example.com"
----

 .. *Métadonnées IDP*{nbsp}: Le fichier `metadata.xml` que vous https://documentation.pingidentity.com/pingfederate/pf83/index.shtml#concept_exportingMetadata.html[avez exporté depuis votre serveur IdP].
. Après avoir complété le formulaire *Configurer le compte Ping*, cliquez sur *Activer*.
+
Rancher vous redirige vers la page de connexion de l'IdP. Entrez les identifiants permettant de vous authentifier auprès de Ping IdP afin de valider la configuration de PingIdentity dans Rancher.
+

[NOTE]
====
Vous devrez peut-être désactiver votre bloqueur de fenêtres contextuelles pour voir la page de connexion de l'IdP.
====


*Résultat :* Rancher est configuré pour fonctionner avec PingIdentity. Vos utilisateurs peuvent désormais se connecter à Rancher en utilisant leurs identifiants PingIdentity.

[NOTE]
.Avertissements concernant le fournisseur SAML
====
* Les utilisateurs et les groupes ne sont pas validés lorsque vous leur attribuez des autorisations dans Rancher.
* Lors de l'ajout d'utilisateurs, les identifiants d'utilisateur exacts (c'est-à-dire `UID Field`) doivent être saisis correctement. Lorsque vous tapez l'identifiant de l'utilisateur, il n'y aura pas de recherche d'autres identifiants d'utilisateur pouvant correspondre.
* Lors de l'ajout de groupes, vous devez sélectionner le groupe dans le menu déroulant à côté de la zone de texte. Rancher suppose que toute saisie dans la zone de texte est un utilisateur.
* Le menu déroulant des groupes affiche uniquement les groupes dont vous êtes membre. Si vous avez des autorisations d'administrateur ou des autorisations d'administrateur restreintes, vous pouvez rejoindre un groupe dont vous n'êtes pas membre.
====

[#_configuring_saml_single_logout_slo]
== Configuration de la déconnexion unique SAML (SLO)

include::shared:ROOT:partial$en/configure-slo.adoc[]

[#_saml_and_openldap_group_permissions]
== Permissions de groupe SAML et OpenLDAP

include::shared:ROOT:partial$en/saml-openldap-group-permissions.adoc[]
