= Configurer l'application GitHub
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-08
:page-revdate: {revdate}
:community-path: procedures/nouveau-utilisateur/permissions-d-authentification-et-configuration-globale/configuration-d-authentification/configurer-application-github.adoc 
:product-path: rancher-admin/users/authn-and-authz/configure-github-app.adoc

Dans les environnements utilisant GitHub, vous pouvez configurer le nouveau fournisseur d'authentification de l'application GitHub dans Rancher, ce qui permet aux utilisateurs de s'authentifier avec un compte d'organisation GitHub à l'aide d'une https://docs.github.com/en/apps/overview[application GitHub] dédiée. Ce nouveau fournisseur fonctionne en parallèle avec le fournisseur d'authentification GitHub standard existant, offrant une sécurité accrue et une meilleure gestion des permissions basées sur les équipes d'organisation GitHub.

[#_prerequisites]
== Conditions préalables

[CAUTION]
====
Le fournisseur d'authentification de l'application GitHub ne fonctionne qu'avec les https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#organization-accounts[comptes d'organisation GitHub]. Il ne fonctionne pas avec les https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#user-accounts[comptes d'utilisateur GitHub] individuels.
====

Avant de configurer le fournisseur dans Rancher, vous devez d'abord créer une application GitHub pour votre organisation, générer un secret client pour votre application GitHub et générer une clé privée pour votre application GitHub. Référez-vous à https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app[Enregistrement d'une application GitHub] pour plus de détails.

[#_create_github_app]
=== Créer une application GitHub

. Ouvrez les https://github.com/settings/organizations[paramètres de votre organisation GitHub].
. À droite de l'organisation, sélectionnez *Paramètres*.
. Dans la barre latérale gauche, cliquez sur *Paramètres du développeur* > *Applications GitHub*.
. Cliquez sur *Nouvelle application GitHub*.
. Remplissez le formulaire de configuration de l'application GitHub avec ces valeurs{nbsp}:
 ** *Nom de l'application GitHub*{nbsp}: Tout ce que vous voulez, par exemple `My Rancher`.
 ** *Description de l'application*{nbsp}: Optionnel, peut être laissé vide.
 ** *URL de la page d'accueil*{nbsp}: `https://localhost:8443`.
 ** *URL de rappel*{nbsp}: `https://localhost:8443/verify-auth`.
. Sélectionnez *Créer une application GitHub*.

[#_generate_a_client_secret]
=== Générez un secret client

Générez un https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api#using-basic-authentication[secret client] sur la page des paramètres de votre application.

. Allez à votre application GitHub.
. À côté de *Secrets client*, sélectionnez *Générer un nouveau secret client*.

[#_generate_a_private_key]
=== Générez une clé privée

Générez une https://docs.github.com/en/enterprise-server/apps/creating-github-apps/authenticating-with-a-github-app/managing-private-keys-for-github-apps#generating-private-keys[clé privée] sur la page des paramètres de votre application.

. Allez à votre application GitHub.
. À côté de *Clés privées*, cliquez sur *Générer une clé privée*.

[#_github_app_auth_provider_configuration]
== Configuration du fournisseur d'authentification de l'application GitHub

Pour configurer le fournisseur d'authentification de l'application GitHub dans Rancher, suivez ces étapes{nbsp}:

. Naviguez vers la section *Utilisateurs et authentification* dans l'interface utilisateur de Rancher.
. Sélectionnez *Fournisseurs d'authentification*.
. Sélectionnez la tuile *Application GitHub*.
. Rassemblez et entrez les détails de votre application GitHub dans les champs du formulaire de configuration.
+
|===
| Nom du champ | Description

| *ID client* (Requis)
| L'ID client de votre application GitHub.

| *Secret client* (Requis)
| Le secret client de votre application GitHub.

| *ID de l'application GitHub* (Requis)
| L'ID numérique associé à votre application GitHub.

| *ID d'installation* (Optionnel)
| Si vous souhaitez restreindre l'authentification à une seule installation de l'application, fournissez son ID d'installation numérique spécifique.

| *Clé privée* (Requis)
| Le contenu du fichier de clé privée (au format PEM) généré par GitHub pour votre application.
|===
+
[NOTE]
====
Une application GitHub peut être installée sur plusieurs organisations, et chaque installation a un ID d'installation unique. Si vous souhaitez restreindre l'authentification à une seule installation d'application et à une organisation GitHub, fournissez l'ID d'installation lors de la configuration. Si vous ne fournissez pas d'ID d'installation, les autorisations de l'utilisateur sont agrégées sur toutes les installations.
====
+
. Sélectionnez *Activer*. Rancher tente de valider les identifiants et, en cas de succès, active le fournisseur GitHub App.

Une fois activé, les utilisateurs se connectant via le fournisseur GitHub App sont automatiquement identifiés et vous pouvez tirer parti des équipes et des utilisateurs de votre organisation GitHub pour configurer le contrôle d'accès en fonction du rôle (RBAC) et attribuer des autorisations aux projets et aux clusters.

[NOTE]
====
Assurez-vous que les utilisateurs et les équipes que vous souhaitez utiliser pour l'autorisation existent au sein de l'organisation GitHub gérée par l'application.
====

* *Utilisateurs*{nbsp}: Les utilisateurs GitHub individuels qui sont membres de l'organisation GitHub où l'application est installée peuvent se connecter.
* *Groupes*{nbsp}: Les équipes de l'organisation GitHub sont mappées aux groupes Rancher, vous permettant d'attribuer des autorisations à des équipes entières au sein des projets et des clusters Rancher.
