= rancher-logging Helmチャートオプション
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-15
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/logging-helm-chart-options.adoc 
:product-path: observability/logging/logging-helm-chart-options.adoc
ifeval::["{build-type}" != "community"]
:xref-selinux-rpm: xref:security/selinux-rpm/selinux-rpm.adoc
:xref-logging-taints-and-tolerations: xref:observability/logging/taints-and-tolerations.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selinux-rpm: xref:reference-guides/rancher-security/selinux-rpm/index.adoc
:xref-logging-taints-and-tolerations: xref:integrations-in-rancher/logging/taints-and-tolerations.adoc
endif::[]

[#_enable_disable_windows_node_logging]
== Windowsノードロギングの有効化／無効化

`global.cattle.windows.enabled`を`true`または`false`に設定することで、Windowsノードロギングを有効化または無効化できます。 `values.yaml`

デフォルトでは、WindowsクラスターにロギングアプリケーションをインストールするためにCluster Dashboard UIが使用されると、Windowsノードロギングが有効になります。

このシナリオでは、`global.cattle.windows.enabled`を`false`に設定すると、クラスター上のWindowsノードロギングが無効になります。
無効にされている場合でも、Windowsクラスター内のLinuxノードからはログが収集されます。

[NOTE]
====

現在、WindowsクラスターでWindowsロギングを無効にした後に`helm upgrade`を実行すると、Windowsノードエージェントが削除されないという https://github.com/rancher/rancher/issues/32325[問題]があります。このシナリオでは、すでにインストールされている場合、ユーザーはWindowsノードエージェントを手動で削除する必要があります。
====


[#_working_with_a_custom_docker_root_directory]
== カスタムDockerルートディレクトリの使用

カスタムDockerルートディレクトリを使用する場合、`global.dockerRootDirectory`を`values.yaml`に設定できます。

これにより、作成されたロギングCRがデフォルトのDocker `data-root`の場所ではなく、指定したパスを使用することが保証されます。

これはLinuxノードにのみ影響します。

クラスターにWindowsノードがある場合、そのノードには変更が適用されません。

[#_adding_nodeselector_settings_and_tolerations_for_custom_taints]
== カスタムテイント用のNodeSelector設定とTolerationの追加

ロギングHelmチャートの値を編集することで、独自の`nodeSelector`設定を追加し、追加のテイントのために`tolerations`を追加できます。詳細については、{xref-logging-taints-and-tolerations}[このページ]を参照してください。

[#_enabling_the_logging_application_to_work_with_selinux]
== ロギングアプリケーションをSELinuxで動作するように有効化する

[NOTE]
.要件:
====

ロギングv2は、RHEL/CentOS 7および8でSELinuxと共にテストされました。
====


https://en.wikipedia.org/wiki/Security-Enhanced_Linux[セキュリティ強化Linux（SELinux）]はLinuxへのセキュリティ強化です。歴史的に政府機関によって使用されてきたSELinuxは、現在業界標準となり、CentOS 7および8ではデフォルトで有効になっています。

SELinuxでLogging v2を使用するには、`rancher-selinux` RPMを、これらの{xref-selinux-rpm}[手順]に従ってインストールすることをお勧めします。

次に、ロギングアプリケーションをインストールする際に、`global.seLinux.enabled`を`true`に変更してチャート`values.yaml`をSELinux対応に設定します。

[#_additional_logging_sources]
== 追加のログソース

デフォルトでは、Rancherはすべてのクラスタータイプの https://kubernetes.io/docs/concepts/overview/components/#control-plane-components[コントロールプレーンコンポーネント]と https://kubernetes.io/docs/concepts/overview/components/#node-components[ノードコンポーネント]のログを収集します。

場合によっては、Rancherが追加のログを収集できることがあります。

以下の表は、各ノードタイプごとに追加のログが収集される可能性のあるソースをまとめたものです。

|===
| ロギングソース | Linuxノード（Windowsクラスターを含む） | Windowsノード

| RKE2
| ✓
|

| K3s
| ✓
|

ifeval::["{build-type}" != "srfa"]
| AKS
| ✓
|

| EKS
| ✓
|

| GKE
| ✓
|
endif::[]
ifeval::["{build-type}" == "srfa"]
| EKS
| ✓
|
endif::[]
|===

ホスティングされたKubernetesプロバイダーを追加のロギングソースとして有効にするには、Logging Helmチャートをインストールまたはアップグレードする際に*強化されたクラウドプロバイダーロギングを有効にする*オプションを有効にしてください。

有効にすると、Rancherはプロバイダーが提供するすべての追加ノードおよびコントロールプレーンのログを収集しますが、これはプロバイダーによって異なる場合があります。

すでにAWS CloudWatchやGoogle Cloudオペレーションスイート（以前のStackdriver）などのクラウドプロバイダーの独自のロギングソリューションを使用している場合、このオプションを有効にする必要はありません。ネイティブソリューションはすべてのログに無制限にアクセスできます。

[#_systemd_configuration]
== Systemd構成

Rancherロギングでは、`SystemdLogPath`はK3sおよびRKE2 Kubernetes配布パッケージ用に構成する必要があります。

K3sおよびRKE2 Kubernetes配布パッケージは、ロギングに使用されるsystemdのサブシステムであるjournaldにログを記録します。これらのログを収集するには、`systemdLogPath`を定義する必要があります。デフォルトでは`run/log/journal`ディレクトリが使用されますが、一部のLinux配布パッケージはこのパスをデフォルトにしていません。例えば、Ubuntuは`var/log/journal`をデフォルトにしています。`systemdLogPath`の設定を確認するには、以下の手順を参照してください。

*Systemd設定の手順:*

* ノードの1つで`cat /etc/systemd/journald.conf | grep -E ^\#?Storage | cut -d"=" -f2`を実行します。
* `persistent`が返された場合、`systemdLogPath`は`/var/log/journal`である必要があります。
* `volatile`が返された場合、`systemdLogPath`は`/run/log/journal`である必要があります。
* `auto`が返された場合、`/var/log/journal`が存在するか確認してください。
 ** `/var/log/journal`が存在する場合は、`/var/log/journal`を使用してください。
 ** `/var/log/journal`が存在しない場合は、`/run/log/journal`を使用してください。

[NOTE]
====

上記に記載されていない値が返された場合、Rancher Loggingはコントロールプレーンのログを収集できません。この問題に対処するには、すべてのコントロールプレーンノードで以下の操作を実行する必要があります：

* journald.confで`Storage=volatile`を設定します。
* コンピュータを再起動します。
* `systemdLogPath`を`/run/log/journal`に設定します。
====

