= トラブルシューティング
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/logging.adoc 
:product-path: observability/logging/troubleshooting.adoc
:experimental:

[#_log_levels]
== ログレベル

Rancherで使用されるログレベルは次のとおりです。

|===
| 名前 | 説明

| `info`
| 情報メッセージをログに記録します。これは、デフォルトのログレベルです。

| `debug`
| デバッグ(する)ために使用できる詳細なメッセージをログに記録します。

| `trace`
| 内部機能に関する非常に詳細なメッセージをログに記録します。これは非常に冗長で、機密情報を含む可能性があります。
|===

[#_how_to_configure_a_log_level]
=== ログレベルの設定方法

[#_kubernetes_install]
==== Kubernetesのインストール

* デバッグ(する)ログレベルを設定します。

 $ KUBECONFIG=./kube_config_cluster.yml
 $ kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -c rancher -- loglevel --set debug; done
 OK
 OK
 OK
 $ kubectl -n cattle-system logs -l app=rancher -c rancher

* 情報ログレベルを設定します。

 $ KUBECONFIG=./kube_config_cluster.yml
 $ kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -c rancher -- loglevel --set info; done
 OK
 OK
 OK

[#_docker_install]
==== Dockerのインストール

* デバッグ(する)ログレベルを設定します。

 $ docker exec -ti <container_id> loglevel --set debug
 OK
 $ docker logs -f <container_id>

* 情報ログレベルを設定します。

 $ docker exec -ti <container_id> loglevel --set info
 OK

[#_rancher_machine_debug_logs]
== Rancherマシンデバッグ(する)ログ

インフラストラクチャプロバイダーでのオブジェクトの作成をトラブルシューティングする必要がある場合、`rancher-machine`デバッグ(する)ログが役立つかもしれません。

Rancherを起動する際に環境変数を設定することで、`rancher-machine`のデバッグ(する)ログを有効にすることが可能です。

`CATTLE_WHITELIST_ENVVARS`環境変数は、特定の環境変数をホワイトリストに登録し、プロビジョニング中に`rancher-machine`に渡すことを許可します。

`MACHINE_DEBUG`変数は`rancher-machine`でデバッグ(する)ログを有効にします。

したがって、`MACHINE_DEBUG=true`を設定し、`CATTLE_WHITELIST_ENVVARS`のデフォルト変数リストに`MACHINE_DEBUG`を追加することで、RKE1、RKE2、およびk3sクラスターのプロビジョニング時に`rancher-machine`でデバッグ(する)ログを有効にすることが可能です。

[CAUTION]
====

上記の`trace`ログレベルと同様に、`rancher-machine`デバッグ(する)ログは機密情報を含む可能性があります。
====


[#_cattle_cluster_agent_debug_logs]
== Cattle-cluster-agentデバッグログ

`cattle-cluster-agent`ログレベルは、ダウンストリームクラスターを初期化する際に設定できます。

menu:クラスター設定[エージェント環境変数]の下にクラスターを作成する際に、ログレベルを定義するための変数を設定できます。

* トレースレベルのロギング：`CATTLE_TRACE`または`RANCHER_TRACE`を`true`に設定します。
* デバッグ(する)レベルのロギング：`CATTLE_DEBUG`または`RANCHER_DEBUG`を`true`に設定します。

[CAUTION]
====

`cattle-cluster-agent`デバッグ(する)ログには、機密情報が含まれている可能性があります。
====

