= Kubernetes-Distributionen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/kubernetes-distributions/index.adoc 
:product-path: integrations/kubernetes-distributions.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
endif::[]

[#__k3s_product_name]
== {k3s-product-name}
K3s ist eine leichtgewichtige, vollständig konforme Kubernetes-Distribution, die für eine Vielzahl von Anwendungsfällen, einschließlich Edge-Computing, IoT, CI/CD, Entwicklung und Einbettung von Kubernetes in Anwendungen, konzipiert wurde. Es vereinfacht das Kubernetes-Management, indem es das System als eine einzige Binärdatei paketiert, sqlite3 als standardmäßigen Speicher verwendet und einen benutzerfreundlichen Launcher anbietet. K3s umfasst wesentliche Funktionen wie lokalen Speicher und Lastausgleich, Helm Chart Controller und das Traefik CNI. Es minimiert externe Abhängigkeiten und bietet ein optimiertes Kubernetes-Erlebnis. K3s wurde im Juni 2020 als Sandbox-Projekt an die CNCF gespendet.

[#__k3s_product_name_with_rancher]
=== {k3s-product-name} mit Rancher

* Rancher ermöglicht die einfache Bereitstellung von K3s auf einer Vielzahl von Plattformen, einschließlich Amazon EC2, DigitalOcean, Azure, vSphere oder vorhandenen Servern.
* Standardmäßige Rancher-Verwaltung von Kubernetes-Clustern, einschließlich aller aufgeführten {xref-cluster-deployment}#_cluster_management_capabilities_by_cluster_type[Clusterverwaltungsfähigkeiten].

[#__rke2_product_name]
== {rke2-product-name}

RKE2 ist eine konforme Kubernetes-Distribution, die von Rancher entwickelt wurde. Es ist speziell für Sicherheit und Compliance innerhalb der USA konzipiert. US-Bundesbehörden liegt.

Die Hauptmerkmale von RKE2 umfassen:

. *Sicherheits- und Compliance-Fokus*: RKE2 legt großen Wert auf Sicherheit und Compliance, arbeitet unter einem "sicher von Anfang an"-Rahmen und ist somit für Regierungsdienste und stark regulierte Branchen wie Finanzen und Gesundheitswesen geeignet.
. *CIS Kubernetes Benchmark-Konformität*: RKE2 ist vorkonfiguriert, um den CIS Kubernetes Hardening Benchmark (derzeit Unterstützung für v1.23 und v1.7) zu erfüllen, wobei nur minimale manuelle Eingriffe erforderlich sind.
. *FIPS 140-2-Konformität*: RKE2 erfüllt den FIPS 140-2-Standard unter Verwendung von FIPS-validierten Krypto-Modulen für seine Komponenten.
. *Eingebettetes etcd*: RKE2 verwendet standardmäßig ein eingebettetes etcd als seinen Datenspeicher. Dies bringt es näher an die Standardpraktiken von Kubernetes, ermöglicht eine bessere Integration mit anderen Kubernetes-Tools und verringert das Risiko von Fehlkonfigurationen.
. *Ausrichtung an Upstream Kubernetes*: RKE2 zielt darauf ab, sich eng an Upstream Kubernetes auszurichten, wodurch das Risiko einer Nichtkonformität verringert wird, die auftreten kann, wenn Distributionen verwendet werden, die von den Standardpraktiken von Kubernetes abweichen.
. *Unterstützung mehrerer CNI*: RKE2 bietet Unterstützung für mehrere Container Network Interface (CNI) Plugins, einschließlich Cilium, Calico und Multus. Dies ist entscheidend für Anwendungsfälle wie Telekommunikationsverteilzentren und Fabriken mit verschiedenen Produktionsanlagen.

[#__rke2_product_name_with_rancher]
== {rke2-product-name} mit Rancher

* Rancher ermöglicht eine einfache Bereitstellung von RKE2 über eine Vielzahl von Plattformen, einschließlich Amazon EC2, DigitalOcean, Azure, vSphere oder vorhandenen Servern.
* Standardmäßige Rancher-Verwaltung von Kubernetes-Clustern, einschließlich aller aufgeführten {xref-cluster-deployment}#_cluster_management_capabilities_by_cluster_type[Funktionen zur Clusterverwaltung].
