= Kubernetes auf dem Desktop mit Rancher Desktop
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/rancher-desktop.adoc 
:product-path: integrations/rancher-desktop.adoc

Rancher Desktop bündelt wesentliche Werkzeuge zur Entwicklung und zum Testen von cloudnativen Anwendungen von Ihrem Desktop aus.

Wenn Sie von Ihrem lokalen Rechner aus an Anwendungen arbeiten, die für Cloud-Umgebungen gedacht sind, benötigen Sie normalerweise viel Vorbereitung. Sie müssen eine Container-Laufzeitumgebung auswählen, Kubernetes und beliebte Dienstprogramme installieren und möglicherweise eine virtuelle Maschine einrichten. Die Installation der Komponenten einzeln und deren Zusammenarbeit kann ein zeitaufwändiger Prozess sein.

Um die Komplexität zu reduzieren, bietet Rancher Desktop den Teams die folgenden Hauptmerkmale an:

* Einfache und unkomplizierte Installation auf macOS, Linux und Windows-Betriebssystemen.
* K3s, eine sofort einsatzbereite, leichtgewichtige Kubernetes-Distribution.
* Die Möglichkeit, einfach zwischen Kubernetes-Versionen zu wechseln.
* Ein GUI-basiertes Cluster-Dashboard, das von Rancher betrieben wird, um Ihren lokalen Cluster zu erkunden.
* Freiheit, Ihre Container-Engine zu wählen: dockerd (moby) oder containerd.
* Einstellungen zur Anpassung der Anwendung an Ihre Bedürfnisse.
* Mitgelieferte Werkzeuge, die für Ihren Container, für die Kubernetes-basierte Entwicklung und für Betriebsabläufe erforderlich sind.
* Regelmäßige Aktualisierungen, um die mitgelieferten Werkzeuge auf dem neuesten Stand zu halten.
* Integration mit beliebten Werkzeugen/IDEs, einschließlich VS Code und Skaffold.
* Zugriffskontrolle für Images und Registries.
* Unterstützung für Docker-Erweiterungen.

Besuchen Sie die https://rancherdesktop.io[Rancher Desktop]-Website und lesen Sie die https://docs.rancherdesktop.io/[Dokumentation], um mehr zu erfahren.

Um Rancher Desktop auf Ihrem Rechner zu installieren, beziehen Sie sich auf die https://docs.rancherdesktop.io/getting-started/installation[Installationsanleitung].

[#_trying_rancher_on_rancher_desktop]
== Rancher auf Rancher Desktop ausprobieren.

Rancher Desktop bietet das setup und die Werkzeuge, die Sie benötigen, um containerisierte, auf Helm basierende Anwendungen einfach auszuprobieren. Sie können mit der Rancher Kubernetes Management-Plattform über Rancher Desktop beginnen, indem Sie dieser https://docs.rancherdesktop.io/how-to-guides/rancher-on-rancher-desktop[Anleitung] folgen.
