= {rancher-product-name} Architecture
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/rancher-manager-architecture/index.adoc 
:product-path: about-rancher/architecture/architecture.adoc
ifeval::["{build-type}" != "community"]
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-arch-components: xref:about-rancher/architecture/rancher-server-and-components.adoc
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
:xref-rancher-overview: xref:about-rancher/overview.adoc#_features_of_the_rancher_api_server
endif::[]
ifeval::["{build-type}" == "community"]
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-arch-components: xref:reference-guides/rancher-manager-architecture/rancher-server-and-components.adoc
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
:xref-rancher-overview: xref:getting-started/overview.adoc
endif::[]

Cette section se concentre sur le {xref-arch-components}[serveur Rancher et ses composants] et sur la manière dont {xref-arch-com-ds-cluster}[Rancher communique avec les clusters Kubernetes en aval].

Pour des informations sur les différentes manières dont Rancher peut être installé, consultez le {xref-install-upgrade}#_aperçu_des_options_d_installation[aperçu des options d'installation.]

Pour une liste des principales fonctionnalités du serveur API Rancher, consultez la {xref-rancher-overview}[section d'aperçu.]

Pour des conseils sur la mise en place de l'infrastructure sous-jacente pour le serveur Rancher, consultez les {xref-arch-rec}[recommandations d'architecture.]

[NOTE]
====

Cette section suppose une familiarité de base avec Docker et Kubernetes. Pour une brève explication de la façon dont les composants Kubernetes fonctionnent ensemble, reportez-vous à la page {xref-k8s-concepts}[concepts].
====

