= À propos de rancher-selinux
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-01-20
:page-revdate: {revdate}
:community-path: reference-guides/rancher-security/selinux-rpm/about-rancher-selinux.adoc 
:product-path: security/selinux-rpm/about-rancher-selinux.adoc

Pour permettre à Rancher de fonctionner avec SELinux, certaines fonctionnalités doivent être activées manuellement pour les nœuds SELinux. Pour aider à cela, Rancher fournit un RPM SELinux.

Le RPM `rancher-selinux` contient un ensemble de politiques SELinux conçues pour accorder les privilèges nécessaires à divers composants Rancher fonctionnant sur des systèmes Linux avec SELinux activé.

Le dépôt GitHub `rancher-selinux` est https://github.com/rancher/rancher-selinux[ici.]

[#_installing_the_rancher_selinux_rpm]
== Installation du RPM rancher-selinux

[NOTE]
.Configuration requise{nbsp}:
====
Le RPM `rancher-selinux` a été testé sur openSUSE Tumbleweed et les distributions basées sur RHEL, y compris CentOS/RockyLinux 8 et 9.
====

[#_1_set_up_the_yum_repo]
=== 1. Configurer le dépôt yum

Configurer le dépôt yum pour installer `rancher-selinux` directement sur tous les hôtes du cluster.

Pour utiliser le dépôt RPM, sur un système CentOS 8 ou RHEL 8, exécutez le snippet bash suivant{nbsp}:

----
# cat << EOF > /etc/yum.repos.d/rancher.repo
[rancher]
name=Rancher
baseurl=https://rpm.rancher.io/rancher/production/centos/8/noarch
enabled=1
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

Pour utiliser le dépôt RPM, sur un système CentOS 9 ou RHEL 9, exécutez le snippet bash suivant{nbsp}:

----
# cat << EOF > /etc/yum.repos.d/rancher.repo
[rancher]
name=Rancher
baseurl=https://rpm.rancher.io/rancher/production/centos/9/noarch
enabled=1
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

[#_2_installing_the_rpm]
=== 2. Installation du RPM

Installez le RPM{nbsp}:

----
yum -y install rancher-selinux
----

[#_configuring_the_logging_and_monitoring_applications_to_work_with_selinux]
== Configurer les applications de journalisation et de surveillance pour fonctionner avec SELinux

[NOTE]
.Configuration requise{nbsp}:
====
Logging v2 et Monitoring v2 ont été testés avec SELinux sur RHEL/CentOS 8, 9 et Tumbleweed.
====

Les applications ne fonctionnent pas automatiquement une fois le RPM `rancher-selinux` installé sur l'hôte. Elles doivent être configurées pour s'exécuter dans un domaine de conteneur SELinux autorisé fourni par le RPM.

Pour configurer le chart `rancher-logging` ou le chart `rancher-monitoring` pour prendre en charge SELinux, changez `global.seLinux.enabled` en true dans le `values.yaml` lors de l'installation des charts.
