= SELinux RPM
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-01-20
:page-revdate: {revdate}
:community-path: reference-guides/rancher-security/selinux-rpm/index.adoc 
:product-path: security/selinux-rpm/selinux-rpm.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-selinux: xref:security/selinux-rpm/about-rancher-selinux.adoc
:xref-rke2-selinux: xref:security/selinux-rpm/about-rke2-selinux.adoc
:xref-k3s-selinux: xref:security/selinux-rpm/about-k3s-selinux.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-selinux: xref:reference-guides/rancher-security/selinux-rpm/about-rancher-selinux.adoc
:xref-rke2-selinux: xref:reference-guides/rancher-security/selinux-rpm/about-rke2-selinux.adoc
:xref-k3s-selinux: xref:reference-guides/rancher-security/selinux-rpm/about-k3s-selinux.adoc
endif::[]

https://en.wikipedia.org/wiki/Security-Enhanced_Linux[Linux à sécurité renforcée (SELinux)] est une amélioration de la sécurité pour Linux.

Développé par Red Hat, il s'agit d'une mise en œuvre de contrôles d'accès obligatoires (MAC) sur Linux. Les contrôles d'accès obligatoires permettent à un administrateur d'un système de définir comment les applications et les utilisateurs peuvent accéder à différentes ressources telles que des fichiers, des dispositifs, des réseaux et la communication inter-processus. SELinux renforce également la sécurité en rendant un système d'exploitation restrictif par défaut.

Après avoir été historiquement utilisé par des agences gouvernementales, SELinux est désormais une norme industrielle et activé par défaut sur les distributions SUSE telles que SUSE Linux Enterprise 16, les distributions openSUSE telles que openSUSE Tumbleweed, et les systèmes d'exploitation basés sur RHEL tels que Rocky Linux. Pour vérifier si SELinux est activé et appliqué sur votre système, utilisez `getenforce` :

----
# getenforce
Enforcing
----

Nous fournissons trois RPM (RPM Package Manager) qui permettent aux produits Rancher de fonctionner correctement sur des hôtes où SELinux est appliqué :

* {xref-rancher-selinux}[`rancher-selinux`]
* {xref-rke2-selinux}[`rke2-selinux`]
* {xref-k3s-selinux}[`k3s-selinux`]
