= Configuración de máquinas de Azure
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guías-de-referencia/configuración-del-clúster/configuración-del-clúster-sentido-descendente/configuración-de-máquina/azure.adoc 
:product-path: cluster-deployment/infra-providers/azure/machine-configuration.adoc

Para más información sobre Azure, consulta la https://docs.microsoft.com/en-us/azure/?product=featured[documentación oficial de Azure.]

[#_basic_options]
== Opciones básicas

[#_environment]
=== Entorno

Microsoft proporciona múltiples https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest[nubes] para cumplir con las leyes regionales, que están disponibles para tu uso:

* AzurePublicCloud
* AzureGermanCloud
* AzureChinaCloud
* AzureUSGovernmentCloud

[#_location]
=== Lugar

Configura la https://docs.microsoft.com/en-us/azure/virtual-machines/regions[ubicación] del clúster y de los nodos.

[#_resource_group]
=== Grupo de recursos

Un grupo de recursos es un contenedor que alberga recursos relacionados para una solución de Azure. El grupo de recursos puede incluir todos los recursos de la solución, o solo aquellos recursos que deseas gestionar como un grupo. Decides cómo quieres asignar recursos a los grupos de recursos en función de lo que tenga más sentido para tu organización. Generalmente, añade recursos que compartan el mismo ciclo de vida al mismo grupo de recursos para que puedas desplegarlos, actualizarlos y eliminarlos fácilmente como un grupo.

Utiliza un grupo de recursos existente o introduce un nombre de grupo de recursos y se creará uno para ti.

Para información sobre la gestión de grupos de recursos, consulta la https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal[documentación de Azure.]

[#_availability_set_unmanaged]
=== Conjunto de disponibilidad (no gestionado)

Nombre o ID de un https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview[conjunto de disponibilidad] existente al que añadir la máquina virtual.

[#_image]
=== Imagen

El nombre de la imagen del sistema operativo proporcionada como un identificador de recurso ARM. Requiere el uso de disco administrado.

[#_vm_size]
=== Tamaño de VM

Elige un tamaño para cada VM en el grupo de nodos. Para obtener detalles sobre cada tamaño de VM, consulta https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/[esta página.]

[#_advanced_options]
== Opciones avanzadas

[#_fault_domain_count]
=== Número de dominio de fallo

Los dominios de fallo definen el grupo de máquinas virtuales que comparten la misma fuente de alimentación y el mismo conmutador de red. Si el conjunto de disponibilidad ya ha sido creado, se ignorará el número de dominio de fallo.

Para más información sobre los dominios de fallo, https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview#how-do-availability-sets-work[consulta aquí].

[#_update_domain_count]
=== Número de dominio de actualización

Los dominios de actualización indican grupos de máquinas virtuales y el hardware físico subyacente que pueden reiniciarse al mismo tiempo. Si el conjunto de disponibilidad ya ha sido creado, se ignorará el número de dominio de actualización.

Para más información sobre los dominios de actualización, https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview#how-do-availability-sets-work[consulta aquí].

[#_purchase_plan]
=== Plan de compra

Algunas imágenes de máquinas virtuales en el Marketplace de Azure requieren un plan. Si corresponde, selecciona un plan de compra, formateado como `publisher:product:plan`, para usar con la imagen elegida.

[#_subnet]
=== Subred

El nombre de la subred al crear una nueva VNet o al hacer referencia a una existente.

Por defecto: `docker-machine`

[#_subnet_prefix]
=== Prefijo de subred

El prefijo de dirección IP de la subred que se utilizará al crear una nueva VNet en formato CIDR.

Por defecto: `192.168.0.0/16`

[#_virtual_network]
=== Red virtualizada

La https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview[red virtual] que se utilizará o creará si no existe una. Formateado como `[resourcegroup:]name`.

[#_public_ip_options]
=== Opciones de IP pública

[#_no_public_ip]
==== Sin IP pública

No asignar una dirección IP pública.

[#_static_public_ip]
==== IP pública estática

Asignar una dirección IP pública estática.

[#_use_private_ip]
=== Usar IP privada

Usar una dirección IP privada estática.

[#_private_ip_address]
=== Dirección IP privada

Configurar una dirección IP privada estática para usar.

[#_network_security_group]
=== Grupo de seguridad de red

El https://docs.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview[grupo de seguridad de red] que se utilizará. Todos los nodos que utilicen esta plantilla usarán el grupo de seguridad de red proporcionado. Si no se proporciona un grupo de seguridad de red, se creará uno nuevo para cada nodo.

[#_dns_label]
=== Etiqueta DNS

Una etiqueta de nombre DNS única para la dirección IP pública.

[#_storage_type]
=== Tipo de Almacenamiento

El tipo de https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview[cuenta de almacenamiento] que se debe utilizar con tus máquinas virtuales. Las opciones incluyen Standard LRS, Standard ZRS, Standard GRS, Standard RAGRS y Premium LRS.

[#_use_managed_disks]
=== Usar Discos Administrados

Los https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview[discos administrados de Azure] son volúmenes de almacenamiento a nivel de bloque que son gestionados por Azure y utilizados con Máquinas Virtuales de Azure. Los discos administrados están diseñados para una disponibilidad del 99.999%. Los discos administrados logran esto al proporcionarte tres réplicas de tus datos, lo que permite una alta durabilidad.

[#_managed_disk_size]
=== Tamaño del Disco Administrado

El tamaño en GB del disco para cada nodo.

[#_ssh_username]
=== Nombre de Usuario SSH

El nombre de usuario utilizado para crear una conexión SSH a tus nodos.

[#_open_port]
=== Puerto Abierto

Abre el tráfico entrante en los puertos especificados. Al usar un Grupo de Seguridad de Red existente, se ignoran los Puertos Abiertos.

Por defecto: `2379/tcp, 2380/tcp, 6443/tcp, 9796/tcp, 10250/tcp, 10251/tcp, 10252/tcp, 10256/tcp` y `8472/udp, 4789/udp`
