= Control de acceso basado en funciones para el registro
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/rbac-for-logging.adoc 
:product-path: observability/logging/rbac-for-logging.adoc

El registro de Rancher tiene dos roles, `logging-admin` y `logging-view`.

* `logging-admin` otorga a los usuarios acceso completo a los `Flows` y `Outputs` en el espacio de nombres
* `logging-view` permite a los usuarios _ver_ los `Flows` y `Outputs` en el espacio de nombres, y `ClusterFlows` y `ClusterOutputs`

[NOTE]
.¿Por qué elegir un rol sobre el otro?
====

El acceso de edición a los recursos `ClusterFlow` y `ClusterOutput` es poderoso. Cualquier usuario que lo tenga tiene acceso de edición para todos los registros en el clúster.
====


En Rancher, el rol de administrador del clúster es el único rol con acceso completo a todos los recursos `rancher-logging`. Los miembros del clúster no pueden editar ni leer ningún recurso de registro. Los propietarios y miembros del proyecto tienen los siguientes privilegios:

|===
| Propietarios del proyecto | Miembros del proyecto

| capaces de crear los `Flows` y `Outputs` en los espacios de nombres de sus proyectos
| solo pueden ver los `Flows` y `Outputs` en los espacios de nombres de los proyectos

| pueden recopilar los registros de cualquier cosa en los espacios de nombres de sus proyectos
| no pueden recopilar ningún registro en los espacios de nombres de sus proyectos
|===

Tanto los propietarios como los miembros del proyecto requieren al menos _un_ espacio de nombres en su proyecto para usar el registro. Si no lo hacen, entonces puede que no vean el botón de registro en el menú desplegable de navegación superior.
