= Trabajando con Taints y Tolerations
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/taints-and-tolerations.adoc 
:product-path: observabilidad/logging/taints-and-tolerations.adoc

"Tainting" un nodo de Kubernetes hace que los pods eviten ejecutarse en ese nodo.

A menos que los pods tengan un `toleration` para el taint de ese nodo, se ejecutarán en otros nodos del clúster.

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[Taints and tolerations] pueden funcionar en conjunto con el `nodeSelector` https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector[campo] dentro del `PodSpec`, lo que permite el _efecto opuesto_ de un taint.

Usar `nodeSelector` otorga a los pods una afinidad hacia ciertos nodos.

Ambos proporcionan elección sobre en qué nodo(s) se ejecutará el pod.

* <<_default_implementation_in_ranchers_logging_stack,Implementación por defecto en el Stack de Logging de Rancher>>
* <<_adding_nodeselector_settings_and_tolerations_for_custom_taints,Añadiendo configuraciones de NodeSelector y toleraciones para taints personalizados>>

[#_default_implementation_in_ranchers_logging_stack]
== Implementación por defecto en el Stack de Logging de Rancher

Por defecto, Rancher aplica un taint a todos los nodos Linux con `cattle.io/os=linux`, y no aplica ninguno a los nodos Windows.
Los pods del stack de logging tienen `tolerations` para este taint, lo que les permite ejecutarse en nodos Linux.
Además, la mayoría de los pods del stack de logging se ejecutan solo en Linux y tienen un `nodeSelector` añadido para asegurar que se ejecuten en nodos Linux.

Este archivo YAML de ejemplo de Pod muestra un nodeSelector siendo utilizado con una toleration:

[,yaml]
----
apiVersion: v1
kind: Pod
# metadata...
spec:
  # containers...
  tolerations:
    - key: cattle.io/os
      operator: "Equal"
      value: "linux"
      effect: NoSchedule
  nodeSelector:
    kubernetes.io/os: linux
----

En el ejemplo anterior, aseguramos que nuestro pod solo se ejecute en nodos Linux, y añadimos un `toleration` para el taint que tenemos en todos nuestros nodos Linux.

Puedes hacer lo mismo con los taints existentes de Rancher, o con los tuyos propios personalizados.

[#_adding_nodeselector_settings_and_tolerations_for_custom_taints]
== Añadiendo configuraciones de NodeSelector y toleraciones para taints personalizados

Si deseas añadir tus propios ajustes de `nodeSelector`, o si deseas añadir `tolerations` para taints adicionales, puedes pasar lo siguiente a los valores del chart.

[,yaml]
----
tolerations:
  # insert tolerations...
nodeSelector:
  # insert nodeSelector...
----

Estos valores añadirán ambos ajustes a los contenedores `fluentd`, `fluentbit` y `logging-operator`.
Esencialmente, estos son ajustes globales para todos los pods en el stack de logging.

Sin embargo, si deseas añadir tolerations para _solo_ el contenedor `fluentbit`, puedes añadir lo siguiente a los valores del chart.

[,yaml]
----
fluentbit_tolerations:
  # insert tolerations list for fluentbit containers only...
----
