= Solución de problemas
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/logging.adoc 
:product-path: observabilidad/registro/troubleshooting.adoc
:experimental:

[#_log_levels]
== Niveles de registro

Los siguientes niveles de registro se utilizan en Rancher:

|===
| Nombre | Descripción

| `info`
| Registra mensajes informativos. Este es el nivel de registro por defecto.

| `debug`
| Registra mensajes más detallados que pueden ser utilizados para depurar.

| `trace`
| Registra mensajes muy detallados sobre funciones internas. Esto es muy verboso y puede contener información sensible.
|===

[#_how_to_configure_a_log_level]
=== Cómo configurar un nivel de registro

[#_kubernetes_install]
==== Instalación de Kubernetes

* Configurar el nivel de registro de depuración

 $ KUBECONFIG=./kube_config_cluster.yml
 $ kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -c rancher -- loglevel --set debug; done
 OK
 OK
 OK
 $ kubectl -n cattle-system logs -l app=rancher -c rancher

* Configurar el nivel de registro informativo

 $ KUBECONFIG=./kube_config_cluster.yml
 $ kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -c rancher -- loglevel --set info; done
 OK
 OK
 OK

[#_docker_install]
==== Instalación de Docker

* Configurar el nivel de registro de depuración

 $ docker exec -ti <container_id> loglevel --set debug
 OK
 $ docker logs -f <container_id>

* Configurar el nivel de registro informativo

 $ docker exec -ti <container_id> loglevel --set info
 OK

[#_rancher_machine_debug_logs]
== Registros de depuración de Rancher Machine

Si necesitas solucionar problemas en la creación de objetos en tu proveedor de infraestructura elegido, `rancher-machine` los registros de depuración pueden ser útiles para ti.

Es posible habilitar registros de depuración para `rancher-machine` configurando variables de entorno al iniciar Rancher.

La variable de entorno `CATTLE_WHITELIST_ENVVARS` permite a los usuarios incluir en la lista blanca variables de entorno específicas que se pasarán a `rancher-machine` durante la provisión.

La variable `MACHINE_DEBUG` habilita los registros de depuración en `rancher-machine`.

Así, al establecer `MACHINE_DEBUG=true` y añadir `MACHINE_DEBUG` a la lista de variables predeterminadas en `CATTLE_WHITELIST_ENVVARS` (por ejemplo, `CATTLE_WHITELIST_ENVVARS=HTTP_PROXY,HTTPS_PROXY,NO_PROXY,MACHINE_DEBUG`), es posible habilitar los registros de depuración en `rancher-machine` al aprovisionar clústeres RKE1, RKE2 y k3s.

[CAUTION]
====

Al igual que el nivel de registro `trace` mencionado anteriormente, los registros de depuración `rancher-machine` pueden contener información sensible.
====


[#_cattle_cluster_agent_debug_logs]
== Registros de depuración del agente del clúster de Cattle

Los niveles de registro `cattle-cluster-agent` se pueden establecer al inicializar clústeres en sentido descendente.

Cuando creas un clúster bajo menu:Configuración del Clúster[Variables de Entorno del Agente], puedes establecer variables para definir el nivel de registro.

* Registro a nivel de traza: Establece `CATTLE_TRACE` o `RANCHER_TRACE` a `true`
* Registro a nivel de depuración: Establece `CATTLE_DEBUG` o `RANCHER_DEBUG` a `true`

[CAUTION]
====

Los registros de depuración `cattle-cluster-agent` pueden contener información sensible.
====

