= Einrichtung des Microsoft Active Directory Federation Service (SAML)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-09-18
:page-revdate: {revdate}
:community-path: how-to-guides/neue-nutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/configure-microsoft-ad-federation-service-saml/index.adoc 
:product-path: rancher-admin/benutzer/authn-und-authz/microsoft-ad-federation-service-saml/microsoft-ad-federation-service-saml.adoc
ifeval::["{build-type}" != "community"]
:xref-ms-adfs-for-rancher: xref:rancher-admin/benutzer/authn-und-authz/microsoft-ad-federation-service-saml/ms-adfs-für-rancher.adoc
:xref-rancher-for-ms-adfs: xref:rancher-admin/benutzer/authn-und-authz/microsoft-ad-federation-service-saml/rancher-für-ms-adfs.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-ms-adfs-for-rancher: xref:how-to-guides/neue-benutzeranleitungen/authentifizierungsberechtigungen-und-globale-konfiguration/configure-microsoft-ad-federation-service-saml/configure-ms-adfs-für-rancher.adoc
:xref-rancher-for-ms-adfs: xref:how-to-guides/neue-nutzeranleitungen/authentifizierung-berechtigungen-und-globale-konfiguration/configure-microsoft-ad-federation-service-saml/configure-rancher-für-ms-adfs.adoc
endif::[]

Wenn Ihre Organisation Microsoft Active Directory Federation Services (AD FS) zur Benutzerauthentifizierung verwendet, können Sie Rancher so konfigurieren, dass Ihre Benutzer sich mit ihren AD FS-Anmeldeinformationen anmelden können.

[#_prerequisites]
== Voraussetzungen

Sie müssen Rancher installiert haben.

* Erhalten Sie die URL Ihres Rancher-Servers. Ersetzen Sie während der AD FS-Konfiguration diese URL durch den Platzhalter `<RANCHER_SERVER>`.
* Sie müssen über ein globales Administratorkonto in Ihrer Rancher-Installation verfügen.

Sie müssen einen https://docs.microsoft.com/en-us/windows-server/identity/active-directory-federation-services[Microsoft AD FS Server] konfiguriert haben.

* Erhalten Sie den IP/DNS-Namen Ihres AD FS-Servers. Ersetzen Sie während der AD FS-Konfiguration diesen IP/DNS-Namen durch den Platzhalter `<AD_SERVER>`.
* Sie müssen Zugriff haben, um https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/create-a-relying-party-trust[Relying Party Trusts] auf Ihrem AD FS-Server hinzuzufügen.

[#_setup_outline]
== Setup-Übersicht

Die Einrichtung von Microsoft AD FS mit Rancher Server erfordert die Konfiguration von AD FS auf Ihrem Active Directory-Server und die Konfiguration von Rancher zur Nutzung Ihres AD FS-Servers. Die folgenden Seiten dienen als Leitfäden zur Einrichtung der Microsoft AD FS-Authentifizierung in Ihrer Rancher-Installation.

* {xref-ms-adfs-for-rancher}[1. Konfiguration von Microsoft AD FS für Rancher]
* {xref-rancher-for-ms-adfs}[2. Konfiguration von Rancher für Microsoft AD FS]

[NOTE]
.SAML-Anbieter-Hinweise
====
* Benutzer und Gruppen werden nicht validiert, wenn Sie ihnen Berechtigungen in Rancher zuweisen.
* Beim Hinzufügen von Benutzern müssen die genauen Benutzer-IDs (d.h. `UID Field`) korrekt eingegeben werden. Während Sie die Benutzer-ID eingeben, wird nicht nach anderen Benutzer-IDs gesucht, die möglicherweise übereinstimmen.
* Beim Hinzufügen von Gruppen müssen Sie die Gruppe aus dem Dropdown-Menü auswählen, das neben dem Textfeld steht. Rancher geht davon aus, dass jede Eingabe im Textfeld ein Benutzer ist.
* Das Gruppen-Dropdown zeigt nur die Gruppen an, in denen Sie Mitglied sind. Wenn Sie jedoch Administratorrechte oder eingeschränkte Administratorrechte haben, können Sie einer Gruppe beitreten, in der Sie kein Mitglied sind.
====

[#__xref_ms_adfs_for_rancher_next_configuring_microsoft_ad_fs_for_rancher]
=== {xref-ms-adfs-for-rancher}[Weiter: Konfiguration von Microsoft AD FS für Rancher]
