= Conseils pour la migration de RKE1 vers {rke2-product-name} Windows
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guides-de-procédure/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-configuration/utiliser-des-clusters-windows/migration-des-charges-de-travail.adoc 
:product-path: cluster-deployment/custom-clusters/windows/workload-migration-guidance.adoc

CAUTION: Le contenu de ce document n'est pas couvert par le SLA de Rancher Support. Veuillez procéder avec prudence.

Ce document explique comment les utilisateurs finaux peuvent migrer leurs charges de travail Windows de RKE1 vers RKE2.

[#_rke1_windows_scheduling]
== Planification Windows RKE1

La planification des charges de travail Windows RKE1 est basée sur les taints et les tolerations.

Chaque nœud Linux d'un cluster Windows RKE1, quel que soit le rôle qui lui est assigné, aura une taint par défaut qui empêche la planification des charges de travail, à moins que celles-ci ne disposent d'une toleration configurée. C'est une caractéristique majeure de conception des clusters Windows RKE1 qui ont été conçus pour ne faire fonctionner que des charges de travail Windows.

* Taint par défaut du nœud Linux RKE1 `NoSchedule`{nbsp}:

[,yml]
----
apiVersion: v1
kind: Node
spec:
  ...
  taints:
  - effect: NoSchedule
    key: cattle.io/os
    value: linux
----

{blank}

* Toleration RKE1 Linux `NoSchedule` pour les charges de travail

La toleration suivante permettrait à une charge de travail d'utilisateur final d'être planifiée sur n'importe quel nœud Linux d'un cluster Windows RKE1. Ces tolerations sont utilisées pour divers services et charges de travail essentiels de Rancher.

[,yml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
----

{blank}

* En accord avec les meilleures pratiques, toutes les charges de travail d'utilisateur final exécutées sur des nœuds Linux seraient planifiées uniquement sur ceux ayant le rôle de travailleur{nbsp}:

[,yml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
            weight: 100
      ...
----

[#__rke2_product_name_windows_scheduling]
== {rke2-product-name} Planification Windows

Sur la base des retours et des demandes de support pour les charges de travail hybrides, RKE2 Windows a été conçu pour prendre en charge par défaut à la fois les charges de travail Linux et Windows. La planification RKE2 repose par défaut sur des sélecteurs de nœuds. C'est un changement marqué par rapport à RKE1, car les taints et les tolerations n'ont pas été intégrés dans RKE2. Les sélecteurs de nœuds étaient une partie critique des clusters Windows RKE1, ce qui facilite la migration de vos charges de travail.

[#_example_migrations]
== Exemples de migrations

[#_rke1_to_rke2_product_name_windows_workload]
=== RKE1 vers {rke2-product-name} Charge de travail Windows

* Déploiement RKE1 Windows avant la migration{nbsp}:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: NotIn
                values:
                - linux
----

{blank}

* Déploiement RKE2 Windows migré utilisant `NodeAffinity`{nbsp}:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      ...
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - windows
----

[#_rke1_windows_cluster_linux_only_deployment]
=== Déploiement du cluster Windows RKE1 exclusivement sous Linux

[IMPORTANT]
====
Lors de l'utilisation des sélecteurs de nœuds et de l'affinité des nœuds, notez ce qui suit{nbsp}:

* Si `nodeSelector` et `nodeAffinity` sont tous deux spécifiés, les deux doivent être satisfaits pour que le `Pod` soit planifié sur un nœud.
* Si vous spécifiez plusieurs `matchExpressions` associés à un seul `nodeSelectorTerms`, alors le `Pod` ne peut être planifié sur un nœud que si tous les `matchExpressions` sont satisfaits.
====

{blank}

* Déploiement du cluster Windows RKE1 exclusivement Linux avant la migration, ciblant les nœuds de travail Linux RKE1{nbsp}:

[,yml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
----

{blank}

* Déploiement RKE2 cluster hybride uniquement Linux migré ciblant les nœuds de travail Linux RKE2 utilisant des sélecteurs de nœuds{nbsp}:

[,yml]
----
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
      nodeSelector:
        kubernetes.io/os: "linux"
        node-role.kubernetes.io/worker: "true"
----

{blank}

* Déploiement RKE2 cluster hybride uniquement Linux migré ciblant les nœuds de travail Linux RKE2 utilisant l'affinité des nœuds{nbsp}:

[,yaml]
----
 apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    ...
    spec:
       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
----

[#_rke1_windows_supported_windows_server_versions]
== Versions de Windows Server prises en charge par RKE1 Windows

[#_long_term_servicing_channel_ltsc]
=== Canal de service à long terme (LTSC)

* Windows Server 2019 LTSC &#9989; atteindra l'EOL principale le 9 janvier 2024 et l'EOL prolongée le 9 janvier 2029

[#_semi_annual_channel_sac]
=== Canal semi-annuel (SAC)

* Windows Server 20H2 SAC &#10060; a atteint l'EOL le 9 août 2022
* Windows Server 2004 SAC &#10060; a atteint l'EOL le 14 décembre 2021
* Windows Server 1909 SAC &#10060; a atteint l'EOL le 11 mai 2021
* Windows Server 1903 SAC &#10060; a atteint l'EOL le 8 décembre 2020
* Windows Server 1809 SAC &#10060; a atteint l'EOL le 10 novembre 2020

[#__rke2_product_name_windows_supported_windows_server_versions]
== {rke2-product-name} Versions de Windows Server prises en charge par Windows

[#_long_term_servicing_channel_in_rke2_product_name]
=== Canal de service à long terme dans {rke2-product-name}

* Windows Server 2019 LTSC &#9989; atteindra l'EOL principale le 9 janvier 2024 et l'EOL prolongée le 9 janvier 2029
* Windows Server 2022 LTSC &#9989; atteindra l'EOL principale le 13 octobre 2026 et l'EOL prolongée le 13 octobre 2031

NOTE: SAC n'est pas pris en charge dans RKE2.

Pour plus d'informations, veuillez consulter les références suivantes{nbsp}:

* https://docs.microsoft.com/en-us/lifecycle/products/windows-server[Cycle de vie de Windows Server SAC]
* https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2022[Cycle de vie de Windows Server 2022 LTSC]
* https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2019[Cycle de vie de Windows Server 2019 LTSC]

[#_kubernetes_version_support]
== Support des versions de Kubernetes

NOTE: Toutes les versions énumérées ci-dessous sont prises en charge par SLA selon le https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-7/[Tableau de support Rancher v2.6.7]. Toute version non listée doit être considérée comme étant en fin de vie et non prise en charge par SLA par SUSE.

[#_rancher_2_5_vs_rancher_2_6_support_matrix_for_windows_clusters]
=== Rancher 2.5 contre. Tableau de support Rancher 2.6 pour les clusters Windows

*RKE1 contre. Versions de Kubernetes prises en charge par le cluster Windows RKE2 :*

[cols=",^,^"]
|===
| Kubernetes Versions | RKE1 | RKE2

| 1.18
| &check;
|

| 1.19
| &check;
|

| 1.20
| &check;
|

| 1.21
| &check;
|

| 1.22
| &check;
| &check;

| 1.23
|
| &check;

| 1.24
|
| &check;

| 1.25+
|
| &check;
|===

[#_rancher_2_5_vs_rancher_2_6_supported_kubernetes_versions_for_provisioning_rke1_and_rke2_windows_clusters]
=== Rancher 2.5 contre. Versions de Kubernetes prises en charge par Rancher 2.6 pour le provisionnement de RKE1 et {rke2-product-name} des clusters Windows

[cols="^,^,^,^"]
|===
| Versions de Rancher | Kubernetes Versions | RKE1 | RKE2

| 2.5 - Provisionnement RKE1
| 1.18 1.19 1.20
| &check;
|

| 2.6 - Provisionnement RKE1
| 1.18 1.19 1.20 1.21 1.22
| &check;
|

| 2.6 - Provisionnement RKE2
| 1.22 1.23 1.24 1.25+
|
| &check;
|===

[#_guiding_migrations_of_workloads_to_rke2_product_name_windows]
== Orientation pour la migration des charges de travail vers {rke2-product-name} Windows

Reportez-vous aux tableaux dans <<_rancher_2_5_vs_rancher_2_6_support_matrix_for_windows_clusters,Rancher 2.5 vs. Matrice de support Rancher 2.6 pour les clusters Windows>> et <<_rancher_2_5_vs_rancher_2_6_supported_kubernetes_versions_for_provisioning_rke1_and_rke2_windows_clusters,Rancher 2.5 vs. Versions Kubernetes prises en charge par Rancher 2.6 pour le provisionnement des clusters Windows RKE1 et RKE2>>, vous trouverez le chevauchement des versions Kubernetes entre RKE1 et RKE2 qui se produit dans 1.22. Ceci sera la version de base requise pour migrer les charges de travail Windows RKE1 en suivant l'approche recommandée par Rancher.

[#_in_place_upgrade_of_rancher_2_5]
=== Mise à niveau sur place de Rancher 2.5

. Mettre à niveau la version de Rancher vers v2.6.5+.
. Mettre à niveau le(s) cluster(s) en aval Windows RKE1 vers RKE1 v1.22 en utilisant la dernière version de correctif disponible.
. Provisionner un nouveau cluster en aval Windows RKE2 en utilisant RKE2 v1.22 avec la version de correctif correspondante à celle du cluster Windows RKE1.
. Commencer la migration des charges de travail Windows des clusters RKE1 vers RKE2.
. Effectuer des tests de validation pour s'assurer qu'il n'y a eu aucune perte ou changement de fonctionnalité lors de la migration de votre application de RKE1 vers RKE2.
. Après que des tests de validation réussis aient eu lieu, vous pouvez choisir de mettre à niveau votre cluster RKE2 1.22.x vers une nouvelle version mineure telle que 1.23 ou 1.24.

[#_migrating_windows_workloads_to_a_new_rancher_environment]
=== Migration des charges de travail Windows vers un nouvel environnement Rancher

IMPORTANT: Pour effectuer l'une des options suivantes, il faut Rancher v2.6.5 ou supérieur.

*Lors de l'utilisation de versions de correctif Kubernetes correspondantes pour RKE1 et RKE2 :*

. Provisionner un nouveau cluster en aval Windows RKE2 en utilisant RKE2 v1.22 avec la version de correctif correspondante à celle du cluster Windows RKE1.
. Commencer la migration des charges de travail Windows des clusters RKE1 vers RKE2.
. Effectuer des tests de validation pour s'assurer qu'il n'y a eu aucune perte ou changement de fonctionnalité lors de la migration de votre application de RKE1 vers RKE2.
. Après que des tests de validation réussis aient eu lieu, vous pouvez choisir de mettre à niveau votre cluster RKE2 1.22.x vers une nouvelle version mineure telle que 1.23 ou 1.24.

*Lors de l'utilisation d'une version de correctif Kubernetes plus récente pour RKE2 :*

. Provisionner un nouveau cluster en aval Windows RKE2 en utilisant RKE2 v1.23 ou v1.24.
. Commencer la migration des charges de travail Windows des clusters RKE1 vers RKE2.
. Effectuer des tests de validation pour s'assurer qu'il n'y a eu aucune perte ou changement de fonctionnalité lors de la migration de votre application de RKE1 vers RKE2.
