= Roles Bloqueados
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/guías-de-usuarios-nuevos/guías-de-autenticación-permisos-y-configuración-global/gestionar-control-de-acceso-basado-en-funciones-rbac/roles-bloqueados.adoc 
:product-path: rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
ifeval::["{build-type}" != "community"]
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-custom-roles: xref:como-guías/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/gestionar-control-de-acceso-basado-en-funciones-rbac/roles-personalizados.adoc
endif::[]

Puedes establecer roles en un estado de `locked`. Bloquear roles impide que se asignen a usuarios en el futuro.

Roles bloqueados:

* No pueden ser asignados a usuarios que no los tengan ya asignados.
* No aparecen en el menú desplegable *Roles de Miembros* cuando estás añadiendo un usuario a un clúster o proyecto.
* No afectan a los usuarios a los que se les asignó el rol antes de bloquearlo. Estos usuarios mantienen el acceso que proporciona el rol.
+
*Ejemplo:* digamos que tu organización crea una política interna que prohíbe a los usuarios asignados a un clúster crear nuevos proyectos. Es tu trabajo hacer cumplir esta política.
+
Para hacerla cumplir, antes de añadir nuevos usuarios al clúster, deberías bloquear los siguientes roles: `Cluster Owner`, `Cluster Member` y `Create Projects`. Luego podrías crear un nuevo rol personalizado que incluya los mismos permisos que un *Miembro del Clúster*, excepto la capacidad de crear proyectos. Entonces, utilizas este nuevo rol personalizado al añadir usuarios a un clúster.

Los roles pueden ser bloqueados por los siguientes usuarios:

* Cualquier usuario asignado el `Administrator` permiso global.
* Cualquier usuario asignado el `Custom Users` permiso, junto con el rol `Manage Roles`.

[#_locking_unlocking_roles]
== Bloquear/Desbloquear Roles

Si deseas evitar que un rol sea asignado a usuarios, puedes establecerlo en un estado de `locked`.

Puedes bloquear roles en dos contextos:

* Cuando estás {xref-custom-roles}[añadiendo un rol personalizado].
* Cuando estás editando un rol existente (ver más abajo).

Los roles de clúster y los roles de proyecto/espacio de nombres pueden ser bloqueados, pero los roles globales no pueden.

. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En la barra de navegación izquierda, haz clic en *Plantillas de rol*.
. Ve a la pestaña *Clúster* o a la pestaña *Proyecto/Espacio de nombres*.
. Desde el rol que quieres bloquear (o desbloquear), selecciona *⋮ > Editar configuración*.
. Desde la opción *Bloqueado*, elige el botón de radio *Sí* o *No*. Luego haz clic en *Guardar*.
