= {rancher-product-name} Equinix Metal Kurzanleitung
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/equinix-metal.adoc 
:product-path: installation-and-upgrade/quick-start/deploy-rancher/equinix-metal.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-qs-deploy-workloads: xref:installation-and-upgrade/quick-start/deploy-workloads/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-qs-deploy-workloads: xref:getting-started/quick-start-guides/deploy-workloads/index.adoc
endif::[]

[#_this_tutorial_walks_you_through_the_following]
== Dieses Tutorial führt Sie durch die folgenden Schritte:

* Bereitstellung eines Equinix Metal Servers
* Installation of Rancher 2.x
* Erstellung Ihres ersten Clusters
* Implementierung einer Anwendung, Nginx

[CAUTION]
====

Ziel dieser Anleitungen ist es, schnell eine Sandbox zu starten, die Sie zur Evaluierung von Rancher nutzen können. Die Docker-Installation wird nicht für Produktionsumgebungen empfohlen. Für umfassende Installationsanleitungen siehe {xref-install-upgrade}[Installation].
====


[#_quick_start_outline]
== Kurzanleitung Übersicht

Diese Kurzanleitung ist in verschiedene Aufgaben unterteilt, um die Nutzung zu erleichtern.

[#_prerequisites]
== Voraussetzungen

* Ein https://deploy.equinix.com/developers/docs/metal/identity-access-management/users/[Equinix Metal-Konto]
* Ein https://deploy.equinix.com/developers/docs/metal/projects/creating-a-project/[Equinix Metal-Projekt]

[#_1_provision_a_equinix_metal_host]
=== 1. Provisionieren Sie einen Equinix Metal Host

Beginnen Sie mit der Bereitstellung eines Equinix Metal Hosts. Equinix Metal Server können entweder über die Equinix Metal-Konsole, API oder CLI bereitgestellt werden. Sie finden Anleitungen für jeden Bereitstellungstyp in der https://deploy.equinix.com/developers/docs/metal/deploy/on-demand/[Equinix Metal-Implementierungsdokumentation]. Zusätzliche Informationen zu den Servertypen von Equinix Metal finden Sie in der https://deploy.equinix.com/developers/docs/metal/hardware/standard-servers/[Equinix Metal Dokumentation].

[NOTE]
.Hinweise:
====

* Beim Bereitstellen eines neuen Equinix Metal Servers über die CLI oder API müssen Sie die folgenden Informationen angeben: Projekt-ID, Plan, Metro und Betriebssystem.
* Bei der Verwendung einer cloudbasierten virtuellen Maschine müssen Sie eingehende TCP-Kommunikation zu den Ports 80 und 443 zulassen. Bitte beachten Sie die Dokumentation Ihres Cloud-Anbieters für Informationen zur Portkonfiguration.
* Für eine vollständige Liste der Portanforderungen verweisen Sie auf {xref-node-reqs}[Docker-Installation].
* Stellen Sie den Host gemäß unseren {xref-install-reqs}[Anforderungen] bereit.
====


[#_2_install_rancher]
=== 2. Rancher installieren

Um Rancher auf Ihrem Equinix Metal Host zu installieren, verbinden Sie sich mit ihm und verwenden Sie dann eine Shell zur Installation.

. Melden Sie sich bei Ihrem Equinix Metal Host mit Ihrer bevorzugten Shell an, wie PuTTy oder einer Remote-Terminalverbindung.
. Geben Sie in Ihrer Shell den folgenden Befehl ein:
+
----
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher
----

*Ergebnis:* Rancher ist installiert.

[#_3_log_in]
=== 3. Anmeldung

Melden Sie sich bei Rancher an, um die Anwendung zu verwenden. Nachdem Sie sich angemeldet haben, werden Sie einige einmalige Konfigurationen vornehmen.

. Öffnen Sie einen Webbrowser und geben Sie die IP-Adresse Ihres Hosts ein: `\https://<server_ip>`.
+
Ersetzen Sie `<SERVER_IP>` durch die IP-Adresse Ihres Hosts.

. Wenn Sie dazu aufgefordert werden, erstellen Sie ein Passwort für das Standard-`admin` Konto.
. Legen Sie die *Rancher Server-URL* fest. Die URL kann entweder eine IP-Adresse oder ein Hostname sein. Jeder Knoten, der zu Ihrem Cluster hinzugefügt wird, muss jedoch in der Lage sein, sich mit dieser URL zu verbinden. +
 +
Wenn Sie einen Hostnamen in der URL verwenden, muss dieser Hostname von DNS auf den Knoten, die Sie zu Ihrem Cluster hinzufügen möchten, auflösbar sein.

{blank}

[#_4_create_the_cluster]
=== 4. Erstellen Sie den Cluster

Willkommen bei Rancher! Sie können jetzt Ihren ersten Kubernetes-Cluster erstellen.

In dieser Aufgabe können Sie die vielseitige *Benutzerdefiniert* Option verwenden. Diese Option ermöglicht es Ihnen, _beliebigen_ Linux-Host (cloud-basiertes VM, lokale VM oder Bare-Metal) zu einem Cluster hinzuzufügen.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Klicken Sie auf der *Cluster* Seite auf *Erstellen*.
. Wählen Sie *Benutzerdefiniert*.
. Geben Sie einen *Cluster-Namen* ein.
. Klicken Sie auf *Weiter*.
. Wählen Sie aus *Knotenrolle* _alle_ Rollen: *etcd*, *Control* und *Worker*.
 ** *Optional*: Rancher erkennt automatisch die IP-Adressen, die für die Rancher-Kommunikation und die Cluster-Kommunikation verwendet werden. Sie können diese im Abschnitt *Knotenadresse* mit `Public Address` und `Internal Address` überschreiben.
. Kopieren Sie den Registrierungsbefehl in Ihre Zwischenablage.
. Melden Sie sich bei Ihrem Linux-Host mit Ihrer bevorzugten Shell an, wie PuTTy oder einer Remote-Terminalverbindung. Führen Sie den in Ihre Zwischenablage kopierten Befehl aus.
. Wenn Sie das Ausführen des Befehls auf Ihrem Linux-Host abgeschlossen haben, klicken Sie auf *Fertig*.

*Ergebnis:*

Ihr Cluster wurde erstellt und hat den Status *Bereitstellung* erhalten. Rancher richtet Ihren Cluster ein.

Sie können auf Ihren Cluster zugreifen, nachdem sein Status auf *Aktiv* aktualisiert wurde.

*Aktiven* Clustern werden zwei Projekte zugewiesen:

* `Default`, das den `default` Namespace enthält
* `System`, das die Namespaces `cattle-system`, `traefik`, `kube-public` und `kube-system` enthält

[#_finished]
==== Abgeschlossen

Herzlichen Glückwunsch! Sie haben Ihren ersten Cluster erstellt.

[#_whats_next]
==== Was kommt als Nächstes?

Verwenden Sie Rancher, um eine Implementierung zu erstellen. Weitere Informationen finden Sie unter {xref-qs-deploy-workloads}[Implementierungen erstellen].
