= Acesso a Clusters
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/access-clusters/index.adoc 
:product-path: cluster-admin/manage-clusters/access-clusters/access-clusters.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
:xref-user-api-keys: rancher-admin/users/settings/api-keys.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-manage-rbac: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc
:xref-add-users-to-clusters: xref:cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
:xref-user-api-keys: xref:reference-guides/user-settings/api-keys.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
:xref-manage-rbac: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/index.adoc
:xref-add-users-to-clusters: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/add-users-to-clusters.adoc
endif::[]

Esta seção trata das ferramentas que podem ser usadas para acessar clusters gerenciados pelo Rancher.

Para informações sobre como conceder permissão a usuários para acessar um cluster, consulte a seção sobre {xref-add-users-to-clusters}[adicionar usuários a clusters.]

Para mais informações sobre controle de acesso com base em função, veja {xref-manage-rbac}[esta seção.]

Para informações sobre como configurar um sistema de autenticação, consulte {xref-authn-authz}[esta seção.]

[#_clusters_in_rancher_ui]
== Clusters na interface do Rancher

Existem vários caminhos para visualizar e gerenciar clusters através da interface do Rancher.

[#_clusters_page]
=== Página de Clusters

Você pode acessar a página *Clusters* a partir do menu *☰*:

. Clique *☰*.
. Selecione *Gerenciamento de Cluster*.

Você também pode acessar a página *Clusters* clicando no botão *Gerenciar* acima da tabela de clusters na interface do Rancher *Página Inicial*.

Na página *Clusters*, selecione *⁝* no final de cada linha para visualizar um submenu com as seguintes opções:

* {xref-access-cluster-kubectl}[Kubectl Shell]
* Download KubeConfig
* Copiar KubeConfig para a Área de Transferência
* Editar Configuração
* Ver YAML
* Baixar YAML

[#_cluster_dashboard]
=== Painel do Cluster

Na página *Clusters*, selecione o botão *Explorar* no final de cada linha para visualizar o *Painel do Cluster* desse cluster. Você também pode visualizar o painel clicando no nome de um cluster na tabela e, em seguida, clicando no botão *Explorar* na página *Cluster*.

O *Painel do Cluster* também é acessível a partir da interface do Rancher *Página Inicial*, clicando no nome de um cluster.

Você também pode acessar o *Painel do Cluster* pelo *☰* na barra de navegação superior:

. Clique *☰*.
. Selecione o nome de um cluster na opção de menu *Explorar Cluster*.

O *Painel do Cluster* lista informações sobre um cluster específico, como número de nós, uso de memória, eventos e recursos.

[#_kubectl]
== kubectl

Você pode usar a ferramenta de linha de comando do Kubernetes, https://kubernetes.io/docs/reference/kubectl/overview/[kubectl], para gerenciar seus clusters. Você tem duas opções para usar o kubectl:

* *Shell kubectl do Rancher:* Interaja com seus clusters lançando um shell kubectl disponível na interface do Rancher. Esta opção não requer ações de configuração da sua parte. Para mais informações, consulte {xref-access-cluster-kubectl}[Acessando clusters com o kubectl shell].
* *Conexão remota com o terminal:* Você também pode interagir com seus clusters instalando https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl] em sua área de trabalho local e, em seguida, copiando o arquivo kubeconfig do cluster para o seu diretório local `~/.kube/config`. Para mais informações, consulte {xref-access-cluster-kubectl}[Acessando clusters com o kubectl e um arquivo kubeconfig].

[#_rancher_cli]
== Rancher CLI

Você pode controlar seus clusters baixando a interface de linha de comando própria do Rancher, {xref-rancher-cli}[Rancher CLI]. Esta ferramenta CLI pode interagir diretamente com diferentes clusters e projetos ou passar comandos `kubectl` para eles.

[#_rancher_api]
== Rancher API

Finalmente, você pode interagir com seus clusters através da API do Rancher. Antes de usar a API, você deve obter uma {xref-user-api-keys}[chave da API]. Para visualizar os diferentes campos de recursos e ações para um objeto da API, abra a interface da API, que pode ser acessada clicando em *Ver na API* para qualquer objeto da interface do Rancher.
