= Adicionando Usuários a Clusters
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/access-clusters/add-users-to-clusters.adoc 
:product-path: cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/usuarios/authn-e-authz/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-configure-ad: xref:rancher-admin/users/authn-and-authz/configure-active-directory.adoc
:xref-locked-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
:xref-add-users-to-projects: xref:cluster-admin/project-admin/add-users-to-projects.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:como-fazer-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-authn-authz: xref:procedimentos/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/configuração-de-autenticação/index.adoc
:xref-custom-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-personalizadas.adoc
:xref-configure-ad: xref:procedimentos/guias-para-novos-usuários/autenticação-permissões-e-configuração-global/configuração-de-autenticação/configurar-active-directory.adoc
:xref-locked-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-bloqueadas.adoc
:xref-add-users-to-projects: xref:how-to-guides/new-user-guides/add-users-to-projects.adoc
endif::[]

Para fornecer a um usuário acesso para visualizar certos recursos em nível de cluster e criar novos projetos, atribua ao usuário uma **Associação ao Cluster**. Membros do cluster podem criar projetos e gerenciar recursos nesses projetos. No entanto, nem todos os recursos, namespaces e cargas de trabalho em um cluster são acessíveis pelos membros do cluster.

[TIP]
====
Deseja fornecer a um usuário acesso a um projeto _específico_ dentro de um cluster? Veja {xref-add-users-to-projects}[Adicionando Membros ao Projeto] em vez disso.
====

Existem dois contextos onde você pode adicionar membros ao cluster:

* Adicionando Membros a um Novo Cluster
+
Você pode adicionar membros a um cluster enquanto o cria (recomendado, se possível).

* <<_editing_cluster_membership,Adicionando Membros a um Cluster Existente>>
+
Você sempre pode adicionar membros a um cluster após o cluster ser provisionado.

[#_editing_cluster_membership]
== Editando a Associação do Cluster

Administradores de cluster podem editar a associação de um cluster, controlando quais usuários do Rancher podem acessar o cluster e quais recursos podem usar.

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster ao qual você deseja adicionar membros e clique em *⋮ > Editar Configuração*.
. Na aba *Funções de Membro*, clique em *Adicionar Membro*.
. Pesquise o usuário ou grupo que você deseja adicionar ao cluster.
+
[NOTE]
.Notes
====
* Pelo menos 2 caracteres devem ser digitados na caixa de pesquisa para que os resultados apareçam.
* Os usuários podem ser pesquisados com base em seu nome de usuário ou nome exibido.
* A pesquisa é baseada em prefixo (por exemplo, um usuário chamado `Stan Dard` aparecerá ao pesquisar por `Sta`, mas não ao pesquisar por `Dar`) e é sensível a maiúsculas e minúsculas.
====
+
Se a autenticação externa estiver configurada:


 ** O Rancher retorna usuários da sua fonte de {xref-authn-authz}[autenticação externa] à medida que você digita.
+

[NOTE]
.Usando AD, mas não consegue encontrar seus usuários?
====
Pode haver um problema com a configuração do seu atributo de pesquisa. Veja {xref-configure-ad}[Configurando a Autenticação do Active Directory: Etapa 5].
====


 ** Um menu suspenso permite que você adicione grupos em vez de usuários individuais. O menu suspenso lista apenas grupos dos quais você, o usuário logado, faz parte.
+

[NOTE]
====
Se você estiver logado como um usuário local, usuários externos não aparecem nos seus resultados de pesquisa. Para mais informações, veja {xref-authn-authz}#_configuração_de_autenticação_externa_e_usuários_principais[Configuração de Autenticação Externa e Usuários Principais].
====

. Atribua funções ao usuário ou grupo *Cluster*.
+
{xref-cluster-project-roles}[O que são Funções de Cluster?]
+

[TIP]
====
Para Funções Personalizadas, você pode modificar a lista de funções individuais disponíveis para atribuição.

* Para adicionar funções à lista, {xref-custom-roles}[Adicionar uma Função Personalizada].
* Para remover funções da lista, {xref-locked-roles}[Bloquear/Desbloquear Funções].
====

*Resultado:* Os usuários escolhidos são adicionados ao cluster.

* Para revogar a associação ao cluster, selecione o usuário e clique em *Excluir*. Esta ação exclui a associação, não o usuário.
* Para modificar as funções de um usuário no cluster, exclua-o do cluster e, em seguida, adicione-o novamente com as funções modificadas.
