= Acesse um Cluster com Kubectl e kubeconfig
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc 
:product-path: cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:description: Aprenda como acessar e gerenciar seus clusters Kubernetes usando o kubectl, seja através do kubectl Shell ou do kubectl CLI e do arquivo kubeconfig. Um arquivo kubeconfig é usado para configurar o acesso ao Kubernetes. Quando você cria um cluster com o Rancher, ele cria automaticamente um kubeconfig para o seu cluster.
ifeval::["{build-type}" != "community"]
:xref-kubeconfig-file: xref:cluster-admin/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-kubeconfig-file: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
endif::[]

Esta seção descreve como manipular seu cluster Kubernetes downstream com o kubectl a partir da interface do Rancher ou de sua estação de trabalho.

Para mais informações sobre como usar o kubectl, consulte https://kubernetes.io/docs/reference/kubectl/overview/[Documentação do Kubernetes: Visão Geral do kubectl].

[#_accessing_clusters_with_kubectl_shell_in_the_rancher_ui]
== Acessando Clusters com o kubectl Shell na interface do Rancher

Você pode acessar e gerenciar seus clusters fazendo login no Rancher e abrindo o kubectl Shell na interface. Nenhuma configuração adicional necessária.

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que você deseja acessar com kubectl e clique em *Explorar*.
. No menu de navegação superior, clique no botão *Kubectl Shell*. Use a janela que se abre para interagir com seu cluster Kubernetes.

[#_accessing_clusters_with_kubectl_from_your_workstation]
== Acessando clusters com kubectl a partir da sua estação de trabalho

Esta seção descreve como baixar o arquivo kubeconfig do seu cluster, iniciar o kubectl a partir da sua estação de trabalho e acessar seu cluster downstream.

Este método alternativo de acessar o cluster permite que você se autentique com o Rancher e gerencie seu cluster sem usar a interface do Rancher.

[NOTE]
.Pré-requisitos:
====

Estas instruções assumem que você já criou um cluster Kubernetes e que o kubectl está instalado em sua estação de trabalho. Para ajuda na instalação do kubectl, consulte a https://kubernetes.io/docs/tasks/tools/install-kubectl/[documentação oficial do Kubernetes.]
====


. Clique em *☰* no canto superior esquerdo.
. Selecione *Gerenciamento de Cluster*.
. Encontre o cluster cujo kubeconfig você deseja baixar e selecione *⁝* no final da linha.
. Selecione *Baixar KubeConfig* no submenu.
. Salve o arquivo YAML no seu computador local. Mova o arquivo para `~/.kube/config`. Nota: O local padrão que o kubectl usa para o arquivo kubeconfig é `~/.kube/config`, mas você pode usar qualquer diretório e especificá-lo usando a flag `--kubeconfig`, como neste comando:
+
----
  kubectl --kubeconfig /custom/path/kube.config get pods
----

. Da sua estação de trabalho, inicie o kubectl. Use-o para interagir com seu cluster Kubernetes.

[#_note_on_resources_created_using_kubectl]
== Nota sobre Recursos Criados Usando kubectl

O Rancher irá descobrir e mostrar recursos criados por `kubectl`. No entanto, esses recursos podem não ter todas as anotações necessárias na descoberta. Se uma operação (por exemplo, escalonamento da carga de trabalho) for realizada no recurso usando a interface/API do Rancher, isso pode acionar a recriação dos recursos devido às anotações ausentes. Isso deve acontecer apenas na primeira vez que uma operação for realizada no recurso descoberto.

[#_authenticating_directly_with_a_downstream_cluster]
== Autenticando Diretamente com um Cluster Downstream

Esta seção é destinada a ajudá-lo a configurar um método alternativo para acessar um {xref-launch-k8s-with-rancher}[cluster lançado pelo Rancher].

Este método está disponível apenas para clusters RKE2 e K3s que têm o {xref-arch-com-ds-cluster}#_4_authorized_cluster_endpoint[endpoint de cluster autorizado] habilitado. Quando o Rancher cria o cluster, ele gera um arquivo kubeconfig que inclui contextos adicionais do kubectl para acessar seu cluster. Este contexto adicional permite que você use o kubectl para se autenticar com o cluster downstream sem autenticar através do Rancher. Para uma explicação mais longa de como o endpoint de cluster autorizado funciona, consulte {xref-kubeconfig-file}[esta página].

Em clusters RKE2 e K3s, você precisa {xref-register-clusters}#_authorized_cluster_endpoint_support_for_rke2_and_k3s_clusters[habilitar manualmente] endpoints de cluster autorizados.

Recomendamos que, como uma boa prática, você configure este método para acessar seus clusters RKE2 e K3s, para que, caso não consiga se conectar ao Rancher, ainda possa acessar o cluster.

[NOTE]
.Pré-requisitos:
====

Os seguintes passos assumem que você criou um cluster Kubernetes e seguiu os passos para <<_accessing_clusters_with_kubectl_from_your_workstation,conectar ao seu cluster com kubectl a partir da sua estação de trabalho.>>
====


Para encontrar o nome do(s) contexto(s) no seu arquivo kubeconfig baixado, execute:

----
kubectl config get-contexts --kubeconfig /custom/path/kube.config
CURRENT   NAME                        CLUSTER                     AUTHINFO     NAMESPACE
*         my-cluster                  my-cluster                  user-46tmn
          my-cluster-controlplane-1   my-cluster-controlplane-1   user-46tmn
----

Neste exemplo, quando você usa `kubectl` com o primeiro contexto, `my-cluster`, você será autenticado através do servidor Rancher.

Com o segundo contexto, `my-cluster-controlplane-1`, você autenticará com o endpoint do cluster autorizado, comunicando-se diretamente com um cluster downstream RKE2/K3s.

Recomendamos o uso de um balanceador de carga com o endpoint de cluster autorizado. Para detalhes, consulte a seção de {xref-arch-rec}#_architecture_for_an_authorized_cluster_endpoint_ace[arquitetura recomendada.]

Agora que você tem o nome do contexto necessário para autenticar diretamente com o cluster, pode passar o nome do contexto como uma opção ao executar comandos kubectl. Os comandos diferirão dependendo se o seu cluster tem um FQDN definido. Exemplos são fornecidos nas seções abaixo.

Quando `kubectl` funciona normalmente, isso confirma que você pode acessar seu cluster ignorando o proxy de autenticação do Rancher.

[#_connecting_directly_to_clusters_with_fqdn_defined]
=== Conectando-se Diretamente a Clusters com FQDN Definido

Se um FQDN estiver definido para o cluster, um único contexto referenciando o FQDN será criado. O contexto será nomeado `<CLUSTER_NAME>-fqdn`. Quando você quiser usar `kubectl` para acessar este cluster sem o Rancher, precisará usar este contexto.

Assumindo que o arquivo kubeconfig está localizado em `~/.kube/config`:

----
kubectl --context <CLUSTER_NAME>-fqdn get nodes
----

Referenciando diretamente a localização do arquivo kubeconfig:

----
kubectl --kubeconfig /custom/path/kube.config --context <CLUSTER_NAME>-fqdn get pods
----

[#_connecting_directly_to_clusters_without_fqdn_defined]
=== Conectando-se Diretamente a Clusters sem FQDN Definido

Se não houver um FQDN definido para o cluster, contextos extras serão criados referenciando o endereço IP de cada nó no plano de controle. Cada contexto será nomeado `<CLUSTER_NAME>-<NODE_NAME>`. Quando você quiser usar `kubectl` para acessar este cluster sem o Rancher, precisará usar este contexto.

Assumindo que o arquivo kubeconfig está localizado em `~/.kube/config`:

----
kubectl --context <CLUSTER_NAME>-<NODE_NAME> get nodes
----

Referenciando diretamente a localização do arquivo kubeconfig:

----
kubectl --kubeconfig /custom/path/kube.config --context <CLUSTER_NAME>-<NODE_NAME> get pods
----
