= Autoscaler Horizontal de Pods
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/index.adoc 
:product-path: cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/horizontal-pod-autoscaler.adoc
:description: Saiba mais sobre o autoscaler horizontal de pods (HPA). Como gerenciar HPAs e como testá-los com uma implantação de serviço
:experimental:
ifeval::["{build-type}" != "community"]
:xref-hpas-with-kubectl: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
:xref-hpas-with-ui: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:xref-hpas-test: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/test-hpas-with-kubectl.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-hpas-with-kubectl: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
:xref-hpas-with-ui: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:xref-hpas-test: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/test-hpas-with-kubectl.adoc
endif::[]

O https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[Autoscaler Horizontal de Pods] (HPA) é um recurso do Kubernetes que permite configurar seu cluster para escalar automaticamente os serviços que está executando para cima ou para baixo.

O Rancher oferece alguns recursos adicionais para ajudar a gerenciar HPAs, dependendo da versão do Rancher.

Você pode criar, gerenciar e excluir HPAs usando a interface do usuário do Rancher. Ele suporta apenas HPA na `autoscaling/v2beta2` API.

[#_managing_hpas]
== Gerenciando HPAs

A forma como você gerencia HPAs é diferente com base na sua versão da API do Kubernetes:

* *Para a versão da API do Kubernetes autoscaling/V2beta1:* Esta versão da API do Kubernetes permite que você faça o autoscaling de seus pods com base na utilização de CPU e memória do seu aplicativo.
* *Para a versão da API do Kubernetes autoscaling/V2beta2:* Esta versão da API do Kubernetes permite que você faça o autoscaling de seus pods com base na utilização de CPU e memória, além de métricas personalizadas.

Você pode criar, gerenciar e excluir HPAs usando a interface do usuário do Rancher. A partir da interface do usuário do Rancher, você pode configurar o HPA para escalar com base na utilização de CPU e memória. Para mais informações, consulte {xref-hpas-with-ui}[Gerenciando HPAs com a interface do usuário do Rancher]. Para escalar o HPA com base em métricas personalizadas, você ainda precisa usar `kubectl`. Para mais informações, consulte {xref-hpas-with-kubectl}#_configurando_hpa_para_escalar_usando_métricas_personalizadas_com_prometheus[Configurando HPA para Escalar Usando Métricas Personalizadas com Prometheus].

Clusters criados no Rancher v2.0.7 e superiores têm automaticamente todos os requisitos necessários (metrics-server e configuração do cluster Kubernetes) para usar HPA.

[#_testing_hpas_with_a_service_deployment]
== Testando HPAs com uma implantação de serviço

Você pode ver o número atual de réplicas do seu HPA acessando seu projeto e clicando em menu:Recursos[HPA]. Para mais informações, consulte {xref-hpas-with-ui}[Obter Métricas e Status do HPA].

Você também pode usar `kubectl` para obter o status dos HPAs que você testa com sua ferramenta de teste de carga. Para mais informações, consulte {xref-hpas-test}[Testando HPAs com kubectl].
