= Gerenciando HPAs com a {rancher-product-name} interface
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-configuração/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc 
:product-path: cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-hpas-with-kubectl: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-hpas-with-kubectl: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
endif::[]

A interface do Rancher suporta a criação, gerenciamento e exclusão de HPAs. Você pode configurar o uso de CPU ou memória como a métrica que o HPA usa para escalar.

Se você quiser criar HPAs que escalem com base em outras métricas além de CPU e memória, consulte {xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[Configurando HPA para escalar usando métricas personalizadas com Prometheus].

[#_creating_an_hpa]
== Criando um HPA

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster onde você deseja criar um HPA e clique em *Explorar*.
. Na barra de navegação à esquerda, clique em menu:Descoberta de Serviços[HorizontalPodAutoscalers].
. Clique em *Criar*.
. Selecione um *Namespace* para o HPA.
. Insira um *Nome* para o HPA.
. Selecione uma *Referência de Destino* como alvo de escala para o HPA.
. Especifique as *réplicas mínimas* e *réplicas máximas* para o HPA.
. Configure as métricas para o HPA. Você pode escolher o uso de memória ou CPU como a métrica que fará o HPA aumentar ou diminuir o serviço. No campo *Quantidade*, insira a porcentagem do uso de memória ou CPU da carga de trabalho que fará o HPA escalar o serviço. Para configurar outras métricas do HPA, incluindo métricas disponíveis do Prometheus, você precisa {xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[gerenciar HPAs usando kubectl].
. Clique em *Criar* para criar o HPA.

[NOTE]
.Resultado:
====

O HPA é implantado no namespace escolhido. Você pode visualizar o status do HPA na visualização Recursos > HPA do projeto.
====


[#_get_hpa_metrics_and_status]
== Obter Métricas e Status do HPA

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que tem o HPA e clique em *Explorar*.
. Na barra de navegação à esquerda, clique em menu:Descoberta de Serviços[HorizontalPodAutoscalers]. A página *HorizontalPodAutoscalers* mostra o número de réplicas atuais.

Para métricas e status mais detalhados de um HPA específico, clique no nome do HPA. Isso leva à página de detalhes do HPA.

[#_deleting_an_hpa]
== Apagando um HPA

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que tem o HPA que você deseja apagar e clique em *Explorar*.
. Na barra de navegação à esquerda, clique em menu:Descoberta de Serviços[HorizontalPodAutoscalers].
. Clique em menu:Recursos[HPA].
. Encontre o HPA que você gostaria de apagar e clique em *⋮ > Apagar*.
. Clique em *Apagar* para confirmar.

[NOTE]
.Resultado:
====

O HPA é apagado do cluster atual.
====

