= Rollback de Cargas de Trabalho
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/roll-back-workloads.adoc 
:product-path: cluster-admin/kubernetes-resources/workloads-and-pods/roll-back-workloads.adoc

Às vezes, é necessário fazer rollback para a versão anterior do aplicativo, seja para fins de depuração ou porque o upgrade não ocorreu como planejado.

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster onde você deseja fazer upgrade de uma carga de trabalho e clique em *Explorar*.
. Na barra de navegação à esquerda, clique em *Carga de Trabalho*.
. Encontre a carga de trabalho que você deseja fazer rollback e selecione *⋮ > Rollback*.
. Escolha a revisão para a qual você deseja fazer rollback. Clique em *Rollback*.

*Resultado:* Sua carga de trabalho faz rollback para a versão anterior que você escolheu. Aguarde alguns minutos para que a ação seja concluída.
