= Workloads e Pods do Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc 
:product-path: cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:description: Saiba mais sobre os dois conceitos com os quais você pode construir qualquer aplicativo conteinerizado complexo no Kubernetes: Workloads e pods do Kubernetes
ifeval::["{build-type}" != "community"]
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
:xref-upgrade-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/roll-back-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
:xref-upgrade-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/roll-back-workloads.adoc
endif::[]

Você pode construir qualquer aplicativo conteinerizado complexo no Kubernetes usando dois conceitos básicos: pods e workloads. Depois de construir um aplicativo, você pode expô-lo para acesso, seja dentro do mesmo cluster ou na Internet, usando um terceiro conceito: serviços.

[#_pods]
== Pods

https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/[_Pods_] são um ou mais contêineres que compartilham namespaces de rede e volumes de armazenamento. A maioria dos pods tem apenas um contêiner. Portanto, quando discutimos _pods_, o termo é frequentemente sinônimo de _contêineres_. Você escala pods da mesma forma que escala contêineres-- tendo várias instâncias do mesmo pod que implementam um serviço. Normalmente, os pods são escalados e gerenciados pelo workload.

[#_workloads]
== Cargas de trabalho

_Workloads_ são objetos que definem regras de implantação para pods. Com base nessas regras, o Kubernetes realiza a implantação e atualiza o workload com o estado atual do aplicativo.
Os workloads permitem que você defina as regras para agendamento, escalonamento e fazer upgrade do aplicativo.

[#_workload_types]
=== Tipos de Workload

O Kubernetes divide os workloads em diferentes tipos. Os tipos mais populares suportados pelo Kubernetes são:

* https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Implantações]
+
_Implantações_ são mais adequadas para aplicativos sem estado (ou seja, quando você não precisa manter o estado do workload). Os pods gerenciados por workloads de implantação são tratados como independentes e descartáveis. Se um pod encontrar uma interrupção, o Kubernetes o remove e, em seguida, o recria. Um exemplo de aplicativo seria um servidor web Nginx.

* https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/[StatefulSets]
+
_StatefulSets_, em contraste com implantações, são mais adequados quando seu aplicativo precisa manter sua identidade e armazenar dados. Um aplicativo seria algo como Zookeeper-- um aplicativo que requer um banco de dados para armazenamento.

* https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSets]
+
_Daemonsets_ garante que cada nó no cluster execute uma cópia do pod. Para casos de uso onde você está coletando logs ou monitorando o desempenho do nó, esse workload semelhante a um daemon funciona melhor.

* https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/[Jobs]
+
_Jobs_ lançam um ou mais pods e garantem que um número especificado deles termine com sucesso. Os Jobs são mais adequados para executar uma tarefa finita até a conclusão, em vez de gerenciar um estado de aplicativo desejado em andamento.

* https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/[CronJobs]
+
_CronJobs_ são semelhantes aos jobs. CronJobs, no entanto, são executados até a conclusão de acordo com uma programação baseada em cron.

[#_services]
== Serviços

Em muitos casos de uso, um workload deve ser ou:

* Acessado por outros workloads no cluster.
* Exposto ao mundo exterior.

Você pode alcançar esses objetivos criando um _serviço_. Os serviços são mapeados para os pods do workload subjacente usando uma abordagem de https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#service-and-replicationcontroller[seletor/rótulo (veja os exemplos de código)]. A interface do Rancher simplifica esse processo de mapeamento criando automaticamente um serviço junto com o workload, usando a porta e o tipo de serviço que você selecionar.

[#_service_types]
=== Tipos de serviço

Existem vários tipos de serviços disponíveis no Rancher. As descrições abaixo são extraídas da https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types[Documentação do Kubernetes].

* *ClusterIP*
+
____
Expõe o serviço em um IP interno do cluster. Escolher este valor torna o serviço acessível apenas de dentro do cluster. Este é o padrão `ServiceType`.
____

* *NodePort*
+
____
Expõe o serviço no IP de cada nó em uma porta estática (a `NodePort`). Um serviço `ClusterIP`, para o qual o serviço `NodePort` irá rotear, é criado automaticamente. Você poderá contatar o serviço `NodePort`, de fora do cluster, solicitando `<NodeIP>:<NodePort>`.
____

* *LoadBalancer*
+
____
Expõe o serviço externamente usando o balanceador de carga de um provedor de nuvem. Os serviços `NodePort` e `ClusterIP`, para os quais o balanceador de carga externo irá rotear, são criados automaticamente.
____

[#_workload_options]
== Opções de Workload

Esta seção da documentação contém instruções para implantar workloads e usar opções de workload.

* {xref-deploy-workloads}[Implantar Workloads]
* {xref-upgrade-workloads}[Fazer upgrade de Workloads]
* {xref-roll-back-workloads}[Rollback de Workloads]

[#_related_links]
== Links relacionados

* https://kubernetes.io/docs/concepts/services-networking/service/[Serviços]
