= VMware vSphere Knoten-Vorlagen-Konfiguration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/vsphere.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/node-template-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
endif::[]

[#_account_access]
== Kontozugriff

[cols="<,^,<"]
|===
| Parameter | required | Beschreibung

| Cloud-Anmeldeinformationen
| *
| Ihre vSphere-Kontozugangsdaten, gespeichert in {xref-cloud-credentials}[Cloud-Anmeldeinformationen.]
|===

Ihre Cloud-Anmeldeinformationen enthalten folgende Felder:

|===
| Anmeldefelder | Beschreibung

| vCenter oder ESXi Server
| Geben Sie den vCenter- oder ESXi-Hostname/IP ein. ESXi ist die Virtualisierungsplattform, auf der Sie virtuelle Maschinen und virtuelle Appliances erstellen und ausführen. vCenter Server ist der Dienst, über den Sie mehrere Hosts in einem Netzwerk verwalten und deren Ressourcen bündeln.

| Port
| Konfigurieren Sie den Port des vCenter- oder ESXi-Servers.

| Benutzername und Passwort
| Geben Sie Ihren vSphere-Benutzernamen und Ihr Passwort ein.
|===

[#_scheduling]
== Planung

Wählen Sie aus, auf welchen Hypervisor die virtuelle Maschine geplant werden soll.

Die Felder im *Scheduling*-Abschnitt sollten automatisch mit dem Rechenzentrum und anderen verfügbaren Planungsoptionen in vSphere ausgefüllt werden.

|===
| Feld | required | Erklärung

| Rechenzentrum
| *
| Wählen Sie den Namen/Pfad des Rechenzentrums, in dem die VM geplant werden soll.

| Resource Pool
|
| Name des Resource Pools, in dem die VMs geplant werden sollen. Resource Pools können verwendet werden, um die verfügbaren CPU- und Speicherressourcen eines eigenständigen Hosts oder Clusters zu partitionieren, und sie können auch geschachtelt werden. Für einen eigenständigen ESXi leer lassen. Wenn nicht angegeben, wird der Standard Resource Pool verwendet.

| Datenspeicher
| *
| Wenn Sie einen Data Store Cluster haben, können Sie das Feld *Data Store* umschalten. Dies ermöglicht Ihnen die Auswahl eines Data Store Cluster, in dem Ihre VM geplant wird. Wenn das Feld nicht umgeschaltet ist, können Sie eine einzelne Disk auswählen.

| Ordner
|
| Name eines Ordners im Rechenzentrum, in dem die VMs erstellt werden sollen. Muss bereits existieren. Die VM-Ordner in diesem Dropdown-Menü entsprechen direkt Ihren VM-Ordnern in vSphere. Der Ordnername sollte in Ihrer vSphere-Konfigurationsdatei mit `vm/` vorangestellt werden.

| Host
|
| Die IP des Hostsystems, in dem die VMs eingeplant werden sollen. Lassen Sie dieses Feld leer für einen eigenständigen ESXi-Server oder für einen Cluster mit DRS (Distributed Resource Scheduler). Wenn angegeben, wird der Pool des Hostsystems verwendet und der *Resource Pool* Parameter wird ignoriert.

| Graceful Shutdown Timeout
|
| Die Anzahl der Sekunden, die Rancher wartet, bevor virtuelle Maschinen in einem Cluster gelöscht werden. Wenn auf `0` gesetzt, ist das Graceful Shutdown deaktiviert. Akzeptiert nur Ganzzahlwerte.
|===

[#_instance_options]
== Instanzoptionen

Im Abschnitt *Instance Options* konfigurieren Sie die Anzahl der vCPUs, den Arbeitsspeicher und die Festplattengröße für die von dieser Vorlage erstellten VMs.

[cols="<,^,<"]
|===
| Parameter | required | Beschreibung

| CPUs
| *
| Anzahl der vCPUs, die den VMs zugewiesen werden sollen.

| Arbeitsspeicher
| *
| Menge an Arbeitsspeicher, die den VMs zugewiesen werden soll.

| Festplatte
| *
| Größe der Disk (in MB), die an die VMs angehängt werden soll.

| Erstellungsmethode
| *
| Die Methode zur Einrichtung eines Betriebssystems auf dem Knoten. Das Betriebssystem kann von einer ISO oder von einer VM-Vorlage installiert werden. Je nach Erstellungsmethode müssen Sie auch eine VM-Vorlage, eine Inhaltsbibliothek, eine vorhandene VM oder eine ISO angeben. Für weitere Informationen zu den Erstellungsmethoden, lesen Sie <<_about_vm_creation_methods,Über VM-Erstellungsmethoden.>>

| Cloud Init
|
| URL einer `cloud-config.yml`-Datei oder URL zur Bereitstellung von VMs. Diese Datei ermöglicht eine weitere Anpassung des Betriebssystems, wie z. B. Netzwerkkonfiguration, DNS-Server oder System-Daemons. Das Betriebssystem muss `cloud-init` unterstützen.

| Netzwerke
|
| Name(n) des Netzwerks, an das die VM angeschlossen werden soll.

| Konfigurationsparameter, die für guestinfo verwendet werden.
|
| Zusätzliche Konfigurationsparameter für die VMs. Diese entsprechen den https://kb.vmware.com/s/article/1016098[Erweiterten Einstellungen] in der vSphere-Konsole. Beispielanwendungsfälle sind die Bereitstellung von RancherOS https://rancher.com/docs/os/v1.x/en/installation/cloud/vmware-esxi/#vmware-guestinfo[guestinfo]-Parametern oder die Aktivierung von Festplatten-UUIDs für die VMs (`disk.EnableUUID=TRUE`).
|===

[#_about_vm_creation_methods]
=== Über VM-Erstellungsmethoden

Im Feld *Erstellungsmethode* konfigurieren Sie die Methode, die zur Bereitstellung von VMs in vSphere verwendet wird. Verfügbare Optionen umfassen die Erstellung von VMs, die von einer RancherOS-ISO booten, oder die Erstellung von VMs durch Klonen einer vorhandenen virtuellen Maschine oder https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-F7BF0E6B-7C4F-4E46-8BBF-76229AEA7220.html[VM-Vorlage].

Die vorhandene VM oder Vorlage kann jedes moderne Linux-Betriebssystem verwenden, das mit Unterstützung für https://cloudinit.readthedocs.io/en/latest/[cloud-init] konfiguriert ist, unter Verwendung der https://canonical-cloud-init.readthedocs-hosted.com/en/latest/reference/datasources/nocloud.html[NoCloud-Datenquelle].

Wählen Sie die Art und Weise, wie die VM erstellt werden soll:

* *Bereitstellen aus Vorlage: Rechenzentrum:* Wählen Sie eine VM-Vorlage, die im Rechenzentrum vorhanden ist, das Sie ausgewählt haben.
* *Bereitstellen aus Vorlage: Inhaltsbibliothek:* Zuerst wählen Sie die https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-254B2CE8-20A8-43F0-90E8-3F6776C2C896.html[Inhaltsbibliothek] aus, die Ihre Vorlage enthält, und wählen Sie dann die Vorlage aus der ausgefüllten Liste *Bibliotheksvorlagen* aus.
* *Klonen Sie eine vorhandene virtuelle Maschine:* Wählen Sie im Feld *Virtuelle Maschine* eine vorhandene VM aus, von der die neue VM geklont werden soll.
* *Installation von boot2docker ISO:* Stellen Sie sicher, dass das Feld *OS ISO-URL* die URL einer VMware ISO-Version für RancherOS (`rancheros-vmware.iso`) enthält. Beachten Sie, dass diese URL von den Knoten, die Ihre Rancher-Serverinstallation ausführen, erreichbar sein muss.

[#_networks]
== Netzwerke

Die Knotenvorlage ermöglicht es jetzt, eine VM mit mehreren Netzwerken bereitzustellen. Im Feld *Netzwerke* können Sie jetzt auf *Netzwerk hinzufügen* klicken, um alle Netzwerke hinzuzufügen, die Ihnen in vSphere zur Verfügung stehen.

[#_node_tags_and_custom_attributes]
== Knoten-Tags und benutzerdefinierte Attribute

Tags ermöglichen es Ihnen, Metadaten an Objekte im vSphere-Inventar anzuhängen, um das Sortieren und Suchen dieser Objekte zu erleichtern.

Für Tags werden alle Ihre vSphere-Tags als Auswahlmöglichkeiten in Ihrer Knotenvorlage angezeigt.

In den benutzerdefinierten Attributen lässt Rancher Sie alle benutzerdefinierten Attribute auswählen, die Sie bereits in vSphere eingerichtet haben. Die benutzerdefinierten Attribute sind Schlüssel, und Sie können für jedes einen Wert eingeben.

[NOTE]
====

Benutzerdefinierte Attribute sind ein veraltetes Feature, das schließlich aus vSphere entfernt wird.
====


[#_cloud_init]
== cloud-init

https://cloudinit.readthedocs.io/en/latest/[Cloud-init] ermöglicht es Ihnen, Ihre Knoten zu initialisieren, indem Sie beim ersten Bootvorgang Konfiguration anwenden. Dies kann Dinge wie das Erstellen von Benutzern, das Autorisieren von SSH-Schlüsseln oder das Einrichten des Netzwerks umfassen.

Um die cloud-init-Initialisierung zu nutzen, erstellen Sie eine Cloud-Config-Datei mit gültiger YAML-Syntax und fügen Sie den Inhalt der Datei in das Feld *Cloud Init* ein. Verweisen Sie auf die https://cloudinit.readthedocs.io/en/latest/topics/examples.html[cloud-init-Dokumentation.] für eine kommentierte Sammlung von Beispielen unterstützter Cloud-Config-Direktiven.

Beachten Sie, dass cloud-init nicht unterstützt wird, wenn die ISO-Erstellungsmethode verwendet wird.

[#_engine_options]
== Engine-Optionen

Im Abschnitt *Engine-Optionen* der Knotenvorlage können Sie den Container-Daemon konfigurieren. Sie möchten möglicherweise die Container-Version oder einen Container-Image-Registry-Mirror angeben.

[NOTE]
====
Wenn Sie Red Hat Enterprise Linux (RHEL) oder CentOS-Knoten bereitstellen, lassen Sie das Feld *Docker Install URL* auf dem Standardwert oder wählen Sie *keine* aus. Dies umgeht eine Überprüfung der Docker-Installation, da Docker bereits auf diesen Knotentypen installiert ist.

Wenn Sie *Docker Install URL* auf einen anderen Wert als den Standard oder *keine* setzen, könnte eine Fehlermeldung wie die folgende angezeigt werden: `Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`
====

