= Sanftes Herunterfahren für VMware vSphere-VMs (virtuelle Maschinen)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/starten-von-kubernetes-mit-rancher/neue-knoten-in-einem-infrastrukturanbieter/vsphere/shutdown-vm.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/shutdown-vm.adoc
:experimental:

In Rancher v2.8.3 und später können Sie das sanfte Herunterfahren von virtuellen Maschinen (VMs) für VMware vSphere-Knotentreiber-Cluster konfigurieren. Das sanfte Herunterfahren führt eine Verzögerung ein, bevor die VM zwangsweise gelöscht wird, was Zeit für das Beenden von laufenden Prozessen und offenen Verbindungen ermöglicht.

In RKE2/K3s können Sie das sanfte Herunterfahren einrichten, wenn Sie den Cluster erstellen, oder die Konfiguration des Clusters bearbeiten, um es anschließend hinzuzufügen.

[NOTE]
====
Da Rancher die Plattform eines importierten Clusters nicht erkennen kann, können Sie das sanfte Herunterfahren für VMware vSphere-Cluster, die Sie importiert haben, nicht aktivieren.
====


[#_enable_graceful_shutdown_during_vmware_vsphere_cluster_creation]
== Aktivieren Sie das sanfte Herunterfahren während der Erstellung von VMware vSphere-Clustern

In RKE2/K3s können Sie neue VMware vSphere-Cluster mit dem sanften Herunterfahren für VMs konfigurieren:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Klicken Sie *Erstellen* und wählen Sie *VMware vSphere* aus, um einen neuen Cluster bereitzustellen.
. Unter menu:Maschinenpools[Planung] geben Sie im Feld *Timeout für sanftes Herunterfahren* einen ganzzahligen Wert größer als 0 ein. Der Wert, den Sie eingeben, ist die Zeit in Sekunden, die Rancher wartet, bevor VMs im Cluster gelöscht werden. Wenn der Wert auf `0` gesetzt ist, ist das sanfte Herunterfahren deaktiviert.

[#_enable_graceful_shutdown_in_existing_rke2_product_name_k3s_product_name_clusters]
== Aktivieren Sie das sanfte Herunterfahren in bestehenden {rke2-product-name}/{k3s-product-name} Clustern

In RKE2/K3s können Sie die Konfiguration eines bestehenden VMware vSphere-Clusters bearbeiten, um das sanfte Herunterfahren zu aktivieren, was eine Verzögerung vor dem Löschen von VMs hinzufügt.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Auf der Seite *Cluster* finden Sie den gehosteten VMware vSphere-Cluster, den Sie bearbeiten möchten. Klicken Sie *⋮* am Ende der Zeile, die mit dem Cluster verbunden ist. Wählen Sie *Konfiguration bearbeiten*.
. Unter menu:Maschinenpools[Planung] geben Sie im Feld *Timeout für sanftes Herunterfahren* einen ganzzahligen Wert größer als 0 ein. Der Wert, den Sie eingeben, ist die Zeit in Sekunden, die Rancher wartet, bevor VMs im Cluster gelöscht werden. Wenn der Wert auf `0` gesetzt ist, ist das sanfte Herunterfahren deaktiviert.
