= Erstellen eines VMware vSphere-Clusters
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/starten-von-kubernetes-mit-rancher/neue-knoten-in-einem-infrastrukturprovider/vsphere/index.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/vsphere.adoc
:description: Verwenden Sie Rancher, um einen VMware vSphere-Cluster zu erstellen. Er kann aus Gruppen von VMs mit unterschiedlichen Eigenschaften bestehen, die eine feingranulare Kontrolle über die Größe der Knoten ermöglichen.
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-cloud-provider-vsphere-out-of-tree: xref:cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-vsphere-storage-example: xref:cluster-admin/manage-clusters/persistent-storage/examples/vsphere-storage.adoc
:xref-provision-cluster-in-vsphere: xref:cluster-deployment/infra-providers/vsphere/provision-kubernetes-clusters-in-vsphere.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-cloud-provider-vsphere-out-of-tree: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/cloud-anbieter-setup/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/cloud-anbieter-setup/configure-in-tree-vsphere.adoc
:xref-vsphere-storage-example: xref:how-to-guides/Anleitung/manage-clusters/provisioning-storage-beispiele/vsphere-speicher.adoc
:xref-provision-cluster-in-vsphere: xref:how-to-guides/neue-benutzeranleitungen/starten-von-kubernetes-mit-rancher/neue-knoten-in-einem-infrastrukturprovider/vsphere/provision-kubernetes-clusters-in-vsphere.adoc
endif::[]

import YouTube from '@site/src/components/YouTube'

Durch die Verwendung von Rancher mit VMware vSphere können Sie Cloud-Operationen lokal durchführen.

Rancher kann Knoten in vSphere bereitstellen und Kubernetes auf ihnen installieren. Beim Erstellen eines Kubernetes-Clusters in vSphere stellt Rancher zunächst die angegebene Anzahl von virtuellen Maschinen bereit, indem es mit der vCenter-API kommuniziert. Dann installiert es Kubernetes darauf.

Ein vSphere-Cluster kann aus mehreren Gruppen von VMs mit unterschiedlichen Eigenschaften bestehen, wie z.B. der Menge an Arbeitsspeicher oder der Anzahl der vCPUs. Diese Gruppierung ermöglicht eine feingranulare Kontrolle über die Größe der Knoten für jede Kubernetes-Rolle.

[#_creating_a_vmware_vsphere_cluster]
== Erstellen eines VMware vSphere-Clusters

In {xref-provision-cluster-in-vsphere}[diesem Abschnitt] lernen Sie, wie Sie Rancher verwenden, um ein {url-rke2-landing-page}[RKE2] oder {url-k3s-landing-page}[K3s] Kubernetes-Cluster in vSphere zu installieren.

[#_provisioning_storage]
== Speicher bereitstellen

Als Beispiel dafür, wie man Speicher in vSphere mit Rancher bereitstellt, siehe {xref-vsphere-storage-example}[diesen Abschnitt]. Um Speicher in vSphere dynamisch bereitzustellen, muss der vSphere-Anbieter aktiviert sein. Siehe {xref-cloud-provider-vsphere}[in-tree vSphere-Konfiguration] und {xref-cloud-provider-vsphere-out-of-tree}[out-of-tree vSphere-Konfiguration].

[#_enabling_the_vmware_vsphere_cloud_provider]
== Aktivierung des VMware vSphere-Cloud-Anbieters

Wenn ein Cloud-Anbieter in Rancher eingerichtet ist, kann der Rancher-Server automatisch neue Infrastruktur für den Cluster bereitstellen, einschließlich neuer Knoten oder persistenter Speichergeräte.

Für Details zur Aktivierung des vSphere-Cloud-Anbieters siehe {xref-cloud-provider-vsphere}[in-tree vSphere-Konfiguration] und {xref-cloud-provider-vsphere-out-of-tree}[out-of-tree vSphere-Konfiguration].
