= Arrêt en douceur pour les machines virtuelles VMware vSphere
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: procédure-guides/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/vsphere/arrêter-vm.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/shutdown-vm.adoc
:experimental:

Dans Rancher v2.8.3 et versions ultérieures, vous pouvez configurer l'arrêt en douceur des machines virtuelles (VM) pour les clusters de pilotes de nœuds VMware vSphere. L'arrêt en douceur introduit un délai avant que la VM ne soit supprimée de force, ce qui permet de terminer les processus en cours et les connexions ouvertes.

Dans RKE2/K3s, vous pouvez configurer l'arrêt en douceur lors de la création du cluster, ou modifier la configuration du cluster pour l'ajouter par la suite.

[NOTE]
====
Étant donné que Rancher ne peut pas détecter la plateforme d'un cluster importé, vous ne pouvez pas activer l'arrêt en douceur sur les clusters VMware vSphere que vous avez importés.
====


[#_enable_graceful_shutdown_during_vmware_vsphere_cluster_creation]
== Activer l'arrêt en douceur lors de la création d'un cluster VMware vSphere

Dans RKE2/K3s, vous pouvez configurer de nouveaux clusters VMware vSphere avec un arrêt en douceur pour les VM{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Cliquez *Créer* et sélectionnez *VMware vSphere* pour provisionner un nouveau cluster.
. Sous menu:Pools de machines[Planification], dans le champ *Délai d'arrêt en douceur*, saisissez une valeur entière supérieure à 0. La valeur que vous saisissez est le temps en secondes que Rancher attend avant de supprimer les VM sur le cluster. Si la valeur est définie sur `0`, l'arrêt en douceur est désactivé.

[#_enable_graceful_shutdown_in_existing_rke2_product_name_k3s_product_name_clusters]
== Activer l'arrêt en douceur dans les clusters existants {rke2-product-name}/{k3s-product-name}

Dans RKE2/K3s, vous pouvez modifier la configuration d'un cluster VMware vSphere existant pour activer l'arrêt en douceur, ce qui ajoute un délai avant de supprimer les VM.

. Cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, trouvez le cluster hébergé par VMware vSphere que vous souhaitez modifier. Cliquez *⋮* à la fin de la ligne associée au cluster. Sélectionnez *Modifier la configuration*.
. Sous menu:Pools de machines[Planification], dans le champ *Délai d'arrêt en douceur*, saisissez une valeur entière supérieure à 0. La valeur que vous saisissez est le temps en secondes que Rancher attend avant de supprimer les VM sur le cluster. Si la valeur est définie sur `0`, l'arrêt en douceur est désactivé.
