= Créer un cluster VMware vSphere
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: how-to-guides/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/vsphere/index.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/vsphere.adoc
:description: Utilisez Rancher pour créer un cluster VMware vSphere. Il peut se composer de groupes de machines virtuelles avec des propriétés distinctes qui permettent un contrôle précis sur la taille des nœuds.
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-cloud-provider-vsphere-out-of-tree: xref:cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-vsphere-storage-example: xref:cluster-admin/manage-clusters/persistent-storage/examples/vsphere-storage.adoc
:xref-provision-cluster-in-vsphere: xref:cluster-deployment/infra-providers/vsphere/provision-kubernetes-clusters-in-vsphere.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-cloud-provider-vsphere-out-of-tree: xref:procédures/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-mise-en-place/mise-en-place-fournisseurs-de-cloud/configurer-vsphere-hors-arbre.adoc
:xref-cloud-provider-vsphere: xref:procédures/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-mise-en-place/mise-en-place-fournisseurs-de-cloud/configurer-vsphere-intégrée.adoc
:xref-vsphere-storage-example: xref:how-to-guides/nouveaux-guides-utilisateurs/gerer-des-clusters/exemples-de-provisionnement-de-stockage/vsphere-storage.adoc
:xref-provision-cluster-in-vsphere: xref:how-to-guides/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/vsphere/provision-kubernetes-clusters-in-vsphere.adoc
endif::[]

importer YouTube depuis '@site/src/components/YouTube'

En utilisant Rancher avec VMware vSphere, vous pouvez apporter des opérations cloud sur site.

Rancher peut provisionner des nœuds dans vSphere et y installer Kubernetes. Lors de la création d'un cluster Kubernetes dans vSphere, Rancher provisionne d'abord le nombre spécifié de machines virtuelles en communiquant avec l'API vCenter. Ensuite, il installe Kubernetes sur celles-ci.

Un cluster vSphere peut se composer de plusieurs groupes de machines virtuelles avec des propriétés distinctes, telles que la quantité de mémoire ou le nombre de vCPUs. Ce regroupement permet un contrôle précis sur la taille des nœuds pour chaque rôle Kubernetes.

[#_creating_a_vmware_vsphere_cluster]
== Créer un cluster VMware vSphere

Dans {xref-provision-cluster-in-vsphere}[cette section,] vous apprendrez à utiliser Rancher pour installer un cluster Kubernetes {url-rke2-landing-page}[RKE2] ou {url-k3s-landing-page}[K3s] dans vSphere.

[#_provisioning_storage]
== Provisionnement de stockage

Pour un exemple de la façon de provisionner du stockage dans vSphere en utilisant Rancher, référez-vous à {xref-vsphere-storage-example}[cette section.] Pour provisionner dynamiquement du stockage dans vSphere, le fournisseur vSphere doit être activé. Référez-vous à {xref-cloud-provider-vsphere}[la configuration vSphere intégrée] et {xref-cloud-provider-vsphere-out-of-tree}[la configuration vSphere externe].

[#_enabling_the_vmware_vsphere_cloud_provider]
== Activation du fournisseur de cloud VMware vSphere

Lorsqu'un fournisseur de cloud est configuré dans Rancher, le serveur Rancher peut automatiquement provisionner une nouvelle infrastructure pour le cluster, y compris de nouveaux nœuds ou des dispositifs de stockage persistants.

Pour des détails sur l'activation du fournisseur de cloud vSphere, référez-vous à {xref-cloud-provider-vsphere}[configuration vSphere intégrée] et {xref-cloud-provider-vsphere-out-of-tree}[configuration vSphere externe].
