= Pilotes de cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/nouveaux-guides-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-pilotes-de-provisionnement/gérer-pilotes-de-cluster.adoc 
:product-path: rancher-admin/global-configuration/provisioning-drivers/manage-cluster-drivers.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc 
:xref-hosted-k8s-clusters: xref:guides-pratiques/nouveaux-guides-utilisateurs/clusters-kubernetes-dans-rancher-configuration/configurer-des-clusters-à-partir-de-fournisseurs-kubernetes-hébergés/index.adoc
endif::[]

Les pilotes de cluster sont utilisés pour créer des clusters dans un {xref-hosted-k8s-clusters}[fournisseur Kubernetes hébergé], tel que Google GKE. La disponibilité du pilote de cluster à afficher lors de la création de clusters est définie par l'état du pilote de cluster. Seuls `active` pilotes de cluster seront affichés comme option pour la création de clusters. Par défaut, Rancher est livré avec plusieurs pilotes de cluster de fournisseurs de cloud existants, mais vous pouvez également ajouter des pilotes de cluster personnalisés à Rancher.

S'il y a des pilotes de cluster spécifiques que vous ne souhaitez pas afficher à vos utilisateurs, vous pouvez désactiver ces pilotes de cluster dans Rancher et ils n'apparaîtront pas comme option pour la création de clusters.

[#_managing_cluster_drivers]
== Gestion des pilotes de cluster

[NOTE]
.Conditions préalables :
====

Pour créer, modifier ou supprimer des pilotes de cluster, vous avez besoin de _l'une_ des autorisations suivantes :

* {xref-global-permissions}[Autorisations globales d'administrateur]
* {xref-global-permissions}#_permissions_globales_personnalisees[Permissions globales personnalisées] avec le rôle {xref-global-permissions}[Gérer les pilotes de cluster] attribué.
====


[#_activating_deactivating_cluster_drivers]
== Activation/Désactivation des pilotes de cluster

Par défaut, Rancher active uniquement les pilotes pour les fournisseurs de cloud les plus populaires, Google GKE, Amazon EKS et Azure AKS. Si vous souhaitez afficher ou masquer un pilote de nœud, vous pouvez changer son statut.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Dans le menu de navigation de gauche, cliquez sur *Pilotes*.
. Dans l'onglet *Pilotes de cluster*, sélectionnez le pilote que vous souhaitez activer ou désactiver et cliquez sur *⋮ > Activer* ou *⋮ > Désactiver*.

[#_adding_custom_cluster_drivers]
== Ajout de pilotes de cluster personnalisés

Si vous souhaitez utiliser un pilote de cluster que Rancher ne prend pas en charge par défaut, vous pouvez ajouter le pilote du fournisseur afin de commencer à les utiliser pour créer des clusters Kubernetes _hébergés_.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Dans le menu de navigation de gauche, cliquez sur *Pilotes*.
. Dans l'onglet *Pilotes de cluster*, cliquez sur *Ajouter un pilote de cluster*.
. Complétez le formulaire *Ajouter un pilote de cluster*. Puis cliquez sur *Créer*.

[#_developing_your_own_cluster_driver]
== Développer votre propre pilote de cluster

Pour développer un pilote de cluster à ajouter à Rancher, veuillez vous référer à notre https://github.com/rancher-plugins/kontainer-engine-driver-example[exemple].
