= Pilotes de nœud
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.adoc 
:product-path: rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions.adoc 
endif::[]

Un pilote de nœud est le même qu'un https://github.com/docker/docs/blob/vnext-engine/machine/drivers/index.md[pilote Docker Machine]. Les pilotes de nœud sont utilisés pour provisionner des hôtes, que Rancher utilise pour lancer et gérer des clusters Kubernetes. Par défaut, Rancher est livré avec de nombreux pilotes de nœud, mais vous pouvez également créer et ajouter des pilotes de nœud personnalisés à Rancher.

Seuls `Active` pilotes de nœud sont affichés dans l'interface utilisateur de Rancher lorsque vous créez des modèles de nœud. S'il y a des pilotes de nœud spécifiques que vous ne souhaitez pas montrer à vos utilisateurs, vous devez désactiver ces pilotes de nœud.

[#_managing_node_drivers]
== Gestion des pilotes de nœud

[NOTE]
.Conditions préalables :
====

Pour créer, modifier ou supprimer des pilotes, vous avez besoin de _l'une_ des autorisations suivantes{nbsp}:

* {xref-global-permissions}[Autorisations globales d'administrateur]
* {xref-global-permissions}#_custom_global_permissions[Autorisations globales personnalisées] avec le rôle {xref-global-permissions}[Gérer les pilotes de nœud] attribué.
====


[#_activating_deactivating_node_drivers]
=== Activation/Désactivation des pilotes de nœud

Par défaut, Rancher n'active que les pilotes pour les fournisseurs de cloud les plus populaires, tels qu'Amazon EC2, Azure, DigitalOcean, Linode et vSphere. Si vous souhaitez afficher ou masquer un pilote de nœud, vous pouvez changer son statut.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Dans le menu de navigation à gauche, cliquez sur *Pilotes*.
. Dans l'onglet *Pilotes de nœud*, sélectionnez le pilote que vous souhaitez activer ou désactiver et cliquez sur *⋮ > Activer* ou *⋮ > Désactiver*.

[WARNING]
====

Vous pouvez perdre l'accès aux clusters après avoir désactivé un pilote de nœud.

Désactiver un pilote de nœud n'affecte pas seulement sa visibilité dans l'interface utilisateur de Rancher. Lorsque vous désactivez ou supprimez un pilote de nœud, tous les nœuds déployés avec ce pilote deviennent inaccessibles.

Par exemple, si vous désactivez un pilote de nœud vSphere pour le cacher dans l'interface utilisateur, et que vous avez un cluster vSphere qui a été déployé avec ce pilote, le nœud initial du cluster échouera, et l'ensemble du cluster deviendra inaccessible. Les tentatives de suppression des nœuds vSphere échoueront, avec des nœuds bloqués dans un état prolongé `Removing`.

Avant de désactiver un pilote de nœud, assurez-vous qu'il n'a pas de clusters associés. Une façon de vérifier est de voir si la plateforme respective d'un pilote est répertoriée parmi vos clusters :

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sélectionnez *Clusters*.
. Vérifiez la colonne *Fournisseur* du tableau pour les instances du pilote de nœud que vous désactivez.
====


[#_adding_custom_node_drivers]
=== Ajouter des pilotes de nœud personnalisés

Si vous souhaitez utiliser un pilote de nœud que Rancher ne prend pas en charge par défaut, vous pouvez ajouter le pilote de ce fournisseur afin de commencer à les utiliser pour créer des modèles de nœuds et éventuellement des pools de nœuds pour votre cluster Kubernetes.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Dans le menu de navigation à gauche, cliquez sur *Pilotes*.
. Dans l'onglet *Pilotes de nœud*, cliquez sur *Ajouter un pilote de nœud*.
. Complétez le formulaire *Ajouter un pilote de nœud*. Puis cliquez sur *Créer*.

[#_developing_your_own_node_drivers]
=== Développer vos propres pilotes de nœud

Les pilotes de nœud sont implémentés avec https://github.com/rancher/machine[Rancher Machine], un fork de https://github.com/docker/machine[Docker Machine]. Docker Machine n'est plus en développement actif.

Référez-vous à la documentation originale https://github.com/docker/docs/blob/vnext-engine/machine/overview.md[Docker Machine documentation] pour des détails sur la façon de développer vos propres pilotes de nœud.
