= À propos des pilotes de provisionnement
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: guides-procédures/nouveaux-guides-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-pilotes-de-provisionnement/index.adoc 
:product-path: rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc
ifeval::["{build-type}" != "community"]
:xref-harvester-overview: xref:integrations/harvester/overview.adoc
:xref-infra-providers: xref:cluster-deployment/fournisseurs-infra/fournisseurs-infra.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-infra-aws: xref:déploiement-cluster/fournisseurs-infra/aws/aws.adoc
:xref-deploy-gke: xref:cluster-deployment/hosted-kubernetes/gke/gke.adoc
:xref-deploy-eks: xref:cluster-deployment/hosted-kubernetes/eks/eks.adoc
:xref-deploy-aks: xref:cluster-deployment/hosted-kubernetes/aks/aks.adoc
:xref-infra-gce: xref:cluster-deployment/infra-providers/gce/gce.adoc
:xref-infra-azure: xref:cluster-deployment/infra-providers/azure/azure.adoc
:xref-infra-digitalocean: xref:cluster-deployment/infra-providers/digitalocean/digitalocean.adoc
:xref-infra-vsphere: xref:cluster-deployment/infra-providers/vsphere/vsphere.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-harvester-overview: xref:integrations-in-rancher/harvester/overview.adoc
:xref-infra-providers: xref:guides-procédures/guides-nouveaux-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/index.adoc
:xref-hosted-k8s-clusters: xref:guides-pratiques/nouveaux-guides-utilisateurs/clusters-kubernetes-dans-rancher-configuration/configurer-des-clusters-à-partir-de-fournisseurs-kubernetes-hébergés/index.adoc
:xref-infra-aws: xref:guides-procédures/guides-nouveaux-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/créer-un-cluster-amazon-ec2.adoc
:xref-deploy-gke: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/gke.adoc
:xref-deploy-eks: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks.adoc
:xref-deploy-aks: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.adoc
:xref-infra-gce: xref:guides-procédures/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/créer-un-cluster-google-compute-engine.adoc
:xref-infra-azure: xref:guides-procédures/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/créer-un-cluster-azure.adoc
:xref-infra-digitalocean: xref:guides-procédures/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/créer-un-cluster-digitalocean.adoc
:xref-infra-vsphere: xref:guides-procédures/nouveaux-guides-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/vsphere/index.adoc
endif::[]

Les pilotes dans Rancher vous permettent de gérer quels fournisseurs peuvent être utilisés pour déployer {xref-hosted-k8s-clusters}[clusters Kubernetes hébergés] ou {xref-infra-providers}[nœuds dans un fournisseur d'infrastructure] afin de permettre à Rancher de déployer et de gérer Kubernetes.

[#_rancher_drivers]
== Pilotes Rancher

Avec les pilotes Rancher, vous pouvez activer/désactiver les pilotes intégrés existants qui sont inclus dans Rancher. Alternativement, vous pouvez ajouter votre propre pilote si Rancher ne l'a pas encore implémenté.

Il existe deux types de pilotes dans Rancher{nbsp}:

* <<_cluster_drivers,Pilotes de cluster>>
* <<_node_drivers,Pilotes de nœud>>

[#_cluster_drivers]
== Pilotes de cluster

Les pilotes de cluster sont utilisés pour provisionner {xref-hosted-k8s-clusters}[clusters Kubernetes hébergés], tels que GKE, EKS, AKS, etc.. La disponibilité du pilote de cluster à afficher lors de la création d'un cluster est définie en fonction de l'état du pilote de cluster. Seuls `active` pilotes de cluster seront affichés comme option pour créer des clusters Kubernetes hébergés. Par défaut, Rancher est livré avec plusieurs pilotes de cluster existants, mais vous pouvez également créer des pilotes de cluster personnalisés à ajouter à Rancher.

Par défaut, Rancher a activé plusieurs fournisseurs de cloud Kubernetes hébergés, y compris{nbsp}:

* {xref-deploy-eks}[Amazon EKS]
* {xref-deploy-gke}[Google GKE]
* {xref-deploy-aks}[Azure AKS]

[#_node_drivers]
== Pilotes de nœud

Les pilotes de nœud sont utilisés pour provisionner des hôtes, que Rancher utilise pour lancer et gérer des clusters Kubernetes. Un pilote de nœud est le même qu'un https://github.com/docker/docs/blob/vnext-engine/machine/drivers/index.md[pilote Docker Machine]. La disponibilité du pilote de nœud à afficher lors de la création de modèles de nœud est définie en fonction de l'état du pilote de nœud. Seuls `active` pilotes de nœud seront affichés comme option pour créer des modèles de nœud. Par défaut, Rancher est livré avec de nombreux pilotes Docker Machine existants, mais vous pouvez également créer des pilotes de nœud personnalisés à ajouter à Rancher.

S'il y a des pilotes de nœud spécifiques que vous ne souhaitez pas montrer à vos utilisateurs, vous devez désactiver ces pilotes de nœud.

Rancher prend en charge plusieurs grands fournisseurs de cloud, mais par défaut, ces pilotes de nœud sont actifs et disponibles pour le déploiement{nbsp}:

* {xref-infra-aws}[Amazon EC2]
* {xref-infra-azure}[Azure]
* {xref-infra-digitalocean}[Digital Ocean]
* {xref-infra-vsphere}[vSphere]

Il existe plusieurs autres pilotes de nœud qui sont désactivés par défaut, mais qui sont inclus dans Rancher{nbsp}:

* {xref-harvester-overview}#_harvester_node_driver/[{harvester-product-name}], disponible depuis Rancher v2.6.1
* {xref-infra-gce}[Google GCE], disponible depuis Rancher v2.12.0
