= Monitoring Configuration Examples
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/examples 
:product-path: observability/monitoring-and-dashboards/configuration/examples

== ServiceMonitor

See the official prometheus-operator GitHub repo for an example https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml[ServiceMonitor] YAML.

== PodMonitor

See the https://prometheus-operator.dev/docs/developer/getting-started/#using-podmonitors[Prometheus Operator documentation] for an example PodMonitor and an example Prometheus resource that refers to a PodMonitor.

== PrometheusRule

A PrometheusRule contains the alerting and recording rules that you would usually place in a https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/[Prometheus rule file].

For a more fine-grained approach, the `ruleSelector` field on a Prometheus resource can select which PrometheusRules should be loaded onto Prometheus, based on the labels attached to the PrometheusRules resources.

See the https://prometheus-operator.dev/docs/developer/alerting/[Prometheus Operator documentation] for an example PrometheusRule.

== Alertmanager Config

See the Rancher docs page on Receivers for an example xref:./receivers.adoc#_example_alertmanager_configs[Alertmanager config].
