= Retour à l'état initial des charges de travail
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/roll-back-workloads.adoc 
:product-path: cluster-admin/kubernetes-resources/workloads-and-pods/roll-back-workloads.adoc

Il peut parfois être nécessaire d'effectuer un retour à l'état initial de l'application, soit pour des raisons de débogage, soit parce que la mise à niveau ne s'est pas déroulée comme prévu.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster où vous souhaitez mettre à niveau une charge de travail et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur *Charge de travail*.
. Trouvez la charge de travail pour laquelle vous souhaitez effectuer un retour à l'état initial et sélectionnez *⋮ > Retour à l'état initial*.
. Choisissez la révision vers laquelle vous souhaitez effectuer un retour à l'état initial. Cliquez sur *Retour à l'état initial*.

*Résultat :* Votre charge de travail revient à l'état initial correspondant à la révision que vous avez choisie. Attendez quelques minutes que l'action soit terminée.
