= Charges de travail Kubernetes et pods
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc 
:product-path: cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:description: Découvrez les deux concepts qui vous permettent de créer n'importe quelle application conteneurisée complexe avec Kubernetes{nbsp}: Charges de travail Kubernetes et pods
ifeval::["{build-type}" != "community"]
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
:xref-upgrade-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/roll-back-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
:xref-upgrade-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/roll-back-workloads.adoc
endif::[]

Vous pouvez créer n'importe quelle application conteneurisée complexe dans Kubernetes en utilisant deux éléments de base{nbsp}: les pods et les charges de travail. Une fois que vous avez créé une application, vous pouvez l'exposer pour y accéder, que ce soit au sein du même cluster ou sur Internet, en utilisant un troisième élément{nbsp}: les services.

[#_pods]
== Pods

https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/[_Les pods_] sont un ou plusieurs conteneurs qui partagent des espaces de noms réseau et des volumes de stockage. La plupart des pods n'ont qu'un seul conteneur. Par conséquent, lorsque nous discutons des _pods_, le terme est souvent synonyme de _conteneurs_. Vous mettez à l'échelle les pods de la même manière que vous mettez à l'échelle les conteneurs--en ayant plusieurs instances du même pod qui implémente un service. En général, les pods sont mis à l'échelle et gérés par les charges de travail.

[#_workloads]
== Workloads

_Les charges de travail_ sont des objets qui définissent les règles de déploiement pour les pods. Sur la base de ces règles, Kubernetes effectue le déploiement et met à jour les charges de travail avec l'état actuel de l'application.
Les charges de travail vous permettent de définir les règles pour la planification, la mise à l'échelle et la mise à niveau des applications.

[#_workload_types]
=== Types de charges de travail

Kubernetes divise les charges de travail en différents types. Les types les plus populaires pris en charge par Kubernetes sont{nbsp}:

* https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Déploiements]
+
_Les déploiements_ sont mieux utilisés pour les applications sans état (c'est-à-dire lorsque vous n'avez pas à maintenir l'état de la charge de travail). Les pods gérés par des charges de travail de type déploiement sont considérés comme indépendants et jetables. Si un pod rencontre une perturbation, Kubernetes le supprime puis le recrée. Un exemple d'application serait un serveur web Nginx.

* https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/[StatefulSets]
+
_StatefulSets_, contrairement aux déploiements, sont mieux utilisés lorsque votre application doit maintenir son identité et stocker des données. Par exemple, une application telle que Zookeeper-- nécessite une base de données pour le stockage.

* https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSets]
+
_DaemonSets_ garantit que chaque nœud du cluster exécute une copie d'un pod. Pour les cas d'utilisation où vous collectez des journaux ou surveillez les performances des nœuds, cette charge de travail de type daemon fonctionne le mieux.

* https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/[Jobs]
+
_Jobs_ lancent un ou plusieurs pods et garantissent qu'un nombre spécifié d'entre eux se terminent avec succès. Les jobs sont mieux utilisés pour exécuter une tâche finie jusqu'à son achèvement plutôt que de gérer un état d'application souhaité en cours.

* https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/[CronJobs]
+
_CronJobs_ sont similaires aux jobs. Les CronJobs, cependant, s'exécutent jusqu'à leur achèvement selon un calendrier basé sur cron.

[#_services]
== Services

Dans de nombreux cas d'utilisation, une charge de travail doit être soit{nbsp}:

* Accédée par d'autres charges de travail dans le cluster.
* Exposée au monde extérieur.

Vous pouvez atteindre ces objectifs en créant un _Service_. Les services sont mappés aux pods de la charge de travail sous-jacente en utilisant une https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#service-and-replicationcontroller[approche de sélecteur/étiquette (voir les exemples de code)]. L'interface utilisateur de Rancher simplifie ce processus de mappage en créant automatiquement un service avec la charge de travail, en utilisant le port et le type de service que vous sélectionnez.

[#_service_types]
=== Types de service

Il existe plusieurs types de services disponibles dans Rancher. Les descriptions ci-dessous proviennent de la https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types[Documentation Kubernetes].

* *ClusterIP*
+
____
Expose le service sur une adresse IP interne au cluster. Choisir cette valeur rend le service uniquement accessible depuis l'intérieur du cluster. Il s'agit de la valeur par défaut `ServiceType`.
____

* *NodePort*
+
____
Expose le service sur l'adresse IP de chaque nœud à un port statique (le `NodePort`). Un service `ClusterIP`, vers lequel le service `NodePort` va router, est automatiquement créé. Vous pourrez contacter le service `NodePort` depuis l'extérieur du cluster en demandant `<NodeIP>:<NodePort>`.
____

* *LoadBalancer*
+
____
Expose le service à l'extérieur en utilisant l'équilibreur de charge d'un fournisseur de cloud. Les services `NodePort` et `ClusterIP`, vers lesquels l'équilibreur de charge externe va router, sont automatiquement créés.
____

[#_workload_options]
== Options de charge de travail

Cette section de la documentation contient des instructions pour déployer des charges de travail et utiliser les options de charge de travail.

* {xref-deploy-workloads}[Déployer des charges de travail]
* {xref-upgrade-workloads}[Mettre à niveau des charges de travail]
* {xref-roll-back-workloads}[Retour à l'état initial des charges de travail]

[#_related_links]
== Liens connexes

* https://kubernetes.io/docs/concepts/services-networking/service/[Services]
