= Extension API Server
:revdate: 2025-08-20
:page-revdate: {revdate}

Rancher extends Kubernetes with additional APIs by registering an extension API server using the https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/[Kubernetes API Aggregation Layer].

== Aggregation Layer is Required

The API aggregation layer must be configured on the local Kubernetes cluster for the `v1.ext.cattle.io` `APIService` to work correctly. If the `APIService` does not receive a registration request after the Rancher server starts, the pod crashes with a log entry indicating the error. If your pods are consistently failing to detect registration despite having a correctly configured cluster, you can increase the timeout by setting the `.Values.aggregationRegistrationTimeout` in Helm.

Starting in Rancher v2.12.0, all versions of Kubernetes supported by RKE2/K3s have the aggregation layer configured and enabled by default. However, if you suspect that your cluster configuration is incorrect, refer to the https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/[Kubernetes Aggregation Layer documentation] for information on configuring the aggregation layer.

[NOTE]
====
If the underlying Kubernetes distribution does not support the aggregation layer, you must migrate to a Kubernetes distribution that does before upgrading.
====
