= Extension API Server
:revdate: 2025-08-05
:page-revdate: {revdate}

Rancher extends Kubernetes with additional APIs by registering an extension API server using the https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/[Kubernetes API Aggregation Layer].

== Disabling the extension API server

The https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/[aggregation layer must be configured] on the local Kubernetes cluster for the `imperative-api-extension` feature to be enabled and to work correctly. The feature assumes this is configured and is enabled by default. If it is not possible to configure the aggregation layer for your local Kubernetes cluster, then you must disable the feature. The `imperative-api-extension` feature flag can be disabled by either using the xref:rancher-admin/experimental-features/experimental-features.adoc#_disabling_features_with_the_rancher_ui[Rancher UI] or xref:rancher-admin/experimental-features/experimental-features.adoc#_disabling_features_with_the_rancher_api[Rancher API].

It will still be possible to access the additional APIs when the feature is disabled. The additional APIs are available at `\https://<rancher url>/ext` and they are compatible with the Kubernetes apiserver. This means you can use `curl` or `kubectl` to interact with the APIs.