= {rancher-product-name} 不再需要
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: faq/rancher-is-no-longer-needed.adoc 
:product-path: faq/rancher-is-no-longer-needed.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
endif::[]

本页面旨在回答如果您不再需要 Rancher，或者不希望某个集群由 Rancher 管理，或如果 Rancher 服务器被删除时会发生什么的问题。

[#_if_the_rancher_server_is_deleted_what_happens_to_the_workloads_in_my_downstream_clusters]
== 如果 Rancher 服务器被删除，我的下游集群中的工作负载会发生什么？

如果 Rancher 被删除或无法恢复，所有由 Rancher 管理的下游 Kubernetes 集群中的工作负载将继续正常运行。

[#_if_the_rancher_server_is_deleted_how_do_i_access_my_downstream_clusters]
== 如果 Rancher 服务器被删除，我该如何访问我的下游集群？

在没有 Rancher 的情况下访问下游集群的能力取决于集群的类型和创建方式。总结：

* *注册/导入的集群：*该集群将不受影响，您可以使用与注册集群到 Rancher 之前相同的方法访问该集群。
ifeval::["{build-type}" != "srfa"] 
* *托管的 Kubernetes 集群：*如果您在云托管的 Kubernetes 提供商（如 EKS、GKE 或 AKS）中创建了集群，您可以继续使用提供商的云凭据管理该集群。
endif::[]
ifeval::["{build-type}" == "srfa"]
* *托管的 Kubernetes 集群：*如果您在云托管的 Kubernetes 提供商（如 EKS）中创建了集群，您可以继续使用提供商的云凭据管理该集群。
endif::[]
* *Rancher 提供的集群：*要访问一个 {xref-launch-k8s-with-rancher}[RKE2/K3s 集群，] 该集群必须启用 {xref-arch-com-ds-cluster}#_4_authorized_cluster_endpoint[授权集群端点]，并且您必须已经从 Rancher UI 下载了集群的 kubeconfig 文件。（RKE 集群的授权集群端点默认启用。）通过此端点，您可以直接使用 kubectl 访问集群，而不是通过 Rancher 服务器的 {xref-arch-com-ds-cluster}#_1_the_authentication_proxy[身份验证代理] 进行通信。有关如何配置 kubectl 使用授权集群端点的说明，请参阅关于直接使用 {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[kubectl 和 kubeconfig 文件] 访问集群的部分。这些集群将使用 Rancher 被移除时配置的身份验证快照。

[#_what_if_i_dont_want_rancher_anymore]
== 如果我不再想要 Rancher，该怎么办？

[NOTE]
====

自 2022 年 6 月以来，之前推荐的 xref:[系统工具] 已被弃用。
====


如果您 {xref-install-rancher}[在 Kubernetes 集群上安装了 Rancher，] 请使用 https://github.com/rancher/rancher-cleanup[Rancher 清理] 工具删除 Rancher。

在高可用性（HA）模式下卸载 Rancher 还将删除所有 `helm-operation-*` pod 和以下应用程序：

* fleet
* fleet-agent
* rancher-operator
* rancher-webhook

自定义资源（CRD）和自定义名称空间仍需手动删除。

如果您是通过 Docker 安装 Rancher 的，可以通过删除其运行的单个 Docker 容器来卸载 Rancher。

导入的集群不会受到去除 Rancher 的影响。对于其他类型的集群，请参阅关于<<_if_the_rancher_server_is_deleted_how_do_i_access_my_downstream_clusters,去除 Rancher 时访问下游集群>>的部分。

[#_what_if_i_dont_want_my_registered_cluster_managed_by_rancher]
== 如果我不想让我的注册集群由 Rancher 管理怎么办？

如果在 Rancher UI 中删除注册集群，该集群将与 Rancher 断开连接，保持完整，并可以通过注册 Rancher 之前使用的相同方法访问。

要断开集群，

. 在左上角，点击 *☰ > 集群管理*。
. 请转到应与 Rancher 断开连接的注册集群，然后单击*⋮ > 删除*。
. 单击*删除*。

*结果：*注册集群与 Rancher 断开连接，并在 Rancher 外部正常运行。

[#_what_if_i_dont_want_my_hosted_kubernetes_cluster_managed_by_rancher]
== 如果我不想让我的托管 Kubernetes 集群由 Rancher 管理怎么办？

目前，没有功能可以将这些集群从 Rancher 中断开。在此上下文中，“断开”被定义为能够从集群中移除 Rancher 组件，并独立于 Rancher 管理对集群的访问。

在此 https://github.com/rancher/rancher/issues/25234[问题]中跟踪在没有 Rancher 的情况下管理这些集群的能力。

有关如何在删除 Rancher 服务器后访问集群的信息，请参阅<<_if_the_rancher_server_is_deleted_how_do_i_access_my_downstream_clusters,本节。>>
