= 安全常见问题解答
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: faq/security.adoc 
:product-path: faq/security.adoc
ifeval::["{build-type}" != "community"]
:xref-security-overview: xref:security/security-overview.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-security-overview: xref:reference-guides/rancher-security/index.adoc
endif::[]

[#_is_there_a_hardening_guide]
== 是否有安全强化指南？

安全强化指南位于主要的{xref-security-overview}[安全]部分。

[#_have_hardened_rancher_kubernetes_clusters_been_evaluated_by_the_cis_kubernetes_benchmark_where_can_i_find_the_results]
== 安全强化的Rancher Kubernetes集群是否已通过CIS Kubernetes基准评估？我在哪里可以找到结果？

我们已经对安全强化的Rancher Kubernetes集群进行了CIS Kubernetes基准评估。 该评估的结果可以在主要的{xref-security-overview}[安全]部分找到。

[#_how_does_rancher_verify_communication_with_downstream_clusters_and_what_are_some_associated_security_concerns]
== Rancher如何验证与下游集群的通信，以及存在哪些相关的安全问题？

Rancher服务器与下游集群之间的通信是通过代理进行的。Rancher使用注册的证书颁发机构（CA）捆绑包或本地信任存储来验证Rancher代理与Rancher服务器之间的通信。使用CA捆绑包进行验证更为严格，因为只有基于该捆绑包的证书才被信任。如果显式CA捆绑包的TLS验证失败，Rancher可能会回退到使用本地信任存储来验证未来的通信。本地信任存储中的任何CA都可以用来生成有效的证书。

如 https://www.suse.com/c/rancher-security-update/[Rancher安全更新CVE-2024-22030]中所述，在特定情况下，恶意行为者可以通过利用Rancher CA的行为来接管Rancher节点。为了使攻击成功，恶意行为者必须从目标Rancher服务器中的有效CA或从有效注册CA生成有效证书。攻击者还需要先劫持或伪造Rancher服务器URL，作为初步步骤。Rancher目前正在评估Rancher CA的行为，以缓解这种及任何类似的攻击风险。
