= 创建 GKE 集群
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/Kubernetes 集群在 Rancher 中设置/从托管的 Kubernetes 提供商设置集群/gke.adoc 
:product-path: cluster-deployment/hosted-kubernetes/gke/gke.adoc
ifeval::["{build-type}" != "community"]
:xref-sync-hosted-clusters: xref:cluster-deployment/hosted-kubernetes/sync-clusters.adoc
:xref-gke-private-clusters: xref:cluster-deployment/hosted-kubernetes/gke/private-clusters.adoc
:xref-gke-config: xref:cluster-deployment/hosted-kubernetes/gke/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-sync-hosted-clusters: xref:reference-guides/cluster-configuration/rancher-server-configuration/sync-clusters.adoc
:xref-gke-private-clusters: xref:参考指南/集群配置/Rancher 服务器配置/gke 集群配置/gke 私有集群.adoc
:xref-gke-config: xref:参考指南/集群配置/Rancher 服务器配置/gke 集群配置/index.adoc
endif::[]

[#_prerequisites]
== 先决条件

需要在 Google Kubernetes Engine 中进行一些设置。

[#_service_account_token]
=== 服务账户令牌

使用 https://console.cloud.google.com/projectselector/iam-admin/serviceaccounts[Google Kubernetes Engine] 创建服务账户。GKE 使用此账户来操作您的集群。创建此账户还会生成用于身份验证的私钥。

服务账户需要以下角色：

* *计算查看者:* `roles/compute.viewer`
* *项目查看者:* `roles/viewer`
* *Kubernetes Engine 管理员:* `roles/container.admin`
* *服务账户用户:* `roles/iam.serviceAccountUser`

https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[Google 文档：创建和启用服务账户]

有关获取服务账户私钥的帮助，请参阅 Google 云文档 https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys[这里。] 您需要将密钥保存为 JSON 格式。

[#_google_project_id]
=== Google 项目 ID

您的集群需要成为 Google 项目的一部分。

要创建新项目，请参阅 Google 云文档 https://cloud.google.com/resource-manager/docs/creating-managing-projects#creating_a_project[这里。]

要获取现有项目的项目 ID，请参考 Google 云文档 https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects[这里。]

[#_provisioning_a_gke_cluster]
== 设置 GKE 集群

[CAUTION]
====

部署到 GKE 将会产生费用。
====


[#_1_create_a_cloud_credential]
=== 1.创建云凭据

. 单击 *☰ > 集群管理*。
. 在左侧导航栏中，点击 *云凭据*。
. 单击*创建*。
. 输入您的 Google 云凭据的名称。
. 在 *服务账户* 文本框中，粘贴您的服务账户私钥 JSON，或上传 JSON 文件。
. 单击*创建*。

*结果：*您已创建 Rancher 将用于配置新 GKE 集群的凭据。

[#_2_create_the_gke_cluster]
=== 2.创建 GKE 集群

使用 Rancher 设置和配置您的 Kubernetes 集群。要成功使用 Rancher 创建 GKE 集群，您的 GKE 必须处于标准模式。GKE 在创建 Kubernetes 集群时有两种操作模式，自动驾驶模式和标准模式。自动驾驶模式的集群配置对编辑 kube-system 命名空间有限制。然而，Rancher 在安装过程中需要在 kube-system 命名空间中创建资源。因此，您将无法在自动驾驶模式下创建 GKE 集群。有关 GKE 自动驾驶模式与标准模式差异的详细信息，请访问 https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison[比较 GKE 自动驾驶模式与标准模式]

. 单击 *☰ > 集群管理*。
. 在 *集群* 页面，点击 *创建*。
. 点击 *Google GKE*。
. 输入*集群名称*。
. 可选：使用 *成员角色* 配置集群的用户授权。点击 *添加成员* 以添加可以访问集群的用户。使用 *角色* 下拉菜单为每个用户设置权限。
. 可选：向集群添加 Kubernetes https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[标签] 或 https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/[注解]。
. 输入您的 Google 项目 ID 和 Google 云凭据。
. 填写表单的其余部分。有关帮助，请参阅 {xref-gke-config}[GKE 集群配置参考。]
. 单击*创建*。

*结果：*您已成功部署 GKE 集群。

您的集群已创建并被分配为*正在配置*状态。Rancher 正在启动您的集群。

在集群状态更新为*活动*后，您可以访问您的集群。

*活动*集群被分配两个项目：

* `Default`，包含`default`名称空间
* `System`，包含 `cattle-system`、`traefik`、`kube-public` 和 `kube-system` 名称空间

[#_private_clusters]
== 私有集群

支持私有 GKE 集群。注意：此高级设置在集群预配过程中可能需要更多步骤。有关详细信息，请参见 {xref-gke-private-clusters}[本节。]

[#_configuration_reference]
== 配置参考

有关在 Rancher 中配置 GKE 集群的详细信息，请参见 {xref-gke-config}[此页面。]

[#_updating_kubernetes_version]
== 更新 Kubernetes 版本

集群的 Kubernetes 版本可以升级到所在区域或可用区内 GKE 提供的任何版本。升级主 Kubernetes 版本不会自动升级工作节点。节点可以独立升级。

[NOTE]
====

GKE 在 1.19+ 中已移除基本身份验证。为了将集群升级到 1.19+，必须在 Google Cloud 中禁用基本身份验证。否则，在尝试升级到 1.19+ 时，Rancher 中会出现错误。您可以参考 https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#disabling_authentication_with_a_static_password[Google 文档]。之后，可以通过 Rancher 将 Kubernetes 版本更新到 1.19+。
====


[#_syncing]
== 同步中

GKE 提供程序可以在 Rancher 和提供商之间同步 GKE 集群的状态。有关此工作原理的深入技术解释，请参见 {xref-sync-hosted-clusters}[同步。]

有关配置刷新间隔的信息，请参见 {xref-gke-config}#_configuring_the_refresh_interval[本节。]

[#_programmatically_creating_gke_clusters]
== 以编程方式创建 GKE 集群

通过 Rancher 以编程方式部署 GKE 集群的最常见方式是使用 Rancher2 Terraform 提供程序。使用 Terraform 创建集群的文档在 https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster[这里]。
