= Visão Geral
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/harvester/overview.adoc 
:product-path: integrations/harvester/overview.adoc
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-provisioning-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-provisioning-drivers: xref:procedimentos/novos-guias-de-usuario/autenticação-permissões-e-configuração-global/sobre-drivers-de-provisionamento/index.adoc
endif::[]

Introduzido no Rancher v2.6.1, https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/introduction/overview.html[{harvester-product-name}] é um software de infraestrutura hiperconvergente (HCI) de código aberto construído sobre Kubernetes. O Harvester é instalado em servidores bare metal e fornece recursos integrados de virtualização e de armazenamento distribuído. Embora o Harvester opere usando Kubernetes, não é necessário que os usuários conheçam os conceitos do Kubernetes, tornando-o um aplicativo mais amigável.

[#_feature_flag]
== Sinalizador de Recurso

O sinalizador de recurso do Harvester é usado para gerenciar o acesso à página de Gerenciamento de Virtualização (VM) no Rancher, onde os usuários podem navegar diretamente para os clusters do Harvester e acessar a interface do Harvester. O sinalizador de recurso do Harvester está habilitado por padrão. Clique {xref-experimental-features}[aqui] para mais informações sobre sinalizadores de recursos no Rancher.

Para navegar até o cluster do Harvester, clique em *☰ > Gerenciamento de Virtualização*. Na página de Clusters do Harvester, clique em um dos clusters listados para ir para a visualização de um único cluster do Harvester.

* Se o sinalizador de recurso do Harvester estiver habilitado, os clusters do Harvester serão filtrados de quaisquer páginas ou aplicativos (como Entrega Contínua com Fleet) que listem clusters do Kubernetes.
* Se o sinalizador de recurso do Harvester estiver desativado e um cluster do Harvester for importado, o cluster do Harvester será exibido na lista de clusters do Rancher na página de Gerenciamento de Clusters. Os clusters do Harvester só serão exibidos na lista de clusters quando o sinalizador de recurso estiver desativado.
* Com a integração do Harvester, os clusters do Harvester agora podem ser importados para o Rancher como um tipo de cluster `Harvester`.
* Os usuários podem importar um cluster do Harvester apenas na página de Gerenciamento de Virtualização. Importar um cluster na página de Gerenciamento de Clusters não é suportado, e um aviso irá aconselhá-lo a retornar à página de Gerenciamento de Virtualização para fazê-lo.

[#__harvester_product_name_node_driver]
== {harvester-product-name} Driver de Nó

O https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/integrations/rancher/node-driver/node-driver.html[{harvester-product-name} driver de nó] está geralmente disponível para opções K3s e RKE2 no Rancher. O driver de nó está disponível independentemente de o sinalizador de recurso do Harvester estar habilitado ou não. Observe que o driver de nó está desativado por padrão. Os usuários podem criar clusters K3s ou RKE2 no Harvester apenas a partir da página de Gerenciamento de Clusters.

O Harvester permite que `.ISO` imagens sejam carregadas e exibidas através da interface do Harvester, mas isso não é suportado na interface do Rancher. Isso ocorre porque `.ISO` imagens geralmente requerem configuração adicional que interfere em uma implantação limpa (sem exigir intervenção do usuário) e normalmente não são usadas em ambientes de nuvem.

Veja {xref-provisioning-drivers}#_node_drivers[Drivers de Provisionamento] para mais informações sobre drivers de nó no Rancher.

[#_port_requirements]
== Requisitos de Porta

Os requisitos de porta para o cluster do Harvester podem ser encontrados https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/installation-setup/requirements.html#_network_requirements[aqui].

Além disso, outras considerações de rede são as seguintes:

* Certifique-se de habilitar as portas trunk VLAN do switch físico para redes VLAN de máquinas virtuais.
* Siga as orientações de configuração de rede https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/networking/cluster-network.html[aqui].

Para outros requisitos de porta para outros clusters de convidados, como K3s e RKE2, consulte https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/installation-setup/requirements.html#_port_requirements_for_k3s_or_rkerke2_clusters[estes docs].
