= {rancher-product-name} Integration mit Protokollierungsdiensten
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/index.adoc 
:product-path: observability/logging/logging.adoc
:description: Rancher integriert sich mit beliebten Protokollierungsdiensten. Erfahren Sie die Anforderungen und Vorteile der Integration mit Protokollierungsdiensten und aktivieren Sie die Protokollierung in Ihrem Cluster.
ifeval::["{build-type}" != "community"]
:xref-logging-taints-and-tolerations: xref:observability/logging/taints-and-tolerations.adoc
:xref-logging-helm-chart-options: xref:observability/logging/logging-helm-chart-options.adoc
:xref-logging-architecture: xref:observability/logging/logging-architecture.adoc
:xref-logging-rbac: xref:observability/logging/rbac-for-logging.adoc
:xref-logging-flows-clusterflows: xref:observability/logging/custom-resource-configuration/flows-and-clusterflows.adoc
:xref-logging-outputs-clusteroutputs: xref:observability/logging/custom-resource-configuration/outputs-and-clusteroutputs.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-logging-taints-and-tolerations: xref:integrations-in-rancher/logging/taints-and-tolerations.adoc
:xref-logging-helm-chart-options: xref:integrations-in-rancher/logging/logging-helm-chart-options.adoc
:xref-logging-architecture: xref:integrations-in-rancher/logging/logging-architecture.adoc
:xref-logging-rbac: xref:integrations-in-rancher/logging/rbac-for-logging.adoc
:xref-logging-flows-clusterflows: xref:integrations-in-rancher/logging/custom-resource-configuration/flows-and-clusterflows.adoc
:xref-logging-outputs-clusteroutputs: xref:integrations-in-rancher/logging/custom-resource-configuration/outputs-and-clusteroutputs.adoc
endif::[]

Der https://kube-logging.github.io/docs/[Protokollierungsoperator] unterstützt jetzt die Protokollierungslösung von Rancher anstelle der früheren internen Lösung.

[#_enabling_logging]
== Protokollierung aktivieren

Sie können die Protokollierung für einen von Rancher verwalteten Cluster aktivieren, indem Sie zur Seite "Apps" gehen und die Protokollierungs-App installieren.

. Gehen Sie zu dem Cluster, in dem Sie die Protokollierung installieren möchten, und klicken Sie auf *Apps*.
. Klicken Sie auf die *Protokollierung*-App.
. Scrollen Sie zum Ende der README des Helm-Charts und klicken Sie auf *Installieren*.

*Ergebnis:* Die Protokollierungs-App wird im `cattle-logging-system` Namespace bereitgestellt.

[#_uninstall_logging]
== Protokollierung deinstallieren

. Gehen Sie zu dem Cluster, in dem Sie die Protokollierung installieren möchten, und klicken Sie auf *Apps*.
. Klicken Sie auf *Installierte Apps*.
. Gehen Sie zum `cattle-logging-system` Namespace und aktivieren Sie die Kästchen für `rancher-logging` und `rancher-logging-crd`.
. Klicken Sie auf *Löschen*.
. Bestätigen Sie *Löschen*.

*Ergebnis* `rancher-logging` ist deinstalliert.

[#_architecture]
== Architektur

Für weitere Informationen darüber, wie die Protokollierungsanwendung funktioniert, siehe {xref-logging-architecture}[diesen Abschnitt.]

[#_role_based_access_control]
== Rollenbasierte Zugriffssteuerung

Rancher-Protokollierung hat zwei Rollen, `logging-admin` und `logging-view`. Für weitere Informationen darüber, wie und wann Sie diese Rollen verwenden, siehe {xref-logging-rbac}[diese Seite.]

[#_configuring_logging_custom_resources]
== Konfigurieren von benutzerdefinierten Protokollierungsressourcen

Um `Flows,` `ClusterFlows`, `Outputs` und `ClusterOutputs` zu verwalten,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Cluster* zu dem Cluster, in dem Sie benutzerdefinierte Protokollierungsressourcen konfigurieren möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie in der linken Navigationsleiste auf *Protokollierung*.

[#_flows_and_clusterflows]
=== Flüsse und ClusterFlüsse

Für Hilfe bei der Konfiguration von `Flows` und `ClusterFlows`, siehe {xref-logging-flows-clusterflows}[diese Seite.]

[#_outputs_and_clusteroutputs]
=== Ausgaben und ClusterAusgaben

Für Hilfe bei der Konfiguration von `Outputs` und `ClusterOutputs`, siehe {xref-logging-outputs-clusteroutputs}[diese Seite.]

[#_using_a_custom_hosttailer_image]
== Verwendung eines benutzerdefinierten HostTailer-Images

Um ein benutzerdefiniertes Image für die `HostTailer`-Ressource zu verwenden, müssen Sie das Image im `containerOverrides`-Abschnitt jeder `fileTailer` der `HostTailer`-Ressource angeben.

[,yaml]
----
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: cluster-system-log
spec:
  workloadMetaOverrides:
    annotations: {}
    labels: {}
  fileTailers:
    - disabled: false
      name: kubelet-log
      path: /var/lib/rancher/rke2/agent/logs/*.log
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
    - disabled: false
      name: containerd-log
      path: /var/lib/rancher/rke2/agent/containerd/*.log
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
    - name: kube-audit
      path: /var/log/kube-audit/audit-log.json
      disabled: false
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
----

[#_configuring_the_logging_helm_chart]
== Konfigurieren des Helm-Charts für die Protokollierung

Für eine Liste von Optionen, die konfiguriert werden können, wenn die Logging-Anwendung installiert oder geupgradet wird, siehe {xref-logging-helm-chart-options}[diese Seite.]

[#_windows_support]
=== Windows Support

Sie können xref:./logging-helm-chart-options.adoc#_enabledisable_windows_node_logging[die Protokollierung] auf Windows-Knoten aktivieren.

[#_working_with_a_custom_docker_root_directory]
=== Arbeiten mit einem benutzerdefinierten Docker-Stammverzeichnis

Für Details zur Verwendung eines benutzerdefinierten Docker-Stammverzeichnisses siehe xref:./logging-helm-chart-options.adoc#_working_with_a_custom_docker_root_directory[dieser Abschnitt.]

[#_working_with_taints_and_tolerations]
=== Arbeiten mit Taints und Toleranzen

Für Informationen zur Verwendung von Taints und Toleranzen mit der Logging-Anwendung siehe {xref-logging-taints-and-tolerations}[diese Seite.]

[#_logging_v2_with_selinux]
=== Protokollierung V2 mit SELinux

Für Informationen zur Aktivierung der Logging-Anwendung für SELinux-aktivierte Knoten siehe xref:./logging-helm-chart-options.adoc#_enabling_the_logging_application_to_work_with_selinux[dieser Abschnitt.]

[#_additional_logging_sources]
=== Zusätzliche Protokollierungsquellen

Standardmäßig sammelt Rancher Protokolle für Steuerungsebene-Komponenten und Knotenkomponenten für alle Cluster-Typen. In einigen Fällen können zusätzliche Protokolle gesammelt werden. Für Details siehe xref:./logging-helm-chart-options.adoc#_additional_logging_sources[dieser Abschnitt.]

[#_troubleshooting]
== Fehlerbehebung

[#_the_logging_buffer_overloads_pods]
=== Der Protokollpuffer überlastet Pods

Je nach Ihrer Konfiguration kann die Standardpuffergröße zu groß sein und Pod-Fehler verursachen. Eine Möglichkeit, die Last zu reduzieren, besteht darin, das Flush-Intervall des Protokollgebers zu verringern. Dies verhindert, dass Protokolle den Puffer überfüllen. Sie können auch mehr Flush-Threads hinzufügen, um Momente zu bewältigen, in denen viele Protokolle versuchen, den Puffer gleichzeitig zu füllen.

Für eine umfassendere Beschreibung, wie Sie den Protokollpuffer an die Bedürfnisse Ihrer Organisation anpassen können, siehe die offizielle Dokumentation des Protokollierungsoperators zu https://kube-logging.github.io/docs/configuration/plugins/outputs/buffer/[Puffern] und zu https://kube-logging.github.io/docs/logging-infrastructure/fluentd/[Fluentd-Konfiguration].

[#_the_cattle_logging_namespace_being_recreated]
=== Der `cattle-logging` Namespace wird neu erstellt

Wenn Ihr Cluster zuvor die Protokollierung aus der globalen Ansicht in der alten Rancher-Benutzeroberfläche bereitgestellt hat, können Sie auf ein Problem stoßen, bei dem sein `cattle-logging` Namespace ständig neu erstellt wird.

Die Lösung besteht darin, alle `clusterloggings.management.cattle.io` und `projectloggings.management.cattle.io` benutzerdefinierten Ressourcen aus dem cluster-spezifischen Namespace im Management-Cluster zu löschen.
Die Existenz dieser benutzerdefinierten Ressourcen führt dazu, dass Rancher den `cattle-logging` Namespace im Downstream-Cluster erstellt, wenn er nicht existiert.

Der Cluster-Namespace entspricht der Cluster-ID, daher müssen wir die Cluster-ID für jeden Cluster finden.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf die *Cluster*-Seite, gehen Sie zu dem Cluster, dessen ID Sie erhalten möchten, und klicken Sie auf *Erkunden*.
. Kopieren Sie den `<cluster-id>`-Teil aus einer der untenstehenden URLs. Der `<cluster-id>` Teil ist der Name des Cluster-Namensraums.

[,bash]
----
# Cluster Management UI
https://<your-url>/c/<cluster-id>/

# Cluster Dashboard
https://<your-url>/dashboard/c/<cluster-id>/
----

Jetzt, da wir den `<cluster-id>` Namensraum haben, können wir die CRs löschen, die dazu führen, dass `cattle-logging` ständig neu erstellt wird.
_Warnung:_ Stellen Sie sicher, dass die Protokollierung, die aus der globalen Ansicht in der alten Rancher-Benutzeroberfläche installiert wurde, derzeit nicht verwendet wird.

[,bash]
----
kubectl delete crd clusterloggings.management.cattle.io -n <cluster-id>
kubectl delete crd projectloggings.management.cattle.io -n <cluster-id>
----
