= Rollenbasierte Zugriffskontrolle für das Logging
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/rbac-for-logging.adoc 
:product-path: observability/logging/rbac-for-logging.adoc

Rancher-Protokollierung hat zwei Rollen, `logging-admin` und `logging-view`.

* `logging-admin` gewährt Benutzern vollen Zugriff auf namensraumbezogene `Flows` und `Outputs`
* `logging-view` ermöglicht Benutzern, _anzusehen_ namensraumbezogene `Flows` und `Outputs` sowie `ClusterFlows` und `ClusterOutputs`

[NOTE]
.Warum eine Rolle der anderen vorziehen?
====

Der Bearbeitungszugriff auf `ClusterFlow` und `ClusterOutput` Ressourcen ist mächtig. Jeder Benutzer mit diesem Zugriff hat Bearbeitungszugriff auf alle Protokolle im Cluster.
====


In Rancher ist die Rolle des Clusteradministrators die einzige Rolle mit vollem Zugriff auf alle `rancher-logging` Ressourcen. Cluster-Mitglieder können keine Logging-Ressourcen bearbeiten oder lesen. Projektbesitzer und Mitglieder haben die folgenden Privilegien:

|===
| Projektbesitzer | Projektmitglieder

| können namensraumbezogene `Flows` und `Outputs` in den Namespaces ihrer Projekte erstellen
| können nur die `Flows` und `Outputs` in den Namespaces der Projekte anzeigen

| können Protokolle von allem in den Namespaces ihrer Projekte sammeln
| können keine Protokolle in den Namespaces ihrer Projekte sammeln
|===

Sowohl Projektbesitzer als auch Projektmitglieder benötigen mindestens _einen_ Namespace in ihrem Projekt, um Logging zu verwenden. Wenn sie dies nicht tun, sehen sie möglicherweise die Logging-Schaltfläche im Dropdown-Menü der oberen Navigation nicht.
