= Fehlerbehebung
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/logging.adoc 
:product-path: observability/logging/troubleshooting.adoc
:experimental:

[#_log_levels]
== Protokollierumfang

Die folgenden Protokollebenen werden in Rancher verwendet:

|===
| Name | Beschreibung

| `info`
| Protokolliert informative Meldungen. Dies ist der Standard-Protokollierumfang.

| `debug`
| Protokolliert detailliertere Nachrichten, die zum Debuggen verwendet werden können.

| `trace`
| Protokolliert sehr detaillierte Nachrichten zu internen Funktionen. Dies ist sehr ausführlich und kann sensible Informationen enthalten.
|===

[#_how_to_configure_a_log_level]
=== So konfigurieren Sie eine Protokollebene

[#_kubernetes_install]
==== Kubernetes Install

* Konfigurieren Sie die Debug-Protokollebene

 $ KUBECONFIG=./kube_config_cluster.yml
 $ kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -c rancher -- loglevel --set debug; done
 OK
 OK
 OK
 $ kubectl -n cattle-system logs -l app=rancher -c rancher

* Konfigurieren Sie die Info-Protokollebene

 $ KUBECONFIG=./kube_config_cluster.yml
 $ kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -c rancher -- loglevel --set info; done
 OK
 OK
 OK

[#_docker_install]
==== Docker-Installation

* Konfigurieren Sie die Debug-Protokollebene

 $ docker exec -ti <container_id> loglevel --set debug
 OK
 $ docker logs -f <container_id>

* Konfigurieren Sie die Info-Protokollebene

 $ docker exec -ti <container_id> loglevel --set info
 OK

[#_rancher_machine_debug_logs]
== Rancher-Maschine Debug-Protokolle

Wenn Sie Probleme bei der Erstellung von Objekten in Ihrem bevorzugten Infrastrukturprovider beheben müssen, können `rancher-machine` Debug-Protokolle hilfreich sein.

Es ist möglich, Debug-Protokolle für `rancher-machine` zu aktivieren, indem Umgebungsvariablen beim Start von Rancher gesetzt werden.

Die `CATTLE_WHITELIST_ENVVARS` Umgebungsvariable ermöglicht es Benutzern, bestimmte Umgebungsvariablen auf die Whitelist zu setzen, die während der Bereitstellung an `rancher-machine` weitergegeben werden sollen.

Die `MACHINE_DEBUG` Variable aktiviert Debug-Protokolle in `rancher-machine`.

Durch das Setzen von `MACHINE_DEBUG=true` und das Hinzufügen von `MACHINE_DEBUG` zur Standardliste der Variablen in `CATTLE_WHITELIST_ENVVARS` (z. B. `CATTLE_WHITELIST_ENVVARS=HTTP_PROXY,HTTPS_PROXY,NO_PROXY,MACHINE_DEBUG`) ist es möglich, Debug-Protokolle in `rancher-machine` bei der Bereitstellung von RKE1-, RKE2- und k3s-Clustern zu aktivieren.

[CAUTION]
====

Genau wie die oben genannte `trace` Protokollebene können `rancher-machine` Debug-Protokolle sensible Informationen enthalten.
====


[#_cattle_cluster_agent_debug_logs]
== Cattle-cluster-agent Debug-Protokolle

Die `cattle-cluster-agent` Protokollebenen können festgelegt werden, wenn Sie Downstream-Cluster initialisieren.

Wenn Sie einen Cluster unter menu:Cluster-Konfiguration[Agent-Umgebungsvariablen] erstellen, können Sie Variablen festlegen, um die Protokollebene zu definieren.

* Protokollierung auf Trace-Ebene: Setzen Sie `CATTLE_TRACE` oder `RANCHER_TRACE` auf `true`
* Protokollierung auf Debug-Ebene: Setzen Sie `CATTLE_DEBUG` oder `RANCHER_DEBUG` auf `true`

[CAUTION]
====

Die `cattle-cluster-agent` Debug-Protokolle können sensible Informationen enthalten.
====

