= Gestión de credenciales de nube
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: reference-guides/user-settings/manage-cloud-credentials.adoc 
:product-path: rancher-admin/users/settings/manage-cloud-credentials.adoc
ifeval::["{build-type}" != "community"]
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-manage-node-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-infra-providers: xref:guías-de-instrucciones/nuevas-guías-de-usuario/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/index.adoc
:xref-manage-node-drivers: xref:guías-de-instrucciones/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-controladores-de-provisión/gestionar-controladores-de-nodos.adoc
endif::[]

La creación o asociación de credenciales de nube forma parte del proceso de creación de clúster, la información a continuación proporciona orientación sobre la gestión de credenciales en Rancher.

Las credenciales de nube están vinculadas al perfil de usuario de su creador. No *se pueden* compartir entre usuarios no administradores. Sin embargo, los administradores pueden ver y gestionar las credenciales de nube de otros usuarios.

[#_creating_a_cloud_credential]
== Creación de una credencial de nube

. Haz clic en *☰ > Gestión de Clústeres*.
. Haz clic en *Credenciales de Nube*.
. Haga clic en *Crear*.
. Haz clic en un tipo de credencial de nube. Los valores de este desplegable se basan en los `active` {xref-manage-node-drivers}[controladores de nodos] en Rancher.
. Introduce un nombre para la credencial de nube.
. Según el tipo de credencial de nube seleccionada, introduce los valores requeridos para autenticarte con el proveedor de infraestructura.
. Haga clic en *Crear*.

**Resultado:** La credencial de nube ha sido creada.

[#_updating_a_cloud_credential]
== Actualización de una credencial de nube

Cuando se cambian o comprometen las credenciales de acceso, actualizar una credencial de nube te permite rotar esas credenciales mientras mantienes la misma plantilla de nodo.

. Haz clic en *☰ > Gestión de Clústeres*.
. Haz clic en *Credenciales de Nube*.
. Elige la credencial de nube que deseas editar y haz clic en *⋮ > Editar configuración*.
. Actualiza la información de la credencial y haz clic en *Guardar*.

**Resultado:** La credencial de nube se actualiza con las nuevas credenciales de acceso.

[#_deleting_a_cloud_credential]
== Eliminando una credencial de nube

. Haz clic en *☰ > Gestión de Clústeres*.
. Haz clic en *Credenciales de Nube*.
. Puedes eliminar una credencial de nube individualmente o eliminar en bloque.
 ** Para eliminar una individualmente, elige la credencial de nube que deseas editar y haz clic en *⋮ > Eliminar*.
 ** Para eliminar credenciales de nube en bloque, selecciona una o más credenciales de nube de la lista. Haz clic en *Eliminar*.
. Confirma que deseas eliminar estas credenciales de nube.
