= Como o Armazenamento Persistente Funciona
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/novos-guias-de-usuário/gerenciar-clusters/criar-armazenamento-persistente-kubernetes/gerenciar-armazenamento-persistente/sobre-armazenamento-persistente.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/about-persistent-storage.adoc
:experimental:

Um volume persistente (PV) é uma unidade de armazenamento no cluster Kubernetes, enquanto uma solicitação de volume persistente (PVC) é um pedido de armazenamento.

Existem duas maneiras de usar armazenamento persistente no Kubernetes:

* Usar um volume persistente existente
* Provisionar novos volumes persistentes dinamicamente

Para usar um PV existente, sua aplicação precisará usar um PVC que esteja vinculado a um PV, e o PV deve incluir os recursos mínimos que o PVC requer.

Para o provisionamento dinâmico de armazenamento, sua aplicação precisará usar um PVC que esteja vinculado a uma classe de armazenamento. A classe de armazenamento contém a autorização para provisionar novos volumes persistentes.

image::rancher-storage.svg[Configurando Armazenamento Persistente Novo e Existente]

Para mais informações, consulte a https://kubernetes.io/docs/concepts/storage/volumes/[documentação oficial do Kubernetes sobre armazenamento]

[#_about_persistent_volume_claims]
== Sobre Solicitações de Volume Persistente

As solicitações de volume persistente (PVCs) são objetos que solicitam recursos de armazenamento do seu cluster. Elas são semelhantes a um voucher que sua implantação pode resgatar para acesso ao armazenamento. Um PVC é montado em uma carga de trabalho como um volume para que a carga de trabalho possa reivindicar sua parte especificada do armazenamento persistente.

Para acessar o armazenamento persistente, um pod deve ter um PVC montado como um volume. Esse PVC permite que sua implantação armazene seus dados em um local externo, de modo que, se um pod falhar, ele pode ser substituído por um novo pod e continuar acessando seus dados armazenados externamente, como se uma interrupção nunca tivesse ocorrido.

Cada projeto do Rancher contém uma lista de PVCs que você criou, disponível em menu:Recursos[Cargas de trabalho> Volumes]. Você pode reutilizar esses PVCs ao criar implantações no futuro.

[#_pvcs_are_required_for_both_new_and_existing_persistent_storage]
=== PVCs são Necessários para Armazenamento Persistente Novo e Existente

Um PVC é necessário para que os pods usem qualquer armazenamento persistente, independentemente de a carga de trabalho estar destinada a usar armazenamento que já existe ou se a carga de trabalho precisará provisionar dinamicamente novo armazenamento sob demanda.

Se você estiver configurando armazenamento existente para uma carga de trabalho, a carga de trabalho monta um PVC, que se refere a um PV, que corresponde à infraestrutura de armazenamento existente.

Se uma carga de trabalho deve solicitar novo armazenamento, a carga de trabalho monta um PVC, que se refere a uma classe de armazenamento, que tem a capacidade de criar um novo PV junto com sua infraestrutura de armazenamento subjacente.

O Rancher permite que você crie quantos PVCs desejar dentro de um projeto.

Você pode montar PVCs em uma implantação enquanto a cria, ou depois, após a implantação estar em execução.

[#_setting_up_existing_storage_with_a_pvc_and_pv]
== Configurando Armazenamento Existente com um PVC e PV

Seus pods podem armazenar dados em https://kubernetes.io/docs/concepts/storage/volumes/[volumes,], mas se o pod falhar, esses dados serão perdidos. Para resolver esse problema, o Kubernetes oferece volumes persistentes (PVs), que são recursos do Kubernetes que correspondem a discos de armazenamento externos ou sistemas de arquivos que seus pods podem acessar. Se um pod falhar, seu pod substituto pode acessar os dados no armazenamento persistente sem perda de dados.

Os PVs podem representar um disco físico ou um sistema de arquivos que você hospeda localmente, ou um recurso de armazenamento hospedado por um fornecedor, como Amazon EBS ou Azure Disk.

Criar um volume persistente no Rancher não criará um volume de armazenamento. Ele apenas cria um recurso do Kubernetes que mapeia para um volume existente. Portanto, antes de criar um volume persistente como um recurso do Kubernetes, você deve ter o armazenamento provisionado.

[NOTE]
.Importante:
====

Os PVs são criados no nível do cluster, o que significa que, em um cluster multiusuário, equipes com acesso a namespaces separados podem ter acesso ao mesmo PV.
====


[#_binding_pvs_to_pvcs]
=== Vinculando PVs a PVCs

Quando os pods são configurados para usar armazenamento persistente, eles montam uma reivindicação de volume persistente (PVC) que é montada da mesma forma que qualquer outro volume do Kubernetes. Quando cada PVC é criado, o master do Kubernetes considera isso uma solicitação de armazenamento e o vincula a um PV que atende aos requisitos mínimos de recursos do PVC. Nem todo PVC está garantido a ser vinculado a um PV. De acordo com a https://kubernetes.io/docs/concepts/storage/persistent-volumes/[documentação,] do Kubernetes

____
As reivindicações permanecerão não vinculadas indefinidamente se um volume correspondente não existir. As reivindicações serão vinculadas à medida que volumes correspondentes se tornem disponíveis. Por exemplo, um cluster provisionado com muitos PVs de 50Gi não corresponderia a um PVC solicitando 100Gi. O PVC pode ser vinculado quando um PV de 100Gi é adicionado ao cluster.
____

Em outras palavras, você pode criar PVCs ilimitados, mas eles só serão vinculados a PVs se o mestre do Kubernetes puder encontrar um PV suficiente que tenha pelo menos a quantidade de espaço em disco exigida pelo PVC.

Para provisionar dinamicamente novo armazenamento, o PVC montado no pod teria que corresponder a uma classe de armazenamento em vez de um volume persistente.

[#_provisioning_new_storage_with_a_pvc_and_storage_class]
== Provisionando Novo Armazenamento com um PVC e Classe de Armazenamento

Classes de Armazenamento permitem que você crie PVs dinamicamente sem precisar criar armazenamento persistente em um provedor de infraestrutura primeiro.

Por exemplo, se uma carga de trabalho estiver vinculada a um PVC e o PVC se referir a uma Classe de Armazenamento do Amazon EBS, a classe de armazenamento pode criar dinamicamente um volume EBS e um PV correspondente.

O master do Kubernetes então vinculará o PV recém-criado ao PVC da sua carga de trabalho, permitindo que sua carga de trabalho utilize o armazenamento persistente.
