= Requisitos da Versão do Helm
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-21
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/helm-version-requirements.adoc 
:product-path: installation-and-upgrade/requirements/helm-version-requirements.adoc

Esta seção contém os requisitos para o Helm, que é a ferramenta usada para instalar o Rancher em um cluster Kubernetes de alta disponibilidade.

[#_identifying_the_proper_helm_v3_version]
== Identificando a Versão Correta do Helm v3

Selecione qualquer versão do Helm v3 que seja oficialmente compatível com a faixa de versão do Kubernetes que você está usando em nossa https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Matriz de Suporte do Rancher].

Para aplicar esta regra, você pode precisar consultar dois recursos externos:

* *Compatibilidade da Versão do Helm:* Consulte a https://helm.sh/docs/topics/version_skew/[Política de Suporte da Versão do Helm] e selecione a versão que corresponde à regra para sua versão menor alvo do Rancher.
* *Faixa de Suporte do Kubernetes do Rancher:* Use a https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Matriz de Suporte do Rancher] para identificar as versões do Kubernetes suportadas pela sua versão menor alvo do Rancher.

[#_example]
=== Exemplo

* *Cenário:* Você está visando o Rancher v2.11.4, que suporta as versões do Kubernetes de 1.30 a 1.32.
* *Aplicativo:* Nossa regra requer uma versão do Helm que suporte essa faixa. Você pode verificar isso conferindo a compatibilidade da versão do Helm com a versão mais alta da faixa, Kubernetes v1.32.
* *Resultado:* Você descobre que tanto o Helm v3.17 quanto o Helm v3.18 suportam a faixa de Kubernetes v1.30-v1.32.
* Embora ambos funcionem, recomendamos o Helm v3.18 porque é a versão menor mais nova do Helm que se sobrepõe à faixa de Kubernetes suportada.

[#_additional_notes]
== Notas adicionais

* É necessário o Helm v3.2.x ou superior para instalar ou fazer upgrade do Rancher v2.5.
* Ao usar ferramentas que executam comandos do Helm para você (como o Terraform), você deve garantir que elas estejam configuradas para usar a versão correta do Helm.
