= Requisitos de instalação
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:product-path: installation-and-upgrade/requirements/requirements.adoc
:description: Aprenda os requisitos dos nós para cada nó que executa o servidor Rancher ao configurar o Rancher para rodar em uma configuração de Kubernetes.
ifeval::["{build-type}" != "community"]
:url-k3s-advanced-docker-runtime: https://documentation.suse.com/cloudnative/k3s/latest/en/advanced.html#_using_docker_as_the_container_runtime
:url-rke2-requirements: https://documentation.suse.com/cloudnative/rke2/latest/en/install/requirements.html
:url-k3s-datastore: https://documentation.suse.com/cloudnative/k3s/latest/en/datastore/datastore.html
:url-k3s-requirements: https://documentation.suse.com/cloudnative/k3s/latest/en/installation/requirements.html
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
:xref-psact: xref:security/psact.adoc
:xref-rancher-on-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
:xref-tuning-rancher-at-scale: xref:installation-and-upgrade/best-practices/tuning-rancher-at-scale.adoc
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-rancher-on-arm64: xref:rancher-admin/experimental-features/rancher-on-arm64.adoc
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc
:xref-dual-stack: xref:cluster-deployment/dual-stack.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-advanced-docker-runtime: https://docs.k3s.io/advanced#using-docker-as-the-container-runtime
:url-rke2-requirements: https://docs.rke2.io/install/requirements
:url-k3s-datastore: https://docs.k3s.io/datastore
:url-k3s-requirements: https://docs.k3s.io/installation/requirements
:xref-node-reqs: xref:como-fazer/guias-para-novos-usuários/cluster-kubernetes-na-configuração-do-rancher/requisitos-dos-nós-para-clusters-gerenciados-pelo-rancher.adoc
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-rancher-on-aks: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-aks.adoc
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
:xref-psact: xref:como-fazer/guias-para-novos-usuários/autenticação-permissões-e-configuração-global/modelos-de-configuração-psa.adoc
:xref-rancher-on-eks: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-amazon-eks.adoc
:xref-tuning-rancher-at-scale: xref:guias-de-referência/melhores-práticas/servidor-rancher/ajustes-e-melhores-práticas-para-o-rancher-em-escala.adoc
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-rancher-on-arm64: xref:how-to-guides/advanced-user-guides/enable-experimental-features/rancher-on-arm64.adoc
:xref-rancher-on-gke: xref:começando/instalação-e-atualização/instalar-atualizar-em-um-cluster-kubernetes/rancher-no-gke.adoc
:xref-dual-stack: xref:guias-de-referência/dual-stack.adoc
endif::[]

Esta página descreve os requisitos de software, hardware e rede para os nós onde o servidor Rancher será instalado. O servidor Rancher pode ser instalado em um único nó ou em um cluster Kubernetes de alta disponibilidade.

[NOTE]
.Importante:
====

Se você instalar o Rancher em um cluster Kubernetes, os requisitos são diferentes dos {xref-node-reqs}[requisitos dos nós para clusters de usuários downstream,] que executarão seus aplicativos e serviços.
====


A interface do usuário do Rancher funciona melhor no Firefox ou em navegadores baseados em Chromium (Chrome, Edge, Opera, Brave, etc).

Veja nossa página sobre {xref-tips-for-running-rancher}[melhores práticas] para uma lista de recomendações para executar um servidor Rancher em produção.

[#_kubernetes_compatibility_with_rancher]
== Compatibilidade do Kubernetes com o Rancher

O Rancher precisa ser instalado em uma versão suportada do Kubernetes. Consulte a https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[matriz de suporte do Rancher] para garantir que a versão do Kubernetes que você pretende usar é suportada.

Independentemente da versão e distribuição, o cluster Kubernetes deve ter a camada de API de agregação configurada corretamente para suportar a xref:api/extension-apiserver.adoc[API de extensão] usada pelo Rancher.

[#_install_rancher_on_a_hardened_kubernetes_cluster]
=== Instale o Rancher em um Cluster Kubernetes Endurecido

Se você instalar o Rancher em um cluster Kubernetes endurecido, verifique a seção {xref-psact}#_isentar_nomes_de_espacos_do_rancher[Isentando Nomes de Espaços do Rancher Necessários] para requisitos detalhados.

[#_install_rancher_on_an_ipv6_only_or_dual_stack_kubernetes_cluster]
=== Instale o Rancher em um Cluster Kubernetes Somente IPv6 ou de Pilha Dupla

Você pode implantar o Rancher em um cluster Kubernetes somente IPv6 ou de pilha dupla.

Para detalhes sobre o suporte do Rancher para IPv6 somente e pilha dupla, consulte a página {xref-dual-stack}[IPv4/IPv6 Pilha Dupla].

[#_operating_systems_and_container_runtime_requirements]
== Requisitos de Sistemas Operacionais e Tempo de Execução do Contêiner

Todos os sistemas operacionais suportados são de 64 bits x86. O Rancher deve funcionar com qualquer distribuição Linux moderna.

A https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[matriz de suporte do Rancher] lista quais versões de SO e Docker foram testadas para cada versão do Rancher.

O Docker é necessário para nós que executarão clusters RKE. Não é necessário para clusters RKE2 ou K3s.

O pacote `ntp` (Protocolo de Tempo de Rede) deve ser instalado. Isso previne erros com a validação de certificados que podem ocorrer quando o tempo não está sincronizado entre o cliente e o servidor.

Algumas distribuições do Linux podem ter regras de gateway de segurança padrão que bloqueiam a comunicação dentro do cluster Kubernetes. Desde o Kubernetes v1.19, o firewalld deve ser desativado, pois ele conflita com os plugins de rede do Kubernetes.

Se você não se sentir confortável fazendo isso, pode verificar sugestões na https://github.com/rancher/rancher/issues/28840[questão respectiva]. Alguns usuários tiveram sucesso https://github.com/rancher/rancher/issues/28840#issuecomment-787404822[criando uma zona de firewalld separada com uma política de ACEITAR para o Pod CIDR].

Se você planeja executar o Rancher em ARM64, veja {xref-rancher-on-arm64}[Executando em ARM64 (Experimental).]

[#__rke2_product_name_specific_requirements]
=== {rke2-product-name} Requisitos Específicos

O RKE2 inclui seu próprio tempo de execução do contêiner, o containerd.

Para detalhes sobre quais versões de SO foram testadas com o RKE2, consulte a https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[matriz de suporte do Rancher].

[#__k3s_product_name_specific_requirements]
=== {k3s-product-name} Requisitos Específicos

Para o tempo de execução do contêiner, o K3s inclui seu próprio containerd por padrão. Alternativamente, você pode configurar o K3s para usar um tempo de execução do contêiner Docker já instalado. Para mais informações sobre o uso do K3s com Docker, veja a {url-k3s-advanced-docker-runtime}[documentação do K3s.]

O Rancher precisa ser instalado em uma versão suportada do Kubernetes. Para descobrir quais versões do Kubernetes são suportadas para sua versão do Rancher, consulte a https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[matriz de suporte do Rancher]. Para especificar a versão do K3s, use a variável de ambiente INSTALL_K3S_VERSION ao executar o script de instalação do K3s.

Se você estiver instalando o Rancher em um cluster K3s com *Raspbian Buster*, siga https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster[estas etapas] para mudar para iptables legado.

Se você estiver instalando o Rancher em um cluster K3s com Alpine Linux, siga https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup[estas etapas] para configuração adicional.

[#_hardware_requirements]
== Requisitos de hardware

As seções a seguir descrevem os requisitos de CPU, memória e I/O para os nós onde o Rancher está instalado. Os requisitos variam com base no tamanho da infraestrutura.

[#_practical_considerations]
=== Considerações Práticas

A pegada de hardware do Rancher depende de vários fatores, incluindo:

* Tamanho da infraestrutura gerenciada (por exemplo, contagem de nós, contagem de clusters).
* Complexidade das regras de controle de acesso desejadas (por exemplo, `RoleBinding` contagem de objetos).
* Número de cargas de trabalho (por exemplo, implantações do Kubernetes, implantações do Fleet).
* Padrões de uso (por exemplo, subconjunto de funcionalidades ativamente utilizadas, frequência de uso, número de usuários simultâneos).

Como existem muitos fatores influentes que podem variar ao longo do tempo, os requisitos listados aqui devem ser entendidos como pontos de partida razoáveis que funcionam bem para a maioria dos casos de uso. No entanto, seu caso de uso pode ter requisitos diferentes. Para consultas sobre um cenário específico, por favor https://rancher.com/contact/[entre em contato com o Rancher] para mais orientações.

Em particular, os requisitos nesta página estão sujeitos a suposições de uso típicas, que incluem:

* Menos de 60.000 recursos Kubernetes no total, por tipo.
* Até 120 pods por nó.
* Até 200 CRDs no upstream (cluster local).
* Até 100 CRDs em downstream clusters.
* Até 50 implantações do Fleet.

Números mais altos são possíveis, mas os requisitos podem ser maiores. Se você tiver mais de 20.000 recursos do mesmo tipo, o tempo de carregamento de toda a lista através da interface do Rancher pode levar vários segundos.

[NOTE]
.Evolution:
====

A base de código do Rancher evolui, os casos de uso mudam e o corpo de experiência acumulada do Rancher cresce a cada dia.

As recomendações de requisitos de hardware estão sujeitas a mudanças ao longo do tempo, à medida que as diretrizes melhoram em precisão e se tornam mais concretas.

Se você descobrir que sua implantação do Rancher não está mais em conformidade com as recomendações listadas, https://rancher.com/contact/[entre em contato com o Rancher] para uma reavaliação.
====


[#__rke2_product_name_kubernetes]
=== {rke2-product-name} Kubernetes

A tabela a seguir lista os requisitos mínimos de CPU e memória para cada nó no {xref-install-rancher}[upstream cluster].

Observe que uma configuração altamente disponível com pelo menos três nós é necessária para produção.

|===
| Tamanho da Infraestrutura Gerenciada | Número Máximo de Clusters | Número Máximo de Nós | vCPUs | RAM

| Small
| 150
| 1500
| 4
| 16 GB

| Média
| 300
| 3000
| 8
| 32 GB

| Grande (*)
| 500
| 5000
| 16
| 64 GB

| Maior (†)
| (†)
| (†)
| (†)
| (†)
|===

(*): Implantações grandes exigem que você {xref-tuning-rancher-at-scale}[siga as melhores práticas] para um desempenho adequado.

(†): Tamanhos de implantação maiores são geralmente possíveis com recomendações de hardware ad-hoc e ajustes. Você pode https://rancher.com/contact/[contatar Rancher] para uma avaliação personalizada.

Consulte a documentação do RKE2 para informações mais detalhadas sobre {url-rke2-requirements}[requisitos gerais do RKE2].

[#__k3s_product_name_kubernetes]
=== {k3s-product-name} Kubernetes

A tabela a seguir lista os requisitos mínimos de CPU e memória para cada nó no {xref-install-rancher}[upstream cluster].

Observe que uma configuração altamente disponível com pelo menos três nós é necessária para produção.

|===
| Tamanho da Infraestrutura Gerenciada | Número Máximo de Clusters | Número Máximo de Nós | vCPUs | RAM | Host de Banco de Dados Externo (*)

| Small
| 150
| 1500
| 4
| 16 GB
| 2 vCPUs, 8 GB + 1000 IOPS

| Média
| 300
| 3000
| 8
| 32 GB
| 4 vCPUs, 16 GB + 2000 IOPS

| Grande (†)
| 500
| 5000
| 16
| 64 GB
| 8 vCPUs, 32 GB + 4000 IOPS
|===

(*): O Host de Banco de Dados Externo refere-se a hospedar o armazenamento de dados do cluster K3s em um {url-k3s-datastore}[host externo dedicado]. Isso é opcional. Os requisitos exatos dependem do armazenamento de dados externo.

(†): Implantações grandes exigem que você {xref-tuning-rancher-at-scale}[siga as melhores práticas] para um desempenho adequado.

Consulte a documentação do K3s para informações mais detalhadas sobre {url-k3s-requirements}[requisitos gerais].

[#_hosted_kubernetes]
=== Kubernetes hospedado

A tabela a seguir lista os requisitos mínimos de CPU e memória para cada nó no {xref-install-rancher}[upstream cluster].

Observe que uma configuração altamente disponível com pelo menos três nós é necessária para produção.

Esses requisitos se aplicam a clusters Kubernetes hospedados, como Amazon Elastic Kubernetes Service (EKS), Azure Kubernetes Service (AKS) ou Google Kubernetes Engine (GKE). Eles não se aplicam a soluções SaaS do Rancher, como https://www.rancher.com/products/rancher[Rancher Prime Hosted].

|===
| Tamanho da Infraestrutura Gerenciada | Número Máximo de Clusters | Número Máximo de Nós | vCPUs | RAM

| Small
| 150
| 1500
| 4
| 16 GB

| Média
| 300
| 3000
| 8
| 32 GB

| Grande (*)
| 500
| 5000
| 16
| 64 GB
|===

(*): Implantações grandes exigem que você {xref-tuning-rancher-at-scale}[siga as melhores práticas] para um desempenho adequado.

ifeval::["{build-type}" == "community"]

[#_docker]
=== Docker

A tabela a seguir lista os requisitos mínimos de CPU e memória para uma xref:[instalação em nó único do Docker para o Rancher].

Observe que uma instalação Docker é adequada apenas para fins de desenvolvimento ou teste e não deve ser usada em ambientes de produção.

|===
| Tamanho da Infraestrutura Gerenciada | Número Máximo de Clusters | Número Máximo de Nós | vCPUs | RAM

| Small
| 5
| 50
| 1
| 4 GB

| Média
| 15
| 200
| 2
| 8 GB
|===

endif::[]

[#_ingress]
== Ingress

Cada nó no cluster Kubernetes onde o Rancher está instalado deve executar um Ingress.

O Ingress deve ser implantado como DaemonSet para garantir que seu balanceador de carga possa direcionar o tráfego com sucesso para todos os nós.

Para instalações RKE2 e K3s, você não precisa instalar o Ingress manualmente, pois ele é instalado por padrão.

Para clusters Kubernetes hospedados (EKS, GKE, AKS), você precisará configurar o Ingress.

* *Amazon EKS:* Para detalhes sobre como instalar o Rancher no Amazon EKS, incluindo como instalar um Ingress para que o servidor Rancher possa ser acessado, consulte {xref-rancher-on-eks}[esta página.]
* *AKS:* Para detalhes sobre como instalar o Rancher com o Azure Kubernetes Service, incluindo como instalar um Ingress para que o servidor Rancher possa ser acessado, consulte {xref-rancher-on-aks}[esta página.]
* *GKE:* Para detalhes sobre como instalar o Rancher com o Google Kubernetes Engine, incluindo como instalar um Ingress para que o servidor Rancher possa ser acessado, consulte {xref-rancher-on-gke}[esta página.]

[#_disks]
== Discos

O desempenho do Rancher depende do desempenho do etcd no cluster. Para garantir velocidade ideal, recomendamos sempre usar discos SSD para suportar seu cluster Kubernetes de gerenciamento do Rancher. Em provedores de nuvem, você também vai querer usar o tamanho mínimo que permite o máximo de IOPS. Em clusters maiores, considere usar dispositivos de armazenamento dedicados para dados do etcd e diretórios wal.

[#_networking_requirements]
== Requisitos de Rede

Esta seção descreve os requisitos de rede para o(s) nó(s) onde o servidor Rancher está instalado.

[CAUTION]
====

Se um servidor contendo o Rancher tiver o cabeçalho `X-Frame-Options=DENY`, algumas páginas na nova interface do usuário do Rancher não conseguirão renderizar após a atualização da interface do usuário legada. Isso ocorre porque algumas páginas legadas estão incorporadas como iFrames na nova interface do usuário.
====


[#_node_ip_addresses]
=== Endereços IP do Nó

Cada nó utilizado deve ter um IP estático configurado, independentemente de você estar instalando o Rancher em um único nó ou em um cluster HA. Em caso de DHCP, cada nó deve ter uma reserva de DHCP para garantir que o nó receba o mesmo IP alocado.

[#_port_requirements]
=== Requisitos de Porta

Para operar corretamente, o Rancher requer que um número de portas estejam abertas nos nós do Rancher e nos nós do cluster Kubernetes downstream. {xref-port-reqs}[Requisitos de Porta] lista todas as portas necessárias para o Rancher e clusters downstream para os diferentes tipos de cluster.

[#_load_balancer_requirements]
=== Requisitos do Balanceador de Carga

Se você usar um balanceador de carga, ele deve ser compatível com HTTP/2.

Para receber ajuda do Suporte da SUSE, clientes do Rancher Prime que usam balanceadores de carga (ou qualquer outro intermediário, como firewalls), devem usar um que seja compatível com HTTP/2.

Quando o HTTP/2 não está disponível, o Rancher recua para HTTP/1.1. No entanto, como o HTTP/2 oferece melhor desempenho de aplicativos web, usar HTTP/1.1 pode criar problemas de desempenho.
