= Acceso y uso compartido
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/acceder-o-compartir-plantillas.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/gestionar-plantillas-rke1.adoc
endif::[]

Si eres propietario de una plantilla RKE, puedes compartirla con usuarios o grupos de usuarios, quienes podrán utilizar la plantilla para crear clústeres.

Dado que las plantillas RKE se comparten específicamente con usuarios y grupos, los propietarios pueden compartir diferentes plantillas RKE con diferentes conjuntos de usuarios.

Cuando compartes una plantilla, cada usuario puede tener uno de dos niveles de acceso:

* *Propietario:* Este usuario puede actualizar, eliminar y compartir las plantillas que posee. El propietario también puede compartir la plantilla con otros usuarios.
* *Usuario:* Estos usuarios pueden crear clústeres utilizando la plantilla. También pueden actualizar la versión de esos clústeres a nuevas revisiones de la misma plantilla. Cuando compartes una plantilla como *Hacer Público (solo lectura),* todos los usuarios en tu configuración de Rancher tienen el nivel de acceso de Usuario para la plantilla.

Si creas una plantilla, automáticamente te conviertes en propietario de esa plantilla.

Si deseas delegar la responsabilidad de actualizar la plantilla, puedes compartir la propiedad de la plantilla. Para obtener detalles sobre cómo los propietarios pueden modificar plantillas, consulta la {xref-manage-rke1-templates}[documentación sobre la revisión de plantillas.]

Hay varias formas de compartir plantillas:

* Añadir usuarios a una nueva plantilla RKE durante la creación de la plantilla
* Añadir usuarios a una plantilla RKE existente
* Hacer la plantilla RKE pública, compartiéndola con todos los usuarios en la configuración de Rancher
* Compartir la propiedad de la plantilla con usuarios que sean de confianza para modificar la plantilla

[#_sharing_templates_with_specific_users_or_groups]
== Compartir plantillas con usuarios o grupos específicos

Para permitir que usuarios o grupos creen clústeres utilizando tu plantilla, puedes darles el nivel de acceso básico *Usuario* para la plantilla.

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Bajo *la configuración de RKE1*, haz clic en *Plantillas de RKE*.
. Ve a la plantilla que deseas compartir y haz clic en *⋮ > Editar*.
. En la sección *Compartir plantilla*, haz clic en *Añadir miembro*.
. Busca en el campo *Nombre* al usuario o grupo con el que deseas compartir la plantilla.
. Elige el tipo de acceso *Usuario*.
. Haz clic en *Guardar*.

*Resultado:* El usuario o grupo puede crear clústeres utilizando la plantilla.

[#_sharing_templates_with_all_users]
== Compartir plantillas con todos los usuarios

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En el menú de navegación de la izquierda, haz clic en menu:Configuración de RKE1[Plantillas de RKE].
. Ve a la plantilla que deseas compartir y haz clic en *⋮ > Editar*.
. Bajo *Compartir plantilla,* marca la casilla para *Hacer público (solo lectura)*.
. Haz clic en *Guardar*.

*Resultado:* Todos los usuarios en la configuración de Rancher pueden crear clústeres utilizando la plantilla.

[#_sharing_ownership_of_templates]
== Compartir la propiedad de las plantillas

Si eres el creador de una plantilla, puede que desees delegar la responsabilidad de mantener y actualizar una plantilla a otro usuario o grupo.

En ese caso, puedes dar a los usuarios el tipo de acceso de Propietario, que permite a otro usuario actualizar tu plantilla, eliminarla o compartir el acceso a ella con otros usuarios.

Para dar acceso de propietario a un usuario o grupo,

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Bajo *la configuración de RKE1*, haz clic en *Plantillas de RKE*.
. Ve a la plantilla de RKE que deseas compartir y haz clic en *⋮ > Editar*.
. Bajo *Compartir plantilla*, haz clic en *Añadir miembro* y busca en el campo *Nombre* al usuario o grupo con el que deseas compartir la plantilla.
. En el campo *Tipo de acceso*, haz clic en *Propietario*.
. Haz clic en *Guardar*.

*Resultado:* El usuario o grupo tiene el tipo de acceso de Propietario, y puede modificar, compartir o eliminar la plantilla.
