= Aplicando Plantillas
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/aplicar-plantillas.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/apply-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-access-share-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/acceder-o-compartir-plantillas.adoc
:xref-manage-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/gestionar-plantillas-rke1.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

Puedes crear un clúster a partir de una plantilla RKE que hayas creado, o de una plantilla que ha sido {xref-access-share-rke1-templates}[compartida contigo.]

Las plantillas RKE se pueden aplicar a nuevos clústeres.

Puedes <<_converting_an_existing_cluster_to_use_an_rke_template,guardar la configuración de un clúster existente como una plantilla RKE.>> Entonces, los ajustes del clúster solo se pueden cambiar si la plantilla se actualiza.

No puedes cambiar un clúster para usar una plantilla RKE diferente. Solo puedes actualizar el clúster a una nueva revisión de la misma plantilla.

[#_creating_a_cluster_from_an_rke_template]
== Creando un Clúster a partir de una Plantilla RKE

Para añadir un clúster {xref-launch-k8s-with-rancher}[alojado por un proveedor de infraestructura] utilizando una plantilla RKE, sigue estos pasos:

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, haz clic en *Crear* y elige el proveedor de infraestructura.
. Proporciona el nombre del clúster y los detalles de la plantilla de nodo como de costumbre.
. Para usar una plantilla RKE, en las *Opciones del Clúster*, marca la casilla para *Usar una plantilla RKE y revisión existente*.
. Elige una plantilla RKE y revisión del menú desplegable.
. Opcional: Puedes editar cualquier configuración que el propietario de la plantilla RKE marcó como *Permitir Sobrescritura de Usuario* cuando se creó la plantilla. Si hay configuraciones que deseas cambiar, pero no tienes la opción de hacerlo, necesitarás contactar al propietario de la plantilla para obtener una nueva revisión de la plantilla. Luego necesitarás editar el clúster para actualizarlo a la nueva revisión.
. Haz clic en *Crear* para lanzar el clúster.

[#_updating_a_cluster_created_with_an_rke_template]
== Actualizando un Clúster Creado con una Plantilla RKE

Cuando el propietario de la plantilla crea una plantilla, cada configuración tiene un interruptor en la interfaz de usuario de Rancher que indica si los usuarios pueden sobrescribir la configuración.

* Si la configuración permite una sobrescritura de usuario, puedes actualizar estas configuraciones en el clúster xref:[editando el clúster.]
* Si el interruptor está desactivado, no puedes cambiar estas configuraciones a menos que el propietario del clúster cree una revisión de plantilla que te permita sobrescribirlas. Si hay configuraciones que deseas cambiar, pero no tienes la opción de hacerlo, necesitarás contactar al propietario de la plantilla para obtener una nueva revisión de la plantilla.

Si un clúster fue creado a partir de una plantilla RKE, puedes editar el clúster para actualizarlo a una nueva revisión de la plantilla.

Las configuraciones de un clúster existente pueden ser <<_converting_an_existing_cluster_to_use_an_rke_template,guardadas como una plantilla RKE.>> En esa situación, también puedes editar el clúster para actualizarlo a una nueva revisión de la plantilla.

[NOTE]
====

No puedes cambiar el clúster para usar una plantilla RKE diferente. Solo puedes actualizar el clúster a una nueva revisión de la misma plantilla.
====


[#_converting_an_existing_cluster_to_use_an_rke_template]
== Convertir un clúster existente para usar una plantilla RKE

Esta sección describe cómo crear una plantilla RKE a partir de un clúster existente.

Las plantillas RKE no pueden aplicarse a clústeres existentes, excepto si guardas las configuraciones de un clúster existente como una plantilla RKE. Esto exporta las configuraciones del clúster como una nueva plantilla RKE, y también vincula el clúster a esa plantilla. El resultado es que el clúster solo puede ser cambiado si el {xref-manage-rke1-templates}#_actualizando_una_plantilla[la plantilla se actualiza,] y el clúster se actualiza a {xref-manage-rke1-templates}#_actualizando_un_clúster_para_usar_una_nueva_revisión_de_plantilla[una versión más reciente de la plantilla].

Para convertir un clúster existente para usar una plantilla RKE,

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, ve al clúster que será convertido para usar una plantilla RKE. Haz clic en *⋮ > Guardar como Plantilla RKE*.
. Introduce un nombre para la plantilla en el formulario que aparece y haz clic en *Crear*.

*Resultados:*

* Se crea una nueva plantilla RKE.
* El clúster se convierte para utilizar la nueva plantilla.
* Se pueden <<_creating_a_cluster_from_an_rke_template,crear nuevos clústeres a partir de la nueva plantilla.>>
