= Aplicando plantillas
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guías-prácticas/guías-para-nuevos-usuarios/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/aplicar-plantillas.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/enforce-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions.adoc 
:xref-manage-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/gestionar-plantillas-rke1.adoc
endif::[]

Esta sección describe cómo los administradores de plantillas pueden aplicar plantillas en Rancher, restringiendo la capacidad de los usuarios para crear clústeres sin una plantilla.

Por defecto, cualquier usuario estándar en Rancher puede crear clústeres. Pero cuando se activa la aplicación de plantillas RKE,

* Solo un administrador tiene la capacidad de crear clústeres sin una plantilla.
* Todos los usuarios estándar deben usar una plantilla RKE para crear un nuevo clúster.
* Los usuarios estándar no pueden crear un clúster sin usar una plantilla.

Los usuarios solo pueden crear nuevas plantillas si el administrador xref:./creator-permissions.adoc#_allowing_a_user_to_create_templates[les da permiso.]

Después de que se crea un clúster con una plantilla RKE, el creador del clúster no puede editar los ajustes que están definidos en la plantilla. La única forma de cambiar esos ajustes después de que se crea el clúster es xref:./apply-templates.adoc#_updating_a_cluster_created_with_an_rke_template[actualizar la versión del clúster a una nueva revisión] de la misma plantilla. Si los creadores de clústeres quieren cambiar los ajustes definidos por la plantilla, necesitarían contactar al propietario de la plantilla para obtener una nueva revisión de la plantilla. Para detalles sobre cómo funcionan las revisiones de plantillas, consulte la {xref-manage-rke1-templates}#_actualizando_una_plantilla[documentación sobre la revisión de plantillas.]

[#_requiring_new_clusters_to_use_an_rke_template]
== Requerir que los nuevos clústeres usen una plantilla RKE

Puede que desee requerir que los nuevos clústeres usen una plantilla para asegurar que cualquier clúster lanzado por un {xref-global-permissions}[usuario estándar] utilizará los ajustes de Kubernetes y/o Rancher que han sido verificados por los administradores.

Para requerir que los nuevos clústeres usen una plantilla RKE, los administradores pueden activar la aplicación de plantillas RKE con los siguientes pasos:

. Haga clic en *☰ > Configuración Global*.
. Vaya a la `cluster-template-enforcement` configuración. Haga clic en *⋮ > Editar configuración*.
. Establezca el valor en *Verdadero* y haga clic en *Guardar*.
+

[NOTE]
.Importante:
====
Cuando el administrador establece el `cluster-template-enforcement` en *Verdadero*, también necesita compartir el `clusterTemplates` con los usuarios para que los usuarios puedan seleccionar una de estas plantillas para crear el clúster.
====


*Resultado:* Todos los clústeres provisionados por Rancher deben utilizar una plantilla, a menos que el creador sea un administrador.

[#_disabling_rke_template_enforcement]
== Desactivando la Aplicación de Plantillas RKE

Para permitir que se creen nuevos clústeres sin una plantilla RKE, los administradores pueden desactivar la aplicación de plantillas RKE con los siguientes pasos:

. Haga clic en *☰ > Configuración Global*.
. Vaya a la `cluster-template-enforcement` configuración. Haga clic en *⋮ > Editar configuración*.
. Establezca el valor en *Falso* y haga clic en *Guardar*.

*Resultado:* Cuando los clústeres son provisionados por Rancher, no necesitan utilizar una plantilla.
