= Ejemplos prácticos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/guías-para-nuevos-usuarios/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/casos-de-uso-ejemplo.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/example-use-cases.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions.adoc 
:xref-access-share-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/acceder-o-compartir-plantillas.adoc
:xref-manage-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/gestionar-plantillas-rke1.adoc
endif::[]

Estos escenarios de ejemplo describen cómo una organización podría utilizar plantillas para estandarizar la creación de clústeres.

* *Aplicando plantillas:* Los administradores pueden querer <<_enforcing_a_template_setting_for_everyone,aplicar una o más configuraciones de plantilla para todos>> si desean que todos los nuevos clústeres provisionados por Rancher tengan esas configuraciones.
* *Compartiendo diferentes plantillas con diferentes usuarios:* Los administradores pueden dar <<_templates_for_basic_and_advanced_users,diferentes plantillas a usuarios básicos y avanzados,>> para que los usuarios básicos tengan opciones más restringidas y los usuarios avanzados tengan más discreción al crear clústeres.
* *Actualizando configuraciones de plantilla:* Si los equipos de seguridad y DevOps de una organización deciden incorporar las mejores prácticas en las configuraciones requeridas para nuevos clústeres, esas mejores prácticas podrían cambiar con el tiempo. Si las mejores prácticas cambian, <<_updating_templates_and_clusters_created_with_them,una plantilla se puede actualizar a una nueva revisión>> y los clústeres creados a partir de la plantilla pueden actualizar la versión a la nueva.
* *Compartiendo la propiedad de una plantilla:* Cuando un propietario de plantilla ya no desea mantener una plantilla, o quiere delegar la propiedad de la plantilla, este escenario describe cómo <<_allowing_other_users_to_control_and_share_a_template,la propiedad de la plantilla puede ser compartida.>>

[#_enforcing_a_template_setting_for_everyone]
== Aplicar una configuración de plantilla para todos

Supongamos que hay una organización en la que los administradores deciden que todos los nuevos clústeres deben crearse con la versión de Kubernetes 1.14.

. Primero, un administrador crea una plantilla que especifica la versión de Kubernetes como 1.14 y marca todas las demás configuraciones como *Permitir Sobrescritura del Usuario*.
. El administrador hace pública la plantilla.
. El administrador activa la aplicación de la plantilla.

*Resultados:*

* Todos los usuarios de Rancher en la organización tienen acceso a la plantilla.
* Todos los nuevos clústeres creados por {xref-global-permissions}[usuarios estándar] con esta plantilla utilizarán Kubernetes 1.14 y no podrán usar una versión diferente de Kubernetes. Por defecto, los usuarios estándar no tienen permiso para crear plantillas, por lo que esta plantilla será la única que puedan usar a menos que se compartan más plantillas con ellos.
* Todos los usuarios estándar deben usar una plantilla de clúster para crear un nuevo clúster. No pueden crear un clúster sin usar una plantilla.

De esta manera, los administradores aplican la versión de Kubernetes en toda la organización, mientras que aún permiten a los usuarios finales configurar todo lo demás.

[#_templates_for_basic_and_advanced_users]
== Plantillas para usuarios básicos y avanzados

Supongamos que una organización tiene tanto usuarios básicos como avanzados. Los administradores quieren que los usuarios básicos estén obligados a usar una plantilla, mientras que los usuarios avanzados y los administradores crean sus clústeres como deseen.

. Primero, un administrador activa xref:./enforce-templates.adoc#_requiring_new_clusters_to_use_an_rke_template[la aplicación de plantillas RKE.] Esto significa que cada {xref-global-permissions}[usuario estándar] en Rancher necesitará utilizar una plantilla RKE cuando cree un clúster.
. El administrador luego crea dos plantillas:

* Una plantilla para usuarios básicos, con casi todas las opciones especificadas excepto las claves de acceso.
* Una plantilla para usuarios avanzados, que tiene la mayoría o todas las opciones con *Permitir Sobrescritura del Usuario* activada.

. El administrador comparte la plantilla avanzada solo con los usuarios avanzados.
. El administrador hace pública la plantilla para usuarios básicos, de modo que la plantilla más restrictiva sea una opción para todos los que crean un clúster provisionado por Rancher.

*Resultado:* Todos los usuarios de Rancher, excepto los administradores, están obligados a utilizar una plantilla al crear un clúster. Todos tienen acceso a la plantilla restrictiva, pero solo los usuarios avanzados tienen permiso para utilizar la plantilla más permisiva. Los usuarios básicos están más restringidos, mientras que los usuarios avanzados tienen más libertad al configurar sus clústeres de Kubernetes.

[#_updating_templates_and_clusters_created_with_them]
== Actualización de plantillas y clústeres creados con ellas

Supongamos que una organización tiene una plantilla que requiere que los clústeres utilicen Kubernetes v1.14. Sin embargo, a medida que pasa el tiempo, los administradores cambian de opinión. Deciden que quieren que los usuarios puedan actualizar la versión de sus clústeres para utilizar versiones más nuevas de Kubernetes.

En esta organización, se crearon muchos clústeres con una plantilla que requiere Kubernetes v1.14. Debido a que la plantilla no permite que esa configuración sea anulada, los usuarios que crearon el clúster no pueden editar directamente esa configuración.

El propietario de la plantilla tiene varias opciones para permitir que los creadores de clústeres actualicen la versión de Kubernetes en sus clústeres:

* *Especificar Kubernetes v1.15 en la plantilla:* El propietario de la plantilla puede crear una nueva revisión de la plantilla que especifique Kubernetes v1.15. Luego, el propietario de cada clúster que utiliza esa plantilla puede actualizar la versión de su clúster a una nueva revisión de la plantilla. Esta actualización de versión de plantilla permite al creador del clúster actualizar Kubernetes a la v1.15 en su clúster.
* *Permitir cualquier versión de Kubernetes en la plantilla:* Al crear una revisión de plantilla, el propietario de la plantilla también puede marcar la versión de Kubernetes como *Permitir Sobrescritura del Usuario* utilizando el interruptor cerca de esa configuración en la interfaz de usuario de Rancher. Esto permitirá que los clústeres que se actualicen a esta revisión de plantilla utilicen cualquier versión de Kubernetes.
* *Permitir la última versión menor de Kubernetes en la plantilla:* El propietario de la plantilla también puede crear una revisión de plantilla en la que la versión de Kubernetes se defina como *Última v1.14 (Permite actualizaciones de versión de parche)*. Esto significa que los clústeres que utilicen esa revisión podrán obtener actualizaciones de versión de parche, pero no se permitirán actualizaciones de versión principal.

[#_allowing_other_users_to_control_and_share_a_template]
== Permitir que Otros Usuarios Controlen y Compartan una Plantilla

Supongamos que Alice es una administradora de Rancher. Ella posee una plantilla RKE que refleja las mejores prácticas acordadas de su organización para crear un clúster.

Bob es un usuario avanzado que puede tomar decisiones informadas sobre la configuración del clúster. Alice confía en que Bob cree nuevas revisiones de su plantilla a medida que las mejores prácticas se actualizan con el tiempo. Por lo tanto, decide hacer de Bob un propietario de la plantilla.

Para compartir la propiedad de la plantilla con Bob, Alice xref:./access-or-share-templates.adoc#_sharing_ownership_of_templates[agrega a Bob como propietario de su plantilla.]

El resultado es que, como propietario de la plantilla, Bob está a cargo del control de versiones de esa plantilla. Bob ahora puede hacer todo lo siguiente:

* {xref-manage-rke1-templates}#_actualizando_una_plantilla[Revisar la plantilla] cuando cambian las mejores prácticas
* {xref-manage-rke1-templates}#_deshabilitando_una_revisión_de_plantilla[Deshabilitar revisiones obsoletas] de la plantilla para que no se puedan crear nuevos clústeres con ella
* {xref-manage-rke1-templates}#_eliminando_una_plantilla[Eliminar toda la plantilla] si la organización quiere ir en una dirección diferente
* {xref-manage-rke1-templates}#_estableciendo_una_revisión_de_plantilla_como_predeterminada[Establecer una cierta revisión como predeterminada] cuando los usuarios crean un clúster con ella. Los usuarios finales de la plantilla aún podrán elegir qué revisión desean utilizar para crear el clúster.
* {xref-access-share-rke1-templates}[Comparta la plantilla] con usuarios específicos, haga que la plantilla esté disponible para todos los usuarios de Rancher, o comparta la propiedad de la plantilla con otro usuario.
