= Sobrescribiendo la Configuración de Plantillas
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/sobrescribir-configuración-plantillas.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/override-template-settings.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/gestionar-plantillas-rke1.adoc
endif::[]

Cuando un usuario crea una plantilla RKE, cada configuración en la plantilla tiene un interruptor en la interfaz de usuario de Rancher que indica si los usuarios pueden sobrescribir la configuración. Este interruptor marca esas configuraciones como *Permitir Sobrescritura por el Usuario*.

Después de que se crea un clúster con una plantilla, los usuarios finales no pueden actualizar ninguna de las configuraciones definidas en la plantilla a menos que el propietario de la plantilla las haya marcado como *Permitir Sobrescritura por el Usuario*. Sin embargo, si la plantilla es {xref-manage-rke1-templates}[actualizada a una nueva revisión] que cambia las configuraciones o permite a los usuarios finales cambiarlas, el clúster puede actualizar su versión a una nueva revisión de la plantilla y los cambios en la nueva revisión se aplicarán al clúster.

Cuando cualquier parámetro se establece como *Permitir Sobrescritura por el Usuario* en la plantilla RKE, significa que los usuarios finales tienen que completar esos campos durante la creación del clúster y pueden editar esas configuraciones en cualquier momento después.

El modelo *Permitir Sobrescritura por el Usuario* de la plantilla RKE es útil para situaciones como:

* Los administradores saben que algunas configuraciones necesitarán la flexibilidad de ser actualizadas frecuentemente con el tiempo
* Los usuarios finales necesitarán ingresar sus propias claves de acceso o claves secretas, por ejemplo, credenciales de la nube o credenciales para instantáneas de copia de seguridad.
