= Acerca de las plantillas RKE1
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guías-prácticas/guías-para-nuevos-usuarios/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/index.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/rke1-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-rke1-template-example-yaml: xref:rancher-admin/global-configuration/rke1-templates/template-example-yaml.adoc
:xref-rke1-template-infrastructure: xref:rancher-admin/global-configuration/rke1-templates/infrastructure.adoc
:xref-rke1-creator-permissions: xref:rancher-admin/global-configuration/rke1-templates/creator-permissions.adoc
:xref-cluster-templates: xref:cluster-admin/manage-clusters/cluster-templates.adoc
:xref-rke1-template-example-use-cases: xref:rancher-admin/global-configuration/rke1-templates/example-use-cases.adoc
:xref-rke1-template-override-settings: xref:rancher-admin/global-configuration/rke1-templates/override-template-settings.adoc
:xref-rke1-template-apply: xref:rancher-admin/global-configuration/rke1-templates/apply-templates.adoc
:xref-rke1-template-enforce: xref:rancher-admin/global-configuration/rke1-templates/enforce-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/gestionar-plantillas-rke1.adoc
:xref-access-share-rke1-templates: xref:how-to-guides/nuevas-guías-de-usuario/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/acceder-o-compartir-plantillas.adoc
:xref-rke1-template-example-yaml: xref:reference-guides/rke1-template-example-yaml.adoc
:xref-rke1-template-infrastructure: xref:how-to-guides/guías-para-nuevos-usuarios/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/infrastructure.adoc
:xref-rke1-creator-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/creator-permissions.adoc
:xref-cluster-templates: xref:how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc
:xref-rke1-template-example-use-cases: xref:how-to-guides/guías-para-nuevos-usuarios/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/casos-de-uso-ejemplo.adoc
:xref-rke1-template-override-settings: xref:how-to-guides/guías-para-nuevos-usuarios/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/sobrescribir-configuración-de-plantilla.adoc
:xref-rke1-template-apply: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/apply-templates.adoc
:xref-rke1-template-enforce: guías-prácticas/guías-para-nuevos-usuarios/autenticación-permisos-y-configuración-global/acerca-de-plantillas-rke1/aplicar-plantillas.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

Las plantillas RKE están diseñadas para permitir que los equipos de DevOps y seguridad estandaricen y simplifiquen la creación de clústeres de Kubernetes.

RKE es el https://rancher.com/docs/rke/latest/en/[Rancher Kubernetes Engine,], que es la herramienta que Rancher utiliza para aprovisionar clústeres de Kubernetes.

Con el aumento de la popularidad de Kubernetes, hay una tendencia hacia la gestión de un mayor número de clústeres más pequeños. Cuando deseas crear muchos clústeres, es más importante gestionarlos de manera coherente. La gestión de múltiples clústeres presenta desafíos para hacer cumplir la seguridad y las configuraciones adicionales que deben estandarizarse antes de entregar los clústeres a los usuarios finales.

Las plantillas RKE ayudan a estandarizar estas configuraciones. Independientemente de si los clústeres se crean con la interfaz de usuario de Rancher, la API de Rancher o un proceso automatizado, Rancher garantizará que cada clúster que aprovisione a partir de una plantilla RKE sea uniforme y consistente en la forma en que se produce.

Los administradores controlan qué opciones de clúster pueden ser cambiadas por los usuarios finales. Las plantillas RKE también se pueden compartir con usuarios y grupos específicos, de modo que los administradores puedan crear diferentes plantillas RKE para diferentes conjuntos de usuarios.

Si un clúster fue creado con una plantilla RKE, no puedes cambiarlo a una plantilla RKE diferente. Solo puedes actualizar el clúster a una nueva revisión de la misma plantilla.

Puedes {xref-rke1-template-apply}#_converting_an_existing_cluster_to_use_an_rke_template[guardar la configuración de un clúster existente como una plantilla RKE.] Entonces, la configuración del clúster solo puede ser cambiada si la plantilla se actualiza. La nueva plantilla también se puede utilizar para lanzar nuevos clústeres.

Las características principales de las plantillas RKE permiten a los equipos de DevOps y seguridad:

* Estandarizar la configuración del clúster y asegurar que los clústeres provisionados por Rancher se creen siguiendo las mejores prácticas.
* Prevenir que los usuarios menos técnicos tomen decisiones poco informadas al provisionar clústeres.
* Compartir diferentes plantillas con diferentes conjuntos de usuarios y grupos.
* Delegar la propiedad de las plantillas a usuarios que sean de confianza para realizar cambios en ellas.
* Controlar qué usuarios pueden crear plantillas.
* Requerir que los usuarios creen clústeres a partir de una plantilla.

[#_configurable_settings]
== Ajustes configurables

Las plantillas RKE se pueden crear en la interfaz de usuario de Rancher o definir en formato YAML. Pueden definir todos los mismos parámetros que se pueden especificar cuando utilizas Rancher para provisionar nodos personalizados o nodos de un proveedor de infraestructura:

* Opciones del proveedor de nube
* Opciones de seguridad de pods
* Proveedores de red
* Controladores de Ingress
* Configuración de seguridad de red
* Plugins de red
* URL y credenciales del registro privado
* Complementos
* Opciones de Kubernetes, incluidas configuraciones para componentes de Kubernetes como kube-api, kube-controller, kubelet y servicios

La <<_add_ons,sección de complemento>> de una plantilla RKE es especialmente poderosa porque permite una amplia gama de opciones de personalización.

[#_scope_of_rke_templates]
== Alcance de las Plantillas RKE

Las plantillas RKE son compatibles con clústeres provisionados por Rancher. Las plantillas se pueden utilizar para provisionar clústeres personalizados o clústeres que son lanzados por un proveedor de infraestructura.

Las plantillas RKE son para definir configuraciones de Kubernetes y Rancher. Las plantillas de nodo son responsables de configurar nodos. Para obtener consejos sobre cómo utilizar las plantillas RKE en conjunto con hardware, consulta {xref-rke1-template-infrastructure}[Plantillas RKE y Hardware].

Las plantillas RKE se pueden crear desde cero para predefinir la configuración del clúster. Se pueden aplicar para lanzar nuevos clústeres, o las plantillas también se pueden exportar de clústeres existentes en funcionamiento.

La configuración de un clúster existente puede ser {xref-rke1-template-apply}#_convirtiendo_un_clúster_existente_para_usar_una_plantilla_rke[guardada como una plantilla RKE.] Esto crea una nueva plantilla y vincula la configuración del clúster a la plantilla, de modo que el clúster solo se puede actualizar si la {xref-manage-rke1-templates}#_actualizando_una_plantilla[plantilla se actualiza], y el clúster se actualiza para {xref-manage-rke1-templates}#_actualizando_un_clúster_para_usar_una_nueva_revisión_de_plantilla[usar una versión más nueva de la plantilla.] La nueva plantilla también se puede utilizar para crear nuevos clústeres.

[#_example_scenarios]
== Ejemplos prácticos

Cuando una organización tiene tanto usuarios básicos como avanzados de Rancher, los administradores pueden querer dar a los usuarios avanzados más opciones para la creación de clústeres, mientras restringen las opciones para los usuarios básicos.

Estos {xref-rke1-template-example-use-cases}[escenarios de ejemplo] describen cómo una organización podría utilizar plantillas para estandarizar la creación de clústeres.

Algunos de los escenarios de ejemplo incluyen lo siguiente:

* *Aplicando plantillas:* Los administradores pueden querer {xref-rke1-template-example-use-cases}#_aplicar_una_configuración_de_plantilla_para_todos[aplicar una o más configuraciones de plantilla para todos] si desean que todos los nuevos clústeres provisionados por Rancher tengan esas configuraciones.
* *Compartiendo diferentes plantillas con diferentes usuarios:* Los administradores pueden dar {xref-rke1-template-example-use-cases}#_plantillas_para_usuarios_básicos_y_avanzados[diferentes plantillas a usuarios básicos y avanzados,] para que los usuarios básicos tengan opciones más restringidas y los usuarios avanzados puedan usar más discreción al crear clústeres.
* *Actualizando configuraciones de plantilla:* Si los equipos de seguridad y DevOps de una organización deciden incorporar las mejores prácticas en las configuraciones requeridas para nuevos clústeres, esas mejores prácticas podrían cambiar con el tiempo. Si las mejores prácticas cambian, {xref-rke1-template-example-use-cases}#_actualizando_plantillas_y_clústeres_creados_con_ellas[una plantilla puede actualizarse a una nueva revisión] y los clústeres creados a partir de la plantilla pueden {xref-manage-rke1-templates}#_actualizando_un_clúster_para_usar_una_nueva_revisión_de_plantilla[actualizarse a la nueva versión de la plantilla].
* *Compartiendo la propiedad de una plantilla:* Cuando un propietario de plantilla ya no desea mantener una plantilla, o quiere compartir la propiedad de la plantilla, este escenario describe cómo {xref-rke1-template-example-use-cases}#_permitiendo_a_otros_usuarios_controlar_y_compartir_una_plantilla[se puede compartir la propiedad de la plantilla.]

[#_template_management]
== Gestión de Plantillas

Cuando creas una plantilla RKE, está disponible en la interfaz de usuario de Rancher desde la vista de *Gestión de Clústeres* bajo *Plantillas RKE*. Cuando creas una plantilla, te conviertes en el propietario de la plantilla, lo que te da permiso para revisar y compartir la plantilla. Puedes compartir las plantillas RKE con usuarios o grupos específicos, y también puedes hacerla pública.

Los administradores pueden activar la aplicación de plantillas para requerir que los usuarios siempre utilicen plantillas RKE al crear un clúster. Esto permite a los administradores garantizar que Rancher siempre provisiona clústeres con configuraciones específicas.

Las actualizaciones de plantillas RKE se gestionan a través de un sistema de revisiones. Si deseas cambiar o actualizar una plantilla, creas una nueva revisión de la plantilla. Entonces, un clúster que fue creado con la versión anterior de la plantilla puede ser actualizado a la nueva revisión de la plantilla.

En una plantilla RKE, los ajustes pueden ser restringidos a lo que el propietario de la plantilla elige, o pueden estar abiertos para que el usuario final seleccione el valor. La diferencia se indica mediante el interruptor *Permitir Sobrescritura por el Usuario* sobre cada ajuste en la interfaz de usuario de Rancher cuando se crea la plantilla.

Para los ajustes que no pueden ser sobrescritos, el usuario final no podrá editarlos directamente. Para que un usuario obtenga diferentes opciones de estos ajustes, el propietario de la plantilla RKE necesitaría crear una nueva revisión de la plantilla RKE, lo que permitiría al usuario actualizar y cambiar esa opción.

Los documentos en esta sección explican los detalles de la gestión de plantillas RKE:

* {xref-rke1-creator-permissions}[Obteniendo permiso para crear plantillas]
* {xref-manage-rke1-templates}[Creando y revisando plantillas]
* {xref-rke1-template-enforce}#_requiring_new_clusters_to_use_an_rke_template[Enforcing template settings]
* {xref-rke1-template-override-settings}[Sobrescribiendo ajustes de plantilla]
* {xref-access-share-rke1-templates}#_sharing_templates_with_specific_users_or_groups[Compartiendo plantillas con creadores de clústeres]
* {xref-access-share-rke1-templates}#_sharing_ownership_of_templates[Compartiendo la propiedad de una plantilla]

Se proporciona un {xref-rke1-template-example-yaml}[ejemplo de archivo de configuración YAML para una plantilla] como referencia.

[#_applying_templates]
== Aplicando Plantillas

Puedes {xref-rke1-template-apply}#_creating_a_cluster_from_an_rke_template[crear un clúster a partir de una plantilla] que hayas creado, o de una plantilla que ha sido {xref-access-share-rke1-templates}[compartida contigo.]

Si el propietario de la plantilla RKE crea una nueva revisión de la plantilla, puedes {xref-rke1-template-apply}#_updating_a_cluster_created_with_an_rke_template[actualizar la versión de tu clúster a esa revisión.]

Las plantillas RKE se pueden crear desde cero para predefinir la configuración del clúster. Se pueden aplicar para lanzar nuevos clústeres, o también se pueden exportar plantillas de clústeres en funcionamiento.

Puedes {xref-rke1-template-apply}#_converting_an_existing_cluster_to_use_an_rke_template[guardar la configuración de un clúster existente como una plantilla RKE.] Entonces, la configuración del clúster solo puede ser cambiada si la plantilla se actualiza.

[#_standardizing_hardware]
== Estandarizando Hardware

Las plantillas RKE están diseñadas para estandarizar los ajustes de Kubernetes y Rancher. Si también deseas estandarizar tu infraestructura, una opción es utilizar plantillas RKE {xref-rke1-template-infrastructure}[junto con otras herramientas].

Otra opción es utilizar {xref-cluster-templates}[plantillas de clúster,] que incluyen opciones de configuración de grupos de nodos, pero no hacen cumplir la configuración.

[#_yaml_customization]
== Personalización YAML

Si defines una plantilla RKE como un archivo YAML, puedes modificar este {xref-rke1-template-example-yaml}[ejemplo de plantilla RKE en YAML]. El YAML en la plantilla RKE utiliza la misma personalización que Rancher utiliza al crear un clúster RKE, pero dado que el YAML se encuentra dentro del contexto de un clúster provisionado por Rancher, necesitarás anidar la personalización de la plantilla RKE bajo la directiva `rancher_kubernetes_engine_config` en el YAML.

La documentación de RKE también tiene https://rancher.com/docs/rke/latest/en/example-yamls/[archivos anotados] `cluster.yml` que puedes usar como referencia.

Para obtener orientación sobre las opciones disponibles, consulta la documentación de RKE sobre https://rancher.com/docs/rke/latest/en/config-options/[configuración del clúster.]

[#_add_ons]
=== Complementos

La sección de complemento del archivo de configuración de la plantilla RKE funciona de la misma manera que la https://rancher.com/docs/rke/latest/en/config-options/add-ons/[sección de complemento de un archivo de configuración de clúster].

La directiva de complementos definidos por el usuario te permite llamar y descargar manifiestos de Kubernetes o incluirlos directamente en línea. Si incluyes estos manifiestos como parte de tu plantilla RKE, Rancher los provisionará en el clúster.

Algunas cosas que podrías hacer con los complementos incluyen:

* Instalar aplicaciones en el clúster de Kubernetes después de que se inicie
* Instalar complementos en nodos que se despliegan con un daemonset de Kubernetes
* Configurar automáticamente espacios de nombres, cuentas de servicio o vinculaciones de roles

La configuración de la plantilla RKE debe estar anidada dentro de la directiva `rancher_kubernetes_engine_config`. Para establecer complementos, al crear la plantilla, harás clic en *Editar como YAML*. Luego utiliza la directiva `addons` para añadir un manifiesto, o la directiva `addons_include` para establecer qué archivos YAML se utilizan para los complementos. Para más información sobre complementos personalizados, consulta la https://rancher.com/docs/rke/latest/en/config-options/add-ons/user-defined-add-ons/[documentación de complementos definidos por el usuario.]
