= Guías de configuración de monitorización
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/index.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
:xref-configure-alertmanager: xref:observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-prometheus: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
:xref-servicemonitors-and-podmonitors: xref:observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:observability/monitoring-and-dashboards/configuration/routes.adoc
:xref-helm-chart-options: xref:observability/monitoring-and-dashboards/configuration/helm-chart-options.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
:xref-configure-alertmanager: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc
:xref-prometheus: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc
:xref-servicemonitors-and-podmonitors: xref:reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:reference-guides/monitoring-v2-configuration/routes.adoc
:xref-helm-chart-options: xref:reference-guides/monitoring-v2-configuration/helm-chart-options.adoc
endif::[]

Esta página captura algunas de las opciones más importantes para configurar la Monitorización V2 en la interfaz de usuario de Rancher.

Para información sobre cómo configurar objetivos de scraping y reglas personalizadas para Prometheus, por favor consulta la documentación en sentido ascendente para el https://github.com/prometheus-operator/prometheus-operator[Operador de Prometheus.] Algunos de los recursos personalizados más importantes se explican en la https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/getting-started/design.md[documentación de diseño del Operador de Prometheus.] La documentación del Operador de Prometheus también puede ayudarte a configurar RBAC, Thanos o configuración personalizada.

[#_setting_resource_limits_and_requests]
== Configuración de Límites y Solicitudes de Recursos

Las solicitudes y límites de recursos para la aplicación de monitorización pueden configurarse al instalar `rancher-monitoring`. Para más información sobre los límites predeterminados, consulta {xref-helm-chart-options}#_configuring_resource_limits_and_requests[esta página.]

[TIP]
====

En un clúster inactivo, la Monitorización puede tener un alto uso de CPU. Para mejorar el rendimiento, desactiva el adaptador de Prometheus.
====


[#_prometheus_configuration]
== Configuración de Prometheus

Por lo general, no es necesario editar directamente el recurso personalizado de Prometheus.

En su lugar, para configurar Prometheus para recopilar métricas personalizadas, solo necesitarás crear un nuevo ServiceMonitor o PodMonitor para configurar Prometheus para recopilar métricas adicionales.

[#_servicemonitor_and_podmonitor_configuration]
=== Configuración de ServiceMonitor y PodMonitor

Para más detalles, consulta {xref-servicemonitors-and-podmonitors}[esta página.]

[#_advanced_prometheus_configuration]
=== Configuración avanzada de Prometheus

Para obtener más información sobre la edición directa del recurso personalizado de Prometheus, que puede ser útil en casos de uso avanzados, consulta {xref-prometheus}[esta página.]

[#_alertmanager_configuration]
== Configuración de Alertmanager

El recurso personalizado de Alertmanager generalmente no necesita ser editado directamente. Para la mayoría de los casos de uso comunes, puedes gestionar alertas actualizando Rutas y Receptores.

Las rutas y los receptores son parte de la configuración del recurso personalizado de Alertmanager. En la interfaz de usuario de Rancher, las Rutas y los Receptores no son verdaderos recursos personalizados, sino recursos pseudo-personalizados que el Operador de Prometheus utiliza para sincronizar tu configuración con el recurso personalizado de Alertmanager. Cuando se actualizan las rutas y los receptores, la aplicación de monitorización actualizará automáticamente Alertmanager para reflejar esos cambios.

Para algunos casos de uso avanzados, puede que desees configurar Alertmanager directamente. Para más información, consulta {xref-configure-alertmanager}[esta página.]

[#_receivers]
=== Receptores

Los receptores se utilizan para configurar notificaciones. Para detalles sobre cómo configurar receptores, consulta {xref-receivers}[esta página.]

[#_routes]
=== Rutas

Las rutas filtran las notificaciones antes de que lleguen a los receptores. Cada ruta necesita referirse a un receptor que ya ha sido configurado. Para obtener detalles sobre cómo configurar rutas, consulta {xref-monitoring-routes}[esta página.]

[#_advanced]
=== Avanzadas

Para más información sobre cómo editar directamente el recurso personalizado de Alertmanager, que puede ser útil en casos de uso avanzados, consulta {xref-configure-alertmanager}[esta página.]
