= {longhorn-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/longhorn/index.adoc 
:product-path: integrations/longhorn/longhorn.adoc

Longhorn ist ein offizielles https://cncf.io/[Projekt der Cloud Native Computing Foundation (CNCF)], das eine leistungsstarke cloudnativ verteilte Speicherplattform für Kubernetes bereitstellt, die überall betrieben werden kann. In Kombination mit Rancher erleichtert Longhorn die Bereitstellung von hochverfügbarem persistentem Blockspeicher in Ihrer Kubernetes-Umgebung, einfach, schnell und zuverlässig.

[#__longhorn_product_name_with_rancher]
== {longhorn-product-name} mit Rancher

Mit Rancher Prime und Longhorn können Benutzer einfach mit 1-Klick über den Rancher-Katalog bereitstellen und das Lebenszyklus-Management für verwaltete Cluster durchführen; dies ermöglicht dem Benutzer, zu installieren und ein Upgrade durchzuführen, zusammen mit der Entleerungsoperation für reibungslose Abläufe. Longhorn mit Rancher bietet auch Unterstützung für gemischte Cluster mit Windows, von Rancher gehosteten Bildern, UI-Proxy-Zugriff über Rancher und Rancher-Überwachung mit Longhorn-Metriken.
