= Cluster-Autoskalierer
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}

In diesem Abschnitt erfahren Sie, wie Sie den https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/[Kubernetes cluster-autoscaler] auf benutzerdefinierten Rancher-Clustern mit AWS EC2 Auto Scaling-Gruppen installieren und verwenden.

Der Cluster-Autoskalierer ist ein Tool, das die Größe des Kubernetes-Clusters automatisch anpasst, wenn eine der folgenden Bedingungen zutrifft:

* Es gibt Pods, die im Cluster aufgrund unzureichender Ressourcen nicht ausgeführt werden konnten.
* Es gibt Knoten im Cluster, die über einen längeren Zeitraum unterausgelastet waren und deren Pods auf anderen vorhandenen Knoten platziert werden können.

Um zu verhindern, dass Ihr Pod verdrängt wird, setzen Sie eine `priorityClassName: system-cluster-critical` Eigenschaft in Ihrer Pod-Spezifikation.

Cluster-Autoskalierer ist dafür ausgelegt, auf Kubernetes-Masterknoten zu laufen. Der Cluster-Autoskalierer kann im `kube-system` Namespace ausgeführt werden. Cluster-Autoskalierer skaliert keine Knoten mit nicht gespiegelten `kube-system` Pods, die auf ihnen laufen.

Es ist möglich, eine angepasste Implementierung des Cluster-Autoskalierers auf Arbeitsknoten auszuführen, aber es muss besondere Sorgfalt darauf verwendet werden, dass der Cluster-Autoskalierer betriebsbereit bleibt.

[#_cloud_providers]
== Cloud-Anbieter

Cluster-Autoskalierer bietet Unterstützung für verschiedene Cloud-Anbieter. Für weitere Informationen besuchen Sie https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#deployment[die vom Cluster-Autoskalierer unterstützten Cloud-Anbieter.]

[#_setting_up_cluster_autoscaler_on_amazon_cloud_provider]
=== Einrichten des Cluster-Autoskalierers auf dem Amazon Cloud Provider

Für Details zur Ausführung des Cluster-Autoskalierers auf dem Amazon Cloud Provider siehe xref:cluster-admin/manage-clusters/install-cluster-autoscaler/use-aws-ec2-auto-scaling-groups.adoc[diese Seite.]
