= Helm Version Requirements
:page-languages: [en, zh]
:revdate: 2026-04-21
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/helm-version-requirements.adoc 
:product-path: installation-and-upgrade/requirements/helm-version-requirements.adoc

This section contains the requirements for Helm, which is the tool used to install Rancher on a high-availability Kubernetes cluster.

____
The installation instructions have been updated for Helm 3. For migration of installs started with Helm 2, refer to the official https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/[Helm 2 to 3 Migration Docs.] xref:[This section] provides a copy of the older high-availability Rancher installation instructions that used Helm 2, and it is intended to be used if upgrading to Helm 3 is not feasible.
____

include::shared:ROOT:partial$en/deprecation-helm2.adoc[]

== Identifying the Proper Helm v3 Version

Select any Helm v3 version that is officially compatible with the Kubernetes version range you are using from our https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancher Support Matrix].

To apply this rule, you may need to reference two external resources:

* *Helm Version Compatibility:* Refer to the https://helm.sh/docs/topics/version_skew/[Helm Version Support Policy] and select the version matching the rule for your Rancher minor target.
* *Rancher’s Kubernetes Support Range:* Use the https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[Rancher Support Matrix] to identify the Kubernetes versions supported by your target Rancher minor version.

=== Example

* *Scenario:* You are targeting Rancher v2.10.8, which supports Kubernetes versions v1.28 through v1.31.
* *Application:* Our rule requires a Helm version that supports this range. You can verify this by checking the Helm version's compatibility with the highest version in the range, Kubernetes v1.31.
* *Result:* You find that Helm v3.16 support the Kubernetes v1.28-v1.31 range.
* We recommend Helm v3.16 because matches Rancher's range exactly. 

== Additional Notes

* Helm v3.2.x or higher is required to install or upgrade Rancher v2.5.
* Helm v2 support was removed in Rancher v2.9.x.
* When using tools that run Helm commands for you (like Terraform), you must make sure they are configured to use the correct Helm version.
