= Support Windows
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/fleet/windows-support.adoc 
:product-path: integrations/fleet/windows-support.adoc

Avant Rancher v2.5.6, le `agent` n'avait pas de manifestes Windows natifs sur les clusters en aval avec des nœuds Windows. Cela entraînerait un `agent` pod défaillant pour le cluster.

Si vous mettez à niveau à partir d'une version antérieure de Rancher vers v2.5.6+, vous pouvez déployer un `agent` fonctionnel avec le flux de travail suivant _dans le cluster en aval_{nbsp}:

. Cordonner tous les nœuds Windows.
. Appliquez la tolérance ci-dessous à la `agent` charge de travail.
. Décordonner tous les nœuds Windows.
. Supprimer tous les `agent` pods. De nouveaux pods devraient être créés avec la nouvelle tolérance.
. Une fois que les `agent` pods sont en cours d'exécution, et que la mise à jour automatique est activée pour Fleet, ils devraient être mis à jour vers une `agent` version compatible avec Windows.

[,yaml]
----
tolerations:
- effect: NoSchedule
  key: cattle.io/os
  operator: Equal
  value: linux
----
