= VMware vSphere環境に{rancher-product-name}をインストールする
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-server/on-premises-rancher-in-vsphere.adoc 
:product-path: installation-and-upgrade/best-practices/rancher-on-vsphere.adoc
ifeval::["{build-type}" != "community"]
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
endif::[]

このガイドでは、VMware vSphere環境におけるRKE KubernetesクラスターにRancherをインストールするためのリファレンスアーキテクチャを概説します。また、VMwareによって文書化された標準的なvSphereのベストプラクティスについても説明します。

.ソリューションの概要
image::rancher-on-prem-vsphere.svg[ソリューションの概要]

[#_1_load_balancer_considerations]
== 1.ロードバランサーの考慮事項

RKEノードに存在するRancherワークロードにトラフィックを誘導するために、ロードバランサーが必要です。

[#_leverage_fault_tolerance_and_high_availability]
=== 耐障害性と高可用性を活用する

高可用性機能（F5、NSX-T、Keepalivedなど）を持つ外部（ハードウェアまたはソフトウェア）ロードバランサーを利用してください。

[#_back_up_load_balancer_configuration]
=== ロードバランサー設定のバックアップ

災害復旧活動が発生した場合、ロードバランサー設定の可用性は回復プロセスを迅速化します。

[#_configure_health_checks]
=== ヘルスチェックの設定

ヘルスチェックが失敗した場合にノードを自動的に利用不可としてマークするようにロードバランサーを設定します。例えば、NGINXはこれを次のように実現できます：

`max_fails=3 fail_timeout=5s`

[#_leverage_an_external_load_balancer]
=== 外部ロードバランサーを活用する

管理クラスター内にソフトウェアロードバランサーを実装することは避けてください。

[#_secure_access_to_rancher]
=== Rancherへのアクセスを保護する

Rancherへのアクセスのみを許可するように、適切なファイアウォールやACLルールを設定してください。

[#_2_vm_considerations]
== 2.VMの考慮事項

[#_size_the_vms_according_to_rancher_documentation]
=== Rancherのドキュメントに従ってVMのサイズを設定する

{xref-install-reqs}[インストール要件]を参照してください。

[#_leverage_vm_templates_to_construct_the_environment]
=== VMテンプレートを活用して環境を構築する

環境全体で展開される仮想マシンの一貫性を促進するために、VMテンプレートの形でゴールデンイメージの使用を検討してください。これを達成するためにPackerを使用することができ、より多くのカスタマイズオプションを追加します。

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_rancher_cluster_nodes_across_esxi_hosts]
=== DRSアンチアフィニティルール（可能な場合）を活用して、RancherクラスターのノードをESXiホスト間で分離する

これにより、ノードVMが複数のESXiホストに分散され、ホストレベルでの単一障害点を防ぐことができます。

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_rancher_cluster_nodes_across_datastores]
=== DRSアンチアフィニティルール（可能な場合）を活用して、Rancherクラスターのノードをデータストア間で分離する

これにより、ノードVMが複数のデータストアに分散され、データストアレベルでの単一障害点を防ぐことができます。

[#_configure_vms_as_appropriate_for_kubernetes]
=== Kubernetesに適したVMを構成する

ノードを展開する際には、スワップを無効にし、クラスター内のすべてのマシン間で完全なネットワーク接続があることを再確認し、各ノードに対してユニークなホスト名、MACアドレス、およびproduct_uuidを使用するなど、K8sおよびetcdのベストプラクティスに従うことが重要です。

[#_3_network_considerations]
== 3.ネットワークの考慮事項

[#_leverage_low_latency_high_bandwidth_connectivity_between_etcd_nodes]
=== ETCDノード間の低遅延、高帯域幅の接続を活用する

可能な限り、単一のデータセンター内にETCDメンバーをデプロイすることで、遅延オーバーヘッドを回避し、ネットワーク分割の可能性を減らします。ほとんどのセットアップでは、1Gbの接続で十分です。大規模なクラスターの場合、10Gbの接続によりバックアップからの復元にかかる時間を短縮できます。

[#_consistent_ip_addressing_for_vms]
=== VMの一貫したIPアドレス設定

使用する各ノードには静的IPが設定されている必要があります。DHCPの場合、各ノードにはDHCP予約が必要で、ノードが同じIPを割り当てられることを確認します。

[#_4_storage_considerations]
== 4.ストレージの考慮事項

[#_leverage_ssd_drives_for_etcd_nodes]
=== ETCDノードにSSDドライブを活用する

ETCDは書き込み遅延に非常に敏感です。したがって、可能な限りSSDを活用してください。

[#_5_backups_and_disaster_recovery]
== 5.バックアップと災害復旧

[#_perform_regular_management_cluster_backups]
=== 定期的な管理クラスターのバックアップを実施してください。

Rancherは、存在するKubernetesクラスターのETCDデータストアにデータを保存します。他のKubernetesクラスターと同様に、このクラスターの頻繁でテスト済みのバックアップを実施してください。

[#_back_up_rancher_cluster_node_vms]
=== RancherクラスターのノードVMをバックアップしてください。

標準のVMバックアップポリシーにRancher管理ノードVMを組み込んでください。
