= Clusterwerkzeuge für Protokollierung, Überwachung und Einblick
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/rancher-cluster-tools.adoc 
:product-path: observability/rancher-cluster-tools.adoc
ifeval::["{build-type}" != "community"]
:xref-istio: xref:observability/istio/istio.adoc
:xref-monitoring-and-dashboards: xref:observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:xref-logging: xref:observability/logging/logging.adoc
:xref-compliance-scans-howto: xref:security/compliance-scans/how-to.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio: xref:integrations-in-rancher/istio/index.adoc
:xref-monitoring-and-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/index.adoc
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
:xref-compliance-scans-howto: xref:how-to-guides/advanced-user-guides/compliance-scan-guides/index.adoc
endif::[]

Rancher enthält eine Vielzahl von Werkzeugen, die nicht in Kubernetes enthalten sind, um Ihre DevOps-Operationen zu unterstützen. Rancher kann mit externen Diensten integriert werden, um einen effizienteren Betrieb Ihrer Cluster zu ermöglichen. Werkzeuge werden in folgende Kategorien unterteilt:

[#_logging]
== Protokollierung

Protokollierung ist hilfreich, weil sie es Ihnen ermöglicht:

* Den Zustand Ihres Clusters zu erfassen und zu analysieren
* Nach Trends in Ihrer Umgebung zu suchen
* Ihre Protokolle an einem sicheren Ort außerhalb Ihres Clusters zu speichern
* Über Ereignisse wie einen Containerabsturz, eine Pod-Evakuierung oder einen Ausfall eines Knotens informiert zu bleiben
* Probleme leichter zu debuggen und zu beheben

Rancher kann mit Elasticsearch, Splunk, Kafka, Syslog und Fluentd integriert werden.

Für weitere Informationen verweisen Sie auf die Protokolldokumentation {xref-logging}[hier.]

[#_monitoring_and_alerts]
== Überwachung und Warnungen

Mit Rancher können Sie den Zustand und die Prozesse Ihrer Clusterknoten, Kubernetes-Komponenten und Software-Implementierungen durch die Integration mit https://prometheus.io/[Prometheus], einer führenden Open-Source-Überwachungslösung, überwachen.

Nachdem die Überwachung aktiviert ist, können Sie Warnungen und Benachrichtigungen einrichten, die den Mechanismus bereitstellen, um sie zu empfangen.

Benachrichtigungsdienste sind Dienste, die Sie über Alarmereignisse informieren. Sie können Benachrichtigungsdienste so konfigurieren, dass sie Alarmbenachrichtigungen an das Personal senden, das am besten geeignet ist, um Korrekturmaßnahmen zu ergreifen. Benachrichtigungen können über Slack, E-Mail, PagerDuty, WeChat und Webhooks gesendet werden.

Warnungen sind Regeln, die diese Benachrichtigungen auslösen. Bevor Sie Warnungen empfangen können, müssen Sie einen oder mehrere Benachrichtigungsdienste in Rancher konfigurieren. Der Umfang für Warnungen kann entweder auf Cluster- oder Projektebene festgelegt werden.

Für weitere Informationen verweisen Sie auf die Überwachungsdokumentation {xref-monitoring-and-dashboards}[hier.]

[#_istio]
== Istio

https://istio.io/[Istio] ist ein Open Source-Tool, das es DevOps-Teams erleichtert, den Datenverkehr innerhalb eines komplexen Netzwerks von Mikrodiensten zu überwachen, zu steuern, Fehler zu beheben und abzusichern.

Die Integration von Rancher mit Istio wurde in Rancher v2.5 verbessert.

Für weitere Informationen verweisen Sie auf die Istio-Dokumentation {xref-istio}[hier.]

[#_compliance_scans]
== Compliance-Scans

Rancher kann einen Sicherheits-Scan durchführen, um zu überprüfen, ob Kubernetes gemäß den Sicherheitsbestimmungen, die in den am meisten anerkannten Kubernetes-Sicherheitsbenchmarks definiert sind, bereitgestellt wurde, wie z.B. STIG.

Für weitere Informationen verweisen Sie auf die Dokumentation zum Compliance-Scan {xref-compliance-scans-howto}[hier.]
