= Projektwerkzeuge für Protokollierung, Überwachung und Einblick
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/rancher-project-tools.adoc 
:product-path: observability/rancher-project-tools.adoc
ifeval::["{build-type}" != "community"]
:xref-monitoring-and-dashboards: xref:observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:xref-logging: xref:observability/logging/logging.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-monitoring-and-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/index.adoc
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
endif::[]

Rancher enthält eine Vielzahl von Werkzeugen, die nicht in Kubernetes enthalten sind, um Ihre DevOps-Operationen zu unterstützen. Rancher kann mit externen Diensten integriert werden, um einen effizienteren Betrieb Ihrer Cluster zu ermöglichen.

[#_notifiers_and_alerts]
== Benachrichtigungsdienste und Warnungen

Benachrichtigungsdienste und Warnungen sind zwei Funktionen, die zusammenarbeiten, um Sie über Ereignisse im Rancher-System zu informieren. Bevor sie aktiviert werden können, muss die Überwachungsanwendung installiert werden.

Benachrichtigungsdienste sind Dienste, die Sie über Alarmereignisse informieren. Sie können Benachrichtigungsdienste so konfigurieren, dass sie Alarmbenachrichtigungen an das Personal senden, das am besten geeignet ist, um Korrekturmaßnahmen zu ergreifen. Benachrichtigungen können über Slack, E-Mail, PagerDuty, WeChat und Webhooks gesendet werden.

Warnungen sind Regeln, die diese Benachrichtigungen auslösen. Bevor Sie Warnungen empfangen können, müssen Sie einen oder mehrere Benachrichtigungsdienste in Rancher konfigurieren. Der Umfang für Warnungen kann entweder auf Cluster- oder Projektebene festgelegt werden.

[#_logging]
== Protokollierung

Protokollierung ist hilfreich, weil sie es Ihnen ermöglicht:

* Den Zustand Ihres Clusters zu erfassen und zu analysieren
* Nach Trends in Ihrer Umgebung zu suchen
* Ihre Protokolle an einem sicheren Ort außerhalb Ihres Clusters zu speichern
* Über Ereignisse wie einen Containerabsturz, eine Pod-Evakuierung oder einen Ausfall eines Knotens informiert zu bleiben
* Probleme leichter zu debuggen und zu beheben

Rancher kann mit Elasticsearch, Splunk, Kafka, Syslog und Fluentd integriert werden.

Für Details, siehe den {xref-logging}[Protokollierungsabschnitt.]

[#_monitoring]
== Überwachung

Mit Rancher können Sie den Zustand und die Prozesse Ihrer Clusterknoten, Kubernetes-Komponenten und Software-Implementierungen durch die Integration mit https://prometheus.io/[Prometheus], einer führenden Open-Source-Überwachungslösung, überwachen. Für Details, siehe den {xref-monitoring-and-dashboards}[Überwachungsabschnitt.]
