= AWS Marketplace-Integration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/index.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/aws.adoc
ifeval::["{build-type}" != "community"]
:xref-aws-cloud-marketplace-adapter-reqs: xref:installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/adapter-requirements.adoc
:xref-aws-cloud-marketplace-install-adapter: xref:installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-aws-cloud-marketplace-adapter-reqs: xref:integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/adapter-requirements.adoc
:xref-aws-cloud-marketplace-install-adapter: xref:integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.adoc
endif::[]

[#_overview]
== Übersicht

Rancher bietet eine Integration mit dem AWS Marketplace an, die es Benutzern ermöglicht, einen Supportvertrag mit SUSE zu erwerben. Diese Integration ermöglicht es Ihnen, Ihre Supportbedürfnisse einfach anzupassen, während Sie beginnen, mehr Cluster zu unterstützen.

[#_limitations]
== Nutzungsbeschränkungen

* Sie müssen Rancher v2.6.7 oder höher ausführen.
* Rancher muss mit aktivierten zusätzlichen Metriken bereitgestellt werden.
* Rancher muss auf einem EKS-Cluster installiert sein.
* Sie müssen mindestens ein Anrecht auf Rancher-Support über den AWS Marketplace erwerben.
* Möglicherweise benötigen Sie zusätzliches setup, um Proxy-/Airgap-Anwendungsfälle zu unterstützen. Siehe die {xref-aws-cloud-marketplace-adapter-reqs}[Voraussetzungen] für weitere Informationen.

[#_how_to_use]
== Anleitung

. Vervollständigen Sie die {xref-aws-cloud-marketplace-adapter-reqs}[Voraussetzungsschritte].
. {xref-aws-cloud-marketplace-install-adapter}[Installieren Sie den CSP-Adapter].

[#_faq]
== FAQ

*Kann ich später Support für mehr Knoten erwerben?*

Ja. Gehen Sie einfach zu dem Eintrag im AWS Marketplace, den Sie ursprünglich zum Kauf des Supports verwendet haben, und erhöhen Sie die Anzahl der Anrechte.

*Kann ich mehrere Instanzen von Rancher im selben AWS-Konto verwenden?*

Ja. Jeder Cluster, in dem Rancher installiert ist, muss jedoch die Voraussetzungen einhalten.

Darüber hinaus sollten Sie beachten, dass ein bestimmtes Anrecht nur von einem Rancher-Managementserver gleichzeitig verwendet werden kann.
