= Allgemeine Probleme
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/common-issues.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/common-issues.adoc
ifeval::["{build-type}" != "community"]
:xref-aws-cloud-marketplace-adapter-reqs: xref:installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/adapter-requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-aws-cloud-marketplace-adapter-reqs: xref:integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/adapter-requirements.adoc
endif::[]

*Nach der Installation des Adapters erscheint in Rancher eine Banner-Nachricht mit dem Text "AWS Marketplace Adapter: Der Adapter kann nicht ausgeführt werden, bitte überprüfen Sie die Protokolle des Adapters"*

Dieser Fehler zeigt an, dass der Adapter zwar in den Cluster installiert wurde, jedoch ein Fehler aufgetreten ist, der verhindert, dass er Lizenzen ordnungsgemäß eincheckt/auscheckt.

Dies geschieht häufig, weil die IAM-Rolle nicht richtig eingerichtet wurde. Überprüfen Sie die {xref-aws-cloud-marketplace-adapter-reqs}[Voraussetzungen] und vergewissern Sie sich, dass:

* Ein OIDC-Anbieter wurde erstellt bzw. dem Cluster zugeordnet, auf dem Rancher läuft.
* Die IAM-Rolle wurde so konfiguriert, dass sie diesem OIDC-Anbieter vertraut.
* Die IAM-Rolle verfügt mindestens über die in der Richtlinie beschriebenen Berechtigungen.

Wenn all dies korrekt konfiguriert wurde, wenden Sie sich an den Support, um Unterstützung zu erhalten.

*Ich sehe eine Banner-Nachricht, die besagt: "AWS Marketplace Adapter: Sie haben Ihre lizenzierte Knotenzahl überschritten. Mindestens x weitere Lizenz(en) sind in AWS erforderlich, um konform zu werden"*

Diese Nachricht zeigt an, dass Sie nicht genügend Berechtigungen für die Anzahl der Knoten haben, die Rancher derzeit verwaltet.

Beachten Sie die folgenden Einschränkungen:

* Jede Berechtigung ist für eine bestimmte Anzahl von Knoten gültig.
* Jeder Knoten, der derzeit von Rancher verwaltet wird, zählt zu Ihrer Gesamtnutzung (mit Ausnahme der Knoten im Cluster, auf dem Rancher installiert ist).
* Jede Berechtigung kann von höchstens einer Rancher-Instanz verwendet werden. Wenn Sie beispielsweise zwei laufende Rancher-Instanzen in Ihrem Konto haben (jede auf einem separaten EKS-Cluster installiert), benötigen Sie mindestens zwei Berechtigungen.

Möglicherweise haben Sie den Adapter auch kürzlich deinstalliert/wieder installiert. Wenn der Adapter den Überblick über die Lizenzen verliert, die er derzeit verwaltet, kann es bis zu einer Stunde dauern, um den tatsächlichen Zustand der Lizenzen zu ermitteln.
