= 認可されたクラスターエンドポイントの動作について
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc 
:product-path: cluster-admin/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
endif::[]

このセクションでは、kubectl CLI、kubeconfigファイル、および認可されたクラスターエンドポイントがどのように連携して、Rancherサーバーを介さずにダウンストリームKubernetesクラスターに直接アクセスできるかを説明します。これは、{xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[クラスターに直接アクセスするためのkubectlの設定方法]に関する指示の背景情報と文脈を提供することを目的としています。

[#_about_the_kubeconfig_file]
== Kubeconfigファイルについて

kubeconfigファイルは、kubectlコマンドラインツール（または他のクライアント）と併用してKubernetesへのアクセスを構成するために使用されます。

kubeconfigファイルとその内容は、各クラスターに特有のものです。これは、Rancherの*Clusters*ページからダウンロードできます。

. 左上隅の*☰*をクリックします。
. *クラスター管理*を選択します。
. ダウンロードしたいkubeconfigを持つクラスターを見つけ、行の最後にある*⁝*を選択します。
. サブメニューから*Download KubeConfig*を選択します。

Rancherでアクセスできる各クラスターには、別々のkubeconfigファイルが必要です。

kubeconfigファイルをダウンロードした後、kubeconfigファイルとそのKubernetes https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration[contexts]を使用してダウンストリームクラスターにアクセスできるようになります。

管理者がxref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[kubeconfigトークン生成を無効にしている場合]、kubeconfigファイルには{xref-rancher-cli}[Rancher CLI]がPATHに存在する必要があります。

[#_about_the_kube_api_auth_authentication_webhook]
== kube-api-auth認証Webhookについて

`kube-api-auth`マイクロサービスは、{xref-arch-com-ds-cluster}#_4_authorized_cluster_endpoint[認可されたクラスターエンドポイント]のユーザー認証機能を提供するためにデプロイされています。`kubectl`を使用してユーザークラスターにアクセスすると、クラスターのKubernetes APIサーバーは`kube-api-auth`サービスをウェブフックとして使用してあなたを認証します。

クラスターのプロビジョニング中に、ファイル`/etc/kubernetes/kube-api-authn-webhook.yaml`がデプロイされ、`kube-apiserver`が`--authentication-token-webhook-config-file=/etc/kubernetes/kube-api-authn-webhook.yaml`で構成されます。これにより、`kube-apiserver`が`http://127.0.0.1:6440/v1/authenticate`にクエリを送信してベアラートークンの認証を決定します。

`kube-api-auth`のスケジューリングルールは以下の通りです：

|===
| コンポーネント | nodeAffinity nodeSelectorTerms | nodeSelector | トレランス

| kube-api-auth
| `beta.kubernetes.io/os:NotIn:windows`
`node-role.kubernetes.io/controlplane:In:"true"`
| none
| `operator:Exists`
|===
