= {rancher-product-name} Servidor y Componentes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: reference-guides/rancher-manager-architecture/rancher-server-and-components.adoc 
:product-path: about-rancher/architecture/rancher-server-and-components.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-hosted-k8s-clusters: xref:guías-de-instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configurar-clusters-a-partir-de-proveedores-kubernetes-alojados/index.adoc
:xref-migrate-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster.adoc
endif::[]

La mayoría del software de Rancher 2.x se ejecuta en el Servidor Rancher. El Servidor Rancher incluye todos los componentes de software utilizados para gestionar todo el despliegue de Rancher.

El diagrama a continuación ilustra la arquitectura de alto nivel de Rancher 2.x. La figura representa una instalación del Servidor Rancher que gestiona dos clústeres de Kubernetes en sentido descendente: uno creado por RKE2 y otro creado por Amazon EKS (Elastic Kubernetes Service).

Para el mejor rendimiento y seguridad, recomendamos un clúster de Kubernetes dedicado para el servidor de gestión de Rancher. No se aconseja ejecutar cargas de trabajo de usuarios en este clúster. Después de desplegar Rancher, puedes {xref-cluster-deployment}[crear o importar clústeres] para ejecutar tus cargas de trabajo.

El diagrama muestra cómo los usuarios pueden manipular tanto los clústeres de Kubernetes {xref-launch-k8s-with-rancher}[lanzados por Rancher] como los clústeres de Kubernetes {xref-hosted-k8s-clusters}[alojados] a través del proxy de autenticación de Rancher:

.Gestión de Clústeres de Kubernetes a través del Proxy de Autenticación de Rancher
image::rancher-architecture-rancher-api-server.svg[Arquitectura]

Puedes instalar Rancher en un solo nodo, o en un clúster de Kubernetes de alta disponibilidad.

Se recomienda una instalación de Kubernetes de alta disponibilidad para producción.

Una instalación de Docker de Rancher se recomienda solo para desarrollo y pruebas. La capacidad de migrar Rancher a un clúster de alta disponibilidad depende de la versión de Rancher.

Para ver los recursos desplegados, ejecuta el siguiente comando:

[,bash]
----
kubectl get all -n <namespace>
----

Si tienes privilegios de administrador, también puedes ver estos recursos listados en la interfaz de usuario de Rancher:

. Haz clic en *☰* y selecciona un clúster.
. Selecciona *Más Recursos* en el menú de navegación lateral para ver los recursos desplegados por tipo.
. Selecciona *Clúster* > *Proyectos/Espacios de nombres* en el menú de navegación lateral, luego selecciona un espacio de nombres para ver los recursos desplegados por espacio de nombres.
El operador de copia de seguridad de Rancher se puede utilizar para migrar Rancher de la instalación de un solo contenedor de Docker a una instalación en un clúster de Kubernetes de alta disponibilidad. Para más detalles, consulta la documentación sobre {xref-migrate-cluster}[migrar Rancher a un nuevo clúster].

El servidor de Rancher, independientemente del método de instalación, siempre debe ejecutarse en nodos que estén separados de los clústeres de usuarios en sentido descendente que gestiona. Si Rancher está instalado en un clúster de Kubernetes de alta disponibilidad, debe ejecutarse en un clúster separado de los clústeres que gestiona.
