= 启用实验性功能
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-22
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc 
:product-path: rancher-admin/experimental-features/experimental-features.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap-rancher-ha: xref:installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc
:xref-unsupported-storage-drivers: xref:rancher-admin/experimental-features/unsupported-storage-drivers.adoc
:xref-feature-flags: xref:installation-and-upgrade/references/feature-flags.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap-rancher-ha: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha.adoc
:xref-unsupported-storage-drivers: xref:how-to-guides/advanced-user-guides/enable-experimental-features/unsupported-storage-drivers.adoc
:xref-feature-flags: xref:getting-started/installation-and-upgrade/installation-references/feature-flags.adoc
endif::[]

Rancher 包含一些实验性功能，默认情况下是禁用的。如果您认为使用 {xref-unsupported-storage-drivers}[不受支持的存储类型] 的好处超过使用未经过测试的功能的风险，您可能想要启用这些功能。引入功能标志是为了让您尝试这些默认情况下未启用的功能。

可以通过三种方式启用这些功能：

* <<_enabling_features_when_starting_rancher,在启动 Rancher 时启用功能。>>使用 CLI 安装 Rancher 时，您可以使用功能标志默认启用某个功能。
* <<_enabling_features_with_the_rancher_ui,从 Rancher UI 启用功能>>，方法是前往 *设置* 页面。
* <<_enabling_features_with_the_rancher_api,通过 Rancher API 启用功能>>，请在安装 Rancher 后执行。

每个功能都有两个值：

* 一个默认值，可以通过命令行的功能标志或环境变量进行配置
* 一个设置值，可以通过 Rancher API 或 UI 进行配置

如果没有设置值，Rancher 将使用默认值。

因为 API 设置实际值，而命令行设置默认值，这意味着如果您通过 API 或 UI 启用或禁用某个功能，它将覆盖通过命令行设置的任何值。

例如，如果您安装 Rancher，然后通过 Rancher API 将功能标志设置为 true，再通过一个将功能标志设置为 false 的命令升级 Rancher，默认值仍然是 false，但该功能仍然会启用，因为它是通过 Rancher API 设置的。如果您随后通过 Rancher API 删除设置值（true），将其设置为 NULL，默认值（false）将生效。有关更多信息，请参见 {xref-feature-flags}[功能标志页面]。

[#_enabling_features_when_starting_rancher]
== 在启动 Rancher 时启用功能

安装 Rancher 时，通过功能标志启用您想要的功能。该命令因您是在单节点上安装 Rancher 还是进行 Kubernetes 安装而有所不同。

[#_enabling_features_for_kubernetes_installs]
=== 为 Kubernetes 安装启用功能

[NOTE]
====

从 Rancher API 设置的值将覆盖通过命令行传递的值。
====


使用 Helm 图表安装 Rancher 时，请使用 `--set` 选项。在下面的示例中，通过传递以逗号分隔的功能标志名称启用了两个功能：

[,shell,subs="attributes+"]
----
helm install rancher {rancher-helm-repo}/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set 'extraEnv[0].name=CATTLE_FEATURES'
  --set 'extraEnv[0].value=<FEATURE-FLAG-NAME-1>=true,<FEATURE-FLAG-NAME-2>=true'
----

[#_enabling_features_for_air_gap_installs]
=== 为隔离安装启用功能

要执行 {xref-air-gap-rancher-ha}[Rancher 的隔离安装]，请添加 Helm 图表储存库并下载 Helm 图表，然后使用 Helm 安装 Rancher。

安装 Helm 图表时，您应以逗号分隔的列表传递功能标志名称，如以下示例所示：

----
helm install rancher ./rancher-<VERSION>.tgz \
  --namespace cattle-system 
  --set hostname=<RANCHER.YOURDOMAIN.COM> \
  --set image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
  --set ingress.tls.source=secret \
  --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ # Set a default private registry to be used in Rancher
  --set useBundledSystemChart=true # Use the packaged Rancher system charts
  --set 'extraEnv[0].name=CATTLE_FEATURES'
  --set 'extraEnv[0].value=<FEATURE-FLAG-NAME-1>=true,<FEATURE-FLAG-NAME-2>=true'
----

[#_enabling_features_for_docker_installs]
=== 为 Docker 安装启用功能

使用 Docker 安装 Rancher 时，请使用 `--features` 选项。在下面的示例中，通过传递以逗号分隔的功能标志名称启用了两个功能：

----
docker run -d -p 80:80 -p 443:443 \
  --restart=unless-stopped \
  rancher/rancher:rancher-latest \
  --features=<FEATURE-FLAG-NAME-1>=true,<FEATURE-FLAG-NAME-2>=true
----

[#_enabling_features_with_the_rancher_ui]
== 通过 Rancher UI 启用功能

. 在左上角，点击 *☰ > 全局设置*。
. 点击 *功能标志*。
. 要启用某个功能，请转到您想启用的已禁用的功能，然后点击 *⋮ > 激活*。

*结果：*该功能已启用。

[#_disabling_features_with_the_rancher_ui]
=== 通过 Rancher UI 禁用功能

. 在左上角，点击 *☰ > 全局设置*。
. 点击 *功能标志*。您将看到一个实验性功能的列表。
. 要禁用某个功能，请转到您想要禁用的已启用功能，然后点击 *⋮ > 禁用*。

*结果：*该功能已禁用。

[#_enabling_features_with_the_rancher_api]
== 通过 Rancher API 启用功能

. 其网址为 `<RANCHER-SERVER-URL>/v3/features`。
. 在 `data` 部分，您将看到一个数组，其中包含所有可以通过功能标志开启的功能。该功能的名称在 `id` 字段中。单击您想要启用的功能名称。
. 在屏幕左上角，点击 *操作* 下的 *编辑*。
. 在 *值* 下拉菜单中，单击 *真*。
. 单击 *显示请求*。
. 单击 *发送请求*。
. 单击 *关闭*。

*结果：*该功能已启用。

[#_disabling_features_with_the_rancher_api]
=== 通过 Rancher API 禁用功能

. 其网址为 `<RANCHER-SERVER-URL>/v3/features`。
. 在 `data` 部分，您将看到一个数组，其中包含所有可以通过功能标志开启的功能。该功能的名称在 `id` 字段中。单击您想要禁用的功能名称。
. 在屏幕左上角，点击 *操作* 下的 *编辑*。
. 在 *值* 下拉菜单中，单击 *假*。
. 单击 *显示请求*。
. 单击 *发送请求*。
. 单击 *关闭*。

*结果：*该功能已禁用。
