= Application des modèles
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/nouveaux-utilisateurs/authentification-autorisations-et-global-configuration/a-propos-des-modèles-rke1/appliquer-les-modèles.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/enforce-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc 
:xref-manage-rke1-templates: xref:guides-pratiques/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/gérer-les-modèles-rke1.adoc
endif::[]

Cette section décrit comment les administrateurs de modèles peuvent imposer des modèles dans Rancher, restreignant la capacité des utilisateurs à créer des clusters sans modèle.

Par défaut, tout utilisateur standard dans Rancher peut créer des clusters. Mais lorsque l'application des modèles RKE est activée,

* Seul un administrateur a la capacité de créer des clusters sans modèle.
* Tous les utilisateurs standard doivent utiliser un modèle RKE pour créer un nouveau cluster.
* Les utilisateurs standard ne peuvent pas créer un cluster sans utiliser un modèle.

Les utilisateurs ne peuvent créer de nouveaux modèles que si l'administrateur xref:./creator-permissions.adoc#_allowing_a_user_to_create_templates[leur donne la permission.]

Après qu'un cluster a été créé avec un modèle RKE, le créateur du cluster ne peut pas modifier les paramètres définis dans le modèle. La seule façon de changer ces paramètres après la création du cluster est de xref:./apply-templates.adoc#_updating_a_cluster_created_with_an_rke_template[mettre à niveau le cluster vers une nouvelle révision] du même modèle. Si les créateurs de clusters souhaitent modifier les paramètres définis par le modèle, ils doivent contacter le propriétaire du modèle pour obtenir une nouvelle révision du modèle. Pour des détails sur le fonctionnement des révisions de modèles, consultez la {xref-manage-rke1-templates}#_mise_à_jour_d'un_modèle[documentation sur la révision des modèles.]

[#_requiring_new_clusters_to_use_an_rke_template]
== Exiger que les nouveaux clusters utilisent un modèle RKE

Vous pourriez vouloir exiger que les nouveaux clusters utilisent un modèle pour garantir que tout cluster lancé par un {xref-global-permissions}[utilisateur standard] utilisera les paramètres Kubernetes et/ou Rancher qui ont été validés par les administrateurs.

Pour exiger que les nouveaux clusters utilisent un modèle RKE, les administrateurs peuvent activer l'application des modèles RKE avec les étapes suivantes{nbsp}:

. Cliquez sur *☰ > Paramètres globaux*.
. Accédez au `cluster-template-enforcement` paramètre. Cliquez sur *⋮ > Modifier le paramètre*.
. Définissez la valeur sur *True* et cliquez sur *Enregistrer*.
+

[NOTE]
.Important :
====
Lorsque l'administrateur définit le `cluster-template-enforcement` sur *True*, il doit également partager le `clusterTemplates` avec les utilisateurs afin que ceux-ci puissent sélectionner l'un de ces modèles pour créer le cluster.
====


*Résultat :* Tous les clusters provisionnés par Rancher doivent utiliser un modèle, sauf si le créateur est un administrateur.

[#_disabling_rke_template_enforcement]
== Désactivation de l'application des modèles RKE

Pour permettre la création de nouveaux clusters sans un modèle RKE, les administrateurs peuvent désactiver l'application des modèles RKE en suivant les étapes suivantes{nbsp}:

. Cliquez sur *☰ > Paramètres globaux*.
. Accédez au `cluster-template-enforcement` paramètre. Cliquez sur *⋮ > Modifier le paramètre*.
. Définissez la valeur sur *False* et cliquez sur *Enregistrer*.

*Résultat :* Lorsque des clusters sont provisionnés par Rancher, ils n'ont pas besoin d'utiliser un modèle.
