= Surcharge des paramètres de modèle
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/override-template-settings.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/override-template-settings.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rke1-templates: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/manage-rke1-templates.adoc
endif::[]

Lorsqu'un utilisateur crée un modèle RKE, chaque paramètre du modèle dispose d'un interrupteur dans l'interface utilisateur de Rancher qui indique si les utilisateurs peuvent remplacer le paramètre. Cet interrupteur marque ces paramètres comme *Autoriser le remplacement par l'utilisateur*.

Après qu'un cluster a été créé avec un modèle, les utilisateurs finaux ne peuvent pas mettre à jour les paramètres définis dans le modèle à moins que le propriétaire du modèle ne les ait marqués comme *Autoriser le remplacement par l'utilisateur*. Cependant, si le modèle est {xref-manage-rke1-templates}[mis à jour vers une nouvelle révision] qui modifie les paramètres ou permet aux utilisateurs finaux de les changer, le cluster peut être mis à niveau vers une nouvelle révision du modèle et les modifications de la nouvelle révision seront appliquées au cluster.

Lorsque n'importe quel paramètre est défini comme *Autoriser le remplacement par l'utilisateur* sur le modèle RKE, cela signifie que les utilisateurs finaux doivent remplir ces champs lors de la création du cluster et qu'ils peuvent modifier ces paramètres par la suite à tout moment.

L’option *Autoriser le remplacement par l'utilisateur* du modèle RKE est utile dans des situations telles que{nbsp}:

* Les administrateurs savent que certains paramètres nécessiteront la flexibilité d'être fréquemment mis à jour au fil du temps
* Les utilisateurs finaux devront entrer leurs propres clés d'accès ou clés secrètes, par exemple, des identifiants cloud ou des identifiants pour des instantanés de sauvegarde
