= À propos des modèles RKE1
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/index.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/rke1-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-rke1-template-example-yaml: xref:rancher-admin/global-configuration/rke1-templates/template-example-yaml.adoc
:xref-rke1-template-infrastructure: xref:rancher-admin/global-configuration/rke1-templates/infrastructure.adoc
:xref-rke1-creator-permissions: xref:rancher-admin/global-configuration/rke1-templates/creator-permissions.adoc
:xref-cluster-templates: xref:cluster-admin/manage-clusters/cluster-templates.adoc
:xref-rke1-template-example-use-cases: xref:rancher-admin/global-configuration/rke1-templates/example-use-cases.adoc
:xref-rke1-template-override-settings: xref:rancher-admin/global-configuration/rke1-templates/override-template-settings.adoc
:xref-rke1-template-apply: xref:rancher-admin/global-configuration/rke1-templates/apply-templates.adoc
:xref-rke1-template-enforce: xref:rancher-admin/global-configuration/rke1-templates/enforce-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rke1-templates: xref:guides-pratiques/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/gérer-les-modèles-rke1.adoc
:xref-access-share-rke1-templates: xref:guides-pratiques/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/accéder-ou-partager-les-modèles.adoc
:xref-rke1-template-example-yaml: xref:reference-guides/rke1-template-example-yaml.adoc
:xref-rke1-template-infrastructure: xref:how-to-guides/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/infrastructure.adoc
:xref-rke1-creator-permissions: xref:guides-pratiques/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/permissions-du-créateur.adoc
:xref-cluster-templates: xref:how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc
:xref-rke1-template-example-use-cases: xref:how-to-guides/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/cas-d'utilisation-exemples.adoc
:xref-rke1-template-override-settings: xref:how-to-guides/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/remplacer-les-paramètres-du-modèle.adoc
:xref-rke1-template-apply: xref:guides-pratiques/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/appliquer-les-modèles.adoc
:xref-rke1-template-enforce: how-to-guides/nouveaux-utilisateurs/authentification-autorisations-et-configuration-globale/a-propos-des-modèles-rke1/imposer-des-modèles.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

Les modèles RKE sont conçus pour permettre aux équipes DevOps et de sécurité de standardiser et de simplifier la création de clusters Kubernetes.

RKE est le https://rancher.com/docs/rke/latest/en/[Rancher Kubernetes Engine,] qui est l'outil que Rancher utilise pour provisionner des clusters Kubernetes.

Avec la popularité croissante de Kubernetes, il y a une tendance à gérer un plus grand nombre de petits clusters. Lorsque vous souhaitez créer de nombreux clusters, il est plus important de les gérer de manière cohérente. La gestion multi-clusters présente des défis pour l'application des règles de sécurité et des configurations de produits complémentaires qui doivent être standardisées avant de remettre les clusters aux utilisateurs finaux.

Les modèles RKE aident à standardiser ces configurations. Que les clusters soient créés avec l'interface utilisateur de Rancher, l'API de Rancher ou un processus automatisé, Rancher garantira que chaque cluster qu'il provisionne à partir d'un modèle RKE est uniforme et cohérent dans sa production.

Les administrateurs contrôlent quelles options de cluster peuvent être modifiées par les utilisateurs finaux. Les modèles RKE peuvent également être partagés avec des utilisateurs et des groupes spécifiques, afin que les administrateurs puissent créer différents modèles RKE pour différents ensembles d'utilisateurs.

Si un cluster a été créé avec un modèle RKE, vous ne pouvez pas le changer pour un autre modèle RKE. Vous ne pouvez mettre à jour le cluster qu'à une nouvelle révision du même modèle.

Vous pouvez {xref-rke1-template-apply}#_converting_an_existing_cluster_to_use_an_rke_template[sauvegarder la configuration d'un cluster existant en tant que modèle RKE.] Ensuite, les paramètres du cluster ne peuvent être modifiés que si le modèle est mis à jour. Le nouveau modèle peut également être utilisé pour lancer de nouveaux clusters.

Les fonctionnalités principales des modèles RKE permettent aux équipes DevOps et de sécurité de{nbsp}:

* Standardiser la configuration des clusters et s'assurer que les clusters provisionnés par Rancher sont créés selon les meilleures pratiques
* Empêcher les utilisateurs moins techniques de faire des choix non informés lors du provisionnement des clusters
* Partager différents modèles avec différents ensembles d'utilisateurs et de groupes
* Déléguer la propriété des modèles à des utilisateurs de confiance pour apporter des modifications
* Contrôler quels utilisateurs peuvent créer des modèles
* Exiger que les utilisateurs créent des clusters à partir d'un modèle

[#_configurable_settings]
== Paramètres configurables

Les modèles RKE peuvent être créés dans l'interface utilisateur de Rancher ou définis au format YAML. Ils peuvent définir tous les mêmes paramètres qui peuvent être spécifiés lorsque vous utilisez Rancher pour provisionner des nœuds personnalisés ou des nœuds d'un fournisseur d'infrastructure{nbsp}:

* Options du fournisseur de cloud
* Options de sécurité des pods
* Fournisseurs de réseau
* Contrôleurs d'Ingress
* Configuration de la sécurité du réseau
* Plugins réseau
* URL et identifiants du registre privé
* Modules complémentaires
* Options Kubernetes, y compris la configuration des composants Kubernetes tels que kube-api, kube-controller, kubelet et les services.

La <<_add_ons,section des produits complémentaires>> d'un modèle RKE est particulièrement puissante car elle permet une large gamme d'options de personnalisation.

[#_scope_of_rke_templates]
== Portée des modèles RKE

Les modèles RKE sont pris en charge pour les clusters provisionnés par Rancher. Les modèles peuvent être utilisés pour provisionner des clusters personnalisés ou des clusters lancés par un fournisseur d'infrastructure.

Les modèles RKE servent à définir les paramètres Kubernetes et Rancher. Les modèles de nœuds sont responsables de la configuration des nœuds. Pour des conseils sur l'utilisation des modèles RKE en conjonction avec le matériel, consultez {xref-rke1-template-infrastructure}[Modèles RKE et matériel].

Les modèles RKE peuvent être créés de zéro pour pré-définir la configuration des clusters. Ils peuvent être appliqués pour lancer de nouveaux clusters, ou les modèles peuvent également être exportés à partir de clusters existants en cours d'exécution.

Les paramètres d'un cluster existant peuvent être {xref-rke1-template-apply}#_convertir_un_cluster_existant_pour_utiliser_un_modèle_rke[sauvegardés en tant que modèle RKE.] Cela crée un nouveau modèle et lie les paramètres du cluster au modèle, de sorte que le cluster ne peut être mis à niveau que si le {xref-manage-rke1-templates}#_mettre_à_jour_un_modèle[modèle est mis à jour], et le cluster est mis à niveau pour {xref-manage-rke1-templates}#_mettre_à_niveau_un_cluster_pour_utiliser_une_nouvelle_révision_de_modèle[utiliser une version plus récente du modèle.] Le nouveau modèle peut également être utilisé pour créer de nouveaux clusters.

[#_example_scenarios]
== Exemples de scénarios

Lorsqu'une organisation a à la fois des utilisateurs de Rancher basiques et avancés, les administrateurs peuvent souhaiter donner aux utilisateurs avancés plus d'options pour la création de clusters, tout en restreignant les options pour les utilisateurs basiques.

Ces {xref-rke1-template-example-use-cases}[scénarios d'exemple] décrivent comment une organisation pourrait utiliser des modèles pour standardiser la création de clusters.

Certains des scénarios d'exemple incluent les suivants{nbsp}:

* *Application des modèles :* Les administrateurs pourraient vouloir {xref-rke1-template-example-use-cases}#_appliquer_un_paramètre_de_modèle_pour_tous[appliquer un ou plusieurs paramètres de modèle pour tout le monde] s'ils souhaitent que tous les nouveaux clusters provisionnés par Rancher aient ces paramètres.
* *Partage de différents modèles avec différents utilisateurs :* Les administrateurs pourraient donner {xref-rke1-template-example-use-cases}#_différents_modèles_aux_utilisateurs_basiques_et_avancés[différents modèles aux utilisateurs basiques et avancés,] afin que les utilisateurs basiques puissent avoir des options plus restreintes et que les utilisateurs avancés puissent avoir plus de liberté lors de la création de clusters.
* *Mise à jour des paramètres de modèle :* Si les équipes de sécurité et de DevOps d'une organisation décident d'incorporer les meilleures pratiques dans les paramètres requis pour les nouveaux clusters, ces meilleures pratiques pourraient évoluer avec le temps. Si les meilleures pratiques changent, {xref-rke1-template-example-use-cases}#_mettre_à_jour_les_modèles_et_les_clusters_créés_avec_eux[un modèle peut être mis à jour vers une nouvelle révision] et les clusters créés à partir du modèle peuvent {xref-manage-rke1-templates}#_mettre_à_niveau_un_cluster_pour_utiliser_une_nouvelle_révision_de_modèle[être mis à niveau vers la nouvelle version] du modèle.
* *Partage de la propriété d'un modèle :* Lorsque le propriétaire d'un modèle ne souhaite plus maintenir un modèle, ou souhaite partager la propriété du modèle, ce scénario décrit comment {xref-rke1-template-example-use-cases}#_permettre_aux_autres_utilisateurs_de_contrôler_et_partager_un_modèle[la propriété du modèle peut être partagée.]

[#_template_management]
== Gestion des modèles

Lorsque vous créez un modèle RKE, il est disponible dans l'interface utilisateur de Rancher depuis la vue *Gestion des clusters* sous *Modèles RKE*. Lorsque vous créez un modèle, vous devenez le propriétaire du modèle, ce qui vous donne la permission de réviser et de partager le modèle. Vous pouvez partager les modèles RKE avec des utilisateurs ou des groupes spécifiques, et vous pouvez également les rendre publics.

Les administrateurs peuvent activer l'application des modèles pour exiger que les utilisateurs utilisent toujours des modèles RKE lors de la création d'un cluster. Cela permet aux administrateurs de garantir que Rancher provisionne toujours des clusters avec des paramètres spécifiques.

Les mises à jour des modèles RKE sont gérées par un système de révision. Si vous souhaitez modifier ou mettre à jour un modèle, vous créez une nouvelle révision du modèle. Ensuite, un cluster qui a été créé avec l'ancienne version du modèle peut être mis à niveau vers la nouvelle révision du modèle.

Dans un modèle RKE, les paramètres peuvent être restreints à ce que le propriétaire du modèle choisit, ou ils peuvent être ouverts pour que l'utilisateur final sélectionne la valeur. La différence est indiquée par le commutateur *Autoriser le remplacement par l'utilisateur* au-dessus de chaque paramètre dans l'interface utilisateur de Rancher lors de la création du modèle.

Pour les paramètres qui ne peuvent pas être remplacés, l'utilisateur final ne pourra pas les modifier directement. Pour qu'un utilisateur obtienne différentes options pour ces paramètres, un propriétaire de modèle RKE devrait créer une nouvelle révision du modèle RKE, ce qui permettrait à l'utilisateur de mettre à niveau et de changer cette option.

Les documents de cette section expliquent les détails de la gestion des modèles RKE{nbsp}:

* {xref-rke1-creator-permissions}[Obtenir la permission de créer des modèles]
* {xref-manage-rke1-templates}[Création et révision des modèles]
* {xref-rke1-template-enforce}#_requiring_new_clusters_to_use_an_rke_template[Enforcing template settings]
* {xref-rke1-template-override-settings}[Surcharge des paramètres du modèle]
* {xref-access-share-rke1-templates}#_sharing_templates_with_specific_users_or_groups[Sharing templates with cluster creators]
* {xref-access-share-rke1-templates}#_sharing_ownership_of_templates[Sharing ownership of a template]

Un {xref-rke1-template-example-yaml}[exemple de fichier de configuration YAML pour un modèle] est fourni à titre de référence.

[#_applying_templates]
== Application des modèles

Vous pouvez {xref-rke1-template-apply}#_créer_un_cluster_à_partir_d_un_modèle_rke[créer un cluster à partir d'un modèle] que vous avez créé, ou à partir d'un modèle qui a été {xref-access-share-rke1-templates}[partagé avec vous.]

Si le propriétaire du modèle RKE crée une nouvelle révision du modèle, vous pouvez {xref-rke1-template-apply}#_mettre_à_jour_un_cluster_créé_avec_un_modèle_rke[mettre à niveau votre cluster vers cette révision.]

Les modèles RKE peuvent être créés de zéro pour pré-définir la configuration des clusters. Ils peuvent être appliqués pour lancer de nouveaux clusters, ou les modèles peuvent également être exportés à partir de clusters existants en cours d'exécution.

Vous pouvez {xref-rke1-template-apply}#_converting_an_existing_cluster_to_use_an_rke_template[sauvegarder la configuration d'un cluster existant en tant que modèle RKE.] Ensuite, les paramètres du cluster ne peuvent être modifiés que si le modèle est mis à jour.

[#_standardizing_hardware]
== Standardisation du matériel

Les modèles RKE sont conçus pour standardiser les paramètres de Kubernetes et de Rancher. Si vous souhaitez également standardiser votre infrastructure, une option est d'utiliser les modèles RKE {xref-rke1-template-infrastructure}[en conjonction avec d'autres outils].

Une autre option consiste à utiliser {xref-cluster-templates}[des modèles de cluster,] qui incluent des options de configuration des pools de nœuds, mais n'assurent pas l'application de la configuration.

[#_yaml_customization]
== Personnalisation YAML

Si vous définissez un modèle RKE sous forme de fichier YAML, vous pouvez modifier cet {xref-rke1-template-example-yaml}[exemple de modèle RKE YAML]. Le YAML dans le modèle RKE utilise la même personnalisation que Rancher utilise lors de la création d'un cluster RKE, mais comme le YAML est situé dans le contexte d'un cluster provisionné par Rancher, vous devrez imbriquer la personnalisation du modèle RKE sous la directive `rancher_kubernetes_engine_config` dans le YAML.

La documentation RKE contient également des fichiers https://rancher.com/docs/rke/latest/en/example-yamls/[annotés] `cluster.yml` que vous pouvez utiliser comme référence.

Pour des conseils sur les options disponibles, consultez la documentation RKE sur https://rancher.com/docs/rke/latest/en/config-options/[la configuration du cluster.]

[#_add_ons]
=== Modules complémentaires

La section du produit complémentaire du fichier de configuration du modèle RKE fonctionne de la même manière que la https://rancher.com/docs/rke/latest/en/config-options/add-ons/[section du produit complémentaire d'un fichier de configuration de cluster].

La directive des produits complémentaires définis par l'utilisateur vous permet soit d'appeler et de télécharger des manifestes Kubernetes, soit de les inclure directement en ligne. Si vous incluez ces manifestes dans votre modèle RKE, Rancher les provisionnera dans le cluster.

Voici quelques actions que vous pourriez réaliser avec des produits complémentaires{nbsp}:

* Installez des applications sur le cluster Kubernetes après son démarrage
* Installez des plugins sur les nœuds déployés avec un daemonset Kubernetes
* Configurez automatiquement des espaces de noms, des comptes de service ou des liaisons de rôle

La configuration du modèle RKE doit être imbriquée dans la directive `rancher_kubernetes_engine_config`. Pour définir des produits complémentaires, lors de la création du modèle, vous cliquerez sur *Edit as YAML*. Ensuite, utilisez la directive `addons` pour ajouter un manifeste, ou la directive `addons_include` pour définir quels fichiers YAML sont utilisés pour les produits complémentaires. Pour plus d'informations sur les produits complémentaires personnalisés, consultez la documentation https://rancher.com/docs/rke/latest/en/config-options/add-ons/user-defined-add-ons/[des produits complémentaires définis par l'utilisateur.]
