= Seguimiento de ID de usuario en los registros de auditoría
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-27
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc 
:product-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc
ifeval::["{build-type}" != "community"]
:xref-enable-api-audit-log: xref:observability/logging/enable-api-audit-log.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-enable-api-audit-log: xref:how-to-guides/advanced-user-guides/enable-api-audit-log.adoc
endif::[]

Los siguientes registros de auditoría se utilizan en Rancher para rastrear eventos que ocurren en los clústeres locales y en sentido descendente:

* https://rancher.com/docs/rke/latest/en/config-options/audit-log/[Registros de Auditoría de Kubernetes]
* {xref-enable-api-audit-log}[Registros de Auditoría de la API de Rancher]

Los registros de auditoría en Rancher v2.6 se han mejorado para incluir el nombre del Proveedor de Identidad externo (nombre común del usuario en el proveedor de autenticación externo) tanto en los registros de auditoría de Rancher como en los de Kubernetes en sentido descendente.

Antes de v2.6, un Administrador de Rancher no podía rastrear un evento desde los registros de auditoría de Rancher hasta los registros de auditoría de Kubernetes sin conocer la correspondencia del nombre de usuario del Proveedor de Identidad externo con el userId (`u-xXXX`) utilizado en Rancher.
Para conocer esta correspondencia, los administradores del clúster necesitaban tener acceso a la API de Rancher, a la interfaz de usuario y al clúster de gestión local.

Ahora, con esta función, un administrador de clústeres en sentido descendente debería poder consultar los registros de auditoría de Kubernetes y saber qué usuario específico del Proveedor de Identidad externo (IDP) realizó una acción sin necesidad de ver nada en Rancher.
Si los registros de auditoría se envían fuera del clúster, un usuario del sistema de registro debería poder identificar al usuario en el sistema del Proveedor de Identidad externo.
Un Administrador de Rancher ahora debería poder ver los registros de auditoría de Rancher y seguir hasta el registro de auditoría de Kubernetes utilizando el nombre de usuario del Proveedor de Identidad externo.

[#_feature_description]
== Descripción

* Cuando se habilitan los registros de auditoría de Kubernetes en el clúster en sentido descendente, en cada evento que se registra, el nombre de usuario del Proveedor de Identidad externo ahora se registra para cada solicitud, a nivel de 'metadatos'.
* Cuando habilitas los registros de auditoría de la API de Rancher para una instalación de Rancher, el nombre de usuario del Proveedor de Identidad externo también se registra ahora en el `auditLog.level=0` para cada solicitud que llega al servidor de la API de Rancher, incluidas las solicitudes de inicio de sesión.
