= Arquitetura Recomendada do Cluster
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: xref:guias-procedimentos/guias-para-novos-usuĂĄrios/clusters-kubernetes-no-rancher/configuraĂ§ĂŁo/lista-de-verificaĂ§ĂŁo-para-clusters-prontos-para-produĂ§ĂŁo/arquitetura-recomendada-do-cluster.adoc 
:product-path: cluster-deployment/production-checklist/recommended-cluster-architecture.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-production-checklist-node-roles: xref:cluster-deployment/production-checklist/roles-for-nodes-in-kubernetes.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:como-fazer/guias-para-novos-usuĂĄrios/cluster-kubernetes-na-configuraĂ§ĂŁo-do-rancher/requisitos-dos-nĂłs-para-clusters-gerenciados-pelo-rancher.adoc
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-production-checklist-node-roles: xref:guias-procedimentos/guias-para-novos-usuĂĄrios/clusters-kubernetes-no-rancher/configuraĂ§ĂŁo/papĂ©is-para-nĂłs-no-kubernetes.adoc
endif::[]

Existem trĂȘs papĂ©is que podem ser atribuĂ­dos aos nĂłs: `etcd`, `controlplane` e `worker`.

[#_separating_worker_nodes_from_nodes_with_other_roles]
== Separando nĂłs Worker dos nĂłs com outros papĂ©is

Ao projetar seu(s) cluster(s), vocĂȘ tem duas opĂ§Ă”es:

* Usar nĂłs dedicados para cada papel. Isso garante a disponibilidade de recursos para os componentes necessĂĄrios para o papel especificado. Isso tambĂ©m isola estritamente o trĂĄfego de rede entre os papĂ©is, de acordo com {xref-node-reqs}#_networking_requirements[os requisitos de porta].
* Atribua os papĂ©is `etcd` e `controlplane` aos mesmos nĂłs. Esses nĂłs devem atender aos requisitos de hardware para ambos os papĂ©is.

Em qualquer um dos casos, o papel `worker` nĂŁo deve ser usado ou adicionado a nĂłs com o papel `etcd` ou `controlplane`.

Portanto, cada nĂł deve ter uma das seguintes configuraĂ§Ă”es de papel:

* `etcd`
* `controlplane`
* Tanto `etcd` quanto `controlplane`
* `worker`

[#_recommended_number_of_nodes_with_each_role]
== NĂșmero Recomendado de NĂłs com Cada Papel

O cluster deve ter:

* Pelo menos trĂȘs nĂłs com o papel `etcd` para sobreviver Ă  perda de um nĂł. Aumente essa contagem para maior tolerĂąncia a falhas de nĂłs e distribua-os por zonas (de disponibilidade) para fornecer uma tolerĂąncia a falhas ainda melhor.
* Pelo menos dois nĂłs com o papel `controlplane` para alta disponibilidade do componente mestre.
* Pelo menos dois nĂłs com o papel `worker` para reprogramaĂ§ĂŁo de cargas de trabalho em caso de falha de um nĂł.

Para mais informaĂ§Ă”es sobre para que serve cada papel, consulte a {xref-production-checklist-node-roles}[seĂ§ĂŁo sobre papĂ©is para nĂłs no Kubernetes.]

[#_number_of_controlplane_nodes]
=== NĂșmero de NĂłs Controlplane

Adicionar mais de um nĂł com o papel `controlplane` torna cada componente mestre altamente disponĂ­vel.

[#_number_of_etcd_nodes]
=== NĂșmero de NĂłs etcd

O nĂșmero de nĂłs que vocĂȘ pode perder de uma vez enquanto mantĂ©m a disponibilidade do cluster Ă© determinado pelo nĂșmero de nĂłs atribuĂ­dos ao papel `etcd`. Para um cluster com n membros, o mĂ­nimo Ă© (n/2)+1. Portanto, recomendamos criar um nĂł `etcd` em 3 zonas de disponibilidade diferentes dentro de uma regiĂŁo para sobreviver Ă  perda de uma zona de disponibilidade. Se vocĂȘ usar apenas duas zonas, poderĂĄ sobreviver apenas Ă  perda da zona onde nĂŁo perde a maioria dos nĂłs.

|===
| NĂłs com o papel `etcd` | Maioria | TolerĂąncia a Falhas

| 1
| 1
| 0

| 2
| 2
| 0

| 3
| 2
| *1*

| 4
| 3
| 1

| 5
| 3
| *2*

| 6
| 4
| 2

| 7
| 4
| *3*

| 8
| 5
| 3

| 9
| 5
| *4*
|===

ReferĂȘncias:

* https://etcd.io/docs/v3.5/faq/#what-is-failure-tolerance[DocumentaĂ§ĂŁo oficial do etcd sobre o tamanho ideal do cluster etcd]
* https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/[DocumentaĂ§ĂŁo oficial do Kubernetes sobre a operaĂ§ĂŁo de clusters etcd para Kubernetes]

[#_number_of_worker_nodes]
=== NĂșmero de NĂłs Worker

Adicionar mais de um nĂł com o papel `worker` garantirĂĄ que suas cargas de trabalho possam ser reprogramadas se um nĂł falhar.

[#_why_production_requirements_are_different_for_the_rancher_cluster_and_the_clusters_running_your_applications]
=== Por que os requisitos de produĂ§ĂŁo sĂŁo diferentes para o cluster Rancher e os clusters que executam seus aplicativos

VocĂȘ pode ter notado que nossas instruĂ§Ă”es de {xref-install-rancher}[InstalaĂ§ĂŁo do Kubernetes] nĂŁo atendem Ă  nossa definiĂ§ĂŁo de um cluster pronto para produĂ§ĂŁo, pois nĂŁo hĂĄ nĂłs dedicados para o papel `worker`. No entanto, para sua instalaĂ§ĂŁo do Rancher, este cluster de trĂȘs nĂłs Ă© vĂĄlido, porque:

* Permite uma falha de nĂł `etcd`.
* MantĂ©m vĂĄrias instĂąncias dos componentes mestres ao ter mĂșltiplos nĂłs `controlplane`.
* Nenhuma outra carga de trabalho alĂ©m do prĂłprio Rancher deve ser criada neste cluster.

[#_references]
== ReferĂȘncias

* https://kubernetes.io/docs/concepts/overview/components/#master-components[Kubernetes: Componentes Mestres]
