= Funções dos nós no Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/guias-para-novos-usuários/clusters-kubernetes-no-rancher/configuração/lista-de-verificação-para-clusters-prontos-para-produção/funções-dos-nós-no-kubernetes.adoc 
:product-path: cluster-deployment/production-checklist/roles-for-nodes-in-kubernetes.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
endif::[]

Esta seção descreve as funções dos nós etcd, nós de plano de controle e nós de trabalho no Kubernetes, e como essas funções trabalham juntas em um cluster.

Este diagrama é aplicável a clusters do Kubernetes {xref-launch-k8s-with-rancher}[lançados com Rancher usando RKE.]

.Linhas mostram o fluxo de tráfego entre os componentes. As cores são usadas apenas para auxílio visual
image::clusterdiagram.svg[Diagrama do cluster]

[#_etcd]
== etcd

Nós com a função `etcd` executam o etcd, que é um armazenamento de chave-valor consistente e altamente disponível usado como armazenamento de apoio do Kubernetes`' para todos os dados do cluster. O etcd replica os dados para cada nó.

[NOTE]
====

Nós com a função `etcd` são mostrados como `Unschedulable` na interface, ou seja, nenhum pod será agendado para esses nós por padrão.
====


[#_controlplane]
== controlplane

Nós com a função `controlplane` executam os componentes mestre do Kubernetes (excluindo `etcd`, pois é uma função separada). Veja https://kubernetes.io/docs/concepts/overview/components/#master-components[Kubernetes: Componentes Mestre] para uma lista detalhada de componentes.

[NOTE]
====

Nós com a função `controlplane` são mostrados como `Unschedulable` na interface, ou seja, nenhum pod será agendado para esses nós por padrão.
====


[#_kube_apiserver]
=== kube-apiserver

O servidor de API do Kubernetes (`kube-apiserver`) escala horizontalmente. Cada nó com a função `controlplane` será adicionado ao proxy NGINX nos nós com componentes que precisam acessar o servidor de API do Kubernetes. Isso significa que se um nó se tornar inacessível, o proxy NGINX local no nó encaminhará a solicitação para outro servidor de API do Kubernetes na lista.

[#_kube_controller_manager]
=== kube-controller-manager

O gerenciador de controladores do Kubernetes usa eleição de líder usando um endpoint no Kubernetes. Uma instância do `kube-controller-manager` criará uma entrada nos endpoints do Kubernetes e atualizará essa entrada em um intervalo configurado. Outras instâncias verão um líder ativo e esperarão que essa entrada expire (por exemplo, quando um nó não responde).

[#_kube_scheduler]
=== kube-scheduler

O agendador do Kubernetes usa eleição de líder usando um endpoint no Kubernetes. Uma instância do `kube-scheduler` criará uma entrada nos endpoints do Kubernetes e atualizará essa entrada em um intervalo configurado. Outras instâncias verão um líder ativo e esperarão que essa entrada expire (por exemplo, quando um nó não responde).

[#_worker]
== trabalhador

Nós com a função `worker` executam os componentes do nó do Kubernetes. Veja https://kubernetes.io/docs/concepts/overview/components/#node-components[Kubernetes: Componentes do nó] para uma lista detalhada de componentes.

[#_references]
== Referências

* https://kubernetes.io/docs/concepts/overview/components/#node-components[Kubernetes: Componentes do nó]
