= Integração com o AWS Marketplace
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/index.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/aws.adoc
ifeval::["{build-type}" != "community"]
:xref-aws-cloud-marketplace-adapter-reqs: xref:installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/adapter-requirements.adoc
:xref-aws-cloud-marketplace-install-adapter: xref:installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/install-adapter.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-aws-cloud-marketplace-adapter-reqs: xref:integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/adapter-requirements.adoc
:xref-aws-cloud-marketplace-install-adapter: xref:integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.adoc
endif::[]

[#_overview]
== Visão Geral

O Rancher oferece uma integração com o AWS Marketplace que permite aos usuários adquirir um contrato de suporte com a SUSE. Essa integração permite que você ajuste facilmente suas necessidades de suporte à medida que começa a suportar mais clusters.

[#_limitations]
== Limitações

* Você deve estar executando o Rancher v2.6.7 ou superior
* O Rancher deve ser implantado com métricas adicionais habilitadas.
* O Rancher deve ser instalado em um cluster EKS.
* Você deve adquirir pelo menos uma concessão de suporte ao Rancher através do AWS Marketplace.
* Você pode precisar de configuração adicional para suportar casos de uso de proxy/airgap. Veja os {xref-aws-cloud-marketplace-adapter-reqs}[pré-requisitos] para mais informações.

[#_how_to_use]
== Como usar

. Complete os {xref-aws-cloud-marketplace-adapter-reqs}[passos pré-requisitos].
. {xref-aws-cloud-marketplace-install-adapter}[Instale o Adaptador CSP].

[#_faq]
== FAQs

*Posso adquirir suporte para mais nós posteriormente?*

Sim. Basta ir à entrada do AWS Marketplace que você usou para adquirir suporte inicialmente e aumentar o número de concessões.

*Posso usar várias instâncias do Rancher na mesma conta da AWS?*

Sim. No entanto, cada cluster em que o Rancher está instalado precisará aderir aos pré-requisitos.

Além disso, tenha em mente que uma determinada concessão só pode ser usada por um servidor de gerenciamento do Rancher por vez.
