= Funções de Cluster e Projeto
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-02-11
:page-revdate: {revdate}
:community-path: como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-de-cluster-e-projeto.adoc 
:product-path: rancher-admin/usuários/autenticação-e-autorização/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-de-cluster-e-projeto.adoc
ifeval::["{build-type}" != "community"]
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-psa-pss: xref:security/psa-pss.adoc
:xref-locked-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-psa-pss: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/padrões-de-segurança-de-pod.adoc
:xref-custom-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-personalizadas.adoc
:xref-locked-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-bloqueadas.adoc
endif::[]

As funções de cluster e projeto definem a autorização do usuário dentro de um cluster ou projeto.

Para gerenciar essas funções,

. Clique em *☰ > Usuários e Autenticação*.
. Na barra de navegação à esquerda, clique em *Modelos de Função* e vá para a aba *Cluster* ou *Projeto/namespace*.

[#_membership_and_role_assignment]
== Associação e Atribuição de Função

Os projetos e clusters acessíveis a usuários não administrativos são determinados pela _associação_. A associação é uma lista de usuários que têm acesso a um cluster ou projeto específico com base nas funções que foram atribuídas a eles nesse cluster ou projeto. Cada cluster e projeto inclui uma aba que um usuário com as permissões apropriadas pode usar para gerenciar a associação.

Quando você cria um cluster ou projeto, o Rancher automaticamente atribui você como `Owner` dele. Usuários atribuídos à função `Owner` podem atribuir funções a outros usuários no cluster ou projeto.

[NOTE]
====

Usuários não administrativos não podem acessar nenhum projeto/cluster existente por padrão. Um usuário com permissões apropriadas (tipicamente o proprietário) deve atribuir explicitamente a associação do projeto e do cluster.
====


[#_cluster_roles]
== Funções de Cluster

_Funções de cluster_ são funções que você pode atribuir a usuários, concedendo-lhes acesso a um cluster. Existem duas funções principais de cluster: `Owner` e `Member`.

* *Proprietário do Cluster:*
+
Esses usuários têm controle total sobre o cluster e todos os recursos nele.

* *Membro do Cluster:*
+
Esses usuários podem visualizar a maioria dos recursos em nível de cluster e criar novos projetos.
+
[WARNING]
====
Quando um Membro do Cluster cria um projeto, o usuário é automaticamente atribuído a <<Project Roles, privilégios de Proprietário do Projeto>>. Isso lhes concede controle abrangente sobre o projeto e seus recursos associados, incluindo permissões para implantar cargas de trabalho. Sem a aplicação das {xref-psa-pss}[Normas de Segurança de Pod (PSS) e Admissão de Segurança de Pod (PSA)], um Membro do Cluster pode executar contêineres privilegiados no cluster.
====

[#_custom_cluster_roles]
=== Funções de Cluster Personalizadas

O Rancher permite que você atribua _funções de cluster personalizadas_ a um usuário padrão em vez das típicas funções `Owner` ou `Member`. Essas funções podem ser uma função de cluster personalizada incorporada ou uma definida por um administrador do Rancher. Elas são convenientes para definir acesso restrito ou especializado para um usuário padrão dentro de um cluster. Veja a tabela abaixo para uma lista de funções de cluster personalizadas incorporadas.

[#_cluster_role_reference]
=== Referência de Funções de Cluster

A tabela a seguir lista cada função de cluster personalizada incorporada disponível e se esse nível de acesso está incluído nas permissões padrão em nível de cluster, `Cluster Owner` e `Cluster Member`.

|===
| Função de Cluster Incorporada | Proprietário | Membro +++<a id="clus-roles">++++++</a>+++

| Criar Projetos
| ✓
| ✓

| Gerenciar Backups de Cluster
| ✓
|

| Gerenciar Catálogos de Cluster
| ✓
|

| Gerenciar Membros do Cluster
| ✓
|

| Gerenciar Nós <<_manage_nodes_permissions,(veja a tabela abaixo)>>
| ✓
|

| Gerenciar Armazenamento
| ✓
|

| Ver Todos os Projetos
| ✓
|

| Ver Catálogos de Cluster
| ✓
| ✓

| Ver Membros do Cluster
| ✓
| ✓

| Ver Nós
| ✓
| ✓
|===

[#_manage_nodes_permissions]
=== Gerenciar Permissões de Nós

A tabela a seguir lista as permissões disponíveis para a função `Manage Nodes` no RKE e RKE2.

|===
| Gerenciar Permissões de Nós | RKE | RKE2

| Acesso SSH
| ✓
| ✓

| Excluir Nós
| ✓
| ✓

| Escalar Clusters Para Cima e Para Baixo
| ✓
| *
|===

*No RKE2, você deve ter permissão para editar um cluster para poder escalar clusters para cima e para baixo.*

Para detalhes sobre como cada função de cluster pode acessar recursos do Kubernetes, você pode consultá-los na interface do Rancher:

. No canto superior esquerdo, clique em *☰ > Usuários e Autenticação*.
. Na barra de navegação à esquerda, clique em *Modelos de Função*.
. Clique na aba *Cluster*.
. Clique no nome de uma função individual. A tabela mostra todas as operações e recursos que são permitidos pela função.

[NOTE]
====

Ao visualizar os recursos associados às funções padrão criadas pelo Rancher, se houver múltiplos recursos da API do Kubernetes em um item de linha, o recurso terá `(Custom)` anexado a ele. Estes não são recursos personalizados, mas apenas uma indicação de que há múltiplos recursos da API do Kubernetes como um único recurso.
====


[#_giving_a_custom_cluster_role_to_a_cluster_member]
== Atribuindo uma Função de Cluster Personalizada a um Membro do Cluster

Após um administrador {xref-custom-roles}[configurar uma função de cluster personalizada,] os proprietários e administradores do cluster podem então atribuir essas funções aos membros do cluster.

Para atribuir uma função personalizada a um novo membro do cluster, você pode usar a interface do Rancher. Para modificar as permissões de um membro existente, você precisará usar a visualização da API do Rancher.

Para atribuir a função a um novo membro do cluster,

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster onde você deseja atribuir uma função a um membro e clique em *Explorar*.
. Clique em menu:Cluster[Membros do Cluster].
. Clique em *Adicionar*.
. Na seção *Permissões do Cluster*, escolha a função de cluster personalizada que deve ser atribuída ao membro.
. Clique em *Criar*.

*Resultado:* O membro tem a função atribuída.

Para atribuir qualquer função personalizada a um membro existente do cluster,

. Clique em *☰ > Usuários e Autenticação*.
. Vá até o membro a quem você deseja dar a função. Clique no *⋮ > Editar Configuração*.
. Se você adicionou funções personalizadas, elas aparecerão na seção *Personalizado*. Escolha a função que você deseja atribuir ao membro.
. Clique em *Salvar*.

*Resultado:* O membro tem a função atribuída.

[#_project_roles]
== Funções de Projeto

_Funções de projeto_ são funções que podem ser usadas para conceder acesso a um projeto aos usuários. Existem três funções principais de projeto: `Owner`, `Member` e `Read Only`.

* *Proprietário do Projeto:*
+
Esses usuários têm controle total sobre o projeto e todos os recursos nele.

* *Membro do Projeto:*
+
Esses usuários podem gerenciar recursos específicos do projeto, como namespaces e cargas de trabalho, mas não podem gerenciar outros membros do projeto.

[NOTE]
====

Por padrão, a função Rancher de `project-member` herda da função `Kubernetes-edit`, e a função `project-owner` herda da função `Kubernetes-admin`. Assim, tanto as funções `project-member` quanto `project-owner` permitirão o gerenciamento de namespaces, incluindo a capacidade de criar e excluir namespaces.
====


* *Apenas Leitura:*
+
Esses usuários podem ver tudo no projeto, mas não podem criar, atualizar ou excluir nada.

[WARNING]
====

Usuários atribuídos à função `Owner` ou `Member` para um projeto herdam automaticamente a função `namespace creation`. No entanto, essa função é um https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole[ClusterRole do Kubernetes], o que significa que seu escopo se estende a todos os projetos no cluster. Portanto, usuários explicitamente atribuídos à função `owner` ou `member` para um projeto podem criar namespaces em outros projetos aos quais estão atribuídos, mesmo com apenas a função `Read Only` atribuída.
====


[#_custom_project_roles]
=== Funções de Projeto Personalizadas

O Rancher permite que você atribua _funções de projeto personalizadas_ a um usuário padrão em vez das típicas funções `Owner`, `Member` ou `Read Only`. Essas funções podem ser uma função de projeto personalizada incorporada ou uma definida por um administrador do Rancher. Elas são convenientes para definir acesso restrito ou especializado para um usuário padrão dentro de um projeto. Veja a tabela abaixo para uma lista de funções de projeto personalizadas incorporadas.

[#_project_role_reference]
=== Referência de Funções de Projeto

A tabela a seguir lista cada função de projeto personalizada incorporada disponível no Rancher e se também é concedida pela função `Owner`, `Member` ou `Read Only`.

|===
| Função de Projeto Incorporada | Proprietário | Membro+++<a id="proj-roles">++++++</a>+++ | Apenas Leitura

| Gerenciar Membros do Projeto
| ✓
|
|

| Criar Namespaces
| ✓
| ✓
|

| Gerenciar Config Maps
| ✓
| ✓
|

| Gerenciar Ingress
| ✓
| ✓
|

| Gerenciar Catálogos de Projetos
| ✓
|
|

| Gerenciar Segredos
| ✓
| ✓
|

| Gerenciar Contas de Serviço
| ✓
| ✓
|

| Gerenciar Serviços
| ✓
| ✓
|

| Gerenciar Volumes
| ✓
| ✓
|

| Gerenciar Cargas de Trabalho
| ✓
| ✓
|

| Visualizar Segredos
| ✓
| ✓
|

| Visualizar Config Maps
| ✓
| ✓
| ✓

| Visualizar Ingress
| ✓
| ✓
| ✓

| Visualizar Membros do Projeto
| ✓
| ✓
| ✓

| Visualizar Catálogos de Projetos
| ✓
| ✓
| ✓

| Visualizar Contas de Serviço
| ✓
| ✓
| ✓

| Visualizar Serviços
| ✓
| ✓
| ✓

| Visualizar Volumes
| ✓
| ✓
| ✓

| Visualizar Cargas de trabalho
| ✓
| ✓
| ✓
|===

[NOTE]
.Notas:
====

* Cada função de projeto listada acima, incluindo `Owner`, `Member` e `Read Only`, é composta por várias regras que concedem acesso a diversos recursos. Você pode visualizar as funções e suas regras na página Global > Segurança > Funções.
* Ao visualizar os recursos associados às funções padrão criadas pelo Rancher, se houver múltiplos recursos da API do Kubernetes em um item de linha, o recurso terá `(Custom)` anexado a ele. Estes não são recursos personalizados, mas apenas uma indicação de que há múltiplos recursos da API do Kubernetes como um único recurso.
* A função `Manage Project Members` permite que o proprietário do projeto gerencie qualquer membro do projeto *e* conceda a eles qualquer função com escopo de projeto, independentemente do acesso aos recursos do projeto. Tenha cuidado ao atribuir esta função individualmente.
====


[#_defining_custom_roles]
== Definindo Funções Personalizadas

Como mencionado anteriormente, funções personalizadas podem ser definidas para uso no nível de cluster ou projeto. O campo de contexto define se a função aparecerá na página de membros do cluster, na página de membros do projeto ou em ambas.

Ao definir uma função personalizada, você pode conceder acesso a recursos específicos ou especificar funções das quais a função personalizada deve herdar. Uma função personalizada pode ser composta por uma combinação de concessões específicas e funções herdadas. Todas as concessões são aditivas. Isso significa que definir uma concessão mais restrita para um recurso específico *não* substituirá uma concessão mais ampla definida em uma função da qual a função personalizada está herdando.

[#_default_cluster_and_project_roles]
== Funções Padrão de Cluster e Projeto

Por padrão, quando um usuário padrão cria um novo cluster ou projeto, ele é automaticamente atribuído a uma função de propriedade: seja <<_cluster_roles,proprietário do cluster>> ou <<_project_roles,proprietário do projeto>>. No entanto, em algumas organizações, essas funções podem estender excessivamente o acesso administrativo. Neste caso de uso, você pode alterar a função padrão para algo mais restritivo, como um conjunto de funções individuais ou uma função personalizada.

Existem dois métodos para alterar funções padrão de cluster/projeto:

* *Atribuir Funções Personalizadas*: Crie uma {xref-custom-roles}[função personalizada] para seu <<_custom_cluster_roles,cluster>> ou <<_custom_project_roles,projeto>>, e então defina a função personalizada como padrão.
* *Atribuir Funções Individuais*: Configure várias funções <<_cluster_role_reference,cluster>>/<<_project_role_reference,projeto>> como padrão para atribuição ao usuário que está criando.
+
Por exemplo, em vez de atribuir uma função que herda outras funções (como `cluster owner`), você pode escolher uma mistura de funções individuais (como `manage nodes` e `manage storage`).

[NOTE]
====

* Embora você possa {xref-locked-roles}[travar] uma função padrão, o sistema ainda atribui a função a usuários que criam um cluster/projeto.
* Apenas usuários que criam clusters/projetos herdam suas funções. Usuários adicionados à associação do cluster/projeto posteriormente devem ter suas funções atribuídas explicitamente.
====


[#_configuring_default_roles_for_cluster_and_project_creators]
== Configurando Funções Padrão para Criadores de Cluster e Projeto

Você pode alterar as funções de cluster ou projeto que são atribuídas automaticamente ao usuário que está criando.

. No canto superior esquerdo, clique em *☰ > Usuários e Autenticação*.
. Na barra de navegação à esquerda, clique em *Modelos de Função*.
. Clique na aba *Cluster* ou *Projeto/Namespaces*.
. Encontre a função personalizada ou individual que você deseja usar como padrão. Em seguida, edite a função selecionando *⋮ > Editar Configuração*.
. Na seção *Cluster Creator Default* ou *Project Creator Default*, ative a função como padrão.
. Clique em *Salvar*.

*Resultado:* As funções padrão são configuradas com base nas suas alterações. As funções atribuídas aos criadores de cluster/projeto exibem uma marca de verificação na coluna *Cluster/Project Creator Default*.

Se você deseja remover uma função padrão, edite a permissão e selecione *Não* na opção de funções padrão.

[#_cluster_membership_revocation_behavior]
== Comportamento de Revogação de Associação ao Cluster

Quando você revoga a associação ao cluster de um usuário padrão que está explicitamente atribuído à associação tanto ao cluster _quanto_ a um projeto dentro do cluster, esse usuário padrão <<_cluster_roles,perde suas funções de cluster>> mas <<_project_roles,mantém suas funções de projeto>>. Em outras palavras, embora você tenha revogado as permissões do usuário para acessar o cluster e seus nós, o usuário padrão ainda pode:

* Acessar os projetos nos quais possui associação.
* Exercer quaisquer <<_project_role_reference,funções de projeto individuais>> que lhe foram atribuídas.

Se você deseja revogar completamente o acesso de um usuário dentro de um cluster, revogue tanto suas associações ao cluster quanto ao projeto.

[#_external_roletemplate_behavior]
== Comportamento Externo `RoleTemplate`

No Rancher v2.9.0 e versões posteriores, objetos externos `RoleTemplate` só podem ser criados se o `ClusterRole` de suporte existir no cluster local ou se o `ExternalRules` estiver configurado em sua configuração.

Para contextualizar, o `ClusterRole` de suporte contém regras e privilégios do cluster, e compartilha o mesmo `metadata.name` usado no `RoleTemplate` em seu respectivo cluster referenciado pelo `ClusterRoleTemplateBinding/ProjectRoleTemplateBinding`. Além disso, observe que permissões `escalate` em `RoleTemplates` são necessárias para criar `RoleTemplates` externos com `ExternalRules`.
