= Papéis Bloqueados
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/papéis-bloqueados.adoc 
:product-path: rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
ifeval::["{build-type}" != "community"]
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-custom-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-personalizadas.adoc
endif::[]

Você pode definir papéis para um status de `locked`. Bloquear papéis impede que eles sejam atribuídos a usuários no futuro.

Papéis bloqueados:

* Não podem ser atribuídos a usuários que ainda não os tenham.
* Não estão listados no menu suspenso *Papéis de Membro* ao adicionar um usuário a um cluster ou projeto.
* Não afetam os usuários que receberam o papel antes de você bloqueá-lo. Esses usuários mantêm o acesso que o papel fornece.
+
*Exemplo:* digamos que sua organização crie uma política interna que proíbe usuários atribuídos a um cluster de criar novos projetos. É seu trabalho fazer cumprir essa política.
+
Para aplicá-la, antes de adicionar novos usuários ao cluster, você deve bloquear os seguintes papéis: `Cluster Owner`, `Cluster Member` e `Create Projects`. Então, você poderia criar um novo papel personalizado que inclua as mesmas permissões de um *Membro do Cluster*, exceto a capacidade de criar projetos. Então, você usa esse novo papel personalizado ao adicionar usuários a um cluster.

Os papéis podem ser bloqueados pelos seguintes usuários:

* Qualquer usuário atribuído à permissão global `Administrator`.
* Qualquer usuário atribuído à permissão `Custom Users`, juntamente com o papel `Manage Roles`.

[#_locking_unlocking_roles]
== Bloqueio/Desbloqueio de Papéis

Se você quiser impedir que um papel seja atribuído a usuários, pode defini-lo para um status de `locked`.

Você pode bloquear papéis em dois contextos:

* Quando você está {xref-custom-roles}[adicionando um papel personalizado].
* Quando você está editando um papel existente (veja abaixo).

Papéis de cluster e papéis de projeto/namespace podem ser bloqueados, mas papéis globais não podem.

. No canto superior esquerdo, clique em *☰ > Usuários e Autenticação*.
. Na barra de navegação à esquerda, clique em *Modelos de Função*.
. Vá para a guia *Cluster* ou a guia *Projeto/Namespaces*.
. Do papel que você deseja bloquear (ou desbloquear), selecione *⋮ > Editar Configuração*.
. Na opção *Bloqueado*, escolha o botão de opção *Sim* ou *Não*. Então clique em *Salvar*.
