= Gerenciando o Controle de Acesso com Base em Função (RBAC)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/novos-usuários/guias-de-autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/index.adoc 
:product-path: rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/usuarios/authn-e-authz/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/permissões-globais.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:como-fazer-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-global-permissions: xref:procedimentos/novos-usuários/guias-de-autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/permissões-globais.adoc 
:xref-authn-authz: xref:procedimentos/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/configuração-de-autenticação/index.adoc
endif::[]

Dentro do Rancher, cada pessoa se autentica como um _usuário_, que é um login que concede acesso ao Rancher. Conforme mencionado em {xref-authn-authz}[Autenticação], os usuários podem ser locais ou externos.

Após configurar a autenticação externa, os usuários que aparecem na página *Usuários* mudam.

* Se você estiver logado como um usuário local, apenas usuários locais aparecem.
* Se você estiver logado como um usuário externo, tanto usuários externos quanto locais aparecem.

[#_users_and_roles]
== Usuários e funções

Uma vez que o usuário faz login no Rancher, sua _autorização_, ou seus direitos de acesso dentro do sistema, é determinado por _permissões globais_ e _funções de cluster e projeto_.

* {xref-global-permissions}[Permissões Globais]:
+
Defina a autorização do usuário fora do escopo de qualquer cluster específico.

* {xref-cluster-project-roles}[Funções de Cluster e Projeto]:
+
Define a autorização do usuário dentro do cluster ou projeto específico onde o usuário recebe a função.

Tanto as permissões globais quanto as funções de cluster e projeto são implementadas sobre https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Kubernetes RBAC]. Portanto, a aplicação de permissões e funções é realizada pelo Kubernetes.
