= Docker-Installation mit TLS-Beendigung an der Layer-7-Schicht des NGINX-Load-Balancers
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-27
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/configure-layer-7-nginx-load-balancer.adoc 
:product-path: installation-and-upgrade/infrastructure-setup/configure-layer-7-nginx-load-balancer.adoc
ifeval::["{build-type}" != "community"]
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
:xref-enable-api-audit-log: xref:observability/logging/enable-api-audit-log.adoc
:xref-certificate-troubleshooting: xref:installation-and-upgrade/troubleshooting/certificate-troubleshooting.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-air-gap: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/index.adoc
:xref-enable-api-audit-log: xref:how-to-guides/advanced-user-guides/enable-api-audit-log.adoc
:xref-certificate-troubleshooting: xref:getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/certificate-troubleshooting.adoc
endif::[]

Für Entwicklungs- und Testumgebungen, die eine spezielle Anforderung haben, TLS/SSL an einem Load Balancer statt in Ihrem Rancher-Server-Container zu beenden, stellen Sie Rancher bereit und konfigurieren Sie einen Load Balancer, der mit ihm zusammenarbeitet.

Ein Layer-7-Load-Balancer kann vorteilhaft sein, wenn Sie Ihre TLS-Beendigung in Ihrer Infrastruktur zentralisieren möchten. Layer-7-Load Balancer bietet auch die Möglichkeit, dass Ihr Load Balancer Entscheidungen basierend auf HTTP-Attributen wie Cookies usw. trifft, mit denen sich ein Layer-4-Load Balancer nicht befassen kann.

Dieses Installationsverfahren führt Sie durch die Bereitstellung von Rancher mit einem einzelnen Container und bietet dann eine Beispielkonfiguration für einen Layer-7 NGINX-Load-Balancer.

[#_requirements_for_os_docker_hardware_and_networking]
== Anforderungen an das Betriebssystem, Docker, Hardware und Netzwerk

Stellen Sie sicher, dass Ihr Knoten die allgemeinen {xref-install-reqs}[Installationsanforderungen] erfüllt.

[#_installation_outline]
== Installationsübersicht

[#_1_provision_linux_host]
== 1. Linux-Host bereitstellen

Stellen Sie einen einzelnen Linux-Host gemäß unseren {xref-install-reqs}[Anforderungen] bereit, um Ihren Rancher-Server zu starten.

[#_2_choose_an_ssl_option_and_install_rancher]
== 2. Wählen Sie eine SSL-Option und installieren Sie Rancher

Aus Sicherheitsgründen ist SSL (Secure Sockets Layer) erforderlich, wenn Sie Rancher verwenden. SSL sichert alle Netzwerkkommunikationen von Rancher, wie z.B. beim Anmelden oder Interagieren mit einem Cluster.

[NOTE]
.Möchten Sie..
====

* Eine Air Gap-Installation abschließen?
* Alle Transaktionen mit der Rancher-API aufzeichnen?

Siehe <<_advanced_options,Erweiterte Optionen>> unten, bevor Sie fortfahren.
====


Treffen Sie eine Auswahl aus den folgenden Optionen:

.Option A - Bringen Sie Ihr eigenes Zertifikat mit: Selbstsigniert
[%collapsible]
======
Wenn Sie sich entscheiden, ein selbstsigniertes Zertifikat zur Verschlüsselung der Kommunikation zu verwenden, müssen Sie das Zertifikat auf Ihrem Load Balancer (was Sie später tun werden) und in Ihrem Rancher-Container installieren. Führen Sie den Docker-Befehl aus, um Rancher bereitzustellen, und verweisen Sie auf Ihr Zertifikat.

[NOTE]
.Voraussetzungen:
====

Erstellen Sie ein selbstsigniertes Zertifikat.

* Die Zertifikatdateien müssen im PEM-Format vorliegen.
====


*Um Rancher mit einem selbstsignierten Zertifikat zu installieren:*

. Während Sie den Docker-Befehl zur Bereitstellung von Rancher ausführen, verweisen Sie Docker auf Ihre CA-Zertifikatdatei.
+
----
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v /etc/your_certificate_directory/cacerts.pem:/etc/rancher/ssl/cacerts.pem \
  rancher/rancher:latest
----
+
======
Option B – Bringen Sie Ihr eigenes Zertifikat mit: Von einer anerkannten CA signiert
[%collapsible]
======
Wenn Ihr Cluster öffentlich zugänglich ist, ist es am besten, ein von einer anerkannten CA signiertes Zertifikat zu verwenden.

[NOTE]
.Voraussetzungen:
====

* Die Zertifikatdateien müssen im PEM-Format vorliegen.
====


*Um Rancher mit einem von einer anerkannten CA signierten Zertifikat zu installieren:*

Wenn Sie ein von einer anerkannten CA signiertes Zertifikat verwenden, ist es nicht notwendig, Ihr Zertifikat im Rancher-Container zu installieren. Wir müssen sicherstellen, dass kein standardmäßiges CA-Zertifikat generiert und gespeichert wird; dies können Sie tun, indem Sie den `--no-cacerts` Parameter an den Container übergeben.

. Geben Sie den folgenden Befehl ein.
+
----
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  rancher/rancher:latest --no-cacerts
----
+
======

[#_3_configure_load_balancer]
== 3. Konfigurieren Sie den Lastausgleich

Wenn Sie einen Lastausgleich vor Ihrem Rancher-Container verwenden, ist es nicht erforderlich, dass der Container die Portkommunikation von Port 80 oder Port 443 umleitet. Durch das Übergeben des `X-Forwarded-Proto: https` Headers wird diese Umleitung deaktiviert.

Der Lastausgleich oder Proxy muss so konfiguriert werden, dass er Folgendes unterstützt:

* *WebSocket* Verbindungen
* *SPDY* / *HTTP/2* Protokolle
* Übergeben / Setzen der folgenden Header:
+
|===
| Kopftext | Wert | Beschreibung

| `Host`
| Hostname, der verwendet wird, um Rancher zu erreichen.
| Um den vom Client angeforderten Server zu identifizieren.

| `X-Forwarded-Proto`
| `https`
| Um das Protokoll zu identifizieren, das ein Client verwendet hat, um sich mit dem Lastausgleich oder Proxy zu verbinden. *Hinweis:* Wenn dieser Header vorhanden ist, `rancher/rancher` leitet HTTP nicht auf HTTPS um.

| `X-Forwarded-Port`
| Port, der verwendet wird, um Rancher zu erreichen.
| Um das Protokoll zu identifizieren, das der Client verwendet hat, um sich mit dem Lastausgleich oder Proxy zu verbinden.

| `X-Forwarded-For`
| IP der Clientverbindung.
| Um die ursprüngliche IP-Adresse eines Clients zu identifizieren.
|===

[#_example_nginx_configuration]
=== Beispiel NGINX-Konfiguration

Diese NGINX-Konfiguration wurde auf NGINX 1.14 getestet.

[NOTE]
====

Diese NGINX-Konfiguration ist nur ein Beispiel und passt möglicherweise nicht zu Ihrer Umgebung. Für die vollständige Dokumentation siehe https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/[NGINX Load Balancing - HTTP Load Balancing].
====


* Ersetzen Sie `rancher-server` durch die IP-Adresse oder den Hostnamen des Knotens, der den Rancher-Container ausführt.
* Ersetzen Sie beide Vorkommen von `FQDN` durch den DNS-Namen für Rancher.
* Ersetzen Sie `/certs/fullchain.pem` und `/certs/privkey.pem` durch den Speicherort des Serverzertifikats und des Serverzertifikatsschlüssels.

----
worker_processes 4;
worker_rlimit_nofile 40000;

events {
    worker_connections 8192;
}

http {
    upstream rancher {
        server rancher-server:80;
    }

    map $http_upgrade $connection_upgrade {
        default Upgrade;
        ''      close;
    }

    server {
        listen 443 ssl http2;
        server_name FQDN;
        ssl_certificate /certs/fullchain.pem;
        ssl_certificate_key /certs/privkey.pem;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://rancher;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
            proxy_read_timeout 900s;
            proxy_buffering off;
        }
    }

    server {
        listen 80;
        server_name FQDN;
        return 301 https://$server_name$request_uri;
    }
}
----

{blank}

[#_whats_next]
== Was kommt als Nächstes?

* *Empfohlen:* Überprüfen Sie die Einzelknoten-xref:[Sicherung] und xref:[Wiederherstellung]. Obwohl Sie derzeit keine Daten haben, die Sie sichern müssen, empfehlen wir, nach regelmäßigem Rancher-Gebrauch Sicherungen zu erstellen.
* Erstellen Sie einen Kubernetes-Cluster: {xref-cluster-deployment}[Bereitstellung von Kubernetes-Clustern].

{blank}

[#_faq_and_troubleshooting]
== FAQ und Fehlerbehebung

Für Hilfe bei der Fehlersuche von Zertifikaten siehe {xref-certificate-troubleshooting}[diesen Abschnitt.]

[#_advanced_options]
== Erweiterte Optionen

[#_api_auditing]
=== API-Auditierung

Wenn Sie alle Transaktionen mit der Rancher API aufzeichnen möchten, aktivieren Sie die {xref-enable-api-audit-log}[API Auditing]-Funktion, indem Sie die untenstehenden Flags in Ihren Installationsbefehl einfügen.

 -e AUDIT_LEVEL=1 \
 -e AUDIT_LOG_ENABLED=true \
 -e AUDIT_LOG_PATH=/var/log/auditlog/rancher-api-audit.log \
 -e AUDIT_LOG_MAXAGE=20 \
 -e AUDIT_LOG_MAXBACKUP=20 \
 -e AUDIT_LOG_MAXSIZE=100 \

[#_air_gap]
=== Air Gap

Wenn Sie diese Seite besuchen, um eine {xref-air-gap}[Air Gap Installation] abzuschließen, müssen Sie Ihre private Registry-URL dem Server-Tag voranstellen, wenn Sie den Installationsbefehl in der von Ihnen gewählten Option ausführen. Fügen Sie `<REGISTRY.DOMAIN.COM:PORT>` mit Ihrer privaten Registry-URL vor `rancher/rancher:latest` hinzu.

*Beispiel:*

  <REGISTRY.DOMAIN.COM:PORT>/rancher/rancher:latest

[#_persistent_data]
=== Persistente Daten

Rancher verwendet etcd als Datenspeicher. Wenn Rancher mit Docker installiert ist, wird das eingebettete etcd verwendet. Die persistenten Daten befinden sich im folgenden Pfad im Container: `/var/lib/rancher`.

Sie können ein Host-Volume an diesem Ort binden, um Daten auf dem Host, auf dem es läuft, zu speichern:

----
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v /opt/rancher:/var/lib/rancher \
  --privileged \
  rancher/rancher:latest
----

Dieser Vorgang erfordert xref:#_privileged_access_for_rancher[privilegierten Zugriff].

Diese Layer-7-NGINX-Konfiguration wurde mit NGINX Version 1.13 (Mainline) und 1.14 (Stable) getestet.

[NOTE]
====

Diese NGINX-Konfiguration ist nur ein Beispiel und passt möglicherweise nicht zu Ihrer Umgebung. Für die vollständige Dokumentation siehe https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/[NGINX Load Balancing – TCP und UDP Load Balancer].
====


----
upstream rancher {
    server rancher-server:80;
}

map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

server {
    listen 443 ssl http2;
    server_name rancher.yourdomain.com;
    ssl_certificate /etc/your_certificate_directory/fullchain.pem;
    ssl_certificate_key /etc/your_certificate_directory/privkey.pem;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
        proxy_buffering off;
    }
}

server {
    listen 80;
    server_name rancher.yourdomain.com;
    return 301 https://$server_name$request_uri;
}
----

{blank}
