= Einrichten von Knoten in Amazon EC2
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc 
:product-path: installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-set-up-cloud-providers: xref:how-to-guides/neue-benutzeranleitungen/kubernetes-cluster-in-rancher-einrichten/cloud-anbieter-einrichten/index.adoc
endif::[]

In diesem Tutorial lernen Sie eine Möglichkeit kennen, Linux-Knoten für den Rancher-Management-Server einzurichten. Diese Knoten erfüllen die Knotenanforderungen für {xref-install-reqs}[Betriebssystem, Docker, Hardware und Netzwerk.]

Wenn der Rancher-Server in einem RKE-Kubernetes-Cluster installiert wird, sollten Sie drei Instanzen bereitstellen.

Wenn der Rancher-Server in einem K3s-Kubernetes-Cluster installiert wird, müssen Sie nur zwei Instanzen bereitstellen.

Wenn der Rancher-Server in einem einzelnen Docker-Container installiert ist, benötigen Sie nur eine Instanz.

[#_1_optional_preparation]
== 1. Optionale Vorbereitung

* *IAM-Rolle erstellen:* Um Rancher zu ermöglichen, AWS-Ressourcen zu manipulieren, wie z.B. neuen Speicher oder neue Knoten bereitzustellen, müssen Sie Amazon als Cloud-Anbieter konfigurieren. Es gibt mehrere Dinge, die Sie tun müssen, um den Cloud-Anbieter auf EC2 einzurichten, aber ein Teil dieses Prozesses besteht darin, eine IAM-Rolle für die Rancher-Serverknoten einzurichten. Für die vollständigen Details zur Einrichtung des Cloud-Anbieters verweisen Sie auf diese {xref-set-up-cloud-providers}[Seite.]
* *Sicherheitsgruppe erstellen:* Wir empfehlen ebenfalls, eine Sicherheitsgruppe für die Rancher-Knoten einzurichten, die den {xref-install-reqs}#_port_requirements[Portanforderungen für Rancher-Knoten] entspricht.

[#_2_provision_instances]
== 2. Instanzen bereitstellen

. Melden Sie sich bei der https://console.aws.amazon.com/ec2/[Amazon AWS EC2-Konsole] an, um zu beginnen. Stellen Sie sicher, dass Sie die *Region* notieren, in der Ihre EC2-Instanzen (Linux-Knoten) erstellt werden, da die gesamte Infrastruktur für den Rancher-Management-Server in derselben Region sein sollte.
. Klicken Sie im linken Bereich auf *Instanzen*.
. Klicken Sie auf *Instanz starten*.
. Im Abschnitt mit dem Titel *Schritt 1: Wählen Sie ein Amazon Machine Image (AMI),* wir verwenden Ubuntu 18.04 als das Linux-Betriebssystem, unter Verwendung von `ami-0d1cd67c26f5fca19 (64-bit x86)`. Gehen Sie zum Ubuntu AMI und klicken Sie auf *Auswählen*.
. Im *Schritt 2: Wählen Sie im Abschnitt * den `t2.medium` Typ aus.
. Klicken Sie auf *Weiter: Instanzendetails konfigurieren*.
. Geben Sie im Feld *Anzahl der Instanzen* die Anzahl der Instanzen ein. Ein hochverfügbares K3s-Cluster benötigt nur zwei Instanzen, während ein hochverfügbares RKE-Cluster drei Instanzen benötigt.
. Optional: Wenn Sie eine IAM-Rolle für Rancher erstellt haben, um AWS-Ressourcen zu verwalten, wählen Sie die neue IAM-Rolle im Feld *IAM-Rolle* aus.
. Klicken Sie auf *Weiter: Speicher hinzufügen,* *Weiter: Tags hinzufügen,* und *Weiter: Sicherheitsgruppe konfigurieren*.
. In *Schritt 6: Konfigurieren Sie die Sicherheitsgruppe,* wählen Sie eine Sicherheitsgruppe aus, die den {xref-install-reqs}#_port_requirements[Portanforderungen] für Rancher-Knoten entspricht.
. Klicken Sie auf *Überprüfen und Starten*.
. Klicken Sie auf *Starten*.
. Wählen Sie ein neues oder vorhandenes Schlüsselpaar aus, das Sie später verwenden werden, um sich mit Ihrer Instanz zu verbinden. Wenn Sie ein vorhandenes Schlüsselpaar verwenden, stellen Sie sicher, dass Sie bereits Zugriff auf den privaten Schlüssel haben.
. Klicken Sie auf *Instanzen starten*.

*Ergebnis:* Sie haben Rancher-Knoten erstellt, die die Anforderungen an das Betriebssystem, die Hardware und das Netzwerk erfüllen.

[NOTE]
====

Wenn die Knoten für ein RKE-Kubernetes-Cluster verwendet werden, installieren Sie im nächsten Schritt Docker auf jedem Knoten. Für ein K3s-Kubernetes-Cluster sind die Knoten jetzt bereit, um K3s zu installieren.
====


[#_3_install_docker_and_create_user_for_rke_kubernetes_cluster_nodes]
== 3. Installieren Sie Docker und erstellen Sie einen Benutzer für RKE Kubernetes-Cluster-Knoten.

. Klicken Sie im https://console.aws.amazon.com/ec2/[AWS EC2-Konsole,] auf *Instanzen* im linken Bereich.
. Gehen Sie zu der Instanz, auf der Sie Docker installieren möchten. Wählen Sie die Instanz aus und klicken Sie auf menu:Aktionen[Verbinden].
. Verbinden Sie sich mit der Instanz, indem Sie den Anweisungen auf dem Bildschirm folgen, der erscheint. Kopieren Sie die Public DNS der Instanz. Ein Beispielbefehl, um sich per SSH mit der Instanz zu verbinden, lautet wie folgt:
+
----
sudo ssh -i [path-to-private-key] ubuntu@[public-DNS-of-instance]
----

. Führen Sie den folgenden Befehl auf der Instanz aus, um Docker mit einem der Installationsskripte von Rancher zu installieren:
+
----
curl https://releases.rancher.com/install-docker/18.09.sh | sh
----

. Wenn Sie mit der Instanz verbunden sind, führen Sie den folgenden Befehl auf der Instanz aus, um einen Benutzer zu erstellen:
+
----
sudo usermod -aG docker ubuntu
----

. Wiederholen Sie diese Schritte, damit Docker auf jedem Knoten installiert ist, der schließlich den Rancher-Management-Server ausführen wird.

[TIP]
====

Um herauszufinden, ob ein Skript zur Installation einer bestimmten Docker-Version verfügbar ist, beziehen Sie sich auf dieses https://github.com/rancher/install-docker[GitHub-Repository,], das alle Skripte von Rancher für die Docker-Installation enthält.
====


*Ergebnis:* Sie haben Rancher-Serverknoten eingerichtet, die alle Anforderungen für das Betriebssystem, Docker, Hardware und Netzwerk erfüllen.

[#_next_steps_for_rke_kubernetes_cluster_nodes]
== Nächste Schritte für RKE Kubernetes-Cluster-Knoten

Wenn Sie einen RKE-Cluster auf den neuen Knoten installieren möchten, beachten Sie die *IPv4-Öffentliche IP* und *Private IP* jedes Knotens. Diese Informationen finden Sie im *Beschreibung*-Tab für jeden Knoten, nachdem er erstellt wurde. Die öffentliche und private IP wird verwendet, um die `address` und `internal_address` jedes Knotens in der RKE-Konfigurationsdatei, `rancher-cluster.yml`, auszufüllen.

RKE benötigt auch Zugriff auf den privaten Schlüssel, um sich mit jedem Knoten zu verbinden. Daher möchten Sie möglicherweise den Pfad zu Ihren privaten Schlüsseln notieren, um sich mit den Knoten zu verbinden, der ebenfalls im `rancher-cluster.yml` unter der `ssh_key_path`-Direktive für jeden Knoten enthalten sein kann.
