= Best Practices für den {rancher-product-name} Server
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-server/index.adoc 
:product-path: installation-and-upgrade/best-practices/best-practices.adoc
ifeval::["{build-type}" != "community"]
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-rancher-on-vsphere: xref:installation-and-upgrade/best-practices/rancher-on-vsphere.adoc
:xref-deployment-strategy: xref:installation-and-upgrade/best-practices/deployment-strategy.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-rancher-on-vsphere: xref:reference-guides/best-practices/rancher-server/on-premises-rancher-in-vsphere.adoc
:xref-deployment-strategy: xref:reference-guides/best-practices/rancher-server/rancher-deployment-strategy.adoc
endif::[]

Dieser Leitfaden enthält unsere Empfehlungen für den Betrieb des Rancher-Servers und ist für Situationen gedacht, in denen Rancher Downstream Kubernetes-Cluster verwaltet.

[#_recommended_architecture_and_infrastructure]
== Empfohlene Architektur und Infrastruktur

Siehe diesen {xref-tips-for-running-rancher}[Leitfaden] für unsere allgemeinen Ratschläge zur Einrichtung des Rancher-Servers für eine Produktionsinstallation.

[#_deployment_strategies]
== Installationsstrategien

Dieser {xref-deployment-strategy}[Leitfaden] soll Ihnen helfen zu entscheiden, ob eine regionale Implementierungsstrategie oder eine Hub-and-Spoke-Implementierungsstrategie besser für einen Rancher-Server geeignet ist, der Downstream Kubernetes-Cluster verwaltet.

[#_installing_rancher_in_a_vmware_vsphere_environment]
== Installation von Rancher in einer VMware vSphere-Umgebung

Dieser {xref-rancher-on-vsphere}[Leitfaden] skizziert eine Referenzarchitektur für die Installation von Rancher in einer vSphere-Umgebung, zusätzlich zu den standardmäßigen vSphere-Best Practices, wie sie von VMware dokumentiert sind.
