= {rancher-product-name} Implementierungsstrategie
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-server/rancher-deployment-strategy.adoc 
:product-path: installation-and-upgrade/best-practices/deployment-strategy.adoc

Es gibt zwei empfohlene Implementierungsstrategien für eine Rancher-Instanz, die Downstream-Kubernetes-Cluster verwaltet. Jede hat ihre eigenen Vor- und Nachteile. Erfahren Sie mehr darüber, welche am besten zu Ihrem Anwendungsfall passt.

[#_hub_spoke_strategy]
== Hub- und Spoke-Strategie

'''

In diesem Implementierungsszenario gibt es eine einzelne Rancher-Instanz, die Kubernetes-Cluster weltweit verwaltet. Die Rancher-Instanz würde auf einem Kubernetes-Cluster mit hoher Verfügbarkeit betrieben, und es würde aufgrund von Latenzen zu Auswirkungen kommen.

[#_pros]
=== Vorteile

* Einzelne Steuerungsebene, um alle Regionen und Umgebungen zu sehen.
* Kubernetes benötigt Rancher nicht zum Betrieb und kann den Verlust der Verbindung zur Rancher-Instanz tolerieren.

[#_cons]
=== Nachteile

* Unterliegt einer niedrigeren Netzwerk-Latenz.
* Wenn Rancher ausfällt, ist die globale Bereitstellung neuer Dienste nicht verfügbar, bis es wiederhergestellt ist. Allerdings kann jeder Kubernetes-Cluster weiterhin individuell verwaltet werden.

[#_regional_strategy]
== Regionale Strategie

'''

Im regionalen Implementierungsmodell wird eine Rancher-Instanz in unmittelbarer Nähe zu den Downstream-Kubernetes-Clustern bereitgestellt.

[#_pros_1]
=== Vorteile

* Die Rancher-Funktionalität in den Regionen bleibt betriebsbereit, wenn eine Rancher-Instanz in einer anderen Region ausfällt.
* Die Netzwerk-Latenz zwischen Rancher und Downstream-Clustern wird erheblich reduziert, was die Leistung der Funktionalität in Rancher verbessert.
* Upgrades von Rancher können pro Region unabhängig durchgeführt werden.

[#_cons_1]
=== Nachteile

* Mehraufwand bei der Verwaltung mehrerer Rancher-Installationen.
* Die Sichtbarkeit in Kubernetes-Clustern in verschiedenen Regionen erfordert mehrere Schnittstellen/Ansichten.
* Das Bereitstellen von Multi-Cluster-Anwendungen in Rancher erfordert, dass der Prozess für jeden Rancher-Server wiederholt wird.
