= Über Installationen mit hoher Verfügbarkeit
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-cluster-setup/high-availability-installs.adoc 
:product-path: installation-and-upgrade/best-practices/high-availability-installs.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-architecture: xref:about-rancher/architecture/architecture.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
endif::[]

Wir empfehlen die Verwendung von Helm, einem Kubernetes-Paketmanager, um Rancher auf einem dedizierten Kubernetes-Cluster zu installieren. Dies wird als Kubernetes-Installation mit hoher Verfügbarkeit bezeichnet, da eine erhöhte Verfügbarkeit erreicht wird, indem Rancher auf mehreren Knoten ausgeführt wird.

Bei einer Standardinstallation wird Kubernetes zunächst auf drei Knoten installiert, die bei einem Infrastruktur-Anbieter wie Amazons EC2 oder Google Compute Engine gehostet werden.

Anschließend wird Helm verwendet, um Rancher auf dem Kubernetes-Cluster zu installieren. Helm verwendet das Helm-Chart von Rancher, um eine Kopie von Rancher auf jedem der drei Knoten im Kubernetes-Cluster zu installieren. Wir empfehlen die Verwendung eines Lastenausgleichers, um den Datenverkehr an jede Kopie von Rancher im Cluster zu leiten, um die Verfügbarkeit von Rancher zu erhöhen.

Die Daten des Rancher-Servers werden auf etcd gespeichert. Diese etcd-Datenbank läuft ebenfalls auf allen drei Knoten und erfordert eine ungerade Anzahl von Knoten, damit sie immer einen Leader mit einer Mehrheit des etcd-Clusters wählen kann. Wenn die etcd-Datenbank keinen Leader wählen kann, kann etcd ausfallen, was erfordert, dass der Cluster aus einer Sicherung wiederhergestellt wird.

Für Informationen darüber, wie Rancher funktioniert, unabhängig von der Installationsmethode, siehe den {xref-rancher-architecture}[Architekturabschnitt.]

[#_recommended_architecture]
== Empfohlene Architektur

* DNS für Rancher sollte auf einen Layer-4-Lastenausgleicher auflösen
* Der Lastenausgleicher sollte die Ports TCP/80 und TCP/443 an alle 3 Knoten im Kubernetes-Cluster weiterleiten.
* Der Ingress-Controller wird HTTP auf HTTPS umleiten und SSL/TLS an Port TCP/443 terminieren.
* Der Ingress-Controller wird den Datenverkehr an Port TCP/80 im Pod der Rancher-Bereitstellung weiterleiten.

.Kubernetes Rancher-Installation mit Layer-4-Lastenausgleicher, der die SSL-Terminierung an Ingress-Controllern darstellt
image::ha/rancher2ha.svg[High-availability Kubernetes Installation of Rancher]
