= Installation von {rancher-product-name} in einer VMware vSphere-Umgebung
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-server/on-premises-rancher-in-vsphere.adoc 
:product-path: installation-and-upgrade/best-practices/rancher-on-vsphere.adoc
ifeval::["{build-type}" != "community"]
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
endif::[]

Dieser Leitfaden beschreibt eine Referenzarchitektur für die Installation von Rancher auf einem RKE Kubernetes-Cluster in einer VMware vSphere-Umgebung. Er beschreibt auch die standardmäßigen vSphere-Best Practices, wie sie von VMware dokumentiert sind.

.Lösung
image::rancher-on-prem-vsphere.svg[Lösungsübersicht]

[#_1_load_balancer_considerations]
== 1. Überlegungen zum Lastenausgleich

Ein Load Balancer ist erforderlich, um den Datenverkehr zu den Rancher-Arbeitslasten, die auf den RKE-Knoten liegen, zu leiten.

[#_leverage_fault_tolerance_and_high_availability]
=== Nutzen Sie Fehlertoleranz und hohe Verfügbarkeit

Nutzen Sie einen externen (Hardware- oder Software-) Load Balancer, der über Funktionen für hohe Verfügbarkeit verfügt (F5, NSX-T, Keepalived usw.).

[#_back_up_load_balancer_configuration]
=== Sichern Sie die Konfiguration des Lastenausgleichers

Im Falle einer Katastrophenwiederherstellungsaktivität wird die Verfügbarkeit der Load Balancer-Konfiguration den Wiederherstellungsprozess beschleunigen.

[#_configure_health_checks]
=== Konfigurieren Sie Gesundheitsprüfungen

Konfigurieren Sie den Load Balancer so, dass Knoten automatisch als nicht verfügbar markiert werden, wenn eine Gesundheitsprüfung fehlschlägt. Zum Beispiel kann NGINX dies ermöglichen mit:

`max_fails=3 fail_timeout=5s`

[#_leverage_an_external_load_balancer]
=== Nutzen Sie einen externen Load Balancer

Vermeiden Sie die Implementierung eines Software-Load Balancers innerhalb des Verwaltungsclusters.

[#_secure_access_to_rancher]
=== Sichern Sie den Zugriff auf Rancher

Konfigurieren Sie geeignete Firewall-/ACL-Regeln, um den Zugriff auf Rancher nur freizugeben.

[#_2_vm_considerations]
== 2. VM-Überlegungen

[#_size_the_vms_according_to_rancher_documentation]
=== Größen der VMs gemäß der Rancher-Dokumentation festlegen

Siehe {xref-install-reqs}[Installationsanforderungen].

[#_leverage_vm_templates_to_construct_the_environment]
=== Nutzen Sie VM-Vorlagen, um die Umgebung zu erstellen.

Um die Konsistenz der in der Umgebung bereitgestellten virtuellen Maschinen zu gewährleisten, ziehen Sie die Verwendung von "Golden Images" in Form von VM-Vorlagen in Betracht. Packer kann verwendet werden, um dies zu erreichen und bietet größere Anpassungsoptionen.

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_rancher_cluster_nodes_across_esxi_hosts]
=== Nutzen Sie DRS-Anti-Affinitätsregeln (wo möglich), um Rancher-Cluster-Knoten über ESXi-Hosts zu trennen.

Dadurch wird sichergestellt, dass die Knoten-VMs über mehrere ESXi-Hosts verteilt sind, wodurch ein einzelner Ausfallpunkt auf Host-Ebene verhindert wird.

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_rancher_cluster_nodes_across_datastores]
=== Nutzen Sie DRS-Anti-Affinitätsregeln (wo möglich), um Rancher-Cluster-Knoten über Datenspeicher zu trennen.

Dadurch wird sichergestellt, dass die Knoten-VMs über mehrere Datenspeicher verteilt sind, wodurch ein einzelner Ausfallpunkt auf Datenspeicher-Ebene verhindert wird.

[#_configure_vms_as_appropriate_for_kubernetes]
=== Konfigurieren Sie die VMs entsprechend für Kubernetes.

Es ist wichtig, die besten Praktiken von K8s und etcd zu befolgen, wenn Sie Ihre Knoten bereitstellen, einschließlich der Deaktivierung von Swap, der Überprüfung, dass Sie eine vollständige Netzwerkverbindung zwischen allen Maschinen im Cluster haben, und der Verwendung einzigartiger Hostnamen, MAC-Adressen und product_uuids für jeden Knoten.

[#_3_network_considerations]
== 3. Netzwerküberlegungen

[#_leverage_low_latency_high_bandwidth_connectivity_between_etcd_nodes]
=== Nutzen Sie eine Verbindung mit niedriger Latenz und hoher Bandbreite zwischen ETCD-Knoten.

Setzen Sie etcd-Mitglieder nach Möglichkeit innerhalb eines einzelnen Rechenzentrums ein, um Latenzüberhänge zu vermeiden und die Wahrscheinlichkeit einer Netzwerkpartitionierung zu verringern. Für die meisten Setups reichen 1Gb-Verbindungen aus. Für große Cluster können 10Gb-Verbindungen die Zeit zum Wiederherstellen aus einer Sicherung verkürzen.

[#_consistent_ip_addressing_for_vms]
=== Konsistente IP-Adressierung für VMs.

Jeder verwendete Knoten sollte eine statische IP konfiguriert haben. Im Falle von DHCP sollte jeder Knoten eine DHCP-Reservierung haben, um sicherzustellen, dass der Knoten die gleiche IP zugewiesen bekommt.

[#_4_storage_considerations]
== 4. Speicherüberlegungen

[#_leverage_ssd_drives_for_etcd_nodes]
=== Nutzen Sie SSD-Laufwerke für ETCD-Knoten.

ETCD ist sehr empfindlich gegenüber Schreiblatenz. Nutzen Sie SSD-Laufwerke, wo immer möglich.

[#_5_backups_and_disaster_recovery]
== 5. Sicherungen und Notfallwiederherstellung

[#_perform_regular_management_cluster_backups]
=== Führen Sie regelmäßige Sicherungen des Management-Clusters durch.

Rancher speichert seine Daten im ETCD-Datenspeicher des Kubernetes-Clusters, auf dem es sich befindet. Wie bei jedem Kubernetes-Cluster sollten Sie häufig getestete Sicherungen dieses Clusters durchführen.

[#_back_up_rancher_cluster_node_vms]
=== Sichern Sie die VMs der Rancher-Clusterknoten

Integrieren Sie die VMs des Rancher-Managementknotens in eine standardmäßige VM-Sicherungs-Richtlinie.
