= Weitere Ressourcen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/index.adoc 
:product-path: installation-and-upgrade/best-practices/resources.adoc
ifeval::["{build-type}" != "community"]
:xref-security-overview: xref:security/security-overview.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-security-overview: xref:reference-guides/rancher-security/index.adoc
endif::[]

Der Zweck dieses Abschnitts besteht darin, bewährte Praktiken für Rancher-Implementierungen zu konsolidieren. Dies umfasst auch Empfehlungen für verwandte Technologien wie Kubernetes, Docker, Container und mehr. Das Ziel ist es, das Ergebnis einer Rancher-Implementierung durch die operative Erfahrung von Rancher und seinen Kunden zu verbessern.

Wenn Sie Fragen haben, wie diese auf Ihren Anwendungsfall zutreffen könnten, wenden Sie sich bitte an Ihren Customer Success Manager oder den Support.

Verwenden Sie die Navigationsleiste auf der linken Seite, um die aktuellen bewährten Praktiken für die Verwaltung und Bereitstellung des Rancher Servers zu finden.

Für weitere Hinweise zu bewährten Praktiken können Sie diese Ressourcen konsultieren:

* {xref-security-overview}[Security]
* https://www.suse.com/c/rancherblog/[Rancher Blog]
* https://forums.rancher.com/[Rancher Forum]
* https://slack.rancher.io/[Rancher Users Slack]
* https://www.youtube.com/channel/UCh5Xtp82q8wjijP8npkVTBA/featured[Rancher Labs YouTube-Kanal - Online-Meetups, Demos, Schulungen, and Webinars]
