= 用户和组
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-09-18
:page-revdate: {revdate}
:community-path: xref:how-to-guides/新用户指南/认证权限和全局配置/认证配置/管理用户和组.adoc 
:product-path: rancher-admin/users/authn-and-authz/manage-users-and-groups.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rbac: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc
:xref-local-users: xref:rancher-admin/users/authn-and-authz/create-local-users.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rbac: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/index.adoc
:xref-local-users: xref:how-to-guides/新用户指南/认证权限和全局配置/认证配置/创建本地用户.adoc
endif::[]

Rancher依赖用户和组来确定谁被允许登录Rancher以及他们可以访问哪些资源。当您配置外部认证提供者时，该提供者的用户将能够登录到您的Rancher服务器。当用户登录时，认证提供者将向您的Rancher服务器提供用户所属的组列表。

通过将单个用户或组添加到这些资源，可以控制对集群、项目和全局DNS提供者及条目的访问。当您将组添加到资源时，认证提供者中该组的所有成员用户将能够以您为该组指定的权限访问该资源。有关角色和权限的更多信息，请参见{xref-manage-rbac}[基于角色的访问控制]。

[#_managing_members]
== 管理成员

在将用户或组添加到资源时，您可以通过开始输入他们的名称来搜索用户或组。Rancher服务器将查询认证提供者，以查找与您输入的内容匹配的用户和组。搜索仅限于您当前登录的认证提供者。例如，如果您启用了GitHub认证但使用{xref-local-users}[本地]用户帐户登录，则无法搜索GitHub用户或组。

所有用户，无论是本地用户还是来自认证提供者的用户，都可以查看和管理。在左上角，点击*☰ > 用户与身份验证*。在左侧导航栏中，点击*用户*。

[NOTE]
.SAML提供者注意事项
====
* 在Rancher中分配权限时，用户和组不会被验证。
* 添加用户时，必须正确输入确切的用户ID（即`UID Field`）。当您输入用户ID时，不会搜索可能匹配的其他用户ID。
* 添加组时，您必须从文本框旁边的下拉列表中选择该组。Rancher假设文本框中的任何输入都是用户。
* 组下拉菜单仅显示您是成员的组。但是，如果您拥有管理员权限或受限的管理员权限，您可以加入您不是成员的组。
====

[#_user_information]
== 用户信息

Rancher维护通过身份验证提供者登录的每个用户的信息。这些信息包括用户是否被允许访问您的Rancher服务器以及用户所属的组列表。Rancher保留这些用户信息，以便CLI、API和kubectl可以准确反映用户基于其在身份验证提供者中的组成员资格所拥有的访问权限。

每当用户通过身份验证提供者登录到UI时，Rancher会自动更新此用户信息。

[#_automatically_refreshing_user_information]
=== 自动刷新用户信息

Rancher会定期刷新用户信息，即使在用户通过UI登录之前。您可以控制Rancher刷新此信息的频率。

两个设置控制此行为：

* *`auth-user-info-max-age-seconds`*
+
此设置控制用户信息在Rancher刷新之前可以有多旧。如果用户发出 API 调用（无论是直接还是通过 Rancher CLI 或 kubectl），并且自上次刷新以来的时间超过此设置，则 Rancher 将触发刷新。此设置默认为 `3600` 秒，即 1 小时。

* *`auth-user-info-resync-cron`*
+
此设置控制为所有用户重新同步身份验证提供者信息的定期计划。无论用户是否最近登录或使用 API，这将导致用户在指定的时间间隔内被刷新。此设置默认为 `0 0 * * *`，即每天午夜一次。有关此设置有效值的更多信息，请参见 https://en.wikipedia.org/wiki/Cron[Cron 文档]。

要更改这些设置，

. 在左上角，单击 *☰ > 全局设置*。
. 转到您想要配置的设置并单击 *⋮ > 编辑设置*。

[NOTE]
====

由于 SAML 不支持用户查找，基于 SAML 的身份验证提供者不支持定期刷新用户信息。用户信息仅在用户登录 Rancher UI 时刷新。
====


[#_manually_refreshing_user_information]
=== 手动刷新用户信息

如果您不确定 Rancher 上次自动刷新用户信息的时间，您可以手动刷新所有用户。

. 在左上角，点击*☰ > 用户与身份验证*。
. 在 *用户* 页面上，点击 *刷新组成员资格*。

*结果：*Rancher 刷新所有用户的用户信息。请求此刷新将更新可以访问 Rancher 的用户以及每个用户所属的所有组。

[NOTE]
====

由于 SAML 不支持用户查找，基于 SAML 的身份验证提供者不支持手动刷新用户信息的功能。用户信息仅在用户登录 Rancher UI 时刷新。
====


[#_minimum_password_length]
== 最短口令长度

默认情况下，用户密码必须至少为 12 个字符。但是，您可以自定义密码长度要求：

. 在左上角，单击 *☰ > 全局设置*。
. 前往 *`password-min-length`* 并点击 *⋮ > 编辑设置*。
. 输入一个介于 2 和 256 之间的整数值，然后点击 *保存*。

[#_session_length]
== 会话时长

每个用户会话的默认时长（TTL）是可调的。默认会话时长为 16 小时。

. 在左上角，单击 *☰ > 全局设置*。
. 前往 *`auth-user-session-ttl-minutes`* 并点击 *⋮ > 编辑设置*。
. 输入会话时长应持续的分钟数，然后点击 *保存*。

*结果：*用户在设定的分钟数后会自动退出 Rancher。
