= Nutanix节点模板配置
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: 参考指南/集群配置/下游集群配置/节点模板配置/nutanix.adoc 
:product-path: cluster-deployment/infra-providers/nutanix/node-template-configuration.adoc

[#_account_access]
== 账户访问

[cols="<,^,<,<"]
|===
| 参数 | 必需 | 说明 | 默认值

| 管理端点
| ✓
| Prism Central的主机名/IP地址
|

| 用户名
| ✓
| Prism Central用户的用户名
|

| 口令
| ✓
| Prism Central用户的密码
|

| 允许不安全的通信
|
| 设置为true以允许与Prism Central的不安全SSL通信
| False
|===

[#_scheduling]
== 安排日程

选择虚拟机将被调度到哪个Nutanix集群。

[cols="<,^,<"]
|===
| 参数 | 必需 | 说明

| 群集
| ✓
| 虚拟机应部署到的Nutanix集群名称（区分大小写）
|===

[#_instance_options]
== 实例选项

在*实例选项*部分，配置由此模板创建的虚拟机的vCPU数量、内存和磁盘大小。

[cols="<,^,<,<"]
|===
| 参数 | 必需 | 说明 | 默认值

| CPU
|
| 分配给虚拟机的vCPU数量（核心）
| 2

| 内存
|
| 分配给虚拟机的RAM数量（MB）
| 2 GB

| 模板镜像
| ✓
| 作为虚拟机主磁盘克隆的磁盘镜像模板名称（必须支持cloud-init）
|

| 虚拟机磁盘大小
|
| 虚拟机主磁盘的新大小（以GiB为单位）
|

| 附加磁盘大小
|
| 要添加到虚拟机的附加磁盘大小（以GiB为单位）
|

| 存储容器
|
| 存储容器 _UUID_ 用于配置额外的磁盘
|

| 云配置 YAML
|
| Cloud-init 提供给虚拟机（将通过 Rancher 注入 root 用户）
|

| 网络
| ✓
| 要附加到虚拟机的网络名称
|

| 虚拟机类别
|
| 要应用于虚拟机的任何类别名称
|
|===

虚拟机可以使用任何现代 Linux 操作系统，该操作系统配置了对 https://cloudinit.readthedocs.io/en/latest/[cloud-init] 的支持，使用 https://cloudinit.readthedocs.io/en/latest/reference/datasources/configdrive.html[Config Drive v2 数据源]。

[#_networks]
== 网络

节点模板允许虚拟机配置多个网络。在 *网络* 字段中，您可以点击 *添加* 来添加您在 AOS 中可用的任何网络。

[#_vm_categories]
== 虚拟机类别

类别是将实体分组为键值对。通常，虚拟机根据某些标准分配到一个类别。然后，可以将策略与分配（按特定类别值分组）的实体关联。

[#_cloud_init]
== cloud-init

https://cloudinit.readthedocs.io/en/latest/[Cloud-init] 允许您通过在第一次启动时应用配置来初始化节点。这可能涉及创建用户或授权 SSH 密钥等操作。

要使用 cloud-init 初始化，请将有效 YAML 语法的云配置粘贴到 *云配置 YAML* 字段中。请参考 https://cloudinit.readthedocs.io/en/latest/topics/examples.html[cloud-init 文档]，以获取支持的云配置指令的注释示例集。

请注意，不建议使用基于 cloud-init 的网络配置，仅通过用户数据 `runcmd` 支持，而不是通过 NoCloud 或其他网络配置数据源。

建议使用 Nutanix IP 地址管理（IPAM）或其他 DHCP 服务。

[#_engine_options]
== 引擎选项

在节点模板的 *引擎选项* 部分，您可以配置容器守护程序。您可能想要指定容器版本或容器镜像注册表的镜像。

[NOTE]
====
如果您正在配置 Red Hat Enterprise Linux (RHEL) 或 CentOS 节点，请将 *Docker 安装 URL* 字段保留为默认值，或选择 *无*。这将绕过对 Docker 安装的检查，因为这些节点类型上已经安装了 Docker。

如果您将 *Docker 安装 URL* 设置为非默认值或 *无*，您可能会看到如下错误消息：`Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`
====

