= Overview
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-07-09
:page-revdate: {revdate}
:community-path: integrations-in-rancher/cluster-api/overview.adoc 
:product-path: integrations/cluster-api/overview.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-ref-capiprovider: https://documentation.suse.com/cloudnative/cluster-api/{turtles-docs-version}/en/reference/capiprovider.html
:url-capi-slsa: https://documentation.suse.com/cloudnative/cluster-api/{turtles-docs-version}/en/security/slsa.html
endif::[]
ifeval::["{build-type}" == "community"]
:xref-ref-capiprovider: https://turtles.docs.rancher.com/turtles/{turtles-docs-version}/en/reference/capiprovider.html
:url-capi-slsa: https://turtles.docs.rancher.com/turtles/{turtles-docs-version}/en/security/slsa.html
endif::[]

[NOTE]
====
The core CAPI controller manifest is embedded in a ConfigMap, which simplifies operation in air-gapped environments.
====

{turtles-product-name} is automatically deployed as a system component in the `cattle-turtles-system` namespace. This includes:

* The `rancher-turtles-controller-manager` pod, which handles all CAPI-related resources.
* Core CAPI CRDs and the core CAPI controller.
* The `CAPIProvider` custom resource, which allows declarative definition of CAPI providers.

[#_security]
== Security

As defined by https://slsa.dev/spec/v1.0/about[Supply-chain Levels for Software Artifacts (SLSA)], SLSA is a set of incrementally adoptable guidelines for supply chain security, established by industry consensus. The specification set by SLSA is useful for both software producers and consumers: producers can follow SLSA's guidelines to make their software supply chain more secure, and consumers can use SLSA to make decisions about whether to trust a software package.

{turtles-product-name} meets https://slsa.dev/spec/v1.0/levels#build-l3[SLSA Level 3] requirements as an appropriate hardened build platform, with consistent build processes, and provenance distribution. For more information, visit the {url-capi-slsa}[{turtles-product-name} Security] document.

[#_installing_capi_providers]
== Installing CAPI Providers

With {turtles-product-name} embedded in Rancher, CAPI providers are no longer bundled by default. Providers are managed declaratively using the `CAPIProvider` custom resource. 

ifeval::["{build-type}" != "community"]
A separate providers chart for Prime users is available for installing certified providers. For more information, refer to https://documentation.suse.com/cloudnative/cluster-api/{turtles-docs-version}/en/user/providers.html[Install certified providers].
endif::[]

For example, to define a provider:

[source,yaml]
----
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws
  namespace: cattle-turtles-system
spec:
  type: infrastructure
  name: aws
----

Refer to the {xref-ref-capiprovider}[CAPIProvider reference] for the full list of configuration options.

[#_uninstalling]
== Uninstalling

[CAUTION]
====
When installing {turtles-product-name} in your Rancher environment, the CAPI Operator cleanup is enabled by default. This includes cleaning up CAPI Operator specific webhooks and deployments that otherwise cause issues with Rancher provisioning.

To simplify uninstalling {turtles-product-name} (via Rancher or Helm command), the official {turtles-product-name} Helm chart includes a `post-delete` hook that removes the following:

* Deletes the `mutating-webhook-configuration` and `validating-webhook-configuration` webhooks that are no longer needed.
* Deletes the CAPI `deployments` that are no longer needed.
====

To uninstall {turtles-product-name}:

[,bash]
----
helm uninstall -n cattle-turtles-system rancher-turtles --cascade foreground --wait
----

This may take a few minutes to complete.

[NOTE]
====
Remember that, if you use a different name for the installation or a different namespace, you may need to customize the command for your specific configuration.
====


After {turtles-product-name} is uninstalled, Rancher's `embedded-cluster-api` feature must be re-enabled:

. Create a `feature.yaml` file, with `embedded-cluster-api` set to true:
+
.feature.yaml
[,yaml]
----
apiVersion: management.cattle.io/v3
kind: Feature
metadata:
  name: embedded-cluster-api
spec:
  value: true

----

. Use `kubectl` to apply the `feature.yaml` file to the cluster:
+
[,bash]
----
kubectl apply -f feature.yaml
----