= 1.インフラストラクチャとプライベートレジストリの設定
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/infrastructure-private-registry.adoc 
:product-path: installation-and-upgrade/other-installation-methods/air-gapped/infrastructure-private-registry.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-setup-ec2-nodes: xref:installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:installation-and-upgrade/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:installation-and-upgrade/infrastructure-setup/amazon-elb-load-balancer.adoc
:xref-mysql-amazon-rds: xref:installation-and-upgrade/infrastructure-setup/mysql-database-in-amazon-rds.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-setup-ec2-nodes: xref:how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:how-to-guides/new-user-guides/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:how-to-guides/new-user-guides/infrastructure-setup/amazon-elb-load-balancer.adoc
:xref-mysql-amazon-rds: xref:how-to-guides/new-user-guides/infrastructure-setup/mysql-database-in-amazon-rds.adoc
endif::[]


このセクションでは、エアギャップ環境でRancher管理サーバーの基盤となるインフラストラクチャをプロビジョニングします。また、Rancherノードに利用可能なプライベートコンテナイメージレジストリを設定します。

エアギャップ環境とは、Rancherサーバーがオフラインまたはファイアウォールの背後にインストールされている環境です。

インフラストラクチャは、K3s Kubernetesクラスター、RKE Kubernetesクラスター、または単一のDockerコンテナにRancherをインストールするかどうかによって異なります。各インストールオプションの詳細については、{xref-install-upgrade}[このページを参照してください。]

Rancherは、任意のKubernetesクラスターにインストールできます。以下のRKEおよびK3s Kubernetesインフラストラクチャのチュートリアルは、便利さのために引き続き含まれています。

[tabs]
======
K3s::
+
--
高可用性のインストールのために、以下のインフラストラクチャを設定することをお勧めします：

* *2つのLinuxノード*（通常は仮想マシン）を、選択したインフラストラクチャプロバイダー内に用意します。
* *外部データベース* クラスターデータを保存するためのものです。PostgreSQL、MySQL、およびetcdがサポートされています。
* *ロードバランサー*は、2つのノードにトラフィックを振り分けます。
* *DNSレコード*は、URLをロードバランサーにマッピングします。これがRancherサーバーのURLとなり、ダウンストリームのKubernetesクラスターはこれにアクセスする必要があります。
* *プライベートイメージレジストリ*を使用して、コンテナイメージをマシンに配布します。

[#_k3s_1_set_up_linux_nodes]
[pass]
<h3><a class="anchor" id="_k3s_1_set_up_linux_nodes" href="#_k3s_1_set_up_linux_nodes"></a>1.Linuxノードのセットアップ</h3>

これらのホストはインターネットから切断されますが、プライベートレジストリに接続できる必要があります。

ノードが{xref-install-reqs}[OS、コンテナランタイム、ハードウェア、ネットワーキング]の一般的なインストール要件を満たしていることを確認してください。

Linuxノードを設定する一例については、Amazon EC2のインスタンスとしてノードを設定するためのこの{xref-setup-ec2-nodes}[チュートリアル]を参照してください。

[#_2_set_up_external_datastore]
[pass]
<h3><a class="anchor" id="_2_set_up_external_datastore" href="#_2_set_up_external_datastore"></a>2.外部データストアを設定する</h3>

etcd以外のデータストアを用いてKubernetesを実行できる機能により、K3sは他のKubernetesディストリビューションと差別化されています。この機能はKubernetesオペレーターに柔軟性を提供します。利用可能なオプションにより、ご利用のユースケースに最適なデータストアを選択できます。

高可用性のK3sインストールには、以下の外部データベースのいずれかを設定する必要があります：

* https://www.postgresql.org/[PostgreSQL]（バージョン10.7および11.5に対して認証済み）
* https://www.mysql.com/[MySQL]（バージョン5.7に対して認証済み）
* https://etcd.io/[etcd]（バージョン3.3.15に対して認証済み）

Kubernetesをインストールする際には、K3sがデータベースに接続するための詳細を渡します。

データベースの設定方法の一例については、AmazonのRDSサービスでMySQLデータベースを設定するためのこの{xref-mysql-amazon-rds}[チュートリアル]を参照してください。

K3sクラスターのデータストアを構成するために利用可能なオプションの完全なリストについては、 https://rancher.com/docs/k3s/latest/en/installation/datastore/[K3sドキュメント]を参照してください。

[#_k3s_3_set_up_the_load_balancer]
[pass]
<h3><a class="anchor" id="_k3s_3_set_up_the_load_balancer" href="#_k3s_3_set_up_the_load_balancer"></a>3.ロードバランサーの設定</h3>

Rancherのレプリカにトラフィックを誘導するために、両方のノードにロードバランサーを設定する必要があります。これにより、単一のノードの障害がRancher管理サーバーへの通信を妨げることを防ぎます。

Kubernetesが後のステップで設定されると、K3sツールがTraefik Ingressコントローラーをデプロイします。このコントローラーは、ワーカーノードのポート80および443でリスンし、特定のホスト名宛てのトラフィックに応答します。

Rancherがインストールされると（これも後のステップで）、RancherシステムはIngressリソースを作成します。そのIngressは、Traefik IngressコントローラーにRancherのホスト名宛てのトラフィックをリスンするよう指示します。Traefik Ingressコントローラーは、Rancherのホスト名宛てのトラフィックを受信すると、そのトラフィックをクラスター内の実行中のRancherポッドに転送します。

実装において、レイヤー4またはレイヤー7のロードバランサーを使用するかどうかを検討してください：

* *レイヤー4のロードバランサー*は、ノードにTCPトラフィックを転送するという点で、2つの選択肢の中でよりシンプルです。ロードバランサーをレイヤー4バランサーとして構成し、TCP/80およびTCP/443のポートにトラフィックをRancher管理クラスターのノードに転送することをお勧めします。クラスター内のIngressコントローラーは、HTTPトラフィックをHTTPSにリダイレクトし、ポートTCP/443でSSL/TLSを終了します。Ingressコントローラーは、Rancherデプロイメント内のIngressポッドにTCP/80のポートへのトラフィックを転送します。
* *レイヤー7のロードバランサー*は少し複雑ですが、必要な機能を提供することができます。例えば、レイヤー7のロードバランサーは、RancherがTLS終了を行うのではなく、ロードバランサーでTLS終了を処理することができます。これは、インフラストラクチャ内でTLS終了を集中管理したい場合に有益です。レイヤー7のロードバランシングは、レイヤー4のロードバランサーが関与できないクッキーなどのHTTP属性に基づいて、ロードバランサーが意思決定を行う能力も提供します。レイヤー7のロードバランサーでSSL/TLSトラフィックを終了することを決定した場合、後のステップでRancherをインストールする際に`--set tls=external`オプションを使用する必要があります。詳細については、{xref-helm-chart-options}#_external_tls_termination[Rancher Helmチャートオプション]を参照してください。

NGINXロードバランサーの設定方法を示す例については、{xref-nginx-load-balancer}[このページ]を参照してください。

Amazon ELBネットワークロードバランサーのセットアップに関するハウツーガイドについては、{xref-amazon-elb}[このページ]を参照してください。

[NOTE]
.重要:
====

インストール後、Rancher以外のアプリケーションのロードバランシングにこのロードバランサー（すなわち、`local`クラスターのIngress）を使用しないでください。このIngressを他のアプリケーションと共有すると、他のアプリのIngress設定のリロード後にRancherに対してウェブソケットエラーが発生する可能性があります。`local`クラスターをRancher専用にし、他のアプリケーションには使用しないことをお勧めします。
====


[#_k3s_4_set_up_the_dns_record]
[pass]
<h3><a class="anchor" id="_k3s_4_set_up_the_dns_record" href="#_k3s_4_set_up_the_dns_record"></a>4.DNSレコードを設定する</h3>

ロードバランサーを設定したら、このロードバランサーにトラフィックを送信するためのDNSレコードを作成する必要があります。

環境によっては、これはロードバランサーIPを指すAレコードであるか、ロードバランサーのホスト名を指すCNAMEである場合があります。いずれの場合でも、このレコードがRancherが応答することを意図しているホスト名であることを確認してください。

Rancherをインストールする際の後のステップでこのホスト名を指定する必要があり、後で変更することはできません。あなたの決定が最終的なものであることを確認してください。

Amazon ELBロードバランサーにドメイントラフィックをルーティングするためのDNSレコードの設定に関するハウツーガイドについては、 https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer[公式AWSドキュメントを参照してください。]

[#_k3s_5_set_up_a_private_image_registry]
[pass]
<h3><a class="anchor" id="_k3s_5_set_up_a_private_image_registry" href="#_k3s_5_set_up_a_private_image_registry"></a>5.プライベートイメージレジストリを設定する</h3>

Rancherはプライベートレジストリを使用したエアギャップインストールをサポートしています。独自のプライベートレジストリまたはコンテナイメージをマシンに配布するための他の手段を持っている必要があります。

後のステップで、K3s Kubernetesクラスターを設定する際に、このレジストリの詳細を含む https://rancher.com/docs/k3s/latest/en/installation/private-registry/[プライベートレジストリ設定ファイル]を作成します。

プライベートレジストリを作成する必要がある場合は、それぞれのランタイムのドキュメントページを参照してください。

* https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration[Containerd]。
 ** https://github.com/containerd/nerdctl/blob/main/docs/registry.md[Nerdctlコマンドと管理されたレジストリサービス]。
* https://docs.docker.com/registry/deploying/[Docker]。
--

RKE::
+
--
高可用性のRKEクラスターにRancher管理サーバーをインストールするには、以下のインフラストラクチャを設定することをお勧めします：

- **三つのLinuxノード**、通常は仮想マシンで、AmazonのEC2、Google Compute Engine、またはvSphereなどのインフラストラクチャプロバイダーに配置されます。
- **ロードバランサー** フロントエンドトラフィックを三つのノードに振り分けるため。
- **DNSレコード** URLをロードバランサーにマッピングするため。これがRancherサーバーのURLとなり、ダウンストリームのKubernetesクラスターはこれにアクセスする必要があります。
- **プライベートイメージレジストリ** コンテナイメージをマシンに配布するため。

これらのノードは同じリージョン/データセンター内に配置する必要があります。これらのサーバーは別々のアベイラビリティゾーンに配置することができます。

[#_why_three_nodes]
[pass]
<h3><a class="anchor" id="_why_three_nodes" href="#_why_three_nodes"></a>なぜ三つのノードなのか？</h3>

RKEクラスターでは、Rancherサーバーのデータはetcdに保存されます。このetcdデータベースは3つのノードすべてで実行されます。

etcdデータベースは、常にetcdクラスターの過半数でリーダーを選出できるように、奇数のノード数を必要とします。etcdデータベースがリーダーを選出できない場合、 https://www.quora.com/What-is-split-brain-in-distributed-systems[スプリットブレイン]が発生し、クラスターをバックアップから復元する必要があります。三つのetcdノードのうち一つが故障した場合、残りの二つのノードはetcdノードの総数の過半数を持っているため、リーダーを選出できます。

[#_rke_1_set_up_linux_nodes]
[pass]
<h3><a class="anchor" id="_rke_1_set_up_linux_nodes" href="#_rke_1_set_up_linux_nodes"></a>1.Linuxノードのセットアップ</h3>

これらのホストはインターネットから切断されますが、プライベートレジストリに接続できる必要があります。

ノードが{xref-install-reqs}[OS、コンテナランタイム、ハードウェア、ネットワーキング]の一般的なインストール要件を満たしていることを確認してください。

Linuxノードを設定する一例については、Amazon EC2のインスタンスとしてノードを設定するためのこの{xref-setup-ec2-nodes}[チュートリアル]を参照してください。

[#_rke_2_set_up_the_load_balancer]
[pass]
<h3><a class="anchor" id="_rke_2_set_up_the_load_balancer" href="#_rke_2_set_up_the_load_balancer"></a> 2.ロードバランサーの設定</h3>

Rancherのレプリカにトラフィックを誘導するために、両方のノードにロードバランサーを設定する必要があります。これにより、単一のノードの障害がRancher管理サーバーへの通信を妨げることを防ぎます。

Kubernetesが後のステップで設定されると、RKEツールがNGINX Ingressコントローラーをデプロイします。このコントローラーは、ワーカーノードのポート80および443でリスンし、特定のホスト名宛てのトラフィックに応答します。

Rancherがインストールされると（これも後のステップで）、RancherシステムはIngressリソースを作成します。そのIngressは、NGINX IngressコントローラーにRancherのホスト名宛てのトラフィックをリスンするよう指示します。NGINX Ingressコントローラーは、Rancherのホスト名宛てのトラフィックを受信すると、そのトラフィックをクラスター内の実行中のRancherポッドに転送します。

実装において、レイヤー4またはレイヤー7のロードバランサーを使用するかどうかを検討してください：

- **レイヤー4ロードバランサー**は、2つの選択肢のうちよりシンプルで、ノードにTCPトラフィックを転送します。ロードバランサーをレイヤー4バランサーとして構成し、TCP/80およびTCP/443のポートにトラフィックをRancher管理クラスターのノードに転送することをお勧めします。クラスター内のIngressコントローラーは、HTTPトラフィックをHTTPSにリダイレクトし、ポートTCP/443でSSL/TLSを終了します。Ingressコントローラーは、Rancherデプロイメント内のIngressポッドにTCP/80のポートへのトラフィックを転送します。
- **レイヤー7ロードバランサー**は少し複雑ですが、必要な機能を提供できます。例えば、レイヤー7のロードバランサーは、RancherがTLS終了を行うのではなく、ロードバランサーでTLS終了を処理することができます。これは、インフラストラクチャ内でTLS終了を集中管理したい場合に有益です。レイヤー7のロードバランシングは、レイヤー4のロードバランサーが関与できないクッキーなどのHTTP属性に基づいて、ロードバランサーが意思決定を行う能力も提供します。レイヤー7のロードバランサーでSSL/TLSトラフィックを終了することを決定した場合、後のステップでRancherをインストールする際に`--set tls=external`オプションを使用する必要があります。詳細については、{xref-helm-chart-options}#_external_tls_termination[Rancher Helmチャートオプション]を参照してください。

NGINXロードバランサーの設定方法を示す例については、{xref-nginx-load-balancer}[このページ]を参照してください。

Amazon ELBネットワークロードバランサーの設定に関するハウツーガイドについては、{xref-amazon-elb}[このページ]を参照してください。

[CAUTION]
====
インストール後、Rancher以外のアプリケーションのロードバランシングにこのロードバランサー（すなわち、`local`クラスターのIngress）を使用しないでください。このIngressを他のアプリケーションと共有すると、他のアプリのIngress設定のリロード後にRancherに対してウェブソケットエラーが発生する可能性があります。`local`クラスターをRancher専用にし、他のアプリケーションには使用しないことをお勧めします。
====

[#_rke_3_set_up_the_dns_record]
[pass]
<h3><a class="anchor" id="_rke_3_set_up_the_dns_record" href="#_rke_3_set_up_the_dns_record"></a>3.DNSレコードを設定する</h3>

ロードバランサーを設定したら、このロードバランサーにトラフィックを送信するためのDNSレコードを作成する必要があります。

環境によっては、LB IPを指すAレコードであるか、ロードバランサーのホスト名を指すCNAMEである場合があります。いずれの場合でも、このレコードがRancherが応答することを意図しているホスト名であることを確認してください。

Rancherをインストールする際の後のステップでこのホスト名を指定する必要があり、後で変更することはできません。あなたの決定が最終的なものであることを確認してください。

Amazon ELBロードバランサーにドメイントラフィックをルーティングするためのDNSレコードの設定に関するハウツーガイドについては、 https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer[公式AWSドキュメント]を参照してください。

[#_rke_4_set_up_a_private_image_registry]
[pass]
<h3><a class="anchor" id="_rke_4_set_up_a_private_image_registry" href="#_rke_4_set_up_a_private_image_registry"></a>4.プライベートイメージレジストリを設定する</h3>

Rancherは、安全なプライベートレジストリを使用したエアギャップインストールをサポートしています。独自のプライベートレジストリまたはコンテナイメージをマシンに配布するための他の手段を持っている必要があります。

後のステップで、RKE Kubernetesクラスターを設定する際に、このレジストリの詳細を含む https://rke.docs.rancher.com/config-options/private-registries[プライベートレジストリ設定ファイル]を作成します。

プライベートレジストリを作成する必要がある場合は、それぞれのランタイムのドキュメントページを参照してください。

* https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration[Containerd]
** https://github.com/containerd/nerdctl/blob/main/docs/registry.md[Nerdctlコマンドと管理されたレジストリサービス]
* https://docs.docker.com/registry/deploying/[Docker]
--
======
