= Instalación {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/index.adoc 
:product-path: installation-and-upgrade/installation-and-upgrade.adoc
:description: Aprende a instalar Rancher en entornos de desarrollo y producción. Lee sobre la instalación en un solo nodo y en alta disponibilidad
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
:xref-rancher-architecture: xref:about-rancher/architecture/architecture.adoc
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-qs-aws-marketplace: xref:installation-and-upgrade/quick-start/deploy-rancher/aws-marketplace.adoc
:xref-http-proxy: xref:installation-and-upgrade/other-installation-methods/http-proxy/http-proxy.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-air-gap: xref:comenzando/instalación-y-actualización/otros-métodos-de-instalación/instalación-helm-cli-entorno-aislado/index.adoc
:xref-migrate-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster.adoc
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-qs-aws-marketplace: xref:getting-started/quick-start-guides/deploy-rancher-manager/aws-marketplace.adoc
:xref-http-proxy: xref:getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/index.adoc
endif::[]

Esta sección proporciona una visión general de las opciones de arquitectura para instalar Rancher, describiendo las ventajas de cada opción.

[#_terminology]
== terminología

En esta sección,

* *El servidor de Rancher* gestiona y aprovisiona clústeres de Kubernetes. Puedes interactuar con los clústeres de Kubernetes en sentido descendente a través de la interfaz de usuario del servidor de Rancher. El servidor de gestión de Rancher se puede instalar en cualquier clúster de Kubernetes, incluidos clústeres alojados, como los clústeres de Amazon EKS.
* *RKE (Rancher Kubernetes Engine)* es una distribución de Kubernetes certificada y una CLI/biblioteca que crea y gestiona un clúster de Kubernetes.
* *K3s (Kubernetes Ligero)* también es una distribución de Kubernetes totalmente conforme. Es más reciente que RKE, más fácil de usar y más ligero, con un tamaño binario de menos de 100 MB.
* *RKE2* es una distribución de Kubernetes totalmente conforme que se centra en la seguridad y el cumplimiento de las normativas en EE. UU. Gobierno federal de Estados Unidos.

[#_overview_of_installation_options]
== Visión general de las opciones de instalación

Rancher se puede instalar en estas arquitecturas principales:

[#_high_availability_kubernetes_install_with_the_helm_cli]
=== Instalación de Kubernetes de alta disponibilidad con la CLI de Helm

Recomendamos usar Helm, un gestor de paquetes de Kubernetes, para instalar Rancher en múltiples nodos en un clúster de Kubernetes dedicado. Para los clústeres de RKE, se requieren tres nodos para lograr un clúster de alta disponibilidad. Para los clústeres de K3s, solo se requieren dos nodos.

[#_rancher_on_eks_install_with_the_aws_marketplace]
=== Instalación de Rancher en EKS con el AWS Marketplace

Rancher se puede instalar en Amazon Elastic Kubernetes Service (EKS) {xref-qs-aws-marketplace}[a través del AWS Marketplace]. El clúster de EKS desplegado está listo para producción y sigue las mejores prácticas de AWS.

[#_single_node_kubernetes_install]
=== Single-node Kubernetes Install

Rancher se puede instalar en un clúster de Kubernetes de un solo nodo. En este caso, el servidor de Rancher no tiene alta disponibilidad, lo cual es importante para ejecutar Rancher en producción.

Sin embargo, esta opción es útil si deseas ahorrar recursos utilizando un solo nodo a corto plazo, mientras preservas un camino de migración a alta disponibilidad. En el futuro, puedes añadir nodos al clúster para obtener un servidor de Rancher de alta disponibilidad.

[#_docker_install]
=== Instalación de Docker

Para fines de prueba y demostración, Rancher se puede instalar con Docker en un solo nodo. Un clúster local de Kubernetes se instala en el único contenedor de Docker, y Rancher se instala en el clúster local.

El operador de copia de seguridad de Rancher se puede utilizar para migrar Rancher de la instalación de un solo contenedor de Docker a una instalación en un clúster de Kubernetes de alta disponibilidad. Para más detalles, consulta la documentación sobre {xref-migrate-cluster}[migrar Rancher a un nuevo clúster.]

[#_other_options]
=== Otras opciones

También hay instrucciones separadas para instalar Rancher en un entorno aislado o detrás de un proxy HTTP:

|===
| Nivel de Acceso a Internet | Instalación de Kubernetes - Muy Recomendado | Instalación de Docker

| Con acceso directo a Internet
| {xref-install-rancher}[Docs]
| xref:[Documentos]

| Detrás de un proxy HTTP
| {xref-http-proxy}[Docs]
| Estos xref:[docs,] más esta xref:[configuración]

| En un entorno aislado
| {xref-air-gap}[Docs]
| {xref-air-gap}[Docs]
|===

Recomendamos instalar Rancher en un clúster de Kubernetes, porque en un clúster de múltiples nodos, el servidor de gestión de Rancher se vuelve altamente disponible. Esta configuración de alta disponibilidad ayuda a mantener un acceso consistente a los clústeres de Kubernetes que Rancher gestionará.

Por esa razón, recomendamos que para una arquitectura de nivel de producción, debéis configurar un clúster de Kubernetes de alta disponibilidad y luego instalar Rancher en él. Después de que Rancher esté instalado, podéis usar Rancher para desplegar y gestionar clústeres de Kubernetes.

Para fines de prueba o demostración, podéis instalar Rancher en un único contenedor de Docker. En esta instalación de Docker, podéis usar Rancher para configurar clústeres de Kubernetes de forma inmediata. La instalación de Docker os permite explorar la funcionalidad del servidor Rancher, pero está destinada a ser utilizada solo para desarrollo y pruebas.

Nuestras {xref-install-rancher}[instrucciones para instalar Rancher en Kubernetes] describen cómo usar primero K3s o RKE para crear y gestionar un clúster de Kubernetes, y luego instalar Rancher en ese clúster.

Cuando los nodos en vuestro clúster de Kubernetes estén en funcionamiento y cumplan con los {xref-install-reqs}[requisitos de nodo,] usaréis Helm para desplegar Rancher en Kubernetes. Helm utiliza el gráfico de Helm de Rancher para instalar una réplica de Rancher en cada nodo del clúster de Kubernetes. Recomendamos usar un equilibrador de carga para dirigir el tráfico a cada réplica de Rancher en el clúster.

Para una discusión más extensa sobre la arquitectura de Rancher, consultad el {xref-rancher-architecture}[resumen de arquitectura,] {xref-arch-rec}[recomendaciones para arquitectura de nivel de producción,] o nuestra {xref-tips-for-running-rancher}[guía de mejores prácticas.]

[#_prerequisites]
== Requisitos previos

Antes de instalar Rancher, aseguraos de que vuestros nodos cumplan con todos los {xref-install-reqs}[requisitos de instalación.]

[#_architecture_tip]
== Consejo de Arquitectura

Para el mejor rendimiento y mayor seguridad, recomendamos un clúster de Kubernetes separado y dedicado para el servidor de gestión de Rancher. No se aconseja ejecutar cargas de trabajo de usuarios en este clúster. Después de desplegar Rancher, podéis {xref-cluster-deployment}[crear o importar clústeres] para ejecutar vuestras cargas de trabajo.

Para más recomendaciones de arquitectura, consultad {xref-arch-rec}[esta página.]

[#_more_options_for_installations_on_a_kubernetes_cluster]
=== Más opciones para instalaciones en un clúster de Kubernetes

Consultad las {xref-helm-chart-options}[opciones del gráfico de Helm] para detalles sobre la instalación de Rancher en un clúster de Kubernetes con otras configuraciones, incluyendo:

* Con {xref-helm-chart-options}#_api_audit_log[auditoría de API para registrar todas las transacciones]
* Con {xref-helm-chart-options}#_external_tls_termination[terminación TLS en un equilibrador de carga]
* Con un {xref-helm-chart-options}#_customizing_your_ingress[Ingress personalizado]

En las instrucciones de instalación de Rancher, recomendamos utilizar K3s o RKE para configurar un clúster de Kubernetes antes de instalar Rancher en el clúster. Tanto K3s como RKE tienen muchas opciones de configuración para personalizar el clúster de Kubernetes según tu entorno específico. Para la lista completa de sus capacidades, consulte su documentación:

* https://rancher.com/docs/rke/latest/en/config-options/[Opciones de configuración de RKE]
* https://rancher.com/docs/k3s/latest/en/installation/install-options/[Opciones de configuración de K3s]

