= Actualizaciones
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-06
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades.adoc 
:product-path: installation-and-upgrade/upgrades.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
:xref-backup-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/back-up.adoc
:xref-upgrade-certmanager: xref:installation-and-upgrade/resources/upgrade-cert-manager.adoc
:xref-air-gap-publish-images: xref:installation-and-upgrade/other-installation-methods/air-gapped/publish-images.adoc
:xref-helm-chart-in-rancher: xref:cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc
:xref-air-gap-upgrade: xref:installation-and-upgrade/other-installation-methods/air-gapped/upgrades.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap: xref:comenzando/instalación-y-actualización/otros-métodos-de-instalación/instalación-helm-cli-entorno-aislado/index.adoc
:xref-backup-cluster: xref:guías-de-cómo/nuevas-guías-de-usuario/copia-de-seguridad-recuperación-y-recuperación-de-desastres/copia-de-seguridad-rancher.adoc
:xref-upgrade-certmanager: xref:getting-started/installation-and-upgrade/resources/upgrade-cert-manager.adoc
:xref-air-gap-publish-images: xref:comenzando/instalación-y-actualización/otros-métodos-de-instalación/instalación-helm-cli-entorno-aislado/publicar-imágenes.adoc
:xref-helm-chart-in-rancher: xref:how-to-guides/new-user-guides/helm-charts-in-rancher/index.adoc
:xref-air-gap-upgrade: xref:comenzando/instalación-y-actualización/instalar-actualizar-en-un-cluster-kubernetes/actualizaciones-entorno-aislado.adoc
endif::[]

Las siguientes instrucciones te guiarán a través de la actualización de un servidor Rancher que fue instalado en un clúster de Kubernetes con Helm. Estos pasos también se aplican a instalaciones en entorno aislado con Helm.

Para las instrucciones para actualizar Rancher instalado con Docker, consulta xref:[esta página.]

[#_prerequisites]
== Requisitos previos

[#_access_to_kubeconfig]
=== Acceso a kubeconfig

Helm debe ejecutarse desde la misma ubicación que tu archivo kubeconfig, o desde la misma ubicación donde ejecutas tus comandos kubectl.

Si instalaste Kubernetes con RKE2/K3s, el Kubeconfig se almacena en el directorio `/etc/rancher/rke2/rke2.yaml` o `/etc/rancher/k3s/k3s.yaml` dependiendo de tu distribución elegida.

El kubeconfig también puede ser dirigido manualmente para el clúster previsto con la etiqueta `--kubeconfig` (ver: https://helm.sh/docs/helm/helm/)

[#_review_known_issues]
=== Revisar Problemas Conocidos

Revisa la lista de problemas conocidos para cada versión de Rancher, que se puede encontrar en las notas de la versión en https://github.com/rancher/rancher/releases[GitHub] y en los https://forums.rancher.com/c/announcements/12[foros de Rancher.]

[#_helm_version]
=== Versión de Helm

Las instrucciones de actualización asumen que estás utilizando Helm 3.

[#_for_air_gapped_installs_populate_private_registry]
=== Para instalaciones en entorno aislado: Poblar el registro privado

Para {xref-air-gap}[instalaciones en entorno aislado únicamente,] recopila y carga las imágenes para la nueva versión del servidor Rancher. Sigue la guía para {xref-air-gap-publish-images}[poblar tu registro privado] con las imágenes de la versión de Rancher a la que deseas actualizar.

[#_for_upgrades_with_cert_manager_older_than_0_8_0]
=== Para las actualizaciones con cert-manager anteriores a 0.8.0

https://community.letsencrypt.org/t/blocking-old-cert-manager-versions/98753[Let's Encrypt bloqueará las instancias de cert-manager anteriores a 0.8.0 a partir del 1 de noviembre de 2019.] Actualiza cert-manager a la última versión siguiendo {xref-upgrade-certmanager}[estas instrucciones.]

[#_upgrade_outline]
== Esquema de actualización

Sigue los pasos para actualizar el servidor Rancher:

[#_1_back_up_your_kubernetes_cluster_that_is_running_rancher_server]
=== 1. Haz una copia de seguridad de tu clúster de Kubernetes que está ejecutando el servidor Rancher

Utiliza la {xref-backup-cluster}[aplicación de copia de seguridad] para hacer una copia de seguridad de Rancher.

Utilizarás la copia de seguridad como un punto de restauración si algo sale mal durante la actualización.

[#_2_update_the_helm_chart_repository]
=== 2. Actualiza el repositorio del gráfico de Helm

. Actualiza la caché de tu repositorio local de Helm.
+
----
helm repo update
----

. Obtén el nombre del repositorio que utilizaste para instalar Rancher.
+
----
helm repo list

NAME                     URL
rancher-prime          <helm-chart-repo-url>
----

. Descarga el gráfico más reciente para instalar Rancher desde el repositorio de gráficos de Helm.
+
Este comando descargará los gráficos más recientes y los guardará en el directorio actual como un archivo `.tgz`.
+
[,plain]
----
 helm fetch rancher-prime/rancher
----
+
Puedes obtener el gráfico para la versión específica a la que estás actualizando añadiendo la etiqueta `--version=`.  Por ejemplo:
+
[,plain]
----
 helm fetch rancher-prime/rancher --version={current-patch-version}
----

[#_3_review_rancher_feature_chart_versions_before_upgrade]
=== 3. Revisa las versiones del gráfico de características de Rancher antes de la actualización

Los gráficos de características de Rancher siguen líneas de lanzamiento específicas que se alinean con las versiones de Rancher. Las versiones principales de los gráficos de características corresponden a las versiones menores de Rancher y siguen un esquema de versionado definido.

Antes de actualizar Rancher, revisa los gráficos de características instalados y actualízalos a la última versión disponible dentro de su línea de lanzamiento actual. Esto ayuda a garantizar la compatibilidad y evita problemas potenciales durante o después de la actualización de Rancher.

Para revisar los gráficos de características instalados:

1. En la interfaz de usuario de Rancher, ve a **Apps & Marketplace**.
2. Selecciona **Installed Apps**.
3. Revisa las versiones de los gráficos y actualiza a la última versión de parche dentro de la misma versión principal del gráfico si es necesario.

Para más información, consulta el {xref-helm-chart-in-rancher}#_versioning_scheme[Gráficos de Helm en Rancher – Esquema de Versionado].

[#_4_upgrade_rancher]
=== 4. Actualizar Rancher

Esta sección describe cómo actualizar instalaciones normales (conectadas a Internet) o instalaciones en entorno aislado de Rancher con Helm.

[NOTE]
.Instrucciones para instalaciones en entorno aislado:
====

Si estás instalando Rancher en un entorno aislado, omite el resto de esta página y genera la plantilla de Helm siguiendo las instrucciones en {xref-air-gap-upgrade}[esta página].
====

[IMPORTANT]
.Actualizando desde Rancher v2.13.1
====
En Rancher v2.13.2, el nombre del gráfico de Helm ha vuelto de `rancher-prime` a `rancher`. Si estás actualizando desde v2.13.1, el recurso Ingress existente creado por el gráfico anterior entra en conflicto con el nuevo, causando que la actualización falle con un error similar a:

[,shell]
----
Error: UPGRADE FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "rancher.my.org" and path "/" is already defined in ingress cattle-system/rancher-rancher-prime
----

Para prevenir o resolver este problema, debes eliminar manualmente el antiguo Ingress antes de completar la actualización:

[,shell]
----
kubectl delete ingress rancher-rancher-prime -n cattle-system
----
====

Obtén los valores, que se pasaron con `--set`, del gráfico de Helm de Rancher actual que está instalado.

----
helm get values rancher -n cattle-system

hostname: rancher.my.org
----

[NOTE]
====

Habrá más valores que se enumeran con este comando. Este es solo un ejemplo de uno de los valores.
====


[TIP]
====

El nombre de tu ampliación puede variar; por ejemplo, si estás desplegando Rancher a través del AWS Marketplace, el nombre de la ampliación es 'rancher-prime'.
Así:

----
helm get values rancher-prime -n cattle-system

hostname: rancher.my.org
----
====


Si estás actualizando cert-manager a la última versión desde v1.5 o anterior, sigue los {xref-upgrade-certmanager}#_option_c_upgrade_cert_manager_from_versions_15_and_below[documentos de actualización de cert-manager] para aprender cómo actualizar cert-manager sin necesidad de desinstalar o reinstalar Rancher. De lo contrario, sigue los <<_steps_to_upgrade_rancher,pasos para actualizar Rancher>> a continuación.

[#_steps_to_upgrade_rancher]
==== Pasos para actualizar Rancher

Actualiza Rancher a la última versión con todas tus configuraciones.

Toma todos los valores del paso anterior y añádelos al comando usando `--set key=value`.

----
helm upgrade rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org
----

[NOTE]
====

Lo anterior es un ejemplo, puede haber más valores del paso anterior que necesiten ser añadidos.
====


[TIP]
====
Si despliegas Rancher a través del AWS Marketplace, el nombre de la ampliación es 'rancher-prime'.
Así:

----
helm upgrade rancher-prime rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org
----
====


Alternativamente, es posible exportar los valores actuales a un archivo y hacer referencia a ese archivo durante la actualización. Por ejemplo, para cambiar solo la versión de Rancher:

. Exporta los valores actuales a un archivo:
+
----
 helm get values rancher -n cattle-system -o yaml > values.yaml
----

. Actualiza solo la versión de Rancher:
+
----
 helm upgrade rancher rancher-prime/rancher \
   --namespace cattle-system \
   -f values.yaml \
   --version={current-patch-version}
----

[#_5_verify_the_upgrade]
=== 5. Verifica la actualización

Inicia sesión en Rancher para confirmar que la actualización se realizó con éxito.

[#_known_upgrade_issues]
== Problemas de actualización conocidos

Una lista de problemas conocidos para cada versión de Rancher se puede encontrar en las notas de la versión en https://github.com/rancher/rancher/releases[GitHub] y en los https://forums.rancher.com/c/announcements/12[foros de Rancher.]
