= Dynamisches Bereitstellen neuer Speicher in {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-09-12
:page-revdate: {revdate}
:community-path: how-to-guides/neue-anleitungen/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/dynamisch-neuen-speicher-bereitstellen.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/dynamically-provision-new-storage.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/benutzer/authn-und-authz/rollenbasierte-zugriffskontrolle-rbac/cluster-und-projektrollen.adoc
:xref-longhorn: xref:integrations/longhorn/longhorn.adoc
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
:xref-unsupported-storage-drivers: xref:rancher-admin/experimental-features/unsupported-storage-drivers.adoc
:xref-about-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/about-persistent-storage.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:how-to-guides/neue-anleitungen/authentifizierung-berechtigungen-und-global-konfiguration/manage-role-based-access-control-rbac/cluster-und-projektrollen.adoc
:xref-longhorn: xref:integrations-in-rancher/longhorn/index.adoc
:xref-set-up-cloud-providers: xref:how-to-guides/neue-anleitungen/kubernetes-cluster-in-rancher-einrichten/cloud-anbieter-einrichten/index.adoc
:xref-unsupported-storage-drivers: xref:how-to-guides/fortgeschrittene-benutzeranleitungen/experimentelle-funktionen-aktivieren/nicht-unterstützte-speicher-treiber.adoc
:xref-about-persistent-storage: xref:how-to-guides/neue-anleitungen/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/über-persistent-storage.adoc
endif::[]

Dieser Abschnitt beschreibt, wie man neuen persistenten Speicher für Workloads in Rancher bereitstellt.

Dieser Abschnitt geht davon aus, dass Sie die Kubernetes-Konzepte von Speicherklassen und persistenten Volumenansprüchen verstehen. Für weitere Informationen siehe den Abschnitt über {xref-about-persistent-storage}[wie Speicher funktioniert.]

Neuer Speicher wird oft von einem Cloud-Anbieter wie Amazon EBS bereitgestellt. Allerdings muss neuer Speicher nicht in der Cloud sein.

Wenn Sie einen Pool von Blockspeicher haben und keinen Cloud-Anbieter verwenden möchten, könnte Longhorn Ihnen helfen, persistenten Speicher für Ihr Kubernetes-Cluster bereitzustellen. Für weitere Informationen siehe {xref-longhorn}[Cloudnativ Storage mit Longhorn].

Um neuen Speicher für Ihre Workloads bereitzustellen, folgen Sie diesen Schritten:

. <<_1_add_a_storage_class_and_configure_it_to_use_your_storage,Fügen Sie eine Speicherklasse hinzu und konfigurieren Sie sie, um Ihren Speicher zu verwenden.>>
. <<_2_use_the_storage_class_for_pods_deployed_with_a_statefulset,Verwenden Sie die Storage-Klasse für Pods, die mit einem StatefulSet bereitgestellt werden.>>

[#_prerequisites]
== Voraussetzungen

* Um persistenten Speicher einzurichten, ist die `Manage Volumes` {xref-cluster-project-roles}#_project_role_reference[Rolle] erforderlich.
* Wenn Sie Speicher für einen in der Cloud gehosteten Cluster bereitstellen, müssen der Speicher und die Cluster-Hosts denselben Cloud-Anbieter haben.
* Der Cloud-Anbieter muss aktiviert sein. Für Details zur Aktivierung von Cloud-Anbietern siehe {xref-set-up-cloud-providers}[diese Seite.]
* Stellen Sie sicher, dass Ihr Speicherbereitsteller verfügbar ist, um aktiviert zu werden.

Die folgenden Speicherbereitsteller sind standardmäßig aktiviert:

|===
| Name | Plugin

| Amazon EBS Disk
| `aws-ebs`

ifeval::["{build-type}" != "srfa"]
| AzureFile
| `azure-file`

| AzureDisk
| `azure-disk`

| Google Persistent Disk
| `gce-pd`

| VMware vSphere Volume
| `vsphere-volume`
endif::[]

| Lokal
| `local`

| Network File System
| `nfs`

| hostPath
| `host-path`
|===

Um einen Speicherbereitsteller zu verwenden, der nicht auf der obigen Liste steht, müssen Sie ein {xref-unsupported-storage-drivers}[Feature-Flag verwenden, um nicht unterstützte Speicher-Treiber zu aktivieren.]

[#_1_add_a_storage_class_and_configure_it_to_use_your_storage]
== 1. Fügen Sie eine Speicherklasse hinzu und konfigurieren Sie sie, um Ihren Speicher zu verwenden.

Diese Schritte beschreiben, wie Sie eine Speicherklasse auf Cluster-Ebene einrichten.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie dynamisch persistente Speicher-Volumes bereitstellen möchten, und klicken Sie auf *Explore*.
. Klicken Sie auf menu:Speicher[Speicherklassen].
. Klicken Sie auf *Erstellen*.
. Geben Sie einen Namen für Ihre Storage-Klasse ein.
. Wählen Sie aus dem *Bereitsteller*-Dropdown den Dienst aus, den Sie verwenden möchten, um dynamisch Speicher-Volumes bereitzustellen. Wenn Sie beispielsweise einen Amazon EC2-Cluster haben und Cloud-Speicher dafür verwenden möchten, verwenden Sie den `Amazon EBS Disk` Bereitsteller.
. Füllen Sie im Tab *Parameter* die Informationen aus, die für den Dienst erforderlich sind, um dynamisch Speicher-Volumes bereitzustellen. Jeder Bereitsteller benötigt unterschiedliche Informationen, um dynamisch Speicher-Volumes bereitzustellen. Konsultieren Sie die Dokumentation des Dienstes, um Hilfe zu erhalten, wie Sie diese Informationen abrufen können.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Die Speicherklasse steht zur Verwendung durch ein PVC zur Verfügung.

Für vollständige Informationen zu den Parametern der Speicherklasse verweisen Sie auf die offizielle https://kubernetes.io/docs/concepts/storage/storage-classes/#parameters[Kubernetes-Dokumentation.].

[#_2_use_the_storage_class_for_pods_deployed_with_a_statefulset]
== 2. Verwenden Sie die Speicherklasse für Pods, die mit einem StatefulSet bereitgestellt werden.

StatefulSets verwalten die Bereitstellung und Skalierung von Pods und behalten dabei eine feste Identität für jeden Pod bei. In diesem StatefulSet werden wir eine VolumeClaimTemplate konfigurieren. Jeder Pod, der vom StatefulSet verwaltet wird, wird mit einem PersistentVolumeClaim bereitgestellt, der auf diesem VolumeClaimTemplate basiert. Der PersistentVolumeClaim wird auf die StorageClass verweisen, die wir erstellt haben. Daher wird jeder Pod, der vom StatefulSet verwaltet wird, beim Bereitstellen an dynamisch bereitgestellten Speicher gebunden, der mit der in seinem PersistentVolumeClaim definierten StorageClass verwendet wird.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie die StorageClass für eine Arbeitslast verwenden möchten, und klicken Sie auf *Explore*.
. Klicken Sie in der linken Navigationsleiste auf *Arbeitslast*.
. Klicken Sie auf *Erstellen*.
. Klicken Sie auf *StatefulSet*.
. Klicken Sie im Tab *Volume Claim Templates* auf *Claim-Vorlage hinzufügen*.
. Geben Sie einen Namen für das persistente Volume ein.
. Wählen Sie im Feld *StorageClass* die StorageClass aus, die dynamisch Speicher für von diesem StatefulSet verwaltete Pods bereitstellt.
. Geben Sie im Feld *Einhängepunkt* den Pfad ein, den die Arbeitslast verwenden wird, um auf das Volume zuzugreifen.
. Klicken Sie auf *Starten*.

*Ergebnis:* Wenn jeder Pod, der vom StatefulSet verwaltet wird, bereitgestellt wird, wird er eine Anfrage für den angegebenen Speicherplatz an den Kubernetes-Master stellen. Wenn ein PV mit den angegebenen Ressourcen verfügbar ist, wenn die Arbeitslast bereitgestellt wird, wird der Kubernetes-Master das PV an den Pod mit einem kompatiblen PVC binden.

Um das PVC an eine vorhandene Arbeitslast anzuhängen,

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie die StorageClass für eine Arbeitslast hinzufügen möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie in der linken Navigationsleiste auf *Arbeitslast*.
. Gehen Sie zu der Arbeitslast, die den mit der StorageClass bereitgestellten Speicher verwenden wird, und klicken Sie auf *⋮ > Konfiguration bearbeiten*.
. Klicken Sie im Abschnitt *Vorlagen für Volume Claims* auf *Volume Claim-Vorlage hinzufügen*.
. Geben Sie einen dauerhaften Volumennamen ein.
. Wählen Sie im Feld *StorageClass* die StorageClass aus, die dynamisch Speicher für von diesem StatefulSet verwaltete Pods bereitstellt.
. Geben Sie im Feld *Einhängepunkt* den Pfad ein, den die Arbeitslast verwenden wird, um auf das Volume zuzugreifen.
. Klicken Sie auf *Speichern*.

*Ergebnis:* Die Arbeitslast wird eine Anfrage für den angegebenen Speicherplatz an den Kubernetes-Master stellen. Wenn ein PV mit den angegebenen Ressourcen verfügbar ist, wenn die Arbeitslast bereitgestellt wird, wird der Kubernetes-Master das PV an das PVC binden. Andernfalls wird Rancher neuen persistenten Speicher bereitstellen.
