= Einrichtung bestehender Speicher
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/Anleitung/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/set-up-existing-storage.adoc 
:product-path: cluster-admin/manage-clusters/persistent-storage/set-up-existing-storage.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/benutzer/authn-und-authz/manage-role-based-access-control-rbac/cluster-und-projektrollen.adoc
:xref-longhorn: xref:integrations/longhorn/longhorn.adoc
:xref-vsphere-storage-example: xref:cluster-admin/manage-clusters/persistent-storage/examples/vsphere-storage.adoc
:xref-amazon-ebs-storage: xref:cluster-admin/manage-clusters/persistent-storage/examples/persistent-storage-in-amazon-ebs.adoc
:xref-nfs-storage: xref:cluster-admin/manage-clusters/persistent-storage/examples/nfs-storage.adoc
:xref-about-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/about-persistent-storage.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:how-to-guides/Anleitung/authentifizierung-berechtigungen-und-globale-konfiguration/manage-role-based-access-control-rbac/cluster-und-projektrollen.adoc
:xref-longhorn: xref:integrations-in-rancher/longhorn/index.adoc
:xref-vsphere-storage-example: xref:how-to-guides/Anleitung/manage-clusters/provisioning-storage-beispiele/vsphere-speicher.adoc
:xref-amazon-ebs-storage: xref:how-to-guides/Anleitung/manage-clusters/provisioning-storage-beispiele/persistent-storage-in-amazon-ebs.adoc
:xref-nfs-storage: xref:how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/nfs-storage.adoc
:xref-about-persistent-storage: xref:how-to-guides/Anleitung/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/über-persistent-storage.adoc
endif::[]

Dieser Abschnitt beschreibt, wie man bestehenden persistenten Speicher für Workloads in Rancher einrichtet.

[NOTE]
====

Dieser Abschnitt geht davon aus, dass Sie die Kubernetes-Konzepte von persistenten Volumes und persistenten Volume-Anforderungen verstehen. Für weitere Informationen siehe den Abschnitt über {xref-about-persistent-storage}[wie Speicher funktioniert.]
====


Um Speicher einzurichten, folgen Sie diesen Schritten:

. <<_1_set_up_persistent_storage,Richten Sie persistenten Speicher ein.>>
. <<_2_add_a_persistentvolume_that_refers_to_the_persistent_storage,Fügen Sie ein PersistentVolume hinzu, das auf den persistenten Speicher verweist.>>
. <<_3_use_the_storage_class_for_pods_deployed_with_a_statefulset,Verwenden Sie die Storage-Klasse für Pods, die mit einem StatefulSet bereitgestellt werden.>>

[#_prerequisites]
== Voraussetzungen

* Um ein persistentes Volume als Kubernetes-Ressource zu erstellen, müssen Sie die `Manage Volumes` {xref-cluster-project-roles}#_project_role_reference[Rolle.]
* Wenn Sie Speicher für einen in der Cloud gehosteten Cluster bereitstellen, müssen der Speicher und die Cluster-Hosts denselben Cloud-Anbieter haben.

[#_1_set_up_persistent_storage]
== 1. Richten Sie persistenten Speicher ein

Das Erstellen eines PersistentVolumes in Rancher erstellt kein Speicher-Volume. Es erstellt lediglich eine Kubernetes-Ressource, die auf ein vorhandenes Volume verweist. Daher müssen Sie, bevor Sie ein PersistentVolume als Kubernetes-Ressource erstellen können, Speicher bereitgestellt haben.

ifeval::["{build-type}" != "srfa"]
Die Schritte zur Einrichtung eines persistenten Speichers hängen von Ihrer Infrastruktur ab. Wir bieten Beispiele dafür, wie Sie Speicher mit {xref-vsphere-storage-example}[vSphere,] {xref-nfs-storage}[NFS,] oder Amazons {xref-amazon-ebs-storage}[EBS.] einrichten können.
endif::[]
ifeval::["{build-type}" == "srfa"]
Die Schritte zur Einrichtung eines persistenten Speichers hängen von Ihrer Infrastruktur ab. Wir bieten Beispiele dafür, wie Sie Speicher mit {xref-nfs-storage}[NFS] oder Amazons {xref-amazon-ebs-storage}[EBS.] einrichten können.
endif::[]

Wenn Sie einen Pool von Blockspeicher haben und keinen Cloud-Anbieter verwenden möchten, könnte Longhorn Ihnen helfen, persistenten Speicher für Ihren Kubernetes-Cluster bereitzustellen. Für weitere Informationen siehe {xref-longhorn}[Cloud Native Storage mit Longhorn].

[#_2_add_a_persistentvolume_that_refers_to_the_persistent_storage]
== 2. Fügen Sie ein PersistentVolume hinzu, das auf den persistenten Speicher verweist

Diese Schritte beschreiben, wie Sie ein PersistentVolume auf Cluster-Ebene in Kubernetes einrichten.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie ein persistentes Volume hinzufügen möchten, und klicken Sie auf *Erforschen*.
. Klicken Sie in der linken Navigationsleiste auf menu:Speicher[Persistente Volumes].
. Klicken Sie auf *Erstellen*.
. Geben Sie einen *Name* für das persistente Volume ein.
. Wählen Sie das *Volume-Plugin* für den Festplattentyp oder den Dienst aus, den Sie verwenden. Beim Hinzufügen von Speicher zu einem von einem Cloud-Anbieter gehosteten Cluster verwenden Sie das Plugin des Cloud-Anbieters für Cloud-Speicher. Wenn Sie beispielsweise einen Amazon EC2-Cluster haben und Cloud-Speicher dafür verwenden möchten, müssen Sie das `Amazon EBS Disk` Volume-Plugin verwenden.
. Geben Sie die *Kapazität* Ihres Volumes in Gigabyte ein.
. Vervollständigen Sie das *Plugin-Konfigurationsformular*. Jeder Plugin-Typ erfordert spezifische Informationen zum Anbieter des Datenträgers. Für Hilfe zu den Formularen jedes Plugins und den erforderlichen Informationen konsultieren Sie die Dokumentation des Plugin-Anbieters.
. Optional: Im *Anpassungsformular* konfigurieren Sie die https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[Zugriffsmodi.] Diese Option legt fest, wie viele Knoten auf das Volume zugreifen können, sowie die Lese-/Schreibberechtigungen der Knoten. Die https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[Kubernetes-Dokumentation] enthält eine Tabelle, die auflistet, welche Zugriffsmodi von den verfügbaren Plugins unterstützt werden.
. Optional: Im *Anpassungsformular* konfigurieren Sie die https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options[Mount-Optionen.] Jeder Volume-Plugin ermöglicht es Ihnen, zusätzliche Befehlszeilenoptionen während des Mountvorgangs anzugeben. Konsultieren Sie die Dokumentation des Anbieters jedes Plugins für die verfügbaren Mount-Optionen.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Ihr neues persistentes Volume wurde erstellt.

[#_3_use_the_storage_class_for_pods_deployed_with_a_statefulset]
== 3. Verwenden Sie die Storage Class für mit einem StatefulSet bereitgestellte Pods.

StatefulSets verwalten die Bereitstellung und Skalierung von Pods, während sie eine feste Identität für jeden Pod beibehalten. In diesem StatefulSet werden wir eine VolumeClaimTemplate konfigurieren. Jeder Pod, der vom StatefulSet verwaltet wird, wird mit einem PersistentVolumeClaim bereitgestellt, der auf dieser VolumeClaimTemplate basiert. Der PersistentVolumeClaim wird auf das PersistentVolume verweisen, das wir erstellt haben. Daher wird jeder Pod, der vom StatefulSet verwaltet wird, beim Bereitstellen an ein PersistentVolume gebunden, wie es in seinem PersistentVolumeClaim definiert ist.

Sie können den Speicher für das StatefulSet während oder nach der Erstellung der Arbeitslast konfigurieren.

Die folgenden Schritte beschreiben, wie Sie vorhandenen Speicher einem neuen StatefulSet zuweisen:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie den Speicher für das StatefulSet konfigurieren möchten, und klicken Sie auf *Erforschen*.
. Klicken Sie in der linken Navigationsleiste auf menu:Arbeitslast[StatefulSets].
. Klicken Sie auf *Erstellen*.
. Wählen Sie den Namespace aus, in dem die Arbeitslast bereitgestellt wird.
. Geben Sie einen Namen für das StatefulSet ein.
. Klicken Sie auf die Registerkarte *Volume Claim Templates* und dann auf *Claim-Vorlage hinzufügen*.
. Klicken Sie auf *Verwenden Sie ein vorhandenes PersistentVolume*.
. Wählen Sie im Feld PersistentVolumes das PersistentVolume aus, das Sie erstellt haben.
. Geben Sie im Feld *Einhängepunkt* den Pfad ein, den die Arbeitslast verwenden wird, um auf das Volume zuzugreifen.
. Klicken Sie auf *Starten*.

*Ergebnis:* Wenn die Arbeitslast bereitgestellt wird, wird eine Anfrage für den angegebenen Speicherplatz an den Kubernetes-Master gesendet. Wenn ein PV mit den angegebenen Ressourcen verfügbar ist, wenn die Arbeitslast bereitgestellt wird, wird der Kubernetes-Master das PV an das PVC binden.

Die folgenden Schritte beschreiben, wie Sie persistenten Speicher einer vorhandenen Arbeitslast zuweisen:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie den Speicher für das StatefulSet konfigurieren möchten, und klicken Sie auf *Erforschen*.
. Klicken Sie in der linken Navigationsleiste auf menu:Arbeitslast[StatefulSets].
. Gehen Sie zu der Arbeitslast, der Sie den persistenten Speicher hinzufügen möchten. Klicken Sie auf *⋮ > Bearbeiten*.
. Klicken Sie auf die Registerkarte *Volume Claim Templates* und dann auf *Claim-Vorlage hinzufügen*.
. Klicken Sie auf *Verwenden Sie ein vorhandenes PersistentVolume*.
. Wählen Sie im Feld PersistentVolumes das PersistentVolume aus, das Sie erstellt haben.
. Geben Sie im Feld *Einhängepunkt* den Pfad ein, den die Arbeitslast verwenden wird, um auf das Volume zuzugreifen.
. Klicken Sie auf *Starten*.

*Ergebnis:* Die Arbeitslast wird eine Anfrage für den angegebenen Speicherplatz an den Kubernetes-Master senden. Wenn ein PV mit den angegebenen Ressourcen verfügbar ist, wenn die Arbeitslast bereitgestellt wird, wird der Kubernetes-Master das PV an das PVC binden.
