= Meilleures pratiques pour le {rancher-product-name} serveur
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-server/index.adoc 
:product-path: installation-and-upgrade/best-practices/best-practices.adoc
ifeval::["{build-type}" != "community"]
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-rancher-on-vsphere: xref:installation-and-upgrade/best-practices/rancher-on-vsphere.adoc
:xref-deployment-strategy: xref:installation-and-upgrade/best-practices/deployment-strategy.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-rancher-on-vsphere: xref:reference-guides/best-practices/rancher-server/on-premises-rancher-in-vsphere.adoc
:xref-deployment-strategy: xref:reference-guides/best-practices/rancher-server/rancher-deployment-strategy.adoc
endif::[]

Ce guide contient nos recommandations pour l'exécution du serveur Rancher et est destiné à être utilisé dans des situations où Rancher gère des clusters Kubernetes en aval.

[#_recommended_architecture_and_infrastructure]
== Architecture et infrastructure recommandées

Consultez ce {xref-tips-for-running-rancher}[guide] pour nos conseils généraux sur la configuration du serveur Rancher pour une installation en production.

[#_deployment_strategies]
== Stratégies de déploiement

Ce {xref-deployment-strategy}[guide] est conçu pour vous aider à choisir si une stratégie de déploiement régional ou une stratégie de déploiement en hub et en spoke est préférable pour un serveur Rancher qui gère des clusters Kubernetes en aval.

[#_installing_rancher_in_a_vmware_vsphere_environment]
== Installation de Rancher dans un environnement VMware vSphere

Ce {xref-rancher-on-vsphere}[guide] décrit une architecture de référence pour l'installation de Rancher dans un environnement vSphere, en plus des meilleures pratiques standard de vSphere telles que documentées par VMware.
