= {rancher-prime}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/prime.adoc 
:product-path: about-rancher/prime.adoc

SUSE Rancher presenta Rancher Prime -- una evolución de Rancher -- desde la versión v2.7. Rancher Prime es la nueva oferta empresarial disponible comercialmente de Rancher, construida sobre el mismo código abierto. El proyecto Rancher seguirá siendo 100% de código abierto. Prime aporta valor adicional con mayores garantías de seguridad, ciclos de vida extendidos, acceso a arquitecturas enfocadas y avisos de Kubernetes. Rancher Prime también ofrecerá opciones para obtener asistencia de producción para proyectos innovadores de Rancher. Con Rancher Prime, los recursos de instalación se alojan en un registro de confianza propiedad de Rancher y gestionado por Rancher.

Para comenzar con Rancher Prime, https://www.rancher.com/quick-start[accede a esta página] y completa el formulario.
