= {elemental-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/elemental/index.adoc 
:product-path: integrations/elemental.adoc

Elemental permite a gestão de hosts nativa de nuvem. Elemental permite que você integre qualquer máquina em qualquer local, seja em um datacenter ou na borda, e as integre perfeitamente ao Kubernetes enquanto gerencia seus fluxos de trabalho (por exemplo, atualizações de SO).

[#__elemental_product_name_with_rancher]
== {elemental-product-name} com o Rancher

Elemental no Rancher:

* É nativo do Kubernetes, o que permite gerenciar o SO via Elemental em clusters do Kubernetes.
* É não disruptivo do ponto de vista operacional do Kubernetes.
* É declarativo e amigável ao GitOps.
* Permite fluxos baseados em imagens OCI, que são confiáveis, determinísticos e previsíveis.
* Funciona em grande escala. Permite a gestão do SO em escala Fleet.

[#_when_should_i_use_elemental_product_name]
=== Quando devo usar {elemental-product-name}?

* Elemental permite a gestão de SO nativa de nuvem a partir do gerenciador Rancher. Funciona com qualquer SO (por exemplo, SLE Micro vanilla).
* Elemental permite a gestão nativa de nuvem para máquinas em datacenters e na borda.
* Elemental é flexível e permite que as equipes de plataforma realizem todos os tipos de fluxos de trabalho em sua Fleet.

[#__elemental_product_name_with_rancher_prime]
== {elemental-product-name} com {rancher-prime}

* Já integrado profundamente como extensão GUI no Rancher.
* Estende a história do Rancher para o SO. Funcionando perfeitamente com SLE Micro para Rancher hoje.
