= {stackstate-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/suse-observability/index.adoc 
:product-path: integrations/suse-observability.adoc

SUSE Observability é uma solução completa de observabilidade que fornece insights profundos sobre a saúde de seus clusters e nós, além das cargas de trabalho que estão sendo executadas neles. Projetada para oferecer visibilidade clara em todo o seu ambiente Kubernetes, a abordagem full-stack da SUSE Observability permite que você explore tudo, desde serviços até infraestrutura, dentro de uma única plataforma, eliminando a necessidade de várias ferramentas de observabilidade.

A SUSE Observability coleta e correlaciona dados de forma segura, oferecendo insights acionáveis sobre problemas existentes e potenciais em seu cluster. Isso ajuda você a resolver problemas atuais rapidamente e a tomar medidas preventivas contra desafios futuros.

Os painéis intuitivos destacam áreas problemáticas e oferecem etapas de remediação, guiando você desde a identificação do problema até a análise da causa raiz e, finalmente, à resolução, no menor tempo possível.

Para mais informações e para configurar a SUSE Observability em seu cluster Kubernetes gerenciado pelo SUSE Rancher, consulte a https://documentation.suse.com/en-us/cloudnative/suse-observability/[documentação].
