= 关于 RKE1 模板
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/index.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/rke1-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-rke1-template-example-yaml: xref:rancher-admin/global-configuration/rke1-templates/template-example-yaml.adoc
:xref-rke1-template-infrastructure: xref:rancher-admin/global-configuration/rke1-templates/infrastructure.adoc
:xref-rke1-creator-permissions: xref:rancher-admin/global-configuration/rke1-templates/creator-permissions.adoc
:xref-cluster-templates: xref:cluster-admin/manage-clusters/cluster-templates.adoc
:xref-rke1-template-example-use-cases: xref:rancher-admin/global-configuration/rke1-templates/example-use-cases.adoc
:xref-rke1-template-override-settings: xref:rancher-admin/global-configuration/rke1-templates/override-template-settings.adoc
:xref-rke1-template-apply: xref:rancher-admin/global-configuration/rke1-templates/apply-templates.adoc
:xref-rke1-template-enforce: xref:rancher-admin/global-configuration/rke1-templates/enforce-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rke1-templates: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/manage-rke1-templates.adoc
:xref-access-share-rke1-templates: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/access-or-share-templates.adoc
:xref-rke1-template-example-yaml: xref:reference-guides/rke1-template-example-yaml.adoc
:xref-rke1-template-infrastructure: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/infrastructure.adoc
:xref-rke1-creator-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/creator-permissions.adoc
:xref-cluster-templates: xref:how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc
:xref-rke1-template-example-use-cases: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/example-use-cases.adoc
:xref-rke1-template-override-settings: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/override-template-settings.adoc
:xref-rke1-template-apply: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/apply-templates.adoc
:xref-rke1-template-enforce: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/enforce-templates.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

RKE 模板旨在使 DevOps 和安全团队能够标准化和简化 Kubernetes 集群的创建。

RKE 是 https://rancher.com/docs/rke/latest/en/[Rancher Kubernetes Engine,]，这是 Rancher 用于配置 Kubernetes 集群的工具。

随着 Kubernetes 的日益普及，管理更多数量的小型集群的趋势正在增加。当您想要创建多个集群时，保持一致的管理变得更加重要。多集群管理面临着强制执行安全性和附加配置的挑战，这些配置需要在将集群交给最终用户之前进行标准化。

RKE 模板有助于标准化这些配置。无论集群是通过 Rancher UI、Rancher API 还是自动化过程创建的，Rancher 都会保证从 RKE 模板配置的每个集群在生产方式上都是统一和一致的。

管理员控制最终用户可以更改哪些集群选项。RKE 模板还可以与特定用户和组共享，以便管理员可以为不同的用户组创建不同的 RKE 模板。

如果集群是使用 RKE 模板创建的，则无法更改为不同的 RKE 模板。您只能将集群更新为同一模板的新版本。

您可以 {xref-rke1-template-apply}#_converting_an_existing_cluster_to_use_an_rke_template[将现有集群的配置保存为 RKE 模板。] 然后，只有在模板更新后，才能更改集群的设置。新模板也可以用于启动新集群。

RKE 模板的核心功能允许 DevOps 和安全团队：

* 标准化集群配置，确保 Rancher 提供的集群按照最佳实践创建
* 防止技术水平较低的用户在配置集群时做出不明智的选择
* 与不同的用户和组共享不同的模板
* 将模板的所有权委托给可信任的用户，以便他们可以对其进行更改
* 控制哪些用户可以创建模板
* 要求用户从模板创建集群

[#_configurable_settings]
== 可配置设置

RKE 模板可以在 Rancher UI 中创建或以 YAML 格式定义。它们可以定义使用 Rancher 配置自定义节点或从基础设施提供商配置节点时可以指定的所有相同参数：

* 云服务提供商选项
* Pod 安全选项
* 网络提供商
* Ingress 控制器
* 网络安全配置
* 网络插件
* 私有注册表 URL 和凭证
* 附加组件
* Kubernetes 选项，包括 Kubernetes 组件的配置，如 kube-api、kube-controller、kubelet 和服务

RKE 模板的 <<_add_ons,附加产品部分>> 特别强大，因为它允许广泛的自定义选项。

[#_scope_of_rke_templates]
== RKE 模板的范围

RKE 模板支持 Rancher 提供的集群。这些模板可用于配置自定义集群或由基础设施提供商启动的集群。

RKE 模板用于定义 Kubernetes 和 Rancher 设置。节点模板负责配置节点。有关如何将 RKE 模板与硬件结合使用的提示，请参阅 {xref-rke1-template-infrastructure}[RKE Templates and Hardware].

RKE 模板可以从头开始创建，以预定义集群配置。它们可以应用于启动新集群，或者模板也可以从现有运行的集群中导出。

现有集群的设置可以 {xref-rke1-template-apply}#_将现有集群转换为使用 RKE 模板[保存为 RKE 模板。] 这会创建一个新模板并将集群设置绑定到模板，因此集群只能在 {xref-manage-rke1-templates}#_更新模板[模板更新] 时升级，并且集群升级到 {xref-manage-rke1-templates}#_升级集群以使用新模板版本[使用模板的新版本。] 新模板也可以用于创建新集群。

[#_example_scenarios]
== 示例方案

当一个组织同时拥有基础和高级 Rancher 用户时，管理员可能希望为高级用户提供更多的集群创建选项，同时限制基础用户的选项。

这些 {xref-rke1-template-example-use-cases}[example scenarios]描述了一个组织如何使用模板来标准化集群创建。

一些示例场景包括以下内容：

* *强制模板:*如果管理员希望所有新创建的Rancher集群都具有这些设置，他们可能想要{xref-rke1-template-example-use-cases}#_强制所有人使用模板设置[强制所有人使用一个或多个模板设置]。
* *与不同用户共享不同模板:*管理员可能会给{xref-rke1-template-example-use-cases}#_templates_for_basic_and_advanced_users[different templates to basic and advanced users,]以便基本用户可以拥有更受限的选项，而高级用户在创建集群时可以使用更多的自由度。
* *更新模板设置:*如果一个组织的安全和DevOps团队决定将最佳实践嵌入到新集群的必需设置中，这些最佳实践可能会随着时间的推移而变化。如果最佳实践发生变化，{xref-rke1-template-example-use-cases}#_updating_templates_and_clusters_created_with_them[a template can be updated to a new revision]，而从该模板创建的集群可以{xref-manage-rke1-templates}#_upgrading_a_cluster_to_use_a_new_template_revision[upgrade to the new version]。
* *共享模板的所有权:*当模板所有者不再想维护模板，或想要共享模板的所有权时，此场景描述了{xref-rke1-template-example-use-cases}#_allowing_other_users_to_control_and_share_a_template[template ownership can be shared.]

[#_template_management]
== 模板管理

当您创建RKE模板时，它在Rancher UI的*集群管理*视图下的*RKE模板*中可用。当您创建一个模板时，您成为模板所有者，这使您有权限修订和共享该模板。您可以与特定用户或组共享RKE模板，也可以将其设为公开。

管理员可以启用模板强制，以要求用户在创建集群时始终使用RKE模板。这使管理员能够确保Rancher始终以特定设置配置集群。

RKE模板更新通过修订系统进行管理。如果您想更改或更新模板，您需要创建该模板的新修订版。然后，使用旧版本模板创建的集群可以升级到新模板修订版。

在 RKE 模板中，设置可以限制为模板所有者选择的内容，或者可以开放给最终用户选择值。差异通过 Rancher UI 中每个设置上方的 *允许用户覆盖* 切换开关在模板创建时指示。

对于无法被覆盖的设置，最终用户将无法直接编辑它们。为了让用户获得这些设置的不同选项，RKE 模板所有者需要创建 RKE 模板的新修订版，这将允许用户升级并更改该选项。

本节中的文档解释了 RKE 模板管理的详细信息：

* {xref-rke1-creator-permissions}[获取创建模板的权限]
* {xref-manage-rke1-templates}[创建和修订模板]
* {xref-rke1-template-enforce}#_requiring_new_clusters_to_use_an_rke_template[Enforcing template settings]
* {xref-rke1-template-override-settings}[覆盖模板设置]
* {xref-access-share-rke1-templates}#_与特定用户或组共享模板[与集群创建者共享模板]
* {xref-access-share-rke1-templates}#_共享模板的所有权[共享模板的所有权]

提供了一个 {xref-rke1-template-example-yaml}[示例 YAML 配置文件（用于模板）] 供参考。

[#_applying_templates]
== 应用模板

您可以 {xref-rke1-template-apply}#_creating_a_cluster_from_an_rke_template[create a cluster from a template]，也可以从已与您 {xref-access-share-rke1-templates}[shared with you.] 的模板创建集群。

如果 RKE 模板所有者创建了模板的新修订版，您可以 {xref-rke1-template-apply}#_updating_a_cluster_created_with_an_rke_template[upgrade your cluster to that revision.]

RKE 模板可以从头开始创建，以预定义集群配置。它们可以应用于启动新集群，或者模板也可以从现有运行的集群中导出。

您可以 {xref-rke1-template-apply}#_converting_an_existing_cluster_to_use_an_rke_template[save the configuration of an existing cluster as an RKE template.] 然后，只有在模板更新时，集群的设置才能更改。

[#_standardizing_hardware]
== 标准化硬件

RKE 模板旨在标准化 Kubernetes 和 Rancher 设置。如果您还想标准化基础设施，一个选项是将 RKE 模板 {xref-rke1-template-infrastructure}[in conjunction with other tools]。

另一个选项是使用 {xref-cluster-templates}[集群模板]，其中包括节点池的配置选项，但不提供配置强制执行。

[#_yaml_customization]
== YAML 自定义

如果您将 RKE 模板定义为 YAML 文件，您可以修改此 {xref-rke1-template-example-yaml}[示例 RKE 模板 YAML]。RKE 模板中的 YAML 使用与 Rancher 创建 RKE 集群时相同的自定义，但由于 YAML 位于 Rancher 提供的集群的上下文中，您需要将 RKE 模板自定义嵌套在 YAML 的 `rancher_kubernetes_engine_config` 指令下。

RKE 文档中还有 https://rancher.com/docs/rke/latest/en/example-yamls/[带注释的] `cluster.yml` 文件，供您参考。

有关可用选项的指导，请参阅 RKE 文档中的 https://rancher.com/docs/rke/latest/en/config-options/[集群配置。]

[#_add_ons]
=== 附加组件

RKE 模板配置文件的附加产品部分与 https://rancher.com/docs/rke/latest/en/config-options/add-ons/[集群配置文件的附加产品部分] 的工作方式相同。

用户定义的附加产品指令允许您调用并下载 Kubernetes 清单或直接将其内联放置。如果您将这些清单作为 RKE 模板的一部分包含，Rancher 将在集群中提供这些清单。

通过附加产品，您可以实现以下一些操作：

* 在 Kubernetes 集群启动后安装应用程序
* 在使用 Kubernetes daemonset 部署的节点上安装插件
* 自动设置命名空间、服务帐户或角色绑定

RKE 模板配置必须嵌套在 `rancher_kubernetes_engine_config` 指令中。要设置附加产品，在创建模板时，您将点击 *以 YAML 编辑*。然后使用 `addons` 指令添加清单，或使用 `addons_include` 指令设置用于附加产品的 YAML 文件。有关自定义附加产品的更多信息，请参阅 https://rancher.com/docs/rke/latest/en/config-options/add-ons/user-defined-add-ons/[用户定义的附加产品文档。]
