= {elemental-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/elemental/index.adoc 
:product-path: integrations/elemental.adoc

Élémentaire permet la gestion des hôtes natifs Cloud. Élémentaire vous permet d'intégrer n'importe quelle machine, où qu'elle se trouve, que ce soit dans un datacenter ou en périphérie, et de les intégrer de manière transparente dans Kubernetes tout en gérant vos flux de travail (par exemple, les mises à jour du système d'exploitation).

[#__elemental_product_name_with_rancher]
== {elemental-product-name} avec Rancher

Élémentaire dans Rancher{nbsp}:

* Est natif de Kubernetes, ce qui vous permet de gérer le système d'exploitation via Élémentaire dans des clusters Kubernetes.
* Est non disruptif du point de vue opérationnel de Kubernetes.
* Est déclaratif et compatible avec GitOps.
* Permet des flux basés sur des images OCI, qui sont fiables, déterministes et prévisibles.
* Fonctionne à grande échelle. Il permet la gestion des systèmes d'exploitation à l'échelle de Fleet.

[#_when_should_i_use_elemental_product_name]
=== Quand devrais-je utiliser {elemental-product-name}{nbsp}?

* Élémentaire permet la gestion des systèmes d'exploitation natifs Cloud depuis Rancher Manager. Il fonctionne avec n'importe quel système d'exploitation (par exemple, SLE Micro vanilla).
* Élémentaire permet la gestion native Cloud pour les machines dans les datacenters et en périphérie.
* Élémentaire est flexible et permet aux équipes de plateforme d'effectuer toutes sortes de flux de travail à travers leur Fleet de machines.

[#__elemental_product_name_with_rancher_prime]
== {elemental-product-name} avec {rancher-prime}

* Déjà profondément intégré en tant qu'extension GUI dans Rancher.
* Étend l'histoire de Rancher au système d'exploitation. Fonctionne parfaitement avec SLE Micro pour Rancher aujourd'hui.
