= Kubernetes sur le bureau avec Rancher Desktop
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/rancher-desktop.adoc 
:product-path: integrations/rancher-desktop.adoc

Rancher Desktop regroupe les outils essentiels pour développer et tester des applications cloud-native depuis votre bureau.

Si vous travaillez depuis votre machine locale sur des applications destinées aux environnements cloud, vous avez normalement besoin de beaucoup de préparation. Vous devez sélectionner un moteur de conteneur, installer Kubernetes et des utilitaires populaires, et éventuellement configurer une machine virtuelle. Installer les composants individuellement et les faire fonctionner ensemble peut être un processus chronophage.

Pour réduire la complexité, Rancher Desktop offre aux équipes les fonctionnalités clés suivantes{nbsp}:

* Installation simple et facile sur les systèmes d'exploitation macOS, Linux et Windows.
* K3s, une distribution Kubernetes légère et prête à l'emploi.
* La possibilité de passer facilement d'une version de Kubernetes à une autre.
* Un tableau de bord de cluster GUI alimenté par Rancher pour explorer votre grappe locale.
* Liberté de choisir votre moteur de conteneur{nbsp}: dockerd (moby) ou containerd.
* Paramètres de préférence pour configurer l'application selon vos besoins.
* Outils regroupés nécessaires pour votre conteneur, pour le développement basé sur Kubernetes, et pour les flux de travail opérationnels.
* Mises à jour périodiques pour maintenir les outils regroupés à jour.
* Intégration avec des outils/IDEs populaires, y compris VS Code et Skaffold.
* Contrôle d'accès aux images et aux registres.
* Prise en charge des extensions Docker.

Visitez le https://rancherdesktop.io[site de Rancher Desktop] et lisez les https://docs.rancherdesktop.io/[docs] pour en savoir plus.

Pour installer Rancher Desktop sur votre machine, consultez le https://docs.rancherdesktop.io/getting-started/installation[guide d'installation].

[#_trying_rancher_on_rancher_desktop]
== Essayer Rancher sur Rancher Desktop

Rancher Desktop offre la configuration et les outils nécessaires pour essayer facilement des applications conteneurisées basées sur Helm. Vous pouvez commencer à utiliser la plateforme de gestion Kubernetes de Rancher avec Rancher Desktop en suivant cette https://docs.rancherdesktop.io/how-to-guides/rancher-on-rancher-desktop[procédure].
