= {stackstate-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/suse-observability/index.adoc 
:product-path: integrations/suse-observability.adoc

SUSE Observability est une solution complète d'observabilité qui fournit des informations approfondies sur la santé de vos clusters et nœuds, ainsi que sur les charges de travail qui y sont exécutées. Conçu pour vous offrir une visibilité claire sur l'ensemble de votre environnement Kubernetes, l'approche full-stack de SUSE Observability vous permet d'explorer sans effort, depuis les services jusqu'à l'infrastructure, sur une seule plateforme, éliminant ainsi le recours à plusieurs outils d'observabilité.

SUSE Observability collecte et corrèle les données de manière sécurisée, offrant des informations exploitables sur les problèmes existants et potentiels dans votre cluster. Cela vous aide à résoudre rapidement les problèmes actuels et à prendre des mesures préventives contre les défis futurs.

Les tableaux de bord intuitifs mettent en évidence les zones problématiques et offrent des étapes de remédiation, vous guidant de l'identification des problèmes à l'analyse des causes profondes, et finalement à la résolution, dans les meilleurs délais.

Pour plus d'informations et pour configurer SUSE Observability dans votre cluster Kubernetes géré par SUSE Rancher, veuillez vous référer à la https://documentation.suse.com/en-us/cloudnative/suse-observability/[documentation].
