= Nutanix AOS クラスターの作成
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/nutanix/index.adoc 
:product-path: cluster-deployment/infra-providers/nutanix/nutanix.adoc
:description: Rancher を使用して Nutanix AOS (AHV) クラスターを作成します。これは、ノードのサイズを細かく制御できる異なるプロパティを持つ VM のグループで構成される場合があります。
ifeval::["{build-type}" != "community"]
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:xref-nutanix-aos-provisioning: xref:cluster-deployment/infra-providers/nutanix/provision-kubernetes-clusters-in-aos.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-landing-page: https://docs.k3s.io/
:url-rke2-landing-page: https://docs.rke2.io/
:xref-nutanix-aos-provisioning: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/nutanix/provision-kubernetes-clusters-in-aos.adoc
endif::[]

https://www.nutanix.com/products/acropolis[Nutanix Acropolis Operating System] (Nutanix AOS) は、Nutanix ハイパーコンバージドインフラストラクチャプラットフォームのオペレーティングシステムです。AOS には、 https://www.nutanix.com/products/ahv[Acropolis Hypervisor] と呼ばれるビルトインのハイパーバイザー、つまり AHV が付属しています。Nutanix AOS (AHV) と Rancher を使用することで、クラウドオペレーションをオンプレミスに持ち込むことができます。

Rancher は AOS (AHV) にノードをプロビジョニングし、それらに Kubernetes をインストールできます。AOS で Kubernetes クラスターを作成する際、Rancher は最初に Prism Central API と通信して指定された数の仮想マシンをプロビジョニングします。次に、それらの VM の上に Kubernetes をインストールします。

Nutanix クラスターは、メモリの量や vCPU の数など、異なるプロパティを持つ複数の VM グループで構成される場合があります。このグループ化により、各 Kubernetes ロールのノードサイズを細かく制御できます。

[#_creating_a_nutanix_cluster]
== Nutanix クラスターの作成

{xref-nutanix-aos-provisioning}[Nutanix AOS における Kubernetes クラスターのプロビジョニング] を参照して、Rancher を使用して Nutanix AOS に {url-rke2-landing-page}[RKE2]/{url-k3s-landing-page}[K3s] Kubernetes クラスターをインストールする方法を学んでください。
