= Helm Charts und Apps
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/helm-charts-in-rancher/index.adoc 
:product-path: cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-air-gap-rancher-ha: xref:installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc
:xref-oci-repo: xref:cluster-admin/helm-charts-in-rancher/oci-repositories.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-air-gap-rancher-ha: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha.adoc
:xref-oci-repo: xref:how-to-guides/new-user-guides/helm-charts-in-rancher/oci-repositories.adoc
endif::[]

In diesem Abschnitt lernen Sie, wie Sie Helm-Chart-Repositories und Apps in Rancher verwalten.

[#_how_helm_charts_work_in_rancher]
== Wie Helm Charts in Rancher funktionieren

Helm-Chart-Repositories in Rancher werden über *Apps* verwaltet.

Rancher verwendet ein katalogähnliches System, um Bündel von Charts aus Repositories zu importieren und diese Charts dann entweder zur Bereitstellung benutzerdefinierter Kubernetes-Anwendungen oder von Rancher-Tools wie Monitoring oder Istio zu verwenden. Rancher-Tools kommen als vorinstallierte Repositories, die als eigenständige Helm-Charts bereitgestellt werden. Zusätzliche Repositories werden nur zum aktuellen Cluster hinzugefügt.

[#_catalogs_apps_and_the_rancher_ui]
=== Kataloge, Apps und die Rancher-Benutzeroberfläche

xref:[Rancher v2.4 und früher] wurden Repositories von einsatzbereiten Anwendungen (Anwendungen) als "Kataloge" bezeichnet. Diese Repositories wurden über den Abschnitt *Kataloge* der Benutzeroberfläche verwaltet.

Rancher v2.5 ersetzte das frühere Katalogsystem durch eine neue *Apps & Marketplace*-Funktion.

Seit Rancher v2.6.5 wird die *Apps & Marketplace*-Funktion in der Benutzeroberfläche als *Apps* bezeichnet.

[#_versioning_scheme]
=== Versionsschema

Das Versionsschema der Rancher-Funktionscharts konzentriert sich auf die Hauptversion der Charts und die `+up` Annotation für Upstream-Charts, wo zutreffend.

*Hauptversion:* Die Hauptversionen der Funktionscharts sind an bestimmte Nebenversionen von Rancher gebunden. Wenn Sie ein Upgrade auf eine neue Nebenversion von Rancher durchführen, sollten Sie sicherstellen, dass alle Ihre Funktionscharts ebenfalls auf die richtige Release-Linie für das Chart aktualisiert werden.

*Charts basierend auf Upstream:* Wenn Sie ein Upgrade durchführen, stellen Sie sicher, dass die Upstream-Chart-Version mit Ihrer Rancher-Version kompatibel ist. Die `+up` Annotation für das Chart zeigt an, welche Upstream-Version das Rancher-Chart verfolgt. Zum Beispiel verfolgt `100.x.x+up16.6.0` für Monitoring den upstream kube-prometheus-stack `16.6.0` mit einigen zusätzlichen Rancher-Patches.

Beim Upgrade von Rancher-Versionen sollten Sie die Version des Charts, das Sie verwenden, nicht herabstufen. Wenn Sie beispielsweise eine Version von Monitoring verwenden, die später als `16.6.0` in Rancher v2.5 ist, sollten Sie nicht auf `100.x.x+up16.6.0` upgraden. Stattdessen sollten Sie auf die entsprechende Version in der nächsten Veröffentlichung upgraden.

[#_prerelease_versions]
==== Prerelease-Versionen

Prereleases halten sich an https://semver.org/#spec-item-9[die Spezifikation], die von https://semver.org/[Semantic Versioning 2.0.0] definiert ist. Zum Beispiel wird ein Helm-Chart mit einer Version von `0.1.3-dev.12ab4f` als Prerelease betrachtet. Prerelease-Versionen werden standardmäßig nicht angezeigt und müssen so konfiguriert werden.

Um Prerelease-Versionen anzuzeigen:

. Klicken Sie auf Ihr Benutzeravatar in der oberen rechten Ecke.
. Klicken Sie auf *Einstellungen*.
. Unter *Helm Charts* wählen Sie *Prerelease-Versionen einbeziehen*.

[#_access_charts]
== Zugriff auf Charts

Die *Charts*-Seite enthält alle Rancher-, Partner- und benutzerdefinierten Charts. Sie können Charts filtern, indem Sie das linkeste(n) Dropdown-Menü auswählen:

* Rancher-Tools wie Logging oder Monitoring sind unter dem *Rancher*-Label aufgeführt.
* Partner-Charts sind unter dem *Partners*-Label aufgeführt.
* Benutzerdefinierte Charts sind unter dem Namen ihres jeweiligen Repository aufgeführt.

Alle drei Arten von Charts werden auf die gleiche Weise bereitgestellt und verwaltet.

[NOTE]
====

Apps, die vom Cluster-Manager (der globalen Ansicht in der alten Rancher-Benutzeroberfläche) verwaltet werden, werden weiterhin nur vom Cluster-Manager verwaltet, und Apps, die mit *Apps* in der neuen Benutzeroberfläche verwaltet werden, müssen nur von *Apps* verwaltet werden.
====


Um auf die *Charts*-Seite zuzugreifen:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Finden Sie den Namen des Clusters, dessen Charts Sie aufrufen möchten. Klicken Sie *Erforschen* am Ende der Zeile des Clusters.
. Im linken Navigationsmenü auf dem *Cluster-Dashboard* klicken Sie menu:Apps[Charts].

[#_manage_repositories]
== Repositories verwalten

Die *Repositories*-Seite listet Ihre Helm-Repositories auf. Diese umfassen traditionelle Helm-Endpunkte, die ein index.yaml haben, und Git-Repositories, die geklont werden und auf einen bestimmten Branch verweisen. Um benutzerdefinierte Charts zu verwenden, fügen Sie hier Ihr Repository hinzu. Nachdem Sie ein Repository hinzugefügt haben, können Sie auf benutzerdefinierte Charts auf der *Charts*-Seite zugreifen, die unter dem Namen des Repository aufgeführt sind.

Um auf die *Repositories*-Seite zuzugreifen:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Finden Sie den Namen des Clusters, dessen Repositories Sie aufrufen möchten. Klicken Sie *Erforschen* am Ende der Zeile des Clusters.
. Im linken Navigationsmenü auf dem *Cluster-Dashboard* klicken Sie menu:Apps[Repositories].

[#_add_custom_git_repositories]
=== Benutzerdefinierte Git-Repositories hinzufügen

Um ein benutzerdefiniertes Git-Repository hinzuzufügen, das Ihre Helm-Charts oder Cluster-Vorlagendefinitionen enthält:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Finden Sie den Namen des Clusters, dessen Repositories Sie aufrufen möchten. Klicken Sie *Erforschen* am Ende der Zeile des Clusters.
. Im linken Navigationsmenü auf dem *Cluster-Dashboard* klicken Sie menu:Apps[Repositories].
. Klicken Sie auf *Erstellen*.
. Wählen Sie das Ziel, *Git-Repository, das Helm-Chart...*.
. Sie müssen einen Namen und eine Git-Repository-URL eingeben. Die anderen Felder, einschließlich der Beschreibung, sind optional. Geben Sie einen alternativen Branch-Namen ein, wenn Sie nicht von dem Branch abrufen möchten, den der Repository-Besitzer als Standard festgelegt hat. In der Regel heißt der Standard-Branch entweder `main` oder `master`.
. Klicken Sie *Erstellen*, um das Repository hinzuzufügen.

Nachdem Sie ein Chart-Repository zu Rancher hinzugefügt haben, steht es sofort zur Verfügung.

[#_add_custom_helm_chart_repositories]
=== Benutzerdefinierte Helm-Chart-Repositories hinzufügen

Sie können Ihre eigenen Helm-Chart-Repositories hinzufügen, um Chart-Pakete an Rancher bereitzustellen. Sie können jeden HTTP-Server verwenden, solange der Server auf GET-Anfragen reagieren und YAML-Dateien sowie Tarball-Dateien bereitstellen kann.

Für weitere Informationen zu Helm-Chart-Repositories siehe die https://helm.sh/docs/topics/chart_repository/[offiziellen Helm-Dokumente].

Um ein benutzerdefiniertes Helm-Chart-Repository zu Rancher hinzuzufügen:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Finden Sie den Namen des Clusters, dessen Repositories Sie aufrufen möchten. Klicken Sie *Erforschen* am Ende der Zeile des Clusters.
. Im linken Navigationsmenü auf dem *Cluster-Dashboard* klicken Sie menu:Apps[Repositories].
. Klicken Sie auf *Erstellen*.
. Wählen Sie das Ziel, *http(s) URL zu einem von Helm generierten Index*.
. Geben Sie einen Repository-Namen und die Index-URL-Adresse des Chart-Repositories ein.
. Klicken Sie *Erstellen*, um das Repository hinzuzufügen.

[#_add_private_git_helm_chart_repositories]
=== Fügen Sie private Git/Helm-Chart-Repositories hinzu

Sie können private Git- oder Helm-Chart-Repositories mit SSH-Schlüssel-Anmeldeinformationen oder einem HTTP-Basic-Auth-Geheimnis, wie einem Benutzernamen und Passwort, hinzufügen.

[#_add_a_private_ca_to_repositories]
=== Fügen Sie ein privates CA-Zertifikat zu Repositories hinzu

Um ein privates CA-Zertifikat zu Helm-Chart-Repositories hinzuzufügen, müssen Sie eine base64-kodierte Kopie des CA-Zertifikats im DER-Format zu dem `spec.caBundle field` des Chart-Repositories hinzufügen, wie `openssl x509 -outform der -in ca.pem | base64 -w0`. Die Anweisungen sind für Git-basierte und HTTP-basierte Repositories gleich:

. Klicken Sie auf *☰*. Unter *Cluster erkunden* im linken Navigationsmenü wählen Sie einen Cluster aus.
. Im linken Navigationsmenü auf dem *Cluster-Dashboard* klicken Sie menu:Apps[Repositories].
. Suchen Sie die Zeile, die mit dem Git-basierten oder HTTP-basierten Repository verknüpft ist, zu dem Sie ein privates CA-Zertifikat hinzufügen möchten, und klicken Sie auf *⋮ > YAML bearbeiten*.
. Setzen Sie den `caBundle` Wert, wie im folgenden Beispiel:

[,yaml]
----
    [...]
    spec:
      caBundle:
    MIIFXzCCA0egAwIBAgIUWNy8WrvSkgNzV0zdWRP79j9cVcEwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtNeU9yZywgSW5jLjENMAsGA1UEAwwEcm9vdDAeFw0yMTEyMTQwODMyMTdaFw0yNDEwMDMwODMyMT
    ...
    nDxZ/tNXt/WPJr/PgEB3hQdInDWYMg7vGO0Oz00G5kWg0sJ0ZTSoA10ZwdjIdGEeKlj1NlPyAqpQ+uDnmx6DW+zqfYtLnc/g6GuLLVPamraqN+gyU8CHwAWPNjZonFN9Vpg0PIk1I2zuOc4EHifoTAXSpnjfzfyAxCaZsnTptimlPFJJqAMj+FfDArGmr4=
    [...]
----

[NOTE]
.Helm-Chart-Repositories mit Authentifizierung
====

Die Repository.Spec enthält einen `disableSameOriginCheck` Wert. Dieser Wert ermöglicht es Ihnen, die Same-Origin-Prüfungen zu umgehen, indem die Authentifizierungsinformationen des Repositories als Basic Auth-Header mit allen API-Aufrufen gesendet werden. Dies wird nicht empfohlen, kann jedoch als vorübergehende Lösung in Fällen von nicht standardmäßigen Helm-Chart-Repositories verwendet werden, wie z.B. solchen, die Weiterleitungen zu einer anderen Ursprungs-URL haben.

Um diese Funktion für ein bestehendes Helm-Chart-Repository zu nutzen, folgen Sie den vorherigen Schritten bis zur Bearbeitung des YAML. Fügen Sie im `spec` Abschnitt der YAML-Datei `disableSameOriginCheck` hinzu und setzen Sie es auf `true`.

[,yaml]
----
[...]
spec:
  disableSameOriginCheck: true
[...]
----
====


[#_add_custom_oci_chart_repositories]
=== Benutzerdefinierte OCI-Chart-Repositorys hinzufügen

Helm v3 führte die Speicherung von Helm-Charts als https://opencontainers.org/about/overview/[Open Container Initiative (OCI)] Artefakte in Container-Registries ein. Mit Rancher v2.9.0 können Sie https://helm.sh/docs/topics/registries/[OCI-basierte Helm-Chart-Repositories] neben HTTP-basierten und Git-basierten Repositories hinzufügen. Das bedeutet, dass Sie Apps bereitstellen können, die als OCI-Artefakte gespeichert sind. Für weitere Informationen siehe {xref-oci-repo}[Verwendung von OCI Helm-Chart-Repositories].

[#_helm_compatibility]
=== Helm-Kompatibilität

Es werden nur Helm 3-kompatible Charts unterstützt.

[#_refresh_chart_repositories]
=== Chart-Repositories aktualisieren

Die *Aktualisieren*-Schaltfläche kann verwendet werden, um Änderungen von ausgewählten Helm-Chart-Repositories auf der *Repositories*-Seite zu synchronisieren.

Um ein Chart-Repository zu aktualisieren:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Finden Sie den Namen des Clusters, dessen Repositories Sie aufrufen möchten. Klicken Sie *Erforschen* am Ende der Zeile des Clusters.
. Im linken Navigationsmenü auf dem *Cluster-Dashboard* klicken Sie menu:Apps[Repositories].
. Verwenden Sie den Schalter neben dem *Status*-Feld, um alle Repositories auszuwählen, oder schalten Sie bestimmte Chart-Repositories um, um Änderungen zu synchronisieren.
. Klicken Sie auf *Aktualisieren*.
. Das *⋮* am Ende jeder Zeile des Chart-Repositories enthält ebenfalls eine *Aktualisieren*-Option, die angeklickt werden kann, um das jeweilige Repository zu aktualisieren.

Nicht-Airgap-Rancher-Installationen spiegeln bei der Aktualisierung sofort alle Änderungen des Chart-Repositories wider, und Sie werden sehen, dass das *Status*-Feld für aktualisierte Repositories von `In Progress` auf `Active` wechselt, sobald die Aktion abgeschlossen ist.

Airgap-Installationen, bei denen Rancher so konfiguriert ist, dass es die verpackte Kopie der Helm-Systemcharts ({xref-air-gap-rancher-ha}#_helm_chart_options_for_air_gap_installations[`useBundledSystemChart=true`]) verwendet, beziehen sich nur auf das https://github.com/rancher/system-charts[system-chart] Repository, das gebündelt ist, und können nicht aktualisiert oder synchronisiert werden.

[#_refresh_interval]
==== Intervall für Neuanzeige

Rancher v2.10.0 fügt das `refreshInterval` Feld zur `ClusterRepo` CRD hinzu. Der Standardwert beträgt 3600 Sekunden, was bedeutet, dass Rancher jedes Helm-Repository alle 3600 Sekunden synchronisiert.

Um das Aktualisierungsintervall eines Chart-Repositories zu ändern:

. Klicken Sie auf **☰ > Clusterverwaltung**.
. Finden Sie den Namen des Clusters, dessen Repositories Sie aufrufen möchten. Klicken Sie **Erforschen** am Ende der Zeile des Clusters.
. Klicken Sie im linken Navigationsmenü auf dem **Cluster-Dashboard** auf **Apps > Repositories**.
. Suchen Sie das Repository, das Sie ändern möchten, und klicken Sie auf **⋮ > YAML bearbeiten**.
. Setzen Sie das **refreshInterval** Feld unter **Spec** auf den gewünschten Wert in Sekunden.
. Klicken Sie auf **Speichern**.

[#_enable_disable_helm_chart_repositories]
=== Aktivieren/Deaktivieren von Helm-Chart-Repositories

Rancher v2.10.0 fügt die Möglichkeit hinzu, Helm-Repositories zu aktivieren und zu deaktivieren. Helm-Repositories sind standardmäßig aktiviert.

Um ein Chart-Repository zu deaktivieren:

. Klicken Sie auf **☰ > Clusterverwaltung**.
. Finden Sie den Namen des Clusters, dessen Repositories Sie aufrufen möchten. Klicken Sie **Erforschen** am Ende der Zeile des Clusters.
. Klicken Sie im linken Navigationsmenü auf dem **Cluster-Dashboard** auf **Apps > Repositories**.
. Suchen Sie das Repository, das Sie deaktivieren möchten, und klicken Sie auf **⋮ > YAML bearbeiten**.
. Setzen Sie das **Enabled** Feld unter **Spec** auf **false**.
. Klicken Sie auf **Speichern**.
. Wenn Sie ein Repository deaktivieren, werden Updates deaktiviert und neue Änderungen am clusterRepo werden nicht angewendet.

Um ein Chart-Repository zu aktivieren:

. Klicken Sie auf **☰ > Clusterverwaltung**.
. Finden Sie den Namen des Clusters, dessen Repositories Sie aufrufen möchten. Klicken Sie **Erforschen** am Ende der Zeile des Clusters.
. Klicken Sie im linken Navigationsmenü auf dem **Cluster-Dashboard** auf **Apps > Repositories**.
. Suchen Sie das Repository, das Sie aktivieren möchten, und klicken Sie auf **⋮ > YAML bearbeiten**.
. Setzen Sie das **Enabled** Feld unter **Spec** auf **true**.
. Klicken Sie auf **Speichern**.

[#_deploy_and_upgrade_charts]
== Charts bereitstellen und aktualisieren

Um ein Chart zu installieren und bereitzustellen:

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Finden Sie den Namen des Clusters, dessen Repositories Sie aufrufen möchten. Klicken Sie *Erforschen* am Ende der Zeile des Clusters.
. Im linken Navigationsmenü auf dem *Cluster-Dashboard* klicken Sie menu:Apps[Charts].
. Wählen Sie ein Chart aus und klicken Sie auf *Installieren*.

Rancher- und Partner-Charts können zusätzliche Konfigurationen über benutzerdefinierte Seiten oder questions.yaml-Dateien haben. Alle Chart-Installationen können jedoch die values.yaml und andere grundlegende Einstellungen ändern. Nachdem Sie auf *Installieren* geklickt haben, wird ein Helm-Betriebsjob bereitgestellt, und die Konsole für den Job wird angezeigt.

Um alle aktuellen Änderungen anzuzeigen, klicken Sie auf menu:Apps[Aktuelle Vorgänge] im linken Navigationsmenü. Von dort aus können Sie die Aufrufe, Bedingungen, Ereignisse und Protokolle einsehen.

Nach der Installation eines Charts können Sie es anzeigen, indem Sie auf menu:Apps[Installierte Apps] im linken Navigationsmenü klicken. Sie können die Installation upgraden oder entfernen und weitere Details einsehen. Das Upgrade verwendet die gleichen Formulare und Werte wie bei der ursprünglichen Installation.

Die meisten Rancher-Tools haben zusätzliche Seiten in der Symbolleiste unter dem Abschnitt *Apps*, um die Funktionen zu verwalten und zu nutzen. Diese Seiten enthalten Links zu Dashboards, Formulare zum einfachen Hinzufügen von benutzerdefinierten Ressourcen und zusätzliche Informationen.

[CAUTION]
====

Wenn Sie Ihr Chart mit *Helm-Optionen vor dem Upgrade anpassen* upgraden und Ihr Chart unveränderliche Felder enthält, kann die Verwendung der `--force`-Option zu Fehlern führen. Das liegt daran, dass einige Objekte in Kubernetes nach ihrer Erstellung nicht mehr geändert werden können. Um diesen Fehler zu vermeiden:

* Verwenden Sie die Standard-Upgrade-Option (d.h. verwenden Sie nicht `--force`).
* Deinstallieren Sie das vorhandene Chart und installieren Sie das upgegradete Chart.
* Löschen Sie die Ressourcen mit unveränderlichen Feldern aus dem Cluster, bevor Sie ein erzwungenes Upgrade durchführen.
====


[#_legacy_apps]
=== Legacy-Apps

Die Upgrade-Schaltfläche ist für Legacy-Apps auf der Seite menu:Apps[Installierte Apps] nicht verfügbar.

Wenn Sie eine installierte Legacy-App aktualisieren möchten, muss das {xref-experimental-features}[Legacy-Feature-Flag] aktiviert sein. Dieses Flag wird automatisch aktiviert, wenn Sie bereits eine Legacy-App hatten, bevor Sie Rancher aktualisiert haben.

. Aktivieren Sie das {xref-experimental-features}[Legacy-Feature-Flag], falls es noch nicht aktiviert ist.
. Klicken Sie auf *☰ > Clusterverwaltung*.
. Finden Sie den Namen des Clusters, dessen Apps Sie aufrufen möchten. Klicken Sie *Erforschen* am Ende der Zeile des Clusters.
. Klicken Sie auf menu:Legacy[Projekt> Apps].

Wenn Sie *Apps* nicht unter menu:Legacy[Projekt] sehen, klicken Sie auf die Suchleiste für Projekt/Namensraum in der oberen Navigation und wählen Sie das relevante Projekt aus dem Dropdown-Menü aus.

Um Legacy-Multi-Cluster-Apps zu upgraden:

. Klicken Sie auf *☰*.
. Unter *Legacy Apps* klicken Sie auf *Multi-Cluster-Apps*.

[#_chart_specific_information]
=== Chart-spezifische Informationen

[#_sriov_chart_deprecation_and_migration]
==== SR-IOV-Chart-Abkündigung und Migration

Das `sriov` (SR-IOV-Netzwerkoperator) Chart aus dem Rancher Charts Repository ist abgekündigt und wird in Rancher v2.10 entfernt. Bitte migrieren Sie stattdessen zum `sriov-network-operator` Chart aus dem SUSE Edge Repository (https://github.com/suse-edge/charts).

Um zu migrieren, folgen Sie diesen Schritten:

. Fügen Sie das SUSE Edge Repository zu Ihrem Cluster hinzu, indem Sie die Schritte in <<_add_custom_git_repositories,Benutzerdefinierte Git-Repositories hinzufügen>> befolgen.
. Geben Sie im Feld *Git Repo URL* `https://github.com/suse-edge/charts` ein.
. Klicken Sie auf *Erstellen*.
. Im linken Navigationsmenü auf dem *Cluster-Dashboard* klicken Sie menu:Apps[Charts].
. Suchen Sie das `sriov-network-operator` Chart und klicken Sie darauf.
. Klicken Sie auf *Installieren*.
. Geben Sie im Feld *Name* denselben Namen ein, den Sie für Ihre bestehende `sriov` Chart-Installation verwendet haben.
. Klicken Sie auf *Weiter*.
. Klicken Sie auf *Installieren*.

*Ergebnis:* Rancher leitet zur Seite *Installierte Apps* weiter, wo Ihre bestehende Installation den Status *Wird aktualisiert* erreicht. Die Migration ist abgeschlossen, wenn der Status *Bereitgestellt* erreicht ist.

[#_limitations]
== Nutzungsbeschränkungen

* Dashboard-Apps oder Rancher-Funktionscharts können nicht über die Rancher Kommandozeilenschnittstelle installiert werden.
* Bei der Bestimmung der neuesten Version, die für die Spalte *Upgradefähig* auf der Seite menu:Apps[Installierte Apps] angezeigt werden soll, berücksichtigt Rancher nicht nur die Versionen des Helm-Charts aus dem Repository, aus dem es installiert wurde, sondern auch die Versionen des Helm-Charts aus allen Repositories im Cluster.
+
Angenommen, Sie installieren `cert-manager` v1.13.0 aus Repository A, wo v1.14.0 jetzt die neueste verfügbare Version ist. In diesem Fall erwarten Sie, dass *Upgradefähig* v1.14.0 anzeigt. Wenn der Cluster jedoch auch Zugriff auf Repository B hat, wo v1.15.0 von `cert-manager` verfügbar ist, zeigt *Upgradefähig* v1.15.0 an, obwohl die ursprüngliche Installation Repository A verwendet hat.
