= {rancher-product-name} Integração com serviços de registro
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/index.adoc 
:product-path: observability/logging/logging.adoc
:description: O Rancher se integra a serviços de registro populares. Saiba os requisitos e benefícios de integrar-se a serviços de registro e habilite o registro em seu cluster.
ifeval::["{build-type}" != "community"]
:xref-logging-taints-and-tolerations: xref:observability/logging/taints-and-tolerations.adoc
:xref-logging-helm-chart-options: xref:observability/logging/logging-helm-chart-options.adoc
:xref-logging-architecture: xref:observability/logging/logging-architecture.adoc
:xref-logging-rbac: xref:observability/logging/rbac-for-logging.adoc
:xref-logging-flows-clusterflows: xref:observability/logging/custom-resource-configuration/flows-and-clusterflows.adoc
:xref-logging-outputs-clusteroutputs: xref:observability/logging/custom-resource-configuration/outputs-and-clusteroutputs.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-logging-taints-and-tolerations: xref:integrations-in-rancher/logging/taints-and-tolerations.adoc
:xref-logging-helm-chart-options: xref:integrations-in-rancher/logging/logging-helm-chart-options.adoc
:xref-logging-architecture: xref:integrations-in-rancher/logging/logging-architecture.adoc
:xref-logging-rbac: xref:integrations-in-rancher/logging/rbac-for-logging.adoc
:xref-logging-flows-clusterflows: xref:integrations-in-rancher/logging/custom-resource-configuration/flows-and-clusterflows.adoc
:xref-logging-outputs-clusteroutputs: xref:integrations-in-rancher/logging/custom-resource-configuration/outputs-and-clusteroutputs.adoc
endif::[]

O https://kube-logging.github.io/docs/[Operador de Registro] agora alimenta a solução de registro do Rancher em vez da antiga solução interna.

[#_enabling_logging]
== Habilitando Registro

Você pode habilitar o registro para um cluster gerenciado pelo Rancher acessando a página de Aplicativos e instalando o aplicativo de registro.

. Vá para o cluster onde deseja instalar o registro e clique em *Aplicativos*.
. Clique no aplicativo *Registro*.
. Role até o final do README do gráfico Helm e clique em *Instalar*.

*Resultado:* O aplicativo de registro está implantado no namespace `cattle-logging-system`.

[#_uninstall_logging]
== Desinstalar Registro

. Vá para o cluster onde deseja instalar o registro e clique em *Aplicativos*.
. Clique em *Apps Instalados*.
. Vá para o namespace `cattle-logging-system` e marque as caixas para `rancher-logging` e `rancher-logging-crd`.
. Clique em *Excluir*.
. Confirme *Excluir*.

*Resultado* `rancher-logging` está desinstalado.

[#_architecture]
== Arquitetura

Para mais informações sobre como o aplicativo de registro funciona, veja {xref-logging-architecture}[esta seção.]

[#_role_based_access_control]
== Controle de acesso com base em função

O registro do Rancher tem dois papéis, `logging-admin` e `logging-view`. Para mais informações sobre como e quando usar esses papéis, veja {xref-logging-rbac}[esta página.]

[#_configuring_logging_custom_resources]
== Configurando Recursos Personalizados de Registro

Para gerenciar `Flows,` `ClusterFlows`, `Outputs` e `ClusterOutputs`,

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster onde você deseja configurar recursos personalizados de registro e clique em *Explorar*.
. Na barra de navegação à esquerda, clique em *Registro*.

[#_flows_and_clusterflows]
=== Fluxos e ClusterFlows

Para ajuda com a configuração de `Flows` e `ClusterFlows`, veja {xref-logging-flows-clusterflows}[esta página.]

[#_outputs_and_clusteroutputs]
=== Saídas e ClusterOutputs

Para ajuda com a configuração de `Outputs` e `ClusterOutputs`, veja {xref-logging-outputs-clusteroutputs}[esta página.]

[#_using_a_custom_hosttailer_image]
== Usando uma Imagem Customizada do HostTailer

Para usar uma imagem customizada para o recurso `HostTailer`, você precisa especificar a imagem na seção `containerOverrides` de cada `fileTailer` do recurso `HostTailer`.

[,yaml]
----
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: cluster-system-log
spec:
  workloadMetaOverrides:
    annotations: {}
    labels: {}
  fileTailers:
    - disabled: false
      name: kubelet-log
      path: /var/lib/rancher/rke2/agent/logs/*.log
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
    - disabled: false
      name: containerd-log
      path: /var/lib/rancher/rke2/agent/containerd/*.log
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
    - name: kube-audit
      path: /var/log/kube-audit/audit-log.json
      disabled: false
      containerOverrides:
        image: <your_registry>/<your_image>:<your_tag>
----

[#_configuring_the_logging_helm_chart]
== Configurando o Helm Chart de registro

Para uma lista de opções que podem ser configuradas quando o aplicativo de registro é instalado ou atualizado, consulte {xref-logging-helm-chart-options}[esta página.]

[#_windows_support]
=== Suporte ao Windows

Você pode xref:./logging-helm-chart-options.adoc#_enabledisable_windows_node_logging[ativar o registro] a partir de nós Windows.

[#_working_with_a_custom_docker_root_directory]
=== Trabalhando com um Diretório Raiz do Docker Customizado

Para detalhes sobre como usar um diretório raiz do Docker customizado, consulte xref:./logging-helm-chart-options.adoc#_working_with_a_custom_docker_root_directory[esta seção.]

[#_working_with_taints_and_tolerations]
=== Trabalhando com Taints e Tolerations

Para informações sobre como usar taints e tolerations com o aplicativo de registro, consulte {xref-logging-taints-and-tolerations}[esta página.]

[#_logging_v2_with_selinux]
=== Registro V2 com SELinux

Para informações sobre como habilitar o aplicativo de registro para nós com SELinux habilitado, consulte xref:./logging-helm-chart-options.adoc#_enabling_the_logging_application_to_work_with_selinux[esta seção.]

[#_additional_logging_sources]
=== Fontes de Log Adicionais

Por padrão, o Rancher coleta registros dos componentes do plano de controle e dos nós para todos os tipos de cluster. Em alguns casos, registros adicionais podem ser coletados. Para detalhes, consulte xref:./logging-helm-chart-options.adoc#_additional_logging_sources[esta seção.]

[#_troubleshooting]
== Solução de problemas

[#_the_logging_buffer_overloads_pods]
=== O buffer de registro sobrecarrega os pods.

Dependendo da sua configuração, o tamanho do buffer padrão pode ser muito grande e causar falhas nos pods. Uma maneira de reduzir a carga é diminuir o intervalo de descarregamento do logger. Isso evita que os registros sobrecarreguem o buffer. Você também pode adicionar mais threads de descarregamento para lidar com momentos em que muitos registros estão tentando preencher o buffer ao mesmo tempo.

Para uma descrição mais completa de como configurar o buffer de registro para atender às necessidades da sua organização, consulte a documentação oficial do operador de registro em https://kube-logging.github.io/docs/configuration/plugins/outputs/buffer/[buffers] e em https://kube-logging.github.io/docs/logging-infrastructure/fluentd/[configuração do Fluentd].

[#_the_cattle_logging_namespace_being_recreated]
=== O Namespace `cattle-logging` Sendo Recriado

Se seu cluster anteriormente implantou registro a partir da visão global na interface legada do Rancher, você pode encontrar um problema em que seu namespace `cattle-logging` está sendo continuamente recriado.

A solução é excluir todos os recursos personalizados `clusterloggings.management.cattle.io` e `projectloggings.management.cattle.io` do namespace específico do cluster no cluster de gerenciamento.
A existência desses recursos personalizados faz com que o Rancher crie o namespace `cattle-logging` no cluster downstream se ele não existir.

O namespace do cluster corresponde ao ID do cluster, então precisamos encontrar o ID do cluster para cada cluster.

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster do qual você deseja obter o ID e clique em *Explorar*.
. Copie a parte `<cluster-id>` de uma das URLs abaixo. A parte `<cluster-id>` é o nome do namespace do cluster.

[,bash]
----
# Cluster Management UI
https://<your-url>/c/<cluster-id>/

# Cluster Dashboard
https://<your-url>/dashboard/c/<cluster-id>/
----

Agora que temos o `<cluster-id>` namespace, podemos excluir os CRs que fazem com que `cattle-logging` seja continuamente recriado.
_Aviso:_ certifique-se de que o registro, a versão instalada a partir da visão global na interface legada do Rancher, não esteja atualmente em uso.

[,bash]
----
kubectl delete crd clusterloggings.management.cattle.io -n <cluster-id>
kubectl delete crd projectloggings.management.cattle.io -n <cluster-id>
----
