= Einrichten von lokalen System-Charts für Air-Gapped-Installationen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/local-system-charts.adoc 
:product-path: installation-and-upgrade/other-installation-methods/air-gapped/local-system-charts.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap: xref:einsteiger/installation-und-upgrade/andere-installationsmethoden/air-gapped-helm-cli-install/index.adoc
endif::[]

Das https://github.com/rancher/charts[Charts] Repository enthält alle Helm-Katalogelemente, die für Funktionen wie Überwachung, Protokollierung, Alarmierung und Istio erforderlich sind.

Bei einer Air-Gapped-Installation von Rancher müssen Sie Rancher so konfigurieren, dass es eine lokale Kopie der System-Charts verwendet. Dieser Abschnitt beschreibt, wie lokale System-Charts mit einem Flag der Kommandozeilenschnittstelle verwendet werden.

[#_using_local_system_charts]
== Verwendung lokaler System-Charts

Eine lokale Kopie von `system-charts` wurde in den `rancher/rancher` Container gepackt. Um diese Funktionen in einer Air-Gapped-Installation nutzen zu können, müssen Sie den Rancher-Installationsbefehl mit einer zusätzlichen Umgebungsvariable `CATTLE_SYSTEM_CATALOG=bundled` ausführen, die Rancher anweist, die lokale Kopie der System-Charts anstelle des Versuchs, sie von GitHub abzurufen, zu verwenden.

Beispielbefehle für eine Rancher-Installation mit einem gebündelten `system-charts` sind in den {xref-air-gap}[Anweisungen zur Air-Gapped-Installation] für Docker- und Helm-Installationen enthalten.
