= Usando tokens de API
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-06
:page-revdate: {revdate}
:community-path: api/api-tokens.adoc 
:product-path: api/api-tokens.adoc
ifeval::["{build-type}" != "community"]
:xref-api-reference: xref:api/reference.adoc
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
:xref-kubeconfig-file: xref:cluster-admin/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc
:xref-kubectl: xref:rancher-admin/cli/kubectl.adoc
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-api-reference: xref:api/api-reference.adoc
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
:xref-kubeconfig-file: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/authorized-cluster-endpoint.adoc
:xref-kubectl: xref:reference-guides/cli-with-rancher/kubectl-utility.adoc
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
endif::[]

include::shared:ROOT:partial$en/v3-api-tokens-deprecation-warning.adoc[]

Rancher v2.8.0 introdujo el {xref-api-reference}[API de Kubernetes de Rancher] que se puede usar para gestionar recursos de Rancher a través de `kubectl`. Esta página cubre información sobre los tokens de API utilizados con el {xref-rancher-cli}[Rancher CLI], {xref-kubeconfig-file}#_about_the_kubeconfig_file[archivos kubeconfig], Terraform y el xref:api/v3-rancher-api-guide.adoc#_enable_view_in_api[navegador de API v3].

Por defecto, algunos tokens de API a nivel de clúster se generan con un tiempo de vida infinito (`ttl=0`). En otras palabras, los tokens de API con `ttl=0` nunca expiran a menos que los invalides. Los tokens no se invalidan al cambiar una contraseña.

Puedes desactivar los tokens de API eliminándolos o desactivando la cuenta de usuario.

[#_deleting_tokens]
== Eliminando tokens

Para eliminar un token:

. Ve a la lista de todos los tokens en la vista de API de Rancher en `\https://<Rancher-Server-IP>/v3/tokens`.
. Accede al token que deseas eliminar por su ID. Por ejemplo, `\https://<Rancher-Server-IP>/v3/tokens/kubectl-shell-user-vqkqt`
. Haz clic en *Eliminar*.

La siguiente es una lista completa de tokens generados con `ttl=0`:

|===
| Testigo | Descripción

| `kubectl-shell-*`
| Acceso a la shell `kubectl` en el navegador

| `agent-*`
| Token para el despliegue de agentes

| `compose-token-*`
| Token para Compose

| `helm-token-*`
| Token para el despliegue del gráfico de Helm

| `drain-node-*`
| Token para drenar (Rancher utiliza `kubectl` para drenar porque no hay una API nativa de Kubernetes).
|===

[#_setting_ttl_on_kubeconfig_tokens]
== Configurando TTL en Tokens de Kubeconfig

Los administradores pueden establecer un tiempo de vida global (TTL) en los tokens de Kubeconfig. Cambiar el TTL predeterminado de kubeconfig se puede hacer navegando a la configuración global y estableciendo <<_kubeconfig_default_token_ttl_minutes,`kubeconfig-default-token-ttl-minutes`>> a la duración deseada en minutos. A partir de Rancher v2.8, el valor predeterminado de <<_kubeconfig_default_token_ttl_minutes,`kubeconfig-default-token-ttl-minutes`>> es `43200`, lo que significa que los tokens expiran en 30 días.

[NOTE]
====

Esta configuración es utilizada por todos los tokens de kubeconfig excepto aquellos creados por la CLI para <<_disable_tokens_in_generated_kubeconfigs,generar tokens de kubeconfig>>.
====


[#_disable_tokens_in_generated_kubeconfigs]
== Desactivar Tokens en Kubeconfigs Generados

Establece la configuración `kubeconfig-generate-token` a `false`. Esta configuración instruye a Rancher a no generar automáticamente un token cuando un usuario hace clic en descargar un archivo kubeconfig. Cuando esta configuración está desactivada, un kubeconfig generado hace referencia a {xref-kubectl}#_authentication_with_kubectl_and_kubeconfig_tokens_with_ttl[Rancher CLI] para recuperar un token de corta duración para el clúster. Cuando este kubeconfig se utiliza en un cliente, como `kubectl`, se necesita tener instalado el Rancher CLI para completar la solicitud de inicio de sesión.

[#_token_hashing]
== Hashing de Token

Puede {xref-experimental-features}[habilitar el hashing de tokens], donde los tokens pasan por un hash unidireccional utilizando el algoritmo SHA256. Este es un proceso no reversible: una vez habilitado, esta función no se puede desactivar. Primero deberías evaluar esta configuración en un entorno de prueba y/o hacer copias de seguridad antes de habilitarla.

Esta función afecta a todos los tokens que incluyen, pero no se limitan a, los siguientes:

* Tokens de Kubeconfig
* Tokens Bearer, claves/llamadas de API
* Tokens utilizados por operaciones internas

[#_token_settings]
== Configuraciones de Token

Estas configuraciones globales afectan el comportamiento de los tokens de Rancher.

|===
| Valor | Descripción

| <<_auth_user_session_ttl_minutes,`auth-user-session-ttl-minutes`>>
| TTL en minutos en un token de sesión de autenticación de usuario.

| <<_auth_user_session_idle_ttl_minutes, `auth-user-session-idle-ttl-minutes`>>
| TTL en minutos en un token de sesión de autenticación de usuario, sin actividad del usuario.

| <<_kubeconfig_default_token_ttl_minutes,`kubeconfig-default-token-ttl-minutes`>>
| TTL por defecto aplicado a todos los tokens de kubeconfig, excepto a los tokens <<_disable_tokens_in_generated_kubeconfigs,generados por Rancher CLI>>.

| <<_auth_token_max_ttl_minutes,`auth-token-max-ttl-minutes`>>
| TTL máximo para todos los tokens, excepto aquellos controlados por <<_auth_user_session_ttl_minutes,`auth-user-session-ttl-minutes`>>.

| <<_kubeconfig_generate_token,`kubeconfig-generate-token`>>
| Si es verdadero, genera automáticamente tokens cuando un usuario descarga un kubeconfig.
|===

[#_auth_user_session_ttl_minutes]
=== auth-user-session-ttl-minutes

Duración del tiempo de vida (TTL) en minutos, utilizada para determinar cuándo expira un token de sesión de autenticación de usuario. Cuando expira, el usuario debe iniciar sesión y obtener un nuevo token. Esta configuración no se ve afectada por <<_auth_token_max_ttl_minutes,`auth-token-max-ttl-minutes`>>. Los tokens de sesión se crean cuando un usuario inicia sesión en Rancher.

[#_auth_user_session_idle_ttl_minutes]
=== auth-user-session-idle-ttl-minutes

Tiempo de vida (TTL) sin actividad del usuario para los tokens de sesión de inicio de sesión, en minutos.
Por defecto, `auth-user-session-idle-ttl-minutes` se establece en el mismo valor que <<_auth_user_session_ttl_minutes, `auth-user-session-ttl-minutes`>> (por compatibilidad hacia atrás). Nunca debe exceder el valor de `auth-user-session-ttl-minutes`.

[#_kubeconfig_default_token_ttl_minutes]
=== kubeconfig-default-token-ttl-minutes

Duración del tiempo de vida (TTL) en minutos, utilizada para determinar cuándo expira un token de kubeconfig. Cuando el token ha expirado, la API rechaza el token. Esta configuración no puede ser mayor que <<_auth_token_max_ttl_minutes,`auth-token-max-ttl-minutes`>>. Esta configuración se aplica a los tokens generados en un archivo kubeconfig solicitado, excepto para los tokens <<_disable_tokens_in_generated_kubeconfigs,generados por Rancher CLI>>. A partir de Rancher v2.8, la duración por defecto es `43200`, lo que significa que los tokens expiran en 30 días.

[#_auth_token_max_ttl_minutes]
=== auth-token-max-ttl-minutes

Tiempo de vida (TTL) máximo en minutos permitido para los tokens de autenticación. Si un usuario intenta crear un token con un TTL mayor que `auth-token-max-ttl-minutes`, Rancher establece el TTL del token al valor de `auth-token-max-ttl-minutes`. Se aplica a todos los tokens de kubeconfig y tokens de API. A partir de Rancher v2.8, la duración por defecto es `129600`, lo que significa que los tokens expiran en 90 días.

[#_kubeconfig_generate_token]
=== kubeconfig-generar-token

Cuando es verdadero, los kubeconfigs solicitados a través de la interfaz de usuario contienen un token válido. Cuando es falso, los kubeconfigs contienen un comando que utiliza el Rancher CLI para solicitar al usuario que inicie sesión. {xref-kubectl}#_autenticación_con_kubectl_y_tokens_de_kubeconfig_con_ttl[El CLI luego recupera y almacena en caché un token para el usuario]. +
cli/kubectl.adoc#_autenticación_con_kubectl_y_tokens_de_kubeconfig_con_ttl[El CLI luego recupera y almacena en caché un token para el usuario].
