= Servidor de API de extensión
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 20-08-2025
:page-revdate: {revdate}
:community-path: api/extension-apiserver.adoc 
:product-path: api/extension-apiserver.adoc

Rancher extiende Kubernetes con APIs adicionales registrando un servidor de API de extensión utilizando la https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/[capa de agregación de API de Kubernetes].

[#_aggregation_layer_is_required]
== Se requiere la capa de agregación.

La capa de agregación de API debe configurarse en el clúster local de Kubernetes para que el `v1.ext.cattle.io` `APIService` funcione correctamente. Si el `APIService` no recibe una solicitud de registro después de que el servidor de Rancher se inicie, el pod se bloquea con una entrada de registro que indica el error. Si sus pods están fallando constantemente en detectar el registro a pesar de tener un clúster configurado correctamente, puede aumentar el tiempo de espera configurando el `.Values.aggregationRegistrationTimeout` en Helm.

En esta versión de Rancher, las versiones de Kubernetes soportadas por RKE2/K3s tienen la capa de agregación configurada y habilitada por defecto. Sin embargo, si sospecha que la configuración de su clúster es incorrecta, consulte la https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/[documentación de la Capa de Agregación de Kubernetes] para obtener información sobre cómo configurar la capa de agregación.

[NOTE]
====
Si la distribución subyacente de Kubernetes no soporta la capa de agregación, debe migrar a una distribución de Kubernetes que sí la soporte antes de actualizar.
====
