= Nutzer-ID-Tracking in Audit-Logs
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-27
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc 
:product-path: troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs.adoc
ifeval::["{build-type}" != "community"]
:xref-enable-api-audit-log: xref:observability/logging/enable-api-audit-log.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-enable-api-audit-log: xref:how-to-guides/advanced-user-guides/enable-api-audit-log.adoc
endif::[]

Die folgenden Audit-Protokolle werden in Rancher verwendet, um Ereignisse zu verfolgen, die in den lokalen und Downstream-Clustern auftreten:

* https://rancher.com/docs/rke/latest/en/config-options/audit-log/[Kubernetes Audit Logs]
* {xref-enable-api-audit-log}[Rancher-API-Audit-Protokolle]

Die Audit-Protokolle in Rancher v2.6 wurden verbessert, um den Namen des externen Identitätsanbieters (allgemeiner Name des Benutzers im externen Authentifizierungsanbieter) sowohl in den Rancher- als auch in den Downstream-Kubernetes-Audit-Protokollen einzuschließen.

Vor v2.6 konnte ein Rancher-Administrator ein Ereignis in den Rancher-Audit-Protokollen nicht zurückverfolgen und in die Kubernetes-Audit-Protokolle gelangen, ohne die Zuordnung des Benutzernamens des externen Identitätsanbieters zum Benutzer-ID (`u-xXXX`) zu kennen, die in Rancher verwendet wird.
Um diese Zuordnung zu kennen, benötigten die Cluster-Administratoren Zugriff auf die Rancher-API, die Benutzeroberfläche und den lokalen Verwaltungscluster.

Jetzt sollte ein Downstream-Cluster-Administrator in der Lage sein, die Kubernetes-Audit-Protokolle einzusehen und zu wissen, welcher spezifische Benutzer des externen Identitätsanbieters (IDP) eine Aktion durchgeführt hat, ohne etwas in Rancher einsehen zu müssen.
Wenn die Audit-Protokolle vom Cluster übertragen werden, sollte ein Benutzer des Protokollierungssystems in der Lage sein, den Benutzer im System des externen Identitätsanbieters zu identifizieren.
Ein Rancher-Administrator sollte jetzt in der Lage sein, die Rancher-Audit-Protokolle einzusehen und über den Benutzernamen des externen Identitätsanbieters zu den Kubernetes-Audit-Protokollen zu gelangen.

[#_feature_description]
== Beschreibung

* Wenn die Kubernetes-Audit-Protokolle im Downstream-Cluster aktiviert sind, wird bei jedem protokollierten Ereignis der Benutzername des externen Identitätsanbieters jetzt für jede Anfrage auf der "Metadaten"-Ebene protokolliert.
* Wenn Sie die Rancher-API-Audit-Protokolle für eine Rancher-Installation aktivieren, wird der Benutzername des externen Identitätsanbieters jetzt auch auf der `auditLog.level=0` für jede Anfrage, die den Rancher-API-Server erreicht, einschließlich Anmeldeanfragen, protokolliert.
