= About rancher-selinux
:description: Install the rancher-selinux RPM to enable SELinux support for Rancher components on SUSE and RHEL-based systems, then set global.seLinux.enabled in supported charts
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-10-05
:page-revdate: {revdate}
:page-community-path: reference-guides/rancher-security/selinux-rpm/about-rancher-selinux.adoc 
:page-product-path: security/selinux-rpm/about-rancher-selinux.adoc

To allow Rancher to work with SELinux, some functionality has to be manually enabled for the SELinux nodes. To help with that, Rancher provides an SELinux RPM.

[TIP]
.Why SELinux?
====
By assigning a dedicated SELinux type to each container, we ensure that containers are limited to their minimal needs and cannot pivot to other resources if compromised.
====

The `rancher-selinux` RPM contains a set of SELinux policies designed to grant the necessary privileges to various Rancher components running on Linux systems with SELinux enabled.

The source code, policy files and development guide are available in the https://github.com/rancher/rancher-selinux[rancher-selinux GitHub repository].

[#_supported_operating_systems]
== Supported Operating Systems

[cols="3,1,1",options="header"]
|===
| Operating System | Version | Repo path
| openSUSE Leap / SLE / SLE Micro | 16 / 6 | `sle/16`
| openSUSE MicroOS / Tumbleweed | Rolling | `microos`
| RHEL / CentOS / Rocky Linux | 9 | `centos/9`
| RHEL / CentOS / Rocky Linux | 10 | `centos/10`
|===

All policies are covered by end-to-end tests. For the most up-to-date matrix, see the https://github.com/rancher/rancher-selinux#support-matrix[rancher-selinux support matrix].

[#_installing_the_rancher_selinux_rpm]
== Installing the rancher-selinux RPM

Install `rancher-selinux` on *all SELinux-enabled nodes* in the cluster. Replace `<repo-path>` with the value from the table above.

[#_opensuse_leap_sle_sle_micro_microos]
=== openSUSE Leap / SLE / SLE Micro / MicroOS

[,bash]
----
cat << EOF > /etc/zypp/repos.d/rancher.repo
[rancher]
name=Rancher
baseurl=https://rpm.rancher.io/rancher/production/<repo-path>/noarch
enabled=1
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF

zypper --gpg-auto-import-keys refresh
zypper install -y rancher-selinux
----

[#_rhel_centos_rocky_linux_fedora]
=== RHEL / CentOS / Rocky Linux / Fedora

[,bash]
----
cat << EOF > /etc/yum.repos.d/rancher.repo
[rancher]
name=Rancher
baseurl=https://rpm.rancher.io/rancher/production/<repo-path>/noarch
enabled=1
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF

dnf install -y rancher-selinux
----

[NOTE]
.Transactional systems
====
On SLE Micro and openSUSE MicroOS, install the package with `transactional-update pkg install rancher-selinux` and reboot the node.
====

[#_verifying_the_installation]
=== Verifying the installation

[,bash]
----
semodule -l | grep rancher
----

[#_configuring_applications_to_work_with_selinux]
== Configuring Applications to Work with SELinux

Applications do not automatically work once the `rancher-selinux` RPM is installed on the host. They need to be configured to run in an allowed SELinux container domain provided by the RPM.

To configure the supported charts to be SELinux aware, set `global.seLinux.enabled` to `true` in the `values.yaml` when installing the chart.

[cols="1,1,1",options="header"]
|===
| Chart | Container | SELinux type
| Rancher Monitoring | node-exporter | `prom_node_exporter_t`
| Rancher Monitoring | pushprox | `rke_kubereader_t`
| Rancher Logging | fluentbit | `rke_logreader_t`
| Rancher AI | rancher-ai-agent | `rancher_aiagent_container_t`
| Rancher AI | rancher-ai-mcp | `rancher_aimcp_container_t`
|===

[NOTE]
====
Only the components listed above get a dedicated SELinux type. Other Rancher components and workloads use the default `container_t` type provided by `container-selinux`.
====
