= Administration de projet
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/manage-projects/index.adoc 
:product-path: cluster-admin/project-admin/project-admin.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/roles-de-cluster-et-de-projet.adoc
:xref-global-permissions: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc
:xref-project-resource-quotas: xref:cluster-admin/project-admin/project-resource-quotas/project-resource-quotas.adoc
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-namespaces: xref:cluster-admin/namespaces.adoc
:xref-add-users-to-projects: xref:cluster-admin/project-admin/add-users-to-projects.adoc
:xref-rancher-project-tools: xref:observability/rancher-project-tools.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/roles-de-cluster-et-de-projet.adoc
:xref-global-permissions: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc 
:xref-project-resource-quotas: xref:how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/index.adoc
:xref-custom-roles: xref:how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/gérer-le-contrôle-d'accès-en-fonction-du-rôle-rbac/rôles-personnalisés.adoc
:xref-namespaces: xref:how-to-guides/new-user-guides/manage-namespaces.adoc
:xref-add-users-to-projects: xref:how-to-guides/new-user-guides/add-users-to-projects.adoc
:xref-rancher-project-tools: xref:reference-guides/rancher-project-tools.adoc
endif::[]

_Les projets_ sont des objets introduits dans Rancher qui aident à organiser les espaces de noms dans votre cluster Kubernetes. Vous pouvez utiliser des projets pour créer des clusters multi-locataires, ce qui permet à un groupe d'utilisateurs de partager les mêmes ressources sous-jacentes sans interagir avec les applications des autres.

En termes de hiérarchie{nbsp}:

* Les clusters contiennent des projets
* Les projets contiennent des espaces de noms

Dans Rancher, les projets vous permettent de gérer plusieurs espaces de noms comme une seule entité. Dans Kubernetes natif, qui n'inclut pas de projets, des fonctionnalités comme les droits d'accès basés sur les rôles ou les ressources du cluster sont attribuées à des espaces de noms individuels. Dans les clusters où plusieurs espaces de noms nécessitent le même ensemble de droits d'accès, attribuer ces droits à chaque espace de noms individuel peut devenir fastidieux. Même si tous les espaces de noms nécessitent les mêmes droits, il n'y a aucun moyen d'appliquer ces droits à tous vos espaces de noms en une seule action. Il faudrait attribuer ces droits de manière répétée à chaque espace de noms{nbsp}!

Les projets Rancher résolvent ce problème en vous permettant d'appliquer des ressources et des droits d'accès au niveau du projet. Chaque espace de noms dans le projet hérite alors de ces ressources et politiques, vous n'avez donc qu'à les attribuer une fois au projet, plutôt que de les attribuer à chaque espace de noms individuel.

Vous pouvez utiliser des projets pour effectuer des actions telles que{nbsp}:

* {xref-add-users-to-projects}[][Attribuer aux utilisateurs l'accès à un groupe d'espaces de noms]
* Attribuer aux utilisateurs {xref-cluster-project-roles}#_project_roles[rôles spécifiques dans un projet]. Un rôle peut être propriétaire, membre, en lecture seule, ou {xref-custom-roles}[personnalisé].
* {xref-project-resource-quotas}[Set resource quotas]
* {xref-namespaces}[Gérer les espaces de noms]
* {xref-rancher-project-tools}[Configurer des outils]

[#_authorization]
== autorisation

Les utilisateurs non administratifs ne sont autorisés à accéder au projet qu'après qu'un {xref-global-permissions}[administrateur], {xref-cluster-project-roles}#_cluster_roles[propriétaire ou membre du cluster], ou {xref-cluster-project-roles}#_project_roles[propriétaire du projet] les ajoute à l'onglet *Membres* du projet.

Quiconque crée le projet devient automatiquement un {xref-cluster-project-roles}#_project_roles[propriétaire du projet].

[#_switching_between_projects]
== Changer de projet

Pour changer de projet, utilisez le menu déroulant disponible dans la barre de navigation. Alternativement, vous pouvez changer de projet directement dans la barre de navigation.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, allez au cluster où vous souhaitez changer de projet et cliquez sur *Explorer*.
. Dans la barre de navigation supérieure, sélectionnez le projet que vous souhaitez ouvrir.
