= Flujos y Flujos de Clúster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/custom-resource-configuration/flows-and-clusterflows.adoc 
:product-path: observability/logging/custom-resource-configuration/flows-and-clusterflows.adoc
ifeval::["{build-type}" != "community"]
:xref-logging: xref:observabilidad/logging/logging.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
endif::[]

Consulta la https://kube-logging.github.io/docs/configuration/flow/[documentación del operador de logging] para obtener todos los detalles sobre cómo configurar `Flows` y `ClusterFlows`.

Consulta {xref-logging}#_El_Búfer_de_Logging_Sobrepasa_los_Pods[Rancher Integración con Servicios de Logging: Resolución de Problemas] para saber cómo resolver problemas de memoria con el búfer de logging.

[#_flows]
== Flujos

Un `Flow` define qué logs recoger y filtrar y a qué salida enviar los logs.

El `Flow` es un recurso con espacio de nombres, lo que significa que los logs solo se recogerán del espacio de nombres en el que se despliega el `Flow`.

`Flows` se puede configurar completando formularios en la interfaz de usuario de Rancher.

Para más detalles sobre el recurso personalizado `Flow`, consulta https://kube-logging.github.io/docs/configuration/crds/v1beta1/flow_types/[FlowSpec.]

[#_matches]
=== Coincide

Las declaraciones de coincidencia se utilizan para seleccionar de qué contenedores extraer logs.

Puedes especificar declaraciones de coincidencia para seleccionar o excluir logs según las etiquetas de Kubernetes, los nombres de contenedores y de nombre de host. Las declaraciones de coincidencia se evalúan en el orden en que se definen y se procesan solo hasta que se aplica la primera regla de selección o exclusión coincidente.

Las coincidencias se pueden configurar completando los formularios `Flow` o `ClusterFlow` en la interfaz de usuario de Rancher.

Para ejemplos detallados sobre el uso de la declaración de coincidencia, consulta la https://kube-logging.github.io/docs/configuration/log-routing/[documentación oficial sobre el enrutamiento de logs.]

[#_filters]
=== Filtros

Puedes definir uno o más filtros dentro de un `Flow`. Los filtros pueden realizar diversas acciones sobre los logs, como añadir datos, transformar los logs o analizar valores de los registros. Los filtros en el `Flow` se aplican en el mismo orden en que aparecen en la definición.

Para una lista de filtros soportados por el operador de Logging, consulta https://kube-logging.github.io/docs/configuration/plugins/filters/[la documentación oficial sobre filtros de Fluentd].

Los filtros deben configurarse en YAML.

[#_outputs]
=== Salidas

Este `Output` recibirá logs del `Flow`. Debido a que el `Flow` es un recurso con espacio de nombres, el `Output` debe residir en el mismo espacio de nombres que el `Flow`.

`Outputs` puede ser referenciado al completar los formularios `Flow` o `ClusterFlow` en la interfaz de usuario de Rancher.

[#_clusterflows]
== ClusterFlows

Las coincidencias, filtros y `Outputs` se configuran para `ClusterFlows` de la misma manera que se configuran para `Flows`. La diferencia clave es que el `ClusterFlow` está limitado al nivel del clúster y puede configurar la recolección de logs en todos los espacios de nombres.

`ClusterFlows` se puede configurar completando formularios en la interfaz de usuario de Rancher.

Después de que `ClusterFlow` seleccione logs de todos los espacios de nombres en el clúster, los logs del clúster serán recolectados y registrados en el `ClusterOutput` seleccionado.

[#_yaml_example]
== Ejemplo de YAML

El siguiente ejemplo `Flow` transforma los mensajes de registro del espacio de nombres predeterminado y los envía a un S3 `Output`:

[,yaml]
----
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  filters:
    - parser:
        remove_key_name_field: true
        parse:
          type: nginx
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
  localOutputRefs:
    - s3-output
  match:
    - select:
        labels:
          app: nginx
----
