= Actualización y reversión de Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes.adoc 
:product-path: cluster-admin/backups-and-restore/backups-and-restore.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-ds-backup: xref:cluster-admin/backups-and-restore/backups.adoc
:xref-nodes-machinepools: xref:cluster-admin/manage-clusters/nodes-and-machine-pools.adoc
:xref-ds-restore: xref:cluster-admin/backups-and-restore/restore.adoc
:xref-backup-disaster-recovery: xref:rancher-admin/back-up-restore-and-disaster-recovery/back-up-restore-and-disaster-recovery.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-register-clusters: xref:guías-de-instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/registrar-clusters-existentes.adoc
:xref-ds-backup: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher-launched-kubernetes-clusters.adoc
:xref-nodes-machinepools: xref:how-to-guides/new-user-guides/manage-clusters/nodes-and-machine-pools.adoc
:xref-ds-restore: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher-launched-kubernetes-clusters-from-backup.adoc
:xref-backup-disaster-recovery: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/index.adoc
endif::[]

Tras una actualización a la última versión de Rancher, los clústeres de Kubernetes en sentido descendente pueden actualizarse para utilizar la última versión compatible de Kubernetes.

Rancher llama a RKE (Rancher Kubernetes Engine) como una librería al aprovisionar y editar clústeres RKE. Para más información sobre cómo configurar la estrategia de actualización para clústeres RKE, consulta la https://rancher.com/docs/rke/latest/en/[documentación de RKE].

[#_tested_kubernetes_versions]
== Versiones de Kubernetes probadas

Antes de que se publique una nueva versión de Rancher, se prueba con las últimas versiones menores de Kubernetes para garantizar la compatibilidad. Para detalles sobre qué versiones de Kubernetes se probaron en cada versión de Rancher, consulta los https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.6.0/[términos de mantenimiento de soporte.]

[#_how_upgrades_work]
== Cómo funcionan las actualizaciones

RKE v1.1.0 cambió la forma en que se actualizan los clústeres.

En esta sección de la https://rancher.com/docs/rke/latest/en/upgrades/how-upgrades-work[documentación de RKE,] aprenderás qué sucede cuando editas o actualizas tu clúster de Kubernetes RKE.

[#_recommended_best_practice_for_upgrades]
== Mejor práctica recomendada para actualizaciones

Al actualizar la versión de Kubernetes de un clúster, te recomendamos que:

. Toma una instantánea.
. Inicia una actualización de Kubernetes.
. Si la actualización falla, revierte el clúster a la versión de Kubernetes anterior a la actualización. Esto se logra seleccionando la opción *Restaurar la versión de etcd y Kubernetes*. Esto devolverá tu clúster a la versión de Kubernetes anterior a la actualización antes de restaurar la instantánea de etcd.

La operación de restauración funcionará en un clúster que no esté en un estado saludable o activo.

[#_upgrading_the_kubernetes_version]
== Actualizando la versión de Kubernetes

[NOTE]
.Requisitos previos:
====

* Las opciones a continuación están disponibles para {xref-launch-k8s-with-rancher}[clústeres de Kubernetes lanzados por Rancher] y {xref-register-clusters}#_additional_features_for_registered_rke2_and_k3s_clusters[clústeres de Kubernetes K3s registrados].
* Las siguientes opciones también se aplican a los clústeres RKE2 importados que has registrado. Si importas un clúster de una plataforma de nube externa pero no lo registras, no podrás actualizar la versión de Kubernetes desde Rancher.
* Antes de actualizar Kubernetes, {xref-backup-disaster-recovery}[haz una copia de seguridad de tu clúster.]
====


. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, ve al clúster que deseas actualizar y haz clic en *⋮ > Editar Configuración*.
. En el menú desplegable *Versión de Kubernetes*, elige la versión de Kubernetes que deseas usar para el clúster.
. Haz clic en *Guardar*.

*Resultado:* Kubernetes comienza a actualizarse para el clúster.

[#_rolling_back]
== Reversión

Un clúster puede ser restaurado a una copia de seguridad en la que se utilizó la versión anterior de Kubernetes. Para obtener más información, consulta las siguientes secciones:

* {xref-ds-backup}#_how_snapshots_work[Haciendo una copia de seguridad de un clúster]
* {xref-ds-restore}#_restoring_a_cluster_from_a_snapshot[Restaurando un clúster desde una copia de seguridad]

[#_configuring_the_upgrade_strategy]
== Configurando la estrategia de actualización

A partir de RKE v1.1.0, se han hecho disponibles opciones de actualización adicionales para ofrecer un control más granular sobre el proceso de actualización. Estas opciones pueden utilizarse para mantener la disponibilidad de tus aplicaciones durante una actualización de clúster si se cumplen ciertas https://rancher.com/docs/rke/latest/en/upgrades/maintaining-availability[condiciones y requisitos].

La estrategia de actualización se puede configurar en la interfaz de usuario de Rancher, o editando el `cluster.yml`. Opciones más avanzadas están disponibles editando el `cluster.yml`.

[#_configuring_the_maximum_unavailable_worker_nodes_in_the_rancher_ui]
=== Configurando el Máximo de Nodos de Trabajo No Disponibles en la Interfaz de Usuario de Rancher

Desde la interfaz de usuario de Rancher, se puede configurar el número máximo de nodos de trabajo no disponibles. Durante una actualización de clúster, los nodos de trabajo se actualizarán en lotes de este tamaño.

Por defecto, el número máximo de nodos de trabajo no disponibles se define como el 10 por ciento de todos los nodos de trabajo. Este número se puede configurar como un porcentaje o como un entero. Cuando se define como un porcentaje, el tamaño del lote se redondea hacia abajo al nodo más cercano, con un mínimo de un nodo.

Para cambiar el número o porcentaje predeterminado de nodos de trabajo,

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, ve al clúster que deseas actualizar y haz clic en *⋮ > Editar Configuración*.
. En la pestaña *Estrategia de Actualización*, introduce el *Concurrencia de Trabajadores* como un número fijo o porcentaje. Para obtener este número, puedes tomar el número de nodos en tu clúster y restar los nodos no disponibles máximos.
. Haz clic en *Guardar*.

*Resultado:* El clúster se actualiza para utilizar la nueva estrategia de actualización.

[#_enabling_draining_nodes_during_upgrades_from_the_rancher_ui]
=== Habilitando el Drenaje de Nodos Durante las Actualizaciones desde la Interfaz de Usuario de Rancher

Por defecto, RKE https://kubernetes.io/docs/concepts/architecture/nodes/#manual-node-administration[cordona] cada nodo antes de actualizarlo. https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/[Drenar] está deshabilitado durante las actualizaciones por defecto. Si el drenaje está habilitado en la configuración del clúster, RKE tanto cordona como drena el nodo antes de que sea actualizado.

Para habilitar el drenaje de cada nodo durante una actualización de clúster,

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, ve al clúster al que deseas habilitar el drenaje de nodos y haz clic en *⋮ > Editar Configuración*.
. Haz clic en *⋮ > Editar*.
. En la pestaña *Estrategia de Actualización*, ve al campo *Drenar nodos* y haz clic en *Sí*. El drenaje de nodos se configura por separado para los nodos del plano de control y los nodos de trabajo.
. Configura las opciones sobre cómo se eliminan los pods. Para más información sobre cada opción, consulta {xref-nodes-machinepools}#_aggressive_and_safe_draining_options[esta sección.]
. Opcionalmente, configura un período de gracia. El período de gracia es el tiempo de espera dado a cada pod para limpiar las cosas, de modo que tengan la oportunidad de salir de forma ordenada. Los pods pueden necesitar terminar cualquier solicitud pendiente, revertir transacciones o guardar el estado en algún almacenamiento externo. Si este valor es negativo, se utilizará el valor predeterminado especificado en el pod.
. Opcionalmente, configura un tiempo de espera, que es la cantidad de tiempo que el drenaje debe continuar esperando antes de rendirse.
. Haz clic en *Guardar*.

*Resultado:* El clúster se actualiza para utilizar la nueva estrategia de actualización.

[NOTE]
====
* Hay un https://github.com/rancher/rancher/issues/25478[problema conocido] en el que la interfaz de usuario de Rancher no muestra el estado de etcd y del plano de control como drenados, aunque están siendo drenados.
* Durante una actualización, los nodos pueden ser drenados incluso cuando no hay cambios en YAML visibles para el usuario. Esto puede ocurrir si se actualizan archivos de configuración no dinámicos o si se introduce una nueva `system-agent-installer` imagen. En tales casos, Rancher genera un nuevo plan de actualización, resultando en un nuevo hash de plan. Cuando `Upgrade Strategy` se establece en `Drain nodes`, este cambio de plan puede activar el drenaje de nodos.
====


[#_maintaining_availability_for_applications_during_upgrades]
=== Mantener la disponibilidad de las aplicaciones durante las actualizaciones

En https://rancher.com/docs/rke/latest/en/upgrades/maintaining-availability/[esta sección de la documentación de RKE,] aprenderás los requisitos para prevenir el tiempo de inactividad de tus aplicaciones al actualizar el clúster.

[#_configuring_the_upgrade_strategy_in_the_cluster_yml]
=== Configurando la Estrategia de Actualización en el cluster.yml

Opciones más avanzadas de configuración de la estrategia de actualización están disponibles editando el `cluster.yml`.

Para más detalles, consulta https://rancher.com/docs/rke/latest/en/upgrades/configuring-strategy[Configurando la Estrategia de Actualización] en la documentación de RKE. La sección también incluye un ejemplo `cluster.yml` para configurar la estrategia de actualización.

[#_troubleshooting]
== Solución de problemas

Si un nodo no se inicia después de una actualización, el comando `rke up` genera un error.

No se procederá con la actualización si el número de nodos no disponibles supera el máximo configurado.

Si una actualización se detiene, puede que necesites arreglar un nodo no disponible o eliminarlo del clúster antes de que la actualización pueda continuar.

Un nodo fallido podría estar en muchos estados diferentes:

* Apagado
* No disponible
* El usuario drena un nodo mientras la actualización está en proceso, por lo que no hay kubelets en el nodo
* La actualización en sí ha fallado

Si se alcanza el número máximo de nodos no disponibles durante una actualización, los clústeres de usuarios de Rancher quedarán atascados en estado de actualización y no avanzarán con la actualización de ningún otro nodo del plano de control. Continuará evaluando el conjunto de nodos no disponibles en caso de que uno de los nodos se vuelva disponible. Si no se puede arreglar el nodo, debes eliminarlo para poder actualizar la versión.
