= ConfigMaps
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc 
:product-path: cluster-admin/kubernetes-resources/configmaps.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
endif::[]

Enquanto a maioria dos tipos de segredos do Kubernetes armazena informações sensíveis, https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/[ConfigMaps] armazenam informações de configuração geral, como um grupo de arquivos de configuração. Como os ConfigMaps não armazenam informações sensíveis, eles podem ser atualizados automaticamente e, portanto, não exigem que seus contêineres sejam reiniciados após a atualização (ao contrário da maioria dos tipos de segredos, que requerem atualizações manuais e a reinicialização do contêiner para entrar em vigor).

Os ConfigMaps aceitam pares de chave-valor em formatos de string comuns, como arquivos de configuração ou blobs JSON. Depois de fazer o upload de um mapa de configuração, qualquer carga de trabalho pode referenciá-lo como uma variável de ambiente ou um ponto de montagem de volume.

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Vá para o cluster que possui a carga de trabalho que deve referenciar um ConfigMap e clique em *Explorar*.
. Na barra de navegação à esquerda, clique em menu:Mais Recursos[Kernel> ConfigMaps].
. Clique em *Criar*.
. Digite um *Nome* para o ConfigMap.
+

[NOTE]
====
O Kubernetes classifica os ConfigMaps como https://kubernetes.io/docs/concepts/configuration/secret/[segredos], e não podem existir dois segredos com nomes duplicados em um projeto ou namespace. Portanto, para evitar conflitos, seus ConfigMaps devem ter um nome único entre os outros certificados, registros e segredos dentro do seu espaço de trabalho.
====


. Selecione o *Namespace* ao qual você deseja adicionar o ConfigMap.
. Na aba *Dados*, adicione um par de chave-valor ao seu ConfigMap. Adicione quantos valores precisar.  Você pode adicionar múltiplos pares de chave-valor ao ConfigMap copiando e colando. Alternativamente, use *Ler de Arquivo* para adicionar os dados. Nota: Se você precisar armazenar dados sensíveis, {xref-secrets}[use um segredo], não um ConfigMap.
. Clique em *Criar*.

*Resultado:* Seu ConfigMap foi adicionado ao namespace. Você pode visualizá-lo na interface do Rancher a partir da visualização menu:Recursos[ConfigMaps].

[#_whats_next]
== O Que Mais?

Agora que você tem um ConfigMap adicionado a um namespace, você pode adicioná-lo a uma carga de trabalho que você implanta a partir do namespace de origem. Você pode usar o ConfigMap para especificar informações que seu aplicativo deve consumir, como:

* Variáveis de ambiente do aplicativo.
* Especificando parâmetros para um volume montado na carga de trabalho.

Para mais informações sobre como adicionar ConfigMaps a uma carga de trabalho, veja {xref-deploy-workloads}[Implantando cargas de trabalho].
