= UI Server-Side Pagination
:page-languages: [en, zh]
:revdate: 2024-09-27
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/enable-experimental-features/ui-server-side-pagination 
:product-path: rancher-admin/experimental-features/ui-server-side-pagination

[CAUTION]
====
UI server-side pagination is not intended for use in production at this time. This feature is considered highly experimental. SUSE customers should consult SUSE Support before activating this feature.
====

UI server-side pagination caching provides an optional SQLite-backed cache of Kubernetes objects to improve performance. This unlocks sorting, filtering and pagination features used by the UI to restrict the amount of resources it fetches and stores in browser memory. These features are primarily used to improve list performance for resources with high counts.

This feature creates file system based caches in the `rancher` pods of the upstream cluster, and in the `cattle-cluster-agent` pods of the downstream clusters. In most environments, disk usage and I/O should not be significant. However, you should monitor activity after you enable caching.

SQLite-backed caching persists copies of any cached Kubernetes objects to disk. See <<_encrypting_sqlite_backed_caches,Encrypting SQLite-backed Caching>> if this is a security concern.

== Enabling UI Server-Side Pagination

. In the upper left corner, click *☰ > Global Settings > Feature Flags*.
. Find *`ui-sql-cache`* and select *⋮ > Activate > Activate*.
. Wait for Rancher to restart. This also restarts agents on all downstream clusters.
. In the upper left corner, click *☰ > Global Settings > Performance*.
. Go to *Server-side Pagination* and check the *Enable Server-side Pagination* option.
. Click *Apply*.
. Reload the page with the browser button (or the equivalent keyboard combination, typically `CTRL + R` on Windows and Linux, and `⌘ + R` on macOS).

== Encrypting SQLite-backed Caches

UI server-side pagination persists copies of any cached Kubernetes objects to disk. If you're concerned about the safety of this data, you can encrypt all objects before they are persisted to disk, by setting the environment variable `CATTLE_ENCRYPT_CACHE_ALL` to `true` in `rancher` pods in the upstream cluster and `cattle-cluster-agent` pods in the downstream clusters.

Secrets and security Tokens are always encrypted regardless of the above setting.

== Known Limitations of UI Server-Side Pagination

This initial release improves the performance of Pods, Secrets, Nodes and ConfigMaps in the Cluster Explorer pages, and most resources in the Explorer's *More Resources* section.

Pages can't be automatically refreshed. You can manually refresh table contents by clicking the *Refresh* button.
