= Monitoramento e Painéis
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/index.adoc 
:product-path: observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:description: O Prometheus permite que você visualize métricas de seus diferentes objetos do Rancher e Kubernetes. Saiba sobre o escopo do monitoramento e como habilitar o monitoramento do cluster
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
:xref-configure-alertmanager: xref:observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:observability/monitoring-and-dashboards/configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:observability/monitoring-and-dashboards/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheusrules.adoc
:xref-prometheus: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
:xref-enable-monitoring: xref:observability/monitoring-and-dashboards/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/create-persistent-grafana-dashboard.adoc
:xref-servicemonitors-and-podmonitors: xref:observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:observability/monitoring-and-dashboards/configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:observability/monitoring-and-dashboards/configuration/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:observability/monitoring-and-dashboards/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:observability/monitoring-and-dashboards/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:observability/monitoring-and-dashboards/windows-support.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
:xref-configure-alertmanager: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:reference-guides/monitoring-v2-configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheusrules.adoc
:xref-prometheus: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc
:xref-enable-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard.adoc
:xref-servicemonitors-and-podmonitors: xref:reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:reference-guides/monitoring-v2-configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:integrations-in-rancher/monitoring-and-alerting/windows-support.adoc
endif::[]

O aplicativo `rancher-monitoring` pode implantar rapidamente as principais soluções de monitoramento e alerta de código aberto em seu cluster.

Introduzido no Rancher v2.5, o aplicativo é alimentado por https://prometheus.io/[Prometheus], https://grafana.com/grafana/[Grafana], https://prometheus.io/docs/alerting/latest/alertmanager/[Alertmanager], o https://github.com/prometheus-operator/prometheus-operator[Prometheus Operator] e o https://github.com/DirectXMan12/k8s-prometheus-adapter[adaptador do Prometheus.]

Para informações sobre monitoramento e alerta V1, disponíveis no Rancher v2.2 até v2.4, consulte a documentação do Rancher v2.0--v2.4 sobre xref:[monitoramento de cluster], xref:[alerta], xref:[notificadores] e outras xref:[ferramentas].

Usando o aplicativo `rancher-monitoring`, você pode implantar rapidamente soluções de monitoramento e alerta de código aberto líderes em seu cluster.

[#_features]
== Recursos

O Prometheus permite que você visualize métricas de seus objetos Rancher e Kubernetes. Usando timestamps, o Prometheus permite que você consulte e visualize essas métricas em gráficos e visuais fáceis de ler, seja através da interface do Rancher ou do Grafana, que é uma plataforma de visualização de análises implantada junto com o Prometheus.

Ao visualizar dados que o Prometheus coleta do seu plano de controle de cluster, nós e implantações, você pode se manter atualizado sobre tudo o que acontece em seu cluster. Você pode então usar essas análises para gerenciar melhor sua organização: parar emergências do sistema antes que comecem, desenvolver estratégias de manutenção ou restaurar servidores que falharam.

O aplicativo de monitoramento:

* Monitora o estado e os processos dos nós do seu cluster, componentes do Kubernetes e implantações de software.
* Define alertas com base em métricas coletadas via Prometheus.
* Cria dashboards personalizados no Grafana.
* Configura notificações baseadas em alertas via e-mail, Slack, PagerDuty, etc., usando o Alertmanager do Prometheus.
* Define expressões pré-computadas, frequentemente necessárias ou computacionalmente caras como novas séries temporais com base em métricas coletadas via Prometheus.
* Expõe métricas coletadas do Prometheus para a API de Métricas Personalizadas do Kubernetes através do Adaptador Prometheus para uso no HPA.

Veja {xref-how-monitoring-works}[Como o Monitoramento Funciona] para uma explicação de como os componentes de monitoramento funcionam juntos.

[#_default_components_and_deployments]
== Componentes e Implantações Padrão

[#_built_in_dashboards]
=== Painéis Integrados

Por padrão, o aplicativo de monitoramento implanta painéis do Grafana (curados pelo projeto https://github.com/prometheus-operator/kube-prometheus[kube-prometheus]) no cluster.

Ele também implanta uma interface do usuário do Alertmanager e uma interface do usuário do Prometheus. Para mais informações sobre essas ferramentas, veja {xref-monitoring-builtin-dashboards}[Painéis Integrados.]

[#_default_metrics_exporters]
=== Exportadores de Métricas Padrão

Por padrão, o Rancher Monitoring implanta exportadores (como https://github.com/prometheus/node_exporter[node-exporter] e https://github.com/kubernetes/kube-state-metrics[kube-state-metrics]).

Esses exportadores padrão coletam automaticamente métricas de CPU e memória de todos os componentes do seu cluster Kubernetes, incluindo suas cargas de trabalho.

[#_default_alerts]
=== Alertas Padrão

O aplicativo de monitoramento implanta alguns alertas por padrão. Para ver os alertas padrão, vá para a xref:./built-in-dashboards.adoc#_alertmanager_ui[interface do usuário do Alertmanager] e clique em *Expandir todos os grupos.*

[#_components_exposed_in_the_rancher_ui]
=== Componentes Expostos na Interface do Usuário do Rancher

Para uma lista de componentes de monitoramento expostos na interface do usuário do Rancher, juntamente com casos de uso comuns para editá-los, veja xref:./how-monitoring-works.adoc#_components_exposed_in_the_rancher_ui[esta seção.]

[#_role_based_access_control]
== Controle de acesso com base em função

Para mais informações sobre como configurar o acesso ao monitoramento, veja {xref-rancher-monitoring-rbac}[esta página.]

[NOTE]
====

As permissões de leitura do Rancher e do Projeto não se aplicam necessariamente aos recursos de monitoramento. Veja xref:./rbac-for-monitoring.adoc#_additional_monitoring_clusterroles[monitoring-ui-view] para mais detalhes.
====


[#_guides]
== Guias

* {xref-enable-monitoring}[Habilitar monitoramento]
* {xref-monitoring-uninstall}[Desinstalar monitoramento]
* {xref-rancher-workload-monitoring}[Monitorar cargas de trabalho]
* {xref-customize-grafana-dashboard}[Personalizar painéis do Grafana]
* {xref-create-persistent-grafana-dashboard}[Painéis persistentes do Grafana]
* {xref-monitoring-debug-high-memory}[Depurando alto uso de memória]

[#_configuration]
== Configuração

[#_configuring_monitoring_resources_in_rancher]
=== Configurando recursos de monitoramento no Rancher

A referência de configuração assume familiaridade com o funcionamento conjunto dos componentes de monitoramento. Para mais informações, veja {xref-how-monitoring-works}[Como o Monitoramento Funciona.]

* {xref-servicemonitors-and-podmonitors}[ServiceMonitor e PodMonitor]
* {xref-receivers}[Receptor]
* {xref-monitoring-routes}[Rota]
* {xref-prometheusrules}[PrometheusRule]
* {xref-prometheus}[Prometheus]
* {xref-configure-alertmanager}[Alertmanager]

[#_configuring_helm_chart_options]
=== Configurando opções do Helm Chart

Para mais informações sobre opções do `rancher-monitoring` chart, incluindo opções para definir limites e solicitações de recursos, veja {xref-monitoring-helm-chart-options}[Opções do Helm Chart].

[#_windows_cluster_support]
== Suporte a Cluster Windows

Para poder implantar completamente o Monitoramento V2 para Windows, todos os seus hosts Windows devem ter uma versão mínima https://github.com/rancher/wins[wins] de v0.1.0.

Para mais detalhes sobre como fazer upgrade do wins em hosts Windows existentes, veja {xref-monitoring-windows}[Suporte a cluster Windows para Monitoramento V2.].

[#_known_issues]
== Problemas conhecidos

Há um https://github.com/rancher/rancher/issues/28787#issuecomment-693611821[problema conhecido] que clusters K3s requerem mais do que a memória padrão alocada. Se você habilitar o monitoramento em um cluster K3s, defina `prometheus.prometheusSpec.resources.memory.limit` para 2500 Mi e `prometheus.prometheusSpec.resources.memory.request` para 1750 Mi.

Veja {xref-monitoring-debug-high-memory}[Depurando alto uso de memória] para conselhos e recomendações.
