= Configurando o Monitoramento para uma Workload
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc 
:product-path: observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
ifeval::["{build-type}" != "community"]
:xref-promql-expressions: xref:observability/monitoring-and-dashboards/promql-expressions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-promql-expressions: xref:integrations-in-rancher/monitoring-and-alerting/promql-expressions.adoc
endif::[]

Se você só precisa de séries temporais de CPU e memória para a workload, não é necessário implantar um ServiceMonitor ou PodMonitor, pois o aplicativo de monitoramento já coleta dados de métricas sobre o uso de recursos por padrão.

Os passos para configurar o monitoramento para workloads dependem de você querer métricas básicas, como CPU e memória, ou de coletar métricas personalizadas da workload.

Se você só precisa de séries temporais de CPU e memória para a workload, não é necessário implantar um ServiceMonitor ou PodMonitor, pois o aplicativo de monitoramento já coleta dados de métricas sobre o uso de recursos por padrão. Os dados de séries temporais de uso de recursos estão no banco de dados de séries temporais local do Prometheus.

O Grafana mostra os dados de forma agregada, mas você pode ver os dados da workload individual usando uma consulta PromQL que extrai os dados para aquela workload. Uma vez que você tenha a consulta PromQL, pode executar a consulta individualmente na interface do usuário do Prometheus e ver as séries temporais visualizadas lá, ou pode usar a consulta para personalizar um painel do Grafana para exibir as métricas da workload. Para exemplos de consultas PromQL para métricas de workload, veja {xref-promql-expressions}#_workload_metrics[esta seção].

Para configurar métricas personalizadas para sua workload, você precisará configurar um exportador e criar um novo recurso customizado ServiceMonitor para configurar o Prometheus para coletar métricas do seu exportador.

[#_display_cpu_and_memory_metrics_for_a_workload]
== Exibir Métricas de CPU e Memória para uma Workload

Por padrão, o aplicativo de monitoramento já coleta CPU e memória.

Para obter detalhes mais específicos sobre uma workload em particular, você pode personalizar um painel do Grafana para exibir as métricas de uma workload específica.

[#_setting_up_metrics_beyond_cpu_and_memory]
== Configurando Métricas Além de CPU e Memória

Para métricas personalizadas, você precisará expor as métricas no seu aplicativo em um formato suportado pelo Prometheus.

Então, recomendamos que você crie um novo recurso customizado ServiceMonitor. Quando este recurso for criado, o recurso customizado do Prometheus será atualizado automaticamente para que sua configuração de coleta inclua o novo endpoint de métricas personalizadas. Então, o Prometheus começará a coletar métricas do endpoint.

Você também pode criar um PodMonitor para expor o endpoint de métricas personalizadas, mas os ServiceMonitors são mais apropriados para a maioria dos casos de uso.
