= Suporte a Cluster do Windows para Monitoramento V2
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/windows-support.adoc 
:product-path: observability/monitoring-and-dashboards/windows-support.adoc

O Monitoramento V2 pode ser implantado em um cluster do Windows para coletar métricas de nós do Windows usando https://github.com/prometheus-community/windows_exporter[prometheus-community/windows_exporter] (anteriormente chamado de `wmi_exporter`).

[#_cluster_requirements]
== Requisitos do Cluster

O Monitoramento V2 para Windows só pode coletar métricas de hosts do Windows que tenham uma `wins` versão mínima de v0.1.0.  Para poder implantar totalmente o Monitoramento V2 para Windows, todos os seus hosts devem atender a esse requisito.

[#_upgrading_existing_clusters_to_wins_v0_1_0]
=== Fazendo upgrade dos clusters existentes para wins v0.1.0

Se o cluster foi provisionado antes do Rancher 2.5.8 (mesmo que a versão atual do Rancher seja 2.5.8), você não poderá implantar com sucesso o Monitoramento V2 para Windows até que você faça o upgrade da versão wins em cada host para pelo menos v0.1.0.

Para facilitar esse fazer upgrade, o Rancher 2.5.8 lançou um novo gráfico Helm chamado `rancher-wins-upgrader`.

. Implante `rancher-wins-upgrader` com a seguinte substituição:
+
[,yaml]
----
 # Masquerading bootstraps the wins-upgrader installation via
 # a previously whitelisted process path since the normal install path,
 # c:\etc\rancher\wins\wins-upgrade.exe is not normally whitelisted.
 # In this case, we are using the previously whitelisted process
 # path used by Monitoring V1.
 masquerade:
   enabled: true
   as: c:\\etc\wmi-exporter\wmi-exporter.exe
----

. Uma vez que todos os seus hosts tenham feito o upgrade com sucesso, por favor, certifique-se de implantar o gráfico Helm mais uma vez com os valores padrão para evitar conflitos com as seguintes configurações:
+
[,yaml]
----
 masquerade:
   enabled: false
----

*Resultado:* Os hosts estão prontos para a instalação do Monitoramento V2. Você pode optar por desinstalar o gráfico `rancher-wins-upgrader` ou mantê-lo em seu cluster para facilitar futuros upgrades.

Para mais informações sobre como ele pode ser utilizado, consulte o https://github.com/rancher/wins/blob/master/charts/rancher-wins-upgrader/README.md[README.md] do gráfico.
