= {k3s-product-name} クラスター設定リファレンス
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-10
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc 
:product-path: cluster-deployment/configuration/k3s.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-ds-backup-restore: xref:cluster-admin/backups-and-restore/backups-and-restore.adoc
:xref-psact: xref:security/psact.adoc
:xref-azure-machine-configuration: xref:cluster-deployment/infra-providers/azure/machine-configuration.adoc
:xref-digitalocean-machine-configuration: xref:cluster-deployment/infra-providers/digitalocean/machine-configuration.adoc
:xref-aws-machine-configuration: xref:cluster-deployment/infra-providers/aws/machine-configuration.adoc
:xref-gce-machine-configuration: xref:cluster-deployment/infra-providers/gce/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/rancher管理クラスターのノード要件.adoc
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-ds-backup-restore: xref:getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes.adoc
:xref-psact: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates.adoc
:xref-azure-machine-configuration: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/azure.adoc
:xref-digitalocean-machine-configuration: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/digitalocean.adoc
:xref-aws-machine-configuration: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/amazon-ec2.adoc
:xref-gce-machine-configuration: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/google-gce.adoc
endif::[]

このセクションでは、Rancherで新しいまたは既存のK3s Kubernetesクラスターに利用可能な設定オプションについて説明します。

[#_overview]
== 概要

Kubernetesオプションは、2つの方法のいずれかで設定できます：

* <<_configuration_options_in_the_rancher_ui,Rancher UI>>：Rancher UIを使用して、Kubernetesクラスターを設定する際に一般的にカスタマイズされるオプションを選択します。
* <<_cluster_config_file_reference,クラスター設定ファイル>>：Rancher UIを使用してクラスターのKubernetesオプションを選択する代わりに、上級ユーザーはK3s設定ファイルを作成できます。設定ファイルを使用すると、K3sインストール中に利用可能な https://rancher.com/docs/k3s/latest/en/installation/install-options/[オプション]のいずれかを設定できます。

[#_editing_clusters_in_the_rancher_ui]
== Rancher UIでのクラスターの編集

Rancher UIでは、クラスターを編集するための2つの方法を提供しています：

. フォームを使用して。
. YAMLを使用して。

[#_editing_clusters_with_a_form]
=== フォームを使用したクラスターの編集

このフォームでは、クラスターに最も頻繁に必要なオプションをカバーしています。

クラスターを編集するには、

. *☰ > クラスター管理*をクリックします。
. 構成したいクラスターに移動し、*⋮ > 設定を編集*をクリックします。

[#_editing_clusters_in_yaml]
=== YAMLでのクラスターの編集

K3sクラスターのYAMLでの設定可能オプションの完全なリファレンスについては、 https://documentation.suse.com/cloudnative/k3s/latest/en/installation/configuration.html[K3sドキュメント]を参照してください。

YAMLでクラスターを編集するには：

. *☰ > クラスター管理*をクリックします。
. 構成したいクラスターに移動し、*⋮ > YAMLとして編集*をクリックします。
. `rkeConfig`ディレクティブの下にRKEオプションを編集します。

[#_configuration_options_in_the_rancher_ui]
== Rancher UIの設定オプション

[#_machine_pool_configuration]
=== マシンプールの設定

このサブセクションでは、一般的なマシンプールの設定について説明します。特定のインフラストラクチャプロバイダーの設定については、以下を参照してください：

* {xref-azure-machine-configuration}[Azure]
* {xref-digitalocean-machine-configuration}[DigitalOcean]
* {xref-aws-machine-configuration}[Amazon EC2]
* {xref-gce-machine-configuration}[Google GCE]

[discrete]
[#_pool_name]
===== プール名

マシンプールの名前です。

[discrete]
[#_machine_count]
===== マシン数

プール内のマシンの数です。

[discrete]
[#_roles]
===== 役割

ノードにetcd、コントロールプレーン、ワーカーの役割を割り当てるオプション。

[#_advanced]
==== 詳細

[#_auto_replace]
===== 自動置換

ノードが連絡不能状態になってから自動的に削除・置き換えられるまでの時間。

[#_drain_before_delete]
===== 削除前の排出

ノードが削除される前に、すべてのポッドを退避させてドレインする機能を有効にします。

[#_kubernetes_node_labels]
===== Kubernetesノードラベル

ノードに https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[ラベル]を追加して、整理やオブジェクト選択を助けます。

ラベルの構文要件の詳細については、 https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set[Kubernetesのドキュメント]を参照してください。

[#_taints]
===== Taints

ノードに https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[テイント]を追加すると、ポッドが一致するトレランスを持たない限り、ノードにスケジュールされたり実行されたりするのを防ぎます。

[#_cluster_configuration]
=== クラスタ設定

[#_basics]
==== 基本

[#_kubernetes_version]
===== Kubernetesバージョン

クラスターのノードにインストールされているKubernetesのバージョン。

Kubernetesのアップグレードまたはロールバックの詳細については、{xref-ds-backup-restore}[Kubernetesのアップグレード]を参照してください。

[#_pod_security_admission_configuration_template]
===== ポッドセキュリティアドミッション設定テンプレート

クラスターのデフォルトの{xref-psact}[ポッドセキュリティアドミッション設定テンプレート]。

[#_encrypt_secrets]
===== シークレットを暗号化する

シークレットの暗号化を有効または無効にするオプション。有効にすると、シークレットはAES-CBCキーを使用して暗号化されます。無効にすると、以前に暗号化されたシークレットは、再度暗号化が有効になるまで読み取れません。詳細については、 https://documentation.suse.com/cloudnative/k3s/latest/en/security/secrets-encryption.html[K3sのドキュメント]を参照してください。

[#_project_network_isolation]
===== プロジェクトネットワークの分離

ネットワークプロバイダーがプロジェクトネットワークの分離を許可している場合、プロジェクト間の通信を有効または無効にするかを選択できます。

[#_selinux]
===== SELinux

https://documentation.suse.com/cloudnative/k3s/latest/en/advanced.html#_selinux_support[SELinux]サポートを有効または無効にするオプション。

[#_coredns]
===== CoreDNS

デフォルトでは、 https://coredns.io/[CoreDNS]がデフォルトのDNSプロバイダーとしてインストールされます。CoreDNSがインストールされていない場合は、別のDNSプロバイダーを自分でインストールする必要があります。詳細については、 https://documentation.suse.com/cloudnative/k3s/latest/en/networking/networking-services.html#_coredns[K3sのドキュメント]を参照してください。

[#_klipper_service_lb]
===== KlipperサービスLB

https://github.com/rancher/klipper-lb[Klipper]サービスのロードバランサーを有効または無効にするオプション。詳細については、 https://documentation.suse.com/cloudnative/k3s/latest/en/networking/networking-services.html#_service_load_balancer[K3sのドキュメント]を参照してください。

[#_traefik_ingress]
===== Traefik Ingress

https://traefik.io/[Traefik] HTTPリバースプロキシおよびロードバランサーを有効または無効にするオプション。詳細および設定オプションについては、 https://documentation.suse.com/cloudnative/k3s/latest/en/networking/networking-services.html#_traefik_ingress_controller[K3sのドキュメント]を参照してください。

[#_local_storage]
===== ローカルストレージ

ノードでの https://documentation.suse.com/cloudnative/k3s/latest/en/storage.html[ローカルストレージ]を有効または無効にするオプション。

[#_metrics_server]
===== メトリクスサーバー

https://github.com/kubernetes-incubator/metrics-server[メトリクスサーバー]を有効または無効にするオプション。有効にした場合、ポート10250が受信TCPトラフィックのために開かれていることを確認してください。

[#_add_on_config]
==== アドオン設定

クラスタの起動時に適用する https://kubernetes.io/docs/concepts/cluster-administration/addons/[アドオン]として管理される追加のKubernetesマニフェスト。詳細については、 https://documentation.suse.com/cloudnative/k3s/latest/en/installation/packaged-components.html#_auto_deploying_manifests_addons[K3sのドキュメント]を参照してください。

[#_agent_environment_vars]
==== エージェント環境変数

https://documentation.suse.com/cloudnative/k3s/latest/en/architecture.html[K3sエージェント]のための環境変数を設定するオプション。環境変数はキーと値のペアを使用して設定できます。詳細については、 https://documentation.suse.com/cloudnative/k3s/latest/en/installation/configuration.html#_configuration_file[K3ドキュメント]を参照してください。

[#_etcd]
==== etcd

[#_automatic_snapshots]
===== 自動スナップショット

定期的なetcdスナップショットを有効または無効にするオプション。有効にした場合、ユーザーはスナップショットの頻度を設定するオプションがあります。詳細については、 https://documentation.suse.com/cloudnative/k3s/latest/en/cli/etcd-snapshot.html#_creating_snapshots[K3sドキュメント]を参照してください。

[#_metrics]
===== Metrics

etcdメトリクスを公開するか、クラスタ内のみにするかを選択するオプション。

[#_networking]
==== ネットワーキング

[#_cluster_cidr]
===== クラスターCIDR

ポッドIP用に使用するIPv4/IPv6ネットワークCIDR（デフォルト：`10.42.0.0/16`）。

値の例：

* IPv4のみ：`10.42.0.0/16`
* IPv6のみ：`2001:cafe:42::/56`
* デュアルスタック：`10.42.0.0/16,2001:cafe:42::/56`

デュアルスタックまたはIPv6専用ネットワークに関連する追加の要件と制限については、以下のリソースを参照してください：

* https://documentation.suse.com/cloudnative/k3s/latest/en/networking/basic-network-options.html#_dual_stack_ipv4_ipv6_networking[K3sドキュメント：デュアルスタック（IPv4 + IPv6）ネットワーキング]
* https://documentation.suse.com/cloudnative/k3s/latest/en/networking/basic-network-options.html#_single_stack_ipv6_networking[K3sドキュメント：シングルスタックIPv6ネットワーキング]

[CAUTION]
====
クラスターを最初に作成する際にサービスCIDRを設定する必要があります。クラスターが起動した後に既存のクラスターでサービスCIDRを有効にすることはできません。
====

[#_service_cidr]
===== サービスCIDR

サービスIP用に使用するIPv4/IPv6ネットワークCIDR（デフォルト：`10.43.0.0/16`）。

値の例：

* IPv4のみ：`10.43.0.0/16`
* IPv6のみ：`2001:cafe:43::/112`
* デュアルスタック：`10.43.0.0/16,2001:cafe:43::/112`

デュアルスタックまたはIPv6専用ネットワークに関連する追加の要件と制限については、以下のリソースを参照してください：

* https://documentation.suse.com/cloudnative/k3s/latest/en/networking/basic-network-options.html#_dual_stack_ipv4_ipv6_networking[K3sドキュメント：デュアルスタック（IPv4 + IPv6）ネットワーキング]
* https://documentation.suse.com/cloudnative/k3s/latest/en/networking/basic-network-options.html#_single_stack_ipv6_networking[K3sドキュメント：シングルスタックIPv6ネットワーキング]

[CAUTION]
====
クラスターを最初に作成する際にサービスCIDRを設定する必要があります。クラスターが起動した後に既存のクラスターでサービスCIDRを有効にすることはできません。
====

[#_cluster_dns]
===== クラスターDNS

corednsサービスのIPv4クラスターIP。サービスCIDR範囲内である必要があります（デフォルト：`10.43.0.10`）。

[#_cluster_domain]
===== クラスター ドメイン

クラスターのドメインを選択してください。デフォルトは`cluster.local`です。

[#_nodeport_service_port_range]
===== NodePort Service Port Range

https://kubernetes.io/docs/concepts/services-networking/service/#nodeport[NodePortサービス]に使用できるポートの範囲を変更するオプション。デフォルトは`30000-32767`です。

[#_truncate_hostnames]
===== ホスト名を切り捨てる

ホスト名を15文字以下に切り捨てるオプション。このフィールドはクラスターの初期作成時にのみ設定できます。クラスター作成後に15文字の制限を有効または無効にすることはできません。

この設定は、マシンプロビジョニングされたクラスターにのみ影響します。カスタムクラスターは、Rancherの外部でノード作成プロセス中にホスト名を設定するため、このフィールドはカスタムクラスターのホスト名の長さを制限しません。

クラスター内のホスト名を切り捨てることで、Windowsベースのシステムとの互換性が向上します。Kubernetesはホスト名を最大63文字まで許可していますが、NetBIOSを使用するシステムはホスト名を15文字以下に制限します。

[#_tls_alternate_names]
===== TLS代替名

サーバーのTLS証明書にSubject Alternative Namesとしてホスト名またはIPv4/IPv6アドレスを追加します。

[#_stack_preference]
===== スタックの優先設定

クラスターのネットワーキングスタックを選択します。このオプションは次のことに影響します：

* Calico、etcd、kube-apiserver、kube-scheduler、kube-controller-manager、kubeletなどのコンポーネントのヘルスおよびレディネスプローブに使用されるアドレス。
* 認可されたクラスターエンドポイントの`authentication-token-webhook-config-file`内のサーバーURL。
* スナップショット復元中のetcdの`advertise-client-urls`設定。

オプションは`ipv4`、`ipv6`、`dual`です：

* `ipv4`に設定すると、クラスターは`127.0.0.1`を使用します。
* `ipv6`に設定すると、クラスターは`[::1]`を使用します。
* `dual`に設定すると、クラスターは`localhost`を使用します。

スタックの優先設定は、クラスターのネットワーキング構成と一致する必要があります：

* IPv4専用クラスターの場合は`ipv4`に設定します。
* IPv6専用クラスターの場合は`ipv6`に設定します。
* デュアルスタッククラスターの場合は`dual`に設定します。

[CAUTION]
====
ループバックアドレスの設定が正しいことを確認することは、クラスターのプロビジョニングを成功させるために重要です。
詳細については、{xref-node-reqs}[ノード要件]ページを参照してください。
====

[#_authorized_cluster_endpoint]
===== 認可されたクラスターエンドポイント

認可されたクラスターエンドポイントは、Rancherを介さずにKubernetes APIサーバーに直接アクセスするために使用できます。

認可されたクラスターエンドポイントの動作とその使用理由の詳細については、{xref-arch-com-ds-cluster}#_4_authorized_cluster_endpoint[アーキテクチャセクション]を参照してください。

認可されたクラスターエンドポイントにはロードバランサーの使用を推奨します。詳細については、{xref-arch-rec}#_architecture_for_an_authorized_cluster_endpoint_ace[推奨アーキテクチャセクション]を参照してください。

[#_registries]
==== レジストリ

Rancherのイメージをプルするためのイメージリポジトリを選択してください。詳細および設定オプションについては、 https://documentation.suse.com/cloudnative/k3s/latest/en/installation/private-registry.html[K3sドキュメント]を参照してください。

[#_upgrade_strategy]
==== アップグレード戦略

[#_control_plane_concurrency]
===== コントロールプレーンの同時実行

同時にアップグレードできるノードの数を選択してください。固定数または割合で指定できます。

[#_worker_concurrency]
===== ワーカーの同時実行

同時にアップグレードできるノードの数を選択してください。固定数または割合で指定できます。

[#_drain_nodes_control_plane]
===== ノードを排出する（コントロールプレーン）

アップグレード前にノードからすべてのポッドを削除するオプション。

[#_drain_nodes_worker_nodes]
===== ノードを排出する（ワーカーノード）

アップグレード前にノードからすべてのポッドを削除するオプション。

[#_advanced_1]
==== 詳細

異なるノードのためのkubeletオプションを設定するオプション。利用可能なオプションについては、 https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/[Kubernetesドキュメント]を参照してください。

[#_cluster_config_file_reference]
== クラスター構成ファイルリファレンス

YAMLでクラスターを編集することで、<<_configuration_options_in_the_rancher_ui,Rancher UIの設定オプション>>に既にリストされている設定を設定したり、Rancher固有のパラメータを設定したりできます。

.*例のクラスター設定ファイルのスニペット*を開くにはクリックしてください。
[%collapsible]
======
apiVersion: provisioning.cattle.io/v1
kind:クラスター +
spec: +
  cloudCredentialSecretName: cattle-global-data:cc-fllv6 +
  clusterAgentDeploymentCustomization: {} +
  fleetAgentDeploymentCustomization: {} +
  kubernetesVersion: v1.26.7+k3s1 +
  localClusterAuthEndpoint: {} +
  rkeConfig: +
    additionalManifest: "" +
    chartValues: {} +
    etcd: +
      snapshotRetention:5
      snapshotScheduleCron:0 */5 * * * +
    machineGlobalConfig: +
      disable-apiserver: false +
      disable-cloud-controller: false +
      disable-controller-manager: false +
      disable-etcd: false +
      disable-kube-proxy: false +
      disable-network-policy: false +
      disable-scheduler: false +
      etcd-expose-metrics: false +
      kube-apiserver-arg: +
        - audit-policy-file=/etc/rancher/k3s/user-audit-policy.yaml +
        - audit-log-path=/etc/rancher/k3s/user-audit.logs +
      profile: null +
      secrets-encryption: false +
    machinePools: +
    - controlPlaneRole: true +
      etcdRole: true +
      machineConfigRef: +
        kind:Amazonec2Config
        name: nc-test-pool1-pwl5h
      name: pool1
      quantity:1 +
      unhealthyNodeTimeout:0s +
      workerRole: true +
    machineSelectorConfig: +
      - config: +
          docker: false +
          protect-kernel-defaults: false +
          selinux: false +
    machineSelectorFiles: +
      - fileSources: +
          - configMap: +
              name: '' +
            secret: +
              name: audit-policy +
              items: +
                - key: audit-policy +
                  path: /etc/rancher/k3s/user-audit-policy.yaml +
        machineLabelSelector: +
          matchLabels: +
            rke.cattle.io/control-plane-role: 'true' +
    registries: {} +
    upgradeStrategy: +
      controlPlaneConcurrency:'1' +
      controlPlaneDrainOptions: +
        deleteEmptyDirData: true +
        disableEviction: false +
        enabled: false +
        force: false +
        gracePeriod: -1 +
        ignoreDaemonSets: true +
        ignoreErrors: false +
        postDrainHooks: null +
        preDrainHooks: null +
        skipWaitForDeleteTimeoutSeconds:0 +
        timeout:120 +
      workerConcurrency:'1' +
      workerDrainOptions: +
        deleteEmptyDirData: true +
        disableEviction: false +
        enabled: false +
        force: false +
        gracePeriod: -1 +
        ignoreDaemonSets: true +
        ignoreErrors: false +
        postDrainHooks: null +
        preDrainHooks: null +
        skipWaitForDeleteTimeoutSeconds:0 +
        timeout:120
======

[#_additionalmanifest]
=== additionalManifest

制御プレーンノードに配信する追加のマニフェストを指定します。

値は文字列で、ターゲットノードのパス`/var/lib/rancher/k3s/server/manifests/rancher/addons.yaml`に配置されます。

例:

[,yaml]
----
additionalManifest: |-
  apiVersion: v1
  kind: Namespace
  metadata:
    name: name-xxxx
----

[NOTE]
====

システムチャートをカスタマイズしたい場合は、以下に説明する`chartValues`フィールドを使用する必要があります。

`additionalManifest`を介してシステムチャートをカスタマイズするためにHelmChartConfigを使用するなどの代替手段は、同じチャートに対して複数のHelmChartConfigが存在するため、予期しない動作を引き起こす可能性があります。
====


[#_chartvalues]
=== chartValues

K3sによってインストールされたシステムチャートの値を指定します。

K3sがパッケージ化されたコンポーネントを管理する方法についての詳細は、 https://documentation.suse.com/cloudnative/k3s/latest/en/installation/packaged-components.html[K3sのドキュメント]を参照してください。

例:

[,yaml]
----
chartValues:
    chart-name:
        key: value
----

[#_machineglobalconfig]
=== machineGlobalConfig

K3sの設定を指定します。ここで行った設定変更は、すべてのノードに適用されます。k3sの https://documentation.suse.com/cloudnative/k3s/latest/en/cli/server.html[スタンドアロンバージョン]で利用可能な設定オプションは、ここに適用できます。

例:

[,yaml]
----
machineGlobalConfig:
    etcd-arg:
        - key1=value1
        - key2=value2
----

事前にノードにファイルを配置しやすくするために、Rancherは設定に以下の値が含まれることを期待しており、K3sは値をファイルパスとして入力することを期待しています:

* プライベートレジストリ
* flannel-conf

Rancherは、ターゲットノードのパス`/var/lib/rancher/k3s/etc/config-files/<option>`にファイルを配信し、K3sサーバーに適切なオプションを設定します。

例:

[,yaml]
----
apiVersion: provisioning.cattle.io/v1
kind: Cluster
spec:
  rkeConfig:
    machineGlobalConfig:
      private-registry: |
        mirrors:
          docker.io:
            endpoint:
              - "http://mycustomreg.com:5000"
        configs:
          "mycustomreg:5000":
            auth:
              username: xxxxxx # this is the registry username
              password: xxxxxx # this is the registry password
----

[#_machineselectorconfig]
=== machineSelectorConfig

`machineSelectorConfig`は<<_machineglobalconfig,`machineGlobalConfig`>>と同じですが、設定に<<_kubernetes_node_labels,ラベル>>セレクターを指定できます。設定は、提供されたラベルセレクターに一致するノードにのみ適用されます。

複数の`config`エントリが許可されており、それぞれが独自の`machineLabelSelector`を指定します。ユーザーは`matchExpressions`、`matchLabels`、両方、またはどちらも指定できます。このフィールドの`machineLabelSelector`セクションを省略すると、設定を`machineGlobalConfig`セクションに置くのと同じ効果があります。

例:

[,yaml]
----
machineSelectorConfig
  - config:
      config-key: config-value
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
----

[#_machineselectorfiles]
=== machineSelectorFiles

[NOTE]
====

この機能はRancher v2.7.2以降で利用可能です。
====


ノードにファイルを配信し、K3sサーバーまたはエージェントプロセスを開始する前にファイルが配置されるようにします。
ファイルの内容は、シークレットまたはコンフィグマップのいずれかから取得されます。ターゲットノードは`machineLabelSelector`によってフィルタリングされます。

例：

[,yaml]
----
machineSelectorFiles:
  - fileSources:
      - secret:
          items:
            - key: example-key
              path: path-to-put-the-file-on-nodes
              permissions: 644 (optional)
              hash: base64-encoded-hash-of-the-content (optional)
          name: example-secret-name
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
  - fileSources:
      - configMap:
          items:
            - key: example-key
              path: path-to-put-the-file-on-nodes
              permissions: 644 (optional)
              hash: base64-encoded-hash-of-the-content (optional)
          name: example-configmap-name
    machineLabelSelector:
      matchExpressions:
        - key: example-key
          operator: string # Valid operators are In, NotIn, Exists and DoesNotExist.
          values:
            - example-value1
            - example-value2
      matchLabels:
        key1: value1
        key2: value2
----

シークレットまたはコンフィグマップは、以下の要件を満たす必要があります：

. それは、Clusterオブジェクトが存在する`fleet-default`ネームスペースにある必要があります。
. ターゲットクラスターが使用できるようにするアノテーション`rke.cattle.io/object-authorized-for-clusters: cluster-name1,cluster-name2`を必ず備えていなければなりません。

[TIP]
====

Rancher Dashboardは、シークレットまたはコンフィグマップを作成するための使いやすいフォームを提供します。
====


例:

[,yaml]
----
apiVersion: v1
data:
  audit-policy: >-
    IyBMb2cgYWxsIHJlcXVlc3RzIGF0IHRoZSBNZXRhZGF0YSBsZXZlbC4KYXBpVmVyc2lvbjogYXVkaXQuazhzLmlvL3YxCmtpbmQ6IFBvbGljeQpydWxlczoKLSBsZXZlbDogTWV0YWRhdGE=
kind: Secret
metadata:
  annotations:
    rke.cattle.io/object-authorized-for-clusters: cluster1
  name: name1
  namespace: fleet-default
----
