= 概要
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-04
:page-revdate: {revdate}
:community-path: integrations-in-rancher/fleet/overview.adoc 
:product-path: integrations/fleet/overview.adoc
ifeval::["{build-type}" != "community"]
:xref-backup-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/back-up.adoc
:xref-fleet-architecture: xref:integrations/fleet/architecture.adoc
:xref-fleet-windows: xref:integrations/fleet/windows-support.adoc
:xref-fleet-proxy: xref:integrations/fleet/use-fleet-behind-a-proxy.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-backup-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher.adoc
:xref-fleet-architecture: xref:integrations-in-rancher/fleet/architecture.adoc
:xref-fleet-windows: xref:integrations-in-rancher/fleet/windows-support.adoc
:xref-fleet-proxy: xref:integrations-in-rancher/fleet/use-fleet-behind-a-proxy.adoc
endif::[]

Fleetを使用した継続的デリバリは、大規模環境でのGitOpsです。Fleetは最大100万のクラスターを管理するように設計されています。それはまた、 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-operators/installation.html#_default_install[単一のクラスター]にも適しているほど軽量ですが、 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-operators/installation.html#_configuration_for_multi_cluster[大規模]になると本当に輝きます。大規模とは、多くのクラスター、多くのデプロイメント、または単一の組織内の多くのチームのいずれかを意味します。

FleetはRancherとは別のプロジェクトであり、Helmを使用して任意のKubernetesクラスターにインストールできます。

[#_architecture]
== アーキテクチャ

Fleetの動作に関する情報は、{xref-fleet-architecture}[アーキテクチャ]ページを参照してください。

[#_accessing_fleet_product_name_in_the_rancher_ui]
== Rancher UIでの{fleet-product-name}へのアクセス

FleetはRancherにプリインストールされており、Rancher UIの*継続的デリバリ*オプションによって管理されています。継続的デリバリやその他のFleetのトラブルシューティングのヒントについての追加情報は、 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/troubleshooting.html[こちら]をご参照ください。

ユーザーは、*gitops*の実践に従うことで、手動操作なしにgitリポジトリ内のKubernetesクラスターにアプリケーションをデプロイするために継続的デリバリを活用できます。

Rancher UIで継続的デリバリにアクセスするための手順は以下の通りです。

. *☰ > 継続的デリバリ*をクリックします。
. メニューの上部でネームスペースを選択し、以下の点に注意してください：
 ** デフォルトでは、*fleet-default*が選択されており、Rancherを通じて登録されたすべてのダウンストリームクラスターが含まれています。
 ** *fleet-local*に切り替えることもできます。これは*ローカルクラスタ*のみを含むか、クラスターを割り当てて移動できる独自のワークスペースを作成することもできます。
 ** その後、左側のナビゲーションバーの*クラスター*をクリックしてクラスターを管理できます。
. 左側のナビゲーションバーの*Gitrepos*をクリックして、現在のワークスペース内のクラスターにgitリポジトリをデプロイします。
. https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-users/gitrepo-add.html[gitリポジトリ]と https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-users/gitrepo-targets.html[ターゲットクラスター/クラスターグループ]を選択します。左側のナビゲーションバーから*クラスターグループ*をクリックすることで、UIでクラスターグループを作成することもできます。
. gitリポジトリがデプロイされると、Rancher UIを通じてアプリケーションを監視できます。

[#_windows_support]
== Windowsのサポート

Windowsノードを持つクラスターのサポートの詳細については、{xref-fleet-windows}[Windowsのサポート]ページを参照してください。

[#_github_repository]
== GitHubリポジトリ。

Fleet Helmチャートは https://github.com/rancher/fleet/releases[こちら]で入手できます。

[#_using_fleet_product_name_behind_a_proxy]
== プロキシの背後で{fleet-product-name}を使用する。

プロキシの背後でFleetを使用する詳細については、{xref-fleet-proxy}[プロキシの背後でFleetを使用する]ページを参照してください。

[#_helm_chart_dependencies]
== Helmチャートの依存関係。

依存関係を持つHelmチャートが正常にデプロイされるためには、手動コマンド（以下に記載）を実行する必要があります。依存関係リストを満たすのはユーザーの責任です。これを行わずにリポジトリをクローンし、`helm install`を実行すると、依存関係が欠落しているため、インストールが失敗します。

Gitリポジトリ内のHelmチャートは、`charts/`サブディレクトリにその依存関係を含める必要があります。これを行うには、手動で`helm dependencies update $chart`を実行するか、ローカルで`helm dependencies build $chart`を実行し、その後、完全な`charts/`ディレクトリをGitリポジトリにコミットしてください。環境に適したパラメータでコマンドを更新することを確認してください。

[#_fleet_resource_configuration]
== Fleetリソースの設定。

Fleetでは、管理クラスターコントローラーとダウンストリームクラスターエージェントの両方に対して、CPUおよびメモリリソースの要求と制限を設定できます。Rancherを通じてFleetを実行する場合、Helmを直接使用するのではなく、`rancher-config` ConfigMapを使用してこれらの変更を適用してください。

詳細な設定オプションについては、link:https://fleet.rancher.io/how-tos-for-operators/resource-limits[Fleetのリソース制限]を参照してください。

[#_troubleshooting]
== トラブルシューティング

* *既知の問題*: Fleetのgitrepos用のclientSecretNameおよびhelmSecretNameシークレットは、{xref-backup-cluster}#_1_install_the_rancher_backup_operator[バックアップ-リストアオペレーター]によって作成されたバックアップやリストアには含まれていません。恒久的な解決策が整い次第、コミュニティに更新します。
* *一時的な回避策*:デフォルトでは、ユーザー定義のシークレットはFleetでバックアップされません。災害復旧の復元やRancherを新しいクラスターに移行する場合、シークレットを再作成する必要があります。バックアップしたい追加のリソースを含めるためにresourceSetを変更するには、ドキュメント https://github.com/rancher/backup-restore-operator#user-flow[こちら]を参照してください。
* *デバッグログ*：Fleetコンポーネントのデバッグログを有効にするには、既存の*rancher-config* ConfigMap内に新しい*fleet*エントリを作成し、値`{"debug": 1, "debugLevel": 1}`を設定します。ConfigMapを保存すると、Fleetアプリケーションが再起動します。

[#_documentation]
== マニュアル

詳細については、 https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/index.html[{fleet-product-name}ドキュメント]を参照してください。
