= Configuration de l'infrastructure pour un cluster {rke2-product-name} Kubernetes à haute disponibilité
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-30
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc 
:product-path: installation-and-upgrade/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-setup-ec2-nodes: xref:installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:installation-and-upgrade/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:installation-and-upgrade/infrastructure-setup/amazon-elb-load-balancer.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-setup-ec2-nodes: xref:how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:how-to-guides/new-user-guides/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:how-to-guides/new-user-guides/infrastructure-setup/amazon-elb-load-balancer.adoc
endif::[]


Ce tutoriel est destiné à vous aider à provisionner l'infrastructure sous-jacente pour un serveur de gestion Rancher.

L'infrastructure recommandée pour le cluster Kubernetes dédié à Rancher diffère selon que Rancher sera installé sur un cluster Kubernetes RKE2, sur un cluster Kubernetes RKE ou sur un conteneur Docker unique.

[NOTE]
.Important :
====

Ces nœuds doivent être dans la même région. Vous pouvez placer ces serveurs dans des zones de disponibilité séparées (datacenter).
====


Pour installer le serveur de gestion Rancher sur un cluster RKE2 à haute disponibilité, nous recommandons de configurer l'infrastructure suivante{nbsp}:

* *Trois nœuds Linux,* généralement des machines virtuelles, dans le fournisseur d'infrastructure de votre choix.
* *Un équilibreur de charge* pour diriger le trafic vers les nœuds.
* *Un enregistrement DNS* pour mapper une URL à l'équilibreur de charge. Cela deviendra l'URL du serveur Rancher, et les clusters Kubernetes en aval devront y accéder.

[#_1_set_up_linux_nodes]
== 1. Configurer des nœuds Linux

Assurez-vous que vos nœuds remplissent les exigences générales d'installation pour {xref-install-reqs}[OS, environnement d'exécution de conteneur, matériel et réseau.]

Pour un exemple d'une façon de configurer des nœuds Linux, référez-vous à ce {xref-setup-ec2-nodes}[tutoriel] pour configurer des nœuds en tant qu'instances dans Amazon EC2.

[#_2_set_up_the_load_balancer]
== 2. Configurer l'équilibreur de charge

Vous devrez également configurer un équilibreur de charge pour diriger le trafic vers la réplique Rancher sur tous les nœuds. Cela empêchera une panne d'un nœud unique de couper les communications avec le serveur de gestion Rancher.

[WARNING]
====
*Ingress-NGINX EOL:* Le contrôleur de la communauté `ingress-nginx` a atteint sa fin du service (EOL) en mars 2026 et a cessé la prise en charge dans RKE2 v1.36. Les versions RKE2 provisionnées par SUSE Rancher Prime continueront à recevoir `ingress-nginx` le support et des correctifs CVE (8+) pendant tout le cycle de vie de RKE2 v1.32, v1.33, v1.34, v1.35 et v1.36. Traefik est le chemin de migration recommandé pour les environnements SUSE Rancher RKE2, il est conseillé de migrer dès que possible. Consultez https://support.scc.suse.com/s/kb/Migrating-from-Ingress-NGINX-to-Traefik-in-a-Rancher-provisioned-RKE2-Cluster?language=en_US[Migration de l'Ingress NGINX vers Traefik dans un cluster RKE2 provisionné par Rancher] pour plus de détails.
====

Lorsque Kubernetes sera configuré dans une étape ultérieure, l'outil RKE2 déploiera un contrôleur Ingress Nginx. Ce contrôleur écoutera sur les ports 80 et 443 des nœuds de travail, répondant au trafic destiné à des noms d'hôtes spécifiques.

Lorsque Rancher sera installé (également dans une étape ultérieure), le système Rancher créera une ressource Ingress. Cet Ingress indique au contrôleur Ingress Nginx d'écouter le trafic destiné au nom d'hôte Rancher. Le contrôleur Ingress Nginx, lorsqu'il reçoit du trafic destiné au nom d'hôte Rancher, transmettra ce trafic aux pods Rancher en cours d'exécution dans le cluster.

Pour votre mise en œuvre, envisagez si vous souhaitez ou avez besoin d'utiliser un équilibreur de charge de couche 4 ou de couche 7{nbsp}:

* *Un équilibreur de charge de couche 4* est le choix le plus simple des deux, dans lequel vous redirigez le trafic TCP vers vos nœuds. Nous recommandons de configurer votre équilibreur de charge en tant qu'équilibreur de charge de couche 4, redirigeant le trafic vers les ports TCP/80 et TCP/443 vers les nœuds du cluster de gestion Rancher. Le contrôleur Ingress sur le cluster redirigera le trafic HTTP vers HTTPS et terminera SSL/TLS sur le port TCP/443. Le contrôleur Ingress transmettra le trafic au port TCP/80 vers le pod Ingress dans le déploiement Rancher.
* *Un équilibreur de charge de couche 7* est un peu plus compliqué mais peut offrir des fonctionnalités que vous pourriez vouloir. Par exemple, un équilibreur de charge de couche 7 est capable de gérer la terminaison TLS au niveau de l'équilibreur de charge, contrairement à Rancher qui effectue lui-même la terminaison TLS. Cela peut être bénéfique si vous souhaitez centraliser votre terminaison TLS dans votre infrastructure. L'équilibrage de charge de couche 7 offre également la capacité à votre équilibreur de charge de prendre des décisions basées sur des attributs HTTP tels que les cookies, etc. qu'un équilibreur de charge de couche 4 ne peut pas prendre en compte. Si vous décidez de terminer le trafic SSL/TLS sur un équilibreur de charge de couche 7, vous devrez utiliser l'option `--set tls=external` lors de l'installation de Rancher à une étape ultérieure. Pour plus d'informations, consultez le {xref-helm-chart-options}#_external_tls_termination[chart Helm de Rancher].

Pour un exemple montrant comment configurer un équilibreur de charge NGINX, consultez {xref-nginx-load-balancer}[cette page.]

Pour un guide pratique sur la configuration d'un équilibreur de charge réseau Amazon ELB, consultez {xref-amazon-elb}[cette page.]

[CAUTION]
====

N'utilisez pas cet équilibreur de charge (c'est-à-dire l'`local`Ingress du cluster) pour équilibrer des applications autres que Rancher après l'installation. Partager cet Ingress avec d'autres applications peut entraîner des erreurs de websocket pour Rancher après les rechargements de configuration de l'Ingress pour d'autres applications. Nous recommandons de dédier le cluster `local` à Rancher et à aucune autre application.
====


[#_3_set_up_the_dns_record]
== 3. Configurer l'enregistrement DNS

Une fois que vous avez configuré votre équilibreur de charge, vous devrez créer un enregistrement DNS pour envoyer le trafic à cet équilibreur de charge.

Selon votre environnement, cela peut être un enregistrement A pointant vers l'IP de l'équilibreur de charge, ou cela peut être un CNAME pointant vers le nom d'hôte de l'équilibreur de charge. Dans les deux cas, assurez-vous que cet enregistrement est le nom d'hôte sur lequel vous souhaitez que Rancher réponde.

Vous devrez spécifier ce nom d'hôte à une étape ultérieure lors de l'installation de Rancher, et il n'est pas possible de le changer par la suite. Assurez-vous que votre décision est définitive.

Pour une procédure sur la configuration d'un enregistrement DNS pour acheminer le trafic de domaine vers un équilibreur de charge Amazon ELB, consultez la https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer[documentation officielle d'AWS.]
