= Configuration des nœuds dans Amazon EC2
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc 
:product-path: installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-set-up-cloud-providers: xref:guides-procédures/guides-nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-configuration/configuration-cloud-providers/index.adoc
endif::[]

Dans ce tutoriel, vous apprendrez une méthode pour configurer des nœuds Linux pour le serveur de gestion Rancher. Ces nœuds répondront aux exigences des nœuds pour {xref-install-reqs}[OS, Docker, matériel et réseau.]

Si le serveur Rancher doit être installé sur un cluster Kubernetes RKE, vous devez provisionner trois instances.

Si le serveur Rancher doit être installé sur un cluster Kubernetes K3s, vous n'avez besoin de provisionner que deux instances.

Si le serveur Rancher est installé dans un seul conteneur Docker, vous n'avez besoin que d'une instance.

[#_1_optional_preparation]
== 1. Préparation optionnelle

* *Créer un rôle IAM :* Pour permettre à Rancher de manipuler les ressources AWS, telles que le provisionnement de nouveaux stockages ou de nouveaux nœuds, vous devrez configurer Amazon en tant que fournisseur de cloud. Il y a plusieurs choses que vous devrez faire pour configurer le fournisseur de cloud sur EC2, mais une partie de ce processus consiste à configurer un rôle IAM pour les nœuds du serveur Rancher. Pour les détails complets sur la configuration du fournisseur de cloud, référez-vous à cette {xref-set-up-cloud-providers}[page.]
* *Créer un groupe de sécurité :* Nous recommandons également de configurer un groupe de sécurité pour les nœuds Rancher qui respecte les {xref-install-reqs}#_port_requirements[exigences de port pour les nœuds Rancher.]

[#_2_provision_instances]
== 2. Provisionner des instances

. Connectez-vous à la https://console.aws.amazon.com/ec2/[Console Amazon AWS EC2] pour commencer. Assurez-vous de noter la *Région* où vos instances EC2 (nœuds Linux) sont créées, car toute l'infrastructure pour le serveur de gestion Rancher doit être dans la même région.
. Dans le panneau de gauche, cliquez sur *Instances*.
. Click *Launch Instance*.
. Dans la section intitulée *Étape 1{nbsp}: Choisissez une image de machine Amazon (AMI),* nous utiliserons Ubuntu 18.04 comme système d'exploitation Linux, en utilisant `ami-0d1cd67c26f5fca19 (64-bit x86)`. Allez à l'AMI Ubuntu et cliquez sur *Sélectionner*.
. Dans l'*Étape 2{nbsp}: Dans la section Choisissez un type d'instance*, sélectionnez le type `t2.medium`.
. Cliquez sur *Suivant{nbsp}: Configurer les détails de l'instance*.
. Dans le champ *Nombre d'instances*, entrez le nombre d'instances. Un cluster K3s à haute disponibilité nécessite seulement deux instances, tandis qu'un cluster RKE à haute disponibilité nécessite trois instances.
. Facultatives : Si vous avez créé un rôle IAM pour que Rancher puisse manipuler les ressources AWS, sélectionnez le nouveau rôle IAM dans le champ *Rôle IAM*.
. Cliquez sur *Suivant{nbsp}: Ajouter du stockage,* *Suivant{nbsp}: Ajouter des balises,* et *Suivant{nbsp}: Configurer le groupe de sécurité*.
. Dans *Étape 6{nbsp}: Configurer le groupe de sécurité,* sélectionnez un groupe de sécurité qui respecte les {xref-install-reqs}#_port_requirements[exigences de port pour les nœuds Rancher].
. Cliquez sur *Vérifier et lancer*.
. Cliquez sur *Lancer*.
. Choisissez une nouvelle paire de clés ou une paire de clés existante que vous utiliserez pour vous connecter à votre instance plus tard. Si vous utilisez une paire de clés existante, assurez-vous d'avoir déjà accès à la clé privée.
. Cliquez sur *Lancer les instances*.

*Résultat :* Vous avez créé des nœuds Rancher qui satisfont aux exigences en matière de système d'exploitation, de matériel et de réseau.

[NOTE]
====

Si les nœuds sont utilisés pour un cluster Kubernetes RKE, installez Docker sur chaque nœud à l'étape suivante. Pour un cluster Kubernetes K3s, les nœuds sont maintenant prêts à installer K3s.
====


[#_3_install_docker_and_create_user_for_rke_kubernetes_cluster_nodes]
== 3. Installez Docker et créez un utilisateur pour les nœuds du cluster Kubernetes RKE.

. Depuis la https://console.aws.amazon.com/ec2/[console AWS EC2,], cliquez sur *Instances* dans le panneau de gauche.
. Allez à l'instance sur laquelle vous souhaitez installer Docker. Sélectionnez l'instance et cliquez sur menu:Actions[Connecter].
. Connectez-vous à l'instance en suivant les instructions à l'écran qui apparaissent. Copiez le DNS public de l'instance. Un exemple de commande pour se connecter à l'instance via SSH est le suivant{nbsp}:
+
----
sudo ssh -i [path-to-private-key] ubuntu@[public-DNS-of-instance]
----

. Exécutez la commande suivante sur l'instance pour installer Docker avec l'un des scripts d'installation de Rancher{nbsp}:
+
----
curl https://releases.rancher.com/install-docker/18.09.sh | sh
----

. Lorsque vous êtes connecté à l'instance, exécutez la commande suivante sur l'instance pour créer un utilisateur{nbsp}:
+
----
sudo usermod -aG docker ubuntu
----

. Répétez ces étapes afin que Docker soit installé sur chaque nœud qui exécutera finalement le serveur de gestion Rancher.

[TIP]
====

Pour savoir si un script est disponible pour installer une certaine version de Docker, consultez ce https://github.com/rancher/install-docker[dépôt GitHub,] qui contient tous les scripts d'installation de Docker de Rancher.
====


*Résultat :* Vous avez configuré des nœuds de serveur Rancher qui remplissent toutes les exigences des nœuds en matière de système d'exploitation, Docker, matériel et réseau.

[#_next_steps_for_rke_kubernetes_cluster_nodes]
== Étapes suivantes pour les nœuds du cluster Kubernetes RKE.

Si vous allez installer un cluster RKE sur les nouveaux nœuds, notez l'*IP publique IPv4* et l'*IP privée* de chaque nœud. Cette information peut être trouvée dans l'onglet *Description* pour chaque nœud après sa création. L'IP publique et l'IP privée seront utilisées pour remplir le `address` et le `internal_address` de chaque nœud dans le fichier de configuration du cluster RKE, `rancher-cluster.yml`.

RKE aura également besoin d'accéder à la clé privée pour se connecter à chaque nœud. Par conséquent, vous voudrez peut-être noter le chemin vers vos clés privées pour vous connecter aux nœuds, qui peut également être inclus dans le `rancher-cluster.yml` sous la directive `ssh_key_path` pour chaque nœud.
