= Anpassen von Grafana-Dashboards
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc 
:product-path: observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-rancher-monitoring-rbac: xref:observability/monitoring-and-dashboards/rbac-for-monitoring.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
endif::[]

In diesem Abschnitt lernen Sie, wie Sie das Grafana-Dashboard anpassen, um Metriken anzuzeigen, die für einen bestimmten Container gelten.

[#_prerequisites]
== Voraussetzungen

Bevor Sie ein Grafana-Dashboard anpassen können, muss die `rancher-monitoring` Anwendung installiert sein.

Um die Links zu den externen Überwachungs-UIs, einschließlich Grafana-Dashboards, zu sehen, benötigen Sie mindestens eine {xref-rancher-monitoring-rbac}#_users_with_rancher_based_permissions[Projektmitglied-Rolle.]

[#_signing_in_to_grafana]
== Anmeldung bei Grafana

. Gehen Sie in der Rancher-Benutzeroberfläche zu dem Cluster, das das Dashboard hat, das Sie anpassen möchten.
. Klicken Sie im linken Menü auf *Monitoring.*
. Klicken Sie auf *Grafana.* Das Grafana-Dashboard sollte in einem neuen Tab geöffnet werden.
. Gehen Sie zum Anmelde-Icon in der unteren linken Ecke und klicken Sie auf *Anmelden.*
. Melden Sie sich bei Grafana an. Der Standard-Admin-Benutzername und das Passwort für die Grafana-Instanz sind `admin/prom-operator`. (Unabhängig davon, wer das Passwort hat, sind Administratorrechte für den Cluster in Rancher erforderlich, um auf die Grafana-Instanz zuzugreifen.) Alternative Anmeldeinformationen können auch beim Bereitstellen oder Aktualisieren des Charts angegeben werden.

[#_getting_the_promql_query_powering_a_grafana_panel]
== Abrufen der PromQL-Abfrage, die ein Grafana-Panel antreibt

Für jedes Panel können Sie auf den Titel klicken und *Erforschen* klicken, um die PromQL-Abfragen zu erhalten, die die Grafik antreiben.

Für dieses Beispiel möchten wir die CPU-Auslastung des Alertmanager-Containers abrufen, also klicken wir auf menu:CPU-Auslastung[Überprüfen.]

Der *Daten*-Tab zeigt die zugrunde liegenden Daten als Zeitreihe an, mit der Zeit in der ersten Spalte und dem Ergebnis der PromQL-Abfrage in der zweiten Spalte. Kopieren Sie die PromQL-Abfrage.

----
(1 - (avg(irate({__name__=~"node_cpu_seconds_total|windows_cpu_time_total",mode="idle"}[5m])))) * 100
----

Sie können die Abfrage dann im Grafana-Panel ändern oder ein neues Grafana-Panel mit der Abfrage erstellen.

Siehe auch:

* https://grafana.com/docs/grafana/latest/panels-visualizations/configure-panel-options/#edit-a-panel[Grafana-Dokumentation zum Bearbeiten eines Panels]
* https://grafana.com/docs/grafana/latest/panels-visualizations/panel-editor-overview[Grafana-Dokumentation zum Hinzufügen eines Panels zu einem Dashboard]
