= Prometheus-Konfiguration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

Es ist normalerweise nicht erforderlich, die benutzerdefinierte Ressource Prometheus direkt zu bearbeiten, da die Überwachungsanwendung sie automatisch basierend auf Änderungen an ServiceMonitors und PodMonitors aktualisiert.

[NOTE]
====

Dieser Abschnitt setzt voraus, dass Sie mit der Funktionsweise der Überwachungskomponenten vertraut sind. Für weitere Informationen siehe {xref-how-monitoring-works}[diesen Abschnitt.]
====


[#_about_the_prometheus_custom_resource]
== Über die benutzerdefinierte Ressource Prometheus

Die Prometheus CR definiert eine gewünschte Prometheus-Implementierung. Der Prometheus Operator überwacht die Prometheus CR. Wenn sich die CR ändert, erstellt der Prometheus Operator `prometheus-rancher-monitoring-prometheus`, eine Prometheus-Implementierung basierend auf der CR-Konfiguration.

Die Prometheus CR gibt Details wie Regeln und welche Alertmanager mit Prometheus verbunden sind, an. Rancher erstellt diese CR für Sie.

Monitoring V2 unterstützt nur ein Prometheus pro Cluster. Sie möchten jedoch möglicherweise die Prometheus CR bearbeiten, wenn Sie die Überwachung auf bestimmte Namespaces beschränken möchten.
