= Konfigurieren von PrometheusRules
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheusrules.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/prometheusrules.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-promql-expressions: xref:observability/monitoring-and-dashboards/promql-expressions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-promql-expressions: xref:integrations-in-rancher/monitoring-and-alerting/promql-expressions.adoc
endif::[]

Eine PrometheusRule definiert eine Gruppe von Prometheus-Alarmierungs- und/oder Aufzeichnungsregeln.

[NOTE]
====

Dieser Abschnitt setzt voraus, dass Sie mit der Funktionsweise der Überwachungskomponenten vertraut sind. Für weitere Informationen siehe {xref-how-monitoring-works}[diesen Abschnitt.]
====


[#_creating_prometheusrules_in_the_rancher_ui]
== Erstellen von PrometheusRules in der Rancher-Benutzeroberfläche

[NOTE]
.Voraussetzung:
====

Die Überwachungsanwendung muss installiert sein.
====


Um Regelgruppen in der Rancher-Benutzeroberfläche zu erstellen,

. Gehen Sie zu dem Cluster, in dem Sie Regelgruppen erstellen möchten. Klicken Sie auf menu:Monitoring[Erweitert] und klicken Sie auf *Prometheus-Regeln*.
. Klicken Sie auf *Erstellen*.
. Geben Sie einen *Gruppennamen* ein.
. Konfigurieren Sie die Regeln. In der Benutzeroberfläche von Rancher erwarten wir, dass eine Regelgruppe entweder Alarmierungsregeln oder Aufzeichnungsregeln enthält, jedoch nicht beides. Für Hilfe beim Ausfüllen der Formulare, beziehen Sie sich auf die untenstehenden Konfigurationsoptionen.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Alarme können so konfiguriert werden, dass sie Benachrichtigungen an die Empfänger senden.

[#_about_the_prometheusrule_custom_resource]
== Über die benutzerdefinierte Ressource PrometheusRule

Wenn Sie eine Regel definieren (die innerhalb einer RuleGroup in einer PrometheusRule-Ressource deklariert ist), enthält die https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#rule[spec der Regel selbst] Labels, die vom Alertmanager verwendet werden, um zu bestimmen, welche Route diesen Alarm erhalten soll. Zum Beispiel wird ein Alarm mit dem Label `team: front-end` an alle Routen gesendet, die mit diesem Label übereinstimmen.

Prometheus-Regeldateien werden in benutzerdefinierten Ressourcen von PrometheusRule gehalten. Eine PrometheusRule ermöglicht es Ihnen, eine oder mehrere RuleGroups zu definieren. Jede RuleGroup besteht aus einer Menge von Regelobjekten, die jeweils entweder eine Alarmierungs- oder eine Aufzeichnungsregel mit den folgenden Feldern darstellen können:

* Der Name des neuen Alarms oder der Aufzeichnung.
* Ein PromQL-Ausdruck für den neuen Alarm oder die neue Aufzeichnung.
* Labels, die dem Alarm oder der Aufzeichnung zugeordnet werden sollten, um diese zu identifizieren (z. B. Clustername oder Schweregrad).
* Annotationen, die zusätzliche wichtige Informationen kodieren, die in der Benachrichtigung für einen Alarm angezeigt werden müssen (z. B. Zusammenfassung, Beschreibung, Nachricht, Runbook-URL usw.). Dieses Feld ist für Aufzeichnungsregeln nicht erforderlich.

Für weitere Informationen darüber, welche Felder angegeben werden können, sehen Sie sich bitte das https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#prometheusrulespec[Spec des Prometheus Operators] an.

Verwenden Sie das Label-Selektorfeld `ruleSelector` im Prometheus-Objekt, um die Regeldateien zu definieren, die in Prometheus eingebunden werden sollen.

Für Beispiele, beziehen Sie sich auf die Prometheus-Dokumentation zu https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/[Aufzeichnungsregeln] und https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[Alarmierungsregeln.]

[#_configuration]
== Konfiguration

[#_rule_group]
=== Regelgruppe

|===
| Feld | Beschreibung

| Gruppenname
| Der Name der Gruppe. Muss innerhalb einer Regeldatei eindeutig sein.

| Gruppenintervall überschreiben
| Dauer in Sekunden, wie oft die Regeln in der Gruppe ausgewertet werden.
|===

[#_alerting_rules]
=== Alarmierungsregeln

https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[Alarmierungsregeln] ermöglichen es Ihnen, Alarmbedingungen basierend auf PromQL (Prometheus Query Language) Ausdrücken zu definieren und Benachrichtigungen über auslösende Alarme an einen externen Dienst zu senden.

|===
| Feld | Beschreibung

| Alarmname
| Der Name des Alarms. Muss ein gültiger Labelwert sein.

| Warten bis zur Auslösung für
| Dauer in Sekunden. Alarme gelten als ausgelöst, sobald sie so lange gemeldet wurden. Alarme, die noch nicht lange genug ausgelöst wurden, werden als ausstehend betrachtet.

| PromQL Expression
| Der zu bewertende PromQL-Ausdruck. Prometheus wird den aktuellen Wert dieses PromQL-Ausdrucks in jedem Bewertungszyklus auswerten, und alle resultierenden Zeitreihen werden als entweder ausstehende oder ausgelöste Alarme klassifiziert. Für weitere Informationen siehe die https://prometheus.io/docs/prometheus/latest/querying/basics/[Prometheus-Dokumentation] oder unsere {xref-promql-expressions}[Beispiel-PromQL-Ausdrücke.]

| Labels
| Labels, die für jeden Alarm hinzugefügt oder überschrieben werden sollen.

| Schweregrad
| Wenn aktiviert, werden Labels an den Alarm oder den Datensatz angehängt, die ihn nach dem Schweregrad identifizieren.

| Der Wert der Schweregradbezeichnung
| Kritisch, Warnung oder keine

| Annotationen
| Annotationen sind eine Reihe von Informationsetiketten, die verwendet werden können, um längere zusätzliche Informationen zu speichern, wie z. B. Alarmbeschreibungen oder Links zu Runbooks. Ein https://en.wikipedia.org/wiki/Runbook[Runbook] ist eine Dokumentation darüber, wie man mit Alarmen umgeht. Die Annotationswerte können https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating[vorlagenbasiert] sein.
|===

[#_recording_rules]
=== Aufzeichnungsregeln

https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules[Aufzeichnungsregeln] ermöglichen es Ihnen, häufig benötigte oder rechenintensive PromQL (Prometheus Query Language) Ausdrücke vorab zu berechnen und deren Ergebnis als neuen Satz von Zeitreihen zu speichern.

|===
| Feld | Beschreibung

| Zeitreihenname
| Der Name der auszugebenden Zeitreihe. Muss ein gültiger Metrikname sein.

| PromQL Expression
| Der zu bewertende PromQL-Ausdruck. Prometheus wird den aktuellen Wert dieses PromQL-Ausdrucks bei jedem Evaluierungszyklus auswerten, und das Ergebnis wird als neuer Satz von Zeitreihen mit dem Metriknamen, wie von 'record' angegeben, aufgezeichnet.  Für weitere Informationen zu Ausdrücken, siehe die https://prometheus.io/docs/prometheus/latest/querying/basics/[Prometheus-Dokumentation] oder unsere {xref-promql-expressions}[Beispiel-PromQL-Ausdrücke.]

| Labels
| Labels, die vor dem Speichern des Ergebnisses hinzugefügt oder überschrieben werden sollen.
|===
