= 节点驱动程序
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.adoc 
:product-path: rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions.adoc 
endif::[]

节点驱动程序与 https://github.com/docker/docs/blob/vnext-engine/machine/drivers/index.md[Docker Machine驱动程序]相同。节点驱动程序用于配置主机，Rancher 使用这些主机来启动和管理 Kubernetes 集群。默认情况下，Rancher 捆绑了许多节点驱动程序，但您也可以创建并添加自定义节点驱动程序到 Rancher。

在创建节点模板时，只有`Active`节点驱动程序会显示在Rancher UI中。如果有特定的节点驱动程序您不希望向用户显示，您必须停用这些节点驱动程序。

[#_managing_node_drivers]
== 管理节点驱动程序

[NOTE]
.先决条件：
====

要创建、编辑或删除驱动程序，您需要以下权限中的_一个_：

* {xref-global-permissions}[管理员全局权限]
* {xref-global-permissions}#_custom_global_permissions[自定义全局权限]，并分配{xref-global-permissions}[管理节点驱动程序]角色。
====


[#_activating_deactivating_node_drivers]
=== 激活/停用节点驱动程序

默认情况下，Rancher仅激活最受欢迎的云服务提供商的驱动程序，如Amazon EC2、Azure、DigitalOcean、Linode和vSphere。如果您想显示或隐藏任何节点驱动程序，可以更改其状态。

. 在左上角，单击*☰ > 集群管理*。
. 在左侧导航菜单中，点击*驱动程序*。
. 在*节点驱动程序*选项卡上，选择您希望激活或停用的驱动程序，然后点击*⋮ > 激活*或*⋮ > 停用*。

[WARNING]
====

停用节点驱动程序后，您可能会失去对集群的访问权限。

停用节点驱动程序不仅仅影响其在Rancher UI中的可见性。当您停用或删除节点驱动程序时，使用该驱动程序部署的任何节点将变得不可访问。

例如，如果您停用 vSphere 节点驱动程序以在 UI 中隐藏它，并且您有一个使用该驱动程序部署的 vSphere 集群，则集群中的初始节点将失败，整个集群将变得不可访问。尝试删除 vSphere 节点将失败，节点将停留在扩展的 `Removing` 状态中。

在停用节点驱动程序之前，请确保它没有关联的集群。检查驱动程序的相应平台是否列在您的集群中是一种方法：

. 在左上角，单击*☰ > 集群管理*。
. 选择 *集群*。
. 检查表格的 *提供者* 列，以查找您正在停用的节点驱动程序的实例。
====


[#_adding_custom_node_drivers]
=== 添加自定义节点驱动程序

如果您想使用 Rancher 不支持的节点驱动程序，可以添加该提供者的驱动程序，以便开始使用它们创建节点模板，最终为您的 Kubernetes 集群创建节点池。

. 在左上角，单击*☰ > 集群管理*。
. 在左侧导航菜单中，点击*驱动程序*。
. 在 *节点驱动程序* 选项卡上，单击 *添加节点驱动程序*。
. 填写 *添加节点驱动程序* 表单。然后单击 *创建*。

[#_developing_your_own_node_drivers]
=== 开发您自己的节点驱动程序

节点驱动程序是通过 https://github.com/rancher/machine[Rancher Machine] 实现的，这是 https://github.com/docker/machine[Docker Machine] 的一个分支。Docker Machine 不再处于积极开发中。

有关如何开发您自己的节点驱动程序的详细信息，请参阅原始 https://github.com/docker/docs/blob/vnext-engine/machine/overview.md[Docker Machine 文档]。
