= プライベートクラスター
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/gke-private-clusters.adoc 
:product-path: cluster-deployment/hosted-kubernetes/gke/private-clusters.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/index.adoc
endif::[]

GKEでは、 https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept[プライベートクラスター]は、ノードが内部IPアドレスのみを割り当てられ、入出力トラフィックから隔離されたクラスターです。GKEのプライベートクラスターでは、コントロールプレーンエンドポイントを公開アドレスまたはプライベートアドレスとして設定するオプションがあります。これは他のKubernetesプロバイダーとは異なり、プライベートコントロールプレーンエンドポイントを持つクラスターを「プライベートクラスター」と呼ぶ場合でも、ノードへの入出力トラフィックが許可されていることがあります。組織のネットワークおよびセキュリティ要件に応じて、公開コントロールプレーンエンドポイントの有無にかかわらず、プライベートノードを持つクラスターを作成できます。RancherからプロビジョニングされたGKEクラスターは、「クラスターオプション」（「詳細オプションを表示」内）で「プライベートクラスター」を選択することにより、内部IPアドレスのみを持つノードを使用できます。「プライベートエンドポイントを有効にする」を選択することで、コントロールプレーンエンドポイントをプライベートに設定できます。

[#_private_nodes]
== プライベートノード

プライベートクラスターのノードは内部IPアドレスのみを持つため、クラスターエージェントをインストールできず、Rancherはクラスターを完全に管理できません。これはいくつかの方法で克服できます。

[#_cloud_nat]
=== Cloud NAT

[CAUTION]
====

Cloud NATは https://cloud.google.com/nat/pricing[料金が発生します]。
====


組織にとって外部インターネットアクセスの制限が問題でない場合、Googleの https://cloud.google.com/nat/docs/using-nat[Cloud NAT]サービスを使用して、プライベートネットワーク内のノードがインターネットにアクセスできるようにし、Docker Hubから必要なイメージをダウンロードし、Rancher管理サーバーに接続できるようにします。これは最も簡単な解決策です。

[#_private_registry]
=== プライベートレジストリ

[CAUTION]
====

このシナリオは公式にはサポートされていませんが、Cloud NATサービスの利用だけでは十分でない場合のために説明されています。
====


ノードへの入出力トラフィックの制限が要件である場合、エアギャップされたインストール手順に従って、クラスターが配置されるVPC上にプライベートコンテナイメージ{xref-air-gap}[registry]を設定し、クラスターのノードがクラスターエージェントを実行するために必要なイメージにアクセスしてダウンロードできるようにします。コントロールプレーンエンドポイントもプライベートである場合、Rancherは<<_direct_access,直接アクセス>>が必要です。

[#_private_control_plane_endpoint]
== プライベートコントロールプレーンエンドポイント

クラスターに公開エンドポイントがある場合、Rancherはクラスターにアクセスでき、追加の手順は必要ありません。ただし、クラスターに公開エンドポイントがない場合、Rancherがクラスターにアクセスできるように考慮する必要があります。

[#_cloud_nat_1]
=== Cloud NAT

[CAUTION]
====

Cloud NATは https://cloud.google.com/nat/pricing[料金が発生します]。
====


上記の通り、ノードへのインターネットアクセスを制限することが問題でない場合、Googleの https://cloud.google.com/nat/docs/using-nat[Cloud NAT]サービスを使用してノードがインターネットにアクセスできるようにすることができます。クラスターのプロビジョニング中、Rancherはクラスターで実行するための登録コマンドを提供します。新しいクラスターのための https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl[kubeconfig]をダウンロードし、クラスターで提供されたkubectlコマンドを実行してください。このコマンドを実行するためにクラスターにアクセスするには、一時的なノードを作成するか、VPC内の既存のノードを使用するか、クラスターのノードの1つにSSHでログインするか、SSHトンネルを作成することができます。

[#_direct_access]
=== 直接アクセス

Rancherサーバーがクラスターのコントロールプレーンと同じVPCで実行されている場合、コントロールプレーンのプライベートエンドポイントに直接アクセスできます。クラスターのノードは、上記のようにイメージをダウンロードするために<<_private_registry,プライベートレジストリ>>にアクセスする必要があります。

また、Googleの https://cloud.google.com/network-connectivity/docs/vpn/concepts/overview[Cloud VPN]や https://cloud.google.com/network-connectivity/docs/interconnect[Cloud Interconnect VLAN]などのサービスを使用して、組織のネットワークとGoogle VPC間の接続を容易にすることができます。
