= 集群工具用于日志记录、监控和可观测性
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/rancher-cluster-tools.adoc 
:product-path: observability/rancher-cluster-tools.adoc
ifeval::["{build-type}" != "community"]
:xref-istio: xref:observability/istio/istio.adoc
:xref-monitoring-and-dashboards: xref:observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:xref-logging: xref:observability/logging/logging.adoc
:xref-compliance-scans-howto: xref:security/compliance-scans/how-to.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio: xref:integrations-in-rancher/istio/index.adoc
:xref-monitoring-and-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/index.adoc
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
:xref-compliance-scans-howto: xref:how-to-guides/advanced-user-guides/compliance-scan-guides/index.adoc
endif::[]

Rancher包含多种不包含在Kubernetes中的工具，以协助您的DevOps操作。Rancher可以与外部服务集成，以帮助您的集群更高效地运行。工具分为以下几类：

[#_logging]
== 日志记录

日志记录很有帮助，因为它允许您：

* 捕获和分析集群的状态
* 查找环境中的趋势
* 将日志保存到集群外的安全位置
* 及时获知诸如容器崩溃、Pod 被驱逐或节点失效等事件
* 更轻松地调试和排查问题

Rancher 可以与 Elasticsearch、Splunk、Kafka、Syslog 和 Fluentd 集成。

有关更多信息，请参见日志记录文档 {xref-logging}[在这里。]

[#_monitoring_and_alerts]
== 监控和警报

使用Rancher，您可以通过与 https://prometheus.io/[Prometheus]的集成，监控集群节点、Kubernetes组件和软件部署的状态和进程。Prometheus是一个领先的开源监控解决方案。

启用监控后，您可以设置警报和通知器，以提供接收它们的机制。

通知器是通知您警报事件的服务。您可以配置通知器，将警报通知发送给最适合采取纠正措施的工作人员。通知可以通过 Slack、电子邮件、PagerDuty、微信和 Webhook 发送。

警报是触发这些通知的规则。在您能够接收警报之前，必须在 Rancher 中配置一个或多个通知器。警报的范围可以设置在集群或项目级别。

有关更多信息，请参见监控文档 {xref-monitoring-and-dashboards}[在这里。]

[#_istio]
== Istio

https://istio.io/[Istio] 是一个开源工具，使 DevOps 团队更容易观察、控制、排查和保护复杂微服务网络中的流量。

Rancher与Istio的集成在Rancher v2.5中得到了改善。

有关详细信息，请参见Istio文档 {xref-istio}[在这里。]

[#_compliance_scans]
== 合规扫描

Rancher可以运行安全扫描，以检查Kubernetes是否按照大多数公认的Kubernetes安全基准（如STIG）定义的安全最佳实践进行部署。

有关详细信息，请参见合规扫描文档 {xref-compliance-scans-howto}[在这里。]
