= 集群访问

本节介绍可以用来访问 Rancher 管理的集群的工具。

有关如何授予用户访问集群的权限的信息，请参阅xref:add-users-to-clusters.adoc[将用户添加到集群]部分。

有关 RBAC 的更多信息，请参阅xref:../../../rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc[本节]。

有关如何设置认证的信息，请参阅xref:../../../rancher-admin/users/authn-and-authz/authn-and-authz.adoc[本节]。

== Rancher UI 中的集群

我们提供了多种通过 Rancher UI 查看和管理集群的方法。

=== 集群页面

从 *☰* 菜单访问**集群**页面：

. 单击 *☰*。
. 选择**集群管理**。

你还可以通过单击 Rancher UI **主页**集群表格上方的**管理**按钮来访问**集群**页面。

在**集群**页面上，选择每行末尾的 *⁝* 以查看包含以下选项的子菜单：

* xref:use-kubectl-and-kubeconfig.adoc[Kubectl Shell]
* 下载 KubeConfig
* 将 KubeConfig 复制到剪切板
* 编辑配置
* 查看 YAML
* 下载 YAML

== 集群仪表板

在**集群**页面上，选择每行末尾的**浏览**按钮查看该集群的**集群仪表板**。你还可以通过单击表中集群的名称，然后单击**集群**页面上的**浏览**按钮来查看仪表板。

也可以通过单击集群名称从 Rancher UI **主页**访问**集群仪表板**。

你还可以从顶部导航栏中的 *☰* 访问**集群仪表板**：

. 单击 *☰*。
. 从**浏览集群**菜单中选择集群的名称。

**集群仪表板**列出了集群相关的信息，例如节点数量、内存使用情况、事件和资源。

== kubectl

你可以使用 Kubernetes 命令行工具 https://kubernetes.io/docs/reference/kubectl/overview/[kubectl]，来管理你的集群。使用 kubectl 有两种选择：

* *Rancher kubectl shell*：通过启动 Rancher UI 中可用的 kubectl shell 与集群交互。此选项不需要你进行任何配置操作。有关详细信息，请参阅xref:use-kubectl-and-kubeconfig.adoc[使用 kubectl Shell 访问集群]。
* *终端远程连接*：你也可以通过在本地桌面上安装 https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl]，然后将集群的 kubeconfig 文件复制到本地 `~/.kube/config` 目录来与集群交互。有关更多信息，请参阅xref:use-kubectl-and-kubeconfig.adoc[使用 kubectl 和 kubeconfig 文件访问集群]。

== Rancher CLI

你可以下载 Rancher 自己的命令行工具 xref:../../../rancher-admin/cli/rancher-cli.adoc[Rancher CLI] 来控制你的集群。这个 CLI 工具可以直接与不同的集群和项目进行交互，或者向它们传递 `kubectl` 命令。

== Rancher API

最后，你可以通过 Rancher API 与集群进行交互。在使用 API 之前，你必须先获取 xref:../../../rancher-admin/users/settings/api-keys.adoc[API 密钥]。要查看 API 对象的不同资源字段和操作，请打开 API UI（API UI 可以通过单击 Rancher UI 对象的**在 API 中查看**访问）。
