= Installing {rancher-product-name} behind an HTTP Proxy
:page-languages: [en, zh]
:revdate: 2025-03-12
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/index.adoc 
:product-path: installation-and-upgrade/other-installation-methods/http-proxy/http-proxy.adoc

In a lot of enterprise environments, servers or VMs running on premise do not have direct Internet access, but must connect to external services through a HTTP(S) proxy for security reasons. This tutorial shows step by step how to set up a highly available Rancher installation in such an environment.

Alternatively, it is also possible to set up Rancher completely air-gapped without any Internet access. This process is described in detail in the xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc[Rancher docs].

== Installation Outline

. xref:installation-and-upgrade/other-installation-methods/http-proxy/set-up-infrastructure.adoc[Set up infrastructure]
. xref:installation-and-upgrade/other-installation-methods/http-proxy/install-kubernetes.adoc[Set up a Kubernetes cluster]
. xref:installation-and-upgrade/other-installation-methods/http-proxy/install-rancher.adoc[Install Rancher]
