= Opções do Helm Chart
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/helm-chart-options.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/helm-chart-options.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-configure-alertmanager: xref:observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-configure-alertmanager: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
endif::[]

[#_configuring_resource_limits_and_requests]
== Configuração de limites e solicitações de recursos

As solicitações e limites de recursos podem ser configurados ao instalar `rancher-monitoring`.

Os valores padrão estão no https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/values.yaml[values.yaml] no `rancher-monitoring` Helm chart.

Os valores padrão na tabela abaixo são os limites e solicitações de recursos mínimos exigidos.

|===
| Nome do Recurso | Limite de Memória | CPU Limit | Requisição de Memória | Requisição de CPU

| alertmanager
| 500Mi
| 1000m
| 100Mi
| 100m

| grafana
| 200Mi
| 200m
| 100Mi
| 100m

| subchart kube-state-metrics
| 200Mi
| 100m
| 130Mi
| 100m

| subchart prometheus-node-exporter
| 50Mi
| 200m
| 30Mi
| 100m

| prometheusOperator
| 500Mi
| 200m
| 100Mi
| 100m

| prometheus
| 2500Mi
| 1000m
| 1750Mi
| 750m

| *Total*
| *3950Mi*
| *2700m*
| *2210Mi*
| *1250m*
|===

É recomendado um armazenamento de pelo menos 50Gi.

[#_trusted_ca_for_notifiers]
== CA confiável para Notificadores

Se você precisar adicionar uma CA confiável ao seu notificador, siga estas etapas:

. Crie o namespace `cattle-monitoring-system`.
. Adicione seu segredo de CA confiável ao namespace `cattle-monitoring-system`.
. Implante ou faça upgrade do `rancher-monitoring` Helm chart. Nas opções do Helm chart, faça referência ao segredo em menu:Alerting[Segredos Adicionais].

*Resultado:* O recurso customizado do Alertmanager terá acesso à sua CA confiável.

[#_additional_scrape_configurations]
== Configurações de Coleta Adicional

Se a configuração de coleta que você deseja não puder ser especificada via um ServiceMonitor ou PodMonitor no momento, você pode fornecer um `additionalScrapeConfigSecret` ao implantar ou fazer upgrade de `rancher-monitoring`.

Uma seção https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config[scrape_config] especifica um conjunto de alvos e parâmetros descrevendo como coletá-los. No caso geral, uma configuração de coleta especifica um único trabalho.

Um exemplo de onde isso pode ser usado é com Istio. Para mais informações, consulte {xref-selectors-and-scrape-configurations}[esta seção.]

[#_configuring_applications_packaged_within_monitoring_v2]
== Configurando Aplicações Empacotadas dentro do Monitoring v2

Implantamos kube-state-metrics e node-exporter com o monitoring v2. Os exporters de nó são implantados como DaemonSets. Cada uma dessas entidades é implantada como subchart através do Helm chart do monitoring v2, values.yaml.

Também implantamos o Grafana, que não é gerenciado pelo Prometheus.

Muitos valores não estão expostos no chart de nível superior. No entanto, você pode adicionar valores ao chart de nível superior para substituir valores que existem nos subcharts.

[#_increase_the_replicas_of_alertmanager]
=== Aumente as Réplicas do Alertmanager

Como parte das opções de implantação do chart, você pode optar por aumentar o número de réplicas do Alertmanager implantado em seu cluster. As réplicas podem ser gerenciadas usando o mesmo Secret de Configuração do Alertmanager subjacente. Para mais informações sobre o Secret de Configuração do Alertmanager, consulte {xref-configure-alertmanager}#_multiple_alertmanager_replicas[esta seção.]

[#_configuring_the_namespace_for_a_persistent_grafana_dashboard]
=== Configurando o Namespace para um Dashboard Persistente do Grafana

Para especificar que você gostaria que o Grafana monitorasse ConfigMaps em todos os namespaces, defina este valor no gráfico Helm `rancher-monitoring`:

----
grafana.sidecar.dashboards.searchNamespace=ALL
----

Observe que os papéis RBAC expostos pelo gráfico de Monitoramento para adicionar Painéis do Grafana ainda estão restritos a conceder permissões para que os usuários adicionem painéis no namespace definido em `grafana.dashboards.namespace`, que por padrão é `cattle-dashboards`.
