= Configuração de Rota
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/routes.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/routes.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
endif::[]

A configuração de rota é a seção do recurso personalizado do Alertmanager que controla como os alertas disparados pelo Prometheus são agrupados e filtrados antes de chegarem ao receptor.

Quando uma Rota é alterada, o Operador Prometheus regenera o recurso personalizado do Alertmanager para refletir as mudanças.

Para mais informações sobre como configurar rotas, consulte a https://www.prometheus.io/docs/alerting/latest/configuration/#route[documentação oficial do Alertmanager.]

[NOTE]
====

Esta seção assume familiaridade com o funcionamento conjunto dos componentes de monitoramento. Para mais informações, consulte {xref-how-monitoring-works}[esta seção.]
====


[#_route_restrictions]
== Restrições de Rota

O Alertmanager faz proxy dos alertas do Prometheus com base em seus receptores e em uma árvore de roteamento que filtra alertas para certos receptores com base em rótulos.

Os drivers de alerta fazem proxy dos alertas do Alertmanager para receptores não nativos, como Microsoft Teams e SMS.

Na interface do Rancher para configurar rotas e receptores, você pode configurar árvores de roteamento com uma raiz e, em seguida, uma profundidade de mais um nível, para uma árvore com profundidade de dois. Mas se você usar uma `continue` rota ao configurar o Alertmanager diretamente, pode tornar a árvore mais profunda.

Cada receptor é para um ou mais provedores de notificação. Portanto, se você souber que todo alerta para o Slack também deve ir para o PagerDuty, pode configurar ambos no mesmo receptor.

[#_route_configuration]
== Configuração de Rota

[#_note_on_labels_and_annotations]
=== Nota sobre Rótulos e Anotações

Rótulos devem ser usados para informações de identificação que podem afetar o roteamento de notificações. Informações de identificação sobre o alerta podem consistir em um nome de contêiner ou o nome da equipe que deve ser notificada.

Anotações devem ser usadas para informações que não afetam quem recebe o alerta, como uma URL de runbook ou mensagem de erro.

[#_receiver]
=== Receptor

A rota precisa se referir a um {xref-receivers}[receptor] que já foi configurado.

[#_grouping]
=== Agrupamento

|===
| Campo | Default | Descrição

| Agrupar por
| N/a
| Lista de rótulos para agrupar. Os rótulos devem ser exclusivos. O rótulo especial "..." (agrupar por todos os rótulos possíveis), se fornecido, deve ser o único elemento na lista. Aceita uma lista de strings. Veja a https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#route[documentação upstream] para mais detalhes.

| Espera de grupo
| 30s
| Quanto tempo esperar para acumular alertas do mesmo grupo antes do envio inicial.

| Intervalo de grupo
| 5m
| Quanto tempo esperar antes de enviar um alerta que foi adicionado a um grupo de alertas para o qual uma notificação inicial já foi enviada.

| Intervalo de repetição
| 4h
| Quanto tempo esperar antes de reenviar um alerta que já foi enviado.
|===

[#_matching]
=== Correspondência

O campo *Correspondência* refere-se a um conjunto de correspondências de igualdade usadas para identificar quais alertas enviar para uma determinada Rota com base nos rótulos definidos nesse alerta. Quando você adiciona pares chave-valor na interface do Rancher, eles correspondem ao YAML neste formato:

[,yaml]
----
match:
  [ <labelname>: <labelvalue>, ... ]
----

O campo *Expressão Regular de Correspondência* refere-se a um conjunto de correspondências regex usadas para identificar quais alertas enviar para uma determinada Rota com base nos rótulos definidos nesse alerta. Quando você adiciona pares chave-valor na interface do Rancher, eles correspondem ao YAML neste formato:

[,yaml]
----
match_re:
  [ <labelname>: <regex>, ... ]
----
