= Configuração do ServiceMonitor e PodMonitor
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

ServiceMonitors e PodMonitors são ambos pseudo-CRDs que mapeiam a configuração do recurso personalizado do Prometheus.

Esses objetos de configuração especificam de forma declarativa os endpoints dos quais o Prometheus irá coletar métricas.

ServiceMonitors são mais comumente usados do que PodMonitors, e os recomendamos para a maioria dos casos de uso.

[NOTE]
====

Esta seção assume familiaridade com o funcionamento conjunto dos componentes de monitoramento. Para mais informações sobre o Alertmanager, consulte {xref-how-monitoring-works}[esta seção.]
====


[#_servicemonitors]
== ServiceMonitors

Este pseudo-CRD mapeia para uma seção da configuração do recurso personalizado do Prometheus. Ele especifica de forma declarativa como grupos de serviços do Kubernetes devem ser monitorados.

Quando um ServiceMonitor é criado, o Operador Prometheus atualiza a configuração do Prometheus para incluir a configuração do ServiceMonitor. Então, o Prometheus começa a coletar métricas do endpoint definido no ServiceMonitor.

Quaisquer Serviços em seu cluster que correspondam aos rótulos localizados no campo `selector` do ServiceMonitor serão monitorados com base no `endpoints` especificado no ServiceMonitor. Para mais informações sobre quais campos podem ser especificados, consulte o https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#servicemonitor[spec] fornecido pelo Operador Prometheus.

Para mais informações sobre como os ServiceMonitors funcionam, consulte a https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/running-exporters.md[documentação do Operador Prometheus.]

[#_podmonitors]
== PodMonitors

Este pseudo-CRD mapeia para uma seção da configuração do recurso personalizado do Prometheus. Ele especifica de forma declarativa como grupos de pods devem ser monitorados.

Quando um PodMonitor é criado, o Operador Prometheus atualiza a configuração do Prometheus para incluir a configuração do PodMonitor. Então, o Prometheus começa a coletar métricas do endpoint definido no PodMonitor.

Quaisquer Pods em seu cluster que correspondam aos rótulos localizados no campo `selector` do PodMonitor serão monitorados com base no `podMetricsEndpoints` especificado no PodMonitor. Para mais informações sobre quais campos podem ser especificados, consulte o https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#podmonitor[spec] fornecido pelo Operador Prometheus.
