= Agregação de RoleTemplate
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-27
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/enable-experimental-features/role-template-aggregation.adoc 
:product-path: rancher-admin/experimental-features/role-template-aggregation.adoc

[CAUTION]
====
A agregação de RoleTemplate é um recurso experimental na v2.13 que altera a arquitetura RBAC utilizada para RoleTemplates, ClusterRoleTemplateBindings e ProjectRoleTemplateBindings. **Não é suportado para ambientes de produção**. Alterações incompatíveis podem ocorrer entre a v2.13 e a v2.14.
====

A agregação de RoleTemplate implementa RoleTemplates, ClusterRoleTemplateBindings e ProjectRoleTemplateBindings usando o recurso do Kubernetes https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles[ClusterRoles Agregados]. A nova arquitetura resulta em uma redução líquida nos objetos RBAC (Roles, RoleBindings, ClusterRoles e ClusterRoleBindings) tanto no cluster Rancher quanto nos clusters downstream.

Para mais informações sobre como o recurso pode melhorar a escalabilidade e o desempenho, consulte o https://www.suse.com/c/rancher_blog/fewer-bindings-more-power-ranchers-rbac-boost-for-enhanced-performance-and-scalability/[post do blog da Rancher].

|===
| Chave da Variável de Ambiente | Valor Padrão | Descrição

| `aggregated-roletemplates`
| `false`
| [Beta] Fazer com que RoleTemplates utilizem agregação para os roles RBAC gerados.
|===

O valor deste sinalizador de recurso é bloqueado na instalação, que aparece na interface como um símbolo de bloqueio ao lado do sinalizador de recurso. Isso significa que o recurso só pode ser configurado na primeira instalação do Rancher. Depois disso, tentativas de modificar o valor são negadas.
