= Kurzanleitung für Workload mit Ingress
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-workloads/workload-ingress.adoc 
:product-path: installation-and-upgrade/quick-start/deploy-workloads/workload-ingress.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-workloads-and-pods: xref:cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-workloads-and-pods: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc
endif::[]

[#_prerequisite]
== Voraussetzung

Sie haben einen laufenden Cluster mit mindestens 1 Knoten.

[#_1_deploying_a_workload]
== 1. Bereitstellen eines Workloads

Sie sind bereit, Ihren ersten Kubernetes https://kubernetes.io/docs/concepts/workloads/[Workload] zu erstellen. Ein Workload ist ein Objekt, das Pods sowie andere Dateien und Informationen enthält, die zum Bereitstellen Ihrer Anwendung erforderlich sind.

Für diesen Workload werden Sie die Anwendung Rancher Hello-World bereitstellen.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, das Sie erstellt haben, und klicken Sie auf *Erforschen*.
. Klicken Sie auf *Arbeitslast*.
. Klicken Sie auf *Erstellen*.
. Klicken Sie auf *Implementierung*.
. Geben Sie einen *Namen* für Ihren Workload ein.
. Geben Sie im Feld *Container-Image* `rancher/hello-world` ein. Groß-/Kleinschreibung wird in diesem Feld berücksichtigt.
. Klicken Sie auf *Port hinzufügen* und `Cluster IP` für den `Service Type` und geben Sie `80` im Feld *Privater Containerport* ein. Sie können das `Name` leer lassen oder einen beliebigen Namen angeben, den Sie wünschen. Das Hinzufügen eines Ports ermöglicht den Zugriff auf die Anwendung innerhalb und außerhalb des Clusters. Für weitere Informationen siehe {xref-workloads-and-pods}#_services[Services].
. Klicken Sie auf *Erstellen*.

*Ergebnis:*

* Ihr Workload ist bereitgestellt. Dieser Prozess kann einige Minuten dauern.
* Wenn Ihr Workload die Bereitstellung abgeschlossen hat, wird ihm der Status *Aktiv* zugewiesen. Sie können diesen Status auf der Seite *Workloads* des Projekts einsehen.

[#_2_expose_the_application_via_an_ingress]
== 2. Die Anwendung über ein Ingress freigeben

Jetzt, da die Anwendung läuft, muss sie freigegeben werden, damit andere Dienste eine Verbindung herstellen können.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, das Sie erstellt haben, und klicken Sie auf *Erforschen*.
. Klicken Sie auf menu:Service Discovery[Ingresses].
. Klicken Sie auf *Erstellen.*
. Stellen Sie beim Auswählen von *Namespace* sicher, dass es dasselbe ist wie das, das Sie bei der Erstellung Ihrer Bereitstellung verwendet haben. Andernfalls wird Ihre Bereitstellung nicht verfügbar sein, wenn Sie versuchen, *Zielservice* auszuwählen, wie in Schritt 8 unten.
. Geben Sie einen *Name* ein, wie zum Beispiel *hallo*.
. Geben Sie Ihren *Pfad* an, wie zum Beispiel `/hello`.
. Im Feld *Zielservice* öffnen Sie die Liste und wählen den Namen aus, den Sie für Ihren Dienst festgelegt haben.
. Im Feld *Port* öffnen Sie die Liste und wählen `80` aus.
. Klicken Sie auf *Erstellen* unten rechts.

*Ergebnis:* Der Anwendung wird eine `sslip.io` Adresse zugewiesen und freigegeben. Es kann ein bis zwei Minuten dauern, bis die Daten angezeigt werden.

[#_view_your_application]
== Sehen Sie sich Ihre Anwendung an

Gehen Sie zur Seite *Bereitstellungen*, suchen Sie die Spalte *Endpunkte* für Ihre Bereitstellung und klicken Sie auf einen Endpunkt. Die verfügbaren Endpunkte hängen davon ab, wie Sie den Port konfiguriert haben, den Sie zu Ihrer Bereitstellung hinzugefügt haben. Für Endpunkte, bei denen Sie keinen zufällig zugewiesenen Port sehen, fügen Sie den Pfad hinzu, den Sie beim Erstellen des Ingress angegeben haben, zur IP-Adresse hinzu. Wenn Ihr Endpunkt beispielsweise wie `xxx.xxx.xxx.xxx` oder `https://xxx.xxx.xxx.xxx` aussieht, ändern Sie ihn in `xxx.xxx.xxx.xxx/hello` oder `https://xxx.xxx.xxx.xxx/hello`.

Ihre Anwendung wird in einem separaten Fenster geöffnet.

[#_finished]
=== Abgeschlossen

Herzlichen Glückwunsch! Sie haben erfolgreich einen Workload bereitgestellt, der über ein Ingress freigegeben wurde.

[#_whats_next]
=== Was kommt als Nächstes?

Wenn Sie mit Ihrer Sandbox fertig sind, zerstören Sie den Rancher-Server und Ihren Cluster.
