= ホステッドKubernetesプロバイダーからのクラスターのセットアップ
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/index.adoc 
:product-path: cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
ifeval::["{build-type}" != "community"]
:xref-deploy-gke: xref:cluster-deployment/hosted-kubernetes/gke/gke.adoc
:xref-deploy-eks: xref:cluster-deployment/hosted-kubernetes/eks/eks.adoc
:xref-deploy-aks: xref:cluster-deployment/hosted-kubernetes/aks/aks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-deploy-gke: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/gke.adoc
:xref-deploy-eks: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks.adoc
:xref-deploy-aks: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.adoc
endif::[]

ifeval::["{build-type}" != "srfa"]
このシナリオでは、RancherはKubernetesをプロビジョニングしません。なぜなら、Google Kubernetes Engine (GKE)、Amazon Elastic Container Service for Kubernetes、またはAzure Kubernetes Serviceなどのプロバイダーによってインストールされるからです。

Google GKEなどのKubernetesプロバイダーを使用する場合、RancherはそのクラウドAPIと統合され、Rancher UIからホステッドクラスターのロールベースのアクセス制御を作成および管理できます。

このユースケースでは、RancherはプロバイダーのAPIを使用してホステッドプロバイダーにリクエストを送信します。その後、プロバイダーがクラスターをプロビジョニングし、ホストします。クラスターの構築が完了すると、Rancher UIから、オンプレミスまたはインフラストラクチャプロバイダーにホストされているプロビジョニング済みのクラスターとともに管理できます。

Rancherは以下のKubernetesプロバイダーをサポートしています：

* https://cloud.google.com/kubernetes-engine/[Google GKE (Google Kubernetes Engine)]
* https://aws.amazon.com/eks/[Amazon EKS (Amazon Elastic Container Service for Kubernetes)]
* https://azure.microsoft.com/en-us/services/kubernetes-service/[Microsoft AKS (Azure Kubernetes Service)]

endif::[]
ifeval::["{build-type}" == "srfa"]
このシナリオでは、RancherはKubernetesをプロビジョニングしません。なぜなら、Amazon Elastic Container Service for Kubernetesによってインストールされるからです。

Kubernetesプロバイダーを使用する場合、RancherはそのクラウドAPIと統合され、Rancher UIからホステッドクラスターのロールベースのアクセス制御を作成および管理できます。

このユースケースでは、RancherはプロバイダーのAPIを使用してホステッドプロバイダーにリクエストを送信します。その後、プロバイダーがクラスターをプロビジョニングし、ホストします。クラスターの構築が完了すると、Rancher UIから、オンプレミスまたはインフラストラクチャプロバイダーにホストされているプロビジョニング済みのクラスターとともに管理できます。

RancherはAmazon EKSプロバイダーをサポートしています：

* https://aws.amazon.com/eks/[Amazon EKS (Amazon Elastic Container Service for Kubernetes)]
endif::[]

[#_hosted_kubernetes_provider_authentication]
== ホステッドKubernetesプロバイダー認証

ifeval::["{build-type}" != "srfa"]
プロバイダーによってホストされるクラスターを作成するためにRancherを使用する際、認証情報の入力を求められます。この情報は、プロバイダーのAPIにアクセスするために必要です。この情報を取得する方法についての詳細は、以下の手順を参照してください：

* {xref-deploy-gke}[GKEクラスターの作成]
* {xref-deploy-eks}[EKSクラスターの作成]
* {xref-deploy-aks}[AKSクラスターの作成]
endif::[]
ifeval::["{build-type}" == "srfa"]
プロバイダーによってホストされるクラスターを作成するためにRancherを使用する際、認証情報の入力を求められます。この情報は、プロバイダーのAPIにアクセスするために必要です。この情報を取得する方法についての詳細は、以下の手順を参照してください：

* {xref-deploy-eks}[EKSクラスターの作成]
endif::[]
