= {elemental-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/elemental/index.adoc 
:product-path: integrations/elemental.adoc

Elemental permite la gestión de hosts nativos de nube. Elemental te permite incorporar cualquier máquina en cualquier ubicación, ya sea en un centro de datos o en el edge, e integrarlas sin problemas en Kubernetes mientras gestionas tus flujos de trabajo (por ejemplo, actualizaciones del sistema operativo).

[#__elemental_product_name_with_rancher]
== {elemental-product-name} con Rancher

Elemental en Rancher:

* Es nativo de Kubernetes, lo que te permite gestionar el sistema operativo a través de Elemental en clústeres de Kubernetes.
* Es no disruptivo desde una perspectiva operativa de Kubernetes.
* Es declarativo y amigable con GitOps.
* Permite flujos basados en imágenes OCI, que son confiables, deterministas y predecibles.
* Funciona a gran escala. Permite la gestión del sistema operativo a nivel de Fleet.

[#_when_should_i_use_elemental_product_name]
=== ¿Cuándo debo usar {elemental-product-name}?

* Elemental permite la gestión de sistemas operativos nativos de nube desde el gestor de Rancher. Funciona con cualquier sistema operativo (por ejemplo, SLE Micro vanilla).
* Elemental permite la gestión nativa de nube para máquinas en centros de datos y en el edge.
* Elemental es flexible y permite a los equipos de plataforma realizar todo tipo de flujos de trabajo a través de su Fleet de máquinas.

[#__elemental_product_name_with_rancher_prime]
== {elemental-product-name} con {rancher-prime}

* Ya está profundamente integrado como extensión de GUI en Rancher.
* Extiende la historia de Rancher al sistema operativo. Funcionando perfectamente con SLE Micro para Rancher hoy.
