= Kubernetes en el escritorio con Rancher Desktop
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/rancher-desktop.adoc 
:product-path: integrations/rancher-desktop.adoc

Rancher Desktop agrupa herramientas esenciales para desarrollar y probar aplicaciones nativas de nube desde tu escritorio.

Si trabajas desde tu máquina local en aplicaciones destinadas a entornos en la nube, normalmente necesitas mucha preparación. Necesitas seleccionar un tiempo de ejecución de contenedor, instalar Kubernetes y utilidades populares, y posiblemente configurar una máquina virtual. Instalar componentes de forma individual y hacer que funcionen juntos puede ser un proceso que consume mucho tiempo.

Para reducir la complejidad, Rancher Desktop ofrece a los equipos las siguientes características clave:

* Instalación simple y fácil en sistemas operativos macOS, Linux y Windows.
* K3s, una distribución de Kubernetes lista para usar y ligera.
* La capacidad de cambiar fácilmente entre versiones de Kubernetes.
* Un panel de control de clúster basado en GUI impulsado por Rancher para explorar tu clúster local.
* Libertad para elegir tu motor de contenedores: dockerd (moby) o containerd.
* Configuraciones de preferencia para configurar la aplicación según tus necesidades.
* Herramientas agrupadas necesarias para tu contenedor, para el desarrollo basado en Kubernetes y para flujos de trabajo de operación.
* Actualizaciones periódicas para mantener las herramientas agrupadas actualizadas.
* Integración con herramientas/IDEs populares, incluyendo VS Code y Skaffold.
* Control de acceso a imágenes y registros.
* Soporte para extensiones de Docker.

Visita el https://rancherdesktop.io[sitio web de Rancher Desktop] y lee la https://docs.rancherdesktop.io/[documentación] para aprender más.

Para instalar Rancher Desktop en tu máquina, consulta la https://docs.rancherdesktop.io/getting-started/installation[guía de instalación].

[#_trying_rancher_on_rancher_desktop]
== Probando Rancher en Rancher Desktop

Rancher Desktop ofrece la configuración y las herramientas que necesitas para probar fácilmente aplicaciones en contenedores y basadas en Helm. Puedes comenzar con la plataforma de gestión de Kubernetes de Rancher utilizando Rancher Desktop, siguiendo estas https://docs.rancherdesktop.io/how-to-guides/rancher-on-rancher-desktop[instrucciones].
