= {stackstate-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/suse-observability/index.adoc 
:product-path: integrations/suse-observability.adoc

SUSE Observability es una solución de observabilidad completa que proporciona información detallada sobre la salud de los clústeres y nodos, así como de las cargas de trabajo que se ejecutan en ellos. Diseñada para ofrecer una visibilidad clara de todo el entorno de Kubernetes, el enfoque de pila completa de SUSE Observability permite explorar sin problemas todo, desde servicios hasta infraestructura, dentro de una única plataforma, eliminando la necesidad de múltiples herramientas de observabilidad.

SUSE Observability recopila y correlaciona datos de forma segura, ofreciendo información útil sobre problemas existentes y potenciales en el clúster. Esto ayuda a abordar rápidamente los problemas actuales y a tomar medidas preventivas contra futuros desafíos.

Los paneles intuitivos destacan las áreas problemáticas y ofrecen pasos de remediación, guiando desde la identificación del problema hasta el análisis de la causa raíz y, en última instancia, hasta la resolución, en el menor tiempo posible.

Para más información y para configurar SUSE Observability en un clúster de Kubernetes gestionado por SUSE Rancher, consulte la https://documentation.suse.com/en-us/cloudnative/suse-observability/[documentación].
