= Ingress NGINX 退役指南
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-25
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/guide-to-ingress-nginx-retirement.adoc 
:product-path: cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/guide-to-ingress-retirement.adoc
:description: Ingress NGINX 退役指南
ifeval::["{build-type}" != "community"]
:url-storage-longhorn-ingress-traefik: https://documentation.suse.com/cloudnative/storage/1.11/en/longhorn-system/system-access/longhorn-ingress-traefik.html
:url-continuous-delivery-webhook: https://documentation.suse.com/cloudnative/continuous-delivery/latest/en/how-tos-for-users/webhook.html
:xref-rancher-on-amazon-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc#_5_install_an_ingress
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc#_5_install_an_ingress
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc#_7_install_an_ingress
endif::[]
ifeval::["{build-type}" == "community"]
:url-storage-longhorn-ingress-traefik: https://longhorn.io/docs/1.11.1/deploy/accessing-the-ui/longhorn-ingress-traefik/#additional-steps-for-aws-eks-kubernetes-clusters
:url-continuous-delivery-webhook: https://fleet.rancher.io/0.15/how-tos-for-users/webhook#_1_configure_the_webhook_service
:xref-rancher-on-amazon-eks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks.adoc#_5_install_an_ingress
:xref-rancher-on-aks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-aks.adoc#_5_install_an_ingress
:xref-rancher-on-gke: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke.adoc#_7_install_an_ingress
endif::[]

Kubernetes SIG 网络和安全响应委员会宣布了 https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/[Ingress NGINX 项目的退役]。上游的最佳努力维护，以及所有相关的上游发布、Bug 修复或安全更新于2026年3月结束。

为了支持用户在此过渡期间，

ifeval::["{build-type}" != "community"]
SUSE 提供了延长的支持时间表和清晰的迁移路径到 Traefik。
endif::[]
ifeval::["{build-type}" == "community"]
Rancher 提供了清晰的迁移路径到 Traefik。
endif::[]

本指南集中提供了根据您的特定部署场景进行操作的信息。

[#_support_and_timelines]
== 支持与时间表

ifeval::["{build-type}" != "community"]
对于无法立即迁移的组织，{rancher-product-name} LTS 为 RKE2 版本 1.35 提供了延长支持。

[IMPORTANT]
.Ingress NGINX 的延长支持
====
{rancher-product-name} LTS 将为 Ingress NGINX 组件在 2027 年 12 月前提供关键和重要的常见漏洞（CVE）补丁。在此期间不会添加新功能。
====
endif::[]

ifeval::["{build-type}" == "community"]
Rancher 和 RKE2 的生命周期与上游退役计划保持一致。

[IMPORTANT]
====
2026年3月后，上游的 Ingress NGINX 镜像将不再接收更新。在此日期之后构建的任何图像仅限于商业客户。用户必须在截止日期之前迁移到 Traefik 或其他受支持的 Ingress 控制器，以确保持续的安全性和兼容性。
====
endif::[]

[#_migration_paths_by_environment]
== 按环境划分的迁移路径

ifeval::["{build-type}" != "community"]
对于准备迁移的组织，SUSE 提供了通往 Traefik 的支持路径。
endif::[]
ifeval::["{build-type}" == "community"]
Rancher 和 RKE2 的生命周期与上游退役计划保持一致。
endif::[]

Traefik 包含一个兼容层，可以解释许多现有的 Ingress NGINX 注释。在下面识别您的集群环境，以找到正确的迁移方法。

[#_standalone_rke2_clusters]
=== 独立的 RKE2 集群

对于当前使用 Ingress NGINX 的独立或导入的 RKE2 集群，请遵循官方 https://support.scc.suse.com/s/kb/Migrating-from-Ingress-NGINX-to-Traefik-in-a-standalone-RKE2-cluster?language=en_US[独立 RKE2 集群的迁移指南]。

迁移过程涉及四个阶段的策略：

. *双Ingress控制器设置：*在Ingress NGINX旁边启用Traefik，使用临时的、无冲突的端口。
. *并行迁移和验证：*复制Ingress资源并测试Traefik对现有注释的处理。
. *最终切换：*去除Ingress NGINX并配置Traefik使用标准端口。
. *清理：*删除遗留的Ingress对象。

[#_rancher_server_on_rke2_local_clusters]
=== RKE2上的Rancher服务器（本地群集）

在迁移Rancher本地集群时，Rancher Ingress资源需要特定处理以防止锁定。遵循特定的 https://support.scc.suse.com/s/kb/How-to-migrate-the-Rancher-Ingress-to-Traefik-in-an-RKE2-cluster?language=en_US[在RKE2集群中将Rancher Ingress迁移到Traefik的指南]。本指南基于独立迁移阶段，但包括针对Rancher管理服务器量身定制的步骤。

[#_downstream_rke2_clusters_provisioned_by_rancher]
=== 下游RKE2集群（由Rancher提供）

对于由 {rancher-product-name} 提供和管理的 RKE2 集群，迁移选项直接集成在用户界面中。

[NOTE]
====
ifeval::["{build-type}" != "community"]
此迁移选项仅在 Rancher v2.13.5+ 和 v2.14 中可用。
endif::[]
ifeval::["{build-type}" == "community"]
此迁移选项仅在 Rancher v2.14.0+ 中可用。
endif::[]
====

集群配置界面提供了双模式迁移选项。这使您可以安全地测试并直接从集群管理屏幕将流量从 Ingress NGINX 迁移到 Traefik。

[#_rancher_on_managed_kubernetes_amazon_eks_azure_aks_google_gke]
=== 在托管 Kubernetes 上的 Rancher（Amazon EKS、Azure AKS、Google GKE）

如果您在托管 Kubernetes 服务上运行 {rancher-product-name}，例如 {xref-rancher-on-amazon-eks}[Amazon Elastic Kubernetes Service (EKS)]、{xref-rancher-on-aks}[Azure Kubernetes Service (AKS)] 或 {xref-rancher-on-gke}[Google Kubernetes Engine (GKE)]，建议迁移到 Traefik。

ifeval::["{build-type}" != "community"]
{rancher-product-name} 客户可以利用应用程序集合来部署和管理 Traefik 代理。
endif::[]
ifeval::["{build-type}" == "community"]
用户应部署并迁移到上游的 Traefik 代理发行版。
endif::[]

ifeval::["{build-type}" != "community"]
[#_impact_on_other_suse_products]
== 对其他 SUSE 产品的影响
endif::[]
ifeval::["{build-type}" == "community"]
[#_impact_on_projects]
== 对项目的影响
endif::[]

Ingress NGINX 的退役影响其他 

ifeval::["{build-type}" != "community"]
SUSE 产品
endif::[]
ifeval::["{build-type}" == "community"]
projects
endif::[]

以以下方式：

* {longhorn-product-name}：对 Longhorn 后端没有影响。但是，管理员必须重新配置他们的 Ingress 以升级 Longhorn UI。有关更多信息，请参阅 {url-storage-longhorn-ingress-traefik}[创建带基本身份验证的 Ingress Traefik]。
* {fleet-product-name}：配置 webhook 服务受到影响。有关更多信息，请参阅 {url-continuous-delivery-webhook}[Fleet 文档]。
* 其他项目文档中的 Ingress NGINX 引用已被删除。
