= Monitorización y Paneles
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/index.adoc 
:product-path: xref:observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:description: Prometheus le permite ver métricas de sus diferentes objetos de Rancher y Kubernetes. Aprenda sobre el alcance de la monitorización y cómo habilitar la monitorización del clúster
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
:xref-configure-alertmanager: xref:observabilidad/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:observabilidad/monitoring-and-dashboards/configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:observabilidad/monitoring-and-dashboards/rbac-para-monitoreo.adoc
:xref-customize-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:observabilidad/monitoring-and-dashboards/configuration/advanced/prometheusrules.adoc
:xref-prometheus: xref:observabilidad/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
:xref-enable-monitoring: xref:observabilidad/monitoring-and-dashboards/habilitar-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/create-persistent-grafana-dashboard.adoc
:xref-servicemonitors-and-podmonitors: xref:observabilidad/monitoring-and-dashboards/configuration/servicemonitors-y-podmonitors.adoc
:xref-monitoring-routes: xref:observabilidad/monitoring-and-dashboards/configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:observabilidad/monitoring-and-dashboards/configuration/borrar-alto-uso-de-memoria.adoc
:xref-monitoring-builtin-dashboards: xref:observabilidad/monitoring-and-dashboards/tableros-integrados.adoc
:xref-monitoring-uninstall: xref:observabilidad/monitoring-and-dashboards/desinstalar-monitorización.adoc
:xref-monitoring-windows: xref:observabilidad/monitoring-and-dashboards/soporte-para-windows.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
:xref-configure-alertmanager: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:reference-guides/monitoring-v2-configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheusrules.adoc
:xref-prometheus: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc
:xref-enable-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/crear-tablero-grafana-persistente.adoc
:xref-servicemonitors-and-podmonitors: xref:reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:reference-guides/monitoring-v2-configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:integrations-in-rancher/monitoring-and-alerting/windows-support.adoc
endif::[]

La aplicación `rancher-monitoring` puede desplegar rápidamente soluciones de monitorización y alertas de código abierto líderes en su clúster.

Introducida en Rancher v2.5, la aplicación está impulsada por https://prometheus.io/[Prometheus], https://grafana.com/grafana/[Grafana], https://prometheus.io/docs/alerting/latest/alertmanager/[Alertmanager], el https://github.com/prometheus-operator/prometheus-operator[Operador de Prometheus], y el https://github.com/DirectXMan12/k8s-prometheus-adapter[adaptador de Prometheus.]

Para información sobre la monitorización y alertas V1, disponible en Rancher v2.2 hasta v2.4, consulte la documentación de Rancher v2.0--v2.4 sobre xref:[monitorización de clústeres], xref:[alertas], xref:[notificadores] y otras xref:[herramientas].

Usando la aplicación `rancher-monitoring`, puede desplegar rápidamente soluciones de monitorización y alertas de código abierto líderes en su clúster.

[#_features]
== Funciones

Prometheus le permite ver métricas de sus objetos de Rancher y Kubernetes. Usando marcas de tiempo, Prometheus le permite consultar y ver estas métricas en gráficos y visuales fáciles de leer, ya sea a través de la interfaz de usuario de Rancher o Grafana, que es una plataforma de visualización de análisis desplegada junto con Prometheus.

Al ver los datos que Prometheus recopila de su plano de control de clúster, nodos y despliegues, puede mantenerse al tanto de todo lo que sucede en su clúster. A continuación, puede utilizar estos análisis para gestionar mejor su organización: detener emergencias del sistema antes de que comiencen, desarrollar estrategias de mantenimiento o restaurar servidores caídos.

La aplicación de monitorización:

* Supervisa el estado y los procesos de los nodos de tu clúster, los componentes de Kubernetes y las implementaciones de software.
* Define alertas basadas en métricas recopiladas a través de Prometheus.
* Crea paneles de Grafana personalizados.
* Configura notificaciones basadas en alertas a través de correo electrónico, Slack, PagerDuty, etc., utilizando Prometheus Alertmanager.
* Define expresiones precomputadas, frecuentemente necesarias o computacionalmente costosas como nuevas series temporales basadas en métricas recopiladas a través de Prometheus.
* Expone métricas recopiladas de Prometheus a la API de Métricas Personalizadas de Kubernetes a través del Adaptador de Prometheus para su uso en HPA.

Consulta {xref-how-monitoring-works}[Cómo Funciona el Monitoreo] para una explicación de cómo los componentes de monitoreo trabajan juntos.

[#_default_components_and_deployments]
== Componentes y Ampliaciones Predeterminados

[#_built_in_dashboards]
=== Paneles Integrados

Por defecto, la aplicación de monitorización despliega paneles de Grafana (curados por el proyecto https://github.com/prometheus-operator/kube-prometheus[kube-prometheus]) en un clúster.

También despliega una interfaz de usuario de Alertmanager y una interfaz de usuario de Prometheus. Para más información sobre estas herramientas, consulta {xref-monitoring-builtin-dashboards}[Paneles Integrado.]

[#_default_metrics_exporters]
=== Exportadores de Métricas Predeterminados

Por defecto, Rancher Monitoring despliega exportadores (como https://github.com/prometheus/node_exporter[node-exporter] y https://github.com/kubernetes/kube-state-metrics[kube-state-metrics]).

Estos exportadores predeterminados recopilan automáticamente métricas de CPU y memoria de todos los componentes de tu clúster de Kubernetes, incluyendo tus cargas de trabajo.

[#_default_alerts]
=== Alertas Predeterminadas

La aplicación de monitorización despliega algunas alertas por defecto. Para ver las alertas predeterminadas, ve a la xref:./built-in-dashboards.adoc#_alertmanager_ui[Interfaz de Usuario de Alertmanager] y haz clic en *Expandir todos los grupos.*

[#_components_exposed_in_the_rancher_ui]
=== Componentes expuestos en la interfaz de usuario de Rancher

Para una lista de componentes de monitorización expuestos en la interfaz de usuario de Rancher, junto con casos de uso comunes para editarlos, consulta xref:./how-monitoring-works.adoc#_components_exposed_in_the_rancher_ui[esta sección.]

[#_role_based_access_control]
== Control de acceso basado en funciones

Para más información sobre cómo configurar el acceso a la monitorización, consulta {xref-rancher-monitoring-rbac}[esta página.]

[NOTE]
====

Los permisos de lectura de Rancher y del proyecto no se aplican necesariamente a los recursos de monitorización. Consulta xref:./rbac-for-monitoring.adoc#_additional_monitoring_clusterroles[monitoring-ui-view] para más detalles.
====


[#_guides]
== Guías

* {xref-enable-monitoring}[Habilitar monitorización]
* {xref-monitoring-uninstall}[Desinstalar monitorización]
* {xref-rancher-workload-monitoring}[Monitorización de cargas de trabajo]
* {xref-customize-grafana-dashboard}[Personalización de paneles de Grafana]
* {xref-create-persistent-grafana-dashboard}[Paneles Integrados de Grafana persistentes]
* {xref-monitoring-debug-high-memory}[Depurar alto uso de memoria]

[#_configuration]
== Configuración

[#_configuring_monitoring_resources_in_rancher]
=== Configuración de recursos de monitorización en Rancher

La referencia de configuración asume familiaridad con el funcionamiento conjunto de los componentes de monitorización. Para más información, consulta {xref-how-monitoring-works}[Cómo funciona la monitorización.]

* {xref-servicemonitors-and-podmonitors}[ServiceMonitor y PodMonitor]
* {xref-receivers}[Receiver]
* {xref-monitoring-routes}[Route]
* {xref-prometheusrules}[PrometheusRule]
* {xref-prometheus}[Prometheus]
* {xref-configure-alertmanager}[Alertmanager]

[#_configuring_helm_chart_options]
=== Configurando las opciones del gráfico de Helm

Para más información sobre las opciones del gráfico `rancher-monitoring`, incluidas las opciones para establecer límites y solicitudes de recursos, consulta {xref-monitoring-helm-chart-options}[Opciones del gráfico de Helm].

[#_windows_cluster_support]
== Soporte para clústeres de Windows

Para poder desplegar completamente Monitoring V2 para Windows, todos sus hosts de Windows deben tener una versión mínima de https://github.com/rancher/wins[wins] v0.1.0.

Para más detalles sobre cómo actualizar la versión de wins en los hosts de Windows existentes, consulte {xref-monitoring-windows}[Soporte para clústeres de Windows para Monitoring V2.].

[#_known_issues]
== Problemas conocidos

Hay un https://github.com/rancher/rancher/issues/28787#issuecomment-693611821[problema conocido] que los clústeres de K3s requieren más memoria de la asignada por defecto. Si habilita la monitorización en un clúster de K3s, establezca `prometheus.prometheusSpec.resources.memory.limit` en 2500 Mi y `prometheus.prometheusSpec.resources.memory.request` en 1750 Mi.

Consulte {xref-monitoring-debug-high-memory}[Depurar alto uso de memoria] para obtener consejos y recomendaciones.
