= Desinstalar monitorización
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-alerting-guides/uninstall-monitoring.adoc 
:product-path: observabilidad/monitoring-and-dashboards/desinstalar-monitorización.adoc

. Haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster que creaste y haz clic en *Explorar*.
. En la barra de navegación izquierda, haz clic en *Apps*.
. Haz clic en *Installed Apps*.
. Ve al espacio de nombres `cattle-monitoring-system` y marca las casillas para `rancher-monitoring-crd` y `rancher-monitoring`.
. Haz clic en *Eliminar*.
. Confirma *Eliminar*.

*Resultado:* `rancher-monitoring` está desinstalado.

[NOTE]
.Paneles persistentes de Grafana:
====

Para los usuarios que están utilizando Monitoring V2 v9.4.203 o anterior, desinstalar el gráfico de monitorización eliminará el espacio de nombres cattle-dashboards, lo que eliminará todos los paneles persistentes, a menos que el espacio de nombres esté marcado con la anotación `helm.sh/resource-policy: "keep"`. Esta anotación se añade por defecto en Monitoring V2 v14.5.100+ pero se puede aplicar manualmente en el espacio de nombres cattle-dashboards antes de una desinstalación si una versión anterior del gráfico de monitorización está actualmente instalada en su clúster.
====

