= Soporte de Clúster de Windows para Monitorización V2
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/windows-support.adoc 
:product-path: observability/monitoring-and-dashboards/windows-support.adoc

La Monitorización V2 se puede desplegar en un clúster de Windows para recopilar métricas de nodos de Windows utilizando https://github.com/prometheus-community/windows_exporter[prometheus-community/windows_exporter] (anteriormente llamado `wmi_exporter`).

[#_cluster_requirements]
== Requisitos del Clúster

La Monitorización V2 para Windows solo puede recopilar métricas de hosts de Windows que tengan una versión mínima de `wins` v0.1.0.  Para poder desplegar completamente la Monitorización V2 para Windows, todos sus hosts deben cumplir con este requisito.

[#_upgrading_existing_clusters_to_wins_v0_1_0]
=== Actualizando Clústeres Existentes a wins v0.1.0

Si el clúster fue provisionado antes de Rancher 2.5.8 (incluso si la versión actual de Rancher es 2.5.8), no podrán desplegar con éxito la Monitorización V2 para Windows hasta que actualicen la versión de wins en cada host a al menos v0.1.0.

Para facilitar esta actualización, Rancher 2.5.8 ha lanzado un nuevo chart de Helm llamado `rancher-wins-upgrader`.

. Despliegue `rancher-wins-upgrader` con la siguiente anulación:
+
[,yaml]
----
 # Masquerading bootstraps the wins-upgrader installation via
 # a previously whitelisted process path since the normal install path,
 # c:\etc\rancher\wins\wins-upgrade.exe is not normally whitelisted.
 # In this case, we are using the previously whitelisted process
 # path used by Monitoring V1.
 masquerade:
   enabled: true
   as: c:\\etc\wmi-exporter\wmi-exporter.exe
----

. Una vez que todos los hosts hayan sido actualizados con éxito, por favor asegúrese de desplegar el chart de Helm una vez más con valores predeterminados para evitar conflictos con las siguientes configuraciones:
+
[,yaml]
----
 masquerade:
   enabled: false
----

*Resultado:* Los hosts están listos para que se instale la Monitorización V2. Puede optar por desinstalar el `rancher-wins-upgrader` chart o mantenerlo en su clúster para facilitar futuras actualizaciones.

Para más información sobre cómo se puede utilizar, por favor consulte el https://github.com/rancher/wins/blob/master/charts/rancher-wins-upgrader/README.md[README.md] del chart.
