= {longhorn-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/longhorn/index.adoc 
:product-path: integrations/longhorn/longhorn.adoc

Longhorn es un proyecto oficial de la https://cncf.io/[Cloud Native Computing Foundation (CNCF)] que ofrece una potente plataforma de almacenamiento distribuido nativo de nube para Kubernetes que puede ejecutarse en cualquier lugar. Cuando se combina con Rancher, Longhorn facilita desplegar almacenamiento en bloques persistente altamente disponible en tu entorno de Kubernetes de manera fácil, rápida y fiable.

[#__longhorn_product_name_with_rancher]
== {longhorn-product-name} con Rancher

Con Rancher Prime y Longhorn, los usuarios pueden desplegar fácilmente con un clic a través del catálogo de Rancher y realizar la gestión del ciclo de vida para clústeres downstream; empoderando al usuario para instalar y actualizar la versión, junto con la operación de drenaje para operaciones sin contratiempos. Longhorn con Rancher también proporciona soporte para clústeres mixtos con Windows, imágenes alojadas en Rancher, acceso al proxy de UI a través de Rancher y monitorización de Rancher con métricas de Longhorn.
