= Erstellen eines Azure-Clusters
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/kubernetes-mit-rancher-starten/neue-knoten-in-einem-infra-anbieter/azure-cluster-erstellen.adoc 
:product-path: cluster-deployment/infra-providers/azure/azure.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-azure-machine-configuration: xref:cluster-deployment/infra-providers/azure/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/index.adoc
:xref-k3s-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc
:xref-azure-machine-configuration: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/azure.adoc
endif::[]

In diesem Abschnitt lernen Sie, wie Sie ein {url-rke2-landing-page}[RKE2] oder {url-k3s-landing-page}[K3s] Kubernetes-Cluster in Azure über Rancher bereitstellen.

Zuerst richten Sie Ihre Azure-Cloud-Anmeldeinformationen in Rancher ein.

Dann erstellen Sie ein Azure-Cluster in Rancher, und beim Konfigurieren des neuen Clusters definieren Sie Maschinenpools dafür. Jeder Maschinenpool hat eine Kubernetes-Rolle von etcd, controlplane oder worker. Rancher installiert Kubernetes auf den neuen Knoten und richtet jeden Knoten mit der durch den Maschinenpool definierten Kubernetes-Rolle ein.

[CAUTION]
====

Wenn das Rancher RKE2/K3s-Cluster in Azure läuft und ein Azure-Lastenausgleich vor ihm steht, schlägt der ausgehende Datenfluss fehl. Die Umgehungslösung für dieses Problem ist wie folgt:

* Beenden Sie die SSL/TLS-Verschlüsselung am internen Lastenausgleich
* Verwenden Sie den L7-Lastenausgleich

Für weitere Informationen siehe die Dokumentation zu https://docs.microsoft.com/en-us/azure/load-balancer/components#_limitations[Beschränkungen des Azure-Lastenausgleichs].
====


Für weitere Informationen zur Konfiguration des Kubernetes-Clusters, den Rancher auf den Azure-Knoten installiert, siehe die {xref-rke2-config}[RKE2] und {xref-k3s-config}[K3s] Clusterkonfigurationsreferenzen.


Für weitere Informationen zur Konfiguration von Azure-Maschinen siehe die {xref-azure-machine-configuration}[Referenz zur Azure-Maschinenkonfiguration].

* <<_preparation_in_azure,Vorbereitung in Azure>>
* <<_creating_an_azure_cluster,Erstellen eines Azure-Clusters>>

[#_preparation_in_azure]
== Vorbereitung in Azure

Bevor ein Cluster bereitgestellt werden kann, müssen wir unser Azure-Abonnement so konfigurieren, dass die Manipulation seiner Ressourcen durch Dritte, wie Rancher, erlaubt ist.

Dazu werden wir zunächst einen neuen Azure *Service Principal (SP)* in Azure *Active Directory (AD)* erstellen, der in Azure ein Anwendungsbenutzer ist, der die Berechtigung hat, Azure-Ressourcen zu verwalten.

Das folgende ist ein `az cli` Skript, das Sie ausführen müssen, um einen Service Principal zu erstellen, wobei Sie Ihren SP-Namen, Rolle und Scope eingeben müssen:

----
az ad sp create-for-rbac \
  --name="<Rancher ServicePrincipal name>" \
  --role="Contributor" \
  --scopes="/subscriptions/<subscription Id>"
----

Die Erstellung dieses Service Principals gibt die **Anwendungs-ID** zurück, die auch als **Client-ID** und **Client-Secret** bezeichnet wird. Diese Informationen werden verwendet, wenn Sie Ihre Cloud-Anmeldeinformationen erstellen.

[#_creating_an_azure_cluster]
== Erstellen eines Azure-Clusters

[#_create_your_cloud_credentials]
=== Erstellen Sie Ihre Cloud-Anmeldeinformationen

Wenn Sie bereits über einen Satz von Cloud-Anmeldeinformationen verfügen, überspringen Sie diesen Abschnitt.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Klicken Sie auf *Cloud-Anmeldeinformationen*.
. Klicken Sie auf *Erstellen*.
. Klicken Sie auf *Azure*.
. Geben Sie Ihre Azure-Anmeldeinformationen ein.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Sie haben die Cloud-Anmeldeinformationen erstellt, die zur Bereitstellung von Knoten in Ihrem Cluster verwendet werden.

[#_create_your_cluster]
=== Erstellen Sie Ihren Cluster

Verwenden Sie Rancher, um einen Kubernetes-Cluster in Azure zu erstellen.

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Klicken Sie auf der *Cluster*-Seite auf *Erstellen*.
. Schalten Sie den Schalter auf *RKE2/K3s* um.
. Klicken Sie auf *Azure*.
. Wählen Sie eine *Cloud-Anmeldeinformation* aus, falls mehr als eine vorhanden ist. Andernfalls ist sie vorausgewählt.
. Geben Sie einen *Cluster-Namen* ein.
. Erstellen Sie einen Maschinenpool für jede Kubernetes-Rolle. Siehe die {xref-infra-providers}#_node_roles[Best Practices] für Empfehlungen zu Rollenzuweisungen und -anzahlen.
 .. Definieren Sie die Maschinenkonfiguration für jeden Maschinenpool. Beziehen Sie sich auf die {xref-azure-machine-configuration}[Referenz zur Azure-Maschinenkonfiguration] für Informationen zu Konfigurationsoptionen.
. Verwenden Sie die *Cluster-Konfiguration*, um die Version von Kubernetes auszuwählen, die installiert werden soll, welchen Netzwerkprovider Sie verwenden möchten und ob Sie die Projekt-Netzwerkisolierung aktivieren möchten.  Für Hilfe bei der Konfiguration des Clusters verweisen Sie auf die {xref-rke2-config}[RKE2] und {xref-k3s-config}[K3s] Cluster-Konfigurationsreferenzen.
. Verwenden Sie *Mitgliederrollen*, um die Benutzerautorisierung für den Cluster zu konfigurieren. Klicken Sie auf *Mitglied hinzufügen*, um Benutzer hinzuzufügen, die auf den Cluster zugreifen können. Verwenden Sie das *Rollen*-Dropdown, um Berechtigungen für jeden Benutzer festzulegen.
. Klicken Sie auf *Erstellen*.

*Ergebnis:*

Ihr Cluster wurde erstellt und hat den Status *Bereitstellung* erhalten. Rancher richtet Ihren Cluster ein.

Sie können auf Ihren Cluster zugreifen, nachdem sein Status auf *Aktiv* aktualisiert wurde.

*Aktiven* Clustern werden zwei Projekte zugeordnet:

* `Default`, das den `default` Namespace enthält
* `System`, der die `cattle-system`, `traefik`, `kube-public` und `kube-system` Namespaces enthält

[#_optional_next_steps]
=== Optionale nächste Schritte

Nach der Erstellung Ihres Clusters können Sie über die Rancher-Benutzeroberfläche darauf zugreifen. Als bewährte Praxis empfehlen wir, diese alternativen Möglichkeiten zum Zugriff auf Ihren Cluster einzurichten:

* *Zugriff auf Ihren Cluster mit der kubectl Kommandozeilenschnittstelle:* Befolgen Sie {xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[diese Schritte], um mit kubectl von Ihrer Workstation aus auf Cluster zuzugreifen. In diesem Fall werden Sie über den Authentifizierungsproxy des Rancher-Servers authentifiziert, dann wird Rancher Sie mit dem Downstream-Cluster verbinden. Diese Methode ermöglicht es Ihnen, den Cluster ohne die Rancher-Benutzeroberfläche zu verwalten.
* *Greifen Sie mit der kubectl-Kommandozeilenschnittstelle auf Ihren Cluster zu, indem Sie den autorisierten Cluster-Endpunkt verwenden:* Befolgen Sie {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[diese Schritte], um direkt mit kubectl auf Ihren Cluster zuzugreifen, ohne sich über Rancher zu authentifizieren. Wir empfehlen, diese alternative Methode einzurichten, um auf Ihren Cluster zuzugreifen, damit Sie auch dann auf den Cluster zugreifen können, wenn Sie sich nicht mit Rancher verbinden können.
