= Azure-Maschinenkonfiguration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cluster-konfiguration/downstream-cluster-konfiguration/maschinen-konfiguration/azure.adoc 
:product-path: cluster-deployment/infra-providers/azure/machine-configuration.adoc

Für weitere Informationen zu Azure, siehe die offizielle https://docs.microsoft.com/en-us/azure/?product=featured[Azure-Dokumentation.]

[#_basic_options]
== Grundlegende Optionen

[#_environment]
=== Umgebung

Microsoft bietet mehrere https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest[Clouds] an, die den regionalen Gesetzen entsprechen und für Ihre Nutzung verfügbar sind:

* AzurePublicCloud
* AzureGermanCloud
* AzureChinaCloud
* AzureUSGovernmentCloud

[#_location]
=== Standort

Konfigurieren Sie den Cluster und den Knoten https://docs.microsoft.com/en-us/azure/virtual-machines/regions[Standort].

[#_resource_group]
=== Ressourcengruppe

Eine Ressourcengruppe ist ein Container, der verwandte Ressourcen für eine Azure-Lösung enthält. Die Ressourcengruppe kann alle Ressourcen für die Lösung oder nur die Ressourcen enthalten, die Sie als Gruppe verwalten möchten. Sie entscheiden, wie Sie Ressourcen den Ressourcengruppen zuweisen möchten, basierend darauf, was für Ihre Organisation am sinnvollsten ist. Im Allgemeinen fügen Sie Ressourcen, die denselben Lebenszyklus teilen, derselben Ressourcengruppe hinzu, damit Sie sie als Gruppe einfach bereitstellen, aktualisieren und löschen können.

Verwenden Sie eine vorhandene Ressourcengruppe oder geben Sie einen Namen für eine Ressourcengruppe ein, und es wird eine für Sie erstellt.

Für Informationen zur Verwaltung von Ressourcengruppen siehe die https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal[Azure-Dokumentation.]

[#_availability_set_unmanaged]
=== Verfügbarkeitsgruppe (nicht verwaltet)

Name oder ID einer vorhandenen https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview[Verfügbarkeitsgruppe], um die VM hinzuzufügen.

[#_image]
=== Abbild

Der Name des Betriebssystemimages, das als ARM-Ressourcenbezeichner bereitgestellt wird. Erfordert die Verwendung einer verwalteten Festplatte.

[#_vm_size]
=== VM-Größe

Wählen Sie eine Größe für jede VM im Knotenpool. Für Details zu jeder VM-Größe siehe https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/[diese Seite.]

[#_advanced_options]
== Erweiterte Optionen

[#_fault_domain_count]
=== Fehlerdomänenanzahl

Fehlerdomänen definieren die Gruppe von virtuellen Maschinen, die eine gemeinsame Stromquelle und einen gemeinsamen Netzwerkschalter teilen. Wenn das Verfügbarkeitsset bereits erstellt wurde, wird die Anzahl der Fehlerdomänen ignoriert.

Für weitere Informationen zu Fehlerdomänen siehe https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview#how-do-availability-sets-work[hier].

[#_update_domain_count]
=== Aktualisierungsdomänenanzahl

Aktualisierungsdomänen bezeichnen Gruppen von virtuellen Maschinen und der zugrunde liegenden physischen Hardware, die gleichzeitig neu gestartet werden können. Wenn das Verfügbarkeitsset bereits erstellt wurde, wird die Anzahl der Aktualisierungsdomänen ignoriert.

Für weitere Informationen zu Aktualisierungsdomänen siehe https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview#how-do-availability-sets-work[hier].

[#_purchase_plan]
=== Kaufplan

Einige VM-Images im Azure Marketplace erfordern einen Plan. Wählen Sie, falls zutreffend, einen Kaufplan aus, der als `publisher:product:plan` formatiert ist, um ihn mit Ihrem gewählten Image zu verwenden.

[#_subnet]
=== Teilnetz

Der Name des Subnetzes beim Erstellen eines neuen VNets oder beim Verweisen auf ein bestehendes.

Standard: `docker-machine`

[#_subnet_prefix]
=== Subnetzpräfix

Das Subnetz-IP-Adresspräfix, das beim Erstellen eines neuen VNets im CIDR-Format verwendet werden soll.

Standard: `192.168.0.0/16`

[#_virtual_network]
=== Virtuelles Netzwerk

Das https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview[virtuelles Netzwerk], das verwendet oder erstellt werden soll, wenn keines vorhanden ist. Formatiert als `[resourcegroup:]name`.

[#_public_ip_options]
=== Öffentliche IP-Optionen

[#_no_public_ip]
==== Keine öffentliche IP

Weisen Sie keine öffentliche IP-Adresse zu.

[#_static_public_ip]
==== Statische öffentliche IP

Weisen Sie eine statische öffentliche IP-Adresse zu.

[#_use_private_ip]
=== Verwenden Sie eine private IP-Adresse

Verwenden Sie eine statische private IP-Adresse.

[#_private_ip_address]
=== Private IP-Adresse

Konfigurieren Sie eine statische private IP-Adresse zur Verwendung.

[#_network_security_group]
=== Netzwerksicherheitsgruppe

Die https://docs.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview[Netzwerksicherheitsgruppe], die verwendet werden soll. Alle Knoten, die diese Vorlage verwenden, verwenden die bereitgestellte Netzwerksicherheitsgruppe. Wenn keine Netzwerksicherheitsgruppe bereitgestellt wird, wird für jeden Knoten eine neue erstellt.

[#_dns_label]
=== DNS-Label

Ein eindeutiges DNS-Label für die öffentliche IP-Adresse.

[#_storage_type]
=== Speichertyp

Der https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview[Speicherkontotyp], der mit Ihren VMs verwendet werden soll. Die Optionen umfassen Standard LRS, Standard ZRS, Standard GRS, Standard RAGRS und Premium LRS.

[#_use_managed_disks]
=== Verwenden Sie verwaltete Festplatten

https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview[Azure verwaltete Festplatten] sind blockbasierte Speicher-Volumes, die von Azure verwaltet werden und mit Azure Virtual Machines verwendet werden. Verwaltete Festplatten sind für eine Verfügbarkeit von 99,999 % ausgelegt. Verwaltete Festplatten erreichen dies, indem sie Ihnen drei Replikate Ihrer Daten bereitstellen, was eine hohe Haltbarkeit ermöglicht.

[#_managed_disk_size]
=== Größe der verwalteten Festplatte

Die Größe in GB für die Festplatte für jeden Knoten.

[#_ssh_username]
=== SSH-Benutzername

Der Benutzername, der verwendet wird, um eine SSH-Verbindung zu Ihren Knoten herzustellen.

[#_open_port]
=== Geöffneter Port

Öffnet den eingehenden Verkehr auf den angegebenen Ports. Bei der Verwendung einer bestehenden Netzwerksicherheitsgruppe werden offene Ports ignoriert.

Standard: `2379/tcp, 2380/tcp, 6443/tcp, 9796/tcp, 10250/tcp, 10251/tcp, 10252/tcp, 10256/tcp` und `8472/udp, 4789/udp`
