= Modèles de cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-04
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc 
:product-path: cluster-admin/manage-clusters/cluster-templates.adoc
:experimental:

Les modèles de cluster englobent à la fois la configuration de Kubernetes et la configuration du pool de nœuds, permettant à un seul modèle de contenir toutes les informations nécessaires à Rancher pour provisionner de nouveaux nœuds chez un fournisseur de cloud et installer Kubernetes sur ces nœuds.

[#_overview]
== Présentation

Les modèles de cluster sont fournis sous forme de charts Helm. Pour les utiliser, vous devrez cloner et forker les modèles, les modifier selon votre cas d'utilisation, puis installer les charts Helm sur le cluster de gestion Rancher. Lorsque le chart Helm est installé sur le cluster de gestion Rancher, une nouvelle ressource de cluster est créée, que Rancher utilise pour provisionner le nouveau cluster.

Après que le cluster a été provisionné à l'aide du modèle, aucune modification du modèle n'affectera le cluster. Après que le cluster a été créé à partir du modèle de cluster, sa configuration et son infrastructure peuvent changer, car aucune restriction n'est imposée par les modèles de cluster.

[#_kubernetes_distribution]
=== Distribution Kubernetes

Les modèles de cluster peuvent utiliser n'importe quelle distribution Kubernetes. Pour l'instant, nous fournissons un exemple avec un cluster Kubernetes RKE2. Nous pourrions fournir d'autres exemples à l'avenir en utilisant d'autres distributions Kubernetes.

[#_versioning]
=== Contrôle des versions

Rancher ne gère pas le contrôle de version pour les modèles de cluster. Le contrôle de version est géré dans le dépôt contenant le chart Helm du modèle.

[#__rke2_product_name_cluster_template]
== {rke2-product-name} Modèle de cluster

Consultez le dépôt d'exemple pour un https://github.com/rancher/cluster-template-examples[modèle de cluster RKE2].

[#_adding_a_cluster_template_to_rancher]
== Ajouter un modèle de cluster à Rancher

Dans cette section, vous apprendrez comment ajouter le modèle de cluster à la liste des dépôts de graphiques du cluster `local`. Le résultat est que Rancher inclura le modèle de cluster comme option lorsque les utilisateurs installeront de nouveaux clusters Kubernetes.

[NOTE]
.Conditions préalables :
====

* Vous aurez besoin d'une autorisation pour installer des graphiques Helm sur le `local` cluster Rancher.
* Pour rendre le chart visible dans le formulaire de création de cluster, à la fois le chart et le fichier index.yaml doivent avoir l'annotation, `catalog.cattle.io/type: cluster-template`.
====


. Allez à un exemple de dépôt de modèle de cluster. Les exemples de Rancher se trouvent dans https://github.com/rancher/cluster-template-examples[ce dépôt GitHub.]
. Faites un fork du dépôt.
. Facultatives : Modifiez les options du cluster en éditant le fichier `values.yaml`. Pour obtenir de l'aide sur l'édition du fichier, consultez le README du chart Helm du modèle de cluster.
. Ajoutez le dépôt de charts à Rancher. Cliquez sur *☰ > Gestion des clusters*.
. Allez au `local` cluster et cliquez sur *Explorer.*
. Dans la barre de navigation à gauche, cliquez sur menu:Apps[Dépôts de charts.].
. Cliquez sur *Créer.*
. Entrez un nom pour le dépôt de modèle de cluster.
. Cliquez sur *Dépôt Git contenant les définitions de chart Helm.*
. Dans le champ *URL du dépôt Git*, entrez l'URL du dépôt. Par exemple : `https://github.com/rancher/cluster-template-examples.git`.
. Dans le champ *Branche Git*, entrez la branche à utiliser comme source pour le modèle. Le dépôt d'exemples de Rancher utilise `main`.
. Cliquez sur *Créer.*

*Résultat :* Le modèle de cluster est disponible dans *Apps* dans le `local` cluster de Rancher. Il peut maintenant être utilisé pour déployer des clusters.

[#_creating_a_cluster_from_a_cluster_template]
== Créer un cluster à partir d'un modèle de cluster

[NOTE]
.Conditions préalables :
====

* Vous aurez besoin d'une autorisation pour provisionner de nouveaux clusters Kubernetes.
* Vous aurez besoin d'identifiants cloud pour provisionner l'infrastructure en utilisant le modèle.
* Pour s'afficher dans le formulaire de création de nouveaux clusters, le chart Helm du modèle de cluster doit avoir l'annotation `catalog.cattle.io/type: cluster-template`.
====


. Cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, cliquez sur *Créer.*
. Cliquez sur le nom de votre modèle de cluster.
. Terminez l'installation du chart Helm.

*Résultat :* Après que Rancher ait provisionné le nouveau cluster, il est géré de la même manière que tout autre cluster Kubernetes lancé par Rancher. Vous pouvez configurer toutes les options via l'interface utilisateur si le modèle de cluster a des options à choisir pour l'utilisateur.

[#_updating_a_cluster_created_from_a_cluster_template]
== Mise à jour d'un cluster créé à partir d'un modèle de cluster

Vous pouvez mettre à jour tous les clusters utilisant un modèle depuis la page menu:Apps[Applications installées], à condition qu'il y ait une nouvelle version d'un modèle utilisé par ces clusters.

[#_deploying_clusters_from_a_template_with_fleet_product_name]
== Déploiement de clusters à partir d'un modèle avec {fleet-product-name}

[NOTE]
.Conditions préalables :
====

* Vous aurez besoin d'une autorisation pour provisionner de nouveaux clusters Kubernetes.
* Vous aurez besoin d'identifiants cloud pour provisionner l'infrastructure en utilisant le modèle.
* Pour s'afficher dans le formulaire de création de nouveaux clusters, le chart Helm du modèle de cluster doit avoir l'annotation `catalog.cattle.io/type:cluster-template`.
* Pour utiliser un modèle dans le cadre de la livraison continue/GitOps, le modèle de cluster doit être déployé dans l'espace de noms `fleet-local` du `local` cluster.
* Toutes les valeurs doivent être définies dans le `values.yaml` du modèle.
* Les dépôts Fleet doivent suivre ces https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/explanations/gitrepo-content.html[directives]. Pour les modèles de cluster RKE2, cela signifie qu'un fichier `fleet.yaml` doit être ajouté au dépôt.
====


. Cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, cliquez sur *Créer.*
. Cliquez sur *Créer un cluster à partir du modèle.*

*Résultat :* Après que Rancher ait provisionné le nouveau cluster, il est géré par Fleet.

[#_uninstalling_cluster_templates]
== Désinstallation des modèles de cluster

. Cliquez sur *☰ > Gestion des clusters*.
. Allez au `local` cluster et cliquez sur menu:Apps[Dépôts de charts.]
. Allez au dépôt de charts pour votre modèle de cluster et cliquez sur *⋮ > Supprimer.*
. Confirmez la suppression.

*Résultat :* Le modèle de cluster est désinstallé. Cette action n'affecte pas les clusters créés avec le modèle de cluster.

Un administrateur ayant accès au `local` cluster peut également supprimer un cluster déployé via des modèles de cluster depuis la page menu:Apps[Applications installées].

[#_configuration_options]
== Options de configuration

Les modèles de cluster sont suffisamment flexibles pour être utilisés pour configurer toutes les options suivantes{nbsp}:

* Configuration du nœud
* Pools de nœuds
* Identifiants cloud pré-spécifiés
* Activer/configurer un point de terminaison de cluster autorisé pour obtenir un accès kubectl au cluster sans utiliser Rancher comme proxy
* Installer la surveillance Rancher V2
* Version de Kubernetes
* Attribuer des membres au cluster
* Configuration de l'infrastructure telle que VPC/sous-réseaux AWS ou centre de données vSphere
* Options du fournisseur de cloud
* Options de sécurité des pods
* Fournisseurs de réseau
* Contrôleurs d'Ingress
* Configuration de la sécurité du réseau
* Plugins réseau
* URL et identifiants du registre privé
* Modules complémentaires
* Options Kubernetes, y compris la configuration des composants Kubernetes tels que kube-api, kube-controller, kubelet et les services.

Pour la procédure de configuration du modèle, reportez-vous au README du chart Helm du modèle de cluster.
