= Administration des clusters
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-18
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/index.adoc 
:product-path: cluster-admin/manage-clusters/manage-clusters.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/cluster-and-project-roles.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
endif::[]

Après avoir provisionné un cluster dans Rancher, vous pouvez commencer à utiliser des fonctionnalités Kubernetes puissantes pour déployer et faire évoluer vos applications conteneurisées dans des environnements de développement, de test ou de production.

[NOTE]
====

Cette section suppose une familiarité de base avec Docker et Kubernetes. Pour une brève explication de la façon dont les composants Kubernetes fonctionnent ensemble, reportez-vous à la page {xref-k8s-concepts}[concepts].
====


[#_managing_clusters_in_rancher]
== Gestion des clusters dans Rancher

Après que les clusters ont été {xref-cluster-deployment}[provisionnés dans Rancher], {xref-cluster-project-roles}#_cluster_roles[les propriétaires de clusters] devront gérer ces clusters. Il existe de nombreuses options différentes pour gérer votre cluster.

ifeval::["{build-type}" != "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table.adoc[]
endif::[]
ifeval::["{build-type}" == "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table-srfa.adoc[]
endif::[]

[#_configuring_tools]
== Configuration des outils

Rancher contient une variété d'outils qui ne sont pas inclus dans Kubernetes pour aider dans vos opérations DevOps. Rancher peut s'intégrer à des services externes pour aider vos clusters à fonctionner plus efficacement. Les outils sont divisés en catégories suivantes{nbsp}:

* Alertes
* Notifiers
* Consignation
* Surveillance
* Maillage de services Istio

Les outils peuvent être installés via *Apps.*
