= Cluster Autoscaler
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}

En esta sección, aprenderás cómo instalar y usar el https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/[Kubernetes cluster-autoscaler] en clusters personalizados de Rancher utilizando Grupos de Autoescalado de AWS EC2.

Cluster Autoscaler es una herramienta que ajusta automáticamente el tamaño del cluster de Kubernetes cuando se cumple una de las siguientes condiciones:

* Hay pods que no pudieron ejecutarse en el clúster debido a recursos insuficientes.
* Hay nodos en el clúster que han estado infrautilizados durante un período prolongado y sus pods pueden ser colocados en otros nodos existentes.

Para evitar que tu pod sea desalojado, establece una propiedad `priorityClassName: system-cluster-critical` en la especificación de tu pod.

Cluster Autoscaler está diseñado para ejecutarse en nodos maestros de Kubernetes. Puede ejecutarse en el espacio de nombres `kube-system`. Cluster Autoscaler no reduce el tamaño de los nodos con pods `kube-system` no espejados ejecutándose en ellos.

Es posible ejecutar un despliegue personalizado de Cluster Autoscaler en nodos de trabajo, pero se debe tener especial cuidado para asegurar que Cluster Autoscaler permanezca en funcionamiento.

[#_cloud_providers]
== Proveedores de Nube

Cluster Autoscaler proporciona soporte a distintos proveedores de nube. Para más información, visita https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#deployment[los proveedores de nube soportados por cluster-autoscaler.]

[#_setting_up_cluster_autoscaler_on_amazon_cloud_provider]
=== Configurando Cluster Autoscaler en Amazon Cloud Provider

Para detalles sobre cómo ejecutar Cluster Autoscaler en Amazon Cloud Provider, consulta xref:cluster-admin/manage-clusters/install-cluster-autoscaler/use-aws-ec2-auto-scaling-groups.adoc[esta página.]
