= Référence de configuration du cluster GKE
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-28
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/index.adoc 
:product-path: cluster-deployment/hosted-kubernetes/gke/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-logging: xref:observability/logging/logging.adoc
:xref-gke-private-clusters: xref:cluster-deployment/hosted-kubernetes/gke/private-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
:xref-gke-private-clusters: xref:reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/gke-private-clusters.adoc
endif::[]

[#_cluster_location]
== Emplacement du cluster

|===
| Valeur | Description

| Type d'emplacement
| Zonal ou Régional. Avec GKE, vous pouvez créer un cluster adapté aux exigences de disponibilité de votre charge de travail et à votre budget. Par défaut, les nœuds d'un cluster s'exécutent dans une seule zone de calcul. Lorsque plusieurs zones sont sélectionnées, les nœuds du cluster s'étendront sur plusieurs zones de calcul, tandis que le plan de contrôle est situé dans une seule zone. Les clusters régionaux augmentent également la disponibilité du plan de contrôle. Pour obtenir de l'aide sur le choix du type de disponibilité du cluster, consultez https://cloud.google.com/kubernetes-engine/docs/best-practices/scalability#choosing_a_regional_or_zonal_control_plane[ces documents.]

| Zone
| Chaque région dans Compute Engine contient un certain nombre de zones. Pour plus d'informations sur les régions et zones disponibles, consultez https://cloud.google.com/compute/docs/regions-zones#available[ces documents.]

| Zones supplémentaires
| Pour les clusters zonaux, vous pouvez sélectionner des zones supplémentaires pour créer un https://cloud.google.com/kubernetes-engine/docs/concepts/types-of-clusters#multi-zonal_clusters[cluster multi-zone.]

| Région
| Pour https://cloud.google.com/kubernetes-engine/docs/concepts/types-of-clusters#regional_clusters[les clusters régionaux,], vous pouvez sélectionner une région. Pour plus d'informations sur les régions et zones disponibles, consultez https://cloud.google.com/compute/docs/regions-zones#available[cette section]. La première partie de chaque nom de zone est le nom de la région.
|===

[#_cluster_options]
== Options de grappe

[#_kubernetes_version]
=== Kubernetes Version

_Mutable: oui_

Pour plus d'informations sur les versions GKE Kubernetes, consultez https://cloud.google.com/kubernetes-engine/versioning[ces documents.]

[#_container_address_range]
=== Plage d'adresses des conteneurs

_Mutable: non_

La plage d'adresses IP pour les pods dans le cluster. Doit être une plage CIDR valide, par exemple 10.42.0.0/16. Si non spécifié, une plage aléatoire est automatiquement choisie parmi 10.0.0.0/8 et exclura les plages déjà attribuées aux VM, autres clusters ou routes. Les plages choisies automatiquement peuvent entrer en conflit avec des adresses IP réservées, des routes dynamiques ou des routes au sein des VPC se connectant au cluster.

[#_network]
=== Réseau

_Mutable: non_

Le réseau Compute Engine auquel le cluster se connecte. Des routes et des passerelles de périmètre de sécurité seront créées en utilisant ce réseau. Si vous utilisez https://cloud.google.com/vpc/docs/shared-vpc[des VPC partagés], les réseaux VPC de votre projet apparaîtront ici et pourront être sélectionnés dans ce champ. Pour plus d'informations, consultez https://cloud.google.com/vpc/docs/vpc#vpc_networks_and_subnets[cette page].

[#_node_subnet_subnet]
=== Sous-réseau de nœud / Sous-réseau

_Mutable: non_

Le sous-réseau Compute Engine auquel le cluster se connecte. Ce sous-réseau doit appartenir au réseau spécifié dans le champ *Réseau*. Sélectionnez un sous-réseau existant, ou choisissez « Créer un sous-réseau automatiquement » pour en créer un. Si vous n'utilisez pas un réseau existant, *Nom du sous-réseau* est requis pour en générer un. Si vous utilisez https://cloud.google.com/vpc/docs/shared-vpc[des VPC partagés], les sous-réseaux VPC partagés avec votre projet apparaîtront ici. Si vous utilisez un réseau VPC partagé, vous ne pouvez pas sélectionner "Créer un sous-réseau automatiquement". Pour plus d'informations, consultez https://cloud.google.com/vpc/docs/vpc#vpc_networks_and_subnets[cette page.]

[#_subnetwork_name]
=== Nom du sous-réseau

_Mutable{nbsp}: non_

Créer automatiquement un sous-réseau avec le nom fourni. Requis si "Création automatique de sous-réseau" est sélectionné pour *Sous-réseau de nœud* ou *Sous-réseau*. Pour plus d'informations sur les sous-réseaux, consultez https://cloud.google.com/vpc/docs/vpc#vpc_networks_and_subnets[cette page.]

[#_ip_aliases]
=== Alias IP

_Mutable{nbsp}: non_

Activez https://cloud.google.com/vpc/docs/alias-ip[les alias IP]. Cela active le routage du trafic natif VPC. Requis si vous utilisez https://cloud.google.com/vpc/docs/shared-vpc[des VPC partagés].

[#_network_policy]
=== Stratégie réseau

_Mutable{nbsp}: oui_

Activez l'application de la politique réseau sur le cluster. Une politique réseau définit le niveau de communication qui peut se produire entre les pods et les services dans le cluster. Pour plus d'informations, reportez-vous à https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy[cette page.]

[#_project_network_isolation]
=== Isolation du réseau de projet

_Mutable{nbsp}: oui_

Choisissez d'activer ou de désactiver la communication inter-projets.

[#_imported_clusters]
==== Clusters importés

Pour les clusters importés, l'isolement de réseau de projet (PNI) nécessite que la politique réseau Kubernetes soit activée sur le cluster au préalable.
Pour les clusters créés par Rancher, Rancher active automatiquement la politique réseau Kubernetes.

. Dans GKE, activez la politique réseau au niveau du cluster. Reportez-vous au https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy[guide officiel de GKE] pour les instructions.
. Après avoir activé la politique réseau, importez le cluster dans Rancher et activez le PNI pour l'isolement au niveau du projet.

[#_node_ipv4_cidr_block]
=== Bloc CIDR IPv4 du nœud

_Mutable{nbsp}: non_

La plage d'adresses IP des IP d'instance dans ce cluster. Peut être défini si "Création automatique de sous-réseau" est sélectionné pour *Node Subnet* ou *Subnet*. Doit être une plage CIDR valide, par exemple 10.96.0.0/14. Pour plus d'informations sur la façon de déterminer la plage d'adresses IP, consultez https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#cluster_sizing[cette page.]

[#_cluster_secondary_range_name]
=== Nom de la plage secondaire du cluster

_Mutable{nbsp}: non_

Le nom d'une plage secondaire existante pour les adresses IP des pods. Si sélectionné, *la plage d'adresses IP des pods du cluster* sera automatiquement remplie. Requis si vous utilisez un réseau VPC partagé.

[#_cluster_pod_address_range]
=== Plage d'adresses IP des pods du cluster

_Mutable{nbsp}: non_

La plage d'adresses IP assignée aux pods dans le cluster. Doit être une plage CIDR valide, par exemple 10.96.0.0/11. Si non fourni, sera créé automatiquement. Doit être fourni si vous utilisez un réseau VPC partagé. Pour plus d'informations sur la façon de déterminer la plage d'adresses IP pour vos pods, consultez https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#cluster_sizing_secondary_range_pods[cette section.]

[#_services_secondary_range_name]
=== Nom de la plage secondaire des services

_Mutable{nbsp}: non_

Le nom d'une plage secondaire existante pour les adresses IP des services. Si sélectionné, *la plage d'adresses IP des services* sera automatiquement remplie. Requis si vous utilisez un réseau VPC partagé.

[#_service_address_range]
=== Plage d'adresses IP des services

_Mutable{nbsp}: non_

La plage d'adresses assignée aux services dans le cluster. Doit être une plage CIDR valide, par exemple 10.94.0.0/18. Si non fourni, sera créé automatiquement. Doit être fourni si vous utilisez un réseau VPC partagé. Pour plus d'informations sur la façon de déterminer la plage d'adresses IP pour vos services, consultez https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#cluster_sizing_secondary_range_svcs[cette section.]

[#_private_cluster]
=== Cluster privé

_Mutable{nbsp}: non_

[CAUTION]
====

Les clusters privés nécessitent une planification et une configuration supplémentaires en dehors de Rancher. Consultez le {xref-gke-private-clusters}[guide des clusters privés].
====


Attribuez uniquement des adresses IP internes aux nœuds. Les nœuds du cluster privé ne peuvent pas accéder à Internet public à moins que des étapes de mise en réseau supplémentaires ne soient prises dans GCP.

[#_enable_private_endpoint]
=== Activer le point de terminaison privé

[CAUTION]
====

Les clusters privés nécessitent une planification et une configuration supplémentaires en dehors de Rancher. Consultez le {xref-gke-private-clusters}[guide des clusters privés].
====


_Mutable{nbsp}: non_

Restreint l'accès externe au point de terminaison du plan de contrôle. Disponible uniquement si *Cluster privé* est également sélectionné. Si sélectionné, et si Rancher n'a pas d'accès direct au réseau VPC privé dans lequel le cluster fonctionne, Rancher fournira une commande d'inscription à exécuter sur le cluster pour permettre à Rancher de s'y connecter.

[#_master_ipv4_cidr_block]
=== Bloc CIDR IPv4 maître

_Mutable{nbsp}: non_

La plage d'adresses IP pour le VPC du plan de contrôle.

[#_master_authorized_network]
=== Réseau autorisé du plan de contrôle

_Mutable{nbsp}: oui_

Activez les réseaux autorisés du plan de contrôle pour bloquer les adresses IP sources non fiables, non-GCP, d'accéder au plan de contrôle Kubernetes via HTTPS. Si sélectionné, des réseaux autorisés supplémentaires peuvent être ajoutés. Si le cluster est créé avec un point de terminaison public, cette option est utile pour restreindre l'accès au point de terminaison public à certains réseaux, comme le réseau où votre service Rancher fonctionne. Si le cluster n'a qu'un point de terminaison privé, ce paramètre est requis.

[#_additional_options]
== Options supplémentaires

[#_cluster_addons]
=== Add-ons du cluster

Composants supplémentaires du cluster Kubernetes. Pour plus d'informations, reportez-vous à https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.AddonsConfig[cette page.]

[#_horizontal_pod_autoscaling]
==== Mise à l'échelle horizontale des pods

_Mutable{nbsp}: oui_

L'autoscaler horizontal des pods modifie la configuration de votre charge de travail Kubernetes en augmentant ou réduisant automatiquement le nombre de pods en fonction de la consommation d'UC ou de mémoire, ou en réponse à des métriques personnalisées rapportées depuis Kubernetes ou à des métriques externes provenant de sources en dehors de votre cluster. Pour plus d'informations, consultez https://cloud.google.com/kubernetes-engine/docs/concepts/horizontalpodautoscaler[cette page.]

[#_http_l7_load_balancing]
==== Équilibrage de la charge HTTP (L7)

_Mutable: oui_

L'équilibrage de la charge HTTP (L7) distribue le trafic HTTP et HTTPS vers les backends hébergés sur GKE. Pour plus d'informations, reportez-vous à https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer[cette page.]

[#_network_policy_config_master_only]
==== Configuration de la stratégie réseau (maître uniquement)

_Mutable: oui_

Configuration pour NetworkPolicy. Cela ne suit que si l'addon est activé ou non sur le maître, cela ne suit pas si la stratégie réseau est activée pour les nœuds.

[#_cluster_features_alpha_features]
=== Fonctionnalités du cluster (Fonctionnalités Alpha)

_Mutable: non_

Active tous les groupes et fonctionnalités de l'API alpha de Kubernetes pour le cluster. Lorsqu'il est activé, le cluster ne peut pas être mis à niveau et sera automatiquement supprimé après 30 jours. Les clusters alpha ne sont pas recommandés pour une utilisation en production car ils ne sont pas couverts par le SLA de GKE. Pour plus d'informations, reportez-vous à https://cloud.google.com/kubernetes-engine/docs/concepts/alpha-clusters[cette page.]

[#_logging_service]
=== Service de consignation

_Mutable: oui_

Le service de consignation que le cluster utilise pour écrire des journaux. Utilisez soit https://cloud.google.com/logging[Cloud Logging] soit aucun service de consignation, auquel cas aucun journal n'est exporté depuis le cluster.

[#_monitoring_service]
=== Service de surveillance

_Mutable: oui_

Le service de surveillance que le cluster utilise pour écrire des métriques. Utilisez soit https://cloud.google.com/monitoring[Cloud Monitoring] soit le service de surveillance, auquel cas aucune métrique n'est exportée depuis le cluster.

[#_maintenance_window]
=== Fenêtre de maintenance

_Mutable: oui_

Définissez l'heure de début pour une fenêtre de maintenance de 4 heures. L'heure est spécifiée dans le fuseau horaire UTC en utilisant le format HH:MM. Pour plus d'informations, reportez-vous à https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions[cette page.]

[#_node_pools]
== Pools de nœuds

Dans cette section, entrez les détails décrivant la configuration de chaque nœud dans le pool de nœuds.

[#_kubernetes_version_1]
=== Kubernetes Version

_Mutable: oui_

La version de Kubernetes pour chaque nœud dans le pool de nœuds. Pour plus d'informations sur les versions GKE Kubernetes, consultez https://cloud.google.com/kubernetes-engine/versioning[ces documents.]

[#_image_type]
=== Type d'image

_Mutable: oui_

L'image du système d'exploitation du nœud. Pour plus d'informations sur les options d'image de nœud que GKE propose pour chaque système d'exploitation, consultez https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#available_node_images[cette page.]

[NOTE]
====

L'option par défaut est "Système d'exploitation optimisé pour les conteneurs avec Docker". Le système de fichiers en lecture seule sur le système d'exploitation optimisé pour les conteneurs de GCP n'est pas compatible avec l'implémentation de xref:[journalisation héritée] dans Rancher. Si vous devez utiliser la fonctionnalité de journalisation héritée, sélectionnez "Ubuntu avec Docker" ou "Ubuntu avec Containerd". La {xref-logging}[fonctionnalité de journalisation actuelle] est compatible avec l'image du système d'exploitation optimisé pour les conteneurs.
====


[NOTE]
====

Si vous sélectionnez "Windows Long Term Service Channel" ou "Windows Semi-Annual Channel" pour le type d'image du pool de nœuds, vous devez également ajouter au moins un pool de nœuds optimisé pour les conteneurs ou Ubuntu.
====


[#_machine_type]
=== Type de machine

_Mutable: non_

Les ressources matérielles virtualisées disponibles pour les instances de nœuds. Pour plus d'informations sur les types de machines Google Cloud, consultez https://cloud.google.com/compute/docs/machine-types#machine_types[cette page.]

[#_root_disk_type]
=== Type de disque racine

_Mutable: non_

Les disques persistants standard sont basés sur des disques durs standard (HDD), tandis que les disques persistants SSD sont basés sur des disques statiques à semiconducteurs (SSD). Pour plus d'informations, consultez https://cloud.google.com/compute/docs/disks[cette section.]

[#_local_ssd_disks]
=== Disques SSD locaux

_Mutable: non_

Configurez le stockage de disque SSD local de chaque nœud en Go. Les disques SSD locaux sont physiquement attachés au serveur qui héberge votre instance VM. Les disques SSD locaux ont un débit plus élevé et une latence plus faible que les disques persistants standard ou les disques persistants SSD. Les données que vous stockez sur un disque SSD local persistent uniquement jusqu'à ce que l'instance soit arrêtée ou supprimée. Pour plus d'informations, consultez https://cloud.google.com/compute/docs/disks#localssds[cette section.]

[#_preemptible_nodes_beta]
=== Nœuds préemptibles (bêta)

_Mutable: non_

Les nœuds préemptibles, également appelés VMs préemptibles, sont des instances VM de Compute Engine qui durent un maximum de 24 heures en général et ne fournissent aucune garantie de disponibilité. Pour plus d'informations, consultez https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms[cette page.]

[#_taints]
=== Taints

_Mutable: non_

Lorsque vous appliquez une « taint » à un nœud, seuls les pods qui tolèrent la « taint » sont autorisés à s'exécuter sur le nœud. Dans un cluster GKE, vous pouvez appliquer une « taint » à un pool de nœuds, ce qui applique la « taint » à tous les nœuds du pool.

[#_node_labels]
=== Étiquettes de nœud

_Mutable: non_

Vous pouvez appliquer des étiquettes au pool de nœuds, ce qui applique les étiquettes à tous les nœuds du pool.

Des étiquettes invalides peuvent empêcher les mises à niveau ou peuvent empêcher Rancher de démarrer. Pour plus de détails sur les exigences de syntaxe des étiquettes, consultez la https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set[documentation Kubernetes.]

[#_network_tags]
=== Tags réseau

_Mutable: non_

Vous pouvez ajouter des tags réseau au pool de nœuds pour créer des règles de passerelle de périmètre de sécurité et des routes entre les sous-réseaux. Les tags s'appliqueront à tous les nœuds du pool.

Pour plus de détails sur la syntaxe des tags et les exigences, consultez la https://cloud.google.com/vpc/docs/add-remove-network-tags[documentation Kubernetes].

[#_group_details]
== Détails du groupe

Dans cette section, entrez des détails décrivant le pool de nœuds.

[#_name]
=== Nom

_Mutable: non_

Entrez un nom pour le pool de nœuds.

[#_initial_node_count]
=== Nombre initial de nœuds

_Mutable: oui_

Entier pour le nombre de départ de nœuds dans le pool de nœuds.

[#_max_pod_per_node]
=== Nombre maximal de pods par nœud

_Mutable: non_

GKE a une limite stricte de 110 pods par nœud. Pour plus d'informations sur les limites de Kubernetes, consultez https://cloud.google.com/kubernetes-engine/docs/best-practices/scalability#dimension_limits[cette section.]

[#_autoscaling]
=== Mise à l'échelle automatique

_Mutable: oui_

La mise à l'échelle automatique du pool de nœuds crée ou supprime dynamiquement des nœuds en fonction des demandes de votre charge de travail. Pour plus d'informations, consultez https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler[cette page.]

[#_auto_repair]
=== Réparation Automatique

_Mutable: oui_

La fonctionnalité de réparation automatique des nœuds de GKE vous aide à maintenir les nœuds de votre cluster dans un état sain et opérationnel. Lorsqu'elle est activée, GKE effectue des vérifications périodiques de l'état de santé de chaque nœud de votre cluster. Si un nœud échoue à des vérifications de santé consécutives pendant une période prolongée, GKE initie un processus de réparation pour ce nœud. Pour plus d'informations, consultez la section sur https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-repair[la réparation automatique des nœuds.]

[#_auto_upgrade]
=== Mise à jour automatique

_Mutable: oui_

Lorsqu'elle est activée, la fonctionnalité de mise à jour automatique maintient les nœuds de votre cluster à jour avec la version du plan de contrôle du cluster (maître) lorsque votre plan de contrôle est https://cloud.google.com/kubernetes-engine/upgrades#automatic_cp_upgrades[mis à jour en votre nom.] Pour plus d'informations sur la mise à jour automatique des nœuds, consultez https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-upgrades[cette page.]

[#_access_scopes]
=== Scopes d'accès

_Mutable: non_

Les scopes d'accès sont la méthode héritée pour spécifier les autorisations de vos nœuds.

* *Autoriser l'accès par défaut :* L'accès par défaut pour les nouveaux clusters est le https://cloud.google.com/compute/docs/access/service-accounts?hl=en_US#default_service_account[compte de service par défaut de Compute Engine.]
* *Autoriser un accès complet à toutes les API Cloud :* En général, vous pouvez simplement définir le scope d'accès cloud-platform pour permettre un accès complet à toutes les API Cloud, puis accorder au compte de service uniquement les rôles IAM pertinents. La combinaison des scopes d'accès accordés à l'instance de machine virtuelle et des rôles IAM accordés au compte de service détermine le niveau d'accès dont dispose le compte de service pour cette instance.
* *Définir l'accès pour chaque API :* Alternativement, vous pouvez choisir de définir des scopes spécifiques qui permettent l'accès aux méthodes API particulières que le service appellera.

Pour plus d'informations, consultez la https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[section sur l'activation des comptes de service pour une VM.]

[#_configuring_the_refresh_interval]
=== Configuration de l'intervalle de rafraîchissement

L'intervalle de rafraîchissement peut être configuré via le paramètre "gke-refresh", qui est un entier représentant des secondes.

La valeur par défaut est de 300 secondes.

L'intervalle de synchronisation peut être modifié en exécutant `kubectl edit setting gke-refresh`.

Plus la fenêtre de rafraîchissement est courte, moins il est probable que des conditions de concurrence se produisent, mais cela augmente la probabilité de rencontrer des limites de demande qui peuvent être en place pour les API GCP.
