= Création d'un cluster GKE
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/gke.adoc 
:product-path: cluster-deployment/hosted-kubernetes/gke/gke.adoc
ifeval::["{build-type}" != "community"]
:xref-sync-hosted-clusters: xref:cluster-deployment/hosted-kubernetes/sync-clusters.adoc
:xref-gke-private-clusters: xref:cluster-deployment/hosted-kubernetes/gke/private-clusters.adoc
:xref-gke-config: xref:cluster-deployment/hosted-kubernetes/gke/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-sync-hosted-clusters: xref:reference-guides/cluster-configuration/rancher-server-configuration/sync-clusters.adoc
:xref-gke-private-clusters: xref:reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/gke-private-clusters.adoc
:xref-gke-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/index.adoc
endif::[]

[#_prerequisites]
== Conditions préalables

Une configuration dans Google Kubernetes Engine est requise.

[#_service_account_token]
=== Jeton de compte de service

Créez un compte de service en utilisant https://console.cloud.google.com/projectselector/iam-admin/serviceaccounts[Google Kubernetes Engine]. GKE utilise ce compte pour faire fonctionner votre cluster. La création de ce compte génère également une clé privée utilisée pour l'authentification.

Le compte de service nécessite les rôles suivants{nbsp}:

* *Visualiseur Compute :* `roles/compute.viewer`
* *Visualiseur de projet :* `roles/viewer`
* *Administrateur Kubernetes Engine :* `roles/container.admin`
* *Utilisateur de compte de service :* `roles/iam.serviceAccountUser`

https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[Documentation Google{nbsp}: Création et activation de comptes de service]

Pour obtenir de l'aide pour obtenir une clé privée pour votre compte de service, consultez la documentation Google Cloud https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys[ici.] Vous devrez enregistrer la clé au format JSON.

[#_google_project_id]
=== ID de projet Google

Votre cluster devra faire partie d'un projet Google.

Pour créer un nouveau projet, consultez la documentation Google Cloud https://cloud.google.com/resource-manager/docs/creating-managing-projects#creating_a_project[ici.]

Pour obtenir l'ID du projet d'un projet existant, consultez la documentation Google Cloud https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects[ici.]

[#_provisioning_a_gke_cluster]
== Provisionnement d'un cluster GKE

[CAUTION]
====

Le déploiement sur GKE entraînera des frais.
====


[#_1_create_a_cloud_credential]
=== 1. Créez un identifiant cloud

. Cliquez sur *☰ > Gestion des clusters*.
. Dans la barre de navigation de gauche, cliquez sur *Identifiants Cloud*.
. Cliquez sur *Create*.
. Entrez un nom pour vos identifiants cloud Google.
. Dans la zone de texte *Compte de Service*, collez votre clé privée JSON de compte de service ou téléchargez le fichier JSON.
. Cliquez sur *Create*.

*Résultat :* Vous avez créé des identifiants que Rancher utilisera pour provisionner le nouveau cluster GKE.

[#_2_create_the_gke_cluster]
=== 2. Créez le cluster GKE

Utilisez Rancher pour configurer votre cluster Kubernetes. Pour créer avec succès un cluster GKE avec Rancher, votre GKE doit être en mode Standard. GKE a deux modes de fonctionnement lors de la création d'un cluster Kubernetes, le mode Autopilot et le mode Standard. La configuration du cluster pour le mode Autopilot a des restrictions sur l'édition de l'espace de noms kube-system. Cependant, Rancher doit créer des ressources dans l'espace de noms kube-system lors de l'installation. En conséquence, vous ne pourrez pas créer de cluster GKE en mode Autopilot. Pour plus d'informations sur la différence entre le mode Autopilot GKE et le mode Standard, visitez https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison[Comparer GKE Autopilot et Standard.]

. Cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, cliquez sur *Créer*.
. Click *Google GKE*.
. Entrez un *Nom de cluster*.
. Facultatives : Utilisez les *Rôles de membre* pour configurer l'autorisation des utilisateurs pour le cluster. Cliquez sur *Ajouter un membre* pour ajouter des utilisateurs pouvant accéder au cluster. Utilisez le menu déroulant *Rôle* pour définir les permissions pour chaque utilisateur.
. Facultatives : Ajoutez des https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[étiquettes Kubernetes] ou des https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/[annotations Kubernetes] au cluster.
. Entrez votre ID de projet Google et vos identifiants Google Cloud.
. Remplissez le reste du formulaire. Pour obtenir de l'aide, consultez la {xref-gke-config}[référence de configuration du cluster GKE.]
. Cliquez sur *Create*.

*Résultat :* Vous avez déployé avec succès un cluster GKE.

Votre cluster est créé et a un état de *Provisionnement*. Rancher est en train de mettre en place votre cluster.

Vous pouvez accéder à votre cluster après que son état soit mis à jour à *Actif*.

Les clusters *Actifs* sont assignés à deux Projets{nbsp}:

* `Default`, contenant l'espace de noms `default`
* `System`, contenant les espaces de noms `cattle-system`, `traefik`, `kube-public` et `kube-system`

[#_private_clusters]
== Clusters privés

Les clusters GKE privés sont pris en charge. Remarque : Cette configuration avancée peut nécessiter plus d'étapes lors du processus de provisionnement du cluster. Pour plus de détails, voir {xref-gke-private-clusters}[cette section.]

[#_configuration_reference]
== Référence de configuration :

Pour des détails sur la configuration des clusters GKE dans Rancher, voir {xref-gke-config}[cette page.]

[#_updating_kubernetes_version]
== Mise à jour de la version de Kubernetes

La version de Kubernetes d'un cluster peut être mise à niveau vers n'importe quelle version disponible dans la région ou la zone pour le cluster GKE. La mise à niveau de la version principale de Kubernetes ne met pas automatiquement à niveau les nœuds de travail. Les nœuds peuvent être mis à niveau indépendamment.

[NOTE]
====

GKE a supprimé l'authentification de base dans la version 1.19+. Pour mettre à niveau un cluster vers 1.19+, l'authentification de base doit être désactivée dans Google Cloud. Sinon, une erreur apparaîtra dans Rancher lors d'une tentative de mise à niveau vers 1.19+. Vous pouvez suivre la https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#disabling_authentication_with_a_static_password[documentation Google]. Après cela, la version de Kubernetes peut être mise à jour vers 1.19+ via Rancher.
====


[#_syncing]
== Synchronisation

Le provisionneur GKE peut synchroniser l'état d'un cluster GKE entre Rancher et le fournisseur. Pour une explication technique approfondie de son fonctionnement, voir {xref-sync-hosted-clusters}[Synchronisation.]

Pour des informations sur la configuration de l'intervalle de rafraîchissement, voir {xref-gke-config}#_configuring_the_refresh_interval[cette section.]

[#_programmatically_creating_gke_clusters]
== Création programmatique de clusters GKE

La manière la plus courante de déployer des clusters GKE de manière programmatique via Rancher est d'utiliser le fournisseur Terraform Rancher2. La documentation pour la création de clusters avec Terraform est https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster[ici.]
