= Sonstige Installationsmethoden
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/other-installation-methods/index.adoc 
:product-path: installation-and-upgrade/other-installation-methods/other-installation-methods.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap: xref:einsteiger/installation-und-upgrade/andere-installationsmethoden/air-gapped-helm-cli-install/index.adoc
:xref-migrate-cluster: xref:how-to-guides/neue-anleitungen/sicherung-wiederherstellung-und-notfallwiederherstellung/migration-rancher-zu-neuem-cluster.adoc
endif::[]

[#_air_gapped_installations]
== Air-Gapped-Installationen

Befolgen Sie {xref-air-gap}[diese Schritte], um den Rancher-Server in einer Air-Gapped-Umgebung zu installieren.

Eine Air-Gapped-Umgebung ist eine Umgebung, in der der Rancher-Server offline, hinter einer Firewall oder hinter einem Proxy installiert wird.

[#_docker_installations]
== Docker-Installationen

Die xref:[Einzelknoten-Docker-Installation] ist für Rancher-Nutzer gedacht, die Rancher testen möchten. Anstatt auf einem Kubernetes-Cluster mit Helm zu arbeiten, installieren Sie die Rancher-Serverkomponente auf einem einzelnen Knoten mit einem `docker run` Befehl.

Die Docker-Installation ist nur für Entwicklungs- und Testumgebungen gedacht.

Da es nur einen Knoten und einen einzelnen Docker-Container gibt, gibt es, wenn der Knoten ausfällt, keine Kopie der etcd-Daten auf anderen Knoten, und Sie verlieren alle Daten Ihres Rancher-Servers.

Der Rancher-Sicherungs-Operator kann verwendet werden, um Rancher von der Einzel-Docker-Container-Installation auf eine Installation in einem Kubernetes-Cluster mit hoher Verfügbarkeit zu migrieren. Für Details siehe die Dokumentation zu {xref-migrate-cluster}[der Migration von Rancher zu einem neuen Cluster.]
