= テンプレートの適用
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/apply-templates.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/apply-templates.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-access-share-rke1-templates: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/manage-rke1-templates.adoc
endif::[]

include::shared:ROOT:partial$en/eol-rke1-warning.adoc[]

作成したRKEテンプレートから、または{xref-access-share-rke1-templates}[共有されたテンプレート]からクラスターを作成できます。

RKEテンプレートは新しいクラスターに適用できます。

既存のクラスターの設定をRKEテンプレートとして<<_converting_an_existing_cluster_to_use_an_rke_template,保存できます。>>その後、テンプレートが更新されない限り、クラスターの設定は変更できません。

クラスターを異なるRKEテンプレートに変更することはできません。同じテンプレートの新しいリビジョンにのみクラスターを更新できます。

[#_creating_a_cluster_from_an_rke_template]
== RKEテンプレートからのクラスターの作成

RKEテンプレートを使用して{xref-launch-k8s-with-rancher}[インフラストラクチャプロバイダーによってホストされる]クラスターを追加するには、次の手順を使用します。

. 左上隅で、*☰ > クラスター管理*をクリックします。
. *クラスター*ページで、*作成*をクリックし、インフラストラクチャプロバイダーを選択します。
. クラスター名とノードテンプレートの詳細を通常通り提供します。
. RKEテンプレートを使用するには、*クラスターオプション*の下で、*既存のRKEテンプレートとリビジョンを使用する*のチェックボックスをオンにします。
. ドロップダウンメニューからRKEテンプレートとリビジョンを選択します。
. オプション:RKEテンプレートの所有者がテンプレート作成時に*ユーザーオーバーライドを許可*としてマークした設定は、編集できます。変更したい設定があるが、オプションがない場合は、テンプレートの所有者に連絡して新しいリビジョンを取得する必要があります。その後、クラスターを編集して新しいリビジョンにアップグレードする必要があります。
. *作成*をクリックしてクラスターを起動します。

[#_updating_a_cluster_created_with_an_rke_template]
== RKEテンプレートを使用して作成されたクラスターの更新

テンプレートの所有者がテンプレートを作成すると、各設定には、ユーザーがその設定を上書きできるかどうかを示すスイッチがRancher UIに表示されます。

* 設定がユーザーの上書きを許可する場合、xref:[クラスターを編集することでこれらの設定を更新できます。]
* スイッチがオフになっている場合、クラスターの所有者がそれらを上書きできるテンプレートの改訂を作成しない限り、これらの設定を変更することはできません。変更したい設定があるが、オプションがない場合は、テンプレートの所有者に連絡して新しいリビジョンを取得する必要があります。

RKEテンプレートから作成されたクラスターの場合、クラスターを編集してテンプレートの新しい改訂に更新することができます。

既存のクラスターの設定は<<_converting_an_existing_cluster_to_use_an_rke_template,RKEテンプレートとして保存できます。>>その場合、クラスターを編集してテンプレートの新しい改訂に更新することもできます。

[NOTE]
====

クラスターを異なるRKEテンプレートに変更することはできません。同じテンプレートの新しいリビジョンにのみクラスターを更新することができます。
====


[#_converting_an_existing_cluster_to_use_an_rke_template]
== 既存のクラスターをRKEテンプレートを使用するように変換する

このセクションでは、既存のクラスターからRKEテンプレートを作成する方法について説明します。

RKEテンプレートは、既存のクラスターに適用することはできません。ただし、既存のクラスターの設定をRKEテンプレートとして保存する場合を除きます。これにより、クラスターの設定が新しいRKEテンプレートとしてエクスポートされ、そのテンプレートにクラスターがバインドされます。その結果、クラスターは、{xref-manage-rke1-templates}#_updating_a_template[template is updated,] かつクラスターが{xref-manage-rke1-templates}#_upgrading_a_cluster_to_use_a_new_template_revision[use a newer version of the template.]の場合にのみ変更できます。

既存のクラスターをRKEテンプレートを使用するように変換するには、

. 左上隅で、*☰ > クラスター管理*をクリックします。
. *クラスター*ページで、RKEテンプレートを使用するように変換されるクラスターに移動します。*⋮  > RKEテンプレートとして保存*をクリックします。
. 表示されるフォームにテンプレートの名前を入力し、*作成*をクリックします。

*結果*

* 新しいRKEテンプレートが作成されます。
* クラスターは新しいテンプレートを使用するように変換されます。
* 新しいクラスターは<<_creating_a_cluster_from_an_rke_template,新しいテンプレートから作成できます。>>
