= サンプルシナリオ
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/example-use-cases.adoc 
:product-path: rancher-admin/global-configuration/rke1-templates/example-use-cases.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
:xref-access-share-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:rancher-admin/global-configuration/rke1-templates/manage-templates.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions.adoc 
:xref-access-share-rke1-templates: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/access-or-share-templates.adoc
:xref-manage-rke1-templates: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/manage-rke1-templates.adoc
endif::[]

これらの例のシナリオは、組織がテンプレートを使用してクラスターの作成を標準化する方法を説明しています。

* *テンプレートの強制:*管理者は、すべての新しいRancherによってプロビジョニングされたクラスターにその設定を持たせたい場合、<<_enforcing_a_template_setting_for_everyone,すべてのユーザーに対して1つ以上のテンプレート設定を強制することを望むかもしれません>>。
* *異なるユーザーに異なるテンプレートを共有する:*管理者は、基本ユーザーにはより制限されたオプションを持たせ、上級ユーザーにはクラスター作成時により多くの裁量を持たせるために、<<_templates_for_basic_and_advanced_users,基本ユーザーと上級ユーザーに異なるテンプレートを提供するかもしれません>>。
* *テンプレート設定の更新:*組織のセキュリティおよびDevOpsチームが新しいクラスターの必須設定にベストプラクティスを組み込むことを決定した場合、それらのベストプラクティスは時間とともに変わる可能性があります。ベストプラクティスが変更された場合、<<_updating_templates_and_clusters_created_with_them,テンプレートは新しいリビジョンに更新することができ>>、そのテンプレートから作成されたクラスターは新しいバージョンのテンプレートにアップグレードできます。
* *テンプレートの所有権の共有:*テンプレートの所有者がもはやテンプレートを維持したくない場合、またはテンプレートの所有権を委譲したい場合、このシナリオは<<_allowing_other_users_to_control_and_share_a_template,テンプレートの所有権を共有する方法を説明しています。>>

[#_enforcing_a_template_setting_for_everyone]
== すべてのユーザーに対するテンプレート設定の強制

ある組織があり、管理者がすべての新しいクラスターをKubernetesバージョン1.14で作成することを決定したとしましょう。

. まず、管理者はKubernetesバージョンを1.14として指定し、他のすべての設定を*ユーザーの上書きを許可*としてマークするテンプレートを作成します。
. 管理者はテンプレートを公開にします。
. 管理者はテンプレートの強制をオンにします。

*結果*

* 組織内のすべてのRancherユーザーはそのテンプレートにアクセスできます。
* このテンプレートを使用して作成された{xref-global-permissions}[標準ユーザー]によるすべての新しいクラスターはKubernetes 1.14を使用し、異なるKubernetesバージョンを使用することはできません。デフォルトでは、標準ユーザーはテンプレートを作成する権限がないため、他のテンプレートが共有されない限り、このテンプレートが彼らが使用できる唯一のテンプレートになります。
* すべての標準ユーザーは新しいクラスターを作成するためにクラスターのテンプレートを使用しなければなりません。テンプレートを使用せずにクラスターを作成することはできません。

このようにして、管理者は組織全体でKubernetesのバージョンを強制しつつ、エンドユーザーが他のすべてを設定できるようにしています。

[#_templates_for_basic_and_advanced_users]
== 基本ユーザーと上級ユーザーのためのテンプレート

ある組織に基本ユーザーと上級ユーザーの両方がいるとしましょう。管理者は、基本ユーザーにテンプレートの使用を義務付けたいと考えていますが、上級ユーザーと管理者は自分たちの好きなようにクラスターを作成します。

. まず、管理者がxref:./enforce-templates.adoc#_requiring_new_clusters_to_use_an_rke_template[RKEテンプレートの強制を有効にします。]これは、Rancherのすべての{xref-global-permissions}[標準ユーザー]がクラスターを作成する際にRKEテンプレートを使用する必要があることを意味します。
. 次に、管理者は2つのテンプレートを作成します：

* 基本ユーザー用のテンプレートは、アクセスキーを除いてほぼすべてのオプションが指定されています。
* 上級ユーザー用のテンプレートは、ほとんどまたはすべてのオプションが*ユーザーの上書きを許可*に設定されています。

. 管理者は上級テンプレートを上級ユーザーのみに共有します。
. 管理者は基本ユーザー用のテンプレートを公開し、より制限のあるテンプレートがRancherによってプロビジョニングされたクラスターを作成するすべての人に選択肢となるようにします。

*結果:*管理者を除くすべてのRancherユーザーは、クラスターを作成する際にテンプレートを使用する必要があります。すべての人が制限のあるテンプレートにアクセスできますが、より緩やかなテンプレートを使用する権限があるのは上級ユーザーのみです。基本ユーザーはより制限されており、上級ユーザーはKubernetesクラスターの設定においてより自由です。

[#_updating_templates_and_clusters_created_with_them]
== テンプレートとそれを使用して作成されたクラスターの更新

ある組織に、クラスターがKubernetes v1.14を使用することを要求するテンプレートがあるとしましょう。しかし、時が経つにつれて、管理者は考えを変えます。彼らは、ユーザーがクラスターを新しいバージョンのKubernetesにアップグレードできるようにしたいと決定します。

この組織では、Kubernetes v1.14を要求するテンプレートで多くのクラスターが作成されました。テンプレートがその設定をオーバーライドすることを許可していないため、クラスターを作成したユーザーはその設定を直接編集することができません。

テンプレートの所有者は、クラスターの作成者が自分のクラスターでKubernetesをアップグレードできるようにするためのいくつかのオプションを持っています：

* *テンプレートでKubernetes v1.15を指定する:*テンプレートの所有者は、Kubernetes v1.15を指定する新しいテンプレートのリビジョンを作成できます。その後、そのテンプレートを使用している各クラスターの所有者は、テンプレートの新しいリビジョンにクラスターをアップグレードできます。このテンプレートのアップグレードにより、クラスターの作成者は自分のクラスターでKubernetesをv1.15にアップグレードすることができます。
* *テンプレートで任意のKubernetesバージョンを許可します：*テンプレートのリビジョンを作成する際、テンプレートの所有者は、Rancher UIのその設定の近くにあるスイッチを使って、Kubernetesバージョンを*ユーザーの上書きを許可*としてマークすることもできます。これにより、このテンプレートリビジョンにアップグレードしたクラスターは、任意のKubernetesバージョンを使用できるようになります。
* *テンプレートで最新のマイナーKubernetesバージョンを許可する：*テンプレートの所有者は、Kubernetesバージョンが*最新のv1.14（パッチバージョンのアップグレードが可能）*として定義されたテンプレートのリビジョンを作成することもできます。これは、そのリビジョンを使用するクラスターがパッチバージョンのアップグレードできることを意味しますが、メジャーバージョンのアップグレードはできません。

[#_allowing_other_users_to_control_and_share_a_template]
== 他のユーザーがテンプレートを操作・共有できるようにする

アリスがRancherの管理者だと仮定します。彼女は、クラスターを作成するための組織で合意されたベストプラクティスを反映したRKEテンプレートを所有しています。

ボブは、クラスターの構成について適切な判断を行うことができる上級ユーザーです。アリスは、ベストプラクティスが時間の経過とともに更新されるのに伴い、ボブが彼女のテンプレートの新しいリビジョンを作成することを任せています。したがって、彼女はボブをテンプレートの所有者にすることに決めました。

ボブとテンプレートの所有権を共有するために、アリスはxref:./access-or-share-templates.adoc#_sharing_ownership_of_templates[テンプレートの所有者としてボブを追加します。]

その結果、テンプレートの所有者としてボブはそのテンプレートのバージョン管理を担当することになります。ボブは次のすべての作業を行うことができます：

* {xref-manage-rke1-templates}#_テンプレートの改訂[ベストプラクティスが変更された場合、テンプレートを修正する]
* {xref-manage-rke1-templates}#_テンプレートリビジョンの無効化[古いリビジョンを無効にし、新しいクラスターが作成できないようにする]
* {xref-manage-rke1-templates}#_テンプレートの削除[組織が異なる方向に進みたい場合、テンプレート全体を削除]
* {xref-manage-rke1-templates}#_特定のリビジョンをデフォルトとして設定[ユーザーがそれを使ってクラスターを作成する際に]テンプレートのエンドユーザーは、どのリビジョンを使用してクラスターを作成するかを選択することができます。
* {xref-access-share-rke1-templates}[特定のユーザーとテンプレートを共有する]、すべてのRancherユーザーにテンプレートを利用可能にする、または別のユーザーを所有者として追加する。
