= FAQ general
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 18-12-2025
:page-revdate: {revdate}
:community-path: faq/general-faq.adoc 
:product-path: faq/general-faq.adoc
ifeval::["{build-type}" != "community"]
:xref-istio: xref:observability/istio/istio.adoc
:xref-manage-clusters: xref:cluster-admin/manage-clusters/manage-clusters.adoc
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-use-windows-clusters: xref:cluster-deployment/custom-clusters/windows/use-windows-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio: xref:integrations-in-rancher/istio/index.adoc
:xref-manage-clusters: xref:how-to-guides/new-user-guides/manage-clusters/index.adoc
:xref-rancher-on-aks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-aks.adoc
:xref-use-windows-clusters: xref:guías-como-hacer/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/utilizar-clústeres-windows/index.adoc
endif::[]

Esta FAQ, que aún se encuentra en desarrollo, está diseñada para responder a las preguntas más frecuentes sobre Rancher v2.x.

Consulta la xref:faq/technical-items.adoc[FAQ Técnica] para preguntas técnicas frecuentes.

ifeval::["{build-type}" != "srfa"]
[#_is_it_possible_to_manage_azure_kubernetes_services_with_rancher_v2_x]
== ¿Es posible gestionar Azure Kubernetes Services con Rancher v2.x?

Sí. Consulta nuestra guía de {xref-manage-clusters}[Administración de Clústeres] para ver qué características de Rancher están disponibles en AKS, así como nuestra {xref-rancher-on-aks}[documentación sobre AKS].

[#_does_rancher_support_windows]
== ¿Rancher soporta Windows?

Sí. Rancher soporta contenedores de Windows Server 1809. Para detalles sobre cómo configurar un clúster con nodos de trabajo de Windows, consulta la sección sobre {xref-use-windows-clusters}[configuración de clústeres personalizados para Windows.]
endif::[]

[#_does_rancher_support_istio]
== ¿Rancher soporta Istio?

Sí. Rancher soporta {xref-istio}[Istio].

[#_will_rancher_v2_x_support_hashicorps_vault_for_storing_secrets]
== ¿Rancher v2.x soportará Vault de Hashicorp para almacenar secretos?

La gestión de secretos está en nuestra hoja de ruta, pero aún no la hemos asignado a una versión específica.

[#_does_rancher_v2_x_support_rkt_containers_as_well]
== ¿Rancher v2.x soporta contenedores RKT también?

En este momento, solo soportamos Docker.

[#_does_rancher_v2_x_support_calico_contiv_contrail_flannel_weave_net_etc_for_embedded_and_registered_kubernetes]
== ¿Rancher v2.x soporta Calico, Contiv, Contrail, Flannel, Weave net, etc., para Kubernetes embebido y registrado?

Listo para usar, Rancher proporciona los siguientes proveedores de red CNI para clústeres de Kubernetes: Canal, Flannel, Calico y Weave.  Siempre consulta la https://rancher.com/support-maintenance-terms/[Matriz de Soporte de Rancher] para detalles sobre lo que está oficialmente soportado.

[#_are_you_planning_on_supporting_traefik_for_existing_setups]
== ¿Estás planeando dar soporte a Traefik para configuraciones existentes?

Actualmente no planeamos proporcionar soporte integrado para Traefik, pero seguimos explorando enfoques de balance de la carga.

[#_can_i_import_openshift_kubernetes_clusters_into_v2_x]
== ¿Puedo importar clústeres de Kubernetes de OpenShift en v2.x?

Nuestro objetivo es ejecutar cualquier clúster de Kubernetes. Por lo tanto, Rancher v2.x debería funcionar con OpenShift, pero aún no lo hemos probado.

[#_is_longhorn_product_name_integrated_with_rancher]
== ¿Está {longhorn-product-name} integrado con Rancher?

Sí. Longhorn está integrado con Rancher v2.5 y versiones posteriores.
