= Preguntas frecuentes sobre seguridad
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: faq/security.adoc 
:product-path: faq/security.adoc
ifeval::["{build-type}" != "community"]
:xref-security-overview: xref:security/security-overview.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-security-overview: xref:reference-guides/rancher-security/index.adoc
endif::[]

[#_is_there_a_hardening_guide]
== ¿Hay una guía de protección?

La guía de protección se encuentra en la sección principal {xref-security-overview}[Seguridad].

[#_have_hardened_rancher_kubernetes_clusters_been_evaluated_by_the_cis_kubernetes_benchmark_where_can_i_find_the_results]
== ¿Se han evaluado los clústeres de Kubernetes de Rancher protegidos según el estándar CIS de Kubernetes? ¿Dónde puedo encontrar los resultados?

Hemos ejecutado el estándar CIS de Kubernetes contra un clúster de Kubernetes de Rancher protegido.  Los resultados de esa evaluación se pueden encontrar en la sección principal {xref-security-overview}[Seguridad].

[#_how_does_rancher_verify_communication_with_downstream_clusters_and_what_are_some_associated_security_concerns]
== ¿Cómo verifica Rancher la comunicación con los clústeres descendentes y cuáles son algunas preocupaciones de seguridad asociadas?

La comunicación entre el servidor de Rancher y los clústeres descendentes se realiza a través de agentes. Rancher utiliza un paquete de autoridad de certificación (CA) registrado o la tienda de confianza local para verificar la comunicación entre los agentes de Rancher y el servidor de Rancher. Utilizar un paquete de CA para la verificación es más estricto, ya que solo se confían los certificados basados en ese paquete. Si la verificación TLS para un paquete de CA explícito falla, Rancher puede recurrir a utilizar la tienda de confianza local para verificar la comunicación futura. Cualquier CA dentro de la tienda de confianza local puede ser utilizada para generar un certificado válido.

Como se describe en https://www.suse.com/c/rancher-security-update/[Actualización de seguridad de Rancher CVE-2024-22030], bajo un conjunto limitado de circunstancias, actores maliciosos pueden tomar el control de los nodos de Rancher explotando el comportamiento de las CAs de Rancher. Para que el ataque tenga éxito, el actor malicioso debe generar un certificado válido de una CA válida en el servidor de Rancher objetivo, o de una CA registrada válida. El atacante también necesita secuestrar o suplantar la URL del servidor de Rancher como un paso preliminar. Rancher está evaluando actualmente el comportamiento de la CA de Rancher para mitigar este y cualquier otro tipo de ataque similar.
