= DÃĐpannage des nÅuds Controlplane
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/kubernetes-components/troubleshooting-controlplane-nodes.adoc 
:product-path: troubleshooting/kubernetes-components/troubleshooting-controlplane-nodes.adoc

Cette section s'applique aux nÅuds ayant le rÃīle `controlplane`.

[#_check_if_the_controlplane_containers_are_running]
== VÃĐrifiez si les conteneurs Controlplane sont en cours d'exÃĐcution

Il y a trois conteneurs spÃĐcifiques lancÃĐs sur les nÅuds ayant le rÃīle `controlplane`{nbsp}:

* `kube-apiserver`
* `kube-controller-manager`
* `kube-scheduler`

Les conteneurs doivent avoir le statut *En cours*. La durÃĐe affichÃĐe aprÃĻs *En cours* est le temps pendant lequel le conteneur a ÃĐtÃĐ en cours d'exÃĐcution.

----
docker ps -a -f=name='kube-apiserver|kube-controller-manager|kube-scheduler'
----

Exemple de sortieÂ :

----
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
26c7159abbcc        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-apiserver
f3d287ca4549        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-scheduler
bdf3898b8063        rancher/hyperkube:v1.11.5-rancher1   "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                              kube-controller-manager
----

[#_controlplane_container_logging]
== Journalisation des conteneurs Controlplane

[NOTE]
====

Si vous avez ajoutÃĐ plusieurs nÅuds avec le rÃīle `controlplane`, `kube-controller-manager` et `kube-scheduler` utilisent un processus d'ÃĐlection du leader pour dÃĐterminer le leader. Seul le leader actuel enregistrera les actions effectuÃĐes. Voir xref:troubleshooting/other-troubleshooting-tips/kubernetes-resources.adoc#_kubernetes_leader_election[ÃĐlection de leader Kubernetes] pour savoir comment rÃĐcupÃĐrer le leader actuel.
====


La journalisation des conteneurs peut contenir des informations sur ce que pourrait ÃŠtre le problÃĻme.

----
docker logs kube-apiserver
docker logs kube-controller-manager
docker logs kube-scheduler
----

[#__rke2_product_name_server_logging]
== {rke2-product-name} Journalisation du serveur

Si Rancher provisionne un cluster RKE2 qui ne peut pas communiquer avec Rancher, vous pouvez exÃĐcuter cette commande sur un nÅud serveur dans le cluster en aval pour obtenir les journaux du serveur RKE2{nbsp}:

----
journalctl -u rke2-server -f
----
