= Configuração do Template de Nó do Azure
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guias-de-referência/configuração-do-cluster/downstream-cluster-configuração/configuração-do-template-de-nó/azure.adoc 
:product-path: cluster-deployment/infra-providers/azure/node-template-configuration.adoc

Para mais informações sobre o Azure, consulte a https://docs.microsoft.com/en-us/azure/?product=featured[documentação oficial do Azure.]

As informações de acesso à conta são armazenadas como uma credencial em nuvem. As credenciais em nuvem são armazenadas como segredos do Kubernetes. Vários templates de nó podem usar a mesma credencial em nuvem. Você pode usar uma credencial em nuvem existente ou criar uma nova.

* *Placement* define a região geográfica onde seu cluster está hospedado e outros metadados de localização.
* *Network* configura a rede utilizada em seu cluster.
* *Instance* personaliza a configuração da sua VM.
+

[NOTE]
====
Se estiver usando uma VNet em um Grupo de Recursos diferente das VMs, o nome da VNet deve ser precedido pelo nome do Grupo de Recursos. Por exemplo, `<resource group>:<vnet>`.
====


Se você usar o Docker, as opções de configuração do https://docs.docker.com/engine/docker-overview/#the-docker-daemon[daemon do Docker] incluem:

* *Rótulos:* Para informações sobre rótulos, consulte a https://docs.docker.com/config/labels-custom-metadata/[documentação de rótulos de objetos do Docker.].
* *URL de Instalação do Docker Engine:* Determina qual versão do Docker será instalada na instância.
+

[NOTE]
====
Se você estiver provisionando nós do Red Hat Enterprise Linux (RHEL) ou CentOS, deixe o campo *URL de instalação do Docker* como o valor padrão ou selecione *nenhum*. Isso ignorará uma verificação para a instalação do Docker, já que o Docker já está instalado nesses tipos de nós.

Se você definir *URL de instalação do Docker* para um valor diferente do padrão ou *nenhum*, pode ver uma mensagem de erro como a seguinte: `Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`
====


* *Espelhos de registro:* Espelho do registro do Docker a ser usado pelo daemon do Docker.
* *Outras opções avançadas:* Consulte a https://docs.docker.com/engine/reference/commandline/dockerd/[referência de opções do daemon do Docker].
