= Erstellen eines Google Compute Engine-Clusters
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: anleitungen/neue-benutzeranleitungen/kubernetes-mit-rancher-starten/neue-knoten-in-einem-infrastruktur-anbieter-nutzen/google-compute-engine-cluster-erstellen.adoc 
:product-path: cluster-deployment/infra-providers/gce/gce.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-infra-gce-machine-config: xref:cluster-deployment/infra-providers/gce/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc
:xref-infra-gce-machine-config: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/google-gce.adoc
endif::[]

In diesem Abschnitt lernen Sie, wie Sie Rancher verwenden, um ein {url-rke2-landing-page}[RKE2] oder {url-k3s-landing-page}[K3s] Kubernetes-Cluster auf der Google Cloud Platform (GCP) mithilfe von Google Compute Engine (GCE) über Rancher bereitzustellen.

Zuerst aktivieren Sie den GCE-Knotentreiber in der Rancher-Benutzeroberfläche. Dann folgen Sie den Schritten, um ein GCP-Dienstkonto mit den erforderlichen Berechtigungen zu erstellen und eine JSON-Schlüsseldatei zu generieren. Diese Schlüsseldatei wird verwendet, um eine Cloud-Anmeldeinformation in Rancher zu erstellen. 

Dann erstellen Sie ein GCE-Cluster in Rancher, und beim Konfigurieren des Clusters definieren Sie Maschinenpools dafür. Jeder Maschinenpool hat eine Kubernetes-Rolle von etcd, controlplane oder worker. Rancher installiert RKE2 auf den neuen Knoten und richtet jeden Knoten mit der durch den Maschinenpool definierten Kubernetes-Rolle ein.

. <<_enable_the_gce_node_driver>>
. <<_create_a_cloud_credential>>
. <<_create_a_cluster_using_the_cloud_credential>>
. <<_gce_best_practices>>

[#_prerequisites]
== Voraussetzungen

.  Ein gültiges Google Cloud Platform-Konto und Projekt.
.  Eine JSON-Schlüsseldatei für das GCP-Dienstkonto. Das mit diesem Schlüssel verbundene Dienstkonto muss über die folgenden IAM-Rollen verfügen:
.. **Compute Admin**
.. **Service Account User**
.. **Vorschau**
. Ein VPC-Netzwerk, um VMs bereitzustellen. 

Siehe die https://cloud.google.com/iam/docs/service-account-overview[GCP-Dokumentation] zum Erstellen und Verwalten von Dienstkontoschlüsseln für weitere Details.

[#_enable_the_gce_node_driver]
== Aktivieren Sie den GCE-Knotentreiber

Der GCE-Knotentreiber ist standardmäßig nicht in Rancher aktiviert. Sie müssen ihn aktivieren, bevor Sie GCE-Cluster bereitstellen oder mit GCE-spezifischen CRDs arbeiten können.

. Klicken Sie auf **☰ > Clusterverwaltung**.
. Klicken Sie auf der linken Seite auf **Treiber**.
. Öffnen Sie die Registerkarte **Knotentreiber**.
. Suchen Sie den **Google GCE**-Treiber und wählen Sie **⋮ > Aktivieren** aus.

[#_create_a_cloud_credential]
== Erstellen Sie eine Cloud-Anmeldeinformation.

. Klicken Sie auf **☰ > Clusterverwaltung**.
. Klicken Sie auf **Cloud-Anmeldeinformationen**.
. Klicken Sie auf **Erstellen**.
. Klicken Sie auf **Google**.
. Geben Sie Ihre GCP-Dienstkonto-JSON-Schlüsseldatei ein.
. Klicken Sie auf **Erstellen**.

**Ergebnis:** Sie haben die Cloud-Anmeldeinformationen erstellt, die zur Bereitstellung von Knoten in Ihrem Cluster verwendet werden. Sie können diese Anmeldeinformationen in anderen Clustern wiederverwenden. Je nach den Berechtigungen, die dem Dienstkonto erteilt wurden, können diese Cloud-Anmeldeinformationen auch für GKE-Cluster verwendet werden.

[#_create_a_cluster_using_the_cloud_credential]
== Erstellen Sie einen Cluster mit der Cloud-Anmeldeinformation.

. Klicken Sie auf **☰ > Clusterverwaltung**.
. Klicken Sie auf der **Clusters**-Seite auf **Erstellen**.
. Klicken Sie auf **Google GCE**.
. Wählen Sie eine **Cloud-Anmeldeinformation** aus und geben Sie das GCP-Projekt an, um die VM zu erstellen.
. Geben Sie einen **Clustername** ein.
. Erstellen Sie einen Maschinenpool für jede Kubernetes-Rolle. Beziehen Sie sich auf die [Best Practices](use-new-nodes-in-an-infra-provider.md#node-roles) für Empfehlungen zu Rollenverteilungen und -anzahlen.
.. Definieren Sie die Maschinenkonfiguration für jeden Maschinenpool. Beziehen Sie sich auf die {xref-infra-gce-machine-config}[Google GCE Maschinenkonfigurationsreferenz] für Informationen zu Konfigurationsoptionen.
. Verwenden Sie die **Cluster-Konfiguration**, um die Version von Kubernetes auszuwählen, die installiert werden soll, welchen Netzwerkprovider verwendet werden soll und ob Sie die Projekt-Netzwerkisolierung aktivieren möchten. Für Hilfe bei der Konfiguration des Clusters verweisen Sie auf die {xref-rke2-config}[RKE2] und {xref-k3s-config}[K3s] Cluster-Konfigurationsreferenzen.
. Verwenden Sie **Mitgliederrollen**, um die Benutzerautorisierung für den Cluster zu konfigurieren. Klicken Sie auf **Mitglied hinzufügen**, um Benutzer hinzuzufügen, die auf den Cluster zugreifen können. Verwenden Sie das **Rolle**-Dropdown, um die Berechtigungen für jeden Benutzer festzulegen.
. Klicken Sie auf **Erstellen**.

**Ergebnis:**

Ihr Cluster wurde erstellt und hat den Status **Bereitstellung** erhalten. Rancher richtet Ihren Cluster ein.

Sie können auf Ihren Cluster zugreifen, nachdem sein Status auf **Aktiv** aktualisiert wurde.

**Aktiven** Cluster werden zwei Projekten zugewiesen:

* `Default`, der den `default` Namespace enthält
* `System`, der die `cattle-system`, `traefik`, `kube-public` und `kube-system` Namespaces enthält

[#_gce_best_practices]
== GCE Best Practices

[#_external_firewall_rules_open_ports_and_ace]
=== Externe Firewall-Regeln, offene Ports und ACE

Wenn der bereitgestellte Cluster die {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[Authorized Cluster Endpoint (ACE)-Funktion] nutzen wird, müssen die Controlplane-Knoten den Port `6443` freigeben. Dieser Port ist in der Standardkonfiguration des Maschinenpools nicht freigegeben, um zu verhindern, dass er über alle Cluster-Knoten hinweg exponiert wird, und um die Anzahl der von Rancher erstellten Firewall-Regeln zu reduzieren.

Damit ACE wie erwartet funktioniert, müssen Sie diesen Port in der Rancher-Benutzeroberfläche angeben, wenn Sie den Maschinenpool für die Controlplane konfigurieren, indem Sie das `Expose external ports` Kontrollkästchen im Abschnitt `Show Advanced` der Benutzeroberfläche zur Maschinenpoolkonfiguration aktivieren. Alternativ können Sie manuell eine benutzerdefinierte Firewall-Regel in GCP erstellen und das zugehörige Netzwerk-Tag in der Konfiguration des Maschinenpools der Controlplane angeben.

[#_internal_firewall_rules]
=== Interne Firewall-Regeln

Rancher erstellt automatisch eine Firewall-Regel und ein Netzwerk-Tag, um die Kommunikation zwischen den Cluster-Knoten intern innerhalb des angegebenen VPC-Netzwerks zu erleichtern. Diese Regel enthält die minimale Anzahl von Ports, die erforderlich sind, um einen RKE2/K3s-Cluster zu erstellen.

Wenn Sie die Anzahl der intern zwischen den Cluster-Knoten freigegebenen Ports erweitern müssen, sollte eine neue Firewall-Regel manuell erstellt und das zugehörige Netzwerk-Tag den relevanten Maschinenpools zugewiesen werden. Falls gewünscht, kann die automatische Erstellung der internen Firewall-Regel für jeden gegebenen Maschinenpool beim Erstellen oder Aktualisieren des Clusters deaktiviert werden.

[#_cross_network_deployments]
=== Cross-Network-Bereitstellungen

Obwohl es möglich ist, verschiedene Maschinenpools in unterschiedlichen VPC-Netzwerken bereitzustellen, unterstützt die von Rancher standardmäßig erstellte interne Firewall-Regel diese Konfiguration nicht. Um Maschinenpools in verschiedenen Netzwerken zu erstellen, müssen zusätzliche Firewall-Regeln manuell erstellt werden, um die Kommunikation zwischen Knoten in verschiedenen Netzwerken zu ermöglichen.

[#_optional_next_steps]
== Optionale nächste Schritte

Nach der Erstellung Ihres Clusters können Sie über die Rancher-Benutzeroberfläche darauf zugreifen. Als bewährte Praxis empfehlen wir, diese alternativen Möglichkeiten zum Zugriff auf Ihren Cluster einzurichten:

* **Zugriff auf Ihren Cluster mit der kubectl Kommandozeilenschnittstelle:** Befolgen Sie {xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[diese Schritte], um mit kubectl von Ihrer Workstation aus auf Cluster zuzugreifen. In diesem Fall werden Sie über den Authentifizierungsproxy des Rancher-Servers authentifiziert, dann wird Rancher Sie mit dem Downstream-Cluster verbinden. Diese Methode ermöglicht es Ihnen, den Cluster ohne die Rancher-Benutzeroberfläche zu verwalten.
* **Greifen Sie mit der kubectl-Kommandozeilenschnittstelle auf Ihren Cluster zu, indem Sie den autorisierten Cluster-Endpunkt verwenden:** Befolgen Sie {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[diese Schritte], um direkt mit kubectl auf Ihren Cluster zuzugreifen, ohne sich über Rancher zu authentifizieren. Wir empfehlen, diese alternative Methode einzurichten, um auf Ihren Cluster zuzugreifen, damit Sie, falls Sie sich nicht mit Rancher verbinden können, dennoch auf den Cluster zugreifen können.
