= GCE Maschinenkonfiguration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/google-gce.adoc 
:product-path: cluster-deployment/infra-providers/gce/machine-configuration.adoc

Für weitere Informationen über die Google Cloud Platform (GCP) und die Google Compute Engine (GCE) siehe die offizielle https://cloud.google.com/docs[GCP-Dokumentation].

[#_basic_options]
== Grundlegende Optionen

[#_zone]
=== Zone

Die GCP-Region und -Zone, in der die VM bereitgestellt wird. Beispiel: `us-east1-b`. 

[#_machine_image_project]
=== Maschinenabbild-Projekt

Das Maschinenabbildprojekt, zu dem die gewünschten Maschinenabbildfamilien gehören.

[#_machine_image_family]
=== Maschinenabbild-Familie

Die Maschinenabbildfamilie, zu der das gewünschte Betriebssystem gehört.

[#_machine_image]
=== Maschinenabbild

Das Betriebssystem, das auf der VM installiert wird.

[#_disk_type]
=== Festplattentyp

Der Typ der an die VM angeschlossenen Festplatte. Die verfügbaren Typen können zwischen den Regionen variieren.

[#_disk_size]
=== Festplattengröße

Die Größe der an die VM angeschlossenen Festplatte, in Gigabyte.

[#_machine_type]
=== Computertyp

Der Typ der VM, die bereitgestellt wird. Maschinentypen bestimmen die Anzahl der Ressourcen (vCPU, RAM usw.), die jedem Knoten zugewiesen werden.

[#_network]
=== Netzwerk

Das VPC-Netzwerk, in dem die VM erstellt wird. Dieser Wert kann nicht geändert werden, sobald der Maschinenpool bereitgestellt wurde.

[#_subnet]
=== Teilnetz

Das VPC-Subnetz, in dem die VM erstellt wird. Dieser Wert kann nicht geändert werden, sobald der Maschinenpool bereitgestellt wurde.

[#_username]
=== Benutzername

Ein benutzerdefinierter Benutzername, der als Standardbenutzer der GCE-VM festgelegt ist. 

[#_external_address]
=== Externe Adresse

Die gewünschte externe IP-Adresse für die GCE-VM.

[#_scopes]
=== Bereiche

Eine Liste von OAuth2-Berechtigungen, die der VM den Zugriff auf andere GCP-APIs ermöglichen.

[#_allow_internal_communication]
=== Interne Kommunikation erlauben

Standardmäßig wird eine VPC-Firewallregel automatisch erstellt, um einen festen Satz von Ports innerhalb der VPC freizugeben, um die Kommunikation zwischen den Clusterknoten zu erleichtern. Dieses Verhalten kann auf Basis des Maschinenpools deaktiviert werden, indem Sie die `Show Advanced`-Option auswählen und das `Allow Internal Communication`-Kontrollkästchen deaktivieren. 

[#_expose_external_ports]
=== Externe Ports freigeben

Eine Liste von Ports, die _extern_ für das breitere Internet geöffnet werden sollen. Offene Ports werden auf der Ebene des Maschinenpools definiert. Die Aktivierung dieser Option führt zur automatischen Erstellung einer VPC-Firewallregel. Diese Regel wird automatisch gelöscht, wenn der Cluster oder der Maschinenpool gelöscht wird.

[#_network_tags]
=== Netzwerk-Tags

Tags ist eine Liste von _Netzwerktags_, die verwendet werden kann, um vorhandene Firewallregeln mit allen VMs innerhalb eines Maschinenpools zu verknüpfen.

[#_labels]
=== Labels

Eine durch Kommas getrennte Liste von benutzerdefinierten Labels, die allen VMs innerhalb eines bestimmten Maschinenpools zugeordnet werden sollen. Im Gegensatz zu Tags beeinflussen Labels das Netzwerkverhalten nicht und dienen nur der Organisation von Cloud-Ressourcen.

[#_advanced_options]
== Erweiterte Optionen

Beim Erstellen von Clustern über die Rancher-Benutzeroberfläche werden einige Optionen automatisch für Sie konfiguriert. Wenn Sie jedoch Maschinenkonfigurationsobjekte manuell erstellen, müssen Sie sicherstellen, dass Sie die folgenden Felder korrekt konfigurieren.

[#_external_firewall_rule_prefix]
=== external-firewall-rule-prefix

Ein Präfix, das beim Erstellen der Firewallregel verwendet wird, um Ports öffentlich freizugeben. Idealerweise sollte dies eine Verkettung des Namens des Maschinenpools und des Namens des Clusters sein. Dieses Feld muss gesetzt werden, wenn der Maschinenpool so konfiguriert ist, dass er Ports öffentlich freigibt, andernfalls kann es weggelassen werden.

[#_internal_firewall_rule_prefix]
=== internal-firewall-rule-prefix

Ein Präfix, das beim Erstellen der internen Firewallregel verwendet wird, die die Kommunikation zwischen den Knoten innerhalb des Clusters ermöglicht. Wenn dieses Feld weggelassen wird, wird keine interne Firewallregel erstellt.

