= Configurando a Senha de Inicialização
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/bootstrap-password.adoc 
:product-path: installation-and-upgrade/resources/bootstrap-password.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-users-and-groups: xref:rancher-admin/users/authn-and-authz/manage-users-and-groups.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-users-and-groups: xref:procedimentos/novos-guias-de-usuario/permissoes-de-autenticacao-e-configuração-global/configuração-de-autenticacao/gerenciar-usuarios-e-grupos.adoc
endif::[]

Quando você instala o Rancher, pode definir uma senha de inicialização para a primeira conta de administrador.

Se você optar por não definir uma senha de inicialização, o Rancher gera aleatoriamente uma senha de inicialização para a primeira conta de administrador.

Para detalhes sobre como definir a senha de inicialização, veja abaixo.

[#_password_requirements]
== Requisitos de Senha

A senha de inicialização pode ter qualquer comprimento.

Quando você redefinir a senha da primeira conta de administrador após o primeiro login, a nova senha deve ter pelo menos 12 caracteres de comprimento.

Você pode {xref-users-and-groups}#_minimum_password_length[personalizar o comprimento mínimo da senha] para contas de usuário, dentro de limitações.

O comprimento mínimo da senha pode ser qualquer valor inteiro positivo entre 2 e 256. Valores decimais e zeros à esquerda não são permitidos.

[#_specifying_the_bootstrap_password]
== Especificando a Senha de Inicialização

Durante {xref-install-rancher}[instalação do Rancher], defina `bootstrapPassword` junto com quaisquer outras flags para o Helm chart do Rancher. Por exemplo:

[,bash]
----
helm install rancher rancher-<chart-repo>/rancher \
  --set bootstrapPassword=<password>
----

## Recuperando a Senha de Inicialização

A senha de inicialização é armazenada nos logs do contêiner Docker. Após a instalação do Rancher, a interface do usuário mostra instruções sobre como recuperar a senha com base no seu método de instalação. 

[,bash]
----
kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{ .data.bootstrapPassword|base64decode}}{{ "\n" }}'
----
