= Sobre Certificados Raiz CA Personalizados
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/custom-ca-root-certificates.adoc 
:product-path: installation-and-upgrade/resources/custom-ca-root-certificates.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
endif::[]

Se você estiver usando o Rancher em um ambiente de produção interno onde não está expondo apps publicamente, use um certificado de uma autoridade certificadora (CA) privada.

Os serviços que o Rancher precisa acessar às vezes são configurados com um certificado de uma CA raiz personalizada/interna, também conhecido como certificado autoassinado. Se o certificado apresentado pelo serviço não puder ser validado pelo Rancher, o seguinte erro será exibido: `x509: certificate signed by unknown authority`.

Para validar o certificado, os certificados CA raiz precisam ser adicionados ao Rancher. Como o Rancher é escrito em Go, podemos usar a variável de ambiente `SSL_CERT_DIR` para apontar para o diretório onde os certificados CA raiz estão localizados no contêiner. O diretório dos certificados CA raiz pode ser montado usando a opção de volume do Docker (`-v host-source-directory:container-destination-directory`) ao iniciar o contêiner do Rancher.

Exemplos de serviços que o Rancher pode acessar:

* Catálogos
* Provedores de autenticação
* Acessando a API de hospedagem/nuvem ao usar drivers de nó

[#_installing_with_the_custom_ca_certificate]
== Instalando com o Certificado CA personalizado

Para detalhes sobre como iniciar um contêiner do Rancher com seus certificados CA privados montados, consulte a documentação de instalação:

* {xref-helm-chart-options}#_additional_trusted_cas[Opções de instalação do Kubernetes para CAs confiáveis adicionais]
