= Doble pila IPv4/IPv6
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-02-18
:page-revdate: {revdate}
:community-path: reference-guides/dual-stack.adoc 
:product-path: cluster-deployment/dual-stack.adoc
ifeval::["{build-type}" != "community"]
:url-k3s-faq: https://documentation.suse.com/cloudnative/k3s/latest/en/faq.html#_does_k3s_support_window
:url-rke2-networking: https://documentation.suse.com/cloudnative/rke2/latest/en/networking/basic_network_options.html
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-custom-clusters: xref:cluster-deployment/custom-clusters/custom-clusters.adoc
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-infra-aws: xref:cluster-deployment/infra-providers/aws/aws.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-digitalocean: xref:cluster-deployment/infra-providers/digitalocean/digitalocean.adoc
:xref-digitalocean-machine-configuration: xref:cluster-deployment/infra-providers/digitalocean/machine-configuration.adoc
:xref-aws-machine-configuration: xref:cluster-deployment/infra-providers/aws/machine-configuration.adoc
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-faq: https://docs.k3s.io/faq#does-k3s-support-windows
:url-rke2-networking: https://docs.rke2.io/networking/basic_network_options
:xref-rke2-config: xref:guías-de-referencia/configuración-de-cluster/configuración-del-servidor-rancher/configuración-del-cluster-rke2.adoc
:xref-custom-clusters: xref:guías-de-referencia/configuración-de-cluster/configuración-del-servidor-rancher/utilizar-nodos-existentes/index.adoc
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-infra-aws: xref:instrucciones/nuevos-usuarios/guías-de-nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/crear-un-cluster-amazon-ec2.adoc
:xref-k3s-config: xref:guías-de-referencia/configuración-de-cluster/configuración-del-servidor-rancher/configuración-del-cluster-k3s.adoc
:xref-digitalocean: xref:instrucciones/nuevos-usuarios/guías-de-nuevos-usuarios/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/crear-un-cluster-digitalocean.adoc
:xref-digitalocean-machine-configuration: xref:guías-de-referencia/configuración-de-cluster/configuración-del-cluster-descendente/configuración-de-máquina/digitalocean.adoc
:xref-aws-machine-configuration: xref:guías-de-referencia/configuración-de-cluster/configuración-del-cluster-descendente/configuración-de-máquina/amazon-ec2.adoc
:xref-node-reqs: xref:guías-como/nuevos-usuarios/guías-de-nuevos-usuarios/clusteres-kubernetes-en-configuración-de-rancher/requisitos-de-nodo-para-clusters-gestionados-por-rancher.adoc
endif::[]

Kubernetes admite configuraciones de red solo IPv4, solo IPv6 y de doble pila. Para más detalles, consulta la documentación oficial de https://kubernetes.io/docs/concepts/services-networking/dual-stack/[Kubernetes].

[#_installing_rancher_on_ipv6_only_or_dual_stack_clusters]
== Instalando Rancher en clústeres solo IPv6 o de doble pila

Rancher puede ejecutarse en clústeres que utilizan:

* Solo IPv4
* Solo IPv6
* Doble pila (IPv4 + IPv6)

Cuando instalas Rancher en un *clúster solo IPv6*, puede comunicarse externamente *solo a través de IPv6*. Esto significa que puede aprovisionar:

* Clústeres solo IPv6
* Clústeres de pila doble
  __(no son posibles clústeres descendentes solo IPv4 en este caso)__

Cuando instalas Rancher en un *clúster de pila doble*, puede comunicarse tanto por IPv4 como por IPv6, y por lo tanto puede aprovisionar:

* Clústeres solo IPv4
* Clústeres solo IPv6
* Clústeres de pila doble

Para los pasos de instalación, consulta la guía: {xref-install-upgrade}[*Instalando y Actualizando Rancher*].

[#_requirement_for_the_rancher_server_url]
=== Requisito para la URL del servidor Rancher

Al aprovisionar clústeres descendentes solo IPv6, la *URL del servidor Rancher debe ser accesible a través de IPv6* porque los nodos descendentes se conectan de nuevo al servidor Rancher utilizando IPv6.

[#_provisioning_ipv6_only_or_dual_stack_clusters]
== Aprovisionando clústeres solo IPv6 o de pila doble

Puedes aprovisionar clústeres RKE2 y K3s *Controlador de nodo* (grupos de máquinas) o *Clúster personalizado* (hosts existentes) utilizando redes solo IPv4, solo IPv6 o de pila doble.

[#_network_configuration]
=== configuración de la red

Para habilitar redes solo IPv6 o de pila doble, debes configurar:

* CIDR de clúster
* CIDR de servicio
* Preferencia de pila

Referencias de configuración:

* {xref-k3s-config}[Referencia de configuración del clúster K3s]
* {xref-rke2-config}[Referencia de configuración del clúster RKE2]

[#_support_for_windows]
=== Compatible con Windows

Kubernetes en Windows:

|===
| Función | Estado de soporte

| Clústeres solo IPv6
| No compatible

| Clústeres de pila doble
| Admitido

| Servicios
| Limitado a una única familia de IP
|===

Para más información, consulta la https://kubernetes.io/docs/concepts/services-networking/dual-stack/#windows-support[documentación de Kubernetes].

K3s *no* es compatible con Windows ({url-k3s-faq}[FAQ])

RKE2 es compatible con Windows, pero requiere usar `Calico` o `Flannel` como CNI.
Ten en cuenta que las instalaciones de RKE2 en Windows no son compatibles con clústeres de doble pila utilizando BGP.
Para más detalles, consulta {url-rke2-networking}[Opciones de red de RKE2].


[#_provisioning_node_driver_clusters]
=== Provisionamiento de clústeres de controladores de nodo

Rancher actualmente admite la asignación de direcciones IPv6 en clústeres de *controlador de nodo* con:

* {xref-aws-machine-configuration}[Amazon EC2]
* {xref-digitalocean-machine-configuration}[DigitalOcean]

El soporte para proveedores adicionales se introducirá en futuras versiones.

[NOTE]
.Limitación de DigitalOcean
====
Crear un **clúster solo IPv6** utilizando el controlador de nodos de DigitalOcean actualmente **no está soportado**. Para más detalles, por favor consulta https://github.com/rancher/rancher/issues/52523#issuecomment-3457803572[rancher/rancher#52523].
====

[#_infrastructure_requirements]
==== Requisitos de infraestructura

Los nodos del clúster deben cumplir con los requisitos listados en {xref-node-reqs}[Requisitos de Nodo para Clústeres downstream de Rancher].

Guías de configuración de grupos de máquinas:

* {xref-infra-aws}[Amazon EC2]
* {xref-digitalocean}[DigitalOcean]

[#_provisioning_custom_clusters]
=== Provisionamiento de Clústeres Personalizados

Para aprovisionar en tus propios nodos, sigue las instrucciones en {xref-custom-clusters}[Provisionar Kubernetes en Nodos Existentes].

[NOTE]
====
* Los campos *IP Pública del Nodo* y *IP Privada del Nodo* aceptan IPv4, IPv6, o ambos (separados por comas).
    >   Ejemplo: `10.0.0.5,2001:db8::1`
* En clústeres *solo IPv6* y *de doble pila*, especifica la *dirección IPv6 del nodo* como la *IP Privada*.
====

[#_infrastructure_requirements_1]
==== Requisitos de Infraestructura

Los requisitos de infraestructura son los mismos que los anteriores para clústeres con controlador de nodos.

[#_limitations]
== limitaciones

ifeval::["{build-type}" == "product"]
[IMPORTANT]
====
Consulta la https://scc.suse.com/rancher-docs/rancherprime/latest/en/suse-rancher-prime/ https://scc.suse.com/rancher-docs/rancherprime/latest/en/suse-rancher-prime/dual-stack.html[documentación de Doble Pila IPv4/IPv6 Prime] para limitaciones adicionales respecto al soporte de URL solo IPv6 de Prime.
====
endif::[]

[#_github_com]
=== GitHub.com

GitHub.com *no* soporta IPv6. Como resultado:

* Cualquier repositorio de aplicación ( `ClusterRepo.catalog.cattle.io/v1` CR) alojado en GitHub.com *no es accesible* desde clústeres solo IPv6.
* De manera similar, cualquier *controlador de nodo no incorporado* alojado en GitHub.com también *no es accesible* en entornos solo IPv6.
