= Überschreiben des Standardlimits für einen Namespace
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-08
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/override-default-limit-in-namespaces.adoc 
:product-path: cluster-admin/project-admin/project-resource-quotas/override-default-limit-in-namespaces.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-projects-and-namespaces: xref:cluster-admin/manage-clusters/projects-and-namespaces.adoc
:xref-resource-quota-types: xref:cluster-admin/project-admin/project-resource-quotas/resource-quota-types.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-projects-and-namespaces: xref:how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces.adoc
:xref-resource-quota-types: xref:how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/resource-quota-types.adoc
endif::[]

Obwohl das *Standardlimit des Namespace* beim Erstellen vom Projekt auf jeden Namespace propagiert wird, müssen Sie in einigen Fällen die Quoten für einen bestimmten Namespace erhöhen (oder verringern). In dieser Situation können Sie die Standardlimits durch Bearbeiten des Namespace überschreiben.

In dem untenstehenden Diagramm hat der Rancher-Administrator eine Ressourcenquote für sein Projekt in Kraft. Der Administrator möchte jedoch die CPU-Limits für `Namespace 3` überschreiben, damit mehr Ressourcen verfügbar sind. Daher {xref-projects-and-namespaces}[erhöht der Administrator die CPU-Limits] für `Namespace 3`, damit der Namespace auf mehr Ressourcen zugreifen kann.

^Überschreibung des Standardlimits des Namespace^

image::rancher-resource-quota-override.svg[Überschreibung des Standardlimits des Namespace]

Anleitung: {xref-projects-and-namespaces}[Bearbeiten der Ressourcenquoten für Namespaces]

[#_editing_namespace_resource_quotas]
== Bearbeiten der Ressourcenquoten für Namespaces

Wenn eine Ressourcenquote für ein Projekt konfiguriert ist, können Sie das Standardlimit des Namespace überschreiben, um einem bestimmten Namespace den Zugriff auf mehr (oder weniger) Projektressourcen zu ermöglichen.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Cluster* zu dem Cluster, in dem Sie eine Ressourcenquote für einen Namespace bearbeiten möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie auf menu:Cluster[Projekte/Namespaces].
. Suchen Sie den Namespace, für den Sie die Ressourcenquote bearbeiten möchten. Klicken Sie auf *⋮ > Konfiguration bearbeiten*.
. Bearbeiten Sie die Ressourcenlimits.  Diese Limits bestimmen die Ressourcen, die dem Namespace zur Verfügung stehen. Die Limits müssen innerhalb der konfigurierten Projektlimits festgelegt werden.
+
Für weitere Informationen zu jedem *Ressourcentyp* siehe {xref-resource-quota-types}[die Typreferenz].
+

[NOTE]
====

 ** Wenn für das Projekt keine Ressourcenquote konfiguriert ist, stehen diese Optionen nicht zur Verfügung.
 ** Wenn Sie Limits eingeben, die die konfigurierten Projektlimits überschreiten, wird Rancher Ihnen nicht erlauben, Ihre Änderungen zu speichern.

+
====


*Ergebnis:* Ihre Überschreibung wird auf die Ressourcenquote des Namespace angewendet.
