= Configuración del Federador de Prometheus para una Carga de Trabajo
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: instrucciones/guías-de-usuario-avanzadas/guías-de-monitoreo-y-alertas/guías-del-federador-de-prometheus/configurar-cargas-de-trabajo.adoc 
:product-path: observability/monitoring-and-dashboards/prometheus-federator/set-up-workloads.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-workload-monitoring: xref:observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-workload-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc
endif::[]

[#_display_cpu_and_memory_metrics_for_a_workload]
== Mostrar métricas de CPU y memoria para una carga de trabajo

La visualización de métricas de CPU y memoria con el Federador de Prometheus se realiza de la misma manera que con rancher-monitoring. For instructions, refer {xref-rancher-workload-monitoring}#_display_cpu_and_memory_metrics_for_a_workload[here].

[#_setting_up_metrics_beyond_cpu_and_memory]
== Configuración de métricas más allá de CPU y memoria

La configuración de métricas más allá de CPU y memoria con el Federador de Prometheus se realiza de la misma manera que con rancher-monitoring. Para instrucciones, consulta {xref-rancher-workload-monitoring}#_setting_up_metrics_beyond_cpu_and_memory[aquí].
