= Benutzer zu Projekten hinzufügen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/add-users-to-projects.adoc 
:product-path: cluster-admin/project-admin/add-users-to-projects.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/cluster-and-project-roles.adoc
:xref-projects-and-namespaces: xref:cluster-admin/manage-clusters/projects-and-namespaces.adoc
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-locked-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles.adoc
:xref-projects-and-namespaces: xref:how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces.adoc
:xref-custom-roles: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-locked-roles: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/locked-roles.adoc
endif::[]

Wenn Sie einem Benutzer Zugriff und Berechtigungen für _spezifische_ Projekte und Ressourcen innerhalb eines Clusters gewähren möchten, weisen Sie dem Benutzer eine Projektmitgliedschaft zu.

Sie können Mitglieder zu einem Projekt hinzufügen, während es erstellt wird, oder sie zu einem bestehenden Projekt hinzufügen.

[TIP]
====

Möchten Sie einem Benutzer Zugriff auf _alle_ Projekte innerhalb eines Clusters gewähren? Siehe stattdessen {xref-cluster-project-roles}[Mitglieder zum Cluster hinzufügen].
====


[#_adding_members_to_a_new_project]
== Mitglieder zu einem neuen Projekt hinzufügen

Sie können Mitglieder zu einem Projekt hinzufügen, während Sie es erstellen (empfohlen, wenn möglich). Für Details zur Erstellung eines neuen Projekts, siehe den {xref-projects-and-namespaces}[Abschnitt zur Clusterverwaltung].

[#_adding_members_to_an_existing_project]
== Mitglieder zu einem bestehenden Projekt hinzufügen

Nach der Erstellung des Projekts können Sie Benutzer als Projektmitglieder hinzufügen, damit sie auf die Ressourcen zugreifen können.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der *Cluster*-Seite zu dem Cluster, in dem Sie Mitglieder zu einem Projekt hinzufügen möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie auf menu:Cluster[Projekte/Namespaces].
. Gehen Sie zu dem Projekt, in dem Sie Mitglieder hinzufügen möchten. Neben der *Namespace erstellen*-Schaltfläche über dem Projektnamen klicken Sie auf *☰*. Wählen Sie *Konfiguration bearbeiten*.
. Im Tab *Mitglieder* klicken Sie auf *Hinzufügen*.
. Suchen Sie nach dem Benutzer oder der Gruppe, die Sie zum Projekt hinzufügen möchten.
+
[NOTE]
.Anmerkungen
====
* Mindestens 2 Zeichen müssen in das Suchfeld eingegeben werden, damit Ergebnisse angezeigt werden.
* Benutzer können anhand ihres Benutzernamens oder Anzeigenamens gesucht werden.
* Die Suche basiert auf Präfixen (z. B. wird ein Benutzer mit dem Namen `Stan Dard` angezeigt, wenn nach `Sta` gesucht wird, jedoch nicht, wenn nach `Dar` gesucht wird) und ist groß-/kleinschreibungssensitiv.
====
+
Wenn die externe Authentifizierung konfiguriert ist:

 ** Rancher gibt Benutzer aus Ihrer externen Authentifizierungsquelle zurück, während Sie tippen.
 ** Ein Dropdown-Menü ermöglicht es Ihnen, Gruppen anstelle von einzelnen Benutzern hinzuzufügen. Das Dropdown-Menü listet nur Gruppen auf, in denen Sie, der angemeldete Benutzer, enthalten sind.

+

[NOTE]
====
Wenn Sie als lokaler Benutzer angemeldet sind, werden externe Benutzer nicht in Ihren Suchergebnissen angezeigt.
====


. Weisen Sie dem Benutzer oder der Gruppe *Projekt*-Rollen zu.
+
{xref-cluster-project-roles}[Was sind Projektrollen?]
+

[NOTE]
.Hinweise:
====

 ** Benutzer, die die Rolle `Owner` oder `Member` für ein Projekt zugewiesen bekommen, erben automatisch die Rolle `namespace creation`. Diese Rolle ist jedoch eine https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole[Kubernetes ClusterRole], was bedeutet, dass ihr Geltungsbereich alle Projekte im Cluster umfasst. Daher können Benutzer, die ausdrücklich die Rolle `Owner` oder `Member` für ein Projekt zugewiesen bekommen, Namespaces in anderen Projekten erstellen oder löschen, denen sie zugewiesen sind, selbst wenn ihnen nur die Rolle `Read Only` zugewiesen ist.
 ** Standardmäßig erbt die Rancher-Rolle `project-member` von der Rolle `Kubernetes-edit`, und die Rolle `project-owner` erbt von der Rolle `Kubernetes-admin`. Daher ermöglichen sowohl die Rollen `project-member` als auch `project-owner` die Verwaltung von Namespaces, einschließlich der Möglichkeit, Namespaces zu erstellen und zu löschen.
 ** Für `Custom` Rollen können Sie die Liste der verfügbaren einzelnen Rollen zur Zuweisung ändern.
  *** Um Rollen zur Liste hinzuzufügen, {xref-custom-roles}[Fügen Sie eine benutzerdefinierte Rolle hinzu].
  *** Um Rollen aus der Liste zu entfernen, {xref-locked-roles}[Lock/Unlock Roles].

+
====


*Ergebnis:* Die ausgewählten Benutzer werden dem Projekt hinzugefügt.

* Um die Projektmitgliedschaft zu widerrufen, wählen Sie den Benutzer aus und klicken Sie auf *Löschen*. Diese Aktion löscht die Mitgliedschaft, nicht den Benutzer.
* Um die Rollen eines Benutzers im Projekt zu ändern, löschen Sie ihn aus dem Projekt und fügen Sie ihn dann mit geänderten Rollen wieder hinzu.
