= ワークロードの監視を設定する
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc 
:product-path: observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
ifeval::["{build-type}" != "community"]
:xref-promql-expressions: xref:observability/monitoring-and-dashboards/promql-expressions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-promql-expressions: xref:integrations-in-rancher/monitoring-and-alerting/promql-expressions.adoc
endif::[]

ワークロードにCPUとメモリの時系列データのみが必要な場合、監視アプリケーションはデフォルトでリソース使用量のメトリクスデータを収集するため、ServiceMonitorやPodMonitorをデプロイする必要はありません。

ワークロードの監視を設定する手順は、ワークロードの基本的なメトリクス（CPUやメモリなど）が必要か、またはワークロードからカスタムメトリクスをスクレイプしたいかによって異なります。

ワークロードにCPUとメモリの時系列データのみが必要な場合、監視アプリケーションはデフォルトでリソース使用量のメトリクスデータを収集するため、ServiceMonitorやPodMonitorをデプロイする必要はありません。リソース使用量の時系列データは、Prometheusのローカル時系列データベースに保存されています。

Grafanaはデータを集約して表示しますが、PromQLクエリを使用して特定のワークロードのデータを抽出することで、個々のワークロードのデータを見ることができます。PromQLクエリを取得したら、Prometheus UIでそのクエリを個別に実行し、そこで時系列を視覚化することができます。または、そのクエリを使用してGrafanaダッシュボードをカスタマイズし、ワークロードメトリクスを表示することもできます。ワークロードメトリクスのPromQLクエリの例については、{xref-promql-expressions}#_workload_metrics[このセクション]を参照してください。

ワークロードのカスタムメトリクスを設定するには、エクスポーターを設定し、Prometheusがエクスポーターからメトリクスをスクレイプするように新しいServiceMonitorカスタムリソースを作成する必要があります。

[#_display_cpu_and_memory_metrics_for_a_workload]
== ワークロードのCPUとメモリメトリクスを表示する

デフォルトで、監視アプリケーションはすでにCPUとメモリをスクレイプしています。

特定のワークロードの詳細な情報を得るために、特定のワークロードのメトリクスを表示するようにGrafanaダッシュボードをカスタマイズすることができます。

[#_setting_up_metrics_beyond_cpu_and_memory]
== CPUとメモリを超えたメトリクスの設定

カスタムメトリクスの場合、アプリケーションでPrometheusがサポートする形式でメトリクスを公開する必要があります。

その後、新しいServiceMonitorカスタムリソースを作成することをお勧めします。このリソースが作成されると、Prometheusカスタムリソースは自動的に更新され、新しいカスタムメトリクスエンドポイントを含むようにそのスクレイプ設定が更新されます。その後、Prometheusはエンドポイントからメトリクスをスクレイプし始めます。

カスタムメトリクスエンドポイントを公開するためにPodMonitorを作成することもできますが、ServiceMonitorは大多数のユースケースに対してより適切です。
