= Monitoring V2のWindowsクラスターサポート
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/windows-support.adoc 
:product-path: observability/monitoring-and-dashboards/windows-support.adoc

Monitoring V2は、 https://github.com/prometheus-community/windows_exporter[prometheus-community/windows_exporter]（以前は`wmi_exporter`と呼ばれていました）を使用して、Windowsノードからメトリクスを取得するためにWindowsクラスターにデプロイできます。

[#_cluster_requirements]
== クラスター要件

Windows用のMonitoring V2は、最低`wins`バージョンのv0.1.0を持つWindowsホストからのみメトリクスを取得できます。 Windows用のMonitoring V2を完全にデプロイするには、すべてのホストがこの要件を満たす必要があります。

[#_upgrading_existing_clusters_to_wins_v0_1_0]
=== 既存のクラスターをwins v0.1.0にアップグレードする

クラスターがRancher 2.5.8以前にプロビジョニングされた場合（現在のRancherバージョンが2.5.8であっても）、各ホストのwinsバージョンを少なくともv0.1.0にアップグレードするまで、Windows用のMonitoring V2を正常にデプロイすることはできません。

このアップグレードを容易にするために、Rancher 2.5.8は`rancher-wins-upgrader`という新しいHelmチャートをリリースしました。

. 次のオーバーライドを使用して`rancher-wins-upgrader`をデプロイしてください：
+
[,yaml]
----
 # Masquerading bootstraps the wins-upgrader installation via
 # a previously whitelisted process path since the normal install path,
 # c:\etc\rancher\wins\wins-upgrade.exe is not normally whitelisted.
 # In this case, we are using the previously whitelisted process
 # path used by Monitoring V1.
 masquerade:
   enabled: true
   as: c:\\etc\wmi-exporter\wmi-exporter.exe
----

. すべてのホストが正常にアップグレードされたら、次の設定との競合を避けるために、デフォルト値でHelmチャートを再度デプロイすることを確認してください。
+
[,yaml]
----
 masquerade:
   enabled: false
----

*結果:*ホストはMonitoring V2をインストールする準備が整いました。`rancher-wins-upgrader`チャートをアンインストールするか、将来のアップグレードを容易にするためにクラスターに保持するかを選択できます。

どのように使用できるかについての詳細は、チャートの https://github.com/rancher/wins/blob/master/charts/rancher-wins-upgrader/README.md[README.md]をご覧ください。
