= Requisitos previos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/adapter-requirements.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/adapter-requirements.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-on-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-on-eks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks.adoc
endif::[]

[#_1_setting_up_license_manager_and_purchasing_support]
== 1. Configuración del Gestor de Licencias y Compra de Soporte

Primero, completa el https://docs.aws.amazon.com/license-manager/latest/userguide/getting-started.html[primer paso] de la configuración única del gestor de licencias.
A continuación, ve al AWS Marketplace. Localiza el "Paquete de Inicio de Contenedor de Facturación de Soporte Premium de Rancher". Compra al menos un derecho.

Si has instalado Rancher utilizando la oferta de AWS Marketplace "Configuración de Rancher", salta al <<_4_create_an_oidc_provider,Paso 4>>.

NOTE: Cada derecho otorga acceso a soporte para una cierta cantidad de nodos. Puedes comprar más licencias según sea necesario más adelante.

[#_2_create_an_eks_cluster]
== 2. Crea un Clúster EKS

Sigue la {xref-rancher-on-eks}[documentación de Rancher] para crear un clúster EKS. Cuando llegues al {xref-rancher-on-eks}#_8_install_the_rancher_helm_chart[último paso para instalar Rancher], *termina y regresa a esta página*. Este clúster deberá cumplir con los siguientes requisitos:

* Versión EKS 1.22.
* Cada nodo en el clúster tiene acceso al registro que contiene Rancher y sus imágenes relacionadas.
* Cada nodo en el clúster tiene acceso al repositorio ECR que almacena el Adaptador CSP.
* Cada nodo en el clúster tiene acceso al servicio del gestor de licencias.
* Cada nodo en el clúster tiene acceso a los puntos finales globales para el servicio STS.

[#_3_install_rancher]
== 3. Instalar Rancher

Además de las opciones especificadas para instalar Rancher en la {xref-rancher-on-eks}#_8_install_the_rancher_helm_chart[documentación de Rancher], también necesitarás habilitar métricas adicionales.
Esto se puede hacer a través de la CLI de Helm mediante las siguientes opciones:

[,bash]
----
--set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
----

También puedes usar un values.yaml como el siguiente:

[,yaml]
----
extraEnv:
  - name: "CATTLE_PROMETHEUS_METRICS"
    value: "true"
----

También necesitarás instalar Rancher versión 2.6.7 o superior.

[#_4_create_an_oidc_provider]
== 4. Crea un Proveedor OIDC

Sigue la https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html[documentación de AWS] para crear un proveedor OIDC para el clúster especificado en la sección anterior.

[#_5_create_an_iam_role]
== 5. Crea un Rol IAM

Se requiere un rol IAM para que el adaptador CSP pueda registrar y retirar derechos.

Primero, configura la política de confianza como se indica a continuación. Reemplaza `MY_AWS_ACC` con tu número de cuenta de AWS, `MY_AWS_REGION` con tu región de AWS y `MY_OIDC_PROVIDER` con el id de tu proveedor OIDC:

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::${MY_AWS_ACC}:oidc-provider/oidc.eks.${MY_AWS_REGION}.amazonaws.com/id/${MY_OIDC_PROVIDER}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.${MY_AWS_REGION}.amazonaws.com/id/${MY_OIDC_PROVIDER}:sub": "system:serviceaccount:cattle-csp-adapter-system:rancher-csp-adapter",
                    "oidc.eks.${MY_AWS_REGION}.amazonaws.com/id/${MY_OIDC_PROVIDER}:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
----

A continuación, utiliza una política para el rol que tenga los siguientes permisos:

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "RancherCSPAdapterPermissions",
            "Effect": "Allow",
            "Action": [
                "license-manager:ListReceivedLicenses",
                "license-manager:CheckoutLicense",
                "license-manager:ExtendLicenseConsumption",
                "license-manager:CheckInLicense",
                "license-manager:GetLicense",
                "license-manager:GetLicenseUsage"
            ],
            "Resource": "*"
        }
    ]
}
----

Guarda el nombre del rol. Lo necesitarás más tarde al instalar el adaptador CSP.
