= Problemas comunes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/common-issues.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/common-issues.adoc
ifeval::["{build-type}" != "community"]
:xref-aws-cloud-marketplace-adapter-reqs: xref:installation-and-upgrade/hosted-kubernetes/cloud-marketplace/aws/adapter-requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-aws-cloud-marketplace-adapter-reqs: xref:integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/adapter-requirements.adoc
endif::[]

*Después de instalar el adaptador, aparece un mensaje en Rancher que dice "Adaptador de AWS Marketplace: No se puede ejecutar el adaptador, por favor revisa los registros del adaptador"*

Este error indica que, aunque el adaptador se instaló en el clúster, se ha producido un error que impide realizar correctamente el check-in y check-out de licencias.

Esto ocurre a menudo porque el rol de IAM no fue configurado correctamente. Revisa los {xref-aws-cloud-marketplace-adapter-reqs}[requisitos previos] y verifica que:

* Se ha creado/asociado un proveedor OIDC con el clúster en el que se está ejecutando Rancher.
* El rol de IAM ha sido configurado para confiar en este proveedor OIDC.
* El rol de IAM tiene al menos los permisos descritos en la directiva.

Si todo lo anterior ha sido configurado correctamente, contacta con el soporte para obtener asistencia.

*Veo un mensaje que indica, "Adaptador de AWS Marketplace: Has superado el número de nodos licenciados. Se requieren al menos x licencia(s) más en AWS para estar en conformidad"*

Este mensaje indica que no tienes suficientes derechos para la cantidad de nodos que Rancher está gestionando actualmente.

Ten en cuenta las siguientes limitaciones:

* Cada derecho es válido para un cierto número de nodos.
* Cada nodo actualmente gestionado por Rancher cuenta para tu total de uso (con excepción de los nodos en el clúster donde está instalado Rancher).
* Cada derecho puede ser utilizado por como máximo una instancia de Rancher. Por ejemplo, si tienes dos instancias de Rancher en funcionamiento en tu cuenta (cada una instalada en un clúster EKS separado), necesitarás al menos dos derechos.

También puede que hayas desinstalado/reinstalado recientemente el adaptador. Si el adaptador pierde el seguimiento de las licencias que está gestionando actualmente, puede tardar hasta una hora en resolver el estado real de las licencias.
