= Rôles personnalisés
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procédure/guide-utilisateur-nouveau/authentification-permissions-et-configuration-globale/gerer-le-contrôle-d'accès-en-fonction-du-rôle-rbac/roles-personnalisés.adoc 
:product-path: rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-users-and-groups: xref:rancher-admin/users/authn-and-authz/manage-users-and-groups.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc 
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
:xref-users-and-groups: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/configuration-d-authentification/gerer-utilisateurs-et-groupes.adoc
endif::[]

Dans Rancher, _les rôles_ déterminent quelles actions un utilisateur peut effectuer au sein d'un cluster ou d'un projet.

Notez que _les rôles_ sont différents des _permissions_, qui déterminent à quels clusters et projets vous pouvez accéder.

[WARNING]
====

Il est possible qu'un rôle personnalisé permette l'escalade de privilèges. Pour plus de détails, voir <<_privilege_escalation,cette section.>>
====


[#_prerequisites]
== Conditions préalables

Pour accomplir les tâches sur cette page, l'une des permissions suivantes est requise{nbsp}:

* {xref-global-permissions}[Permissions globales d'administrateur].
* {xref-global-permissions}#_permissions_globales_personnalisees[Permissions globales personnalisées] avec le rôle {xref-global-permissions}[Gérer les Rôles] attribué.

[#_creating_a_custom_role]
== Création d'un Rôle Personnalisé

Bien que Rancher soit livré avec un ensemble de rôles d'utilisateur par défaut, vous pouvez également créer des rôles personnalisés par défaut pour fournir aux utilisateurs des permissions très spécifiques au sein de Rancher.

Les étapes pour ajouter des rôles personnalisés diffèrent selon la version de Rancher.

. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et Authentification*.
. Dans la barre de navigation à gauche, cliquez sur *Modèles de Rôle*.
. Sélectionnez un onglet pour déterminer la portée du rôle que vous ajoutez. Les onglets sont{nbsp}:

* *Global :* Le rôle est valide pour permettre aux membres de gérer des ressources à portée globale.
* *Grappe :* Le rôle est valide pour l'attribution lors de l'ajout/de la gestion des membres aux clusters.
* *Projet/Espaces de noms :* Le rôle est valide pour l'attribution lors de l'ajout/de la gestion des membres aux projets ou espaces de noms.

. Cliquez sur *Créer un rôle global,* *Créer un rôle de cluster* ou *Créer un rôle de projet/espace de noms,* selon la portée.
. Entrez un *Nom* pour le rôle.
. Facultatives : Choisissez l'option *Créateur de cluster/projet par défaut* pour attribuer ce rôle à un utilisateur lorsqu'il crée un nouveau cluster ou projet. Avec cette fonctionnalité, vous pouvez étendre ou restreindre les rôles par défaut pour les créateurs de clusters/projets.
+
____
Par défaut, les rôles de Créateur de cluster par défaut et de Créateur de projet par défaut sont `Cluster Owner` et `Project Owner` respectivement.
____

. Utilisez les options *Accorder des ressources* pour attribuer des https://kubernetes.io/docs/reference/[points de terminaison de l'API Kubernetes] individuels au rôle.
+
____
Lors de la visualisation des ressources associées aux rôles par défaut créés par Rancher, s'il y a plusieurs ressources de l'API Kubernetes sur un même élément de ligne, la ressource aura `(Custom)` ajouté à son nom. Ce ne sont pas des ressources personnalisées mais simplement une indication qu'il y a plusieurs ressources de l'API Kubernetes en tant qu'une seule ressource.
____
+
____
Le champ Ressource fournit un moyen de rechercher des ressources de l'API Kubernetes prédéfinies ou de saisir un nom de ressource personnalisé pour l'autorisation. La ressource prédéfinie ou `(Custom)` doit être sélectionnée dans le menu déroulant, après avoir saisi un nom de ressource dans ce champ.
____
+
Vous pouvez également choisir les méthodes cURL individuelles (`Create`, `Delete`, `Get`, etc.) disponibles pour chaque point de terminaison que vous attribuez.

. Utilisez les options *Hériter de* pour attribuer des rôles Rancher individuels à vos rôles personnalisés. Remarque : Lorsqu'un rôle personnalisé hérite d'un rôle parent, le rôle parent ne peut pas être supprimé tant que le rôle enfant n'est pas supprimé.
. Cliquez sur *Create*.

[#_creating_a_custom_role_that_inherits_from_another_role]
== Créer un rôle personnalisé qui hérite d'un autre rôle

Si vous avez un groupe d'individus qui ont besoin du même niveau d'accès dans Rancher, il peut être utile de créer un rôle personnalisé dans lequel toutes les règles d'un autre rôle, comme le rôle d'administrateur, sont copiées dans un nouveau rôle. Cela vous permet de ne configurer que les variations entre le rôle existant et le nouveau rôle.

Le rôle personnalisé peut ensuite être attribué à un utilisateur ou à un groupe afin que le rôle prenne effet la première fois que l'utilisateur ou les utilisateurs se connectent à Rancher.

Pour créer un rôle personnalisé basé sur un rôle existant,

. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et Authentification*.
. Dans la barre de navigation à gauche, cliquez sur *Modèles de Rôle*.
. Cliquez sur l'onglet *Cluster* ou *Projet/Espaces de noms*. Cliquez sur *Créer un rôle de cluster* ou *Créer un rôle de projet/espace de noms* selon la portée. Remarque : Seuls les rôles de cluster et les rôles de projet/espace de noms peuvent hériter d'un autre rôle.
. Entrez un nom pour le rôle.
. Dans l'onglet *Hériter de*, sélectionnez le(s) rôle(s) dont le rôle personnalisé héritera des autorisations.
. Dans l'onglet *Accorder des ressources*, sélectionnez les opérations de ressources Kubernetes qui seront activées pour les utilisateurs avec le rôle personnalisé.
+
____
Le champ Ressource fournit un moyen de rechercher des ressources de l'API Kubernetes prédéfinies ou de saisir un nom de ressource personnalisé pour l'octroi. La ressource prédéfinie ou `(Custom)` doit être sélectionnée dans le menu déroulant, après avoir saisi un nom de ressource dans ce champ.
____

. Facultatives : Attribuez le rôle par défaut.
. Cliquez sur *Create*.

[#_deleting_a_custom_role]
== Suppression d'un rôle personnalisé

Lors de la suppression d'un rôle personnalisé, toutes les liaisons de rôle globales avec ce rôle personnalisé sont supprimées.

Si un utilisateur n'a qu'un seul rôle personnalisé attribué et que le rôle est supprimé, l'utilisateur perdra l'accès à Rancher. Pour que l'utilisateur retrouve l'accès, un administrateur devra modifier l'utilisateur et appliquer de nouvelles autorisations globales.

Les rôles personnalisés peuvent être supprimés, mais les rôles intégrés ne peuvent pas être supprimés.

Pour supprimer un rôle personnalisé,

. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et Authentification*.
. Dans la barre de navigation à gauche, cliquez sur *Modèles de Rôle*.
. Accédez au rôle global personnalisé qui doit être supprimé et cliquez sur *⋮ (...) > Supprimer*.
. Cliquez sur *Supprimer*.

[#_assigning_a_custom_role_to_a_group]
== Attribution d'un rôle personnalisé à un groupe

Si vous avez un groupe d'individus qui ont besoin du même niveau d'accès dans Rancher, il peut être utile de créer un rôle personnalisé. Lorsque le rôle est attribué à un groupe, les utilisateurs du groupe ont le niveau d'accès approprié la première fois qu'ils se connectent à Rancher.

Lorsqu'un utilisateur du groupe se connecte, il obtient par défaut le rôle global d'utilisateur standard intégré. Ils obtiendront également les autorisations attribuées à leurs groupes.

Si un utilisateur est retiré du groupe du fournisseur d'authentification externe, il perdra ses autorisations du rôle personnalisé qui a été attribué au groupe. Ils continueront à avoir leur rôle individuel d'utilisateur standard.

[NOTE]
.Conditions préalables :
====

Vous ne pouvez attribuer un rôle global à un groupe que si{nbsp}:

* Vous avez configuré un {xref-authn-authz}#_external_vs_local_authentication[fournisseur d'authentification externe]
* Le fournisseur d'authentification externe prend en charge {xref-users-and-groups}[groupes d'utilisateurs]
* Vous avez déjà configuré au moins un groupe d'utilisateurs avec le fournisseur d'authentification
====


Pour attribuer un rôle personnalisé à un groupe, suivez ces étapes{nbsp}:

. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et Authentification*.
. Dans la barre de navigation à gauche, cliquez sur *Groupes*.
. Allez au groupe existant qui se verra attribuer le rôle personnalisé et cliquez sur *⋮ > Modifier la configuration*.
. Si vous avez créé des rôles, ils apparaîtront dans la section *Personnalisé*. Choisissez n'importe quel rôle personnalisé qui sera attribué au groupe.
. Facultatives : Dans les sections *Permissions globales* ou *Intégrés*, sélectionnez toutes les permissions supplémentaires que le groupe devrait avoir.
. Cliquez sur *Enregistrer.*.

*Résultat :* Le rôle personnalisé prendra effet lorsque les utilisateurs du groupe se connecteront à Rancher.

[#_privilege_escalation]
== Escalade de privilèges

La `Configure Catalogs` permission personnalisée est puissante et doit être utilisée avec précaution. Lorsqu'un administrateur attribue la `Configure Catalogs` permission à un utilisateur standard, cela pourrait entraîner une escalade de privilèges dans laquelle l'utilisateur pourrait se donner un accès administrateur aux clusters provisionnés par Rancher. Quiconque ayant cette permission doit être considéré comme équivalent à un administrateur.
