= Rôles verrouillés
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guides-pratiques/guide-utilisateur-nouveau/authentification-permissions-et-configuration-globale/gerer-le-contrôle-d'accès-en-fonction-du-rôle-rbac/rôles-verrouillés.adoc 
:product-path: rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/locked-roles.adoc
ifeval::["{build-type}" != "community"]
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-custom-roles: xref:how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/gérer-le-contrôle-d'accès-en-fonction-du-rôle-rbac/rôles-personnalisés.adoc
endif::[]

Vous pouvez attribuer aux rôles le statut `locked`. Le verrouillage des rôles empêche leur attribution à des utilisateurs à l'avenir.

Rôles verrouillés{nbsp}:

* Ne peuvent pas être attribués à des utilisateurs qui ne l'ont pas déjà.
* Ne figurent pas dans le menu déroulant *Rôles de Membre* lorsque vous ajoutez un utilisateur à un cluster ou un projet.
* N'affectent pas les utilisateurs à qui le rôle a été attribué avant que vous ne verrouilliez le rôle. Ces utilisateurs conservent l'accès que le rôle fournit.
+
*Exemple :* disons que votre organisation crée une politique interne interdisant aux utilisateurs affectés à un cluster de créer de nouveaux projets. C'est votre travail de faire respecter cette politique.
+
Pour l'appliquer, avant d'ajouter de nouveaux utilisateurs au cluster, vous devez verrouiller les rôles suivants{nbsp}: `Cluster Owner`, `Cluster Member` et `Create Projects`. Ensuite, vous pourriez créer un nouveau rôle personnalisé qui inclut les mêmes permissions qu'un *membre de cluster*, sauf la capacité de créer des projets. Ensuite, vous utilisez ce nouveau rôle personnalisé lors de l'ajout d'utilisateurs à un cluster.

Les rôles peuvent être verrouillés par les utilisateurs suivants{nbsp}:

* Tout utilisateur ayant la permission globale `Administrator`.
* Tout utilisateur ayant la permission `Custom Users`, ainsi que le rôle `Manage Roles`.

[#_locking_unlocking_roles]
== Verrouillage/Déverrouillage des rôles

Si vous souhaitez empêcher un rôle d'être attribué à des utilisateurs, vous pouvez le définir sur un statut de `locked`.

Vous pouvez verrouiller des rôles dans deux contextes{nbsp}:

* Lorsque vous {xref-custom-roles}[ajoutez un rôle personnalisé].
* Lorsque vous modifiez un rôle existant (voir ci-dessous).

Les rôles de cluster et les rôles de projet/espace de noms peuvent être verrouillés, mais les rôles globaux ne le peuvent pas.

. Dans le coin supérieur gauche, cliquez sur *☰ > Utilisateurs et Authentification*.
. Dans la barre de navigation à gauche, cliquez sur *Modèles de Rôle*.
. Allez à l'onglet *Cluster* ou à l'onglet *Projet/Espace de noms*.
. À partir du rôle que vous souhaitez verrouiller (ou déverrouiller), sélectionnez *⋮ > Modifier la configuration*.
. Dans l'option *Verrouillé*, choisissez le bouton radio *Oui* ou *Non*. Puis cliquez sur *Enregistrer*.
