= Gestion du contrôle d'accès en fonction du rôle (RBAC)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/index.adoc 
:product-path: rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/gerer-le-controle-d-acces-en-fonction-du-role-rbac.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/roles-de-cluster-et-de-projet.adoc
:xref-global-permissions: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/roles-de-cluster-et-de-projet.adoc
:xref-global-permissions: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc 
:xref-authn-authz: xref:procedure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/configuration-d-authentification/index.adoc
endif::[]

Au sein de Rancher, chaque personne s'authentifie en tant qu'_utilisateur_, ce qui est une connexion qui vous accorde l'accès à Rancher. Comme mentionné dans {xref-authn-authz}[Authentification], les utilisateurs peuvent être locaux ou externes.

Après avoir configuré l'authentification externe, les utilisateurs affichés sur la page *Utilisateurs* changent.

* Si vous êtes connecté en tant qu'utilisateur local, seuls les utilisateurs locaux s'affichent.
* Si vous êtes connecté en tant qu'utilisateur externe, les utilisateurs externes et locaux s'affichent.

[#_users_and_roles]
== Utilisateurs et rôles

Une fois que l'utilisateur se connecte à Rancher, son _autorisation_, ou ses droits d'accès au sein du système, est déterminé par _autorisations globales_ et _rôles de cluster et de projet_.

* {xref-global-permissions}[Autorisations globales]{nbsp}:
+
Définir l'autorisation des utilisateurs en dehors du cadre de tout cluster particulier.

* {xref-cluster-project-roles}[Rôles de cluster et de projet]{nbsp}:
+
Définir l'autorisation des utilisateurs à l'intérieur du cluster ou du projet spécifique où ils se voient attribuer le rôle.

Les autorisations globales et les rôles de cluster et de projet sont tous deux mis en œuvre sur https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Kubernetes RBAC]. Par conséquent, l'application des autorisations et des rôles est effectuée par Kubernetes.
