= Configuration des graphiques système locaux pour les installations isolées physiquement
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/local-system-charts.adoc 
:product-path: installation-and-upgrade/other-installation-methods/air-gapped/local-system-charts.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap: xref:getting-started/installation-et-mise-à-niveau/autres-méthodes-d-installation/isolé-physiquement-helm-cli-install/index.adoc
endif::[]

Le dépôt https://github.com/rancher/charts[Charts] contient tous les éléments du catalogue Helm nécessaires pour des fonctionnalités telles que la surveillance, la journalisation, l'alerte et Istio.

Dans une installation isolée physiquement de Rancher, vous devrez configurer Rancher pour utiliser une copie locale des graphiques système. Cette section décrit comment utiliser les graphiques système locaux en utilisant une option CLI.

[#_using_local_system_charts]
== Utilisation des graphiques système locaux

Une copie locale de `system-charts` a été empaquetée dans le conteneur `rancher/rancher`. Pour pouvoir utiliser ces fonctionnalités dans une installation isolée physiquement, vous devrez exécuter la commande d'installation de Rancher avec une variable d'environnement supplémentaire, `CATTLE_SYSTEM_CATALOG=bundled`, qui indique à Rancher d'utiliser la copie locale des graphiques au lieu d'essayer de les récupérer depuis GitHub.

Des commandes d'exemple pour une installation de Rancher avec un `system-charts` intégré sont incluses dans les instructions de {xref-air-gap}[installation isolée physiquement] pour les installations Docker et Helm.
