= Configuración de nodos en Amazon EC2
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc 
:product-path: installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-set-up-cloud-providers: xref:instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configurar-proveedores-de-nube/index.adoc
endif::[]

En este tutorial, aprenderás una forma de configurar nodos Linux para el servidor de gestión Rancher. Estos nodos cumplirán con los requisitos de nodo para {xref-install-reqs}[SO, Docker, hardware y redes.]

Si el servidor Rancher se instalará en un clúster de Kubernetes RKE, deberías aprovisionar tres instancias.

Si el servidor Rancher se instalará en un clúster de Kubernetes K3s, solo necesitas aprovisionar dos instancias.

Si el servidor Rancher se instala en un único contenedor Docker, solo necesitas una instancia.

[#_1_optional_preparation]
== 1. Preparación opcional

* *Crear rol IAM:* Para permitir que Rancher manipule recursos de AWS, como aprovisionar nuevo almacenamiento o nuevos nodos, necesitarás configurar Amazon como proveedor de nube. Hay varias cosas que necesitarás hacer para configurar el proveedor de nube en EC2, pero parte de este proceso es configurar un rol IAM para los nodos del servidor Rancher. Para obtener todos los detalles sobre la configuración del proveedor de nube, consulta esta {xref-set-up-cloud-providers}[página.]
* *Crear grupo de seguridad:* También recomendamos configurar un grupo de seguridad para los nodos Rancher que cumpla con los {xref-install-reqs}#_port_requirements[requisitos de puerto para los nodos Rancher.]

[#_2_provision_instances]
== 2. Aprovisionar instancias

. Inicia sesión en https://console.aws.amazon.com/ec2/[la Consola de Amazon AWS EC2] para comenzar. Asegúrate de tomar nota de la *Región* donde se crean tus instancias EC2 (nodos Linux), porque toda la infraestructura para el servidor de gestión Rancher debe estar en la misma región.
. En el panel izquierdo, haz clic en *Instancias*.
. Haz clic en *Lanzar instancia*.
. En la sección llamada *Paso 1: Elige una imagen de máquina de Amazon (AMI),* utilizaremos Ubuntu 18.04 como el sistema operativo Linux, usando `ami-0d1cd67c26f5fca19 (64-bit x86)`. Ve a la AMI de Ubuntu y haz clic en *Seleccionar*.
. En el *Paso 2: En la sección * 'Elija un tipo de instancia', selecciona el tipo `t2.medium`.
. Haga clic en *Siguiente: Configure los detalles de la instancia*.
. En el campo *Número de instancias*, introduzca el número de instancias. Un clúster K3s de alta disponibilidad requiere solo dos instancias, mientras que un clúster RKE de alta disponibilidad requiere tres instancias.
. Opcional: Si ha creado un rol IAM para que Rancher manipule recursos de AWS, seleccione el nuevo rol IAM en el campo *Rol IAM*.
. Haga clic en *Siguiente: Añadir almacenamiento,* *Siguiente: Añadir etiquetas,* y *Siguiente: Configure el grupo de seguridad*.
. En *Paso 6: Configure el grupo de seguridad,* seleccione un grupo de seguridad que cumpla con los {xref-install-reqs}#_port_requirements[requisitos de puerto] para los nodos de Rancher.
. Haga clic en *Revisar y lanzar*.
. Haz clic en *Lanzar*.
. Elija un nuevo par de claves o uno existente que utilizará para conectarse a su instancia más tarde. Si está utilizando un par de claves existente, asegúrese de que ya tiene acceso a la clave privada.
. Haga clic en *Lanzar instancias*.

*Resultado:* Has creado nodos de Rancher que satisfacen los requisitos de SO, hardware y redes.

[NOTE]
====

Si los nodos se están utilizando para un clúster de Kubernetes RKE, instale Docker en cada nodo en el siguiente paso. Para un clúster de Kubernetes K3s, los nodos están ahora listos para instalar K3s.
====


[#_3_install_docker_and_create_user_for_rke_kubernetes_cluster_nodes]
== 3. Instala Docker y crea un usuario para los nodos del clúster de Kubernetes RKE.

. Desde la https://console.aws.amazon.com/ec2/[consola de AWS EC2,], haz clic en *Instancias* en el panel izquierdo.
. Ve a la instancia en la que deseas instalar Docker. Selecciona la instancia y haz clic en menu:Acciones[Conectar].
. Conéctate a la instancia siguiendo las instrucciones en la pantalla que aparece. Copia el DNS público de la instancia. Un comando de ejemplo para acceder a la instancia por SSH es el siguiente:
+
----
sudo ssh -i [path-to-private-key] ubuntu@[public-DNS-of-instance]
----

. Ejecuta el siguiente comando en la instancia para instalar Docker con uno de los scripts de instalación de Rancher:
+
----
curl https://releases.rancher.com/install-docker/18.09.sh | sh
----

. Cuando estés conectado a la instancia, ejecuta el siguiente comando en la instancia para crear un usuario:
+
----
sudo usermod -aG docker ubuntu
----

. Repita estos pasos para que Docker esté instalado en cada nodo que eventualmente ejecutará el servidor de gestión de Rancher.

[TIP]
====

Para averiguar si hay un script disponible para instalar una cierta versión de Docker, consulta este https://github.com/rancher/install-docker[repositorio de GitHub,] que contiene todos los scripts de instalación de Docker de Rancher.
====


*Resultado:* Has configurado nodos del servidor Rancher que cumplen con todos los requisitos de nodo para el sistema operativo, Docker, hardware y redes.

[#_next_steps_for_rke_kubernetes_cluster_nodes]
== Próximos pasos para los nodos del clúster de Kubernetes RKE.

Si vas a instalar un clúster RKE en los nuevos nodos, toma nota de la *IP pública IPv4* y la *IP privada* de cada nodo. Esta información se puede encontrar en la pestaña *Descripción* para cada nodo después de que se crea. La IP pública y privada se utilizarán para completar el `address` y `internal_address` de cada nodo en el archivo de configuración del clúster RKE, `rancher-cluster.yml`.

RKE también necesitará acceso a la clave privada para conectarse a cada nodo. Por lo tanto, es posible que desee tomar nota de la ruta a sus claves privadas para conectarse a los nodos, que también se puede incluir en el `rancher-cluster.yml` bajo la directiva `ssh_key_path` para cada nodo.
