= Alertmanager構成
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

通常、Alertmanagerのカスタムリソースを直接編集する必要はありません。ほとんどのユースケースでは、通知を設定するためにReceiversとRoutesのみを編集する必要があります。

ReceiversとRoutesが更新されると、監視アプリケーションは自動的にAlertmanagerのカスタムリソースをそれらの変更に一致するように更新します。

[NOTE]
====

このセクションは、監視コンポーネントがどのように連携して動作するかに精通していることを前提としています。Alertmanagerに関する詳細情報は、{xref-how-monitoring-works}#_3_how_alertmanager_works[このセクション]を参照してください。
====


[#_about_the_alertmanager_custom_resource]
== Alertmanagerカスタムリソースについて

デフォルトでは、Rancher Monitoringは、デフォルトのAlertmanager Config Secretを使用するクラスターに単一のAlertmanagerをデプロイします。

Rancher UIのフォームでは公開されていない高度なオプションを利用したい場合、例えば、2階層以上のルーティングツリー構造を作成する機能などのために、Alertmanagerのカスタムリソースを編集したいかもしれません。

クラスター内に複数のAlertmanagerを作成することも可能で、これはネームスペーススコープの監視を実装したい場合に便利です。この場合、同じ基盤となるAlertmanager Config Secretを使用してAlertmanagerのカスタムリソースを管理する必要があります。

[#_deeply_nested_routes]
=== 深くネストされたルート

Rancher UIは2階層のルーティングツリーのみをサポートしていますが、Alertmanager YAMLを編集することで、より深くネストされたルーティング構造を構成できます。

[#_multiple_alertmanager_replicas]
=== 複数のAlertmanagerレプリカ

チャートのデプロイオプションの一部として、クラスターにデプロイされるAlertmanagerのレプリカの数を増やすことを選択できます。レプリカはすべて、同じ基盤となるAlertmanager Config Secretを使用して管理できます。

このSecretは、次の操作を行うたびに更新または変更する必要があります：

* 新しいnotifiersまたはReceiversを追加する
* 特定のnotifiersまたはReceiversに送信されるアラートを変更する
* 送信されるアラートのグループを変更する

デフォルトでは、既存のAlertmanager Config Secret（すなわち、`cattle-monitoring-system`ネームスペース内の任意のSecret）を提供するか、Rancher MonitoringがクラスターにデフォルトのAlertmanager Config Secretをデプロイすることを許可できます。

デフォルトでは、Rancherによって作成されたAlertmanager Config Secretは、`rancher-monitoring`チャートのアップグレードやアンインストール時に変更または削除されることはありません。この制限により、ユーザーはチャート上で操作を実行する際にアラート設定を失ったり上書きしたりすることを防ぎます。

Alertmanager Config Secretで指定できるフィールドに関する詳細については、 https://prometheus.io/docs/alerting/latest/alertmanager/[Prometheus Alertmanagerのドキュメントをご覧ください。]

Alertmanagerの設定ファイルの完全な仕様と必要な内容は、 https://prometheus.io/docs/alerting/latest/configuration/#configuration-file[こちらでご覧いただけます。]
