= Prometheus構成
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
endif::[]

通常、Prometheusカスタムリソースを直接編集する必要はありません。監視アプリケーションは、ServiceMonitorsおよびPodMonitorsの変更に基づいて自動的に更新します。

[NOTE]
====

このセクションは、監視コンポーネントがどのように連携して動作するかに精通していることを前提としています。詳細については、{xref-how-monitoring-works}[このセクションを参照してください。]
====


[#_about_the_prometheus_custom_resource]
== Prometheusカスタムリソースについて

Prometheus CRは、希望するPrometheusデプロイメントを定義します。Prometheusオペレーターは、Prometheus CRを監視します。CRが変更されると、PrometheusオペレーターはCRの設定に基づいたPrometheusデプロイメントである`prometheus-rancher-monitoring-prometheus`を作成します。

Prometheus CRは、ルールやPrometheusに接続されているAlertmanagerなどの詳細を指定します。RancherはこのCRをあなたのために構築します。

Monitoring V2は、クラスターごとに1つのPrometheusのみをサポートします。ただし、特定のネームスペースに監視を制限したい場合は、Prometheus CRを編集することを検討するかもしれません。
