= PrometheusRulesの設定
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheusrules.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/advanced/prometheusrules.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-promql-expressions: xref:observability/monitoring-and-dashboards/promql-expressions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-promql-expressions: xref:integrations-in-rancher/monitoring-and-alerting/promql-expressions.adoc
endif::[]

PrometheusRuleは、Prometheusのアラートおよび/または記録ルールのグループを定義します。

[NOTE]
====

このセクションは、監視コンポーネントがどのように連携して動作するかに精通していることを前提としています。詳細については、{xref-how-monitoring-works}[このセクションを参照してください。]
====


[#_creating_prometheusrules_in_the_rancher_ui]
== Rancher UIでのPrometheusRulesの作成

[NOTE]
.前提条件:
====

監視アプリケーションをインストールする必要があります。
====


Rancher UIでルールグループを作成するには、

. ルールグループを作成したいクラスターに移動します。menu:Monitoring[Advanced]をクリックし、*Prometheus Rules*をクリックします。
. ［*作成*］をクリックします。
. *グループ名*を入力してください。
. ルールを設定します。RancherのUIでは、ルールグループにはアラートルールまたは記録ルールのいずれかが含まれることを期待していますが、両方は含まれません。フォームの記入に関するヘルプは、以下の設定オプションを参照してください。
. ［*作成*］をクリックします。

*結果:*アラートは、受信者に通知を送信するように構成できます。

[#_about_the_prometheusrule_custom_resource]
== PrometheusRuleカスタムリソースについて

ルール（PrometheusRuleリソースのRuleGroup内で宣言される）を定義する際に、 https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#rule[ルール自体のspec]には、Alertmanagerがこのアラートを受信すべきルートを特定するために使用するラベルが含まれています。例えば、ラベル`team: front-end`を持つアラートは、そのラベルに一致するすべてのルートに送信されます。

Prometheusルールファイルは、PrometheusRuleカスタムリソースに保持されます。PrometheusRuleを使用すると、1つ以上のRuleGroupを定義できます。各RuleGroupは、アラートルールまたは記録ルールを表すことができるRuleオブジェクトのセットで構成され、以下のフィールドを持ちます：

* 新しいアラートまたは記録の名前
* 新しいアラートまたは記録のためのPromQL式
* アラートまたはレコードに添付されるべきラベル（例：クラスター名や重要度）
* アラートの通知に表示する必要がある追加の重要な情報をエンコードする注釈（例：要約、説明、メッセージ、ランブックのURLなど）。このフィールドは、記録ルールには必須ではありません。

指定できるフィールドに関する詳細については、 https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#prometheusrulespec[Prometheus Operator spec.]をご覧ください。

Prometheusオブジェクトのラベルセレクターフィールド `ruleSelector` を使用して、Prometheusにマウントしたいルールファイルを定義します。

例については、 https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/[記録ルール]および https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[アラートルール]に関するPrometheusのドキュメントを参照してください。

[#_configuration]
== 設定

[#_rule_group]
=== ルールグループ

|===
| フィールド | 説明

| Group Name
| グループの名前です。ルールファイル内で一意である必要があります。

| グループ間隔のオーバーライド
| グループ内のルールが評価される頻度の秒単位の期間。
|===

[#_alerting_rules]
=== アラートルール

https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[アラートルール]を使用すると、PromQL（Prometheus Query Language）式に基づいてアラート条件を定義し、発火したアラートについて外部サービスに通知を送信できます。

|===
| フィールド | 説明

| アラート名
| アラートの名前。有効なラベル値である必要があります。

| 発火までの待機時間
| 秒単位の期間。アラートは、この期間が経過すると発火したと見なされます。まだ十分に発火していないアラートは保留中と見なされます。

| PromQL式
| 評価するためのPromQL式です。Prometheusは、すべての評価サイクルでこのPromQL式の現在の値を評価し、すべての結果のタイムシリーズが保留/発火アラートになります。詳細については、 https://prometheus.io/docs/prometheus/latest/querying/basics/[Prometheusのドキュメント]または私たちの{xref-promql-expressions}[例のPromQL式]を参照してください。

| ラベル
| 各アラートに追加または上書きするラベルです。

| 緊急度
| 有効にすると、ラベルはアラートまたはレコードに添付され、重大度レベルによって識別されます。

| 重大度ラベルの値
| クリティカル、警告、またはなし

| 注釈
| アノテーションは、アラートの説明やランブックのリンクなど、長い追加情報を保存するために使用できる情報ラベルのセットです。 https://en.wikipedia.org/wiki/Runbook[ランブック]は、アラートの処理方法に関するドキュメントのセットです。アノテーションの値は https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating[テンプレート化できます。]
|===

[#_recording_rules]
=== 記録ルール

https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules[記録ルール]は、頻繁に必要とされるまたは計算コストの高いPromQL（Prometheus Query Language）式を事前に計算し、その結果を新しいタイムシリーズのセットとして保存できます。

|===
| フィールド | 説明

| タイムシリーズ名
| 出力するタイムシリーズの名前です。有効なメトリック名である必要があります。

| PromQL式
| 評価するためのPromQL式です。Prometheusは、すべての評価サイクルでこのPromQL式の現在の値を評価し、その結果を'レコード'で指定されたメトリック名を持つ新しいタイムシリーズのセットとして記録します。 式に関する詳細については、 https://prometheus.io/docs/prometheus/latest/querying/basics/[Prometheusのドキュメント]または私たちの{xref-promql-expressions}[例のPromQL式]を参照してください。

| ラベル
| 結果を保存する前に追加または上書きするラベルです。
|===
