= Configuration requise pour l'installation
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:product-path: installation-and-upgrade/requirements/requirements.adoc
:description: Découvrez les exigences des nœuds pour chaque nœud exécutant le serveur Rancher lorsque vous configurez Rancher pour fonctionner dans une configuration Kubernetes.
ifeval::["{build-type}" != "community"]
:url-k3s-advanced-docker-runtime: https://documentation.suse.com/cloudnative/k3s/latest/en/advanced.html#_using_docker_as_the_container_runtime
:url-rke2-requirements: https://documentation.suse.com/cloudnative/rke2/latest/en/install/requirements.html
:url-k3s-datastore: https://documentation.suse.com/cloudnative/k3s/latest/en/datastore/datastore.html
:url-k3s-requirements: https://documentation.suse.com/cloudnative/k3s/latest/en/installation/requirements.html
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-rancher-on-aks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
:xref-psact: xref:security/psact.adoc
:xref-rancher-on-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
:xref-tuning-rancher-at-scale: xref:installation-and-upgrade/best-practices/tuning-rancher-at-scale.adoc
:xref-tips-for-running-rancher: xref:installation-and-upgrade/best-practices/tips-for-running-rancher.adoc
:xref-rancher-on-arm64: xref:rancher-admin/experimental-features/rancher-on-arm64.adoc
:xref-rancher-on-gke: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc
:xref-dual-stack: xref:cluster-deployment/dual-stack.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-advanced-docker-runtime: https://docs.k3s.io/advanced#using-docker-as-the-container-runtime
:url-rke2-requirements: https://docs.rke2.io/install/requirements
:url-k3s-datastore: https://docs.k3s.io/datastore
:url-k3s-requirements: https://docs.k3s.io/installation/requirements
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-rancher-on-aks: xref:démarrer/installation-et-mise-à-niveau/installer-mise-à-niveau-sur-un-cluster-kubernetes/rancher-sur-aks.adoc
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
:xref-psact: xref:how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/psa-modèles-de-configuration.adoc
:xref-rancher-on-eks: xref:démarrer/installation-et-mise-à-niveau/installer-mise-à-niveau-sur-un-cluster-kubernetes/rancher-sur-amazon-eks.adoc
:xref-tuning-rancher-at-scale: xref:reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.adoc
:xref-tips-for-running-rancher: xref:reference-guides/best-practices/rancher-server/tips-for-running-rancher.adoc
:xref-rancher-on-arm64: xref:how-to-guides/advanced-user-guides/enable-experimental-features/rancher-on-arm64.adoc
:xref-rancher-on-gke: xref:démarrer/installation-et-mise-à-niveau/installer-mise-à-niveau-sur-un-cluster-kubernetes/rancher-sur-gke.adoc
:xref-dual-stack: xref:reference-guides/dual-stack.adoc
endif::[]

Cette page décrit les exigences logicielles, matérielles et réseau pour les nœuds où le serveur Rancher sera installé. Le serveur Rancher peut être installé sur un seul nœud ou un cluster Kubernetes à haute disponibilité.

[NOTE]
.Important :
====

Si vous installez Rancher sur un cluster Kubernetes, les exigences sont différentes de celles des {xref-node-reqs}[exigences des nœuds pour les clusters utilisateurs en aval], qui exécuteront vos applications et services.
====


L'interface utilisateur de Rancher fonctionne mieux dans Firefox ou les navigateurs basés sur Chromium (Chrome, Edge, Opera, Brave, etc.).

Consultez notre page sur les {xref-tips-for-running-rancher}[meilleures pratiques] pour une liste de recommandations pour exécuter un serveur Rancher en production.

[#_kubernetes_compatibility_with_rancher]
== Compatibilité de Kubernetes avec Rancher

Rancher doit être installé sur une version Kubernetes prise en charge. Consultez la https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[matrice de support Rancher] pour vous assurer que la version de Kubernetes que vous souhaitez utiliser est prise en charge.

Quelle que soit la version et la distribution, le cluster Kubernetes doit avoir la couche API d'agrégation correctement configurée pour prendre en charge l'xref:api/extension-apiserver.adoc[API d'extension] utilisée par Rancher.

[#_install_rancher_on_a_hardened_kubernetes_cluster]
=== Installez Rancher sur un cluster Kubernetes durci.

Si vous installez Rancher sur un cluster Kubernetes durci, consultez la section {xref-psact}#_exempting_required_rancher_namespaces[Exemption des espaces de noms Rancher requis] pour des exigences détaillées.

[#_install_rancher_on_an_ipv6_only_or_dual_stack_kubernetes_cluster]
=== Installez Rancher sur un cluster Kubernetes uniquement IPv6 ou Dual-stack.

Vous pouvez déployer Rancher sur un cluster Kubernetes uniquement IPv6 ou Dual-stack.

Pour des détails sur le support uniquement IPv6 et Dual-stack de Rancher, consultez la page {xref-dual-stack}[IPv4/IPv6 Dual-stack].

[#_operating_systems_and_container_runtime_requirements]
== Exigences des systèmes d'exploitation et de l'environnement d'exécution de conteneur

Tous les systèmes d'exploitation pris en charge sont en 64 bits x86. Rancher devrait fonctionner avec toute distribution Linux moderne.

La https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[matrice de support de Rancher] indique quels systèmes d'exploitation et versions de Docker ont été testés pour chaque version de Rancher.

Docker est requis pour les nœuds qui exécuteront des clusters RKE. Il n'est pas requis pour les clusters RKE2 ou K3s.

Le paquet `ntp` (Protocole de temps réseau) doit être installé. Cela empêche les erreurs de validation de certificat qui peuvent survenir lorsque l'heure n'est pas synchronisée entre le client et le serveur.

Certaines distributions de Linux peuvent avoir des règles de passerelle de périmètre de sécurité par défaut qui bloquent la communication au sein du cluster Kubernetes. Depuis Kubernetes v1.19, firewalld doit être désactivé, car il entre en conflit avec les plugins de mise en réseau de Kubernetes.

Si vous ne vous sentez pas à l'aise de le faire, vous pouvez consulter les suggestions dans le https://github.com/rancher/rancher/issues/28840[problème respectif]. Certains utilisateurs ont réussi https://github.com/rancher/rancher/issues/28840#issuecomment-787404822[à créer une zone firewalld séparée avec une stratégie d'ACCEPT pour le Pod CIDR].

Si vous prévoyez d'exécuter Rancher sur ARM64, consultez {xref-rancher-on-arm64}[Exécution sur ARM64 (Expérimental)].

[#__rke2_product_name_specific_requirements]
=== {rke2-product-name} Exigences spécifiques

RKE2 regroupe son propre environnement d'exécution de conteneur, containerd.

Pour des détails sur les versions de systèmes d'exploitation qui ont été testées avec RKE2, référez-vous à la https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[matrice de support de Rancher].

[#__k3s_product_name_specific_requirements]
=== {k3s-product-name} Exigences spécifiques

Pour l'environnement d'exécution de conteneur, K3s regroupe par défaut son propre containerd. Alternativement, vous pouvez configurer K3s pour utiliser un environnement d'exécution de conteneur Docker déjà installé. Pour plus d'informations sur l'utilisation de K3s avec Docker, consultez la {url-k3s-advanced-docker-runtime}[documentation K3s.]

Rancher doit être installé sur une version Kubernetes prise en charge. Pour savoir quelles versions de Kubernetes sont prises en charge pour votre version de Rancher, veuillez vous référer à la https://www.suse.com/suse-rancher/support-matrix/all-supported-versions[matrice de support de Rancher]. Pour spécifier la version K3s, utilisez la variable d'environnement INSTALL_K3S_VERSION lors de l'exécution du script d'installation K3s.

Si vous installez Rancher sur un cluster K3s avec *Raspbian Buster*, suivez https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster[ces étapes] pour passer à iptables legacy.

Si vous installez Rancher sur un cluster K3s avec Alpine Linux, suivez https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup[ces étapes] pour une configuration supplémentaire.

[#_hardware_requirements]
== Configuration matérielle requise

Les sections suivantes décrivent les exigences en matière de CPU, de mémoire et d'E/S pour les nœuds où Rancher est installé. Les exigences varient en fonction de la taille de l'infrastructure.

[#_practical_considerations]
=== Considérations pratiques

L'empreinte matérielle de Rancher dépend de plusieurs facteurs, notamment{nbsp}:

* Taille de l'infrastructure gérée (par exemple, nombre de nœuds, nombre de clusters).
* Complexité des règles de contrôle d'accès souhaitées (par exemple, `RoleBinding` nombre d'objets).
* Nombre de charges de travail (par exemple, déploiements Kubernetes, déploiements Fleet).
* Modèles d'utilisation (par exemple, sous-ensemble de fonctionnalités utilisées activement, fréquence d'utilisation, nombre d'utilisateurs simultanés).

Étant donné qu'il existe un grand nombre de facteurs influents qui peuvent varier dans le temps, les exigences énumérées ici doivent être comprises comme des points de départ raisonnables qui fonctionnent bien pour la plupart des cas d'utilisation. Néanmoins, votre cas d'utilisation peut avoir des exigences différentes. Pour des questions concernant un scénario spécifique, veuillez https://rancher.com/contact/[contacter Rancher] pour des conseils supplémentaires.

En particulier, les exigences sur cette page sont soumises à des hypothèses d'utilisation typiques, qui incluent{nbsp}:

* Moins de 60 000 ressources Kubernetes au total, par type.
* Jusqu'à 120 pods par nœud.
* Jusqu'à 200 CRD dans le cluster en amont (local).
* Jusqu'à 100 CRD dans les clusters en aval.
* Jusqu'à 50 déploiements Fleet.

Des nombres plus élevés sont possibles, mais les exigences peuvent être plus élevées. Si vous avez plus de 20 000 ressources du même type, le temps de chargement de la liste entière via l'interface utilisateur de Rancher peut prendre plusieurs secondes.

[NOTE]
.Evolution :
====

La base de code de Rancher évolue, les cas d'utilisation changent et l'ensemble de l'expérience accumulée de Rancher grandit chaque jour.

Les recommandations concernant les exigences matérielles sont susceptibles de changer au fil du temps, à mesure que les directives s'améliorent en précision et deviennent plus concrètes.

Si vous constatez que votre déploiement Rancher ne respecte plus les recommandations énumérées, https://rancher.com/contact/[contactez Rancher] pour une réévaluation.
====


[#__rke2_product_name_kubernetes]
=== {rke2-product-name} Kubernetes

Le tableau suivant répertorie les exigences minimales en CPU et en mémoire pour chaque nœud dans le {xref-install-rancher}[cluster en amont].

Veuillez noter qu'une configuration hautement disponible avec au moins trois nœuds est requise pour la production.

|===
| Taille de l'infrastructure gérée | Nombre maximum de clusters | Nombre maximum de nœuds | vCPUs | Mémoire vive

| Petite
| 150
| 1500
| 4
| 16 Go

| Moyen
| 300
| 3 000
| 8
| 32 Go

| Grand (*)
| 500
| 5000
| 16
| 64 Go

| Plus grand (†)
| (†)
| (†)
| (†)
| (†)
|===

(*): Les déploiements importants nécessitent que vous {xref-tuning-rancher-at-scale}[suiviez les meilleures pratiques] pour des performances adéquates.

(†): Des tailles de déploiement plus grandes sont généralement possibles avec des recommandations matérielles ad hoc et un réglage. Vous pouvez https://rancher.com/contact/[contacter Rancher] pour une évaluation personnalisée.

Consultez la documentation RKE2 pour des informations plus détaillées sur {url-rke2-requirements}[les exigences générales de RKE2].

[#__k3s_product_name_kubernetes]
=== {k3s-product-name} Kubernetes

Le tableau suivant répertorie les exigences minimales en CPU et en mémoire pour chaque nœud dans le {xref-install-rancher}[cluster en amont].

Veuillez noter qu'une configuration hautement disponible avec au moins trois nœuds est requise pour la production.

|===
| Taille de l'infrastructure gérée | Nombre maximum de clusters | Nombre maximum de nœuds | vCPUs | Mémoire vive | Hôte de base de données externe (*)

| Petite
| 150
| 1500
| 4
| 16 Go
| 2 vCPUs, 8 Go + 1000 IOPS

| Moyen
| 300
| 3 000
| 8
| 32 Go
| 4 vCPUs, 16 Go + 2000 IOPS

| Grand (†)
| 500
| 5000
| 16
| 64 Go
| 8 vCPUs, 32 Go + 4000 IOPS
|===

(*): L'hôte de base de données externe fait référence à l'hébergement du magasin de données du cluster K3s sur un {url-k3s-datastore}[hôte externe dédié]. Cette option est facultative. Les exigences exactes dépendent du magasin de données externe.

(†): Les déploiements importants nécessitent que vous {xref-tuning-rancher-at-scale}[suiviez les meilleures pratiques] pour des performances adéquates.

Consultez la documentation K3s pour des informations plus détaillées sur {url-k3s-requirements}[les exigences générales].

[#_hosted_kubernetes]
=== Kubernetes hébergé

Le tableau suivant répertorie les exigences minimales en UC et en mémoire pour chaque nœud dans le {xref-install-rancher}[cluster en amont].

Veuillez noter qu'une configuration hautement disponible avec au moins trois nœuds est requise pour la production.

Ces exigences s'appliquent aux clusters Kubernetes hébergés tels qu'Amazon Elastic Kubernetes Service (EKS), Azure Kubernetes Service (AKS) ou Google Kubernetes Engine (GKE). Elles ne s'appliquent pas aux solutions SaaS de Rancher telles que https://www.rancher.com/products/rancher[Rancher Prime Hosted].

|===
| Taille de l'infrastructure gérée | Nombre maximum de clusters | Nombre maximum de nœuds | vCPUs | Mémoire vive

| Petite
| 150
| 1500
| 4
| 16 Go

| Moyen
| 300
| 3 000
| 8
| 32 Go

| Grand (*)
| 500
| 5000
| 16
| 64 Go
|===

(*): Les déploiements importants nécessitent que vous {xref-tuning-rancher-at-scale}[suiviez les meilleures pratiques] pour des performances adéquates.

ifeval::["{build-type}" == "community"]

[#_docker]
=== Docker

Le tableau suivant répertorie les exigences minimales en UC et en mémoire pour une xref:[installation d'un seul nœud Docker de Rancher].

Veuillez noter qu'une installation Docker n'est adaptée qu'à des fins de développement ou de test et n'est pas destinée à être utilisée dans les environnements de production.

|===
| Taille de l'infrastructure gérée | Nombre maximum de clusters | Nombre maximum de nœuds | vCPUs | Mémoire vive

| Petite
| 5
| 50
| 1
| 4 Go

| Moyen
| 15
| 200
| 2
| 8 Go
|===

endif::[]

[#_ingress]
== Ingress

Chaque nœud du cluster Kubernetes sur lequel Rancher est installé doit exécuter un Ingress.

L'Ingress doit être déployé en tant que DaemonSet pour garantir que votre équilibreur de charge peut acheminer le trafic vers tous les nœuds avec succès.

Pour les installations RKE2 et K3s, vous n'avez pas besoin d'installer l'Ingress manuellement car il est installé par défaut.

Pour les clusters Kubernetes hébergés (EKS, GKE, AKS), vous devrez configurer l'ingress.

* *Amazon EKS:* Pour des détails sur l'installation de Rancher sur Amazon EKS, y compris comment installer un ingress pour que le serveur Rancher soit accessible, consultez {xref-rancher-on-eks}[cette page.]
* *AKS:* Pour des détails sur l'installation de Rancher avec Azure Kubernetes Service, y compris comment installer un ingress pour que le serveur Rancher soit accessible, consultez {xref-rancher-on-aks}[cette page.]
* *GKE:* Pour des détails sur l'installation de Rancher avec Google Kubernetes Engine, y compris comment installer un ingress pour que le serveur Rancher soit accessible, consultez {xref-rancher-on-gke}[cette page.]

[#_disks]
== Disques

Les performances de Rancher dépendent des performances d'etcd dans le cluster. Pour garantir une vitesse optimale, nous recommandons d'utiliser toujours des disques SSD pour soutenir votre cluster Kubernetes de gestion Rancher. Sur les fournisseurs de cloud, vous voudrez également utiliser la taille minimale qui permet le maximum d'IOPS. Dans les clusters plus grands, envisagez d'utiliser des dispositifs de stockage dédiés pour les données etcd et les répertoires wal.

[#_networking_requirements]
== Exigences réseau

Cette section décrit les exigences réseau pour le(s) nœud(s) où le serveur Rancher est installé.

[CAUTION]
====

Si un serveur contenant Rancher a l'en-tête `X-Frame-Options=DENY`, certaines pages de la nouvelle interface utilisateur de Rancher ne pourront pas être rendues après la mise à niveau depuis l'ancienne interface utilisateur. C'est parce que certaines pages anciennes sont intégrées sous forme d'iFrames dans la nouvelle interface utilisateur.
====


[#_node_ip_addresses]
=== Adresses IP des nœuds

Chaque nœud utilisé doit avoir une adresse IP statique configurée, que vous installiez Rancher sur un seul nœud ou sur un cluster HA. En cas de DHCP, chaque nœud doit avoir une réservation DHCP pour s'assurer que le nœud obtienne la même adresse IP allouée.

[#_port_requirements]
=== Exigences de port

Pour fonctionner correctement, Rancher nécessite qu'un certain nombre de ports soient ouverts sur les nœuds Rancher et sur les nœuds du cluster Kubernetes en aval. {xref-port-reqs}[Exigences de port] liste tous les ports nécessaires pour Rancher et les clusters en aval pour les différents types de clusters.

[#_load_balancer_requirements]
=== Exigences de l'équilibreur de charge

Si vous utilisez un équilibreur de charge, il doit être compatible HTTP/2.

Pour recevoir de l'aide du Support SUSE, les clients de Rancher Prime qui utilisent des équilibreurs de charge (ou tout autre dispositif intermédiaire tel que des passerelles de périmètre de sécurité) doivent utiliser un qui est compatible HTTP/2.

Lorsque HTTP/2 n'est pas disponible, Rancher revient à HTTP/1.1. Cependant, puisque HTTP/2 offre une meilleure performance des applications web, l'utilisation de HTTP/1.1 peut engendrer des problèmes de performance.
