= Best Practices for {rancher-product-name} Managed VMware vSphere Clusters
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-managed-clusters/rancher-managed-clusters-in-vsphere.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/best-practices.adoc

This guide outlines a reference architecture for provisioning downstream Rancher clusters in a vSphere environment, in addition to standard vSphere best practices as documented by VMware.

* <<_1_vm_considerations,1. VM Considerations>>
* <<_2_network_considerations,2. Network Considerations>>
* <<_3_storage_considerations,3. Storage Considerations>>
* <<_4_backups_and_disaster_recovery,4. Backups and Disaster Recovery>>

.Solution Overview
image::solution_overview.drawio.svg[Solution Overview]

[#_1_vm_considerations]
== 1. VM Considerations

[#_leverage_vm_templates_to_construct_the_environment]
=== Leverage VM Templates to Construct the Environment

To facilitate consistency across the deployed Virtual Machines across the environment, consider the use of "Golden Images" in the form of VM templates. Packer can be used to accomplish this, adding greater customisation options.

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_downstream_cluster_nodes_across_esxi_hosts]
=== Leverage DRS Anti-Affinity Rules (Where Possible) to Separate Downstream Cluster Nodes Across ESXi Hosts

Doing so will ensure node VM's are spread across multiple ESXi hosts - preventing a single point of failure at the host level.

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_downstream_cluster_nodes_across_datastores]
=== Leverage DRS Anti-Affinity Rules (Where Possible) to Separate Downstream Cluster Nodes Across Datastores

Doing so will ensure node VM's are spread across multiple datastores - preventing a single point of failure at the datastore level.

[#_configure_vms_as_appropriate_for_kubernetes]
=== Configure VM's as Appropriate for Kubernetes

It's important to follow K8s and etcd best practices when deploying your nodes, including disabling swap, double-checking you have full network connectivity between all machines in the cluster, using unique hostnames, MAC addresses, and product_uuids for every node.

[#_2_network_considerations]
== 2. Network Considerations

[#_leverage_low_latency_high_bandwidth_connectivity_between_etcd_nodes]
=== Leverage Low Latency, High Bandwidth Connectivity Between ETCD Nodes

Deploy etcd members within a single data center where possible to avoid latency overheads and reduce the likelihood of network partitioning. For most setups, 1Gb connections will suffice. For large clusters, 10Gb connections can reduce the time taken to restore from backup.

[#_consistent_ip_addressing_for_vms]
=== Consistent IP Addressing for VM's

Each node used should have a static IP configured. In the case of DHCP, each node should have a DHCP reservation to make sure the node gets the same IP allocated.

[#_3_storage_considerations]
== 3. Storage Considerations

[#_leverage_ssd_drives_for_etcd_nodes]
=== Leverage SSD Drives for ETCD Nodes

ETCD is very sensitive to write latency. Therefore, leverage SSD disks where possible.

[#_4_backups_and_disaster_recovery]
== 4. Backups and Disaster Recovery

[#_perform_regular_downstream_cluster_backups]
=== Perform Regular Downstream Cluster Backups

Kubernetes uses etcd to store all its data - from configuration, state and metadata. Backing this up is crucial in the event of disaster recovery.

[#_back_up_downstream_node_vms]
=== Back up Downstream Node VMs

Incorporate the Rancher downstream node VM's within a standard VM backup policy.
