= Sobre o rancher-selinux
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-01-20
:page-revdate: {revdate}
:community-path: reference-guides/rancher-security/selinux-rpm/about-rancher-selinux.adoc 
:product-path: security/selinux-rpm/about-rancher-selinux.adoc

Para permitir que o Rancher funcione com o SELinux, algumas funcionalidades precisam ser habilitadas manualmente para os nós do SELinux. Para ajudar com isso, o Rancher fornece um RPM do SELinux.

O `rancher-selinux` RPM contém um conjunto de políticas do SELinux projetadas para conceder os privilégios necessários a vários componentes do Rancher em sistemas Linux com o SELinux habilitado.

`rancher-selinux` repositório do GitHub está https://github.com/rancher/rancher-selinux[aqui.]

[#_installing_the_rancher_selinux_rpm]
== Instalando o RPM do rancher-selinux

[NOTE]
.de receita:
====
O `rancher-selinux` RPM foi testado no openSUSE Tumbleweed e em distribuições baseadas no RHEL, incluindo CentOS/RockyLinux 8 e 9.
====

[#_1_set_up_the_yum_repo]
=== 1. Configure o repositório yum

Configure o repositório yum para instalar `rancher-selinux` diretamente em todos os hosts do cluster.

Para usar o repositório RPM, em um sistema CentOS 8 ou RHEL 8, execute o seguinte trecho de bash:

----
# cat << EOF > /etc/yum.repos.d/rancher.repo
[rancher]
name=Rancher
baseurl=https://rpm.rancher.io/rancher/production/centos/8/noarch
enabled=1
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

Para usar o repositório RPM, em um sistema CentOS 9 ou RHEL 9, execute o seguinte trecho de bash:

----
# cat << EOF > /etc/yum.repos.d/rancher.repo
[rancher]
name=Rancher
baseurl=https://rpm.rancher.io/rancher/production/centos/9/noarch
enabled=1
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

[#_2_installing_the_rpm]
=== 2. Instalando o RPM

Instale o RPM:

----
yum -y install rancher-selinux
----

[#_configuring_the_logging_and_monitoring_applications_to_work_with_selinux]
== Configurando os Aplicativos de Registro e Monitoramento para Trabalhar com o SELinux

[NOTE]
.de receita:
====
Os aplicativos de registro v2 e monitoramento v2 foram testados com o SELinux no RHEL/CentOS 8, 9 e Tumbleweed.
====

Os aplicativos não funcionam automaticamente uma vez que o `rancher-selinux` RPM está instalado no host. Eles precisam ser configurados para rodar em um domínio de contêiner SELinux permitido fornecido pelo RPM.

Para configurar o chart `rancher-logging` ou `rancher-monitoring` para ser compatível com o SELinux, altere `global.seLinux.enabled` para true no `values.yaml` ao instalar os charts.
