= Personalizando Painéis do Grafana
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc 
:product-path: observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-rancher-monitoring-rbac: xref:observability/monitoring-and-dashboards/rbac-for-monitoring.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
endif::[]

Nesta seção, você aprenderá como personalizar o painel do Grafana para mostrar métricas que se aplicam a um determinado contêiner.

[#_prerequisites]
== Pré-requisitos

Antes de personalizar um painel do Grafana, o aplicativo `rancher-monitoring` deve estar instalado.

Para ver os links para as interfaces de monitoramento externas, incluindo os painéis do Grafana, você precisará ter pelo menos um {xref-rancher-monitoring-rbac}#_users_with_rancher_based_permissions[papel de membro do projeto.]

[#_signing_in_to_grafana]
== Fazendo login no Grafana

. Na interface do Rancher, vá para o cluster que possui o painel que você deseja personalizar.
. No menu de navegação à esquerda, clique em *Monitoramento.*
. Clique em *Grafana.* O painel do Grafana deve abrir em uma nova aba.
. Vá até o ícone de login no canto inferior esquerdo e clique em *Entrar.*
. Efetue login no Grafana. O nome de usuário e a senha padrão do Admin para a instância do Grafana é `admin/prom-operator`. (Independentemente de quem tenha a senha, a permissão de administrador do cluster no Rancher ainda é necessária para acessar a instância do Grafana.) Credenciais alternativas também podem ser fornecidas ao implantar ou atualizar o gráfico.

[#_getting_the_promql_query_powering_a_grafana_panel]
== Obtendo a consulta PromQL que alimenta um painel do Grafana

Para qualquer painel, você pode clicar no título e clicar em *Explorar* para obter as consultas PromQL que alimentam o gráfico.

Para este exemplo, gostaríamos de obter o uso da CPU para o contêiner Alertmanager, então clicamos em menu:Utilização de CPU[Inspecionar.]

A aba *Dados* mostra os dados subjacentes como uma série temporal, com o tempo na primeira coluna e o resultado da consulta PromQL na segunda coluna. Copie a consulta PromQL.

----
(1 - (avg(irate({__name__=~"node_cpu_seconds_total|windows_cpu_time_total",mode="idle"}[5m])))) * 100
----

Você pode então modificar a consulta no painel do Grafana ou criar um novo painel do Grafana usando a consulta.

Consulte também:

* https://grafana.com/docs/grafana/latest/panels-visualizations/configure-panel-options/#edit-a-panel[Documentação do Grafana sobre edição de um painel]
* https://grafana.com/docs/grafana/latest/panels-visualizations/panel-editor-overview[Documentação do Grafana sobre adicionar um painel a um dashboard]
