= {rancher-product-name} Architecture
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/rancher-manager-architecture/index.adoc 
:product-path: about-rancher/architecture/architecture.adoc
ifeval::["{build-type}" != "community"]
:xref-arch-com-ds-cluster: xref:about-rancher/architecture/communicating-with-downstream-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-arch-com-ds-cluster: xref:reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.adoc
endif::[]

This section focuses on the xref:about-rancher/architecture/rancher-server-and-components.adoc[Rancher server and its components] and how {xref-arch-com-ds-cluster}[Rancher communicates with downstream Kubernetes clusters].

For information on the different ways that Rancher can be installed, refer to the xref:installation-and-upgrade/installation-and-upgrade.adoc#_overview_of_installation_options[overview of installation options.]

For a list of main features of the Rancher API server, refer to the xref:about-rancher/overview.adoc#_features_of_the_rancher_api_server[overview section.]

For guidance about setting up the underlying infrastructure for the Rancher server, refer to the xref:about-rancher/architecture/recommendations.adoc[architecture recommendations.]

[NOTE]
====

This section assumes a basic familiarity with Docker and Kubernetes. For a brief explanation of how Kubernetes components work together, refer to the xref:about-rancher/concepts.adoc[concepts] page.
====

