= Configuration d'un fournisseur de cloud VMware vSphere hors arbre
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: xref:procédures/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-mise-en-place/mise-en-place-fournisseurs-de-cloud/configurer-vsphere-hors-arbre.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:experimental:

Kubernetes s'éloigne de la gestion des fournisseurs de cloud in-tree. VMware vSphere dispose d'un fournisseur de cloud out-of-tree qui peut être utilisé en installant le fournisseur de cloud vSphere et les plugins de stockage cloud.

Cette page explique comment installer les plugins de l'interface de fournisseur de cloud (CPI) et de l'interface de stockage cloud (CSI) après avoir configuré un cluster.

[#_prerequisites]
== Conditions préalables

Les versions de vSphere prises en charge{nbsp}:

* 6.7u3
* 7.0u1 ou supérieur.

La version de Kubernetes doit être 1.19 ou supérieure.

L'utilisation du fournisseur de cloud vSphere hors arbre nécessite des nœuds Linux et n'est pas prise en charge sur Windows.

[#_installation]
== Installation

L'interface de fournisseur de cloud (CPI) doit être installée en premier avant d'installer l'interface de stockage cloud (CSI).

[#_1_create_a_vmware_vsphere_cluster]
=== 1. Créer un cluster VMware vSphere

. Cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, cliquez sur *Créer*.
. Cliquez sur *VMware vSphere* ou *Personnalisé*.
. Dans l'onglet *Informations de base* dans la section *Configuration du cluster*, définissez le *Fournisseur de cloud* sur *vSphere*.
. Dans l'onglet *Configuration du produit complémentaire*, se trouvent les options du fournisseur de cloud vSphere (CPI) et du fournisseur de stockage (CSI).
. Terminez la création de votre cluster.

[#_2_install_the_cpi_plugin]
=== 2. Installer le plugin CPI

. Cliquez sur *☰ > Gestion des clusters*.
. Allez au cluster où le plugin vSphere CPI sera installé et cliquez sur *Explorer*.
. Cliquez sur menu:Apps[Charts].
. Cliquez sur *vSphere CPI*.
. Remplissez les détails requis de vCenter.
. vSphere CPI initialise tous les nœuds avec ProviderID, qui est nécessaire pour le pilote vSphere CSI. Vérifiez si tous les nœuds sont initialisés avec le ProviderID avant d'installer le pilote CSI avec la commande suivante{nbsp}:
+
----
 kubectl describe nodes | grep "ProviderID"
----

[#_3_installing_the_csi_plugin]
=== 3. Installation du plugin CSI

. Cliquez sur *☰ > Gestion des clusters*.
. Allez au cluster où le plugin vSphere CSI sera installé et cliquez sur *Explorer*.
. Cliquez sur menu:Apps[Charts].
. Click *vSphere CSI*.
. Cliquez sur *Installer*.
. Remplissez les détails requis de vCenter. Dans l'onglet *Fonctionnalités*, définissez *Activer la migration CSI* sur *false*.
. Dans l'onglet *Stockage*, remplissez les détails pour la StorageClass. Ce chart crée un StorageClass avec le `csi.vsphere.vmware.com` comme provisionneur.
. Cliquez sur *Installer*.

[#_using_the_csi_driver_for_provisioning_volumes]
== Utiliser le pilote CSI pour le provisionnement des volumes

Le chart CSI crée par défaut une StorageClass.

Si cette option n'a pas été sélectionnée lors du lancement du chart, créez une StorageClass avec le `csi.vsphere.vmware.com` comme provisionneur.

Tous les volumes provisionnés en utilisant cette StorageClass seront provisionnés par le pilote CSI.
