= Configuration d'un fournisseur de cloud VMware vSphere intégré
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: xref:procédures/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-configuration/configuration-fournisseurs-de-cloud/configurer-vsphere-intégrée.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc

Pour configurer le fournisseur de cloud VMware vSphere intégré, suivez ces étapes lors de la création du cluster vSphere dans Rancher{nbsp}:

. Définissez l'option *Fournisseur de Cloud* sur `Custom` ou `Custom (In-Tree)`.
. Cliquez sur *Modifier en YAML*
. Insérez la structure suivante dans le YAML du cluster pré-rempli. Cette structure doit être placée sous `rancher_kubernetes_engine_config`. Notez que le `name` _doit_ être défini sur `vsphere`.
+
[,yaml]
----
 rancher_kubernetes_engine_config:
   cloud_provider:
       name: vsphere
       vsphereCloudProvider:
           [Insert provider configuration]
----

Rancher utilise RKE (le Rancher Kubernetes Engine) pour provisionner des clusters Kubernetes. Référez-vous à la https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/config-reference/[référence de configuration vSphere dans la documentation RKE] pour des détails sur les propriétés de la directive `vsphereCloudProvider`.
