= Mise en place des fournisseurs de cloud
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/index.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
ifeval::["{build-type}" != "community"]
:xref-azure-cloud-provider: xref:cluster-deployment/set-up-cloud-providers/azure.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-cloud-provider-amazon: xref:cluster-deployment/set-up-cloud-providers/amazon.adoc
:xref-cloud-provider-google-compute-engine: xref:cluster-deployment/set-up-cloud-providers/google-compute-engine.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-azure-cloud-provider: xref:procédures-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/configuration-cloud-providers/azure.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:procédures/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-mise-en-place/mise-en-place-fournisseurs-de-cloud/configurer-vsphere-hors-arbre.adoc
:xref-cloud-provider-vsphere: xref:procédures/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-mise-en-place/mise-en-place-fournisseurs-de-cloud/configurer-vsphere-intégrée.adoc
:xref-cloud-provider-amazon: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon.adoc
:xref-cloud-provider-google-compute-engine: xref:procédures/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-mise-en-place/mise-en-place-fournisseurs-de-cloud/google-compute-engine.adoc
endif::[]

Un _fournisseur de cloud_ est un module dans Kubernetes qui fournit une interface pour gérer les nœuds, les équilibreurs de charge et les routes réseau.

Lorsqu'un fournisseur de cloud est mis en place dans Rancher, le serveur Rancher peut automatiquement provisionner de nouveaux nœuds, équilibreurs de charge ou dispositifs de stockage persistant lors du lancement des définitions Kubernetes, si le fournisseur de cloud que vous utilisez prend en charge une telle automatisation.

Votre cluster ne sera pas correctement provisionné si vous configurez un cluster de nœuds pour un fournisseur de cloud qui ne répond pas aux prérequis.

Par défaut, l'option *Fournisseur de cloud* est définie sur `None`.

Les fournisseurs de cloud suivants peuvent être activés :

* Amazon
* Azure
* GCE (Google Compute Engine)
* vSphere

[#_setting_up_the_amazon_cloud_provider]
== Mise en place du fournisseur de cloud Amazon

Pour des détails sur l'activation du fournisseur de cloud Amazon, référez-vous à {xref-cloud-provider-amazon}[cette page.]

[#_setting_up_the_azure_cloud_provider]
== Mise en place du fournisseur de cloud Azure

Pour des détails sur l'activation du fournisseur de cloud Azure, référez-vous à {xref-azure-cloud-provider}[cette page.]

[#_setting_up_the_gce_cloud_provider]
== Mise en place du fournisseur de cloud GCE

Pour des détails sur l'activation du fournisseur de cloud Google Compute Engine, référez-vous à {xref-cloud-provider-google-compute-engine}[cette page.]

[#_setting_up_the_vmware_vsphere_cloud_provider]
== Mise en place du fournisseur de cloud VMware vSphere

Pour des détails sur l'activation du fournisseur de cloud vSphere, référez-vous à {xref-cloud-provider-vsphere}[configuration vSphere intégrée] et {xref-cloud-provider-vsphere-out-of-tree}[configuration vSphere externe].

[#_setting_up_a_custom_cloud_provider]
== Mise en place d'un fournisseur de cloud personnalisé

Le fournisseur de cloud `Custom` est disponible si vous souhaitez configurer n'importe quel fournisseur de cloud Kubernetes.

Pour l'option de fournisseur de cloud personnalisé, vous pouvez vous référer à la https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/[docs RKE] pour savoir comment modifier le fichier yaml pour votre fournisseur de cloud spécifique. Il existe des fournisseurs de cloud spécifiques qui ont une configuration plus détaillée :

* https://rke.docs.rancher.com/config-options/cloud-providers/vsphere[vSphere]
* https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/openstack/[OpenStack]
