= {longhorn-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/longhorn/index.adoc 
:product-path: integrations/longhorn/longhorn.adoc

Longhorn est un projet officiel https://cncf.io/[de la Cloud Native Computing Foundation (CNCF)] qui offre une puissante plateforme de stockage distribué natif Cloud pour Kubernetes pouvant fonctionner n'importe où. Lorsqu'il est combiné avec Rancher, Longhorn facilite le déploiement d'un stockage de blocs persistant hautement disponible dans votre environnement Kubernetes de manière simple, rapide et fiable.

[#__longhorn_product_name_with_rancher]
== {longhorn-product-name} avec Rancher

Avec Rancher Prime et Longhorn, les utilisateurs peuvent facilement déployer en un clic via le catalogue Rancher et gérer le cycle de vie des clusters gérés, ce qui leur permet d'installer et de mettre à niveau, ainsi que d'exécuter une opération de drainage pour assurer une transition en douceur. Longhorn avec Rancher offre également une prise en charge des clusters mixtes avec Windows, des images hébergées par Rancher, un accès proxy UI via Rancher, et la surveillance via Rancher avec des métriques Longhorn.
