= CPU- und Speicherzuweisungen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/cpu-and-memory-allocations.adoc 
:product-path: observability/istio/cpu-and-memory-allocations.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-config: xref:observability/istio/configuration/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ist seit Rancher v2.12.0 ausgelaufen; wenden Sie sich an die https://apps.rancher.io[SUSE Application Collection] Version von Istio für verbesserte Sicherheit (in SUSE Rancher Prime-Abonnements enthalten).
Detaillierte Informationen finden Sie in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[dieser Ankündigung].
====

Dieser Abschnitt beschreibt die minimal empfohlenen Rechenressourcen für die Istio-Komponenten in einem Cluster.

Die CPU- und Arbeitsspeicherzuweisungen für jede Komponente sind <<_configuring_resource_allocations,konfigurierbar.>>

Bevor Sie Istio aktivieren, empfehlen wir, dass Sie bestätigen, dass Ihre Rancher-Worker-Knoten genügend CPU und Arbeitsspeicher haben, um alle Komponenten von Istio auszuführen.

[TIP]
====

Bei größeren Bereitstellungen wird dringend empfohlen, die Infrastruktur auf dedizierte Knoten im Cluster zu platzieren, indem für jede Istio-Komponente ein Knoten-Selector hinzugefügt wird.
====


Die folgende Tabelle zeigt eine Zusammenfassung der minimal empfohlenen Ressourcennachfragen und -limits für die CPU und den Arbeitsspeicher jeder Kern-Istio-Komponente.

In Kubernetes zeigt die Ressourcennachfrage an, dass die Arbeitslast nicht auf einem Knoten bereitgestellt wird, es sei denn, der Knoten hat mindestens die angegebene Menge an Arbeitsspeicher und CPU verfügbar. Wenn die Arbeitslast das Limit für CPU oder Arbeitsspeicher überschreitet, kann sie beendet oder vom Knoten entfernt werden. Für weitere Informationen zur Verwaltung von Ressourcenlimits für Container verweisen Sie auf die https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/[Kubernetes-Dokumentation.]

|===
| Workload | CPU - Anfrage | Speicher - Anfrage | CPU - Limit | Arbeitsspeicher - Limit

| Ingress-Gateway
| 100m
| 128mi
| 2000m
| 1024mi

| Egress-Gateway
| 100m
| 128mi
| 2000m
| 1024mi

| istiod
| 500 m
| 2048mi
| Keine Begrenzung
| Keine Begrenzung

| Vertretung
| 10 m
| 10mi
| 2000m
| 1024mi

| *Gesamt:*
| *710m*
| *2314Mi*
| *6000m*
| *3072Mi*
|===

[#_configuring_resource_allocations]
== Konfigurieren von Ressourcenallokationen

Sie können die Ressourcenallokation für jeden Typ von Istio-Komponente individuell konfigurieren. Dieser Abschnitt enthält die Standardressourcenallokationen für jede Komponente.

Um es einfacher zu machen, die Arbeitslasten einem Knoten zuzuweisen, kann ein Cluster-Administrator die CPU- und Speicherressourcenanforderungen für die Komponente reduzieren. Die Standard-CPU- und Speicherressourcenallokationen sind jedoch das Minimum, das wir empfehlen.

Weitere Informationen zur Istio-Konfiguration finden Sie in der https://istio.io/[offiziellen Istio-Dokumentation].

Um die Ressourcen zu konfigurieren, die einer Istio-Komponente zugewiesen sind,

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, das Sie erstellt haben, und klicken Sie auf *Erforschen*.
. Klicken Sie in der linken Navigationsleiste auf *Apps*.
. Klicken Sie auf *Installierte Apps*.
. Gehen Sie zum `istio-system` Namespace. Klicken Sie in einer der Istio-Arbeitslasten, wie z. B. `rancher-istio`, auf *⋮ > Bearbeiten/Upgrade*.
. Klicken Sie auf *Upgrade*, um die Basiskomponenten über Änderungen an der values.yaml zu bearbeiten oder eine {xref-istio-config}#_overlay_file[Overlay-Datei] hinzuzufügen. Weitere Informationen zum Bearbeiten der Overlay-Datei finden Sie in <<_editing_the_overlay_file,diesen Abschnitt.>>
. Ändern Sie die CPU- oder Speicherkapazitäten, die Knoten, auf denen jede Komponente geplant wird, oder die Knoten-Toleranzen.
. Klicken Sie auf *Upgrade*, um Änderungen bereitzustellen.

*Ergebnis:* Die Ressourcenallokationen für die Istio-Komponenten wurden aktualisiert.

[#_editing_the_overlay_file]
=== Bearbeiten der Overlay-Datei

Die Overlay-Datei kann beliebige Werte aus der https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec[Istio Operator-Spezifikation] enthalten. Die mit der Istio-Anwendung bereitgestellte Overlay-Datei ist nur ein Beispiel für eine mögliche Konfiguration der Overlay-Datei.

Solange die Datei `kind: IstioOperator` enthält und die YAML-Optionen gültig sind, kann die Datei als Overlay verwendet werden.

In der mit der Istio-Anwendung bereitgestellten Beispiel-Overlay-Datei können Sie im folgenden Abschnitt Kubernetes-Ressourcen ändern:

----
#      k8s:
#        resources:
#          requests:
#            cpu: 200m
----
