= Istio deaktivieren
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/disable-istio.adoc 
:product-path: observability/istio/disable-istio.adoc

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ist seit Rancher v2.12.0 ausgelaufen; wenden Sie sich an die https://apps.rancher.io[SUSE Application Collection] Version von Istio für verbesserte Sicherheit (in SUSE Rancher Prime-Abonnements enthalten).
Detaillierte Informationen finden Sie in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[dieser Ankündigung].
====

In diesem Abschnitt wird beschrieben, wie Sie Istio in einem Cluster deinstallieren oder einen Namespace oder eine Arbeitslast deaktivieren.

[#_uninstall_istio_in_a_cluster]
== Istio in einem Cluster deinstallieren

Um Istio zu deinstallieren,

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, das Sie erstellt haben, und klicken Sie auf *Erforschen*.
. Klicken Sie in der linken Navigationsleiste auf menu:Apps[Installierte Apps].
. Gehen Sie im `istio-system` Namespace zu `rancher-istio` und klicken Sie auf *⋮ > Löschen*.
. Nachdem `rancher-istio` gelöscht wurde, können Sie alle verbleibenden Apps im `istio-system` Namespace auswählen und auf *Löschen* klicken.

*Ergebnis:* Die `rancher-istio` App im Cluster wird entfernt. Der Istio Sidecar kann nicht auf Arbeitslasten im Cluster bereitgestellt werden.

[NOTE]
====

Sie können Ihre Istio-Installation nicht mehr deaktivieren und wieder aktivieren. Wenn Sie Ihre Einstellungen für eine zukünftige Installation speichern möchten, sehen Sie sich die einzelnen YAML-Dateien an und speichern Sie diese, um sie für zukünftige Installationen wiederzuverwenden.
====


*Fehlersuche bei der Deinstallation:* Wenn Sie die Deinstallationsschritte nicht befolgt haben, kann es während der Deinstallation zu einer Warnung kommen:

`Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: unable to recognize "": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"`

Das könnte einige Dinge bedeuten. Entweder haben Sie alle Apps im `istio-system` Namespace ausgewählt und gleichzeitig gelöscht, oder Sie haben die `rancher-istio` Chart-Abhängigkeiten vor dem Löschen des `rancher-istio` Charts gelöscht. Da die Deinstallation nicht ordnungsgemäß abgeschlossen wurde, verbleiben Ressourcen im `istio-system` Namespace, die Sie manuell bereinigen müssen. Eine weitere Möglichkeit, um manuelle Bereinigungen zu vermeiden, besteht darin, `rancher-istio` erneut zu installieren und es dann in der richtigen Reihenfolge zu deinstallieren.

[#_disable_istio_in_a_namespace]
== Deaktivieren Sie Istio in einem Namespace

. Klicken Sie auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, den Sie erstellt haben, und klicken Sie auf *Erforschen*.
. Klicken Sie auf menu:Cluster[Projekte/Namespaces].
. Gehen Sie zu dem Namespace, in dem Sie Istio aktivieren möchten, und klicken Sie auf *⋮  > Istio-Auto-Injektion aktivieren*. Alternativ klicken Sie auf den Namespace und klicken Sie dann auf der Detailseite des Namespaces auf *⋮  > Istio-Auto-Injektion aktivieren*.

*Ergebnis:* Wenn Arbeitslasten in diesem Namespace bereitgestellt werden, haben sie keinen Istio Sidecar.

[#_remove_the_istio_sidecar_from_a_workload]
== Entfernen Sie den Istio Sidecar von einer Arbeitslast

Deaktivieren Sie Istio im Namespace und stellen Sie die Workloads darin neu bereit. Sie werden ohne den Istio Sidecar bereitgestellt.
