= Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/index.adoc 
:product-path: observability/istio/istio.adoc
ifeval::["{build-type}" != "community"]
:xref-monitoring-and-dashboards: xref:observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
:xref-istio-guides: xref:observability/istio/guides/guides.adoc
:xref-istio-cpu-memory-allocations: xref:observability/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:observability/istio/configuration/install-istio-on-rke2-cluster.adoc
:xref-istio-config: xref:observability/istio/configuration/configuration.adoc
:xref-istio-disable: xref:observability/istio/disable-istio.adoc
:xref-istio-rbac: xref:observability/istio/rbac.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-monitoring-and-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/index.adoc
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
:xref-istio-guides: xref:how-to-guides/advanced-user-guides/istio-setup-guide/index.adoc
:xref-istio-cpu-memory-allocations: xref:integrations-in-rancher/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
:xref-istio-disable: xref:integrations-in-rancher/istio/disable-istio.adoc
:xref-istio-rbac: xref:integrations-in-rancher/istio/rbac-for-istio.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ist seit Rancher v2.12.0 ausgelaufen; wenden Sie sich an die https://apps.rancher.io[SUSE Application Collection] Version von Istio für verbesserte Sicherheit (in SUSE Rancher Prime-Abonnements enthalten).
Detaillierte Informationen finden Sie in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[dieser Ankündigung].
====

https://istio.io/[Istio] ist ein Open-Source-Tool, das es DevOps-Teams erleichtert, den Datenverkehr innerhalb eines komplexen Netzwerks von Mikrodiensten zu beobachten, zu sichern, zu steuern und zu beheben.

Wenn sich ein Netzwerk von Mikrodiensten ändert und wächst, können die Interaktionen zwischen ihnen zunehmend schwierig zu verwalten und zu verstehen werden. In einer solchen Situation ist es nützlich, ein Service-Mesh als separate Infrastrukturebene zu haben. Das Service-Mesh von Istio ermöglicht es Ihnen, den Datenverkehr zwischen Mikrodiensten zu steuern, ohne die Mikrodienste direkt zu ändern.

Unsere Integration von Istio ist so konzipiert, dass ein Rancher-Betreiber, wie ein Administrator oder Clusterbesitzer, Istio an ein Team von Entwicklern bereitstellen kann. Dann können Entwickler Istio verwenden, um Sicherheitsrichtlinien durchzusetzen, Probleme zu beheben oder den Datenverkehr für grüne/blaue Bereitstellungen, Canary-Bereitstellungen oder A/B-Tests zu verwalten.

Dieses Kernel-Service-Mesh bietet Funktionen, die unter anderem Folgendes umfassen:

* *Datenverkehrsmanagement* wie Eingangs- und Ausgangs-Routing, Circuit-Breaking, Spiegelung.
* *Sicherheit* mit Ressourcen zur Authentifizierung und Autorisierung von Datenverkehr und Benutzern, mTLS eingeschlossen.
* *Einblick* von Protokollen, Metriken und verteilten Datenverkehrsflüssen.

Nach {xref-istio-guides}[Einrichten von Istio] können Sie die Funktionalität der Steuerungsebene von Istio über die Rancher-Benutzeroberfläche, `kubectl`, oder `istioctl` nutzen.

Istio muss von einem `cluster-admin` eingerichtet werden, bevor es in einem Projekt verwendet werden kann.

[#_whats_new_in_rancher_v2_5]
== Was gibt es Neues in Rancher v2.5

Die Gesamtarchitektur von Istio wurde vereinfacht. Eine einzelne Komponente, Istiod, wurde durch die Kombination von Pilot, Citadel, Galley und dem Sidecar-Injektor erstellt. Die Funktionalität des Node Agents wurde ebenfalls in den istio-agent integriert.

Addons, die zuvor von Istio installiert wurden (cert-manager, Grafana, Jaeger, Kiali, Prometheus, Zipkin), müssen jetzt separat installiert werden. Istio wird die Installation von Integrationen unterstützen, die aus dem Istio-Projekt stammen, und die Kompatibilität mit Integrationen gewährleisten, die nicht aus dem Istio-Projekt stammen.

Eine Prometheus-Integration wird weiterhin über eine Installation von {xref-monitoring-and-dashboards}[Rancher Monitoring] oder durch die Installation Ihres eigenen Prometheus-Operators verfügbar sein. Das Istio-Chart von Rancher wird auch standardmäßig Kiali installieren, um sicherzustellen, dass Sie ein vollständiges Bild Ihrer Mikrodienste sofort erhalten.

Istio hat sich von Helm als Installationsmethode für Istio entfernt und bietet jetzt die Installation über die istioctl-Binärdatei oder den Istio-Operator an. Um die einfachste Interaktion mit Istio zu gewährleisten, wird das Istio von Rancher ein Helm-Chart beibehalten, das die istioctl-Binärdatei verwendet, um Ihre Istio-Installation zu verwalten.

Dieses Helm-Chart wird über die Apps und den Marktplatz in der Benutzeroberfläche verfügbar sein. Ein Benutzer, der Zugriff auf den Katalog der Rancher-Charts hat, muss Istio einrichten, bevor es im Projekt verwendet werden kann.

[#_tools_bundled_with_istio]
== Werkzeuge, die mit Istio gebündelt sind

Unser https://istio.io/[Istio] Installer umschließt die Befehle der istioctl-Binärdatei in einem praktischen Helm-Chart, einschließlich einer Overlay-Dateioption, um komplexe Anpassungen zu ermöglichen.

Es enthält auch Folgendes:

[#_kiali]
=== Kiali

https://kiali.io/[Kiali] ist ein umfassendes Visualisierungshilfsmittel, das zur grafischen Darstellung des Datenverkehrsflusses im Service Mesh verwendet wird. Es ermöglicht Ihnen zu sehen, wie sie verbunden sind, einschließlich der Verkehrsraten und Latenzen zwischen ihnen.

Sie können die Gesundheit des Service Mesh überprüfen oder detailliert sehen, welche eingehenden und ausgehenden Anfragen an eine einzelne Komponente gerichtet sind.

[NOTE]
====
Für Istio-Installationen `103.1.0+up1.19.6` und später verwendet Kiali ein Token für seine Authentifizierungsstrategie. Der Name des Kiali-Dienstkontos in Rancher ist `kiali`. Verwenden Sie diesen Namen, wenn Sie Befehle schreiben, die erfordern, dass Sie den Namen des Kiali-Dienstkontos eingeben (zum Beispiel, wenn Sie versuchen, ein Sitzungstoken zu generieren oder abzurufen). Für weitere Informationen siehe die https://kiali.io/docs/faq/authentication/[Kiali-Token-Authentifizierungs-FAQ].
====


[#_jaeger]
=== Jaeger

Unser Istio-Installer enthält eine Kurzanleitung, All-in-One-Installation von https://www.jaegertracing.io/[Jaeger,], einem Tool, das zum Tracing verteilter Systeme verwendet wird.

Beachten Sie, dass dies keine produktionsqualifizierte Bereitstellung von Jaeger ist. Diese Bereitstellung verwendet eine In-Memory-Speicherkomponente, während für die Produktion eine persistente Speicherkomponente empfohlen wird. Für weitere Informationen zu der Bereitstellungsstrategie, die Sie möglicherweise benötigen, siehe die https://www.jaegertracing.io/docs/1.65/operator/#production-strategy[Jaeger-Dokumentation.]

[#_prerequisites]
== Voraussetzungen

Bevor Sie Istio aktivieren, empfehlen wir, dass Sie bestätigen, dass Ihre Rancher-Worker-Knoten genügend {xref-istio-cpu-memory-allocations}[CPU und Arbeitsspeicher] haben, um alle Komponenten von Istio auszuführen.

Wenn Sie Istio in einem RKE2-Cluster installieren, sind einige zusätzliche Schritte erforderlich. Für Details siehe <<_additional_steps_for_installing_istio_on_an_rke2_cluster,diesen Abschnitt.>>

[#_setup_guide]
== Einrichtungshandbuch

Siehe die {xref-istio-guides}[setup guide] für Anweisungen, wie Sie Istio einrichten und in einem Projekt verwenden können.

[#_remove_istio]
== Istio entfernen

Um Istio-Komponenten aus einem Cluster, Namespace oder einer Arbeitslast zu entfernen, verweisen Sie auf den Abschnitt über {xref-istio-disable}[Istio entfernen].

[#_accessing_visualizations]
== Zugriff auf Visualisierungen

____
Standardmäßig haben nur Cluster-Administratoren Zugriff auf Kiali. Für Anweisungen, wie Sie Admin-, Bearbeitungs- oder Ansichtsrollen den Zugriff gewähren können, siehe {xref-istio-rbac}[diesen Abschnitt.]
____

[NOTE]
====
Für Istio-Installationen der Version `103.1.0+up1.19.6` und später verwendet Kiali einen Token für seine Authentifizierungsstrategie. Der Name des Kiali-Dienstkontos in Rancher ist `kiali`. Verwenden Sie diesen Namen, wenn Sie Befehle schreiben, die erfordern, dass Sie den Namen des Kiali-Dienstkontos eingeben (zum Beispiel, wenn Sie versuchen, ein Sitzungstoken zu generieren oder abzurufen). Für weitere Informationen siehe die https://kiali.io/docs/faq/authentication/[Kiali-Token-Authentifizierungs-FAQ].
====


Nachdem Istio in einem Cluster eingerichtet ist, sind Grafana, Prometheus und Kiali in der Rancher-Benutzeroberfläche verfügbar.

Um auf die Grafana- und Prometheus-Visualisierungen zuzugreifen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der *Clusters*-Seite zu dem Cluster, in dem Sie die Visualisierungen sehen möchten, und klicken Sie auf *Erforschen*.
. Klicken Sie in der linken Navigationsleiste auf *Monitoring*.
. Klicken Sie auf *Grafana* oder eines der anderen Dashboards.

Um auf die Kiali-Visualisierung zuzugreifen,

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie auf der Seite *Clusters* zu dem Cluster, in dem Sie Kiali sehen möchten, und klicken Sie auf *Explore*.
. Klicken Sie in der linken Navigationsleiste auf *Istio*.
. Klicken Sie auf *Kiali*. Von hier aus können Sie auf die Registerkarte *Traffic Graph* oder die Registerkarte *Traffic Metrics* zugreifen, um Netzwerkvisualisierungen und Metriken zu sehen.

Standardmäßig werden alle Namespaces von Prometheus erfasst und Daten für Kiali-Diagramme bereitgestellt. Verweisen Sie auf {xref-selectors-and-scrape-configurations}[selector/scrape config setup], wenn Sie eine andere Konfiguration für das Scraping von Prometheus-Daten verwenden möchten.

Ihr Zugriff auf die Visualisierungen hängt von Ihrer Rolle ab. Grafana und Prometheus sind nur für `cluster-admin` Rollen verfügbar. Die Kiali-Benutzeroberfläche ist standardmäßig nur für `cluster-admin` verfügbar, aber `cluster-admin` kann anderen Rollen den Zugriff ermöglichen, indem die Istio values.yaml bearbeitet wird.

[#_architecture]
== Architektur

Istio installiert ein Service-Mesh, das https://www.envoyproxy.io[Envoy] Sidecar-Proxys verwendet, um den Datenverkehr zu jedem Workload abzufangen. Diese Sidecars fangen die Kommunikation zwischen den Diensten ab und verwalten sie, was eine feingranulare Beobachtung und Kontrolle über den Datenverkehr innerhalb des Clusters ermöglicht.

Nur Workloads, die das Istio-Sidecar injiziert haben, können von Istio verfolgt und kontrolliert werden.

Wenn ein Namespace Istio aktiviert hat, erhalten neue Workloads, die im Namespace bereitgestellt werden, automatisch das Istio-Sidecar. Sie müssen Istio manuell in bereits vorhandenen Workloads aktivieren.

Für weitere Informationen zum Istio-Sidecar verweisen Sie auf die https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/[Dokumentation zur Istio-Sidecar-Injektion] und für weitere Informationen zur Architektur von Istio verweisen Sie auf die https://istio.io/latest/docs/ops/deployment/architecture/[Dokumentation zur Istio-Architektur].

[#_multiple_ingresses]
=== Mehrere Ingresses

Standardmäßig hat jeder von Rancher bereitgestellte Cluster einen NGINX-Ingress-Controller, der den Datenverkehr in den Cluster ermöglicht. Istio installiert standardmäßig ein Ingress-Gateway im `istio-system` Namespace.  Das Ergebnis ist, dass Ihr Cluster zwei Ingresses haben wird.

image::istio-ingress.svg[In einem Istio-aktivierten Cluster, you can have two ingresses: the default Nginx ingress, and the default Istio controller.]

Zusätzliche Istio Ingress-Gateways können über die {xref-istio-config}#_overlay_file[Overlay-Datei] aktiviert werden.

[#_egress_support]
=== Egress-Unterstützung

Standardmäßig ist das Egress-Gateway deaktiviert, kann jedoch bei der Installation oder beim Upgrade über die values.yaml oder über die {xref-istio-config}#_overlay_file[Overlay-Datei] aktiviert werden.

[#_additional_steps_for_installing_istio_on_an_rke2_cluster]
== Zusätzliche Schritte zur Installation von Istio auf einem {rke2-product-name} Cluster

Um Istio auf einem RKE2-Cluster zu installieren, folgen Sie den Schritten in {xref-istio-on-rke2}[diesem Abschnitt.]

[#_upgrading_istio_in_an_air_gapped_environment]
== Upgrade von Istio in einer Air-Gapped-Umgebung

Die Istio-Pod-Sicherheitsrichtlinie ist jetzt standardmäßig aktiviert. Ein neuer Wert, `installer.releaseMirror.enabled`, wurde zum rancher-istio-Chart hinzugefügt, um den Server zu aktivieren und zu deaktivieren, der Air-Gapped-Upgrades unterstützt. Beachten Sie, dass `installer.releaseMirror.enabled` standardmäßig auf `false` gesetzt ist. Sie können diesen Wert nach Bedarf bei der Installation oder beim Upgrade festlegen. Führen Sie die folgenden Schritte aus:

. Stellen Sie eine Air-Gapped-Rancher-Instanz und einen Air-Gapped-benutzerdefinierten Cluster in der Rancher-Benutzeroberfläche bereit.
. Installieren Sie Monitoring im Cluster: *Cluster Explorer \-> Apps & Marketplace \-> Charts \-> Monitoring*.
. Ziehen Sie alle erforderlichen Bilder für Istio in das private Repository, das Sie in der Air-Gapped-Umgebung verwenden werden.
. Installieren Sie Istio im Cluster: *Cluster Explorer \-> Apps & Marketplace \-> Charts \-> Istio*.

[NOTE]
====

Sie können https://www.jaegertracing.io/[Jaeger] und https://kiali.io/[Kiali] bei einer frischen Istio-Installation aktivieren. Um sicherzustellen, dass Jaeger und Kiali funktionieren, setzen Sie `installer.releaseMirror.enabled` auf `true` in `values.yaml` während der Installation.
====


. Führen Sie ein Upgrade der Istio-Installation durch.

[CAUTION]
====

Falls Sie es noch nicht getan haben, setzen Sie `installer.releaseMirror.enabled=true`, um Istio zu upgraden.
====

