= Rollenbasierte Zugriffssteuerung
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/rbac-for-istio.adoc 
:product-path: observability/istio/rbac.adoc

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ist seit Rancher v2.12.0 ausgelaufen; wenden Sie sich an die https://apps.rancher.io[SUSE Application Collection] Version von Istio fĂĽr verbesserte Sicherheit (in SUSE Rancher Prime-Abonnements enthalten).
Detaillierte Informationen finden Sie in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[dieser AnkĂĽndigung].
====

Dieser Abschnitt beschreibt die Berechtigungen, die erforderlich sind, um auf Istio-Funktionen zuzugreifen.

Das Rancher Istio-Chart installiert drei `ClusterRoles`.

[#_cluster_admin_access]
== Cluster-Admin-Zugriff

StandardmĂ¤Ăźig kĂ¶nnen nur diejenigen mit dem `cluster-admin` `ClusterRole`:

* Die Istio-App in einem Cluster installieren.
* Ressourcenzuweisungen fĂĽr Istio konfigurieren.

[#_admin_and_edit_access]
== Admin- und Bearbeitungszugriff.

StandardmĂ¤Ăźig kĂ¶nnen nur Admin- und Bearbeitungsrollen:

* Die automatische Injektion des Istio-Sidecars fĂĽr Namespaces aktivieren und deaktivieren.
* Das Istio-Sidecar zu Workloads hinzufĂĽgen.
* Die Verkehrsmetriken und das Verkehrsdiagramm fĂĽr das Cluster anzeigen.
* Die Ressourcen von Istio (wie das Gateway, Zielregeln oder virtuelle Dienste) konfigurieren.

[#_summary_of_default_permissions_for_kubernetes_default_roles]
== Zusammenfassung der Standardberechtigungen fĂĽr die Standardrollen von Kubernetes.

Istio erstellt drei `ClusterRoles` und fĂĽgt den folgenden Standard-K8s `ClusterRole` den Istio-CRD-Zugriff hinzu:

[cols=">,>,>"]
|===
| ClusterRole, die durch das Chart erstellt wurde. | Standard-K8s-ClusterRole | Rancher-Rolle.

| `istio-admin`
| admin
| Projekt-EigentĂĽmer.

| `istio-edit`
| Bearbeiten
| Projektmitglied.

| `istio-view`
| view
| Nur-Lesen
|===

Rancher wird weiterhin cluster-owner, cluster-member, project-owner, project-member usw. als Rollennamen verwenden, aber die Standardrollen nutzen, um den Zugriff zu bestimmen. FĂĽr jede Standard-K8s `ClusterRole` gibt es unterschiedliche Istio-CRD-Berechtigungen und K8s-Aktionen (Erstellen \(C), Abrufen (G), Auflisten (L), Ăśberwachen (W), Aktualisieren (U), Patch (P), LĂ¶schen (D), Alle (*)), die durchgefĂĽhrt werden kĂ¶nnen.

|===
| CRDs | Admin. | Bearbeiten | Anzeigen

| <ul><li>``config.istio.io``</li><ul><li>``adapters``</li><li>``attributemanifests``</li><li>``handlers``</li><li>``httpapispecbindings``</li><li>``httpapispecs``</li><li>``instances``</li><li>``quotaspecbindings``</li><li>``quotaspecs``</li><li>``rules``</li><li>``templates``</li></ul></ul>
| GLW
| GLW
| GLW

| <ul><li>``networking.istio.io``</li><ul><li>``destinationrules``</li><li>``envoyfilters``</li><li>``gateways``</li><li>``serviceentries``</li><li>``sidecars``</li><li>``virtualservices``</li><li>``workloadentries``</li></ul></ul>
| *
| *
| GLW

| <ul><li>``security.istio.io``</li><ul><li>``authorizationpolicies``</li><li>``peerauthentications``</li><li>``requestauthentications``</li></ul></ul>
| *
| *
| GLW
|===
