= Konfiguration des Speicherorts für Sicherungen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/backup-restore-configuration/storage-configuration.adoc 
:product-path: rancher-admin/back-up-restore-and-disaster-recovery/configuration/storage.adoc
ifeval::["{build-type}" != "community"]
:xref-existing-storage-setup: xref:cluster-admin/manage-clusters/persistent-storage/set-up-existing-storage.adoc
:xref-dynamically-provision-new-storage: xref:cluster-admin/manage-clusters/persistent-storage/dynamically-provision-new-storage.adoc
:xref-rancher-backup-config: xref:rancher-admin/back-up-restore-and-disaster-recovery/configuration/backup.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-existing-storage-setup: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/set-up-existing-storage.adoc
:xref-dynamically-provision-new-storage: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/dynamically-provision-new-storage.adoc
:xref-rancher-backup-config: xref:reference-guides/backup-restore-configuration/backup-configuration.adoc
endif::[]

Konfigurieren Sie einen Speicherort, an dem alle Sicherungen standardmäßig gespeichert werden. Sie haben die Möglichkeit, dies bei jeder Sicherung zu überschreiben, sind jedoch auf die Verwendung eines S3-kompatiblen Objektspeichers beschränkt.

Es kann nur ein Speicherort auf der Betreiber-Ebene konfiguriert werden.

[#_storage_location_configuration]
== Konfiguration des Speicherorts

[#_no_default_storage_location]
=== Kein Standard-Speicherort

Sie können wählen, keinen Speicherort auf der Betreiber-Ebene zu konfigurieren. Wenn Sie diese Option auswählen, müssen Sie einen S3-kompatiblen Objektspeicher als Speicherort für jede einzelne Sicherung konfigurieren.

[#_s3_compatible_object_store]
=== S3-kompatibler Objektspeicher

|===
| Parameter | Beschreibung

| Anmeldegeheimnis
| Wählen Sie die Anmeldeinformationen für S3 aus Ihren Geheimnissen in Rancher. {xref-rancher-backup-config}#_example_credentialsecret[Beispiel].

| Bucket-Name
| Geben Sie den Namen des https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html[S3-Buckets] ein, in dem die Sicherungen gespeichert werden. Standard: `rancherbackups`.

| Region
| Die https://aws.amazon.com/about-aws/global-infrastructure/regions_az/[AWS-Region], in der sich der S3-Bucket befindet.

| Ordner
| Der https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html[Ordner im S3-Bucket], in dem die Sicherungen gespeichert werden. Wenn dieses Feld leer gelassen wird, ist das Standardverhalten, die Sicherungsdateien im Stammordner des S3-Buckets zu speichern.

| Endpunkt
| Der https://docs.aws.amazon.com/general/latest/gr/s3.html[S3-Endpunkt]. Zum Beispiel `s3.us-west-2.amazonaws.com`.

| Endpunkt-CA
| Das CA-Zertifikat, das für den S3-Endpunkt verwendet wird. Standard: base64 kodiertes CA-Zertifikat

| insecureTLSSkipVerify
| Auf true setzen, wenn Sie TLS nicht verwenden.
|===

[#_existing_storageclass]
=== Vorhandene StorageClass

Die Installation des `rancher-backup` Charts durch Auswahl der StorageClass-Option erstellt einen Persistent Volume Claim (PVC), und Kubernetes wird im Gegenzug dynamisch einen Persistent Volume (PV) bereitstellen, in dem standardmäßig alle Sicherungen gespeichert werden.

Für Informationen zur Erstellung von Storage-Klassen siehe {xref-dynamically-provision-new-storage}[diesen Abschnitt.]

[NOTE]
.Wichtig:
====

Es wird dringend empfohlen, eine StorageClass mit einer Rückgewinnungsrichtlinie von "Behalten" zu verwenden. Andernfalls, wenn der durch das `rancher-backup` Chart erstellte PVC gelöscht wird (entweder während des App-Upgrades oder versehentlich), wird auch der PV gelöscht, was bedeutet, dass alle darin gespeicherten Sicherungen gelöscht werden.
Wenn keine solche StorageClass verfügbar ist, stellen Sie sicher, dass Sie die Rückgewinnungsrichtlinie des PV bearbeiten und auf "Behalten" setzen, bevor Sie Sicherungen darin speichern.
====


[#_existing_persistent_volume]
=== Vorhandener Persistent Volume

Wählen Sie einen vorhandenen Persistent Volume (PV) aus, der verwendet wird, um Ihre Sicherungen zu speichern. Für Informationen zur Erstellung von PersistentVolumes in Rancher siehe {xref-existing-storage-setup}#_2_add_a_persistentvolume_that_refers_to_the_persistent_storage[diesen Abschnitt.]

[NOTE]
.Wichtig:
====

Es wird dringend empfohlen, einen Persistent Volume mit einer Rückgewinnungsrichtlinie von "Behalten" zu verwenden. Andernfalls, wenn der durch das `rancher-backup` Chart erstellte PVC gelöscht wird (entweder während des App-Upgrades oder versehentlich), wird auch der PV gelöscht, was bedeutet, dass alle darin gespeicherten Sicherungen gelöscht werden.
====


[#_example_yaml_file_rancher_backup_helm_chart]
== Beispiel-YAML-Datei: Rancher Backup Helm Chart

Die dokumentierte `values.yaml` Datei, die zur Konfiguration des `backup-restore-operator` verwendet werden kann, wenn die Helm-Kommandozeilenschnittstelle verwendet wird, befindet sich im https://github.com/rancher/backup-restore-operator/blob/master/charts/rancher-backup/values.yaml[backup-restore-operator Repository.]

Für weitere Informationen zu `values.yaml` Dateien und zur Konfiguration von Helm Charts während der Installation siehe die https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing[Helm-Dokumentation.]
