= 高可用性{rke2-product-name} Kubernetesクラスターのインフラストラクチャの設定
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-30
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc 
:product-path: installation-and-upgrade/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-setup-ec2-nodes: xref:installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:installation-and-upgrade/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:installation-and-upgrade/infrastructure-setup/amazon-elb-load-balancer.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-setup-ec2-nodes: xref:how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:how-to-guides/new-user-guides/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:how-to-guides/new-user-guides/infrastructure-setup/amazon-elb-load-balancer.adoc
endif::[]


このチュートリアルは、Rancher管理サーバーの基盤となるインフラストラクチャをプロビジョニングするのに役立つことを目的としています。

Rancher専用のKubernetesクラスターに推奨されるインフラストラクチャは、RancherがRKE2 Kubernetesクラスター、RKE Kubernetesクラスター、または単一のDockerコンテナにインストールされるかどうかによって異なります。

[NOTE]
.重要:
====

これらのノードは同じリージョンに存在する必要があります。これらのサーバーを別々の可用性ゾーン（データセンター）に配置することができます。
====


高可用性のRKE2クラスターにRancher管理サーバーをインストールするには、以下のインフラストラクチャを設定することをお勧めします：

* *3つのLinuxノード*（通常は仮想マシン）を、選択したインフラストラクチャプロバイダー内に用意します。
* *ロードバランサー*は、ノードにトラフィックを振り分けます。
* *DNSレコード*は、URLをロードバランサーにマッピングします。これがRancherサーバーのURLとなり、ダウンストリームのKubernetesクラスターはこれにアクセスする必要があります。

[#_1_set_up_linux_nodes]
== 1.Linuxノードの設定

ノードが{xref-install-reqs}[OS、コンテナランタイム、ハードウェア、ネットワーク]の一般的なインストール要件を満たしていることを確認してください。

Linuxノードを設定する一例については、Amazon EC2のインスタンスとしてノードを設定するためのこの{xref-setup-ec2-nodes}[チュートリアル]を参照してください。

[#_2_set_up_the_load_balancer]
== 2.ロードバランサーの設定

すべてのノード上のRancherレプリカにトラフィックを誘導するために、ロードバランサーを設定する必要があります。これにより、単一のノードの障害がRancher管理サーバーへの通信を妨げることを防ぎます。

[WARNING]
====
*Ingress-NGINX EOL:*コミュニティ`ingress-nginx`コントローラーは2026年3月にサービス終了（EOL）し、RKE2 v1.36で廃止されます。SUSE Rancher Primeが提供するRKE2バージョンは、RKE2 v1.32、v1.33、v1.34、v1.35およびv1.36のライフサイクル全体にわたって`ingress-nginx`サポートとCVE修正（8+）を受け続けます。TraefikはSUSE Rancher RKE2環境の推奨される移行パスであり、できるだけ早く移行することをお勧めします。詳細については、 https://support.scc.suse.com/s/kb/Migrating-from-Ingress-NGINX-to-Traefik-in-a-Rancher-provisioned-RKE2-Cluster?language=en_US[Rancherが提供するRKE2クラスターでのIngress NGINXからTraefikへの移行]を参照してください。
====

Kubernetesが後のステップで設定されると、RKE2ツールがNginx Ingressコントローラーをデプロイします。このコントローラーは、ワーカーノードのポート80および443でリスンし、特定のホスト名宛てのトラフィックに応答します。

Rancherがインストールされると（これも後のステップで）、RancherシステムはIngressリソースを作成します。そのIngressは、Nginx IngressコントローラーにRancherのホスト名宛てのトラフィックをリスンするよう指示します。Nginx Ingressコントローラーは、Rancherのホスト名宛てのトラフィックを受信すると、そのトラフィックをクラスター内の実行中のRancherポッドに転送します。

実装において、レイヤー4またはレイヤー7のロードバランサーを使用するかどうかを検討してください：

* *レイヤー4のロードバランサー*は、ノードにTCPトラフィックを転送するという点で、2つの選択肢の中でよりシンプルです。ロードバランサーをレイヤー4バランサーとして構成し、TCP/80およびTCP/443のポートにトラフィックをRancher管理クラスターのノードに転送することをお勧めします。クラスター内のIngressコントローラーは、HTTPトラフィックをHTTPSにリダイレクトし、ポートTCP/443でSSL/TLSを終了します。Ingressコントローラーは、Rancherデプロイメント内のIngressポッドにTCP/80のポートへのトラフィックを転送します。
* *レイヤー7のロードバランサー*は少し複雑ですが、必要な機能を提供することができます。例えば、レイヤー7のロードバランサーは、RancherがTLS終了を行うのではなく、ロードバランサーでTLS終了を処理することができます。これは、インフラストラクチャ内でTLS終了を集中管理したい場合に有益です。レイヤー7のロードバランシングは、レイヤー4のロードバランサーが関与できないクッキーなどのHTTP属性に基づいて、ロードバランサーが意思決定を行う能力も提供します。レイヤー7のロードバランサーでSSL/TLSトラフィックを終了することを決定した場合、後のステップでRancherをインストールする際に`--set tls=external`オプションを使用する必要があります。詳細については、{xref-helm-chart-options}#_external_tls_termination[Rancher Helmチャートオプション]を参照してください。

NGINXロードバランサーの設定方法を示す例については、{xref-nginx-load-balancer}[このページ]を参照してください。

Amazon ELB ネットワークロードバランサーの設定に関するハウツーについては、{xref-amazon-elb}[こちらのページをご覧ください。]

[CAUTION]
====

このロードバランサー（すなわち、`local` クラスターの Ingress）を、インストール後に Rancher 以外のアプリケーションのロードバランシングに使用しないでください。このIngressを他のアプリケーションと共有すると、他のアプリのIngress設定のリロード後にRancherに対してウェブソケットエラーが発生する可能性があります。`local`クラスターをRancher専用にし、他のアプリケーションには使用しないことをお勧めします。
====


[#_3_set_up_the_dns_record]
== 3.DNSレコードを設定する

ロードバランサーを設定したら、このロードバランサーにトラフィックを送信するためのDNSレコードを作成する必要があります。

環境によっては、これはロードバランサーIPを指すAレコードであるか、ロードバランサーのホスト名を指すCNAMEである場合があります。いずれの場合でも、このレコードがRancherが応答することを意図しているホスト名であることを確認してください。

Rancherをインストールする際の後のステップでこのホスト名を指定する必要があり、後で変更することはできません。あなたの決定が最終的なものであることを確認してください。

ドメイントラフィックを Amazon ELB ロードバランサーにルーティングするための DNS レコードの設定に関するハウツーガイドについては、 https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer[公式 AWS ドキュメントをご覧ください。]
