= Authentification, Droits d'accès et Paramètres Globaux
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/index.adoc 
:product-path: rancher-admin/rancher-admin.adoc
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-infra-providers: xref:cluster-deployment/fournisseurs-infra/fournisseurs-infra.adoc
:xref-global-permissions: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-manage-rbac: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/gerer-le-controle-d-acces-en-fonction-du-role-rbac.adoc
:xref-provisioning-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc
:xref-backups-without-uprading-rancher: xref:cluster-admin/backups-and-restore/backups-without-uprading-rancher.adoc
:xref-user-retention: xref:rancher-admin/users/authn-and-authz/enable-user-retention.adoc
:xref-custom-branding: xref:rancher-admin/global-configuration/custom-branding.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-infra-providers: xref:guides-procédures/guides-nouveaux-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/index.adoc
:xref-global-permissions: xref:procédure/guide-utilisateur-nouveau/autorisations-d-authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/autorisations-globales.adoc 
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
:xref-hosted-k8s-clusters: xref:guides-pratiques/nouveaux-guides-utilisateurs/clusters-kubernetes-dans-rancher-configuration/configurer-des-clusters-à-partir-de-fournisseurs-kubernetes-hébergés/index.adoc
:xref-manage-rbac: xref:how-to-guides/nouveaux-utilisateurs/autorisations-d'authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/index.adoc
:xref-provisioning-drivers: xref:guides-pratiques/guide-nouvel-utilisateur/authentification-autorisations-et-configuration-globale/a-propos-des-pilotes-de-provisionnement/index.adoc
:xref-backups-without-uprading-rancher: xref:getting-started/installation-and-upgrade/upgrade-kubernetes-without-upgrading-rancher.adoc
:xref-user-retention: xref:how-to-guides/advanced-user-guides/enable-user-retention.adoc
:xref-custom-branding: xref:how-to-guides/nouveaux-utilisateurs/procédure-authentification-droits-d'accès-et-configuration-globale/personnalisation-de-la-marque.adoc
endif::[]

Après l'installation, le {xref-global-permissions}[administrateur système] doit configurer Rancher pour configurer l'authentification, l'autorisation, la sécurité, les paramètres par défaut, les politiques de sécurité, les pilotes et les entrées DNS globales.

[#_first_log_in]
== Première connexion

Après vous être connecté à Rancher pour la première fois, Rancher vous demandera un *URL du serveur Rancher*. Vous devez définir l'URL sur le point d'entrée principal du serveur Rancher. Lorsqu'un équilibreur de charge se trouve devant un cluster de serveurs Rancher, l'URL doit résoudre vers l'équilibreur de charge. Le système essaiera automatiquement d'inférer l'URL du serveur Rancher à partir de l'adresse IP ou du nom d'hôte de l'hôte exécutant le serveur Rancher. Ceci est correct uniquement si vous exécutez une installation de serveur Rancher à nœud unique. Dans la plupart des cas, vous devez donc définir vous-même l'URL du serveur Rancher sur la valeur correcte.

[WARNING]
====

Après avoir défini l'URL du serveur Rancher, nous ne prenons pas en charge sa mise à jour. Définissez l'URL avec une extrême prudence.
====


[#_authentication]
== Authentification

L'une des fonctionnalités clés que Rancher ajoute à Kubernetes est l'authentification utilisateur centralisée. Cette fonctionnalité permet de configurer des utilisateurs locaux et/ou de se connecter à un fournisseur d'authentification externe. En vous connectant à un fournisseur d'authentification externe, vous pouvez tirer parti des utilisateurs et des groupes de ce fournisseur.

Pour plus d'informations sur le fonctionnement de l'authentification et sur la façon de configurer chaque fournisseur, voir {xref-authn-authz}[Authentification].

[#_authorization]
== autorisation

Au sein de Rancher, chaque personne s'authentifie en tant qu'_utilisateur_, ce qui est une connexion qui vous accorde l'accès à Rancher. Une fois que l'utilisateur se connecte à Rancher, ses _autorisations_, ou ses droits d'accès au sein du système, sont déterminés par le rôle de l'utilisateur. Rancher fournit des rôles intégrés pour vous permettre de configurer facilement les autorisations d'un utilisateur sur les ressources, mais Rancher offre également la possibilité de personnaliser les rôles pour chaque ressource Kubernetes.

Pour plus d'informations sur le fonctionnement de l'autorisation et sur la façon de personnaliser les rôles, voir {xref-manage-rbac}[Contrôle d'accès en fonction du rôle (RBAC)].

[#_user_retention]
== Rétention des utilisateurs

Dans Rancher v2.8.5 et versions ultérieures, vous pouvez activer la rétention des utilisateurs. Cette fonctionnalité supprime automatiquement les utilisateurs inactifs après une période de temps configurable.

La fonctionnalité de rétention des utilisateurs est désactivée par défaut.

Pour plus d'informations, voir {xref-user-retention}[Activation de la rétention des utilisateurs].

[#_provisioning_drivers]
== Pilotes de provisionnement

Les pilotes dans Rancher vous permettent de gérer quels fournisseurs peuvent être utilisés pour provisionner {xref-hosted-k8s-clusters}[clusters Kubernetes hébergés] ou {xref-infra-providers}[nœuds dans un fournisseur d'infrastructure] afin de permettre à Rancher de déployer et de gérer Kubernetes.

Pour plus d'informations, voir {xref-provisioning-drivers}[Pilotes de provisionnement].

[#_adding_kubernetes_versions_into_rancher]
== Ajout de versions Kubernetes dans Rancher

Avec cette fonctionnalité, vous pouvez passer à la dernière version de Kubernetes dès qu'elle est publiée, sans mettre à niveau Rancher. Cette fonctionnalité vous permet de mettre à niveau facilement les versions de correctifs Kubernetes (c'est-à-dire `v1.15.X`), mais n'est pas destinée à mettre à niveau les versions mineures de Kubernetes (c'est-à-dire `v1.X.0`) car Kubernetes a tendance à cesser la prise en charge ou à ajouter des API entre les versions mineures.

Les informations que Rancher utilise pour provisionner {xref-launch-k8s-with-rancher}[clusters RKE] se trouvent désormais dans les métadonnées Kubernetes de Rancher. Pour des détails sur la configuration des métadonnées et sur la façon de changer la version de Kubernetes utilisée pour le provisionnement des clusters RKE, voir {xref-backups-without-uprading-rancher}[Métadonnées Kubernetes de Rancher.]

Les métadonnées Kubernetes de Rancher contiennent des informations sur la version de Kubernetes que Rancher utilise pour provisionner {xref-launch-k8s-with-rancher}[clusters RKE].

Pour plus d'informations sur le fonctionnement des métadonnées et sur la façon de configurer la configuration des métadonnées, voir {xref-backups-without-uprading-rancher}[Métadonnées Kubernetes de Rancher].

[#_global_settings]
== Paramètres globaux

Les options qui contrôlent certains paramètres globaux de Rancher sont disponibles dans la barre de navigation supérieure.

Cliquez sur *☰* dans le coin supérieur gauche, puis sélectionnez *Paramètres globaux*, pour afficher et configurer les paramètres suivants{nbsp}:

* *Paramètres*: Divers paramètres par défaut de Rancher, tels que la longueur minimale du mot de passe d'un utilisateur (`password-min-length`). Vous devez être prudent lorsque vous modifiez ces paramètres, car des valeurs invalides peuvent endommager votre installation de Rancher.
* *Drapeaux de fonctionnalités*: Fonctionnalités de Rancher qui peuvent être activées ou désactivées. Certains de ces drapeaux concernent les <<_enabling_experimental_features,fonctionnalités expérimentales>>.
* *Bannières*: Éléments que vous pouvez ajouter à des emplacements fixes sur le portail. Par exemple, vous pouvez utiliser ces options pour {xref-custom-branding}#_fixed_banners[définir une bannière personnalisée] pour les utilisateurs lorsqu'ils se connectent à Rancher.
* *Branding*: Éléments de design de l'interface utilisateur de Rancher que vous pouvez {xref-custom-branding}[personnaliser]. Vous pouvez ajouter un logo ou un favicon personnalisé, et modifier les couleurs de l'interface utilisateur.
* *Performance*: Paramètres de performance pour l'interface utilisateur de Rancher, tels que le chargement progressif des ressources.
* *Liens Accueil*: Liens affichés sur la page *Accueil* de l'interface utilisateur de Rancher. Vous pouvez modifier la visibilité des liens par défaut ou ajouter vos propres liens.

[#_enabling_experimental_features]
=== Activation des Fonctionnalités Expérimentales

Rancher inclut certaines fonctionnalités qui sont expérimentales et/ou désactivées par défaut. Les drapeaux de fonctionnalités vous permettent d'activer ces fonctionnalités. Pour plus d'informations, consultez la section sur {xref-experimental-features}[les drapeaux de fonctionnalités.]

[#_global_configuration]
=== configuration globale

Les options de *Configuration Globale* ne sont pas visibles à moins d'activer le *legacy* {xref-experimental-features}[drapeau de fonctionnalité]. Le *legacy* flag est désactivé par défaut sur les nouvelles installations de Rancher v2.6 et ultérieures. Si vous mettez à niveau à partir d'une version antérieure de Rancher, ou activez le *legacy* flag de fonctionnalité sur Rancher v2.6 et ultérieures, *Configuration Globale* est disponible dans le menu de navigation supérieur :

. Cliquez sur *☰* dans le coin supérieur gauche.
. Sélectionnez *Configuration Globale* à partir des *Applications legacy*.

Les fonctionnalités suivantes sont disponibles sous *Configuration Globale*{nbsp}:

* *Catalogues*
* *Entrées DNS Globales*
* *Fournisseurs DNS Globaux*

Étant donné qu'il s'agit de fonctionnalités héritées, veuillez consulter la documentation de Rancher v2.0--v2.4 sur xref:[catalogues], xref:/versioned_docs/version-2.0-2.4/how-to-guides/new-user-guides/helm-charts-in-rancher/globaldns.adoc#_adding_a_global_dns_entry[entrées DNS globales], et xref:/versioned_docs/version-2.0-2.4/how-to-guides/new-user-guides/helm-charts-in-rancher/globaldns.adoc#_editing_a_global_dns_provider[fournisseurs DNS globaux] pour plus de détails.
