= Configuration du modèle de nœud EC2
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: guides-de-référence/configuration-cluster/configuration-cluster-en-aval/configuration-modèle-nœud/amazon-ec2.adoc 
:product-path: cluster-deployment/infra-providers/aws/node-template-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
:xref-infra-aws: xref:déploiement-cluster/fournisseurs-infra/aws/aws.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-set-up-cloud-providers: xref:guides-procédures/guides-nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-configuration/configuration-cloud-providers/index.adoc
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
:xref-infra-aws: xref:guides-procédures/guides-nouveaux-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/créer-un-cluster-amazon-ec2.adoc
endif::[]

Pour plus de détails sur EC2 et les nœuds, consultez la documentation officielle pour la https://aws.amazon.com/ec2[console de gestion EC2].

[#_region]
== Région

Dans le champ *Région*, sélectionnez la même région que celle que vous avez utilisée lors de la création de vos identifiants cloud.

[#_cloud_credentials]
== Identifiants Cloud

Vos informations d'accès à votre compte AWS, stockées dans un {xref-cloud-credentials}[identifiant cloud].

Voir https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey[Documentation Amazon{nbsp}: Création de clés d'accès] comment créer une clé d'accès et une clé secrète.

Voir https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html#access_policies_create-start[Documentation Amazon{nbsp}: Création de stratégies IAM (Console)] comment créer une stratégie IAM.

Voir https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_change-permissions.html#users_change_permissions-add-console[Documentation Amazon{nbsp}: Ajout de permissions à un utilisateur (Console)] pour savoir comment attacher un IAM

Voir nos trois exemples de stratégies JSON{nbsp}:

* {xref-infra-aws}#_exemple_stratégie_iam[Exemple de stratégie IAM]
* {xref-infra-aws}#_exemple_stratégie_iam_avec_passrole[Exemple de stratégie IAM avec PassRole] (nécessaire si vous souhaitez utiliser {xref-set-up-cloud-providers}[Fournisseur de Cloud Kubernetes] ou passer un profil IAM à une instance)
* {xref-infra-aws}#_exemple_stratégie_iam_autoriser_volumes_ebs_chiffrés[Exemple de stratégie IAM pour autoriser les volumes EBS chiffrés] à un utilisateur.

[#_authenticate_configure_nodes]
== Authentifier et configurer les nœuds

Choisissez une zone de disponibilité et des paramètres réseau pour votre cluster.

[#_security_group]
== Groupe de sécurité

Choisissez le groupe de sécurité par défaut ou configurez un groupe de sécurité.

Veuillez vous référer à {xref-port-reqs}#_rancher_aws_ec2_security_group[groupe de sécurité Amazon EC2 lors de l'utilisation du pilote Node] pour voir quelles règles sont créées dans le `rancher-nodes` groupe de sécurité.

Si vous fournissez votre propre groupe de sécurité pour une instance EC2, veuillez noter que Rancher ne le modifiera pas. En tant que tel, vous serez responsable de vous assurer que votre groupe de sécurité est configuré pour autoriser les {xref-port-reqs}#_ports_for_rancher_server_nodes_on_rke2[ports nécessaires pour que Rancher provisionne l'instance]. Pour plus d'informations sur le contrôle du trafic entrant et sortant vers les instances EC2 avec des groupes de sécurité, référez-vous à https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#WorkingWithSecurityGroups[ici].

[#_instance_options]
== Options d'instance

Configurez les instances qui seront créées. Assurez-vous de configurer le bon *utilisateur SSH* pour l'AMI configurée. Il est possible qu'une région sélectionnée ne prenne pas en charge le type d'instance par défaut. Dans ce scénario, vous devez sélectionner un type d'instance qui existe, sinon une erreur se produira indiquant que la configuration demandée n'est pas prise en charge.

Si vous devez passer un *nom de profil d'instance IAM* (pas ARN), par exemple, lorsque vous souhaitez utiliser un {xref-set-up-cloud-providers}[fournisseur de cloud Kubernetes], vous aurez besoin d'une autorisation supplémentaire dans votre stratégie. Voir {xref-infra-aws}#_example_iam_policy_with_passrole[Exemple de stratégie IAM avec PassRole] pour un exemple de stratégie.

[#_engine_options]
== Options de moteur

Dans la section *Options de moteur* du modèle de nœud, vous pouvez configurer le daemon de conteneur. Vous souhaiterez peut-être spécifier la version du conteneur ou un miroir de registre d'images de conteneur.
