= Création d’un cluster Azure
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: guides-procédures/guides-nouveaux-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/créer-un-cluster-azure.adoc 
:product-path: cluster-deployment/infra-providers/azure/azure.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:cluster-deployment/fournisseurs-infra/fournisseurs-infra.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-azure-machine-configuration: xref:cluster-deployment/infra-providers/azure/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:guides-de-référence/configuration-de-cluster/configuration-du-serveur-rancher/configuration-du-cluster-rke2.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:guides-procédures/guides-nouveaux-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/index.adoc
:xref-k3s-config: xref:guides-de-référence/configuration-de-cluster/configuration-du-serveur-rancher/configuration-du-cluster-k3s.adoc
:xref-azure-machine-configuration: xref:guides-de-référence/configuration-cluster/configuration-cluster-en-aval/configuration-machine/azure.adoc
endif::[]

Dans cette section, vous apprendrez à déployer un cluster Kubernetes {url-rke2-landing-page}[RKE2] ou {url-k3s-landing-page}[K3s] dans Azure via Rancher.

Tout d'abord, vous configurez vos identifiants cloud Azure dans Rancher.

Ensuite, vous créez un cluster Azure dans Rancher, et lors de la configuration du nouveau cluster, vous définissez des pools de machines pour celui-ci. Chaque pool de machines a un rôle Kubernetes d'etcd, de controlplane ou de worker. Rancher installe Kubernetes sur les nouveaux nœuds, et il configure chaque nœud avec le rôle Kubernetes défini par le pool de machines.

[CAUTION]
====

Lorsque le cluster Rancher RKE2/K3s fonctionne dans Azure et dispose d'un équilibreur de charge Azure en façade, le flux sortant échoue. La solution de contournement pour ce problème est la suivante{nbsp}:

* Désactivez la terminaison SSL/TLS sur l'équilibreur de charge interne
* Utilisez l'équilibreur de charge L7

Pour plus d'informations, consultez la documentation sur https://docs.microsoft.com/en-us/azure/load-balancer/components#_limitations[les limitations du répartiteur de charge Azure].
====


Pour plus d'informations sur la configuration du cluster Kubernetes que Rancher installe sur les nœuds Azure, consultez les références de configuration de cluster {xref-rke2-config}[RKE2] et {xref-k3s-config}[K3s].


Pour plus d'informations sur la configuration des machines Azure, consultez la {xref-azure-machine-configuration}[référence de configuration des machines Azure].

* <<_preparation_in_azure,Préparation dans Azure>>
* <<_creating_an_azure_cluster,Création d'un cluster Azure>>

[#_preparation_in_azure]
== Préparation dans Azure

Avant qu'un cluster puisse être déployé, nous devons configurer notre abonnement Azure pour permettre la manipulation de ses ressources par un tiers, tel que Rancher.

Pour ce faire, nous allons d'abord créer un nouveau *principal de service (SP)* dans Azure *Active Directory (AD)*, qui, dans Azure, est un utilisateur d'application ayant la permission de gérer les ressources Azure.

Voici un modèle de `az cli` script que vous devez exécuter pour créer un principal de service, où vous devez entrer le nom de votre SP, le rôle et la portée{nbsp}:

----
az ad sp create-for-rbac \
  --name="<Rancher ServicePrincipal name>" \
  --role="Contributor" \
  --scopes="/subscriptions/<subscription Id>"
----

La création de ce principal de service renvoie l'**ID d'application**, également appelé **ID client**, et le **secret client**. Ces informations sont utilisées lorsque vous créez vos identifiants cloud.

[#_creating_an_azure_cluster]
== Création d’un cluster Azure

[#_create_your_cloud_credentials]
=== Créez vos identifiants cloud

Si vous avez déjà un ensemble d'identifiants cloud à utiliser, passez cette section.

. Cliquez sur *☰ > Gestion des clusters*.
. Cliquez sur *Identifiants Cloud*.
. Cliquez sur *Create*.
. Click *Azure*.
. Entrez vos identifiants Azure.
. Cliquez sur *Create*.

*Résultat :* Vous avez créé les identifiants cloud qui sont utilisés pour provisionner des nœuds dans votre cluster.

[#_create_your_cluster]
=== Créez votre cluster

Utilisez Rancher pour créer un cluster Kubernetes dans Azure.

. Cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, cliquez sur *Créer*.
. Basculez l'interrupteur sur *RKE2/K3s*.
. Click *Azure*.
. Sélectionnez un *Identifiant cloud*, s'il en existe plusieurs. Sinon, il est pré-sélectionné.
. Entrez un *Nom de cluster*.
. Créez un pool de machines pour chaque rôle Kubernetes. Référez-vous aux {xref-infra-providers}#_node_roles[meilleures pratiques] pour des recommandations sur les attributions de rôles et les quantités.
 .. Pour chaque pool de machines, définissez la configuration de la machine. Référez-vous à la {xref-azure-machine-configuration}[référence de configuration des machines Azure] pour des informations sur les options de configuration.
. Utilisez la *Configuration du Cluster* pour choisir la version de Kubernetes à installer, quel fournisseur de réseau utiliser et si vous souhaitez activer l'isolement réseau des projets.  Pour obtenir de l'aide sur la configuration du cluster, référez-vous aux {xref-rke2-config}[références de configuration du RKE2] et {xref-k3s-config}[K3s].
. Utilisez les *Rôles de membre* pour configurer l'autorisation des utilisateurs pour le cluster. Cliquez sur *Ajouter un membre* pour ajouter des utilisateurs pouvant accéder au cluster. Utilisez le menu déroulant *Rôle* pour définir les permissions pour chaque utilisateur.
. Cliquez sur *Create*.

*Résultat :*

Votre cluster est créé et a un état de *Provisionnement*. Rancher est en train de mettre en place votre cluster.

Vous pouvez accéder à votre cluster après que son état soit mis à jour à *Actif*.

Les clusters *Actifs* sont assignés à deux Projets{nbsp}:

* `Default`, contenant l'espace de noms `default`
* `System`, contenant les espaces de noms `cattle-system`, `traefik`, `kube-public` et `kube-system`

[#_optional_next_steps]
=== Étapes suivantes optionnelles

Après avoir créé votre cluster, vous pouvez y accéder via l'interface utilisateur de Rancher. En tant que meilleure pratique, nous recommandons de mettre en place ces méthodes alternatives pour accéder à votre cluster{nbsp}:

* *Accédez à votre cluster avec la CLI kubectl :* Suivez {xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[ces étapes] pour accéder aux clusters avec kubectl sur votre station de travail. Dans ce cas, vous serez authentifié via le proxy d'authentification du serveur Rancher, puis Rancher vous connectera au cluster en aval. Cette méthode vous permet de gérer le cluster sans l'interface utilisateur de Rancher.
* *Accédez à votre cluster avec la CLI kubectl, en utilisant le point de terminaison de cluster autorisé :* Suivez {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[ces étapes] pour accéder directement à votre cluster avec kubectl, sans vous authentifier via Rancher. Nous recommandons de mettre en place cette méthode alternative pour accéder à votre cluster afin que, dans le cas où vous ne pouvez pas vous connecter à Rancher, vous puissiez toujours accéder au cluster.
