= {rancher-product-name} Estrategia de ampliación
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-server/rancher-deployment-strategy.adoc 
:product-path: installation-and-upgrade/best-practices/deployment-strategy.adoc

Hay dos estrategias de ampliación recomendadas para una instancia de Rancher que gestiona clústeres de Kubernetes descendentes. Cada una tiene sus propios pros y contras. Lee más sobre cuál se adaptaría mejor a tu caso de uso.

[#_hub_spoke_strategy]
== Estrategia de Hub y Spoke

'''

En este escenario de ampliación, hay una única instancia de Rancher gestionando clústeres de Kubernetes en todo el mundo. La instancia de Rancher se ejecutaría en un clúster de Kubernetes de alta disponibilidad, y habría un impacto debido a las latencias.

[#_pros]
=== Pros

* Interfaz de plano de control único para ver todas las regiones y entornos.
* Kubernetes no requiere de Rancher para operar y puede tolerar la pérdida de conectividad con la instancia de Rancher.

[#_cons]
=== Contras

* Sujeto a latencias de red.
* Si Rancher falla, la provisión global de nuevos servicios no está disponible hasta que se restaure. Sin embargo, cada clúster de Kubernetes puede seguir siendo gestionado individualmente.

[#_regional_strategy]
== Estrategia Regional

'''

En el modelo de ampliación regional, se despliega una instancia de Rancher en estrecha proximidad a los clústeres de Kubernetes descendentes.

[#_pros_1]
=== Pros

* La funcionalidad de Rancher en las regiones permanece operativa si una instancia de Rancher en otra región falla.
* La latencia de red entre Rancher y los clústeres descendentes se reduce considerablemente, mejorando el rendimiento de la funcionalidad en Rancher.
* Las actualizaciones de versión de Rancher se pueden realizar de forma independiente por región.

[#_cons_1]
=== Contras

* Sobrecarga de gestionar múltiples instalaciones de Rancher.
* La visibilidad en los clústeres de Kubernetes en diferentes regiones requiere múltiples interfaces o paneles de control.
* Desplegar apps de múltiples clústeres en Rancher requiere repetir el proceso para cada servidor de Rancher.
