= Acerca de las instalaciones de alta disponibilidad
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-cluster-setup/high-availability-installs.adoc 
:product-path: installation-and-upgrade/best-practices/high-availability-installs.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-architecture: xref:about-rancher/architecture/architecture.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
endif::[]

Recomendamos usar Helm, un gestor de paquetes de Kubernetes, para instalar Rancher en un cluster de Kubernetes dedicado. Esto se llama una instalación de Kubernetes de alta disponibilidad porque se logra una mayor disponibilidad ejecutando Rancher en múltiples nodos.

En una instalación estándar, Kubernetes se instala primero en tres nodos que están alojados en un proveedor de infraestructura como Amazon EC2 o Google Compute Engine.

Luego se utiliza Helm para instalar Rancher sobre el cluster de Kubernetes. Helm utiliza el gráfico de Helm de Rancher para instalar una réplica de Rancher en cada uno de los tres nodos en el cluster de Kubernetes. Recomendamos usar un balanceador de carga para dirigir el tráfico a cada réplica de Rancher en el cluster, con el fin de aumentar la disponibilidad de Rancher.

Los datos del servidor de Rancher se almacenan en etcd. Esta base de datos etcd también se ejecuta en los tres nodos, y requiere un número impar de nodos para que siempre pueda elegir un líder con la mayoría del cluster de etcd. Si la base de datos etcd no puede elegir un líder, etcd puede fallar, requiriendo que el cluster sea restaurado desde una copia de seguridad.

Para información sobre cómo funciona Rancher, independientemente del método de instalación, consulta la {xref-rancher-architecture}[sección de arquitectura.]

[#_recommended_architecture]
== Arquitectura Recomendada

* El DNS para Rancher debe resolverse a un balanceador de carga de capa 4
* El Balanceador de Carga debe redirigir el puerto TCP/80 y TCP/443 a los 3 nodos en el cluster de Kubernetes.
* El controlador de Ingress redirigirá HTTP a HTTPS y terminará SSL/TLS en el puerto TCP/443.
* El controlador de Ingress redirigirá el tráfico al puerto TCP/80 en el pod de la ampliación de Rancher.

.Instalación de Kubernetes Rancher con balanceador de carga de capa 4, representando la terminación de SSL en los controladores de Ingress.
image::ha/rancher2ha.svg[Instalación de Rancher en Kubernetes de alta disponibilidad]
