= Criando um Cluster Nutanix AOS
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: procedimentos/novos-usuários/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/nutanix/index.adoc 
:product-path: cluster-deployment/infra-providers/nutanix/nutanix.adoc
:description: Use o Rancher para criar um cluster Nutanix AOS (AHV). Ele pode consistir em grupos de VMs com propriedades distintas que permitem um controle detalhado sobre o dimensionamento dos nós.
ifeval::["{build-type}" != "community"]
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:xref-nutanix-aos-provisioning: xref:cluster-deployment/infra-providers/nutanix/provision-kubernetes-clusters-in-aos.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s-landing-page: https://docs.k3s.io/
:url-rke2-landing-page: https://docs.rke2.io/
:xref-nutanix-aos-provisioning: xref:procedimentos/novos-usuários/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/nutanix/provisionar-clusters-kubernetes-no-aos.adoc
endif::[]

https://www.nutanix.com/products/acropolis[Nutanix Acropolis Operating System] (Nutanix AOS) é um sistema operacional para a plataforma de infraestrutura hiperconvergente Nutanix. O AOS vem com um hipervisor incorporado chamado https://www.nutanix.com/products/ahv[Acropolis Hypervisor], ou AHV. Ao usar o Rancher com o Nutanix AOS (AHV), você pode trazer operações de nuvem no local.

O Rancher pode provisionar nós no AOS (AHV) e instalar o Kubernetes neles. Ao criar um cluster Kubernetes no AOS, o Rancher primeiro provisiona o número especificado de máquinas virtuais comunicando-se com a API do Prism Central. Em seguida, ele instala o Kubernetes sobre as VMs.

Um cluster Nutanix pode consistir em vários grupos de VMs com propriedades distintas, como a quantidade de memória ou o número de vCPUs. Esse agrupamento permite um controle detalhado sobre o dimensionamento dos nós para cada função do Kubernetes.

[#_creating_a_nutanix_cluster]
== Criando um Cluster Nutanix

Consulte o {xref-nutanix-aos-provisioning}[Provisionamento de Clusters Kubernetes no Nutanix AOS] para aprender como usar o Rancher para instalar um cluster Kubernetes {url-rke2-landing-page}[RKE2]/{url-k3s-landing-page}[K3s] no Nutanix AOS.
