= 在 {rancher-product-name}Amazon EKS 上安装
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-09
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-qs-aws-marketplace: xref:installation-and-upgrade/quick-start/deploy-rancher/aws-marketplace.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-qs-aws-marketplace: xref:getting-started/quick-start-guides/deploy-rancher-manager/aws-marketplace.adoc
endif::[]

本页面介绍如何在 Amazon EKS 集群上安装 Rancher。 您也可以通过 {xref-qs-aws-marketplace}[AWS Marketplace 安装 Rancher]。

如果您已经有一个 EKS Kubernetes 集群，请跳到关于 <<_5_install_an_ingress,安装 Ingress 的步骤。>>然后按照 {xref-install-rancher}#_install_the_rancher_helm_chart[本页面]上的说明安装 Rancher Helm 图表。

[#_creating_an_eks_cluster_for_the_rancher_server]
== 为 Rancher 服务器创建 EKS 集群

在本节中，您将使用命令行工具安装带有 Ingress 的 EKS 集群。如果您想在 EKS 上试用 Rancher 时使用更少的资源，本指南可能会很有用。

[NOTE]
.先决条件：
====

* 您应该已经拥有一个 AWS 账户。
* 建议使用 IAM 用户而不是 root AWS 账户。您需要 IAM 用户的访问密钥和秘密密钥来配置 AWS 命令行界面。
* IAM 用户需要官方 https://eksctl.io/usage/minimum-iam-policies/[eksctl 文档]中描述的最小 IAM 策略。
====


[#_1_prepare_your_workstation]
=== 1.准备您的工作站

在您的工作站上安装以下命令行工具：

* *AWS CLI v2:*如需帮助，请参考这些 https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html[安装步骤。]
* *eksctl:*如需帮助，请参考这些 https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html[安装步骤。]
* *kubectl:*如需帮助，请参考这些 https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html[安装步骤。]
* *helm:*如需帮助，请参考这些 https://helm.sh/docs/intro/install/[安装步骤。]

[#_2_configure_the_aws_cli]
=== 2.配置 AWS CLI

要配置 AWS CLI，请运行以下命令：

----
aws configure
----

然后输入以下值：

|===
| 值 | 说明

| AWS 访问密钥 ID
| 具有 EKS 权限的 IAM 用户的访问密钥凭证。

| AWS 秘密访问密钥
| 具有 EKS 权限的 IAM 用户的秘密密钥凭证。

| 默认区域名称
| 集群节点所在的 https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html#Concepts.RegionsAndAvailabilityZones.Regions[AWS 区域]。

| 默认输出格式
| 输入 `json`。
|===

[#_3_create_the_eks_cluster]
=== 3.创建 EKS 集群

要创建 EKS 集群，请运行以下命令。使用适用于您用例的 AWS 区域。选择 Kubernetes 版本时，请务必先查阅 https://rancher.com/support-matrix/[支持矩阵]，以找到已为您的 Rancher 版本验证的最高 Kubernetes 版本。

----
eksctl create cluster \
  --name rancher-server \
  --version <VERSION> \
  --region us-west-2 \
  --nodegroup-name ranchernodes \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
----

集群通过 CloudFormation 部署可能需要一些时间。

[#_4_test_the_cluster]
=== 4.测试集群

要测试集群，请运行：

----
eksctl get cluster
----

结果应如下所示：

----
eksctl get cluster
2021-03-18 15:09:35 [ℹ]  eksctl version 0.40.0
2021-03-18 15:09:35 [ℹ]  using region us-west-2
NAME        REGION        EKSCTL CREATED
rancher-server-cluster        us-west-2    True
----

[#_5_install_an_ingress]
=== 5.安装 Ingress

集群需要一个 Ingress，以便从集群外部访问 Rancher。安装 Ingress 需要分配一个公共 IP 地址。确保您有足够的配额，否则将无法分配 IP 地址。每个订阅的公共 IP 地址限制适用于区域级别。您可以使用 AWS 提供的托管 Ingress 控制器（ALB）或像 Traefik 这样的第三方 Ingress 控制器。

[WARNING]
====
如果已经在使用托管 Ingress 控制器，则不建议安装像 Traefik 这样的第三方 Ingress 控制器。
====

[WARNING]
====
**Ingress-NGINX 终止服务：**社区 `ingress-nginx` 控制器将于 2026 年 3 月终止服务。此页面使用 Traefik，这是 Rancher 环境推荐的迁移路径。
====

Traefik 包含一个原生的 Ingress NGINX 提供程序。这使您可以在不重写现有 Ingress 对象的情况下从 NGINX 迁移，因为 Traefik 会自动解释 `nginx.ingress.kubernetes.io` 注释。如果您正在升级已经使用 `ingress-nginx` 的集群，请遵循此 https://doc.traefik.io/traefik/migrate/nginx-to-traefik/[指南] 以获取更多信息。

要安装 Traefik，我们强烈建议使用 https://apps.rancher.io/applications/traefik-proxy[Rancher Prime 应用程序集合] 中的 Traefik 应用程序。查看他们的 https://docs.apps.rancher.io/howto-guides/integrate-with-rancher-manager[文档以与 Rancher 管理器集成]。


[#_6_get_load_balancer_ip]
=== 6.获取负载均衡器 IP

要获取负载均衡器的地址，请运行：

----
kubectl get service traefik --namespace=traefik
----

结果应类似如下内容：

----
NAME                       TYPE           CLUSTER-IP     EXTERNAL-IP                                                              PORT(S)
 AGE
traefik  LoadBalancer   10.0.116.18    40.31.180.83   80:31229/TCP,443:31050/TCP 27m
----

保存 `EXTERNAL-IP`。

[#_7_set_up_dns]
=== 7.设置 DNS

外部流量需要指向您创建的负载均衡器。

为您保存的外部 IP 设置 DNS 记录。此 DNS 将用作 Rancher 服务器 URL.

有很多有效的方法来设置 DNS。如需帮助，请参阅 AWS 文档中关于 https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer.html[将流量路由到 ELB 负载均衡器] 的说明。

[#_8_install_the_rancher_helm_chart]
=== 8.安装 Rancher Helm Chart

接下来，按照 {xref-install-rancher}#_install_the_rancher_helm_chart[此页面] 上的说明安装 Rancher Helm Chart。Helm 的说明在任何 Kubernetes 发行版上安装 Rancher 时均相同。

在安装 Rancher 时，请使用上一步中的 DNS 名称作为 Rancher 服务器 URL。它可以作为 Helm 选项传递。例如，如果 DNS 名称是 `rancher.my.org`，您可以使用选项 `--set hostname=rancher.my.org` 运行 Helm 安装命令。

在此设置上安装 Rancher 时，您还需要将下面的值传递给 Rancher Helm 安装命令，以便设置将与 Rancher 的 Ingress 资源一起使用的 Ingress 控制器的名称：

----
--set ingress.ingressClassName=traefik
----

请参阅 {xref-install-rancher}#_5_install_rancher_with_helm_and_your_chosen_certificate_option[此处的 Helm 安装命令] 以获取您选择的证书选项。
