= 在 Azure Kubernetes Service 上安装 {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-09
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-aks.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/rancher-on-aks.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
endif::[]

本页面介绍如何在微软的 Azure Kubernetes Service (AKS) 上安装 Rancher。

本指南使用命令行工具来配置带有入口的 AKS 集群。如果您更喜欢使用 Azure 门户来配置集群，请参考 https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal[官方文档]。

如果您已经有一个 AKS Kubernetes 集群，请跳转到有关 <<_5_install_an_ingress,安装Ingress>> 的步骤。然后按照 {xref-install-rancher}#_install_the_rancher_helm_chart[本页面] 上的说明安装 Rancher Helm 图表。

[#_prerequisites]
== 先决条件

[CAUTION]
====

在微软 Azure 上部署将会产生费用。
====


* https://azure.microsoft.com/en-us/free/[微软 Azure 帐户]：创建资源以部署 Rancher 和 Kubernetes 需要一个微软 Azure 帐户。
* https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/create-subscription#create-a-subscription-in-the-azure-portal[微软 Azure 订阅]：如果您还没有微软 Azure 订阅，请使用此链接查看教程以创建一个。
* https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-create-new-tenant[微软 Azure 租户]：使用此链接并按照说明创建一个微软 Azure 租户。
* 您的订阅至少有足够的配额用于 2 个 vCPU。有关 Rancher 服务器资源要求的详细信息，请参考 {xref-install-reqs}[本节]。
* 在 Azure 中使用 Helm 安装 Rancher 时，请使用 L7 负载均衡器以避免网络问题。有关更多信息，请参考 https://docs.microsoft.com/en-us/azure/load-balancer/components#_limitations[Azure 负载均衡器限制] 的文档。

[#_1_prepare_your_workstation]
== 1.准备您的工作站

在您的工作站上安装以下命令行工具：

* Azure CLI，*az:*有关帮助，请参阅这些 https://docs.microsoft.com/en-us/cli/azure/[安装步骤。]
* *kubectl:*有关帮助，请参阅这些 https://kubernetes.io/docs/tasks/tools/#kubectl[安装步骤。]
* *helm:*有关帮助，请参阅这些 https://helm.sh/docs/intro/install/[安装步骤。]

[#_2_create_a_resource_group]
== 2.创建资源组

安装 CLI 后，您需要使用您的 Azure 帐户登录。

----
az login
----

创建一个 https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal[资源组]以保存集群的所有相关资源。使用适合您用例的位置。

----
az group create --name rancher-rg --location eastus
----

[#_3_create_the_aks_cluster]
== 3.创建 AKS 集群

要创建 AKS 集群，请运行以下命令。使用适合您用例的虚拟机大小。请参阅 https://docs.microsoft.com/en-us/azure/virtual-machines/sizes[本文]以获取可用的大小和选项。在选择 Kubernetes 版本时，请务必先查阅 https://rancher.com/support-matrix/[支持矩阵]，以找到已为您的 Rancher 版本验证的最高 Kubernetes 版本。

----
az aks create \
  --resource-group rancher-rg \
  --name rancher-server \
  --kubernetes-version <VERSION> \
  --node-count 3 \
  --node-vm-size Standard_D2_v3
----

集群部署需要一些时间。

[#_4_get_access_credentials]
== 4.获取访问凭证

集群部署后，获取访问凭证。

----
az aks get-credentials --resource-group rancher-rg --name rancher-server
----

此命令将您的集群凭证合并到现有的 kubeconfig 中，并允许 `kubectl` 与集群进行交互。

[#_5_install_an_ingress]
== 5.安装Ingress

集群需要一个Ingress，以便从集群外部访问Rancher。安装Ingress需要分配一个公共IP地址。确保您有足够的配额，否则将无法分配IP地址。公共 IP 地址的限制适用于每个订阅的区域级别。您可以使用 Azure 提供的托管 Ingress 控制器或像 Traefik 这样的第三方 Ingress 控制器。

[WARNING]
====
如果已经在使用托管 Ingress 控制器，则不建议安装像 Traefik 这样的第三方 Ingress 控制器。
====

[WARNING]
====
**Ingress-NGINX EOL：**社区 `ingress-nginx` 控制器将在 2026 年 3 月达到终止服务（EOL）。此页面使用 Traefik，这是 Rancher 环境推荐的迁移路径。
====

Traefik 包含一个原生的 Ingress NGINX 提供程序。这使您可以在不重写现有 Ingress 对象的情况下从 NGINX 迁移，因为 Traefik 会自动解释 `nginx.ingress.kubernetes.io` 注释。如果您正在升级已经使用 `ingress-nginx` 的集群，请遵循此 https://doc.traefik.io/traefik/migrate/nginx-to-traefik/[指南] 以获取更多信息。

要安装 Traefik，我们强烈建议使用 https://apps.rancher.io/applications/traefik-proxy[Rancher Prime 应用程序集合] 中的 Traefik 应用程序。查看他们的 https://docs.apps.rancher.io/howto-guides/integrate-with-rancher-manager[文档以与 Rancher 管理器集成]。


[#_6_get_load_balancer_ip]
== 6.获取负载均衡器 IP

要获取负载均衡器的地址，请运行：

----
kubectl get service traefik --namespace=traefik
----

结果应类似如下内容：

----
NAME                       TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)
 AGE
traefik  LoadBalancer   10.0.116.18    40.31.180.83   80:31229/TCP,443:31050/TCP 67s
----

保存 `EXTERNAL-IP`。

[#_7_set_up_dns]
== 7.设置 DNS

外部流量需要指向您创建的负载均衡器。

设置一个 DNS 指向您保存的 `EXTERNAL-IP`。此 DNS 将用作 Rancher 服务器 URL。

有许多有效的方法来设置 DNS。有关帮助，请参阅 https://docs.microsoft.com/en-us/azure/dns/[Azure DNS 文档]。

[#_8_install_the_rancher_helm_chart]
== 8.安装 Rancher Helm 图表

接下来，请按照 {xref-install-rancher}#_install_the_rancher_helm_chart[此页面] 上的说明安装 Rancher Helm 图表。Helm 的说明在任何 Kubernetes 发行版上安装 Rancher 时都是相同的。

在安装 Rancher 时，请使用上一步中的 DNS 名称作为 Rancher 服务器 URL。可以作为 Helm 选项传递。例如，如果 DNS 名称是 `rancher.my.org`，您可以使用选项 `--set hostname=rancher.my.org` 运行 Helm 安装命令。

在此设置上安装 Rancher 时，您还需要将下面的值传递到 Rancher Helm 安装命令中，以便设置与 Rancher 的 Ingress 资源一起使用的 Ingress 控制器的名称：

----
--set ingress.ingressClassName=traefik
----

有关您选择的证书选项，请参阅 {xref-install-rancher}#_5_install_rancher_with_helm_and_your_chosen_certificate_option[此处的 Helm 安装命令]。
