= Surveillance et Tableaux de Bord
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/index.adoc 
:product-path: observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:description: Prometheus vous permet de visualiser les métriques de vos différents objets Rancher et Kubernetes. Découvrez l'étendue de la surveillance et comment activer la surveillance des clusters
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
:xref-configure-alertmanager: xref:observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:observability/monitoring-and-dashboards/configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:observability/monitoring-and-dashboards/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheusrules.adoc
:xref-prometheus: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
:xref-enable-monitoring: xref:observability/monitoring-and-dashboards/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:observabilité/surveillance-et-tableaux-de-bord/personnaliser-le-tableau-de-bord/créer-un-tableau-de-bord-grafana-persistant.adoc
:xref-servicemonitors-and-podmonitors: xref:observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:observability/monitoring-and-dashboards/configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:observability/monitoring-and-dashboards/configuration/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:observability/monitoring-and-dashboards/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:observability/monitoring-and-dashboards/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:observability/monitoring-and-dashboards/windows-support.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
:xref-configure-alertmanager: xref:guides-pratiques/guides-utilisateurs-avancés/guide-de-configuration-de-surveillance-v2/configuration-avancée/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:reference-guides/monitoring-v2-configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:guides-pratiques/guides-utilisateurs-avancés/guide-de-surveillance-et-d'alerte/configurer-la-surveillance-des-charges-de-travail.adoc
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:comment-faire/guide-utilisateur-avancé/guide-de-configuration-de-surveillance-v2/configuration-avancée/règles-prometheus.adoc
:xref-prometheus: xref:comment-faire/guide-utilisateur-avancé/guide-de-configuration-de-surveillance-v2/configuration-avancée/prometheus.adoc
:xref-enable-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:comment-faire/guide-utilisateur-avancé/guide-de-surveillance-et-d'alerte/créer-un-tableau-de-bord-grafana-persistant.adoc
:xref-servicemonitors-and-podmonitors: xref:reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:reference-guides/monitoring-v2-configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:integrations-in-rancher/monitoring-and-alerting/windows-support.adoc
endif::[]

L'application `rancher-monitoring` peut déployer rapidement des solutions de surveillance et d'alerte Open Source de premier plan sur votre cluster.

Introduite dans Rancher v2.5, l'application est alimentée par https://prometheus.io/[Prometheus], https://grafana.com/grafana/[Grafana], https://prometheus.io/docs/alerting/latest/alertmanager/[Alertmanager], le https://github.com/prometheus-operator/prometheus-operator[Prometheus Operator], et le https://github.com/DirectXMan12/k8s-prometheus-adapter[Prometheus adapter.]

Pour des informations sur la surveillance et l'alerte V1, disponibles dans Rancher v2.2 jusqu'à v2.4, veuillez consulter la documentation Rancher v2.0--v2.4 sur xref:[la surveillance des clusters], xref:[l'alerte], xref:[les notificateurs] et d'autres xref:[outils].

En utilisant l'application `rancher-monitoring`, vous pouvez rapidement déployer des solutions de surveillance et d'alerte Open Source de premier plan sur votre cluster.

[#_features]
== Fonctions

Prometheus vous permet de visualiser des métriques provenant de vos objets Rancher et Kubernetes. En utilisant des horodatages, Prometheus vous permet d'interroger et de visualiser ces métriques dans des graphiques et des visuels faciles à lire, soit via l'interface utilisateur de Rancher, soit via Grafana, qui est une plateforme d'analyse déployée avec Prometheus.

En visualisant les données que Prometheus collecte depuis votre plan de contrôle de cluster, vos nœuds et vos déploiements, vous pouvez rester informé de tout ce qui se passe dans votre cluster. Vous pouvez ensuite utiliser ces analyses pour mieux gérer votre organisation{nbsp}: interrompre les urgences système avant qu'elles ne commencent, développer des stratégies de maintenance, ou restaurer des serveurs en panne.

L'application de surveillance{nbsp}:

* Surveille l'état et les processus de vos nœuds de cluster, des composants Kubernetes et des déploiements logiciels.
* Définit des alertes basées sur des métriques collectées via Prometheus.
* Crée des tableaux de bord Grafana personnalisés.
* Configure des notifications basées sur des alertes par e-mail, Slack, PagerDuty, etc. en utilisant Prometheus Alertmanager.
* Définit des expressions pré-calculées, fréquemment nécessaires ou coûteuses en calcul comme de nouvelles séries temporelles basées sur des métriques collectées via Prometheus.
* Expose les métriques collectées de Prometheus à l'API des métriques personnalisées Kubernetes via l'adaptateur Prometheus pour une utilisation dans HPA.

Voir {xref-how-monitoring-works}[Comment fonctionne la surveillance] pour une explication de la façon dont les composants de surveillance fonctionnent ensemble.

[#_default_components_and_deployments]
== Composants et déploiements par défaut

[#_built_in_dashboards]
=== Tableaux de bord intégrés

Par défaut, l'application de surveillance déploie des tableaux de bord Grafana (curés par le projet https://github.com/prometheus-operator/kube-prometheus[kube-prometheus]) sur un cluster.

Elle déploie également une interface utilisateur Alertmanager et une interface utilisateur Prometheus. Pour plus d'informations sur ces outils, voir {xref-monitoring-builtin-dashboards}[Tableaux de bord intégrés.]

[#_default_metrics_exporters]
=== Exportateurs de métriques par défaut

Par défaut, Rancher Monitoring déploie des exportateurs (tels que https://github.com/prometheus/node_exporter[node-exporter] et https://github.com/kubernetes/kube-state-metrics[kube-state-metrics]).

Ces exportateurs par défaut récupèrent automatiquement les métriques pour l'UC et la mémoire de tous les composants de votre cluster Kubernetes, y compris vos charges de travail.

[#_default_alerts]
=== Alertes par défaut

L'application de surveillance déploie certaines alertes par défaut. Pour voir les alertes par défaut, allez à l'xref:./built-in-dashboards.adoc#_alertmanager_ui[interface utilisateur Alertmanager] et cliquez sur *Développer tous les groupes.*

[#_components_exposed_in_the_rancher_ui]
=== Composants exposés dans l'interface utilisateur Rancher

Pour une liste des composants de surveillance exposés dans l'interface utilisateur Rancher, ainsi que des cas d'utilisation courants pour les modifier, voir xref:./how-monitoring-works.adoc#_components_exposed_in_the_rancher_ui[cette section.]

[#_role_based_access_control]
== Contrôle d'accès en fonction du rôle

Pour plus d'informations sur la configuration de l'accès à la surveillance, voir {xref-rancher-monitoring-rbac}[cette page.]

[NOTE]
====

Les permissions de lecture de Rancher et de projet ne s'appliquent pas nécessairement aux ressources de surveillance. Voir xref:./rbac-for-monitoring.adoc#_additional_monitoring_clusterroles[monitoring-ui-view] pour plus de détails.
====


[#_guides]
== Guides

* {xref-enable-monitoring}[Activer la surveillance]
* {xref-monitoring-uninstall}[Désinstaller la surveillance]
* {xref-rancher-workload-monitoring}[Surveiller les charges de travail]
* {xref-customize-grafana-dashboard}[Personnalisation des tableaux de bord Grafana]
* {xref-create-persistent-grafana-dashboard}[Tableaux de bord Grafana persistants]
* {xref-monitoring-debug-high-memory}[Débogage de l'utilisation élevée de la mémoire]

[#_configuration]
== Configuration

[#_configuring_monitoring_resources_in_rancher]
=== Configuration des ressources de surveillance dans Rancher

La référence de configuration suppose une familiarité avec le fonctionnement des composants de surveillance ensemble. Pour plus d'informations, voir {xref-how-monitoring-works}[Comment fonctionne la surveillance.]

* {xref-servicemonitors-and-podmonitors}[ServiceMonitor et PodMonitor]
* {xref-receivers}[Receiver]
* {xref-monitoring-routes}[Route]
* {xref-prometheusrules}[RèglePrometheus]
* {xref-prometheus}[Prometheus]
* {xref-configure-alertmanager}[Alertmanager]

[#_configuring_helm_chart_options]
=== Configuration des options du graphique Helm

Pour plus d'informations sur les options de `rancher-monitoring` graphique, y compris les options pour définir les limites et les demandes de ressources, voir {xref-monitoring-helm-chart-options}[Options du graphique Helm].

[#_windows_cluster_support]
== Prise en charge des grappes Windows

Pour pouvoir déployer complètement la surveillance V2 pour Windows, tous vos hôtes Windows doivent avoir une version minimale de https://github.com/rancher/wins[wins] v0.1.0.

Pour plus de détails sur la façon de mettre à niveau wins sur les hôtes Windows existants, voir {xref-monitoring-windows}[Prise en charge des grappes Windows pour la surveillance V2.]

[#_known_issues]
== Problèmes connus

Il existe un https://github.com/rancher/rancher/issues/28787#issuecomment-693611821[problème connu] selon lequel les grappes K3s nécessitent plus de mémoire que celle allouée par défaut. Si vous activez la surveillance sur une grappe K3s, définissez `prometheus.prometheusSpec.resources.memory.limit` à 2500 Mi et `prometheus.prometheusSpec.resources.memory.request` à 1750 Mi.

Voir {xref-monitoring-debug-high-memory}[Débogage de l'utilisation élevée de la mémoire] pour des conseils et des recommandations.
