= Support de cluster Windows pour la V2 d'observabilité
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/windows-support.adoc 
:product-path: observability/monitoring-and-dashboards/windows-support.adoc

La V2 d'observabilité peut être déployée sur un cluster Windows pour extraire des métriques des nœuds Windows en utilisant https://github.com/prometheus-community/windows_exporter[prometheus-community/windows_exporter] (précédemment nommé `wmi_exporter`).

[#_cluster_requirements]
== Exigences du cluster

La V2 d'observabilité pour Windows ne peut extraire des métriques que des hôtes Windows ayant une version minimale de `wins` v0.1.0.  Pour pouvoir déployer complètement la V2 d'observabilité pour Windows, tous vos hôtes doivent répondre à cette exigence.

[#_upgrading_existing_clusters_to_wins_v0_1_0]
=== Mise à niveau des clusters existants vers wins v0.1.0

Si le cluster a été provisionné avant Rancher 2.5.8 (même si la version actuelle de Rancher est 2.5.8), vous ne pourrez pas déployer avec succès la V2 d'observabilité pour Windows tant que vous n'aurez pas mis à niveau la version wins sur chaque hôte à au moins v0.1.0.

Pour faciliter cette mise à niveau, Rancher 2.5.8 a publié un tout nouveau chart Helm appelé `rancher-wins-upgrader`.

. Déployez `rancher-wins-upgrader` avec l'override suivant{nbsp}:
+
[,yaml]
----
 # Masquerading bootstraps the wins-upgrader installation via
 # a previously whitelisted process path since the normal install path,
 # c:\etc\rancher\wins\wins-upgrade.exe is not normally whitelisted.
 # In this case, we are using the previously whitelisted process
 # path used by Monitoring V1.
 masquerade:
   enabled: true
   as: c:\\etc\wmi-exporter\wmi-exporter.exe
----

. Une fois que tous vos hôtes ont été mis à niveau avec succès, veuillez vous assurer de déployer à nouveau le chart Helm avec les valeurs par défaut pour éviter les conflits avec les paramètres suivants{nbsp}:
+
[,yaml]
----
 masquerade:
   enabled: false
----

*Résultat :* Les hôtes sont prêts pour l'installation de la V2 d'observabilité. Vous pouvez choisir de désinstaller le chart `rancher-wins-upgrader` ou de le conserver dans votre cluster pour faciliter les futures mises à niveau.

Pour plus d'informations sur son utilisation, veuillez consulter le https://github.com/rancher/wins/blob/master/charts/rancher-wins-upgrader/README.md[README.md] du chart.
