= 水平ポッドオートスケーラー
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/index.adoc 
:product-path: cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/horizontal-pod-autoscaler.adoc
:description: 水平ポッドオートスケーラー（HPA）について学びます。HPAを管理する方法と、サービスデプロイメントでテストする方法
:experimental:
ifeval::["{build-type}" != "community"]
:xref-hpas-with-kubectl: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
:xref-hpas-with-ui: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:xref-hpas-test: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/test-hpas-with-kubectl.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-hpas-with-kubectl: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
:xref-hpas-with-ui: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:xref-hpas-test: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/test-hpas-with-kubectl.adoc
endif::[]

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[水平ポッドオートスケーラー]（HPA）は、クラスターを自動的にスケールアップまたはスケールダウンするように構成できるKubernetesの機能です。

Rancherは、Rancherのバージョンに応じてHPAを管理するための追加機能を提供します。

Rancher UIを使用してHPAを作成、管理、削除できます。これは`autoscaling/v2beta2` APIのHPAのみをサポートしています。

[#_managing_hpas]
== HPAの管理

HPAの管理方法は、Kubernetes APIのバージョンによって異なります：

* *Kubernetes APIバージョンautoscaling/V2beta1の場合:*このバージョンのKubernetes APIでは、アプリケーションのCPUおよびメモリ使用率に基づいてポッドを自動スケールできます。
* *Kubernetes APIバージョンautoscaling/V2beta2の場合:*このバージョンのKubernetes APIでは、CPUおよびメモリ使用率に加えて、カスタムメトリクスに基づいてポッドを自動スケールできます。

Rancher UIを使用してHPAを作成、管理、削除できます。Rancher UIから、CPUおよびメモリ使用率に基づいてHPAをスケールするように構成できます。詳細については、{xref-hpas-with-ui}[Rancher UIを使用したHPAの管理]を参照してください。カスタムメトリクスに基づいてHPAをスケールするには、依然として`kubectl`を使用する必要があります。詳細については、{xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[Prometheusを使用してカスタムメトリクスでスケールするためのHPAの構成]を参照してください。

Rancher v2.0.7以降で作成されたクラスターは、HPAを使用するために必要なすべての要件（メトリクスサーバーとKubernetesクラスターの設定）を自動的に満たしています。

[#_testing_hpas_with_a_service_deployment]
== サービスデプロイメントでのHPAのテスト

プロジェクトに移動し、menu:リソース[HPA]をクリックすることで、HPAの現在のレプリカ数を確認できます。詳細については、{xref-hpas-with-ui}[HPAメトリクスとステータスの取得]を参照してください。

負荷テストツールでテストしたHPAのステータスを取得するには、`kubectl`を使用することもできます。詳細については、{xref-hpas-test}[kubectlを使用したHPAのテスト]を参照してください。
