= {rancher-product-name} UIを使用したHPAの管理
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc 
:product-path: cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-hpas-with-kubectl: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-hpas-with-kubectl: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
endif::[]

Rancher UIは、HPAの作成、管理、および削除をサポートしています。HPAがスケールに使用するメトリックとして、CPUまたはメモリ使用量を設定できます。

CPUやメモリ以外のメトリックに基づいてスケールするHPAを作成したい場合は、{xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[Prometheusを使用したカスタムメトリックによるHPAのスケーリングの設定]を参照してください。

[#_creating_an_hpa]
== HPAの作成

. 左上隅で、*☰ > クラスター管理*をクリックします。
. HPAを作成したいクラスターに移動し、*探索*をクリックします。
. 左側のナビゲーションバーで、menu:サービスディスカバリー[HorizontalPodAutoscalers]をクリックします。
. ［*作成*］をクリックします。
. HPAのための*ネームスペース*を選択します。
. HPAのための*名前*を入力します。
. HPAのスケールターゲットとして*ターゲットリファレンス*を選択します。
. HPAのための*最小レプリカ*と*最大レプリカ*を指定します。
. HPAのメトリックを設定します。HPAがサービスをスケールアップまたはスケールダウンさせるメトリックとして、メモリまたはCPU使用量を選択できます。*数量*フィールドには、HPAがサービスをスケールさせるトリガーとなるワークロードのメモリまたはCPU使用量の割合を入力します。Prometheusから利用可能なメトリックを含む他のHPAメトリックを設定するには、{xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[kubectlを使用してHPAを管理する]が必要です。
. HPAを作成するには、*作成*をクリックします。

[NOTE]
.結果:
====

HPAは選択したネームスペースにデプロイされます。プロジェクトのリソース > HPAビューからHPAのステータスを確認できます。
====


[#_get_hpa_metrics_and_status]
== HPAメトリックとステータスを取得

. 左上隅で、*☰ > クラスター管理*をクリックします。
. HPAを持つクラスターに移動し、*探索*をクリックします。
. 左側のナビゲーションバーで、menu:サービスディスカバリー[HorizontalPodAutoscalers]をクリックします。*HorizontalPodAutoscalers*ページには、現在のレプリカの数が表示されます。

特定のHPAの詳細なメトリクスとステータスを確認するには、HPAの名前をクリックします。これにより、HPAの詳細ページに移動します。

[#_deleting_an_hpa]
== HPAの削除

. 左上隅で、*☰ > クラスター管理*をクリックします。
. 削除したいHPAを持つクラスターに移動し、*探索*をクリックします。
. 左側のナビゲーションバーで、menu:サービスディスカバリー[HorizontalPodAutoscalers]をクリックします。
. menu:リソース[HPA]をクリックします。
. 削除したいHPAを見つけて、*⋮ > 削除*をクリックします。
. *削除*をクリックして確認します。

[NOTE]
.結果:
====

HPAは現在のクラスターから削除されました。
====

