= Requisitos de puertos
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc 
:product-path: installation-and-upgrade/requirements/port-requirements.adoc
:description: Lee sobre los requisitos de puerto necesarios para que Rancher funcione correctamente, tanto para los nodos de Rancher como para los nodos del clúster de Kubernetes en sentido descendente.
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-harvester-overview: xref:integrations/harvester/overview.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-custom-clusters: xref:cluster-deployment/custom-clusters/custom-clusters.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-infra-aws: xref:cluster-deployment/infra-providers/aws/aws.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-harvester-overview: xref:integrations-in-rancher/harvester/overview.adoc
:xref-infra-providers: xref:guías-de-instrucciones/nuevas-guías-de-usuario/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/index.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-register-clusters: xref:guías-de-instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/registrar-clusters-existentes.adoc
:xref-custom-clusters: xref:guías-de-referencia/configuración-de-cluster/configuración-del-servidor-rancher/utilizar-nodos-existentes/index.adoc
:xref-hosted-k8s-clusters: xref:guías-de-instrucciones/nuevas-guías-de-usuario/clusters-de-kubernetes-en-rancher-configuración/configurar-clusters-a-partir-de-proveedores-kubernetes-alojados/index.adoc
:xref-infra-aws: xref:instrucciones/nuevas-guías-de-usuario/lanzar-kubernetes-con-rancher/utilizar-nuevos-nodos-en-un-proveedor-de-infraestructura/crear-un-cluster-amazon-ec2.adoc
endif::[]

Para funcionar correctamente, Rancher requiere que se abran varios puertos en los nodos de Rancher y en los nodos del clúster de Kubernetes en sentido descendente.

[#_rancher_nodes]
== Nodos de Rancher

La siguiente tabla enumera los puertos que deben estar abiertos hacia y desde los nodos que están ejecutando el servidor Rancher.

Los requisitos de puertos difieren según la arquitectura del servidor Rancher.

Rancher se puede instalar en cualquier clúster de Kubernetes. Para las instalaciones de Rancher en un clúster de Kubernetes K3s, RKE o RKE2, consulta las pestañas a continuación. Para otras distribuciones de Kubernetes, consulta la documentación de la distribución para los requisitos de puertos de los nodos del clúster.

[NOTE]
.Notas:
====
* Los nodos de Rancher también pueden requerir acceso saliente adicional para cualquier proveedor de autenticación externo que esté configurado (por ejemplo, LDAP).
* Kubernetes recomienda TCP 30000-32767 para los servicios de puerto de nodo.
* Para los firewalls, puede ser necesario habilitar el tráfico dentro del clúster y el CIDR de los pods.
* Los nodos de Rancher también pueden necesitar acceso saliente a una ubicación S3 externa que se utiliza para almacenar copias de seguridad del clúster (por ejemplo, Minio).
====


[#_ports_for_rancher_server_nodes_on_k3s_product_name]
=== Puertos para los Nodos del Servidor Rancher en {k3s-product-name}

.Haga clic para expandir
[%collapsible]
======
El servidor K3s necesita que el puerto 6443 sea accesible por los nodos.

Los nodos necesitan poder alcanzar a otros nodos a través del puerto UDP 8472 cuando se utiliza Flannel VXLAN. El nodo no debe escuchar en ningún otro puerto. K3s utiliza túneles inversos de modo que los nodos establecen conexiones salientes al servidor y todo el tráfico de kubelet pasa a través de ese túnel. Sin embargo, si no utilizas Flannel y proporcionas tu propia CNI personalizada, entonces el puerto 8472 no es necesario para K3s.

Si deseas utilizar el servidor de métricas, necesitarás abrir el puerto 10250 en cada nodo.

[NOTE]
.Importante:
====
El puerto VXLAN en los nodos no debe exponerse al mundo, ya que permite que tu red de clúster sea accesible para cualquiera. Ejecuta tus nodos detrás de un firewall/grupo de seguridad que desactive el acceso al puerto 8472.
====


Las siguientes tablas desglosan los requisitos de puertos para el tráfico entrante y saliente:

.Reglas de Entrada para los Nodos del Servidor Rancher
|===
| Protocolo | Puerto | Fuente | Descripción

| TCP
| 80
| Balanceador de carga/proxy que realiza la terminación SSL externa
| Interfaz de usuario/API de Rancher cuando se utiliza la terminación SSL externa

| TCP
| 443
| <ul><li>nodos de servidor</li><li>nodos agentes</li><li>Kubernetes alojado/registrado</li><li>cualquier fuente que necesite poder usar la interfaz de usuario o API de Rancher</li></ul>
| agente de Rancher, interfaz de usuario/API de Rancher, kubectl

| TCP
| 6443
| nodos de servidor K3s
| API de Kubernetes

| UDP
| 8472
| nodos de servidor y agentes K3s
| Requerido solo para Flannel VXLAN.

| TCP
| 10250
| nodos de servidor y agentes K3s
| kubelet
|===

.Reglas de salida para nodos de Rancher
|===
| Protocolo | Puerto | Destino | Descripción

| TCP
| 22
| Cualquier IP de nodo de un nodo creado utilizando el controlador de nodos
| Provisionamiento SSH de nodos utilizando el controlador de nodos

| TCP
| 443
| git.rancher.io
| Catálogo de Rancher

| TCP
| 2376
| Cualquier IP de nodo de un nodo creado utilizando el controlador de nodos
| Puerto TLS del daemon de Docker utilizado por Docker Machine

| TCP
| 6443
| API de Kubernetes alojada/importada
| servidor API de Kubernetes
|===
======

[#_ports_for_rancher_server_nodes_on_rke2_product_name]
=== Puertos para los Nodos del Servidor Rancher en {rke2-product-name}

.Haga clic para expandir
[%collapsible]
======
El servidor RKE2 necesita que los puertos 6443 y 9345 sean accesibles por otros nodos en el clúster.

Todos los nodos necesitan poder alcanzar a otros nodos a través del puerto UDP 8472 cuando se utiliza Flannel VXLAN.

Si deseas utilizar el servidor de métricas, necesitarás abrir el puerto 10250 en cada nodo.

[NOTE]
.Importante:
====

El puerto VXLAN en los nodos no debe exponerse al mundo, ya que permite que tu red de clúster sea accesible para cualquiera. Ejecuta tus nodos detrás de un firewall/grupo de seguridad que desactive el acceso al puerto 8472.
====

.Reglas de entrada para nodos de servidor RKE2
|===
| Protocolo | Puerto | Fuente | Descripción

| TCP
| 9345
| nodos de servidor y agentes RKE2
| Registro de nodos. El puerto debe estar abierto en todos los nodos de servidor a todos los demás nodos en el clúster.

| TCP
| 6443
| nodos de agente RKE2
| API de Kubernetes

| UDP
| 8472
| nodos de servidor y agentes RKE2
| Requerido solo para Flannel VXLAN

| TCP
| 10250
| nodos de servidor y agentes RKE2
| kubelet

| TCP
| 2379
| Nodos de servidor RKE2
| Puerto del cliente etcd

| TCP
| 2380
| Nodos de servidor RKE2
| Puerto de pares etcd

| TCP
| 30000-32767
| nodos de servidor y agentes RKE2
| Rango de puertos NodePort. Puede usar TCP o UDP.

| TCP
| 5473
| Pod de Calico-node conectándose al pod de typha
| Requerido al desplegar con Calico

| HTTP
| 80
| Balanceador de carga/proxy que realiza la terminación SSL externa
| Interfaz de usuario/API de Rancher cuando se utiliza la terminación SSL externa

| HTTPS
| 443
| <ul><li>Kubernetes alojado/registrado</li><li>cualquier fuente que necesite poder usar la interfaz de usuario o API de Rancher</li></ul>
| agente de Rancher, interfaz de usuario/API de Rancher, kubectl. No es necesario si tienes un balanceador de carga que realice la terminación TLS.
|===

Típicamente, se permite todo el tráfico saliente.
======

[#_ports_for_rancher_server_in_docker]
=== Puertos para el servidor Rancher en Docker

.Haga clic para expandir
[%collapsible]
======
Las siguientes tablas desglosan los requisitos de puertos para los nodos de Rancher, para el tráfico entrante y saliente:

.Reglas de entrada para el nodo de Rancher
|===
| Protocolo | Puerto | Fuente | Descripción

| TCP
| 80
| Balanceador de carga/proxy que realiza la terminación SSL externa
| Interfaz de usuario/API de Rancher cuando se utiliza la terminación SSL externa

| TCP
| 443
| <ul><li>Kubernetes alojado/registrado</li><li>cualquier fuente que necesite poder usar la interfaz de usuario o API de Rancher</li></ul>
| Agente de Rancher, Interfaz de usuario/API de Rancher, kubectl.
|===

.Reglas de salida para el nodo de Rancher
|===
| Protocolo | Puerto | Fuente | Descripción

| TCP
| 22
| Cualquier IP de nodo de un nodo creado utilizando el controlador de nodos
| Provisionamiento SSH de nodos utilizando el controlador de nodos

| TCP
| 443
| git.rancher.io
| catálogo de Rancher

| TCP
| 2376
| Cualquier IP de nodo de un nodo creado utilizando un controlador de nodo
| Puerto TLS del daemon de Docker utilizado por Docker Machine

| TCP
| 6443
| API de Kubernetes alojada/importada
| servidor API de Kubernetes
|===
======

[#_downstream_kubernetes_cluster_nodes]
== Nodos del clúster de Kubernetes en sentido descendente

Los clústeres de Kubernetes en sentido descendente ejecutan tus aplicaciones y servicios. Esta sección describe qué puertos deben abrirse en los nodos de los clústeres en sentido descendente para que Rancher pueda comunicarse con ellos.

Los requisitos de puertos difieren dependiendo de cómo se lanzó el clúster en sentido descendente. Cada una de las pestañas a continuación lista los puertos que deben abrirse para diferentes {xref-cluster-deployment}[tipos de clúster].

El siguiente diagrama representa los puertos que están abiertos para cada {xref-cluster-deployment}[tipo de clúster].

.Requisitos de puertos para el plano de gestión de Rancher
image::port-communications.svg[Requisitos básicos de puertos]

[TIP]
====

Si la seguridad no es una gran preocupación y estás de acuerdo con abrir algunos puertos adicionales, puedes usar la tabla en <<_commonly_used_ports,Puertos comúnmente utilizados>> como tu referencia de puertos en lugar de las tablas completas a continuación.
====


[#_ports_for_harvester_product_name_clusters]
=== Puertos para {harvester-product-name} clústeres

Consulta el {xref-harvester-overview}#_requisitos_de_puerto[{harvester-product-name} Visión General de Integración] para más información sobre los requisitos de puerto de Harvester.

[#_ports_for_rancher_launched_kubernetes_clusters_using_node_pools]
=== Puertos para clústeres de Kubernetes lanzados por Rancher utilizando grupos de nodos

.Haga clic para expandir
[%collapsible]
======
La siguiente tabla muestra los requisitos de puerto para {xref-launch-k8s-with-rancher}[Kubernetes Lanzado por Rancher] con nodos creados en un {xref-infra-providers}[Proveedor de Infraestructura].

[NOTE]
====
Los puertos requeridos se abren automáticamente por Rancher durante la creación de clústeres en proveedores de nube como Amazon EC2 o DigitalOcean.
====

include::shared:ROOT:partial$en/ports-iaas-nodes.adoc[]

======

[#_ports_for_rancher_launched_kubernetes_clusters_using_custom_nodes]
=== Puertos para clústeres de Kubernetes lanzados por Rancher utilizando nodos personalizados

.Haga clic para expandir
[%collapsible]
======
La siguiente tabla muestra los requisitos de puerto para {xref-launch-k8s-with-rancher}[Kubernetes lanzado por Rancher] con {xref-custom-clusters}[nodos personalizados].

include::shared:ROOT:partial$en/ports-custom-nodes.adoc[]

======

[#_ports_for_hosted_kubernetes_clusters]
=== Puertos para clústeres de Kubernetes alojados

.Haga clic para expandir
[%collapsible]
======
La siguiente tabla muestra los requisitos de puerto para {xref-hosted-k8s-clusters}[clústeres alojados].

include::shared:ROOT:partial$en/ports-imported-hosted.adoc[]

======

[#_ports_for_registered_clusters]
=== Puertos para clústeres registrados

[NOTE]
====

Los clústeres registrados se llamaban clústeres importados antes de Rancher v2.5.
====


.Haga clic para expandir
[%collapsible]
======
La siguiente tabla muestra los requisitos de puerto para {xref-register-clusters}[clústeres registrados].

include::shared:ROOT:partial$en/ports-imported-hosted.adoc[]

======

[#_other_port_considerations]
== Otras consideraciones de puerto

[#_commonly_used_ports]
=== Puertos comúnmente utilizados

Estos puertos suelen estar abiertos en sus nodos de Kubernetes, independientemente del tipo de clúster que sea.

include::shared:ROOT:partial$en/common-ports-table.adoc[]

'''

[#_local_node_traffic]
=== Tráfico de nodo local

Los puertos marcados como `local traffic` (es decir, `9099 TCP`) en los requisitos anteriores se utilizan para las comprobaciones de salud de Kubernetes (`livenessProbe` y ``readinessProbe``).
Estas comprobaciones de salud se ejecutan en el propio nodo. En la mayoría de los entornos de nube, este tráfico local está permitido por defecto.

Sin embargo, este tráfico puede ser bloqueado cuando:

* Has aplicado políticas de firewall estrictas en el nodo.
* Estás utilizando nodos que tienen múltiples interfaces (multihomed).

En estos casos, tienes que permitir explícitamente este tráfico en tu firewall de host, o en el caso de máquinas alojadas en la nube pública o privada (es decir, AWS u OpenStack), en la configuración de tu grupo de seguridad. Ten en cuenta que al usar un grupo de seguridad como origen o destino en tu grupo de seguridad, abrir puertos explícitamente solo se aplica a la interfaz privada de los nodos/instancias.

[#_rancher_aws_ec2_security_group]
=== Grupo de seguridad de Rancher AWS EC2

Al usar el {xref-infra-aws}[controlador de nodo AWS EC2] para aprovisionar nodos de clúster en Rancher, puedes optar por permitir que Rancher cree un grupo de seguridad llamado `rancher-nodes`. Las siguientes reglas se añaden automáticamente a este grupo de seguridad.

[cols=",^,^,,^"]
|===
| Tipo | Protocolo | Rango de Puertos | Origen/Destino | Tipo de Regla

| SSH
| TCP
| 22
| 0.0.0.0/0 y ::/0
| Entrante

| HTTP
| TCP
| 80
| 0.0.0.0/0 y ::/0
| Entrante

| Regla TCP personalizada
| TCP
| 443
| 0.0.0.0/0 y ::/0
| Entrante

| Regla TCP personalizada
| TCP
| 2376
| 0.0.0.0/0 y ::/0
| Entrante

| Regla TCP personalizada
| TCP
| 6443
| 0.0.0.0/0 y ::/0
| Entrante

| Regla TCP personalizada
| TCP
| 179
| sg-xxx (nodos-rancher)
| Entrante

| Regla TCP personalizada
| TCP
| 9345
| sg-xxx (nodos-rancher)
| Entrante

| Regla TCP personalizada
| TCP
| 2379-2380
| sg-xxx (nodos-rancher)
| Entrante

| Regla TCP personalizada
| TCP
| 10250-10252
| sg-xxx (nodos-rancher)
| Entrante

| Regla TCP personalizada
| TCP
| 10256
| sg-xxx (nodos-rancher)
| Entrante

| Regla UDP personalizada
| UDP
| 4789
| sg-xxx (nodos-rancher)
| Entrante

| Regla UDP personalizada
| UDP
| 8472
| sg-xxx (nodos-rancher)
| Entrante

| Regla TCP personalizada
| TCP
| 30000-32767
| 0.0.0.0/0 y ::/0
| Entrante

| Regla UDP personalizada
| UDP
| 30000-32767
| 0.0.0.0/0 y ::/0
| Entrante

| Todo el tráfico
| Todas
| Todas
| 0.0.0.0/0 y ::/0
| Saliente
|===

[#_opening_suse_linux_ports]
=== Apertura de Puertos de SUSE Linux

SUSE Linux puede tener un firewall que bloquea todos los puertos por defecto. Para abrir los puertos necesarios para añadir el host a un clúster personalizado,

[tabs]
======
SLES 15 / openSUSE Leap 15::
+
--
. Conectaos por SSH a la instancia.
. Iniciar YaST en modo de texto:
+
----
 sudo yast2
----

. Navegar a *Seguridad y Usuarios* > *Firewall* > *Zonas:pública* > *Puertos*. Para navegar dentro de la interfaz, seguid estas https://doc.opensuse.org/documentation/leap/reference/html/book-reference/cha-yast-text.html#sec-yast-cli-navigate[instrucciones].
. Para abrir los puertos requeridos, introducidlos en los campos *Puertos TCP* y *Puertos UDP*. En este ejemplo, los puertos 9796 y 10250 también están abiertos para la monitorización. Los campos resultantes deberían parecerse a lo siguiente:
+
[,yaml]
----
 TCP Ports
 22, 80, 443, 2376, 2379, 2380, 6443, 9099, 9796, 10250, 10254, 30000-32767
 UDP Ports
 8472, 30000-32767
----

. Cuando todos los puertos requeridos estén introducidos, seleccionad *Aceptar*.
--

SLES 12 / openSUSE Leap 42::
+
--
. Conectaos por SSH a la instancia.
. Editad /`etc/sysconfig/SuSEfirewall2` y abrid los puertos requeridos. En este ejemplo, los puertos 9796 y 10250 también están abiertos para la monitorización:
+
----
 FW_SERVICES_EXT_TCP="22 80 443 2376 2379 2380 6443 9099 9796 10250 10254 30000:32767"
 FW_SERVICES_EXT_UDP="8472 30000:32767"
 FW_ROUTE=yes
----

. Reiniciar el firewall con los nuevos puertos:
+
----
 SuSEfirewall2
----
--
======

*Resultado:* El nodo tiene los puertos abiertos requeridos para ser añadido a un clúster personalizado.
