= Google Kubernetes Engineクラスターに{rancher-product-name}をインストールする
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-09
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke.adoc 
:product-path: installation-and-upgrade/hosted-kubernetes/rancher-on-gke.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
endif::[]

このセクションでは、Google Kubernetes Engineを使用してRancherをインストールする方法を学びます。

すでにGKE Kubernetesクラスターをお持ちの場合は、<<_7_install_an_ingress,イングレスのインストールに関するステップにスキップしてください。>>次に、{xref-install-rancher}#_install_the_rancher_helm_chart[このページ]の指示に従ってRancher Helmチャートをインストールします。

[#_prerequisites]
== 前提条件

* Googleアカウントが必要です。
* Google Cloudの請求アカウントが必要です。Google Cloud Consoleを使用してCloud Billingアカウントを管理できます。Cloud Consoleに関する詳細情報については、 https://support.google.com/cloud/answer/3465889?hl=en&ref_topic=3340599[コンソールの一般ガイド]をご覧ください。
* 使用中のIPアドレスが少なくとも1つ、CPUが少なくとも2つのクラウドクォータが必要です。Rancherサーバーのハードウェア要件に関する詳細は、{xref-install-reqs}[このセクション]を参照してください。

[#_1_enable_the_kubernetes_engine_api]
== 1.Kubernetes Engine APIを有効にする

Kubernetes Engine APIを有効にするための手順は以下の通りです：

. Google Cloud Consoleの https://console.cloud.google.com/projectselector/kubernetes?_ga=2.169595943.767329331.1617810440-856599067.1617343886[Kubernetes Engineページ]にアクセスします。
. プロジェクトを作成または選択します。
. プロジェクトを開き、そのプロジェクトのKubernetes Engine APIを有効にします。APIと関連サービスが有効になるまで待ちます。これには数分かかる場合があります。
. Cloudプロジェクトの請求が有効になっていることを確認してください。プロジェクトの請求を有効にする方法については、 https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project[Google Cloudのドキュメント]を参照してください。

[#_2_open_the_cloud_shell]
== 2.Cloud Shellを開く

Cloud Shellは、Google Cloud上でホストされているリソースを管理するためのシェル環境です。Cloud Shellには、`gcloud`コマンドラインツールとkubectlコマンドラインツールがプリインストールされています。`gcloud`ツールはGoogle Cloudの主要なコマンドラインインターフェースを提供し、`kubectl`はKubernetesクラスターに対してコマンドを実行するための主要なコマンドラインインターフェースを提供します。

以下のセクションでは、Google Cloud Consoleまたはローカルワークステーションからクラウドシェルを起動する方法について説明します。

[#_cloud_shell]
=== クラウドシェル

https://console.cloud.google.com[Google Cloud Console,]からシェルを起動するには、コンソールの右上隅に移動し、ターミナルボタンをクリックします。ボタンにカーソルを合わせると、*Cloud Shellを有効にする*と表示されます。

[#_local_shell]
=== ローカルシェル

`gcloud`と`kubectl`をインストールするには、次の手順を実行します：

. https://cloud.google.com/sdk/docs/install[これらの手順]に従ってCloud SDKをインストールします。Cloud SDKには`gcloud`コマンドラインツールが含まれています。手順はOSによって異なります。
. Cloud SDKをインストールした後、次のコマンドを実行して`kubectl`コマンドラインツールをインストールします：
+
----
 gcloud components install kubectl
----
+
後のステップで、`kubectl`は新しいGKEクラスターを使用するように設定されます。

. https://helm.sh/docs/intro/install/[Helm 3がまだインストールされていない場合は、インストールしてください。]
. https://github.com/helm/community/blob/master/hips/hip-0006.md[OCI イメージのための Helm の実験的サポート] を `HELM_EXPERIMENTAL_OCI` 変数で有効にします。次の行を`~/.bashrc`に追加します（macOSでは`~/.bash_profile`、またはシェルが環境変数を保存する場所に追加します）：
+
----
 export HELM_EXPERIMENTAL_OCI=1
----

. 次のコマンドを実行して、更新された`.bashrc`ファイルを読み込みます：
+
----
 source ~/.bashrc
----
+
macOSを使用している場合は、このコマンドを使用します：
+
----
 source ~/.bash_profile
----

[#_3_configure_the_gcloud_cli]
== 3.gcloud CLIを設定します

次のいずれかの方法を使用して、デフォルトの gcloud 設定をセットアップします：

* gcloud init を使用する場合、デフォルト設定の手順が案内されます。
* gcloud configを使用して、プロジェクト ID、ゾーン、およびリージョンを個別に設定します。

[tabs]
======
gcloud initを使用します。::
+
--
. gcloud initを実行し、指示に従ってください：
+
----
  gcloud init
----
+
リモートサーバーで SSH を使用している場合は、コマンドがブラウザを起動しないように --console-only フラグを使用してください：
+
----
  gcloud init --console-only
----

. 指示に従って、gcloud があなたの Google Cloud アカウントを使用するための承認を行い、作成した新しいプロジェクトを選択してください。
--

gcloud configを使用します。::
+
--
--
======

[#_4_confirm_that_gcloud_is_configured_correctly]
== 4.gcloud が正しく構成されていることを確認します。

次のスクリプトを実行します。

----
gcloud config list
----

出力は次のようになります：

----
[compute]
region = us-west1 # Your chosen region
zone = us-west1-b # Your chosen zone
[core]
account = <Your email>
disable_usage_reporting = True
project = <Your project ID>

Your active configuration is: [default]
----

[#_5_create_a_gke_cluster]
== 5.GKE クラスターを作成します。

次のコマンドは、3 ノードのクラスターを作成します。

`cluster-name` を新しいクラスターの名前に置き換えてください。

Kubernetesのバージョンを選択する際は、最初に https://rancher.com/support-matrix/[サポートマトリックス]を確認して、Rancherのバージョンに対して検証された最高のKubernetesバージョンを見つけてください。

RancherでGKEクラスターを正常に作成するには、GKEがスタンダードモードである必要があります。GKEには、Kubernetesクラスターを作成する際に、オートパイロットモードとスタンダードモードの2つの操作モードがあります。オートパイロットモードのクラスター構成には、kube-systemネームスペースの編集に制限があります。ただし、Rancherはインストール中にkube-systemネームスペースにリソースを作成する必要があります。その結果、Autopilot モードで作成された GKE クラスターに Rancher をインストールすることはできません。GKEオートパイロットモードとスタンダードモードの違いについての詳細は、 https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison[GKEオートパイロットとスタンダードの比較を参照してください。]

----
gcloud container clusters create cluster-name --num-nodes=3 --cluster-version=<VERSION>
----

[#_6_get_authentication_credentials]
== 6.認証情報を取得します。

クラスターを作成した後、クラスターと対話するための認証情報を取得する必要があります：

----
gcloud container clusters get-credentials cluster-name
----

このコマンドは、`kubectl` を作成したクラスターを使用するように構成します。

[#_7_install_an_ingress]
== 7.Ingressをインストールする

クラスターには、Rancherがクラスターの外部からアクセスできるようにするためにIngressが必要です。Ingressをインストールするには、パブリックIPアドレスを割り当てる必要があります。十分なクォータがあることを確認してください。そうでないと、IPアドレスの割り当てに失敗します。パブリックIPアドレスの制限は、サブスクリプションごとに地域レベルで適用されます。GCP が提供するマネージドイングレスコントローラーや、Traefik のようなサードパーティのイングレスコントローラーを使用できます。

[WARNING]
====
マネージドイングレスコントローラーがすでに使用されている場合、Traefik のようなサードパーティのイングレスコントローラーをインストールすることは推奨されません。
====

[WARNING]
====
**Ingress-NGINX EOL:**コミュニティの`ingress-nginx`コントローラーは2026年3月にサービス終了となります。このページでは、Rancher環境に推奨される移行パスであるTraefikを使用しています。
====

Traefikには、ネイティブのIngress NGINXプロバイダーが含まれています。これにより、既存のIngressオブジェクトを再記述することなくNGINXから移行でき、Traefikは`nginx.ingress.kubernetes.io`アノテーションを自動的に解釈します。すでに`ingress-nginx`を使用しているクラスターをアップグレードする場合は、詳細についてはこの https://doc.traefik.io/traefik/migrate/nginx-to-traefik/[ガイド]に従ってください。

Traefikをインストールするには、 https://apps.rancher.io/applications/traefik-proxy[Rancher Prime Application Collection]のTraefikアプリケーションを使用することを強くお勧めします。Rancher Managerと統合するための https://docs.apps.rancher.io/howto-guides/integrate-with-rancher-manager[ドキュメントを確認してください]。


[#_8_get_load_balancer_ip]
== 8.ロードバランサーIPを取得する

ロードバランサーのアドレスを取得するには、次のコマンドを実行します：

----
kubectl get service traefik --namespace=traefik
----

結果は次のようになります：

----
NAME                       TYPE           CLUSTER-IP     EXTERNAL-IP                                                              PORT(S)
 AGE
traefik  LoadBalancer   10.0.116.18    40.31.180.83   80:31229/TCP,443:31050/TCP 27m
----

`EXTERNAL-IP`を保存します。

[#_9_set_up_dns]
== 9.DNSを設定します。

Rancherサーバーへの外部トラフィックは、作成したロードバランサーに向ける必要があります。

保存した外部IPを指すDNSを設定します。このDNSはRancherサーバーのURLとして使用されます。

DNSを設定するための有効な方法は多数あります。ヘルプが必要な場合は、 https://cloud.google.com/dns/docs/records[DNS レコードの管理に関する Google Cloud ドキュメントを参照してください。]

[#_10_install_the_rancher_helm_chart]
== 10.Rancher Helm チャートをインストールします。

次に、{xref-install-rancher}#_install_the_rancher_helm_chart[このページ]の指示に従って Rancher Helm チャートをインストールします。Helm の指示は、任意の Kubernetes ディストリビューションに Rancher をインストールする際に同じです。

Rancher をインストールする際には、前のステップで得た DNS 名を Rancher サーバーの URL として使用します。それは Helm オプションとして渡すことができます。例えば、DNS 名が `rancher.my.org` の場合、オプション `--set hostname=rancher.my.org` を使用して Helmインストールコマンドを実行できます。

このセットアップの上にRancherをインストールする際には、Rancherのingressリソースで使用するingressコントローラーの名前を設定する必要があります。

----
--set ingress.ingressClassName=traefik
----

選択した証明書オプションの Helm インストールコマンドについては、{xref-install-rancher}#_5_install_rancher_with_helm_and_your_chosen_certificate_option[こちら]を参照してください。

Rancher v2.7.5では、VPCネイティブクラスター モードを有効にせずにクラスターでデフォルトのGKE ingressを使用する予定の場合、次のフラグを設定する必要があります。

----
--set service.type=NodePort
----

これは、セットアップと、`cattle-system/rancher`のデフォルトタイプであるClusterIPとの互換性の問題があるため、必要です。
