= Helm Chart 选项
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/helm-chart-options.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/helm-chart-options.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-configure-alertmanager: xref:observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-configure-alertmanager: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
endif::[]

[#_configuring_resource_limits_and_requests]
== 配置资源限制和请求

在安装 `rancher-monitoring` 时可以配置资源请求和限制。

默认值在 https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/values.yaml[values.yaml] 中的 `rancher-monitoring` Helm 图表中。

下表中的默认值是所需的最低资源限制和请求。

|===
| 资源名 | 内存限制 | 处理器限制 | 内存请求 | 处理器请求

| alertmanager
| 500Mi
| 1000m
| 100Mi
| 100m

| grafana
| 200Mi
| 200m
| 100Mi
| 100m

| kube-state-metrics subchart
| 200Mi
| 100m
| 130Mi
| 100m

| prometheus-node-exporter 子图表
| 50Mi
| 200m
| 30Mi
| 100m

| prometheusOperator
| 500Mi
| 200m
| 100Mi
| 100m

| prometheus
| 2500Mi
| 1000m
| 1750Mi
| 750m

| *Total*
| *3950Mi*
| *2700m*
| *2210Mi*
| *1250m*
|===

建议至少使用 50Gi 存储。

[#_trusted_ca_for_notifiers]
== 通知者的受信任 CA

如果您需要将受信任的 CA 添加到通知者，请按照以下步骤操作：

. 创建 `cattle-monitoring-system` 名称空间。
. 将您的受信任 CA 密钥添加到 `cattle-monitoring-system` 名称空间。
. 部署或升级 `rancher-monitoring` Helm 图表。在图表选项中引用 menu:告警[附加密钥] 中的密钥。

*结果：*默认的 Alertmanager 自定义资源将能够访问您的受信任 CA。

[#_additional_scrape_configurations]
== 附加抓取配置

如果您想要的抓取配置目前无法通过 ServiceMonitor 或 PodMonitor 指定，您可以在部署或升级 `additionalScrapeConfigSecret` 时提供一个 `rancher-monitoring`。

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config[抓取配置部分] 指定了一组目标和描述如何抓取它们的参数。一般情况下，一个抓取配置指定一个单独的作业。

一个可能使用此功能的示例是与 Istio 一起使用。有关更多信息，请参见 {xref-selectors-and-scrape-configurations}[本节。]

[#_configuring_applications_packaged_within_monitoring_v2]
== 配置打包在监控 v2 中的应用程序

我们使用监控 v2 部署 kube-state-metrics 和 node-exporter。节点导出器作为 DaemonSets 部署。这些实体通过监控 v2 Helm 图表、values.yaml 部署为子图表。

我们还部署了 Grafana，它不受 Prometheus 管理。

许多值在顶层图表中并未暴露。但是，您可以向顶层图表添加值，以覆盖子图表中存在的值。

[#_increase_the_replicas_of_alertmanager]
=== 增加 Alertmanager 的副本数

作为图表部署选项的一部分，您可以选择增加部署到集群中的 Alertmanager 的副本数。所有副本都可以使用相同的基础 Alertmanager 配置密钥进行管理。有关 Alertmanager 配置密钥的更多信息，请参阅 {xref-configure-alertmanager}#_multiple_alertmanager_replicas[本节。]

[#_configuring_the_namespace_for_a_persistent_grafana_dashboard]
=== 为持久 Grafana 仪表板配置名称空间。

要指定您希望 Grafana 监视所有命名空间中的 ConfigMaps，请在 `rancher-monitoring` Helm 图表中设置此值：

----
grafana.sidecar.dashboards.searchNamespace=ALL
----

请注意，监控图表暴露的 RBAC 角色用于添加 Grafana 仪表板仍然限制用户在 `grafana.dashboards.namespace` 中定义的命名空间内添加仪表板的权限，默认值为 `cattle-dashboards`。
