= ConfigMaps
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc 
:product-path: cluster-admin/kubernetes-resources/configmaps.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
endif::[]

Während die meisten Arten von Kubernetes-Geheimnissen sensible Informationen speichern, speichern https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/[ConfigMaps] allgemeine Konfigurationsinformationen, wie eine Gruppe von Konfigurationsdateien. Da ConfigMaps keine sensiblen Informationen speichern, können sie automatisch aktualisiert werden und erfordern daher nicht, dass ihre Container nach der Aktualisierung neu gestartet werden (im Gegensatz zu den meisten Geheimnisarten, die manuelle Updates und einen Containerneustart benötigen, um wirksam zu werden).

ConfigMaps akzeptieren Schlüssel-Wert-Paare in gängigen Stringformaten, wie Konfigurationsdateien oder JSON-Blobs. Nachdem Sie eine ConfigMap hochgeladen haben, kann jede Arbeitslast sie entweder als Umgebungsvariable oder als Volume-Mount referenzieren.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, das die Arbeitslast hat, die auf eine ConfigMap verweisen soll, und klicken Sie auf *Erforschen*.
. Klicken Sie in der linken Navigationsleiste auf menu:Weitere Ressourcen[Kernel> ConfigMaps].
. Klicken Sie auf *Erstellen*.
. Geben Sie einen *Name* für die ConfigMap ein.
+

[NOTE]
====
Kubernetes klassifiziert ConfigMaps als https://kubernetes.io/docs/concepts/configuration/secret/[Geheimnisse], und keine zwei Geheimnisse in einem Projekt oder Namespace können denselben Namen haben. Um Konflikte zu vermeiden, müssen Ihre ConfigMaps daher einen eindeutigen Namen unter den anderen Zertifikaten, Registries und Geheimnissen in Ihrem Arbeitsbereich haben.
====


. Wählen Sie den *Namespace* aus, zu dem Sie die ConfigMap hinzufügen möchten.
. Fügen Sie im Tab *Daten* ein Schlüssel-Wert-Paar zu Ihrer ConfigMap hinzu. Fügen Sie so viele Werte hinzu, wie Sie benötigen.  Sie können mehrere Schlüssel-Wert-Paare zur ConfigMap hinzufügen, indem Sie kopieren und einfügen. Alternativ können Sie *Aus Datei lesen* verwenden, um die Daten hinzuzufügen. Hinweis: Wenn Sie sensible Daten speichern müssen, {xref-secrets}[verwenden Sie ein Geheimnis], nicht eine ConfigMap.
. Klicken Sie auf *Erstellen*.

*Ergebnis:* Ihre ConfigMap wird dem Namespace hinzugefügt. Sie können sie in der Rancher-Benutzeroberfläche im menu:Ressourcen[ConfigMaps]-Ansicht anzeigen.

[#_whats_next]
== Was kommt als Nächstes?

Jetzt, da Sie eine ConfigMap zu einem Namespace hinzugefügt haben, können Sie sie zu einer Arbeitslast hinzufügen, die Sie aus dem Ursprungs-Namespace bereitstellen. Sie können die ConfigMap verwenden, um Informationen anzugeben, die Ihre Anwendung konsumieren soll, wie zum Beispiel:

* Anwendungsumgebungsvariablen.
* Parameter für einen Volume-Mount, der an die Arbeitslast angebunden ist.

Für weitere Informationen zum Hinzufügen von ConfigMaps zu einer Arbeitslast, siehe {xref-deploy-workloads}[Bereitstellen von Arbeitslasten].
