= 復元 {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-04
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher.adoc 
:product-path: rancher-admin/back-up-restore-and-disaster-recovery/restore.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:url-continuous-delivery-gitreo-add: https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/how-tos-for-users/gitrepo-add.html#_backing_up_and_restoring
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
:xref-rancher-restore-config: xref:rancher-admin/back-up-restore-and-disaster-recovery/configuration/restore.adoc
:xref-back-restore-example-configs: xref:rancher-admin/back-up-restore-and-disaster-recovery/configuration/examples.adoc
:xref-rancher-rollback: xref:installation-and-upgrade/rollbacks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-continuous-delivery-gitreo-add: https://fleet.rancher.io/{fleet-docs-version}/how-tos-for-users/gitrepo-add
:xref-migrate-cluster: xref:how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster.adoc
:xref-rancher-restore-config: xref:reference-guides/backup-restore-configuration/restore-configuration.adoc
:xref-back-restore-example-configs: xref:reference-guides/backup-restore-configuration/examples.adoc
:xref-rancher-rollback: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rollbacks.adoc
endif::[]

このページでは、Rancherを使用して復元を実行する方法について説明します。

次の場合は、このページの指示に従ってください：

* 実行中のRancherインスタンスがバックアップが作成されたときと同じバージョンである。
* アップストリーム（ローカルクラスタ）は、バックアップが作成された場所と同じである。

[NOTE]
.重要
====

同じセットアップでRancherを復元する際、オペレーターは復元が開始されるとRancherのデプロイメントをスケールダウンし、復元が完了するとデプロイメントを再度スケールアップします。復元中はRancherは利用できません。
====


[NOTE]
.Fleetユーザーへの警告
====
Fleetワークロードを実行しているRancherセットアップを復元する際には、Kubernetes APIサーバーの可用性と一時停止中のGitReposの取り扱いを考慮する必要があります。詳細については、{url-continuous-delivery-gitreo-add}[{fleet-product-name} ドキュメント]を参照してください。
====

[TIP]
====

* これらの手順に従って{xref-migrate-cluster}[Rancherを移行]してください。
* アップグレード後にRancherを以前のバージョンに復元する必要がある場合は、{xref-rancher-rollback}[ロールバックドキュメント]を参照してください。
====


[#_create_the_restore_custom_resource]
== 復元カスタムリソースを作成する

復元は、復元カスタムリソースを作成することで実行されます。

. 左上隅で、*☰ > クラスター管理*をクリックします。
. *クラスター*ページで、`local`クラスターに移動し、*探索*をクリックします。`local`クラスターはRancherサーバーを実行しています。
. 左側のナビゲーションバーで、menu:Rancherバックアップ[復元]をクリックします。
. ［*作成*］をクリックします。
. フォームまたはYAMLを使用して復元を作成します。 フォームを使用して復元リソースを作成するには、{xref-rancher-restore-config}[設定リファレンス]および{xref-back-restore-example-configs}[例]を参照してください。
. YAMLエディタを使用する場合は、menu:作成[YAMLから作成]をクリックできます。復元YAMLを入力してください。
+
[,yaml]
----
 apiVersion: resources.cattle.io/v1
 kind: Restore
 metadata:
   name: restore-migration
 spec:
   backupFilename: backup-b0450532-cee1-4aa1-a881-f5f48a007b1c-2020-09-15T07-27-09Z.tar.gz
   encryptionConfigSecretName: encryptionconfig
   storageLocation:
     s3:
       credentialSecretName: s3-creds
       credentialSecretNamespace: default
       bucketName: rancher-backups
       folder: rancher
       region: us-west-2
       endpoint: s3.us-west-2.amazonaws.com
----
+
復元の設定に関するヘルプについては、{xref-rancher-restore-config}[設定リファレンス]および{xref-back-restore-example-configs}[例]を参照してください。

. ［*作成*］をクリックします。

*結果:*Rancherオペレーターは、復元中にRancherデプロイメントをスケールダウンし、復元が完了すると再びスケールアップします。リソースは以下の順序で復元されます：

. カスタムリソース定義（CRD）
. クラスター範囲のリソース
. ネームスペースリソース

[#_logs]
== ログ

復元の進行状況を確認するには、オペレーターのログを確認できます。このコマンドを実行してログを追跡してください：

----
kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f
----

[#_cleanup]
== クリーンアップ

kubectlで復元リソースを作成した場合、将来の復元との名前の競合を防ぐためにリソースを削除してください。

[#_known_issues]
== 既知の問題

バックアップを復元した後、Rancherのログに以下のようなエラーが表示されることがあります：

----
2021/10/05 21:30:45 [ERROR] error syncing 'c-89d82/m-4067aa68dd78': handler rke-worker-upgrader: clusters.management.cattle.io "c-89d82" not found, requeuing
----

これは、復元されたリソースの1つにファイナライザーがあり、関連するリソースが削除されたため、ハンドラーがそれを見つけられないために発生します。

エラーを解消するには、エラーを引き起こしているリソースを見つけて削除する必要があります。詳細情報は https://github.com/rancher/rancher/issues/35050#issuecomment-937968556[こちら]にあります。
