= Utilitário kubectl
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cli-with-rancher/kubectl-utility.adoc 
:product-path: rancher-admin/cli/kubectl.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
endif::[]

[#_kubectl]
== kubectl

Interaja com o Rancher usando kubectl.

[#_kubectl_utility]
=== Utilitário kubectl

Instale o `kubectl` utilitário. Veja https://kubernetes.io/docs/tasks/tools/install-kubectl/[instalar kubectl].

Configure o kubectl visitando seu cluster na interface web do Rancher, clicando em `Kubeconfig`, copiando o conteúdo e colocando-o no seu arquivo `~/.kube/config`.

Execute `kubectl cluster-info` ou `kubectl get pods` com sucesso.

[#_authentication_with_kubectl_and_kubeconfig_tokens_with_ttl]
=== Autenticação com kubectl e tokens kubeconfig com TTL

_Requisitos_

Se os administradores tiverem xref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[desativado a geração de token kubeconfig], o arquivo kubeconfig requer que o {xref-rancher-cli}[Rancher CLI] esteja presente em seu caminho quando você executar `kubectl`. Caso contrário, você verá um erro como:
`Unable to connect to the server: getting credentials: exec: exec: "rancher": executable file not found in $PATH`.

Esse recurso permite que o kubectl se autentique com o servidor Rancher e obtenha um novo token kubeconfig quando necessário. Os seguintes provedores de autenticação são atualmente suportados:

. Local
. Active Directory (apenas LDAP)
. FreeIPA
. OpenLDAP
. Provedores SAML: Ping, Okta, ADFS, Keycloak, Shibboleth
. Azure AD

Quando você executa o kubectl pela primeira vez, por exemplo, `kubectl get pods`, você é solicitado a escolher um provedor de autenticação e fazer login no servidor Rancher. O token kubeconfig é armazenado em cache no caminho onde você executa o kubectl em `./.cache/token`. Esse token é válido até xref:api/api-tokens.adoc#_disable_tokens_in_generated_kubeconfigs[expirar], ou xref:api/api-tokens.adoc#_deleting_tokens[ser excluído do servidor Rancher]. Após a expiração, você deve fazer login novamente no servidor Rancher para executar o comando `kubectl get pods`.
