= 名前空間でIstioを有効にする
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-namespace.adoc 
:product-path: observability/istio/guides/enable-istio-in-namespace.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-sidecar: xref:observability/istio/guides/use-istio-sidecar.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-sidecar: xref:how-to-guides/advanced-user-guides/istio-setup-guide/use-istio-sidecar.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio]はRancher v2.12.0以降廃止されました。セキュリティを強化するために、 https://apps.rancher.io[SUSE Application Collection]のIstioビルドに切り替えてください（SUSE Rancher Primeサブスクリプションに含まれています）。
詳細情報は https://forums.suse.com/t/deprecation-of-rancher-istio/45043[この発表]にあります。
====

Istioによって追跡または制御される各名前空間で手動でIstioを有効にする必要があります。名前空間でIstioが有効になると、Envoyサイドカープロキシがその名前空間にデプロイされるすべての新しいワークロードに自動的に注入されます。

この名前空間の設定は、その名前空間内の新しいワークロードにのみ影響します。既存のワークロードは、サイドカーの自動注入を利用するために再デプロイする必要があります。

[NOTE]
.前提条件:
====

名前空間でIstioを有効にするには、クラスターにIstioがインストールされている必要があります。
====


. *☰ > クラスター管理*をクリックします。
. 作成したクラスターに移動し、*探索*をクリックします。
. menu:クラスター[プロジェクト/名前空間]をクリックします。
. Istioを有効にしたい名前空間に移動し、*⋮  > Istio自動注入を有効にする*をクリックします。または、名前空間をクリックし、名前空間の詳細ページで*⋮  > Istio自動注入を有効にする*をクリックします。

*結果:*名前空間には現在、ラベル`istio-injection=enabled`があります。この名前空間にデプロイされたすべての新しいワークロードには、デフォルトでIstioサイドカーが注入されます。

[#_verifying_that_automatic_istio_sidecar_injection_is_enabled]
== 自動Istioサイドカー注入が有効であることを確認する

Istioが有効であることを確認するには、名前空間にhello-worldワークロードをデプロイします。ワークロードに移動し、ポッド名をクリックします。*コンテナ*セクションで、`istio-proxy`コンテナが表示されるはずです。

[#_excluding_workloads_from_being_injected_with_the_istio_sidecar]
== Istioサイドカーの注入を除外するワークロード

Istioサイドカーの注入を除外する必要があるワークロードには、次のアノテーションを使用してください：

----
sidecar.istio.io/inject: “false”
----

ワークロードにアノテーションを追加するには、

. *☰ > クラスター管理*をクリックします。
. 作成したクラスターに移動し、*探索*をクリックします。
. *ワークロード*をクリックします。
. サイドカーを持たないワークロードに移動し、yamlとして編集します。
. 次のキーと値`sidecar.istio.io/inject: false`をワークロードのアノテーションとして追加します。
. ［*保存*］をクリックします。

*結果:*Istioサイドカーはワークロードに注入されません。

[NOTE]
====

デプロイしたジョブが完了しない問題が発生している場合は、提供された手順を使用してポッドにこのアノテーションを追加する必要があります。Istioサイドカーは無期限に実行されるため、ジョブはそのタスクが完了しても完了とは見なされません。
====

[#__xref_istio_sidecar_next_add_deployments_with_the_istio_sidecar]
== {xref-istio-sidecar}[次へ：Istioサイドカーを持つデプロイメントを追加]
