= Istio からのトラフィックを生成および表示する
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/generate-and-view-traffic.adoc 
:product-path: observability/istio/guides/generate-and-view-traffic.adoc
ifeval::["{build-type}" != "community"]
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio]はRancher v2.12.0以降廃止されました。セキュリティを強化するために、 https://apps.rancher.io[SUSE Application Collection]のIstioビルドに切り替えてください（SUSE Rancher Primeサブスクリプションに含まれています）。
詳細情報は https://forums.suse.com/t/deprecation-of-rancher-istio/45043[この発表]にあります。
====

[#_the_kiali_traffic_graph]
== Kiali のトラフィックグラフ

Istio 概要ページには Kiali ダッシュボードへのリンクが提供されています。Kiali ダッシュボードから、各ネームスペースのグラフを表示できます。Kiali グラフは、Istio サービスメッシュのトポロジーを視覚化するための強力な方法を提供します。どのサービスが互いに通信しているかを示します。

[#_prerequisites]
== 前提条件

グラフにトラフィックが表示されるようにするには、クラスターに Prometheus がインストールされていることを確認してください。`Rancher-istio` は Kiali をインストールし、デフォルトで `rancher-monitoring` チャートと連携するように設定します。`rancher-monitoring` を使用するか、自分の監視ソリューションをインストールできます。

さらに、Istio インストールバージョン `103.1.0+up1.19.6` 以降では、Kiali は認証戦略のためにトークン値を使用します。トークンを生成または取得しようとしている場合（例：ログイン用）、Rancher の Kiali サービスアカウントの名前は `kiali` であることに注意してください。詳細については、 https://kiali.io/docs/faq/authentication/[Kiali トークン認証 FAQ] を参照してください。

オプション:データスクレイピングが発生するネームスペースを設定するには、{xref-selectors-and-scrape-configurations}[セレクターとスクレイプ設定] に記載されている Helm チャートオプションを設定します。

[#_traffic_visualization]
== トラフィックの視覚化

トラフィックグラフを見るには、以下の手順に従ってください：

. Istio がインストールされているクラスターで、左側のナビゲーションバーから *Istio* をクリックします。
. *Kiali* リンクをクリックします。
. サイドナビの *グラフ* をクリックします。
. *ネームスペース* ドロップダウンでネームスペースを変更して、各ネームスペースのトラフィックを表示します。

BookInfo アプリの URL を何度か更新すると、Kiali グラフに `v1` と `v3` のトラフィックを示す緑の矢印が表示されるはずです。グラフの右側にあるコントロールパネルでは、直近のトラフィックを何分間表示するかなど、詳細を設定できます。

追加のツールや可視化については、*Monitoring* *Overview* ページから Grafana および Prometheus ダッシュボードにアクセスできます。
