= Rotation abgelaufener Webhook-Zertifikate
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/expired-webhook-certificate-rotation.adoc 
:product-path: security/rancher-webhook/expired-webhook-certificate-rotation.adoc

Bei Rancher-Versionen, in denen `rancher-webhook` installiert ist, haben bestimmte Versionen Zertifikate erstellt, die nach einem Jahr ablaufen. Es wird notwendig sein, Ihr Webhook-Zertifikat auszutauschen, wenn das Zertifikat nicht erneuert wurde.

In Rancher v2.6.3 und höher werden die Rancher-Webhook-Bereitstellungen ihr TLS-Zertifikat automatisch erneuern, wenn es innerhalb von 30 oder weniger Tagen vor dem Ablaufdatum liegt. Wenn Sie v2.6.2 oder älter verwenden, gibt es zwei Methoden, um dieses Problem zu umgehen:

[#_1_users_with_cluster_access_run_the_following_commands]
== 1. Benutzer mit Clusterzugriff führen die folgenden Befehle aus:

----
kubectl delete secret -n cattle-system cattle-webhook-tls
kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io --ignore-not-found=true rancher.cattle.io
kubectl delete pod -n cattle-system -l app=rancher-webhook
----

[#_2_users_with_no_cluster_access_via_kubectl]
== 2. Benutzer ohne Clusterzugriff über `kubectl`:

. Löschen Sie das `cattle-webhook-tls` Secret im `cattle-system` Namespace im lokalen Cluster.
. Löschen Sie den `rancher.cattle.io` mutierenden Webhook.
. Löschen Sie das `rancher-webhook` Pod im `cattle-system` Namespace im lokalen Cluster.

[NOTE]
====

Das Problem mit dem Ablauf des Webhook-Zertifikats ist nicht spezifisch für `cattle-webhook-tls`, wie in den Beispielen aufgeführt. Sie werden Ihr abgelaufenes Zertifikat-Secret entsprechend ausfüllen.
====

