= EKSクラスター設定リファレンス
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-21
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/eks-cluster-configuration.adoc 
:product-path: cluster-deployment/hosted-kubernetes/eks/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
endif::[]

[#_account_access]
== アカウントアクセス

IAMポリシー用に取得した情報を使って、各ドロップダウンとフィールドを入力してください。

|===
| 設定 | 説明

| 地域
| ドロップダウンから、クラスターを構築するリージョンを選択してください。

| クラウド資格情報
| IAMポリシーのために作成したクラウドクレデンシャルを選択してください。Rancherでクラウドクレデンシャルを作成する方法の詳細については、{xref-cloud-credentials}[このページ]を参照してください。
|===

[#_service_role]
== サービスロール

https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html[サービスロール]を選択してください。

|===
| サービスロール | 説明

| 標準:Rancherが生成したサービスロール
| このロールを選択すると、Rancherはクラスターで使用するためのサービスロールを自動的に追加します。

| カスタム:既存のサービスロールから選択してください
| このロールを選択すると、RancherはAWS内で既に作成したサービスロールから選択できるようにします。AWSでカスタムサービスロールを作成する方法の詳細については、 https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html#create-service-linked-role[Amazonのドキュメント]を参照してください。
|===

[#_secrets_encryption]
== シークレット暗号化

オプション:秘密を暗号化するには、 https://docs.aws.amazon.com/kms/latest/developerguide/overview.html[AWSキー管理サービス（KMS）]で作成したキーを選択または入力してください。

[#_api_server_endpoint_access]
== APIサーバーエンドポイントアクセス

パブリック/プライベートAPIアクセスの構成は、高度なユースケースです。詳細については、EKSクラスターエンドポイントアクセス制御に関する https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html[ドキュメント]を参照してください。

[#_private_only_api_endpoints]
== プライベート専用APIエンドポイント

クラスターを作成する際にプライベートを有効にし、パブリックAPIエンドポイントアクセスを無効にすると、Rancherがクラスターに正常に接続するために追加の手順が必要です。この場合、Rancherにクラスターを登録するためのコマンドが記載されたポップアップが表示されます。クラスターがプロビジョニングされると、クラスターのKubernetes APIに接続できる場所で表示されたコマンドを実行できます。

この追加の手動ステップを回避する方法は2つあります：

* クラスター作成時に、プライベートおよびパブリックAPIエンドポイントアクセスの両方を持つクラスターを作成できます。クラスターが作成され、アクティブな状態になった後にパブリックアクセスを無効にすることができ、RancherはEKSクラスターと引き続き通信します。
* RancherがEKSクラスターと同じサブネットを共有することを確認できます。その後、セキュリティグループを使用してRancherがクラスターのAPIエンドポイントと通信できるようにします。この場合、クラスターを登録するためのコマンドは必要なく、Rancherはクラスターと通信できるようになります。セキュリティグループの設定に関する詳細情報は、 https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html[セキュリティグループのドキュメント]を参照してください。

[#_public_access_endpoints]
== パブリックアクセスエンドポイント

オプションで、明示的なCIDRブロックを介してパブリックエンドポイントへのアクセスを制限できます。

特定のCIDRブロックへのアクセスを制限する場合は、クラスターへのネットワーク通信を失わないようにプライベートアクセスも有効にすることをお勧めします。

プライベートアクセスを有効にするには、以下のいずれかが必要です：

* RancherのIPは許可されたCIDRブロックの一部でなければなりません。
* プライベートアクセスを有効にし、Rancherはクラスターと同じサブネットを共有し、クラスターへのネットワークアクセスを持つ必要があります。これはセキュリティグループで設定できます。

クラスターエンドポイントへのパブリックおよびプライベートアクセスに関する詳細情報は、 https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html[Amazon EKSのドキュメント]を参照してください。

[#_ipv6_dual_stack_networking]
== IPv6 / デュアルスタックネットワーキング

Rancherは、IPv6ネットワークルーティングを使用してAmazon EKSクラスターのプロビジョニングと管理をサポートしています。IPv6が有効になると、KubernetesポッドとサービスにIPv6アドレスが割り当てられます。ただし、基盤となるEC2ワーカーノードは*デュアルスタックモード*で動作し（IPv4およびIPv6アドレスの両方を受信します）。このデュアルスタックアーキテクチャにより、ノードはIPv4を介してAWS APIおよびKubernetesコントロールプレーンと通信し、アプリケーションワークロードはIPv6を介して通信できることが保証されます。

Rancher UIからデュアルスタッククラスターをプロビジョニングするには：

. クラスター作成中に、*Networking*セクションを開きます。
. *IP Family*の下で、*IPv6*ラジオボタンを選択します。
+
[NOTE]
====
IPファミリーを変更すると、フォームで行った現在のサブネット選択がクリアされます。
====

. *VPCs and Subnets*の下で、*新しいVPCとサブネットを自動的に作成する*か、*既存のサブネットから選択する*のいずれかを選択します。
+
[WARNING]
.カスタムVPCに関する警告 
====
既存のサブネットを選択する場合、*必ず*デュアルスタックサブネットを選択する必要があります。選択したサブネットには、IPv4 CIDRブロックとIPv6 CIDRブロックの両方が必要です。IPv6専用のサブネットはサポートされていません。
====

. クラスター構成の残りの部分（ノードグループなど）を完了します。
. ［*作成*］をクリックします。

[IMPORTANT]
====
IPファミリー設定は*不変*です。EKSクラスターが作成された後、IPv4クラスターをIPv6に変換することも、IPv6クラスターをIPv4に変換することもできません。
====

[#_importing_existing_ipv6_clusters]
== 既存のIPv6クラスターのインポート

Rancherは、Rancherの外部でIPv6ネットワーキングで構成された既存のAmazon EKSクラスターの登録（インポート）を完全にサポートしています（例：TerraformやAWSコンソールを介して）。

既存のEKSクラスターを登録する際：

. 標準のクラスター登録プロセスに従います（*クラスター管理 > クラスターの追加 > 一般*）。
. RancherはAWS EKS APIにクエリを送信して、クラスターのアップストリーム状態を読み取ります。
. Rancherは、クラスターがIPv6でプロビジョニングされたかどうかを自動的に検出します。

IPv6クラスターを構成する際には、いくつかの自動化された動作と厳格な要件が適用されます：

* *サービスCIDR：*AWSは固定IPv6範囲からサービスCIDRを自動的に割り当てます（`fd00::/108`）。IPv6クラスターのサービスCIDRをカスタマイズすることはできません。
* *OIDCプロバイダー（IRSA）要件:*IPv6クラスターでは、Amazon VPC CNIプラグインは、Elastic Network Interfaces（ENI）にIPv6プレフィックスを割り当てるためにIAM権限を厳格に要求します。この認証は、サービスアカウントのためのIAMロール（IRSA）を介して処理されます。したがって、IPv6クラスターをプロビジョニングする際には、*IAM OIDCプロバイダーは必須であり、Rancherによって自動的に有効化されます*。それがないと、ポッドはIPアドレスを取得できません。

[#_eksclusterconfig_reference_example_ipv6]
== EKSクラスター設定の参照例（IPv6）

`eksclusterconfigs.eks.cattle.io`カスタムリソースを使用してプログラム的にEKSクラスターをデプロイする場合、`ipFamily`フィールドを`ipv6`に設定することでIPv6を有効にできます。

以下は、IPv6用に構成された最小限の`EKSClusterConfig`の例です。`ipFamily`が設定されており、AWSがIPv6モードで自動的に管理するため、`serviceCidr`のような標準IPv4フィールドは省略されていることに注意してください。

[,yaml]
----
apiVersion: eks.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: my-ipv6-cluster
  namespace: cluster-fleet-default
spec:
  amazonCredentialSecret: cattle-global-data/my-aws-credentials
  displayName: my-ipv6-cluster
  region: us-west-2
  imported: false
  kubernetesVersion: "1.33"
  ipFamily: "ipv6" # Enables Dual-Stack IPv6 networking. Triggers automatic OIDC creation.
  nodeGroups:
    - nodegroupName: initial-nodegroup
      desiredSize: 2
      maxSize: 3
      minSize: 1
      instanceType: t3.medium
      diskSize: 20
      requestSpotInstances: false
      version: "1.33"
  privateAccess: false
  publicAccess: true
  secretsEncryption: false
----

[#_subnet]
== サブネット

|===
| オプション | 説明

| 標準:Rancherが生成したVPCとサブネット
| クラスターをプロビジョニングする際、Rancherは3つのパブリックサブネットを持つ新しいVPCを生成します。

| カスタム:既存のVPCとサブネットから選択してください。
| クラスターをプロビジョニングする際、Rancherはあなたがすでに https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html[AWSで作成した] VPCとサブネットを使用するように制御プレーンとノードを構成します。
|===

詳細については、 https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html[クラスターVPCの考慮事項]に関するAWSのドキュメントを参照してください。前のステップでの選択に基づいて、以下の指示のセットのいずれかに従ってください。

[WARNING]
.カスタムVPCに関する警告 
====
`IPv6`をIPファミリーとして選択し、カスタムVPCを持っている場合、**デュアルスタックサブネットを選択する必要があります**。選択したサブネットは、**IPv4 CIDRブロックとIPv6 CIDRブロックの両方を持っている必要があります**。"IPv6専用"サブネットはEKSによってサポートされていません。EC2ワーカーノードは、クラスターに参加しAWSサービスと通信するために依然としてIPv4アドレスを必要とします。
====

* https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html[Amazon VPCとは？]
* https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html[VPCとサブネット]

[#_security_group]
== セキュリティグループ

Amazonのドキュメント：

* https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html[クラスターセキュリティグループの考慮事項]
* https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html[VPCのためのセキュリティグループ]
* https://docs.aws.amazon.com/vpc/latest/userguide/getting-started-ipv4.html#getting-started-create-security-group[セキュリティグループを作成する]

[#_logging]
== ログ記録

コントロールプレーンのログをAmazon CloudWatchに送信するように設定します。クラスターからCloudWatch Logsに送信されるログに対して、標準のCloudWatch Logsデータ取り込みおよびストレージコストが請求されます。

各ログタイプはKubernetesコントロールプレーンのコンポーネントに対応しています。これらのコンポーネントについて詳しくは、Kubernetesドキュメントの https://kubernetes.io/docs/concepts/overview/components/[Kubernetesコンポーネント]を参照してください。

EKSコントロールプレーンのログに関する詳細は、公式の https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html[ドキュメントを参照してください。]

[#_managed_node_groups]
== 管理ノードグループ

Amazon EKSの管理ノードグループは、Amazon EKS Kubernetesクラスターのノード（Amazon EC2インスタンス）のプロビジョニングとライフサイクル管理を自動化します。

ノードグループの動作と構成方法についての詳細は、 https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html[EKSドキュメントを参照してください。]

[#_user_provided_launch_templates]
=== ユーザー提供の起動テンプレート

ノードグループ内のEC2インスタンスを構成するために、独自の起動テンプレートIDとバージョンを提供できます。起動テンプレートを提供する場合、テンプレートの設定はRancherから構成できません。起動テンプレート内で、以下に示すすべての必須オプションを設定する必要があります。

また、起動テンプレートを提供する場合、テンプレートIDではなく、テンプレートバージョンのみを更新できます。新しいテンプレートIDを使用するには、新しい管理ノードグループを作成してください。

|===
| オプション | 説明 | 必須/オプション

| インスタンスタイプ
| プロビジョニングしているインスタンスのために、 https://aws.amazon.com/ec2/instance-types/[ハードウェア仕様]を選択してください。
| 必須

| イメージID
| ノード用のカスタムAMIを指定してください。EKSで使用されるカスタムAMIは、 https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/[適切に構成されている必要があります]。
| オプション

| ノードボリュームサイズ
| 起動テンプレートは、希望するサイズのEBSボリュームを指定する必要があります。
| 必須

| SSHキー
| ノードへのSSHアクセスを提供するためにインスタンスに追加されるキーです。
| オプション

| ユーザデータ
| https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data[MIMEマルチパート形式]のクラウドinitスクリプト
| オプション

| インスタンスリソースタグ
| ノードグループ内の各EC2インスタンスとそのボリュームにタグを付けてください。
| オプション
|===

[CAUTION]
====

カスタム起動テンプレートから作成されたノードグループは、新しいKubernetesバージョンに直接更新することはできません。適切なKubernetesバージョンの新しい起動テンプレートを作成し、ノードグループを新しいテンプレートに関連付ける必要があります。
====


[#_rancher_managed_launch_templates]
=== Rancher管理の起動テンプレート

起動テンプレートを指定しない場合、上記のオプションをRancher UIで構成でき、作成後にすべて更新できます。これらすべてのオプションを活用するために、Rancherがあなたのために起動テンプレートを作成し管理します。Rancherの各クラスターには1つのRancher管理の起動テンプレートがあり、指定された起動テンプレートを持たない各管理ノードグループには管理起動テンプレートの1つのバージョンがあります。この起動テンプレートの名前は、"rancher-managed-lt-"というプレフィックスの後にクラスターの表示名が続きます。さらに、Rancher管理の起動テンプレートには、"rancher-managed-template"というキーと"do-not-modify-or-delete"という値がタグ付けされ、Rancher管理であることを識別するのに役立ちます。この起動テンプレートとそのバージョンは、変更、削除、または他のクラスターや管理ノードグループで使用されないことが重要です。そうすることで、ノードグループが「劣化」し、破棄して再作成する必要が生じる可能性があります。

[#_custom_amis]
=== カスタムAMI

カスタムAMIを指定する場合、起動テンプレートまたはRancherで、イメージは https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/[適切に構成されている必要があり]、ノードを https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-custom-ami[起動するためのユーザーデータを提供しなければなりません]。これは高度な使用ケースと見なされ、要件を理解することが不可欠です。

カスタムAMIを含まない起動テンプレートを指定した場合、AmazonはKubernetesのバージョンと選択したリージョンに対して https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html[EKS最適化AMI]を使用します。また、ワークロードに利益をもたらす https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html#gpu-ami[GPU対応インスタンス]を選択することもできます。

[NOTE]
====

カスタムAMIが提供されている場合、RancherのGPU対応インスタンス設定は無視されます。
====


[#_spot_instances]
=== スポットインスタンス

スポットインスタンスは現在 https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html#managed-node-group-capacity-types-spot[EKSによってサポートされています]。起動テンプレートが指定されている場合、Amazonはテンプレートがインスタンスタイプを提供しないことを推奨します。代わりに、Amazonは複数のインスタンスタイプを提供することを推奨します。ノードグループの「スポットインスタンスをリクエスト」チェックボックスが有効になっている場合、複数のインスタンスタイプを提供する機会があります。

[NOTE]
====

インスタンスタイプのドロップダウンで行った選択はこの状況では無視され、"スポットインスタンスタイプ"セクションに少なくとも1つのインスタンスタイプを指定しなければなりません。さらに、EKSで使用される起動テンプレートはスポットインスタンスをリクエストすることはできません。スポットインスタンスのリクエストはEKSの設定の一部でなければなりません。
====


[#_node_group_settings]
=== ノードグループ設定

以下の設定も構成可能です。これらのうち「ノードグループ名」を除くすべては、ノードグループが作成された後に編集可能です。

|===
| オプション | 説明

| ノードグループ名
| ノードグループの名前。

| 希望するASGサイズ
| 希望するインスタンスの数。

| 最大ASGサイズ
| 最大インスタンス数。この設定は、 https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html[クラスターオートスケーラー]がインストールされるまで有効になりません。

| 最小ASGサイズ
| 最小インスタンス数。この設定は、 https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html[クラスターオートスケーラー]がインストールされるまで有効になりません。

| ラベル
| 管理ノードグループ内のノードに適用されるKubernetesラベル。

| タグ
| これらは管理ノードグループのタグであり、関連リソースには伝播しません。
|===

[#_self_managed_amazon_linux_nodes]
== 自己管理型Amazon Linuxノード

自己管理型Amazon Linuxノードを含むEKSクラスターを登録できます。このタイプのクラスターは、 https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html[自己管理型Amazon Linuxノードの起動に関する公式AWSドキュメント]の指示に従って設定する必要があります。自己管理型Amazon Linuxノードを含むEKSクラスターは、通常、 https://karpenter.sh/docs/[Karpenter]プロジェクトによって運用されます。自己管理型Amazon Linuxノードを含むEKSクラスターをプロビジョニングした後、{xref-register-clusters}[クラスターを登録]してRancherによって管理できるようにします。ただし、ノードはRancher UIには表示されません。

[#_iam_roles_for_service_accounts]
== サービスアカウント用のIAMロール

EKSクラスター上で実行されるアプリケーションデプロイメントは、IAM権限を介してAWSサービスにリクエストを行うことができます。これらのアプリケーションは、AWS資格情報でリクエストに署名する必要があります。IAMロールは、サービスアカウントがこれらの資格情報をAWS OIDCエンドポイントを使用して管理します。AWSの資格情報をコンテナに配布したり、EC2インスタンスのロールに依存する代わりに、 https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html[IAMロールをKubernetesサービスアカウントにリンクし]、Podをこのアカウントを使用するように構成できます。

[NOTE]
====

EKSクラスター内のRancherポッドに対してIAMロールへのリンクはサポートされていません。
====


サービスアカウントのためのIAMロールを有効にするには：

. https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html[クラスターのためのIAM OIDCプロバイダーを作成します]
. https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html[KubernetesサービスアカウントをIAMロールを引き受けるように構成します]
. https://docs.aws.amazon.com/eks/latest/userguide/pod-configuration.html[PodをKubernetesサービスアカウントを使用するように構成します]
. https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html[サポートされているAWS SDKを使用します]

[#_configuring_the_refresh_interval]
== リフレッシュ間隔の設定

`eks-refresh-cron`設定は廃止されました。それは`eks-refresh`設定に移行されました。これは秒を表す整数です。

デフォルト値は300秒です。

sync間隔は`kubectl edit setting eks-refresh`を実行することで変更できます。

`eks-refresh-cron`設定が以前に設定されていた場合、移行は自動的に行われます。

リフレッシュウィンドウが短いほど、レースコンディションが発生する可能性は低くなりますが、AWS APIに対して設定されているリクエスト制限に遭遇する可能性は高くなります。
