= {rancher-prime}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/prime.adoc 
:product-path: about-rancher/prime.adoc

SUSE Rancher présente Rancher Prime -- une évolution de Rancher -- à partir de la version v2.7. Rancher Prime est la nouvelle offre commerciale disponible de Rancher, construite sur le même code Open Source. Le projet Rancher continuera d'être 100 % Open Source. Prime apporte une valeur ajoutée avec de meilleures garanties de sécurité, des cycles de vie étendus, un accès à des architectures ciblées et des conseils Kubernetes. Rancher Prime proposera également des options pour obtenir un support en production pour des projets Rancher innovants. Avec Rancher Prime, les ressources d'installation sont hébergées sur un registre de confiance détenu et géré par Rancher.

Pour commencer avec Rancher Prime, https://www.rancher.com/quick-start[allez sur cette page] et remplissez le formulaire.
