= Cifrado de la comunicación HTTP
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc 
:product-path: security/encrypting-http.adoc
:description: Aprende a añadir un certificado SSL (Capa de sockets seguros) o un certificado TLS (Seguridad de la Capa de Transporte)
:experimental:
ifeval::["{build-type}" != "community"]
:xref-add-ingresses: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/add-ingresses.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-add-ingresses: xref:guías-prácticas/nuevos-usuarios/recursos-kubernetes-configuración/balanceador-de-carga-y-controlador-de-ingress/añadir-ingress.adoc
endif::[]

Cuando creas un ingress dentro de Rancher/Kubernetes, debes proporcionarle un secreto que incluya una clave privada TLS y un certificado, que se utilizan para cifrar y descifrar las comunicaciones que pasan a través del ingress. Puedes hacer que los certificados estén disponibles para su uso en ingress añadiendo el certificado al despliegue del ingress.

[NOTE]
.Requisito previo:
====

Debes tener una clave privada TLS y un certificado disponibles para subir.
====


[#_1_create_a_secret]
== 1. Crea un Secreto

. En la esquina superior izquierda, haz clic en *☰ > Gestión del Clúster*.
. Ve al clúster donde deseas desplegar tu ingress y haz clic en menu:Más Recursos[Núcleo> Secretos].
. Haga clic en *Crear*.
. Haz clic en *Certificado TLS*.
. Introduce un nombre para el secreto. Nota: Tu secreto debe tener un nombre único entre los otros certificados, registros y secretos dentro de tu proyecto/espacio de trabajo.
. En el campo *Clave Privada*, copia y pega la clave privada de tu certificado en el cuadro de texto (incluye el encabezado y el pie), o haz clic en *Leer de un archivo* para buscar la clave privada en tu sistema de archivos. Si es posible, recomendamos usar *Leer de un archivo* para reducir la probabilidad de error. Nota: Los archivos de clave privada terminan con una extensión de `.key`.
. En el campo *Certificado*, copia y pega tu certificado en el cuadro de texto (incluye el encabezado y el pie), o haz clic en *Leer de un archivo* para buscar el certificado en tu sistema de archivos. Si es posible, recomendamos usar *Leer de un archivo* para reducir la probabilidad de error. Nota: Los archivos de certificado terminan con una extensión de `.crt`.
. Haga clic en *Crear*.

[#_2_add_the_secret_to_an_ingress]
== 2. Añade el Secreto a un Ingress

. En la esquina superior izquierda, haz clic en *☰ > Gestión del Clúster*.
. Ve al clúster donde deseas desplegar tu ingress y haz clic en menu:Descubrimiento de Servicios[Ingresses].
. Haga clic en *Crear*.
. Selecciona el *Espacio de nombres* del ingress.
. Introduce un *Nombre* para el ingress.
. En la pestaña *Certificados*, selecciona el secreto que contiene tu certificado y tu clave privada.
. Haga clic en *Crear*.

[#_whats_next]
== ¿Qué sigue?

Ahora puedes añadir el certificado al lanzar un ingress dentro de tu proyecto o espacio de nombres actual. Para obtener más información, consulta {xref-add-ingresses}[Añadir Ingress].
