= Normas de seguridad de pods (PSS) y Admisión de seguridad de pods (PSA)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/normas-de-seguridad-de-pods.adoc 
:product-path: security/psa-pss.adoc
ifeval::["{build-type}" != "community"]
:xref-psact: xref:security/psact.adoc
:xref-sample-psact: xref:security/sample-psact.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-psact: xref:guías-de-cómo/nuevas-guías-para-usuarios/permisos-de-autenticación-y-configuración-global/plantillas-de-configuración-psa.adoc
:xref-sample-psact: xref:reference-guides/rancher-security/psa-restricted-exemptions.adoc
endif::[]

https://kubernetes.io/docs/concepts/security/pod-security-standards/[Normas de seguridad de pods (PSS)] y https://kubernetes.io/docs/concepts/security/pod-security-admission/[Admisión de seguridad de pods (PSA)] definen restricciones de seguridad para un amplio conjunto de cargas de trabajo.
Se hicieron disponibles y se activaron por defecto en Kubernetes v1.23, y reemplazan a https://kubernetes.io/docs/concepts/security/pod-security-policy/[Políticas de seguridad de pods (PSP)] en Kubernetes v1.25 y versiones posteriores.

Las PSS definen niveles de seguridad para cargas de trabajo. Las PSAs describen requisitos para los contextos de seguridad de pods y campos relacionados. Las PSAs hacen referencia a los niveles de PSS para definir restricciones de seguridad.

[#_pod_security_admission_configuration_templates]
== Plantillas de configuración de admisión de seguridad de pods

Rancher ofrece plantillas de configuración de PSA. Estas son configuraciones de seguridad predefinidas que puedes aplicar a un clúster. Los administradores de Rancher (o aquellos con los permisos adecuados) pueden {xref-psact}[crear, gestionar y editar] plantillas de PSA.

[#_rancher_on_psa_restricted_clusters]
=== Rancher en clústeres restringidos por PSA

Los espacios de nombres del sistema de Rancher también se ven afectados por las políticas de seguridad restrictivas descritas por las plantillas de PSA. Necesitas eximir los espacios de nombres del sistema de Rancher después de asignar la plantilla, de lo contrario, el clúster no funcionará correctamente. Consulta {xref-psact}#_eximiendo_espacios_de_nombres_requeridos_de_rancher[Plantillas de configuración de admisión de seguridad de pods (PSA)] para más detalles.

Para un archivo completo que contenga todas las exenciones necesarias para ejecutar Rancher, consulta esta {xref-sample-psact}[muestra de configuración de admisión].
