= Überwachung und Dashboards
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/monitoring-and-alerting/index.adoc 
:product-path: observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:description: Prometheus ermöglicht es Ihnen, Metriken von Ihren verschiedenen Rancher- und Kubernetes-Objekten anzuzeigen. Erfahren Sie mehr über den Umfang der Überwachung und wie Sie die Clusterüberwachung aktivieren können.
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
:xref-configure-alertmanager: xref:observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:observability/monitoring-and-dashboards/configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:observability/monitoring-and-dashboards/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheusrules.adoc
:xref-prometheus: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
:xref-enable-monitoring: xref:observability/monitoring-and-dashboards/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:observability/monitoring-and-dashboards/customizing-dashboard/create-persistent-grafana-dashboard.adoc
:xref-servicemonitors-and-podmonitors: xref:observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:observability/monitoring-and-dashboards/configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:observability/monitoring-and-dashboards/configuration/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:observability/monitoring-and-dashboards/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:observability/monitoring-and-dashboards/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:observability/monitoring-and-dashboards/windows-support.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
:xref-configure-alertmanager: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc
:xref-monitoring-helm-chart-options: xref:reference-guides/monitoring-v2-configuration/helm-chart-options.adoc
:xref-rancher-workload-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
:xref-customize-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc
:xref-prometheusrules: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheusrules.adoc
:xref-prometheus: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc
:xref-enable-monitoring: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring.adoc
:xref-create-persistent-grafana-dashboard: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard.adoc
:xref-servicemonitors-and-podmonitors: xref:reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:reference-guides/monitoring-v2-configuration/routes.adoc
:xref-monitoring-debug-high-memory: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/debug-high-memory-usage.adoc
:xref-monitoring-builtin-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/built-in-dashboards.adoc
:xref-monitoring-uninstall: xref:how-to-guides/advanced-user-guides/monitoring-alerting-guides/uninstall-monitoring.adoc
:xref-monitoring-windows: xref:integrations-in-rancher/monitoring-and-alerting/windows-support.adoc
endif::[]

Die `rancher-monitoring` Anwendung kann führende Open-Source-Überwachungs- und Alarmierungslösungen schnell auf Ihrem Cluster bereitstellen.

Eingeführt in Rancher v2.5, wird die Anwendung von https://prometheus.io/[Prometheus], https://grafana.com/grafana/[Grafana], https://prometheus.io/docs/alerting/latest/alertmanager/[Alertmanager], dem https://github.com/prometheus-operator/prometheus-operator[Prometheus Operator] und dem https://github.com/DirectXMan12/k8s-prometheus-adapter[Prometheus-Adapter.] betrieben.

Für Informationen zur V1-Überwachung und Alarmierung, die in Rancher v2.2 bis v2.4 verfügbar sind, siehe bitte die Rancher v2.0--v2.4-Dokumentation zu xref:[Cluster-Überwachung], xref:[Alarmierung], xref:[Benachrichtigungen] und anderen xref:[Tools].

Mit der `rancher-monitoring` Anwendung können Sie führende Open-Source-Überwachungs- und Alarmierungslösungen schnell auf Ihrem Cluster bereitstellen.

[#_features]
== Funktionen

Prometheus ermöglicht es Ihnen, Metriken von Ihren Rancher- und Kubernetes-Objekten anzuzeigen. Mit Zeitstempeln ermöglicht es Prometheus Ihnen, diese Metriken in leicht lesbaren Grafiken und Visualisierungen abzufragen und anzuzeigen, entweder über die Rancher-Benutzeroberfläche oder Grafana, das eine Analyse-Ansichtsplattform ist, die zusammen mit Prometheus bereitgestellt wird.

Durch die Anzeige von Daten, die Prometheus von Ihrem Cluster-Kontrollbereich, Knoten und Bereitstellungen erfasst, können Sie alles, was in Ihrem Cluster passiert, im Blick behalten. Sie können diese Analysen dann nutzen, um Ihre Organisation besser zu führen: Systemnotfälle verhindern, bevor sie beginnen, Wartungsstrategien entwickeln oder abgestürzte Server wiederherstellen.

Die Überwachungsanwendung:

* Überwacht den Zustand und die Prozesse Ihrer Clusterknoten, Kubernetes-Komponenten und Softwarebereitstellungen.
* Definiert Alarme basierend auf Metriken, die über Prometheus gesammelt werden.
* Erstellt benutzerdefinierte Grafana-Dashboards.
* Konfiguriert benachrichtigungsbasierte Mitteilungen per E-Mail, Slack, PagerDuty usw. mit Prometheus Alertmanager.
* Definiert vorab berechnete, häufig benötigte oder rechenintensive Ausdrücke als neue Zeitreihen basierend auf Metriken, die über Prometheus gesammelt wurden.
* Stellt gesammelte Metriken von Prometheus über den Prometheus-Adapter der Kubernetes Custom Metrics API zur Verfügung, um sie im HPA zu verwenden.

Siehe {xref-how-monitoring-works}[Wie Monitoring funktioniert] für eine Erklärung, wie die Überwachungsbestandteile zusammenarbeiten.

[#_default_components_and_deployments]
== Standardkomponenten und -bereitstellungen

[#_built_in_dashboards]
=== Integrierte Dashboards

Standardmäßig stellt die Überwachungsanwendung Grafana-Dashboards (kuratiert durch das https://github.com/prometheus-operator/kube-prometheus[kube-prometheus] Projekt) auf einem Cluster bereit.

Es stellt auch eine Alertmanager-Benutzeroberfläche und eine Prometheus-Benutzeroberfläche bereit. Für weitere Informationen zu diesen Tools siehe {xref-monitoring-builtin-dashboards}[Integrierte Dashboards.]

[#_default_metrics_exporters]
=== Standardmetriken-Exporter

Standardmäßig stellt Rancher Monitoring Exporter (wie https://github.com/prometheus/node_exporter[node-exporter] und https://github.com/kubernetes/kube-state-metrics[kube-state-metrics]) bereit.

Diese Standard-Exporter erfassen automatisch Metriken für CPU und Arbeitsspeicher von allen Komponenten Ihres Kubernetes-Clusters, einschließlich Ihrer Arbeitslasten.

[#_default_alerts]
=== Standardalarme

Die Überwachungsanwendung stellt standardmäßig einige Alarme bereit. Um die Standardalarme zu sehen, gehen Sie zur xref:./built-in-dashboards.adoc#_alertmanager_ui[Alertmanager-Benutzeroberfläche] und klicken Sie auf *Alle Gruppen erweitern.*

[#_components_exposed_in_the_rancher_ui]
=== In der Rancher-Benutzeroberfläche exponierte Komponenten

Für eine Liste der in der Rancher-Benutzeroberfläche exponierten Überwachungsbestandteile sowie gängige Anwendungsfälle für deren Bearbeitung siehe xref:./how-monitoring-works.adoc#_components_exposed_in_the_rancher_ui[diesen Abschnitt.]

[#_role_based_access_control]
== Rollenbasierte Zugriffssteuerung

Für weitere Informationen zur Konfiguration des Zugriffs auf das Monitoring siehe {xref-rancher-monitoring-rbac}[diese Seite.]

[NOTE]
====

Rancher- und Projektleseberechtigungen gelten nicht unbedingt für Überwachungsressourcen. Siehe xref:./rbac-for-monitoring.adoc#_additional_monitoring_clusterroles[monitoring-ui-view] für weitere Details.
====


[#_guides]
== Handbücher

* {xref-enable-monitoring}[Überwachung aktivieren]
* {xref-monitoring-uninstall}[Überwachung deinstallieren]
* {xref-rancher-workload-monitoring}[Überwachung von Arbeitslasten]
* {xref-customize-grafana-dashboard}[Grafana-Dashboards anpassen]
* {xref-create-persistent-grafana-dashboard}[Persistente Grafana-Dashboards]
* {xref-monitoring-debug-high-memory}[Debugging bei hohem Speicherverbrauch]

[#_configuration]
== Konfiguration

[#_configuring_monitoring_resources_in_rancher]
=== Konfiguration von Überwachungsressourcen in Rancher

Die Konfigurationsreferenz setzt voraus, dass Sie mit der Funktionsweise der Überwachungsbestandteile vertraut sind. Für weitere Informationen siehe {xref-how-monitoring-works}[Wie Überwachung funktioniert.]

* {xref-servicemonitors-and-podmonitors}[ServiceMonitor und PodMonitor]
* {xref-receivers}[Empfänger]
* {xref-monitoring-routes}[Route]
* {xref-prometheusrules}[PrometheusRule]
* {xref-prometheus}[Prometheus]
* {xref-configure-alertmanager}[Alertmanager]

[#_configuring_helm_chart_options]
=== Konfiguration von Helm-Chart-Optionen

Für weitere Informationen zu `rancher-monitoring` Chart-Optionen, einschließlich Optionen zur Festlegung von Ressourcenlimits und -anforderungen, siehe {xref-monitoring-helm-chart-options}[Helm-Chart-Optionen].

[#_windows_cluster_support]
== Unterstützung für Windows Cluster

Um Monitoring V2 für Windows vollständig bereitstellen zu können, müssen alle Ihre Windows-Hosts eine Mindestversion von https://github.com/rancher/wins[wins] v0.1.0 haben.

Für weitere Informationen zum Upgrade von wins auf bestehenden Windows-Hosts siehe {xref-monitoring-windows}[Windows-Clusterunterstützung für Monitoring V2.].

[#_known_issues]
== Bekannte Probleme

Es gibt ein https://github.com/rancher/rancher/issues/28787#issuecomment-693611821[bekanntes Problem], dass K3s-Cluster mehr als den vorgesehenen Standard-Speicher benötigen. Wenn Sie das Monitoring auf einem K3s-Cluster aktivieren, setzen Sie `prometheus.prometheusSpec.resources.memory.limit` auf 2500 Mi und `prometheus.prometheusSpec.resources.memory.request` auf 1750 Mi.

Siehe {xref-monitoring-debug-high-memory}[Debugging bei hohem Speicherverbrauch] für Ratschläge und Empfehlungen.
