= Überwachung für eine Arbeitslast einrichten
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads.adoc 
:product-path: observability/monitoring-and-dashboards/set-up-monitoring-for-workloads.adoc
ifeval::["{build-type}" != "community"]
:xref-promql-expressions: xref:observability/monitoring-and-dashboards/promql-expressions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-promql-expressions: xref:integrations-in-rancher/monitoring-and-alerting/promql-expressions.adoc
endif::[]

Wenn Sie nur CPU- und Arbeitsspeicher-Zeitreihen für die Arbeitslast benötigen, müssen Sie keinen ServiceMonitor oder PodMonitor bereitstellen, da die Überwachungsanwendung standardmäßig bereits Metrikdaten zur Ressourcennutzung sammelt.

Die Schritte zum Einrichten der Überwachung für Arbeitslasten hängen davon ab, ob Sie grundlegende Metriken wie CPU und Arbeitsspeicher für die Arbeitslast wünschen oder ob Sie benutzerdefinierte Metriken von der Arbeitslast abrufen möchten.

Wenn Sie nur CPU- und Arbeitsspeicher-Zeitreihen für die Arbeitslast benötigen, müssen Sie keinen ServiceMonitor oder PodMonitor bereitstellen, da die Überwachungsanwendung standardmäßig bereits Metrikdaten zur Ressourcennutzung sammelt. Die Zeitreihendaten zur Ressourcennutzung befinden sich in der lokalen Zeitreihendatenbank von Prometheus.

Grafana zeigt die Daten aggregiert an, aber Sie können die Daten für die einzelne Arbeitslast sehen, indem Sie eine PromQL-Abfrage verwenden, die die Daten für diese Arbeitslast extrahiert. Sobald Sie die PromQL-Abfrage haben, können Sie diese einzeln in der Prometheus-Benutzeroberfläche ausführen und die Zeitreihen dort visualisiert sehen, oder Sie können die Abfrage verwenden, um ein Grafana-Dashboard anzupassen, um die Arbeitslastmetriken anzuzeigen. Für Beispiele von PromQL-Abfragen für Arbeitslastmetriken siehe {xref-promql-expressions}#_workload_metrics[diesen Abschnitt].

Um benutzerdefinierte Metriken für Ihre Arbeitslast einzurichten, müssen Sie einen Exporter einrichten und eine neue benutzerdefinierte Ressource vom Typ ServiceMonitor erstellen, um Prometheus zu konfigurieren, damit Metriken von Ihrem Exporter abgerufen werden.

[#_display_cpu_and_memory_metrics_for_a_workload]
== CPU- und Arbeitsspeicher-Metriken für eine Arbeitslast anzeigen

Standardmäßig ruft die Überwachungsanwendung bereits CPU und Arbeitsspeicher ab.

Um detailliertere Informationen für eine bestimmte Arbeitslast zu erhalten, können Sie ein Grafana-Dashboard anpassen, um die Metriken für eine bestimmte Arbeitslast anzuzeigen.

[#_setting_up_metrics_beyond_cpu_and_memory]
== Einrichten von Metriken über CPU und Arbeitsspeicher hinaus

Für benutzerdefinierte Metriken müssen Sie die Metriken in Ihrer Anwendung in einem von Prometheus unterstützten Format bereitstellen.

Dann empfehlen wir, dass Sie eine neue benutzerdefinierte Ressource vom Typ ServiceMonitor erstellen. Wenn diese Ressource erstellt wird, wird die benutzerdefinierte Ressource von Prometheus automatisch aktualisiert, sodass ihre Scrape-Konfiguration den neuen benutzerdefinierten Metriken-Endpunkt umfasst. Dann beginnt Prometheus, Metriken vom Endpunkt abzurufen.

Sie können auch einen PodMonitor erstellen, um den benutzerdefinierten Metriken-Endpunkt bereitzustellen, aber ServiceMonitors sind für die Mehrheit der Anwendungsfälle geeigneter.
