= {rancher-product-name} Início Rápido do Equinix Metal
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/equinix-metal.adoc 
:product-path: installation-and-upgrade/quick-start/deploy-rancher/equinix-metal.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-qs-deploy-workloads: xref:installation-and-upgrade/quick-start/deploy-workloads/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-qs-deploy-workloads: xref:getting-started/quick-start-guides/deploy-workloads/index.adoc
endif::[]

[#_this_tutorial_walks_you_through_the_following]
== Este tutorial o guiará pelos seguintes passos:

* Provisionamento de um Servidor Equinix Metal
* Instalação do Rancher 2.x
* Criação do seu primeiro cluster
* Implantação de um aplicativo, Nginx

[CAUTION]
====

A intenção destes guias é lançar rapidamente uma área de segurança que você pode usar para avaliar o Rancher. A instalação do Docker não é recomendada para ambientes de produção. Para instruções abrangentes de configuração, consulte {xref-install-upgrade}[Instalação].
====


[#_quick_start_outline]
== Esboço do Início Rápido

Este Guia de Início Rápido é dividido em diferentes tarefas para facilitar o consumo.

[#_prerequisites]
== Pré-requisitos

* Uma https://deploy.equinix.com/developers/docs/metal/identity-access-management/users/[conta do Equinix Metal]
* Um https://deploy.equinix.com/developers/docs/metal/projects/creating-a-project/[projeto do Equinix Metal]

[#_1_provision_a_equinix_metal_host]
=== 1. Provisionar um Host Equinix Metal

Comece a implantar um Host Equinix Metal. Os Servidores Equinix Metal podem ser provisionados a partir do console, API ou CLI do Equinix Metal. Você pode encontrar instruções para cada tipo de implantação na https://deploy.equinix.com/developers/docs/metal/deploy/on-demand/[documentação de implantação do Equinix Metal]. Você pode encontrar informações adicionais sobre os tipos de servidores Equinix Metal na https://deploy.equinix.com/developers/docs/metal/hardware/standard-servers/[Documentação do Equinix Metal].

[NOTE]
.Notas:
====

* Ao provisionar um novo Servidor Equinix Metal via CLI ou API, você precisará fornecer as seguintes informações: project-id, plano, metro e sistema operacional.
* Ao usar uma máquina virtual hospedada na nuvem, você precisa permitir a comunicação TCP de entrada nas portas 80 e 443. Consulte a documentação do seu provedor de nuvem para obter informações sobre a configuração de portas.
* Para uma lista completa dos requisitos de portas, consulte {xref-node-reqs}[Instalação do Docker].
* Provisione o host de acordo com nossos {xref-install-reqs}[Requisitos].
====


[#_2_install_rancher]
=== 2. Instalar o Rancher

Para instalar o Rancher no seu host Equinix Metal, conecte-se a ele e, em seguida, use um shell para instalar.

. Faça login no seu host Equinix Metal usando seu shell preferido, como PuTTy ou uma conexão de Terminal remoto.
. No seu shell, insira o seguinte comando:
+
----
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher
----

*Resultado:* O Rancher está instalado.

[#_3_log_in]
=== 3. Efetuar login

Faça login no Rancher para começar a usar o aplicativo. Após fazer login, você fará algumas configurações únicas.

. Abra um navegador da web e insira o endereço IP do seu host: `\https://<server_ip>`.
+
Substitua `<SERVER_IP>` pelo endereço IP do seu host.

. Quando solicitado, crie uma senha para a conta padrão `admin`.
. Defina a *URL do Servidor Rancher*. A URL pode ser um endereço IP ou um nome de host. No entanto, cada nó adicionado ao seu cluster deve ser capaz de se conectar a essa URL. +
 +
Se você usar um nome de host na URL, esse nome de host deve ser resolvível pelo DNS nos nós que você deseja adicionar ao seu cluster.

{blank}

[#_4_create_the_cluster]
=== 4. Crie o Cluster

Bem-vindo ao Rancher! Agora você pode criar seu primeiro cluster Kubernetes.

Nesta tarefa, você pode usar a versátil opção *Personalizado*. Essa opção permite que você adicione _qualquer_ host Linux (VM hospedada na nuvem, VM local ou bare metal) para uso em um cluster.

. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique em *Criar*.
. Escolha *Personalizado*.
. Digite um *Nome do Cluster*.
. Clique em *Próximo*.
. De *Papel do Nó*, selecione _todos_ os papéis: *etcd*, *Control* e *Worker*.
 ** *Opcional*: O Rancher detecta automaticamente os endereços IP usados para comunicação do Rancher e comunicação do cluster. Você pode substituir esses usando `Public Address` e `Internal Address` na seção *Endereço do Nó*.
. Copie o comando de registro para sua área de transferência.
. Faça login no seu host Linux usando seu shell preferido, como PuTTy ou uma conexão de Terminal remoto. Execute o comando copiado para sua área de transferência.
. Quando você terminar de executar o comando no seu host Linux, clique em *Concluído*.

*Resultado:*

Seu cluster foi criado e atribuído ao estado de *Provisionamento*. O Rancher está configurando seu cluster.

Você pode acessar seu cluster após seu estado ser atualizado para *Ativo*.

Clusters *Ativos* são atribuídos a dois projetos:

* `Default`, contendo o namespace `default`
* `System`, contendo os namespaces `cattle-system`, `traefik`, `kube-public` e `kube-system`

[#_finished]
==== Concluído

Parabéns! Você criou seu primeiro cluster.

[#_whats_next]
==== O Que Mais?

Use o Rancher para criar uma implantação. Para mais informações, veja {xref-qs-deploy-workloads}[Criando Implantações].
