= Rôles pour les nœuds dans Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters/roles-for-nodes-in-kubernetes.adoc 
:product-path: cluster-deployment/production-checklist/roles-for-nodes-in-kubernetes.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
endif::[]

Cette section décrit les rôles des nœuds etcd, des nœuds de contrôle et des nœuds de travail dans Kubernetes, et comment ces rôles fonctionnent ensemble dans un cluster.

Ce diagramme s'applique aux clusters Kubernetes {xref-launch-k8s-with-rancher}[lancés avec Rancher en utilisant RKE.].

.Les lignes montrent le flux de trafic entre les composants. Les couleurs sont utilisées uniquement à des fins d'aide visuelle
image::clusterdiagram.svg[Diagramme du cluster]

[#_etcd]
== etcd

Les nœuds avec le rôle `etcd` exécutent etcd, qui est un magasin de valeurs clé cohérent et hautement disponible utilisé comme `' magasin de sauvegarde pour toutes les données du cluster. etcd réplique les données sur chaque nœud.

[NOTE]
====

Les nœuds avec le rôle `etcd` sont affichés comme `Unschedulable` dans l'interface utilisateur, ce qui signifie qu'aucun pod ne sera programmé sur ces nœuds par défaut.
====


[#_controlplane]
== controlplane

Les nœuds avec le rôle `controlplane` exécutent les composants principaux de Kubernetes (à l'exception de `etcd`, car c'est un rôle séparé). Voir https://kubernetes.io/docs/concepts/overview/components/#master-components[Kubernetes{nbsp}: Composants principaux] pour une liste détaillée des composants.

[NOTE]
====

Les nœuds avec le rôle `controlplane` sont affichés comme `Unschedulable` dans l'interface utilisateur, ce qui signifie qu'aucun pod ne sera programmé sur ces nœuds par défaut.
====


[#_kube_apiserver]
=== kube-apiserver

Le serveur API Kubernetes (`kube-apiserver`) se met à l'échelle horizontalement. Chaque nœud avec le rôle `controlplane` sera ajouté au proxy NGINX sur les nœuds avec des composants qui ont besoin d'accéder au serveur API Kubernetes. Cela signifie que si un nœud devient inaccessible, le proxy NGINX local sur le nœud transmettra la demande à un autre serveur API Kubernetes dans la liste.

[#_kube_controller_manager]
=== kube-controller-manager

Le gestionnaire de contrôleur Kubernetes utilise l'élection de leader en utilisant un point de terminaison dans Kubernetes. Une instance du `kube-controller-manager` créera une entrée dans les points de terminaison Kubernetes et mettra à jour cette entrée à un intervalle configuré. D'autres instances verront un leader actif et attendront que cette entrée expire (par exemple, lorsqu'un nœud ne répond pas).

[#_kube_scheduler]
=== kube-scheduler

Le planificateur Kubernetes utilise l'élection de leader en utilisant un point de terminaison dans Kubernetes. Une instance du `kube-scheduler` créera une entrée dans les points de terminaison Kubernetes et mettra à jour cette entrée à un intervalle configuré. D'autres instances verront un leader actif et attendront que cette entrée expire (par exemple, lorsqu'un nœud ne répond pas).

[#_worker]
== nœud de travail

Les nœuds avec le rôle `worker` exécutent les composants de nœud Kubernetes. Voir https://kubernetes.io/docs/concepts/overview/components/#node-components[Kubernetes{nbsp}: Composants de nœud] pour une liste détaillée des composants.

[#_references]
== Références

* https://kubernetes.io/docs/concepts/overview/components/#node-components[Kubernetes{nbsp}: Composants de nœud]
