= フローとクラスター・フロー
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/custom-resource-configuration/flows-and-clusterflows.adoc 
:product-path: observability/logging/custom-resource-configuration/flows-and-clusterflows.adoc
ifeval::["{build-type}" != "community"]
:xref-logging: xref:observability/logging/logging.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
endif::[]

https://kube-logging.github.io/docs/configuration/flow/[ログオペレーターのドキュメント]を参照して、`Flows`と`ClusterFlows`の設定方法の詳細を確認してください。

{xref-logging} #_ログバッファオーバーロードポッド[Rancherとログサービスの統合：トラブルシューティング]を参照して、ログバッファのメモリ問題を解決する方法を確認してください。

[#_flows]
== フロー

`Flow`は、収集するログとフィルタリングするログ、そしてログを送信する出力を定義します。

`Flow`はネームスペースリソースであり、`Flow`がデプロイされているネームスペースからのみログが収集されることを意味します。

`Flows`はRancher UIのフォームに記入することで設定できます。

`Flow`カスタムリソースの詳細については、 https://kube-logging.github.io/docs/configuration/crds/v1beta1/flow_types/[FlowSpec.]を参照してください。

[#_matches]
=== 一致する

マッチステートメントは、どのコンテナからログを取得するかを選択するために使用されます。

Kubernetesのラベル、コンテナ名、ホスト名に基づいてログを選択または除外するために、マッチステートメントを指定できます。マッチステートメントは、定義された順序で評価され、最初の一致する選択または除外ルールが適用されるまで処理されます。

マッチは、Rancher UIの`Flow`または`ClusterFlow`フォームに記入することで設定できます。

マッチステートメントの使用に関する詳細な例については、 https://kube-logging.github.io/docs/configuration/log-routing/[ログルーティングに関する公式ドキュメントを参照してください。]

[#_filters]
=== フィルタ

`Flow`内に1つ以上のフィルターを定義できます。フィルターは、データの追加、ログの変換、またはレコードからの値の解析など、ログに対してさまざまなアクションを実行できます。`Flow`内のフィルターは、定義に表示される順序で適用されます。

ログオペレーターがサポートするフィルターのリストについては、 https://kube-logging.github.io/docs/configuration/plugins/filters/[Fluentdフィルターに関する公式ドキュメントを参照してください。]

フィルターはYAMLで設定する必要があります。

[#_outputs]
=== 出力

この`Output`は`Flow`からログを受信します。`Flow`はネームスペースリソースであるため、`Output`は`Flow`と同じネームスペースに存在する必要があります。

`Outputs` は、Rancher UI の `Flow` または `ClusterFlow` フォームを記入する際に参照できます。

[#_clusterflows]
== ClusterFlows

マッチ、フィルター、および `Outputs` は、`ClusterFlows` に対して `Flows` と同様に設定されています。主な違いは、`ClusterFlow` がクラスター レベルでスコープされており、すべてのネームスペースにわたってログ収集を構成できることです。

`ClusterFlows`はRancher UIのフォームに記入することで設定できます。

`ClusterFlow` がクラスター内のすべてのネームスペースからログを選択した後、クラスターのログが収集され、選択した `ClusterOutput` に記録されます。

[#_yaml_example]
== YAML の例

次の例では、`Flow`デフォルトのネームスペースからのログメッセージを変換し、それらを S3 `Output` に送信します。

[,yaml]
----
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  filters:
    - parser:
        remove_key_name_field: true
        parse:
          type: nginx
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
  localOutputRefs:
    - s3-output
  match:
    - select:
        labels:
          app: nginx
----
