= Checkliste für produktionsbereite Cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/kubernetes-clusters-in-rancher-setup/checkliste-für-produktionsbereite-cluster/index.adoc 
:product-path: cluster-deployment/production-checklist/production-checklist.adoc
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/knotenanforderungen.adoc
:xref-arch-rec: xref:about-rancher/architecture/recommendations.adoc
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
:xref-production-checklist-node-roles: xref:cluster-deployment/production-checklist/roles-for-nodes-in-kubernetes.adoc
:xref-best-practices: xref:installation-and-upgrade/best-practices/best-practices.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/neue-nutzeranleitungen/kubernetes-cluster-in-rancher-einrichten/knotenanforderungen-für-rancher-verwaltete-cluster.adoc
:xref-arch-rec: xref:reference-guides/rancher-manager-architecture/architecture-recommendations.adoc
:xref-set-up-cloud-providers: xref:how-to-guides/neue-benutzeranleitungen/kubernetes-cluster-in-rancher-einrichten/cloud-anbieter-einrichten/index.adoc
:xref-production-checklist-node-roles: xref:how-to-guides/neue-benutzeranleitungen/kubernetes-cluster-in-rancher-setup/checkliste-für-produktionsbereite-cluster/rollen-für-knoten-in-kubernetes.adoc
:xref-best-practices: xref:reference-guides/best-practices/rancher-server/index.adoc
endif::[]

In diesem Abschnitt empfehlen wir bewährte Praktiken zur Erstellung von produktionsbereiten Kubernetes-Clustern, die Ihre Apps und Dienste ausführen werden.

Für eine Liste der Anforderungen an Ihr Cluster, einschließlich der Anforderungen für OS/Docker, Hardware und Netzwerk, siehe den Abschnitt über {xref-node-reqs}[Knotenanforderungen.]

Dies ist eine Kurzliste von bewährten Praktiken, die wir für alle Produktionscluster dringend empfehlen.

Für eine vollständige Liste aller bewährten Praktiken, die wir empfehlen, siehe den {xref-best-practices}[Abschnitt über bewährte Praktiken.]

[#_node_requirements]
== Knotenanforderungen

* Stellen Sie sicher, dass Ihre Knoten alle {xref-node-reqs}[Knotenanforderungen] erfüllen, einschließlich der Portanforderungen.

[#_back_up_etcd]
== Sichern Sie etcd

* Aktivieren Sie etcd-Snapshots. Überprüfen Sie, ob Snapshots erstellt werden, und führen Sie ein Szenario zur Katastrophenwiederherstellung durch, um zu überprüfen, ob die Snapshots gültig sind. etcd ist der Ort, an dem der Zustand Ihres Clusters gespeichert ist, und der Verlust von etcd-Daten bedeutet den Verlust Ihres Clusters. Stellen Sie sicher, dass Sie wiederkehrende Snapshots von etcd für Ihr(e) Cluster(s) konfigurieren, und stellen Sie sicher, dass die Snapshots auch extern (außerhalb des Knotens) gespeichert werden.

[#_cluster_architecture]
== Cluster-Architektur

* Knoten sollten eine der folgenden Rollenkonfigurationen haben:
 ** `etcd`
 ** `controlplane`
 ** `etcd` und `controlplane`
 ** `worker` (die Rolle `worker` sollte nicht verwendet oder auf Knoten mit der Rolle `etcd` oder `controlplane` hinzugefügt werden)
* Haben Sie mindestens drei Knoten mit der Rolle `etcd`, um den Verlust eines Knotens zu überstehen. Erhöhen Sie diese Anzahl für eine höhere Fehlertoleranz der Knoten und verteilen Sie sie über (Verfügbarkeits-)Zonen, um eine noch bessere Fehlertoleranz zu gewährleisten.
* Weisen Sie zwei oder mehr Knoten die Rolle `controlplane` für hohe Verfügbarkeit der Masterkomponenten zu.
* Weisen Sie zwei oder mehr Knoten die Rolle `worker` für die Neuzuweisung von Workloads bei einem Knotenausfall zu.

Für weitere Informationen darüber, wofür jede Rolle verwendet wird, siehe die {xref-production-checklist-node-roles}[Sektion über Rollen für Knoten in Kubernetes.]

Für weitere Informationen über die Anzahl der Knoten für jede Kubernetes-Rolle siehe den Abschnitt über {xref-arch-rec}[empfohlene Architektur.]

[#_logging_and_monitoring]
== Protokollierung und Überwachung

* Konfigurieren Sie Warnungen/Benachrichtigungen für Kubernetes-Komponenten (Systemdienst).
* Konfigurieren Sie das Logging für Clusteranalysen und Nachbesprechungen.

[#_reliability]
== Zuverlässigkeit

* Führen Sie Lasttests auf Ihrem Cluster durch, um zu überprüfen, ob die Hardware Ihre Arbeitslasten unterstützen kann.

[#_networking]
== Netzwerke

* Minimieren Sie die Netzwerklatenz. Rancher empfiehlt, die Latenz zwischen den etcd-Knoten zu minimieren. Die Standardeinstellung für `heartbeat-interval` ist `500`, und die Standardeinstellung für `election-timeout` ist `5000`. Diese https://etcd.io/docs/v3.5/tuning/[Einstellungen zur etcd-Optimierung] ermöglichen es etcd, in den meisten Netzwerken (außer in wirklich hochlatenten Netzwerken) zu arbeiten.
* Clusterknoten sollten sich innerhalb einer einzigen Region befinden. Die meisten Cloud-Anbieter bieten mehrere Verfügbarkeitszonen innerhalb einer Region an, die zur Schaffung einer höheren Verfügbarkeit für Ihr Cluster genutzt werden können. Die Verwendung mehrerer Verfügbarkeitszonen ist für Knoten mit jeder Rolle in Ordnung. Wenn Sie {xref-set-up-cloud-providers}[Kubernetes Cloud Provider]-Ressourcen verwenden, konsultieren Sie die Dokumentation für etwaige Einschränkungen (z. B. Einschränkungen bei der Zonenspeicherung).
