= Betrieb auf ARM64-Mischarchitektur (Experimentell)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-07
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/enable-experimental-features/rancher-on-arm64.adoc 
:product-path: rancher-admin/experimental-features/rancher-on-arm64.adoc
ifeval::["{build-type}" != "community"]
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rke2-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.adoc
:xref-k3s-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc
endif::[]

[CAUTION]
====
Der Betrieb auf einer ARM64-Mischarchitektur-Plattform ist derzeit eine experimentelle Funktion und wird in Rancher noch nicht offiziell unterstützt. Daher empfehlen wir nicht, ARM64-basierten Knoten in einer Produktionsumgebung zu verwenden.
====

Die folgenden Optionen stehen zur Verfügung, wenn Sie eine ARM64-Plattform verwenden:

* Erstellen eines benutzerdefinierten Clusters und Hinzufügen von ARM64-basierten Knoten
 ** Die Kubernetes-Cluster-Version muss 1.12 oder höher sein
* Importieren von Clustern, die ARM64-basierte Knoten enthalten
 ** Die Kubernetes-Cluster-Version muss 1.12 oder höher sein

Je nach Ihrer Cluster-Bereitstellung verweisen Sie auf {xref-rke2-config}[RKE2-Cluster-Konfigurationsoptionen] oder {xref-k3s-config}[K3s-Cluster-Konfigurationsoptionen] für weitere Informationen.

Die folgenden Funktionen sind nicht getestet:

* Überwachung, Warnungen, Benachrichtigungen, Pipelines und Protokollierung
* Apps aus dem Katalog starten
