= RoleTemplate Aggregation
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-11-27
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/enable-experimental-features/role-template-aggregation.adoc 
:product-path: rancher-admin/experimental-features/role-template-aggregation.adoc

[CAUTION]
====
Die Rollenvorlagen-Aggregation ist eine experimentelle Funktion in v2.13, die die RBAC-Architektur für Rollenvorlagen, Clusterrollenbindungs- und Projektrollenbindungs-Vorlagen ändert. **Sie wird nicht für Produktionsumgebungen unterstützt**. Zwischen v2.13 und v2.14 kann es zu Breaking Changes kommen.
====

Die Rollenvorlagen-Aggregation implementiert Rollenvorlagen, Clusterrollenbindungs- und Projektrollenbindungs-Vorlagen unter Verwendung der Kubernetes-Funktion https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles[Aggregierte Clusterrollen]. Die neue Architektur führt zu einer Netto-Reduzierung der RBAC-Objekte (Rollen, Rollenbindungen, Clusterrollen und Clusterrollenbindungen) sowohl im Rancher-Cluster als auch in den Downstream-Clustern.

Für weitere Informationen darüber, wie die Funktion die Skalierbarkeit und Leistung verbessern kann, siehe bitte den https://www.suse.com/c/rancher_blog/fewer-bindings-more-power-ranchers-rbac-boost-for-enhanced-performance-and-scalability/[Rancher-Blogbeitrag].

|===
| Umgebungsvariablen-Schlüssel | Standardwert | Beschreibung

| `aggregated-roletemplates`
| `false`
| [Beta] Rollenvorlagen verwenden Aggregation für generierte RBAC-Rollen.
|===

Der Wert dieses Funktionsschalters ist bei der Installation gesperrt, was in der Benutzeroberfläche als ein Schlosssymbol neben dem Funktionsschalter angezeigt wird. Das bedeutet, dass die Funktion nur bei der allerersten Installation von Rancher festgelegt werden kann. Danach werden Versuche, den Wert zu ändern, abgelehnt.
