= Charts e Apps do Helm
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/helm-charts-in-rancher/index.adoc 
:product-path: cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-air-gap-rancher-ha: xref:installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc
:xref-oci-repo: xref:cluster-admin/helm-charts-in-rancher/oci-repositories.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-air-gap-rancher-ha: xref:começando/instalação-e-atualização/outros-métodos-de-instalação/air-gapped-helm-cli-install/instalar-rancher-ha.adoc
:xref-oci-repo: xref:how-to-guides/new-user-guides/helm-charts-in-rancher/oci-repositories.adoc
endif::[]

Nesta seção, você aprenderá como gerenciar repositórios de charts do Helm e apps no Rancher.

[#_how_helm_charts_work_in_rancher]
== Como os charts do Helm funcionam no Rancher

Os repositórios de charts do Helm no Rancher são gerenciados usando *Apps*.

O Rancher utiliza um sistema semelhante a um catálogo para importar pacotes de charts de repositórios e, em seguida, usa esses charts para implantar apps Kubernetes personalizados ou ferramentas do Rancher, como Monitoramento ou Istio. As ferramentas do Rancher vêm como repositórios pré-carregados que são implantados como charts do Helm independentes. Quaisquer repositórios adicionais são adicionados apenas ao cluster atual.

[#_catalogs_apps_and_the_rancher_ui]
=== Catálogos, Apps e a UI do Rancher

xref:[Rancher v2.4 e anteriores], repositórios de apps prontos para implantação eram chamados de "catálogos". Esses repositórios eram gerenciados através da seção *Catálogos* da UI.

O Rancher v2.5 substituiu o antigo sistema de catálogo por um novo recurso *Apps & Marketplace*.

Desde o Rancher v2.6.5, o recurso *Apps & Marketplace* é chamado *Apps* na UI.

[#_versioning_scheme]
=== Esquema de Versionamento

O esquema de versionamento dos charts de recursos do Rancher é centrado na versão principal dos charts e na anotação `+up` para charts upstream, quando aplicável.

*Versão Principal:* As versões principais dos charts de recursos estão ligadas a versões menores específicas do Rancher. Quando você fizer upgrade para uma nova versão menor do Rancher, deve garantir que todos os seus charts de recursos também sejam atualizados para a linha de lançamento correta do chart.

*Charts baseados em upstream:* Ao fazer upgrade, certifique-se de que a versão do chart upstream seja compatível com a sua versão do Rancher. A anotação `+up` para o chart indica qual versão upstream o chart do Rancher está rastreando. Por exemplo, `100.x.x+up16.6.0` para Monitoramento rastreia o kube-prometheus-stack upstream `16.6.0` com alguns patches adicionais do Rancher.

Ao fazer upgrade de versões do Rancher, não faça downgrade da versão do chart que você está usando. Por exemplo, se você estiver usando uma versão do Monitoramento que é posterior a `16.6.0` no Rancher v2.5, você não deve fazer upgrade para `100.x.x+up16.6.0`. Em vez disso, você deve fazer upgrade para a versão apropriada na próxima versão.

[#_prerelease_versions]
==== Versões de Pré-lançamento

Pré-lançamentos aderem à https://semver.org/#spec-item-9[especificação] definida por https://semver.org/[Versionamento Semântico 2.0.0]. Por exemplo, um chart Helm com uma versão de `0.1.3-dev.12ab4f` é considerado um pré-lançamento. Versões de pré-lançamento não são exibidas por padrão e devem ser configuradas para isso.

Para exibir versões de pré-lançamento:

. Clique no seu avatar de usuário no canto superior direito.
. Clique em *Preferências*.
. Em *Charts Helm*, selecione *Incluir Versões de Pré-lançamento*.

[#_access_charts]
== Acessar Charts

A página *Charts* contém todos os charts do Rancher, Parceiros e Personalizados. Você pode filtrar charts selecionando o menu suspenso mais à esquerda:

* Ferramentas do Rancher, como Logging ou Monitoramento, estão listadas sob o rótulo *Rancher*.
* Charts de Parceiros estão sob o rótulo *Parceiros*.
* Charts personalizados estão listados sob o nome de seu respectivo repositório.

Todos os três tipos de charts são implantados e gerenciados da mesma forma.

[NOTE]
====

Apps gerenciados pelo Cluster Manager (a visão global na interface do usuário legada do Rancher) continuam a ser gerenciados apenas pelo Cluster Manager, e apps gerenciados com *Apps* na nova interface devem ser gerenciados apenas por *Apps*.
====


Para acessar a página *Charts*:

. Clique em *☰ > Gerenciamento de Cluster*.
. Encontre o nome do cluster cujos charts você deseja acessar. Clique em *Explorar* no final da linha do cluster.
. No menu de navegação à esquerda no *Painel do Cluster*, clique em menu:Apps[Charts].

[#_manage_repositories]
== Gerenciar Repositórios

A página *Repositórios* lista seus repositórios Helm. Isso inclui endpoints Helm tradicionais que possuem um index.yaml e repositórios Git que são clonados e apontam para um branch específico. Para usar charts personalizados, adicione seu repositório aqui. Depois de adicionar um repositório, você pode acessar charts personalizados na página *Charts*, listados sob o nome do repositório.

Para acessar a página *Repositórios*:

. Clique em *☰ > Gerenciamento de Cluster*.
. Encontre o nome do cluster cujos repositórios você deseja acessar. Clique em *Explorar* no final da linha do cluster.
. No menu de navegação à esquerda no *Painel do Cluster*, clique em menu:Apps[Repositórios].

[#_add_custom_git_repositories]
=== Adicionar Repositórios Git Personalizados

Para adicionar um repositório Git personalizado que contém seus charts Helm ou definições de modelo de cluster:

. Clique em *☰ > Gerenciamento de Cluster*.
. Encontre o nome do cluster cujos repositórios você deseja acessar. Clique em *Explorar* no final da linha do cluster.
. No menu de navegação à esquerda no *Painel do Cluster*, clique em menu:Apps[Repositórios].
. Clique em *Criar*.
. Selecione o alvo, *Repositório Git contendo gráfico Helm...*.
. Você deve inserir um nome e uma URL de repositório Git. Os outros campos, incluindo a descrição, são opcionais. Insira um nome de branch alternativo se você não quiser puxar de qualquer branch que o proprietário do repositório definiu como padrão. Normalmente, o branch padrão é nomeado como `main` ou `master`.
. Clique em *Criar* para adicionar o repositório.

Após adicionar um repositório de charts ao Rancher, ele se torna disponível imediatamente.

[#_add_custom_helm_chart_repositories]
=== Adicionar Repositórios de Charts Helm Personalizados

Você pode adicionar seus próprios repositórios de charts Helm para fornecer pacotes de charts ao Rancher. Você pode usar qualquer servidor HTTP, desde que o servidor possa responder a solicitações GET e servir arquivos YAML e tarballs.

Para mais informações sobre repositórios de charts Helm, consulte a https://helm.sh/docs/topics/chart_repository/[documentação oficial do Helm].

Para adicionar um repositório de charts Helm personalizado ao Rancher:

. Clique em *☰ > Gerenciamento de Cluster*.
. Encontre o nome do cluster cujos repositórios você deseja acessar. Clique em *Explorar* no final da linha do cluster.
. No menu de navegação à esquerda no *Painel do Cluster*, clique em menu:Apps[Repositórios].
. Clique em *Criar*.
. Selecione o destino, *URL http(s) para um índice gerado pelo Helm*.
. Digite um nome de repositório e o endereço URL do índice do repositório de charts.
. Clique em *Criar* para adicionar o repositório.

[#_add_private_git_helm_chart_repositories]
=== Adicionar Repositórios Privados de Git/Charts Helm

Você pode adicionar repositórios Git ou charts Helm privados com credenciais de chave SSH ou um segredo de autenticação básica HTTP, como um nome de usuário e senha.

[#_add_a_private_ca_to_repositories]
=== Adicionar uma CA Privada aos Repositórios

Para adicionar uma CA privada aos repositórios de charts Helm, você deve adicionar uma cópia codificada em base64 do certificado CA no formato DER ao `spec.caBundle field` do repositório de charts, como `openssl x509 -outform der -in ca.pem | base64 -w0`. As instruções são as mesmas para repositórios baseados em Git e baseados em HTTP:

. Clique *☰*. Em *Explorar Cluster* no menu de navegação à esquerda, selecione um cluster.
. No menu de navegação à esquerda no *Painel do Cluster*, clique em menu:Apps[Repositórios].
. Encontre a linha associada ao repositório baseado em Git ou HTTP ao qual você deseja adicionar uma CA privada e clique em *⋮ > Editar YAML*.
. Defina o valor de `caBundle`, como no seguinte exemplo:

[,yaml]
----
    [...]
    spec:
      caBundle:
    MIIFXzCCA0egAwIBAgIUWNy8WrvSkgNzV0zdWRP79j9cVcEwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtNeU9yZywgSW5jLjENMAsGA1UEAwwEcm9vdDAeFw0yMTEyMTQwODMyMTdaFw0yNDEwMDMwODMyMT
    ...
    nDxZ/tNXt/WPJr/PgEB3hQdInDWYMg7vGO0Oz00G5kWg0sJ0ZTSoA10ZwdjIdGEeKlj1NlPyAqpQ+uDnmx6DW+zqfYtLnc/g6GuLLVPamraqN+gyU8CHwAWPNjZonFN9Vpg0PIk1I2zuOc4EHifoTAXSpnjfzfyAxCaZsnTptimlPFJJqAMj+FfDArGmr4=
    [...]
----

[NOTE]
.Repositórios de charts Helm com autenticação
====

O Repo.Spec contém um valor de `disableSameOriginCheck`. Esse valor permite que você ignore as verificações de mesma origem, enviando as informações de autenticação do repositório como um cabeçalho de autenticação básica com todas as chamadas de API. Isso não é recomendado, mas pode ser usado como uma solução temporária em casos de repositórios de charts Helm não padrão, como aqueles que têm redirecionamentos para uma URL de origem diferente.

Para usar este recurso em um repositório de charts Helm existente, siga os passos anteriores até editar o YAML. Na parte `spec` do arquivo YAML, adicione `disableSameOriginCheck` e defina como `true`.

[,yaml]
----
[...]
spec:
  disableSameOriginCheck: true
[...]
----
====


[#_add_custom_oci_chart_repositories]
=== Adicionar Repositórios de Charts OCI Personalizados

O Helm v3 introduziu o armazenamento de Helm charts como artefatos da https://opencontainers.org/about/overview/[Iniciativa de Contêineres Abertos (OCI)] em registros de contêiner. Com o Rancher v2.9.0, você pode adicionar https://helm.sh/docs/topics/registries/[repositórios de charts Helm baseados em OCI] ao lado de repositórios baseados em HTTP e Git. Isso significa que você pode implantar apps que estão armazenados como artefatos OCI. Para mais informações, veja {xref-oci-repo}[Usando Repositórios de Helm Chart OCI].

[#_helm_compatibility]
=== Compatibilidade do Helm

Apenas charts compatíveis com Helm 3 são suportados.

[#_refresh_chart_repositories]
=== Atualizar Repositórios de Chart

O botão *Atualizar* pode ser usado para sincronizar alterações dos repositórios de Helm chart selecionados na página *Repositórios*.

Para atualizar um repositório de chart:

. Clique em *☰ > Gerenciamento de Cluster*.
. Encontre o nome do cluster cujos repositórios você deseja acessar. Clique em *Explorar* no final da linha do cluster.
. No menu de navegação à esquerda no *Painel do Cluster*, clique em menu:Apps[Repositórios].
. Use o alternador ao lado do campo *Estado* para selecionar todos os repositórios ou alternar repositórios de chart especificados para sincronizar alterações.
. Clique em *Atualizar*.
. O *⋮* no final de cada linha de repositório de chart também inclui uma opção *Atualizar*, que pode ser clicada para atualizar o respectivo repositório.

Instalações do Rancher não Airgap, ao atualizar, refletirão imediatamente quaisquer alterações no repositório de chart e você verá o campo *Estado* para repositórios atualizados mudar de `In Progress` para `Active` uma vez que a ação seja concluída.

Instalações air gap onde o Rancher está configurado para usar a cópia embalada dos charts do sistema Helm ({xref-air-gap-rancher-ha}#_opções_de_chart_helm_para_instalações_air_gap[`useBundledSystemChart=true`]) só se referirão ao repositório https://github.com/rancher/system-charts[chart-do-sistema] que vem incluído e não poderão ser atualizados ou sincronizados.

[#_refresh_interval]
==== Renovar Intervalo

O Rancher v2.10.0 adiciona o campo `refreshInterval` ao CRD `ClusterRepo`. O valor padrão é 3600 segundos, o que significa que o Rancher sincroniza cada repositório de Helm a cada 3600 segundos.

Para modificar o intervalo de atualização de um repositório de chart:

. Clique em **☰ > Gerenciamento de Cluster**.
. Encontre o nome do cluster cujos repositórios você deseja acessar. Clique em **Explorar** no final da linha do cluster.
. No menu de navegação à esquerda no **Painel do Cluster**, clique em **Apps > Repositórios**.
. Encontre o repositório que você deseja modificar e clique em **⋮ > Editar YAML**.
. Defina o campo **refreshInterval** em **Spec** para o valor desejado em segundos.
. Clique em **Salvar**.

[#_enable_disable_helm_chart_repositories]
=== Habilitar/Desabilitar Repositórios de Helm Chart

O Rancher v2.10.0 adiciona a capacidade de habilitar e desabilitar repositórios de Helm. Os repositórios de Helm estão habilitados por padrão.

Para desabilitar um repositório de chart:

. Clique em **☰ > Gerenciamento de Cluster**.
. Encontre o nome do cluster cujos repositórios você deseja acessar. Clique em **Explorar** no final da linha do cluster.
. No menu de navegação à esquerda no **Painel do Cluster**, clique em **Apps > Repositórios**.
. Encontre o repositório que você deseja desabilitar e clique em **⋮ > Editar YAML**.
. Defina o campo **Enabled** em **Spec** para **false**.
. Clique em **Salvar**.
. Quando você desabilita um repositório, as atualizações são desativadas e novas alterações no clusterRepo não são aplicadas.

Para habilitar um repositório de chart:

. Clique em **☰ > Gerenciamento de Cluster**.
. Encontre o nome do cluster cujos repositórios você deseja acessar. Clique em **Explorar** no final da linha do cluster.
. No menu de navegação à esquerda no **Painel do Cluster**, clique em **Apps > Repositórios**.
. Encontre o repositório que você deseja habilitar e clique em **⋮ > Editar YAML**.
. Defina o campo **Enabled** em **Spec** para **true**.
. Clique em **Salvar**.

[#_deploy_and_upgrade_charts]
== Implantar e Atualizar Charts

Para instalar e implantar um chart:

. Clique em *☰ > Gerenciamento de Cluster*.
. Encontre o nome do cluster cujos repositórios você deseja acessar. Clique em *Explorar* no final da linha do cluster.
. No menu de navegação à esquerda no *Painel do Cluster*, clique em menu:Apps[Charts].
. Selecione um chart e clique em *Instalar*.

Os charts do Rancher e dos parceiros podem ter configurações extras disponíveis através de páginas personalizadas ou arquivos questions.yaml. No entanto, todas as instalações de charts podem modificar o values.yaml e outras configurações básicas. Após clicar em *Instalar*, um trabalho de operação do Helm é implantado e o console para o trabalho é exibido.

Para ver todas as alterações recentes, clique em menu:Apps[Operações Recentes] no menu de navegação à esquerda. A partir daí, você pode visualizar as chamadas, condições, eventos e logs.

Após instalar um chart, você pode visualizá-lo clicando em menu:Apps[Aplicativos Instalados] no menu de navegação à esquerda. Você pode atualizar ou excluir a instalação e ver mais detalhes. A atualização utiliza os mesmos formulários e valores que você viu durante a instalação inicial.

A maioria das ferramentas do Rancher possui páginas adicionais localizadas na barra de ferramentas abaixo da seção *Apps* para ajudar a gerenciar e usar os recursos. Essas páginas incluem links para painéis, formulários para adicionar Recursos Personalizados facilmente e informações adicionais.

[CAUTION]
====

Se você estiver atualizando seu chart usando *Personalizar opções do Helm antes da atualização*, e seu chart contiver campos imutáveis, usar a opção `--force` pode resultar em erros. Isso ocorre porque alguns objetos no Kubernetes não podem ser alterados após serem criados. Para evitar esse erro:

* Use a opção de fazer upgrade padrão (ou seja, não use `--force`).
* Desinstale o chart existente e instale o chart atualizado.
* Exclua os recursos com campos imutáveis do cluster antes de realizar um upgrade forçado.
====


[#_legacy_apps]
=== Aplicativos Legados

O botão de atualização não está disponível para aplicativos legados na página menu:Apps[Aplicativos Instalados].

Se você quiser fazer upgrade de um aplicativo legado instalado, o {xref-experimental-features}[sinalizador de recurso legado] deve estar ativado. Esse sinalizador é ativado automaticamente se você já tinha um aplicativo legado em execução antes de fazer upgrade do Rancher.

. Ative o {xref-experimental-features}[sinalizador de recurso legado], se ainda não estiver ativado.
. Clique em *☰ > Gerenciamento de Cluster*.
. Encontre o nome do cluster cujos aplicativos você deseja acessar. Clique em *Explorar* no final da linha do cluster.
. Clique em menu:Legado[Projeto> Aplicativos].

Se você não ver *Apps* listado sob menu:Legado[Projeto], clique na barra de pesquisa de projeto/namespace na navegação superior e selecione o projeto relevante no menu suspenso.

Para fazer upgrade de aplicativos legados de múltiplos clusters:

. Clique *☰*.
. Sob *Aplicativos Legados*, clique em *Aplicativos de Múltiplos Clusters*.

[#_chart_specific_information]
=== Informações Específicas do Chart

[#_sriov_chart_deprecation_and_migration]
==== Depreciação e Migração do Chart sriov

O chart `sriov` (operador de rede SR-IOV) do repositório Rancher Charts está descontinuado e será removido no Rancher v2.10. Por favor, migre para o chart `sriov-network-operator` do repositório SUSE Edge (https://github.com/suse-edge/charts) em vez disso.

Para migrar, siga estas etapas:

. Adicione o repositório SUSE Edge ao seu cluster seguindo os passos em <<_add_custom_git_repositories,Adicionar Repositórios Git Personalizados>>.
. Para o campo *URL do Repositório Git*, insira `https://github.com/suse-edge/charts`.
. Clique em *Criar*.
. No menu de navegação à esquerda no *Painel do Cluster*, clique em menu:Apps[Charts].
. Encontre o chart `sriov-network-operator` e clique nele.
. Clique em *Instalar*.
. No campo *Nome*, insira o mesmo nome que você usou para a instalação do chart `sriov` existente.
. Clique em *Próximo*.
. Clique em *Instalar*.

*Resultado:* O Rancher redireciona para a página *Aplicativos Instalados* onde sua instalação existente entra no estado *Atualizando*. A migração está completa quando entra no estado *Implantado*.

[#_limitations]
== Limitações

* Aplicativos de painel ou charts de recursos do Rancher não podem ser instalados usando o Rancher CLI.
* Ao determinar a versão mais recente a ser exibida para a coluna *Fazer upgrade disponível* na página menu:Aplicativos[Aplicativos Instalados], em vez de considerar apenas as versões do chart Helm do repositório de onde foi instalada, o Rancher considera as versões do chart Helm de todos os repositórios no cluster.
+
Por exemplo, suponha que você instale `cert-manager` v1.13.0 do repositório A, onde v1.14.0 é agora a versão mais recente disponível. Nesse caso, você espera que *Atualizável* exiba v1.14.0. No entanto, se o cluster também tiver acesso ao repositório B onde v1.15.0 de `cert-manager` está disponível, então *Atualizável* exibe v1.15.0, mesmo que a instalação original tenha usado o repositório A.
