= Charts y aplicaciones de Helm
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/helm-charts-in-rancher/index.adoc 
:product-path: cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-air-gap-rancher-ha: xref:installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc
:xref-oci-repo: xref:cluster-admin/helm-charts-in-rancher/oci-repositories.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-air-gap-rancher-ha: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha.adoc
:xref-oci-repo: xref:how-to-guides/new-user-guides/helm-charts-in-rancher/oci-repositories.adoc
endif::[]

En esta sección, aprenderá a gestionar los repositorios de charts de Helm y las aplicaciones en Rancher.

[#_how_helm_charts_work_in_rancher]
== Cómo funcionan los charts de Helm en Rancher

Los repositorios de charts de Helm en Rancher se gestionan utilizando *Apps*.

Rancher utiliza un sistema similar a un catálogo para importar paquetes de charts de los repositorios y luego utiliza esos charts para desplegar aplicaciones personalizadas de Kubernetes o herramientas de Rancher como Monitoring o Istio. Las herramientas de Rancher vienen como repositorios pre-cargados que se despliegan como charts de Helm independientes. Cualquier repositorio adicional solo se añade al clúster actual.

[#_catalogs_apps_and_the_rancher_ui]
=== Catálogos, Apps y la Interfaz de Usuario de Rancher

En xref:[Rancher v2.4 y versiones anteriores], los repositorios de aplicaciones listas para desplegar se llamaban "catálogos". Estos repositorios se gestionaban a través de la sección *Catálogos* de la interfaz de usuario.

Rancher v2.5 reemplazó el antiguo sistema de catálogos con una nueva función de *Apps & Marketplace*.

Desde Rancher v2.6.5, la función de *Apps & Marketplace* se llama *Apps* en la interfaz de usuario.

[#_versioning_scheme]
=== Esquema de versionado

El esquema de versionado de charts de características de Rancher se centra en la versión principal de los charts y la anotación `+up` para charts upstream, cuando sea aplicable.

*Versión Principal:* Las versiones principales de los charts de características están vinculadas a versiones menores particulares de Rancher. Cuando actualice a una nueva versión menor de Rancher, debe asegurarse de que todos sus charts de características también se actualicen a la línea de lanzamiento correcta para el chart.

*Charts basados en upstream:* Cuando actualices, asegúrate de que la versión del chart upstream sea compatible con tu versión de Rancher. La anotación `+up` para el chart indica qué versión upstream está siguiendo el chart de Rancher. Por ejemplo, `100.x.x+up16.6.0` para Monitoring sigue el kube-prometheus-stack upstream `16.6.0` con algunos parches adicionales de Rancher.

Al actualizar las versiones de Rancher, no debes degradar la versión del chart que estás utilizando. Por ejemplo, si estás utilizando una versión de Monitoring que es posterior a `16.6.0` en Rancher v2.5, no deberías actualizar a `100.x.x+up16.6.0`. En su lugar, deberías actualizar a la versión apropiada en el próximo lanzamiento.

[#_prerelease_versions]
==== Versiones de pre-lanzamiento

Las versiones de prueba se adhieren a https://semver.org/#spec-item-9[la especificación] definida por https://semver.org/[Semantic Versioning 2.0.0]. Por ejemplo, un chart de Helm con una versión de `0.1.3-dev.12ab4f` se considera una versión de pre-lanzamiento. Las versiones de pre-lanzamiento no se muestran por defecto y deben configurarse para hacerlo.

Para mostrar versiones de pre-lanzamiento:

. Haz clic en tu avatar de usuario en la esquina superior derecha.
. Haz clic en *Preferencias*.
. Bajo *Charts de Helm*, selecciona *Incluir versiones de pre-lanzamiento*.

[#_access_charts]
== Acceder a Charts

La página *Charts* contiene todos los charts de Rancher, Partner y personalizados. Puedes filtrar charts seleccionando el menú desplegable más a la izquierda:

* Las herramientas de Rancher, como Logging o Monitoring, se enumeran bajo la etiqueta *Rancher*.
* Los charts de Partner están bajo la etiqueta *Partners*.
* Los charts personalizados se enumeran bajo el nombre de su respectivo repositorio.

Los tres tipos de charts se implementan y gestionan de la misma manera.

[NOTE]
====

Las aplicaciones gestionadas por el Administrador de Clúster (la vista global en la interfaz de usuario heredada de Rancher) continúan siendo gestionadas únicamente por el Administrador de Clúster, y las aplicaciones gestionadas con *Apps* en la nueva interfaz deben ser gestionadas solo por *Apps*.
====


Para acceder a la página de *Charts*:

. Haz clic en *☰ > Gestión de Clústeres*.
. Encuentra el nombre del clúster a cuyos gráficos deseas acceder. Haz clic en *Explorar* al final de la fila del clúster.
. En el menú de navegación de la izquierda en el *Tablero del Clúster*, haz clic en menu:Apps[Charts].

[#_manage_repositories]
== Gestionar Repositorios

La página de *Repositories* lista tus repositorios de Helm. Estos incluyen puntos finales de Helm tradicionales que tienen un index.yaml, y repositorios de Git que son clonados y apuntan a una rama específica. Para usar charts personalizados, añade tu repositorio aquí. Después de añadir un repositorio, puedes acceder a charts personalizados en la página de *Charts*, listados bajo el nombre del repositorio.

Para acceder a la página de *Repositories*:

. Haz clic en *☰ > Gestión de Clústeres*.
. Encuentra el nombre del clúster a cuyos repositorios deseas acceder. Haz clic en *Explorar* al final de la fila del clúster.
. En el menú de navegación de la izquierda en el *Tablero del Clúster*, haz clic en menu:Apps[Repositories].

[#_add_custom_git_repositories]
=== Añadir Repositorios Git Personalizados

Para añadir un repositorio Git personalizado que contenga tus charts de Helm o definiciones de plantillas de clúster:

. Haz clic en *☰ > Gestión de Clústeres*.
. Encuentra el nombre del clúster a cuyos repositorios deseas acceder. Haz clic en *Explorar* al final de la fila del clúster.
. En el menú de navegación de la izquierda en el *Tablero del Clúster*, haz clic en menu:Apps[Repositories].
. Haga clic en *Crear*.
. Selecciona el objetivo, *Repositorio Git que contiene el chart de Helm...*.
. Debes ingresar un nombre y una URL de repositorio Git. Los otros campos, incluida la descripción, son opcionales. Ingresa un nombre de rama alternativa si no deseas extraer de la rama que el propietario del repositorio ha establecido como predeterminada. Por lo general, la rama predeterminada se llama `main` o `master`.
. Haz clic en *Crear* para añadir el repositorio.

Después de añadir un repositorio de charts a Rancher, estará disponible de inmediato.

[#_add_custom_helm_chart_repositories]
=== Añadir Repositorios de Charts Helm Personalizados

Puedes añadir tus propios repositorios de charts Helm para servir paquetes de charts a Rancher. Puedes utilizar cualquier servidor HTTP, siempre que el servidor pueda responder a solicitudes GET y servir archivos YAML y archivos .tar.

Para más información sobre los repositorios de charts Helm, consulta la https://helm.sh/docs/topics/chart_repository/[documentación oficial de Helm].

Para añadir un repositorio de charts Helm personalizado a Rancher:

. Haz clic en *☰ > Gestión de Clústeres*.
. Encuentra el nombre del clúster a cuyos repositorios deseas acceder. Haz clic en *Explorar* al final de la fila del clúster.
. En el menú de navegación de la izquierda en el *Tablero del Clúster*, haz clic en menu:Apps[Repositories].
. Haga clic en *Crear*.
. Selecciona el destino, *URL http(s) a un índice generado por Helm*.
. Introduce un nombre de repositorio y la dirección URL del índice del repositorio de gráficos.
. Haz clic en *Crear* para añadir el repositorio.

[#_add_private_git_helm_chart_repositories]
=== Añadir Repositorios de Charts/Helm Privados

Puedes añadir repositorios privados de Git o charts Helm con credenciales de clave SSH o un secreto de autenticación básica HTTP, como un nombre de usuario y una contraseña.

[#_add_a_private_ca_to_repositories]
=== Añadir una CA Privada a los Repositorios

Para añadir una CA privada a los repositorios de charts Helm, debes añadir una copia codificada en base64 del certificado CA en formato DER al `spec.caBundle field` del repositorio de charts, como `openssl x509 -outform der -in ca.pem | base64 -w0`. Las instrucciones son las mismas para los repositorios basados en Git y los repositorios basados en HTTP:

. Haz clic en *☰*. Bajo *Explorar Clúster* en el menú de navegación izquierdo, selecciona un clúster.
. En el menú de navegación de la izquierda en el *Tablero del Clúster*, haz clic en menu:Apps[Repositories].
. Encuentra la fila asociada con el repositorio basado en Git o basado en HTTP al que deseas añadir una CA privada, y haz clic en *⋮ > Editar YAML*.
. Establece el valor de `caBundle`, como en el siguiente ejemplo:

[,yaml]
----
    [...]
    spec:
      caBundle:
    MIIFXzCCA0egAwIBAgIUWNy8WrvSkgNzV0zdWRP79j9cVcEwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtNeU9yZywgSW5jLjENMAsGA1UEAwwEcm9vdDAeFw0yMTEyMTQwODMyMTdaFw0yNDEwMDMwODMyMT
    ...
    nDxZ/tNXt/WPJr/PgEB3hQdInDWYMg7vGO0Oz00G5kWg0sJ0ZTSoA10ZwdjIdGEeKlj1NlPyAqpQ+uDnmx6DW+zqfYtLnc/g6GuLLVPamraqN+gyU8CHwAWPNjZonFN9Vpg0PIk1I2zuOc4EHifoTAXSpnjfzfyAxCaZsnTptimlPFJJqAMj+FfDArGmr4=
    [...]
----

[NOTE]
.Repositorios de charts Helm con autenticación
====

El Repo.Spec contiene un valor de `disableSameOriginCheck`. Este valor te permite omitir las comprobaciones de mismo origen, enviando la información de autenticación del repositorio como un encabezado de autenticación básica con todas las llamadas a la API. Esto no se recomienda, pero se puede utilizar como una solución temporal en casos de repositorios de charts Helm no estándar, como aquellos que tienen redirecciones a una URL de origen diferente.

Para utilizar esta función en un repositorio de charts Helm existente, sigue los pasos anteriores hasta editar el YAML. En la parte `spec` del archivo YAML, añade `disableSameOriginCheck` y configúralo a `true`.

[,yaml]
----
[...]
spec:
  disableSameOriginCheck: true
[...]
----
====


[#_add_custom_oci_chart_repositories]
=== Añadir Repositorios de Charts OCI Personalizados

Helm v3 introdujo el almacenamiento de charts Helm como artefactos de https://opencontainers.org/about/overview/[Iniciativa de Contenedores Abiertos (OCI)] en registros de contenedores. Con Rancher v2.9.0, puede añadir https://helm.sh/docs/topics/registries/[repositorios de gráficos de Helm basados en OCI] junto a repositorios basados en HTTP y Git. Esto significa que puede desplegar apps que están almacenadas como artefactos OCI. Para más información, consulte {xref-oci-repo}[Uso de Repositorios de Gráficos de Helm OCI].

[#_helm_compatibility]
=== Compatibilidad con Helm

Solo se admiten gráficos compatibles con Helm 3.

[#_refresh_chart_repositories]
=== Actualizar Repositorios de Gráficos

El botón *Actualizar* se puede utilizar para sincronizar cambios de los repositorios de gráficos de Helm seleccionados en la página *Repositorios*.

Para actualizar un repositorio de gráficos:

. Haz clic en *☰ > Gestión de Clústeres*.
. Encuentra el nombre del clúster cuyos repositorios deseas acceder. Haz clic en *Explorar* al final de la fila del clúster.
. En el menú de navegación de la izquierda en el *Tablero del Clúster*, haz clic en menu:Aplicaciones[Repositorios].
. Utilice el interruptor junto al campo *Estado* para seleccionar todos los repositorios, o active los repositorios de gráficos especificados para sincronizar cambios.
. Haga clic en *Actualizar*.
. El *⋮* al final de cada fila de repositorio de gráficos también incluye una opción de *Actualizar*, que se puede hacer clic para actualizar el repositorio respectivo.

Las instalaciones de Rancher que no están en un entorno aislado, al actualizar, reflejarán inmediatamente cualquier cambio en el repositorio de gráficos, y verás que el campo *Estado* de los repositorios actualizados se mueve de `In Progress` a `Active` una vez completada la acción.

Las instalaciones en entorno aislado donde Rancher está configurado para usar la copia empaquetada de gráficos del sistema de Helm ({xref-air-gap-rancher-ha}#_opciones_de_gráficos_de_helm_para_instalaciones_air_gap[`useBundledSystemChart=true`]) solo se referirán al repositorio https://github.com/rancher/system-charts[system-chart] que viene empaquetado y no podrá ser actualizado o sincronizado.

[#_refresh_interval]
==== Intervalo de renovación

Rancher v2.10.0 añade el campo `refreshInterval` al CRD `ClusterRepo`. El valor predeterminado es 3600 segundos, lo que significa que Rancher sincroniza cada repositorio de Helm cada 3600 segundos.

Para modificar el intervalo de actualización de un repositorio de gráficos:

. Haz clic en **☰ > Gestión de Clústeres**.
. Encuentra el nombre del clúster cuyos repositorios deseas acceder. Haz clic en **Explorar** al final de la fila del clúster.
. En el menú de navegación de la izquierda en el **Tablero del Clúster**, haz clic en **Aplicaciones > Repositorios**.
. Encuentra el repositorio que deseas modificar y haz clic en **⋮ > Editar YAML**.
. Establece el campo **refreshInterval** bajo **Spec** al valor deseado en segundos.
. Haz clic en **Guardar**.

[#_enable_disable_helm_chart_repositories]
=== Habilitar/Deshabilitar Repositorios de Gráficos de Helm

Rancher v2.10.0 añade la capacidad de habilitar y deshabilitar repositorios de Helm. Los repositorios de Helm están habilitados por defecto.

Para deshabilitar un repositorio de gráficos:

. Haz clic en **☰ > Gestión de Clústeres**.
. Encuentra el nombre del clúster a cuyos repositorios deseas acceder. Haz clic en **Explorar** al final de la fila del clúster.
. En el menú de navegación de la izquierda en el **Tablero del Clúster**, haz clic en **Aplicaciones > Repositorios**.
. Encuentra el repositorio que deseas deshabilitar y haz clic en **⋮ > Editar YAML**.
. Establece el campo **Enabled** bajo **Spec** a **false**.
. Haz clic en **Guardar**.
. Cuando deshabilitas un repositorio, las actualizaciones se deshabilitan y los nuevos cambios en el clusterRepo no se aplican.

Para habilitar un repositorio de gráficos:

. Haz clic en **☰ > Gestión de Clústeres**.
. Encuentra el nombre del clúster a cuyos repositorios deseas acceder. Haz clic en **Explorar** al final de la fila del clúster.
. En el menú de navegación de la izquierda en el **Tablero del Clúster**, haz clic en **Aplicaciones > Repositorios**.
. Encuentra el repositorio que deseas deshabilitar y haz clic en **⋮ > Editar YAML**.
. Establece el campo **Enabled** bajo **Spec** a **true**.
. Haz clic en **Guardar**.

[#_deploy_and_upgrade_charts]
== Desplegar y Actualizar Gráficos

Para instalar y desplegar un gráfico:

. Haz clic en *☰ > Gestión de Clústeres*.
. Encuentra el nombre del clúster a cuyos repositorios deseas acceder. Haz clic en *Explorar* al final de la fila del clúster.
. En el menú de navegación de la izquierda en el *Tablero del Clúster*, haz clic en menu:Aplicaciones[Gráficos].
. Selecciona un gráfico y haz clic en *Instalar*.

Los gráficos de Rancher y de socios pueden tener configuraciones adicionales disponibles a través de páginas personalizadas o archivos questions.yaml. Sin embargo, todas las instalaciones de gráficos pueden modificar el values.yaml y otros ajustes básicos. Después de hacer clic en *Instalar*, se despliega un trabajo de operación de Helm y se muestra la consola para el trabajo.

Para ver todos los cambios recientes, haz clic en menu:Aplicaciones[Operaciones Recientes] en el menú de navegación de la izquierda. Desde allí, puedes ver las llamadas, condiciones, eventos y registros.

Después de instalar un gráfico, puedes verlo haciendo clic en menu:Aplicaciones[Aplicaciones instaladas] en el menú de navegación de la izquierda. Puedes actualizar o eliminar la instalación y ver más detalles. La actualización utiliza los mismos formularios y valores que viste durante la instalación inicial.

La mayoría de las herramientas de Rancher tienen páginas adicionales ubicadas en la barra de herramientas debajo de la sección *Aplicaciones* para ayudar a gestionar y utilizar las funciones. Estas páginas incluyen enlaces a paneles, formularios para añadir fácilmente Recursos Personalizados y información adicional.

[CAUTION]
====

Si estás actualizando tu gráfico utilizando *Personalizar opciones de Helm antes de actualizar versión*, y tu gráfico contiene campos inmutables, usar la opción `--force` puede resultar en errores. Esto se debe a que algunos objetos en Kubernetes no pueden ser cambiados una vez que han sido creados. Para evitar este error:

* Utiliza la opción de actualizar versión predeterminada (es decir, no uses `--force`).
* Desinstala el gráfico existente e instala el gráfico actualizado.
* Elimina los recursos con campos inmutables del clúster antes de realizar una actualización forzada.
====


[#_legacy_apps]
=== Aplicaciones heredadas

El botón de actualización no está disponible para aplicaciones heredadas en la página menu:Aplicaciones[Aplicaciones instaladas].

Si deseas actualizar una aplicación heredada instalada, el {xref-experimental-features}[indicador de función heredada] debe estar activado. Este indicador se activa automáticamente si tenías una aplicación heredada en funcionamiento antes de actualizar Rancher.

. Activa el {xref-experimental-features}[indicador de función heredada], si no está activado ya.
. Haz clic en *☰ > Gestión de Clústeres*.
. Encuentra el nombre del clúster cuyas aplicaciones deseas acceder. Haz clic en *Explorar* al final de la fila del clúster.
. Haz clic en menu:Heredado[Proyecto> Aplicaciones].

Si no ves *Aplicaciones* listado bajo menu:Heredado[Proyecto], haz clic en la barra de búsqueda de proyectos/espacios de nombres en la navegación superior y selecciona el proyecto relevante del menú desplegable.

Para actualizar aplicaciones de múltiples clústeres heredadas:

. Haz clic en *☰*.
. Bajo *Aplicaciones heredadas*, haz clic en *Aplicaciones de múltiples clústeres*.

[#_chart_specific_information]
=== Información específica del gráfico

[#_sriov_chart_deprecation_and_migration]
==== Deprecación y migración del gráfico sriov

El gráfico `sriov` (operador de red SR-IOV) del repositorio de gráficos de Rancher ha quedado obsoleto y se eliminará en Rancher v2.10. Por favor, migra al gráfico `sriov-network-operator` del repositorio de SUSE Edge (https://github.com/suse-edge/charts) en su lugar.

Para migrar, sigue estos pasos:

. Añade el repositorio de SUSE Edge a tu clúster siguiendo los pasos en <<_add_custom_git_repositories,Añadir repositorios Git personalizados>>.
. Para el campo *URL del repositorio Git*, introduce `https://github.com/suse-edge/charts`.
. Haga clic en *Crear*.
. En el menú de navegación de la izquierda en el *Tablero del Clúster*, haz clic en menu:Aplicaciones[Gráficos].
. Encuentra el gráfico `sriov-network-operator` y haz clic en él.
. Haz clic en *Instalar*.
. En el campo *Nombre*, introduce el mismo nombre que usaste para tu instalación existente del gráfico `sriov`.
. Haga clic en *Siguiente*.
. Haz clic en *Instalar*.

*Resultado:* Rancher redirige a la página *Aplicaciones instaladas* donde tu instalación existente entra en el estado *Actualizando*. La migración se completa cuando entra en el estado *Desplegado*.

[#_limitations]
== limitaciones

* Las aplicaciones del panel o los gráficos de características de Rancher no se pueden instalar utilizando la CLI de Rancher.
* Al determinar la versión más reciente para mostrar en la columna *Actualizable* en la página menu:Aplicaciones[Aplicaciones instaladas], en lugar de considerar solo las versiones del gráfico de Helm del repositorio del que se instaló, Rancher considera las versiones del gráfico de Helm de todos los repositorios en el clúster.
+
Por ejemplo, supongamos que instalas `cert-manager` v1.13.0 desde el repositorio A, donde v1.14.0 es ahora la versión más reciente disponible. En este caso, esperas que *Actualizable* muestre v1.14.0. Sin embargo, si el clúster también tiene acceso al repositorio B donde v1.15.0 de `cert-manager` está disponible, entonces *Actualizable* muestra v1.15.0 a pesar de que la instalación original utilizó el repositorio A.
