= 为高可用性 {rke2-product-name} Kubernetes 集群设置基础设施
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-30
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc 
:product-path: installation-and-upgrade/infrastructure-setup/ha-rke2-kubernetes-cluster.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-setup-ec2-nodes: xref:installation-and-upgrade/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:installation-and-upgrade/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:installation-and-upgrade/infrastructure-setup/amazon-elb-load-balancer.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-setup-ec2-nodes: xref:how-to-guides/new-user-guides/infrastructure-setup/nodes-in-amazon-ec2.adoc
:xref-nginx-load-balancer: xref:how-to-guides/new-user-guides/infrastructure-setup/nginx-load-balancer.adoc
:xref-amazon-elb: xref:how-to-guides/new-user-guides/infrastructure-setup/amazon-elb-load-balancer.adoc
endif::[]


本教程旨在帮助您为 Rancher 管理服务器配置基础设施。

Rancher 专用 Kubernetes 集群的推荐基础设施取决于 Rancher 是安装在 RKE2 Kubernetes 集群、RKE Kubernetes 集群，还是单个 Docker 容器上。

[NOTE]
.重要说明：
====

这些节点必须位于同一区域。您可以将这些服务器放置在不同的可用区（数据中心）。
====


要在高可用性 RKE2 集群上安装 Rancher 管理服务器，我们建议设置以下基础设施：

* *三个 Linux 节点，* 通常是您选择的基础设施提供商中的虚拟机。
* *一个负载平衡器* 用于将流量引导到节点。
* *一个 DNS 记录* 用于将 URL 映射到负载均衡器。这将成为 Rancher 服务器的 URL，下游的 Kubernetes 集群需要访问它。

[#_1_set_up_linux_nodes]
== 1.设置 Linux 节点

确保您的节点满足 {xref-install-reqs}[操作系统、容器运行时、硬件和网络] 的一般安装要求。

有关设置 Linux 节点的一种示例，请参考此 {xref-setup-ec2-nodes}[教程]，以将节点设置为 Amazon EC2 中的实例。

[#_2_set_up_the_load_balancer]
== 2.设置负载平衡器

您还需要设置一个负载平衡器，将流量引导到所有节点上的 Rancher 副本。这将防止任何单个节点的故障导致与 Rancher 管理服务器的通信中断。

[WARNING]
====
*Ingress-NGINX EOL：*社区 `ingress-nginx` 控制器于 2026 年 3 月终止服务（EOL），并在 RKE2 v1.36 中被弃用。SUSE Rancher Prime 提供的 RKE2 版本将在 RKE2 v1.32、v1.33、v1.34、v1.35 和 v1.36 的整个生命周期内继续获得 `ingress-nginx` 支持和 CVE 修复（8+）。Traefik 是 SUSE Rancher RKE2 环境的推荐迁移路径，建议尽快进行迁移。有关更多详细信息，请参考 https://support.scc.suse.com/s/kb/Migrating-from-Ingress-NGINX-to-Traefik-in-a-Rancher-provisioned-RKE2-Cluster?language=en_US[从 Ingress NGINX 迁移到 Rancher 提供的 RKE2 集群中的 Traefik]。
====

当 Kubernetes 在后面的步骤中设置时，RKE2 工具将部署一个 Nginx Ingress 控制器。该控制器将在工作节点的 80 和 443 端口上侦听，响应发送到特定主机名的流量。

当 Rancher 安装完成（也在后面的步骤中）时，Rancher 系统会创建一个 Ingress 资源。该 Ingress 告诉 Nginx Ingress 控制器侦听发送到 Rancher 主机名的流量。当 Nginx Ingress 控制器接收到发送到 Rancher 主机名的流量时，将把该流量转发到集群中正在运行的 Rancher pod。

对于您的实现，请考虑您是否希望或需要使用 Layer-4 或 Layer-7 负载平衡器：

* *Layer-4 负载平衡器* 是两者中更简单的选择，您将 TCP 流量转发到您的节点。我们建议将您的负载平衡器配置为 Layer-4 负载平衡器，将流量转发到 Rancher 管理集群节点的 TCP/80 和 TCP/443 端口。集群上的 Ingress 控制器将把 HTTP 流量重定向到 HTTPS，并在 TCP/443 端口终止 SSL/TLS。Ingress 控制器将把流量转发到 Rancher 部署中的 Ingress pod 的 TCP/80 端口。
* *Layer-7 负载平衡器* 稍微复杂一些，但可以提供您可能需要的功能。例如，Layer-7 负载平衡器能够在负载平衡器处处理 TLS 终止，而不是让 Rancher 自行处理 TLS 终止。如果您希望在基础设施中集中管理 TLS 终止，这可能是有益的。Layer-7 负载平衡器还提供了让负载平衡器基于 HTTP 属性（如 cookies 等）做出决策的能力，而 Layer-4 负载平衡器无法处理这些。如果您决定在 Layer-7 负载平衡器上终止 SSL/TLS 流量，则在后面的步骤中安装 Rancher 时需要使用 `--set tls=external` 选项。有关更多信息，请参考 {xref-helm-chart-options}#_external_tls_termination[Rancher Helm chart 选项。]

有关如何设置 NGINX 负载平衡的示例，请参阅 {xref-nginx-load-balancer}[此页面。]

有关设置 Amazon ELB 网络负载平衡器的操作指南，请参阅 {xref-amazon-elb}[此页面。]

[CAUTION]
====

安装后，请勿使用此负载平衡器（即 `local` 集群 Ingress）来负载均衡除 Rancher 以外的应用程序。与其他应用程序共享此 Ingress 可能会导致 Rancher 在其他应用程序的 Ingress 配置重新加载后出现 websocket 错误。我们建议将 `local` 集群专用于 Rancher，而不用于其他应用程序。
====


[#_3_set_up_the_dns_record]
== 3.设置 DNS 记录

设置负载平衡器后，您需要创建一个 DNS 记录以将流量发送到此负载平衡器。

根据您的环境，这可能是指向负载平衡器 IP 的 A 记录，或者是指向负载平衡器主机名的 CNAME。无论哪种情况，请确保此记录是您希望 Rancher 响应的主机名。

在稍后的步骤中安装 Rancher 时，您需要指定此主机名，并且之后无法更改。确保您的决定是最终的。

有关设置 DNS 记录以将域流量路由到 Amazon ELB 负载平衡器的操作指南，请参阅 https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-elb-load-balancer[官方 AWS 文档。]
