= Autoscaler horizontal de pods
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/index.adoc 
:product-path: cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/horizontal-pod-autoscaler.adoc
:description: Découvrez l'autoscaler horizontal de pods (HPA). Comment gérer les HPA et comment les tester avec un déploiement de service
:experimental:
ifeval::["{build-type}" != "community"]
:xref-hpas-with-kubectl: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
:xref-hpas-with-ui: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:xref-hpas-test: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/test-hpas-with-kubectl.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-hpas-with-kubectl: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
:xref-hpas-with-ui: xref:how-to-guides/nouveaux-utilisateurs/ressources-kubernetes-configuration/autoscaler-horizontal-de-pods/gerer-les-hpa-avec-ui.adoc
:xref-hpas-test: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/test-hpas-with-kubectl.adoc
endif::[]

L'https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[autoscaler horizontal de pods] (HPA) est une fonctionnalité de Kubernetes qui vous permet de configurer votre cluster pour ajuster automatiquement les services qu'il exécute, à la hausse ou à la baisse.

Rancher propose des fonctionnalités supplémentaires pour aider à gérer les HPA, en fonction de la version de Rancher.

Vous pouvez créer, gérer et supprimer des HPA en utilisant l'interface utilisateur de Rancher. Il ne prend en charge que l'HPA dans l'`autoscaling/v2beta2` API.

[#_managing_hpas]
== Gestion des HPA

La manière dont vous gérez les HPA diffère selon votre version de l'API Kubernetes{nbsp}:

* *Pour la version de l'API Kubernetes autoscaling/V2beta1 :* Cette version de l'API Kubernetes vous permet d'autoscaler vos pods en fonction de l'utilisation de l'UC et de la mémoire de votre application.
* *Pour la version de l'API Kubernetes autoscaling/V2beta2 :* Cette version de l'API Kubernetes vous permet d'autoscaler vos pods en fonction de l'utilisation de l'UC et de la mémoire, en plus des métriques personnalisées.

Vous pouvez créer, gérer et supprimer des HPA en utilisant l'interface utilisateur de Rancher. Depuis l'interface utilisateur de Rancher, vous pouvez configurer l'HPA pour qu'il s'ajuste en fonction de l'utilisation de l'UC et de la mémoire. Pour plus d'informations, référez-vous à {xref-hpas-with-ui}[Gestion des HPA avec l'interface utilisateur de Rancher]. Pour ajuster l'HPA en fonction de métriques personnalisées, vous devez toujours utiliser `kubectl`. Pour plus d'informations, consultez {xref-hpas-with-kubectl}#_configurer_hpa_pour_scaler_en_utilisant_des_métriques_personnalisées_avec_prometheus[Configurer l'HPA pour qu'il s'ajuste en utilisant des métriques personnalisées avec Prometheus].

Les clusters créés dans Rancher v2.0.7 et supérieur ont automatiquement toutes les exigences nécessaires (serveur de métriques et configuration du cluster Kubernetes) pour utiliser l'HPA.

[#_testing_hpas_with_a_service_deployment]
== Tester les HPA avec un déploiement de service

Vous pouvez voir le nombre actuel de réplicas de votre HPA en allant dans votre projet et en cliquant sur menu:Ressources[HPA]. Pour plus d'informations, consultez {xref-hpas-with-ui}[Obtenir les métriques et l'état des HPA].

Vous pouvez également utiliser `kubectl` pour obtenir l'état des HPA que vous testez avec votre outil de test de charge. Pour plus d'informations, consultez {xref-hpas-test}[Tester les HPA avec kubectl].
