= Gestion des HPA avec kubectl
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/nouveaux-utilisateurs/ressources-kubernetes-configuration/autoscaler-horizontal-de-pods/gerer-les-hpa-avec-kubectl.adoc 
:product-path: cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
ifeval::["{build-type}" != "community"]
:xref-hpas-with-ui: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-hpas-with-ui: xref:how-to-guides/nouveaux-utilisateurs/ressources-kubernetes-configuration/autoscaler-horizontal-de-pods/gerer-les-hpa-avec-ui.adoc
endif::[]

Cette section décrit la gestion des HPA avec `kubectl`. Ce document contient des instructions sur la façon de{nbsp}:

* Créer un HPA
* Obtenir des informations sur les HPA
* Supprimer un HPA
* Configurer vos HPA pour qu'ils s'adaptent à l'utilisation de l'UC ou de la mémoire
* Configurer vos HPA pour qu'ils s'adaptent en utilisant des métriques personnalisées, si vous utilisez un outil tiers tel que Prometheus pour les métriques

Vous pouvez créer, visualiser et supprimer des HPA depuis l'interface utilisateur de Rancher. Vous pouvez également les configurer pour qu'ils s'adaptent en fonction de l'utilisation de l'UC ou de la mémoire depuis l'interface utilisateur de Rancher. Pour plus d'informations, référez-vous à {xref-hpas-with-ui}[Gestion des HPA avec l'interface utilisateur de Rancher]. Pour faire évoluer les HPA en fonction d'autres métriques que l'UC ou la mémoire, vous avez toujours besoin de `kubectl`.

[#_basic_kubectl_command_for_managing_hpas]
== Commande kubectl de base pour gérer les HPA

Si vous avez un fichier manifeste HPA, vous pouvez créer, gérer et supprimer des HPA en utilisant `kubectl`{nbsp}:

* Création d'un HPA
 ** Avec manifeste{nbsp}: `kubectl create -f <HPA_MANIFEST>`
 ** Sans manifeste (Support uniquement CPU){nbsp}: `kubectl autoscale deployment hello-world --min=2 --max=5 --cpu-percent=50`
* Obtenir des informations sur les HPA
 ** De base{nbsp}: `kubectl get hpa hello-world`
 ** Description détaillée{nbsp}: `kubectl describe hpa hello-world`
* Suppression de l'HPA
 ** `kubectl delete hpa hello-world`

[#_hpa_manifest_definition_example]
== Exemple de définition de manifeste HPA

Le manifeste HPA est le fichier de configuration utilisé pour gérer un HPA avec `kubectl`.

L'extrait suivant démontre l'utilisation de différentes directives dans un manifeste HPA. Voir la liste située sous l'exemple pour comprendre le but de chaque directive.

[,yml]
----
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hello-world
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 100Mi
----

|===
| Directive | Description

| `apiVersion: autoscaling/v2beta1`
| La version du groupe d'API Kubernetes `autoscaling` en cours d'utilisation. Cet exemple de manifeste utilise la version bêta, donc le scaling par CPU et mémoire est activé.

| `name: hello-world`
| Indique que l'HPA effectue un autoscaling pour le déploiement `hello-word`.

| `minReplicas: 1`
| Indique que le nombre minimum de réplicas en cours d'exécution ne peut pas descendre en dessous de 1.

| `maxReplicas: 10`
| Indique que le nombre maximum de réplicas dans le déploiement ne peut pas dépasser 10.

| `targetAverageUtilization: 50`
| Indique que le déploiement augmentera le nombre de pods lorsque le pod moyen en cours d'exécution utilise plus de 50 % de son UC demandée.

| `targetAverageValue: 100Mi`
| Indique que le déploiement augmentera le nombre de pods lorsque le pod moyen en cours d'exécution utilise plus de 100Mi de mémoire.
|===

[#_configuring_hpa_to_scale_using_resource_metrics_cpu_and_memory]
== Configuration de l'HPA pour le scaling en utilisant des métriques de ressources (UC et mémoire)

Les clusters créés dans Rancher v2.0.7 et supérieur ont toutes les exigences nécessaires (serveur de métriques et configuration du cluster Kubernetes) pour utiliser l'Horizontal Pod Autoscaler.

Exécutez les commandes suivantes pour vérifier si les métriques sont disponibles dans votre installation{nbsp}:

 $ kubectl top nodes
 NAME                              CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
 node-controlplane   196m         9%        1623Mi          42%
 node-etcd           80m          4%        1090Mi          28%
 node-worker         64m          3%        1146Mi          29%
 $ kubectl -n kube-system top pods
 NAME                                   CPU(cores)   MEMORY(bytes)
 canal-pgldr                            18m          46Mi
 canal-vhkgr                            20m          45Mi
 canal-x5q5v                            17m          37Mi
 canal-xknnz                            20m          37Mi
 kube-dns-7588d5b5f5-298j2              0m           22Mi
 kube-dns-autoscaler-5db9bbb766-t24hw   0m           5Mi
 metrics-server-97bc649d5-jxrlt         0m           12Mi
 $ kubectl -n kube-system logs -l k8s-app=metrics-server
 I1002 12:55:32.172841       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:https://kubernetes.default.svc?kubeletHttps=true&kubeletPort=10250&useServiceAccount=true&insecure=true
 I1002 12:55:32.172994       1 heapster.go:72] Metrics Server version v0.2.1
 I1002 12:55:32.173378       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default.svc" and version
 I1002 12:55:32.173401       1 configs.go:62] Using kubelet port 10250
 I1002 12:55:32.173946       1 heapster.go:128] Starting with Metric Sink
 I1002 12:55:32.592703       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
 I1002 12:55:32.925630       1 heapster.go:101] Starting Heapster API server...
 [restful] 2018/10/02 12:55:32 log.go:33: [restful/swagger] listing is available at https:///swaggerapi
 [restful] 2018/10/02 12:55:32 log.go:33: [restful/swagger] https:///swaggerui/ is mapped to folder /swagger-ui/
 I1002 12:55:32.928597       1 serve.go:85] Serving securely on 0.0.0.0:443

[#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus]
== Configuration de l'HPA pour le scaling en utilisant des métriques personnalisées avec Prometheus

Vous pouvez configurer l'HPA pour effectuer un autoscaling basé sur des métriques personnalisées fournies par des logiciels tiers. Le cas d'utilisation le plus courant pour l'autoscaling utilisant des logiciels tiers est basé sur des métriques au niveau de l'application (c'est-à-dire, les requêtes HTTP par seconde){nbsp}: HPA utilise l'API `custom.metrics.k8s.io` pour consommer ces métriques. Cette API est activée en déployant un adaptateur de métriques personnalisé pour la solution de collecte de métriques.

Pour cet exemple, nous allons utiliser https://prometheus.io/[Prometheus]. Nous commençons avec les hypothèses suivantes{nbsp}:

* Prometheus est déployé dans le cluster.
* Prometheus est configuré correctement et collecte des métriques appropriées des pods, des nœuds, des espaces de noms, etc.
* Prometheus est exposé à l'URL et au port suivants{nbsp}: `http://prometheus.mycompany.io:80`

Prometheus est disponible pour déploiement dans le catalogue Rancher v2.0. Déployez-le depuis le catalogue Rancher s'il n'est pas déjà en cours d'exécution dans votre cluster.

Pour que HPA utilise des métriques personnalisées de Prometheus, le package https://github.com/DirectXMan12/k8s-prometheus-adapter[k8s-prometheus-adapter] est requis dans l'espace de noms `kube-system` de votre cluster. Pour installer `k8s-prometheus-adapter`, nous utilisons le chart Helm disponible à https://github.com/banzaicloud/banzai-charts[banzai-charts].

. Initialisez Helm dans votre cluster.
+
----
  # kubectl -n kube-system create serviceaccount tiller
  kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
  helm init --service-account tiller
----

. Clonez le dépôt `banzai-charts` depuis GitHub{nbsp}:
+
----
  # git clone https://github.com/banzaicloud/banzai-charts
----

. Installez le chart `prometheus-adapter`, en spécifiant l'URL et le numéro de port de Prometheus.
+
----
  # helm install --name prometheus-adapter banzai-charts/prometheus-adapter --set prometheus.url="http://prometheus.mycompany.io",prometheus.port="80" --namespace kube-system
----

. Vérifiez que `prometheus-adapter` fonctionne correctement. Vérifiez le pod de service et les journaux dans l'espace de noms `kube-system`.
. Vérifiez que le pod de service est `Running`. Entrez la commande suivante.
    `
    # kubectl get pods -n kube-system
   `
    Dans la sortie résultante, recherchez un statut de `Running`.
    `+
    NOM                                  PRÊT     STATUT    RESTARTS   ÂGE
    ...
    prometheus-adapter-prometheus-adapter-568674d97f-hbzfx   1/1       En cours d'exécution   0          7h
    ...
   +`
. Vérifiez les journaux du service pour vous assurer que le service fonctionne correctement en entrant la commande suivante.
    `
    # kubectl logs prometheus-adapter-prometheus-adapter-568674d97f-hbzfx -n kube-system
   `
    Ensuite, examinez la sortie des journaux pour confirmer que le service fonctionne.

 .Prometheus Adaptor Logs [%collapsible] ====== ...
 I0724 10:18:45.696679       1 round_trippers.go:436] GET https://10.43.0.1:443/api/v1/namespaces/default/pods?labelSelector=app%3Dhello-world 200 OK in 2 milliseconds
 I0724 10:18:45.696695       1 round_trippers.go:442] Response Headers:
 I0724 10:18:45.696699       1 round_trippers.go:445]     Date: Tue, 24 Jul 2018 10:18:45 GMT
 I0724 10:18:45.696703       1 round_trippers.go:445]     Content-Type: application/json
 I0724 10:18:45.696706       1 round_trippers.go:445]     Content-Length: 2581
 I0724 10:18:45.696766       1 request.go:836] Response Body: {"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/default/pods","resourceVersion":"6237"},"items":[{"metadata":{"name":"hello-world-54764dfbf8-q6l82","generateName":"hello-world-54764dfbf8-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/hello-world-54764dfbf8-q6l82","uid":"484cb929-8f29-11e8-99d2-067cac34e79c","resourceVersion":"4066","creationTimestamp":"2018-07-24T10:06:50Z","labels":{"app":"hello-world","pod-template-hash":"1032089694"},"annotations":{"cni.projectcalico.org/podIP":"10.42.0.7/32"},"ownerReferences":[{"apiVersion":"extensions/v1beta1","kind":"ReplicaSet","name":"hello-world-54764dfbf8","uid":"4849b9b1-8f29-11e8-99d2-067cac34e79c","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"default-token-ncvts","secret":{"secretName":"default-token-ncvts","defaultMode":420}}],"containers":[{"name":"hello-world","image":"rancher/hello-world","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{"requests":{"cpu":"500m","memory":"64Mi"}},"volumeMounts":[{"name":"default-token-ncvts","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","nodeName":"34.220.18.140","securityContext":{},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}]},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2018-07-24T10:06:50Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2018-07-24T10:06:54Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2018-07-24T10:06:50Z"}],"hostIP":"34.220.18.140","podIP":"10.42.0.7","startTime":"2018-07-24T10:06:50Z","containerStatuses":[{"name":"hello-world","state":{"running":{"startedAt":"2018-07-24T10:06:54Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"rancher/hello-world:latest","imageID":"docker-pullable://rancher/hello-world@sha256:4b1559cb4b57ca36fa2b313a3c7dde774801aa3a2047930d94e11a45168bc053","containerID":"docker://cce4df5fc0408f03d4adf82c90de222f64c302bf7a04be1c82d584ec31530773"}],"qosClass":"Burstable"}}]}
 I0724 10:18:45.699525       1 api.go:74] GET http://prometheus-server.prometheus.34.220.18.140.xip.io/api/v1/query?query=sum%28rate%28container_fs_read_seconds_total%7Bpod_name%3D%22hello-world-54764dfbf8-q6l82%22%2Ccontainer_name%21%3D%22POD%22%2Cnamespace%3D%22default%22%7D%5B5m%5D%29%29by%28pod_name%29&time=1532427525.697 200 OK
 I0724 10:18:45.699620       1 api.go:93] Response Body: {"status":"success","data":{"resultType":"vector","result":[{"metric":{"pod_name":"hello-world-54764dfbf8-q6l82"},"value":[1532427525.697,"0"]}]}}
 I0724 10:18:45.699939       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/%2A/fs_read?labelSelector=app%3Dhello-world: (12.431262ms) 200 [[kube-controller-manager/v1.10.1 (linux/amd64) kubernetes/d4ab475/system:serviceaccount:kube-system:horizontal-pod-autoscaler] 10.42.0.0:24268]
 I0724 10:18:51.727845       1 request.go:836] Request Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"nonResourceAttributes":{"path":"/","verb":"get"},"user":"system:anonymous","group":["system:unauthenticated"]},"status":{"allowed":false}}
 ... ======

. Vérifiez que l'API des métriques est accessible depuis kubectl.

* Si vous accédez directement au cluster, entrez votre URL de serveur dans la configuration kubectl au format suivant{nbsp}: `\https://<Kubernetes_URL>:6443`.
+
----
# kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
----
+
Si l'API est accessible, vous devriez recevoir une sortie similaire à ce qui suit.
+
.Réponse de l'API
[%collapsible]
======
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[{"name":"pods/fs_usage_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_rss","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_cpu_period","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_cfs_throttled","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_io_time","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_read","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_sector_writes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_user","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/last_seen","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/tasks_state","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_cpu_quota","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/start_time_seconds","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_limit_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_write","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_cache","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_usage_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_cfs_periods","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_cfs_throttled_periods","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_reads_merged","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_working_set_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/network_udp_usage","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_inodes_free","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_inodes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_io_time_weighted","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_failures","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_swap","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_cpu_shares","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_memory_swap_limit_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_usage","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_io_current","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_writes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_failcnt","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_reads","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_writes_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_writes_merged","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/network_tcp_usage","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_max_usage_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_memory_limit_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_memory_reservation_limit_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_load_average_10s","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_system","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_reads_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_sector_reads","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]}]}
======

* Si vous accédez au cluster via Rancher, entrez votre URL de serveur dans la configuration kubectl au format suivant{nbsp}: `\https://<RANCHER_URL>/k8s/clusters/<CLUSTER_ID>`. Ajoutez le suffixe `/k8s/clusters/<CLUSTER_ID>` au chemin de l’API.
+
----
# kubectl get --raw /k8s/clusters/<CLUSTER_ID>/apis/custom.metrics.k8s.io/v1beta1
----
+
Si l'API est accessible, vous devriez recevoir une sortie similaire à ce qui suit.
+
.Réponse de l'API
[%collapsible]
======
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[{"name":"pods/fs_usage_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_rss","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_cpu_period","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_cfs_throttled","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_io_time","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_read","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_sector_writes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_user","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/last_seen","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/tasks_state","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_cpu_quota","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/start_time_seconds","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_limit_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_write","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_cache","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_usage_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_cfs_periods","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_cfs_throttled_periods","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_reads_merged","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_working_set_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/network_udp_usage","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_inodes_free","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_inodes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_io_time_weighted","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_failures","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_swap","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_cpu_shares","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_memory_swap_limit_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_usage","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_io_current","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_writes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_failcnt","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_reads","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_writes_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_writes_merged","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/network_tcp_usage","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/memory_max_usage_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_memory_limit_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/spec_memory_reservation_limit_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_load_average_10s","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/cpu_system","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_reads_bytes","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]},{"name":"pods/fs_sector_reads","singularName":"","namespaced":true,"kind":"MetricValueList","verbs":["get"]}]}
======
