= Gestion des HPA avec {rancher-product-name} l'UI
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guides-procédure/nouveaux-utilisateurs/ressources-kubernetes-configuration/autoscaler-horizontal-de-pods/gérer-les-hpa-avec-ui.adoc 
:product-path: cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-ui.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-hpas-with-kubectl: xref:cluster-admin/kubernetes-resources/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-hpas-with-kubectl: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-kubectl.adoc
endif::[]

L'interface Rancher prend en charge la création, la gestion et la suppression des HPA. Vous pouvez configurer l'utilisation de l'UC ou de la mémoire comme métrique que le HPA utilise pour mettre à l'échelle.

Si vous souhaitez créer des HPA qui se mettent à l'échelle en fonction d'autres métriques que l'UC et la mémoire, référez-vous à {xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[Configurer le HPA pour se mettre à l'échelle en utilisant des métriques personnalisées avec Prometheus].

[#_creating_an_hpa]
== Création d'un HPA

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez dans le cluster où vous souhaitez créer un HPA et cliquez sur *Explorer*.
. Dans la barre de navigation de gauche, cliquez sur menu:Découverte de services[HorizontalPodAutoscalers].
. Cliquez sur *Create*.
. Sélectionnez un *espace de noms* pour le HPA.
. Entrez un *Nom* pour le HPA.
. Sélectionnez un *Target Reference* comme cible d'échelle pour le HPA.
. Spécifiez le *Minimum Replicas* et le *Maximum Replicas* pour le HPA.
. Configurez les métriques pour le HPA. Vous pouvez choisir l'utilisation de la mémoire ou de l'UC comme métrique qui fera que le HPA mettra le service à l'échelle. Dans le champ *Quantity*, entrez le pourcentage de l'utilisation de la mémoire ou de l'UC de la charge de travail qui fera que le HPA mettra le service à l'échelle. Pour configurer d'autres métriques HPA, y compris les métriques disponibles depuis Prometheus, vous devez {xref-hpas-with-kubectl}#_configuring_hpa_to_scale_using_custom_metrics_with_prometheus[gérer les HPA en utilisant kubectl].
. Cliquez sur *Créer* pour créer le HPA.

[NOTE]
.Résultat :
====

Le HPA est déployé dans l'espace de noms choisi. Vous pouvez voir l'état du HPA depuis la vue Ressources > HPA du projet.
====


[#_get_hpa_metrics_and_status]
== Obtenir les métriques et l'état du HPA

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez au cluster qui a le HPA et cliquez sur *Explorer*.
. Dans la barre de navigation de gauche, cliquez sur menu:Découverte de services[HorizontalPodAutoscalers]. La page *HorizontalPodAutoscalers* montre le nombre de réplicas actuels.

Pour des métriques et un statut plus détaillés d'un HPA spécifique, cliquez sur le nom du HPA. Cela mène à la page de détails du HPA.

[#_deleting_an_hpa]
== Suppression d'un HPA

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Allez au cluster qui a le HPA que vous souhaitez supprimer et cliquez sur *Explorer*.
. Dans la barre de navigation de gauche, cliquez sur menu:Découverte de services[HorizontalPodAutoscalers].
. Cliquez sur menu:Ressources[HPA].
. Trouvez le HPA que vous souhaitez supprimer et cliquez sur *⋮ > Supprimer*.
. Cliquez sur *Supprimer* pour confirmer.

[NOTE]
.Résultat :
====

Le HPA est supprimé du cluster actuel.
====

