= Criptografando a Comunicação HTTP
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc 
:product-path: security/encrypting-http.adoc
:description: Aprenda como adicionar um certificado SSL (Secure Sockets Layer) ou certificado TLS (Transport Layer Security)
:experimental:
ifeval::["{build-type}" != "community"]
:xref-add-ingresses: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/add-ingresses.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-add-ingresses: xref:procedimentos/novos-guias/configuração-de-recursos-do-kubernetes/balanceador-de-carga-e-controlador-de-ingress/add-ingresses.adoc
endif::[]

Quando você cria um ingress dentro do Rancher/Kubernetes, deve fornecer um segredo que inclua uma chave privada TLS e um certificado, que são usados para criptografar e descriptografar as comunicações que passam pelo ingress. Você pode disponibilizar certificados para uso no ingress adicionando o certificado à implantação do ingress.

[NOTE]
.Pré-requisitos:
====

Você deve ter uma chave privada TLS e um certificado disponíveis para upload.
====


[#_1_create_a_secret]
== 1. Crie um Segredo

. No canto superior esquerdo, clique *☰ > Gerenciamento de Cluster*.
. Vá para o cluster onde deseja implantar seu ingress e clique menu:Mais Recursos[Kernel> Segredos].
. Clique em *Criar*.
. Clique *Certificado TLS*.
. Insira um nome para o segredo. Nota: Seu segredo deve ter um nome único entre os outros certificados, registros e segredos dentro do seu projeto/espaço de trabalho.
. No campo *Chave Privada*, copie e cole a chave privada TLS do seu certificado na caixa de texto (inclua o cabeçalho e o rodapé), ou clique *Ler de um arquivo* para navegar até a chave privada no seu sistema de arquivos. Se possível, recomendamos usar *Ler de um arquivo* para reduzir a probabilidade de erro. Nota: Os arquivos de chave privada terminam com uma extensão de `.key`.
. No campo *Certificado*, copie e cole seu certificado na caixa de texto (inclua o cabeçalho e o rodapé), ou clique *Ler de um arquivo* para navegar até o certificado no seu sistema de arquivos. Se possível, recomendamos usar *Ler de um arquivo* para reduzir a probabilidade de erro. Nota: Os arquivos de certificado terminam com uma extensão de `.crt`.
. Clique em *Criar*.

[#_2_add_the_secret_to_an_ingress]
== 2. Adicione o Segredo a um Ingress

. No canto superior esquerdo, clique *☰ > Gerenciamento de Cluster*.
. Vá para o cluster onde deseja implantar seu ingress e clique menu:Descoberta de Serviço[Ingresses].
. Clique em *Criar*.
. Selecione o *Namespace* do ingress.
. Insira um *Nome* para o ingress.
. Na aba *Certificados*, selecione o segredo que contém seu certificado e chave privada.
. Clique em *Criar*.

[#_whats_next]
== O Que Mais?

Agora você pode adicionar o certificado ao lançar um ingress dentro do projeto ou namespace atual. Para mais informações, consulte {xref-add-ingresses}[Adding Ingress].
