= Modelos de Configuração de Admissão de Segurança de Pod (PSA)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: procedimentos-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/modelos-de-configuração-psa.adoc 
:product-path: security/psact.adoc
ifeval::["{build-type}" != "community"]
:xref-psa-pss: xref:security/psa-pss.adoc
:xref-sample-psact: xref:security/sample-psact.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-psa-pss: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/padrões-de-segurança-de-pod.adoc
:xref-sample-psact: xref:reference-guides/rancher-security/psa-restricted-exemptions.adoc
endif::[]

{xref-psa-pss}[Modelos de configuração de admissão de segurança de Pod (PSA)] são um recurso definido pelo usuário (CRD) do Rancher, disponível no Rancher v2.7.2 e superior. Os modelos fornecem configurações de segurança pré-definidas que você pode aplicar a um cluster:

[IMPORTANT]
====
As políticas enviadas por padrão no Rancher visam proporcionar um equilíbrio entre segurança e conveniência. Se uma configuração de política mais rigorosa for necessária, os usuários podem elaborar tais políticas com base em seus requisitos específicos. No caso de as políticas do Rancher serem preferidas, você precisará implantar controladores de admissão que bloqueiem a criação de quaisquer <<_exempting_required_rancher_namespaces,namespaces isentos>> que não serão utilizados em seus ambientes.
====

* `rancher-privileged`: A configuração mais permissiva. Ela não restringe o comportamento de nenhum pod. Isso permite escalonamentos de privilégios conhecidos. Esta política não possui isenções.
* `rancher-restricted`: Uma configuração fortemente restrita que segue as melhores práticas atuais para proteção de pods. Você deve fazer {xref-psa-pss}#_rancher_on_psa_restricted_clusters[isenções em nível de namespace] para componentes do Rancher.

[#_assign_a_pod_security_admissions_psa_configuration_template]
== Atribuir um Modelo de Configuração de Admissão de Segurança de Pod (PSA)

Você pode atribuir um modelo PSA ao mesmo tempo em que cria um cluster downstream. Você também pode adicionar um modelo configurando um cluster downstream existente.

[#_assign_a_template_during_cluster_creation]
=== Atribuir um Modelo Durante a Criação do Cluster

[tabs]
======
RKE2 e K3s::
+
--
:experimental:

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique no botão *Criar*.
. Selecione um provedor.
. Na *Cluster: Na página Criar*, vá para menu:Configurações Básicas[Segurança].
. No menu suspenso *Modelo de Configuração de Admissão de Segurança de Pod (PSA)*, selecione o modelo que você deseja atribuir.
. Clique em *Criar*.

[pass]
<h3><a id="_assign_a_template_to_an_existing_cluster"></a>Atribuir um Modelo a um Cluster Existente</h3>

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Encontre o cluster que você deseja atualizar na tabela *Clusters* e clique no *⋮*.
. Selecione *Editar Configuração*.
. No menu suspenso *Modelo de Configuração de Admissão de Segurança de Pod (PSA)*, selecione o modelo que você deseja atribuir.
. Clique em *Salvar*.

--

RKE1::
+
--
. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique no botão *Criar*.
. Selecione um provedor.
. Na página *Adicionar Cluster*, em *Opções do Cluster*, clique em *Opções Avançadas*.
. No menu suspenso *Modelo de Configuração de Admissão de Segurança de Pod (PSA)*, selecione o modelo que você deseja atribuir.
. Clique em *Criar*.

[pass]
<h3><a id="_assign_a_template_to_an_existing_cluster"></a>Atribuir um Modelo a um Cluster Existente</h3>

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Encontre o cluster que você deseja atualizar na tabela *Clusters* e clique no *⋮*.
. Selecione *Editar Configuração*.
. Na página *Editar Cluster*, vá para menu:Opções do Cluster[Opções Avançadas].
. No *Modelo de Configuração de Admissão de Segurança de Pod (PSA)*, selecione o modelo que você deseja atribuir.
. Clique em *Salvar*.
--
======

[#_add_or_edit_a_pod_security_admissions_psa_configuration_template]
== Adicionar ou Editar um Modelo de Configuração de Admissão de Segurança de Pod (PSA)

Se você tiver privilégios de administrador, pode personalizar restrições de segurança e permissões criando modelos PSA adicionais ou editando modelos existentes.

[CAUTION]
====
Se você editar um modelo PSA existente enquanto ele ainda estiver em uso, as alterações serão aplicadas a todos os clusters que foram atribuídos a esse modelo.
====


. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Clique em *Avançado* para abrir o menu suspenso.
. Selecione *Admissões de Segurança para Pods*.
. Encontre o modelo que você deseja modificar e clique no *⋮*.
. Selecione *Editar Configuração* para editar o modelo.
. Quando você terminar de editar a configuração, clique em *Salvar*.

[#_allow_non_admin_users_to_manage_psa_templates]
=== Permitir que usuários não administradores gerenciem modelos de PSA

Se você quiser permitir que outros usuários gerenciem modelos, pode vincular esse usuário a um papel que concede todos os verbos (`"*"`) em `management.cattle.io/podsecurityadmissionconfigurationtemplates`.

[CAUTION]
====
Qualquer usuário que estiver vinculado à permissão acima poderá alterar os níveis de restrição em _todos_ os clusters gerenciados que utilizam um determinado modelo de PSA, incluindo aqueles nos quais não possui permissões.
====


[#_exempting_required_rancher_namespaces]
== Isentando namespaces obrigatórios do Rancher

Quando você executa o Rancher em um cluster Kubernetes que aplica uma política de segurança restritiva por padrão, você precisará <<_exempting_namespaces,isentar os seguintes namespaces>>, caso contrário, a política pode impedir que os pods do sistema do Rancher sejam executados corretamente.

* `calico-apiserver`
* `calico-system`
* `cattle-alerting`
* `cattle-capi-system`
* `cattle-csp-adapter-system`
* `cattle-elemental-system`
* `cattle-epinio-system`
* `cattle-externalip-system`
* `cattle-fleet-local-system`
* `cattle-fleet-system`
* `cattle-gatekeeper-system`
* `cattle-global-data`
* `cattle-global-nt`
* `cattle-impersonation-system`
* `cattle-istio`
* `cattle-istio-system`
* `cattle-logging`
* `cattle-logging-system`
* `cattle-monitoring-system`
* `cattle-neuvector-system`
* `cattle-prometheus`
* `cattle-provisioning-capi-system`
* `cattle-resources-system`
* `cattle-scc-system`
* `cattle-sriov-system`
* `cattle-system`
* `cattle-turtles-system`
* `cattle-ui-plugin-system`
* `cattle-windows-gmsa-system`
* `cert-manager`
* `cis-operator-system`
* `compliance-operator-system`
* `fleet-default`
* `fleet-local`
* `istio-system`
* `kube-node-lease`
* `kube-public`
* `kube-system`
* `longhorn-system`
* `rancher-alerting-drivers`
* `rancher-compliance-system`
* `security-scan`
* `sr-operator-system`
* `tigera-operator`
* `traefik`

Rancher, alguns gráficos de propriedade do Rancher e as distribuições RKE2 e K3s utilizam todos esses namespaces. Um subconjunto dos namespaces listados já está isento na política incorporada do Rancher `rancher-restricted`, para uso em clusters downstream. Para um Modelo completo que possui todas as isenções necessárias para executar o Rancher, consulte este {xref-sample-psact}[Modelo de Configuração de Admissão de Segurança de exemplo].

[#_exempting_namespaces]
== Isentando namespaces

Se você atribuir o modelo `rancher-restricted` a um cluster, por padrão, as restrições são aplicadas em todo o cluster no nível do namespace. Para isentar certos namespaces dessa política altamente restritiva, faça o seguinte:

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Clique em *Avançado* para abrir o menu suspenso.
. Selecione *Admissões de Segurança para Pods*.
. Encontre o modelo que você deseja modificar e clique no *⋮*.
. Selecione *Editar Configuração*.
. Clique na caixa de seleção *Namespaces* sob *Isenções* para editar o campo *Namespaces*.
. Quando você terminar de isentar namespaces, clique em *Salvar*.

[NOTE]
====
Você precisa atualizar o cluster de destino para que o novo modelo tenha efeito nesse cluster. Uma atualização pode ser acionada editando e salvando o cluster sem alterar os valores.
====

