= 在名称空间中启用Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-namespace.adoc 
:product-path: observability/istio/guides/enable-istio-in-namespace.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-sidecar: xref:observability/istio/guides/use-istio-sidecar.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-sidecar: xref:how-to-guides/advanced-user-guides/istio-setup-guide/use-istio-sidecar.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] 自 Rancher v2.12.0 起已被弃用；请转向 https://apps.rancher.io[SUSE 应用程序集合] 版本的 Istio，以获得增强的安全性（包含在 SUSE Rancher Prime 订阅中）。
详细信息可以在 https://forums.suse.com/t/deprecation-of-rancher-istio/45043[此公告] 中找到。
====

您需要手动在每个希望被Istio跟踪或控制的名称空间中启用Istio。当Istio在名称空间中启用时，Envoy边车代理将自动注入到该名称空间中所有新部署的工作负载中。

此名称空间设置只会影响该名称空间中的新工作负载。任何现有的工作负载需要重新部署才能利用边车自动注入。

[NOTE]
.前提条件：
====

要在名称空间中启用Istio，集群必须已安装Istio。
====


. 单击 *☰ > 集群管理*。
. 转到您创建的集群并单击*探索*。
. 单击menu:集群[项目/名称空间]。
. 转到您希望启用Istio的名称空间并单击*⋮  > 启用Istio自动注入*。或者，单击名称空间，然后在名称空间详细信息页面上单击*⋮  > 启用Istio自动注入*。

*结果：*该名称空间现在具有标签`istio-injection=enabled`。在此名称空间中部署的所有新工作负载将默认注入Istio边车。

[#_verifying_that_automatic_istio_sidecar_injection_is_enabled]
== 验证自动Istio边车注入是否已启用

要验证Istio是否已启用，请在名称空间中部署一个hello-world工作负载。转到工作负载并单击Pod名称。在*容器*部分，您应该看到`istio-proxy`容器。

[#_excluding_workloads_from_being_injected_with_the_istio_sidecar]
== 排除工作负载不被注入Istio边车

如果您需要排除某个工作负载不被注入Istio边车，请在工作负载上使用以下注释：

----
sidecar.istio.io/inject: “false”
----

要将注释添加到工作负载，

. 单击 *☰ > 集群管理*。
. 转到您创建的集群并单击*Explore*.
. 单击*工作负载*。
. 转到不应有边车的工作负载，并以 YAML 格式进行编辑
. 在工作负载上添加以下键、值`sidecar.istio.io/inject: false`作为注释
. 单击 *保存*。

*结果：*Istio边车将不会被注入到工作负载中。

[NOTE]
====

如果您部署的作业未完成，您需要按照提供的步骤将此注释添加到您的Pod中。由于Istio边车无限期运行，即使任务已完成，作业也不能被视为完成。
====

[#__xref_istio_sidecar_next_add_deployments_with_the_istio_sidecar]
== {xref-istio-sidecar}[下一步：添加带有Istio边车的部署]
