= Konfigurationsoptionen
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/configuration-options/index.adoc 
:product-path: observability/istio/configuration/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
:xref-istio-on-rke2: xref:observability/istio/configuration/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:observability/istio/configuration/project-network-isolation.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
:xref-istio-on-rke2: xref:integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc
:xref-istio-project-network-isolation: xref:integrations-in-rancher/istio/configuration-options/project-network-isolation.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ist seit Rancher v2.12.0 ausgelaufen; wenden Sie sich an die https://apps.rancher.io[SUSE Application Collection] Version von Istio für verbesserte Sicherheit (in SUSE Rancher Prime-Abonnements enthalten).
Detaillierte Informationen finden Sie in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[dieser Ankündigung].
====

[#_egress_support]
== Egress-Unterstützung

Standardmäßig ist das Egress-Gateway deaktiviert, kann jedoch bei der Installation oder beim Upgrade über die values.yaml oder über die <<_overlay_file,Overlay-Datei>> aktiviert werden.

[#_enabling_automatic_sidecar_injection]
== Aktivierung der automatischen Sidecar-Injektion

Die automatische Sidecar-Injektion ist standardmäßig deaktiviert. Um dies zu aktivieren, setzen Sie das `sidecarInjectorWebhook.enableNamespacesByDefault=true` in der values.yaml bei der Installation oder beim Upgrade. Dies aktiviert automatisch die Istio-Sidecar-Injektion in allen neuen Namespaces, die bereitgestellt werden.

[#_overlay_file]
== Overlay-Datei

Eine Overlay-Datei ist dafür konzipiert, eine umfangreiche Konfiguration Ihrer Istio-Installation zu unterstützen. Sie ermöglicht es Ihnen, Änderungen an allen Werten vorzunehmen, die in der https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/[IstioOperator API] verfügbar sind. Dies stellt sicher, dass Sie die Standardinstallation an jedes Szenario anpassen können.

Die Overlay-Datei fügt der Standardinstallation, die von der Istio-Chart-Installation bereitgestellt wird, Konfiguration hinzu. Das bedeutet, dass Sie die bereits für die Installation definierten Komponenten nicht neu definieren müssen.

Für weitere Informationen zu Overlay-Dateien lesen Sie die https://istio.io/latest/docs/setup/install/istioctl/#configure-component-settings[Istio-Dokumentation.]

[#_selectors_and_scrape_configs]
== Selektoren und Scrape-Konfigurationen

Die Monitoring-App setzt `prometheus.prometheusSpec.ignoreNamespaceSelectors=false`, was standardmäßig das Monitoring über alle Namespaces hinweg ermöglicht. Dies stellt sicher, dass Sie den Datenverkehr, die Metriken und die Grafiken für Ressourcen, die in einem Namespace mit `istio-injection=enabled`-Label bereitgestellt wurden, einsehen können.

Wenn Sie Prometheus auf bestimmte Namespaces beschränken möchten, setzen Sie `prometheus.prometheusSpec.ignoreNamespaceSelectors=true`. Sobald Sie dies getan haben, müssen Sie noch zusätzliche Konfiguration vornehmen, um Ihre Ressourcen weiterhin zu überwachen.

Für Details siehe {xref-selectors-and-scrape-configurations}[diesen Abschnitt.]

[#_additional_steps_for_installing_istio_on_an_rke2_product_name_cluster]
== Zusätzliche Schritte zur Installation von Istio auf einem {rke2-product-name} Cluster

Siehe {xref-istio-on-rke2}[diesen Abschnitt.]

[#_additional_steps_for_project_network_isolation]
== Zusätzliche Schritte zur Isolierung des Projektnetzwerks

Siehe {xref-istio-project-network-isolation}[diesen Abschnitt.]
