= CPUおよびメモリの割り当て
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/cpu-and-memory-allocations.adoc 
:product-path: observability/istio/cpu-and-memory-allocations.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-config: xref:observability/istio/configuration/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio]はRancher v2.12.0以降廃止されました。セキュリティを強化するために、 https://apps.rancher.io[SUSE Application Collection]のIstioビルドに切り替えてください（SUSE Rancher Primeサブスクリプションに含まれています）。
詳細情報は https://forums.suse.com/t/deprecation-of-rancher-istio/45043[この発表]にあります。
====

このセクションでは、クラスター内のIstioコンポーネントに推奨される最小限の計算リソースについて説明します。

各コンポーネントのCPUおよびメモリの割り当ては<<_configuring_resource_allocations,設定可能です。>>

Istioを有効にする前に、RancherワーカーノードがIstioのすべてのコンポーネントを実行するのに十分なCPUとメモリを持っていることを確認することをお勧めします。

[TIP]
====

大規模なデプロイメントでは、各Istioコンポーネントのノードセレクターを追加することにより、インフラストラクチャをクラスター内の専用ノードに配置することを強くお勧めします。
====


以下の表は、各コアIstioコンポーネントのCPUおよびメモリに対する推奨される最小リソース要求と制限の概要を示しています。

Kubernetesでは、リソース要求は、ワークロードがノードにデプロイされるためには、ノードに指定された量のメモリとCPUが利用可能でなければならないことを示します。ワークロードがCPUまたはメモリの制限を超えた場合、ノードから終了または追い出される可能性があります。コンテナのリソース制限の管理に関する詳細は、 https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/[Kubernetesのドキュメントを参照してください。]

|===
| ワークロード | CPU - リクエスト | メモリ - リクエスト | CPU - 制限 | メモリ - 制限

| ingressゲートウェイ
| 100m
| 128mi
| 2000m
| 1024Mi

| egressゲートウェイ
| 100m
| 128mi
| 2000m
| 1024Mi

| istiod
| 500m
| 2048Mi
| 制限なし
| 制限なし

| プロキシ
| 10m
| 10Mi
| 2000m
| 1024Mi

| *合計:*
| *710m*
| *2314Mi*
| *6000m*
| *3072Mi*
|===

[#_configuring_resource_allocations]
== リソース割り当ての構成

各タイプのIstioコンポーネントに対して、個別にリソース割り当てを構成できます。このセクションには、各コンポーネントのデフォルトのリソース割り当てが含まれています。

ワークロードをノードにスケジュールしやすくするために、クラスター管理者はコンポーネントのCPUおよびメモリリソース要求を減らすことができます。ただし、デフォルトのCPUおよびメモリ割り当ては、推奨する最小限の値です。

Istioの構成に関する詳細情報は、 https://istio.io/[公式のIstioドキュメント]で確認できます。

Istioコンポーネントに割り当てられるリソースを構成するには、

. *☰ > クラスター管理*をクリックします。
. 作成したクラスターに移動し、*探索*をクリックします。
. 左のナビゲーションバーで*アプリ*をクリックします。
. *インストール済みアプリ*をクリックします。
. `istio-system`ネームスペースに移動します。`rancher-istio`などのIstioワークロードの1つで、*⋮ > 編集/アップグレード*をクリックします。
. *アップグレード*をクリックして、values.yamlの変更を通じてベースコンポーネントを編集するか、{xref-istio-config}#_overlay_file[オーバーレイファイル]を追加します。オーバーレイファイルの編集に関する詳細情報は、<<_editing_the_overlay_file,このセクションを参照してください。>>
. CPUまたはメモリの割り当て、各コンポーネントがスケジュールされるノード、またはノードのトレランスを変更します。
. *アップグレード*をクリックして、変更を展開します。

*結果:*Istioコンポーネントのリソース割り当てが更新されました。

[#_editing_the_overlay_file]
=== オーバーレイファイルの編集

オーバーレイファイルには、 https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec[Istio Operator spec.]の値のいずれかを含めることができます。Istioアプリケーションに含まれるオーバーレイファイルは、オーバーレイファイルの潜在的な構成の一例に過ぎません。

ファイルに`kind: IstioOperator`が含まれ、YAMLオプションが有効であれば、そのファイルはオーバーレイとして使用できます。

Istioアプリケーションに提供される例のオーバーレイファイルでは、次のセクションでKubernetesリソースを変更することができます:

----
#      k8s:
#        resources:
#          requests:
#            cpu: 200m
----
