= Espacios de nombres
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-namespaces.adoc 
:product-path: cluster-admin/namespaces.adoc
ifeval::["{build-type}" != "community"]
:xref-secrets: xref:security/secrets-hub.adoc
:xref-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/manage-persistent-storage.adoc
:xref-configmaps: xref:cluster-admin/kubernetes-resources/configmaps.adoc
:xref-workloads-and-pods: xref:cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:xref-project-resource-quotas: xref:cluster-admin/project-admin/project-resource-quotas/project-resource-quotas.adoc
:xref-http-encrypt: xref:security/encrypting-http.adoc
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
:xref-k8s-docker-registries: xref:cluster-admin/kubernetes-resources/kubernetes-and-docker-registries.adoc
:xref-create-services: xref:cluster-admin/kubernetes-resources/create-services.adoc
:xref-lb-and-ingress-controller: xref:cluster-admin/recursos-kubernetes/balanceador-de-carga-y-controlador-de-ingress/balanceador-de-carga-y-controlador-de-ingress.adoc
:xref-namespace-default-limit: xref:cluster-admin/project-admin/project-resource-quotas/override-default-limit-in-namespaces.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-persistent-storage: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/index.adoc
:xref-configmaps: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc
:xref-workloads-and-pods: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc
:xref-project-resource-quotas: xref:how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/index.adoc
:xref-http-encrypt: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
:xref-k8s-docker-registries: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries.adoc
:xref-create-services: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/create-services.adoc
:xref-lb-and-ingress-controller: xref:guías-prácticas/nuevos-usuarios/recursos-kubernetes-configuración/balanceador-de-carga-y-controlador-de-ingress/index.adoc
:xref-namespace-default-limit: xref:instrucciones/guías-de-usuario-avanzadas/gestionar-proyectos/gestionar-cuotas-de-recursos-del-proyecto/anular-límite-predeterminado-en-espacios-de-nombres.adoc
endif::[]

Dentro de Rancher, puedes dividir aún más los proyectos en diferentes https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/[espacios de nombres], que son clústeres virtuales dentro de un proyecto respaldado por un clúster físico. Si necesitas otro nivel de organización más allá de los proyectos y el `default` espacio de nombres, puedes usar múltiples espacios de nombres para aislar aplicaciones y recursos.

Aunque asignas recursos a nivel de proyecto para que cada espacio de nombres en el proyecto pueda utilizarlos, puedes anular esta herencia asignando recursos explícitamente a un espacio de nombres.

Los recursos que puedes asignar directamente a los espacios de nombres incluyen:

* {xref-workloads-and-pods}[Cargas de trabajo]
* {xref-lb-and-ingress-controller}[Balanceadores de Carga/Ingress]
* {xref-create-services}[Registros de Descubrimiento de Servicios]
* {xref-persistent-storage}[Solicitudes de Volúmenes Persistentes]
* {xref-http-encrypt}[Certificados]
* {xref-configmaps}[ConfigMaps]
* {xref-k8s-docker-registries}[Registros]
* {xref-secrets}[Secrets]

Para gestionar permisos en un clúster de Kubernetes estándar, los administradores del clúster configuran políticas de control de acceso basado en funciones para cada espacio de nombres. Con Rancher, los permisos de usuario se asignan a nivel de proyecto, y los permisos se heredan automáticamente por cualquier espacio de nombres que pertenezca al proyecto en particular.

[NOTE]
====

Si creas un espacio de nombres con `kubectl`, es posible que no funcione porque `kubectl` no exige que tu nuevo espacio de nombres esté asociado a un proyecto al que tengas acceso. Si tus permisos están restringidos a nivel de proyecto, es mejor <<_creating_namespaces,crear un espacio de nombres a través de Rancher>> para asegurarte de que tendrás permiso para acceder al espacio de nombres.
====


[#_creating_namespaces]
== Creando Espacios de Nombres

Crea un nuevo espacio de nombres para aislar aplicaciones y recursos en un proyecto.

[TIP]
====

Al trabajar con recursos de proyecto que puedes asignar a un espacio de nombres (es decir, {xref-deploy-workloads}[cargas de trabajo], {xref-http-encrypt}[certificados], {xref-configmaps}[ConfigMaps], etc.), puedes crear un espacio de nombres sobre la marcha.
====


. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, ve al clúster donde quieras crear un espacio de nombres y haz clic en *Explorar*.
. Haz clic en menu:Clúster[Proyectos/Espacios de nombres].
. Ve al proyecto donde quieras añadir un espacio de nombres y haz clic en *Crear Espacio de Nombres*. Alternativamente, ve a *No en un Proyecto* para crear un espacio de nombres no asociado con un proyecto.
. *Opcional:* Si tu proyecto tiene {xref-project-resource-quotas}[Cuotas de Recursos] en efecto, puedes anular los *Límites de recursos predeterminados* (que establecen un límite en los recursos que el espacio de nombres puede consumir).
. Introduce un *Nombre* y luego haz clic en *Crear*.

*Resultado:* Tu espacio de nombres se añade al proyecto. Puedes comenzar a asignar recursos del clúster al espacio de nombres.

[#_moving_namespaces_to_another_project]
== Mover Espacios de Nombres a Otro Proyecto

Los administradores de clúster y los miembros pueden necesitar ocasionalmente mover un espacio de nombres a otro proyecto, como cuando deseas que un equipo diferente comience a usar la aplicación.

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, ve al clúster donde quieras mover un espacio de nombres y haz clic en *Explorar*.
. Haz clic en menu:Clúster[Proyectos/Espacios de nombres].
. Ve al espacio de nombres que deseas mover y haz clic en *⋮ > Mover*.
. Selecciona el(los) espacio(s) de nombres que deseas mover a un proyecto diferente. Luego haz clic en *Mover*. Puedes mover múltiples espacios de nombres a la vez.
+
[NOTE]
.Notas:
====
* No muevas los espacios de nombres en el proyecto `System`. Mover estos espacios de nombres puede afectar negativamente a la red del clúster.
* No puedes mover un espacio de nombres a un proyecto que ya tiene una {xref-project-resource-quotas}[cuota de recursos] configurada.
* Si mueves un espacio de nombres de un proyecto que tiene una cuota establecida a un proyecto sin cuota establecida, la cuota se elimina del espacio de nombres.
====

. Elige un nuevo proyecto para el nuevo espacio de nombres y luego haz clic en *Mover*. Alternativamente, puedes eliminar el espacio de nombres de todos los proyectos seleccionando *Ninguno*.

*Resultado:* Tu espacio de nombres se mueve a un proyecto diferente (o se desasocia de todos los proyectos). Si hay recursos de proyecto adjuntos al espacio de nombres, este los libera y luego asigna los recursos del nuevo proyecto.

[#_editing_namespace_resource_quotas]
== Editar Cuotas de Recursos del Espacio de Nombres

Siempre puedes anular el límite predeterminado del espacio de nombres para proporcionar a un espacio de nombres específico acceso a más (o menos) recursos del proyecto.

Para más información, consulta cómo {xref-namespace-default-limit}[editar cuotas de recursos del espacio de nombres].
