= {harvester-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/harvester/index.adoc 
:product-path: integrations/harvester/harvester.adoc

Introduit dans Rancher v2.6.1, Harvester est un logiciel d'infrastructure hyper-convergée (HCI) Open Source construit sur Kubernetes. Harvester s'installe sur des serveurs à matériel sans système d'exploitation et fournit des fonctionnalités intégrées de virtualisation et de stockage distribué. Bien que Harvester fonctionne avec Kubernetes, il n'est pas nécessaire de connaître les concepts de Kubernetes, ce qui le rend plus convivial.

[#__harvester_product_name_with_rancher]
== {harvester-product-name} avec Rancher

Avec Rancher Prime et Harvester, les opérateurs informatiques ont désormais accès à une plateforme d'infrastructure prête pour l'entreprise et facile à utiliser, qui gère de manière cohérente leurs machines virtuelles et leurs clusters Kubernetes ensemble. Pour plus d'informations sur l'offre de support, consultez la https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-2-0/[Matrice de support]. Avec la fonctionnalité de gestion de la virtualisation de Rancher, les utilisateurs peuvent importer et gérer plusieurs clusters Harvester. En tirant parti de la fonctionnalité d'authentification de Rancher et du contrôle RBAC, on bénéficie d'une prise en charge multi-locataire.
