= Grafanaダッシュボードのカスタマイズ
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard.adoc 
:product-path: observability/monitoring-and-dashboards/customizing-dashboard/customize-grafana-dashboard.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-rancher-monitoring-rbac: xref:observability/monitoring-and-dashboards/rbac-for-monitoring.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-monitoring-rbac: xref:integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring.adoc
endif::[]

このセクションでは、特定のコンテナに適用されるメトリクスを表示するためにGrafanaダッシュボードをカスタマイズする方法を学びます。

[#_prerequisites]
== 前提条件

Grafanaダッシュボードをカスタマイズする前に、`rancher-monitoring`アプリケーションをインストールする必要があります。

Grafanaダッシュボードを含む外部監視UIへのリンクを見るには、少なくとも{xref-rancher-monitoring-rbac}#_users_with_rancher_based_permissions[project-member role.]が必要です。

[#_signing_in_to_grafana]
== Grafanaにサインインする

. Rancher UIで、カスタマイズしたいダッシュボードがあるクラスターに移動します。
. 左側のメニューで*Monitoring.*をクリックします。
. *Grafana.*をクリックします。Grafanaダッシュボードは新しいタブで開くはずです。
. 左下隅のログインアイコンに移動し、*サインイン*をクリックします。
. Grafanaにログインします。Grafanaインスタンスのデフォルトの管理者ユーザー名とパスワードは`admin/prom-operator`です。（パスワードを持っている人に関係なく、Rancherでのクラスター管理者の権限がなければGrafanaインスタンスにアクセスできません。）代替の認証情報は、チャートのデプロイまたはアップグレード時にも提供できます。

[#_getting_the_promql_query_powering_a_grafana_panel]
== Grafanaパネルを支えるPromQLクエリの取得

任意のパネルについて、タイトルをクリックし、*Explore*をクリックすると、グラフィックを支えるPromQLクエリを取得できます。

この例では、AlertmanagerコンテナのCPU使用率を取得したいので、menu:CPU Utilization[Inspect.]をクリックします。

*Data*タブは、時間を最初の列に、PromQLクエリの結果を2番目の列に持つ時系列として基礎データを表示します。PromQLクエリをコピーします。

----
(1 - (avg(irate({__name__=~"node_cpu_seconds_total|windows_cpu_time_total",mode="idle"}[5m])))) * 100
----

その後、Grafanaパネルでクエリを修正するか、クエリを使用して新しいGrafanaパネルを作成できます。

関連項目:

* https://grafana.com/docs/grafana/latest/panels-visualizations/configure-panel-options/#edit-a-panel[Grafanaのパネル編集に関するドキュメント]
* https://grafana.com/docs/grafana/latest/panels-visualizations/panel-editor-overview[Grafanaのダッシュボードにパネルを追加するためのドキュメント]
