= {harvester-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/harvester/index.adoc 
:product-path: integrations/harvester/harvester.adoc

Eingeführt in Rancher v2.6.1, ist Harvester eine Open Source-Software für hyperkonvergente Infrastrukturen (HCI), die auf Kubernetes basiert. Harvester wird auf Bare-Metal-Servern installiert und bietet integrierte Virtualisierungs- und verteilte Speicherfunktionen. Obwohl Harvester mit Kubernetes arbeitet, erfordert es kein Wissen über Kubernetes-Konzepte, was es benutzerfreundlicher macht.

[#__harvester_product_name_with_rancher]
== {harvester-product-name} mit Rancher

Mit Rancher Prime und Harvester haben IT-Betreiber jetzt Zugang zu einer unternehmensbereiten, einfach zu bedienenden Infrastrukturplattform, die ihre virtuellen Maschinen und Kubernetes-Cluster zusammen verwaltet. Für weitere Informationen zum Unterstützungsangebot siehe die https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-2-0/[Support-Matrix]. Mit der Funktion zur Virtualisierungsverwaltung von Rancher können Benutzer mehrere Harvester cluster importieren und verwalten. Nutzung der Authentifizierungsfunktion von Rancher und der RBAC-Kontrolle zur Unterstützung von Multi-Tenancy.
