= Criando um Cluster DigitalOcean
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: procedimentos/guias-para-novos-usuários/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/criar-um-cluster-digitalocean.adoc 
:product-path: cluster-deployment/infra-providers/digitalocean/digitalocean.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-digitalocean-machine-configuration: xref:cluster-deployment/infra-providers/digitalocean/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-rke2.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:guias-de-procedimentos/guias-para-novos-usuarios/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-infra-provider/index.adoc
:xref-k3s-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-k3s.adoc
:xref-digitalocean-machine-configuration: xref:guias-de-referência/configuração-do-cluster/configuração-do-cluster-downstream/configuração-da-máquina/digitalocean.adoc
endif::[]

Nesta seção, você aprenderá como implantar um cluster Kubernetes {url-rke2-landing-page}[RKE2] ou {url-k3s-landing-page}[K3s] na DigitalOcean.

Primeiro, você configura suas credenciais de nuvem DigitalOcean no Rancher.

Em seguida, você cria um cluster DigitalOcean no Rancher e, ao configurar o novo cluster, define os pools de máquinas para ele. Cada pool de máquinas tem um papel Kubernetes: etcd, plano de controle ou worker. O Rancher instala o Kubernetes nos novos nós e configura cada nó com o papel Kubernetes definido pelo pool de máquinas.

[#_create_your_cloud_credentials]
== Crie suas credenciais de nuvem

Se você já possui um conjunto de credenciais de nuvem para usar, pule esta seção.

. Clique em *☰ > Gerenciamento de Cluster*.
. Clique em *Credenciais de Nuvem*.
. Clique em *Criar*.
. Clique *DigitalOcean*.
. Insira suas credenciais da DigitalOcean.
. Clique em *Criar*.

[#_create_your_cluster]
== Crie seu cluster

Use o Rancher para criar um cluster Kubernetes na DigitalOcean.

. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique em *Criar*.
. Ative o interruptor para *RKE2/K3s*.
. Clique *DigitalOcean*.
. Selecione uma *Credencial de Nuvem*, se houver mais de uma. Caso contrário, está pré-selecionada.
. Digite um *Nome do Cluster*.
. Crie um pool de máquinas para cada função do Kubernetes. Consulte as {xref-infra-providers}#_node_roles[melhores práticas] para recomendações sobre atribuições e contagens de funções.
 .. Para cada pool de máquinas, defina a configuração da máquina. Consulte a {xref-digitalocean-machine-configuration}[referência de configuração de máquinas da DigitalOcean] para obter informações sobre as opções de configuração.
. Use a *Configuração do Cluster* para escolher a versão do Kubernetes a ser instalada, qual provedor de rede usar e se deseja habilitar o isolamento de rede do projeto. Para ajuda na configuração do cluster, consulte as referências de configuração do {xref-rke2-config}[RKE2] e {xref-k3s-config}[K3s].
. Use *Funções de Membro* para configurar a autorização de usuários para o cluster. Clique em *Adicionar Membro* para adicionar usuários que podem acessar o cluster. Use o menu suspenso *Função* para definir permissões para cada usuário.
. Clique em *Criar*.

*Resultado:*

Seu cluster foi criado e atribuído ao estado de *Provisionamento*. O Rancher está configurando seu cluster.

Você pode acessar seu cluster após seu estado ser atualizado para *Ativo*.

Clusters *Ativos* são atribuídos a dois projetos:

* `Default`, contendo o namespace `default`
* `System`, contendo os namespaces `cattle-system`, `traefik`, `kube-public` e `kube-system`

[#_optional_next_steps]
== Próximas etapas opcionais

Após criar seu cluster, você pode acessá-lo através da interface do Rancher. Como uma melhor prática, recomendamos configurar essas maneiras alternativas de acessar seu cluster:

* *Acesse seu cluster com a CLI kubectl:* Siga {xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[estas etapas] para acessar clusters com kubectl em sua estação de trabalho. Neste caso, você será autenticado através do proxy de autenticação do servidor Rancher, e então o Rancher o conectará ao cluster downstream. Este método permite que você gerencie o cluster sem a interface do Rancher.
* *Acesse seu cluster com a CLI kubectl, usando o endpoint autorizado do cluster:* Siga {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[estas etapas] para acessar seu cluster com kubectl diretamente, sem autenticar através do Rancher. Recomendamos configurar este método alternativo para acessar seu cluster, para que, caso você não consiga se conectar ao Rancher, ainda possa acessar o cluster.
