= Hinzufügen eines Sidecars
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/add-a-sidecar.adoc 
:product-path: cluster-admin/kubernetes-resources/workloads-and-pods/add-a-sidecar.adoc
ifeval::["{build-type}" != "community"]
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
endif::[]

Ein _Sidecar_ ist ein Container, der den Hauptcontainer in einem Pod erweitert oder verbessert. Der Hauptcontainer und das Sidecar teilen sich einen Pod und somit denselben Netzwerkraum und Speicher. Sie können Sidecars zu bestehenden Workloads hinzufügen, indem Sie die Option *Sidecar hinzufügen* verwenden.

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie ein Sidecar hinzufügen möchten, und klicken Sie auf *Erkunden*.
. Klicken Sie in der linken Navigationsleiste auf *Workload*.
. Finden Sie den Workload, den Sie erweitern möchten. Wählen Sie *⋮ > + Sidecar hinzufügen*.
. Geben Sie einen *Namen* für das Sidecar ein.
. Wählen Sie im Abschnitt *Allgemein* einen Sidecar-Typ aus. Diese Option bestimmt, ob der Sidecar-Container vor oder nach dem Hauptcontainer bereitgestellt wird.
 ** *Standard-Container:*
+
Der Sidecar-Container wird nach dem Hauptcontainer bereitgestellt.

 ** *Init-Container:*
+
Der Sidecar-Container wird vor dem Hauptcontainer bereitgestellt.
. Geben Sie im Feld *Container-Image* den Namen des Container-Images ein, das Sie zur Unterstützung des Hauptcontainers bereitstellen möchten. Während der Bereitstellung zieht Rancher dieses Image von https://hub.docker.com/explore/[Docker Hub]. Geben Sie den Namen genau so ein, wie er auf Docker Hub erscheint.
. Legen Sie die verbleibenden Optionen fest. Sie können darüber in {xref-deploy-workloads}[Bereitstellung von Workloads] lesen.
. Klicken Sie auf *Starten*.

*Ergebnis:* Das Sidecar wird gemäß Ihren Parametern bereitgestellt. Nach der Bereitstellung können Sie das Sidecar anzeigen, indem Sie *⋮-Symbol (...) > Bearbeiten* für die Hauptimplementierung auswählen.

[#_related_links]
== Verwandte Themen

* https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/[Das Distributed System ToolKit: Schemata für zusammengesetzte Container]
