= Kubernetes-Workloads und Pods
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc 
:product-path: cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:description: Erfahren Sie mehr über die beiden Konstrukte, mit denen Sie jede komplexe containerisierte Anwendung in Kubernetes erstellen können: Kubernetes-Workloads und Pods
ifeval::["{build-type}" != "community"]
:xref-deploy-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/deploy-workloads.adoc
:xref-upgrade-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:cluster-admin/kubernetes-resources/workloads-and-pods/roll-back-workloads.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-deploy-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/deploy-workloads.adoc
:xref-upgrade-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/upgrade-workloads.adoc
:xref-roll-back-workloads: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/roll-back-workloads.adoc
endif::[]

Sie können jede komplexe containerisierte Anwendung in Kubernetes mit zwei grundlegenden Konstrukten erstellen: Pods und Workloads. Sobald Sie eine Anwendung erstellt haben, können Sie sie entweder innerhalb des gleichen Clusters oder im Internet über ein drittes Konstrukt, die Dienste, zugänglich machen.

[#_pods]
== Pods

https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/[_Pods_] sind ein oder mehrere Container, die sich Netzwerk-Namensräume und Speicher-Volumes teilen. Die meisten Pods haben nur einen Container. Daher ist der Begriff _Pods_ oft synonym mit _Containern_. Sie skalieren Pods auf die gleiche Weise, wie Sie Container skalieren--, indem Sie mehrere Instanzen desselben Pods haben, die einen Dienst implementieren. In der Regel werden Pods durch die Workloads skaliert und verwaltet.

[#_workloads]
== Workloads

_Workloads_ sind Objekte, die Implementierungsregeln für Pods festlegen. Basierend auf diesen Regeln führt Kubernetes die Implementierung durch und aktualisiert den Workload mit dem aktuellen Zustand der Anwendung.
Workloads ermöglichen es Ihnen, die Regeln für die Anwendungsplanung, Skalierung und Upgrade festzulegen.

[#_workload_types]
=== Workload-Typen

Kubernetes unterteilt Workloads in verschiedene Typen. Die beliebtesten von Kubernetes unterstützten Typen sind:

* https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Implementierungen]
+
_Implementierungen_ eignen sich am besten für zustandslose Anwendungen (d.h. wenn Sie den Zustand des Workloads nicht aufrechterhalten müssen). Pods, die von Implementierungs-Workloads verwaltet werden, werden als unabhängig und entbehrlich behandelt. Wenn ein Pod auf Störungen stößt, entfernt Kubernetes ihn und erstellt ihn dann neu. Eine Beispielanwendung wäre ein Nginx-Webserver.

* https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/[Zustandssets]
+
_Zustandssets_ hingegen eignen sich am besten, wenn Ihre Anwendung ihre Identität aufrechterhalten und Daten speichern muss. Eine Anwendung wäre etwas wie Zookeeper--eine Anwendung, die eine Datenbank für die Speicherung benötigt.

* https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSets]
+
_DaemonSets_ stellt sicher, dass jeder Knoten im Cluster eine Kopie des Pods ausführt. Für Anwendungsfälle, in denen Sie Protokolle sammeln oder die Leistung von Knoten überwachen, funktioniert dieser daemonähnliche Workload am besten.

* https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/[Jobs]
+
_Jobs_ starten einen oder mehrere Pods und stellen sicher, dass eine bestimmte Anzahl von ihnen erfolgreich beendet wird. Jobs eignen sich am besten, um eine endliche Aufgabe bis zur Vollendung auszuführen, anstatt einen fortlaufenden gewünschten Anwendungszustand zu verwalten.

* https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/[CronJobs]
+
_CronJobs_ sind ähnlich wie Jobs. CronJobs hingegen werden nach einem cron-basierten Zeitplan bis zur Vollendung ausgeführt.

[#_services]
== Services

In vielen Anwendungsfällen muss ein Workload entweder:

* Von anderen Workloads im Cluster zugegriffen werden.
* Der Außenwelt ausgesetzt.

Sie können diese Ziele erreichen, indem Sie einen _Service_ erstellen. Services werden mithilfe eines https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#service-and-replicationcontroller[Selectors/Label-Ansatzes (siehe die Codebeispiele)] den zugrunde liegenden Pods des Workloads zugeordnet. Die Rancher UI vereinfacht diesen Zuordnungsprozess, indem sie automatisch einen Service zusammen mit dem Workload erstellt, wobei der von Ihnen ausgewählte Serviceport und -typ verwendet werden.

[#_service_types]
=== Service-Typen

Es stehen mehrere Arten von Services in Rancher zur Verfügung. Die folgenden Beschreibungen stammen aus der https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types[Kubernetes-Dokumentation].

* *ClusterIP*
+
____
Exponiert den Dienst an einer clusterinternen IP. Die Wahl dieses Wertes macht den Dienst nur innerhalb des Clusters erreichbar. Dies ist der Standard `ServiceType`.
____

* *NodePort*
+
____
Exponiert den Dienst an der IP jedes Knotens an einem statischen Port (dem `NodePort`). Ein `ClusterIP` Dienst, an den der `NodePort` Dienst weiterleitet, wird automatisch erstellt. Sie können den `NodePort` Dienst von außerhalb des Clusters erreichen, indem Sie `<NodeIP>:<NodePort>` anfordern.
____

* *LoadBalancer*
+
____
Exponiert den Dienst extern mithilfe eines Load Balancers des Cloud-Anbieters. `NodePort` und `ClusterIP` Dienste, an die der externe Load Balancer weiterleitet, werden automatisch erstellt.
____

[#_workload_options]
== Workload-Optionen

Dieser Abschnitt der Dokumentation enthält Anweisungen zum Bereitstellen von Workloads und zur Verwendung von Workload-Optionen.

* {xref-deploy-workloads}[Workloads bereitstellen]
* {xref-upgrade-workloads}[Workloads Upgrade]
* {xref-roll-back-workloads}[Workloads Rollback]

[#_related_links]
== Verwandte Themen

* https://kubernetes.io/docs/concepts/services-networking/service/[Services]
