= 使用 启动 Kubernetes{rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc 
:product-path: cluster-deployment/launch-kubernetes-with-rancher.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-introduction: https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html
:url-k3s: https://documentation.suse.com/cloudnative/k3s
:url-rke2-requirements: https://documentation.suse.com/cloudnative/rke2/latest/en/install/requirements.html
:xref-clean-cluster-nodes: xref:cluster-admin/manage-clusters/clean-cluster-nodes.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s: https://docs.k3s.io/
:url-rke2-introduction: https://docs.rke2.io/
:url-rke2-requirements: https://docs.rke2.io/install/requirements
:xref-clean-cluster-nodes: xref:how-to-guides/new-user-guides/manage-clusters/clean-cluster-nodes.adoc
endif::[]

Rancher 允许您在不同类型的节点上启动 Kubernetes 集群，包括裸机服务器、本地虚拟机和基础设施提供商的虚拟机。在将 Kubernetes 部署到这些节点时，Rancher 让您可以选择使用 {url-rke2-introduction}[RKE2] 或 {url-k3s}[K3s]。

Rancher 可以在现有节点上安装 Kubernetes，或者它可以在基础设施提供商中动态配置节点并在其上安装 Kubernetes。

Rancher 还可以创建机器池。在由基础设施提供商托管的机器池上安装 Kubernetes 的一个好处是，如果某个节点与集群失去连接，Rancher 可以自动创建另一个节点加入集群，以确保机器池的数量符合预期。

[#__rke2_product_name]
== {rke2-product-name}

Rancher v2.6 直接通过 Rancher UI 为 {url-rke2-introduction}[RKE2] 集群提供配置。RKE2，也称为 RKE 政府，是一款完全符合认证标准的 Kubernetes 发行版，专注于美国的安全和合规性。安全和合规要求。在 Rancher v.2.6.4 及更早版本中，RKE2 配置处于技术预览阶段。

请注意，在 Rancher v2.6.5 中，RKE2 配置已成为 GA。

[#_requirements]
=== 要求

如果您使用 RKE2 设置集群，则您的节点必须满足下游用户集群中节点的 {url-rke2-requirements}[要求]。

[#_launching_kubernetes_on_new_nodes_in_an_infrastructure_provider]
=== 在基础设施提供商中新节点上部署 Kubernetes

RKE2 配置建立在一个新的配置框架之上，该框架利用了上游的 https://github.com/kubernetes-sigs/cluster-api[集群 API (CAPI)] 项目。使用这个新的配置框架，您可以：

* 在 Rancher 拥有节点驱动程序的任何提供商上配置 RKE2 集群。
* 在 Rancher 中完全配置 RKE2 集群。
* 选择 CNI 选项 Calico、Cilium 和 Multus，此外还有 Canal。

当您在 RKE2 中对集群配置进行更改时，这可能会导致节点重新配置。这由 CAPI 控制器控制，而不是由 Rancher 本身控制。请注意，对于 etcd 节点，情况并非如此。

可能导致上述行为的一个示例配置更改是编辑集群并在删除前启用排空。在这种情况下，现有的控制平面节点和工作节点将被删除，并创建新的节点。

RKE2 配置还包括在具有 Windows 节点的集群上安装 RKE2。

RKE2 的 Windows 功能包括：

* Windows 支持 vSphere 节点驱动程序
* Windows RKE2 自定义集群的 Calico 和 Flannel CNI
* Calico 的项目网络隔离 (PNI)
* Windows 容器与 RKE2（由 containerd 驱动）
* 通过 Terraform 配置 Windows RKE2 集群。
* 直接从 Rancher UI 配置 Windows RKE2 自定义集群。

RKE2 自定义集群的 Windows 支持要求选择 Calico 作为 CNI。

[#_launching_kubernetes_on_existing_custom_nodes]
=== 在现有自定义节点上启动Kubernetes

RKE2 配置还允许您在先前配置的虚拟机或裸机节点上安装自定义集群。

如果您想重用之前自定义集群中的节点，请在再次使用之前{xref-clean-cluster-nodes}#_cleaning_up_nodes[清理节点]。如果您重用未清理的节点，集群配置可能会失败。

[#_programmatically_creating_rke2_product_name_clusters]
=== 以编程方式创建 {rke2-product-name} 集群

通过 Rancher 以编程方式部署 RKE2 集群的最常见方式是使用 https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2[Rancher2 Terraform 提供者]。
