= {rancher-product-name} 管理的集群的节点要求
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-20
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc 
:product-path: cluster-deployment/node-requirements.adoc
ifeval::["{build-type}" != "community"]
:xref-use-windows-clusters: xref:cluster-deployment/custom-clusters/windows/use-windows-clusters.adoc
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-install-reqs: xref:installation-and-upgrade/requirements/requirements.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-security-overview: xref:security/security-overview.adoc
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
:xref-provisioning-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc
:xref-rancher-on-arm64: xref:rancher-admin/experimental-features/rancher-on-arm64.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-use-windows-clusters: xref:如何指南/新用户指南/在Rancher中设置Kubernetes集群/使用Windows集群/index.adoc
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-install-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/index.adoc 
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-security-overview: xref:reference-guides/rancher-security/index.adoc
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
:xref-provisioning-drivers: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/index.adoc
:xref-rancher-on-arm64: xref:how-to-guides/advanced-user-guides/enable-experimental-features/rancher-on-arm64.adoc
endif::[]

本页面描述了 Rancher 管理的 Kubernetes 集群的要求，您的应用和服务将安装在这些集群中。这些下游集群应与运行 Rancher 的三节点集群分开。

[NOTE]
====

如果 Rancher 安装在高可用性 Kubernetes 集群上，Rancher 服务器三节点集群和下游集群的要求是不同的。有关 Rancher 安装要求，请参阅 {xref-install-reqs}[安装部分]中的节点要求。
====


[#_operating_systems_and_container_runtime_requirements]
== 操作系统和容器运行时要求

Rancher 应与任何现代 Linux 发行套件和任何现代 Docker 版本兼容。所有下游集群的 etcd 和 controlplane 节点都需要 Linux。工作节点可以运行 Linux 或 <<_windows_nodes,Windows Server.>>

有关每个 Rancher 版本测试的操作系统和 Docker 版本的详细信息，请参阅 https://rancher.com/support-maintenance-terms/[支持维护条款。]

所有支持的操作系统均为 64 位 x86。

如果您计划使用 ARM64，请参见 {xref-rancher-on-arm64}[在 ARM64 上运行（实验性）]。

有关如何安装 Docker 的信息，请参阅官方 https://docs.docker.com/[Docker 文档。]

[#_oracle_linux_and_rhel_derived_linux_nodes]
=== Oracle Linux 和 RHEL 派生的 Linux 节点

一些基于 RHEL 的 Linux 发行版，包括 Oracle Linux，可能具有默认的防火墙规则，阻止与 Helm 的通信。我们建议禁用 firewalld。对于 Kubernetes 1.19，必须关闭 firewalld。

[NOTE]
====

在 RHEL 8.4 中，NetworkManager 中包含两个额外的服务：`nm-cloud-setup.service` 和 `nm-cloud-setup.timer`。这些服务添加的路由表会干扰 CNI 插件的配置。如果启用了这些服务，您必须使用以下命令禁用它们，然后重启节点以恢复连接：

----
   systemctl disable nm-cloud-setup.service nm-cloud-setup.timer
   reboot
----
====


[#_suse_linux_nodes]
=== SUSE Linux 节点

SUSE Linux 可能默认会有一个阻止所有端口的防火墙。在这种情况下，请按照{xref-port-reqs}#_opening_suse_linux_ports[这些步骤]打开添加主机到自定义集群所需的端口。

[#_flatcar_container_linux_nodes]
=== Flatcar容器Linux节点

当使用 Flatcar 容器 Linux 节点 {xref-launch-k8s-with-rancher}[启动 Kubernetes 与 Rancher] 时，需要在集群配置文件中使用以下配置。

[tabs]
======
Canal::
+
--
[,yaml]
----
rancher_kubernetes_engine_config:
  network:
    plugin: canal
    options:
      canal_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
      flannel_backend_type: vxlan

  services:
    kube-controller:
      extra_args:
        flex-volume-plugin-dir: /opt/kubernetes/kubelet-plugins/volume/exec/
----
--

Calico::
+
--
[,yaml]
----
rancher_kubernetes_engine_config:
  network:
    plugin: calico
    options:
      calico_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
      flannel_backend_type: vxlan

  services:
    kube-controller:
      extra_args:
        flex-volume-plugin-dir: /opt/kubernetes/kubelet-plugins/volume/exec/
----
--
======

还需要启用 Docker 服务，您可以使用以下命令启用 Docker 服务：

----
systemctl enable docker.service
----

使用{xref-provisioning-drivers}#_node_drivers[节点驱动程序]时，Docker 服务会自动启用。

[#_windows_nodes]
=== Windows节点

运行 Windows Server 的节点必须使用 Docker 企业版。

Windows节点仅可用作工作节点。请参见 {xref-use-windows-clusters}[为 Windows 配置自定义集群]

[#_hardware_requirements]
== 硬件要求

具有`worker`角色的节点的硬件要求主要取决于您的工作负载。运行 Kubernetes 节点组件的最低要求是 1 个 CPU（内核）和 1GB 内存。

关于 CPU 和内存，建议 Kubernetes 集群的不同平面（etcd、控制平面和工作节点）应托管在不同的节点上，以便它们可以独立扩展。

有关大型 Kubernetes 集群的硬件建议，请参阅官方 Kubernetes 文档中的 https://kubernetes.io/docs/setup/best-practices/cluster-large/[构建大型集群。]

有关生产环境中 etcd 集群的硬件建议，请参阅官方 https://etcd.io/docs/v3.5/op-guide/hardware/[etcd 文档。]

[#_networking_requirements]
== 网络要求

对于生产集群，我们建议通过仅打开下面端口要求中定义的端口来限制流量。

所需打开的端口因用户集群的启动方式而异。以下每个部分列出了不同的 {xref-cluster-deployment}[集群创建选项]所需打开的端口。

有关 Kubernetes 集群中 etcd 节点、控制平面节点和工作节点的端口要求的详细信息，请参阅 https://rancher.com/docs/rke/latest/en/os/#ports[Rancher Kubernetes 引擎的端口要求。]

每种情况使用的端口的详细信息可以在{xref-port-reqs}#_downstream_kubernetes_cluster_nodes[下游集群端口要求]中找到。

[#_ipv6_address_requirements]
=== IPv6 地址要求

Rancher 支持配置为仅 IPv4、仅 IPv6 或双栈网络的集群。

您必须根据集群网络配置为每个节点提供至少一个有效的 IPv4 地址、一个 IPv6 地址或两者。

对于仅 IPv6 的环境，请确保正确配置操作系统，并且 `/etc/hosts` 文件包含有效的 localhost 条目，例如：

[source,shell]
----
::1       localhost
----

[CAUTION]
====

您绝不应使用与现有节点相同的主机名或 IP 地址注册节点。这样会导致 RKE 阻止节点加入，并使配置挂起。这可能发生在节点驱动程序和自定义集群中。如果节点必须重用现有节点的主机名或 IP，您必须在注册节点之前设置 `hostname_override` https://rke.docs.rancher.com/config-options/nodes#overriding-the-hostname[RKE 选项]，以便它可以正确加入。
====


[#_optional_security_considerations]
== 可选：安全考虑

如果您想配置符合 CIS（互联网安全中心）Kubernetes 基准的 Kubernetes 集群，我们建议您在安装 Kubernetes 之前遵循我们的安全强化指南来配置节点。

有关安全强化指南的更多信息以及与您的 Rancher 和 Kubernetes 版本对应的指南版本的详细信息，请参阅 {xref-security-overview}#_rancher_hardening_guide[安全部分。]
