= Autres méthodes d'installation
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/other-installation-methods/index.adoc 
:product-path: installation-et-mise-à-niveau/autres-méthodes-d'installation/autres-méthodes-d'installation.adoc
ifeval::["{build-type}" != "community"]
:xref-air-gap: xref:installation-and-upgrade/other-installation-methods/air-gapped/air-gapped.adoc
:xref-migrate-cluster: xref:rancher-admin/back-up-restore-and-disaster-recovery/migrate-to-a-new-cluster.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-air-gap: xref:getting-started/installation-et-mise-à-niveau/autres-méthodes-d-installation/isolé-physiquement-helm-cli-install/index.adoc
:xref-migrate-cluster: xref:guides-pratiques/nouveaux-guides-utilisateurs/sauvegarde-restauration-et-récupération-en-cas-de-sinistre/migrer-rancher-vers-un-nouveau-cluster.adoc
endif::[]

[#_air_gapped_installations]
== Installations isolées physiquement

Suivez {xref-air-gap}[ces étapes] pour installer le serveur Rancher dans un environnement isolé physiquement.

Un environnement isolé physiquement pourrait être un endroit où le serveur Rancher sera installé hors ligne, derrière une passerelle de périmètre de sécurité ou un proxy.

[#_docker_installations]
== Installations Docker

L'xref:[installation Docker à nœud unique] est destinée aux utilisateurs de Rancher qui souhaitent tester Rancher. Au lieu de fonctionner sur un cluster Kubernetes en utilisant Helm, vous installez le composant serveur Rancher sur un nœud unique en utilisant une `docker run` commande.

L'installation Docker est uniquement destinée aux environnements de développement et de test.

Étant donné qu'il n'y a qu'un seul nœud et un seul conteneur Docker, si le nœud tombe en panne, il n'y a pas de copie des données etcd disponibles sur d'autres nœuds et vous perdrez toutes les données de votre serveur Rancher.

L'opérateur de sauvegarde de Rancher peut être utilisé pour migrer Rancher de l'installation unique de conteneur Docker vers une installation sur un cluster Kubernetes à haute disponibilité. Pour plus de détails, consultez la documentation sur {xref-migrate-cluster}[la migration de Rancher vers un nouveau cluster.]
