= Charts Helm et applis
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/helm-charts-in-rancher/index.adoc 
:product-path: cluster-admin/helm-charts-in-rancher/helm-charts-in-rancher.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-air-gap-rancher-ha: xref:installation-and-upgrade/other-installation-methods/air-gapped/install-rancher-ha.adoc
:xref-oci-repo: xref:cluster-admin/helm-charts-in-rancher/oci-repositories.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-air-gap-rancher-ha: xref:getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha.adoc
:xref-oci-repo: xref:how-to-guides/new-user-guides/helm-charts-in-rancher/oci-repositories.adoc
endif::[]

Dans cette section, vous apprendrez à gérer les dépôts de charts Helm et les applis dans Rancher.

[#_how_helm_charts_work_in_rancher]
== Comment fonctionnent les charts Helm dans Rancher

Les dépôts de charts Helm dans Rancher sont gérés à l'aide de *Applis*.

Rancher utilise un système de type catalogue pour importer des ensembles de charts Helm à partir de dépôts, puis utilise ces charts pour déployer des applis Kubernetes personnalisées ou des outils de Rancher tels que Monitoring ou Istio. Les outils de Rancher sont fournis sous forme de dépôts préchargés qui se déploient en tant que charts Helm autonomes. Tout dépôt supplémentaire n'est ajouté qu'au cluster actuel.

[#_catalogs_apps_and_the_rancher_ui]
=== Catalogues, Applis et l'interface utilisateur de Rancher

xref:[Rancher v2.4 et versions antérieures], les dépôts d'applis prêtes à déployer étaient appelés « catalogues ». Ces dépôts étaient gérés via la section *Catalogues* de l'interface utilisateur.

Rancher v2.5 a remplacé l'ancien système de catalogue par une nouvelle fonctionnalité *Applis & Marketplace*.

Depuis Rancher v2.6.5, la fonctionnalité *Applis & Marketplace* est nommée *Applis* dans l'interface utilisateur.

[#_versioning_scheme]
=== Schéma de versioning

Le schéma de versioning des charts de fonctionnalités de Rancher est centré sur la version majeure des charts et l'annotation `+up` pour les charts en amont, le cas échéant.

*Version majeure :* Les versions majeures des charts de fonctionnalités sont liées à des versions mineures particulières de Rancher. Lorsque vous mettez à niveau vers une nouvelle version mineure de Rancher, vous devez vous assurer que tous vos charts de fonctionnalités sont également mis à niveau vers la bonne ligne de version pour le chart.

*Charts basés sur en amont :* Lorsque vous effectuez une mise à niveau, assurez-vous que la version du chart en amont est compatible avec votre version de Rancher. L'annotation `+up` pour le chart indique quelle version en amont le chart Rancher suit. Par exemple, `100.x.x+up16.6.0` pour Monitoring suit le kube-prometheus-stack en amont `16.6.0` avec quelques correctifs supplémentaires de Rancher.

Lors de la mise à niveau des versions de Rancher, ne rétrogradez pas la version du graphique que vous utilisez. Par exemple, si vous utilisez une version de Monitoring qui est postérieure à `16.6.0` dans Rancher v2.5, vous ne devriez pas mettre à niveau vers `100.x.x+up16.6.0`. Au lieu de cela, vous devriez mettre à niveau vers la version appropriée dans la prochaine version.

[#_prerelease_versions]
==== Versions de prépublication

Les prépublications adhèrent à https://semver.org/#spec-item-9[la spécification] définie par https://semver.org/[Semantic Versioning 2.0.0]. Par exemple, un chart Helm avec une version de `0.1.3-dev.12ab4f` est considéré comme une prépublication. Les versions de prépublication ne sont pas affichées par défaut et doivent être configurées pour le faire.

Pour afficher les versions de prépublication{nbsp}:

. Cliquez sur votre avatar utilisateur dans le coin supérieur droit.
. Cliquez sur *Préférences*.
. Sous *Charts Helm*, sélectionnez *Inclure les versions de prépublication*.

[#_access_charts]
== Accéder aux Charts

La page *Charts* contient tous les charts Rancher, partenaires et personnalisés. Vous pouvez filtrer les charts en sélectionnant le menu déroulant le plus à gauche{nbsp}:

* Les outils Rancher tels que Logging ou Monitoring sont répertoriés sous l'étiquette *Rancher*.
* Les charts des partenaires sont sous l'étiquette *Partenaires*.
* Les charts personnalisés sont répertoriés sous le nom de leur dépôt respectif.

Les trois types de charts sont déployés et gérés de la même manière.

[NOTE]
====

Les applis gérées par le Cluster Manager (la vue globale dans l'interface utilisateur héritée de Rancher) continuent d'être gérées uniquement par le Cluster Manager, et les applis gérées avec *Apps* dans la nouvelle interface utilisateur doivent être gérées uniquement par *Apps*.
====


Pour accéder à la page *Charts*{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Trouvez le nom du cluster dont vous souhaitez accéder aux charts. Cliquez sur *Explorer* à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche du *Tableau de bord du Cluster*, cliquez sur menu:Apps[Charts].

[#_manage_repositories]
== Gérer les dépôts

La page *Dépôts* liste vos dépôts Helm. Ceci inclut les points de terminaison Helm traditionnels qui ont un index.yaml, et les dépôts Git qui sont clonés et pointent vers une branche spécifique. Pour utiliser des charts personnalisés, ajoutez votre dépôt ici. Après avoir ajouté un dépôt, vous pouvez accéder aux charts personnalisés dans la page *Charts*, listés sous le nom du dépôt.

Pour accéder à la page *Dépôts*{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Trouvez le nom du cluster dont vous souhaitez accéder aux dépôts. Cliquez sur *Explorer* à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche du *Tableau de bord du Cluster*, cliquez sur menu:Apps[Dépôts].

[#_add_custom_git_repositories]
=== Ajouter des Dépôts Git Personnalisés

Pour ajouter un dépôt Git personnalisé contenant vos charts Helm ou définitions de modèles de cluster{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Trouvez le nom du cluster dont vous souhaitez accéder aux dépôts. Cliquez sur *Explorer* à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche du *Tableau de bord du Cluster*, cliquez sur menu:Apps[Dépôts].
. Cliquez sur *Create*.
. Sélectionnez la cible, *Dépôt Git contenant le chart Helm...*.
. Vous devez entrer un nom et une URL de dépôt Git. Les autres champs, y compris la description, sont optionnels. Entrez un nom de branche alternatif si vous ne souhaitez pas tirer de la branche par défaut définie par le propriétaire du dépôt. En général, la branche par défaut est nommée soit `main` soit `master`.
. Cliquez sur *Créer* pour ajouter le dépôt.

Après avoir ajouté un dépôt de charts à Rancher, il devient immédiatement disponible.

[#_add_custom_helm_chart_repositories]
=== Ajouter des dépôts de charts Helm personnalisés

Vous pouvez ajouter vos propres dépôts de charts Helm pour servir des paquets de charts à Rancher. Vous pouvez utiliser n'importe quel serveur HTTP, tant que le serveur peut répondre aux requêtes GET et servir des fichiers YAML et des tarballs.

Pour plus d'informations sur les dépôts de charts Helm, consultez la https://helm.sh/docs/topics/chart_repository/[documentation officielle de Helm].

Pour ajouter un dépôt de charts Helm personnalisé à Rancher{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Trouvez le nom du cluster dont vous souhaitez accéder aux dépôts. Cliquez sur *Explorer* à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche du *Tableau de bord du Cluster*, cliquez sur menu:Apps[Dépôts].
. Cliquez sur *Create*.
. Sélectionnez la cible, *URL http(s) vers un index généré par Helm*.
. Entrez un nom du dépôt et l'adresse URL de l'index du dépôt de charts.
. Cliquez sur *Créer* pour ajouter le dépôt.

[#_add_private_git_helm_chart_repositories]
=== Ajouter des dépôts de charts Git/Helm privés

Vous pouvez ajouter des dépôts de charts Git ou Helm privés avec des identifiants de clé SSH ou un secret d'authentification HTTP de base, tel qu'un nom d'utilisateur et un mot de passe.

[#_add_a_private_ca_to_repositories]
=== Ajouter une CA privée aux dépôts

Pour ajouter une CA privée aux dépôts de charts Helm, vous devez ajouter une copie encodée en base64 du certificat CA au format DER dans le `spec.caBundle field` du dépôt de charts, tel que `openssl x509 -outform der -in ca.pem | base64 -w0`. Les instructions sont les mêmes pour les dépôts basés sur Git et ceux basés sur HTTP{nbsp}:

. Click *☰*. Sous *Explorer le Cluster* dans le menu de navigation à gauche, sélectionnez un cluster.
. Dans le menu de navigation à gauche du *Tableau de bord du Cluster*, cliquez sur menu:Applications[Dépôts].
. Trouvez la ligne associée au dépôt basé sur Git ou HTTP auquel vous souhaitez ajouter une CA privée, et cliquez sur *⋮ > Modifier YAML*.
. Définissez la valeur `caBundle`, comme dans l'exemple suivant{nbsp}:

[,yaml]
----
    [...]
    spec:
      caBundle:
    MIIFXzCCA0egAwIBAgIUWNy8WrvSkgNzV0zdWRP79j9cVcEwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRQwEgYDVQQKDAtNeU9yZywgSW5jLjENMAsGA1UEAwwEcm9vdDAeFw0yMTEyMTQwODMyMTdaFw0yNDEwMDMwODMyMT
    ...
    nDxZ/tNXt/WPJr/PgEB3hQdInDWYMg7vGO0Oz00G5kWg0sJ0ZTSoA10ZwdjIdGEeKlj1NlPyAqpQ+uDnmx6DW+zqfYtLnc/g6GuLLVPamraqN+gyU8CHwAWPNjZonFN9Vpg0PIk1I2zuOc4EHifoTAXSpnjfzfyAxCaZsnTptimlPFJJqAMj+FfDArGmr4=
    [...]
----

[NOTE]
.Dépôts de charts Helm avec authentification
====

Le Repo.Spec contient une valeur `disableSameOriginCheck`. Cette valeur vous permet de contourner les vérifications de même origine, en envoyant les informations d'authentification du dépôt en tant qu'en-tête d'authentification de base avec tous les appels API. Cela n'est pas recommandé mais peut être utilisé comme solution temporaire dans le cas de dépôts de charts Helm non standards, tels que ceux qui redirigent vers une URL d'origine différente.

Pour utiliser cette fonctionnalité pour un dépôt de charts Helm existant, suivez les étapes précédentes jusqu'à modifier le YAML. Dans la portion `spec` du fichier YAML, ajoutez `disableSameOriginCheck` et définissez-le sur `true`.

[,yaml]
----
[...]
spec:
  disableSameOriginCheck: true
[...]
----
====


[#_add_custom_oci_chart_repositories]
=== Ajouter des dépôts de charts OCI personnalisés

Helm v3 a introduit le stockage des charts Helm en tant qu'artefacts https://opencontainers.org/about/overview/[Open Container Initiative (OCI)] dans des registres de conteneur. Avec Rancher v2.9.0, vous pouvez ajouter https://helm.sh/docs/topics/registries/[des dépôts de chart Helm basés sur OCI] aux dépôts basés sur HTTP et Git. Cela signifie que vous pouvez déployer des applications qui sont stockées en tant qu'artefacts OCI. Pour plus d'informations, voir {xref-oci-repo}[Utilisation des dépôts de chart Helm OCI].

[#_helm_compatibility]
=== Compatibilité Helm

Seuls les charts compatibles avec Helm 3 sont pris en charge.

[#_refresh_chart_repositories]
=== Rafraîchir les dépôts de chart

Le bouton *Rafraîchir* peut être utilisé pour synchroniser les modifications des dépôts de chart sélectionnés sur la page *Dépôts*.

Pour rafraîchir un dépôt de chart{nbsp}:

. Cliquez sur *☰ > Gestion des clusters*.
. Trouvez le nom du cluster dont vous souhaitez accéder aux dépôts. Cliquez sur *Explorer* à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche du *Tableau de bord du Cluster*, cliquez sur menu:Applications[Dépôts].
. Utilisez le commutateur à côté du champ *État* pour sélectionner tous les dépôts, ou activez les dépôts de chart spécifiés pour synchroniser les modifications.
. Cliquez sur *Rafraîchir*.
. Le *⋮* à la fin de chaque ligne de dépôt de chart inclut également une option *Rafraîchir*, qui peut être cliquée pour rafraîchir le dépôt respectif.

Les installations Rancher non Airgap, lors du rafraîchissement, refléteront immédiatement les modifications du dépôt de chart et vous verrez le champ *État* pour les dépôts mis à jour passer de `In Progress` à `Active` une fois l'action terminée.

Les installations Airgap où Rancher est configuré pour utiliser la copie empaquetée des charts système Helm ({xref-air-gap-rancher-ha}#_options_de_chart_helm_pour_installations_air_gap[`useBundledSystemChart=true`]) ne se référeront qu'au dépôt https://github.com/rancher/system-charts[chart-système] qui est inclus et ne pourra pas être rafraîchi ou synchronisé.

[#_refresh_interval]
==== Intervalle de rafraîchissement

Rancher v2.10.0 ajoute le champ `refreshInterval` au CRD `ClusterRepo`. La valeur par défaut est de 3600 secondes, ce qui signifie que Rancher synchronise chaque dépôt Helm toutes les 3600 secondes.

Pour modifier l'intervalle de rafraîchissement d'un dépôt de chart{nbsp}:

. Cliquez sur **☰ > Gestion des clusters**.
. Trouvez le nom du cluster dont vous souhaitez accéder aux dépôts. Cliquez sur **Explorer** à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche sur le **Tableau de bord du cluster**, cliquez sur **Applications > Dépôts**.
. Trouvez le dépôt que vous souhaitez modifier, puis cliquez sur **⋮ > Modifier YAML**.
. Définissez le champ **refreshInterval** sous **Spécification** à la valeur souhaitée en secondes.
. Cliquez sur **Enregistrer**.

[#_enable_disable_helm_chart_repositories]
=== Activer/Désactiver les dépôts de chart Helm

Rancher v2.10.0 ajoute la possibilité d'activer et de désactiver les dépôts Helm. Les dépôts Helm sont activés par défaut.

Pour désactiver un dépôt de chart{nbsp}:

. Cliquez sur **☰ > Gestion des clusters**.
. Trouvez le nom du cluster dont vous souhaitez accéder aux dépôts. Cliquez sur **Explorer** à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche sur le **Tableau de bord du cluster**, cliquez sur **Applications > Dépôts**.
. Trouvez le dépôt que vous souhaitez désactiver, puis cliquez sur **⋮ > Modifier YAML**.
. Définissez le champ **Activé** sous **Spécification** à **false**.
. Cliquez sur **Enregistrer**.
. Lorsque vous désactivez un dépôt, les mises à jour sont désactivées et les nouvelles modifications du clusterRepo ne sont pas appliquées.

Pour activer un chart :

. Cliquez sur **☰ > Gestion des clusters**.
. Trouvez le nom du cluster dont vous souhaitez accéder aux dépôts. Cliquez sur **Explorer** à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche sur le **Tableau de bord du cluster**, cliquez sur **Applications > Dépôts**.
. Trouvez le dépôt que vous souhaitez désactiver, puis cliquez sur **⋮ > Modifier YAML**.
. Définissez le champ **Activé** sous **Spécification** à **true**.
. Cliquez sur **Enregistrer**.

[#_deploy_and_upgrade_charts]
== Déployer et mettre à niveau des charts

Pour installer et déployer un chart :

. Cliquez sur *☰ > Gestion des clusters*.
. Trouvez le nom du cluster dont vous souhaitez accéder aux dépôts. Cliquez sur *Explorer* à la fin de la ligne du cluster.
. Dans le menu de navigation à gauche du *Tableau de bord du Cluster*, cliquez sur menu:Applications[Charts].
. Sélectionnez un chart, puis cliquez sur *Installer*.

Les charts Rancher et Partenaire peuvent avoir des configurations supplémentaires disponibles via des pages personnalisées ou des fichiers questions.yaml. Cependant, toutes les installations de charts peuvent modifier le fichier values.yaml et d'autres paramètres de base. Après avoir cliqué sur *Installer*, un travail d'opération Helm est déployé, et la console pour le travail est affichée.

Pour voir tous les changements récents, cliquez sur menu:Applications[Opérations récentes] dans le menu de navigation à gauche. De là, vous pouvez voir les appels, conditions, événements et journaux.

Après avoir installé un chart, vous pouvez le visualiser en cliquant sur menu:Applications[Applications installées] dans le menu de navigation à gauche. Vous pouvez mettre à niveau ou supprimer l'installation, et voir plus de détails. La mise à niveau utilise les mêmes formulaires et valeurs que ceux que vous avez vus lors de l'installation initiale.

La plupart des outils Rancher ont des pages supplémentaires situées dans la barre d'outils en dessous de la section *Applications* pour aider à gérer et utiliser les fonctionnalités. Ces pages incluent des liens vers des tableaux de bord, des formulaires pour ajouter facilement des ressources personnalisées, et des informations supplémentaires.

[CAUTION]
====

Si vous mettez à niveau votre chart en utilisant *Personnaliser les options Helm avant la mise à niveau*, et que votre chart contient des champs immuables, l'utilisation de l'option `--force` peut entraîner des erreurs. C'est parce que certains objets dans Kubernetes ne peuvent pas être modifiés après leur création. Pour éviter cette erreur{nbsp}:

* Utilisez l'option de mise à niveau par défaut (c'est-à-dire ne pas utiliser `--force`).
* Désinstallez le chart existant et installez le chart mis à niveau.
* Supprimez les ressources avec des champs immuables du cluster avant d'effectuer une mise à niveau forcée.
====


[#_legacy_apps]
=== Applications héritées

Le bouton de mise à niveau n'est pas disponible pour les applications héritées sur la page menu:Applications[Applications installées].

Si vous souhaitez mettre à niveau une appli héritée installée, le {xref-experimental-features}[drapeau de fonctionnalité héritée] doit être activé. Ce drapeau est automatiquement activé si vous aviez déjà une appli héritée en cours d'exécution avant de mettre à niveau Rancher.

. Activez le {xref-experimental-features}[drapeau de fonctionnalité héritée], s'il n'est pas déjà activé.
. Cliquez sur *☰ > Gestion des clusters*.
. Trouvez le nom du cluster dont vous souhaitez accéder aux applications. Cliquez sur *Explorer* à la fin de la ligne du cluster.
. Cliquez sur menu:Héritées[Projet> Applications].

Si vous ne voyez pas *Applications* listées sous menu:Héritées[Projet], cliquez sur la barre de recherche de projet/espace de noms dans la navigation en haut et sélectionnez le projet pertinent dans le menu déroulant.

Pour mettre à niveau les applications héritées multi-cluster{nbsp}:

. Click *☰*.
. Sous *Applications héritées*, cliquez sur *Applications multi-cluster*.

[#_chart_specific_information]
=== Informations spécifiques au chart

[#_sriov_chart_deprecation_and_migration]
==== Cessation de prise en charge et migration du chart sriov

Le chart `sriov` (opérateur de réseau SR-IOV) du dépôt Rancher Charts n'est plus pris en charge et sera supprimé dans Rancher v2.10. Veuillez migrer vers le chart `sriov-network-operator` du dépôt SUSE Edge (https://github.com/suse-edge/charts) à la place.

Pour migrer, suivez ces étapes{nbsp}:

. Ajoutez le dépôt SUSE Edge à votre cluster en suivant les étapes dans <<_add_custom_git_repositories,Ajouter des dépôts Git personnalisés>>.
. Pour le champ *URL du dépôt Git*, entrez `https://github.com/suse-edge/charts`.
. Cliquez sur *Create*.
. Dans le menu de navigation à gauche du *Tableau de bord du Cluster*, cliquez sur menu:Applications[Charts].
. Trouvez le chart `sriov-network-operator` et cliquez dessus.
. Cliquez sur *Installer*.
. Dans le champ *Nom*, entrez le même nom que celui que vous avez utilisé pour votre installation de chart `sriov` existante.
. Cliquez sur *Next*.
. Cliquez sur *Installer*.

*Résultat :* Rancher redirige vers la page *Applications installées* où votre installation existante entre dans l'état *Mise à jour*. La migration est complète lorsqu'elle entre dans l'état *Déployé*.

[#_limitations]
== limites

* Les applications de tableau de bord ou les charts de fonctionnalités Rancher ne peuvent pas être installés en utilisant le Rancher CLI.
* Lors de la détermination de la version la plus récente à afficher pour la colonne *Upgradable* sur la page menu:Applis[Applis installées], plutôt que de considérer uniquement les versions du chart Helm du dépôt à partir duquel il a été installé, Rancher considère les versions du chart Helm de tous les dépôts sur le cluster.
+
Par exemple, supposons que vous installiez `cert-manager` v1.13.0 à partir du dépôt A, où v1.14.0 est maintenant la version la plus récente disponible. Dans ce cas, vous vous attendez à ce que *Upgradable* affiche v1.14.0. Cependant, si le cluster a également accès au dépôt B où v1.15.0 de `cert-manager` est disponible, alors *Upgradable* affiche v1.15.0 même si l'installation originale a utilisé le dépôt A.
