= 创建 Google Compute Engine 集群
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-google-compute-engine-cluster.adoc 
:product-path: cluster-deployment/infra-providers/gce/gce.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-infra-gce-machine-config: xref:cluster-deployment/infra-providers/gce/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:参考指南/集群配置/Rancher 服务器配置/rke2-cluster-configuration.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-k3s-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc
:xref-infra-gce-machine-config: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/google-gce.adoc
endif::[]

在本节中，您将学习如何使用 Rancher 在 Google Cloud Platform (GCP) 上通过 Google Compute Engine (GCE) 提供 {url-rke2-landing-page}[RKE2] 或 {url-k3s-landing-page}[K3s] Kubernetes 集群。

首先，您需要在 Rancher UI 中启用 GCE 节点驱动程序。然后，您按照步骤创建一个具有必要权限的 GCP 服务帐户，并生成一个 JSON 密钥文件。此密钥文件将用于在 Rancher 中创建云凭据。

接下来，您将在 Rancher 中创建一个 GCE 集群，并在配置集群时定义机器池。每个机器池将具有 etcd、controlplane 或 worker 的 Kubernetes 角色。Rancher 将在新节点上安装 RKE2，并根据机器池定义的 Kubernetes 角色设置每个节点。

. <<_enable_the_gce_node_driver>>
. <<_create_a_cloud_credential>>
. <<_create_a_cluster_using_the_cloud_credential>>
. <<_gce_best_practices>>

[#_prerequisites]
== 先决条件

.  有效的 Google Cloud Platform 帐户和项目。
.  GCP 服务帐户 JSON 密钥文件。与此密钥关联的服务帐户必须具有以下 IAM 角色：
.. **计算管理员**
.. **服务帐户用户**
.. **查看器**
. 一个用于在其中提供虚拟机的 VPC 网络。

有关创建和管理服务帐户密钥的更多详细信息，请参阅 https://cloud.google.com/iam/docs/service-account-overview[GCP 文档]。

[#_enable_the_gce_node_driver]
== 启用 GCE 节点驱动程序

GCE 节点驱动程序在 Rancher 中默认未启用。您必须在提供 GCE 集群或使用 GCE 特定 CRD 之前启用它。

. 单击 **☰ > 集群管理**。
. 在左侧，点击**驱动程序**。
. 打开**节点驱动程序**选项卡。
. 找到**Google GCE**驱动程序并选择**⋮ > 激活**。

[#_create_a_cloud_credential]
== 创建云凭据

. 单击 **☰ > 集群管理**。
. 点击**云凭据**。
. 点击**创建**。
. 点击**Google**。
. 输入您的 GCP 服务帐户 JSON 密钥文件。
. 点击**创建**。

**结果：**您已创建将用于在集群中配置节点的云凭据。您可以在其他集群中重用这些凭据。根据授予服务账户的权限，此凭据也可以用于GKE集群。

[#_create_a_cluster_using_the_cloud_credential]
== 使用云凭据创建集群

. 单击 **☰ > 集群管理**。
. 在**集群**页面，点击**创建**。
. 点击**Google GCE**。
. 选择一个**云凭据**并提供GCP项目以创建虚拟机。
. 输入**集群名称**。
. 为每个Kubernetes角色创建一个机器池。请参考[最佳实践](use-new-nodes-in-an-infra-provider.md#node-roles)以获取角色分配和数量的建议。
.. 为每个机器池定义机器配置。请参考{xref-infra-gce-machine-config}[Google GCE机器配置参考]以获取有关配置选项的信息。
. 使用**集群配置**选择要安装的Kubernetes版本、使用的网络提供程序以及是否要启用项目网络隔离。有关配置集群的帮助，请参考{xref-rke2-config}[RKE2]和{xref-k3s-config}[K3s]集群配置参考。
. 使用**成员角色**配置集群的用户授权。点击**添加成员**以添加可以访问集群的用户。使用**角色**下拉菜单为每个用户设置权限。
. 点击**创建**。

**结果：**

您的集群已创建，状态为 **预配**。Rancher 正在启动您的集群。

在集群状态更新为**活动**后，您可以访问您的集群。

**活动**集群被分配两个项目：

* `Default`，包含`default`名称空间
* `System`，包含 `cattle-system`、`traefik`、`kube-public` 和 `kube-system` 名称空间

[#_gce_best_practices]
== GCE 最佳实践

[#_external_firewall_rules_open_ports_and_ace]
=== 外部防火墙规则、开放端口和ACE

如果正在配置的集群将使用{xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[授权集群端点（ACE）功能]，控制平面节点必须暴露端口`6443`。此端口在默认机器池配置中未暴露，以防止其在所有集群节点中暴露，并减少Rancher创建的防火墙规则数量。

为了使 ACE 按预期工作，您必须在 Rancher UI 中配置控制平面机器池时，在机器池配置 UI 的 `Show Advanced` 部分下启用 `Expose external ports` 复选框，从而指定此端口。或者，您可以在GCP中手动创建自定义防火墙规则，并在控制平面机器池配置中提供相关的网络标签。

[#_internal_firewall_rules]
=== 内部防火墙规则

Rancher 将自动创建防火墙规则和网络标签，以促进在指定 VPC 网络内各集群节点之间的内部通信。此规则将包含创建 RKE2/K3s 集群所需的最少端口数量。

如果您需要扩展集群节点之间内部暴露的端口数量，则应手动创建新的防火墙规则，并将相关的网络标签分配给相关的机器池。如果需要，可以在创建或更新集群时为每个给定的机器池禁用内部防火墙规则的自动创建。

[#_cross_network_deployments]
=== 跨网络部署

虽然可以将不同的机器池部署到不同的 VPC 网络中，但 Rancher 创建的内部防火墙规则默认不支持此配置。要在不同网络中创建机器池，必须手动创建额外的防火墙规则，以促进不同网络中节点之间的通信。

[#_optional_next_steps]
== 可选的后续步骤

创建集群后，您可以通过Rancher UI访问它。作为最佳实践，我们建议设置这些访问集群的替代方式：

* **使用kubectl CLI访问您的集群：**按照{xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[这些步骤]在您的工作站上使用kubectl访问集群。在这种情况下，您将通过 Rancher 服务器的身份验证代理进行身份验证，然后 Rancher 将连接您到下游集群。此方法允许您在没有Rancher UI的情况下管理集群。
* **使用授权的集群端点，通过kubectl CLI访问您的集群：**按照{xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[这些步骤]直接使用kubectl访问您的集群，而无需通过Rancher进行身份验证。我们建议设置这种替代方法来访问您的集群，以便在无法连接到Rancher的情况下，您仍然可以访问集群。
