= Einrichten des Bootstrap-Passworts
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/bootstrap-password.adoc 
:product-path: installation-and-upgrade/resources/bootstrap-password.adoc
ifeval::["{build-type}" != "community"]
:xref-install-rancher: xref:installation-and-upgrade/install-rancher.adoc
:xref-users-and-groups: xref:rancher-admin/users/authn-and-authz/manage-users-and-groups.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-rancher: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/index.adoc
:xref-users-and-groups: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/manage-users-and-groups.adoc
endif::[]

Wenn Sie Rancher installieren, können Sie ein Bootstrap-Passwort für das erste Administratorkonto festlegen.

Wenn Sie sich entscheiden, kein Bootstrap-Passwort festzulegen, generiert Rancher ein zufälliges Bootstrap-Passwort für das erste Administratorkonto.

Für Details zur Festlegung des Bootstrap-Passworts siehe unten.

[#_password_requirements]
== Passwortanforderungen

Das Bootstrap-Passwort kann beliebig lang sein.

Wenn Sie das Passwort des ersten Administratorkontos nach der ersten Anmeldung zurücksetzen, muss das neue Passwort mindestens 12 Zeichen lang sein.

Sie können {xref-users-and-groups}#_minimum_password_length[die minimale Passwortlänge] für Benutzerkonten anpassen, innerhalb der Einschränkungen.

Die minimale Passwortlänge kann jeden positiven ganzzahligen Wert zwischen 2 und 256 annehmen. Dezimalwerte und führende Nullen sind nicht erlaubt.

[#_specifying_the_bootstrap_password]
== Festlegen des Bootstrap-Passworts

Während der {xref-install-rancher}[Rancher-Installation] setzen Sie `bootstrapPassword` zusammen mit anderen Flags für das Rancher Helm-Chart. Beispiel:

[,bash]
----
helm install rancher rancher-<chart-repo>/rancher \
  --set bootstrapPassword=<password>
----

## Abrufen des Bootstrap-Passworts

Das Bootstrap-Passwort wird in den Docker-Container-Protokollen gespeichert. Nachdem Rancher installiert ist, zeigt die Benutzeroberfläche Anweisungen zum Abrufen des Passworts basierend auf Ihrer Installationsmethode. 

[,bash]
----
kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{ .data.bootstrapPassword|base64decode}}{{ "\n" }}'
----
