= Über benutzerdefinierte CA-Stammzertifikate
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/resources/custom-ca-root-certificates.adoc 
:product-path: installation-and-upgrade/resources/custom-ca-root-certificates.adoc
ifeval::["{build-type}" != "community"]
:xref-helm-chart-options: xref:installation-and-upgrade/references/helm-chart-options.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-helm-chart-options: xref:getting-started/installation-and-upgrade/installation-references/helm-chart-options.adoc
endif::[]

Wenn Sie Rancher in einer internen Produktionsumgebung verwenden, in der Sie Apps nicht öffentlich zugänglich machen, verwenden Sie ein Zertifikat von einer privaten Zertifizierungsstelle (CA).

Dienste, auf die Rancher zugreifen muss, sind manchmal mit einem Zertifikat konfiguriert, das von einem benutzerdefinierten/internen CA-Stammzertifikat stammt, auch bekannt als selbstsigniertes Zertifikat. Wenn das präsentierte Zertifikat vom Dienst von Rancher nicht validiert werden kann, wird der folgende Fehler angezeigt: `x509: certificate signed by unknown authority`.

Um das Zertifikat zu validieren, müssen die CA-Stammzertifikate zu Rancher hinzugefügt werden. Da Rancher in Go geschrieben ist, können wir die Umgebungsvariable `SSL_CERT_DIR` verwenden, um auf das Verzeichnis zu verweisen, in dem sich die CA-Stammzertifikate im Container befinden. Das Verzeichnis der CA-Stammzertifikate kann beim Starten des Rancher-Containers mit der Docker-Volume-Option (`-v host-source-directory:container-destination-directory`) eingebunden werden.

Beispiele für Dienste, auf die Rancher zugreifen kann:

* Kataloge
* Authentifizierungsanbieter
* Zugriff auf Hosting-/Cloud-API bei Verwendung von Node-Treibern

[#_installing_with_the_custom_ca_certificate]
== Installation mit dem benutzerdefinierten CA-Zertifikat

Für Details zum Starten eines Rancher-Containers mit Ihren privaten CA-Zertifikaten, die eingebunden sind, siehe die Installationsdokumentation:

* {xref-helm-chart-options}#_additional_trusted_cas[Kubernetes install options for Additional Trusted CAs]
