= Asignaciones de CPU y Memoria
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/cpu-and-memory-allocations.adoc 
:product-path: observability/istio/cpu-and-memory-allocations.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-config: xref:observabilidad/istio/configuración/configuración.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] ha quedado obsoleto desde Rancher v2.12.0; recurran a la https://apps.rancher.io[SUSE Application Collection] de Istio para una mayor seguridad (incluida en las suscripciones de SUSE Rancher Prime).
Se puede encontrar información detallada en https://forums.suse.com/t/deprecation-of-rancher-istio/45043[este anuncio].
====

Esta sección describe los recursos informáticos mínimos recomendados para los componentes de Istio en un clúster.

Las asignaciones de CPU y memoria para cada componente son <<_configuring_resource_allocations,configurables.>>

Antes de habilitar Istio, te recomendamos que confirmes que tus nodos de trabajo de Rancher tienen suficiente CPU y memoria para ejecutar todos los componentes de Istio.

[TIP]
====

En implementaciones más grandes, se aconseja encarecidamente que la infraestructura se coloque en nodos dedicados en el clúster añadiendo un selector de nodos para cada componente de Istio.
====


La tabla a continuación muestra un resumen de las solicitudes y límites de recursos mínimos recomendados para la CPU y la memoria de cada componente central de Istio.

En Kubernetes, la solicitud de recursos indica que la carga de trabajo no se desplegará en un nodo a menos que el nodo tenga al menos la cantidad especificada de memoria y CPU disponibles. Si la carga de trabajo supera el límite de CPU o memoria, puede ser terminada o desalojada del nodo. Para más información sobre la gestión de límites de recursos para contenedores, consulta la https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/[documentación de Kubernetes.]

|===
| Workload   | CPU - Solicitud | Memoria - Solicitud | CPU - Limit | Memoria - Límite

| puerta de enlace de ingreso
| 100m
| 128Mi
| 2000m
| 1024Mi

| puerta de enlace de egreso
| 100m
| 128Mi
| 2000m
| 1024Mi

| istiod
| 500m
| 2048Mi
| Sin límite
| Sin límite

| proxy
| 10m
| 10mi
| 2000m
| 1024Mi

| *Totales:*
| *710m*
| *2314Mi*
| *6000m*
| *3072Mi*
|===

[#_configuring_resource_allocations]
== Configurando las Asignaciones de Recursos

Puedes configurar individualmente la asignación de recursos para cada tipo de componente de Istio. Esta sección incluye las asignaciones de recursos predeterminadas para cada componente.

Para facilitar la programación de las cargas de trabajo en un nodo, un administrador de clúster puede reducir las solicitudes de recursos de CPU y memoria para el componente. Sin embargo, las asignaciones predeterminadas de CPU y memoria son el mínimo que recomendamos.

Puedes encontrar más información sobre la configuración de Istio en la https://istio.io/[documentación oficial de Istio].

Para configurar los recursos asignados a un componente de Istio,

. Haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster que creaste y haz clic en *Explorar*.
. En la barra de navegación izquierda, haz clic en *Apps*.
. Haz clic en *Installed Apps*.
. Ve al espacio de nombres `istio-system`. En una de las cargas de trabajo de Istio, como `rancher-istio`, haz clic en *⋮ > Editar/Actualizar versión*.
. Haz clic en *Actualizar versión* para editar los componentes base a través de cambios en el values.yaml o añadir un {xref-istio-config}#_overlay_file[archivo de superposición]. Para más información sobre cómo editar el archivo de superposición, consulta <<_editing_the_overlay_file,esta sección.>>
. Cambia las asignaciones de CPU o memoria, los nodos donde se programará cada componente, o las tolerancias de nodo.
. Haz clic en *Actualizar versión* para implementar los cambios.

*Resultado:* Las asignaciones de recursos para los componentes de Istio se han actualizado.

[#_editing_the_overlay_file]
=== Editando el Archivo de Superposición

El archivo de superposición puede contener cualquiera de los valores en el https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec[especificación del Operador de Istio.] El archivo de superposición incluido con la aplicación de Istio es solo un ejemplo de una posible configuración del archivo de superposición.

Siempre que el archivo contenga `kind: IstioOperator` y las opciones YAML sean válidas, el archivo puede utilizarse como overlay.

En el archivo overlay de ejemplo proporcionado con la aplicación Istio, la siguiente sección permite cambiar los recursos de Kubernetes:

----
#      k8s:
#        resources:
#          requests:
#            cpu: 200m
----
