= Outils de cluster pour la journalisation, la surveillance et la visibilité
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/rancher-cluster-tools.adoc 
:product-path: observability/rancher-cluster-tools.adoc
ifeval::["{build-type}" != "community"]
:xref-istio: xref:observability/istio/istio.adoc
:xref-monitoring-and-dashboards: xref:observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:xref-logging: xref:observability/logging/logging.adoc
:xref-compliance-scans-howto: xref:security/compliance-scans/how-to.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio: xref:integrations-in-rancher/istio/index.adoc
:xref-monitoring-and-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/index.adoc
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
:xref-compliance-scans-howto: xref:how-to-guides/advanced-user-guides/compliance-scan-guides/index.adoc
endif::[]

Rancher contient une variété d'outils qui ne sont pas inclus dans Kubernetes pour aider dans vos opérations DevOps. Rancher peut s'intégrer à des services externes pour aider vos clusters à fonctionner plus efficacement. Les outils sont divisés en plusieurs catégories{nbsp}:

[#_logging]
== Consignation

La journalisation est utile car elle vous permet de{nbsp}:

* Capturer et analyser l'état de votre cluster
* Rechercher des tendances dans votre environnement
* Sauvegarder vos journaux dans un emplacement sûr en dehors de votre cluster
* Rester informé des événements tels qu'un conteneur qui plante, une éviction de pod ou une défaillance de nœud
* Déboguer et résoudre plus facilement les problèmes

Rancher peut s'intégrer à Elasticsearch, Splunk, Kafka, Syslog et Fluentd.

Pour plus d'informations, reportez-vous à la documentation de journalisation {xref-logging}[ici.]

[#_monitoring_and_alerts]
== Surveillance et alertes

En utilisant Rancher, vous pouvez surveiller l'état et les processus de vos nœuds de cluster, des composants Kubernetes et des déploiements logiciels grâce à l'intégration avec https://prometheus.io/[Prometheus], une solution de surveillance Open Source de premier plan.

Après l'activation de la surveillance, vous pouvez configurer des alertes et des notificateurs qui fournissent le mécanisme pour les recevoir.

Les notificateurs sont des services qui vous informent des événements d'alerte. Vous pouvez configurer des notificateurs pour envoyer des notifications d'alerte au personnel le mieux placé pour prendre des mesures correctives. Les notifications peuvent être envoyées par Slack, email, PagerDuty, WeChat et webhooks.

Les alertes sont des règles qui déclenchent ces notifications. Avant de pouvoir recevoir des alertes, vous devez configurer un ou plusieurs notificateurs dans Rancher. Le champ d'application des alertes peut être défini au niveau du cluster ou du projet.

Pour plus d'informations, reportez-vous à la documentation de surveillance {xref-monitoring-and-dashboards}[ici.]

[#_istio]
== Istio

https://istio.io/[Istio] est un outil Open Source qui facilite aux équipes DevOps l'observation, le contrôle, le dépannage et la sécurisation du trafic au sein d'un réseau complexe de microservices.

L'intégration de Rancher avec Istio a été améliorée dans Rancher v2.5.

Pour plus d'informations, reportez-vous à la documentation d'Istio {xref-istio}[ici.]

[#_compliance_scans]
== Analyses de conformité

Rancher peut exécuter une analyse de sécurité pour vérifier si Kubernetes est déployé conformément aux meilleures pratiques de sécurité définies dans la plupart des normes de sécurité Kubernetes reconnues, telles que STIG.

Pour plus d'informations, reportez-vous à la documentation de l'analyse de conformité {xref-compliance-scans-howto}[ici.]
