= Définir les limites de ressources par défaut des conteneurs
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guides-de-procédure/guides-utilisateur-avancés/gestion-des-projets/gestion-des-quotas-de-ressources/définir-les-limites-de-ressources-par-défaut-des-conteneurs.adoc 
:product-path: cluster-admin/project-admin/project-resource-quotas/set-container-default-resource-limits.adoc
:experimental:

Lors de la définition des quotas de ressources, si vous définissez quoi que ce soit lié au CPU ou à la mémoire (c'est-à-dire des limites ou des réservations) sur un projet / un espace de noms, tous les conteneurs devront avoir un champ CPU ou mémoire respectif défini lors de leur création. Voir la https://kubernetes.io/docs/concepts/policy/resource-quotas/#requests-vs-limits[documentation Kubernetes] pour plus de détails sur les raisons pour lesquelles cela est nécessaire.

Pour éviter de définir ces limites sur chaque conteneur lors de la création de la charge de travail, une limite de ressources par défaut pour les conteneurs peut être spécifiée au niveau de l'espace de noms.

[#_editing_the_container_default_resource_limit]
== Modifier la limite de ressources par défaut des conteneurs

Modifier la limite de ressources par défaut des conteneurs lorsque{nbsp}:

* Vous avez un quota de ressources CPU ou mémoire défini sur un projet et souhaitez fournir les valeurs par défaut correspondantes pour un conteneur.
* Vous souhaitez modifier la limite de ressources par défaut des conteneurs.

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion du cluster*.
. Sur la page *Clusters*, allez au cluster où vous souhaitez modifier la limite de ressources par défaut et cliquez sur *Explorer*.
. Cliquez sur menu:Cluster[Projets/Espaces de noms].
. Trouvez le projet dont vous souhaitez modifier la limite de ressources par défaut des conteneurs. À partir de ce projet, sélectionnez *⋮ > Modifier la configuration*.
. Développez *Limite de ressources par défaut des conteneurs* et modifiez les valeurs.

[#_resource_limit_propagation]
== Propagation de la limite de ressources

Lorsque la limite de ressources par défaut des conteneurs est définie au niveau d'un projet, le paramètre sera propagé à tout espace de noms créé dans le projet après que la limite a été définie. Pour tout espace de noms existant dans un projet, cette limite ne sera pas automatiquement propagée. Vous devrez définir manuellement la limite de ressources par défaut des conteneurs pour tout espace de noms existant dans le projet afin qu'elle soit utilisée lors de la création de conteneurs.

Vous pouvez définir la limite de ressources par défaut des conteneurs sur un projet et lancer toutes les applications du catalogue.

Une fois la limite de ressources par défaut des conteneurs configurée sur un espace de noms, la valeur par défaut sera pré-remplie pour tous les conteneurs créés dans cet espace de noms. Ces limites/réservations peuvent toujours être remplacées lors de la création de la charge de travail.

[#_container_resource_quota_types]
== Types de quotas de ressources des conteneurs

Les limites de ressources suivantes peuvent être configurées{nbsp}:

|===
| Type de ressource | Description

| Limite de CPU
| La quantité maximale de CPU (en https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu[millicores]) allouée au conteneur.

| Réservation de CPU
| La quantité minimale de CPU (en millicores) garantie au conteneur.

| Limite de mémoire
| La quantité maximale de mémoire (en octets) allouée au conteneur.

| Réservation de mémoire
| La quantité minimale de mémoire (en octets) garantie au conteneur.

| Limite/Réservation de GPU NVIDIA
| Le nombre de GPU alloués au conteneur. La limite et la réservation sont toujours les mêmes pour les GPU.
|===
