= 監視設定ガイド
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/index.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
:xref-configure-alertmanager: xref:observability/monitoring-and-dashboards/configuration/advanced/alertmanager.adoc
:xref-prometheus: xref:observability/monitoring-and-dashboards/configuration/advanced/prometheus.adoc
:xref-servicemonitors-and-podmonitors: xref:observability/monitoring-and-dashboards/configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:observability/monitoring-and-dashboards/configuration/routes.adoc
:xref-helm-chart-options: xref:observability/monitoring-and-dashboards/configuration/helm-chart-options.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
:xref-configure-alertmanager: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/alertmanager.adoc
:xref-prometheus: xref:how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/advanced-configuration/prometheus.adoc
:xref-servicemonitors-and-podmonitors: xref:reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors.adoc
:xref-monitoring-routes: xref:reference-guides/monitoring-v2-configuration/routes.adoc
:xref-helm-chart-options: xref:reference-guides/monitoring-v2-configuration/helm-chart-options.adoc
endif::[]

このページでは、Rancher UIでMonitoring V2を構成するための最も重要なオプションのいくつかをまとめています。

Prometheusのカスタムスクレイプターゲットとルールの設定に関する情報については、 https://github.com/prometheus-operator/prometheus-operator[Prometheus Operator.]のアップストリームドキュメントを参照してください。最も重要なカスタムリソースのいくつかは、Prometheus Operatorの https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/getting-started/design.md[設計ドキュメント.]で説明されています。Prometheus Operatorのドキュメントは、RBAC、Thanos、またはカスタム設定のセットアップにも役立ちます。

[#_setting_resource_limits_and_requests]
== リソース制限とリクエストの設定

監視アプリケーションのリソースリクエストと制限は、`rancher-monitoring`をインストールする際に構成できます。デフォルトの制限に関する詳細については、{xref-helm-chart-options}#_configuring_resource_limits_and_requests[このページ]を参照してください。

[TIP]
====

アイドルクラスターでは、Monitoringが高いCPU使用率を示すことがあります。パフォーマンスを向上させるために、Prometheusアダプターをオフにしてください。
====


[#_prometheus_configuration]
== Prometheus構成

通常、Prometheusのカスタムリソースを直接編集する必要はありません。

代わりに、Prometheusがカスタムメトリクスをスクレイプするように構成するには、新しいServiceMonitorまたはPodMonitorを作成するだけで、Prometheusが追加のメトリクスをスクレイプするように構成できます。

[#_servicemonitor_and_podmonitor_configuration]
=== ServiceMonitorおよびPodMonitorの設定

詳細については、{xref-servicemonitors-and-podmonitors}[このページ]を参照してください。

[#_advanced_prometheus_configuration]
=== 高度なPrometheus構成

高度な使用ケースで役立つ可能性のあるPrometheusのカスタムリソースを直接編集することに関する詳細については、{xref-prometheus}[このページ]を参照してください。

[#_alertmanager_configuration]
== Alertmanager構成

Alertmanagerのカスタムリソースは通常、直接編集する必要はありません。最も一般的な使用ケースでは、ルートと受信者を更新することでアラートを管理できます。

ルートと受信者は、Alertmanagerカスタムリソースの構成の一部です。Rancher UIでは、ルートと受信者は真のカスタムリソースではなく、Prometheus OperatorがAlertmanagerカスタムリソースとの構成を同期させるために使用する擬似カスタムリソースです。ルートと受信者が更新されると、監視アプリケーションは自動的にAlertmanagerを更新してその変更を反映します。

一部の高度な使用例では、Alertmanagerを直接構成することを検討するかもしれません。詳細については、{xref-configure-alertmanager}[このページ]を参照してください。

[#_receivers]
=== 受信者

受信者は通知を設定するために使用されます。受信者を構成する方法の詳細については、{xref-receivers}[このページ]を参照してください。

[#_routes]
=== ルート

ルートは、通知が受信者に到達する前にフィルタリングします。各ルートは、すでに構成されている受信者を参照する必要があります。ルートを構成する方法の詳細については、{xref-monitoring-routes}[このページ]を参照してください。

[#_advanced]
=== 詳細

Alertmanagerのカスタムリソースを直接編集する方法（高度な使用例で役立つ場合があります）についての詳細は、{xref-configure-alertmanager}[このページ]を参照してください。
