= ルート構成
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/monitoring-v2-configuration/routes.adoc 
:product-path: observability/monitoring-and-dashboards/configuration/routes.adoc
ifeval::["{build-type}" != "community"]
:xref-how-monitoring-works: xref:observability/monitoring-and-dashboards/how-monitoring-works.adoc
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-how-monitoring-works: xref:integrations-in-rancher/monitoring-and-alerting/how-monitoring-works.adoc
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
endif::[]

ルート構成は、Prometheusによって発火されたアラートが受信者に到達する前に、どのようにグループ化され、フィルタリングされるかを制御するAlertmanagerカスタムリソースのセクションです。

ルートが変更されると、Prometheusオペレーターは変更を反映するためにAlertmanagerカスタムリソースを再生成します。

ルートの構成に関する詳細については、 https://www.prometheus.io/docs/alerting/latest/configuration/#route[公式のAlertmanagerドキュメントを参照してください。]

[NOTE]
====

このセクションは、監視コンポーネントがどのように連携して動作するかに精通していることを前提としています。詳細については、{xref-how-monitoring-works}[このセクションを参照してください。]
====


[#_route_restrictions]
== ルート制限

Alertmanagerは、受信者とラベルに基づいてアラートを特定の受信者にフィルタリングするルーティングツリーに基づいて、Prometheusのアラートをプロキシします。

アラートドライバーは、Microsoft TeamsやSMSなどの非ネイティブ受信者に対してAlertmanagerのアラートをプロキシします。

ルートと受信者を構成するためのRancher UIでは、1つのルートを持つルーティングツリーを構成し、さらに1つのレベルの深さを持つツリーを構成できます。ただし、Alertmanagerを直接構成する際に`continue`ルートを使用すると、ツリーをより深くすることができます。

各受信者は1つ以上の通知プロバイダー用です。したがって、すべてのSlackアラートがPagerDutyにも送信されるべきであることがわかっている場合、同じ受信者で両方を構成できます。

[#_route_configuration]
== ルート構成

[#_note_on_labels_and_annotations]
=== ラベルと注釈に関する注意

ラベルは、通知のルーティングに影響を与える可能性のある識別情報に使用する必要があります。アラートに関する識別情報は、コンテナ名や通知されるべきチームの名前で構成される可能性があります。

注釈は、ランブックのURLやエラーメッセージなど、アラートを受信する人に影響を与えない情報に使用する必要があります。

[#_receiver]
=== Receiver

ルートは、すでに構成されている{xref-receivers}[受信者]を参照する必要があります。

[#_grouping]
=== [Grouping]

|===
| フィールド | デフォルト | 説明

| グループ分け
| N/a
| グループ化するためのラベルのリスト。ラベルは一意でなければなりません。特別なラベル「...」（すべての可能なラベルで集約する場合）、提供されている場合は、リスト内の唯一の要素でなければなりません。文字列のリストを受け入れます。詳細については、 https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#route[アップストリームのドキュメント]を参照してください。

| グループ待機
| 30秒
| 最初に送信する前に、同じグループのアラートをバッファリングするために待機する時間。

| グループ間隔
| 5m
| 最初の通知がすでに送信されたアラートのグループに追加されたアラートを送信する前に待機する時間。

| 繰り返し間隔
| 4時間
| すでに送信された特定のアラートを再送信する前に待機する時間。
|===

[#_matching]
=== 一致

*マッチ*フィールドは、そのアラートで定義されたラベルに基づいて、どのアラートを特定のルートに送信するかを識別するために使用される一連の等価マッチャーを指します。Rancher UIにキーと値のペアを追加すると、それはこの形式のYAMLに対応します。

[,yaml]
----
match:
  [ <labelname>: <labelvalue>, ... ]
----

*マッチ正規表現*フィールドは、そのアラートで定義されたラベルに基づいて、どのアラートを特定のルートに送信するかを識別するために使用される一連の正規表現マッチャーを指します。Rancher UIにキーと値のペアを追加すると、それはこの形式のYAMLに対応します。

[,yaml]
----
match_re:
  [ <labelname>: <regex>, ... ]
----
