= Kubernetesにおけるノードの役割
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/運用準備完了クラスタのチェックリスト/roles-for-nodes-in-kubernetes.adoc 
:product-path: cluster-deployment/production-checklist/roles-for-nodes-in-kubernetes.adoc
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
endif::[]

このセクションでは、Kubernetesにおけるetcdノード、コントロールプレーンノード、ワーカーノードの役割と、それらの役割がクラスター内でどのように連携するかについて説明します。

この図は、{xref-launch-k8s-with-rancher}でRKEを使用してRancherで起動されたKubernetesクラスターに適用されます。

.ラインはコンポーネント間のトラフィックフローを示しています。色は視覚的な補助のためにのみ使用されます。
image::clusterdiagram.svg[クラスターダイアグラム]

[#_etcd]
== etcd

`etcd`の役割を持つノードはetcdを実行します。etcdは、Kubernetes`'のすべてのクラスターデータのバックストアとして使用される、一貫性があり高可用性のキー・バリュー・ストアです。etcdはデータを各ノードに複製します。

[NOTE]
====

`etcd`の役割を持つノードはUIで`Unschedulable`として表示され、デフォルトではこれらのノードにポッドはスケジュールされません。
====


[#_controlplane]
== コントロールプレーン

`controlplane`の役割を持つノードはKubernetesのマスターコンポーネントを実行します（`etcd`は別の役割のため除外されます）。コンポーネントの詳細なリストについては、 https://kubernetes.io/docs/concepts/overview/components/#master-components[Kubernetes: マスターコンポーネント]を参照してください。

[NOTE]
====

`controlplane`の役割を持つノードはUIで`Unschedulable`として表示され、デフォルトではこれらのノードにポッドはスケジュールされません。
====


[#_kube_apiserver]
=== kube-apiserver

Kubernetes APIサーバー（`kube-apiserver`）は水平スケーリングします。`controlplane`の役割を持つ各ノードは、Kubernetes APIサーバーにアクセスする必要があるコンポーネントを持つノードのNGINXプロキシに追加されます。これは、ノードが到達不能になると、そのノードのローカルNGINXプロキシがリスト内の別のKubernetes APIサーバーにリクエストを転送することを意味します。

[#_kube_controller_manager]
=== kube-controller-manager

Kubernetesコントローラーマネージャーは、Kubernetes内のエンドポイントを使用してリーダー選挙を行います。`kube-controller-manager`のインスタンスはKubernetesエンドポイントにエントリを作成し、設定された間隔でそのエントリを更新します。他のインスタンスはアクティブなリーダーを確認し、そのエントリが期限切れになるのを待ちます（例えば、ノードが応答しない場合）。

[#_kube_scheduler]
=== kube-scheduler

Kubernetesスケジューラーは、Kubernetes内のエンドポイントを使用してリーダー選挙を行います。`kube-scheduler`のインスタンスはKubernetesエンドポイントにエントリを作成し、設定された間隔でそのエントリを更新します。他のインスタンスはアクティブなリーダーを確認し、そのエントリが期限切れになるのを待ちます（例えば、ノードが応答しない場合）。

[#_worker]
== ワーカー

`worker`の役割を持つノードはKubernetesノードコンポーネントを実行します。コンポーネントの詳細なリストについては、 https://kubernetes.io/docs/concepts/overview/components/#node-components[Kubernetes: ノードコンポーネント]を参照してください。

[#_references]
== 参考資料

* https://kubernetes.io/docs/concepts/overview/components/#node-components[Kubernetes: ノードコンポーネント]
