= コンテナの設定に関するヒント
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-managed-clusters/tips-to-set-up-containers.adoc 
:product-path: cluster-deployment/production-checklist/tips-to-set-up-containers.adoc

適切に構築されたコンテナを実行することは、環境全体のパフォーマンスとセキュリティに大きな影響を与える可能性があります。

以下は、コンテナを設定するためのいくつかのヒントです。

コンテナのセキュリティに関する詳細な議論については、Rancher's https://rancher.com/complete-guide-container-security[コンテナセキュリティガイド]を参照してください。

[#_use_a_common_container_os]
== 一般的なコンテナOSを使用する

可能な限り、一般的なコンテナベースのOSに標準化することをお勧めします。

AlpineやBusyBoxのような小規模なディストリビューションは、コンテナイメージのサイズを削減し、一般的に攻撃面および脆弱性のリスクが低減されます。

Ubuntu、Fedora、CentOSのような人気のあるディストリビューションは、より多くのフィールドテストを受けており、より多くの機能を提供します。

[#_start_with_a_from_scratch_container]
== FROM scratchコンテナから始める

マイクロサービスがスタンドアロンの静的バイナリである場合は、FROM scratchコンテナを使用するべきです。

FROM scratchコンテナは、最小限のイメージを設計するために使用できる空の https://hub.docker.com/_/scratch[公式Dockerイメージ]です。

これにより、最小の攻撃面と最小のイメージサイズが得られます。

[#_run_container_processes_as_unprivileged]
== コンテナプロセスを特権のないユーザーとして実行する

可能な限り、コンテナ内でプロセスを実行する際には、特権のないユーザーを使用してください。コンテナランタイムは隔離を提供しますが、脆弱性や攻撃は依然として可能です。コンテナがルートとして実行されている場合、意図しないホストマウントにも影響を与える可能性があります。ポッドまたはコンテナのセキュリティコンテキストを構成する詳細については、 https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[Kubernetesドキュメント]を参照してください。

[#_define_resource_limits]
== リソース制限を定義する

ポッドにCPUとメモリの制限を適用してください。これにより、ワーカーノードのリソースを管理し、故障したマイクロサービスが他のマイクロサービスに影響を与えるのを防ぐことができます。

標準のKubernetesでは、ネームスペースレベルでリソース制限を設定できます。Rancherでは、プロジェクトレベルでリソース制限を設定でき、それがプロジェクト内のすべてのネームスペースに伝播します。詳細については、Rancherのドキュメントを参照してください。

リソースクォータを設定する際に、プロジェクトまたはネームスペースにCPUまたはメモリ（すなわち制限または予約）に関連するものを設定すると、すべてのコンテナは作成時にそれぞれのCPUまたはメモリフィールドを設定する必要があります。ワークロード作成時にこれらの制限をすべてのコンテナに設定しないようにするために、ネームスペースにデフォルトのコンテナリソース制限を指定できます。

Kubernetesのドキュメントには、リソース制限を https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container[コンテナレベル]およびネームスペースレベルで設定する方法に関する詳細が記載されています。

[#_define_resource_requirements]
== リソース要件を定義する

ポッドにCPUおよびメモリの要件を適用する必要があります。これは、スケジューラにポッドが配置されるべきコンピュートノードの種類を通知し、そのノードが過剰にプロビジョニングされないようにするために重要です。Kubernetesでは、ポッドのコンテナ仕様のリソースリクエストフィールドで`resources.requests`を定義することにより、リソース要件を設定できます。詳細については、 https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container[Kubernetesのドキュメント]を参照してください。

[NOTE]
====

ポッドがデプロイされているネームスペースにリソース制限を設定し、コンテナに特定のリソースリクエストがない場合、ポッドは起動できません。ワークロード作成時にこれらのフィールドをすべてのコンテナに設定しないようにするために、ネームスペースにデフォルトのコンテナリソース制限を指定できます。
====


リソース要件はコンテナレベルで定義することをお勧めします。そうしないと、スケジューラはクラスタが負荷を受けているときにアプリケーションに役立たない仮定をする可能性があります。

[#_liveness_and_readiness_probes]
== ライブネスおよびレディネスプローブ

コンテナのライブネスおよびレディネスプローブを設定してください。コンテナが完全にクラッシュしない限り、状態を報告するエンドポイントまたは仕組みがなければ、Kubernetesはその不健康状態を検知できません。あるいは、不健康な場合はコンテナが停止してクラッシュすることを確認してください。

Kubernetesのドキュメントには、 https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/[コンテナのライブネスおよびレディネスプローブを設定する方法が示されています。]
