= ノードドライバ
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.adoc 
:product-path: rancher-admin/global-configuration/provisioning-drivers/manage-node-drivers.adoc
ifeval::["{build-type}" != "community"]
:xref-global-permissions: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-global-permissions: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions.adoc 
endif::[]

ノードドライバは、 https://github.com/docker/docs/blob/vnext-engine/machine/drivers/index.md[Docker Machineドライバ]と同じです。ノードドライバは、ホストをプロビジョニングするために使用され、Rancherはこれを使用してKubernetesクラスターを起動および管理します。デフォルトでは、Rancherには多くのノードドライバがパッケージされていますが、カスタムノードドライバを作成してRancherに追加することもできます。

ノードテンプレートを作成する際、Rancher UIには`Active`のノードドライバのみが表示されます。特定のノードドライバをユーザーに表示したくない場合は、これらのノードドライバを無効にする必要があります。

[#_managing_node_drivers]
== ノードドライバの管理

[NOTE]
.前提条件:
====

ドライバを作成、編集、または削除するには、_次のいずれかの_権限が必要です。

* {xref-global-permissions}[管理者グローバル権限]
* {xref-global-permissions}#_custom_global_permissions[カスタムグローバル権限]で、{xref-global-permissions}[ノードドライバの管理]ロールが割り当てられていること。
====


[#_activating_deactivating_node_drivers]
=== ノードドライバの有効化/無効化

デフォルトでは、RancherはAmazon EC2、Azure、DigitalOcean、Linode、vSphereなどの最も人気のあるクラウドプロバイダーのドライバのみを有効にします。任意のノードドライバを表示または非表示にしたい場合は、そのステータスを変更できます。

. 左上隅で、*☰ > クラスター管理*をクリックします。
. 左側のナビゲーションメニューで、*ドライバ*をクリックします。
. *ノードドライバ*タブで、有効化または無効化したいドライバを選択し、*⋮ > 有効化*または*⋮ > 無効化*をクリックします。

[WARNING]
====

ノードドライバを無効化した後、クラスターへのアクセスを失う可能性があります。

ノードドライバを無効にすると、Rancher UIでの表示に影響を与えるだけではありません。ノードドライバを無効にしたり削除したりすると、そのドライバでデプロイされたノードはアクセスできなくなります。

例えば、UIで非表示にするためにvSphereノードドライバを無効にすると、そのドライバでデプロイされたvSphereクラスターの初期ノードが失敗し、クラスター全体がアクセスできなくなります。vSphereノードの削除を試みても失敗し、ノードは長時間`Removing`状態のままになります。

ノードドライバーを無効にする前に、関連するクラスターがないことを確認してください。確認する方法の一つは、ドライバーのプラットフォームがクラスターの中にリストされているかどうかを見ることです：

. 左上隅で、*☰ > クラスター管理*をクリックします。
. *クラスター*を選択します。
. 無効にしているノードドライバーのインスタンスについて、テーブルの*プロバイダー*列を確認してください。
====


[#_adding_custom_node_drivers]
=== カスタムノードドライバーの追加

Rancherが標準でサポートしていないノードドライバーを使用したい場合、そのプロバイダーのドライバーを追加して、ノードテンプレートや最終的にはKubernetesクラスターのノードプールを作成するために使用できます。

. 左上隅で、*☰ > クラスター管理*をクリックします。
. 左側のナビゲーションメニューで、*ドライバ*をクリックします。
. *ノードドライバ*タブで、*ノードドライバの追加*をクリックします。
. *ノードドライバの追加*フォームを完成させます。続いて*作成*をクリックします。

[#_developing_your_own_node_drivers]
=== 独自のノードドライバの開発

ノードドライバは、 https://github.com/rancher/machine[Rancher Machine]を使用して実装されており、これは https://github.com/docker/machine[Docker Machine]のフォークです。Docker Machineは、もはや積極的に開発されていません。

独自のノードドライバを開発する方法の詳細については、元の https://github.com/docker/docs/blob/vnext-engine/machine/overview.md[Docker Machineのドキュメント]を参照してください。
