= Modelos de cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 04-11-2025
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates.adoc 
:product-path: cluster-admin/manage-clusters/cluster-templates.adoc
:experimental:

Modelos de cluster abrangem tanto a configuração do Kubernetes quanto a configuração do pool de nós, permitindo que um único modelo contenha todas as informações que o Rancher precisa para provisionar novos nós em um provedor de nuvem e instalar o Kubernetes nesses nós.

[#_overview]
== Visão Geral

Os modelos de cluster são fornecidos como gráficos Helm. Para usá-los, você precisará clonar e bifurcar os modelos, alterá-los de acordo com seu caso de uso e, em seguida, instalar os gráficos Helm no cluster de gerenciamento do Rancher. Quando o gráfico Helm é instalado no cluster de gerenciamento do Rancher, um novo recurso de cluster é criado, que o Rancher usa para provisionar o novo cluster.

Após o cluster ser provisionado usando o modelo, nenhuma alteração no modelo afetará o cluster. Após o cluster ser criado a partir do modelo de cluster, sua configuração e infraestrutura podem mudar, pois nenhuma restrição é imposta pelos modelos de cluster.

[#_kubernetes_distribution]
=== Kubernetes Distribution

Os modelos de cluster podem usar qualquer distribuição do Kubernetes. Por enquanto, fornecemos um exemplo com um cluster Kubernetes RKE2. Podemos fornecer mais exemplos no futuro usando outras distribuições do Kubernetes.

[#_versioning]
=== Controle de versão

O Rancher não gerencia o controle de versão para modelos de cluster. O controle de versão é gerenciado no repositório que contém o gráfico Helm do modelo.

[#__rke2_product_name_cluster_template]
== {rke2-product-name} Modelo de cluster

Veja o repositório de exemplo para um https://github.com/rancher/cluster-template-examples[modelo de cluster RKE2].

[#_adding_a_cluster_template_to_rancher]
== Adicionando um modelo de cluster ao Rancher

Nesta seção, você aprenderá como adicionar o modelo de cluster à `local` lista de repositórios de gráficos do cluster. O resultado é que o Rancher incluirá o modelo de cluster como uma opção quando os usuários instalarem novos clusters Kubernetes.

[NOTE]
.Pré-requisitos:
====

* Você precisará de permissão para instalar gráficos Helm no `local` cluster Rancher.
* Para tornar o gráfico visível no formulário de criação do cluster, tanto o gráfico quanto o arquivo index.yaml devem ter a anotação, `catalog.cattle.io/type: cluster-template`.
====


. Vá para um repositório de exemplo de modelo de cluster. Os exemplos do Rancher estão em https://github.com/rancher/cluster-template-examples[este repositório do GitHub.]
. Faça um fork do repositório.
. Opcional: Edite as opções do cluster editando o arquivo `values.yaml`. Para ajuda na edição do arquivo, consulte o README do gráfico Helm do modelo de cluster.
. Adicione o repositório ao Rancher. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o `local` cluster e clique em *Explorar.*
. Na barra de navegação à esquerda, clique em menu:Apps[Repositórios de Gráficos.]
. Clique em *Criar.*
. Digite um nome para o repositório do modelo de cluster.
. Clique em *Repositório Git contendo definições de gráficos Helm.*
. No campo *URL do Repositório Git*, insira a URL do repositório. Por exemplo, `https://github.com/rancher/cluster-template-examples.git`.
. No campo *Branch do Git*, insira o branch a ser usado como fonte para o modelo. O repositório de exemplo do Rancher usa `main`.
. Clique em *Criar.*

*Resultado:* O modelo de cluster disponível em *Apps* no `local` cluster do Rancher. Agora pode ser usado para implantar clusters.

[#_creating_a_cluster_from_a_cluster_template]
== Criando um cluster a partir de um modelo de cluster

[NOTE]
.Pré-requisitos:
====

* Você precisará de permissão para provisionar novos clusters Kubernetes.
* Você precisará de credenciais de nuvem para provisionar infraestrutura usando o modelo.
* Para mostrar no formulário de criação de novos clusters, o gráfico Helm do modelo de cluster deve ter a anotação `catalog.cattle.io/type: cluster-template`.
====


. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique em *Criar.*
. Clique no nome do seu modelo de cluster.
. Finalize a instalação do gráfico Helm.

*Resultado:* Depois que o Rancher provisiona o novo cluster, ele é gerenciado da mesma forma que qualquer outro cluster Kubernetes iniciado pelo Rancher. Você pode configurar quaisquer opções através da interface se o modelo de cluster tiver opções para o usuário escolher.

[#_updating_a_cluster_created_from_a_cluster_template]
== Atualizando um cluster criado a partir de um modelo de cluster

Você pode atualizar quaisquer clusters usando um modelo na página menu:Apps[Aplicativos Instalados], desde que haja uma nova versão de um modelo sendo usado por esses clusters.

[#_deploying_clusters_from_a_template_with_fleet_product_name]
== Implantando Clusters a partir de um Modelo com {fleet-product-name}

[NOTE]
.Pré-requisitos:
====

* Você precisará de permissão para provisionar novos clusters Kubernetes.
* Você precisará de credenciais de nuvem para provisionar infraestrutura usando o modelo.
* Para mostrar no formulário de criação de novos clusters, o gráfico Helm do modelo de cluster deve ter a anotação `catalog.cattle.io/type:cluster-template`.
* Para usar um modelo como parte da entrega contínua/GitOps, o modelo de cluster precisa ser implantado no `fleet-local` namespace do `local` cluster.
* Todos os valores devem ser definidos no `values.yaml` do modelo.
* Os repositórios do Fleet devem seguir estas https://documentation.suse.com/cloudnative/continuous-delivery/{fleet-docs-version}/en/explanations/gitrepo-content.html[diretrizes]. Para modelos de cluster RKE2, isso significa que um arquivo `fleet.yaml` deve ser adicionado ao repositório.
====


. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique em *Criar.*
. Clique em *Criar cluster a partir do modelo.*

*Resultado:* Depois que o Rancher provisiona o novo cluster, ele é gerenciado pelo Fleet.

[#_uninstalling_cluster_templates]
== Desinstalando modelos de cluster

. Clique em *☰ > Gerenciamento de Cluster*.
. Vá para o `local` cluster e clique em menu:Apps[Repositórios de gráficos.]
. Vá para o repositório de gráficos do seu modelo de cluster e clique em *⋮ > Excluir.*
. Confirme a exclusão.

*Resultado:* O modelo de cluster foi desinstalado. Esta ação não afeta os clusters criados com o modelo de cluster.

Um administrador com acesso ao `local` cluster também pode remover um cluster implantado via modelos de cluster através da página menu:Apps[Aplicativos Instalados].

[#_configuration_options]
== Opções de configuração

Os modelos de cluster são flexíveis o suficiente para que possam ser usados para configurar todas as seguintes opções:

* Configuração do nó
* Pools de nós
* Credenciais de nuvem pré-especificadas
* Habilitar/configurar um endpoint de cluster autorizado para obter acesso kubectl ao cluster sem usar o Rancher como proxy
* Instalar monitoramento do Rancher V2
* Kubernetes version
* Atribuir membros ao cluster
* Configuração de infraestrutura, como VPC/sub-redes da AWS ou data center vSphere
* Opções de provedores de nuvem
* Opções de segurança de pod
* Provedores de rede
* Controladores de ingress
* Configuração de segurança de rede
* Plugins de rede
* URL e credenciais do registro privado
* Complementos
* Opções do Kubernetes, incluindo configurações para componentes do Kubernetes, como kube-api, kube-controller, kubelet e serviços

Para detalhes sobre como configurar o modelo, consulte o README do gráfico Helm do modelo de cluster.
