= Administração de cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-18
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/index.adoc 
:product-path: cluster-admin/manage-clusters/manage-clusters.adoc
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/usuarios/authn-e-authz/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-cluster-deployment: xref:cluster-deployment/cluster-deployment.adoc
:xref-k8s-concepts: xref:sobre-rancher/conceitos.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:como-fazer-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-cluster-deployment: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
endif::[]

Após provisionar um cluster no Rancher, você pode começar a usar recursos poderosos do Kubernetes para implantar e escalar seus aplicativos conteinerizados em ambientes de desenvolvimento, teste ou produção.

[NOTE]
====

Esta seção assume uma familiaridade básica com Docker e Kubernetes. Para uma breve explicação de como os componentes do Kubernetes trabalham juntos, consulte a página {xref-k8s-concepts}[conceitos].
====


[#_managing_clusters_in_rancher]
== Gerenciando Clusters no Rancher

Após os clusters terem sido {xref-cluster-deployment}[provisionados no Rancher], {xref-cluster-project-roles}#_cluster_roles[proprietários do cluster] precisarão gerenciar esses clusters. Existem muitas opções diferentes para gerenciar seu cluster.

ifeval::["{build-type}" != "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table.adoc[]
endif::[]
ifeval::["{build-type}" == "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table-srfa.adoc[]
endif::[]

[#_configuring_tools]
== Configurando Ferramentas

O Rancher contém uma variedade de ferramentas que não estão incluídas no Kubernetes para auxiliar em suas operações de DevOps. O Rancher pode se integrar a serviços externos para ajudar seus clusters a funcionarem de forma mais eficiente. As ferramentas são divididas nas seguintes categorias:

* Alertas
* Notificadores
* Registro
* Monitoramento
* Istio Service Mesh

As ferramentas podem ser instaladas através de *Apps.*
