= Projetos e namespaces do Kubernetes com {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-01-08
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces.adoc 
:product-path: cluster-admin/manage-clusters/projects-and-namespaces.adoc
:description: Os Projetos do Rancher facilitam a carga administrativa do seu cluster e suportam multi-tenancy. Aprenda a criar projetos e dividir projetos em namespaces do Kubernetes
:experimental:
ifeval::["{build-type}" != "community"]
:xref-cluster-project-roles: xref:rancher-admin/usuarios/authn-e-authz/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-secrets: xref:security/secrets-hub.adoc
:xref-persistent-storage: xref:cluster-admin/manage-clusters/persistent-storage/manage-persistent-storage.adoc
:xref-configmaps: xref:cluster-admin/kubernetes-resources/configmaps.adoc
:xref-workloads-and-pods: xref:cluster-admin/kubernetes-resources/workloads-and-pods/workloads-and-pods.adoc
:xref-project-resource-quotas: xref:cluster-admin/project-admin/project-resource-quotas/project-resource-quotas.adoc
:xref-custom-roles: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/custom-roles.adoc
:xref-http-encrypt: xref:security/encrypting-http.adoc
:xref-namespaces: xref:cluster-admin/namespaces.adoc
:xref-k8s-docker-registries: xref:cluster-admin/kubernetes-resources/kubernetes-and-docker-registries.adoc
:xref-create-services: xref:cluster-admin/kubernetes-resources/create-services.adoc
:xref-lb-and-ingress-controller: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/balanceador-de-carga-e-controlador-de-ingress.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cluster-project-roles: xref:como-fazer-guias/novos-guias-de-usuário/autenticação-permissões-e-configuração-global/gerenciar-controle-de-acesso-com-base-em-função-rbac/funções-de-cluster-e-projeto.adoc
:xref-secrets: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.adoc
:xref-persistent-storage: xref:how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/index.adoc
:xref-configmaps: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/configmaps.adoc
:xref-workloads-and-pods: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/index.adoc
:xref-project-resource-quotas: xref:how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/index.adoc
:xref-custom-roles: xref:como-guia/novos-usuários/guias-de-autenticação-e-permissões/configuração-global/gerenciar-controle-de-acesso-baseado-em-funções-rbac/funções-personalizadas.adoc
:xref-http-encrypt: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc
:xref-namespaces: xref:how-to-guides/new-user-guides/manage-namespaces.adoc
:xref-k8s-docker-registries: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries.adoc
:xref-create-services: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/create-services.adoc
:xref-lb-and-ingress-controller: xref:procedimentos/novos-usuarios/configuração-de-recursos-do-kubernetes/balanceador-de-carga-e-controlador-de-ingress/index.adoc
endif::[]

Um namespace é um conceito do Kubernetes que permite um cluster virtual dentro de um cluster, o que é útil para dividir o cluster em "clusters virtuais" separados, cada um com seu próprio controle de acesso e cotas de recursos.

Um projeto é um grupo de namespaces, e é um conceito introduzido pelo Rancher. Os projetos permitem que você gerencie múltiplos namespaces como um grupo e realize operações do Kubernetes neles. Você pode usar projetos para suportar multi-tenancy, de modo que uma equipe possa acessar um projeto dentro de um cluster sem ter acesso a outros projetos no mesmo cluster.

[NOTE]
====
Os projetos são menos enfatizados na interface do usuário porque não é necessário criar recursos do Kubernetes dentro do escopo de um projeto. No entanto, recursos como {xref-secrets}#_creating_secrets_in_projects[Segredos] ainda podem ser criados no escopo de um projeto.
====


Esta seção descreve como projetos e namespaces funcionam com o Rancher.

[#_about_namespaces]
== Sobre Namespaces

Um namespace é um conceito introduzido pelo Kubernetes. De acordo com a https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/[documentação oficial do Kubernetes sobre namespaces,]

[NOTE]
====

O Kubernetes suporta múltiplos clusters virtuais respaldados pelo mesmo cluster físico. Esses clusters virtuais são chamados de namespaces. [...] Os namespaces são destinados ao uso em ambientes com muitos usuários espalhados por várias equipes ou projetos. Para clusters com poucos a dezenas de usuários, você não deve precisar criar ou pensar em namespaces.
====


Os namespaces fornecem a seguinte funcionalidade:

* *Fornecendo um escopo para nomes:* Os nomes dos recursos precisam ser únicos dentro de um namespace, mas não entre namespaces. Os namespaces não podem ser aninhados um dentro do outro e cada recurso do Kubernetes pode estar em apenas um namespace.
* *Cotas de recursos:* Os namespaces fornecem uma maneira de dividir os recursos do cluster entre vários usuários.

Você pode atribuir recursos no nível do projeto para que cada namespace no projeto possa usá-los. Você também pode contornar essa herança atribuindo recursos explicitamente a um namespace.

Você pode atribuir os seguintes recursos diretamente aos namespaces:

* {xref-workloads-and-pods}[Cargas de trabalho]
* {xref-lb-and-ingress-controller}[Balanceadores de Carga/Ingress]
* {xref-create-services}[Registros de Descoberta de Serviço]
* {xref-persistent-storage}[Solicitações de Volume Persistente]
* {xref-http-encrypt}[Certificados]
* {xref-configmaps}[ConfigMaps]
* {xref-k8s-docker-registries}[Registros]
* {xref-secrets}[Segredos]

Para gerenciar permissões em um cluster Kubernetes padrão, os administradores do cluster configuram políticas de acesso baseadas em função para cada namespace. Com o Rancher, as permissões dos usuários são atribuídas no nível do projeto, e as permissões são automaticamente herdadas por qualquer namespace pertencente ao projeto específico.

Para mais informações sobre como criar e mover namespaces, veja {xref-namespaces}[Namespaces].

[#_role_based_access_control_issues_with_namespaces_and_kubectl]
=== Questões de controle de acesso com base em função com namespaces e kubectl

Como os projetos são um conceito introduzido pelo Rancher, o kubectl não tem a capacidade de restringir a criação de namespaces a um projeto ao qual o criador tem acesso.

Isso significa que, quando usuários padrão com permissões limitadas a projetos criam um namespace com `kubectl`, ele pode ser inutilizável porque `kubectl` não exige que o novo namespace esteja restrito a um determinado projeto.

Se suas permissões estão restritas ao nível do projeto, é melhor {xref-namespaces}[criar um namespace através do Rancher] para garantir que você terá permissão para acessar o namespace.

Se um usuário padrão for proprietário de um projeto, o usuário poderá criar namespaces dentro desse projeto. A interface do Rancher impedirá que esse usuário crie namespaces fora do escopo dos projetos aos quais ele tem acesso.

[#_about_projects]
== Sobre Projetos

Em termos de hierarquia:

* Clusters contêm projetos
* Projetos contêm namespaces

Você pode usar projetos para suportar multi-tenancy, de modo que uma equipe possa acessar um projeto dentro de um cluster sem ter acesso a outros projetos no mesmo cluster.

Na versão base do Kubernetes, recursos como direitos de acesso baseados em função ou recursos de cluster são atribuídos a namespaces individuais. Um projeto permite que você economize tempo ao dar a um indivíduo ou a uma equipe acesso a múltiplos namespaces simultaneamente.

Você pode usar projetos para realizar ações como:

* Atribuir usuários a um grupo de namespaces (ou seja, {xref-cluster-project-roles}[membros do projeto]).
* Atribuir usuários a funções específicas em um projeto. Uma função pode ser proprietário, membro, somente leitura ou {xref-custom-roles}[personalizada].
* Atribuir recursos ao projeto.

Quando você cria um cluster, dois projetos são automaticamente criados dentro dele:

* <<_the_clusters_default_project,Projeto Padrão>>
* <<_the_system_project,Projeto do Sistema>>

[#_the_clusters_default_project]
=== O Projeto Padrão do Cluster

Quando você provisiona um cluster com o Rancher, ele cria automaticamente um `default` projeto para o cluster. Este é um projeto que você pode usar para começar com seu cluster, mas você sempre pode excluí-lo e substituí-lo por projetos que tenham nomes mais descritivos.

Se você não precisa de mais do que o namespace padrão, também não precisa de mais do que o projeto *Projeto Padrão* no Rancher.

Se você precisar de outro nível de organização além do projeto *Projeto Padrão*, pode criar mais projetos no Rancher para isolar namespaces, aplicações e recursos.

[#_the_system_project]
=== O Projeto do Sistema

Ao solucionar problemas, você pode visualizar o projeto `system` para verificar se namespaces importantes no sistema Kubernetes estão funcionando corretamente. Este projeto de fácil acesso evita que você tenha que solucionar problemas de contêineres de namespaces do sistema individualmente.

Para abri-lo, acesse a visualização do cluster e clique em menu:Cluster[Projetos/Namespaces]. Esta visualização mostra todos os namespaces no projeto `system`.

O projeto `system`:

* É criado automaticamente quando você provisiona um cluster.
* Lista todos os namespaces que existem em `v3/settings/system-namespaces`, se existirem.
* Permite que você adicione mais namespaces ou mova seus namespaces para outros projetos.
* Não pode ser excluído porque é necessário para as operações do cluster.

[NOTE]
====

Em clusters RKE2/K3s onde a opção de isolamento de rede do projeto está habilitada, o projeto `system` substitui a opção de isolamento de rede do projeto para que possa se comunicar com outros projetos, coletar logs e verificar a saúde.
====


[#_project_authorization]
== Autorização do Projeto

Usuários padrão estão autorizados apenas para acesso ao projeto em duas situações:

* Um administrador, proprietário do cluster ou membro do cluster adiciona explicitamente o usuário padrão na aba *Membros* do projeto.
* Usuários padrão podem acessar projetos que criam por conta própria.


[#_creating_projects]
== Criando Projetos

Esta seção descreve como criar um novo projeto com um nome e com política de segurança de pod opcional, membros e cotas de recursos.

. <<_name_a_new_project,Nomeie um novo projeto.>>
. <<_recommended_add_project_members,Recomendado: Adicione membros ao projeto.>>
. <<_optional_add_resource_quotas,Opcional: Adicione cotas de recursos.>>

[#_name_a_new_project]
=== Nomeie um Novo Projeto

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster no qual você deseja criar um projeto e clique em *Explorar*.
. Clique em menu:Cluster[Projetos/Namespaces].
. Clique em *Criar Projeto*.
. Digite um *Nome do Projeto*.

[#_recommended_add_project_members]
=== Recomendado: Adicione Membros ao Projeto

Use a seção *Membros* para fornecer acesso e funções de projeto a outros usuários.

Por padrão, seu usuário é adicionado como o `Owner` do projeto.

[NOTE]
.Notas sobre Permissões:
====

* Usuários atribuídos à função `Owner` ou `Member` para um projeto herdam automaticamente a função `namespace creation`. No entanto, essa função é um https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole[ClusterRole do Kubernetes], o que significa que seu escopo se estende a todos os projetos no cluster. Portanto, usuários explicitamente atribuídos à função `Owner` ou `Member` para um projeto podem criar namespaces em outros projetos aos quais estão atribuídos, mesmo com apenas a função `Read Only` atribuída.
* Por padrão, a função Rancher de `project-member` herda da função `Kubernetes-edit`, e a função `project-owner` herda da função `Kubernetes-admin`. Assim, tanto as funções `project-member` quanto `project-owner` permitirão o gerenciamento de namespaces, incluindo a capacidade de criar e excluir namespaces.
* Escolha `Custom` para criar uma função personalizada rapidamente: {xref-cluster-project-roles}#_custom_project_roles[Funções de Projeto Personalizadas].
====


Para adicionar membros:

. Na aba *Membros*, clique em *Adicionar*.
. No campo *Selecionar Membro*, pesquise por um usuário ou grupo que você deseja atribuir acesso ao projeto. Você só pode pesquisar grupos se a autenticação externa estiver habilitada.
+
[NOTE]
.Notes
====
* Pelo menos 2 caracteres devem ser digitados na caixa de pesquisa para que os resultados apareçam.
* Os usuários podem ser pesquisados com base em seu nome de usuário ou nome exibido.
* A pesquisa é baseada em prefixo (por exemplo, um usuário chamado `Stan Dard` aparecerá ao pesquisar por `Sta`, mas não ao pesquisar por `Dar`) e é sensível a maiúsculas e minúsculas.
====

. Na seção *Permissões do Projeto*, escolha uma função. Para mais informações, consulte a {xref-cluster-project-roles}[documentação sobre funções de projeto.]

[#_optional_add_resource_quotas]
=== Opcional: Adicionar Cotas de Recursos

As cotas de recursos limitam os recursos que um projeto (e seus namespaces) podem consumir. Para mais informações, veja {xref-project-resource-quotas}[Cotas de Recursos].

Para adicionar uma cota de recurso,

. Na aba *Cotas de Recursos*, clique em *Adicionar Recurso*.
. Selecione um *Tipo de Recurso*. Para mais informações, veja {xref-project-resource-quotas}[Cotas de Recursos.].
. Insira valores para o *Limite do Projeto* e o *Limite Padrão do Namespace*.
. *Opcional:* Especifique *Limite Padrão de Recursos do Contêiner*, que será aplicado a cada contêiner iniciado no projeto. O parâmetro é recomendado se você tiver limites de CPU ou Memória definidos pela Cota de Recursos. Ele pode ser substituído em um nível de namespace individual ou de contêiner. Para mais informações, veja {xref-project-resource-quotas}[Limite Padrão de Recursos do Contêiner]
. Clique em *Criar*.

*Resultado:* Seu projeto foi criado. Você pode visualizá-lo a partir da visualização de *Projetos/Namespaces* do cluster.

|===
| Campo | Descrição

| Limite do Projeto
| O limite geral de recursos para o projeto.

| Limite Padrão do Namespace
| O limite padrão de recursos disponível para cada namespace. Esse limite é propagado para cada namespace no projeto quando criado. O limite combinado de todos os namespaces do projeto não deve exceder o limite do projeto.
|===

[#_deleting_projects]
== Excluindo Projetos

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster ao qual o projeto está vinculado e clique em *Explorar*.
. Clique em menu:Cluster[Projetos/Namespaces].
. Encontre o projeto que você deseja excluir e clique em *⋮*.
. Selecione *Excluir*.

Quando você exclui um projeto, quaisquer namespaces que estavam anteriormente associados ao projeto permanecerão no cluster. Você pode encontrar esses namespaces na interface do Rancher, na aba *Não em um Projeto* da página *Projetos/Namespaces*. Você pode reatribuir esses namespaces a um projeto, {xref-namespaces}#_movendo_namespaces_para_outro_projeto[movendo]‑os.

[#_further_reading]
== Leitura recomendada

Você pode criar projetos e membros do projeto de forma mais programática através da xref:api/quickstart.adoc[API Pública]. Veja o xref:api/workflows/projects.adoc[documento de fluxo de trabalho do projeto] para mais informações.
