= Windows Support
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/fleet/windows-support.adoc 
:product-path: integrations/fleet/windows-support.adoc

Vor Rancher v2.5.6 hatte der `agent` keine nativen Windows-Manifeste auf Downstream-Clustern mit Windows-Knoten. Dies würde zu einem fehlerhaften `agent` Pod für den Cluster führen.

Wenn Sie von einer älteren Version von Rancher auf v2.5.6+ aktualisieren, können Sie einen funktionierenden `agent` mit dem folgenden Workflow _im Downstream-Cluster_ bereitstellen:

. Führen Sie cordon auf allen Windows-Knoten aus.
. Wenden Sie die folgende Tolerierung auf die `agent` Arbeitslast an.
. Führen Sie uncordon auf allen Windows-Knoten aus.
. Löschen Sie alle `agent` Pods. Neue Pods sollten mit der neuen Tolerierung erstellt werden.
. Sobald die `agent` Pods laufen und die automatische Aktualisierung für Fleet aktiviert ist, sollten sie auf eine Windows-kompatible `agent` Version aktualisiert werden.

[,yaml]
----
tolerations:
- effect: NoSchedule
  key: cattle.io/os
  operator: Equal
  value: linux
----
