= Herramientas del clúster para registro, monitoreo y observabilidad
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/rancher-cluster-tools.adoc 
:product-path: observability/rancher-cluster-tools.adoc
ifeval::["{build-type}" != "community"]
:xref-istio: xref:observability/istio/istio.adoc
:xref-monitoring-and-dashboards: xref:observabilidad/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:xref-logging: xref:observability/logging/logging.adoc
:xref-compliance-scans-howto: xref:security/compliance-scans/how-to.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio: xref:integrations-in-rancher/istio/index.adoc
:xref-monitoring-and-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/index.adoc
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
:xref-compliance-scans-howto: xref:how-to-guides/advanced-user-guides/compliance-scan-guides/index.adoc
endif::[]

Rancher contiene una variedad de herramientas que no están incluidas en Kubernetes para ayudar en tus operaciones de DevOps. Rancher puede integrarse con servicios externos para ayudar a que tus clústeres funcionen de manera más eficiente. Las herramientas se dividen en las siguientes categorías:

[#_logging]
== Registro

El registro es útil porque te permite:

* Capturar y analizar el estado de tu clúster
* Buscar tendencias en tu entorno
* Guardar tus registros en un lugar seguro fuera de tu clúster
* Mantenerte informado de eventos como un contenedor que se bloquea, una expulsión de pod o un nodo que falla
* Depurar y solucionar problemas más fácilmente

Rancher puede integrarse con Elasticsearch, Splunk, Kafka, Syslog y Fluentd.

Para obtener más información, consulta la documentación de registro {xref-logging}[aquí.]

[#_monitoring_and_alerts]
== Monitoreo y Alertas

Usando Rancher, puedes monitorear el estado y los procesos de los nodos de tu clúster, los componentes de Kubernetes y las ampliaciones de software a través de la integración con https://prometheus.io/[Prometheus], una solución de monitoreo de código abierto líder.

Una vez habilitado el monitoreo, puedes configurar alertas y notificadores que proporcionan el mecanismo para recibirlas.

Los notificadores son servicios que te informan sobre eventos de alerta. Puedes configurar los notificadores para enviar notificaciones de alerta al personal más adecuado para tomar medidas correctivas. Las notificaciones pueden enviarse a través de Slack, correo electrónico, PagerDuty, WeChat y webhooks.

Las alertas son reglas que desencadenan esas notificaciones. Antes de que puedas recibir alertas, debes configurar uno o más notificadores en Rancher. El alcance de las alertas puede establecerse a nivel de clúster o de proyecto.

Para obtener más información, consulta la documentación de monitoreo {xref-monitoring-and-dashboards}[aquí.]

[#_istio]
== Istio

https://istio.io/[Istio] es una herramienta de código abierto que facilita a los equipos de DevOps observar, controlar, solucionar problemas y asegurar el tráfico dentro de una red compleja de microservicios.

La integración de Rancher con Istio se mejoró en Rancher v2.5.

Para obtener más información, consulta la documentación de Istio {xref-istio}[aquí.]

[#_compliance_scans]
== Escaneos de Cumplimiento

Rancher puede ejecutar un escaneo de seguridad para verificar si Kubernetes está desplegado de acuerdo con las mejores prácticas de seguridad definidas en los estándares de seguridad de Kubernetes más reconocidos, como STIG.

Para obtener más información, consulta la documentación del escaneo de cumplimiento {xref-compliance-scans-howto}[aquí.]
