= Herramientas del proyecto para registro, monitoreo y visibilidad
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/rancher-project-tools.adoc 
:product-path: observability/rancher-project-tools.adoc
ifeval::["{build-type}" != "community"]
:xref-monitoring-and-dashboards: xref:observabilidad/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:xref-logging: xref:observability/logging/logging.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-monitoring-and-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/index.adoc
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
endif::[]

Rancher contiene una variedad de herramientas que no están incluidas en Kubernetes para ayudar en tus operaciones de DevOps. Rancher puede integrarse con servicios externos para ayudar a que tus clústeres funcionen de manera más eficiente.

[#_notifiers_and_alerts]
== Notificadores y alertas

Los notificadores y las alertas son dos características que trabajan juntas para informarte sobre eventos en el sistema Rancher. Antes de que puedan ser habilitadas, la aplicación de monitoreo debe estar instalada.

Los notificadores son servicios que te informan sobre eventos de alerta. Puedes configurar los notificadores para enviar notificaciones de alerta al personal más adecuado para tomar medidas correctivas. Las notificaciones pueden enviarse a través de Slack, correo electrónico, PagerDuty, WeChat y webhooks.

Las alertas son reglas que desencadenan esas notificaciones. Antes de que puedas recibir alertas, debes configurar uno o más notificadores en Rancher. El alcance de las alertas puede establecerse a nivel de clúster o de proyecto.

[#_logging]
== Registro

El registro es útil porque te permite:

* Capturar y analizar el estado de tu clúster
* Buscar tendencias en tu entorno
* Guardar tus registros en un lugar seguro fuera de tu clúster
* Mantenerte informado de eventos como un contenedor que se bloquea, una expulsión de pod o un nodo que falla
* Depurar y solucionar problemas más fácilmente

Rancher puede integrarse con Elasticsearch, Splunk, Kafka, Syslog y Fluentd.

Para obtener más información, consulta la {xref-logging}[sección de registro.]

[#_monitoring]
== Monitorización

Usando Rancher, puedes monitorear el estado y los procesos de los nodos de tu clúster, los componentes de Kubernetes y las ampliaciones de software a través de la integración con https://prometheus.io/[Prometheus], una solución de monitoreo de código abierto líder. Para obtener más detalles, consulta la {xref-monitoring-and-dashboards}[sección de monitoreo.]
