= Permisos de Grupo con Shibboleth y OpenLDAP
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configurar-shibboleth-saml/acerca-de-los-permisos-de-grupo.adoc 
:product-path: rancher-admin/users/authn-and-authz/shibboleth-saml/group-permissions.adoc

Debido a que Shibboleth es un proveedor SAML, no admite la búsqueda de grupos. Aunque una integración de Shibboleth puede validar las credenciales de los usuarios, no se puede utilizar para asignar permisos a grupos en Rancher sin una configuración adicional.

Una solución a este problema es configurar un proveedor de identidad OpenLDAP. Con un sistema secundario OpenLDAP para Shibboleth, podrás buscar grupos en Rancher y asignarlos a recursos como clústeres, proyectos o espacios de nombres desde la interfaz de usuario de Rancher.

[#_terminology]
== terminología

* *Shibboleth* es un sistema de inicio de sesión único para redes informáticas e Internet. Permite a las personas iniciar sesión utilizando solo una identidad en varios sistemas. Valida las credenciales de los usuarios, pero no gestiona, por sí solo, las membresías de grupos.
* *SAML:* Lenguaje de marcas de aserciones de seguridad, un estándar abierto para intercambiar datos de autenticación y autorización entre un proveedor de identidad y un proveedor de servicios.
* *OpenLDAP:* una implementación gratuita y de código abierto del Protocolo de Acceso a Directorios Ligero (LDAP). Se utiliza para gestionar los ordenadores y usuarios de una organización. OpenLDAP es útil para los usuarios de Rancher porque admite grupos. En Rancher, es posible asignar permisos a grupos para que puedan acceder a recursos como clústeres, proyectos o espacios de nombres, siempre que los grupos ya existan en el proveedor de identidad.
* *IdP o IDP:* Un proveedor de identidad. OpenLDAP es un ejemplo de un proveedor de identidad.

[#_adding_openldap_group_permissions_to_rancher_resources]
== Añadiendo Permisos de Grupo OpenLDAP a los Recursos de Rancher

El diagrama a continuación ilustra cómo los miembros de un grupo OpenLDAP pueden acceder a recursos en Rancher para los cuales el grupo tiene permisos.

Por ejemplo, un propietario de clúster podría añadir un grupo OpenLDAP a un clúster para que tenga permisos para ver la mayoría de los recursos a nivel de clúster y crear nuevos proyectos. Entonces, los miembros del grupo OpenLDAP tendrán acceso al clúster tan pronto como inicien sesión en Rancher.

En este escenario, OpenLDAP permite al propietario del clúster buscar grupos al asignar permisos. Sin OpenLDAP, la funcionalidad para buscar grupos no estaría soportada.

Cuando un miembro del grupo OpenLDAP inicia sesión en Rancher, se le redirige a Shibboleth y introduce su nombre de usuario y contraseña.

Shibboleth valida sus credenciales y recupera los atributos del usuario de OpenLDAP, incluidos los grupos. Luego, Shibboleth envía una aserción SAML a Rancher incluyendo los atributos del usuario. Rancher utiliza los datos del grupo para que pueda acceder a todos los recursos y permisos para los que sus grupos tienen permisos.

image::shibboleth-with-openldap-groups.svg[Añadiendo Permisos de Grupo OpenLDAP a los Recursos de Rancher]

[#_saml_and_openldap_group_permissions]
== Permisos de grupo SAML y OpenLDAP

include::shared:ROOT:partial$en/saml-openldap-group-permissions.adoc[]
