= Configurando Shibboleth (SAML)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-24
:page-revdate: {revdate}
:community-path: instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configurar-shibboleth-saml/index.adoc 
:product-path: rancher-admin/users/authn-and-authz/shibboleth-saml/shibboleth-saml.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-openldap-reference: xref:rancher-admin/users/authn-and-authz/openldap/reference.adoc
:xref-shibboleth-saml-group-permissions: xref:rancher-admin/users/authn-and-authz/shibboleth-saml/group-permissions.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configuración-de-autenticación/index.adoc
:xref-openldap-reference: xref:instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configurar-openldap/referencia-de-configuración-openldap.adoc
:xref-shibboleth-saml-group-permissions: xref:instrucciones/nuevos-usuarios/guías-de-autenticación-permisos-y-configuración-global/configurar-shibboleth-saml/acerca-de-los-permisos-de-grupo.adoc
endif::[]

Si tu organización utiliza Shibboleth Identity Provider (IdP) para la autenticación de usuarios, puedes configurar Rancher para permitir que tus usuarios inicien sesión en Rancher utilizando sus credenciales de Shibboleth.

En esta configuración, cuando los usuarios de Rancher inicien sesión, serán redirigidos al IdP de Shibboleth para ingresar sus credenciales. Después de la autenticación, serán redirigidos de vuelta a la interfaz de usuario de Rancher.

Si también configuras OpenLDAP como el sistema secundario de Shibboleth, devolverá una afirmación SAML a Rancher con atributos de usuario que incluyen grupos. Entonces, el usuario autenticado podrá acceder a los recursos en Rancher para los cuales sus grupos tienen permisos.

____
Las instrucciones en esta sección asumen que entiendes cómo funcionan juntos Rancher, Shibboleth y OpenLDAP. Para una explicación más detallada de cómo funciona, consulta {xref-shibboleth-saml-group-permissions}[esta página.]
____

[#_setting_up_shibboleth_in_rancher]
== Configurando Shibboleth en Rancher

[#_shibboleth_prerequisites]
=== Requisitos previos de Shibboleth

____
* Debes tener un servidor Shibboleth IdP configurado.
* A continuación se presentan las URL del Proveedor de Servicios de Rancher necesarias para la configuración:
Metadata URL: `\https://<rancher-server>/v1-saml/shibboleth/saml/metadata`
URL del Servicio de Consumo de Afirmaciones (ACS): `\https://<rancher-server>/v1-saml/shibboleth/saml/acs`
* Exporta un archivo `metadata.xml` desde tu servidor IdP. Para obtener más información, consulta la https://wiki.shibboleth.net/confluence/display/SP3/Home[documentación de Shibboleth.]
____

[#_configure_shibboleth_in_rancher]
=== Configura Shibboleth en Rancher

Si tu organización utiliza Shibboleth para la autenticación de usuarios, puedes configurar Rancher para permitir que tus usuarios inicien sesión utilizando sus credenciales de IdP.

. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En el menú de navegación de la izquierda, haz clic en *Proveedor de Autenticación*.
. Haz clic en *Shibboleth*.
. Completa el formulario *Configurar Cuenta de Shibboleth*. Shibboleth IdP te permite especificar qué almacén de datos deseas utilizar. Puedes añadir una base de datos o utilizar un servidor LDAP existente. Por ejemplo, si seleccionas tu servidor de Active Directory (AD), los ejemplos a continuación describen cómo puedes mapear atributos de AD a campos dentro de Rancher.
 .. *Campo Nombre para Mostrar*: Introduce el atributo de AD que contiene el nombre para mostrar de los usuarios (ejemplo: `displayName`).
 .. *Campo Nombre de Usuario*: Introduce el atributo de AD que contiene el nombre de usuario/nombre de pila (ejemplo: `givenName`).
 .. *Campo UID*: Introduce un atributo de AD que sea único para cada usuario (ejemplo: `sAMAccountName`, `distinguishedName`).
 .. *Campo Grupos*: Haz entradas para gestionar la membresía de grupos (ejemplo: `memberOf`).
 .. *Host de la API de Rancher*: Introduce la URL de tu servidor Rancher.
 .. *Clave Privada* y *Certificado*: Este es un par de clave-certificado para crear un shell seguro entre Rancher y tu IdP.
+
Puedes generar uno utilizando un comando openssl. Por ejemplo:
+
----
 openssl req -x509 -newkey rsa:2048 -keyout myservice.key -out myservice.cert -days 365 -nodes -subj "/CN=myservice.example.com"
----

 .. *IDP-metadata*: El archivo `metadata.xml` que exportaste desde tu servidor IdP.
. Después de completar el formulario *Configurar Cuenta Shibboleth*, haz clic en *Habilitar*.
+
Rancher te redirige a la página de inicio de sesión del IdP. Introduce las credenciales que autentican con Shibboleth IdP para validar tu configuración de Shibboleth en Rancher.
+

[NOTE]
====
Es posible que tengas que desactivar tu bloqueador de ventanas emergentes para ver la página de inicio de sesión del IdP.
====


*Resultado:* Rancher está configurado para trabajar con Shibboleth. Tus usuarios ahora pueden iniciar sesión en Rancher utilizando sus credenciales de Shibboleth.

[NOTE]
.Advertencias del Proveedor SAML
====
Si configuras Shibboleth sin OpenLDAP, las siguientes advertencias se aplican debido a que el Protocolo SAML no soporta búsqueda o consulta de usuarios o grupos.

* No hay validación sobre usuarios o grupos al asignar permisos a ellos en Rancher.
* Al añadir usuarios, los IDs de usuario exactos (es decir, el campo UID) deben ser introducidos correctamente. A medida que escribes el ID de usuario, no habrá búsqueda de otros IDs de usuario que puedan coincidir.
* Al añadir grupos, debes seleccionar el grupo del menú desplegable que está al lado del cuadro de texto. Rancher asume que cualquier entrada del cuadro de texto es un usuario.
* El menú desplegable de grupos muestra solo los grupos de los que eres miembro. Sin embargo, si tienes permisos de Administrador o permisos de Administrador restringidos, puedes unirte a un grupo del que no eres miembro.

Para habilitar la búsqueda de grupos al asignar permisos en Rancher, necesitarás configurar un sistema secundario para el proveedor SAML que soporte grupos, como OpenLDAP.
====

[#_configuring_saml_single_logout_slo]
=== Configuración de Cierre de Sesión Único SAML (SLO)

include::shared:ROOT:partial$en/configure-slo.adoc[]

[#_setting_up_openldap_in_rancher]
== Configuración de OpenLDAP en Rancher

Si también configuras OpenLDAP como el sistema secundario de Shibboleth, devolverá una afirmación SAML a Rancher con atributos de usuario que incluyen grupos. Entonces, los usuarios autenticados podrán acceder a los recursos en Rancher para los que sus grupos tienen permisos.

[#_openldap_prerequisites]
=== Requisitos Previos de OpenLDAP

Rancher debe estar configurado con una cuenta de enlace LDAP (también conocida como cuenta de servicio) para buscar y recuperar entradas LDAP relacionadas con los usuarios y grupos que deberían tener acceso. Se recomienda no utilizar una cuenta de administrador o cuenta personal para este propósito y, en su lugar, crear una cuenta dedicada en OpenLDAP con acceso de solo lectura a los usuarios y grupos bajo la base de búsqueda configurada (ver más abajo).

____
*¿Usando TLS?*

Si el certificado utilizado por el servidor OpenLDAP es autofirmado o no proviene de una autoridad de certificación reconocida, asegúrate de tener a mano el certificado CA (concatenado con cualquier certificado intermedio) en formato PEM. Tendrás que pegar este certificado durante la configuración para que Rancher pueda validar la cadena de certificados.
____

[#_configure_openldap_in_rancher]
=== Configura OpenLDAP en Rancher

Configura los ajustes para el servidor OpenLDAP, grupos y usuarios. Para ayuda al completar cada campo, consulta la {xref-openldap-reference}[referencia de configuración.] Ten en cuenta que la membresía de grupos anidados no está disponible para Shibboleth.

____
Antes de proceder con la configuración, familiarízate con los conceptos de {xref-authn-authz}#_external_authentication_configuration_and_principal_users[Configuración de Autenticación Externa y Usuarios Principales].
____

. Inicia sesión en la interfaz de usuario de Rancher utilizando la cuenta local inicial `admin`.
. En la esquina superior izquierda, haz clic en *☰ > Usuarios y Autenticación*.
. En el menú de navegación de la izquierda, haz clic en *Proveedor de Autenticación*.
. Haz clic en *Shibboleth* o, si SAML ya está configurado, en *Editar Config*
. Bajo *Búsqueda de Usuarios y Grupos*, marca *Configurar un servidor OpenLDAP*

[#_troubleshooting]
== Solución de problemas

Si estás experimentando problemas al probar la conexión con el servidor OpenLDAP, primero verifica las credenciales ingresadas para la cuenta de servicio así como la configuración de la base de búsqueda. También puedes inspeccionar los registros de Rancher para ayudar a identificar la causa del problema. Los registros de depuración pueden contener información más detallada sobre el error. Por favor, consulta xref:faq/technical-items.adoc#_how_can_i_enable_debug_logging[Cómo puedo habilitar el registro de depuración] en esta documentación.
