= Verschlüsselung der HTTP-Kommunikation
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc 
:product-path: security/encrypting-http.adoc
:description: Erfahren Sie, wie Sie ein SSL (Secure Sockets Layer)-Zertifikat oder ein TLS (Transport Layer Security)-Zertifikat hinzufügen können
:experimental:
ifeval::["{build-type}" != "community"]
:xref-add-ingresses: xref:cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/add-ingresses.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-add-ingresses: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/add-ingresses.adoc
endif::[]

Wenn Sie ein Ingress innerhalb von Rancher/Kubernetes erstellen, müssen Sie ihm ein Geheimnis zur Verfügung stellen, das einen TLS-Privatschlüssel und ein Zertifikat enthält, die verwendet werden, um die Kommunikation, die durch das Ingress kommt, zu verschlüsseln und zu entschlüsseln. Sie können Zertifikate für die Verwendung mit Ingress verfügbar machen, indem Sie das Zertifikat in die Ingress-Implementierung hinzufügen.

[NOTE]
.Voraussetzung:
====

Sie müssen einen TLS-Privatschlüssel und ein Zertifikat zur Verfügung haben, um sie hochzuladen.
====


[#_1_create_a_secret]
== 1. Erstellen Sie ein Geheimnis

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie Ihr Ingress bereitstellen möchten, und klicken Sie auf menu:Weitere Ressourcen[Kernel> Geheimnisse].
. Klicken Sie auf *Erstellen*.
. Klicken Sie auf *TLS-Zertifikat*.
. Geben Sie einen Namen für das Geheimnis ein. Hinweis: Ihr Geheimnis muss einen eindeutigen Namen unter den anderen Zertifikaten, Registries und Geheimnissen innerhalb Ihres Projekts/Ihres Arbeitsbereichs haben.
. Geben Sie im Feld *Privatschlüssel* entweder den Privatschlüssel Ihres Zertifikats in das Textfeld ein (einschließlich der Kopf- und Fußzeile) oder klicken Sie auf *Von einer Datei lesen*, um den Privatschlüssel auf Ihrem Dateisystem auszuwählen. Wenn möglich, empfehlen wir die Verwendung von *Von einer Datei lesen*, um die Wahrscheinlichkeit von Fehlern zu verringern. Hinweis: Privatschlüsseldateien enden mit einer Erweiterung `.key`.
. Geben Sie im Feld *Zertifikat* entweder Ihr Zertifikat in das Textfeld ein (einschließlich der Kopf- und Fußzeile) oder klicken Sie auf *Von einer Datei lesen*, um das Zertifikat auf Ihrem Dateisystem auszuwählen. Wenn möglich, empfehlen wir die Verwendung von *Von einer Datei lesen*, um die Wahrscheinlichkeit von Fehlern zu verringern. Hinweis: Zertifikatsdateien enden mit einer Erweiterung `.crt`.
. Klicken Sie auf *Erstellen*.

[#_2_add_the_secret_to_an_ingress]
== 2. Fügen Sie das Geheimnis zu einem Ingress hinzu

. Klicken Sie in der oberen linken Ecke auf *☰ > Clusterverwaltung*.
. Gehen Sie zu dem Cluster, in dem Sie Ihr Ingress bereitstellen möchten, und klicken Sie auf menu:Service Discovery[Ingresses].
. Klicken Sie auf *Erstellen*.
. Wählen Sie den *Namespace* des Ingress aus.
. Geben Sie einen *Name* für den Ingress ein.
. Wählen Sie im *Zertifikate*-Tab das Geheimnis aus, das Ihr Zertifikat und Ihren privaten Schlüssel enthält.
. Klicken Sie auf *Erstellen*.

[#_whats_next]
== Weitere Schritte?

Jetzt können Sie das Zertifikat beim Starten eines Ingress innerhalb des aktuellen Projekts oder Namensraums hinzufügen. Weitere Informationen finden Sie unter {xref-add-ingresses}[Ingress hinzufügen].
