= {rancher-product-name} Sicherheitsleitfäden
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-01-20
:page-revdate: {revdate}
:community-path: reference-guides/rancher-security/index.adoc 
:product-path: security/security-overview.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rbac: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc
:xref-compliance-scans-howto: xref:security/compliance-scans/how-to.adoc
:xref-selinux-rpm: xref:security/selinux-rpm/selinux-rpm.adoc
:xref-neuvector: xref:integrations/neuvector/neuvector.adoc
:xref-cves: xref:security/cves.adoc
:xref-security-best-practices: xref:security/rancher-security-best-practices.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rbac: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/index.adoc
:xref-compliance-scans-howto: xref:how-to-guides/advanced-user-guides/compliance-scan-guides/index.adoc
:xref-selinux-rpm: xref:reference-guides/rancher-security/selinux-rpm/index.adoc
:xref-neuvector: xref:integrations-in-rancher/neuvector/index.adoc
:xref-cves: xref:reference-guides/rancher-security/security-advisories-and-cves.adoc
:xref-security-best-practices: xref:reference-guides/rancher-security/rancher-security-best-practices.adoc
endif::[]

[pass]
<table width="100%">
  <tr style="vertical-align: top;text-align: center;border-bottom-style: none;border-top-style: solid;border-top-width: 2px;border-top-color: #c0c2c4;">
    <td width="30%">
      <h4>Sicherheitsrichtlinie</h4><br/>
      <p style="{{padding:" mem-invalid-attributes-holder='8px'}}>Rancher Labs unterstützt verantwortungsvolle Offenlegung und bemüht sich, alle Probleme in einem angemessenen Zeitrahmen zu lösen. </p>
    </td>
    <td width="30%">
      <h4>Meldeprozess</h4><br/>
      <p style="{{padding:" mem-invalid-attributes-holder='8px'}}>Bitte senden Sie mögliche Sicherheitsprobleme per E-Mail an <a href="mailto:security-rancher@suse.com">security-rancher@suse.com</a>.</p>
    </td>
    <td width="30%">
      <h4>Ankündigungen</h4><br/>
      <p style={{padding:'8px'}}>Abonnieren Sie das <a href="https://forums.rancher.com/c/announcements">Rancher-Ankündigungsforum</a> für Aktualisierungen zu Veröffentlichungen.</p>
    </td>
  </tr>
</table>

Sicherheit steht im Mittelpunkt aller Rancher-Funktionen. Von der Integration mit allen gängigen Authentifizierungswerkzeugen und -diensten bis hin zu einer Unternehmensklasse {xref-manage-rbac}[RBAC-Funktionalität] macht Rancher Ihre Kubernetes-Cluster noch sicherer.

Auf dieser Seite stellen wir sicherheitsrelevante Dokumentationen sowie Ressourcen zur Verfügung, die Ihnen helfen, Ihre Rancher-Installation und Ihre Downstream-Kubernetes-Cluster abzusichern.

[#__neuvector_product_name_integration_with_rancher]
== {neuvector-product-name} Integration mit Rancher

NeuVector ist eine Open-Source-Sicherheitsanwendung, die sich auf Container konzentriert und jetzt in Rancher integriert ist. NeuVector bietet Produktionssicherheit, DevOps-Schutz vor Schwachstellen und eine Container-Firewall usw. Bitte siehe die {xref-neuvector}[Rancher-Dokumentation] und die https://documentation.suse.com/cloudnative/security/{neuvector-docs-version}/en/overview.html[{neuvector-product-name} Dokumente] für weitere Informationen.

[#_running_a_compliance_security_scan_on_a_kubernetes_cluster]
== Durchführung eines Compliance-Sicherheits-Scans auf einem Kubernetes-Cluster

Rancher nutzt https://github.com/aquasecurity/kube-bench[kube-bench], um einen Sicherheits-Scan durchzuführen, um zu überprüfen, ob Kubernetes gemäß den besten Sicherheitspraktiken bereitgestellt wurde.

Wenn Rancher einen Compliance-Scan auf einem Cluster durchführt, wird ein Bericht erstellt, der die Ergebnisse jedes Tests zeigt, einschließlich einer Zusammenfassung mit der Anzahl der bestandenen, übersprungenen und fehlgeschlagenen Tests. Der Bericht enthält auch Maßnahmen zur Behebung von fehlgeschlagenen Tests.

Für Details siehe den Abschnitt über {xref-compliance-scans-howto}[Sicherheits-Scans].

[#_selinux_rpm]
== SELinux RPM

Wir bieten drei RPMs (RPM Package Manager) an, die es Rancher-Produkten ermöglichen, ordnungsgemäß auf SELinux-durchsetzenden Hosts zu funktionieren: `rancher-selinux`, `rke2-selinux` und `k3s-selinux`.  Für Details siehe {xref-selinux-rpm}[diese Seite].

[#_rancher_hardening_guide]
== Rancher-Härtungsleitfaden

Der Rancher-Härtungsleitfaden basiert auf Kontrollen und Best Practices, die im https://www.cisecurity.org/benchmark/kubernetes/[CIS Kubernetes Benchmark] des Center for Internet Security zu finden sind.

Die Härtungsleitfäden bieten präskriptive Anleitungen zur Härtung einer Produktionsinstallation von Rancher. Siehe die Leitfäden von Rancher für <<_the_cis_benchmark_and_self_assessment,Selbsteinschätzung des CIS Kubernetes Benchmark>> für die vollständige Liste der Sicherheitskontrollen.

____
Die Härtungsleitfäden beschreiben, wie die Knoten in Ihrem Cluster gesichert werden, und es wird empfohlen, einen Härtungsleitfaden zu befolgen, bevor Sie Kubernetes installieren.
____

Jede Version des Härtungsleitfadens ist für die Verwendung mit spezifischen Versionen des CIS Kubernetes Benchmark, Kubernetes und Rancher vorgesehen.

[#_the_cis_benchmark_and_self_assessment]
== Der CIS-Benchmark und die Selbsteinschätzung

Die Selbsteinschätzung des Benchmarks ist ein Begleitdokument zum Rancher-Sicherheits-Härtungsleitfaden. Während der Härtungsleitfaden Ihnen zeigt, wie Sie den Cluster härten, soll der Benchmarkleitfaden Ihnen helfen, das Sicherheitsniveau des gehärteten Clusters zu bewerten.

Dieser Leitfaden führt durch die verschiedenen Kontrollen und bietet aktualisierte Beispielbefehle zur Überprüfung der Konformität in von Rancher erstellten Clustern. Die ursprünglichen Benchmarkdokumente können von der https://www.cisecurity.org/benchmark/kubernetes/[CIS-Website] heruntergeladen werden.

Jede Version des Selbstbewertungsleitfadens von Rancher entspricht spezifischen Versionen des Härtungsleitfadens, Rancher, Kubernetes und des CIS-Benchmarks.

[#_third_party_penetration_test_reports]
== Penetrationstestberichte von Dritten

Rancher beauftragt regelmäßig Dritte, Sicherheitsaudits und Penetrationstests des Rancher-Software-Stack durchzuführen. Die getesteten Umgebungen folgen den von Rancher bereitgestellten Härtungsleitfäden zum Zeitpunkt der Tests. Frühere Penetrationstestberichte sind unten verfügbar.

Ergebnisse:

* https://releases.rancher.com/documents/security/pen-tests/2019/RAN-01-cure53-report.final.pdf[Cure53 Penetrationstest - Juli 2019]
* https://releases.rancher.com/documents/security/pen-tests/2019/UntamedTheory-Rancher_SecurityAssessment-20190712_v5.pdf[Untamed Theory Penetrationstest - März 2019]

Bitte beachten Sie, dass neue Berichte nicht mehr geteilt oder öffentlich zugänglich gemacht werden.

[#_rancher_security_advisories_and_cves]
== Rancher Sicherheitswarnungen und CVEs

Rancher verpflichtet sich, die Gemeinschaft über Sicherheitsprobleme in unseren Produkten zu informieren. Für die Liste der CVEs (Common Vulnerabilities and Exposures) zu Problemen, die wir behoben haben, siehe {xref-cves}[diese Seite.]

[#_kubernetes_security_best_practices]
== Kubernetes Security Best Practices

Für Empfehlungen zur Absicherung Ihres Kubernetes-Clusters siehe den https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/[Kubernetes Cluster Sicherheits-Best-Practices] Leitfaden.

[#_rancher_security_best_practices]
== Rancher Sicherheits-Best-Practices

Für Empfehlungen zur Absicherung Ihrer Rancher Manager Implementierungen siehe den {xref-security-best-practices}[Rancher Sicherheits-Best-Practices] Leitfaden.

[#_rancher_kubernetes_distributions_k3s_rke2_self_assessment_and_hardening_guides]
== Rancher Kubernetes Distributionen (K3s/RKE2) Selbstbewertungs- und Härtungsleitfäden

Rancher verwendet die folgenden Kubernetes-Distributionen:

* https://documentation.suse.com/en-us/cloudnative/rke2/[*RKE2*] ist eine vollständig konforme Kubernetes-Distribution, die sich auf Sicherheit und Compliance innerhalb der USA konzentriert. US-Bundesbehörden liegt.
* https://documentation.suse.com/en-us/cloudnative/k3s/[*K3s*] ist eine vollständig konforme, leichtgewichtige Kubernetes-Distribution. Es ist einfach zu installieren, mit der Hälfte des Speicherbedarfs von Upstream Kubernetes, alles in einer Binärdatei von weniger als 100 MB.

Um einen Kubernetes-Cluster zu härten, der eine andere Distribution als die aufgeführten verwendet, siehe die Dokumentation Ihres Kubernetes-Anbieters.

[#_hardening_guides_and_benchmark_versions]
=== Härtungsleitfäden und Benchmark-Versionen

Jeder Selbstbewertungsleitfaden wird von einem Härtungsleitfaden begleitet. Diese Leitfäden wurden zusammen mit den aufgeführten Rancher-Versionen getestet. Jeder Selbstbewertungsleitfaden wurde auf einer bestimmten Kubernetes-Version und CIS-Benchmark-Version getestet. Wenn ein CIS-Benchmark für Ihre Kubernetes-Version nicht validiert wurde, können Sie die vorhandenen Leitfäden verwenden, bis ein Leitfaden für Ihre Version hinzugefügt wird.

[#_rke2_guides]
=== RKE2 Leitfäden

|===
| Typ | Kubernetes Version | CIS Benchmark Version | Leitfaden zur Selbstbewertung | Härtungshandbuch

| Standalone RKE2
| Kubernetes v1.27
| CIS v1.9
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment19.html[Link]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Link]

| Standalone RKE2
| Kubernetes v1.28
| CIS v1.10
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment110.html[Link]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Link]

| Standalone RKE2
| Kubernetes v1.29 und höher
| CIS v1.11
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment111.html[Link]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Link]
|===

[#_k3s_guides]
=== K3s Leitfäden

|===
| Typ | Kubernetes Version | CIS Benchmark Version | Leitfaden zur Selbstbewertung | Härtungshandbuch

| Standalone K3s
| Kubernetes v1.27
| CIS v1.9
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.9.html[Link]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Link]

| Standalone K3s
| Kubernetes v1.28
| CIS v1.10
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.10.html[Link]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Link]

| Standalone K3s
| Kubernetes v1.29 und höher
| CIS v1.11
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.11.html[Link]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Link]
|===
