= Referencia de configuración de máquina EC2
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-10
:page-revdate: {revdate}
:community-path: guías-de-referencia/configuración-del-clúster/configuración-del-clúster-sentido-descendente/configuración-de-máquina/amazon-ec2.adoc 
:product-path: cluster-deployment/infra-providers/aws/machine-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
endif::[]

Para más detalles sobre los nodos de EC2, consulta la documentación oficial para la https://aws.amazon.com/ec2[Consola de gestión de EC2].

[#_basic_options]
== Opciones básicas

[#_region]
=== Región

La https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html[región] geográfica en la que construir tu clúster.

[#_zone]
=== Zona

La https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-availability-zones[zona], una ubicación aislada dentro de una región para construir tu clúster.

[#_instance_type]
=== Tipo de instancia

El https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html[tipo de instancia], que determina las características de hardware, utilizado para aprovisionar tu clúster.

[#_root_disk_size]
=== Tamaño del disco raíz

Configura el tamaño (en GB) para tu https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html[dispositivo raíz].

[#_vpc_subnet]
=== VPC/Subnet

La https://docs.aws.amazon.com/vpc/latest/userguide/configure-your-vpc.html[VPC] o https://docs.aws.amazon.com/vpc/latest/userguide/configure-subnets.html[subred] específica, un rango de IP en tu VPC, para añadir tus recursos.

[#_iam_instance_profile_name]
=== Nombre del perfil de instancia IAM

El nombre del https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html[perfil de instancia] utilizado para pasar un rol IAM a una instancia de EC2.

[#_advanced_options]
== Opciones avanzadas

[#_ami_id]
=== ID de AMI

La https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html[Imagen de Máquina de Amazon] utilizada para los nodos en tu clúster.

[#_ssh_username_for_ami]
=== Nombre de usuario SSH para AMI

El nombre de usuario para conectarte a tus instancias lanzadas. Consulta https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connection-prereqs.html[aquí] para los nombres de usuario predeterminados de las AMIs seleccionadas. Para las AMIs no listadas, consulta con el proveedor de AMI.

[#_security_group]
=== Grupo de seguridad

Elige el grupo de seguridad predeterminado o configura un grupo de seguridad.

Por favor, consulta {xref-port-reqs}#_rancher_aws_ec2_security_group[grupo de seguridad de Amazon EC2 al usar el controlador de nodos] para ver qué reglas se crean en el `rancher-nodes` grupo de seguridad.

[#_ebs_root_volume_type]
=== Tipo de volumen raíz EBS

El https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html[tipo de volumen EBS] a utilizar para el dispositivo raíz.

[#_encrypt_ebs_volume]
=== Cifrar volumen EBS

Habilitar https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html[el cifrado de Amazon EBS].

[#_request_spot_instance]
=== Solicitar instancia Spot

Habilitar la opción de https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html[solicitar instancias spot] y especificar el precio máximo por hora que estás dispuesto a pagar.

[#_use_only_private_address]
=== Usar solo dirección privada

Habilitar la opción de usar solo https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html[direcciones privadas].

[#_ebs_optimized_instance]
=== Instancia optimizada para EBS

Usar una https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html[instancia optimizada para EBS].

[#_allow_access_to_ec2_metadata]
=== Permitir acceso a los metadatos de EC2

Habilitar acceso a https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html[los metadatos de EC2].

[#_use_tokens_for_metadata]
=== Usar tokens para metadatos

Usar https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html[la versión 2 del servicio de metadatos de instancia (IMDSv2)], un método basado en tokens para acceder a los metadatos.

[#_add_tag]
=== Añadir etiqueta

Añadir metadatos usando https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html[etiquetas] para categorizar recursos.

[#_ipv6_address_count]
=== Conteo de direcciones IPv6

Especificar cuántas direcciones IPv6 asignar a la interfaz de red de la instancia.

[#_ipv6_address_only]
=== Solo dirección IPv6

Habilitar esta opción si la instancia debe usar IPv6 exclusivamente. Las VPCs o subredes exclusivas para IPv6 requieren esto. Cuando está habilitado, la instancia tiene IPv6 como su única dirección, y el conteo de direcciones IPv6 debe ser mayor que cero.

[#_http_protocol_ipv6]
=== HTTP Protocol IPv6

Habilitar o deshabilitar los puntos finales de IPv6 para el servicio de metadatos de la instancia.

[#_enable_primary_ipv6]
=== Habilitar IPv6 primario

Habilitar esta opción para designar la primera dirección IPv6 asignada como la dirección principal. Esto asegura una dirección IPv6 consistente y no cambiante para la instancia. No controla si se asignan direcciones IPv6.
