= Kubernetes-Cluster im {rancher-product-name} Setup
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc 
:product-path: cluster-deployment/cluster-deployment.adoc
:description: Bereitstellung von Kubernetes-Clustern
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-custom-clusters: xref:cluster-deployment/custom-clusters/custom-clusters.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
:xref-rancher-architecture: xref:about-rancher/architecture/architecture.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-infra-providers: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/index.adoc
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
:xref-custom-clusters: xref:reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/index.adoc
:xref-hosted-k8s-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/index.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
endif::[]

Rancher vereinfacht die Erstellung von Clustern, indem es Ihnen ermöglicht, diese über die Rancher-Benutzeroberfläche zu erstellen, anstatt komplexere Alternativen zu nutzen. Rancher bietet mehrere Optionen zum Starten eines Clusters. Verwenden Sie die Option, die am besten zu Ihrem Anwendungsfall passt.

Dieser Abschnitt setzt eine grundlegende Vertrautheit mit Docker und Kubernetes voraus. Für eine kurze Erklärung, wie die Kubernetes-Komponenten zusammenarbeiten, verweisen Sie auf die {xref-k8s-concepts}[Konzepte]-Seite.

Für einen konzeptionellen Überblick darüber, wie der Rancher-Server Cluster bereitstellt und welche Werkzeuge er dafür verwendet, verweisen Sie auf die {xref-rancher-architecture}[Architektur]-Seite.

[#_cluster_management_capabilities_by_cluster_type]
== Cluster-Verwaltungsfunktionen nach Cluster-Typ

Die folgende Tabelle fasst die Optionen und Einstellungen für jeden Cluster-Typ zusammen:

ifeval::["{build-type}" != "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table.adoc[]
endif::[]
ifeval::["{build-type}" == "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table-srfa.adoc[]
endif::[]

[#_setting_up_clusters_in_a_hosted_kubernetes_provider]
== Einrichten von Clustern in einem gehosteten Kubernetes-Anbieter

ifeval::["{build-type}" != "srfa"]
In diesem Szenario provisioniert Rancher Kubernetes nicht, da es von Anbietern wie Google Kubernetes Engine (GKE), Amazon Elastic Container Service für Kubernetes oder Azure Kubernetes Service installiert wird.
endif::[]
ifeval::["{build-type}" == "srfa"]
In diesem Szenario provisioniert Rancher Kubernetes nicht, da es von Amazon Elastic Container Service für Kubernetes installiert wird.
endif::[]

ifeval::["{build-type}" != "srfa"]
Wenn Sie einen Kubernetes-Anbieter wie Google GKE verwenden, integriert sich Rancher mit dessen Cloud-APIs, sodass Sie die rollenbasierte Zugriffskontrolle für den gehosteten Cluster über die Rancher-Benutzeroberfläche erstellen und verwalten können.
endif::[]
ifeval::["{build-type}" == "srfa"]
Wenn Sie einen Kubernetes-Anbieter verwenden, integriert sich Rancher mit dessen Cloud-APIs, sodass Sie die rollenbasierte Zugriffskontrolle für den gehosteten Cluster über die Rancher-Benutzeroberfläche erstellen und verwalten können.
endif::[]

Für weitere Informationen siehe den Abschnitt über {xref-hosted-k8s-clusters}[gehostete Kubernetes-Cluster].

[#_launching_kubernetes_with_rancher]
== Kubernetes mit Rancher starten

Rancher verwendet https://docs.rke2.io/[RKE2] oder https://docs.k3s.io/[K3s] als Bibliothek, wenn Kubernetes auf Ihren eigenen Knoten bereitgestellt wird. RKE2 ist Ranchers eigener leichter Kubernetes-Installer.

In RKE2-Clustern verwaltet Rancher die Bereitstellung von Kubernetes. Diese Cluster können auf jedem Bare-Metal-Server, Cloud-Anbieter oder Virtualisierungsplattform bereitgestellt werden.

Wenn Sie bereits einen Knoten haben, den Sie zu einem RKE2-Cluster hinzufügen möchten, können Sie ihn hinzufügen, indem Sie einen Rancher RKE2-Agent-Container darauf ausführen.

Für weitere Informationen siehe {xref-launch-k8s-with-rancher}[Kubernetes mit Rancher starten].

[#_launching_kubernetes_and_provisioning_nodes_in_an_infrastructure_provider]
=== Kubernetes starten und Knoten in einem Infrastruktur-Anbieter bereitstellen

ifeval::["{build-type}" != "srfa"]
Rancher kann Knoten in Infrastruktur-Anbietern wie Amazon EC2, DigitalOcean, Azure oder vSphere dynamisch bereitstellen und anschließend Kubernetes darauf installieren.
endif::[]
ifeval::["{build-type}" == "srfa"]
Rancher kann Knoten in Infrastruktur-Anbietern wie Amazon EC2 dynamisch bereitstellen und anschließend Kubernetes darauf installieren.
endif::[]

Ein Vorteil der Verwendung von Knoten, die von einem Infrastruktur-Anbieter gehostet werden, besteht darin, dass, wenn ein Knoten die Verbindung zum Cluster verliert, Rancher ihn automatisch ersetzen kann, um die erwartete Clusterkonfiguration aufrechtzuerhalten.

Für weitere Informationen siehe {xref-infra-providers}[Kubernetes auf neuen Knoten in einem Infrastruktur-Anbieter starten]

[#_launching_kubernetes_on_existing_custom_nodes]
=== Kubernetes auf vorhandenen benutzerdefinierten Knoten starten

Bei der Einrichtung dieses Typs von Cluster installiert Rancher Kubernetes auf vorhandenen {xref-custom-clusters}[benutzerdefinierten Knoten,] was einen benutzerdefinierten Cluster erstellt.

Sie können beliebige Knoten zu Rancher bringen und sie verwenden, um einen Cluster zu erstellen.

Diese Knoten umfassen lokale Bare-Metal-Server, cloudgehostete virtuelle Maschinen oder lokale virtuelle Maschinen.

[#_registering_existing_clusters]
== Registrierung vorhandener Cluster

Die Clusterregistrierungsfunktion ersetzt die Funktion zum Importieren von Clustern.

Die Registrierung von EKS-Clustern bietet nun zusätzliche Vorteile. Im Großen und Ganzen werden registrierte EKS-Cluster und EKS-Cluster, die in Rancher erstellt wurden, in der Rancher-Benutzeroberfläche gleich behandelt, mit Ausnahme der Löschung.

Wenn Sie einen EKS-Cluster löschen, der in Rancher erstellt wurde, wird der Cluster zerstört. Wenn Sie einen EKS-Cluster löschen, der in Rancher registriert wurde, wird er vom Rancher-Server getrennt, existiert jedoch weiterhin und Sie können weiterhin auf ihn zugreifen, wie Sie es vor der Registrierung in Rancher getan haben.

Für weitere Informationen siehe {xref-register-clusters}[Registrierung vorhandener Cluster].

[#_programmatically_creating_clusters]
== Programmgesteuertes Erstellen von Clustern

Der gebräuchlichste Weg, Kubernetes-Cluster programmgesteuert über Rancher bereitzustellen, ist die Verwendung des Rancher2 Terraform-Anbieters. Siehe die Dokumentation für https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster[Cluster mit Terraform erstellen].

ifeval::["{build-type}" != "srfa"]
EKS-, GKE- und AKS-Cluster können mit Terraform erstellt oder importiert werden.
endif::[]
ifeval::["{build-type}" == "srfa"]
EKS-Cluster können mit Terraform erstellt oder importiert werden.
endif::[]
