= Registrierte Cluster
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: troubleshooting/other-troubleshooting-tips/registered-clusters.adoc 
:product-path: cluster-deployment/register-existing-clusters-troubleshooting.adoc

Die auf dieser Seite aufgeführten Befehle und Schritte können verwendet werden, um Cluster zu überprüfen, die Sie registrieren oder die in Rancher registriert sind.

Stellen Sie sicher, dass Sie die korrekte kubeconfig konfiguriert haben (zum Beispiel `export KUBECONFIG=$PWD/kubeconfig_from_imported_cluster.yml`)

[#_rancher_agents]
== Rancher-Agenten

Die Kommunikation mit dem Cluster (Kubernetes-API über cattle-cluster-agent) und die Kommunikation mit den Knoten erfolgt über Rancher-Agenten.

Wenn der cattle-cluster-agent keine Verbindung zu dem konfigurierten `server-url` herstellen kann, bleibt der Cluster im Zustand *Ausstehend* und zeigt `Waiting for full cluster configuration` an.

[#_cattle_node_agent]
=== cattle-node-agent

[NOTE]
====

cattle-node-agents sind nur in Clustern vorhanden, die in Rancher mit RKE erstellt wurden.
====


Überprüfen Sie, ob die cattle-node-agent-Pods auf jedem Knoten vorhanden sind, den Status *Running* haben und keine hohe Anzahl an Neustarts aufweisen:

----
kubectl -n cattle-system get pods -l app=cattle-agent -o wide
----

Beispielausgabe:

----
NAME                      READY     STATUS    RESTARTS   AGE       IP                NODE
cattle-node-agent-4gc2p   1/1       Running   0          2h        x.x.x.x           worker-1
cattle-node-agent-8cxkk   1/1       Running   0          2h        x.x.x.x           etcd-1
cattle-node-agent-kzrlg   1/1       Running   0          2h        x.x.x.x           etcd-0
cattle-node-agent-nclz9   1/1       Running   0          2h        x.x.x.x           controlplane-0
cattle-node-agent-pwxp7   1/1       Running   0          2h        x.x.x.x           worker-0
cattle-node-agent-t5484   1/1       Running   0          2h        x.x.x.x           controlplane-1
cattle-node-agent-t8mtz   1/1       Running   0          2h        x.x.x.x           etcd-2
----

Überprüfen Sie die Protokollierung eines bestimmten cattle-node-agent-Pods oder aller cattle-node-agent-Pods:

----
kubectl -n cattle-system logs -l app=cattle-agent
----

[#_cattle_cluster_agent]
=== cattle-cluster-agent

Überprüfen Sie, ob der cattle-cluster-agent-Pod im Cluster vorhanden ist, den Status *Running* hat und keine hohe Anzahl an Neustarts aufweist:

----
kubectl -n cattle-system get pods -l app=cattle-cluster-agent -o wide
----

Beispielausgabe:

----
NAME                                    READY     STATUS    RESTARTS   AGE       IP           NODE
cattle-cluster-agent-54d7c6c54d-ht9h4   1/1       Running   0          2h        x.x.x.x      worker-1
----

Überprüfen Sie die Protokollierung des cattle-cluster-agent-Pods:

----
kubectl -n cattle-system logs -l app=cattle-cluster-agent
----
