= Lancement de Kubernetes sur des nœuds personnalisés existants.
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/index.adoc 
:product-path: cluster-deployment/custom-clusters/custom-clusters.adoc
:description: Pour créer un cluster avec des nœuds personnalisés, vous devrez accéder aux serveurs de votre cluster et les provisionner selon les exigences de Rancher.
ifeval::["{build-type}" != "community"]
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-use-windows-clusters: xref:cluster-deployment/custom-clusters/windows/use-windows-clusters.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-clean-cluster-nodes: xref:cluster-admin/manage-clusters/clean-cluster-nodes.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
:xref-production-checklist: xref:cluster-deployment/production-checklist/production-checklist.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-node-reqs: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters.adoc
:xref-rke2-config: xref:guides-de-référence/configuration-de-cluster/configuration-du-serveur-rancher/configuration-du-cluster-rke2.adoc
:xref-use-windows-clusters: xref:how-to-guides/nouveaux-utilisateurs/kubernetes-clusters-dans-rancher-configuration/utiliser-des-clusters-windows/index.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-clean-cluster-nodes: xref:how-to-guides/new-user-guides/manage-clusters/clean-cluster-nodes.adoc
:xref-k3s-config: xref:guides-de-référence/configuration-de-cluster/configuration-du-serveur-rancher/configuration-du-cluster-k3s.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
:xref-production-checklist: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters/index.adoc
endif::[]

Lorsque vous créez un cluster personnalisé, Rancher peut utiliser RKE2/K3s pour créer un cluster Kubernetes sur des serveurs de matériel sans système d'exploitation sur site, des machines virtuelles sur site ou sur tout nœud hébergé par un fournisseur d'infrastructure.

Pour utiliser cette option, vous devez avoir accès aux serveurs qui feront partie de votre cluster Kubernetes. Provisionnez chaque serveur selon les {xref-node-reqs}[exigences]. Ensuite, exécutez la commande fournie dans l'interface utilisateur de Rancher sur chaque serveur pour le convertir en nœud Kubernetes.

Cette section décrit comment configurer un cluster personnalisé.

[#_creating_a_cluster_with_custom_nodes]
== Créer un cluster avec des nœuds personnalisés

[NOTE]
.Vous souhaitez utiliser des hôtes Windows comme nœuds de travail Kubernetes{nbsp}?
====

Consultez {xref-use-windows-clusters}[Configuration des clusters personnalisés pour Windows] avant de commencer.
====


[#_1_provision_a_linux_host]
=== 1. Provisionnez un hôte Linux

Commencez la création d'un cluster personnalisé en provisionnant un hôte Linux. Votre hôte peut être{nbsp}:

* Une machine virtuelle (VM) hébergée dans le cloud
* Une VM sur site
* Un serveur en matériel sans système d'exploitation

Si vous souhaitez réutiliser un nœud d'un cluster personnalisé précédent, {xref-clean-cluster-nodes}[nettoyez le nœud] avant de l'utiliser à nouveau dans un cluster. Si vous réutilisez un nœud qui n'a pas été nettoyé, le provisionnement du cluster peut échouer.

Provisionnez l'hôte selon les {xref-node-reqs}[exigences d'installation] et la {xref-production-checklist}[liste de contrôle pour des clusters prêts pour la production].

[NOTE]
.Cluster uniquement IPv6
====
Pour un cluster uniquement IPv6, assurez-vous que votre système d'exploitation configure correctement le fichier `/etc/hosts`.

----
::1       localhost
----
====

[#_2_create_the_custom_cluster]
=== 2. Créer le cluster personnalisé

. Cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, cliquez sur *Créer*.
. Cliquez sur *Personnaliser*.
. Entrez un *Nom de cluster*.
. Utilisez la section *Configuration du cluster* pour configurer le cluster. Pour plus d'informations, consultez {xref-rke2-config}[Référence de configuration du cluster RKE2] et {xref-k3s-config}[Référence de configuration du cluster K3s].
+
[NOTE]
.Nœuds Windows
====
Pour en savoir plus sur l'utilisation des nœuds Windows en tant que nœuds de travail Kubernetes, consultez {xref-use-windows-clusters}[Lancement de Kubernetes sur des clusters Windows].
====
+
. Cliquez sur *Create*.
+
*Résultat :* L'interface utilisateur redirige vers la page *Inscription*, où vous pouvez générer la commande d'inscription pour vos nœuds.
+
. Dans *Rôle du nœud*, sélectionnez les rôles que vous souhaitez attribuer à un nœud de cluster. Vous devez provisionner au moins un nœud pour chaque rôle{nbsp}: etcd, nœud de travail et plan de contrôle. Un cluster personnalisé nécessite les trois rôles pour terminer le provisionnement. Pour plus d'informations sur les rôles, consultez {xref-k8s-concepts}#_roles_for_nodes_in_kubernetes_clusters[Rôles pour les nœuds dans les clusters Kubernetes].
+
[NOTE]
.Serveur en matériel sans système d'exploitation
====
Si vous prévoyez de dédier des serveurs en matériel sans système d'exploitation à chaque rôle, vous devez provisionner un serveur en matériel sans système d'exploitation pour chaque rôle (c'est-à-dire, provisionner plusieurs serveurs en matériel sans système d'exploitation).
====
+
. *Facultatives :* Cliquez sur *Afficher les options avancées* pour configurer des paramètres supplémentaires tels que spécifier l'adresse IP, remplacer le nom d'hôte du nœud ou ajouter https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[étiquettes] ou https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[taints] au nœud.
+
[NOTE]
====
* Les champs *IP publique du nœud* et *IP privée du nœud* peuvent accepter soit une seule adresse, soit une liste d'adresses séparées par des virgules (par exemple{nbsp}: `10.0.0.5,2001:db8::1`).
====
+
[NOTE]
.Cluster uniquement IPv6 ou à double pile
====
* Dans les clusters uniquement IPv6 et à double pile, vous devez spécifier l'*adresse IPv6* du nœud comme *IP privée du nœud*.
====
+
. Copiez la commande affichée à l'écran dans votre presse-papiers.
. Connectez-vous à votre hôte Linux en utilisant votre shell préféré, tel que PuTTy ou une connexion Terminal à distance. Exécutez la commande copiée dans votre presse-papiers.

[NOTE]
====
Répétez les étapes 7 à 10 si vous souhaitez dédier des hôtes spécifiques à des rôles de nœud spécifiques. Répétez les étapes autant de fois que nécessaire.
====

*Résultat :*

Le cluster est créé et passe à l'état *Mise à jour* pendant que Rancher initialise et provisionne les composants du cluster.

Vous pouvez accéder à votre cluster après que son état soit mis à jour à *Actif*.

Les clusters *Actifs* sont assignés à deux Projets{nbsp}:

* `Default`, contenant l'espace de noms `default`
* `System`, contenant les espaces de noms `cattle-system`, `traefik`, `kube-public` et `kube-system`

[#_3_amazon_only_tag_resources]
=== 3. Amazon uniquement{nbsp}: Ajouter des balises aux ressources

Si vous avez configuré votre cluster pour utiliser Amazon en tant que *fournisseur de cloud*, ajoutez une balise à vos ressources AWS avec un ID de cluster.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html[Documentation Amazon{nbsp}: Ajouter des balises à vos ressources Amazon EC2]

[NOTE]
====

Vous pouvez utiliser des instances Amazon EC2 sans configurer de fournisseur de cloud dans Kubernetes. Vous devez uniquement configurer le fournisseur de cloud si vous souhaitez utiliser des fonctionnalités spécifiques au fournisseur de cloud Kubernetes. Pour plus d'informations, voir https://github.com/kubernetes/website/blob/release-1.18/content/en/docs/concepts/cluster-administration/cloud-providers.md[Fournisseurs de cloud Kubernetes]
====


Les ressources suivantes doivent être balisées avec un `ClusterID`{nbsp}:

* *Nœuds*{nbsp}: Tous les hôtes ajoutés dans Rancher.
* *Sous-réseau*{nbsp}: Le sous-réseau utilisé pour votre cluster
* *Groupe de sécurité*{nbsp}: Le groupe de sécurité utilisé pour votre cluster.

[NOTE]
====

Ne balisez pas plusieurs groupes de sécurité. Baliser plusieurs groupes génère une erreur lors de la création de l'Elastic Load Balancer.
====


La balise qui doit être utilisée est{nbsp}:

----
Key=kubernetes.io/cluster/<CLUSTERID>, Value=owned
----

`<CLUSTERID>` peut être n'importe quelle chaîne que vous choisissez. Cependant, la même chaîne doit être utilisée sur chaque ressource que vous taguez. Définir la valeur de la balise à `owned` informe le cluster que toutes les ressources balisées avec le `<CLUSTERID>` sont possédées et gérées par ce cluster.

Si vous partagez des ressources entre des clusters, vous pouvez changer la balise en :

----
Key=kubernetes.io/cluster/CLUSTERID, Value=shared
----

[#_optional_next_steps]
== Étapes suivantes optionnelles

Après avoir créé votre cluster, vous pouvez y accéder via l'interface utilisateur de Rancher. En tant que meilleure pratique, nous recommandons de mettre en place ces méthodes alternatives pour accéder à votre cluster{nbsp}:

* *Accédez à votre cluster avec la CLI kubectl :* Suivez {xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[ces étapes] pour accéder aux clusters avec kubectl sur votre station de travail. Dans ce cas, vous serez authentifié via le proxy d'authentification du serveur Rancher, puis Rancher vous connectera au cluster en aval. Cette méthode vous permet de gérer le cluster sans l'interface utilisateur de Rancher.
* *Accédez à votre cluster avec la CLI kubectl, en utilisant le point de terminaison de cluster autorisé :* Suivez {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[ces étapes] pour accéder directement à votre cluster avec kubectl, sans vous authentifier via Rancher. Nous recommandons de mettre en place cette méthode alternative pour accéder à votre cluster afin que, dans le cas où vous ne pouvez pas vous connecter à Rancher, vous puissiez toujours accéder au cluster.
