= OpenLDAPの設定
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/configure-openldap/index.adoc 
:product-path: rancher-admin/users/authn-and-authz/openldap/openldap.adoc
ifeval::["{build-type}" != "community"]
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-openldap-reference: xref:rancher-admin/users/authn-and-authz/openldap/reference.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
:xref-openldap-reference: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/configure-openldap/openldap-config-reference.adoc
endif::[]

組織がユーザー認証にLDAPを使用している場合、Rancherを設定してOpenLDAPサーバーと通信し、ユーザーを認証することができます。これにより、Rancherの管理者は、組織のリポジトリで外部管理されているユーザーやグループに基づいて、クラスターやプロジェクトへのアクセスを制御でき、エンドユーザーはRancher UIにログインする際にLDAP資格情報で認証できます。

[#_prerequisites]
== 前提条件

Rancherは、アクセス権を持つユーザーやグループに関連するLDAPエントリを検索および取得するために、LDAPバインドアカウント（サービスアカウントとも呼ばれます）で構成する必要があります。この目的のために管理者アカウントや個人アカウントを使用せず、代わりに設定された検索ベースの下にあるユーザーやグループに対して読み取り専用アクセスを持つ専用アカウントをOpenLDAPで作成することをお勧めします（下記参照）。

____
*TLSを使用していますか？*

OpenLDAPサーバーで使用される証明書が自己署名であるか、認識された証明書機関からのものでない場合、CA証明書（中間証明書と連結されたもの）をPEM形式で手元に用意してください。この証明書を設定中に貼り付ける必要があるため、Rancherが証明書チェーンを検証できるようにします。
____

[#_configure_openldap_in_rancher]
== RancherでOpenLDAPを設定する

OpenLDAPサーバー、グループ、およびユーザーの設定を構成します。各フィールドの記入に関するヘルプについては、{xref-openldap-reference}[設定リファレンス]を参照してください。

____
設定を進める前に、{xref-authn-authz}#_external_authentication_configuration_and_principal_users[外部認証設定と主要ユーザー]の概念に慣れておいてください。
____

. 左上隅で、*☰ > ユーザーと認証*をクリックします。
. 左側のナビゲーションメニューで、*認証プロバイダー*をクリックします。
. *OpenLDAP*をクリックします。*OpenLDAPサーバーの設定*フォームに記入します。
. ［*有効］*をクリックします。

[#_test_authentication]
=== 認証のテスト

設定が完了したら、OpenLDAPサーバーへの接続をテストして進めてください。OpenLDAPによる認証は、テストが成功した場合に暗黙的に有効になります。

[NOTE]
====

このステップで入力された資格情報に関連するOpenLDAPユーザーは、ローカルの主要アカウントにマッピングされ、Rancherで管理者権限が付与されます。したがって、このステップを実行するために使用するLDAPアカウントについて、意識的な決定を下す必要があります。
====


. ローカルの主要アカウントにマッピングされるべきOpenLDAPアカウントの*ユーザー名*と*パスワード*を入力してください。
. *OpenLDAPで認証する*をクリックして、OpenLDAP接続をテストし、セットアップを完了してください。

*結果:*

* OpenLDAP認証が設定されました。
* 入力された資格情報に関連するLDAPユーザーは、ローカルの主要（管理）アカウントにマッピングされます。

[NOTE]
====

LDAPサービスが中断された場合でも、ローカルに設定された`admin`アカウントとパスワードを使用してログインすることができます。
====


[#_annex_troubleshooting]
== 付録：トラブルシューティング

OpenLDAPサーバーへの接続をテストしている際に問題が発生した場合は、サービスアカウントの資格情報と検索ベースの設定を再確認してください。問題の原因を特定するために、Rancherのログを確認することもできます。デバッグログには、エラーに関するより詳細な情報が含まれている場合があります。このドキュメントのxref:faq/technical-items.adoc#_how_can_i_enable_debug_logging[デバッグログを有効にする方法]を参照してください。
