= Normes de sécurité des pods (PSS) et admission de sécurité des pods (PSA)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/normes-de-sécurité-des-pods.adoc 
:product-path: security/psa-pss.adoc
ifeval::["{build-type}" != "community"]
:xref-psact: xref:security/psact.adoc
:xref-sample-psact: xref:security/sample-psact.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-psact: xref:how-to-guides/nouveaux-utilisateurs/guide-d'authentification-permissions-et-configuration-globale/psa-modèles-de-configuration.adoc
:xref-sample-psact: xref:reference-guides/rancher-security/psa-restricted-exemptions.adoc
endif::[]

https://kubernetes.io/docs/concepts/security/pod-security-standards/[Normes de sécurité des pods (PSS)] et https://kubernetes.io/docs/concepts/security/pod-security-admission/[admission de sécurité des pods (PSA)] définissent des restrictions de sécurité pour un large éventail de charges de travail.
Elles sont devenues disponibles et activées par défaut dans Kubernetes v1.23, et remplacent https://kubernetes.io/docs/concepts/security/pod-security-policy/[les politiques de sécurité des pods (PSP)] dans Kubernetes v1.25 et versions ultérieures.

Les PSS définissent des niveaux de sécurité pour les charges de travail. Les PSA décrivent les exigences pour les contextes de sécurité des pods et les champs associés. Les PSA font référence aux niveaux PSS pour définir des restrictions de sécurité.

[#_pod_security_admission_configuration_templates]
== Modèles de configuration d'admission de sécurité des pods

Rancher propose des modèles de configuration PSA. Ce sont des configurations de sécurité prédéfinies que vous pouvez appliquer à un cluster. Les administrateurs Rancher (ou ceux ayant les autorisations appropriées) peuvent {xref-psact}[créer, gérer et modifier] des modèles PSA.

[#_rancher_on_psa_restricted_clusters]
=== Rancher sur des clusters restreints par PSA

Les espaces de noms système de Rancher sont également affectés par les politiques de sécurité restrictives décrites par les modèles PSA. Vous devez exempter les espaces de noms système de Rancher après avoir assigné le modèle, sinon le cluster ne fonctionnera pas correctement. Voir {xref-psact}#_exempting_required_rancher_namespaces[Modèles de configuration de l'admission de sécurité des pods (PSA)] pour plus de détails.

Pour un fichier complet contenant toutes les exemptions nécessaires pour exécuter Rancher, veuillez vous référer à cet {xref-sample-psact}[exemple de configuration d'admission].
