= {rancher-product-name} Guides de sécurité
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-01-20
:page-revdate: {revdate}
:community-path: reference-guides/rancher-security/index.adoc 
:product-path: security/security-overview.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rbac: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/gerer-le-controle-d-acces-en-fonction-du-role-rbac.adoc
:xref-compliance-scans-howto: xref:security/compliance-scans/how-to.adoc
:xref-selinux-rpm: xref:security/selinux-rpm/selinux-rpm.adoc
:xref-neuvector: xref:integrations/neuvector/neuvector.adoc
:xref-cves: xref:security/cves.adoc
:xref-security-best-practices: xref:security/rancher-security-best-practices.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rbac: xref:how-to-guides/nouveaux-utilisateurs/autorisations-d'authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/index.adoc
:xref-compliance-scans-howto: xref:how-to-guides/advanced-user-guides/compliance-scan-guides/index.adoc
:xref-selinux-rpm: xref:reference-guides/rancher-security/selinux-rpm/index.adoc
:xref-neuvector: xref:integrations-in-rancher/neuvector/index.adoc
:xref-cves: xref:reference-guides/rancher-security/security-advisories-and-cves.adoc
:xref-security-best-practices: xref:reference-guides/rancher-security/rancher-security-best-practices.adoc
endif::[]

[pass]
<table width="100%">
  <tr style="vertical-align: top;text-align: center;border-bottom-style: none;border-top-style: solid;border-top-width: 2px;border-top-color: #c0c2c4;">
    <td width="30%">
      <h4>Stratégie de sécurité</h4><br/>
      <p style="{{padding:" mem-invalid-attributes-holder='8px'}}>Rancher Labs soutient la divulgation responsable et s'efforce de résoudre tous les problèmes dans un délai raisonnable. </p>
    </td>
    <td width="30%">
      <h4>Processus de signalement</h4><br/>
      <p style="{{padding:" mem-invalid-attributes-holder='8px'}}>Veuillez soumettre les problèmes de sécurité éventuels en envoyant un e-mail à <a href="mailto:security-rancher@suse.com">security-rancher@suse.com</a>.</p>
    </td>
    <td width="30%">
      <h4>Annonces</h4><br/>
      <p style={{padding:'8px'}}>Abonnez-vous au <a href="https://forums.rancher.com/c/announcements">forum des annonces Rancher</a> pour les mises à jour de version.</p>
    </td>
  </tr>
</table>

La sécurité est au cœur de toutes les fonctionnalités de Rancher. De l'intégration avec tous les outils et services d'authentification populaires, à une capacité {xref-manage-rbac}[RBAC de niveau entreprise], Rancher rend vos clusters Kubernetes encore plus sécurisés.

Sur cette page, nous fournissons une documentation liée à la sécurité ainsi que des ressources pour vous aider à sécuriser votre installation Rancher et vos clusters Kubernetes en aval.

[#__neuvector_product_name_integration_with_rancher]
== {neuvector-product-name} Intégration avec Rancher

NeuVector est une application de sécurité open-source, axée sur les conteneurs, qui est désormais intégrée à Rancher. NeuVector fournit une sécurité de production, une protection contre les vulnérabilités DevOps et un pare-feu pour conteneurs, entre autres. Veuillez consulter la {xref-neuvector}[documentation Rancher] et la https://documentation.suse.com/cloudnative/security/{neuvector-docs-version}/en/overview.html[{neuvector-product-name} documentation] pour plus d'informations.

[#_running_a_compliance_security_scan_on_a_kubernetes_cluster]
== Exécution d'une analyse de sécurité de conformité sur un cluster Kubernetes

Rancher utilise https://github.com/aquasecurity/kube-bench[kube-bench] pour exécuter une analyse de sécurité afin de vérifier si Kubernetes est déployé conformément aux meilleures pratiques de sécurité.

Lorsque Rancher exécute une analyse de conformité sur un cluster, il génère un rapport montrant les résultats de chaque test, y compris un résumé avec le nombre de tests réussis, ignorés et échoués. Le rapport comprend également des étapes de remédiation pour tout test échoué.

Pour plus de détails, reportez-vous à la section sur {xref-compliance-scans-howto}[les analyses de sécurité].

[#_selinux_rpm]
== SELinux RPM

Nous fournissons trois RPM (RPM Package Manager) qui permettent aux produits Rancher de fonctionner correctement sur des hôtes où SELinux est appliqué{nbsp}: `rancher-selinux`, `rke2-selinux` et `k3s-selinux`.  Pour plus de détails, voir {xref-selinux-rpm}[cette page].

[#_rancher_hardening_guide]
== Guide de renforcement de la sécurité de Rancher

Le Guide de renforcement de la sécurité de Rancher est basé sur des contrôles et des meilleures pratiques trouvés dans le https://www.cisecurity.org/benchmark/kubernetes/[Référentiel CIS Kubernetes] du Center for Internet Security.

Les guides de renforcement de la sécurité fournissent des conseils prescriptifs pour renforcer la sécurité d'une installation de production de Rancher. Voir les guides de Rancher pour <<_the_cis_benchmark_and_self_assessment,Auto-évaluation du Référentiel CIS Kubernetes>> pour la liste complète des contrôles de sécurité.

____
Les guides de renforcement de la sécurité décrivent comment sécuriser les nœuds de votre cluster, et il est recommandé de suivre un guide de renforcement de la sécurité avant d'installer Kubernetes.
____

Chaque version du guide de renforcement de la sécurité est destinée à être utilisée avec des versions spécifiques du Référentiel CIS Kubernetes, de Kubernetes et de Rancher.

[#_the_cis_benchmark_and_self_assessment]
== Le Référentiel CIS et l'Auto-évaluation

L'auto-évaluation du référentiel est un complément au guide de renforcement de la sécurité de Rancher. Alors que le guide de renforcement de la sécurité vous montre comment renforcer la sécurité du cluster, le guide de référence est destiné à vous aider à évaluer le niveau de sécurité du cluster renforcé.

Ce guide passe en revue les différents contrôles et fournit des exemples de commandes mises à jour pour auditer la conformité dans les clusters créés par Rancher. Les documents de référence originaux peuvent être téléchargés depuis le https://www.cisecurity.org/benchmark/kubernetes/[site web du CIS].

Chaque version du guide d'auto-évaluation de Rancher correspond à des versions spécifiques du guide de renforcement de la sécurité, de Rancher, de Kubernetes et du Référentiel CIS.

[#_third_party_penetration_test_reports]
== Rapports de tests de pénétration de tiers

Rancher engage périodiquement des tiers pour effectuer des audits de sécurité et des tests de pénétration de la pile logicielle Rancher. Les environnements testés suivent les guides de renforcement de la sécurité fournis par Rancher au moment des tests. Les rapports de tests de pénétration précédents sont disponibles ci-dessous.

Résultats :

* https://releases.rancher.com/documents/security/pen-tests/2019/RAN-01-cure53-report.final.pdf[Test de pénétration Cure53 - Juillet 2019]
* https://releases.rancher.com/documents/security/pen-tests/2019/UntamedTheory-Rancher_SecurityAssessment-20190712_v5.pdf[Test de pénétration Untamed Theory - Mars 2019]

Veuillez noter que les nouveaux rapports ne sont plus partagés ni rendus publics.

[#_rancher_security_advisories_and_cves]
== Avis de sécurité et CVEs de Rancher

Rancher s'engage à informer la communauté des problèmes de sécurité dans nos produits. Pour la liste des CVEs (Vulnérabilités et Expositions Communes) pour les problèmes que nous avons résolus, veuillez vous référer à {xref-cves}[cette page.]

[#_kubernetes_security_best_practices]
== Meilleures pratiques de sécurité Kubernetes

Pour des recommandations sur la sécurisation de votre cluster Kubernetes, veuillez vous référer au guide https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/[Meilleures pratiques de sécurité du cluster Kubernetes].

[#_rancher_security_best_practices]
== Meilleures pratiques de sécurité de Rancher

Pour des recommandations sur la sécurisation de vos déploiements Rancher Manager, veuillez vous référer au guide {xref-security-best-practices}[Meilleures pratiques de sécurité de Rancher].

[#_rancher_kubernetes_distributions_k3s_rke2_self_assessment_and_hardening_guides]
== Guides d'auto-évaluation et de renforcement de la sécurité des distributions Kubernetes de Rancher (K3s/RKE2)

Rancher utilise les distributions Kubernetes suivantes{nbsp}:

* https://documentation.suse.com/en-us/cloudnative/rke2/[*RKE2*] est une distribution Kubernetes parfaitement conforme axée sur la sécurité et la conformité au sein des États-Unis. secteur du gouvernement fédéral américain.
* https://documentation.suse.com/en-us/cloudnative/k3s/[*K3s*] est une distribution Kubernetes légère et parfaitement conforme. Elle est facile à installer, avec une exigence mémoire de moitié inférieure à celle de Kubernetes en amont, le tout dans un binaire de moins de 100 Mo.

Pour renforcer la sécurité d'un cluster Kubernetes fonctionnant avec une distribution autre que celles listées, veuillez vous référer à la documentation de votre fournisseur Kubernetes.

[#_hardening_guides_and_benchmark_versions]
=== Guides de renforcement de la sécurité et versions de référence

Chaque guide d'auto-évaluation est accompagné d'un guide de renforcement de la sécurité. Ces guides ont été testés avec les versions de Rancher listées. Chaque guide d'auto-évaluation a été testé sur une version spécifique de Kubernetes et une version de référence CIS. Si un benchmark CIS n'a pas été validé pour votre version de Kubernetes, vous pouvez utiliser les guides existants jusqu'à ce qu'un guide pour votre version soit ajouté.

[#_rke2_guides]
=== Guides RKE2

|===
| Type | Kubernetes Version | Version du référentiel CIS | Guide d'auto-évaluation | Guide de renforcement de la sécurité

| RKE2 autonome
| Kubernetes v1.27
| CIS v1.9
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment19.html[Lien]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Lien]

| RKE2 autonome
| Kubernetes v1.28
| CIS v1.10
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment110.html[Lien]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Lien]

| RKE2 autonome
| Kubernetes v1.29 et versions ultérieures
| CIS v1.11
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/cis_self_assessment111.html[Lien]
| https://documentation.suse.com/cloudnative/rke2/latest/en/security/hardening_guide.html[Lien]
|===

[#_k3s_guides]
=== Guides K3s

|===
| Type | Kubernetes Version | Version du référentiel CIS | Guide d'auto-évaluation | Guide de renforcement de la sécurité

| K3s autonome
| Kubernetes v1.27
| CIS v1.9
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.9.html[Lien]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Lien]

| K3s autonome
| Kubernetes v1.28
| CIS v1.10
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.10.html[Lien]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Lien]

| K3s autonome
| Kubernetes v1.29 et versions ultérieures
| CIS v1.11
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/self-assessment-1.11.html[Lien]
| https://documentation.suse.com/cloudnative/k3s/latest/en/security/hardening-guide.html[Lien]
|===
