= {rancher-product-name} Kurzanleitungen zur Implementierung
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/index.adoc 
:product-path: installation-and-upgrade/quick-start/quick-start.adoc
ifeval::["{build-type}" != "community"]
:xref-install-upgrade: xref:installation-and-upgrade/installation-and-upgrade.adoc
:xref-qs-deploy-workloads: xref:installation-and-upgrade/quick-start/deploy-workloads/deploy-workloads.adoc
:xref-qs-deploy-rancher: xref:installation-and-upgrade/quick-start/deploy-rancher/deploy-rancher.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-install-upgrade: xref:getting-started/installation-and-upgrade/index.adoc
:xref-qs-deploy-workloads: xref:getting-started/quick-start-guides/deploy-workloads/index.adoc
:xref-qs-deploy-rancher: xref:getting-started/quick-start-guides/deploy-rancher-manager/index.adoc
endif::[]

[CAUTION]
====

Ziel dieser Anleitungen ist es, schnell eine Sandbox zu starten, die Sie zur Evaluierung von Rancher verwenden können. Diese Anleitungen sind nicht für Produktionsumgebungen gedacht. Für umfassende setup-Anweisungen, siehe {xref-install-upgrade}[Installation].
====


Verwenden Sie diesen Abschnitt der Dokumentation, um Ihre Implementierung und Tests von Rancher 2.x zu starten. Er enthält Anweisungen für ein einfaches Rancher-Setup und einige gängige Anwendungsfälle. Wir planen, in Zukunft weitere Inhalte zu diesem Abschnitt hinzuzufügen.

Wir haben Kurzanleitungen für:

* {xref-qs-deploy-rancher}[Implementierung des Rancher-Servers]: Beginnen Sie mit der Ausführung von Rancher mit der für Sie bequemsten Methode.
* {xref-qs-deploy-workloads}[Bereitstellung von Workloads]: Stellen Sie ein einfaches https://kubernetes.io/docs/concepts/workloads/[workload] bereit und machen Sie es zugänglich, sodass Sie von außerhalb des Clusters darauf zugreifen können.
