= Creando un clúster GKE
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: instrucciones/nuevas-guías-de-usuario/clústeres-de-kubernetes-en-rancher/configurar-clústeres-a-partir-de-proveedores-kubernetes-alojados/gke.adoc 
:product-path: cluster-deployment/hosted-kubernetes/gke/gke.adoc
ifeval::["{build-type}" != "community"]
:xref-sync-hosted-clusters: xref:cluster-deployment/hosted-kubernetes/sync-clusters.adoc
:xref-gke-private-clusters: xref:cluster-deployment/hosted-kubernetes/gke/private-clusters.adoc
:xref-gke-config: xref:ampliación-de-clúster/kubernetes-alojado/gke/configuración.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-sync-hosted-clusters: xref:reference-guides/cluster-configuration/rancher-server-configuration/sync-clusters.adoc
:xref-gke-private-clusters: xref:guías-de-referencia/configuración-de-clúster/configuración-del-servidor-rancher/configuración-del-clúster-gke/clústeres-privados-gke.adoc
:xref-gke-config: xref:guías-de-referencia/configuración-de-clúster/configuración-del-servidor-rancher/configuración-del-clúster-gke/index.adoc
endif::[]

[#_prerequisites]
== Requisitos previos

Se requiere configuración en Google Kubernetes Engine.

[#_service_account_token]
=== Token de cuenta de servicio

Crea una cuenta de servicio utilizando https://console.cloud.google.com/projectselector/iam-admin/serviceaccounts[Google Kubernetes Engine]. GKE utiliza esta cuenta para operar tu clúster. Crear esta cuenta también genera una clave privada utilizada para la autenticación.

La cuenta de servicio requiere los siguientes roles:

* *Visor de Computación:* `roles/compute.viewer`
* *Visor de Proyecto:* `roles/viewer`
* *Administrador de Kubernetes Engine:* `roles/container.admin`
* *Usuario de Cuenta de Servicio:* `roles/iam.serviceAccountUser`

https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[Documentación de Google: Creación y Habilitación de Cuentas de Servicio]

Para obtener ayuda para obtener una clave privada para tu cuenta de servicio, consulta la documentación de Google Cloud https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys[aquí.] Necesitarás guardar la clave en formato JSON.

[#_google_project_id]
=== Google Project ID

Tu clúster deberá formar parte de un Proyecto de Google.

Para crear un nuevo proyecto, consulta la documentación de Google Cloud https://cloud.google.com/resource-manager/docs/creating-managing-projects#creating_a_project[aquí.]

Para obtener el ID del proyecto de un proyecto existente, consulta la documentación de Google Cloud https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects[aquí.]

[#_provisioning_a_gke_cluster]
== Provisionamiento de un Clúster GKE

[CAUTION]
====

Desplegar en GKE generará cargos.
====


[#_1_create_a_cloud_credential]
=== 1. Crear una Credencial de Nube

. Haz clic en *☰ > Gestión de Clústeres*.
. En la barra de navegación izquierda, haz clic en *Credenciales de Nube*.
. Haga clic en *Crear*.
. Introduce un nombre para tus credenciales de Google Cloud.
. En el cuadro de texto *Cuenta de Servicio*, pega tu clave privada JSON de la cuenta de servicio o sube el archivo JSON.
. Haga clic en *Crear*.

*Resultado:* Has creado credenciales que Rancher utilizará para provisionar el nuevo clúster GKE.

[#_2_create_the_gke_cluster]
=== 2. Crear el Clúster GKE

Utiliza Rancher para instalar y configurar tu clúster de Kubernetes. Para crear con éxito un clúster GKE con Rancher, tu GKE debe estar en modo Estándar. GKE tiene dos modos de operación al crear un clúster de Kubernetes, Modo Autopilot y Modo Estándar. La configuración del clúster para el modo Autopilot tiene restricciones sobre la edición del espacio de nombres kube-system. Sin embargo, Rancher necesita crear recursos en el espacio de nombres kube-system durante la instalación. Como resultado, no podrás crear un clúster GKE en modo Autopilot. Para más información sobre la diferencia entre el modo Autopilot de GKE y el modo Estándar, visita https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison[Compara GKE Autopilot y Estándar.]

. Haz clic en *☰ > Gestión de Clústeres*.
. En la página *Clústeres*, haz clic en *Crear*.
. Click *Google GKE*.
. Introduce un *Nombre del Clúster*.
. Opcional: Utiliza *Roles de Miembros* para configurar la autorización de usuarios para el clúster. Haz clic en *Añadir Miembro* para añadir usuarios que puedan acceder al clúster. Utiliza el menú desplegable *Rol* para establecer permisos para cada usuario.
. Opcional: Añade https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[etiquetas] o https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/[anotaciones] de Kubernetes al clúster.
. Introduce tu ID de proyecto de Google y tus credenciales de Google Cloud.
. Completa el resto del formulario. Para obtener ayuda, consulta la {xref-gke-config}[referencia de configuración del clúster GKE.]
. Haga clic en *Crear*.

*Resultado:* Has desplegado con éxito un clúster GKE.

Tu clúster se ha creado y se le ha asignado un estado de *Provisionando*. Rancher está configurando tu clúster.

Puedes acceder a tu clúster después de que su estado se actualice a *Activo*.

Los clústeres *Activos* están asignados a dos Proyectos:

* `Default`, que contiene el espacio de nombres `default`
* `System`, que contiene los espacios de nombres `cattle-system`, `traefik`, `kube-public` y `kube-system`

[#_private_clusters]
== Clústeres privados

Se admiten clústeres GKE privados. Nota: Esta configuración avanzada puede requerir más pasos durante el proceso de provisionamiento del clúster. Para más detalles, consulta {xref-gke-private-clusters}[esta sección.]

[#_configuration_reference]
== Referencia de configuración

Para detalles sobre la configuración de clústeres GKE en Rancher, consulta {xref-gke-config}[esta página.]

[#_updating_kubernetes_version]
== Actualizando la Versión de Kubernetes

La versión de Kubernetes de un clúster se puede actualizar a cualquier versión disponible en la región o zona para el clúster GKE. Actualizar la versión maestra de Kubernetes no actualiza automáticamente los nodos trabajadores. Los nodos se pueden actualizar de forma independiente.

[NOTE]
====

GKE ha eliminado la autenticación básica en 1.19+. Para actualizar un clúster a 1.19+, la autenticación básica debe ser desactivada en Google Cloud. De lo contrario, aparecerá un error en Rancher cuando se intente una actualización a 1.19+. Puedes seguir la https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#disabling_authentication_with_a_static_password[documentación de Google]. Después de esto, la versión de Kubernetes se puede actualizar a 1.19+ a través de Rancher.
====


[#_syncing]
== Sincronizando

El aprovisionador de GKE puede sincronizar el estado de un clúster de GKE entre Rancher y el proveedor. Para una explicación técnica detallada de cómo funciona esto, consulta {xref-sync-hosted-clusters}[Sincronizando.]

Para información sobre cómo configurar el intervalo de actualización, consulta {xref-gke-config}#_configuring_the_refresh_interval[esta sección.]

[#_programmatically_creating_gke_clusters]
== Creación programática de clústeres de GKE

La forma más común de desplegar programáticamente clústeres de GKE a través de Rancher es utilizando el proveedor de Terraform Rancher2. La documentación para crear clústeres con Terraform está https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster[aquí.]
