= 在隔离的环境中升级
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-04-22
:page-revdate: {revdate}
:community-path: getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/air-gapped-upgrades.adoc 
:product-path: installation-and-upgrade/other-installation-methods/air-gapped/upgrades.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-upgrades: xref:installation-and-upgrade/upgrades.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-upgrades: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades.adoc
endif::[]

[NOTE]
====

这些说明假设您已经按照{xref-rancher-upgrades}[此页面]上的Kubernetes升级说明进行了操作，包括先决条件，直到第3步。升级 Rancher。
====


[#_rancher_helm_upgrade_options]
== Rancher Helm 升级选项

要使用 Helm 升级，请应用安装 Rancher 时使用的相同选项。请参考下面的参考表以替换每个占位符。Rancher 需要配置为使用私有注册表，以便为任何 Rancher 启动的 Kubernetes 集群或 Rancher 工具提供服务。

根据您在安装过程中做出的选择，完成以下其中一个程序。

|===
| 占位符 | 说明

| `<VERSION>`
| 输出的 tarball 文件的版本号。

| `<RANCHER.YOURDOMAIN.COM>`
| 您为负载均衡器指定的 DNS 名称

| `<REGISTRY.YOURDOMAIN.COM:PORT>`
| 您的私有注册表的 DNS 名称

| `<CERTMANAGER_VERSION>`
| 在 k8s 集群上运行的 Cert-manager 版本。
|===

[#_option_a_default_self_signed_certificate]
=== 选项 A：默认自签名证书

----
helm upgrade rancher ./rancher-<VERSION>.tgz \
    --namespace cattle-system \
    --set hostname=<RANCHER.YOURDOMAIN.COM> \
    --set certmanager.version=<CERTMANAGER_VERSION> \
    --set image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ # 设置 Rancher 中使用的默认私有注册表
    --set useBundledSystemChart=true # 使用打包的 Rancher 系统图表
----

[#_resolving_upgrade_failed_error]
==== 解决 UPGRADE FAILED 错误

如果您遇到错误消息 `Error: UPGRADE FAILED: "rancher" has no deployed releases`，Rancher 可能是通过 `helm template` 命令安装的。要成功升级 Rancher，请改用以下命令：

----
helm template rancher ./rancher-<VERSION>.tgz --output-dir . \
    --no-hooks \ # prevent files for Helm hooks from being generated
    --namespace cattle-system \
    --set hostname=<RANCHER.YOURDOMAIN.COM> \
    --set certmanager.version=<CERTMANAGER_VERSION> \
    --set image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ # Set a default private registry to be used in Rancher
    --set useBundledSystemChart=true # Use the packaged Rancher system charts
----

在您运行 Helm 命令后，应用渲染的模板：

----
kubectl -n cattle-system apply -R -f ./rancher
----

[#_option_b_certificates_from_files_using_kubernetes_secrets]
=== 选项 B：使用 Kubernetes Secrets 从文件中获取证书

[,plain]
----
helm upgrade rancher ./rancher-<VERSION>.tgz \
    --namespace cattle-system \
    --set hostname=<RANCHER.YOURDOMAIN.COM> \
    --set image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set ingress.tls.source=secret \
    --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ # Set a default private registry to be used in Rancher
    --set useBundledSystemChart=true # Use the packaged Rancher system charts
----

如果您使用的是私有 CA 签名的证书，请在 `--set privateCA=true` 后添加 `--set ingress.tls.source=secret`：

[,plain]
----
helm upgrade rancher ./rancher-<VERSION>.tgz \
    --namespace cattle-system \
    --set hostname=<RANCHER.YOURDOMAIN.COM> \
    --set image.registry=<REGISTRY.YOURDOMAIN.COM:PORT> \
    --set ingress.tls.source=secret \
    --set privateCA=true \
    --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ # Set a default private registry to be used in Rancher
    --set useBundledSystemChart=true # Use the packaged Rancher system charts
----

[#_verify_the_upgrade]
== 验证升级

登录 Rancher 以确认升级成功。

[TIP]
====

升级后遇到网络问题？

请参见 xref:[恢复集群网络]。
====


[#_known_upgrade_issues]
== 已知升级问题

每个 Rancher 版本的已知问题列表可以在 https://github.com/rancher/rancher/releases[GitHub] 的发布说明和 https://forums.rancher.com/c/announcements/12[Rancher 论坛] 中找到。
