= Role-based Access Control
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/rbac-for-istio.adoc 
:page-product-path: observability/istio/rbac.adoc

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] has been deprecated since Rancher v2.12.0; turn to the https://apps.rancher.io[SUSE Application Collection] build of Istio for enhanced security (included in SUSE Rancher Prime subscriptions).
Detailed information can be found in https://forums.suse.com/t/deprecation-of-rancher-istio/45043[this announcement].
====

This section describes the permissions required to access Istio features.

The rancher istio chart installs three `ClusterRoles`

[#_cluster_admin_access]
== Cluster-Admin Access

By default, only those with the `cluster-admin` `ClusterRole` can:

* Install istio app in a cluster
* Configure resource allocations for Istio

[#_admin_and_edit_access]
== Admin and Edit access

By default, only Admin and Edit roles can:

* Enable and disable Istio sidecar auto-injection for namespaces
* Add the Istio sidecar to workloads
* View the traffic metrics and traffic graph for the cluster
* Configure Istio's resources (such as the gateway, destination rules, or virtual services)

[#_summary_of_default_permissions_for_kubernetes_default_roles]
== Summary of Default Permissions for Kubernetes Default roles

Istio creates three `ClusterRoles` and adds Istio CRD access to the following default K8s `ClusterRole`:

[cols=">,>,>"]
|===
| ClusterRole create by chart | Default K8s ClusterRole | Rancher Role

| `istio-admin`
| admin
| Project Owner

| `istio-edit`
| edit
| Project Member

| `istio-view`
| view
| Read-only
|===

Rancher will continue to use cluster-owner, cluster-member, project-owner, project-member, etc as role names, but will utilize default roles to determine access. For each default K8s `ClusterRole` there are different Istio CRD permissions and K8s actions (Create ( C ), Get ( G ), List ( L ), Watch ( W ), Update ( U ), Patch ( P ), Delete( D ), All ( * )) that can be performed.

[cols="2,1,1,1"]
|===
| CRDs | Admin | Edit | View

a| * ``config.istio.io``
** ``adapters``
** ``attributemanifests``
** ``handlers``
** ``httpapispecbindings``
** ``httpapispecs``
** ``instances``
** ``quotaspecbindings``
** ``quotaspecs``
** ``rules``
** ``templates``
| GLW
| GLW
| GLW

a| * ``networking.istio.io``
** ``destinationrules``
** ``envoyfilters``
** ``gateways``
** ``serviceentries``
** ``sidecars``
** ``virtualservices``
** ``workloadentries``
| *
| *
| GLW

a| * ``security.istio.io``
** ``authorizationpolicies``
** ``peerauthentications``
** ``requestauthentications``
| *
| *
| GLW
|===
