= Melhores práticas para {rancher-product-name} clusters VMware vSphere gerenciados
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/best-practices/rancher-managed-clusters/rancher-managed-clusters-in-vsphere.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/best-practices.adoc

Este guia descreve uma arquitetura de referência para provisionar clusters Rancher downstream em um ambiente vSphere, além das melhores práticas padrão do vSphere conforme documentado pela VMware.

* <<_1_vm_considerations,1. Considerações sobre VMs>>
* <<_2_network_considerations,2. Considerações sobre Rede>>
* <<_3_storage_considerations,3. Considerações sobre Armazenamento>>
* <<_4_backups_and_disaster_recovery,4. Backups e Recuperação de Desastres>>

.Visão geral da solução
image::solution_overview.drawio.svg[Visão Geral da Solução]

[#_1_vm_considerations]
== 1. Considerações sobre VMs

[#_leverage_vm_templates_to_construct_the_environment]
=== Utilize Modelos de VM para Construir o Ambiente

Para facilitar a consistência entre as máquinas virtuais implantadas no ambiente, considere o uso de "imagens douradas" na forma de modelos de VM. O Packer pode ser usado para realizar isso, adicionando mais opções de personalização.

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_downstream_cluster_nodes_across_esxi_hosts]
=== Utilize as regras de anti-afinidade do DRS (quando possível) para separar os nós do cluster downstream entre hosts ESXi.

Fazer isso garantirá que as VMs dos nós sejam distribuídas entre vários hosts ESXi - prevenindo um único ponto de falha no nível do host.

[#_leverage_drs_anti_affinity_rules_where_possible_to_separate_downstream_cluster_nodes_across_datastores]
=== Utilize as regras de anti-afinidade do DRS (quando possível) para separar os nós do cluster downstream entre datastores.

Fazer isso garantirá que as VMs dos nós sejam distribuídas entre vários datastores - prevenindo um único ponto de falha no nível do datastore.

[#_configure_vms_as_appropriate_for_kubernetes]
=== Configure as VMs conforme apropriado para o Kubernetes

É importante seguir as melhores práticas do K8s e etcd ao implantar seus nós, incluindo desabilitar swap, verificar se você tem conectividade de rede total entre todas as máquinas no cluster, usando nomes de host, endereços MAC e product_uuids exclusivos para cada nó.

[#_2_network_considerations]
== 2. Considerações sobre Rede

[#_leverage_low_latency_high_bandwidth_connectivity_between_etcd_nodes]
=== Utilize a conectividade de baixa latência e alta largura de banda entre os nós do ETCD

Implante membros do etcd dentro de um único data center sempre que possível para evitar sobrecargas de latência e reduzir a probabilidade de particionamento de rede. Para a maioria das configurações, conexões de 1 Gb serão suficientes. Para clusters grandes, conexões de 10 Gb podem reduzir o tempo necessário para restaurar a partir do backup.

[#_consistent_ip_addressing_for_vms]
=== Endereçamento IP consistente para as VMs

Cada nó utilizado deve ter um IP estático configurado. No caso de DHCP, cada nó deve ter uma reserva de DHCP para garantir que o nó receba o mesmo IP alocado.

[#_3_storage_considerations]
== 3. Considerações sobre Armazenamento

[#_leverage_ssd_drives_for_etcd_nodes]
=== Utilize discos SSD para os nós do etcd

O etcd é muito sensível à latência de gravação. Portanto, aproveite discos SSD sempre que possível.

[#_4_backups_and_disaster_recovery]
== 4. Backups e Recuperação de Desastres

[#_perform_regular_downstream_cluster_backups]
=== Realize backups regulares do cluster downstream.

O Kubernetes usa o etcd para armazenar todos os seus dados - desde configuração, estado e metadados. Fazer backup disso é crucial em caso de recuperação de desastres.

[#_back_up_downstream_node_vms]
=== Faça backup das VMs dos nós downstream

Incorpore as VMs dos nós downstream do Rancher dentro de uma política padrão de backup de VMs.
