= Configuração do Modelo de Nó do VMware vSphere
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guias-de-referência/configuração-do-cluster/configuração-do-cluster-downstream/configuração-do-modelo-de-nó/vsphere.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/node-template-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
endif::[]

[#_account_access]
== Acesso à Conta

[cols="<,^,<"]
|===
| Parâmetro | Obrigatória | Descrição

| Credenciais de Nuvem
| *
| As informações de acesso da sua conta vSphere, armazenadas em uma {xref-cloud-credentials}[credencial de nuvem.]
|===

Sua credencial de nuvem possui os seguintes campos:

|===
| Campo da Credencial | Descrição

| vCenter or ESXi Server
| Digite o hostname/IP do vCenter ou ESXi. ESXi é a plataforma de virtualização onde você cria e executa máquinas virtuais e aplicações virtuais. O vCenter Server é o serviço através do qual você gerencia múltiplos hosts conectados em uma rede e agrupa os recursos dos hosts.

| Portar
| Configure a porta do servidor vCenter ou ESXi.

| Nome de usuário e senha
| Digite seu nome de usuário e senha de login do vSphere.
|===

[#_scheduling]
== Programação

Escolha qual hipervisor a máquina virtual será agendada.

Os campos na seção *Agendamento* devem ser preenchidos automaticamente com o data center e outras opções de agendamento que estão disponíveis para você no vSphere.

|===
| Campo | Obrigatória | Explicação

| Data center
| *
| Escolha o nome/caminho do data center onde a VM será agendada.

| Pool de recursos
|
| Nome do pool de recursos para agendar as VMs. Pools de recursos podem ser usados para particionar os recursos de CPU e memória disponíveis de um host autônomo ou cluster, e também podem ser aninhados. Deixe em branco para ESXi autônomo. Se não especificado, o pool de recursos padrão é utilizado.

| Data Store
| *
| Se você tiver um cluster de armazenamento, pode alternar o campo *Armazenamento*. Isso permite que você selecione um cluster de armazenamento onde sua VM será agendada. Se o campo não estiver alternado, você pode selecionar um disco individual.

| Pasta
|
| Nome de uma pasta no datacenter para criar as VMs. Deve já existir. As pastas de VM neste menu suspenso correspondem diretamente às suas pastas de VM no vSphere. O nome da pasta deve ser precedido por `vm/` no seu arquivo de configuração do vSphere.

| Host
|
| O IP do sistema host para agendar VMs. Deixe este campo em branco para um ESXi autônomo ou para um cluster com DRS (Distributed Resource Scheduler). Se especificado, o pool do sistema host será utilizado e o parâmetro *Pool de recursos* será ignorado.

| Tempo limite para desligamento gracioso
|
| A quantidade de tempo, em segundos, que o Rancher espera antes de excluir máquinas virtuais em um cluster. Se definido como `0`, o desligamento gracioso está desativado. Aceita apenas valores inteiros.
|===

[#_instance_options]
== Opções de Instância

Na seção *Instance Options*, configure o número de vCPUs, memória e tamanho do disco para as VMs criadas por este modelo.

[cols="<,^,<"]
|===
| Parâmetro | Obrigatória | Descrição

| CPUs
| *
| Número de vCPUs a serem atribuídos às VMs.

| Memória
| *
| Quantidade de memória a ser atribuída às VMs.

| Disco
| *
| Tamanho do disco (em MB) a ser anexado às VMs.

| Método de criação
| *
| O método para configurar um sistema operacional no nó. O sistema operacional pode ser instalado a partir de um ISO ou de um modelo de VM. Dependendo do método de criação, você também terá que especificar um modelo de VM, biblioteca de conteúdo, VM existente ou ISO. Para mais informações sobre métodos de criação, consulte <<_about_vm_creation_methods,About VM Creation Methods.>>

| Cloud Init
|
| URL de um arquivo `cloud-config.yml` ou URL para provisionar VMs. Este arquivo permite uma personalização adicional do sistema operacional, como configuração de rede, servidores DNS ou daemons do sistema. O sistema operacional deve suportar `cloud-init`.

| Redes
|
| Nome(s) da rede para conectar a VM.

| Parâmetros de configuração usados para guestinfo
|
| Parâmetros de configuração adicionais para as VMs. Estes correspondem às https://kb.vmware.com/s/article/1016098[Configurações Avançadas] no console do vSphere. Exemplos de casos de uso incluem fornecer parâmetros https://rancher.com/docs/os/v1.x/en/installation/cloud/vmware-esxi/#vmware-guestinfo[guestinfo] do RancherOS ou habilitar UUIDs de disco para as VMs (`disk.EnableUUID=TRUE`).
|===

[#_about_vm_creation_methods]
=== Sobre Métodos de Criação de VM

No campo *Método de Criação*, configure o método usado para provisionar VMs no vSphere. As opções disponíveis incluem criar VMs que inicializam a partir de uma ISO do RancherOS ou criar VMs clonando de uma máquina virtual existente ou https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-F7BF0E6B-7C4F-4E46-8BBF-76229AEA7220.html[modelo de VM].

A VM ou modelo existente pode usar qualquer sistema operacional Linux moderno que esteja configurado com suporte para https://cloudinit.readthedocs.io/en/latest/[cloud-init] usando a https://canonical-cloud-init.readthedocs-hosted.com/en/latest/reference/datasources/nocloud.html[fonte de dados NoCloud].

Escolha a forma como a VM será criada:

* *Implantar a partir de modelo: Data Center:* Escolha um modelo de VM que exista no data center que você selecionou.
* *Implantar a partir de modelo: Biblioteca de Conteúdo:* Primeiro, selecione a https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-254B2CE8-20A8-43F0-90E8-3F6776C2C896.html[Biblioteca de Conteúdo] que contém seu modelo, depois selecione o modelo da lista populada *Modelos da biblioteca*.
* *Clonar uma máquina virtual existente:* No campo *Máquina virtual*, escolha uma VM existente da qual a nova VM será clonada.
* *Instalar a partir da ISO do boot2docker:* Certifique-se de que o campo *URL da ISO do SO* contenha a URL de uma versão ISO do VMware para o RancherOS (`rancheros-vmware.iso`). Observe que esta URL deve ser acessível a partir dos nós que executam sua instalação do servidor Rancher.

[#_networks]
== Redes

O modelo de nó agora permite que uma VM seja provisionada com várias redes. No campo *Redes*, você pode agora clicar em *Adicionar Rede* para adicionar quaisquer redes disponíveis para você no vSphere.

[#_node_tags_and_custom_attributes]
== Tags de Nó e Atributos Personalizados

As tags permitem que você anexe metadados a objetos no inventário do vSphere para facilitar a classificação e a busca por esses objetos.

Para tags, todas as suas tags do vSphere aparecerão como opções para selecionar em seu modelo de nó.

Nos atributos personalizados, o Rancher permitirá que você selecione todos os atributos personalizados que você já configurou no vSphere. Os atributos personalizados são chaves e você pode inserir valores para cada um deles.

[NOTE]
====

Atributos personalizados são um recurso legado que eventualmente será removido do vSphere.
====


[#_cloud_init]
== cloud-init

https://cloudinit.readthedocs.io/en/latest/[Cloud-init] permite que você inicialize seus nós aplicando configuração na primeira inicialização. Isso pode envolver coisas como criar usuários, autorizar chaves SSH ou configurar a rede.

Para utilizar a inicialização do cloud-init, crie um arquivo de configuração de nuvem usando a sintaxe YAML válida e cole o conteúdo do arquivo no campo *Cloud Init*. Consulte a https://cloudinit.readthedocs.io/en/latest/topics/examples.html[documentação do cloud-init.] para um conjunto comentado de exemplos de diretivas de configuração de nuvem suportadas.

Observe que o cloud-init não é suportado ao usar o método de criação de ISO.

[#_engine_options]
== Opções de Motor

Na seção *Opções de Motor* do modelo de nó, você pode configurar o daemon de contêiner. Você pode querer especificar a versão do contêiner ou um espelho de registro de imagem de contêiner.

[NOTE]
====
Se você estiver provisionando nós do Red Hat Enterprise Linux (RHEL) ou CentOS, deixe o campo *URL de instalação do Docker* como o valor padrão ou selecione *nenhum*. Isso ignorará uma verificação para a instalação do Docker, já que o Docker já está instalado nesses tipos de nós.

Se você definir *URL de instalação do Docker* para um valor diferente do padrão ou *nenhum*, pode ver uma mensagem de erro como a seguinte: `Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`
====

