= Provisionamento de Clusters Kubernetes no VMware vSphere
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: procedimentos/novos-guias-de-usuário/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/vsphere/provisionar-clusters-kubernetes-no-vsphere.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/provision-kubernetes-clusters-in-vsphere.adoc
:experimental:
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-node-reqs: xref:cluster-deployment/node-requirements.adoc
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-vsphere-node-template-config: xref:cluster-deployment/infra-providers/vsphere/node-template-configuration.adoc
:xref-vsphere-create-credentials: xref:cluster-deployment/infra-providers/vsphere/create-credentials.adoc
:xref-persistent-storage-examples: xref:cluster-admin/manage-clusters/persistent-storage/examples/examples.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-node-reqs: xref:como-fazer/guias-para-novos-usuários/cluster-kubernetes-na-configuração-do-rancher/requisitos-dos-nós-para-clusters-gerenciados-pelo-rancher.adoc
:xref-rke2-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-rke2.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:procedimentos/novos-guias-de-usuário/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/index.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:procedimentos/novos-guias-de-usuário/configuração-de-clusters-kubernetes-no-rancher/configurar-provedores-de-nuvem/configurar-vsphere-fora-da-arvore.adoc
:xref-cloud-provider-vsphere: xref:procedimentos/novos-guias-de-usuário/configuração-de-clusters-kubernetes-no-rancher/configurar-provedores-de-nuvem/configurar-vsphere-na-arvore.adoc
:xref-k3s-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/configuração-do-cluster-k3s.adoc
:xref-vsphere-node-template-config: xref:guias-de-referência/configuração-do-cluster/configuração-do-cluster-downstream/configuração-do-modelo-de-nó/vsphere.adoc
:xref-vsphere-create-credentials: xref:procedimentos/novos-guias-de-usuário/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/vsphere/criar-credenciais.adoc
:xref-persistent-storage-examples: xref:how-to-guides/new-user-guides/manage-clusters/provisioning-storage-examples/index.adoc
endif::[]

Nesta seção, você aprenderá como usar o Rancher para implantar um {url-rke2-landing-page}[RKE2] ou {url-k3s-landing-page}[K3s] cluster Kubernetes no VMware vSphere.

Primeiro, você configura suas credenciais de nuvem vSphere no Rancher.

Em seguida, você cria um cluster vSphere no Rancher e, ao configurar o novo cluster, define pools de máquinas para ele. Cada pool de máquinas tem um papel Kubernetes: etcd, plano de controle ou worker. O Rancher instala o Kubernetes nos novos nós e configura cada nó com o papel Kubernetes definido pelo pool de máquinas.

* <<_preparation_in_vmware_vsphere,Preparação no vSphere>>
* <<_creating_a_vmware_vsphere_cluster,Criando um Cluster vSphere>>

[#_preparation_in_vmware_vsphere]
== Preparação no VMware vSphere

Esta seção descreve os requisitos para configurar o vSphere de modo que o Rancher possa provisionar VMs e clusters.

[#_create_credentials_in_vmware_vsphere]
=== Criar Credenciais no VMware vSphere

Antes de prosseguir para criar um cluster, você deve garantir que possui um usuário do vSphere com permissões suficientes.

Consulte este {xref-vsphere-create-credentials}[guia prático] para instruções sobre como criar um usuário no vSphere com as permissões necessárias. Esses passos resultam em um nome de usuário e senha que você precisará fornecer ao Rancher, o que permite que o Rancher provisione recursos no vSphere.

[#_network_permissions]
=== Permissões de Rede

Deve-se garantir que os hosts executando o servidor Rancher consigam estabelecer as seguintes conexões de rede:

* Para a API do vSphere no servidor vCenter (geralmente na porta 443/TCP).
* Para a API do Host (porta 443/TCP) em todos os hosts ESXi usados para instanciar máquinas virtuais para os clusters (_somente necessário ao usar o método de criação de ISO_).
* Para a porta 22/TCP e 2376/TCP nas VMs criadas

Veja {xref-node-reqs}#_networking_requirements[Requisitos de Rede dos Nós] para uma lista detalhada dos requisitos de porta aplicáveis à criação de nós em um provedor de infraestrutura.

[#_valid_esxi_license_for_vmware_vsphere_api_access]
=== Licença ESXi Válida para Acesso à API do VMware vSphere

A licença ESXi gratuita não suporta acesso à API. Os servidores vSphere devem ter uma licença ESXi válida ou de avaliação.

[#_vm_vm_affinity_rules_for_clusters_with_drs]
=== Regras de Afinidade VM-VM para Clusters com DRS

Se você tiver um cluster com DRS habilitado, é recomendável configurar https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-7297C302-378F-4AF2-9BD6-6EDB1E0A850A.html[Regras de Afinidade VM-VM]. Essas regras permitem que VMs atribuídas aos papéis etcd e plano de controle operem em hosts ESXi separados quando atribuídas a diferentes pools de nós. Essa prática garante que a falha de uma única máquina física não afete a disponibilidade desses planos.

[#_creating_a_vmware_vsphere_cluster]
== Criando um Cluster VMware vSphere

[#_1_create_your_cloud_credentials]
=== 1. Crie suas credenciais de nuvem

. Clique em *☰ > Gerenciamento de Cluster*.
. Clique em *Credenciais de Nuvem*.
. Clique em *Criar*.
. Clique em *VMware vSphere*.
. Insira suas credenciais do vSphere. Para ajuda, consulte *Acesso à Conta* na {xref-vsphere-node-template-config}[referência de configuração do template de nó.]
. Clique em *Criar*.

**Resultado:** Você criou as credenciais de nuvem que são usadas para provisionar nós em seu cluster.

[#_2_create_your_cluster]
=== 2. Crie seu cluster

Use o Rancher para criar um cluster Kubernetes no vSphere.

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, clique em *Criar*.
. Clique em *VMware vSphere*.
. Insira um *Nome do Cluster* e use suas credenciais de nuvem do vSphere.
. Crie um pool de máquinas para cada função do Kubernetes. Consulte as {xref-infra-providers}#_node_roles[melhores práticas] para recomendações sobre atribuições e contagens de funções.
.. Para cada pool de máquinas, defina a configuração da máquina.
. Use a *Configuração do Cluster* para escolher a versão do Kubernetes a ser instalada, qual provedor de rede usar e se deseja habilitar a isolação de rede do projeto.  Para ajuda na configuração do cluster, consulte as referências de configuração do {xref-rke2-config}[RKE2] e {xref-k3s-config}[K3s].
. Use *Funções de Membro* para configurar a autorização de usuários para o cluster. Clique em *Adicionar Membro* para adicionar usuários que podem acessar o cluster. Use o menu suspenso *Função* para definir permissões para cada usuário.
. Se você quiser provisionar dinamicamente armazenamento persistente ou outra infraestrutura mais tarde, precisará habilitar o provedor de nuvem vSphere modificando o arquivo YAML do cluster. Para detalhes, consulte {xref-cloud-provider-vsphere}[documentação do provedor de nuvem vSphere em árvore] e {xref-cloud-provider-vsphere-out-of-tree}[documentação do provedor de nuvem vSphere fora da árvore].
. Revise suas opções para confirmar se estão corretas. Então clique em *Criar*.

*Resultado:*

Seu cluster foi criado e atribuído ao estado de *Provisionamento*. O Rancher está configurando seu cluster.

Você pode acessar seu cluster após seu estado ser atualizado para *Ativo*.

Clusters *Ativos* são atribuídos a dois projetos:

* `Default`, contendo o namespace `default`
* `System`, contendo os namespaces `cattle-system`, `traefik`, `kube-public` e `kube-system`

[#_optional_next_steps]
== Próximas etapas opcionais

Após criar seu cluster, você pode acessá-lo através da interface do Rancher. Como uma melhor prática, recomendamos configurar essas maneiras alternativas de acessar seu cluster:

* *Acesse seu cluster com a CLI kubectl:* Siga {xref-access-cluster-kubectl}#_accessing_clusters_with_kubectl_from_your_workstation[estas etapas] para acessar clusters com kubectl em sua estação de trabalho. Neste caso, você será autenticado através do proxy de autenticação do servidor Rancher, e então o Rancher o conectará ao cluster downstream. Este método permite que você gerencie o cluster sem a interface do Rancher.
* *Acesse seu cluster com a CLI kubectl, usando o endpoint autorizado do cluster:* Siga {xref-access-cluster-kubectl}#_authenticating_directly_with_a_downstream_cluster[estas etapas] para acessar seu cluster com kubectl diretamente, sem autenticar através do Rancher. Recomendamos configurar este método alternativo para acessar seu cluster, para que, caso você não consiga se conectar ao Rancher, ainda possa acessar o cluster.
* *Aprovisionar armazenamento:* Para um exemplo de como provisionar armazenamento no vSphere usando o Rancher, consulte {xref-persistent-storage-examples}[esta seção]. Para provisionar armazenamento dinamicamente no vSphere, o provedor vSphere deve estar habilitado. Para mais detalhes, consulte {xref-cloud-provider-vsphere}[documentação do provedor de nuvem vSphere em árvore] e {xref-cloud-provider-vsphere-out-of-tree}[documentação do provedor de nuvem vSphere fora da árvore].
