= Desligamento controlado para Máquinas Virtuais VMware vSphere
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: procedimentos/guias-para-novos-usuários/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/vsphere/desligar-vm.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/shutdown-vm.adoc
:experimental:

No Rancher v2.8.3 e versões posteriores, você pode configurar o desligamento controlado de máquinas virtuais (VMs) para clusters de driver de nó VMware vSphere. O desligamento controlado introduz um atraso antes que a VM seja excluída forçosamente, o que permite tempo para encerrar quaisquer processos em execução e conexões abertas.

No RKE2/K3s, você pode configurar o desligamento controlado ao criar o cluster ou editar a configuração do cluster para adicioná-lo posteriormente.

[NOTE]
====
Como o Rancher não consegue detectar a plataforma de um cluster importado, você não pode habilitar o desligamento controlado em clusters VMware vSphere que você importou.
====


[#_enable_graceful_shutdown_during_vmware_vsphere_cluster_creation]
== Habilitar Desligamento Controlado Durante a Criação do Cluster VMware vSphere

No RKE2/K3s, você pode configurar novos clusters VMware vSphere com desligamento controlado para VMs:

. Clique em *☰ > Gerenciamento de Cluster*.
. Clique *Criar* e selecione *VMware vSphere* para provisionar um novo cluster.
. Em menu:Pools de Máquinas[Agendamento], no campo *Tempo Limite para Desligamento Controlado*, insira um valor inteiro maior que 0. O valor que você inserir é a quantidade de tempo em segundos que o Rancher espera antes de excluir VMs no cluster. Se o valor for definido como `0`, o desligamento controlado está desabilitado.

[#_enable_graceful_shutdown_in_existing_rke2_product_name_k3s_product_name_clusters]
== Habilitar Desligamento Controlado em Clusters Existentes {rke2-product-name}/{k3s-product-name}

No RKE2/K3s, você pode editar a configuração de um cluster VMware vSphere existente para habilitar o desligamento controlado, o que adiciona um atraso antes de excluir VMs.

. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, encontre o cluster hospedado VMware vSphere que você deseja editar. Clique *⋮* no final da linha associada ao cluster. Selecione *Editar Configuração*.
. Em menu:Pools de Máquinas[Agendamento], no campo *Tempo Limite para Desligamento Controlado*, insira um valor inteiro maior que 0. O valor que você inserir é a quantidade de tempo em segundos que o Rancher espera antes de excluir VMs no cluster. Se o valor for definido como `0`, o desligamento controlado está desabilitado.
