= Criando um Cluster VMware vSphere
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: procedimentos/novos-guias-de-usuário/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/vsphere/index.adoc 
:product-path: cluster-deployment/infra-providers/vsphere/vsphere.adoc
:description: Use o Rancher para criar um cluster VMware vSphere. Ele pode consistir em grupos de VMs com propriedades distintas que permitem um controle detalhado sobre o dimensionamento dos nós.
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-cloud-provider-vsphere-out-of-tree: xref:cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-vsphere-storage-example: xref:cluster-admin/manage-clusters/persistent-storage/examples/vsphere-storage.adoc
:xref-provision-cluster-in-vsphere: xref:cluster-deployment/infra-providers/vsphere/provision-kubernetes-clusters-in-vsphere.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-cloud-provider-vsphere-out-of-tree: xref:guias-de-procedimentos/guias-para-novos-usuarios/clusters-kubernetes-no-rancher/configuração-de-provedores-de-nuvem/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:guias-de-procedimentos/guias-para-novos-usuarios/clusters-kubernetes-no-rancher/configuração-de-provedores-de-nuvem/configure-in-tree-vsphere.adoc
:xref-vsphere-storage-example: xref:procedimentos-guias/novos-guias-de-usuário/gerenciar-clusters/provisionamento-exemplos-de-armazenamento/armazenamento-vsphere.adoc
:xref-provision-cluster-in-vsphere: xref:procedimentos/novos-guias-de-usuário/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-provedor-infra/vsphere/provisionar-clusters-kubernetes-no-vsphere.adoc
endif::[]

importar YouTube de '@site/src/components/YouTube'

Ao usar o Rancher com o VMware vSphere, você pode trazer operações em nuvem no local.

O Rancher pode provisionar nós no vSphere e instalar o Kubernetes neles. Ao criar um cluster Kubernetes no vSphere, o Rancher primeiro provisiona o número especificado de máquinas virtuais comunicando-se com a API do vCenter. Em seguida, ele instala o Kubernetes sobre eles.

Um cluster vSphere pode consistir em vários grupos de VMs com propriedades distintas, como a quantidade de memória ou o número de vCPUs. Esse agrupamento permite um controle detalhado sobre o dimensionamento dos nós para cada função do Kubernetes.

[#_creating_a_vmware_vsphere_cluster]
== Criando um Cluster VMware vSphere

Na {xref-provision-cluster-in-vsphere}[esta seção,] você aprenderá como usar o Rancher para instalar um {url-rke2-landing-page}[RKE2] ou {url-k3s-landing-page}[K3s] cluster Kubernetes no vSphere.

[#_provisioning_storage]
== Provisionamento de Armazenamento

Para um exemplo de como provisionar armazenamento no vSphere usando o Rancher, consulte {xref-vsphere-storage-example}[esta seção]. Para provisionar armazenamento dinamicamente no vSphere, o provedor vSphere deve estar habilitado. Consulte {xref-cloud-provider-vsphere}[configuração vSphere in-tree] e {xref-cloud-provider-vsphere-out-of-tree}[configuração vSphere out-of-tree].

[#_enabling_the_vmware_vsphere_cloud_provider]
== Habilitando o Provedor de Nuvem VMware vSphere

Quando um provedor de nuvem é configurado no Rancher, o servidor Rancher pode automaticamente provisionar nova infraestrutura para o cluster, incluindo novos nós ou dispositivos de armazenamento persistente.

Para detalhes sobre como habilitar o provedor de nuvem vSphere, consulte {xref-cloud-provider-vsphere}[in-tree vSphere config] e {xref-cloud-provider-vsphere-out-of-tree}[out-of-tree vSphere config].
