= Contribuindo para {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-14
:page-revdate: {revdate}
:community-path: contribute-to-rancher.adoc 
:product-path: contribute-to-rancher.adoc

Saiba mais sobre os repositórios usados para o Rancher e a documentação do Rancher, como construir repositórios do Rancher e quais informações incluir ao registrar um problema.

Para informações mais detalhadas sobre como contribuir para o desenvolvimento dos projetos do Rancher, consulte o https://github.com/rancher/rancher/wiki[Wiki do Desenvolvedor do Rancher]. O wiki possui recursos sobre muitos tópicos, incluindo os seguintes:

* Como configurar o ambiente de desenvolvimento do Rancher e executar testes
* O fluxo típico de um problema ao longo do ciclo de vida do desenvolvimento
* Diretrizes de codificação e melhores práticas de desenvolvimento
* Depuração e solução de problemas
* Desenvolvendo a API do Rancher

No Slack dos Usuários do Rancher, o canal para desenvolvedores é *#developer*.

[#_rancher_docs]
== Documentação do Rancher

Se você tiver sugestões para a documentação deste site, https://github.com/rancher/rancher-docs/issues/new/choose[abra] um problema no repositório principal https://github.com/rancher/rancher-docs[documentação do Rancher]. Este repositório contém documentação para o Rancher v2.0 e versões posteriores.

Veja o https://github.com/rancher/rancher-docs#readme[README da documentação do Rancher] para mais detalhes sobre como contribuir e construir o repositório de documentação do Rancher v2.x.

Para documentação descrevendo o Rancher v1.6 e versões anteriores, consulte o repositório https://github.com/rancher/rancher.github.io[Rancher 1.x docs], que contém arquivos fonte para https://rancher.com/docs/rancher/v1.6/en/.

[#_rancher_repositories]
== Repositórios do Rancher

Todos os repositórios estão localizados dentro da nossa organização principal no GitHub. Existem muitos repositórios usados para o Rancher, mas forneceremos descrições de alguns dos principais usados no Rancher.

|===
| Repositório | URL | Descrição

| Rancher
| https://github.com/rancher/rancher
| Este repositório é o código-fonte principal do Rancher 2.x.

| Tipos
| https://github.com/rancher/types
| Este repositório é o repositório que contém todos os tipos de API para o Rancher 2.x.

| Framework de API
| https://github.com/rancher/norman
| Este repositório é um framework de API para construir APIs no estilo Rancher, apoiadas por Recursos Personalizados do Kubernetes.

| Interface do usuário
| https://github.com/rancher/dashboard/
| Este repositório é a fonte da interface do usuário do Dashboard.

| (Rancher) Docker Machine
| https://github.com/rancher/machine
| Este repositório é a fonte do binário do Docker Machine usado ao utilizar Drivers de Nó. Este é um fork do repositório `docker/machine`.

| pacote-máquina
| https://github.com/rancher/machine-package
| Este repositório é usado para construir o binário do Docker Machine do Rancher.

| kontainer-engine
| https://github.com/rancher/kontainer-engine
| Este repositório é a fonte do kontainer-engine, a ferramenta para provisionar clusters Kubernetes hospedados.

| CLI
| https://github.com/rancher/cli
| Este repositório é o código-fonte do Rancher CLI usado no Rancher 2.x.

| (Rancher) repositório Helm
| https://github.com/rancher/helm
| Este repositório é a fonte do binário do Helm empacotado. Este é um fork do repositório `helm/helm`.

| repositório loglevel
| https://github.com/rancher/loglevel
| Este repositório é a fonte do binário loglevel, usado para mudar dinamicamente os níveis de log.
|===

Para ver todas as bibliotecas/projetos usados no Rancher, veja o arquivo https://github.com/rancher/rancher/blob/master/go.mod[`go.mod`] no repositório `rancher/rancher`.

.Componentes do Rancher usados para provisionar/gerenciar clusters Kubernetes
image::ranchercomponentsdiagram-2.6.svg[Diagrama do Rancher]

[#_building_rancher_repositories]
=== Construindo repositórios do Rancher

Todo repositório deve ter um Makefile e pode ser construído usando o comando `make`. Os alvos `make` são baseados nos scripts no diretório `/scripts` do repositório, e cada alvo usará https://github.com/rancher/dapper[Dapper] para executar o alvo em um ambiente isolado. O `Dockerfile.dapper` será usado para este processo e inclui todas as ferramentas de build necessárias.

O alvo padrão é `ci`, e executará `./scripts/validate`, `./scripts/build`, `./scripts/test` e `./scripts/package`. Os binários resultantes do build estarão em `./build/bin` e geralmente também são empacotados em uma imagem Docker.

[#_rancher_bugs_issues_or_questions]
=== Bugs, Problemas ou Perguntas do Rancher

Se você encontrar algum bug ou estiver tendo problemas, por favor, pesquise o https://github.com/rancher/rancher/issues[problema reportado] pois alguém pode ter enfrentado o mesmo problema ou estamos trabalhando ativamente em uma solução.

Se você não conseguir encontrar nada relacionado ao seu problema, entre em contato conosco através de https://github.com/rancher/rancher/issues/new[registrando um problema]. Embora tenhamos muitos repositórios relacionados ao Rancher, queremos que os bugs sejam registrados no repositório do Rancher para que não deixemos passar nenhum! Se você quiser fazer uma pergunta ou perguntar a outros usuários sobre um caso de uso, sugerimos criar uma postagem nos https://forums.rancher.com[Fóruns do Rancher].

[#_checklist_for_filing_issues]
==== Lista de verificação para registrar problemas

Por favor, siga esta lista de verificação ao registrar um problema para nos ajudar a investigar e corrigir o problema. Mais informações significam mais dados que podemos usar para determinar o que está causando o problema ou o que pode estar relacionado ao problema.

[NOTE]
====

Para grandes quantidades de dados, por favor, use https://gist.github.com/[GitHub Gist] ou similar e vincule o recurso criado no problema.
====


[NOTE]
.Importante:
====

Por favor, remova quaisquer dados sensíveis, pois eles serão visíveis publicamente.
====


* *Recursos:* Forneça o máximo de detalhes possível sobre os recursos utilizados. Como a origem do problema pode ser muitas coisas, incluir o máximo de detalhes possível ajuda a determinar a causa raiz. Veja alguns exemplos abaixo:
 ** *Hosts:* Quais são as especificações do host, como CPU/memória/disco, em qual nuvem isso acontece, qual Amazon Machine Image você está usando, qual droplet da DigitalOcean você está usando, qual imagem você está provisionando que podemos reconstruir ou usar quando tentarmos reproduzir
 ** *Sistema Operacional:* Qual sistema operacional você está usando? Fornecer detalhes ajuda aqui, como a saída de `cat /etc/os-release` para a versão exata do SO e `uname -r` para o kernel exato utilizado
 ** *Docker:* Qual versão do Docker você está usando, como você o instalou? A maioria dos detalhes do Docker pode ser encontrada fornecendo a saída de `docker version` e `docker info`
 ** *Ambiente:* Você está em um ambiente de proxy, está usando certificados CA reconhecidos/certificados autoassinados, está usando um balanceador de carga externo
 ** *Rancher:* Qual versão do Rancher você está usando, isso pode ser encontrado no canto inferior esquerdo da interface ou pode ser recuperado da tag da imagem que você está executando no host
 ** *Clusters:* Que tipo de cluster você criou, como você o criou, o que você especificou ao criá-lo
* *Passos para reproduzir o problema:* Forneça o máximo de detalhes sobre como você chegou à situação relatada. Isso ajuda a pessoa a reproduzir a situação em que você se encontra.
 ** Forneça passos manuais ou scripts de automação usados para ir de uma configuração recém-criada à situação que você relatou.
* *Registros:* Forneça dados/registros dos recursos utilizados.
 ** Rancher
  *** Instalação do Docker

+
----
  docker logs \
  --timestamps \
  $(docker ps | grep -E "rancher/rancher:|rancher/rancher " | awk '{ print $1 }')
----
  *** Instalação do Kubernetes usando `kubectl`

+

[NOTE]
====
Certifique-se de que você configurou o kubeconfig correto (por exemplo, `export KUBECONFIG=$PWD/kube_config_cluster.yml` se o Rancher estiver instalado em um cluster Kubernetes) ou está usando o kubectl embutido via interface.
====

+
----
  kubectl -n cattle-system \
  logs \
  -l app=rancher \
  --timestamps=true
----

 ** Registro do sistema (esses podem não existir todos, dependendo do sistema operacional)
  *** `/var/log/messages`
  *** `/var/log/syslog`
  *** `/var/log/kern.log`
 ** Registro do daemon do Docker (pode ser que nem todos existam, dependendo do sistema operacional)
  *** `/var/log/docker.log`
* *Métricas:* Se você está enfrentando problemas de desempenho, por favor forneça o máximo de dados (arquivos ou capturas de tela) de métricas que possam ajudar a determinar o que está acontecendo. Se você tiver um problema relacionado a uma máquina, é útil fornecer a saída de `top`, `free -m`, `df` que mostra processos, uso de memória e uso de disco.
