= Clusters Kubernetes dans la {rancher-product-name}configuration
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc 
:product-path: cluster-deployment/cluster-deployment.adoc
:description: Provisionnement des clusters Kubernetes
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-infra-providers: xref:cluster-deployment/fournisseurs-infra/fournisseurs-infra.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-custom-clusters: xref:cluster-deployment/custom-clusters/custom-clusters.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-k8s-concepts: xref:about-rancher/concepts.adoc
:xref-rancher-architecture: xref:about-rancher/architecture/architecture.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-infra-providers: xref:guides-procédures/guides-nouveaux-utilisateurs/lancer-kubernetes-avec-rancher/utiliser-nouveaux-nœuds-dans-un-fournisseur-infra/index.adoc
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
:xref-custom-clusters: xref:guides-de-référence/configuration/serveur-rancher/utiliser-des-nœuds-existants/index.adoc
:xref-hosted-k8s-clusters: xref:guides-pratiques/nouveaux-guides-utilisateurs/clusters-kubernetes-dans-rancher-configuration/configurer-des-clusters-à-partir-de-fournisseurs-kubernetes-hébergés/index.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
endif::[]

Rancher simplifie la création de clusters en vous permettant de les créer via l'interface utilisateur de Rancher plutôt que par des alternatives plus complexes. Rancher propose plusieurs options pour lancer un cluster. Utilisez l'option qui correspond le mieux à votre cas d'utilisation.

Cette section suppose une familiarité de base avec Docker et Kubernetes. Pour une brève explication de la façon dont les composants Kubernetes fonctionnent ensemble, reportez-vous à la page {xref-k8s-concepts}[concepts].

Pour un aperçu conceptuel de la manière dont le serveur Rancher provisionne des clusters et des outils qu'il utilise pour les provisionner, consultez la {xref-rancher-architecture}page [architecture].

[#_cluster_management_capabilities_by_cluster_type]
== Capacités de gestion des clusters par type de cluster

Le tableau suivant résume les options et paramètres disponibles pour chaque type de cluster{nbsp}:

ifeval::["{build-type}" != "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table.adoc[]
endif::[]
ifeval::["{build-type}" == "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table-srfa.adoc[]
endif::[]

[#_setting_up_clusters_in_a_hosted_kubernetes_provider]
== Configuration des clusters dans un fournisseur Kubernetes hébergé

ifeval::["{build-type}" != "srfa"]
Dans ce scénario, Rancher ne provisionne pas Kubernetes car il est installé par des fournisseurs tels que Google Kubernetes Engine (GKE), Amazon Elastic Container Service for Kubernetes ou Azure Kubernetes Service.
endif::[]
ifeval::["{build-type}" == "srfa"]
Dans ce scénario, Rancher ne provisionne pas Kubernetes car il est installé par Amazon Elastic Container Service for Kubernetes.
endif::[]

ifeval::["{build-type}" != "srfa"]
Si vous utilisez un fournisseur Kubernetes tel que Google GKE, Rancher s'intègre à ses API cloud, vous permettant de créer et de gérer le contrôle d'accès en fonction du rôle pour le cluster hébergé depuis l'interface utilisateur de Rancher.
endif::[]
ifeval::["{build-type}" == "srfa"]
Si vous utilisez un fournisseur Kubernetes, Rancher s'intègre à ses API cloud, vous permettant de créer et de gérer le contrôle d'accès en fonction du rôle pour le cluster hébergé depuis l'interface utilisateur de Rancher.
endif::[]

Pour plus d'informations, consultez la section sur {xref-hosted-k8s-clusters}[clusters Kubernetes hébergés].

[#_launching_kubernetes_with_rancher]
== Lancement de Kubernetes avec Rancher

Rancher utilise https://docs.rke2.io/[RKE2] ou https://docs.k3s.io/[K3s] comme bibliothèque lors du provisionnement de Kubernetes sur vos propres nœuds. RKE2 est l'installateur Kubernetes léger propre à Rancher.

Dans les clusters RKE2, Rancher gère le déploiement de Kubernetes. Ces clusters peuvent être déployés sur n'importe quel matériel sans système d'exploitation, fournisseur de cloud ou plate-forme de virtualisation.

Si vous avez déjà un nœud que vous souhaitez ajouter à un cluster RKE2, vous pouvez l'ajouter au cluster en exécutant un conteneur agent RKE2 de Rancher dessus.

Pour plus d'informations, consultez {xref-launch-k8s-with-rancher}[Lancement de Kubernetes avec Rancher].

[#_launching_kubernetes_and_provisioning_nodes_in_an_infrastructure_provider]
=== Lancement de Kubernetes et provisionnement de nœuds dans un fournisseur d'infrastructure

ifeval::["{build-type}" != "srfa"]
Rancher peut provisionner dynamiquement des nœuds dans des fournisseurs d'infrastructure tels qu'Amazon EC2, DigitalOcean, Azure ou vSphere, puis installer Kubernetes dessus.
endif::[]
ifeval::["{build-type}" == "srfa"]
Rancher peut provisionner dynamiquement des nœuds dans des fournisseurs d'infrastructure tels qu'Amazon EC2, puis installer Kubernetes sur ceux-ci.
endif::[]

Un avantage d'utiliser des nœuds hébergés par un fournisseur d'infrastructure est que si un nœud perd la connectivité avec le cluster, Rancher peut automatiquement le remplacer, maintenant ainsi la configuration attendue du cluster.

Pour plus d'informations, consultez {xref-infra-providers}[Lancement de Kubernetes sur de nouveaux nœuds dans un fournisseur d'infrastructure]

[#_launching_kubernetes_on_existing_custom_nodes]
=== Lancement de Kubernetes sur des nœuds personnalisés existants.

Lors de la configuration de ce type de cluster, Rancher installe Kubernetes sur des {xref-custom-clusters}[nœuds personnalisés existants,] ce qui crée un cluster personnalisé.

Vous pouvez apporter tous les nœuds que vous souhaitez à Rancher et les utiliser pour créer un cluster.

Ces nœuds incluent du matériel sans système d'exploitation sur site, des machines virtuelles hébergées dans le cloud ou des machines virtuelles sur site.

[#_registering_existing_clusters]
== Enregistrement des clusters existants

La fonctionnalité d'enregistrement de cluster remplace la fonctionnalité d'importation de clusters.

L'enregistrement des clusters EKS offre désormais des avantages supplémentaires. Pour la plupart, les clusters EKS enregistrés et les clusters EKS créés dans Rancher sont traités de la même manière dans l'interface utilisateur de Rancher, sauf pour la suppression.

Lorsque vous supprimez un cluster EKS qui a été créé dans Rancher, le cluster est détruit. Lorsque vous supprimez un cluster EKS qui a été enregistré dans Rancher, il est déconnecté du serveur Rancher, mais il existe toujours et vous pouvez y accéder de la même manière que vous le faisiez avant qu'il ne soit enregistré dans Rancher.

Pour plus d'informations, consultez {xref-register-clusters}[Enregistrement des clusters existants].

[#_programmatically_creating_clusters]
== Création programmatique de clusters

La manière la plus courante de déployer des clusters Kubernetes de manière programmatique via Rancher est d'utiliser le fournisseur Terraform Rancher2. Consultez la documentation pour https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster[la création de clusters avec Terraform].

ifeval::["{build-type}" != "srfa"]
Les clusters EKS, GKE et AKS peuvent être créés ou importés avec Terraform.
endif::[]
ifeval::["{build-type}" == "srfa"]
Les clusters EKS peuvent être créés ou importés avec Terraform.
endif::[]
