= Acceso a Clústeres
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/manage-clusters/access-clusters/index.adoc 
:product-path: cluster-admin/manage-clusters/access-clusters/access-clusters.adoc
ifeval::["{build-type}" != "community"]
:xref-rancher-cli: xref:rancher-admin/cli/rancher-cli.adoc
:xref-user-api-keys: rancher-admin/users/settings/api-keys.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-authn-authz: xref:rancher-admin/users/authn-and-authz/authn-and-authz.adoc
:xref-manage-rbac: xref:rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/manage-role-based-access-control-rbac.adoc
:xref-add-users-to-clusters: xref:cluster-admin/manage-clusters/access-clusters/add-users-to-clusters.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rancher-cli: xref:reference-guides/cli-with-rancher/rancher-cli.adoc
:xref-user-api-keys: xref:reference-guides/user-settings/api-keys.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-authn-authz: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/index.adoc
:xref-manage-rbac: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/index.adoc
:xref-add-users-to-clusters: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/add-users-to-clusters.adoc
endif::[]

Esta sección trata sobre qué herramientas se pueden utilizar para acceder a los clústeres gestionados por Rancher.

Para información sobre cómo dar permisos a los usuarios para acceder a un clúster, consulta la sección sobre {xref-add-users-to-clusters}[agregar usuarios a clústeres.]

Para más información sobre el control de acceso basado en funciones, consulta {xref-manage-rbac}[esta sección.]

Para información sobre cómo configurar un sistema de autenticación, consulta {xref-authn-authz}[esta sección.]

[#_clusters_in_rancher_ui]
== Clústeres en la interfaz de usuario de Rancher

Hay varias formas de ver y gestionar clústeres a través de la interfaz de usuario de Rancher.

[#_clusters_page]
=== Página de Clústeres

Puedes acceder a la página de *Clústeres* desde el menú *☰*:

. Haz clic en *☰*.
. Selecciona *Gestión de Clústeres*.

También puedes acceder a la página de *Clústeres* haciendo clic en el botón *Gestionar* en la parte superior de la tabla de clústeres en la página de inicio de Rancher *Inicio*.

En la página de *Clústeres*, selecciona *⁝* al final de cada fila para ver un submenú con las siguientes opciones:

* {xref-access-cluster-kubectl}[Shell de kubectl]
* Descargar KubeConfig
* Copiar KubeConfig al portapapeles
* Editar Configuración
* Ver YAML
* Descargar YAML

[#_cluster_dashboard]
=== Panel de Clúster

En la página de *Clústeres*, selecciona el botón *Explorar* al final de cada fila para ver el *Panel de Clúster* de ese clúster. También puedes ver el panel haciendo clic en el nombre de un clúster en la tabla, luego haciendo clic en el botón *Explorar* en la página de *Clúster*.

El *Panel de Clúster* también es accesible desde la página de inicio de Rancher UI *Inicio*, haciendo clic en el nombre de un clúster.

También puedes acceder al *Panel de Clúster* desde el *☰* en la barra de navegación superior:

. Haz clic en *☰*.
. Selecciona el nombre de un clúster de la opción del menú *Explorar Clúster*.

El *Panel de Clúster* lista información sobre un clúster específico, como el número de nodos, el uso de memoria, eventos y recursos.

[#_kubectl]
== kubectl

Puedes usar la herramienta shell de Kubernetes, https://kubernetes.io/docs/reference/kubectl/overview/[kubectl], para gestionar tus clústeres. Tienes dos opciones para usar kubectl:

* *Shell de kubectl de Rancher:* Interactúa con tus clústeres lanzando una shell de kubectl disponible en la interfaz de usuario de Rancher. Esta opción no requiere acciones de configuración por tu parte. Para más información, consulta {xref-access-cluster-kubectl}[Accediendo a Clústeres con la Shell de kubectl].
* *Conexión remota de terminal:* También puedes interactuar con tus clústeres instalando https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl] en tu escritorio local y luego copiando el archivo kubeconfig del clúster a tu directorio local `~/.kube/config`. Para más información, consulta {xref-access-cluster-kubectl}[Accediendo a Clústeres con kubectl y un archivo kubeconfig].

[#_rancher_cli]
== Rancher CLI

Puedes controlar tus clústeres descargando la propia interfaz de línea de comandos de Rancher, {xref-rancher-cli}[Rancher CLI]. Esta herramienta CLI puede interactuar directamente con diferentes clústeres y proyectos o pasarles `kubectl` comandos.

[#_rancher_api]
== Rancher API

Finalmente, puedes interactuar con tus clústeres a través de la API de Rancher. Antes de usar la API, debes obtener una {xref-user-api-keys}[clave API]. Para ver los diferentes campos de recursos y acciones para un objeto de API, abre la interfaz de usuario de la API, a la que se puede acceder haciendo clic en *Ver en API* para cualquier objeto de la interfaz de usuario de Rancher.
