= Configurando o Provedor de Nuvem Google Compute Engine
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: procedimentos/guias-para-novos-usuarios/clusters-kubernetes-no-rancher-configuração/configuração/provedores-de-nuvem/google-compute-engine.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/google-compute-engine.adoc

Nesta seção, você aprenderá como habilitar o provedor de nuvem Google Compute Engine (GCE) para clusters personalizados no Rancher. Um cluster personalizado é aquele em que o Rancher instala o Kubernetes em nós existentes.

A documentação oficial do Kubernetes para o provedor de nuvem GCE está https://github.com/kubernetes/website/blob/release-1.18/content/en/docs/concepts/cluster-administration/cloud-providers.md#gce[aqui.]

[NOTE]
.Pré-requisitos:
====

A conta de serviço com acesso `Identity and API` no GCE precisa da permissão `Computer Admin`.
====


Se você estiver usando Calico,

. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster personalizado e clique em _*⋮ > Editar YAML._ Insira a seguinte configuração:
+
[,yaml]
----
 rancher_kubernetes_engine_config:
   cloud_provider:
     name: gce
     customCloudProvider: |-
       [Global]
       project-id=<your project ID, optional>
       network-name=<your network, optional if using default network>
       subnetwork-name=<your subnetwork of the above network, optional if using default network>
       node-instance-prefix=<your instance group name/your instance name specific prefix, required>
       node-tags=<your network tags, must patch one or some tags, required>
   network:
     options:
       calico_cloud_provider: "gce"
     plugin: "calico"
----

Se você estiver usando Canal ou Flannel,

. Clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster personalizado e clique em _*⋮ > Editar YAML._ Insira a seguinte configuração:
+
[,yaml]
----
 rancher_kubernetes_engine_config:
   cloud_provider:
     name: gce
     customCloudProvider: |-
       [Global]
       project-id=<your project ID, optional>
       network-name=<your network, optional if using default network>
       subnetwork-name=<your subnetwork of the above network, optional if using default network>
       node-instance-prefix=<your instance group name/your instance name specific prefix, required>
       node-tags=<your network tags, must patch one or some tags, required>
   services:
     kube_controller:
       extra_args:
         configure-cloud-routes: true # we need to allow the cloud provider configure the routes for the hosts
----
