= Configuração de Provedores de Nuvem
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/index.adoc 
:product-path: cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
ifeval::["{build-type}" != "community"]
:xref-azure-cloud-provider: xref:cluster-deployment/set-up-cloud-providers/azure.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:cluster-deployment/set-up-cloud-providers/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:cluster-deployment/set-up-cloud-providers/configure-in-tree-vsphere.adoc
:xref-cloud-provider-amazon: xref:cluster-deployment/set-up-cloud-providers/amazon.adoc
:xref-cloud-provider-google-compute-engine: xref:cluster-deployment/set-up-cloud-providers/google-compute-engine.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-azure-cloud-provider: xref:guias-de-procedimentos/guias-para-novos-usuarios/clusters-kubernetes-no-rancher/configuração-de-provedores-de-nuvem/azure.adoc
:xref-cloud-provider-vsphere-out-of-tree: xref:guias-de-procedimentos/guias-para-novos-usuarios/clusters-kubernetes-no-rancher/configuração-de-provedores-de-nuvem/configure-out-of-tree-vsphere.adoc
:xref-cloud-provider-vsphere: xref:guias-de-procedimentos/guias-para-novos-usuarios/clusters-kubernetes-no-rancher/configuração-de-provedores-de-nuvem/configure-in-tree-vsphere.adoc
:xref-cloud-provider-amazon: xref:guias-de-procedimentos/guias-para-novos-usuarios/clusters-kubernetes-no-rancher/configuração-de-provedores-de-nuvem/amazon.adoc
:xref-cloud-provider-google-compute-engine: xref:guias-de-procedimentos/guias-para-novos-usuarios/clusters-kubernetes-no-rancher/configuração-de-provedores-de-nuvem/google-compute-engine.adoc
endif::[]

Um _provedor de nuvem_ é um módulo no Kubernetes que fornece uma interface para gerenciar nós, balanceadores de carga e rotas de rede.

Quando um provedor de nuvem é configurado no Rancher, o servidor Rancher pode provisionar automaticamente novos nós, balanceadores de carga ou dispositivos de armazenamento persistente ao lançar definições do Kubernetes, se o provedor de nuvem que você está usando suportar essa automação.

Seu cluster não será provisionado corretamente se você configurar um cluster de nós de provedor de nuvem que não atenda aos pré-requisitos.

Por padrão, a opção *Provedor de Nuvem* está definida como `None`.

Os seguintes provedores de nuvem podem ser habilitados:

* Amazon
* Azure
* GCE (Google Compute Engine)
* vSphere

[#_setting_up_the_amazon_cloud_provider]
== Configuração do Provedor de Nuvem Amazon

Para detalhes sobre como habilitar o provedor de nuvem Amazon, consulte {xref-cloud-provider-amazon}[esta página.]

[#_setting_up_the_azure_cloud_provider]
== Configuração do Provedor de Nuvem Azure

Para detalhes sobre como habilitar o provedor de nuvem Azure, consulte {xref-azure-cloud-provider}[esta página.]

[#_setting_up_the_gce_cloud_provider]
== Configuração do Provedor de Nuvem GCE

Para detalhes sobre como habilitar o provedor de nuvem Google Compute Engine, consulte {xref-cloud-provider-google-compute-engine}[esta página.]

[#_setting_up_the_vmware_vsphere_cloud_provider]
== Configuração do Provedor de Nuvem VMware vSphere

Para detalhes sobre como habilitar o provedor de nuvem vSphere, consulte {xref-cloud-provider-vsphere}[in-tree vSphere config] e {xref-cloud-provider-vsphere-out-of-tree}[out-of-tree vSphere config].

[#_setting_up_a_custom_cloud_provider]
== Configuração de um Provedor de Nuvem Personalizado

O provedor de nuvem `Custom` está disponível se você quiser configurar qualquer provedor de nuvem Kubernetes.

Para a opção de provedor de nuvem personalizado, você pode consultar os https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/[documentos RKE] sobre como editar o arquivo yaml para o seu provedor de nuvem específico. Existem provedores de nuvem específicos que têm configuração mais detalhada:

* https://rke.docs.rancher.com/config-options/cloud-providers/vsphere[vSphere]
* https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/openstack/[OpenStack]
