= Konfigurieren eines Ingress
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-20
:page-revdate: {revdate}
:community-path: how-to-guides/neue-benutzeranleitungen/kubernetes-ressourcen-setup/load-balancer-und-ingress-controller/ingress-konfiguration.adoc 
:product-path: cluster-admin/kubernetes-resources/load-balancer-and-ingress-controller/ingress-configuration.adoc
:description: Konfigurieren eines Ingress
ifeval::["{build-type}" != "community"]
:xref-rke1-config: xref:cluster-deployment/configuration/rke1.adoc
:xref-http-encrypt: xref:security/encrypting-http.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rke1-config: xref:referenzanleitungen/cluster-Konfiguration/rancher-server-Konfiguration/rke1-cluster-Konfiguration.adoc
:xref-http-encrypt: xref:how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication.adoc
endif::[]

[#_specify_a_hostname_to_use]
== Geben Sie einen Hostnamen an, der verwendet werden soll

Wenn Sie diese Option verwenden, leitet Ingress Anfragen für einen Hostnamen an den Dienst oder die Arbeitslast weiter, die Sie angeben.

. Geben Sie einen Pfad vom Typ `Prefix` an und spezifizieren Sie einen Pfad wie `/`.
. Fügen Sie einen *Ziel-Dienst* hinzu.
. *Optional:* Wenn Sie eine Arbeitslast oder einen Dienst angeben möchten, wenn eine Anfrage an einen bestimmten Hostnamen-Pfad gesendet wird, fügen Sie einen *Pfad* für das Ziel hinzu. Wenn Sie beispielsweise möchten, dass Anfragen für `www.mysite.com/contact-us` an einen anderen Dienst als `www.mysite.com` gesendet werden, geben Sie `/contact-us` im Feld *Pfad* ein. Typischerweise enthält die erste Regel, die Sie erstellen, keinen Pfad.
. Geben Sie die *Port*-Nummer an, auf der jeder Ziel-Dienst arbeitet.

[#_certificates]
== Zertifikate

[NOTE]
====

Sie müssen ein SSL-Zertifikat haben, das Ingress verwenden kann, um die Kommunikation zu verschlüsseln und zu entschlüsseln. Für weitere Informationen siehe {xref-http-encrypt}[SSL-Zertifikate hinzufügen].
====


. Um einen Ingress-Controller zu erstellen, klicken Sie auf die Registerkarte *Zertifikate*.
. Klicken Sie auf *Zertifikat hinzufügen*.
. Wählen Sie einen *Zertifikat - Secret-Name* aus der Dropdownliste aus.
. Geben Sie den Host unter Verwendung verschlüsselter Kommunikation ein.
. Um weitere Hosts hinzuzufügen, die dasselbe Zertifikat verwenden, klicken Sie auf *Hosts hinzufügen*.

[#_labels_and_annotations]
== Labels und Annotationen

Bitte beziehen Sie sich auf die Traefik-Dokumentation für die vollständige Liste der Ingress NGINX-Annotationen, die von Traefiks kubernetesIngressNginx-Anbieter https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/ingress-nginx/#annotations-support[unterstützt] und https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/ingress-nginx/#unsupported-annotations[nicht unterstützt] werden.
