= 创建Amazon EC2集群
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-19
:page-revdate: {revdate}
:community-path: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-an-amazon-ec2-cluster.adoc 
:product-path: cluster-deployment/infra-providers/aws/aws.adoc
:description: 了解使用Rancher创建Amazon EC2集群所需的先决条件和步骤
ifeval::["{build-type}" != "community"]
:url-rke2-landing-page: https://documentation.suse.com/cloudnative/rke2/
:url-k3s-landing-page: https://documentation.suse.com/cloudnative/k3s/
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
:xref-access-cluster-kubectl: xref:cluster-admin/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
:xref-k3s-config: xref:cluster-deployment/configuration/k3s.adoc
:xref-aws-machine-configuration: xref:cluster-deployment/infra-providers/aws/machine-configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-rke2-landing-page: https://docs.rke2.io/
:url-k3s-landing-page: https://docs.k3s.io/
:xref-rke2-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.adoc
:xref-access-cluster-kubectl: xref:how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.adoc
:xref-infra-providers: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/index.adoc
:xref-set-up-cloud-providers: xref:如何指南/新用户指南/在Rancher中设置Kubernetes集群/设置云提供商/index.adoc
:xref-k3s-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.adoc
:xref-aws-machine-configuration: xref:reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/amazon-ec2.adoc
endif::[]

在本节中，您将学习如何在Amazon EC2中部署{url-rke2-landing-page}[RKE2]或{url-k3s-landing-page}[K3s] Kubernetes集群。

首先，您需要在Rancher中设置您的EC2云凭证。

然后，您在Rancher中创建一个EC2集群，并在配置新集群时定义机器池。每个机器池都有一个Kubernetes角色：etcd、controlplane或worker。Rancher在新节点上安装Kubernetes，并根据机器池定义的Kubernetes角色设置每个节点。

[#_prerequisites]
== 先决条件

* *AWS EC2访问密钥和秘密密钥*，将用于创建实例。请参见 https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey[亚马逊文档：创建访问密钥]，了解如何创建访问密钥和秘密密钥。
* *创建的IAM策略*，以添加到访问密钥和秘密密钥的用户。请参见 https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html#access_policies_create-start[亚马逊文档：创建IAM策略（控制台）]，了解如何创建IAM策略。请查看下面我们的三个示例JSON策略：
 ** <<_example_iam_policy,示例IAM策略>>
 ** <<_example_iam_policy_with_passrole,带有PassRole的示例IAM策略>>（如果您想使用{xref-set-up-cloud-providers}[Kubernetes云提供商]或想将IAM控制文件传递给实例，则需要）
 ** <<_example_iam_policy_to_allow_encrypted_ebs_volumes,允许加密EBS卷的示例IAM策略>>
* *作为权限添加的IAM策略*，以添加到用户。请参见 https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_change-permissions.html#users_change_permissions-add-console[亚马逊文档：向用户添加权限（控制台）]，了解如何将其附加到用户。
* *仅IPv4或仅IPv6或双栈子网和/或VPC*，可以在其中配置节点并分配IPv4和/或IPv6地址。请参见 https://docs.aws.amazon.com/vpc/latest/userguide/vpc-migrate-ipv6.html[亚马逊文档：您的VPC的IPv6支持]。

[#_creating_an_ec2_cluster]
== 创建EC2集群

创建集群的步骤根据您的Rancher版本而有所不同。

[#_create_your_cloud_credentials]
=== 创建您的云凭据

如果您已经有一组云凭证可供使用，请跳过此部分。

. 单击 *☰ > 集群管理*。
. 点击 *云凭据*。
. 单击*创建*。
. 点击*Amazon*。
. 输入云凭证的名称。
. 在*默认区域*字段中，选择您的集群节点将要所在的AWS区域。
. 输入您的AWS EC2 *访问密钥*和*秘密密钥*。
. 单击*创建*。

*结果：*您已创建用于在集群中部署节点的云凭证。

[#_create_your_cluster]
=== 创建您的集群

. 单击 *☰ > 集群管理*。
. 在*集群*页面，点击*创建*。
. 切换开关到*RKE2/K3s*。
. 点击*Amazon EC2*。
. 选择一个*云凭证*（如果存在多个）。否则，它会被预选。
. 输入*集群名称*。
. 为每个Kubernetes角色创建一个机器池。请参考{xref-infra-providers}#_node_roles[最佳实践]，以获取角色分配和数量的建议。
 .. 为每个机器池定义机器配置。请参考{xref-aws-machine-configuration}[EC2机器配置参考]以获取有关配置选项的信息。
. 使用*集群配置*选择要安装的Kubernetes版本、使用的网络提供商以及是否希望启用项目网络隔离。有关配置集群的帮助，请参考{xref-rke2-config}[RKE2]和{xref-k3s-config}[K3s]集群配置参考。
. 使用*成员角色*配置集群的用户授权。点击*添加成员*以添加可以访问集群的用户。使用*角色*下拉菜单为每个用户设置权限。
. 单击*创建*。

*结果：*

您的集群已创建并被分配为*正在配置*状态。Rancher 正在启动您的集群。

在集群状态更新为*活动*后，您可以访问您的集群。

*活动*集群被分配两个项目：

* `Default`，包含`default`名称空间
* `System`，包含 `cattle-system`、`traefik`、`kube-public` 和 `kube-system` 名称空间

[#_optional_next_steps]
=== 可选的后续步骤

创建集群后，您可以通过Rancher UI访问它。作为最佳实践，我们建议设置这些访问集群的替代方法：

* *使用kubectl CLI访问您的集群：*按照{xref-access-cluster-kubectl}#_从工作站使用kubectl访问集群[这些步骤]，在您的工作站上使用kubectl访问集群。在这种情况下，您将通过Rancher服务器的身份验证代理进行身份验证，然后Rancher将连接您到下游集群。此方法允许您在没有Rancher UI的情况下管理集群。
* *使用授权的集群端点通过kubectl CLI访问您的集群：*按照{xref-access-cluster-kubectl}#_直接与下游集群进行身份验证[这些步骤]，直接使用kubectl访问您的集群，而无需通过Rancher进行身份验证。我们建议设置这种替代方法来访问您的集群，以便在无法连接到Rancher的情况下，您仍然可以访问集群。

[#_iam_policies]
== IAM策略

[#_example_iam_policy]
=== 示例IAM策略

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:Describe*",
                "ec2:ImportKeyPair",
                "ec2:CreateKeyPair",
                "ec2:CreateSecurityGroup",
                "ec2:CreateTags",
                "ec2:DeleteKeyPair",
                "ec2:ModifyInstanceMetadataOptions"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "ec2:RunInstances"
            ],
            "Resource": [
                "arn:aws:ec2:REGION::image/ami-*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:instance/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:placement-group/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:volume/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:subnet/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:key-pair/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:network-interface/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:security-group/*"
            ]
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "ec2:RebootInstances",
                "ec2:TerminateInstances",
                "ec2:StartInstances",
                "ec2:StopInstances"
            ],
            "Resource": "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:instance/*"
        }
    ]
}
----

[#_example_iam_policy_with_passrole]
=== 带有PassRole的示例IAM策略

[,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:Describe*",
                "ec2:ImportKeyPair",
                "ec2:CreateKeyPair",
                "ec2:CreateSecurityGroup",
                "ec2:CreateTags",
                "ec2:DeleteKeyPair",
                "ec2:ModifyInstanceMetadataOptions"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "iam:PassRole",
                "ec2:RunInstances"
            ],
            "Resource": [
                "arn:aws:ec2:REGION::image/ami-*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:instance/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:placement-group/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:volume/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:subnet/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:key-pair/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:network-interface/*",
                "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:security-group/*",
                "arn:aws:iam::AWS_ACCOUNT_ID:role/YOUR_ROLE_NAME"
            ]
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "ec2:RebootInstances",
                "ec2:TerminateInstances",
                "ec2:StartInstances",
                "ec2:StopInstances"
            ],
            "Resource": "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:instance/*"
        }
    ]
}
----

[#_example_iam_policy_to_allow_encrypted_ebs_volumes]
=== 允许加密EBS卷的示例IAM策略

[,json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "kms:Decrypt",
        "kms:GenerateDataKeyWithoutPlaintext",
        "kms:Encrypt",
        "kms:DescribeKey",
        "kms:CreateGrant",
        "ec2:DetachVolume",
        "ec2:AttachVolume",
        "ec2:DeleteSnapshot",
        "ec2:DeleteTags",
        "ec2:CreateTags",
        "ec2:CreateVolume",
        "ec2:DeleteVolume",
        "ec2:CreateSnapshot"
      ],
      "Resource": [
        "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:volume/*",
        "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:instance/*",
        "arn:aws:ec2:REGION:AWS_ACCOUNT_ID:snapshot/*",
        "arn:aws:kms:REGION:AWS_ACCOUNT_ID:key/KMS_KEY_ID"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:DescribeInstances",
        "ec2:DescribeTags",
        "ec2:DescribeVolumes",
        "ec2:DescribeSnapshots"
      ],
      "Resource": "*"
    }
  ]
}
----
