= EC2机器配置参考
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-12-10
:page-revdate: {revdate}
:community-path: 参考指南/集群配置/下游集群配置/机器配置/amazon-ec2.adoc 
:product-path: cluster-deployment/infra-providers/aws/machine-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
endif::[]

有关EC2节点的更多详细信息，请参阅 https://aws.amazon.com/ec2[EC2管理控制台]的官方文档。

[#_basic_options]
== 基本选项

[#_region]
=== 区域

构建集群的地理 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html[区域]。

[#_zone]
=== 区域

构建集群的 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-availability-zones[可用区]，这是区域内的一个隔离位置。

[#_instance_type]
=== 实例类型

决定硬件特性的 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html[实例类型]，用于配置您的集群。

[#_root_disk_size]
=== 根磁盘大小

为您的 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html[根设备]配置大小（以 GB 为单位）。

[#_vpc_subnet]
=== VPC/Subnet

将资源添加到的 https://docs.aws.amazon.com/vpc/latest/userguide/configure-your-vpc.html[VPC]或特定的 https://docs.aws.amazon.com/vpc/latest/userguide/configure-subnets.html[子网，即您VPC中的一个IP地址范围。]

[#_iam_instance_profile_name]
=== IAM实例配置文件名称

用于将IAM角色传递给EC2实例的 https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html[实例配置文件]的名称。

[#_advanced_options]
== 高级选项

[#_ami_id]
=== AMI ID

用于您集群中节点的 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html[亚马逊机器镜像]。

[#_ssh_username_for_ami]
=== AMI的SSH用户名

用于连接到您启动的实例的用户名。有关所选AMI的默认用户名，请参阅 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connection-prereqs.html[这里]。对于未列出的AMI，请与AMI提供商联系。

[#_security_group]
=== 安全组

选择默认安全组或配置安全组。

请参阅{xref-port-reqs}#_rancher_aws_ec2_security_group[使用节点驱动程序时的Amazon EC2安全组]，以查看在`rancher-nodes`安全组中创建了哪些规则。

[#_ebs_root_volume_type]
=== EBS根卷类型

用于根设备的 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html[EBS卷类型]。

[#_encrypt_ebs_volume]
=== 加密EBS卷

启用 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html[亚马逊EBS加密]。

[#_request_spot_instance]
=== 请求现货实例

启用选项以 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html[请求现货实例]并指定您愿意支付的每小时最大实例价格。

[#_use_only_private_address]
=== 仅使用私有地址

启用选项仅使用 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html[私有地址]。

[#_ebs_optimized_instance]
=== EBS优化实例

使用 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html[EBS优化实例]。

[#_allow_access_to_ec2_metadata]
=== 允许访问EC2元数据

启用对 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html[EC2元数据]的访问。

[#_use_tokens_for_metadata]
=== 使用元数据令牌

使用 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html[实例元数据服务版本2（IMDSv2）]，这是一种基于令牌的方法来访问元数据。

[#_add_tag]
=== 添加标签

使用 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html[标签]添加元数据以对资源进行分类。

[#_ipv6_address_count]
=== IPv6地址数量

指定要分配给实例网络接口的IPv6地址数量。

[#_ipv6_address_only]
=== 仅IPv6地址

如果实例应仅使用IPv6，请启用此选项。仅IPv6的VPC或子网需要此项。启用后，实例将仅使用IPv6作为其唯一地址，且IPv6地址数量必须大于零。

[#_http_protocol_ipv6]
=== HTTP 协议 IPv6

启用或禁用实例元数据服务的 IPv6 端点。

[#_enable_primary_ipv6]
=== 启用主 IPv6

启用此选项以将第一个分配的 IPv6 地址指定为主地址。这确保实例具有一致且不变的 IPv6 地址。它不控制是否分配 IPv6 地址。
