= EC2节点模板配置
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-03-16
:page-revdate: {revdate}
:community-path: 参考指南/集群配置/下游集群配置/节点模板配置/amazon-ec2.adoc 
:product-path: cluster-deployment/infra-providers/aws/node-template-configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-set-up-cloud-providers: xref:cluster-deployment/set-up-cloud-providers/set-up-cloud-providers.adoc
:xref-port-reqs: xref:installation-and-upgrade/requirements/port-requirements.adoc
:xref-cloud-credentials: xref:rancher-admin/users/settings/manage-cloud-credentials.adoc
:xref-infra-aws: xref:cluster-deployment/infra-providers/aws/aws.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-set-up-cloud-providers: xref:如何指南/新用户指南/在Rancher中设置Kubernetes集群/设置云提供商/index.adoc
:xref-port-reqs: xref:getting-started/installation-and-upgrade/installation-requirements/port-requirements.adoc
:xref-cloud-credentials: xref:reference-guides/user-settings/manage-cloud-credentials.adoc
:xref-infra-aws: xref:如何指南/新用户指南/使用Rancher启动Kubernetes/在基础设施提供商中使用新节点/创建Amazon EC2集群.adoc
endif::[]

有关EC2和节点的更多详细信息，请参阅 https://aws.amazon.com/ec2[EC2管理控制台]的官方文档。

[#_region]
== 区域

在*区域*字段中，选择您在创建云凭据时使用的相同区域。

[#_cloud_credentials]
== 云凭据

您的AWS账户访问信息，存储在{xref-cloud-credentials}[云凭据]中。

请参见 https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey[亚马逊文档：创建访问密钥]，了解如何创建访问密钥和秘密密钥。

请参见 https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html#access_policies_create-start[亚马逊文档：创建IAM策略（控制台）]，了解如何创建IAM策略。

请参见 https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_change-permissions.html#users_change_permissions-add-console[亚马逊文档：向用户添加权限（控制台）]，了解如何附加IAM。

请查看我们的三个示例JSON策略：

* {xref-infra-aws}#_example_iam_policy[Example IAM Policy]
* {xref-infra-aws}#_example_iam_policy_with_passrole[带有PassRole的示例IAM策略]（如果您想使用{xref-set-up-cloud-providers}[Kubernetes云提供商]或想将IAM控制文件传递给实例，则需要）
* {xref-infra-aws}#_example_iam_policy_to_allow_encrypted_ebs_volumes[允许加密EBS卷的示例IAM策略]策略给用户。

[#_authenticate_configure_nodes]
== 认证与配置节点

为您的集群选择可用区和网络设置。

[#_security_group]
== 安全组

选择默认安全组或配置安全组。

请参阅{xref-port-reqs}#_rancher_aws_ec2_security_group[使用节点驱动程序时的Amazon EC2安全组]，以查看在`rancher-nodes`安全组中创建了哪些规则。

如果您为EC2实例提供自己的安全组，请注意Rancher不会修改它。因此，您需要确保您的安全组设置为允许{xref-port-reqs}#_ports_for_rancher_server_nodes_on_rke2[为Rancher配置实例所需的端口]。有关使用安全组控制EC2实例的入站和出站流量的更多信息，请参阅 https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#WorkingWithSecurityGroups[这里]。

[#_instance_options]
== 实例选项

配置将要创建的实例。确保为配置的AMI配置正确的*SSH用户*。所选区域可能不支持默认实例类型。在这种情况下，您必须选择一个确实存在的实例类型，否则会出现错误，说明请求的配置不受支持。

如果您需要传递*IAM控制文件名称*（不是ARN），例如，当您想使用{xref-set-up-cloud-providers}[Kubernetes云提供商]时，您需要在您的策略中添加额外的权限。请参阅 {xref-infra-aws}#_example_iam_policy_with_passrole[示例 IAM 策略与 PassRole] 以获取示例策略。

[#_engine_options]
== 引擎选项

在节点模板的 *引擎选项* 部分，您可以配置容器守护程序。您可能想要指定容器版本或容器镜像注册表的镜像。
