= Actualización de Cargas de Trabajo
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-resources-setup/workloads-and-pods/upgrade-workloads.adoc 
:product-path: cluster-admin/kubernetes-resources/workloads-and-pods/upgrade-workloads.adoc

Cuando se lanza una nueva versión de una imagen de aplicación en Docker Hub, puedes actualizar cualquier carga de trabajo que esté ejecutando una versión anterior de la aplicación a la nueva.

. En la esquina superior izquierda, haz clic en *☰ > Gestión de Clústeres*.
. Ve al clúster donde deseas actualizar una carga de trabajo y haz clic en *Explorar*.
. En la barra de navegación izquierda, haz clic en *Carga de Trabajo*.
. Encuentra la carga de trabajo que deseas actualizar y selecciona *⋮ > Editar Configuración*.
. Actualiza la *Imagen del Contenedor* y cualquier opción que desees cambiar.
. Revisa y edita la *Directiva de Escalado y Actualización* de la carga de trabajo.
+
Estas opciones controlan cómo se realiza la actualización a los contenedores que están actualmente en ejecución. Por ejemplo, para ampliaciones escalables, puedes elegir si deseas detener los pods antiguos antes de desplegar los nuevos, o viceversa, así como el tamaño del lote de actualización.

. Haz clic en *Guardar*.

*Resultado:* La carga de trabajo comienza a actualizar sus contenedores, según tus especificaciones. Ten en cuenta que aumentar la escala de la ampliación o actualizar la directiva de actualización/escalado no resultará en la recreación de los pods.
