= Ativar Alertas para {rancher-product-name} Compliance
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: procedimentos/guias-avancados-do-usuario/guias-de-varredura-de-conformidade/ativar-alertas-para-rancher-compliance.adoc 
:product-path: security/compliance-scans/enable-alerting-for-rancher-compliance.adoc
ifeval::["{build-type}" != "community"]
:xref-receivers: xref:observability/monitoring-and-dashboards/configuration/receivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-receivers: xref:reference-guides/monitoring-v2-configuration/receivers.adoc
endif::[]

Os alertas podem ser configurados para serem enviados para uma varredura que é executada em um cronograma.

[NOTE]
.Pré-requisitos:
====

Antes de ativar os alertas para `rancher-compliance`, certifique-se de instalar o aplicativo `rancher-monitoring` e configurar os Receptores e Rotas. Para mais informações, consulte {xref-receivers}[esta seção.]

Ao configurar as rotas para os alertas de `rancher-compliance`, você pode especificar a correspondência usando o par chave-valor `job: rancher-compliance-scan`. Um exemplo de configuração de rota é {xref-receivers}#_example_route_config_for_compliance_scan_alerts[aqui.]
====


Ao instalar ou atualizar o `rancher-compliance` Helm chart, defina a seguinte flag como `true` no `values.yaml`:

[,yaml]
----
alerts:
  enabled: true
----
