= Executar uma Varredura
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/compliance-scan-guides/run-a-scan.adoc 
:product-path: security/compliance-scans/run-a-scan.adoc
:experimental:

Quando um recurso personalizado do ClusterScan é criado, ele inicia uma nova varredura de conformidade no cluster utilizando o arquivo de controle ClusterScan escolhido.

[NOTE]
====
Atualmente, há uma limitação de executar apenas uma varredura de conformidade por vez para um cluster. Se você criar vários recursos personalizados ClusterScan, eles serão executados um após o outro pelo operador, e até que uma varredura termine, os demais recursos personalizados ClusterScan estarão no estado "Pendente".
====


Para executar uma varredura,

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster onde você deseja executar uma varredura de conformidade e clique em *Explorar*.
. Clique em *Conformidade > Varredura*.
. Clique em *Criar*.
. Escolha um arquivo de controle de varredura de cluster. O arquivo de controle determina qual versão do CIS Benchmark será utilizada e quais testes serão realizados. Se você escolher o arquivo de controle Padrão, o Operador de Conformidade escolherá um arquivo de controle aplicável ao tipo de cluster Kubernetes em que está instalado.
. Clique em *Criar*.

*Resultado:* Um relatório é gerado com os resultados da varredura. Para ver os resultados, clique no nome da varredura que aparece.
