= Executar uma varredura periodicamente em um agendamento
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/compliance-scan-guides/run-a-scan-periodically-on-a-schedule.adoc 
:product-path: security/compliance-scans/run-a-scan-periodically-on-a-schedule.adoc
:experimental:

Para executar uma Varredura de Cluster em um agendamento,

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página *Clusters*, vá para o cluster onde você deseja executar uma varredura de Conformidade e clique em *Explorar*.
. Clique em *Conformidade > Varredura*.
. Escolha um arquivo de controle de varredura de cluster. O arquivo de controle determina qual versão do CIS Benchmark será utilizada e quais testes serão realizados. Se você escolher o arquivo de controle Padrão, o Operador de Conformidade escolherá um arquivo de controle aplicável ao tipo de cluster Kubernetes em que está instalado.
. Escolha a opção *Executar varredura em um agendamento*.
. Insira uma expressão de cron válida no campo *Agendamento*.
. Escolha uma contagem de *Retenção*, que indica o número de relatórios mantidos para esta varredura recorrente. Por padrão, essa contagem é 3. Quando esse limite de retenção for atingido, relatórios mais antigos serão excluídos.
. Clique em *Criar*.

*Resultado:* A varredura é executada e reprogramada para rodar de acordo com o agendamento cron fornecido. O valor *Próxima Varredura* indica a próxima vez que esta varredura será executada novamente.

Um relatório é gerado com os resultados da varredura toda vez que a varredura é executada. Para ver os resultados mais recentes, clique no nome da varredura que aparece.

Você também pode ver os relatórios anteriores escolhendo o relatório no dropdown *Relatórios* na página de detalhes da varredura.
