= Ver Relatórios
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-26
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/compliance-scan-guides/view-reports.adoc 
:product-path: security/compliance-scans/view-reports.adoc
:experimental:

Para visualizar os relatórios de varredura de Conformidade gerados,

. No canto superior esquerdo, clique em *☰ > Gerenciamento de Cluster*.
. Na página **Clusters**, vá para o cluster onde você deseja executar uma varredura de Conformidade e clique em *Explorar*.
. Clique em *Conformidade > Varredura*.
. A página *Varreduras* mostrará os relatórios gerados. Para ver um relatório detalhado, vá até um relatório de varredura e clique no nome.

É possível baixar o relatório da lista de Varreduras ou da página de detalhes da varredura.

Para obter a versão detalhada dos resultados da varredura de conformidade, execute o seguinte comando no cluster que foi escaneado. Observe que a varredura deve ser concluída antes que isso possa ser feito.

[,shell]
----
export REPORT="scan-report-name"
kubectl get clusterscanreports.compliance.cattle.io $REPORT -o json |jq ".spec.reportJSON | fromjson" | jq -r ".actual_value_map_data" | base64 -d | gunzip | jq .
----
