= Configuration du modèle de nœud DigitalOcean
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: guides-de-référence/configuration-cluster/configuration-cluster-en-aval/configuration-modèle-nœud/digitalocean.adoc 
:product-path: cluster-deployment/infra-providers/digitalocean/node-template-configuration.adoc

Les informations d'accès au compte sont stockées en tant qu'identifiant cloud. Les identifiants cloud sont stockés en tant que secrets Kubernetes. Plusieurs modèles de nœuds peuvent utiliser le même identifiant cloud. Vous pouvez utiliser un identifiant cloud existant ou en créer un nouveau.

[#_droplet_options]
== Options de Droplet

Les *Options de Droplet* provisionnent la région géographique et les spécifications de votre cluster.

[#_docker_daemon]
== Daemon Docker

Si vous utilisez Docker, les options de configuration du https://docs.docker.com/engine/docker-overview/#the-docker-daemon[daemon Docker] incluent{nbsp}:

* *Libellés :* Pour des informations sur les libellés, référez-vous à la https://docs.docker.com/config/labels-custom-metadata/[documentation des libellés d'objet Docker.]
* *URL d'installation de Docker Engine :* Détermine quelle version de Docker sera installée sur l'instance.
* *Miroirs de registre :* Miroir de registre Docker à utiliser par le daemon Docker
* *Autres options avancées :* Référez-vous à la https://docs.docker.com/engine/reference/commandline/dockerd/[référence des options du daemon Docker].
