= Rancher for AWS
:page-languages: [en, zh]
:revdate: 2026-06-17
:page-revdate: {revdate}
:community-path: getting-started/quick-start-guides/deploy-rancher-manager/aws-marketplace.adoc 
:product-path: installation-and-upgrade/quick-start/deploy-rancher/aws-marketplace.adoc
:description: Learn about Rancher for AWS from the AWS Marketplace listing.
ifeval::["{build-type}" != "community"]
:xref-qs-rancher-on-amazon-eks: xref:installation-and-upgrade/hosted-kubernetes/rancher-on-amazon-eks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-qs-rancher-on-amazon-eks: xref:getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks.adoc
endif::[]

SUSE Rancher for AWS (SRA/SRFA) is a fully managed Software-as-a-Service (SaaS) offering available through the AWS Marketplace. It provides a centralized control plane to manage, monitor, and scale Kubernetes clusters within an AWS environment.

For deployment prerequisites, architecture requirements, and subscription details, refer to the https://aws.amazon.com/marketplace/pp/prodview-yrzugbpzuukww[AWS Marketplace listing]. For more information, refer to the https://documentation.suse.com/cloudnative/rancher-srfa/[SUSE Rancher for AWS documentation].

[NOTE]
====
SUSE Rancher for AWS is an offering distinct from deploying and managing the Rancher server manually on Amazon EKS. If you intend to install and manage your own Rancher deployment on an EKS cluster, refer to {xref-qs-rancher-on-amazon-eks}[Installing Rancher on Amazon EKS].
====
