= Référence de configuration du cluster AKS
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/rancher-server-configuration/aks-cluster-configuration.adoc 
:product-path: cluster-deployment/hosted-kubernetes/aks/configuration.adoc
ifeval::["{build-type}" != "community"]
:xref-manage-rbac: xref:rancher-admin/utilisateurs/authn-et-authz/gerer-le-controle-d-acces-en-fonction-du-role-rbac/gerer-le-controle-d-acces-en-fonction-du-role-rbac.adoc
:xref-ds-aks-deploy: xref:cluster-deployment/hosted-kubernetes/aks/aks.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-manage-rbac: xref:how-to-guides/nouveaux-utilisateurs/autorisations-d'authentification-et-configuration-globale/gerer-le-controle-d-acces-en-fonction-du-role-rbac/index.adoc
:xref-ds-aks-deploy: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.adoc
endif::[]

[#_role_based_access_control]
== Contrôle d'accès en fonction du rôle

Lors de la création d'un cluster AKS dans la GUI de Rancher, le contrôle d'accès en fonction du rôle ne peut pas être désactivé. Si le contrôle d'accès en fonction du rôle est désactivé pour le cluster dans AKS, le cluster ne peut pas être enregistré ou importé dans Rancher. En pratique, cela signifie que les comptes locaux doivent être activés afin d'enregistrer un cluster AKS.

Rancher peut configurer des rôles de membre pour les clusters AKS de la même manière que pour tout autre cluster. Pour plus d'informations, voir la section sur {xref-manage-rbac}[le contrôle d'accès en fonction du rôle.]

[#_cloud_credentials]
== Identifiants Cloud

[NOTE]
====

Les informations de configuration dans cette section supposent que vous avez déjà configuré un principal de service pour Rancher. Pour des instructions étape par étape sur la façon de configurer le principal de service, voir {xref-ds-aks-deploy}#_prérequis_dans_microsoft_azure[cette section.]
====


[#_subscription_id]
=== ID d'abonnement

Pour obtenir l'ID d'abonnement, cliquez sur *Tous les services* dans la barre de navigation à gauche. Puis cliquez sur *Abonnements*. Allez au nom de l'abonnement que vous souhaitez associer à votre cluster Kubernetes et copiez l'*ID d'abonnement*.

[#_client_id]
=== ID du client

Pour obtenir l'ID client, allez sur le portail Azure, puis cliquez sur *Azure Active Directory*, puis cliquez sur *Enregistrements d'applications,* puis cliquez sur le nom du principal de service. L'ID client est indiqué sur la page de détails de l'enregistrement de l'application comme *ID d'application (client)*.

[#_client_secret]
=== Secret du client

Vous ne pouvez pas récupérer la valeur du secret client après sa création, donc si vous n'avez pas déjà de valeur de secret client, vous devrez créer un nouveau secret client.

Pour obtenir un nouveau secret client, allez sur le portail Azure, puis cliquez sur *Azure Active Directory*, puis cliquez sur *Enregistrements d'applications,* puis cliquez sur le nom du principal de service.

Puis cliquez sur *Certificats et secrets* et cliquez sur *Nouveau secret client*. Cliquez sur *Ajouter*. Puis copiez la *Valeur* du nouveau secret client.

[#_environment]
=== de confiance

Microsoft fournit plusieurs https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest[clouds] pour se conformer aux lois régionales, qui sont disponibles pour votre utilisation:

* AzurePublicCloud
* AzureGermanCloud
* AzureChinaCloud
* AzureUSGovernmentCloud

[#_account_access]
== Accès au compte

Dans cette section, vous devrez sélectionner un identifiant de cloud Azure existant ou en créer un nouveau.

Pour obtenir de l'aide sur la configuration de votre identifiant de cloud Azure, consultez <<_cloud_credentials,cette section.>>

[#_cluster_location]
== Emplacement du cluster

Configurez l'emplacement du cluster et des nœuds. Pour plus d'informations sur les zones de disponibilité pour AKS, consultez la https://docs.microsoft.com/en-us/azure/aks/availability-zones[documentation AKS.]

Les emplacements à haute disponibilité incluent plusieurs zones de disponibilité.

[#_cluster_options]
== Options de grappe

[#_kubernetes_version]
=== Kubernetes Version

Les versions Kubernetes disponibles sont récupérées dynamiquement depuis l'API Azure.

[#_cluster_resource_group]
=== Groupe de ressources du cluster

Un groupe de ressources est un conteneur qui contient des ressources liées pour une solution Azure. Le groupe de ressources peut inclure toutes les ressources de la solution, ou seulement celles que vous souhaitez gérer en tant que groupe. Vous décidez comment vous souhaitez allouer des ressources aux groupes de ressources en fonction de ce qui a le plus de sens pour votre organisation. En général, ajoutez des ressources qui partagent le même cycle de vie au même groupe de ressources afin de pouvoir les déployer, les mettre à jour et les supprimer facilement en tant que groupe.

Utilisez un groupe de ressources existant ou saisissez un nom de groupe de ressources et un groupe sera créé pour vous.

Utiliser un groupe de ressources contenant un cluster AKS existant créera un nouveau groupe de ressources. Azure AKS n'autorise qu'un seul cluster AKS par groupe de ressources.

Pour des informations sur la gestion des groupes de ressources, consultez la https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal[documentation Azure.]

[#_linux_admin_username]
=== Nom d'utilisateur administrateur Linux

Le nom d'utilisateur utilisé pour créer une connexion SSH aux nœuds Linux.

Le nom d'utilisateur par défaut pour les nœuds AKS est `azureuser`.

[#_ssh_public_key]
=== Clé publique SSH

La clé utilisée pour créer une connexion SSH aux nœuds Linux.

[#_tags]
=== Balises

Les balises de cluster peuvent être utiles si votre organisation utilise des balises comme moyen d'organiser les ressources à travers plusieurs services Azure. Ces balises ne s'appliquent pas aux ressources au sein du cluster.

[#_networking_options]
== Options de mise en réseau

[#_loadbalancer_sku]
=== SKU de LoadBalancer

Les équilibreurs de charge Azure prennent en charge à la fois les SKU standard et de base (unités de gestion des stocks).

Pour une comparaison des équilibreurs de charge standard et de base, consultez la https://docs.microsoft.com/en-us/azure/load-balancer/skus#skus[documentation officielle d'Azure.] Microsoft recommande l'équilibreur de charge standard.

L'équilibreur de charge standard est requis si vous avez sélectionné une ou plusieurs zones de disponibilité, ou si vous avez plus d'un pool de nœuds.

[#_network_policy]
=== Stratégie réseau

Tous les pods dans un cluster AKS peuvent envoyer et recevoir du trafic sans limitations, par défaut. Pour améliorer la sécurité, vous pouvez définir des règles qui contrôlent le flux de trafic. La fonctionnalité de politique réseau dans Kubernetes vous permet de définir des règles pour le trafic entrant et sortant entre les pods dans un cluster.

Azure fournit deux façons de mettre en œuvre la politique réseau. Vous choisissez une option de politique réseau lorsque vous créez un cluster AKS. L'option de politique ne peut pas être modifiée après la création du cluster{nbsp}:

* L'implémentation propre à Azure, appelée Azure Network Policies. La politique réseau Azure nécessite l'Azure CNI.
* Calico Network Policies, une solution open source de mise en réseau et de sécurité, fondée par https://www.tigera.io/[Tigera].

Vous pouvez également choisir de ne pas avoir de politique réseau.

Pour plus d'informations sur les différences entre les politiques réseau Azure et Calico et leurs capacités, consultez la https://docs.microsoft.com/en-us/azure/aks/use-network-policies#differences-between-azure-and-calico-policies-and-their-capabilities[documentation AKS.]

[#_dns_prefix]
=== Préfixe DNS

Entrez un préfixe DNS unique pour le FQDN du serveur API Kubernetes de votre cluster.

[#_network_plugin]
=== Plugin réseau

Il existe deux plugins réseau{nbsp}: kubenet et Azure CNI.

Le plugin Kubernetes https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/#kubenet[kubenet] est la configuration par défaut pour la création de clusters AKS. Lorsque kubenet est utilisé, chaque nœud du cluster reçoit une adresse IP routable. Les pods utilisent le NAT pour communiquer avec d'autres ressources en dehors du cluster AKS. Cette approche réduit le nombre d'adresses IP que vous devez réserver dans votre espace réseau pour les pods.

Avec le plugin de mise en réseau Azure CNI (avancé), les pods bénéficient d'une connectivité complète au réseau virtuel et peuvent être atteints directement via leur adresse IP privée depuis les réseaux connectés. Ce plugin nécessite plus d'espace d'adresses IP.

Pour plus d'informations sur les différences entre kubenet et Azure CNI, consultez la https://docs.microsoft.com/en-us/azure/aks/concepts-network#compare-network-models[documentation AKS.]

[#_http_application_routing]
=== Routage d'application HTTP

Lorsqu'il est activé, le produit complémentaire de routage d'application HTTP facilite l'accès aux applications déployées sur le cluster AKS. Elle déploie deux composants{nbsp}: un https://kubernetes.io/docs/concepts/services-networking/ingress/[contrôleur Ingress Kubernetes] et un https://github.com/kubernetes-incubator/external-dns[contrôleur External-DNS].

Pour plus d'informations, consultez la https://docs.microsoft.com/en-us/azure/aks/http-application-routing[documentation AKS.]

[#_set_authorized_ip_ranges]
=== Définir les plages d'adresses IP autorisées

Vous pouvez sécuriser l'accès au serveur API Kubernetes en utilisant des https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges#overview-of-api-server-authorized-ip-ranges[plages d'adresses IP autorisées.]

Le serveur API Kubernetes expose l'API Kubernetes. Ce composant fournit l'interaction pour les outils de gestion, tels que kubectl. AKS fournit un plan de contrôle de cluster à locataire unique avec un serveur API dédié. Par défaut, le serveur API se voit attribuer une adresse IP publique, et vous devez contrôler l'accès à celui-ci en utilisant RBAC basé sur Kubernetes ou Azure.

Pour sécuriser l'accès au plan de contrôle AKS et au serveur API, qui sont autrement accessibles au public, vous pouvez activer et utiliser des plages d'IP autorisées. Ces plages d'IP autorisées ne permettent qu'aux plages d'adresses IP définies de communiquer avec le serveur API.

Cependant, même si vous utilisez des plages d'adresses IP autorisées, vous devez toujours utiliser RBAC Kubernetes ou RBAC Azure pour autoriser les utilisateurs et les actions qu'ils demandent.

[#_container_monitoring]
=== Surveillance des conteneurs

La surveillance des conteneurs vous offre une visibilité sur les performances en collectant des métriques de mémoire et de processeur à partir des contrôleurs, des nœuds et des conteneurs disponibles dans Kubernetes via l'API des métriques. Les journaux des conteneurs sont également collectés. Après avoir activé la surveillance, les métriques et les journaux sont automatiquement collectés pour vous via une version conteneurisée de l'agent Log Analytics pour Linux. Les métriques sont écrites dans le magasin de métriques et les données de journal sont écrites dans le magasin de journaux associé à votre https://docs.microsoft.com/en-us/azure/azure-monitor/logs/log-query-overview[espace de travail Log Analytics].

[#_log_analytics_workspace_resource_group]
=== Groupe de ressources de l'espace de travail Log Analytics

Le https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview#resource-groups[groupe de ressources] contenant l'espace de travail Log Analytics. Vous devez créer au moins un espace de travail pour utiliser les journaux Azure Monitor.

[#_log_analytics_workspace_name]
=== Nom de l'espace de travail Log Analytics

Les données collectées par les journaux Azure Monitor sont stockées dans un ou plusieurs https://docs.microsoft.com/en-us/azure/azure-monitor/logs/design-logs-deployment[espaces de travail Log Analytics.] L'espace de travail définit l'emplacement géographique des données, les droits d'accès définissant quels utilisateurs peuvent accéder aux données, et les paramètres de configuration tels que le niveau de prix et la conservation des données.

Vous devez créer au moins un espace de travail pour utiliser les journaux Azure Monitor. Un seul espace de travail peut être suffisant pour toutes vos données de surveillance, ou vous pouvez choisir de créer plusieurs espaces de travail en fonction de vos besoins. Par exemple, vous pourriez avoir un espace de travail pour vos données de production et un autre pour les tests.

Pour plus d'informations sur les journaux Azure Monitor, consultez la https://docs.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs[documentation Azure.]

[#_support_private_kubernetes_service]
=== Support du service Kubernetes privé

En général, les nœuds de travail AKS n'obtiennent pas d'IP publiques, peu importe si le cluster est privé. Dans un cluster privé, le plan de contrôle n'a pas de point de terminaison public.

Rancher peut se connecter à un cluster AKS privé de deux manières.

La première façon de s'assurer que Rancher fonctionne sur le même https://docs.microsoft.com/en-us/azure/virtual-network/nat-overview[NAT] que les nœuds AKS.

La deuxième façon est d'exécuter une commande pour enregistrer le cluster avec Rancher. Une fois le cluster provisionné, vous pouvez exécuter la commande affichée depuis n'importe où où vous pouvez vous connecter à l'API Kubernetes du cluster. Cette commande est affichée dans une fenêtre contextuelle lorsque vous provisionnez un cluster AKS avec un point de terminaison API privé activé.

[NOTE]
====

Veuillez noter que lors de l'enregistrement d'un cluster AKS existant, le cluster peut prendre un certain temps, éventuellement des heures, pour apparaître dans la `Cluster To register`liste déroulante. Ce résultat sera basé sur la région.
====


Pour plus d'informations sur la connexion à un cluster privé AKS, consultez la https://docs.microsoft.com/en-us/azure/aks/private-clusters#options-for-connecting-to-the-private-cluster[documentation AKS.]

[#_node_pools]
== Pools de nœuds

[#_mode]
=== Mode

L'interface Azure permet aux utilisateurs de spécifier si un Pool de Nœuds Principal repose sur `system` (normalement utilisé pour les plans de contrôle) ou `user` (ce qui est généralement nécessaire pour Rancher).

Pour les Pools de Nœuds Principaux, vous pouvez spécifier le Mode, le Système d'exploitation, le Nombre et la Taille.

Les pools de nœuds système nécessitent toujours des nœuds en cours d'exécution, donc ils ne peuvent pas être réduits en dessous d'un nœud. Au moins un pool de nœuds système est requis.

Pour les pools de nœuds suivants, l'interface utilisateur de Rancher impose par défaut l'Utilisateur. Les pools de nœuds utilisateurs vous permettent de réduire à zéro nœud. Les pools de nœuds utilisateurs n'exécutent aucune partie du plan de contrôle Kubernetes.

AKS n'expose pas les nœuds qui exécutent les composants du plan de contrôle Kubernetes.

[#_availability_zones]
=== Zones de disponibilité

https://docs.microsoft.com/en-us/azure/availability-zones/az-overview[Les zones de disponibilité] sont des emplacements physiques uniques au sein d'une région. Chaque zone est composée d'un ou plusieurs centres de données équipés d'une alimentation, d'un refroidissement et d'un réseau indépendants.

Toutes les régions ne prennent pas en charge les zones de disponibilité. Pour une liste des régions Azure avec des zones de disponibilité, consultez la https://docs.microsoft.com/en-us/azure/availability-zones/az-region#azure-regions-with-availability-zones[documentation Azure.]

[#_vm_size]
=== Taille de la VM :

Choisissez une taille pour chaque VM dans le pool de nœuds. Pour des détails sur chaque taille de VM, consultez https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/[cette page.]

[#_os_disk_type]
=== Type de disque du système d'exploitation

Les nœuds dans le pool de nœuds peuvent avoir des disques gérés ou éphémères.

https://docs.microsoft.com/en-us/azure/virtual-machines/ephemeral-os-disks[Les disques éphémères du système d'exploitation] sont créés sur le stockage local de la machine virtuelle et ne sont pas sauvegardés sur le stockage Azure distant. Les disques éphémères du système d'exploitation fonctionnent bien pour les charges de travail sans état, où les applications tolèrent les échecs individuels de VM, mais sont plus affectées par le temps de déploiement de la VM ou le réimaging des instances de VM individuelles. Avec un disque éphémère du système d'exploitation, vous bénéficiez d'une latence en lecture et en écriture plus faible et d'un réimaging de VM plus rapide.

https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview[Les disques gérés par Azure] sont des volumes de stockage au niveau des blocs qui sont gérés par Azure et utilisés avec les machines virtuelles Azure. Les disques gérés sont conçus pour une disponibilité de 99,999%. Les disques gérés atteignent cela en vous fournissant trois répliques de vos données, permettant une grande durabilité.

[#_os_disk_size]
=== Taille du disque du système d'exploitation

La taille en Go pour le disque de chaque nœud.

[#_node_count]
=== Nombre de nœuds

Le nombre de nœuds dans le pool de nœuds. Le nombre maximum de nœuds peut être limité par votre https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits[abonnement Azure.]

[#_max_pods_per_node]
=== Max Pods par nœud

Le nombre maximum de pods par nœud est par défaut de 110 avec un maximum de 250.

[#_enable_auto_scaling]
=== Activer l'auto-scaling

Lorsque l'auto-scaling est activé, vous devrez entrer un nombre minimum et maximum de nœuds.

Lorsque l'auto-scaling est activé, vous ne pouvez pas mettre à l'échelle manuellement le pool de nœuds. L'échelle est contrôlée par l'autoscaler AKS.
