= Flux et ClusterFlows
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/logging/custom-resource-configuration/flows-and-clusterflows.adoc 
:product-path: observability/logging/custom-resource-configuration/flows-and-clusterflows.adoc
ifeval::["{build-type}" != "community"]
:xref-logging: xref:observability/logging/logging.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-logging: xref:integrations-in-rancher/logging/index.adoc
endif::[]

Consultez la https://kube-logging.github.io/docs/configuration/flow/[documentation de l'opérateur de journalisation] pour tous les détails sur la façon de configurer `Flows` et `ClusterFlows`.

Voir {xref-logging}#_The_Logging_Buffer_Overloads_Pods[Intégration de Rancher avec les services de journalisation{nbsp}: Dépannage] pour savoir comment résoudre les problèmes de mémoire liés au tampon de journalisation.

[#_flows]
== Flux

Un `Flow` définit quels journaux collecter et filtrer et vers quelle sortie envoyer les journaux.

Le `Flow` est une ressource dans un espace de noms, ce qui signifie que les journaux ne seront collectés que dans l'espace de noms où le `Flow` est déployé.

`Flows` peut être configuré en remplissant des formulaires dans l'interface utilisateur de Rancher.

Pour plus de détails sur la ressource personnalisée `Flow`, voir https://kube-logging.github.io/docs/configuration/crds/v1beta1/flow_types/[FlowSpec.]

[#_matches]
=== Correspond à

Les déclarations de correspondance sont utilisées pour sélectionner les conteneurs à partir desquels extraire les journaux.

Vous pouvez spécifier des déclarations de correspondance pour sélectionner ou exclure des journaux en fonction des étiquettes Kubernetes, des noms de conteneurs et des noms d'hôtes. Les déclarations de correspondance sont évaluées dans l'ordre dans lequel elles sont définies et sont traitées uniquement jusqu'à ce que la première règle de sélection ou d'exclusion correspondante s'applique.

Les déclarations de correspondance peuvent être configurées en remplissant les formulaires `Flow` ou `ClusterFlow` dans l'interface utilisateur de Rancher.

Pour des exemples détaillés sur l'utilisation de la déclaration de correspondance, voir la https://kube-logging.github.io/docs/configuration/log-routing/[documentation officielle sur le routage des journaux.]

[#_filters]
=== Filtres

Vous pouvez définir un ou plusieurs filtres dans un `Flow`. Les filtres peuvent effectuer diverses actions sur les journaux, telles que l'ajout de données, la transformation des journaux ou l'analyse des valeurs des enregistrements. Les filtres dans le `Flow` sont appliqués dans le même ordre qu'ils apparaissent dans la définition.

Pour une liste des filtres pris en charge par l'opérateur de journalisation, voir https://kube-logging.github.io/docs/configuration/plugins/filters/[la documentation officielle sur les filtres Fluentd].

Les filtres doivent être configurés en YAML.

[#_outputs]
=== Sorties

Ce `Output` recevra des journaux du `Flow`. Parce que le `Flow` est une ressource dans un espace de noms, le `Output` doit résider dans le même espace de noms que le `Flow`.

`Outputs` peut être référencé lors du remplissage des formulaires `Flow` ou `ClusterFlow` dans l'interface utilisateur de Rancher.

[#_clusterflows]
== ClusterFlows

Les déclarations de correspondance, filtres et `Outputs` sont configurés pour `ClusterFlows` de la même manière qu'ils sont configurés pour `Flows`. La principale différence est que le `ClusterFlow` est défini au niveau du cluster et peut configurer la collecte des journaux dans tous les espaces de noms.

`ClusterFlows` peut être configuré en remplissant des formulaires dans l'interface utilisateur de Rancher.

Après que `ClusterFlow` sélectionne les journaux de tous les espaces de noms dans le cluster, les journaux du cluster seront collectés et enregistrés dans le `ClusterOutput` sélectionné.

[#_yaml_example]
== Exemple YAML

L'exemple suivant `Flow` transforme les messages de journal de l'espace de noms par défaut et les envoie à un S3 `Output`:

[,yaml]
----
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  filters:
    - parser:
        remove_key_name_field: true
        parse:
          type: nginx
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
  localOutputRefs:
    - s3-output
  match:
    - select:
        labels:
          app: nginx
----
