= Azure マシン設定
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/azure.adoc 
:product-path: cluster-deployment/infra-providers/azure/machine-configuration.adoc

Azureに関する詳細は、公式の https://docs.microsoft.com/en-us/azure/?product=featured[Azureドキュメント]を参照してください。

[#_basic_options]
== 基本的なオプション

[#_environment]
=== 使用環境

Microsoftは、地域の法律に準拠するために複数の https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest[クラウド]を提供しており、利用可能です：

* AzurePublicCloud
* AzureGermanCloud
* AzureChinaCloud
* AzureUSGovernmentCloud

[#_location]
=== 場所

クラスターとノードの https://docs.microsoft.com/en-us/azure/virtual-machines/regions[場所]を設定します。

[#_resource_group]
=== Resource Group

リソースグループは、Azureソリューションに関連するリソースを保持するコンテナです。リソースグループには、ソリューションのすべてのリソースを含めるか、またはグループとして管理するリソースのみを含めることができます。組織にとって最も理にかなった方法に基づいて、リソースをリソースグループに割り当てる方法を決定します。一般的に、同じライフサイクルを共有するリソースを同じリソースグループに追加することで、グループとして簡単にデプロイ、更新、削除できます。

既存のリソースグループを使用するか、リソースグループ名を入力すると、新しいリソースグループが作成されます。

リソースグループの管理に関する情報は、 https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal[Azureドキュメントをご覧ください。]

[#_availability_set_unmanaged]
=== 可用性セット（管理されていない）

VMを追加する既存の https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview[可用性セット]の名前またはID。

[#_image]
=== イメージ

ARMリソース識別子として提供されるオペレーティングシステムイメージの名前。管理ディスクの使用が必要です。

[#_vm_size]
=== VMサイズ

ノードプール内の各VMのサイズを選択してください。各VMサイズの詳細については、 https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/[このページをご覧ください。]

[#_advanced_options]
== 詳細オプション

[#_fault_domain_count]
=== フォールトドメイン数

フォールトドメインは、共通の電源とネットワークスイッチを共有する仮想マシンのグループを定義します。可用性セットがすでに作成されている場合、フォールトドメイン数は無視されます。

フォールトドメインに関する詳細は、 https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview#how-do-availability-sets-work[こちらを参照してください]。

[#_update_domain_count]
=== アップデートドメイン数

アップデートドメインは、同時に再起動できる仮想マシンと基盤となる物理ハードウェアのグループを示します。可用性セットがすでに作成されている場合、アップデートドメイン数は無視されます。

アップデートドメインに関する詳細は、 https://docs.microsoft.com/en-us/azure/virtual-machines/availability-set-overview#how-do-availability-sets-work[こちらを参照してください]。

[#_purchase_plan]
=== 購入プラン

Azure Marketplaceの一部のVMイメージには、プランが必要です。該当する場合は、選択したイメージで使用するために、`publisher:product:plan`形式の購入プランを選択してください。

[#_subnet]
=== サブネット

新しいVNetを作成する際のサブネットの名前、または既存のものを参照する際の名前。

デフォルト: `docker-machine`

[#_subnet_prefix]
=== サブネットプレフィックス

新しいVNetをCIDR形式で作成する際に使用するサブネットIPアドレスプレフィックス。

デフォルト: `192.168.0.0/16`

[#_virtual_network]
=== 仮想ネットワーク

存在しない場合に使用または作成する https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview[仮想ネットワーク]。`[resourcegroup:]name`の形式で。

[#_public_ip_options]
=== パブリックIPオプション

[#_no_public_ip]
==== パブリックIPなし

パブリックIPアドレスを割り当てない。

[#_static_public_ip]
==== 静的パブリックIP

静的パブリックIPアドレスを割り当てる。

[#_use_private_ip]
=== プライベートIPを使用

静的プライベートIPアドレスを使用する。

[#_private_ip_address]
=== プライベートIPアドレス

使用する静的プライベートIPアドレスを設定する。

[#_network_security_group]
=== ネットワークセキュリティグループ

使用する https://docs.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview[ネットワークセキュリティグループ]。このテンプレートを使用するすべてのノードは、提供されたネットワークセキュリティグループを使用します。ネットワークセキュリティグループが提供されていない場合、各ノードのために新しいものが作成されます。

[#_dns_label]
=== DNSラベル

パブリックIPアドレスのためのユニークなDNS名ラベル。

[#_storage_type]
=== Storage Type

VMと一緒に使用する https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview[ストレージアカウント]のタイプ。オプションには、Standard LRS、Standard ZRS、Standard GRS、Standard RAGRS、およびPremium LRSが含まれます。

[#_use_managed_disks]
=== マネージドディスクを使用

https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview[Azure管理ディスク]は、Azureによって管理され、Azure仮想マシンで使用されるブロックレベルのストレージボリュームです。管理ディスクは、99.999%の可用性を目指して設計されています。管理ディスクは、データの3つのレプリカを提供することでこれを実現し、高い耐久性を確保します。

[#_managed_disk_size]
=== マネージドディスクのサイズ

各ノードのディスクのサイズ（GB単位）。

[#_ssh_username]
=== SSHユーザー名

ノードへのSSH接続を確立するために使用するユーザー名。

[#_open_port]
=== ポートを開く

指定されたポートでの受信トラフィックを開きます。既存のネットワークセキュリティグループを使用する場合、オープンポートは無視されます。

デフォルト: `2379/tcp, 2380/tcp, 6443/tcp, 9796/tcp, 10250/tcp, 10251/tcp, 10252/tcp, 10256/tcp` と `8472/udp, 4789/udp`
