name: Test Product deployment
run-name: Test Product deployment 

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - '*-maintenance'
      - 'release-notes-*'
    paths-ignore:
      - '**/README.md'

permissions:
  pull-requests: write

jobs:
  test-deploy:
    strategy:
      fail-fast: false
      matrix:
        playbook: ['playbook-product-local.yml', 'playbook-srfa-local.yml']
    uses: rancher/product-docs-common/.github/workflows/test-deploy-min.yml@45107dd493f5e14cfaab19c50b98df62598a5c5d # main
    secrets:
      token: ${{ github.token }}
    with:
      playbook-name: ${{ matrix.playbook }}
