name: Test Community deployment
run-name: Test Community deployment 

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  test-deploy:
    uses: rancher/product-docs-common/.github/workflows/test-deploy-min.yml@c5b3d015b5800313b1adbba3c8508fbaa4860852 # main
    secrets:
      token: ${{ github.token }}
    with:
      playbook-name: 'playbook-community-local.yml'
