name: Test Community deployment
run-name: Test Community deployment 

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  test-deploy:
    uses: rancher/product-docs-common/.github/workflows/test-deploy-min.yml@45107dd493f5e14cfaab19c50b98df62598a5c5d # main
    secrets:
      token: ${{ github.token }}
    with:
      playbook-name: 'playbook-community-local.yml'
