name: Tasks needing write permissions

on:
  workflow_run:
    workflows: ["Test Product deployment"]
    types: [completed]
jobs:
  write-tasks:
    uses: rancher/product-docs-common/.github/workflows/write-tasks.yml@e32c27a0885b518e48287bc201251a3d7f9e0a87 # main
