name: Tasks needing write permissions

on:
  workflow_run:
    workflows: ["Test deployment"]
    types: [completed]
jobs:
  write-tasks:
    uses: rancher/product-docs-common/.github/workflows/write-tasks.yml@e37ee6abff600fe8b90fa8d6ad41ec23d9c4b90c # main
