= 概述
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: integrations-in-rancher/harvester/overview.adoc 
:product-path: integrations/harvester/overview.adoc
ifeval::["{build-type}" != "community"]
:xref-experimental-features: xref:rancher-admin/experimental-features/experimental-features.adoc
:xref-provisioning-drivers: xref:rancher-admin/global-configuration/provisioning-drivers/provisioning-drivers.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-experimental-features: xref:how-to-guides/advanced-user-guides/enable-experimental-features/index.adoc
:xref-provisioning-drivers: xref:how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/index.adoc
endif::[]

在 Rancher v2.6.1 中引入的 https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/introduction/overview.html[{harvester-product-name}] 是一个基于 Kubernetes 的开源超融合基础设施 (HCI) 软件。Harvester 安装在裸机服务器上，提供集成虚拟化和分布式存储功能。尽管 Harvester 使用 Kubernetes 进行操作，但用户无需了解 Kubernetes 概念，使其成为更友好的应用程序。

[#_feature_flag]
== 功能标志

Harvester 功能标志用于管理对 Rancher 中虚拟化管理 (VM) 页面访问的权限，用户可以直接导航到 Harvester 集群并访问 Harvester UI。Harvester 功能标志默认启用。点击 {xref-experimental-features}[这里] 获取有关 Rancher 中功能标志的更多信息。

要导航到 Harvester 集群，请点击 *☰ > 虚拟化管理*。在 Harvester 集群页面，从列出的集群中点击一个以进入单个 Harvester 集群视图。

* 如果 Harvester 功能标志启用，则任何显示 Kubernetes 集群的页面或应用（例如 Fleet 的持续交付）中都不会显示 Harvester 集群。
* 如果 Harvester 功能标志禁用，并且导入了 Harvester 集群，则该集群将在集群管理页面的 Rancher 集群列表中显示。只有在功能标志关闭时，Harvester 集群才会显示在集群列表中。
* 通过 Harvester 集成，Harvester 集群现在可以作为集群类型 `Harvester` 导入到 Rancher 中。
* 用户只能在虚拟化管理页面导入 Harvester 集群。在集群管理页面导入集群不受支持，系统会发出警告，建议您返回 VM 页面进行操作。

[#__harvester_product_name_node_driver]
== {harvester-product-name} 节点驱动

https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/integrations/rancher/node-driver/node-driver.html[{harvester-product-name} 节点驱动] 在 Rancher 的 K3s 和 RKE2 选项中普遍可用。无论 Harvester 功能标志是否启用，节点驱动都可用。请注意，节点驱动默认关闭。用户只能在集群管理页面上创建 K3s 或 RKE2 集群。

Harvester 允许通过 Harvester UI 上传和显示 `.ISO` 镜像，但在 Rancher UI 中不支持。这是因为 `.ISO` 镜像通常需要额外设置，会干扰无需用户干预的干净部署，且通常不用于云环境中。

有关 Rancher 中节点驱动程序的更多信息，请参见 {xref-provisioning-drivers}#_node_drivers[Provisioning Drivers]。

[#_port_requirements]
== 端口要求

Harvester 集群的端口要求可以在 https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/installation-setup/requirements.html#_network_requirements[这里]找到。

此外，其他网络考虑因素如下：

* 请确保为虚拟机 VLAN 网络启用物理交换机的 VLAN 中继端口。
* 请按照网络设置指南 https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/networking/cluster-network.html[这里]操作。

对于其他客集群（如 K3s 和 RKE2）的端口要求，请参见 https://documentation.suse.com/cloudnative/virtualization/{harvester-docs-version}/en/installation-setup/requirements.html#_port_requirements_for_k3s_or_rkerke2_clusters[这些文档]。
