= Running on ARM64 Mixed Architecture (Experimental)
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-07
:page-revdate: {revdate}
:community-path: how-to-guides/advanced-user-guides/enable-experimental-features/rancher-on-arm64.adoc 
:product-path: rancher-admin/experimental-features/rancher-on-arm64.adoc
ifeval::["{build-type}" != "community"]
:xref-rke2-config: xref:cluster-deployment/configuration/rke2.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-rke2-config: xref:reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.adoc
endif::[]

[CAUTION]
====
Running on an ARM64 mixed architecture platform is currently an experimental feature and is not yet officially supported in Rancher. Therefore, we do not recommend using ARM64 mixed architecture based nodes in a production environment.
====

The following options are available when using an ARM64 platform:

* Create custom cluster and adding ARM64 based node(s)
 ** Kubernetes cluster version must be 1.12 or higher
* Importing clusters that contain ARM64 based nodes
 ** Kubernetes cluster version must be 1.12 or higher

Depending on your cluster provisioning refer to {xref-rke2-config}[RKE2 cluster configuration options] or xref:cluster-deployment/configuration/k3s.adoc[K3s cluster configuration options] for more information.

The following features are not tested:

* Monitoring, alerts, notifiers, pipelines and logging
* Launching apps from the catalog
