= Clusters de Kubernetes na {rancher-product-name} configuração
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2026-05-05
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/index.adoc 
:product-path: cluster-deployment/cluster-deployment.adoc
:description: Provisionamento de clusters de Kubernetes
ifeval::["{build-type}" != "community"]
:xref-launch-k8s-with-rancher: xref:cluster-deployment/launch-kubernetes-with-rancher.adoc
:xref-infra-providers: xref:cluster-deployment/infra-providers/infra-providers.adoc
:xref-register-clusters: xref:cluster-deployment/register-existing-clusters.adoc
:xref-custom-clusters: xref:cluster-deployment/custom-clusters/custom-clusters.adoc
:xref-hosted-k8s-clusters: xref:cluster-deployment/hosted-kubernetes/hosted-kubernetes.adoc
:xref-k8s-concepts: xref:sobre-rancher/conceitos.adoc
:xref-rancher-architecture: xref:sobre-rancher/arquitetura/arquitetura.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-launch-k8s-with-rancher: xref:how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc
:xref-infra-providers: xref:guias-de-procedimentos/guias-para-novos-usuarios/lançar-kubernetes-com-rancher/utilizar-novos-nós-em-um-infra-provider/index.adoc
:xref-register-clusters: xref:how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.adoc
:xref-custom-clusters: xref:guias-de-referência/configuração-do-cluster/configuração-do-servidor-rancher/utilizar-nós-existentes/index.adoc
:xref-hosted-k8s-clusters: xref:guias-de-procedimentos/guias-para-novos-usuários/clusters-kubernetes-no-rancher/configuração-clusters-a-partir-de-provedores-kubernetes-hospedados/index.adoc
:xref-k8s-concepts: xref:reference-guides/kubernetes-concepts.adoc
:xref-rancher-architecture: xref:reference-guides/rancher-manager-architecture/index.adoc
endif::[]

O Rancher simplifica a criação de clusters permitindo que você os crie através da interface do Rancher em vez de alternativas mais complexas. O Rancher oferece várias opções para lançar um cluster. Use a opção que melhor se adapta ao seu caso de uso.

Esta seção assume uma familiaridade básica com Docker e Kubernetes. Para uma breve explicação de como os componentes do Kubernetes trabalham juntos, consulte a página {xref-k8s-concepts}[conceitos].

Para uma visão geral conceitual de como o servidor Rancher provisiona clusters e quais ferramentas ele usa para isso, consulte a página de {xref-rancher-architecture}[arquitetura].

[#_cluster_management_capabilities_by_cluster_type]
== Capacidades de Gerenciamento de Clusters por Tipo de Cluster

A tabela a seguir resume as opções e configurações disponíveis para cada tipo de cluster:

ifeval::["{build-type}" != "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table.adoc[]
endif::[]
ifeval::["{build-type}" == "srfa"]
include::shared:ROOT:partial$en/cluster-capabilities-updated-table-srfa.adoc[]
endif::[]

[#_setting_up_clusters_in_a_hosted_kubernetes_provider]
== Configurando Clusters em um Provedor Kubernetes Hospedado

ifeval::["{build-type}" != "srfa"]
Neste cenário, o Rancher não provisiona Kubernetes porque ele é instalado por provedores como Google Kubernetes Engine (GKE), Amazon Elastic Container Service for Kubernetes ou Azure Kubernetes Service.
endif::[]
ifeval::["{build-type}" == "srfa"]
Neste cenário, o Rancher não provisiona Kubernetes porque ele é instalado pelo Amazon Elastic Container Service for Kubernetes.
endif::[]

ifeval::["{build-type}" != "srfa"]
Se você usar um provedor Kubernetes como o Google GKE, o Rancher se integra às suas APIs de nuvem, permitindo que você crie e gerencie o controle de acesso com base em função para o cluster hospedado a partir da interface do Rancher.
endif::[]
ifeval::["{build-type}" == "srfa"]
Se você usar um provedor Kubernetes, o Rancher se integra às suas APIs de nuvem, permitindo que você crie e gerencie o controle de acesso com base em função para o cluster hospedado a partir da interface do Rancher.
endif::[]

Para mais informações, consulte a seção sobre {xref-hosted-k8s-clusters}[clusters Kubernetes hospedados.]

[#_launching_kubernetes_with_rancher]
== Lançando Kubernetes com o Rancher

O Rancher usa https://docs.rke2.io/[RKE2] ou https://docs.k3s.io/[K3s] como uma biblioteca ao provisionar Kubernetes em seus próprios nós. RKE2 é o instalador leve de Kubernetes do Rancher.

Em clusters RKE2, o Rancher gerencia a implantação do Kubernetes. Esses clusters podem ser implantados em qualquer servidor bare metal, provedor de nuvem ou plataforma de virtualização.

Se você já tem um nó que deseja adicionar a um cluster RKE2, pode adicioná-lo ao cluster executando um contêiner de agente RKE2 do Rancher nele.

Para mais informações, consulte {xref-launch-k8s-with-rancher}[Lançando Kubernetes com o Rancher].

[#_launching_kubernetes_and_provisioning_nodes_in_an_infrastructure_provider]
=== Iniciando o Kubernetes e Provisionando Nós em um Provedor de Infraestrutura

ifeval::["{build-type}" != "srfa"]
O Rancher pode provisionar dinamicamente nós em provedores de infraestrutura como Amazon EC2, DigitalOcean, Azure ou vSphere, e então instalar o Kubernetes neles.
endif::[]
ifeval::["{build-type}" == "srfa"]
O Rancher pode provisionar dinamicamente nós em provedores de infraestrutura como Amazon EC2, e então instalar o Kubernetes neles.
endif::[]

Um benefício de usar nós hospedados por um provedor de infraestrutura é que, se um nó perder conectividade com o cluster, o Rancher pode substituí-lo automaticamente, mantendo assim a configuração esperada do cluster.

Para mais informações, consulte {xref-infra-providers}[Lançando o Kubernetes em Novos Nós em um Provedor de Infraestrutura]

[#_launching_kubernetes_on_existing_custom_nodes]
=== Lançando Kubernetes em nós personalizados existentes

Ao configurar esse tipo de cluster, o Rancher instala o Kubernetes em nós existentes {xref-custom-clusters}[personalizados,] o que cria um cluster personalizado.

Você pode trazer quaisquer nós que desejar para o Rancher e usá-los para criar um cluster.

Esses nós incluem servidores bare metal locais, máquinas virtuais hospedadas na nuvem ou máquinas virtuais locais.

[#_registering_existing_clusters]
== Registrando Clusters Existentes

O recurso de registro de cluster substitui o recurso de importar clusters.

O registro de clusters EKS agora oferece benefícios adicionais. Na maior parte, clusters EKS registrados e clusters EKS criados no Rancher são tratados da mesma forma na interface do Rancher, exceto pela exclusão.

Quando você exclui um cluster EKS que foi criado no Rancher, o cluster é destruído. Quando você exclui um cluster EKS que foi registrado no Rancher, ele é desconectado do servidor Rancher, mas ainda existe e você pode acessá-lo da mesma forma que fazia antes de ser registrado no Rancher.

Para mais informações, consulte {xref-register-clusters}[Registrando Clusters Existentes].

[#_programmatically_creating_clusters]
== Criando Clusters Programaticamente

A maneira mais comum de implantar clusters de Kubernetes programaticamente através do Rancher é usando o provedor Terraform Rancher2. Consulte a documentação para https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster[criar clusters com Terraform].

ifeval::["{build-type}" != "srfa"]
Clusters EKS, GKE e AKS podem ser criados ou importados com Terraform.
endif::[]
ifeval::["{build-type}" == "srfa"]
Clusters EKS podem ser criados ou importados com Terraform.
endif::[]
