= Lançando Kubernetes com {rancher-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-25
:page-revdate: {revdate}
:community-path: how-to-guides/new-user-guides/launch-kubernetes-with-rancher/index.adoc 
:product-path: cluster-deployment/launch-kubernetes-with-rancher.adoc
ifeval::["{build-type}" != "community"]
:url-rke2-introduction: https://documentation.suse.com/cloudnative/rke2/latest/en/introduction.html
:url-k3s: https://documentation.suse.com/cloudnative/k3s
:url-rke2-requirements: https://documentation.suse.com/cloudnative/rke2/latest/en/install/requirements.html
:xref-clean-cluster-nodes: xref:cluster-admin/manage-clusters/clean-cluster-nodes.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:url-k3s: https://docs.k3s.io/
:url-rke2-introduction: https://docs.rke2.io/
:url-rke2-requirements: https://docs.rke2.io/install/requirements
:xref-clean-cluster-nodes: xref:how-to-guides/new-user-guides/manage-clusters/clean-cluster-nodes.adoc
endif::[]

O Rancher permite que você inicie um cluster Kubernetes em diferentes tipos de nós, incluindo servidores bare metal, máquinas virtuais locais e máquinas virtuais de um provedor de infraestrutura. Ao implantar o Kubernetes nesses nós, o Rancher oferece a opção de usar {url-rke2-introduction}[RKE2] ou {url-k3s}[K3s].

O Rancher pode instalar o Kubernetes em nós existentes ou pode provisionar dinamicamente nós em um provedor de infraestrutura e instalar o Kubernetes neles.

O Rancher também pode criar pools de máquinas. Um benefício de instalar o Kubernetes em pools de máquinas hospedados por um provedor de infraestrutura é que, se um nó perder conectividade com o cluster, o Rancher pode automaticamente criar outro nó para se juntar ao cluster, garantindo que a contagem do pool de máquinas esteja conforme o esperado.

[#__rke2_product_name]
== {rke2-product-name}

O Rancher v2.6 introduziu o provisionamento para {url-rke2-introduction}[RKE2] clusters diretamente da interface do usuário do Rancher. RKE2, também conhecido como RKE Government, é uma distribuição Kubernetes totalmente compatível que se concentra na segurança e conformidade nos EUA. Governo Federal dos EUA. No Rancher v.2.6.4 e versões anteriores, o provisionamento do RKE2 estava em pré-visualização técnica.

Observe que no Rancher v2.6.5, o provisionamento do RKE2 se tornou GA.

[#_requirements]
=== Requisitos

Se você usar o RKE2 para configurar um cluster, seus nós devem atender aos {url-rke2-requirements}[requisitos] para nós em clusters de usuários downstream.

[#_launching_kubernetes_on_new_nodes_in_an_infrastructure_provider]
=== Lançando Kubernetes em Novos Nós em um Provedor de Infraestrutura

O provisionamento do RKE2 é construído sobre uma nova estrutura de provisionamento que aproveita o projeto upstream https://github.com/kubernetes-sigs/cluster-api[Cluster API (CAPI)]. Com essa nova estrutura de provisionamento, você pode:

* Provisionar clusters RKE2 em qualquer provedor para o qual o Rancher tenha um driver de nó.
* Configurar completamente clusters RKE2 dentro do Rancher.
* Escolher opções de CNI Calico, Cilium e Multus, além de Canal.

Quando você faz alterações na configuração do seu cluster no RKE2, isso pode resultar no reprovisionamento de nós. Isso é controlado pelos controladores do CAPI e não pelo próprio Rancher. Observe que para nós etcd, o mesmo comportamento não se aplica.

Uma alteração de configuração de exemplo que pode causar o comportamento descrito é ao editar um cluster e habilitar o dreno antes da exclusão. Nesse cenário, os nós existentes do plano de controle e os nós de trabalho são excluídos e novos nós são criados.

O provisionamento do RKE2 também inclui a instalação do RKE2 em clusters com nós Windows.

Os recursos do Windows para o RKE2 incluem:

* O Windows suporta o driver de nó vSphere
* Calico e Flannel CNI para clusters personalizados RKE2 no Windows
* Isolamento de Rede do Projeto (PNI) para Calico
* Contêineres Windows com RKE2 alimentados pelo containerd
* Provisionamento de clusters RKE2 no Windows através do Terraform
* Provisionamento de clusters personalizados RKE2 no Windows diretamente pela interface do Rancher

O suporte do Windows para clusters personalizados RKE2 requer a escolha do Calico como CNI.

[#_launching_kubernetes_on_existing_custom_nodes]
=== Iniciando o Kubernetes em Nós Personalizados Existentes

O provisionamento do RKE2 também permite que você instale clusters personalizados em VMs ou nós bare-metal previamente provisionados.

Se você quiser reutilizar um nó de um cluster personalizado anterior, {xref-clean-cluster-nodes}#_cleaning_up_nodes[clean the node] antes de usá-lo em um cluster novamente. Se você reutilizar um nó que não foi limpo, a provisão do cluster pode falhar.

[#_programmatically_creating_rke2_product_name_clusters]
=== Criando programaticamente clusters {rke2-product-name}

A maneira mais comum de implantar clusters RKE2 programaticamente através do Rancher é usando o https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2[Rancher2 Terraform provider].
