= 在桌面上使用 Rancher Desktop 的 Kubernetes
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/rancher-desktop.adoc 
:product-path: integrations/rancher-desktop.adoc

Rancher Desktop 将开发和测试云原生应用所需的基本工具打包在一起，方便您从桌面进行操作。

如果您在本地机器上开发面向云环境的应用程序，通常需要进行大量准备工作。您需要选择一个容器运行时，安装 Kubernetes 和常用工具，并可能需要设置虚拟机。单独安装组件并使其协同工作可能是一个耗时的过程。

为了减少复杂性，Rancher Desktop 为团队提供以下关键功能：

* 在 macOS、Linux 和 Windows 操作系统上简单易用的安装。
* K3s，一个现成的轻量级 Kubernetes 发行版。
* 轻松切换 Kubernetes 版本的能力。
* 由 Rancher 提供支持的基于 GUI 的集群仪表板，用于探索您的本地群集。
* 自由选择您的容器引擎：dockerd (moby) 或 containerd。
* 偏好设置以配置应用程序以满足您的需求。
* 为您的容器、基于 Kubernetes 的开发和操作工作流所需的工具打包在一起。
* 定期更新以保持打包工具的最新状态。
* 与流行工具/IDE 的集成，包括 VS Code 和 Skaffold。
* 镜像和注册表访问控制。
* 支持 Docker 扩展。

访问 https://rancherdesktop.io[Rancher Desktop] 网站并阅读 https://docs.rancherdesktop.io/[文档] 以了解更多信息。

要在您的机器上安装 Rancher Desktop，请参考 https://docs.rancherdesktop.io/getting-started/installation[安装指南]。

[#_trying_rancher_on_rancher_desktop]
== 在 Rancher Desktop 上尝试 Rancher

Rancher Desktop 提供了您所需的设置和工具，以便轻松尝试基于 Helm 的容器化应用程序。借助 Rancher Desktop，您可以开始使用 Rancher Kubernetes 管理平台，只需参照这个 https://docs.rancherdesktop.io/how-to-guides/rancher-on-rancher-desktop[how-to 指南]。
