= Installation und Konfiguration von kubectl
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-18
:page-revdate: {revdate}
:community-path: faq/install-and-configure-kubectl.adoc 
:product-path: faq/install-and-configure-kubectl.adoc

`kubectl` ist eine Kommandozeilenschnittstelle zum Ausführen von Befehlen gegen Kubernetes-Cluster. Es ist für viele Wartungs- und Verwaltungsaufgaben in Rancher 2.x erforderlich.

[#_installation]
== Installation

Siehe https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl Installation] für die Installation auf Ihrem Betriebssystem.

[#_configuration]
== Konfiguration

Wenn Sie einen Kubernetes-Cluster mit RKE2/K3s erstellen, wird die Kubeconfig-Datei je nach gewählter Distribution unter `/etc/rancher/rke2/rke2.yaml` oder `/etc/rancher/k3s/k3s.yaml` gespeichert. Diese Dateien werden verwendet, um den Zugriff auf den Kubernetes-Cluster zu konfigurieren.

Testen Sie Ihre Konnektivität mit `kubectl` und sehen Sie, ob Sie die Liste der Knoten zurückbekommen.

----
kubectl get nodes
 NAME                          STATUS    ROLES                      AGE       VERSION
165.227.114.63                Ready     controlplane,etcd,worker   11m       v1.10.1
165.227.116.167               Ready     controlplane,etcd,worker   11m       v1.10.1
165.227.127.226               Ready     controlplane,etcd,worker   11m       v1.10.1
----
