= {longhorn-product-name}
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-08-05
:page-revdate: {revdate}
:community-path: integrations-in-rancher/longhorn/index.adoc 
:product-path: integrations/longhorn/longhorn.adoc

Longhorn é um projeto oficial da https://cncf.io/[Cloud Native Computing Foundation (CNCF)] que oferece uma poderosa plataforma de armazenamento em blocos distribuído nativo de nuvem para Kubernetes que pode ser executada em qualquer lugar. Quando combinado com o Rancher, o Longhorn torna fácil, rápido e confiável a implantação de armazenamento em blocos persistente altamente disponível em seu ambiente Kubernetes.

[#__longhorn_product_name_with_rancher]
== {longhorn-product-name} com o Rancher

Com o Rancher Prime e o Longhorn, os usuários podem implantar facilmente com 1 clique através do catálogo do Rancher e realizar o gerenciamento do ciclo de vida para clusters gerenciados; permitindo ao usuário instalar e fazer upgrade, juntamente com a operação de drenagem para operações suaves. O Longhorn com o Rancher também oferece suporte a clusters mistos com Windows, imagens hospedadas pelo Rancher, acesso ao proxy da UI através do Rancher e monitoramento do Rancher com métricas do Longhorn.
