= Allocations d'UC et de mémoire
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/cpu-and-memory-allocations.adoc 
:product-path: observability/istio/cpu-and-memory-allocations.adoc
ifeval::["{build-type}" != "community"]
:xref-istio-config: xref:observability/istio/configuration/configuration.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] a cessé la prise en charge depuis Rancher v2.12.0{nbsp}; tournez-vous vers l'https://apps.rancher.io[SUSE Application Collection] d'Istio pour une sécurité renforcée (incluse dans les abonnements SUSE Rancher Prime).
Des informations détaillées peuvent être trouvées dans https://forums.suse.com/t/deprecation-of-rancher-istio/45043[cette annonce].
====

Cette section décrit les ressources informatiques minimales recommandées pour les composants Istio dans un cluster.

Les allocations d'UC et de mémoire pour chaque composant sont <<_configuring_resource_allocations,configurables.>>

Avant d'activer Istio, nous vous recommandons de confirmer que vos nœuds de travail Rancher disposent de suffisamment d'UC et de mémoire pour exécuter tous les composants d'Istio.

[TIP]
====

Dans les déploiements plus importants, il est fortement conseillé que l'infrastructure soit placée sur des nœuds dédiés dans le cluster en ajoutant un sélecteur de nœud pour chaque composant Istio.
====


Le tableau ci-dessous présente un résumé des demandes et limites de ressources minimales recommandées pour l'UC et la mémoire de chaque composant noyau d'Istio.

Dans Kubernetes, la demande de ressources indique que la charge de travail ne sera pas déployée sur un nœud à moins que le nœud dispose d'au moins la quantité spécifiée de mémoire et d'UC disponibles. Si la charge de travail dépasse la limite d'UC ou de mémoire, elle peut être terminée ou évincée du nœud. Pour plus d'informations sur la gestion des limites de ressources pour les conteneurs, consultez la https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/[documentation Kubernetes.]

|===
| Workload | UC - Demande | Mémoire - Demande | UC - Limite | Mémoire - Limite

| passerelle d'entrée
| 100m
| 128mi
| 2000m
| 1024mi

| passerelle de sortie
| 100m
| 128mi
| 2000m
| 1024mi

| istiod
| 500m
| 2048mi
| Un nombre illimité
| Un nombre illimité

| proxy
| 10m
| 10mi
| 2000m
| 1024mi

| *Totaux:*
| *710m*
| *2314Mi*
| *6000m*
| *3072Mi*
|===

[#_configuring_resource_allocations]
== Configuration des allocations de ressources

Vous pouvez configurer individuellement l'allocation de ressources pour chaque type de composant Istio. Cette section inclut les allocations de ressources par défaut pour chaque composant.

Pour faciliter la planification des charges de travail sur un nœud, un administrateur de cluster peut réduire les demandes de ressources d'UC et de mémoire pour le composant. Cependant, les allocations d'UC et de mémoire par défaut sont le minimum que nous recommandons.

Vous pouvez trouver plus d'informations sur la configuration d'Istio dans la https://istio.io/[documentation officielle d'Istio].

Pour configurer les ressources allouées à un composant Istio,

. Cliquez sur *☰ > Gestion des clusters*.
. Allez au cluster que vous avez créé et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur *Applis*.
. Cliquez sur *Applis installées*.
. Allez à l'espace de noms `istio-system`. Dans l'une des charges de travail Istio, comme `rancher-istio`, cliquez sur *⋮ > Modifier/Mettre à niveau*.
. Cliquez sur *Mettre à niveau* pour modifier les composants de base via des changements dans le values.yaml ou ajouter un {xref-istio-config}#_fichier_overlay[fichier overlay]. Pour plus d'informations sur la modification du fichier overlay, consultez <<_editing_the_overlay_file,cette section.>>
. Modifiez les allocations d'UC ou de mémoire, les nœuds où chaque composant sera programmé, ou les tolérances des nœuds.
. Cliquez sur *Mettre à niveau* pour déployer les changements.

*Résultat :* Les allocations de ressources pour les composants Istio ont été mises à jour.

[#_editing_the_overlay_file]
=== Modification du fichier overlay

Le fichier overlay peut contenir n'importe quelle valeur dans le https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec[spécification de l'Opérateur Istio.] Le fichier overlay inclus avec l'application Istio n'est qu'un exemple d'une configuration potentielle du fichier overlay.

Tant que le fichier contient `kind: IstioOperator` et que les options YAML sont valides, le fichier peut être utilisé comme overlay.

Dans le fichier overlay d'exemple fourni avec l'application Istio, la section suivante vous permet de modifier les ressources Kubernetes{nbsp}:

----
#      k8s:
#        resources:
#          requests:
#            cpu: 200m
----
