= Istio
ifeval::["{build-type}" != "srfa"]
:page-languages: [en, zh]
endif::[]
:revdate: 2025-10-01
:page-revdate: {revdate}
:community-path: integrations-in-rancher/istio/index.adoc 
:product-path: observability/istio/istio.adoc
ifeval::["{build-type}" != "community"]
:xref-monitoring-and-dashboards: xref:observability/monitoring-and-dashboards/monitoring-and-dashboards.adoc
:xref-selectors-and-scrape-configurations: xref:observability/istio/configuration/selectors-and-scrape-configurations.adoc
:xref-istio-guides: xref:observability/istio/guides/guides.adoc
:xref-istio-cpu-memory-allocations: xref:observability/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:observability/istio/configuration/install-istio-on-rke2-cluster.adoc
:xref-istio-config: xref:observability/istio/configuration/configuration.adoc
:xref-istio-disable: xref:observability/istio/disable-istio.adoc
:xref-istio-rbac: xref:observability/istio/rbac.adoc
endif::[]
ifeval::["{build-type}" == "community"]
:xref-monitoring-and-dashboards: xref:integrations-in-rancher/monitoring-and-alerting/index.adoc
:xref-selectors-and-scrape-configurations: xref:integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations.adoc
:xref-istio-guides: xref:how-to-guides/advanced-user-guides/istio-setup-guide/index.adoc
:xref-istio-cpu-memory-allocations: xref:integrations-in-rancher/istio/cpu-and-memory-allocations.adoc
:xref-istio-on-rke2: xref:integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.adoc
:xref-istio-config: xref:integrations-in-rancher/istio/configuration-options/index.adoc
:xref-istio-disable: xref:integrations-in-rancher/istio/disable-istio.adoc
:xref-istio-rbac: xref:integrations-in-rancher/istio/rbac-for-istio.adoc
endif::[]

[WARNING]
====
https://github.com/rancher/charts/tree/release-v2.11/charts/rancher-istio[Rancher-Istio] a cessé la prise en charge depuis Rancher v2.12.0{nbsp}; tournez-vous vers l'https://apps.rancher.io[SUSE Application Collection] d'Istio pour une sécurité renforcée (incluse dans les abonnements SUSE Rancher Prime).
Des informations détaillées peuvent être trouvées dans https://forums.suse.com/t/deprecation-of-rancher-istio/45043[cette annonce].
====

https://istio.io/[Istio] est un outil open-source qui facilite aux équipes DevOps l'observation, la sécurisation, le contrôle et le dépannage du trafic au sein d'un réseau complexe de microservices.

À mesure qu'un réseau de microservices évolue et se développe, les interactions entre eux peuvent devenir de plus en plus difficiles à gérer et à comprendre. Dans une telle situation, il est utile d'avoir un maillage de services comme couche d'infrastructure séparée. Le maillage de services d'Istio vous permet de manipuler le trafic entre les microservices sans modifier directement les microservices.

Notre intégration d'Istio est conçue de manière à ce qu'un opérateur Rancher, tel qu'un administrateur ou un propriétaire de cluster, puisse fournir Istio à une équipe de développeurs. Les développeurs peuvent ensuite utiliser Istio pour appliquer des politiques de sécurité, résoudre des problèmes ou gérer le trafic pour des déploiements green/blue, des déploiements canary ou des tests A/B.

Ce maillage de services de base fournit des fonctionnalités qui incluent, mais ne se limitent pas à, ce qui suit{nbsp}:

* *Gestion du Trafic* telle que le routage d'entrée et de sortie, la coupure de circuit, le mirroring.
* *Sécurité* avec des ressources pour authentifier et autoriser le trafic et les utilisateurs, mTLS inclus.
* *Observabilité* des journaux, des métriques et des flux de trafic distribués.

Après {xref-istio-guides}[configuration d'istio], vous pouvez tirer parti des fonctionnalités du plan de contrôle d'Istio via l'interface utilisateur de Rancher, `kubectl`, ou `istioctl`.

Istio doit être configuré par un `cluster-admin` avant de pouvoir être utilisé dans un projet.

[#_whats_new_in_rancher_v2_5]
== Quoi de neuf dans Rancher v2.5

L'architecture globale d'Istio a été simplifiée. Un seul composant, Istiod, a été créé en combinant Pilot, Citadel, Galley et l'injecteur de sidecar. La fonctionnalité de l'Agent de nœud a également été fusionnée dans istio-agent.

Les addons qui étaient auparavant installés par Istio (cert-manager, Grafana, Jaeger, Kiali, Prometheus, Zipkin) devront maintenant être installés séparément. Istio prendra en charge l'installation d'intégrations provenant du projet Istio et maintiendra la compatibilité avec celles qui ne le sont pas.

Une intégration Prometheus sera toujours disponible via une installation de {xref-monitoring-and-dashboards}[Rancher Monitoring], ou en installant votre propre opérateur Prometheus. Le graphique Istio de Rancher installera également Kiali par défaut pour vous assurer d'avoir une vue d'ensemble de vos microservices dès le départ.

Istio a migré de Helm comme moyen d'installer Istio et propose désormais une installation via le binaire istioctl ou l'opérateur Istio. Pour garantir la plus facile interaction avec Istio, l'Istio de Rancher maintiendra un graphique Helm qui utilise le binaire istioctl pour gérer votre installation d'Istio.

Ce graphique Helm sera disponible via les Applications et le Marché dans l'interface utilisateur. Un utilisateur ayant accès au catalogue des graphiques de Rancher devra configurer Istio avant qu'il puisse être utilisé dans le projet.

[#_tools_bundled_with_istio]
== Outils inclus avec Istio

Notre installateur https://istio.io/[Istio] enveloppe les commandes du binaire istioctl dans un graphique Helm pratique, y compris une option de fichier de superposition pour permettre une personnalisation complexe.

Il comprend également ce qui suit{nbsp}:

[#_kiali]
=== Kiali

https://kiali.io/[Kiali] est un outil de visualisation complet utilisé pour représenter le flux de trafic à travers le maillage de services. Il vous permet de voir comment ils sont connectés, y compris les taux de trafic et les latences entre eux.

Vous pouvez vérifier la santé du maillage de services ou examiner en détail les requêtes entrantes et sortantes pour un composant unique.

[NOTE]
====
Pour les installations d'Istio `103.1.0+up1.19.6` et ultérieures, Kiali utilise une valeur de token pour sa stratégie d'authentification. Le nom du compte de service Kiali dans Rancher est `kiali`. Utilisez ce nom si vous écrivez des commandes qui nécessitent que vous saisissiez le nom du compte de service Kiali (par exemple, si vous essayez de générer ou de récupérer un token de session). Pour plus d'informations, consultez le https://kiali.io/docs/faq/authentication/[FAQ sur l'authentification par token Kiali].
====


[#_jaeger]
=== Jaeger

Notre installateur Istio comprend un démarrage rapide, une installation tout-en-un de https://www.jaegertracing.io/[Jaeger,], un outil utilisé pour le traçage des systèmes distribués.

Notez que ce n'est pas un déploiement qualifié pour la production de Jaeger. Ce déploiement utilise un composant de stockage en mémoire, tandis qu'un composant de stockage persistant est recommandé pour la production. Pour plus d'informations sur la stratégie de déploiement dont vous pourriez avoir besoin, référez-vous à la https://www.jaegertracing.io/docs/1.65/operator/#production-strategy[documentation de Jaeger.]

[#_prerequisites]
== Conditions préalables

Avant d'activer Istio, nous vous recommandons de confirmer que vos nœuds de travail Rancher disposent de suffisamment {xref-istio-cpu-memory-allocations}[d'UC et de mémoire] pour exécuter tous les composants d'Istio.

Si vous installez Istio sur un cluster RKE2, des étapes supplémentaires sont nécessaires. Pour plus de détails, voir <<_additional_steps_for_installing_istio_on_an_rke2_cluster,cette section.>>

[#_setup_guide]
== Guide d'installation 

Référez-vous au {xref-istio-guides}[guide de configuration] pour des instructions sur la façon de configurer Istio et de l'utiliser dans un projet.

[#_remove_istio]
== Supprimer Istio

Pour supprimer les composants d'Istio d'un cluster, d'un espace de noms ou d'une charge de travail, référez-vous à la section sur {xref-istio-disable}[la désinstallation d'Istio.]

[#_accessing_visualizations]
== Accéder aux visualisations

____
Par défaut, seuls les administrateurs de cluster ont accès à Kiali. Pour des instructions sur la façon de permettre aux rôles d'administrateur, d'édition ou de visualisation d'y accéder, voir {xref-istio-rbac}[cette section.]
____

[NOTE]
====
Pour les installations d'Istio version `103.1.0+up1.19.6` et ultérieures, Kiali utilise une valeur de token pour sa stratégie d'authentification. Le nom du compte de service Kiali dans Rancher est `kiali`. Utilisez ce nom si vous écrivez des commandes qui nécessitent que vous saisissiez le nom du compte de service Kiali (par exemple, si vous essayez de générer ou de récupérer un token de session). Pour plus d'informations, consultez le https://kiali.io/docs/faq/authentication/[FAQ sur l'authentification par token Kiali].
====


Après qu'Istio soit configuré dans un cluster, Grafana, Prometheus et Kiali sont disponibles dans l'interface utilisateur de Rancher.

Pour accéder aux visualisations de Grafana et Prometheus,

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, allez au cluster où vous souhaitez voir les visualisations et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur *Surveillance*.
. Cliquez sur *Grafana* ou sur l'un des autres tableaux de bord.

Pour accéder à la visualisation Kiali,

. Dans le coin supérieur gauche, cliquez sur *☰ > Gestion des clusters*.
. Sur la page *Clusters*, allez au cluster où vous souhaitez voir Kiali et cliquez sur *Explorer*.
. Dans la barre de navigation à gauche, cliquez sur *Istio*.
. Click *Kiali*. Ici, vous pouvez accéder à l'onglet *Graphique de trafic* ou à l'onglet *Métriques de trafic* pour voir les visualisations et les métriques réseau.

Par défaut, tous les espaces de noms seront pris en compte par Prometheus et rendront les données disponibles pour les graphiques Kiali. Référez-vous à {xref-selectors-and-scrape-configurations}[la configuration du sélecteur/de la collecte] si vous souhaitez utiliser une configuration différente pour la collecte de données de Prometheus.

Votre accès aux visualisations dépend de votre rôle. Grafana et Prometheus ne sont disponibles que pour les rôles `cluster-admin`. L'interface utilisateur de Kiali est disponible uniquement pour `cluster-admin` par défaut, mais `cluster-admin` peut permettre à d'autres rôles d'y accéder en modifiant le fichier values.yaml d'Istio.

[#_architecture]
== Architecture

Istio installe un maillage de services qui utilise des proxys sidecar https://www.envoyproxy.io[Envoy] pour intercepter le trafic vers chaque charge de travail. Ces sidecars interceptent et gèrent la communication de service à service, permettant une observation et un contrôle précis du trafic au sein du cluster.

Seules les charges de travail ayant le sidecar Istio injecté peuvent être suivies et contrôlées par Istio.

Lorsqu'un espace de noms a Istio activé, les nouvelles charges de travail déployées dans l'espace de noms auront automatiquement le sidecar Istio. Vous devez activer manuellement Istio dans les charges de travail existantes.

Pour plus d'informations sur le sidecar Istio, consultez la https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/[documentation sur l'injection de sidecar Istio] et pour plus d'informations sur l'architecture d'Istio, consultez la https://istio.io/latest/docs/ops/deployment/architecture/[documentation sur l'architecture d'Istio].

[#_multiple_ingresses]
=== Multiples Ingresses

Par défaut, chaque cluster provisionné par Rancher dispose d'un contrôleur d'ingress NGINX permettant le trafic vers le cluster. Istio installe également une passerelle d'ingress par défaut dans l'espace de noms `istio-system`.  Le résultat est que votre cluster aura deux ingress dans votre cluster.

image::istio-ingress.svg[Dans un cluster activé par Istio, you can have two ingresses: the default Nginx ingress, and the default Istio controller.]

Des passerelles d'Ingress Istio supplémentaires peuvent être activées via le {xref-istio-config}#_overlay_file[fichier overlay].

[#_egress_support]
=== Support Egress

Par défaut, la passerelle Egress est désactivée, mais peut être activée lors de l'installation ou de la mise à niveau via le values.yaml ou via le {xref-istio-config}#_overlay_file[fichier overlay].

[#_additional_steps_for_installing_istio_on_an_rke2_cluster]
== Étapes supplémentaires pour installer Istio sur un cluster {rke2-product-name}.

Pour installer Istio sur un cluster RKE2, suivez les étapes dans {xref-istio-on-rke2}[cette section].

[#_upgrading_istio_in_an_air_gapped_environment]
== Mise à niveau d'Istio dans un environnement isolé physiquement.

La politique de sécurité des pods Istio est maintenant activée par défaut. Une nouvelle valeur, `installer.releaseMirror.enabled`, a été ajoutée au chart rancher-istio pour activer et désactiver le serveur qui prend en charge les mises à niveau isolées physiquement. Notez que `installer.releaseMirror.enabled` est défini sur `false` par défaut. Vous pouvez définir cette valeur selon vos besoins lors de l'installation ou de la mise à niveau. Suivez la procédure ci-dessous :

. Provisionnez une instance Rancher isolée physiquement et un cluster personnalisé isolé physiquement dans l'interface utilisateur de Rancher.
. Installez Monitoring dans le cluster{nbsp}: *Cluster Explorer \-> Apps & Marketplace \-> Charts \-> Monitoring*.
. Tirez toutes les images requises pour Istio dans le registre privé que vous utiliserez dans l'environnement isolé physiquement.
. Installez Istio dans le cluster{nbsp}: *Cluster Explorer \-> Apps & Marketplace \-> Charts \-> Istio*.

[NOTE]
====

Vous pouvez activer https://www.jaegertracing.io/[Jaeger] et https://kiali.io/[Kiali] lors d'une nouvelle installation d'Istio. Pour garantir que Jaeger et Kiali fonctionnent, définissez `installer.releaseMirror.enabled` sur `true` dans `values.yaml` lors de l'installation.
====


. Mettez à niveau l'installation d'Istio.

[CAUTION]
====

Si ce n'est pas déjà fait, définissez `installer.releaseMirror.enabled=true` pour mettre à niveau Istio.
====

